### ISSUE TITLE
Properly fix `DisplayMetrics.DENSITY_DEVICE_STABLE` mapping

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1084]
Commit ef770245 manually removed the `DisplayMetrics.DENSITY_DEVICE_STABLE` enum binding, added by commit 50c0c15. This fix is incomplete/incorrect: the problem is that the underlying tooling in `build-tools/enumification-helpers` is doing "something" wrong, which means this invalid mapping will be reintroduced in the future.

We need to fix `build-tools/enumification-helpers` so that `DisplayMetrics.DENSITY_DEVICE_STABLE` isn't reintroduced for enum mapping.

**Comment by atsushieno** [comment]
And someone needs to investigate why the PR build was green, which is why I think it's fine and it's merged.

**Comment by atsushieno** [comment]
enumification-helpers is fixed, and we have already discovered that api-compatibility didn't run inter-api-diff and therefore this kind of failure didn't get detected. And there is already 6dfba92 so nothing needs to be tracked from this issue anymore. Closing.
