### ISSUE TITLE
Xamarin Android - JsonSerializationException: Error getting value from '[FIELD]' on '[METHOD]'

### ISSUE THREAD

**Issue by JamesNK** [xamarin/xamarin-android#1113]
Copied from https://github.com/JamesNK/Newtonsoft.Json/issues/1537 @lorisgiglio

---

### Environment

Visual Studio 2015
Xamarin 4.8.0.754
Xamarin Android 8.1.0.13
Xamarin Android SDK 8.1.1.1
Newtonsoft.Json 10.0.3

### Source/destination types

        public class c1
        {
            public string field1 { get; set; }
        }

### Expected behavior

It has to serialize the simple object

### Actual behavior

12-13 10:49:28.412  9122  9122 I MonoDroid: UNHANDLED EXCEPTION:
12-13 10:49:28.419  9122  9122 I MonoDroid: Newtonsoft.Json.JsonSerializationException: Error getting value from 'field1' on 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'. ---> System.MissingMethodException: **Method 'System.Reflection.Emit.DynamicMethod.set_ProfileAPICheck' not found.**
12-13 10:49:28.419  9122  9122 I MonoDroid:   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile (System.Linq.Expressions.LambdaExpression lambda, System.Runtime.CompilerServices.DebugInfoGenerator debugInfoGenerator) [0x0000f] in <bfedf5c3cdd04d14a8bd94e62f153ad8>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at System.Linq.Expressions.LambdaExpression.Compile () [0x00000] in <bfedf5c3cdd04d14a8bd94e62f153ad8>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet[T] (System.Reflection.PropertyInfo propertyInfo) [0x0007c] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateGet[T] (System.Reflection.MemberInfo memberInfo) [0x0000a] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue (System.Object target) [0x0000e] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:    --- End of inner exception stack trace ---
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue (System.Object target) [0x00054] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContainerContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonContract& memberContract, System.Object& memberValue) [0x00066] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00253] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00007] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0

### Steps to reproduce

        public static string GetData(string s1)
        {
           if (string.IsNullOrWhiteSpace(s1)) return null;

            c1 c = new c1();

            c1.field1 = s1;

            string res = JsonConvert.SerializeObject(c1);
            
            return res;
       }

**Comment by radekdoulik** [comment]
I am unable to reproduce it. Tried it with XA Version: 8.1.0.22

If it still happens for you, please attach whole XA project, which reproduces the issue.

**Comment by lorisgiglio** [comment]
Hi, it's a big xamarin project with many references and I can't attach all the project.
I've same problem on Android 5.1 and Android 7.1 devices.

The problems seems to depend by dynamic method creation during NewtonSoft serialization but I don't know how it happens and why.

It happens in Release mode and not in Debug mode compilation. I saw that loaded assembly in **debug** mode are :

Loaded assembly: Microsoft.CSharp.dll [External]
Loaded assembly: System.ComponentModel.TypeConverter.dll [External]
**Loaded assembly: Anonymously Hosted DynamicMethods Assembly [External]**
Loaded assembly: System.Reflection.Primitives.dll [External]
Loaded assembly: System.Net.Http.dll [External]

My project can't compile in Release mode with Linking "SDK Assembly Only" but only with "NONE".

I attach all compile detailed debug information if it can help.
[DEBUG_MODE.txt](https://github.com/xamarin/xamarin-android/files/1621795/DEBUG_MODE.txt)
[RELEASE_MODE_LINKING_NONE.txt](https://github.com/xamarin/xamarin-android/files/1621796/RELEASE_MODE_LINKING_NONE.txt)
[RELEASE_MODE_LINKING_SDKASSEMBLYONLY.txt](https://github.com/xamarin/xamarin-android/files/1621797/RELEASE_MODE_LINKING_SDKASSEMBLYONLY.txt)

**Comment by jonpryor** [comment]
From [RELEASE_MODE_LINKING_SDKASSEMBLYONLY.txt](https://github.com/xamarin/xamarin-android/files/1621797/RELEASE_MODE_LINKING_SDKASSEMBLYONLY.txt)

```
error MSB4018: errore imprevisto dell'attivit‡ "LinkAssemblies".
error MSB4018: System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
error MSB4018:    in Mono.Linker.TypeReferenceExtensions.<GetMethods>d__4.MoveNext()
error MSB4018:    in Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method)
error MSB4018:    in Mono.Linker.Steps.TypeMapStep.GetBaseMethodInTypeHierarchy(TypeDefinition type, MethodDefinition method)
error MSB4018:    in Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type)
error MSB4018:    in Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
error MSB4018:    in Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
error MSB4018:    in Mono.Linker.Steps.BaseStep.Process(LinkContext context)
error MSB4018:    in Mono.Linker.Pipeline.Process(LinkContext context)
error MSB4018:    in MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
error MSB4018:    in Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
error MSB4018:    in Xamarin.Android.Tasks.LinkAssemblies.Execute()
error MSB4018:    in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    in Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

I suspect that you're hitting https://github.com/xamarin/xamarin-macios/issues/3215, the [fix for which](https://github.com/mono/linker/commit/c62335c350f3902ff0459112f7efc8b926f4f15d) involves a null check within `TypeReferenceExtensions.GetMethods()`, so I *think* that this is fixed in:

* https://github.com/mono/linker/commit/c62335c350f3902ff0459112f7efc8b926f4f15d (actual fix)
* https://github.com/mono/mono/commit/3c3e692887af323549aca938dd6d3dca7a9a6cc8 (integrate above fix into mono)
* https://github.com/xamarin/xamarin-android/commit/a82c2860bded546838db7bebdf7062d5a42d7e65 (integrate mono fix into xamarin-android)

The fix has not yet been integrated on xamarin-android/master; the last URL above is on xamarin-android/d15-6, which is for Xamarin.Android 8.2 (currently in beta).

However, I don't know when that fix will actually be released.
