### ISSUE TITLE
android-toolchain needs to sensibly reset SDK & NDK

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1119]
Context: https://github.com/xamarin/xamarin-android/pull/1112#issuecomment-352088555

The Android SDK & NDK install is "forward only" (see b28856f).

### Steps to Reproduce

1. Create a new branch, and on that branch bump the Android NDK dependencies to something "newer".
2. Build the branch from (1), thus installing the "newer" NDK into `$HOME/android-toolchain/ndk`
3. Checkout a *different* branch -- one that uses an "older" NDK -- and rebuild.

### Expected Behavior

The Android NDK should be *re-extracted*, so that `$HOME/android-toolchain/ndk` matches what the current branch requires.

### Actual Behavior

The Android NDK is not touched at all.

**Comment by pjcollins** [comment]
I think this was resolved as part of https://github.com/xamarin/xamarin-android/pull/3051 and https://github.com/xamarin/xamarin-android/pull/3213
