### ISSUE TITLE
New APT0000 msbuild errors are being reported from aapt output parsing

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1134]
This was previously discussed, however there still appear to be some corner cases that weren't addressed by the latest relevant change in commit https://github.com/xamarin/xamarin-android/commit/2135856e.

### Steps to Reproduce

1. Build tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj with msbuild.

### Expected Behavior
Build should succeed without incorrectly reporting aapt warnings as msbuild errors.

### Actual Behavior
Build fails with the following:
```
Executing package -f -m -M /Users/xamarinqa/agent/_work/_temp/r0o3reuu.zcl/manifest/AndroidManifest.xml -J /Users/xamarinqa/agent/_work/_temp/r0o3reuu.zcl --custom-package xamarin.android.jcwgen_tests -F /Users/xamarinqa/agent/_work/_temp/r0o3reuu.zcl/resources.apk.bk -S obj/Release/res/ -S /Users/xamarinqa/agent/_work/r5/a/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/obj/Release/lp/3/jl/res -S /Users/xamarinqa/agent/_work/r5/a/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/obj/Release/lp/5/jl/res -S /Users/xamarinqa/agent/_work/r5/a/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/obj/Release/resourcecache/6ECC701C56CAE8576696DE7B3605BB4A/res -j obj/Release/lp/4/jl/__reference__empty-1.jar -j obj/Release/lp/4/jl/__reference__empty-2.jar -j obj/Release/lp/4/jl/xamarin-test.jar -I /Users/xamarinqa/Library/Developer/Xamarin/android-sdk-macosx/platforms/android-10/android.jar --auto-add-overlay --max-res-version 10 (TaskId:1230)
aapt : error APT0000: max res 10, skipping values-sw720dp-land-v13 "max res 10, skipping values-sw720dp-land-v13". [/Users/xamarinqa/agent/_work/r5/a/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
Done executing task "Aapt" -- FAILED. (TaskId:1230)
```

### Version Information
XA 8.2.0.0.

### Log File
http://xqa.blob.core.windows.net/gist/log-f69375a71be042929c3d54c25ecfd34b.txt

**Comment by jonpryor** [comment]
Cherry-picked to d15-6 as: 23c58018406741f98c9b19558fc3816c60857cc9

**Comment by pjcollins** [comment]
I'm still able to reproduce this with a handful of projects, including `tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj`.

### Version Info
monodroid/d15-6/b6dfc0ad4 (Xamarin.Android 8.2.0.3)

**Comment by dellis1972** [comment]
@pjcollins can you post log output please? I can't seem to repo locally on XA master.

**Comment by pjcollins** [comment]
Here are a few examples from mac and windows:

http://xqa.blob.core.windows.net/gist/log-6a63d8fe578341bf83a6d73138f4ea60.txt
http://xqa.blob.core.windows.net/gist/log-ee13ba5933e84661b2f7ebe7ec5ba91c.txt
http://xqa.blob.core.windows.net/gist/log-2032ff4f710d4790acb0b8ac08d49e26.txt

**Comment by dellis1972** [comment]
@pjcollins I just build d15-6 from scratch  here and I can't repo... `tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj` is building fine..  That said I'm not even seeing the `max res 10, skipping values-sw720dp-land-v13` as a warning.

**Comment by dellis1972** [comment]
@pjcollins what tools versions are you building against?

**Comment by pjcollins** [comment]
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.0
SDK Build Tools Version: 27.0.2

A few MvvmCross samples also encounter this issue, you can find one here:
https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Playground/Playground.Droid

**Comment by dellis1972** [comment]
right ok. Repo'd the issue with MvvmCross. Will start looking at a fix

**Comment by dellis1972** [comment]
PR is up https://github.com/xamarin/xamarin-android/pull/1178
