### ISSUE TITLE
Binding Library using `class-parse` (Error CS1519: Invalid token 'params')

### ISSUE THREAD

**Issue by sushihangover** [xamarin/xamarin-android#1138]
**Error CS1519: Invalid token 'params' in class, struct, or interface member declaration (CS1519)** 

### Steps to Reproduce

1) Create Xamarin.Android binding library of the `.aar` : https://github.com/michael-rapp/AndroidUtil

Via Maven: http://central.maven.org/maven2/com/github/michael-rapp/android-util/1.18.2/android-util-1.18.2.aar

2) Use `class-parse`

`<AndroidClassParser>class-parse</AndroidClassParser>`

### `Xamarin.Android` repro solution/project:

[android-util-1.18.2.zip](https://github.com/xamarin/xamarin-android/files/1581521/android-util-1.18.2.zip)

### Expected Behavior

A beautifully generated binding project with no errors 😺 🍣 

### Actual Behavior

Generated code includes `params` keyword incorrectly, i.e. `params global:: Java.Lang.Object[] p2;`

### Example:
```
public partial class LoadDataEventArgs : global::System.EventArgs {

	public LoadDataEventArgs (bool handled, global::DE.Mrapp.Android.Util.Multithreading.AbstractDataBinder p0, global::Java.Lang.Object p1, params global:: Java.Lang.Object[] p2)
	{
		this.handled = handled;
		this.p0 = p0;
		this.p1 = p1;
		this.p2 = p2;
	}

	bool handled;
	public bool Handled {
		get { return handled; }
		set { handled = value; }
	}

	global::DE.Mrapp.Android.Util.Multithreading.AbstractDataBinder p0;
	public global::DE.Mrapp.Android.Util.Multithreading.AbstractDataBinder P0 {
		get { return p0; }
	}

	global::Java.Lang.Object p1;
	public global::Java.Lang.Object P1 {
		get { return p1; }
	}

	params global:: Java.Lang.Object[] p2;
	public params global:: Java.Lang.Object[] P2 {
		get { return p2; }
	}
}

```

### Version Information

* Xamarin.Android Version: 8.1.0.25 
* Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)

**Comment by JonDouglas** [comment]
There was also an earlier report of https://bugzilla.xamarin.com/show_bug.cgi?id=57927 which was closed due to lack of response. The reproduction in this issue demonstrates the issue clearly. Thanks @sushihangover for the report.

**Comment by Heshanp** [comment]
Related Stackoverflow question. @JonDouglas 
https://stackoverflow.com/questions/47917439/xamarin-binding-library-error?noredirect=1#comment82842259_47917439

**Comment by atsushieno** [comment]
A quick workaround is to make changes to any parameter type in any method that ends up with "..." .
