### ISSUE TITLE
[Android <4.3] AOT + SO_MAX=128 limitation leads to crash on start.

### ISSUE THREAD

**Issue by Belorus** [xamarin/xamarin-android#1146]
Androids pre 4.3 allowed only 128 .so libraries loaded into one process.
https://android.googlesource.com/platform/bionic/+/android-4.2_r1/linker/linker.cpp#54

OS + Runtime normally load about 65 libraries even before first line of code executes.
Other libs like mscorlib, System.Core, System.Net.Http take other ~20.

If your solution has ~20-25 projects (which isn't too much if you have proper architecture), and has another 10-15 nuget references - app won't load.

[Repro project that simply loads hundred of native libs and crashes after 56](https://github.com/xamarin/xamarin-android/files/1593964/lib.zip)

Log will contain entries like that, and crash with some DllNotFoundException
```
D/Mono    ( 6456): DllImport error loading library './libUnluckyLibName.so': 'Cannot load library: alloc_info[268]:   195 too many libraries when loading libUnluckyLibName.so'.
```

There is a [cool solution](https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/release-prep/#Bundle_Assemblies_into_Native_Code) that embeds all .dll files into one app_bundle.so. 
If something like that was implemented for AOT mode (for .so files), that would be great.

**Comment by jonpryor** [comment]
Upstream feature request: https://github.com/mono/mono/issues/6370

**Comment by jonpryor** [comment]
@Belorus: Looking at your Repro project, even if/when mono supports emitting a single AOT `.so` for all assemblies, your repro project will *still* fail, as `ClassLibrary1/ClassLibrary1.csproj` contains 135 native libraries, *none* of which can be merged/unified as part of AOT.

It might be more useful to create a repro which actually results in *AOT native libraries* preventing the launching of the app, not ~arbitrary native libraries packaged with the app.

**Comment by Belorus** [comment]
True, repro only shows the OS limitation and was used to calculate amount of hidden libraries loaded even before user code is run, it isn't a real red/green checker for the issue.
I'll create a proper one a bit later.

Thanks for quick response!

**Comment by jpobst** [comment]
Given that the minimum supported Android in Xamarin.Android is now 4.4, this no longer seems relevant.
