### ISSUE TITLE
eglGetDisplay failed EGL_BAD_PARAMETER

### ISSUE THREAD

**Issue by paradisehuman** [xamarin/xamarin-android#1160]
[EelaTaxi.zip](https://github.com/xamarin/xamarin-android/files/1605941/EelaTaxi.zip)
### Steps to Reproduce

1. Set linking on SDK and User Assemblies 
2. Check AOT Compilation
3. Check Use LLVM Optimizing Compiler
4. Archive the packge
5. Run on Huawei Honor3 or Huawei G700 or Huawei G610 or Huawei Y330

I attached the APK file.

**Tip1 : Everything is working fine without checking AOT Compilation and Use LLVM Optimizing Compiler even on Huawei devices that I mentioned .**

**Tip2 : On other devices ( except Huawei devices that I mentioned  ) everything is working fine even with checking AOT Compilation and Use LLVM Optimizing.** 

**Tip3 : Huawei devices Android versions are 4.2.2 and 4.2.1** 

### Expected Behavior
Runing the Program
### Actual Behavior
Force close on splashview
### Version Information

Visual Studio 15.5.2

### Log File

```
android.view.HardwareRenderer$GlRenderer.initializeEgl
HardwareRenderer.java - line 878
java.lang.RuntimeException: eglGetDisplay failed EGL_BAD_PARAMETER
eglGetDisplay failed EGL_BAD_PARAMETER
1- android.view.HardwareRenderer$GlRenderer.initializeEgl HardwareRenderer.java:878
2- android.view.HardwareRenderer$GlRenderer.initialize HardwareRenderer.java:829
3- android.view.ViewRootImpl.performTraversals ViewRootImpl.java:1806
4- android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1211
5- android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:5039
6- android.view.Choreographer$CallbackRecord.run Choreographer.java:776
7- android.view.Choreographer.doCallbacks Choreographer.java:579
8- android.view.Choreographer.doFrame Choreographer.java:548
9- android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:762
10- android.os.Handler.handleCallback Handler.java:800
11- android.os.Handler.dispatchMessage Handler.java:100
12- android.os.Looper.loop Looper.java:194
13- android.app.ActivityThread.main ActivityThread.java:5433
14- java.lang.reflect.Method.invokeNative Method.java
15- java.lang.reflect.Method.invoke Method.java:525
16- com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:924
17- com.android.internal.os.ZygoteInit.main ZygoteInit.java:691
18- dalvik.system.NativeStart.main NativeStart.java
```

**Comment by radekdoulik** [comment]
Do you know how it behaves with AOT enabled and LLVM disabled?

**Comment by paradisehuman** [comment]
@radekdoulik Hi. I think I tested and I got same result. I dont sure exactly.

**Comment by jonpryor** [comment]
What's odd is that your app doesn't appear to explicitly use OpenGL, yet the failure is around GL usage.

@paradisehuman: Would you be able to provide more `adb logcat` output, e.g. *everything* from the process corresponding to your app?

**Comment by paradisehuman** [comment]
@jonpryor I don’t have Huawei phones beside me right now , but I can provided your requested information tomorrow probably.

**Comment by paradisehuman** [comment]
@jonpryor I attached an image file that includes logcat information.
![untitled](https://user-images.githubusercontent.com/5645699/34638165-5709bb72-f2db-11e7-9db5-8a6ef797c7ef.png)

**Comment by paradisehuman** [comment]
@radekdoulik I have tested without checking LLVM Optimizing Compiler and I got force close.
For your info, Progourd is enable also.

**Comment by paradisehuman** [comment]
Is there any news for fixing that ?

**Comment by cbagpipe** [comment]
Expecting this bug too on IRBIS TX68 (Android 4.2, GPU: Mali-400 MP2)
Visual Studio 2019 (16.7.6)
NuGets (Xamarin Forms version, etc):
![изображение](https://user-images.githubusercontent.com/22903809/96831394-5935ce80-1480-11eb-83d0-1a991f8b7e19.png)

[logcat-dump.txt](https://github.com/xamarin/xamarin-android/files/5420413/logcat-dump.txt)

**Comment by jonathanpeppers** [comment]
Is this issue still happening in .NET 6 Android projects? Thanks!
