### ISSUE TITLE
MonoTests.System.Reflection.Emit.SaveTest.Save test fails in Release configuration with BCL linking on

### ISSUE THREAD

**Issue by grendello** [xamarin/xamarin-android#1186]
A test from the Mono BCL test suite ([MonoTests.System.Reflection.Emit.SaveTest.Save](https://github.com/mono/mono/blob/master/mcs/class/corlib/Test/System.Reflection.Emit/SaveTest.cs#L321)) fails when the tests are built in Release mode with linking set to SdkOnly.
It seems that the linker somehow changes the order of interfaces in emitted code since turning BCL linking off makes the test work again. The test also works fine in Debug configuration (with the linker off)

### Steps to Reproduce

1. Comment out [this line](https://github.com/xamarin/xamarin-android/blob/master/tests/BCL-Tests/Xamarin.Android.Bcl-Tests/nunit-excluded-tests.txt#L7)
2. Run `make CONFIGURATION=Release run-apk-tests` from the top Xamarin.Android dir
3. Wait patiently
4. Find the failure in the NUnit tests result file (`TestResult-Xamarin.Android.Bcl_Tests.nunit-Release.xml` in the top Xamarin.Android directory)

### Expected Behavior
The test should run fine with BCL linking on

### Actual Behavior
The test fails when executed with BCL linking on

### Version Information
Xamarin.Android/master (`c4e81655ac22b06806e732e9dd0bc729e8d2c1d7`)

### Test failure
```
MESSAGE:
  Expected: <iface1>
  But was:  <System.IComparable>

  +++++++++++++++++++
  STACK TRACE:
  at MonoTests.System.Reflection.Emit.SaveTest.CheckAssembly (System.Reflection.Assembly a) [0x000a0] in <1e30aff9165c427db5bedc42c5906861>:0 
  at MonoTests.System.Reflection.Emit.SaveTest.Save () [0x00b6d] in <1e30aff9165c427db5bedc42c5906861>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <0a3e31ed05774b07957e0b91c5cab789>:0
```

**Comment by radekdoulik** [comment]
This doesn't look like a linker bug, as the assembly is created by the test itself, not by the linker.

**Comment by jonpryor** [comment]
@radekdoulik: While that is indeed the case, it's only with a linked BCL that the problem occurs. Running the test with a Debug/unlinked BCL results in the test passing.

We don't understand *why* or *how* linking would be involved, but it's the straw we're grasping at.

**Comment by radekdoulik** [comment]
Further looking into that, I have put the code from the test to simple android app and it works OK in the Release configuration. The first interface is `iface1`.

So not sure yet what might be broken here.

**Comment by radekdoulik** [comment]
OK, the issue is the test is wrong :-)

In the documentation it is clearly stated, that the the interfaces are not returned in any particular order. https://msdn.microsoft.com/en-us/library/system.type.getinterfaces(v=vs.110).aspx#Anchor_2

**Comment by grendello** [comment]
@radekdoulik By 'not documented' I meant it isn't stated that the order must be kept. The wording you pasted states that it 'must not' depend on the order, which would make the test invalid, but as @marek-safar stated we want to keep compatibility with .NET as there might be code out there which relies on the particular behavior of .NET (even if it isn't a documented one)

**Comment by migueldeicaza** [comment]
You might just be getting lucky with some idioms/patterns in .NET, and might change with others, or might change across other implementations.   The documentation is right, we should fix the test.

**Comment by jonpryor** [comment]
On the implementation side of things, it appears that [`RuntimeType.GetInterfaces()`](https://github.com/mono/mono/blob/1e4f6b185b2aab27d5d004626874215c30720651/mcs/class/corlib/ReferenceSources/RuntimeType.cs#L710) is implemented as [`ves_icall_RuntimeType_GetInterfaces()`](https://github.com/mono/mono/blob/1e4f6b185b2aab27d5d004626874215c30720651/mono/metadata/icall.c#L2482-L2534) which uses a `GHashTable` to contain the enumerated interfaces.

I'm going to hazard a guess that `GHashTable`/[`g_hash_table_insert()`](https://github.com/mono/mono/blob/1e4f6b185b2aab27d5d004626874215c30720651/mono/eglib/ghashtable.c#L229-L265) doesn't preserve insertion order, which means the docs are correct and should be followed, because there's no easy way of fixing the implementation, just the tests.

**Comment by marek-safar** [comment]
I'm ok with the test fix but we have bug reports like https://bugzilla.xamarin.com/show_bug.cgi?id=31020 and similar so you could actually end up fixing this issue in XA for real
