### ISSUE TITLE
MSB4018: The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.

### ISSUE THREAD

**Issue by tuyen-vuduc** [xamarin/xamarin-android#1193]
### Steps to Reproduce

1. Clone http://github.com/naxam/accountkit-android-binding
2. Build the solution

### Expected Behavior
Build successfully

### Actual Behavior
Build failed
```
Xamarin.Build.Download.targets(135,3): error MSB4018: The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.
Xamarin.Build.Download.targets(135,3): error MSB4018: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: Attempted to Seek before the beginning of the stream
Xamarin.Build.Download.targets(135,3): error MSB4018:   at System.IO.FileStream.Seek (System.Int64 offset, System.IO.SeekOrigin origin) [0x000be] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:782 
Xamarin.Build.Download.targets(135,3): error MSB4018:   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () [0x00000] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:553 
Xamarin.Build.Download.targets(135,3): error MSB4018:    --- End of inner exception stack trace ---
Xamarin.Build.Download.targets(135,3): error MSB4018:   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () [0x00207] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:631 
Xamarin.Build.Download.targets(135,3): error MSB4018:   at System.IO.Compression.ZipArchive.Init (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen) [0x001c8] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:511 
Xamarin.Build.Download.targets(135,3): error MSB4018:   at System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen, System.Text.Encoding entryNameEncoding) [0x0001c] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:129 
Xamarin.Build.Download.targets(135,3): error MSB4018:   at System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode) [0x00000] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:57 
Xamarin.Build.Download.targets(135,3): error MSB4018:   at Xamarin.Build.Download.XamarinBuildAndroidAarProguardConfigs.Execute () [0x00105] in <dc3c3cbb6f924684ab0c214189899b4c>:0 
Xamarin.Build.Download.targets(135,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/msbuild-15.4/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:631 
Xamarin.Build.Download.targets(135,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x0022d] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/msbuild-15.4/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787 
```
### Version Information
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3.3 (build 5)
Installation UUID: a9ca3c9c-8010-48fc-9c68-07250cac8c03
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.2/Sdks
SDK Versions:
	2.0.2
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.1.3.0 (Visual Studio Enterprise)
Android SDK: /Users/tuyen/Library/Android/sdk
	Supported Android versions:
		4.4.87 (API level 20)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 27.0.0

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.3 (Visual Studio Enterprise)
Hash: f70a1348
Branch: xcode9.2
Build date: 2017-12-18 14:47:16-0500

=== Xamarin.Mac ===

Version: 4.0.0.215 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030005
Git revision: b1c2982e201e71ef758866c9ade05f253a8c6f47
Build date: 2017-12-21 11:04:40-05
Xamarin addins: f397ddfbacfb39e60c9cc8d9e410f73faf8c2cbc
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

LiveXAML 1.3.31
Internet of Things (IoT) development (Preview) 7.1

**Comment by dellis1972** [comment]
That looks like one of the zip files that were downloaded is corrupt. We should add a better error message so that the end user can remove the required file (or it should remove the file and re-download automatically if its not valid).

**Comment by dellis1972** [comment]
PR is up https://github.com/xamarin/XamarinComponents/pull/300

**Comment by dellis1972** [comment]
@Redth can we close this now? I assume its been released?

**Comment by Redth** [comment]
Yep!

**Comment by deepakraod** [comment]
Hi There,

I'm still facing this issue with the latest version of Xamarin.Build.Download (0.4.11).

Please find below logs, any help greatly appreciated, thanks.

Target _ComputeAndroidResourcePaths:
    Creating directory "obj/Debug/res/".
Target _ResolveMonoAndroidSdks:
    MonoAndroid Tools: /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/
    Android Platform API level: 27
    TargetFrameworkVersion: v8.1
    Android NDK: /
    Android SDK: /Users//Library/Developer/Xamarin/android-sdk-macosx/
    Android SDK Build Tools: /Users//Library/Developer/Xamarin/android-sdk-macosx/build-tools/27.0.3/
    Java SDK: /usr/
Target _GetPrimaryCpuAbi:
    _PrimaryCpuAbi=
Target _CheckInstantRunCondition:
    Dex Fast Deployment Enabled: False
Target _SetupInstantRun:
    Android Java Class for Fast Deployment: 
Target _SetupApplicationJavaClass:
    Application Java class: android.support.multidex.MultiDexApplication
Target _XamarinAndroidBuildAarProguardConfigs:
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018: The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: Attempted to Seek before the beginning of the stream
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.FileStream.Seek (System.Int64 offset, System.IO.SeekOrigin origin) [0x000be] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:782 
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:534 
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:    --- End of inner exception stack trace ---
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () [0x00207] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:612 
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive.Init (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen) [0x001c8] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:492 
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen, System.Text.Encoding entryNameEncoding) [0x0001c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:126 
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:56 
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at Xamarin.Build.Download.XamarinBuildAndroidAarProguardConfigs.Execute () [0x00154] in <69caa9f0854a4b74a425ff1835b63ee3>:0 
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /_/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:631 
    /Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in /_/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787 
Done building target "_XamarinAndroidBuildAarProguardConfigs" in project "TestProject.Droid.csproj" -- FAILED.

Done building project "TestProject.Droid.csproj" -- FAILED.

Build FAILED.

/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018: The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: Attempted to Seek before the beginning of the stream
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.FileStream.Seek (System.Int64 offset, System.IO.SeekOrigin origin) [0x000be] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:782 
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:534 
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:    --- End of inner exception stack trace ---
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () [0x00207] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:612 
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive.Init (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen) [0x001c8] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:492 
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen, System.Text.Encoding entryNameEncoding) [0x0001c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:126 
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs:56 
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at Xamarin.Build.Download.XamarinBuildAndroidAarProguardConfigs.Execute () [0x00154] in <69caa9f0854a4b74a425ff1835b63ee3>:0 
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /_/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:631 
/Users//Documents/Test/Project/TestProject/packages/Xamarin.Build.Download.0.4.11/build/Xamarin.Build.Download.targets(137,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in /_/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787 
    0 Warning(s)
    1 Error(s)
