### ISSUE TITLE
Entry did not moves upwards when keyboard is raised

### ISSUE THREAD

**Issue by SelvaKumar68** [xamarin/xamarin-android#1199]
In my custom component I have used one property type of Xamarin.Forms View. My scenario is I am adding Xamarin.Forms Entry (or any other text field) to the view and placing the component to bottom of the screen. While focusing the entry keyboard will popup and the field moves above the keypad and allows us to enter value it is the expected behaviour but in may case entry stays at the same position. So we unable to see what we are editing in entry field. Could you please help me on this?.

### Expected Behavior
The Entry becomes disappear with the half of the screen untill the keyboard overlaps.

### Actual Behavior
The Entry has to move up with the keyboard takes over the screen

Sample link: https://bugzilla.xamarin.com/attachment.cgi?id=23581 

Issue reproducing Video link: https://mail.google.com/mail/u/0/?ui=2&ik=fe63368efa&view=att&th=160310781053cca3&attid=0.1&disp=safe&realattid=f_jawhdor00&zw

**Comment by davidortinau** [comment]
[Archive.zip](https://github.com/xamarin/xamarin-android/files/1641119/Archive.zip)

@SelvaKumar68 I'm not sure what's going on with the layout you have in the linked sample. The ScrollView is commented out. I rebuilt a more simple reproduction linked above that works on iOS and Android.

The main key is to put your content within a ScrollView. The content will slide into view.

Another option to consider is how you want to configure the input mode via Android's UseWindowSoftInputModeAdjust. The [documentation is here](https://developer.xamarin.com/guides/xamarin-forms/platform-features/platform-specifics/consuming/android/#Setting_the_Soft_Keyboard_Input_Mode).

If you have any other issues to report in the future related to Xamarin.Forms, please file them at https://github.com/xamarin/Xamarin.Forms/issues/new.
