### ISSUE TITLE
Can not find OnColorsChangedListener type on Xamarin in API 27

### ISSUE THREAD

**Issue by fullmetaltac** [xamarin/xamarin-android#1201]
### Steps to Reproduce

1. Create c# class
2. Implement WallpaperManager.IOnColorsChangedListener

![image](https://user-images.githubusercontent.com/5435980/35048868-fcf448ee-fba6-11e7-90cb-35cd3b500ac0.png)

### Expected Behavior
I should be able to implement WallpaperManager.OnColorsChangedListener and use it as in android 8.1
https://developer.android.com/reference/android/app/WallpaperManager.OnColorsChangedListener.html

### Actual Behavior
There is no such type as WallpaperManager.OnColorsChangedListener.

### Version Information
[versionInfo.txt](https://github.com/xamarin/xamarin-android/files/1639414/versionInfo.txt)

**Comment by jonpryor** [comment]
The `WallpaperManager.OnColorsChangedListener` type isn't bound because the [`WallpaperColors` type isn't bound](https://github.com/xamarin/xamarin-android/blob/f41afb611ac500baccfeadd2829a8584ad6bdc14/src/Mono.Android/metadata#L1400).

**Comment by pjcollins** [comment]
Ah indeed, I remembered some discussion about this previously but I didn't relate the two items. @jonpryor do you think this is something that we'll be trying to address before 15.6 ships to stable? Or should the milestone be updated/removed at this time?
