### ISSUE TITLE
WCF service integration does not work with Visual Studio 2017 15.5.4

### ISSUE THREAD

**Issue by rob2212** [xamarin/xamarin-android#1209]
### Description

When you create a new Xamarin Project in Visual Studio 2017 using .Net Standard libraries, the access to a WCF web service does no longer work. Even the example project by Xamarin does produce the same issue.

### Steps to Reproduce

1. Download the Xamarin example: https://developer.xamarin.com/guides/xamarin-forms/cloud-services/consuming/wcf/
2. Build with Visual Studio 2017 15.5.4
3. Run Android App on a real device

### Expected Behavior
Method call to web service works (method: SoapService.RefreshDataAsync)

### Actual Behavior
Exception: The message with Action '' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).

### Basic Information

- IDE: Visual Studio 2017 15.5.4
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: Android SDK 7.1
  - UWP:  Not tested
- Android Support Library Version: 
- Affected Devices: Samsung Galaxy Tab A (2016)

**Comment by jonpryor** [comment]
@rob2212: Are there additional steps to reproduce? Do I need to setup a new backend?

When I launch the app, it shows a dialog stating:

> **Hosted Back-End**
> 
> This app is running against Xamarin read-only WCF service. To create, edit, and delete data you must update the service endpoint to point to your own hosted WCF service.

If I dismiss the message, I'm able to tap the `+` button, enter TODO information, and tap `SAVE`, but `adb logcat` doesn't contain anything like your your **Actual Behavior** exception message.

Would you be able to elaborate on step (3) "Run Android App on a real device"? Do you get the message *just* from launching the app? Or do you need to interact with it?

Could you please provide the *full* error message and stack trace?

A *plausible* explanation is that you're hosting your own WCF backend, and your WCF backend is configured to support only TLS 1.2+, while [by default Xamarin.Android only supports TLS 1.0](https://blog.xamarin.com/securing-web-requests-with-tls-1-2/#Android), as neither [`$(AndroidHttpClientHandlerType)` nor `$(AndroidTlsProvider)`](https://developer.xamarin.com/guides/android/advanced_topics/building-apps/build-process/) are set in the project.

**Comment by rob2212** [comment]
@jonpryor Could you reproduce the issue?

**Comment by jonpryor** [comment]
@rob2212: No, I was *not* able to reproduce. I was able to run the app, without throwing an exception, though [it did tell me it was using the read-only service](https://github.com/xamarin/xamarin-android/issues/1209#issuecomment-359025394).

**Comment by jonathanpeppers** [comment]
@rob2212 we haven't heard anything on this for a while. Visual Studio 15.8.4 is the latest version at present.

Closing for now, feel free to reopen if you can send more info, thanks!
