### ISSUE TITLE
Allow/use JAVA_HOME

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1213]
The default xamarin-android build uses whatever `java` is in `$PATH`, that the manner to override this choice is ill-defined. Additionally, the default xamarin-android build artifacts (`xabuild`) will likewise use whatever `java` is in `$PATH`.

Unfortunately, [on macOS it is rather "weird" to control the the default JDK which is used when more than one is installed](https://stackoverflow.com/a/44169445), making the "use whatever `java` is in `$PATH`" behavior sub-optimal.

There is already a way to specify the JDK to use for app builds: `$HOME/.config/xbuild/monodroid-config.xml` contains a `/monodroid/java-sdk/@path` attribute which is the path to the JDK to use.

However, *defaults matter*, and the default is `$PATH`.

We should do something smarter here, so that when we encounter a machine with both JDK 1.8 and JDK 9 installed, we prefer JDK 8.

**Comment by directhex** [comment]
Dumb question: why not try a few built-in paths after `JAVA_HOME`, before `$PATH`?

Like

Why not call the fully-qualified path from a common location?

`/Library/Java/JavaVirtualMachines/jdk1.8.0*/Contents/Home/bin/`
`/usr/lib/jvm/java-8-openjdk*/bin/`
`/usr/lib/jvm/java-1.8.0*/bin/`
`C:\Program Files\Java\jdk1.8.0\bin\`
`C:\Program Files (x86)\Java\jdk1.8.0\bin\`

That way you don't need to care about the user's default.

**Comment by jonpryor** [comment]
This should be fixed as of https://github.com/xamarin/java.interop/commit/4bd9297f311b3e0fb3e07335507a38278b83d255 and https://github.com/xamarin/java.interop/commit/bed29582923e35e692ae9354404937df6c5c1863 and 9bc51aed62d6e00035496dc3c6a76fb303a5fa90.

**Comment by awattar** [comment]
@jonpryor Are there any plans to support other standard Java/Android variables for SKD and NDK?
