### ISSUE TITLE
Add android:networkSecurityConfig support to ApplicationAttribute

### ISSUE THREAD

**Issue by alexsorokoletov** [xamarin/xamarin-android#1224]
### Steps to Reproduce

1. Add `[Application]` attribute and try specifying networkSecurityConfig as a property
2. Compilation fails

### Expected Behavior
Should allow user to specify url/path to the networkSecurityConfig
### Actual Behavior
Xamarin.Android does not support specifying this attribute in manifest through property.

### Version Information
Latest master https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.NamingCustomAttributes/Android.App/ApplicationAttribute.cs

### Log File
N/A

### Other
This attribute was included in API 24
https://developer.android.com/guide/topics/manifest/application-element.html#networkSecurityConfig

Looks like it is not yet available via C# surface

**Comment by atsushieno** [comment]
For future reference, there is nothing related to bindings. It is about MSBuild.

**Comment by nologinatgit** [comment]
I really need this attribute. When will it be publicly available?

**Comment by deyupopp** [comment]
Is there any documentation regarding how to use the attribute? I can see it's publicly available, but when I add it with [Application(NetworkSecurityConfig = "@xml/network_security_config")], the project does not build anymore (error is The "GenerateJavaStubs" task failed unexpectedly).
The network_security_config.xml file is under Resources/xml.

**Comment by deyupopp** [comment]
@jonpryor Can you please have a look on my previous comment?

**Comment by StevenBonePgh** [comment]
Similar concerns in this issue #2176. There is no apparent workaround to achieve desired results.

**Comment by JANeto87** [comment]
For future reference. Make sure after you add the **network_security_config.xml** file, you configure the **Build Action** to **AndroidResource** in the **Property** panel. This actually fixed the build error for me.
