### ISSUE TITLE
Issues with incremental build of resources (missing EmbeddedResource.LogicalName for __AndroidLibraryProjects__)

### ISSUE THREAD

**Issue by xen2** [xamarin/xamarin-android#1235]
Sorry, no clear steps to reproduce. Problem happens after various incremental builds.

`_AddLibraryProjectsEmbeddedResourceToProject` creates an `EmbeddedResource`:

```
Task "CreateItem" (TaskId:5014)
  Task Parameter:Include=obj\Android-OpenGLES\__AndroidLibraryProjects__.zip (TaskId:5014)
  Task Parameter:AdditionalMetadata=LogicalName=__AndroidLibraryProjects__.zip (TaskId:5014)
  Output Item(s): 
      EmbeddedResource=
          obj\Android-OpenGLES\__AndroidLibraryProjects__.zip
                  LogicalName=__AndroidLibraryProjects__.zip (TaskId:5014)
```

However, if `_AddLibraryProjectsEmbeddedResourceToProject` inputs/outputs are already up to date, it will add it without the `LogicalName`:
```
5>Skipping target "_AddLibraryProjectsEmbeddedResourceToProject" because all output files are up-to-date with respect to the input files.
5>Input files: C:\DEV\xenko2\sources\engine\SiliconStudio.Xenko.Engine\obj\Android-OpenGLES\res\layout\game.xml
5>Output files: obj\Android-OpenGLES\__AndroidLibraryProjects__.zip
```
result:
```
EmbeddedResource=
    obj\Android-OpenGLES\__AndroidLibraryProjects__.zip
            OriginalItemSpec=obj\Android-OpenGLES\__AndroidLibraryProjects__.zip
            TargetPath=obj\Android-OpenGLES\__AndroidLibraryProjects__.zip
```

Then, `CreateCSharpManifestResourceName` ends up creating a `LogicalName` which contains the root namespace:
```
obj\Android-OpenGLES\__AndroidLibraryProjects__.zip
    LogicalName=SiliconStudio.Xenko.obj.Android_OpenGLES.__AndroidLibraryProjects__.zip
```

As a result, `ResolveLibraryProjectImports` from Xamarin can't find the expected `__AndroidLibraryProjects__.zip` file since it has another name.
Resources collides and it results in a runtime crash when loading resource.

**Comment by xen2** [comment]
Additional details on MSBuild behavior regarding AdditionalMetadata:

https://social.msdn.microsoft.com/Forums/netframework/en-US/259271d8-a3fc-4a9b-9e3a-fecad8f6f63f/potential-bug-with-createitem-task-and-additionalmetadata?forum=msbuild

Seems like the AdditionalMetadata should always be added, so it could be done during `_UpdateAndroidResources` after it has been found by the "cached" task

**Comment by dellis1972** [comment]
@xen2 are you building with `xbuild` or `msbuild`? We are trying to figure out which one has the bug.

**Comment by xen2** [comment]
@dellis1972 with `MSBuild`. I suppose `xbuild` probably have the same issue, since metadatas can't be magically recreated out of nothing on second run.

**Comment by dellis1972** [comment]
@xen2 looks like we need to rework our targets a bit so the target which creates the item already runs but the one that generates the zip still gets skipped. Thanks for the bug report :)
