### ISSUE TITLE
Bump Android tooling defaults to latest versions in MSBuild

### ISSUE THREAD

**Issue by JonDouglas** [xamarin/xamarin-android#1266]
There are three Android SDK version MSBuild properties that we should bump in `Xamarin.Android.Common.targets`:

- `$(AndroidSdkBuildToolsVersion)`
- `$(AndroidSdkPlatformToolsVersion)`
- `$(AndroidSdkToolsVersion)`

Here are the current defaults:
```
<AndroidSdkBuildToolsVersion Condition="'$(AndroidSdkBuildToolsVersion)' == ''">23.0.0</AndroidSdkBuildToolsVersion>
<AndroidSdkPlatformToolsVersion Condition="'$(AndroidSdkPlatformToolsVersion)' == ''">25.0.5</AndroidSdkPlatformToolsVersion>
<AndroidSdkToolsVersion Condition="'$(AndroidSdkToolsVersion)' == ''">25.2.5</AndroidSdkToolsVersion>
```

Here is the latest versions as of Android 8.1:

- `build-tools`: 27.0.3
- `platform-tools`: 27.0.1
- `sdk tools`: 26.1.1

Currently there are some scenarios in which these defaults get picked up and used within various CI / CD services such as AppCenter. Instead of picking up old values, we should set these to be more recent.

**Comment by pjcollins** [comment]
A duplicate concern related to build tools version was discussed in https://bugzilla.xamarin.com/show_bug.cgi?id=60915. I will close that bugzilla issue as this item is now being tracked here.
