### ISSUE TITLE
Remove cruft from .vsix installer

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1267]
The `.vsix` installer is full of cruft, containing files which are not necessary:

* `v8.0/libZipSharp.dll.config`
* `v8.0/libzip.3.0.dylib`
* `v8.0/Mono.Android.Export.dll`
* `v8.0/OpenTK*`
* `v8.0/Mono.Android.GoogleMaps.xml`
* ...

Many of these files aren't needed (`.dylib` files on Windows?!). Many are obsolete and shouldn't exist at all (`Mono.Android.GoogleMaps.xml`?!). Many are "duplicative": `OpenTK*` is present in v2.3; there is no need for it to be in later API levels.

Review and cleanup the `.vsix` contents.

**Comment by jonpryor** [comment]
Related question: where is `v1.0/mscorlib.xml` *coming from*?!

It's present within the commercial installer, and I'm not currently sure *why*.

**Comment by pierceboggan** [comment]
What are the potential size implications for the Android VSIX of removing this cruft?

**Comment by jonpryor** [comment]
@pierceboggan: The hope is that we get an *installed* size on Windows (reportedly currently in the ~1.5GB range) closer to the installed size on macOS (~800MB). Not world-changing, but a good improvement.

The one complication there is documentation: macOS uses `mdoc` documentation, so there's a single (zipped!) file we install that contains the documentation for `Mono.Android.dll`. Windows instead emits a `Mono.Android.xml` file *alongside each `Mono.Android.dll` file*, and since each file is ~48MB...that's *a lot* of space just on documentation. (Across *13* API levels, that's ~624MB *just for documentation*.)

**Comment by pierceboggan** [comment]
@jonpryor Awesome, thanks so much for this context! :)

**Comment by pierceboggan** [comment]
@jonpryor: From someone who totally doesn't understand how this works: 

Now that we have automatic Android SDK management in place for 15.7, is it possible to install the relevant documentation pieces when we download the SDKs for an API level, or does that have to be baked into the VSIX?

**Comment by jonpryor** [comment]
@pierceboggan: Anything is possible, but that doesn't mean it's *easy*. The `Mono.Android.xml` documentation files are shown by VS IntelliSense, and need to be located in the same directory as the `Mono.Android.dll` which VS is using for compilation.

Could it be placed there as part of the Android SDK API-Level downloads? ¯\_(ツ)_/¯

@kzu: is that something worth exploring?

Meanwhile we've got other ideas running around, in various stages of "craziness" or simplicity, e.g. @joj has suggested that we update the Android SDK Installer infrastructure to *also* handle `Mono.Android.dll`/etc. files, or we could start using NuGet more (which still has the "minor" problem that we don't know what that actually looks like or what the implications would be...).
