### ISSUE TITLE
System.IO.FileNotFoundException when using Xamarin Forms

### ISSUE THREAD

**Issue by divega** [xamarin/xamarin-android#1275]
_From @frogcrush on November 7, 2017 22:16_

When trying to use with a Xamarin Forms application, I keep receiving the following error message:

![image](https://user-images.githubusercontent.com/6116333/32520758-f28f6dde-c3c5-11e7-895e-a456ff7cdb2b.png)

It's happened over two computers (one with a fresh VS2017 install). 

Microsoft.EntityFrameworkcore.Sqlite and Microsoft.EntityframeworkCore is referenced in both the .NET Core "shared" project and the .Android project.

### Steps to reproduce
Attempt to use Microsoft.EntityFrameworkCore.Sqlite with a Xamarin Forms project

### Further technical details
EF Core version: 2.0.0
Database Provider: e.g. Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio Community 2017

_Copied from original issue: aspnet/EntityFrameworkCore#10234_

**Comment by atsushieno** [comment]
As the error message states, Microsoft.EntityFrameworkCore.Sqlite does not exist in Xamarin.Android, just like Windwos.Forms does not exist in Xamarin.Android.

For a library to become usable on Xamarin.Android, it has to be either a Xamarin.Android library, a netstandard whose version targets Xamarin.Android, or a PCL whose profile targets Xamarin.Android.

**Comment by jonpryor** [comment]
I'm not able to reproduce this.

Test case:

[Scratch.Gxa1275.zip](https://github.com/xamarin/xamarin-android/files/1701241/Scratch.Gxa1275.zip)

Repro Steps:

```bash
curl -o Scratch.Gxa1275.zip https://github.com/xamarin/xamarin-android/files/1701241/Scratch.Gxa1275.zip
unzip Scratch.Gxa1275.zip
nuget restore *.sln
cd Droid
msbuild /t:SignAndroidPackage Scratch.Gxa1275.Droid.csproj
```

The project builds successfully.

The above project is a new Xamarin.Forms project on Visual Studio for Mac, then I added the [Microsoft.EntityFrameworkCore.Sqlite](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite/) NuGet package.

It builds.

Note: The `Microsoft.EntityFrameworkCore.Sqlite` package appears to be empty, but depends on the [Microsoft.EntityFrameworkCore.Sqlite.Core](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite.Core/) NuGet package, which contains netstandard2.0 assemblies:

```bash
$ unzip -l microsoft.entityframeworkcore.sqlite.core.2.0.0.nupkg | grep dll$
    95752  07-25-2017 00:48   lib/netstandard2.0/Microsoft.EntityFrameworkCore.Sqlite.dl
```

**Comment by divega** [comment]
@frogcrush since you filed the original issue at https://github.com/aspnet/EntityFrameworkCore/issues/10234, do you have a repro project that the Xamarin team can use to investigate?

**Comment by jonpryor** [comment]
Closing due to no response in three months.
