### ISSUE TITLE
async void OnCreate not reporting errors on API 15/16

### ISSUE THREAD

**Issue by rihadavid** [xamarin/xamarin-android#1277]
### Steps to Reproduce

1. Use this sample code:
       
        public class MyActivity : AppCompatActivity
        {
           protected override async void OnCreate(Bundle savedInstanceState)
           {
                base.OnCreate(savedInstanceState);
                throw new Exception();
           }
        }
2. Run the app and open the activity on API 15 or 16
3. The exception is ignored, app continues running
4. when removing the word ``async``, the exception gets reported, app crashes.

### Expected Behavior
App should crash no matter whether it is ``async void`` or just ``void``, especially if the exception is thrown before any ``await``.
### Actual Behavior
On API 15 and 16, it only crashes if it is ``void``. On android M and others, it crashes with both ``async void`` and ``void``.
### Version Information
Microsoft Visual Studio Community 2017 
Version 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA614
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA614
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA614
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31125.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.11025.7
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.8.0.753 (6575bd113)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.8.188 (c5813fa34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.1.0.25 (HEAD/d8c6e504f)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.6.1.2 (6857dfc)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonpryor** [comment]
Does this happen *just* on API-15/16, or does it happen on *all* API levels?

**Comment by rihadavid** [comment]
As described in "Actual Behavior", it is happening just on API 15/16. I tested this on Android M and there it is no such problem, crashes as expected. However, I did not test this on _all_ API levels.

**Comment by oli-g-sk** [comment]
I just discovered that the repro steps are incomplete: It's not enough that the method is `async void`, it also has to run asynchronously, so **it needs an 'await' somewhere**. Maybe that's obvious, just saying for the sake of completeness.

**Comment by rihadavid** [comment]
for me, on API 15, it is happening even without any await. @oli-g-sk  is testing on API 16, so maybe it slightly differs.

**Comment by oli-g-sk** [comment]
Ok, actually, it's more complicated than that, forget my previous comment :)
It seems it's behaving differently in different activities. We'll investigate and post an update.

**Comment by oli-g-sk** [comment]
Actually, it seems **this bug does not exist**.
Sorry for the false alarm, we were a bit out of sync when this was reported.

The app **doesn't continue running** after an Exception in an `async void` method.

The 'async' keyword in `OnCreate` only caused the **other lifecycle callbacks** (like `OnStart`) to get **executed first**, before the "async" Exception could even crash the app.

In those other lifecycle callbacks, we were assuming our layout was inflated and views were bound, which wasn't the case (due to `OnCreate` not running to completion). As a result, a `NullReferenceException` was thrown _before_ the original `Exception` had its chance. Duh!

In a blank Activity with literally nothing more than the sample code above, the Exception _does crash the app eventually_. If we keep `OnCreate` is synchronous, it crashes _instantly_.

**Comment by rihadavid** [comment]
Ok, it's still a little strange that ``OnStart`` is called before the exception in ``async void OnCreate`` is thrown, but I think we can close this, now when we know the exception is actually reported, just a little later then it should be.

**Comment by grendello** [comment]
@rihadavid it is actually quite expected. There's no guarantee about the order in which the tasks are executed if they aren't dependent on each other - and they're not in this case. Also, the exception my be "held" by TPL code and then thrown eventually - also asynchronously. With that, to support asynchronous execution of the `On*` methods we'd need to add support for this in our backend code/XA runtime. It's an idea we should revisit at some point.
