### ISSUE TITLE
Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF]

### ISSUE THREAD

**Issue by koz01** [xamarin/xamarin-android#1284]
How can i solve this warning?
Severity	Code	Description	Project	File	Line	Suppression State
Warning		can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])

**Comment by jonpryor** [comment]
This was fixed in 2c2d47c4a28eeb398500a8c0a9a0a803324de014 and Issue #1137 / commit d1bc5339.

The fix is in Xamarin.Android 8.2 (d15-6).

**Comment by jrahma** [comment]
I have this problem :(

> You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR: JAR_SIG_NO_MANIFEST: Missing META-INF/MANIFEST.MF
