### ISSUE TITLE
Resource related intellisense breaks after Rebuilding

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1286]
Moving report from https://bugzilla.xamarin.com/show_bug.cgi?id=60880 into Issues. It looks like the clean target is still deleting `designtime\Resource.Designer.cs` in d15-6.

### Steps to Reproduce

1. Create a new Single-View Android App
2. Open MainActivity.cs, and notice that both `Resource.Layout.Main` and `Resource.ID.myButton` are available in Intellisense
3. Select Build -> Clean Solution.
4. Resource.* related Intellisense no longer works as expected

### Expected Behavior
Resource related Intellisense will continue to work after cleaning, building, rebuilding, etc.

### Actual Behavior
The following IntelliSense output is displayed, and Resource related Intellisense no longer works.
> [Failure] Could not find file 'c:\users\peter\source\repos\App16\App16\obj\Debug\designtime\Resource.Designer.cs'.
### Version Information
VS 15.6 Preview 4:
https://gist.github.com/pjcollins/b8be35efd9b9eb0fb7e1355e74396fd2

### Log File
https://gist.github.com/pjcollins/ee151a4e90f0d8ac7ec9d28984e52be7#file-gistfile1-txt-L1197-L1205

**Comment by dellis1972** [comment]
Hmm, `Xamarin.Android.Windows.targets` does not seem to be imported. Can you confirm it exists "somewhere" in the installation for windows?

**Comment by pjcollins** [comment]
I do have that targets file at the following location:
`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common\ImportAfter\Xamarin.Android.Windows.targets`

**Comment by dellis1972** [comment]
So weird. so why is that not being imported...

**Comment by dellis1972** [comment]
ok that log is the `Clean` target being run.. So its that target which is removing our designer file. And because `IncrementalClean` is not run as part of a `Clean` our targets are not running which would preserve the file.

**Comment by pjcollins** [comment]
Verified fixed against ef7a59fae3b417d9d959a824beb7ff5151a5fcac

**Comment by Aguilex** [comment]
added vs-sync to create VSTS bug so it can be associated with PR https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/107122
