### ISSUE TITLE
Encountering BCL-Test failure in MonoTests.System.Runtime.CompilerServices.RuntimeFeatureTest.NoNewFeaturesAdded (monodroid_corlib_test) when running on Android in Release config

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1310]
Similar to #1309, the following test case fails on Android when ran in Release configuration. Presumably the issue is linker related?

https://github.com/mono/mono/blob/master/mcs/class/corlib/Test/System.Runtime.CompilerServices/RuntimeFeatureTest.cs#L44

### Steps to Reproduce

1. Copy over the relevant test source linked above into a new Android project and deploy it in release configuration.

### Expected Behavior
The test should pass when ran in a 'Release' configuration.

### Actual Behavior
The test fails when ran in a 'Release' configuration.

### Version Information
mono-2017-12
https://gist.github.com/pjcollins/43e1e192125ac5db93c1af50faaffee8

### Log File

``` 
MonoTests.System.Runtime.CompilerServices.RuntimeFeatureTest.NoNewFeaturesAdded (monodroid_corlib_test)
02-14 14:41:22.282 10712 10729 I NUnit   :   Expected is <System.ValueTuple`2[System.String,System.Boolean][1]>, actual is <System.ValueTuple`2[System.String,System.Boolean][0]>
02-14 14:41:22.282 10712 10729 I NUnit   :   Values differ at index [0]
02-14 14:41:22.282 10712 10729 I NUnit   :   Missing:  < (PortablePdb, True) >
02-14 14:41:22.282 10712 10729 I NUnit   :
02-14 14:41:22.282 10712 10729 I NUnit   :   at MonoTests.System.Runtime.CompilerServices.RuntimeFeatureTest.NoNewFeaturesAdded () [0x00088] in <51b16f8a5a3c437f97c053afcbbba491>:0
02-14 14:41:22.282 10712 10729 I NUnit   :   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
02-14 14:41:22.282 10712 10729 I NUnit   :   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <3e87052017124b0aa0d514e8df5eadbc>:0```

**Comment by marek-safar** [comment]
This is Mono issue

**Comment by akoeplinger** [comment]
This was fixed by https://github.com/mono/mono/pull/7149 in Mono (backported to 2017-12 with https://github.com/mono/mono/pull/7152).

**Comment by pjcollins** [comment]
I'm encountering the new inconclusive assert when running this with the linker enabled in d15-7, as expected.
