### ISSUE TITLE
Provide 64-bit versions in addition to 32-bit version for AndroidSupportedAbis in default Release configuration

### ISSUE THREAD

**Issue by JonDouglas** [xamarin/xamarin-android#1311]
**In August 2019, Play will require that new apps and app updates with native libraries provide 64-bit versions in addition to their 32-bit versions.**

**Source:** https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

This should be a small fix in nature by adding the respective 64-bit CPU instruction set to the `<AndroidSupportedAbis>` MSBuild property:

```
<AndroidSupportedAbis Condition=" '$(AndroidSupportedAbis)' == '' ">armeabi-v7a;arm64-v8a</AndroidSupportedAbis>
```

Although this requirement isn't until August 2019, we may want to start pushing the default to our release configuration with 64-bit in mind as a best practice? Thoughts?

**Comment by jonpryor** [comment]
The concern is that this will impact our default minimum `.apk` size.

For example, if we take our [HelloWorld sample](https://github.com/xamarin/xamarin-android/tree/master/samples/HelloWorld), the default size with just armeabi-v7a is 4.2MB: 

```bash
$ xbuild /t:SignAndroidPackage /p:Configuration=Release
$ ls -lh bin/Release/*-Signed.apk
-rw-r--r--  1 jon  staff   4.2M Feb 15 09:58 bin/Release/com.xamarin.android.helloworld-Signed.apk
```

If we update that as proposed, it becomes 5.5MB. Add BTLS, and it'll be worse (not measured).

*Just* arm64-v8a inclusion results in a 4.0 MB `.apk`.

**Comment by tomcurran** [comment]
@jonpryor We maintain several apps and are concerned about having APK size increase to fulfil the 64 bit requirement. Regardless of the defaults people will likely have to do this. I think using app bundles instead of APKs would help mitigate the increase in app size. Is support for app bundles on the xamarin android roadmap?

**Comment by tomcurran** [comment]
Found app bundle support issue #2727

**Comment by jonathanpeppers** [comment]
The defaults for `$(AndroidSupportedAbis)` were changed in: https://github.com/xamarin/xamarin-android/pull/2825

I think we can close this.
