### ISSUE TITLE
Binding AutofillType and ImportantForAutofill type issue for API 26.

### ISSUE THREAD

**Issue by awattar** [xamarin/xamarin-android#1313]
### Steps to Reproduce

1. Create binding project for library that contains UI controls with inherited AutofillType and ImportantForAutofill.
2. Set target / compileSdkVersion to 8.0 / 26
3. Build.

Probably enums are not correctly mapped for inherited members from autofill framework.

### Expected Behavior

Builds fine.

### Actual Behavior

error CS1715: 'MySearchView.AutofillType': type must be 'AutofillType' to match overridden member 'View.AutofillType'
error CS1715: 'MySearchView.ImportantForAutofill': type must be 'ImportantForAutofill' to match overridden member 'View.ImportantForAutofill'

### Version Information

Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.4 Preview (7.4 build 985)
Installation UUID: fc295dbb-ea60-45ea-a7bd-051b091fe655
Runtime:
	Mono 5.8.0.123 (2017-10/38502063cac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000123

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Android
Version: 8.2.0.12 (Visual Studio Enterprise)
Android SDK: /Users/mwesolowski/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Xamarin.Mac
Version: 4.2.0.19 (Visual Studio Enterprise)

Xamarin.iOS
Version: 11.8.0.19 (Visual Studio Enterprise)
Hash: 5b1f7168
Branch: d15-6
Build date: 2018-02-01 18:50:51-0500

Build Information
Release ID: 704000985
Git revision: 0bed5a3380dbe82009f80c895623208d6c0df152
Build date: 2018-02-02 20:00:14-05
Xamarin addins: 612453baa9a0faea49aa554be49c01c2e0542bf3
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1

**Comment by atsushieno** [comment]
There is no such "correct" automatic-mapping. Changing generator behavior will break existing bindings and possibly introduce build breakage with related to interface implementation.

Such members of a derived type from View need to be explicitly enum-ified by metadata fixup description (Metadata.xml / EnumMetadata.xml). There are fair amount of examples in Android support library bindings e.g. https://github.com/xamarin/AndroidSupportComponents/blob/master/support-core-ui/source/Transforms/EnumMethods.xml

**Comment by awattar** [comment]
Thanks. Good to know that this is "by design" rather than feature impairment or an issue.
