### ISSUE TITLE
Linker exceptions from NRE to 'Android.App.Job.JobServiceEngine' not found

### ISSUE THREAD

**Issue by jtorvald** [xamarin/xamarin-android#1316]
### Steps to Reproduce

1. Open attached demo project
2. Build in release mode

[https://www.dropbox.com/s/bgerxdb6inido2g/test-linker.zip?dl=1](https://www.dropbox.com/s/bgerxdb6inido2g/test-linker.zip?dl=1)

The demo project is quite stripped and packages folder is copied from a real project where I experience the same issue. It contains packages in the packages folder but the packages.json is empty. Even when I try to re-add the Xamarin.Android Support compat and v4 support packge I still get the error in the Preview version (beta)

### Expected Behavior
I try to build in Release mode and expect it to build successfully.
### Actual Behavior
It crashes on the Linker step. With the stable version I get:
```
Xamarin.Android.Common.targets(1696,5): 
error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object
Xamarin.Android.Common.targets(1696,5): error MSB4018:   at
Mono.Linker.TypeReferenceExtensions+<GetMethods>d__4.MoveNext () [0x00038] in <a9f581d0c2a2409a88d42cf1050f6508>:0 
```

With the preview version I get:
```
error MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.App.Job.JobServiceEngine'
(defined in assembly 'Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') 
with scope 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. 
When the scope is different from the defining assembly, it usually means that the type is forwarded.
 ---> Mono.Cecil.ResolutionException: Failed to resolve Android.App.Job.JobServiceEngine
```

### Version Information

=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.4 Preview (7.4 build 985)
Installation UUID: 8a28987a-1e72-4b4e-ae4d-21612ffbdc71
Runtime:
	Mono 5.8.0.123 (2017-10/38502063cac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000123

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.19 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.8.0.19 (Visual Studio Community)
Hash: 5b1f7168
Branch: d15-6
Build date: 2018-02-01 18:50:51-0500

=== Xamarin.Android ===

Version: 8.2.0.12 (Visual Studio Community)
Android SDK: /Users/developer/Library/Developer/Xamarin/android-sdk-mac_x86
	Supported Android versions:
		2.3 (API level 10)
		4.1 (API level 16)
		4.2 (API level 17)
		5.0 (API level 21)
		7.0 (API level 24)
		7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.2

Java SDK: /usr
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704000985
Git revision: 0bed5a3380dbe82009f80c895623208d6c0df152
Build date: 2018-02-02 20:00:14-05
Xamarin addins: 612453baa9a0faea49aa554be49c01c2e0542bf3
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

### Log File

no logs

**Comment by atsushieno** [comment]
While your csproj indicates that the TargetFrameworkVersion is v8.0 (API Level 26), your Xamarin.Android setup does not have API Level 26 installed. It seems it is too old version to use that recent support library NuGet packages.

Recent Android support libraries, at Java side, requires the latest API as the target framework. r26 requires API Level 26 as the target framework.

Either moving back to Support library r25.* or upgrading the product version would resolve your problem.

**Comment by jtorvald** [comment]
@atsushieno thank you so much! I tried to fix that with the packages file, but apparently that does not change the references in the project file. I reverted everything back to the older versions and now I'm able compile and link again.
