### ISSUE TITLE
Binding Library properties shows class-parse but jar2xml is used by default

### ISSUE THREAD

**Issue by JoshaMunnik** [xamarin/xamarin-android#1319]
### Steps to Reproduce

1. Create new Android Binding Library
2. Add jar/aar (for example firebase-messaging-11.8.0.jar)
3. Open properties, Android Class Parser shows "class-parse"
4. Set MSBUILD to Diagnostic (Tools ->Options -> Projects and Solutions -> Build and Run)
5. Build
6. Output shows some JARTOXML warnings

### Expected Behavior
Class-parse being used

### Actual Behavior
Jar2xml being used

### Workaround
1. Open properties
2. Switch Android Class Parser to "jar2xml"
3. Save
4. Switch Android Class Parse to "class-parse"
5. Save

When build/rebuilding class-parse gets used.

### Additional information

Edit: The intial _csproj_ file does not have `<AndroidClassParser>...</AndroidClassParser>` section. Only after changing the value in the properties does this section get added. My assumption is that when this section is missing the default parser is JAR2XML is used even though the project properties show something different.

### Version Information
Microsoft Visual Studio Community 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556
Installed Version: Community
Visual Basic 2017   00369-60000-00001-AA733
Microsoft Visual Basic 2017
Visual C# 2017   00369-60000-00001-AA733
Microsoft Visual C# 2017
Visual F# 4.1   00369-60000-00001-AA733
Microsoft Visual F# 4.1
Application Insights Tools for Visual Studio Package   8.10.01106.1
ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017
ASP.NET Core Razor Language Services   1.0
ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
Azure App Service Tools v3.0.0   15.0.31106.0
Common Azure Tools   1.10
Fabric.DiagnosticEvents   1.0
File Nesting   2.6.67
JavaScript Language Service   2.0
JetBrains ReSharper Ultimate 2017.3    Build 111.0.20171218.133305
Merq   1.1.17-rc (cba4571)
Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3
Microsoft Continuous Delivery Tools for Visual Studio   0.3
Microsoft JVM Debugger   1.0
Microsoft MI-Based Debugger   1.0
Microsoft Visual Studio Tools for Containers   1.1
Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
NuGet Package Manager   4.5.0
SQL Server Data Tools   15.1.61710.120
TypeScript Tools   15.5.11025.1
Visual Studio Code Debug Adapter Host Package   1.0
Visual Studio Tools for Unity   3.5.0.3
VisualStudio.Mac   1.0
Web Compiler   1.11.326
WebJobs Tools v1.0.0   15.0.31201.0
Xamarin   4.8.0.760 (fc93f3f5b)
Xamarin Designer   4.8.188 (c5813fa34)
Xamarin.Android SDK   8.1.5.0 (HEAD/75f8c6838)
Xamarin.iOS and Xamarin.Mac SDK   11.6.1.4 (db807ec)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by atsushieno** [comment]
My guess is that you are seeing build log lines sayin like below:

    Target "ExportJarToXml: (TargetId:38)" in file "/devel/lib/mono/xbuild/Xamarin/Android/Xamarin.Android.Bindings.targets" from project "/home/atsushi/Desktop/BindingTest1/BindingTest1.csproj" (target "GenerateBindings" depends on it):

This is actually invoked even if your project has `<AndroidClassParser>class-parse</AndroidClassParser>` in your `<PropertyGroup>` element.

**Comment by JoshaMunnik** [comment]
No, I saw JAR2XML warnings (only shown when output is set to diagnostic).

I discovered this, because I was binding to a an AAR that contained a class which had some methods that referenced types that were defined outside the AAR. Initially this class was completely missing from the _api.xml_. However I read that class-parse should still have have partially included this class. This is also when I noticed the JAR2XML warnings. So I tried the work around, after a rebuild the _api.xml_ contained the class definition (without the methods that referenced the 'unknown' types) and without any JAR2XML warnings.

**Comment by atsushieno** [comment]
What does your build log say about the actual property value for `AndroidClassParser` ? (shown after `Initial Properties:` header)

If jar2xml is used, then the value should look like `AndroidClassParser = jar2xml`, and it should be `AndroidClassParser = class-parse` if it is resolved as expected.

**Comment by atsushieno** [comment]
(For reference, this is the relevant MSBuild targets description line: https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets#L411)

**Comment by JoshaMunnik** [comment]
It shows: 
    AndroidClassParser = jar2xml

I edited the bug report a bit, my assumption is that either the bug is that the wrong default class parser is shown in the project properties or the wrong default class parser is used when the AndroidClassParser section is missing from the csproj file.

**Comment by atsushieno** [comment]
Thanks. It seems like an IDE issue then.

**Comment by jpobst** [comment]
If `<AndroidClassParser>` is not specified `jar2xml` is used.

Using VS 16.3.10 I verified:
* A new binding project contains `<AndroidClassParser>class-parse</AndroidClassParser>`
* Changing to `jar2xml` in the property page updated the csproj
* Changing back to `class-parse` in the property page updated the csproj
* Loading a project with no `<AndroidClassParser>` specified shows `jar2xml` in the property page
* Changing this project to `class-parse` in the property page updated the csproj

This seems to have been fixed at some point on the VS side, so I'm closing.
