### ISSUE TITLE
Properly reorder AndroidManifest.xml elements

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1332]
There is indeed an appropriate ordering for `AndroidManifest.xml` elements!

In particular, we have encountered an app repro + device which crashes within Skia if `AndroidManifest.xml` contains:

```xml
<uses-sdk android:minSdkVersion="19" />
<application android:label="CrashXamarin.Android"></application>
```

but *works* if `<application/>` comes *before* `<uses-sdk/>`!

```xml
<application android:label="CrashGPSXamarin.Android"></application>
<uses-sdk android:minSdkVersion="19" />
```

We need to determine what the proper ordering actually is, then update the packaging step so that we appropriate reorder elements within `AndroidManifest.xml` so we avoid such bizarre behaviors.

**Comment by JonDouglas** [comment]
`lint.bat` should provide all the information we need on manifest ordering.

EX: On a manifest that has bad placement like the example above:

```
AndroidManifest.xml:4: Warning: <uses-sdk> tag appears after <application> tag [ManifestOrder]
 <uses-sdk android:minSdkVersion="19" />
```

**Comment by atsushieno** [comment]
I'm curious if there is any repro sources...?

**Comment by dellis1972** [comment]
@jonpryor I think we can close this one now. manifestmerger should take care of this. Re-open if you disagree :)
