### ISSUE TITLE
Xamarin.Android: ANDROID_HOME variable is required by tests and should be set by the IDE or when running the UI tests

### ISSUE THREAD

**Issue by curia-damiano** [xamarin/xamarin-android#1333]
### Steps to Reproduce

1. Install a clean machine with Windows 10 and VS2017
2. Update the SDK as needed by your app
3. Open a Xamarin.Android project and try to run the UI tests

### Expected Behavior
I would expect that the UI test will work.
So, if the ANDROID_HOME environment variable is needed, it should be added by the Android SDK installer, by the Visual Studio options dialog, or simply set when running the test (reading from the Visual Studio options dialog).

### Actual Behavior
But in reality it fails because it complains that it can't find the ANDROID_HOME environment variable

### Version Information
VS2017 15.5.7

Microsoft Visual Studio Enterprise 2017 
Version 15.5.7
VisualStudio.15.Release/15.5.7+27130.2036
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual Basic 2017   00369-60000-00001-AA892
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA892
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA892
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31129.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.3.2000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.2000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.2000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.27005.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27130.2036
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WebJobs Tools v1.0.0   15.0.40108.0
WebJobs Tools v1.0.0

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.8.0.760 (fc93f3f5b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.8.188 (c5813fa34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.1.5.0 (HEAD/75f8c6838)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.6.1.4 (db807ec)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

[23.02.2018 15:04:39 Informational] Full log file: C:\Users\dacuri\AppData\Local\Temp\uitest\log-2018-02-23_15-04-39-697.txt

23-02-2018 15:04:39.715 +01:00 - 17 - Potential Android SDK location: (No path) - Not set. [ Source: ANDROID_HOME ]

**Comment by jonpryor** [comment]
I am confused.

> Open a Xamarin.Android project and try to run the UI tests

*What* UI tests? Do you mean the **[X] Add an automated UI test project** checkbox in the Visual Studio (for Mac?) New Project dialog? (This UI test project uses Xamarin Test Cloud.)

How are you running the UI tests? What menu commands/etc. are you using?

Do you have an example project?

**Comment by JonDouglas** [comment]
@curia-damiano 

I believe you are referring to the `ANDROID_HOME` environment variable to be set as the path of the Android SDK to test an Android app using Xamarin.UITest correct?

This is a requirement set by the Calabash / Xamarin.UITest package which is documented here:

https://developer.xamarin.com/guides/testcloud/uitest/intro-to-uitest/#Requirements

Our installer, similar to Android Studio does not set an `ANDROID_HOME` nor `ANDROID_SDK_ROOT` environment variable as these are mostly needed for command-line tooling.

If you're interested, this stems back to [Calabash-Android Requirements](https://github.com/calabash/calabash-android/blob/master/documentation/installation.md#prerequisites)

> You should have the Android SDK installed. You can download it from here. Create an environment variable with the name : ANDROID_HOME and its value pointing to the location of the unzipped downloaded SDK.

Since this issue is not related to the code inside this repo, I am closing this issue. I have however created an internal item to track this with our installer team. In the event that you're unsure of where to file an issue, please refer to our [readme.md](https://github.com/xamarin/xamarin-android/#reporting-bugs) or our [submitting bugs, feature requests, and pull requests wiki](https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#where-to-file-an-issue). Feel free to re-file this issue in Developer Community using the `Report a Problem` feature inside your IDE. That way we can track this publicly as well.

**Comment by curia-damiano** [comment]
Hi Jon,
it's fair if it is documented.
Only to me it sounded strange because on Mac, this variable is set up, in fact UI Tests on VS4Mac work without any problem.
I've also added it on PC and in fact Android tests work fine.
Regards, Damiano
