### ISSUE TITLE
It is optional to have Location header on response 300

### ISSUE THREAD

**Issue by troyanas** [xamarin/xamarin-android#1334]
https://tools.ietf.org/html/rfc7231#section-6.4.1
Regarding this, Android should not throw exception when HttpClient returns response with code 300 not including **Location** header.
iOS handles this fine.

This line should be changed:
https://github.com/xamarin/xamarin-android/blob/8354bef4d6c1978aa979d3b2a055a4c16a2bdfe8/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L539-L540

**Comment by grendello** [comment]
@troyanas what do you suggest it is changed **to**? The RFC is specific in its use of `SHOULD` (generate the `Location` header) and `MAY` (use the `Location` header), but it doesn't specify the behavior when the `Location` header is absent. Should we return a request with empty contents? Should we fail silently? Should we read the body (if any) of the response and return that? What does iOS do in this case?

**Comment by troyanas** [comment]
@grendello, I am not an expert in this but as I understand, Location header SHOULD be added to header, but that means it MAY or MAY NOT be there. iOS returns the body. So I suppose Android should do the same. That is your opinion?

**Comment by grendello** [comment]
@troyanas I guess we should follow suit, yes.

**Comment by grendello** [comment]
@troyanas this is now [fixed in master](https://github.com/xamarin/xamarin-android/commit/eab047f478b5084a157b5dd22dafae2770a9b3d9), I tested it by visiting https://httpbin.org/status/300 and it worked fine.

**Comment by troyanas** [comment]
Is it not working again? I can swear that I have seen this working in Visual Studio 1 week ago and now it is throwing an exception again.
