### ISSUE TITLE
Add @(AndroidDexFile) Item group support. 

### ISSUE THREAD

**Issue by dellis1972** [xamarin/xamarin-android#1340]
The idea being that Items in this list will be used rather than compiling library .class files into .dex files at build time.

**Comment by atsushieno** [comment]
It is actually slightly different from whatever I had in mind - .dex is not really stable format and subject to change. It is kind of worrysome if people distribute libraries in .dex format and expect it to be working. If .dex file is "broken", there is no way for us to verify that, and even if we had such a verifier, running it before using it is harmful for performance after all.

It should be therefore non-public optimization feature that is always subject to change, probably only for our components team.

**Comment by atsushieno** [comment]
Another concern while I was having a look at new r8 shrinker: it takes `--min-api` argument which is used to determine which kind of code is "desugared". That means, each application has to embed "specific" dex libraries to its target API. It is not really viable to ship dex files for each API level, packaged dex is not going to work.
