### ISSUE TITLE
Android Binding Library issue

### ISSUE THREAD

**Issue by tbehera** [xamarin/xamarin-android#1344]
### Steps to Reproduce

1. 
2. 
3. 

### Log File

If I run the same code (android camera code) directly from Android Studio , everything works fine.But if I create a binding library in Visual Studio and then call the camera function from C# (Visual Studio) then I see the following warning messages and the camera is not capturing the image.Camera is stuck.But in a newer Android phone, it works fine.This issue is only observed in the older Android phone while using visual studio binding library.

Skipped XX frames! The application may be doing too much work on its main thread.

What could be the reason?How to fix it?

**Comment by JonDouglas** [comment]
Hi @tbehera,

Thanks for your contribution! Can you please take a quick look over [our best practices when filing a bug?](https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#bug-reports). We will want a reproducible project and any relevant logs demonstrating the behavior. As this issue sits, there's not enough information to investigate. We will want the binding project, a sample project consuming that binding, and various logs on your older device vs newer device. Chances are you are running into an issue with the main thread. You can read more about that in this [blog](https://blog.xamarin.com/tips-for-creating-a-smooth-and-fluid-android-ui/).

**Comment by JonDouglas** [comment]
I am closing this issue due to a lack of activity for more than 7 days. At anytime, feel free to reopen this issue with the requested changes, or create a new issue.

https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#common-labels
