### ISSUE TITLE
Poor method signatures in Android.Opengl.EGL14

### ISSUE THREAD

**Issue by guygodin** [xamarin/xamarin-android#1357]
### Steps to Reproduce

1. Look at the Android.Opengl.EGL14 methods. For example:
EglInitialize(EGLDisplay dpy, int[] major, int majorOffset, int[] minor, int minorOffset);

2. The methods have essentially "out" parameters but instead of being exposed as such, they are exposed as arrays with an additional offset argument.

### Expected Behavior

Signature should be like this:

EglInitialize(EGLDisplay dpy, out int major, out int minor);

### Version Information

Microsoft Visual Studio Community 2017 
Version 15.5.7
VisualStudio.15.Release/15.5.7+27130.2036
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA324
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA324
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA324
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA324
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31129.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27005.02
Visual C++ for Cross Platform Mobile Development (Android)

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27130.2036
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.8.0.760 (fc93f3f5b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.8.188 (c5813fa34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.1.5.0 (HEAD/75f8c6838)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.6.1.4 (db807ec)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonpryor** [comment]
For *most* Java methods, we bind them as "directly" as possible. The [`EGL14.eglInitialize()`](https://developer.android.com/reference/android/opengl/EGL14.html#eglInitialize(android.opengl.EGLDisplay,%20int[],%20int,%20int[],%20int)) signature is unchanged from Java.

That doesn't mean it couldn't be improved.

To fix this issue:

1. Create a new `src/Mono.Android/Android.Opengl/EGL14.cs` file.
2. The `src/Mono.Android/Android.Opengl/EGL14.cs` file would declare the new `EglInitialize()` overload.

For example:

```csharp
namespace Android.Opengl {
    partial class EGL14 {
#if ANDROID_17
        public bool EglInitialize (EGLDisplay dpy, out int major, out int minor)
        {
            var ma = new int[1];
            var mi = new int[1];
            var r  = EglInitialize (dpy, ma, 0, mi, 0);
            major = ma [0];
            minor = mi [0];
            return r;
        }
#endif  // ANDROID_17
    }
}
```

**Comment by guygodin** [comment]
Thanks for the response,
a stackalloc would be preferable here assuming the EglInitialize can take in a int*

This example is not something called often but there might be other methods where allocating these arrays constantly will put pressure on the GC

**Comment by bruno-garcia** [comment]
Is this task still relevant? I'd like to try contributing to this project.
Also, note it's the only task labled `good-first-issue` ;)
