### ISSUE TITLE
Distribute after Archiving solution not working.

### ISSUE THREAD

**Issue by akatriel** [xamarin/xamarin-android#1372]
### Steps to Reproduce

1. archive Solution
2. Press Distribute

### Expected Behavior
The Distribution Channel is expected to open, allowing the user to select Ad Hoc or Google Play distribution methods.
### Actual Behavior
Nothing Appears.
### Version Information
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual Basic 2015   00322-40000-00000-AA121
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA121
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA121
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-40000-00000-AA121
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Clang with Microsoft CodeGen   14.0.25516
Clang with Microsoft CodeGen

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.50113.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.50113.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.50113.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual C++ for Cross Platform Mobile Development (Android)   14.0.25401.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   14.0.25401.00
Visual C++ for Cross Platform Mobile Development (iOS)

Visual Studio Tools for Apache Cordova   Update 10
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.749 (9b0fce36d)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.58 (cee1369d0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.15 (HEAD/22d97e153)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS   11.8.0.20 (1c6f300)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS and Xamarin.Mac SDK   11.8.0.20 (1c6f300)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```
### Log File
Switch to the "Preview" tab to ensure your issue renders correctly.
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin|Information|0|Xamarin - 4.9.0.749-d15-6+9b0fce36d
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin.VisualStudio.Android.XamarinAndroidPackage|Warning|0|Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage
Xamarin.Inspector|Information|0|Inspector extension loaded
Xamarin.VisualStudio.ProjectFixerRunner|Information|0|Solution loaded: 'TransportACE'
Xamarin.VisualStudio.ProjectFixerRunner|Information|0|running fixup on project 'C:\Apacheta_Projects\CoreApps-2012\TransportACE\TransportACE.Droid\TransportACE.Droid.csproj'
Xamarin.VisualStudio.ProjectFixerRunner|Information|0|running fixup on project 'C:\Apacheta_Projects\CoreApps-2012\TransportACE\TransportACE.Shared\TransportACE.Shared.Android.csproj'
Xamarin.VisualStudio.Android.ContinuousPlayerDeviceProvider|Information|0|Live Player started.
Xamarin.VisualStudio.UnhandledExceptionsManager|Error|0|An unhandled error occurred. Details: Sequence contains no matching element

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source, Func`2 predicate)
   at x..ctor(BuildViewModel buildViewModel, IDistributionManager distributionManager, IProgressReportService progressReportService, IAsyncManager asyncManager) in E:\A\_work\61\s\src\Core\VisualStudio.Publishing\Presentation\ViewModels\AndroidDistributeViewModel.cs:line 234
   at Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel.<ShowAndroidDistributeDialog>d__55.MoveNext() in E:\A\_work\61\s\src\Core\VisualStudio.Publishing\Presentation\ViewModels\ArchiveListViewModel.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by brendanzagaeski** [comment]
**Cross-referencing note to the Xamarin team**

Also reported by the same user from this GitHub report in Xamarin's Bugzilla:
<https://bugzilla.xamarin.com/show_bug.cgi?id=61251>

(Based on an initial glance at the stack trace, it looks like the issue might not involve the Xamarin.Android repository, so the Visual Studio Tools for Xamarin team might end up tracking this issue in Bugzilla.)

**Comment by joj** [comment]
We have identified the issue and will be working on a fix. The bug is not on xamarin-android, though. It's on our tooling. I'm adding a parallel issue in our internal tracking but will be keeping this updated so everyone can know what's happening here.

**Comment by joj** [comment]
Side comment: this issue is specific to 2015. Upgrading to 2017 (even on the free Community edition) will immediately fix it. We'll still be working on a 2015 fix.

**Comment by brendanzagaeski** [comment]
Tallying other user reports for bookkeeping

2 users: <https://forums.xamarin.com/discussion/123412> (2018-03-06 to 2018-03-07)

**Comment by creaworlds** [comment]
I have the same problem.

**Comment by brendanzagaeski** [comment]
As a small recommendation, users who would like to tally themselves on this report can use a ":+1:" reaction on the initial description comment of this item at the top of the page, for ease of tallying.

**Comment by brendanzagaeski** [comment]
**Old version downloads, if needed**

For users who cannot yet update to Visual Studio 2017 (recommended when possible) and who would like to switch back temporarily to the previous version of the Visual Studio 2015 Tools for Xamarin, that version (along with the corresponding packages for the paired Mac if needed) can now be found under "Get the previous servicing update of 15.5" section on [the old Xamarin account page](https://store.xamarin.com/account/my/subscription/downloads). If you don't currently have a login for that page, you can create one at <https://www.xamarin.com/account/register>.

**Comment by messiahh** [comment]
I have same problem :(

**Comment by Waqas-Zamir** [comment]
I have the same problem 👎 
And it is blocking me to release my application to testing department.

**Comment by messiahh** [comment]
Any news?

**Comment by sk1llsh0t** [comment]
I've got the same problem. Can't build new release until this is fixed. What a time to tell users that all focus is now on VS 2017 right after completely crippling VS 2015 with no fix in sight.

**Comment by brendanzagaeski** [comment]
For users who are unable to switch back temporarily to the [previous version of the Visual Studio 2015 Tools for Xamarin](https://github.com/xamarin/xamarin-android/issues/1372#issuecomment-372428664), note that it is also possible to complete the signing and distribution process manually:

- https://docs.microsoft.com/xamarin/android/deploy-test/signing/manually-signing-the-apk
    - (Another alternative for this step is to use the [`SignAndroidPackage` target](https://docs.microsoft.com/xamarin/android/deploy-test/building-apps/build-process#Build_Targets) in combination with the [Packaging Properties](https://docs.microsoft.com/xamarin/android/deploy-test/building-apps/build-process#packaging-properties) and [Signing Properties](https://docs.microsoft.com/xamarin/android/deploy-test/building-apps/build-process#Signing_Properties) to create the signed package via the build targets, for example using a command-line `msbuild` build command.)
- https://docs.microsoft.com/xamarin/android/deploy-test/publishing/publishing-to-google-play/manually-uploading-the-apk

**Comment by messiahh** [comment]
Someone updated VS 2015?  its correct now?

**Comment by sk1llsh0t** [comment]
Not yet

**Comment by sk1llsh0t** [comment]
https://store.xamarin.com/account/my/subscription/downloads

If you login to your xamarin account and go to the downloads section, there is an older version link which lets you downgrade to a working version.

**Comment by gokulakshay** [comment]
Not yet?

**Comment by sk1llsh0t** [comment]
no

**Comment by tdsrhh** [comment]
Any news on this ?

**Comment by tdsrhh** [comment]
Anyone from Xamarin have any feedback what is happening on this issue ?

**Comment by risk2k** [comment]
Nothinh happened. Problem in cs2015 stay. Distribute not work. Updates not change situation.

**Comment by yohothemole** [comment]
Can someone please tell me where to get the Xamarin download that will re-allow APK distribution in VS2015?  I've followed every link I've seen and am no nearer an answer.  I've got internal customers breathing down my neck, can't immediately port to VS2017 and am getting nowhere with manual signing.  Please help - not waving but drowning!

**Comment by bblaszkiewicz** [comment]
You can compile app in VS2015 and then sign it in Xamarin Studio

**Comment by yohothemole** [comment]
Thanks bblaszkiewicz.  I don't have Xamarin Studio, since VS is supposedly the way forward.  Not  sure I fancy trying to get it and set it up just for signing.

**Comment by brendanzagaeski** [comment]
_Updated information about old version downloads_

> can now be found under "Get the previous servicing update of 15.5" section on the old Xamarin account page

This information from my earlier comment is now outdated. The old Xamarin account page has now been retired, so instead here is a direct link to the previous version of Visual Studio 2015 Tools for Xamarin (aligned with the Visual Studio 2017 version 15.5.5 release):

[Visual Studio 2015 Tools for Xamarin version 4.8.0.760](https://dl.xamarin.com/XamarinforVisualStudio/Windows/Xamarin.VisualStudio_4.8.0.1289738.msi)

**Comment by renishdadhaniya** [comment]
When will this issue fix? 
Tired of revoking to older version

**Comment by wegascee** [comment]
I think this issue will never be fixed, because they want that you switch to VS 2017. Why should they fix for an old product?

Instead of downgrading you can also [manually sign the apk](https://docs.microsoft.com/de-de/xamarin/android/deploy-test/signing/manually-signing-the-apk#sign-the-apk).

**Comment by hadigityat** [comment]
I have the Visual Studio 2019 version 8.5, and I have been dealing with this issue since VS 2017 so it is not fixed in newer version also.

**Comment by brendanzagaeski** [comment]
@hadigityat , if you are seeing a similar issue in Visual Studio 2019 for Mac, I would recommend submitting a new feedback item via **Help > Report a Problem** so the team can investigate. It sounds like it might be a slightly different problem from the original problem on this old issue, so I think the Visual Studio for Mac team would be interested to take a look. Thanks in advance!

**Comment by jpobst** [comment]
This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

If this is still an issue, please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
