### ISSUE TITLE
Add java-interop.jar to the Xamarin.Android install set

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1375]
The [Android Designer currently has it's own copy of many of our core types](https://github.com/xamarin/md-addins/commit/4bd9fe7a04cbf95348a5a1f34f6c14023fb90b5f), which means if we alter this set of core types, things break.

`java-interop.jar`, part of the Java.Interop build, already contains many of these types.

We should update the Xamarin.Android SDK build to install `java-interop.jar`, and ensure that *all* types which the Android Designer requires are within that file.

**Comment by jpobst** [comment]
Probably no longer relevant.
