### ISSUE TITLE
Cannot deploy if Java 9 installed together with Java 8

### ISSUE THREAD

**Issue by rihadavid** [xamarin/xamarin-android#1383]
Just a quick bug report. I updated to latest VS, 15.6.1, and my Android project just could not be deployed on any device, getting all kinds of errors, like ``Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION]`` or ``Android/sdk/tools/lib is not supported. Use -classpath instead.`` or ``Error: Could not create the Java Virtual Machine.`` or ``device does not exist or its version is less than project minimum API version 15``

Solved by **uninstalling** Java 9 and also the 1.9 JDK, keeping only 8 and 1.8 and updating the Java 8 to latest version.

If you want to reproduce, try installing Java 9.

NOTE: I did not try to use the 9/1.9 explicitly, just the fact that it was installed together with 8/1.8 caused the problems.

**Comment by rihadavid** [comment]
Yes, I had and it worked. Again, I also had the Java 8 installed. The update messed things up, I guess.

**Comment by IoTFier** [comment]
I am in the same boat as @rihadavid. 
**Everything was working with Java 9 and Java 8 installed side by side on my PC up until 15.5.6
Please look at the issue I just published which ties with this one - https://github.com/xamarin/xamarin-android/issues/1392**

Hi @cobey  - I had used to the link you pasted above - **I uninstalled all Java 9 and Java 8 versions, followed by installation of the JDK 8.162 alone on my machine. The resultant is still horrible. The studio loading is , solution building is crawling and debug deployment is pathetic.**

**Comment by JonDouglas** [comment]
I am closing this issue given that Xamarin.Android does not support JDK 9 at this time, and it documented in the following location:

https://developer.xamarin.com/guides/android/troubleshooting/questions/jdk9-errors/

If you are still running into issues with JDK 9, ensure it's off the path and not linked anywhere.
