### ISSUE TITLE
BCL test 'TaskSchedulerTests.GetTaskSchedulersForDebugger_ReturnsDefaultScheduler' fails when the linker is enabled.

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1400]
One of the "recently" added XUnit BCL tests is failing on Android when the linker is enabled. Could we update the test to make sure the needed components aren't linked away, or perhaps add a custom linker configuration to the XA BCL test project to preserve what is needed?

### Steps to Reproduce

1. Run the following test source in an XA app targeting the default 'Release' configuration (or enable thelinker).

https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks/tests/TaskScheduler/TaskSchedulerTests.cs#L295

### Version Information
XA d15-7 (8.3.0.5)

### Log File

```xml
<test-case name="System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_ReturnsDefaultScheduler" executed="True" result="Failure" success="False" time="0.0013152">
```

```
System.NullReferenceException : Object reference not set to an instance of an object</message>
  at System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_ReturnsDefaultScheduler () [0x00019] in &lt;219485eabbb44d4fab42e790fa0e4a65&gt;:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in &lt;7aedcdbd71b44fa6900d0e8ce879bddf&gt;:0
```

**Comment by marek-safar** [comment]
The first test line is a reflection call which is most likely removed by linker and that's fine.

I think setting `TargetFrameworkMonikers.UapAot` could be one way how to ignore such tests as there will be many more like this one

**Comment by jonpryor** [comment]
@marek-safar wrote:

> I think setting `TargetFrameworkMonikers.UapAot` could be one way how to ignore such tests as there will be many more like this one

I do not understand what that means. How do we do that?

**Comment by marek-safar** [comment]
I don't know how you call xunit but for the console we'd use `-notrait category=nonuapaottests` arguments

see https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/XunitConstants.cs

**Comment by grendello** [comment]
@jonp https://github.com/xamarin/xamarin-android/pull/1421 makes the XUnit test runner ignore the category @marek-safar mentioned

**Comment by marek-safar** [comment]
I looked at this again and the test is just wrong for whole Mono. I'll try to disable it in a different way but you can certainly ignore it for now.

The `TargetFrameworkMonikers.UapAot` change is a quick hack so ideally, we should not do it as we are working with CoreFX folks to come up with better categorization for such scenarios.

**Comment by jonpryor** [comment]
@marek-safar: is there an "upstream bug" we can track for the "disable it in a different way" effort, so that we can re-enable the `nonuapaottests` in the future? Or will we *never* want to re-enable `nonuapaottests`, period?
