### ISSUE TITLE
When "Use Shared Runtime" is unchecked, any code changes aren't picked up

### ISSUE THREAD

**Issue by guygodin** [xamarin/xamarin-android#1405]
### Steps to Reproduce

1. In Xamarin Android project settings, uncheck "Use Shared Runtime"
2. Select armembi-v7a as the only supported platform
3. Run a simple Hello World app by pressing F5
4. Stop debugging
5. Comment out a line of code
6. Run again with F5

### Expected Behavior

The changes should be picked up and the commented out line shouldn't execute

### Actual Behavior

The commented out line is still executed. Changes to the source code are not deployed

### Version Information
Microsoft Visual Studio Community 2017 
Version 15.6.1
VisualStudio.15.Release/15.6.1+27428.2002
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA324
Microsoft Visual C++ 2017

Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA324
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10212.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40214.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

C# Tools   2.7.0-beta3-62620-07. Commit Hash: e873e69306527a0424e97af2985370556f474019
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62620-07. Commit Hash: e873e69306527a0424e97af2985370556f474019
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27406.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.749 (9b0fce36d)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.58 (cee1369d0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.15 (HEAD/22d97e153)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.8.0.20 (1c6f300)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

Xenko.VisualStudio.Package   2.0
Xenko VisualStudio Package

> VS bug [#621197](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/621197)

**Comment by pjcollins** [comment]
@guygodin I was unable to reproduce this using VS2017 15.6.2 (XA 8.2.0.15) with the following steps:
1) Create a new Single-View App (Android)
2) Open Project Properties -> Android Options -> Uncheck "Use Shared Runtime".
3) Add the following lines to the end of the OnCreate method:
```csharp
Android.Util.Log.Debug("TAG", "First debug line.");
Android.Util.Log.Debug("TAG", "Second debug line.");
```

4) Start debugging on device (F5), check output for both logging messages.
5) Stop debugging (Shift+F5), comment out the line containing `"First debug line."`.
6) Start debugging on device (F5), check output for both logging messages.

After step 6, I only see the message for the non-commented line `"Second debug line`"`. Could you provide more explicit steps which reproduce the negative behavior you're seeing?

**Comment by guygodin** [comment]
Hi pj, I just tested again using your repro steps on 2 different Android devices and was able to repro the bug on one of them (Android 7.1 - API 25) but not on another (Galaxy S8+, Android 7.0 - API 24). I can't give specifics about the hardware of the first device which reproduces the issue. Any clues on what could be causing this? I don't have this issue when I select the arm64-v8a platform. Feel free to reach out to me in private.

Thanks
Guy

**Comment by stmax82** [comment]
Occasionally we notice that code changes aren't picked up until you clean & rebuild the project. Though we've never been able to reliably reproduce that problem on a small example project. Though we always have "Use Shared Runtime" checked, so there might be other / similar problems lurking in the build system..

**Comment by jonathanpeppers** [comment]
### How to reproduce

Here are the convoluted steps to cause this _every_ time:

1. File -> New Master/Detail Xamarin.Forms project, only checked Android, chose netstandard
1. Launch 2 emulators (you could also use combination of device/emulator, doesn't matter)
1. Deploy to emulator 1
1. Deploy to emulator 2
1. Turn Fast Deployment OFF - (Use Shared Runtime and Use Fast Deployment unchecked)
1. Make a code change, I made the "About" page say "Bazinga Platform" instead of "Xamarin Platform", and also added a `public static int Test = 1234;` field to `App.xaml.cs` so I could easily see if assemblies changed with ILSpy.
1. Deploy to emulator 2
1. Code changes are not deployed

_NOTE: on step 5, I also had to enable the x86 ABI by adding `<AndroidSupportedAbis>armeabi-v7a;x86</AndroidSupportedAbis>`_

### What went wrong?

Using ILSpy my code changes are making it there all the way throughout our intermediate folders, inside the APK, etc.

If I look in `/storage/emulated/0/Android/data/com.companyname/files/.__override__` there are copies of outdated assemblies for the app. These are getting loaded instead of my code changes!

### To fix it

Delete all files in `/storage/emulated/0/Android/data/com.companyname/files/.__override__`.

Or uninstall the app.

### Conclusion

So whatever is going wrong here is happening to developers during their normal workflow.

I think they are hitting this because:
- Developers commonly switch between emulator and device
- There is something else wrong with Fast Deployment, and developers have gotten into the habit of turning it off when something breaks

I'm doing some further investigation on the second point, as I feel like there is a second issue there to fix.

**Comment by jonathanpeppers** [comment]
Updating my comment above ^^ , it appears this issue is worse than I thought. You can reproduce with a single device.
