### ISSUE TITLE
Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

### ISSUE THREAD

**Issue by ghost** [xamarin/xamarin-android#1408]
Hi,

After last release of my app I found some report crash of this kind

```
Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
md57b20ac4f34a29c338d6e74091e4009c4.AdapterAntComune.n_getItemCount(Native Method)
md57b20ac4f34a29c338d6e74091e4009c4.AdapterAntComune.getItemCount(AdapterAntComune.java:49)
android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3603)
android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3408)
android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
android.widget.FrameLayout.onLayout(FrameLayout.java:273)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
android.widget.FrameLayout.onLayout(FrameLayout.java:273)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
android.widget.FrameLayout.onLayout(FrameLayout.java:273)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
android.widget.FrameLayout.onLayout(FrameLayout.java:273)
com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
android.view.View.layout(View.java:16708)
android.view.ViewGroup.layout(ViewGroup.java:5482)
android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2228)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1981)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1140)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6239)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
android.view.Choreographer.doCallbacks(Choreographer.java:670)
android.view.Choreographer.doFrame(Choreographer.java:606)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5551)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

I am unable to reproduce this error, the collection used in the adapter it's a JavaList<T> and it is never null (may be empty, but _not_ null).

Users with this problem use Android 6.0.1 or 7.0.  Can be a problem with the GC?

Regards,

**Comment by jonpryor** [comment]
That stack trace appears to be incomplete: the topmost exception is a [`Java.Interop.JavaLocationException`](https://github.com/xamarin/xamarin-android/blob/8ce253769a4b38de51ba22ccfb2c38dd5c852f9f/src/Mono.Android/Java.Interop/TypeManager.cs#L197-L201), which is [generally](https://github.com/xamarin/xamarin-android/blob/8ce253769a4b38de51ba22ccfb2c38dd5c852f9f/src/Mono.Android/Java.Interop/TypeManager.cs#L152-L154) [thrown](https://github.com/xamarin/xamarin-android/blob/8ce253769a4b38de51ba22ccfb2c38dd5c852f9f/src/Mono.Android/Java.Interop/TypeManager.cs#L194) [as a nested](https://github.com/xamarin/xamarin-android/blob/8ce253769a4b38de51ba22ccfb2c38dd5c852f9f/src/Mono.Android/Java.Interop/TypeManager.cs#L152-L154) [exception](https://github.com/xamarin/xamarin-android/blob/8ce253769a4b38de51ba22ccfb2c38dd5c852f9f/src/Mono.Android/Java.Interop/TypeManager.cs#L260-L263).

Thus, I have to ask: what's the *full* stack trace? If it's a `NotSupportedException("Unable to activate instance of type")`, then it *could* be due to a GC problem, or it *could* be because you're using an i instance after having explicitly disposed of it.

You might want to enable GREF logging to track the instances lifetime.

**Comment by lfongaroScp** [comment]
I have only that stacktrace. :-(
In my app I create the adapter in "OnResume()" and I dispose it in the OnPause(). Can be this the problem?

**Comment by jonpryor** [comment]
> In my app I create the adapter in "OnResume()" and I dispose it in the OnPause()

Possibly. (Remove the `.Dispose()` and see what happens!)

What's *plausible* is that some Java code is holding onto the `AdapterAntComune` instance and invoking methods on it *after* the `OnPause()` method is invoked (animations?). So long as Java code can invoke methods on the `AdapterAntComune` instance after you `Dispose()` it, you will get a `NotSupportedException`.

You should only `Dispose()` instances when you *absolutely* know that nothing else will be using them. This is not always possible, in which case you should let the GC handle it.

**Comment by justintoth** [comment]
I'm seeing the same exception be logged in our prod app.

> Java.Interop.JavaLocationException
> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
> Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
> java.lang.Error: Java callstack:
> md55e721fba4c4933700d4b18d6214b7731.BasePropertyPhotoAdapter.n_getCount(Native Method)
> md55e721fba4c4933700d4b18d6214b7731.BasePropertyPhotoAdapter.getCount(BasePropertyPhotoAdapter.java:48)
> android.support.v4.view.ViewPager.draw(ViewPager.java:2432)
> android.view.View.draw(View.java:20345)
> android.view.ViewGroup.drawChild(ViewGroup.java:4459)
> ...

The code is very straightforward in the BasePropertyPhotoAdapter Count method, so I'm not sure what could possibly be the issue here (except a Xamarin bug?)

```
public override int Count {
            get {
                return photoUrls != null ? photoUrls.Count : 0;
            }
        }
```

**Comment by transis2** [comment]
For me it happens on -> LabelRenderer.onTouchEvent

Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
md5f92e0daf340890c9667469657ee2ece8.LabelRenderer.n_onTouchEvent(Native Method)
md5f92e0daf340890c9667469657ee2ece8.LabelRenderer.onTouchEvent(:54)
android.view.View.dispatchTouchEvent View.java:12629
android.view.ViewGroup.dispatchTransformedTouchEvent ViewGroup.java:3142
android.view.ViewGroup.cancelAndClearTouchTargets ViewGroup.java:2992
android.view.ViewGroup.dispatchDetachedFromWindow ViewGroup.java:3896
android.view.ViewGroup.dispatchDetachedFromWindow ViewGroup.java:3916
android.view.ViewGroup.removeViewInternal ViewGroup.java:5471
android.view.ViewGroup.removeViewInternal ViewGroup.java:5442
android.view.ViewGroup.removeView ViewGroup.java:5373
md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.n_onConfigurationChanged(Native Method)
md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.onConfigurationChanged(:48)
android.app.ActivityThread.performActivityConfigurationChanged ActivityThread.java:5206
android.app.ActivityThread.performConfigurationChangedForActivity ActivityThread.java:5060
android.app.ActivityThread.performConfigurationChangedForActivity ActivityThread.java:5038
android.app.ActivityThread.handleActivityConfigurationChanged ActivityThread.java:5464
android.app.ActivityThread$H.handleMessage ActivityThread.java:1866
android.os.Handler.dispatchMessage Handler.java:106
android.os.Looper.loop Looper.java:164
android.app.ActivityThread.main ActivityThread.java:7000
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:441
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1408

**Comment by jonathanpeppers** [comment]
I think what we're missing here is a sample app. Can you reproduce this in a small project with the latest Xamarin.Android?

Thanks!
