### ISSUE TITLE
SDK Manager does not seem to work? SDK26 is both installed and not installed

### ISSUE THREAD

**Issue by uwantfries** [xamarin/xamarin-android#1409]
### Steps to Reproduce

1. Try to install Oreo as a demo project needs that SDK for some reason
2. Run the SDK manager and install SDK 26 (on VS2017)
3. Do the build - Error: Could not find android.jar for API Level 26. This means the Android SDK platform for API Level 26 is not installed. Either install it in the Android SDK Manager (Tools > Open Android SDK Manager...), or change your Xamarin.Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\android-26\android.jar missing.)	AndroidSample	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	582	

4. Check the Android SDK manager - SDK 26 is not installed. See screenshot.

![sdk26](https://user-images.githubusercontent.com/9169211/37350389-9c1bfb7a-26d0-11e8-9b3d-13b7c43c65f5.PNG)

### Expected Behavior
Should do the same as the Google SDK manager

### Actual Behavior
SDK is listed as installed but is not properly. Directory is there but is mostly empty

### Version Information
Microsoft Visual Studio Enterprise 2017 
Version 15.5.5
VisualStudio.15.Release/15.5.5+27130.2026
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual Basic 2017   00369-60000-00001-AA928
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA928
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA928
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27130.2020
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.8.0.760 (fc93f3f5b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.8.188 (c5813fa34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.1.5.0 (HEAD/75f8c6838)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.6.1.4 (db807ec)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by IoTFier** [comment]
Hi @uwantfries , I had run into similar problem.

I would suggest you to update your android platform via Android Studio / Tools option first.
If interested follow the steps I posted at https://forums.xamarin.com/discussion/comment/323226#Comment_323226

Good luck on the product hacking to keep our passion alive 👍

**Comment by joj** [comment]
Hi! Do you actually have this directory `C:\Program Files (x86)\Android\android-sdk\platforms\android-26` and android.jar in it? I need to investigate the issue but that info will be super useful.

**Comment by IoTFier** [comment]
Yes. That directory with the android.jar does exist on my machine.

**Comment by joj** [comment]
@uwantfries what about you? do you see that directory too?

**Comment by uwantfries** [comment]
I had the directory but there was no jar file in there (but 3/4 subidirs
from what I remember) . I have subsequently run the google SDK and all is
now well.

Current contents are:

 Directory of C:\Program Files
(x86)\Android\android-sdk\platforms\android-26
13/03/18  17:07    <DIR>          .
13/03/18  17:07    <DIR>          ..
13/03/18  15:14         3,315,894 android-stubs-src.jar
13/03/18  15:14        26,467,929 android.jar
13/03/18  15:14             2,186 build.prop
13/03/18  15:14    <DIR>          data
13/03/18  15:14             9,365 framework.aidl
13/03/18  15:14    <DIR>          optional
13/03/18  17:07            17,354 package.xml
13/03/18  15:14               209 sdk.properties
13/03/18  15:14    <DIR>          skins
13/03/18  15:14            16,948 source.properties
13/03/18  15:14    <DIR>          templates
13/03/18  15:14            10,458 uiautomator.jar
               8 File(s)     29,840,343 bytes

**Comment by IoTFier** [comment]
My directory content are -
![image](https://user-images.githubusercontent.com/26844611/37475529-ec502bb8-2840-11e8-8a4d-1d229918b733.png)

**Comment by jonathanpeppers** [comment]
Let us know if you are still running into this, but we would now recommend SDK Manager issues to be filed with the IDE team going forward:

![image](https://user-images.githubusercontent.com/840039/175078659-ca01cb33-c4b6-4e94-86b4-0ec0a6cce7ef.png)

Such as:  https://developercommunity.visualstudio.com/report?entry=problem

Closing for now, as this is not an issue in the xamarin/xamarin-android repo. Thanks!
