### ISSUE TITLE
Typo in developer.xamarin.com

### ISSUE THREAD

**Issue by dehghani-mehdi** [xamarin/xamarin-android#1424]
In following page you miss `,` after `Intent.CategorySampleCode}` : https://developer.xamarin.com/api/type/Android.App.IntentFilterAttribute/

For ref:
```
[Activity]
[IntentFilter (new[]{Intent.ActionMain},
    Categories=new[]{Intent.CategoryLauncher, Intent.CategorySampleCode}
    Icon="@drawable/myicon",
    DataScheme="something",
    DataHost="project.example.com")]
public class MyActivity : Activity
{
}
```

**Comment by jpobst** [comment]
This sample no longer appears to be on that page, so I guess this is obsolete now.
