### ISSUE TITLE
Cannot enable "INTERNET" permission on AndroidManifest.xml dialog

### ISSUE THREAD

**Issue by knocte** [xamarin/xamarin-android#1442]
### Steps to Reproduce

1. Open a solution where you have a xamarin-android project, with VSforMac.
2. Right click on the project -> Options.
3. On the left panel, click on Build->Android Application.
4. On the 'Required permissions' listview, scroll until you see the [ ] INTERNET checkbox
5. Check the [x] INTERNET checkbox to be enabled.
5. Close dialog.
(Effect: the .csproj gets changed with a change like the represented in this diff:
```
 	<uses-sdk android:minSdkVersion="15" />
+	<uses-permission android:name="android.permission.INTERNET" />
 	<application android:label="gwallet" android:icon="@drawable/icon"></application>
 </manifest>
```
6. Perform steps 2, 3, 4 again.

### Expected Behavior
You should see the [ ] INTERNET checkbox checked ([x]).

### Actual Behavior
You see two [ ] INTERNET checkboxes, one checked and with red colour, and one unchecked. If you hover over the one in red, you see the text:
```
android.permission.INTERNET
Unknown Permission
```
See also screenshot:
![screen shot 2018-03-19 at 12 18 01 pm](https://user-images.githubusercontent.com/331303/37595849-2c077cee-2bb5-11e8-9af1-1585c3cf18d4.png)

### Version Information
```
Visual Studio Community 2017 for Mac
Version 7.4 (build 1033)
Installation UUID: fd06ff65-69de-47ae-8b99-ddf257032b7c
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Mac
Version: 4.2.0.20 (Visual Studio Community)

Xamarin.iOS
Version: 11.8.0.20 (Visual Studio Community)
Hash: 1c6f300e
Branch: d15-6
Build date: 2018-02-07 23:42:40-0500

Xamarin.Android
Version: 8.2.0.15 (Visual Studio Community)
Android SDK: /Users/andres/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.13.1
Darwin 17.2.0 Darwin Kernel Version 17.2.0
    Fri Sep 29 18:27:05 PDT 2017
    root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1

```

### Log File
N/A?

**Comment by bratsche** [comment]
Tracking this on DC https://developercommunity.visualstudio.com/content/problem/221083/cannot-enable-internet-permission-on-androidmanife.html

**Comment by knocte** [comment]
If you track it this way, how can I know when its fix is released?

**Comment by sgmunn** [comment]
Issues for Visual Studio for Mac are tracked on developercommunity.visualstudio.com, the DevComm issue status will be updated when a fix is pending release and again when it is released. We do not track GitHub issues logged against the SDK products in our release (as they are different products).

**Comment by bratsche** [comment]
I have the same version of VSMac installed and I'm not able to reproduce this. When I open preferences and scroll down in the required permissions I see Internet checked.

<img width="947" alt="screen shot 2018-03-22 at 6 48 38 pm" src="https://user-images.githubusercontent.com/2041/37804321-b64e8214-2e01-11e8-9617-ab797da89b4f.png">

**Comment by knocte** [comment]
Mmm, that screenshot is showing the options in PascalCase instead of IN_UPPERCASE_WITH_UNDERSCORES. There's certainly something different between my version and yours.

**Comment by bratsche** [comment]
@knocte Are all of your permissions showing up in `UPPERCASE_WITH_UNDERSCORES` or only some of them?

**Comment by knocte** [comment]
> @knocte Are all of your permissions showing up in UPPERCASE_WITH_UNDERSCORES or only some of them?

@bratsche: all of them.

**Comment by knocte** [comment]
I still see this bug after a new VS4Mac update (now in 7.4.1 build 48).

**Comment by clovyclov** [comment]
Im seeing this bug too

**Comment by knocte** [comment]
Yeah it's still there and for any permission in the manifest, not only INTERNET.

**Comment by clovyclov** [comment]
Figured it out, at least for me. Turns out the issue was me turning off the network connection and wifi on the emulator. The phone apparently throws an exception when it can't connect to the internet.

**Comment by RVoiseyFirstApp** [comment]
For me was an issue with the TargetAndroidVersion in the manifest overriding the Target framework in the build settings. Setting them to the same value corrected the problem.

Could also be because there was changes to the way permissions worked in the version I was targetting in the manifest (24) to the way they work in the latest (8.1), i.e. permissions have to be requested at runtime.

Hope this helps someone.

**Comment by knocte** [comment]
@bratsche just realized this problem is specific to F# projects, C# is not affected.

**Comment by sgmunn** [comment]
Thanks for the update

**Comment by knocte** [comment]
Mmm, weird, I created a new Xamarin.Forms blank app project in C# and didn't see the bug.
