### ISSUE TITLE
Xamarin Firebase Unregistered token

### ISSUE THREAD

**Issue by emilmuller** [xamarin/xamarin-android#1460]
### Steps to Reproduce

1. Install the Xamarin Firebase Messaging NuGet package and set up everything
2. Go to Firebase console and send a test message to a device associated with a token
3. Message does not get delivered and Firebase console complains that the token is unregistered

Not sure if this is the right place to report the bug.

Anyhow, I ended up getting this to work by adding this to the manifest:

```
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <receiver
    android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
    android:exported="true"
    android:permission="com.google.android.c2dm.permission.SEND" >
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />

        <category android:name="com.myapp.foo" />
      </intent-filter>
    </receiver>
    <receiver
    android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver"
    android:exported="false" />
```

This is what Android Studio adds when adding Firebase from there.

Don't see this mentioned in any guide. Just recently started having issues with Firebase in a new app.

**Comment by atsushieno** [comment]
Sounds like an issue for https://github.com/xamarin/GooglePlayServicesComponents/ .

**Comment by emilmuller** [comment]
Reported it there.
I guess this can be closed now :)
