### ISSUE TITLE
Add support for appt2

### ISSUE THREAD

**Issue by cobey** [xamarin/xamarin-android#1468]
We should migrate our build process to utilize aapt2 when available, leaving aapt as a fallback option for legacy support. 

https://android.googlesource.com/platform/frameworks/base/+/android-7.0.0_r7/tools/aapt2

> VS bug [#593491](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593491)

**Comment by pjcollins** [comment]
I'd like to remove the `vs-sync` tag here as we have now have an experience and user story currently tracking this task. I will remove the sync and close the corresponding bug and link to this mention on one of the parent items.
