### ISSUE TITLE
VS 15.6.4 - Xamarin Android App - Intallation Errors: XA5209 Unzipping failed

### ISSUE THREAD

**Issue by IoTFier** [xamarin/xamarin-android#1475]
### Steps to Reproduce

1. In VS 2017 15.6.4 create a Xamarin.Forms app using MasterDetail template and .Net Core library option
2.  You will see the error during creation of the Xamarin.Android project as well as during the rebuild process. ( VS 2017 15.7.2 preview doesn't throw this error. I have that preview running on my same PC in side by side )
3.  Sample project attached as below - 
[XF1564Apps.zip](https://github.com/xamarin/xamarin-android/files/1849135/XF1564Apps.zip)

### Expected Behavior
Application to be created and compiled 
### Actual Behavior

_**Expected behavior is Visual Studio GA release to work flawlessely without causing our productivity loss. These releases have utterly poor quality. Please have a rigor to test VS Xamarin releases on both MAC and Windows tested thoroughly. We don't need Xamarin engineering team members just to support and celebrate Apple platform for the delivery. This is really getting annoying. Please improve quality, performance and stability in these releases.**_

**See the console output attached below -**
..............................

Severity Code Description Project File Line Suppression State
Error An error occurred trying to install required android components on Project 'XFHello1564.Android'.
Project 'XFHello1564.Android' requires the following components installed on your machine: 
Xamarin.Android.Support.CustomTabs
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/customtabs/23.3.0/customtabs-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/customtabs/23.3.0/customtabs-23.3.0.aar-23.3.0.0

Please double-click here to install it.

Intallation Errors: XA5209 Unzipping failed. Please download 'https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip' and extract it to the 'C:\Users*\AppData\Local\Xamarin\Xamarin.Android.Support.CustomTabs\23.3.0.0\content' directory
XA5209 Reason: Could not find a part of the path 'C:\Users*\AppData\Local\Xamarin\Xamarin.Android.Support.CustomTabs\23.3.0.0\content\m2repository\'.
XA5207 Please install package: 'Xamarin.Android.Support.CustomTabs' available in SDK installer. Java library file 'C:\Users*\AppData\Local\Xamarin\Xamarin.Android.Support.CustomTabs\23.3.0.0\content\classes.jar' doesn't exist. 0 

..............................

**A warning displayed as -** 
The project type included Xamarin Forms app using master detail and .net core library options. Target OS included Andorid, iOS and UWP. 
..............................
**Cleaning of the solution fails as well** 
Cleaning of the solution also throws error on the windows status bar with the message "Clean Cancelled"

### Version Information
Windows 10 64 bit; VS 2017 15.6.4| Andoroid  API min 23 max 27| VS Android Emulator using API 23

**Comment by brendanzagaeski** [comment]
Developer Community cross-referencing note for the Xamarin team:
<https://developercommunity.visualstudio.com/content/problem/223104/vs-1564-xamarin-android-app-intallation-errors-xa5.html>

**Comment by rmhopkins** [comment]
A few additional notes:

1. Any project requiring Xamarin.Android.Support.CustomTabs exhibits this error and will not build.  The Master Detail template with .NET Core just uses this out of the box.

2. Clicking on the _Please double-click here to install it_ prompt in the Error list does initiate a download (VS 2017 on Windows only tested) and the IDE attempts to install it, however after a period of time (about 10 minutes in my case on a fast connection) the installation fails once the download has reached 100%.

3. Manually installing and unzipping android_m2repository_r29.zip to the relevant directory partially resolves the issue.  There is a second step required which is only flagged as an error once this first step has been done, requiring a file in the unzipped directory structure to be moved to a different directory.

4. The directory and parent directory to which the m2repository is supposed to be manually unzipped does not exist in a clean install, which is likely to be confusing for new developers.

**Comment by IoTFier** [comment]
HI @brendanzagaeski , can we please get some help in addressing this issue ?

@rmhopkins - any luck on your end in finding any solution ?

Thanks

**Comment by rmhopkins** [comment]
@IoTFier 

The only solution I’ve found is to do the install manually following the instructions in the error message.

**Comment by IoTFier** [comment]
Hi @rmhopkins , thank you very much. Addressing 2nd error on a manual basis has taken me forward in my compilation efforts. But, now  -1> my VS emulator keeps throwing error "Unfortunately, Google Play Store has stopped" and 2> there is a warning in the build output as "NU1608	Detected package version outside of dependency constraint: Xamarin.Android.Support.CustomTabs 23.3.0 requires Xamarin.Android.Support.v4 (= 23.3.0) but version Xamarin.Android.Support.v4 25.4.0.2 was resolved."

I am not sure if that warning has to do with Google play store stopping on my VS emulator.

It is really painful to address one thing after another....

**Comment by rmhopkins** [comment]
@IoTFier No, that’s not connected to the Custom tabs issue.  Don’t worry about the warning - it shouldn’t be a major problem.  Are you running the emulator in a VM?  Sometimes I find nesting emulators can cause issues.  Otherwise, you could try another emulator such as genymotion, or try creating a new image in the emulator manager without google play services (it’s not needed for most apps).  I don’t want to go on at too much length though as it will take this discussion off topic from the actually bug report.

**Comment by IoTFier** [comment]
@rmhopkins , I am using VS Emulator so that I can use Docker for windows at the same time. I wish to use HAXM emulators but not interested in toggling hyper-v. I don't know if there are any 3rd party Android emulators based on Hyper-V.

**Comment by acastr7** [comment]
I am experiencing the same issue setting up a brand machine up with VS 15.6.4 and the android support libraries.

**Comment by IoTFier** [comment]
@brendanzagaeski  , Xamarin engineering team leaders -

Is there anyone working on this issue? 

Thanks

**Comment by brendanzagaeski** [comment]
The corresponding Developer Community item has now been raised to **Under Investigation** thanks to the up-votes on that item. Since that item is now marked as **Under Investigation**, I would recommend to vote on and follow it for updates and fix notifications:
- <https://developercommunity.visualstudio.com/content/problem/219446/xamarin-an-error-occurred-trying-to-install-requir.html>

I will tentatively close this GitHub issue to direct further discussion and updates onto the Developer Community item. Xamarin team, feel free to re-open this issue if you wish to use it to track any details about commit information for the eventual fix (or similar). Thanks!

**Comment by IoTFier** [comment]
hi @rbmanian75 , are you facing this issue in 15.6.5 and/or 15.6.6?
Thanks,

**Comment by rbmanian75** [comment]
I am using 15.6.5. However i fixed the issue by manually copying from
android support folder according connect feedback thread.

Thanks

**Comment by dgerding** [comment]
Same issue.  on 15.6.6
Where do I copy the zip contents to fix?

**Comment by rbmanian75** [comment]
follow the instructions at https://gist.github.com/jimmgarrido/a05ffe571230eb279266aeb0e5fb2ad2
