### ISSUE TITLE
Android SDK not found with Jenkins build

### ISSUE THREAD

**Issue by ghost** [xamarin/xamarin-android#1481]
### Steps to Reproduce

1. Install latest SDK's (see versions below)
2. Run an Android build from a separate user (in my case, Jenkins)
3. 

### Expected Behavior
Build succeeds.

### Actual Behavior
Build failed with the following error:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(629,2): error MSB4018: System.InvalidOperationException: Could not determine Android SDK location. Please provide `androidSdkPath`. [/Users/Shared/Jenkins2-Daemon/workspace/dworx-simon-xamarin_develop-2BAM4DDYCSKQFYGNZHEII5ZQB5FXTPNOM5XB3CRFVOJLFQQS3OTQ/Libraries/PN/Plugin.AzurePushNotification.Android/Plugin.AzurePushNotification.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(629,2): error MSB4018:   at Xamarin.Android.Tools.AndroidSdkInfo..ctor (System.Action`2[T1,T2] logger, System.String androidSdkPath, System.String androidNdkPath, System.String javaSdkPath) [0x0005a] in <d1f9cdf0cbad4736accc136a27f21ad7>:0  [/Users/Shared/Jenkins2-Daemon/workspace/dworx-simon-xamarin_develop-2BAM4DDYCSKQFYGNZHEII5ZQB5FXTPNOM5XB3CRFVOJLFQQS3OTQ/Libraries/PN/Plugin.AzurePushNotification.Android/Plugin.AzurePushNotification.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(629,2): error MSB4018:   at Xamarin.Android.Tasks.MonoAndroidHelper.RefreshAndroidSdk (System.String sdkPath, System.String ndkPath, System.String javaPath) [0x00009] in <bae064cadfb64dccb729d7cb7dab7861>:0  [/Users/Shared/Jenkins2-Daemon/workspace/dworx-simon-xamarin_develop-2BAM4DDYCSKQFYGNZHEII5ZQB5FXTPNOM5XB3CRFVOJLFQQS3OTQ/Libraries/PN/Plugin.AzurePushNotification.Android/Plugin.AzurePushNotification.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(629,2): error MSB4018:   at Xamarin.Android.Tasks.ResolveSdks.RunTask () [0x001c3] in <bae064cadfb64dccb729d7cb7dab7861>:0  [/Users/Shared/Jenkins2-Daemon/workspace/dworx-simon-xamarin_develop-2BAM4DDYCSKQFYGNZHEII5ZQB5FXTPNOM5XB3CRFVOJLFQQS3OTQ/Libraries/PN/Plugin.AzurePushNotification.Android/Plugin.AzurePushNotification.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(629,2): error MSB4018:   at Xamarin.Android.Tasks.ResolveSdks.Execute () [0x00000] in <bae064cadfb64dccb729d7cb7dab7861>:0  [/Users/Shared/Jenkins2-Daemon/workspace/dworx-simon-xamarin_develop-2BAM4DDYCSKQFYGNZHEII5ZQB5FXTPNOM5XB3CRFVOJLFQQS3OTQ/Libraries/PN/Plugin.AzurePushNotification.Android/Plugin.AzurePushNotification.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(629,2): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in <99064ce461714f6a83a1f24370e1d7b8>:0  [/Users/Shared/Jenkins2-Daemon/workspace/dworx-simon-xamarin_develop-2BAM4DDYCSKQFYGNZHEII5ZQB5FXTPNOM5XB3CRFVOJLFQQS3OTQ/Libraries/PN/Plugin.AzurePushNotification.Android/Plugin.AzurePushNotification.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(629,2): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in <99064ce461714f6a83a1f24370e1d7b8>:0  [/Users/Shared/Jenkins2-Daemon/workspace/dworx-simon-xamarin_develop-2BAM4DDYCSKQFYGNZHEII5ZQB5FXTPNOM5XB3CRFVOJLFQQS3OTQ/Libraries/PN/Plugin.AzurePushNotification.Android/Plugin.AzurePushNotification.Android.csproj]

### Version Information

=== Visual Studio Professional 2017 for Mac ===

Version 7.4.1 (build 48)
Installation UUID: 17985daf-ca65-44a6-ba05-e8ec30470cf0
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.1.0
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.1
	1.0.0-preview2-1-003177
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.0 (13247)
Build 9A235

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 11.8.1.28 (Visual Studio Professional)
Hash: 3979d081
Branch: d15-6
Build date: 2018-03-09 16:22:34-0500

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Professional)
Android SDK: /usr/local/share/android-sdk
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704010048
Git revision: 6a86203dd590c6cfdf814c8832d24d2ad1e2606f
Build date: 2018-03-20 11:16:55-04
Xamarin addins: 8d83cea9e4ae03cb0c14ba3fbaafdbb0cbd170e7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Mon Nov 13 21:56:25 PST 2017
    root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

**Comment by CAMOBAP795** [comment]
`/p:AndroidSdkDirectory` passed to `msbuild` helped me to avoid this

**Comment by YvesDelcoigne** [comment]
I was already passing this parameter. My solution was to manually add the monodroid-config.xml file to the Jenkins user, as this wasn't created. Apparently, no matter what environment variables you set for pointing to the Android SDK, if it's not set in that file, it's not properly recognized while restoring dependencies.

This wasn't an issue in previous versions, so I'm considering this a regression bug.

**Comment by YvesDelcoigne** [comment]
I could also reproduce this locally, by removing the mentioned file.

**Comment by alan-dev-olostech** [comment]
> I could also reproduce this locally, by removing the mentioned file.

Where I place this monodroid-config.xml file?

**Comment by YvesDelcoigne** [comment]
This should be in ~/.config/xbuild

**Comment by jpobst** [comment]
Assuming this issue is obsolete as we have not received any more reports in currently supported versions.
