### ISSUE TITLE
Contents of the attached PDF are not rendered using PdfRenderer in Android versions below 8.0

### ISSUE THREAD

**Issue by NavaneethS** [xamarin/xamarin-android#1485]
### Steps to Reproduce

1. Run the attached replication sample in Android versions 6 or 7. The sample uses Android.Graphics.PDF.PdfRenderer to convert the first page of the PDF to image and display it on an ImageView. 

2. Compare the rendering of the contents with the PDF as viewed in Adobe Reader or the same sample in Android 8.

[SimplePdfRenderer1.zip](https://github.com/xamarin/xamarin-android/files/1855105/SimplePdfRenderer1.zip)

### Expected Behavior

The contents of the first page fully rendered. Please refer the below image. 

<img width="720" alt="expectedoutput" src="https://user-images.githubusercontent.com/37859978/38019086-4c817692-3294-11e8-917f-dbf95a870895.png">

### Actual Behavior

The contents of the first page not fully rendered. Please refer the below image. 

<img width="540" alt="actualoutput" src="https://user-images.githubusercontent.com/37859978/38019114-5be70610-3294-11e8-954a-d7c400503f07.png">

### Version Information

Correct behavior: Android 8 
Incorrect behavior: Android 6 and Android 7
Devices tested in: Samsung Galaxy Tab A (Android 6), Moto G5S(Android 7) and Google Pixel XL(Android 8)

**Comment by NavaneethS** [comment]
[SimplePdfRenderer1.zip](https://github.com/xamarin/xamarin-android/files/1855642/SimplePdfRenderer1.zip)

**Comment by atsushieno** [comment]
Sounds like an upstream issue. https://issuetracker.google.com/issues/37105160

"If you need to support for < O (and who doesn't?), you have to use a unbundled party pdf library such as pdfium."
