### ISSUE TITLE
Unable to build against preview Android API levels

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1498]
### Steps to Reproduce

1. Copy the v8.1 framework to v99.99.
2. Edit v99.99\AndroidApiInfo.xml, and set `<Id/>` to "Z", set `<Level/>` to 99, set `<Version/>` to v99.99, and `<Stable/>` to False:

    <AndroidApiInfo>
      <Id>Z</Id>
      <Level>99</Level>
      <Name>Z</Name>
      <Version>v99.99</Version>
      <Stable>False</Stable>
    </AndroidApiInfo>

3. Copy `$(AndroidSdkDirectory)\platforms\android-27` to `$(AndroidSdkDirectory)\platforms\android-Z`.

4. Update an new or existing project so that `$(TargetFrameworkVersion)`=v99.99.

Alternatively, a recent build from master which has early P preview support can be used.

### Expected Behavior
Project compiles against preview bindings and preview platform SDK.

### Actual Behavior
Project fails with:
>   C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(907,29): error MSB4030: "Z" is an invalid value for the "AndroidApiLevel" parameter of the "GetAndroidDefineConstants" task. The "AndroidApiLevel" parameter is of type "System.Int32".

### Version Information
Xamarin.Android.Sdk-OSS-8.3.99.86_HEAD_7800139

### Log File
Build output using the steps provided above:
https://gist.github.com/pjcollins/da86d3595cfa97304ac32a42e09a69ac

Build output using Android P preview:
https://gist.github.com/pjcollins/4badecdce72fe24071563fd56fd93e1c

**Comment by dellis1972** [comment]
PR was merged into Master.

**Comment by pjcollins** [comment]
Works for me against the following PR build - https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/938/Azure/. There is however an issue related to UseLatest behavior that I will be filing separately.
