### ISSUE TITLE
Black screen on layout preview

### ISSUE THREAD

**Issue by dimis1989** [xamarin/xamarin-android#1500]
When upating in last xamarin tools version and trying opening layout preview i get only a black screen. In previous versions all worked fine. 

windows 7 64bit
vs 2015 update 3
Gtx 1070 msi
i7-6700k
xamarin tools last version

> VS bug [#609042](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/609042)

**Comment by alanmcgovern** [comment]
Hi,

If you are using Visual Studio 2015 then we highly recommend you upgrade to Visual Studio 2017 as that could resolve the issue.

If that does not help, could you attach the logs files from the session where you trigger the problem and we might be able to diagnose the issue from that. You can find the logs by clicking Help -> Xamarin -> Open Log Directory. It might be easier if you delete all existing logs, then reproduce the problem, then attach every log file that is created in that directory.

Thanks!
