### ISSUE TITLE
Check failed: found_virtual Didn't find oat method index for virtual method: android.content.pm.ResolveInfo

### ISSUE THREAD

**Issue by justintoth** [xamarin/xamarin-android#1510]
### Steps to Reproduce

Launch our Xamarin Android app and log in, go to the search screen (sometimes crashes on load), then go back from the search screen (sometimes crashes on exit.) It's unpredictable what on the search screen is causing the crash (very random), I tried to minimize the impacting code but it seems to be more frequent when showing the keyboard or rebinding data to a list adapter.

### Expected Behavior

App doesn't crash.

### Actual Behavior

App crashes with the following error:

04-03 17:42:40.181: A/art(9316): art/runtime/class_linker.cc:2718] Check failed: found_virtual Didn't find oat method index for virtual method: android.content.pm.ResolveInfo android.accessibilityservice.AccessibilityServiceInfo.getResolveInfo()

### Version Information

=== Visual Studio Community 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: 62cf1ad2-0db0-41e1-ac78-aeb509d79f60
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /android/sdk
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

### Log File

04-03 17:42:40.181: A/art(9316): art/runtime/class_linker.cc:2718] Check failed: found_virtual Didn't find oat method index for virtual method: android.content.pm.ResolveInfo android.accessibilityservice.AccessibilityServiceInfo.getResolveInfo()

**Comment by jpobst** [comment]
Assuming this issue is obsolete as we have not received any more reports in currently supported versions.
