### ISSUE TITLE
Unstable framework versions are used when $(AndroidUselatestPlatformSDK)=true

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1511]
### Steps to Reproduce

1. Copy the v8.1 framework to v108.1.99

2. Edit v108.1.99\AndroidApiInfo.xml, and set `<Id/>` to "Z", set `<Level/>` to 127, set `<Version/>` to v108.1.99, and `<Stable/>` to False:

```xml
    <AndroidApiInfo>
      <Id>Z</Id>
      <Level>127</Level>
      <Name>Z Preview</Name>
      <Version>v108.1.99</Version>
      <Stable>False</Stable>
    </AndroidApiInfo>
```
3. Copy $(AndroidSdkDirectory)\platforms\android-27 to $(AndroidSdkDirectory)\platforms\android-Z.

4. Update a new or existing project so that $(TargetFrameworkVersion)=v8.0, and $(AndroidUseLatestPlatformSdk)=true

Alternatively, a recent build from master which has early P preview support can be used.

### Expected Behavior
Using a project with a $(TargetFrameworkVersion) lower than the max stable version, and setting $(AndroidUseLatestPlatformSdk)=true, I would expect my project to build against the latest stable version that is installed. In the case mentioned above, this would be android-27 (v8.1).

### Actual Behavior
A project with a $(TargetFrameworkVersion) lower than the max stable version, and setting $(AndroidUseLatestPlatformSdk)=true builds against my fake unstable framework version, android-Z.

### Version Information
Xamarin.Android.Sdk-OSS-8.3.99.91_HEAD_33822ad.vsix

### Log File
http://xqa.blob.core.windows.net/gist/log-83bd0e75034940db9ae887a8f5c03d98.txt

> VS bug [#594908](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/594908)

**Comment by pjcollins** [comment]
This is no longer reproducible using xamarin-android/master/efe81f5.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **Bill Holmes**

 Opening bug again for the 15-7 P5 release pipeline.

**Comment by pjcollins** [comment]
While this was seemingly fixed for me against a previous Xamarin OSS master build, I am again able to reproduce this against d15-8. The unstable .dll and .jar files are still used:

> FilteredAssemblies=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v108.1.99\Mono.Android.dll
>MonoPlatformJarPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v108.1.99\mono.android.jar
> JavaPlatformJarPath=C:\Program Files (x86)\Android\android-sdk\platforms\android-Z\android.jar

Diagnostic build output:
http://xqa.blob.core.windows.net/gist/log-fd74d75ecc3c41b0a59c4cbfc3532bfb.txt

**Comment by dellis1972** [comment]
Probably because we haven't bumped to the x-a which has the fix.
Sent from my Windows 10 phone

**Comment by pjcollins** [comment]
This is fixed again when using XA 8.3.99.20 (monodroid/master/80386193a), but I'm having a bit of difficulty tracking the fix as it seems like it should have also been included in 8.3.99.12 (monodroid/master/de662f58d)?

**Comment by jonathanpeppers** [comment]
@pjcollins I think it's because we have multiple copies of `xamarin-android-tools` floating around.

I suspect `monodroid/c03f3b4` fixed this from bumping `androidtools`, which has it's own copy of `xamarin-android-tools` for some reason...

**Comment by jonpryor** [comment]
> which has its own copy of xamarin-android-tools for some reason...

*Everything* references xamarin-android-tools. It's turning into quite the leaf node... You wouldn't believe the fun I've had bumping all the intermediate references...

**Comment by pjcollins** [comment]
This is no longer reproducible from command line on both Mac and Windows using d15-8/8.4.0.6.

As for in IDE experiences however, we're a bit out of sync. VS removes and ignores the AndroidUseLatestPlatformSdk flag entirely in 15.8, so this is no longer a valid scenario there.

This is still an issue when running inside of VS Mac however. I've opened https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636136 to track that, and will and close this one out.

**Comment by MagicAndre1981** [comment]
@pjcollins 

is there any documentation about the AndroidUseLatestPlatformSdk removal in 15.8? I only see it gets removed (changed local files in source control) when I open a project in 15.8
