### ISSUE TITLE
Android Unit Test on Device F# crash:  Resources NotFoundException

### ISSUE THREAD

**Issue by willsam100** [xamarin/xamarin-android#1513]
### Steps to Reproduce

1. Create an Android Unit Test project with F# 
2. Build and run on device

### Expected Behavior
The Unit tests will run on the device

### Actual Behavior

  --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---
android.content.res.Resources$NotFoundException: Resource ID #0x7f020003
	at android.content.res.Resources.getValue(Resources.java:2485)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:4217)
	at android.content.res.Resources.getLayout(Resources.java:2301)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
	at android.app.Activity.setContentView(Activity.java:2399)
	at md54f7330f059cfdce8608ce9cc3a0da7e3.MainActivity.n_onCreate(Native Method)
	at md54f7330f059cfdce8608ce9cc3a0da7e3.MainActivity.onCreate(MainActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:6608)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3243)
	at android.app.ActivityThread.access$1000(ActivityThread.java:218)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6917)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

### Version Information

=== Visual Studio Professional 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: 69cc42aa-2bc3-49e3-929b-43eb3dfdb0eb
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.2
	1.1.1
	1.1.0
	1.0.5
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.4
	1.0.1
	1.0.0-preview2-1-003177
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Professional)

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Professional)
Android SDK: /Users/sam.williams/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3 (API level 10)
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Professional)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MvvmCross Template pack 2.0.1
Paket 0.3
xUnit.NET 2 testing framework support 0.7.5
Redth's Addins 1.0.9
Straight8's SpecFlow Integration 1.11.1.0
SpecFlow Support 1.10.0.0
Internet of Things (IoT) development (Preview) 7.1

### Log File

Intentionally left blank, as the bug is reliably reproducible for me, and I don't think device logs will help in the fix. 

If they are required, I can update.

**Comment by nosami** [comment]
Try searching the auto-generated `Resource.designer.cs` file for `0x7f020003`. It may provide some clues. 

Does the unit test project use resources directly or indirectly via the project under test?

Can you share your code?

**Comment by nosami** [comment]
I see the same exception. Looking at the C# generated file, I don't see any identifiers with Resource ID #0x7f020003. I'm not sure that this is an issue with the F# type provider.

```cs
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("fsandroidnunit.Resource", IsApplication=true)]

namespace fsandroidnunit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::fsandroidnunit.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::fsandroidnunit.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::fsandroidnunit.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::fsandroidnunit.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::fsandroidnunit.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::fsandroidnunit.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::fsandroidnunit.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::fsandroidnunit.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::fsandroidnunit.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::fsandroidnunit.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::fsandroidnunit.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::fsandroidnunit.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::fsandroidnunit.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::fsandroidnunit.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::fsandroidnunit.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::fsandroidnunit.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::fsandroidnunit.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::fsandroidnunit.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::fsandroidnunit.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::fsandroidnunit.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::fsandroidnunit.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::fsandroidnunit.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int OptionHostName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int OptionPort = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int OptionRemoteServer = 2130968576;
			
			// aapt resource value: 0x7f040010
			public const int OptionsButton = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int ResultFullName = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int ResultMessage = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int ResultResultState = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int ResultRunSingleMethodTest = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int ResultStackTrace = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int ResultsFailed = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int ResultsId = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int ResultsIgnored = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ResultsInconclusive = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ResultsMessage = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int ResultsPassed = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int ResultsResult = 2130968580;
			
			// aapt resource value: 0x7f04000f
			public const int RunTestsButton = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int TestSuiteListView = 2130968593;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
	}
}
#pragma warning restore 1591
```

**Comment by nosami** [comment]
`R.java` looks like this. I can't see any differences between the F# resources and the equivalent C# resources when generated from the C# Android NUnit template. 

```java
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package fsandroidnunit.fsandroidnunit;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int OptionHostName=0x7f040001;
        public static final int OptionPort=0x7f040002;
        public static final int OptionRemoteServer=0x7f040000;
        public static final int OptionsButton=0x7f040010;
        public static final int ResultFullName=0x7f04000b;
        public static final int ResultMessage=0x7f04000d;
        public static final int ResultResultState=0x7f04000c;
        public static final int ResultRunSingleMethodTest=0x7f04000a;
        public static final int ResultStackTrace=0x7f04000e;
        public static final int ResultsFailed=0x7f040006;
        public static final int ResultsId=0x7f040003;
        public static final int ResultsIgnored=0x7f040007;
        public static final int ResultsInconclusive=0x7f040008;
        public static final int ResultsMessage=0x7f040009;
        public static final int ResultsPassed=0x7f040005;
        public static final int ResultsResult=0x7f040004;
        public static final int RunTestsButton=0x7f04000f;
        public static final int TestSuiteListView=0x7f040011;
    }
    public static final class layout {
        public static final int options=0x7f030000;
        public static final int results=0x7f030001;
        public static final int test_result=0x7f030002;
        public static final int test_suite=0x7f030003;
    }
    public static final class mipmap {
        public static final int icon=0x7f020000;
    }
}
```

**Comment by nosami** [comment]
F# apk contents
```
14:16 $ unzip -lv fsandroidnunit.fsandroidnunit.apk
Archive:  fsandroidnunit.fsandroidnunit.apk
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    3976  Defl:N     1255  68% 04-05-2018 13:39 34bead2b  AndroidManifest.xml
     604  Defl:N      367  39% 04-05-2018 13:39 50cb51ea  assets/AboutAssets.txt
    1672  Defl:N      441  74% 04-05-2018 13:39 14a778cd  res/layout/options.xml
    1860  Defl:N      402  78% 04-05-2018 13:39 f0ba0635  res/layout/results.xml
    1324  Defl:N      447  66% 04-05-2018 13:39 f79c1b36  res/layout/test_result.xml
    1464  Defl:N      488  67% 04-05-2018 13:39 3f692ae7  res/layout/test_suite.xml
    2380  Stored     2380   0% 04-05-2018 13:39 4e335b52  res/mipmap-hdpi-v4/icon.png
    1591  Stored     1591   0% 04-05-2018 13:39 7e44d3e1  res/mipmap-mdpi-v4/icon.png
    4335  Stored     4335   0% 04-05-2018 13:39 86a9d83b  res/mipmap-xhdpi-v4/icon.png
    7429  Stored     7429   0% 04-05-2018 13:39 765d2fe3  res/mipmap-xxhdpi-v4/icon.png
   11033  Stored    11033   0% 04-05-2018 13:39 0a09d4b7  res/mipmap-xxxhdpi-v4/icon.png
    2400  Stored     2400   0% 04-05-2018 13:39 7e779e53  resources.arsc
     157  Defl:N      121  23% 04-05-2018 13:42 9574b68a  NOTICE
  305272  Defl:N    68252  78% 04-05-2018 13:42 78475023  classes.dex
    8192  Stored     8192   0% 04-05-2018 13:42 a7b666d5  assemblies/fsandroidnunit.dll
     644  Stored      644   0% 04-05-2018 13:42 ab1918d6  assemblies/fsandroidnunit.pdb
 1517568  Stored  1517568   0% 04-05-2018 13:42 af150402  assemblies/FSharp.Core.dll
    5120  Stored     5120   0% 04-05-2018 13:42 35341379  assemblies/Xamarin.Android.FSharp.ResourceProvider.Runtime.dll
     208  Defl:N      177  15% 04-05-2018 13:42 4e52a578  environment
  158168  Defl:N    55863  65% 04-05-2018 13:42 2a6ef8a6  lib/arm64-v8a/libmonodroid.so
  205464  Defl:N    67596  67% 04-05-2018 13:42 51a3246a  lib/arm64-v8a/libmono-profiler-log.so
  145216  Defl:N    59944  59% 04-05-2018 13:42 5449bb52  lib/armeabi/libmonodroid.so
  234380  Defl:N    84637  64% 04-05-2018 13:42 2c59aa87  lib/armeabi/libmono-profiler-log.so
  128836  Defl:N    56338  56% 04-05-2018 13:42 7bcc389e  lib/armeabi-v7a/libmonodroid.so
  248792  Defl:N    85022  66% 04-05-2018 13:42 59e57708  lib/armeabi-v7a/libmono-profiler-log.so
  161544  Defl:N    56490  65% 04-05-2018 13:42 24384eac  lib/x86/libmonodroid.so
  220068  Defl:N    77041  65% 04-05-2018 13:42 341d8e0e  lib/x86/libmono-profiler-log.so
  158440  Defl:N    57691  64% 04-05-2018 13:42 bd0b8818  lib/x86_64/libmonodroid.so
  234680  Defl:N    86173  63% 04-05-2018 13:42 182e1fc8  lib/x86_64/libmono-profiler-log.so
    1623  Stored     1623   0% 04-05-2018 13:42 4afc1309  typemap.jm
    1624  Stored     1624   0% 04-05-2018 13:42 0cb1bbb9  typemap.mj
  813064  Defl:N   412846  49% 04-05-2018 13:42 87844d8a  lib/arm64-v8a/libgdbserver.so
  579940  Defl:N   328354  43% 04-05-2018 13:42 74ee9eb5  lib/armeabi/libgdbserver.so
  579940  Defl:N   328354  43% 04-05-2018 13:42 74ee9eb5  lib/armeabi-v7a/libgdbserver.so
 1121564  Defl:N   475886  58% 04-05-2018 13:42 d1c77d40  lib/x86/libgdbserver.so
 1111288  Defl:N   486439  56% 04-05-2018 13:42 99c078fc  lib/x86_64/libgdbserver.so
```

**Comment by nosami** [comment]
[msbuild-diag-log.txt](https://github.com/xamarin/xamarin-android/files/1880155/msbuild-diag-log.txt)

**Comment by nosami** [comment]
Rename file to msbuild.binlog (github wouldn't let me upload with original extension)

[msbuild.binlog.txt](https://github.com/xamarin/xamarin-android/files/1880160/msbuild.binlog.txt)

**Comment by nosami** [comment]
Referencing the temporary assembly generated by the type provider makes things work. It is probably enough to just copy this assembly to the output folder (or create it there in the first place instead of a temp folder)

![image](https://user-images.githubusercontent.com/667194/38370252-9891c098-38e1-11e8-8ffe-d1689b1312d6.png)

**Comment by willsam100** [comment]
@nosami thanks for that. I can confirm this worked for me too. 
Additionally, I found another small bug when attempting to run the tests:

    [<TestFixture>]
    type TestsSample =

should actually be:

    [<TestFixture>]
    type TestsSample() =

ie it is missing the ``()`` to make it a class, rather than an interface.

Are you able to update the default template in VS4Mac for this project?

**Comment by nosami** [comment]
@willsam100 I saw that too - the tests were failing without the default constructor!

Yes, I'll update the template. Still trying to figure out how to get the temp assembly referenced automatically or copied into the right folder - just putting it into the bin/Debug folder doesn't work.

**Comment by nosami** [comment]
Good news is that I have this working now without copying any assemblies around - the C# types are embedded into the F# assembly.

![image](https://user-images.githubusercontent.com/667194/38420839-12becb20-399d-11e8-9960-e8b468380d3e.png)

I broke the type provider inadvertently when I switched to using the Type Provider SDK. I didn't realise that it was creating a 'metadata only' view of the assembly - it contained all the field values but not the runtime code. This was fine for single assembly applications but not applications that referenced other Android libraries. The type provider fix will be in v 1.0.0.22

I also noticed another issue that must have always been there - the assembly level attribute contained inside the C# code was never applied to the resulting F# assembly. It's going to be necessary to add this into the template somewhere.

```fs
namespace fsandroidnunit
// the name of the type here needs to match the name inside the ResourceDesigner attribute
type Resources = fsandroidnunit.Resource
[<assembly: Android.Runtime.ResourceDesigner("fsandroidnunit.Resources", IsApplication=true)>]
()
```

**Comment by willsam100** [comment]
That's a great find. I really appreciate the work you do on this. F# all the things!

I think this will also fix another bug that I found ,but had no idea how to debug.  I wanted to use MvvmCross in a Droid project (PCL/netstandard worked fine). Given it could have been with either F# or MvvmCross or anything in between.

I will test this fix out with the Droid unit tests to confirm it works on my end.

**Comment by willsam100** [comment]
I can confirm the fix in the `xamarin/Xamarin.Android.FSharp.ResourceProvide` has solved this problem. thanks @nosami 

MvvmCross with F# still does not not work. It is a seperate issue to this (though relates to Android resources). So this issue can be closed :)

**Comment by nosami** [comment]
@willsam100 what's the issue with MvvmCross?

**Comment by willsam100** [comment]
Here is a sample repo with the error: [Fsharp Droid project with MvvmCross](https://github.com/willsam100/MvvmFsharpDroid). (Note: the PCL is still C#. It's the F# droid project that causes the problem though). 

Here is the sample repo from MvvmCross (to check that I have things setup correctly): [MvvmCross Xamarin forms C#](https://github.com/martijn00/MvxForms)

I have tracked the error to this class in the exception can be found in the MvvmCross source here: [MvxAppResourceTypeFinder](https://github.com/MvvmCross/MvvmCross/blob/be4dfea1099a053d0ad850c8b82767624784ca1d/MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs)

And here is the exception that I'm getting: 

``[mono] MvvmCross.Platform.Exceptions.MvxException: Unable to find resource type - MvvmFormsAppFsharp.Droid.Resource. Please check if your setup class is in your application's root namespace.
[mono]   at MvvmCross.Binding.Droid.ResourceHelpers.MvxAppResourceTypeFinder.Find () [0x0002a] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAppResourceTypeFinder.cs:23 
[mono]   at MvvmCross.Binding.Droid.ResourceHelpers.MvxAndroidBindingResource..ctor () [0x0000b] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAndroidBindingResource.cs:31 
[mono]   at MvvmCross.Binding.Droid.ResourceHelpers.MvxAndroidBindingResource.Initialize () [0x00008] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAndroidBindingResource.cs:25 
[mono]   at MvvmCross.Binding.Droid.MvxAndroidBindingBuilder.InitializeBindingResources () [0x00000] in D:\git\MvvmCross\MvvmCross\Binding\Droid\MvxAndroidBindingBuilder.cs:66 
[mono]   at MvvmCross.Binding.Droid.MvxAndroidBindingBuilder.DoRegistration () [0x00006] in D:\git\MvvmCross\MvvmCross\Binding\Droid\MvxAndroidBindingBuilder.cs:32 
[mono]   at MvvmCross.Forms.Droid.Bindings.MvxFormsAndroidBindingBuilder.DoRegistration () [0x00000] in D:\git\MvvmCross\MvvmCross-Forms\MvvmCross.Forms.Droid\Bindings\MvxFormsAndroidBindingBuilder.cs:24 
[mono]   at MvvmCross.Forms.Droid.Platform.MvxFormsAndroidSetup.InitializeBindingBuilder () [0x0000c] in D:\git\MvvmCross\MvvmCross-Forms\MvvmCross.Forms.Droid\Platform\MvxFormsAndroidSetup.cs:89 
[mono]   at MvvmCross.Droid.Platform.MvxAndroidSetup.InitializeLastChance () [0x00006] in D:\git\MvvmCross\MvvmCross\Droid\Droid\Platform\MvxAndroidSetup.cs:133 
[mono]   at MvvmCross.Core.Platform.MvxSetup.InitializeSecondary () [0x0017c] in D:\git\MvvmCross\MvvmCross\Core\Core\Platform\MvxSetup.cs:108 
[mono]   at MvvmCross.Droid.Platform.MvxAndroidSetupSingleton.<InitializeFromSplashScreen>b__7_0 (System.Object ignored) [0x00000] in D:\git\MvvmCross\MvvmCross\Droid\Droid\Platform\MvxAndroidSetupSingleton.cs:92 
[mono]   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono]   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono]   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono]   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono]   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: MvvmCross.Platform.Exceptions.MvxException: Unable to find resource type - MvvmFormsAppFsharp.Droid.Resource. Please check if your setup class is in your application's root namespace.
[mono-rt]   at MvvmCross.Binding.Droid.ResourceHelpers.MvxAppResourceTypeFinder.Find () [0x0002a] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAppResourceTypeFinder.cs:23 
[mono-rt]   at MvvmCross.Binding.Droid.ResourceHelpers.MvxAndroidBindingResource..ctor () [0x0000b] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAndroidBindingResource.cs:31 
[mono-rt]   at MvvmCross.Binding.Droid.ResourceHelpers.MvxAndroidBindingResource.Initialize () [0x00008] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAndroidBindingResource.cs:25 
[mono-rt]   at MvvmCross.Binding.Droid.MvxAndroidBindingBuilder.InitializeBindingResources () [0x00000] in D:\git\MvvmCross\MvvmCross\Binding\Droid\MvxAndroidBindingBuilder.cs:66 
[mono-rt]   at MvvmCross.Binding.Droid.MvxAndroidBindingBuilder.DoRegistration () [0x00006] in D:\git\MvvmCross\MvvmCross\Binding\Droid\MvxAndroidBindingBuilder.cs:32 
[mono-rt]   at MvvmCross.Forms.Droid.Bindings.MvxFormsAndroidBindingBuilder.DoRegistration () [0x00000] in D:\git\MvvmCross\MvvmCross-Forms\MvvmCross.Forms.Droid\Bindings\MvxFormsAndroidBindingBuilder.cs:24 
[mono-rt]   at MvvmCross.Forms.Droid.Platform.MvxFormsAndroidSetup.InitializeBindingBuilder () [0x0000c] in D:\git\MvvmCross\MvvmCross-Forms\MvvmCross.Forms.Droid\Platform\MvxFormsAndroidSetup.cs:89 
[mono-rt]   at MvvmCross.Droid.Platform.MvxAndroidSetup.InitializeLastChance () [0x00006] in D:\git\MvvmCross\MvvmCross\Droid\Droid\Platform\MvxAndroidSetup.cs:133 
[mono-rt]   at MvvmCross.Core.Platform.MvxSetup.InitializeSecondary () [0x0017c] in D:\git\MvvmCross\MvvmCross\Core\Core\Platform\MvxSetup.cs:108 
[mono-rt]   at MvvmCross.Droid.Platform.MvxAndroidSetupSingleton.<InitializeFromSplashScreen>b__7_0 (System.Object ignored) [0x00000] in D:\git\MvvmCross\MvvmCross\Droid\Droid\Platform\MvxAndroidSetupSingleton.cs:92 
[mono-rt]   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono-rt]   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono-rt]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono-rt]   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono-rt]   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono-rt]   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 ``

**Comment by nosami** [comment]
@willsam100 The issue here is with MvvmCross https://github.com/MvvmCross/MvvmCross/blob/be4dfea1099a053d0ad850c8b82767624784ca1d/MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs#L15

It is looking for a type named `rootnamespace.Resource` but in this case, your resource type is plural `Resources`

![image](https://user-images.githubusercontent.com/667194/38452482-f5fbb78c-3a3c-11e8-818c-d7e9cb610e1c.png)

It should do what Xamarin-Android does

https://github.com/xamarin/xamarin-android/blob/f071dd61252abe35b63c724467caafd9314c804c/src/Mono.Android/Android.Runtime/ResourceIdManager.cs#L33-L43

**Comment by nosami** [comment]
@willsam100: I wasn't able to build MvvmCross to submit a PR :(

I can't think of an easy workaround either :( The only thing I can think of would be to fork the type provider and

**Comment by nosami** [comment]
PR submitted.

**Comment by nosami** [comment]
Closing this. I've updated the type provider, updated the templates and made a PR to MvvmCross :)
