### ISSUE TITLE
Rewrite xamarin-android build system with testable framework

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1516]
Since we started using MSBuild as the project build script, this kind of build regressions https://github.com/xamarin/xamarin-android/pull/1491#issuecomment-378875327 have been occuring too many times, making it unreliable, unreadable, and slow. We need build script written in human-hackable language and make it open to everyone, not just one or two people who understands the spaghetti.

**Comment by jpobst** [comment]
This seems unlikely to change.
