### ISSUE TITLE
Reorganize Xamarin.Android.sln

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1517]
What are "Build-Tools", "Core", "Tests" and "Tools" ? Why Xamarin.Android.Tools.Bytecode is part of "Core" while "Xamarin.Android.Tools.ApiXmlAdjuster" is part of "Tools" ?

The categorization doesn't make sense at all, and this brings confusion to developers.

They have to be reorganized appropriately.

**Comment by atsushieno** [comment]
Better action: stop using solution as the master file. Always generate it from some kind of description file.

**Comment by atsushieno** [comment]
For example, Workbooks https://github.com/Microsoft/Workbooks does not contain solution at all. It is generated.

**Comment by jpobst** [comment]
This seems unlikely to change.
