### ISSUE TITLE
Could not load file or assembly 'Ionic.zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

### ISSUE THREAD

**Issue by brunoserrano** [xamarin/xamarin-android#1535]
### Steps to Reproduce

1. Update Visual Studio for Mac to Version 7.4.2 (build 12)
2. Archive Xamarin.Android project
3. Press "Sign and Distribute..."
4. Select Android Distribution Channel (any of them)
5. Select keystore, insert password

### Expected Behavior
Generate Android APK / Start publishing app on Google Play.

### Actual Behavior
ERROR:System.IO.FileNotFoundException: Could not load file or assembly 'Ionic.Zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. 

### Version Information

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: ccf2a17b-25b8-4c0e-82b0-9d2746789925
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Enterprise)
Android SDK: /Users/brunoserrano/Library/Android/sdk
	Supported Android versions:
		4.0.3 (API level 15)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Enterprise)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

AddinMaker 1.4.2

### Log File

--------------------------------------------------

> Begining distribution, 4/10/2018 12:42:58 PM
> Channel: Ad Hoc
> App Bundle Id: br.com.cartaomagnus.magnusempresario, Version: 2.0.0
> Publishing Ad Hoc to /Users/brunoserrano/Downloads/br.com.cartaomagnus.magnusempresario.apk
> Signing packages...
> Detected signing algorithm as : RSA
> ERROR:Signing Failed
> ERROR:System.IO.FileNotFoundException: Could not load file or assembly 'Ionic.Zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
> File name: 'Ionic.Zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null'
>   at MonoDevelop.MonoDroid.AndroidPublisher+<>c__DisplayClass59_0.<SignPackagesAsync>b__1 (System.Threading.Tasks.Task st) [0x00019] in /Users/builder/data/lanes/5810/0d8e3f0a/source/md-addins/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/Archival/AndroidPublisher.cs:274 
>   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00024] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
>   at System.Threading.Tasks.Task.Execute () [0x00010] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
> Saving state back to archive
> Finshed

--------------------------------------------------

> Begining distribution, 4/10/2018 12:43:22 PM
> Channel: Google Play
> App Bundle Id: br.com.cartaomagnus.magnusempresario, Version: 2.0.0
> Publishing to GooglePlay
> Signing packages...
> Detected signing algorithm as : RSA
> ERROR:Signing Failed
> ERROR:System.IO.FileNotFoundException: Could not load file or assembly 'Ionic.Zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
> File name: 'Ionic.Zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null'
>   at MonoDevelop.MonoDroid.AndroidPublisher+<>c__DisplayClass59_0.<SignPackagesAsync>b__1 (System.Threading.Tasks.Task st) [0x00019] in /Users/builder/data/lanes/5810/0d8e3f0a/source/md-addins/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/Archival/AndroidPublisher.cs:274 
>   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00024] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
>   at System.Threading.Tasks.Task.Execute () [0x00010] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
> Saving state back to archive
> Finshed
> 

![screen shot 2018-04-10 at 09 39 17](https://user-images.githubusercontent.com/2973295/38567629-1d33bab6-3cbd-11e8-9ef2-011b68d05439.png)
[Ide.2018-04-10__12-41-14.log](https://github.com/xamarin/xamarin-android/files/1895292/Ide.2018-04-10__12-41-14.log)
[Publishing.2018-04-10__12-41-14.log](https://github.com/xamarin/xamarin-android/files/1895330/Publishing.2018-04-10__12-41-14.log)

**Comment by bratsche** [comment]
@brunoserrano Hi, thanks for reporting this issue. I believe this has already been fixed in our development branch and latest preview release. We'll continue tracking this internally so we may be able to get it into another release for the current stable (15.6) as well. But in the mean time you're welcome to use a preview release.
