### ISSUE TITLE
App not refreshing on simulator when FastDev is disabled

### ISSUE THREAD

**Issue by joj** [xamarin/xamarin-android#1546]
### Steps to Reproduce

1. Open CrossDebuggingSample (I can share a link privately)
2. Set Configuration to Debug-Automatic
3. Run App
4. Modify code (I commented the first part of MainActivity.cs)
5. Run again

### Expected Behavior
App will be modified on the device, commented code will not run.

### Actual Behavior
Commented code is still there and running. If you set a breakpoint on the base.OnCreate() and then step over it, you'll notice the next executed line is on a comment.

### Version Information
This is happening on master.

### Log File
Build log on Run: https://gist.github.com/joj/040631a66b0b11760e8171114425dd4a

> VS bug [#660388](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/660388)

**Comment by jonathanpeppers** [comment]
@joj it worked for me on these builds:
- 15.6.6 Stable
- Internal 15.7.0 Preview 3
- Latest VSIX from monodroid master (installed into 15.7 preview)

I also reset the repo between each (`git clean -dxf ; git reset --hard HEAD`).

I'll get in touch with you tomorrow, and we can see if I'm doing something wrong.

**Comment by jonathanpeppers** [comment]
@joj I think this is surely working now? It's from April.

I'll close, let me know otherwise.
