### ISSUE TITLE
Subsequent unchanged installation fails if app manually uninstalled between deployment attempts

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1555]
It's possible this is by design, but it can lead to some confusing behaviors when the user enters this state.

### Steps to Reproduce

1. `msbuild /t:Install *.csproj`
2. Manually uninstall the app from device, or run `adb uninstall $(package)`
3. `msbuild /t:Install *.csproj`

### Expected Behavior
This is likely a bit of a corner case but it may make sense to make sure the application exists on device during an installation attempt, as if outputs are unchanged the application will not be installed even if it has been removed.

### Actual Behavior
Subsequent unchanged debug or deployment attempts fail from command line and the IDE if I manually uninstall the app in between attempts. 
### Version Information
https://gist.github.com/pjcollins/cddc3ac8a53b58c2bbcdbb56bf8b951a

### Log File
Secondary installation - https://gist.github.com/pjcollins/ecc46729d9c5ef5ee56410420623d1cd

**Comment by jonathanpeppers** [comment]
It looks like `GetPrimaryCpuAbi` is querying the device with `adb` already, but it uses a cached file on subsequent runs... I'm hoping that doesn't mean it's slow.

I could change this task to also query the status of the package, and not cache anything. I guess I should find out how much time this adds to the build first?

**Comment by dellis1972** [comment]
I have a PR on monodroid which should fix this issue. The solution is to kick of a background task just after `_ GetPrimaryCpuAbi` which checks for the uninstalled app.. If its uninstalled we delete the upload.flag file. This should occur before the `_Upload` target runs.

**Comment by jonathanpeppers** [comment]
I believe this is working in .NET 6+, so I think we can close. When testing apps I definitely `adb uninstall` at times, and things work fine.

I suspect one of the fixes here since 2018 solved this one: 

https://github.com/xamarin/monodroid/commits/main/tools/msbuild/Tasks/GetPrimaryCpuAbi.cs
