### ISSUE TITLE
Add error codes to Warnings

### ISSUE THREAD

**Issue by joj** [xamarin/xamarin-android#1560]
There is a `LogCodedWarning` method in Utilities (https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Utilities/MSBuildExtensions.cs#L119) that is never used, as far as I can tell. We need warnings to provide proper error codes, so VS can show them in the correct column in the error list and we can react automatically to known errors that may be fixed easily.

As part of this, we need to make sure that `LogCodedError` is used instead of `LogError` (or that `LogError` is always used with errorCode as a parameter), for the same reason.

> VS bug [#601721](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/601721)

**Comment by bholmes** [comment]
Jon found 2 instances of `LogCodedWarning ` via grep.  We do need more.

**Comment by jonpryor** [comment]
What we should *also* do is *document* these codes. We should add a new `Documentation/guides/messages` directory, which contains one `.md` file per warning/error code, which contains information about the message.

For example, `Documentation/guides/messages/xa4212.md` would contain information about error code XA4212, added in PR#797.

**Comment by jonathanpeppers** [comment]
@brendanzagaeski we made progress towards this in d16-0, but there are probably more codes...

Since this task is so open-ended, should we re-milestone to d16-1?

**Comment by brendanzagaeski** [comment]
Re-milestoning to d16-1 sounds good to me. I'll continue to prioritize the remaining items roughly based on how much project customization is required to hit each one, and I'll keep a tentative goal to complete all of them by the d16-1 milestone.

**Comment by jpobst** [comment]
This seems largely done.  Additional issue(s) should be opened for any remaining occurrences found.
