### ISSUE TITLE
Xamarin Android app build fails on Windows 10 with GetAdditionalResourcesFromAssemblies  throwing an exception (GenerateBuildSessionId in case of iOS)

### ISSUE THREAD

**Issue by srikcgaa2** [xamarin/xamarin-android#1580]
### Steps to Reproduce

1.   On a Windows 10 machine, ensure the group policy "System cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing" is set to "Enabled"
2.   Create a new Xamarin Android application in Visual Studio 2015 Professional Update 3.  Sample project attached with this issue.
3.   Build the project 

### Expected Behavior
Build should be successful

### Actual Behavior
Build fails due to a crash with GetAdditionalResourcesFromAssemblies   step throwing an InvalidOperationException.   If we create a new Xamarin iOS Application instead of Android, the failure occurs from GenerateBuildSessionId step

### Version Information

Please see the attached file for Visual Studio version information as well as Windows 10 system information along with the Security Group Policy screenshot.  Pasted below as well for quick reference

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Professional

Visual Basic 2015   00322-50052-91952-AA572
Microsoft Visual Basic 2015

Visual C# 2015   00322-50052-91952-AA572
Microsoft Visual C# 2015

Visual C++ 2015   00322-50052-91952-AA572
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ILSpy.AddIn   1.0
Integration of the ILSpy Decompiler into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Team Foundation Server 2015 Power Tools   14.0
Power Tools that extend the Team Foundation Server integration with Visual Studio.

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

Mono Debugging for Visual Studio   4.7.4-pre (c2d89eb)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

ShelvesetComparer   1.0
The extension allows you to compare files in two shelvesets.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.7.10.38 (34c1b6c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   8.0.2.1 (c2a33d8)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   11.3.0.47 (51128b8)
Visual Studio extension to enable development for Xamarin.iOS.

### Log File

Xamarin Log file attached. Please check the logs dated 19/April/2018

[App2.zip](https://github.com/xamarin/xamarin-android/files/1927335/App2.zip)
![security policy](https://user-images.githubusercontent.com/24926263/38981221-7e0bf7c4-43dc-11e8-8f16-9b6d284a55fb.PNG)
[System Info.txt](https://github.com/xamarin/xamarin-android/files/1927338/System.Info.txt)
[VS Studio info.txt](https://github.com/xamarin/xamarin-android/files/1927339/VS.Studio.info.txt)
[XamarinLogs.zip](https://github.com/xamarin/xamarin-android/files/1927340/XamarinLogs.zip)

**Comment by srikcgaa2** [comment]
Android build error

Skipping target "_GenerateAndroidAssetsDir" because it has no outputs.
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061: The "GetAdditionalResourcesFromAssemblies" task could not be instantiated from "C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Build.Tasks.dll".  [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms. [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061:    at System.Security.Cryptography.MD5CryptoServiceProvider..ctor() [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061:    --- End of inner exception stack trace --- [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061:    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061:    at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args) [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061:    at System.Security.Cryptography.MD5.Create() [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4061:    at Xamarin.Android.Tasks.GetAdditionalResourcesFromAssemblies..ctor() [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(396,2): error MSB4060: The "GetAdditionalResourcesFromAssemblies" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name. [E:\WS\B1\Components\CDAS\com\medtronic\utilities\crypto\Utilities.Crypto.csproj]

**Comment by srikcgaa2** [comment]
### iOS Build Error

Project "E:\WS\B1\Utilities.sln" (1) is building "E:\WS\B1\\platform\Platform.csproj" (3) on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets(17,5): error MSB4018: 
#### The "GenerateBuildSessionId" task failed unexpectedly. 
[E:\WS\B1\\platform\Platform.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets(17,5): error MSB4018: 
#### System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms. 
[E:\WS\B1\\platform\Platform.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets(17,5): error MSB4018:    at
#### System.Security.Cryptography.MD5CryptoServiceProvider..ctor() 
[E:\WS\B1\\platform\Platform.csproj]
Done Building Project "E:\WS\B1\\platform\Platform.csproj" (default targets) -- FAILED.

**Comment by bbreland19** [comment]
Same thing happening to me as well.

**Comment by cyberjetx** [comment]
Still broken in 2019.  Can we please get a fix in.  Deleting the key at 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy

NOR disabling 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy]
"Enabled"=dword:00000001 -> dword:00000000 

work at this time. 

`The "GenerateBuildSessionId" task failed unexpectedly.
System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()`

**Comment by kealist** [comment]
@jonathanpeppers This basically is making it so that our company cannot use Xamarin due to government requirements for IT.  It seems for the most part that MD5 is used for the naming of cache directories, so there must be an alternative that doesn't use broken cryptographic algorithms.

I was trying to download source and take a look at it, but the `/Prepare` stage is failing to download the android files:  (links work, so not sure why it would be failing)

        downloading android-2.3.3_r02.zip
        downloading android-15_r05.zip
        downloading android-16_r05.zip
        downloading android-17_r03.zip
        downloading android-18_r03.zip
        downloading android-19_r04.zip
        downloading android-20_r02.zip
        downloading android-21_r02.zip
        downloading android-22_r02.zip
        downloading platform-23_r03.zip
        downloading platform-24_r02.zip
        downloading platform-25_r03.zip
        downloading platform-26_r02.zip
        downloading platform-27_r03.zip
        downloading platform-28_r04.zip
        downloading platform-29_r01.zip
        downloading docs-24_r01.zip
        downloading android_m2repository_r47.zip
        downloading x86-29_r06.zip
        downloading android-ndk-r20-windows-x86_64.zip
        downloading build-tools_r29-windows.zip
        downloading sdk-tools-windows-4333796.zip
        downloading emulator-windows-5598178.zip
    Download progress: 8.59% (307 MB at 307 MB/s)
    Download progress: 8.59% (307 MB at 1.29 KB/s)
    Download progress: 8.59% (307 MB at 22.5 KB/s)
    Download progress: 8.59% (307 MB at 9.04 KB/s)
    Download progress: 8.59% (307 MB at 7.75 KB/s)
    Download progress: 8.59% (307 MB at 3.88 KB/s)
    Download progress: 8.59% (307 MB at 11.6 KB/s)
    Download progress: 8.59% (307 MB at 14.2 KB/s)
    Download progress: 8.59% (307 MB at 3.88 KB/s)
    Download progress: 8.6% (307 MB at 41.8 KB/s)

    Step Xamarin.Android.Prepare.Step_Android_SDK_NDK failed: Failed to download https://dl.google.com/android/repository/android-2.3.3_r02.zip: The read operation failed, see inner exception.
    System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_Android_SDK_NDK failed: Failed to download https://dl.google.com/android/repository/android-2.3.3_r02.zip: The read operation failed, see inner exception
    . ---> System.InvalidOperationException: Failed to download https://dl.google.com/android/repository/android-2.3.3_r02.zip: The read operation failed, see inner exception. ---> System.IO.IOException: The read operation fa
    iled, see inner exception. ---> System.Net.WebException: The request was aborted: The request was canceled.
        at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
        at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
        --- End of inner exception stack trace ---

**Comment by jonathanpeppers** [comment]
@kealist I would just try the command again, it doesn't have a network retry yet, you can double-check that URL in a browser: https://dl.google.com/android/repository/android-2.3.3_r02.zip

There is also a video here if that is helpful: https://youtu.be/8qaQleb6Tbk

**Comment by kealist** [comment]
@jonathanpeppers Thank you.  Watching video.  Unfortunately it fails on those downloads even if retrying or using different consoles.  I tried with MSbuild 15 and 16.  I don't want to pollute this issue with off topic build issues. though

**Comment by igloo15** [comment]
I just wanted to add that we are also running into this problem recently. New security guidance at my company as mandated from government customers is to have this FIPS policy enabled. There is no way around it so now we are quickly becoming unable to build Xamarin projects. 

I hope this is fixed soon surprised this has taken so long to get on people's radar considering it was reported over a year ago.

**Comment by kealist** [comment]
I do believe this is resolved for me now.

**Comment by jpobst** [comment]
Agreed, I think the policy checks MS Security has added to our build pipeline ensure there are currently no more non-FIPS compliant algorithms, and it should fail our build if any ever get added back.
