### ISSUE TITLE
Use implicit doc redirection

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1584]
The Windows `.vsix` file is *huge*, for two reasons (among others):

1. We have to ship `Mono.Android.dll` for *14* (soon to be *15*) `$(TargetFrameworkVersion)` values, and *each one* is around 20MB in size.
2. *Documentation XML Files*.

Documentation is *larger than* the assemblies:

```
$ unzip -l ~/Downloads/Xamarin.Android.Sdk.8.3.0.18.vsix | grep xml$
 57309057  04-17-2018 15:07   $ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v4.2/Mono.Android.xml
      131  04-17-2018 15:07   $ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v7.0/AndroidApiInfo.xml
 57309057  04-17-2018 15:07   $ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v4.3/Mono.Android.xml
...
```

~57 *MB* for `Mono.Android.xml`, for *each* `$(TargetFrameworkVersion)`. (Then there's `mscorlib.xml`, which is full of `To be added` docs, and thus useless...)

However, documentation supports "redirection":

```xml
<doc redirect="%PROGRAMFILESDIR%Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\mscorlib.xml" />
```

We should check to see if `/doc/@redirect` can contain *relative* paths, and if it *can*, we can replace all but the "latest" `Mono.Android.xml` with a "redirect" to the latest, a'la:

```xml
<?xml version="1.0" encoding="utf-8"?>
<doc redirect="..\v8.1\Mono.Android.xml" />
```

> VS bug [#603386](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/603386)

**Comment by kzu** [comment]
I'd also consider redirecting all the .NET reference assemblies (`System.*`) so that they all point to the properly documented files that come in the box with VS

**Comment by jonpryor** [comment]
@kzu: Interesting idea, but...where's the documentation for those assemblies? Within `%VSInstallDir%`, `dir /s mscorlib.xml` only finds the file that Xamarin.Android installs. Ditto for `dir /s System.xml`.

Where is the documentation for `mscorlib.dll` and "all the .NET reference assemblies" kept?

**Comment by kzu** [comment]
Sorry for the delay @jonpryor. I'm quite sure those are loaded from the full framework location, at C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v[VERSION]

**Comment by mhutch** [comment]
Given that the Xamarin mobile framework includes netcore APIs that don't exist in netframework, I don't think it's ideal to use the netframework docs. That said, maybe the differences don't matter enough yet.

**Comment by mhutch** [comment]
Couldn't we generate them from Mono's monodoc based docs?

**Comment by kzu** [comment]
I guess. No idea what's involved.

**Comment by marek-safar** [comment]
For Xamarin SDKs we need to start following netcore docs as that's the real API and implementation the users work with. I don't know why we need to ship the .xml files when more comprehensive documentation is available online. What about replacing Mono supplied xmls with links like https://docs.microsoft.com/en-us/dotnet/api/system.string.-ctor?view=netcore-2.1#System_String__ctor_System_ReadOnlySpan_System_Char__ ?

**Comment by mhutch** [comment]
@marek-safar the XML docs files are used for intellisense tooltips

**Comment by AmadeusW** [comment]
I have a fix [available internally](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/136028)
It fixes the code that opens the file, and additionally adds support for relative paths, e.g. `"..\v8.1\Mono.Android.xml"`.

FYI, the underlying code uses the [CreateFileW](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilew) API which according to my experiments does not expand %ENVIRONMENT_VARIABLES%.

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '15.9' that is not in the list of supported values
