### ISSUE TITLE
GC.Collect() call crashes app (API Level 15)

### ISSUE THREAD

**Issue by yaliashkevich** [xamarin/xamarin-android#1593]
### Steps to Reproduce

1. Create sample android project from VS for Mac Template (button click counter)
2. Modify button click event
```
            button.Click += delegate { 
                button.Text = $"{count++} clicks!";
                GC.Collect();
            };
```
3. Run app on android simulator (API level 15)
4. Hit the button

[sample.zip](https://github.com/xamarin/xamarin-android/files/1942259/sample.zip)

### Expected Behavior
App counts clicks
### Actual Behavior
App crashes after first click
### Version Information

[environment.txt](https://github.com/xamarin/xamarin-android/files/1942263/environment.txt)

### Log File

[simulator.api15.txt](https://github.com/xamarin/xamarin-android/files/1942261/simulator.api15.txt)
[log.txt](https://github.com/xamarin/xamarin-android/files/1942262/log.txt)

**Comment by jpobst** [comment]
Assuming this issue is obsolete as we have not received any more reports in currently supported versions.
