### ISSUE TITLE
ConcurrentHashMap doesn't work as expected when use byte array as key in Xamarin

### ISSUE THREAD

**Issue by lin-zy1229** [xamarin/xamarin-android#1598]
Here is code block I use in Xamarin.

```
Java.Util.Concurrent.ConcurrentHashMap map = new Java.Util.Concurrent.ConcurrentHashMap();
var key = new byte[] { 1, 2, 3 };
var data = new byte[] { 1, 2, 3, 4, 5 };

map.Put(key, data);
var val = map.Get(key); // null, WHY?

IEnumeration keys = map.Keys();
while (keys.HasMoreElements)
{
    var k = keys.NextElement();
    var val2 = map.Get(k); // NOT null, val2 is byte array of {1,2,3,4,5}
}
```

I expected `val `is byte array (data), but `val `is null, while `val2 `is not null.

But this Java code works very well.

```
java.util.concurrent.ConcurrentHashMap map = new java.util.concurrent.ConcurrentHashMap();

byte[] key = {1, 2, 3};
byte[] data = {1, 2, 3, 4, 5};

map.put(key, data);
Object o = map.get(key); // byte array of {1,2,3,4,5}
```

What is the reason?

**Comment by jonpryor** [comment]
> What is the reason?

Same reason [as here](https://github.com/xamarin/xamarin-android/issues/1624#issuecomment-386168032): arrays are *deep marshaled* on every call, resulting in a new/unique array instance on every method call.

Out of curiosity, why are you using `Java.Util.Concurrent.ConcurrentHashMap` and not [`ConcurrentDictionary<byte[], byte[]>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=netframework-4.7.1)?

**Comment by jonpryor** [comment]
Addendum: if you use a `Java.Lang.Object` intermediary, it will work as you intend:

```csharp
var map = new Java.Util.Concurrent.ConcurrentHashMap();
Java.Lang.Object key = new byte[] { 1, 2, 3 };
var data = new byte[] { 1, 2, 3, 4, 5 };

map.Put(key, data);
var val = map.Get(key); // val won't be null
```

`val` *will*, however, be a `Java.Lang.Object`. To get a `byte[]` back out, use the [`(byte[])` cast operator](https://github.com/xamarin/xamarin-android/blob/b0efc6ad8a79d592c2771628feba1a21a036d6cd/src/Mono.Android/Java.Lang/Object.cs#L679-L684):

```csharp
byte[] valData = (byte[]) val;
```

**Comment by lin-zy1229** [comment]
Thanks so much, @jonpryor
