### ISSUE TITLE
Unable to open file for read: No such file or directory (APT0000) Intermittent Build Error

### ISSUE THREAD

**Issue by justintoth** [xamarin/xamarin-android#1608]
### Steps to Reproduce

Our Xamarin Android app only builds and deploys successfully probably 25% of the time, and when updating the contents of an axml file then building it pretty much never succeeds. I then have to go through a process of cleaning, rebuilding, uninstalling the app from the device, closing and reopening Visual Studio for Mac, etc... This has always been the case with Xamarin dating back to Xamarin Studio because it's so much more buggy than the real Visual Studio IDE, however it's gotten much worse in the latest release. It's painful to have to go through these steps 30x per day just to test out changes.

1. Open our Xamarin Android solution (can provide through secure method.)
2. Try combination of building / rebuilding / cleaning / deploying app to a device, especially after changing the contents of an axml file (e.g. add a new element so that ResourceDesigner is updated.)
3. Notice that when building it sometimes gives a APT0000 build error that is associated with a tmp file, which is some sort of Xamarin file, not a real file in my solution.

### Expected Behavior

The app builds successfully EVERY TIME, not 25% of the time like it currently does.

### Actual Behavior

> /Users/justintoth/Documents/rpr-mobile/android-application/obj/Debug-Dev/lp/36/jl/res/values-az/values.xml.tmp: Error APT0000: Unable to open file for read: No such file or directory (APT0000) (com.rpr.mobile.droid)
> /Users/justintoth/Documents/rpr-mobile/android-application/obj/Debug-Dev/lp/36/jl/res/values-az/values.xml.tmp.bk: Error APT0000: Unable to open file for read: No such file or directory (APT0000) (com.rpr.mobile.droid)

### Version Information

=== Visual Studio Community 2017 for Mac ===

Version 7.4.3 (build 10)
Installation UUID: 62cf1ad2-0db0-41e1-ac78-aeb509d79f60
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.29 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /android/sdk
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704030010
Git revision: 5af3e98549653fcc5335896ccc296343d08f31bb
Build date: 2018-04-12 12:32:07-04
Xamarin addins: fadb82fb0fe2668cb7789f8b524aec6fb8568ee7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

### Log File

https://gist.github.com/justintoth/d797e9432a7b47c71bf5c5fd90c99cdb

**Comment by jonpryor** [comment]
@justintoth: Could you please provide [diagnostic build output](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)

**Comment by justintoth** [comment]
@jonpryor 
[Build output](https://gist.github.com/justintoth/7dd67c4850a9c5a8998b88632916d441)
[Deploying to device](https://gist.github.com/justintoth/88db019045816121a930a8f155762a0e)

**Comment by dellis1972** [comment]
I suspect this is related to [1] which should be fixed in the d15.7 Preview builds.

[1] https://github.com/xamarin/xamarin-android/commit/b0f4dea6f0731b9a50adaa424ebc3b365caa372a#diff-6e0e3f9d6eaef0a2aac52905be4384df

**Comment by dellis1972** [comment]
Is this still an issue? It should have been fixed by the commit above.
