### ISSUE TITLE
any plans to match kotlin style of android dev?

### ISSUE THREAD

**Issue by touseefbsb** [xamarin/xamarin-android#1612]
xamarin.android currently uses c# but follows the coding pattrens and practices of java used in android, for example getting the resource id and then using it, and many other as well, on the other hand android world is being caught with a storm of kotlin adaption, knowing that kotlin uses a lot lesser code and simplifies android development, for example we dont need to get resource id in order to access them or use them.

So my main question being here is, "Will xamarin.android adapt to kotlin style and way of developing android? or will it stick to java style?"

**Comment by touseefbsb** [comment]
totally agree with @andre-ss6  xamarin.forms is just not good enough, too much overhead , making it native performant is near to impossible, while xamarin.android and xamarin.ios seem good enough,  I want to keep using c# and other productivity features of Microsoft like VS, VSTS, azure and other stuff, that is why I want to use xamarin.android, but the thing is it follows and binds with java android development, whole kotlin is a hell lot better than java for android, in every way possible, less code, less errors, more performance etc, so it would be great if xamarin.android directly syncs its library and bindings with kotlin world of android :) bcz very soon all native development will be done with kotlin, even existing java apps on store are being ported to kotlin by their developers.

**Comment by jonpryor** [comment]
> Will xamarin.android adapt to kotlin style and way of developing android?

@touseefbsb: Links to what you *specifically* mean would be appreciated; I *assume* you mean the [Kotlin Android Extensions](https://kotlinlang.org/docs/tutorials/android-plugin.html), which allows avoiding `findViewById()` by generating "properties" at build-time.

*Assuming* that's what you mean, would [Bindings or Code-Behind](https://github.com/xamarin/xamarin-android/blob/b0efc6ad8a79d592c2771628feba1a21a036d6cd/Documentation/guides/LayoutCodeBehind.md) work for you? This is an experimental feature slated for inclusion in Visual Studio 15.8.

**Comment by touseefbsb** [comment]
@jonpryor  I was not aware that this is actually a separate extension of kotlin to use these features, I thought this was built in default feature of the kotlin language for android, because when I used it with androidStudio I got those features by default. and yes the bindings or code behind feature seem to move towards what I was looking for, to some extent, I am not a anroid expert, so I am not sure which kotlin-android features are missing from Xamarin.android uptil now, but from what I know Xamarin uses java-android bindings in order to create fast and native performant android apps, so I was wondering if the bindings can be with kotlin-android APIs I am not sure if I am able to explain exactly what I am thinking but to summarize it : 

> Xamarin.Android was created by making a wrapped around java-android APIs and now kotlin is the future of native android development, so how about wrapping kotlin-android APIs now instead of java? in newer version of Xamarin.Android?

**Comment by touseefbsb** [comment]
just some stuff to have a look at from google io 18, they are massively improving the platform. https://www.youtube.com/watch?v=0raqVydJmNE&list=PLOU2XLYxmsIInFRc3M44HUTQc3b_YJ4-Y&index=38

https://developer.android.com/jetpack/
