### ISSUE TITLE
Support ConstraintLayout in the VS Designer

### ISSUE THREAD

**Issue by andre-ss6** [xamarin/xamarin-android#1625]
### Steps to Reproduce

1. Create a new project
2. Change the Main view to use ConstraintLayout
3. Switch to the designer

### Expected Behavior

I can use the designer as usual, with drag&drop and etc.

### Actual Behavior

One of those three, depending on Xamarin's mood:

1. A mock view labeled "ConstraintLayout"
2. A red screen
3. A correctly rendered view, but unable to be edited (unable to use drag&drop)

### Version Information
Visual Studio 2017, Xamarin 8.1, Xamarin.Android.Support.Constraint.Layout 1.1.0 Nuget package

> VS bug [#609834](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/609834)

**Comment by garuma** [comment]
Hey,

We added support for basic drag&drop to ConstraintLayout in Visual Studio 2017 15.7 (just what you describe without actual constraint editing).

NuGet interactions in Visual Studio are currently quite finicky and it's easy to get into a bad state. Make sure your project compiles correctly before opening the designer and you can try disabling automatic NuGet restore which can help as well.

**Comment by andre-ss6** [comment]
Ok, thanks! I hope it gets better in future versions.
