### ISSUE TITLE
Publish a roadmap

### ISSUE THREAD

**Issue by andre-ss6** [xamarin/xamarin-android#1626]
What are your plans for the platform for the next years? Will you keep updating the platform? Do you plan to make the current experience better? There are still outstanding issues from over two years that haven't been fixed. Do you plan to fix those? When?

Right now, from the outside, it looks like you are obsoleting the classic platforms in favor of Xamarin.Forms (or at least plan to do so in the near future).

 I want to know if I can invest my company's resources into this platform.

**Comment by jonpryor** [comment]
> What are your plans for the platform for the next years?

Fix bugs and improve reliability and performance and aim to provide the best developer experience possible.

> Will you keep updating the platform?

Yes.

> Do you plan to make the current experience better? 

Yes. :-)

> There are still outstanding issues from over two years that haven't been fixed. Do you plan to fix those? When?

At this point, *I* don't think "completely bug free" software is *possible*...unless you're [Donald Knuth and writing TeX](https://en.wikipedia.org/wiki/TeX).

We don't have unlimited resources. We fix what we can, improve what we can, and endlessly debate the boundary between "bug" and "feature" (e.g. is improving build times fixing a bug, or working on a feature?). There will almost certainly continue to be bugs, and we will do our best to address them.

> Right now, from the outside, it looks like you are obsoleting the classic platforms

What *specifically* gives you this impression? Xamarin.Android master has a prototype [API-P binding](https://github.com/xamarin/xamarin-android/commit/8ce253769a4b38de51ba22ccfb2c38dd5c852f9f), though we're still trying to figure out how best to *release* that binding for people who *don't* use [Jenkins Build Artifacts](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/JenkinsBuildArtifacts.md).

**Comment by andre-ss6** [comment]
> [...] endlessly debate the boundary between "bug" and "feature" (e.g. is improving build times fixing a bug, or working on a feature?)

I know this is the Xamarin.Android repo and you're from the Xamarin.Android team, but I guess there must be some overlap...

Yea, I agree that it may be hard to decide whether improving build times is a bug or a feature - a normal PBI. However, is it that hard to decide between "stabilizing tooling" vs "XAML Intellisense"? And this brings me to the next point.

> What specifically gives you this impression? Xamarin.Android master has a prototype API-P binding

I know you've been still hard at work with Xamarin.Android and I also know about the P bindings. I've even been using that as evidence that the platform is still evolving. However, to be honest, I'm yet to fully convince _myself_ of that. 

Since the Microsoft acquisition, there seems to be just so much focus on the Xamarin.Forms platform. We barely hear anything about the classic platform. Forms has a full roadmap planned and published, with complex and/or time-consuming features planned and being worked on. We see Xamarin.Forms news in the VS Start Page every month. In the meantime, we classic developers still get to experience the same frustrations we did way back on 2016 (I won't dare to go way too much back because I don't have the knowledge/experience), with no info whatsoever as to what the devs are doing. You see things like the Xamarin forums filled with furious rants about how the platform is bad; reddit filled with negative comments about the platform; the SO Developer Survey 2018 showing Xamarin as the second most dreaded framework among developers; medium posts just hating constantly on the platform; And in every one of these places (except for the Xamarin forums, of course) you see all kind of people - PMs, Evangelists, etc - from a lot of different technologies/frameworks, asking for feedback, trying to convince people to use the platform, trying to understand people frustrations...

Now, of course marketing from other technologies won't kill Xamarin. I'm not saying that. But let's just remember that Microsoft has some pretty long history with abandoning frameworks/redoing things from scratch. So yea, my _biggest_ fear is not that Xamarin will be abandoned by the community - instead, that it will be abandoned by Microsoft.

I hope this makes it clear as to why I feel insecure about the future of the platform.

**Comment by andre-ss6** [comment]
@touseefbsb Well, first of all let's not derail this topic please :). But I'll try to answer your questions.

> I would really appreciate if you could help me or guide me in making this decision

It's a bit hard for me to help to answer this because I'm facing the same dilemma.
I think that if you just love C# and .NET and you don't have the responsibility of reporting your team's productivity and won't be blamed by managers on bad technical decisions, than yea, go for it. Embrace Xamarin. It has issues, but you'll be working with C#. But if you're working on some really serious project (meaning: you have to report back to someone), then, well, wait with me for a response here so we know what will be the future of this platform. Lastly, if your app uses some really complex __niche__ tool like offline geocoding or specialized image processors, then know you may not have a good time with Xamarin; Kotlin's learning curve isn't really that steep and as you've guessed, C# and Kotlin shares a lot of the same features, so you've already got some background knowledge there.

In relation to Azure, I don't think it matters _much_ what framework you choose. There are plenty of support for plenty of different technologies. Azure is meant to be completely technology-agnostic. It was renamed from Windows Azure to Microsoft Azure for a reason hehe.

In relation to Flutter, well, it's anyone's guess. As you've noticed, Flutter is something like of a competitor to Kotlin - that is because Flutter is not really "a Google project" in the sense that the company is really putting weight behind it - it's more like a internal project that got greenlighted. So yea, although it seems very promising and looks really attractive, I think the risk associated with Flutter is way, __way__ higher than with Xamarin.

**Comment by touseefbsb** [comment]
Thanks that clarifies a lot. I think I might go for kotlin as learning it wont hurt and in the long run I will get every android feature support simply and easily. but I will keep on eye on xamarin progress as well, if it gets better I can switch to xamarin as I am the decision maker in my scenario lol

**Comment by touseefbsb** [comment]
@JonDouglas  I appreciate it. but obviously we cant disturb u everytime we encounter a bug or a problem with xamarin.android. one of the worry points are the 3rd party libraries, which seem to be usually out dated. do u have any solution for that?

**Comment by andre-ss6** [comment]
@JonDouglas Thank you for the response! I really appreciate it!

>The Xamarin.Android repository however is used for the Xamarin.Android SDK.

I know this is important to you as a Xamarin developer, but you have to understand that as customers _we don't care_ . And I don't mean to come off as rude or offensive _in any way_  - it's just that all developers know this: when a customer complains about something, you can't just tell them "oh that's because you're not using it the way _we_  initially built it to be used". He doesn't care. He just want his feature. And the guys at Microsoft seem to understand this, since, as I said in an earlier reply, Xamarin.Forms news are all over the place: Visual studio blog/start page, Visual studio magazine, Twitter and of course the official roadmap on GitHub - which is full of big features planned. 
So I don't care if the official roadmap is here or elsewhere, I just want to know when (or even if!!) the mentioned issues will be resolved.

I know it isn't that simple, but I don't know, can't you just talk to each other in there, maybe talk to the Visual studio PMs, and tell them that although Xamarin may be a great _technology_, it isn't that great of a platform? Coding in C# may be awesome, but the issues are simply too intrusive to ignore. It feels completely different to work on a Xamarin project and an ASP.NET project. The difference in quality of the tooling/stability is just too big. When I'm working with Xamarin I feel completely out of vs. Just do a quick search on Google on "Xamarin sucks" and you'll see dozens of forums posts complaining about a myriad of issues. But what is _really_  sad is to see that these issues people complained about back in 2016 are still present in the product, two years later. The other day I asked on Reddit if Xamarin is any better - since I hadn't worked with it for some months - to try find arguments to convince my team and myself to make the switch, and people just bashed on the platform, telling me to stay away from it (funny: a flutter PM, which used to be a visual studio PM at Microsoft until recently, replied to the thread, defending Flutter from some accusations, encouraging me to use Flutter and offering help. They _must_  have a marketing department :joy:). I still came back to Xamarin though, only to find out they were right. Anyway, I digress. I'm sorry, it's just too hard to contain the sorrow and rage.

>We are working to improve our overall Android experience roadmap to show more new features that will be included in a future Visual Studio version.

This seems awesome! Even if the current experience may have some issues, knowing that they'll be resolved and how the platform will evolve is enough to be able to make a conscious decision on whether or not to bet your resources on it. This may even spark more interest around the community, inviting more contributors, of which the platform is really in need.

By the way: maybe Android studio integration would pay off more than vs. One of the things I'm considering doing here is to let people keep using AS and make an internal extension to keep files on sync (I know there is such an extension on the marketplace, but I also had problems with it).

>For general Xamarin.Android related pain points, I'd like to invite you both to email me and we can setup a call to walk through them.

Sure! I'll keep note of this. Thanks!
Currently I'm just asking my team to hold on as I keep investigating on how to avoid these issues with Xamarin. If we do choose Xamarin and we have any problem I'll make sure to go after some help!

**Comment by JonDouglas** [comment]
We have made a conscious effort to include all high level features in the [Visual Studio Roadmap](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap) and [Visual Studio for Mac Roadmap](https://docs.microsoft.com/en-us/visualstudio/productinfo/mac-roadmap) that should give you an idea of where Xamarin is headed.

For specific features inside this repository, we work with both [Pull Requests](https://github.com/xamarin/xamarin-android/pulls) and [Projects](https://github.com/xamarin/xamarin-android/projects). This can give you an idea of what is being worked on, and when it will land with the respective `Milestone` or `Branch` being added to.

Additionally, you can now [Suggest a Feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) which, if accepted will be added to the public roadmap.

We will consider in the future a repository specific roadmap for features specific to repositories that do not land on the roadmap, however for the time being, we currently aggregate all of these items to the Visual Studio Roadmaps. Thus I am closing this issue for now.
