### ISSUE TITLE
System.InvalidCastException: Unable to convert instance of type 'Android.Widget.LinearLayout' to type 'Android.Support.V7.Widget.Toolbar'.

### ISSUE THREAD

**Issue by Nixon-Joseph** [xamarin/xamarin-android#1641]
### Steps to Reproduce

1. Build and run repro on Pixel XL 8.1 stock - only happens when proguard is enabled.

I think it'll happen on any device 8.0 + (unproven)

REPRO
https://drive.google.com/file/d/1qo3TtgJb-wnXyHKWuqLJLJGw5fPvEgfD/view?usp=sharing

### Expected Behavior
Run fine

### Actual Behavior
Throws exception in MainActivity.onCreate

### Version Information
***All in repro*** - sorry, out of time, can't type all this info

Hope it fails for you guys too.

**Comment by JonDouglas** [comment]
@Nixon-Joseph Unfortunately this reproduction won't compile as there are many code references to libraries that are not defined in the `.csproj` via `<PackageReference>` or `packages.config`. I will try to start from a new Xamarin.Forms template and see if I can see the behavior with ProGuard enabled.

@dehghani-mehdi If you do run into this again, please feel free to include the output of the exception.

**Comment by Nixon-Joseph** [comment]
Weird, I compiled it before posting it, and it ran as expected... I'll try to take another look at it Monday.

**Comment by Nixon-Joseph** [comment]
Oddly, I wasn't able to get that repro to work either (after downloading it). I'll see what I can do as far as creating a new project with the same problem. Just saw that Xamarin.Forms had an update, any chance that'll fix it?

**Comment by dehghani-mehdi** [comment]
@JonDouglas you can reproduce the issue using following steps (_Visual Stuido v15.7.0_):

1. File -> New Project -> Android -> Android App
2. Select Blank App (_Minimum Android 4.2_)
3. Change to Release mode
4. Enable ProGuard
5. Linking, SDK and User Assemblies
6. Archive and Sign
7. Try to install final APK on device (I tired on Genymotion)

You will see app will crash on load

**Comment by jpobst** [comment]
Assuming this issue is obsolete as we have not received any more reports in currently supported versions.
