### ISSUE TITLE
"make install" fails because of bogus Makefile script

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1648]
This is what happens when you run `make prefix=/devel install` while you already have `/devel/lib/xamarin.android` .

	$ make prefix=/devel install
	tr: warning: an unescaped backslash at end of string is not portable
	tr: warning: an unescaped backslash at end of string is not portable
	mkdir -p "/devel/bin"
	mkdir -p "/devel/lib/mono/xbuild-frameworks"
	mkdir -p "/devel/lib/xamarin.android"
	mkdir -p "/devel/lib/mono/xbuild/Xamarin/"
	# -rm -rf "/devel/lib/xamarin.android/" # FIXME: delete it
	cp -a "bin/Debug/lib/xamarin.android/" "/devel/lib/xamarin.android/"
	rm -rf "/devel/lib/mono/xbuild/Xamarin/Android"
	rm -rf "/devel/lib/mono/xbuild-frameworks/MonoAndroid"
	ln -s "/devel/lib/xamarin.android/xbuild/Xamarin/Android/" "/devel/lib/mono/xbuild/Xamarin/Android"
	ln -s "/devel/lib/xamarin.android/xbuild/Novell/" "/devel/lib/mono/xbuild/Novell"
	ln: failed to create symbolic link '/devel/lib/mono/xbuild/Novell/Novell': File exists
	Makefile:39: recipe for target 'install' failed
	make: *** [install] Error 1

This is the problematic use of `cp`: https://github.com/xamarin/xamarin-android/blob/master/Makefile#L47

Actually I made a change before running it - `# -rm -rf "/devel/lib/xamarin.android/"`. By enabling this line it will work.

Maybe this is unsophisticated use of `cp` based on Mac experience.

**Comment by atsushieno** [comment]
This has been blocking development on Linux for weeks.

**Comment by jonpryor** [comment]
I do not understand what's problematic about the use of `cp`. There is certainly no error message reported around `cp` use.

There *is* an error reported from `ln`, because the `Novell` directory isn't deleted. Does this patch fix `make install` for you?

```diff
diff --git a/Makefile b/Makefile
index ee38f21a..920c9bd7 100644
--- a/Makefile
+++ b/Makefile
@@ -45,6 +45,7 @@ install::
        -mkdir -p "$(prefix)/lib/xamarin.android"
        -mkdir -p "$(prefix)/lib/mono/xbuild/Xamarin/"
        cp -a "bin/$(CONFIGURATION)/lib/xamarin.android/." "$(prefix)/lib/xamarin.android/"
+       -rm -rf "$(prefix)/lib/mono/xbuild/Novell"
        -rm -rf "$(prefix)/lib/mono/xbuild/Xamarin/Android"
        -rm -rf "$(prefix)/lib/mono/xbuild-frameworks/MonoAndroid"
        ln -s "$(prefix)/lib/xamarin.android/xbuild/Xamarin/Android/" "$(prefix)/lib/mono/xbuild/Xamarin/Android"
```

**Comment by atsushieno** [comment]
I believe so, could we just make that change to Makefile?
