### ISSUE TITLE
Xamarin android webview incorrect device.width/height value

### ISSUE THREAD

**Issue by IlyaSemenchenko** [xamarin/xamarin-android#1649]
We use android webkit Webview to show different content inside the app. And we have problems with sites that rely on screen.width/screen.height to select desktop/mobile mode. Xamarin android app with simple Webview activity return sizes in pixel(example for google below): 
Xamarin android: screen sizes in pixels for Google Nexus 5, API 21, 1080x1920
![firstimagexamarin](https://user-images.githubusercontent.com/39047408/39968741-b73ee360-56da-11e8-84d4-67d76b259024.png)

However when I created the same app in Android Studio I got sizes in dpi: 
Native android: screen sizes in pixels for Google Nexus 5, API 21, 1080x1920
![secondimagenative](https://user-images.githubusercontent.com/39047408/39968750-f18c558e-56da-11e8-9f93-7d27cb233523.png)

### Steps to Reproduce

1. Create a simple Xamarin Anroid app with webview
2. Check screen.width and screen.height in Chrome browser Debug Console
(WebView.SetWebContentsDebuggingEnabled(true) was added in both projects)

[TestWebviewAppXamarin.zip](https://github.com/xamarin/xamarin-android/files/1978972/TestWebviewAppXamarin.zip)
[TestWebviewAppNative.zip](https://github.com/xamarin/xamarin-android/files/1978990/TestWebviewAppNative.zip)

### Expected Behavior
Screen sizes in dpi
### Actual Behavior
Screen sizes in pixels
### Version Information

Microsoft Visual Studio Community 2017 
Version 15.6.5
VisualStudio.15.Release/15.6.5+27428.2027
Microsoft .NET Framework
Version 4.7.02556

Xamarin   4.9.0.753 (f0f46392f)

**Comment by IlyaSemenchenko** [comment]
Hi Jonathan, 

I copied this question from Stackoverflow and didn`t notice that all link was broken, sorry. I updated the question.

> Shot-in-the-dark guess: Please try adding an android:targetSdkVersion attribute value to <uses-sdk/> in your Xamarin app. That may resolve the problem for you.
And you was absolutely right, setting android:targetSdkVersion in android manifest make the trick.
 
Thank you!

**Comment by JonDouglas** [comment]
I am closing this issue based on confirmation in https://github.com/xamarin/xamarin-android/issues/1649#issuecomment-388636634. Please feel free to re-open or file a new issue if you are still encountering this issue.
