### ISSUE TITLE
Getting build failure for Cheesesquare sample in both debug and release mode 

### ISSUE THREAD

**Issue by parasAmbhore** [xamarin/xamarin-android#1669]
Moving VSTS bug [BUG 614180](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/614180) to this repo 

Affected Branch: master
Affected Build:  Version 7.6 Preview (7.6 build 750)
Affected Product Language: 

While building "Cheesesquare" sample in VSFM , build failure is observed with below error

"/Users/globallogic/Downloads/monodroid-samples-master/android5.0/Cheesesquare/obj/Debug/generated/Resources/layout/list_item.xml(38,38): Error CS0234: The type or namespace name 'Android' does not exist in the namespace 'Cheesesquare' (are you missing an assembly reference?) (CS0234) (Cheesesquare)"

Build JSON : [https://github.com/xamarin/release-manifests/blob/nightly-master/manifests/0_nightly_smoke_test_master.json](https://github.com/xamarin/release-manifests/blob/nightly-master/manifests/0_nightly_smoke_test_master.json)

Sample link : [https://github.com/xamarin/monodroid-samples/tree/master/android5.0/Cheesesquare](https://github.com/xamarin/monodroid-samples/tree/master/android5.0/Cheesesquare)

Steps to reproduce:
Download or clone the above sample and open it in VS for MAC
Set build config as debug and build the project
Repeat same for Release mode

Expected : App should built successfully 

Actual : Build failure is observed with error mentioned above 

Build info : [https://gist.github.com/parasAmbhore/c78a44483529b357b626830cd0e9e4d0](https://gist.github.com/parasAmbhore/c78a44483529b357b626830cd0e9e4d0)

Reproducibility : 100%

Failure is observed in Automation run as well
[http://xqa.blob.core.windows.net/gist/TestReport-4da6427447aa4bdb8d52345201da9430.txt](http://xqa.blob.core.windows.net/gist/TestReport-4da6427447aa4bdb8d52345201da9430.txt
)

Screen-recording : [http://g.recordit.co/LK1X0YUlvd.gif](http://g.recordit.co/LK1X0YUlvd.gif)

[build and Ide logs.zip](https://github.com/xamarin/xamarin-android/files/1991562/build.and.Ide.logs.zip)

Attaching IDE and Build logs too

**Comment by pjcollins** [comment]
@jonpryor @grendello we're hitting this frequently in existing projects when using the latest from master:
```
obj/Debug/generated/Resources/layout/*.xml Error CS0234: The type or namespace name 'Foo' does not exist in the namespace 'Bar' (are you missing an assembly reference?) (CS0234)
```

I'm assuming that this error is related to layout bindings? However, when I opt out via `/p: AndroidGenerateLayoutBindings=false` I encounter a new build error:
```
 CSC : error CS2001: Source file 'C:\Users\peter\source\monodroid-samples\android5.0\Cheesesquare\obj\Debug\generated\' could not be found.
```

Full build output for the opt-out failure can be found here - https://gist.githubusercontent.com/pjcollins/0ba2dde853b5263ae6bb9416707b04ac/raw/0dbc97703d31f9922947158fa414bb165a3f6b6c/gistfile1.txt.

**Comment by jonpryor** [comment]
@pjcollins, @grendello: the *immediate* cause of the build failure is code-behind. (Yay unanticipated
fallout?

@grendello: *specifically* when I build the Cheesesquare sample using xamarin-android/b32dfd1535091e3e4b7c258de3a3fbae4766d8e5, I get:

```csharp
// within obj/Debug/generated/Binding.list_item.g.cs
		// Declared in: Resources/layout/list_item.xml:(15:6)
		public TextView Text1 => FindView (global::Cheesesquare.Android.Resource.Id.Text1, ref __Text1);
```

The problem is, *there is no* `Cheesesquare.Android.Resource` type; the generated `Resource.designer.cs` file contains a `Cheesesquare.Resource` type (note "added"/inserted `Android`).

***WORKAROUND***: Disable layout generation by setting the `$(AndroidGenerateLayoutBindings)` MSBuild property to False.

**Comment by grendello** [comment]
PR https://github.com/xamarin/xamarin-android/pull/1665 has fix for the problem. Here's the relevant description:

Widgets in Android layout can have two forms of IDs: local and global. Local are of the form `@+id/text` while global look like `@android:id/text`. The binding generator erroneously output fully qualified names for the latter prefixed with the application namespace, i.e.:
    
       global::MyApplication.Android.Id.Text
