### ISSUE TITLE
CS0433 The type ValueTask<TResult> exists in both System.Threading.Tasks.Extensions and mscorlib in Xamarin.Android 8.3

### ISSUE THREAD

**Issue by yinyue200** [xamarin/xamarin-android#1676]
### Steps to Reproduce

1. Build it

**Repro project**: [https://github.com/yinyue200/taskextest](https://github.com/yinyue200/taskextest)

### Expected Behavior

Build success

### Actual Behavior

The type ValueTask<TResult> exists in both "System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"

### Version Information

Microsoft Visual Studio Enterprise 2017 
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.03056

Visual C++ 2017   00369-90000-00000-AA333
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

C# 工具   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
在 IDE 中使用的 C# 组件。根据项目类型和设置，可能会使用不同版本的编译器。

Clear MEF Component Cache   1.4
Clears the Visual Studio MEF component cache to fix issues with cache corruption.

Cookiecutter   15.7.18116.1
提供以 cookiecutter 格式查找、实例化和自定义模板的工具。

Dotfuscator Community Edition   5.34.0.6830-9173b9a63
PreEmptive Protection - Dotfuscator CE

GitHub.VisualStudio   2.5.1.2234
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP 项目系统   2.0
JavaScript UWP 项目系统

JavaScript 语言服务   2.0
JavaScript 语言服务

Markdown Editor   1.12.233
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ 向导   1.0
Microsoft Visual C++ 向导

Microsoft Visual Studio VC 软件包   1.0
Microsoft Visual Studio VC 软件包

Microsoft 用于 Visual Studio 的持续交付工具   0.3
自动化来自 Visual Studio IDE 内的持续生成集成和持续生成交付配置。

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet 包管理器   4.6.0
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 http://docs.nuget.org/。

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.7.18116.1
为 Python 开发人员提供 IntelliSense、项目、模板、调试、交互窗口和其他支持。

Python - Django 支持   15.7.18116.1
为 Django Web 框架提供模板和集成。

Python - IronPython 支持   15.7.18116.1
为基于 IronPython 的项目提供模板和集成。

Python - 分析支持   15.7.18116.1
对 Python 项目的分析支持。

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResXManager   1.19.1082.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic 工具   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
在 IDE 中使用 Visual Basic 组件。根据项目类型和设置，可能会使用不同版本的编译器。

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code 调试适配器主机包   1.0
用于在 Visual Studio 中托管 Visual Studio Code 调试适配器的互操作层

Visual Studio Tools for Universal Windows Apps   15.0.27703.01
Visual Studio Tools for Universal Windows Apps 让你能够构建一种通用的应用体验，运行 Windows 10 的每种设备都可以获得这种体验，如手机、平板电脑、PC 等。它包含 Microsoft Windows 10 软件开发工具包。

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.0.442 (396b18cef)
用于启用 Xamarin.iOS 和 Xamarin.Android 的开发的 Visual Studio 扩展。

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

多语言应用工具包   4.0
多语言应用程序工具包可以帮助您通过提供档案管理、 伪和机器翻译，翻译编辑器中，定位您的 Windows 应用商店应用程序和构建集成。http://aka.ms/matinstall

通用 Azure 工具   1.10
通过 Azure 移动服务和 Microsoft Azure Tools 提供通用服务。

用于容器的 Microsoft Visual Studio Tools   1.1
在目标环境中开发、运行、验证 ASP.NET Core 应用程序。按 F5，应用程序经调试后直接进入容器，或者按 Ctrl+F5 可编辑和刷新应用，无需重新生成容器。

### Log File

N/A

**Comment by marek-safar** [comment]
This is known issue tracked at https://github.com/dotnet/corefx/issues/29585.

**Comment by yinyue200** [comment]
@marek-safar thanks

**Comment by mohakbarokar** [comment]
This bug is tested on following build config: https://gist.github.com/mohakbarokar/56d60130dbf6b0a68ee9ea1d5ba56740
