### ISSUE TITLE
Couldn't connect to logcat, GetProcessId returned: 0 when deploying to Oreo Oneplus Device 

### ISSUE THREAD

**Issue by JungleJ0n** [xamarin/xamarin-android#1677]
### Steps to Reproduce

1. New Project, clean & rebuild, debug on phone, debug again
2. 
3. 

No need, create a fresh solution and deploy twice to a OnePlus physical device.

### Expected Behavior
App to open every time it's deployed

### Actual Behavior
Xamarin happens. 

It deploys first time fine and the second time it opens on the device with a white screen and the the app crashes, in VS  the following is displayed in VS  Output window

Android application is debugging.
Couldn't connect to logcat, GetProcessId returned: 0

This issuse was reported by Simba Mupfunya [Here](https://bugzilla.xamarin.com/show_bug.cgi?id=60236#c82) and Acknowledged by dean.ellis [Here](https://bugzilla.xamarin.com/show_bug.cgi?id=60236#c91) on  2018-03-21 , and then nothing for over a month, I don't understand how a professional company (backed by MS) allows a problem like this to just sit for a month .
 
### Version Information

Microsoft Visual Studio Professional 2017 
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA469
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40502.0
Azure Functions and Web Jobs Tools

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2018.1    Build 112.0.20180414.70444
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27625.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27703.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.5.1
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.0.442 (396b18cef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
### Log File

C:\Program Files (x86)\Android\android-sdk>adb logcat -d | pbcopy 'pbcopy'
'pbcopy' is not recognized as an internal or external command,
operable program or batch file.

but  Simba Mupfunya  post logs [Here](https://bugzilla.xamarin.com/show_bug.cgi?id=60236#c92)

**Comment by MysteryDash** [comment]
Same probleme here.

**Comment by caramelopardalis** [comment]
In my project, solved by adding x86_64 to Supported architectures of Advanced Android options.

**Comment by JungleJ0n** [comment]
> In my project, solved by adding x86_64 to Supported architectures of Advanced Android options.

I checked the Advance Android Options, and all architectures were all already ticked.

The lack of attention this issue has got despite a developer two months knowing and acknowledging it is "shocking" to say the least.

**Comment by Architekt909** [comment]
I just got this. I was previously using Visual Studio 2017 15.7.1 and not having any issues connecting to my Samsung S9 physical device. Upon upgrading, today, to 15.7.3, this issue is happening and I can no longer debug on my device. Given that some of the features I'm using (Firebase Auth) don't work in the simulator, this is pretty crippling.

**Comment by josefromtampa** [comment]
I resolved this by factory resetting my Android device.  This is using VS2017 15.7.3 for a Pixel XL + Android 8.  This might be extreme for some, but I for one don't want to change project settings nor install workaround (because you forget workarounds after they fix them).  To reset, use the Android device manager and right-click on your device, then select "Factory Reset".

**Comment by AshrithaPA** [comment]
Facing the same issue on my Oneplus 5 device. On disabling "Use Shared Runtime", I get a build error - "java.exe exited with code 1". Any work around?

**Comment by Sutphinwb** [comment]
This seems like a chronic problem - kind of petty.  I started having it after trying the new hyper-v compatible emulator.  It was slow, so I switched back to haxm which I upgraded from the Intel site (7.2).  That's what we're supposed to do, right?  stay current?  Now no debug.  Some explanation of what the heck it means would be helpful.

**Comment by rlasker3** [comment]
Luckily for me uninstalling the app from the device and then doing a clean and rebuild got me past this problem.

**Comment by jahmai** [comment]
Happened to me upgrading from 15.8.1 to 15.8.2. Cleaning out all app/xamarin installs on the device and rebuilding worked around the issue. Now it will debug the app but gets stuck during bootstrap. Why can't I just do a VS upgrade without this nonsense?

**Comment by Martinedo** [comment]
Uninstalling manualy the app from my phone helped (i kept "Use Shared Runtime" checked). This is happening everytime i upgrade my VS to newer version. In my case its not a big problem, but i can imagine by some apps in a developing process, this can be a pain in the as*.

**Comment by hannesganthaler85** [comment]
Looks like that this is device specific. On one simulator it worked to debug the app on the other not. For me it helped to uninstall the app from the simulator where the error occur and clean/rebuild it again.

**Comment by raquelsa** [comment]
Any updates on this?

**Comment by Sutphinwb** [comment]
The attached device was holding an old instance of the app.  Uninstall app
from the phone and try again.

**Comment by jpobst** [comment]
This seems like it has not been reported in several years (and several versions of VS).  I'm going to assume it has been fixed in the interim.
