### ISSUE TITLE
Increase Max Heap Size to build apps with support packages 27.x and higher

### ISSUE THREAD

**Issue by rogihee** [xamarin/xamarin-android#1681]
If you update an app to have support packages higher than 27.x, by default it will generate a "java.lang.OutOfMemoryError. Consider increasing the value of $(JavaMaximumHeapSize)".

Apparantly, apps with 27.x support packages require more memory than 26 and below and the default Java Max Heap Size settings is not sufficient. 

I could fix the error by setting "1G" to the Java Max Heap Size in Advanced settings of the Android Options. It would be better if the error would not be triggered at all.

I would suggest to either increase the internal size (setting if value is blank in project settings) or set a default value of 1G as input. 

### Steps to Reproduce
1. Start a blank new Forms app
2. Manage NuGet packages, Update all (you now have 27.x support packages)
3. Build

### Expected Behavior
Build without memory error

### Actual Behavior
java.lang.OutOfMemoryError. Consider increasing the value of $(JavaMaximumHeapSize). 

### Version Information
15.7

**Comment by JonDouglas** [comment]
This has already been included in master as of March:

https://github.com/xamarin/xamarin-android/commit/0dc96b02d9392adc136dc92469b00df7cb999a41#diff-db39bf07b89b50eaab8ab2001546310c

Thank you for the suggestion! You should see it in a future release!
