### ISSUE TITLE
[F#] Xamarin Forms NuGet fails in F# Android class library

### ISSUE THREAD

**Issue by SpiegelSoft** [xamarin/xamarin-android#1691]
### Steps to Reproduce

1. Create a new Xamarin Android class library, via File -> New Project -> Visual F# -> Android -> Class Library (Android)
2. In NuGet Package Manager, type "install package Xamarin.Forms"
3. The installation fails with the following report:

Attempting to gather dependency information for package 'Xamarin.Forms.3.0.0.482510' with respect to project 'ClassLibrary1', targeting 'MonoAndroid,Version=v8.1'
Gathering dependency information took 4.5 sec
Attempting to resolve dependencies for package 'Xamarin.Forms.3.0.0.482510' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Xamarin.Forms.3.0.0.482510'
Resolved actions to install package 'Xamarin.Forms.3.0.0.482510'
Retrieving package 'Xamarin.Android.Support.Animated.Vector.Drawable 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Annotations 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Compat 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Core.UI 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Core.Utils 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Design 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Fragment 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Media.Compat 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Transition 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.v4 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.v7.AppCompat 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.v7.CardView 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.v7.MediaRouter 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.v7.Palette 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.v7.RecyclerView 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Android.Support.Vector.Drawable 25.4.0.2' from 'nuget.org'.
Retrieving package 'Xamarin.Forms 3.0.0.482510' from 'nuget.org'.
Adding package 'Xamarin.Android.Support.Annotations.25.4.0.2' to folder 'c:\users\white\source\repos\ClassLibrary1\packages'
Added package 'Xamarin.Android.Support.Annotations.25.4.0.2' to folder 'c:\users\white\source\repos\ClassLibrary1\packages'
Added package 'Xamarin.Android.Support.Annotations.25.4.0.2' to 'packages.config'
Successfully installed 'Xamarin.Android.Support.Annotations 25.4.0.2' to ClassLibrary1
Adding package 'Xamarin.Android.Support.Compat.25.4.0.2' to folder 'c:\users\white\source\repos\ClassLibrary1\packages'
Added package 'Xamarin.Android.Support.Compat.25.4.0.2' to folder 'c:\users\white\source\repos\ClassLibrary1\packages'
Install failed. Rolling back...
Package 'Xamarin.Android.Support.Compat.25.4.0.2 : Xamarin.Android.Support.Annotations [25.4.0.2, 25.4.0.2]' does not exist in project 'ClassLibrary1'
Removed package 'Xamarin.Android.Support.Annotations.25.4.0.2' from 'packages.config'
Removing package 'Xamarin.Android.Support.Compat.25.4.0.2 : Xamarin.Android.Support.Annotations [25.4.0.2, 25.4.0.2]' from folder 'c:\users\white\source\repos\ClassLibrary1\packages'
Removed package 'Xamarin.Android.Support.Compat.25.4.0.2 : Xamarin.Android.Support.Annotations [25.4.0.2, 25.4.0.2]' from folder 'c:\users\white\source\repos\ClassLibrary1\packages'
Removing package 'Xamarin.Android.Support.Annotations.25.4.0.2' from folder 'c:\users\white\source\repos\ClassLibrary1\packages'
Removed package 'Xamarin.Android.Support.Annotations.25.4.0.2' from folder 'c:\users\white\source\repos\ClassLibrary1\packages'
Executing nuget actions took 1.88 sec
install-package : Failed to add reference to 'Xamarin.Android.Support.Compat'.
  Object reference not set to an instance of an object.
At line:1 char:1
+ install-package Xamarin.Forms
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:08.3701679

**Comment by SpiegelSoft** [comment]
This is related to #1690, but the difference is that there is no workaround consisting of removing existing NuGet packages from within the template.

**Comment by SpiegelSoft** [comment]
It is not just Xamarin.Forms I wish to install, but my own NuGet package XamarinForms.Reactive.FSharp. It seems like Xamarin.Forms would be an easier package to debug in the first instance, though.

**Comment by SpiegelSoft** [comment]
Note that the Xamarin.Forms NuGet package has a dependency on Xamarin.Android.Support.v4:

![image](https://user-images.githubusercontent.com/557824/40138411-7e754fa8-5944-11e8-8c3c-4e3b5b37e102.png)

**Comment by SpiegelSoft** [comment]
And I think this dependency on both Xamarin.Android.Support.v4 and Xamarin.Android.Support.v7.AppCompat is what is causing the problem. v7.AppCompat has a hard dependency on Xamarin.Android.Support.Compat 27.0.2:

![image](https://user-images.githubusercontent.com/557824/40138661-3b3feb16-5945-11e8-92ba-2e24fc7a2515.png)

**Comment by SpiegelSoft** [comment]
This also affects F# Android apps.

**Comment by bugQ** [comment]
+1, this is happening regardless of which version of Xamarin.Forms I try to install, or whether I attempt to install each package individually in dependency order.  The error sometimes refers to a different package, but always asks for versions of packages which have already been installed, which makes no sense.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
