### ISSUE TITLE
Referenced native library doesn't get included in .apk when library output directory uses a relative path

### ISSUE THREAD

**Issue by guygodin** [xamarin/xamarin-android#1704]
### Steps to Reproduce

1. From Android app project, add reference to an android native (C++) project in solution
2. Deploy Android app
3. Referenced .so library will not be bundled with the .apk

### Expected Behavior
https://blogs.msdn.microsoft.com/vcblog/2015/02/23/developing-xamarin-android-native-applications/

### Actual Behavior
I am not able to pinvoke my native library as I get a DllNotFoundException. If I manually copy the .so file and include it in my project, it works.

### Version Information

Microsoft Visual Studio Community 2017  (3)
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA324
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.5
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.0.40502.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.5
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.3.3000.5
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.5
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.1
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.5
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27625.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27703.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.0.442 (396b18cef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by JonDouglas** [comment]
I'm seeing the native library make the device in both a `Debug` and `Release` configuration. The VC++ tooling doesn't make it very obvious how you have to rename the target name or else you'll see only `lib.so` in the APK.

Given that I can see the .so make the APK when it's only a reference, do you perhaps have a reproduction project with respective error messaging?

I used the sample found here to do my testing: https://blogs.msdn.microsoft.com/vcblog/2015/02/23/developing-xamarin-android-native-applications/

Can you double check using a tool like [Native Libs Monitor](https://play.google.com/store/apps/details?id=com.xh.nativelibsmonitor.app) or [My APK](https://play.google.com/store/apps/details?id=com.andatsoft.myapk.fwa) to ensure there is no `libNativeLibrary.so` or equivalent making the device? 

Thanks!

**Comment by JonDouglas** [comment]
@guygodin Thank you, I will be awaiting your findings.

**Comment by guygodin** [comment]
@JonDouglas Ok, was able to identify the issue; the library doesn’t get bundled when the C++ project output directory is changed from the default value. So in the C++ project properties, change the Output Directory from:

$(SolutionDir)\$(Platform)\$(Configuration)\

To

bin\$(Platform)\$(Configuration)\

And the Native library will disappear from the .apk

**Comment by JonDouglas** [comment]
@guygodin Thank you for following up on this. Given the nature of this issue, I do believe this would be an enhancement to our existing `BuildApk` Task logic surrounding adding native libraries. Since there does exist a workaround by means of the default path / non-relative path the Mobile C++ workload provides, I am marking this as `enhancement`.

https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs

**Comment by guygodin** [comment]
An enhancement? I think this is a bug and I’m sure a lot of people will run into this. The fix is quite simple (pseudo code):

If (OutputPath is relative)
     OutputPath = $(ProjectDir) + OutputPath

**Comment by JonDouglas** [comment]
Either way we categorize this issue, I have put it on our product backlog. We will look into improving this experience when using relative paths within the Mobile C++ workload and Xamarin.Android.

Since this project is open source, we gladly accept pull requests and have documentation for [How to Contribute](https://github.com/xamarin/xamarin-android/wiki/How-to-Contribute).

Further activity on this issue will be tracked here such as a corresponding pull request or other feedback surrounding the same issue.

Thanks again for filing an issue!

**Comment by bneumann** [comment]
Hi I just found this while browsing on commute and I filed an issue yesterday (#2136) that sort of has the same problem. I will try to build my project as native linked library (instead of makefile) and see if I can contribute here.

**Comment by jonpryor** [comment]
Build and packaging log for `Scratch.Gxa1704.zip`: https://gist.github.com/jonpryor/cbe7a3771d022af744ea4f1875cf7d06

**Comment by jonathanpeppers** [comment]
I have never looked at these Cpp targets before...

But I think I see what is happening here:
```
Task "MergeApkRecipelists" skipped, due to false condition; ('@(_NativeAndroidRecipeFiles)' != '' And Exists('%(_NativeAndroidRecipeFiles.Identity)')) was evaluated as ('bin\x86\Debug\libNativeLibrary.so.recipe' != '' And Exists('bin\x86\Debug\libNativeLibrary.so.recipe')).
```
This is the task responsible for looking in this "recipe" file and finding the so file to be added to `@(AndroidNativeLibrary)`: https://github.com/xamarin/xamarin-android/blob/ada853bf203aea456129d4015fb132e635f8c8b8/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Microsoft.Cpp.Android.targets#L55-L60

However, the way it currently works:
- From the C# project we invoke the `GetApkRecipeFile` target of the C++ project
- The C++ project *might* return a relative path
- The C# project won't be able to use a relative path if it's in a different directory!

I'm not exactly sure what we should do to fix this? I'm not sure we can prefix `$(ProjectDir)` from the `<Outputs/>` of this MSBuild call: https://github.com/xamarin/xamarin-android/blob/ada853bf203aea456129d4015fb132e635f8c8b8/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Microsoft.Cpp.Android.targets#L47-L53

Here is the content of the target from the C++ project:
```xml
  <Target Name="GetApkRecipeFile" Returns="$(ApkRecipeFile)">
    <PropertyGroup>
      <ApkRecipeFile>$(_ApkRecipeFile)</ApkRecipeFile>
    </PropertyGroup>
  </Target>
```
Here is the binlog: [error.zip](https://github.com/xamarin/xamarin-android/files/2521137/error.zip)

Perhaps we just need to emit errors and warnings here?
- If `@(_NativeAndroidRecipeFiles)` is empty, perhaps that should be a warning?
- If a recipe file doesn't exist, perhaps that should be an error that notes the path, and recommends to use absolute file paths?
