### ISSUE TITLE
No resource found that matches given name

### ISSUE THREAD

**Issue by Virendra3112** [xamarin/xamarin-android#1730]
### Steps to Reproduce

1. Download braintree dropin .aar file from https://mvnrepository.com/artifact/com.braintreepayments.api/drop-in/3.3.0 
2. Now create a Xamarin android Class Library project and add .aar file into Jar folder and set build action as LibraryProjectZip
3. Compile the project then you will get build success with following warnings,
Error: No resource found that matches the given name: attr 'textColorError'.

### Expected Behavior
It needs to compile .aar or .jar file successfully.
### Actual Behavior
Getting above error.
### Version Information
Download braintree dropin .aar file from https://mvnrepository.com/artifact/com.braintreepayments.api/drop-in/3.3.0 

Please help me on this.

**Comment by atsushieno** [comment]
LibraryProjectZip is valid only in Java **Binding** project, not in Android Class Library project.

**Comment by jonathanpeppers** [comment]
@Virendra3112 I believe atsushi's suggestion is the way to go, put these files in a Java binding project.

Closing this for now, feel free to reopen if you can send more info, thanks!
