### ISSUE TITLE
The build script is buggy and fails to build android-P Mono.Android.dll to the right place.

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1737]
Have this content as top-level `Configuration.Override.props`:

```
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <AndroidApiLevel>28</AndroidApiLevel>
    <AndroidPlatformId>P</AndroidPlatformId>
  </PropertyGroup>
</Project>
```

Run `make prepare all`.

It does not generate `bin/Debug/lib/xamarin.android/xbuild-framework/MonoAndroid/v8.1.99/` and its contents.

Meanwhile, src/Mono.Android/obj/Debug/android-28/Mono.Android.dll IS created.

There must be a buggy build script in somewhere in the MSBuild script spaghetti.

**Comment by jonpryor** [comment]
You're not overriding `$(AndroidFrameworkVersion)`.


[`$(AndroidFrameworkVersion)` defaults to `$(AndroidLatestStableFrameworkVersion)`](https://github.com/xamarin/xamarin-android/blob/041d26975357d55c7db406c243ed0b9b27f60a3a/Configuration.props#L30), which you didn't override, and thus `$(AndroidFrameworkVersion)` will default to `v8.1`.


Thus, I imagine that `bin/Debug/lib/xamarin.android/xbuild-framework/MonoAndroid/v8.1/Mono.Android.dll` is being generated, with the contents of your API-P binding.


Given that we have three different yet closely related properties that need to be kept synchronized, if one if them *isn't* synchronized then Weird Things will happen, as you see.


The only way I can imagine fixing this is by removing the three separate properties, and instead have one property which controls those three properties. We don't have such a thing yet.
