### ISSUE TITLE
TestSuiteActivity.cs blocks UI thread when running tests

### ISSUE THREAD

**Issue by MatthewGerber** [xamarin/xamarin-android#1740]
I am using [TestSuiteActivity](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.NUnitLite/Gui/Activities/TestSuiteActivity.cs) within nunitlite for unit testing. One of my unit tests runs on the UI thread, and I think this test is being blocked because the button click handler for starting the tests runs on the UI thread (see [here](https://github.com/xamarin/xamarin-android/blob/462add4c95e19a56c2672d654ed840065277420e/src/Xamarin.Android.NUnitLite/Gui/Activities/TestSuiteActivity.cs#L60)). When I set `automated` to `true` everything works fine (no blocking), as this approach runs the tests on a new thread (see [here](https://github.com/xamarin/xamarin-android/blob/462add4c95e19a56c2672d654ed840065277420e/src/Xamarin.Android.NUnitLite/Gui/Activities/TestSuiteActivity.cs#L88)). Seems like the solution to my problem would be to run the tests on a new thread when clicking the button, as done with automated testing. Agreed?

**Comment by jonathanpeppers** [comment]
@grendello what do you think about this?

Should we look into showing a `ProgressDialog` or something and "always" running the tests in the background?

**Comment by MatthewGerber** [comment]
I believe this is also an issue on the iOS side.

**Comment by jonpryor** [comment]
The related question is, now much priority should `Xamarin.Android.NUnitLite` get when there are existing alternatives such as xUnit which almost certainly get more community attention.

How many people *actually* use `Xamarin.Android.NUnitLite`? How much love should it get? Should we just migrate *away* from it?

**Comment by MatthewGerber** [comment]
Any resolution to this in the foreseeable future?
