### ISSUE TITLE
"Fast Deployment" could prevent code changes when external disk is nearly full

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#1746]
I've been trying to figure out what issue developers are hitting when they disable the `Fast Deployment` feature available in commercial Xamarin.Android.

Here is one possible issue I thought I would outline related to hitting a "disk full" state on an emulator or device. I noticed a customer's application had a ~400MB APK, which lead me to research what could be going on here. The bulk of the file size was in `EmbeddedResource` build items, which would indeed imply a large .NET assembly (300MB!) would be sent through `Fast Deployment`.

### Steps to Reproduce (Theoretical)

1. Deploy an application with large assemblies, `Fast Deployment` will install `.__override__` assemblies to the external disk (SD card)
1. External disk is now full (or nearly full)
1. Make a C# code change
1. Deploy again with `Fast Deployment`, the Xamarin.Android build hits a "disk full" error
1. `Fast Deployment` falls back to an internal disk for the `.__override__` assemblies, this logic is found in commercial Xamarin.Android
1. Apps are uninstalled, something happens where external disk gets enough free space again
1. Make a C# code change
1. Deploy again, `Fast Deployment` successfully deploys to the external disk (SD card)
1. Code changes are no longer picked up, since the outdated assemblies from the internal disk would be loaded...

Xamarin.Android loads `Fast Deployment` assemblies from directories in the following order:
- Internal `.__override__`
- External `.__override__`
- A "legacy" external directory -- which perhaps should be dropped?

Here are the lines in `monodroid-glue.c` that imply the ordering, index 0 should be the internal directory: https://github.com/xamarin/xamarin-android/blob/c87c61763fd041d56d2f43df3eb09938e254ad3b/src/monodroid/jni/monodroid-glue.c#L3751-L3752

Perhaps we need to improve this behavior/logic, in general?

### Expected Behavior

`Fast Deployment` _just works_ and no one ever turns it off. Code changes are picked up no matter what, because it _just works_.

### Actual Behavior

Due to behavior caused by the steps above, code changes will not be picked up.

### Impact

Although this case seems narrow, developers are turning off `Fast Deployment`. There is perhaps another issue I'll uncover if I can get more information about what is really going on.

**Comment by dellis1972** [comment]
@jonathanpeppers My guess is we need to delete the `upload.flag` file in this instance somehow. That would ensure the next build would force an upload.

**Comment by jonathanpeppers** [comment]
@dellis1972 I suspect there might be a problem here related to out of disk space, but seems rare. Since  this is from May, I think we've addressed a lot of the fast deployment issues.

Maybe a better approach would be to see if we can get some kind of telemetry when debugging that could give us an idea of how many times the assembly isn't matching the source code when debugging.

I'll check with IDE team about this.

**Comment by jonathanpeppers** [comment]
Since https://github.com/xamarin/monodroid/pull/1090 completely reworks fast deployment, we can close this.

The external directory is no longer used at all.
