### ISSUE TITLE
Can't build Binding Library project with embedded native lib

### ISSUE THREAD

**Issue by HBenl-BK** [xamarin/xamarin-android#1752]
### Steps to Reproduce

1. download the Brother Printer SDK for Android from http://www.brother.com/product/dev/mobile/android/download/bppsdka309/index.htm
2. create a Binding Library project in Visual Studio (tested with 15.6.4 and 15.7.2)
3. add BrotherPrintLibrary.jar and libcreatedata.so from the Brother SDK to the Jars folder
4. set the Build Actions to EmbeddedJar and EmbeddedNativeLibrary, respectively
5. try to build the project

### Expected Behavior
the project builds

### Actual Behavior
I get the following error:
```
System.IO.FileNotFoundException: Die Datei "C:\GitTF\Aktuell\Apps\ThirdParty\BrotherSDK\obj\Debug_AndroidNativeLibraries.zip.new" konnte nicht gefunden werden.
Dateiname: "C:\GitTF\Aktuell\Apps\ThirdParty\BrotherSDK\obj\Debug_AndroidNativeLibraries.zip.new"
bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
bei System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
bei Xamarin.Android.Tools.Files.CopyIfZipChanged(String source, String destination)
bei Xamarin.Android.Tools.Files.ArchiveZip(String target, Action`1 archiver)
bei Xamarin.Android.Tasks.CreateNativeLibraryArchive.Execute()
bei Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
bei Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() BrotherSDK C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets 582
```
### Version Information

Microsoft Visual Studio Professional 2017 
Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
Version 4.7.02556

Installierte Version: Professional

Allgemeine Azure-Tools   1.10
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

Application Insights-Tools für Visual Studio-Paket   8.12.10405.1
Application Insights-Tools für Visual Studio

ASP.NET and Web Tools 2017   15.0.40511.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

C#-Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
C#-Komponenten, die in der IDE verwendet werden. Je nach Projekttyp und Einstellungen kann eine andere Compilerversion verwendet werden.

JavaScript-Sprachdienst   2.0
JavaScript-Sprachdienst

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP-Projektsystem   2.0
JavaScript UWP-Projektsystem

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure-Tools   2.9
Microsoft Azure-Tools für Microsoft Visual Studio 2017 – v2.9.10420.2

Microsoft Continuous Delivery-Tools für Visual Studio   0.3
Die Konfiguration der fortlaufenden Buildintegration und der fortlaufenden Buildbereitstellung innerhalb der Visual Studio-IDE wird vereinfacht.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio-Tools für Container   1.1
Jetzt können Sie Ihre ASP.NET Core-Anwendung in der Zielumgebung entwickeln, ausführen und überprüfen. Drücken Sie F5, um die Anwendung direkt in einem Container mit Debugfunktionen auszuführen, oder STRG+F5 zum Bearbeiten und Aktualisieren Ihrer Anwendung, ohne den Container erneut erstellen zu müssen.

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet-Paket-Manager   4.6.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter "http://docs.nuget.org/".

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript-Tools   15.7.20419.2003
TypeScript-Tools für Microsoft Visual Studio

Typewriter   1.18.0
Typewriter generates TypeScript files from c# code files using TypeScript Templates. This allows you to create fully typed TypeScript representations of server side API that automatically updates when you make changes to your c# code.

VC-Paket für Microsoft Visual Studio   1.0
VC-Paket für Microsoft Visual Studio

Visual Basic-Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
Visual Basic-Komponenten, die in der IDE verwendet werden. Je nach Projekttyp und Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools 10.1 für F# 4.1   15.7.0.0.  Commit Hash: 56f97a8dd4353d897336941f3e644423b87c794f.
Microsoft Visual F# Tools 10.1 für F# 4.1

Visual Studio Code-Debugadapter-Hostpaket   1.0
Interopebene zum Hosten der Visual Studio Code-Adapter in Visual Studio

Visual Studio Tools für universelle Windows-Apps   15.0.27703.2018
Mit den Visual Studio Tools für universelle Windows-Apps können Sie eine universelle App-Erfahrung erstellen, die auf jedem Gerät genutzt werden kann, das Windows 10 ausführt: Smartphone, Tablet, PC und viele weitere Geräte. Das Microsoft Windows 10 SDK ist in den Tools enthalten.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.0.448 (4373404db)
Visual Studio-Erweiterung, um Entwicklung für Xamarin.iOS und Xamarin.Android zu ermöglichen.

Xamarin Designer   4.12.270 (82d750d12)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.178 (408d357)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by JonDouglas** [comment]
@HBenl-BK Although I can reproduce this behavior, the problem I believe is that you are not providing the proper folder structure needed.

To fix this, you would need to add a `libs\armeabi` folder which you would then put the `libcreatedata.so` file as `EmbeddedNativeLibrary` and it should compile just fine.

Since this does not provide a great resolution in the error message, I am adding this to our backlog and closing this issue. Please comment if you are unable to get this to work with the instructions above.

**Comment by HBenl-BK** [comment]
Thanks, that resolved the build-time errors.
To be able to call the library, I had to rename the folder to `lib\armeabi-v7a`, though. Otherwise it wouldn't load, not even with `Java.Lang.JavaSystem.LoadLibrary("createdata");`.
Please mention the required folder structure in the documentation for Binding Library projects. This may be obvious for someone who is used to handling native libraries on Android, but not every Xamarin developer is.
