### ISSUE TITLE
Xamarin AAR library COMPILETODALVIK error on build

### ISSUE THREAD

**Issue by Raj123456788** [xamarin/xamarin-android#1755]
### Steps to Reproduce

1. Using Latest Visual studio@ JDK 1.8 installed.Below is the error The Bindings project does build. but android project does not.

```
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
2>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
2> java.lang.RuntimeException: Translation has been interrupted
2> at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
2> at com.android.dx.command.dexer.Main.runMonoDex(Main.java:313)
2> at com.android.dx.command.dexer.Main.runDx(Main.java:291)
2> at com.android.dx.command.dexer.Main.main(Main.java:247)
2> at com.android.dx.command.Main.main(Main.java:94)
2> Caused by: java.lang.InterruptedException: Too many errors
2> at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
2> ... 4 more
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2188,3): error : java.lang.RuntimeException : Translation has been interrupted
```

### Expected Behavior
Should Build

### Actual Behavior
above error
### Version Information
Xamarin 4.10.0.448

**Comment by duchnoun** [comment]
Same like that : https://github.com/xamarin/xamarin-android/issues/1738 , it's because you use java 8 feature (lambda or others) and the project is not desugared to java 7 .

**Comment by jonpryor** [comment]
The relevant source code is: https://github.com/xamarin/xamarin-android/blob/041d26975357d55c7db406c243ed0b9b27f60a3a/src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs#L55-L71

The `--min-sdk-version` value comes from one of two things:

1. `MonoAndroidHelper.SupportedVersions.MinStableVersion.ApiLevel`, which is the minimum supported API level that *Xamarin.Android* supports, which at this time is API-10, which is below 26, or
2. `manifest.MinSdkVersion.Value`, which is the [`//uses-sdk/@android:minSdkVersion` value ](https://developer.android.com/guide/topics/manifest/uses-sdk-element#min) within your `AndroidManifest.xml` file, *if specified*.

If your `AndroidManifest.xml` file doesn't specify `//uses-sdk/@android:minSdkVersion`, then we'll use `--min-sdk-version 10`, which will error out (as you see).

Are you setting `//uses-sdk/@android:minSdkVersion` within your `AndroidManifest.xml` file? If not, please try setting it to a value >= 26.

If you *are* already setting that value, please provide the diagnostic build output of your project.

**Comment by bruno-garcia** [comment]
I'm also affected by this issue.

Example:

```
  Xamarin.Android.Common.targets(2732, 3): /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2732,3): error : java/lang/Object;)Lio/sentry/core/SentryEvent;: invoking a static interface method io.sentry.core.ILogger.logIfNotNull : (Lio/sentry/core/ILogger;Lio/sentry/core/SentryLevel;Ljava/lang/String;[Ljava/lang/Object;)V strictly requires --min-sdk-version >= 24 (blocked at current API level 13)
```

Relevant to this problem I found [this SO answer suggesting to enable D8](https://stackoverflow.com/questions/48532610/is-java-8-features-available-for-xamarin-android-in-java-binding-project) via `<AndroidDexTool>d8</AndroidDexTool> `. 

That didn't help me, unfortunately.

[Also from SO from a couple of year ago](https://stackoverflow.com/questions/47794790/xamarin-aar-library-use-sourcecompatibility-javaversion-version-1-8?noredirect=1&lq=1), with a [comment](https://stackoverflow.com/questions/47794790/xamarin-aar-library-use-sourcecompatibility-javaversion-version-1-8?noredirect=1&lq=1#comment82557270_47794790) from @JonDouglas saying all we need is to have the JDK 1.8 installed which I do, also java/javac are in the `$PATH`.

This could be fixed with gradle by defining the compat:

```groovy
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
```

Is there anything else I can try to work around this? I'd love to offer a library for Xamarin devs which I'm hoping to dogfood on an app.

**Comment by bruno-garcia** [comment]
Actually this setting worked just fine:

```xml
  <PropertyGroup>
    <AndroidDexTool>d8</AndroidDexTool>
  </PropertyGroup>
```

Before I had added it to the Java binding library instead of the app.

**Comment by NikhilWaghaye** [comment]
@bruno-garcia where to add this settings...
Thanks

**Comment by jpobst** [comment]
`d8` is now the default, so I think this should be considered fixed.
