### ISSUE TITLE
xamarin-android uses out-of-sync API generator from java.interop

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1759]
There is a big problem in xamarin-android API (Mono.Android) now. https://github.com/xamarin/xamarin-android/pull/1728 should have never been merged without merging https://github.com/xamarin/java.interop/pull/325 .

Next time API generation will be simply impossible.

**Comment by jonpryor** [comment]
https://github.com/xamarin/java.interop/pull/325 has been merged
