### ISSUE TITLE
Throw a warning when targetSdkVersion is < 26 for new Google Play requirements starting August 2018

### ISSUE THREAD

**Issue by JonDouglas** [xamarin/xamarin-android#1766]
> Google Play will require that new apps target at least Android 8.0 (API level 26) from August 2018, and that app updates target Android 8.0 from November 2018.

Thus we should add a warning message to handle the following situations:

**August 1, 2018 - New apps must target at least Android 8.0 (API level 26)**
**November 1, 2018 - App updates must target at least Android 8.0 (API level 26)**

![](https://pbs.twimg.com/media/DeejOhUUQAAvuPZ.jpg)

**Documentation**

- https://support.google.com/googleplay/android-developer/answer/113469#targetsdk
- https://developer.android.com/distribute/best-practices/develop/target-sdk

> VS bug [#635168](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635168)

**Comment by atsushieno** [comment]
I'm not sure throwing an error is appropriate, considering that we used to support Kindle SDK before.

**Comment by dellis1972** [comment]
@atsushieno makes a good point about other non google stores. That said that should be covered by the `minSdkVersion` shouldn't it?

**Comment by dellis1972** [comment]
That said we can add a Warning now to report that api 26 is the minimum.

**Comment by dellis1972** [comment]
Interestingly it seems google implemented this in a `lint` check. We already have `lint` support so we should get that for free. But only if the end users enable the lint checks (via `$(AndroidLintEnabled)` which we default to `false`), which I guess is the same as android studio?

If android studio enables lint by default , perhaps we should too?

**Comment by dellis1972** [comment]
in the mean time I'll add something to `ResolveSdks` which will provide a nice warning and some docs.

**Comment by AdamDavidHill** [comment]
Is there a way to suppress or disable these warnings? Not everyone writes apps for the Play Store. For example, I'm targeting some under-powered hardware that only runs an older version, and the APK would be imaged onto it.

**Comment by dellis1972** [comment]
@AdamDavidHill from the commit message


```
If you are not targeting the Google Play store and wish to hide these
warnings you can make use of the /nowarn:XA0114,XA0113 command line switch.
Alternatively add

<NoWarn>XA0114;XA0113</NoWarn>
to your .csproj.


```
