### ISSUE TITLE
[Aapt2] Certain warnings now surfaced by aapt2 are being treated as errors

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1770]
### Steps to Reproduce

1. `msbuild /t:SignAndroidPackage /p:AndroidUseAapt2=true monodroid-samples\Button\DroidButton.csproj /v:diag`

https://github.com/xamarin/monodroid-samples/tree/master/Button 

I can reproduce this with the default TargetFrameworkVersion of the project (v2.3), as well as v4.0.4, and v4.4. However, if I target v5.0 or greater then my build succeeds.

### Expected Behavior
Project builds successfully with Aapt2 enabled.

### Actual Behavior
```
Executing link --manifest C:\Users\peter\AppData\Local\Temp\wtsbowgt.p03\manifest\AndroidManifest.xml --java C:\Users\peter\AppData\Local\Temp\wtsbowgt.p03 --custom-package mono.samples.button -R obj\\Debug\\compiled.flata --auto-add-overlay -I "C:\Program Files (x86)\Android\android-sdk\platforms\android-10\android.jar" --output-text-symbols obj\\Debug\R.txt -o C:\Users\peter\AppData\Local\Temp\wtsbowgt.p03\resources.apk (TaskId:97)
W/ResourceType(23681): error APT0000: For resource 0x0101053d, entry index(1341) is beyond type entryCount(733) [C:\Users\peter\source\monodroid-samples\Button\DroidButton.csproj]
W/ResourceType(23681): error APT0000: For resource 0x0101053e, entry index(1342) is beyond type entryCount(733) [C:\Users\peter\source\monodroid-samples\Button\DroidButton.csproj]
W/ResourceType(23681): error APT0000: For resource 0x0101053b, entry index(1339) is beyond type entryCount(733) [C:\Users\peter\source\monodroid-samples\Button\DroidButton.csproj]
W/ResourceType(23681): error APT0000: For resource 0x0101053c, entry index(1340) is beyond type entryCount(733) [C:\Users\peter\source\monodroid-samples\Button\DroidButton.csproj]
Done executing task "Aapt2Link" -- FAILED. (TaskId:97)
```
### Version Information
https://gist.github.com/pjcollins/220d551af40c4ccc18db3e7df0c1b72f

### Log File
https://gist.github.com/pjcollins/57dec1bd340d9212129c1d8a0a779433

> VS bug [#624789](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/624789)

**Comment by atsushieno** [comment]
Should we still support targetSdkVersion < 26 while Google Play will start rejecting such apks?

**Comment by pjcollins** [comment]
@dellis1972 when building a similar project in Android Studio this particular message is also generated and displayed. However, in their case, it's is seemingly only perceived as a warning and is non fatal:

```
:app:processDebugResources (Thread[Daemon worker Thread 7,5,main]) started.
:app:processDebugResources
Task ':app:processDebugResources' is not up-to-date because:
  Value of input property 'buildTargetDensity' has changed for task ':app:processDebugResources'
All input files are considered out-of-date for incremental task ':app:processDebugResources'.
Unable do incremental execution: full task run
W/ResourceType( 2584): For resource 0x0101053d, entry index(1341) is beyond type entryCount(1112)
W/ResourceType( 2584): For resource 0x0101053e, entry index(1342) is beyond type entryCount(1112)
W/ResourceType( 2584): For resource 0x0101053b, entry index(1339) is beyond type entryCount(1112)
W/ResourceType( 2584): For resource 0x0101053c, entry index(1340) is beyond type entryCount(1112)

Aapt output file C:\Users\peter\AndroidStudioProjects\NoLibsTest\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_
:app:processDebugResources (Thread[Daemon worker Thread 7,5,main]) completed. Took 0.164 secs.
```

**Comment by dellis1972** [comment]
@pjcollins hmm interesting. time to search in the aapt2 sources I guess.

**Comment by dellis1972** [comment]
I can't find that message in any of the `aapt` or `aapt2` sources. :(

**Comment by dellis1972** [comment]
It does seem to be a warning though, so I guess we need to filter the error output for warnings which I was hoping we would not have to do :'(

**Comment by pjcollins** [comment]
@dellis1972 this does appear to be fixed in many instances, however I am still seeing a few dozen projects reporting this warning as an error in 15.8 (XA version: 9.0.0.17 (HEAD/dfb09269d));
* http://xqa.blob.core.windows.net/gist/log-39890a024129460192c5fd740b2e4891.txt
* http://xqa.blob.core.windows.net/gist/log-37518edadb2e413aa4ffae3aa85f1991.txt
---
* https://github.com/xamarin/monodroid-samples/tree/master/KitKat
* https://github.com/xamarin/monodroid-samples/tree/master/JetBoy
* https://github.com/xamarin/monodroid-samples/tree/master/LabelledSections
* https://github.com/xamarin/monodroid-samples/tree/master/PlatformFeatures/ICS_Samples/ContactsProviderDemo
* https://github.com/xamarin/monodroid-samples/tree/master/RotationDemo
* https://github.com/xamarin/monodroid-samples/tree/master/TexturedCubeES30-1.0
* https://github.com/xamarin/monodroid-samples/tree/master/WeatherREST
* https://github.com/xamarin/monodroid-samples/tree/master/ModelAndVerts
* https://github.com/xamarin/monodroid-samples/tree/master/ModelDrawing
* https://github.com/xamarin/monodroid-samples/tree/master/StorageProvider
* https://github.com/xamarin/monodroid-samples/tree/master/UrbanAirship/samples/PushSample
* https://github.com/xamarin/monodroid-samples/tree/master/WalkingGameEmptyAndroid
* https://github.com/xamarin/monodroid-samples/tree/master/WalkingGameCompleteAndroid
* https://github.com/xamarin/monodroid-samples/tree/master/android5.0/ElevationBasic

* https://github.com/xamarin/mobile-samples/tree/master/BackgroundLocationDemo/location.Android
* https://github.com/xamarin/mobile-samples/tree/master/BluetoothLEExplorer
* https://github.com/xamarin/mobile-samples/tree/master/ContentControls
* https://github.com/xamarin/mobile-samples/tree/master/GLKeysES30
* https://github.com/xamarin/mobile-samples/tree/master/Notifications
* https://github.com/xamarin/mobile-samples/tree/master/StandardControls
* https://github.com/xamarin/mobile-samples/tree/master/Touch
* https://github.com/xamarin/mobile-samples/tree/master/DataAccess
* https://github.com/xamarin/mobile-samples/tree/master/WebServices/HelloWorld
* https://github.com/xamarin/mobile-samples/tree/master/TexturedCubeES30
* https://github.com/xamarin/mobile-samples/tree/master/RazorTodo
* https://github.com/xamarin/mobile-samples/tree/master/BouncingGame
* https://github.com/xamarin/mobile-samples/tree/master/TipCalc/TipCalc.UI.Android

**Comment by dellis1972** [comment]
@pjcollins this works on master, so I can only assume that monodroid does not have the fix in it.... I think its too late to put this in now, so I guess this will have to wait for 15.9.

**Comment by pjcollins** [comment]
@dellis1972 I'll try to retest master today. Could you point out the commit that 15.8 is missing? I thought everything was already applied to that branch.

I believe this issue was fixed for _some_ cases, but somehow some warnings are still surfacing as errors even with the relevant fix in place.

**Comment by dellis1972** [comment]
@pjcollins the commit was [1] its in d15-8 .. so that latest should have the fix.. very weird. 
I could not repo on master. I will update the alpha on my Mac and try again. 

[1] https://github.com/xamarin/xamarin-android/commit/a05492d9738e1a4c09ef3daf0c7481990eda4e27.

**Comment by pjcollins** [comment]
@dellis1972 I'm still able to reproduce this on Windows at least using [XA master](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1111/Azure/processDownloadRequest/xamarin-android/bin/BuildRelease/Xamarin.Android.Sdk-OSS-8.4.99.91_HEAD_2de97c1.vsix) and the projects mentioned above (specifically the [KitKat project](https://github.com/xamarin/monodroid-samples/tree/master/KitKat) in this latest test).  Interestingly enough however, I can no longer reproduce using `monodroid-samples\Button\DroidButton.csproj` as originally reported... these warnings are indeed reported as warnings with this project, [as shown here](https://gist.github.com/pjcollins/079d3075c1bbeae66535e14892e79ec9).

**Comment by dellis1972** [comment]
I repo'd on windows.. doesn't repo on Mac :(

**Comment by dellis1972** [comment]
PR is up https://github.com/xamarin/xamarin-android/pull/2027

**Comment by xamarin-release-manager** [comment]
[VS sync] Milestone is required in VSTS
