### ISSUE TITLE
[Aapt2] Can't operate across drives on Windows

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#1771]
### Steps to Reproduce

See VSTS build here: http://build.devdiv.io/1735992

1. Create a project into `E:\` or some secondary drive with Aapt2 enabled
2. Your system has `%TEMP%` in `C:\`
3. `aapt2.exe` fails an error such as:

```
error APT0000: failed to create directory 'C:\Users\myuser\AppData\Local\Temp\3\hyxjnzdb.0d1\xamarin\forms_performance_integration'.
```

Apparently, because we are running `aapt2.exe` against files on different drives:
```
Executing package -f -m -M C:\Users\myuser\AppData\Local\Temp\3\mbhhnawt.shy\manifest\AndroidManifest.xml -J C:\Users\myuser\AppData\Local\Temp\3\mbhhnawt.shy --custom-package mono.android_tests -F C:\Users\myuser\AppData\Local\Temp\3\mbhhnawt.shy\resources.apk.bk -S E:\A\_work\1\s\src\Mono.Android\Test\obj\\Debug\res -S E:\A\_work\1\s\src\Mono.Android\Test\obj\Debug\lp\1\jl\res -S E:\A\_work\1\s\src\Mono.Android\Test\obj\Debug\lp\2\jl\res -S E:\A\_work\1\s\src\Mono.Android\Test\obj\Debug\lp\3\jl\res -I C:\Users\myuser\android-toolchain\sdk\platforms\android-27\android.jar --auto-add-overlay --output-text-symbols obj\\Debug\ --max-res-version 27
```

Other links about this:
- https://stackoverflow.com/questions/46512990/gradle-error-failed-to-create-directory
- https://issuetracker.google.com/issues/68936311
- https://github.com/xamarin/xamarin-android/pull/1757

### Expected Behavior

`Aapt2` works even if you have the project on a second drive.

### Actual Behavior

`Aapt` fails.

### Version Information

I was using `xamarin-android/master/1cbac614061df022d93fcff2384afdbba813e37e`.

Don't know what we should even do about this, but I thought I would file it...

**Comment by jonpryor** [comment]
Please try to create an equivalent cross-drive scenario in Android Studio, and see if it likewise fails there.

If it does, please file a bug upstream at: https://issuetracker.google.com/

**Comment by jonathanpeppers** [comment]
I worked around the issue by changing the temp drive on VSTS.

I couldn't repro with a USB drive on my machine... I guess we keep this open a little while?

**Comment by kvpt** [comment]
Hi,
I hit this issue when trying to use aapt2 on AzureDevOps.
Any progress on this one ?

**Comment by dellis1972** [comment]
@kvpt this error is in the actual `aapt2` exe which google produces. (see https://issuetracker.google.com/issues/68936311) not sure if there is much we can do to fix it in our side. 

@jonathanpeppers any thoughts? is it worth documenting how to change the temp drive in VSTS so people can work around?

**Comment by jonathanpeppers** [comment]
I checked and this isn't happening for us anymore, probably due to one of two reasons:
* We are using a [newer aapt2 from maven](https://github.com/xamarin/xamarin-android/commit/4ccbeb74c9d9ed91e926788d4b68ca80134aadc4), we now ship this with Xamarin.Android.
* We reworked our Azure Pipelines build, which is [YAML](https://github.com/xamarin/xamarin-android/blob/master/build-tools/automation/azure-pipelines.yaml) now. I had a workaround to change `%TEMP%` which is not in there anymore

Somehow things are working for us now on the same build pool?

@kvpt I am going to close this, since it's not happening for us. Can you collect some [MSBuild binlogs](https://github.com/Microsoft/msbuild/wiki/Binary-Log) during your build and open a new issue?
