### ISSUE TITLE
MSBuildWorkspace load failures (Microsoft.CodeAnalysis.*) for Xamarin.Android projects.

### ISSUE THREAD

**Issue by plynkus** [xamarin/xamarin-android#1775]
### Steps to Reproduce

1. Create a simple console app.  Add nuget packages: Microsoft.CodeAnalysis, Microsoft.Build.Locator.
2. Add boilerplate code to load a project in a workspace, e.g.:

```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.MSBuild;

using System.Threading.Tasks;

namespace AndroidRoslynFailure
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var workspace = MSBuildWorkspace.Create();
            workspace.WorkspaceFailed += WorkspaceFailed;
            var project = await workspace.OpenProjectAsync(@"C:\path\to\android.csproj");

            return;
        }

        private static void WorkspaceFailed(object sender, WorkspaceDiagnosticEventArgs e)
        {
            return;
        }
    }
}
```

3. Set breakpoints at both returns above (to catch the success/failure cases).

### Expected Behavior

Success.  (Works for other project types---iOS, UWP, etc.)

### Actual Behavior

Failure.  The WorkspaceFailed handler is called with diagnostic information of the form:

```
{[Failure] Msbuild failed when processing the file 'C:\Temp\AndroidRoslynFailure\App\App.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets: (52, 5): The "Csc" task failed unexpectedly.
System.InvalidOperationException: MSB3087: An incompatible host object was passed into the "Csc" task.  The host object for this task must implement the "ICscHostObject" interface.
   at Microsoft.CodeAnalysis.BuildTasks.Csc.AddResponseFileCommands(CommandLineBuilderExtension commandLine)
   at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.GenerateResponseFileCommands()
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()}
```

This issue began fairly recently (at least in the Visual studio 15.7.2+ timeframe).  We perform custom build tasks that do some of their work through code analysis and these steps now fail for Xamarin.Android projects only.

If you believe this is not due to some difference in the Xamarin.Android toolchain itself, I can kick this over to the Roslyn issues list as well.  I'll be taking a look at the repositories to try and understand from where ICscHostObject implementers are provided per platform.

### Version Information

Currently stock Visual Studio 15.7.3, tip nuget packages for those cited above.

**Comment by atsushieno** [comment]
> If you believe this is not due to some difference in the Xamarin.Android toolchain itself, I can kick this over to the Roslyn issues list as well.

It certainly isn't Xamarin.Android issue. Please do so. Our build is not special - it perfectly conforms to what MSBuild expects.

Thanks for reporting this though!

**Comment by plynkus** [comment]
Will do.  Thanks.
