### ISSUE TITLE
Erro	XLS0503	Não é possível adicionar um valor de tipo 'Grid' a uma coleção ou a um dicionário de tipo 'IList'

### ISSUE THREAD

**Issue by costaeverton** [xamarin/xamarin-android#1782]
### Steps to Reproduce

1. Depois de atualizar o pacote do Nuget Xamarin.Forms para a versão 3.0.0.530893 no Visual Studio 2017 v. 15.7.3 
2. No editor de XMAL apresenta o erro Erro	XLS0503	Não é possível adicionar um valor de tipo 'Grid' a uma coleção ou a um dicionário de tipo 'IList'
3. Quando compila o erro é ignorado.

**Comment by rmarinho** [comment]
Oi @costaeverton por favor abra um ticket em inglês e no repositório certo @xamarin/xamarin-forms  , também o melhor é associar uma pequena reprodução do problema para conseguimos identificar o problema. 

Obrigado.
