### ISSUE TITLE
Deployment Error - Android manifest attributes not declared

### ISSUE THREAD

**Issue by humbertoadan** [xamarin/xamarin-android#1783]
When I try to deploy a Xamarin.Android project to an emulator it fails and it shows a deployment failed message. It shows on the error lists 3 warnings about attributes not declared in the AndroidManifest.xml. The 3 warnings are the following.

![capture](https://user-images.githubusercontent.com/6433487/41053456-8d4f5320-6989-11e8-966c-830acf5c2391.JPG)

### Steps to Reproduce

1.  Create a Xamarin.Android project on Visual Studio 2017 15.7.3
2.  Add the attribute <uses-sdk> and specify a minSdkVersion and targetSdkVersion.
3.  Run the Xamarin.Android project on an emulator.

### Output

2> Deployment failed
2>Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
2>   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName)
2>   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass94_0.<InstallPackage>b__0(Task`1 t)
2>   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
2>   at System.Threading.Tasks.Task.Execute()
2>Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
2>   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName)
2>   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass94_0.<InstallPackage>b__0(Task`1 t)
2>   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
2>   at System.Threading.Tasks.Task.Execute()
2>Touching "obj\Debug\upload.flag".
2>Done building project "ClaraShoppingList.Android.csproj".
2>Build succeeded.
2>Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
2>   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName)
2>   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass94_0.<InstallPackage>b__0(Task`1 t)
2>   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
2>   at System.Threading.Tasks.Task.Execute()
2>
2>Deploy failed on Nexus_5X_API_27_x86
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by JonDouglas** [comment]
Hi @humbertoadan, 

Thank you for filing an issue. To understand what you're referring to, can you please let me know what you are referring to with regards to:

> Add the attribute and specify a minSdkVersion and targetSdkVersion.

Our 15.7.3 templates should build out of the box with a NuGet restore with 0 errors and 0 warnings. I'm not exactly sure what you mean by adding an attribute and then specifying these two items as they should already be defined in the `AndroidManifest.xml`

i.e.

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
          android:versionCode="1" 
          android:versionName="1.0" 
          package="App2.App2">
  <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="27" />
  <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/AppTheme">
  </application>
</manifest>
```

As for your deployment error, this occurs because you do not have the proper [CPU Architectures](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/cpu-architectures?tabs=vswin) enabled. Please enable `x86` for emulator deployments!

**Comment by humbertoadan** [comment]
It turns out the setting the CPU Architecture solved the problem. It still throws the warnings mentioned with this line in the manifest:
<uses-sdk android:minSdkVersion="17" android:targetSdkVersion="27" />
But besides that, there is no deployment error anymore. 

Thanks for the response.

**Comment by JonDouglas** [comment]
@humbertoadan Is there a trace to where those warnings are coming from in your error list such as a specific file? Or perhaps a [diagnostic build output](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) will have more information as to these warnings that you can upload here or include as a gist.

**Comment by jonathanpeppers** [comment]
@humbertoadan closing this as we haven't heard back on this in a while.

Feel free to reopen if you can send more info, thanks!
