### ISSUE TITLE
Huge build logs make contributions impossible

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1792]
- Open a Jenkins build result page e.g. https://jenkins.mono-project.com/job/xamarin-anroid-linux-pr-builder/2993/
- Click "Indication 1"

Here are what happens:

- On Firefox, since the log page is too long, it cannot complete loading, gives up in the middle:

![screenshot from 2018-06-08 05-56-32](https://user-images.githubusercontent.com/53929/41159632-04d80104-6ae2-11e8-9d39-486dc613ba06.png)

- On Chrome, it seems to load the complete log, but gives up rendering in the middle:

![screenshot from 2018-06-08 06-04-40](https://user-images.githubusercontent.com/53929/41159637-0abe4dc6-6ae2-11e8-98b7-a0e630bac306.png)

![screenshot from 2018-06-08 06-06-28](https://user-images.githubusercontent.com/53929/41159652-19ed1e6c-6ae2-11e8-9fc3-3732aa9611d4.png)

Whether it is a Chrome issue or not does not matter. What is important here is that Xamarin does not give sane way to diagnose any blocking problem for contributors (and of course our own) pull requests.

We have to fix this either 1) by reducing insane amount of build logs, or 2) provide any way to diagnose logs.

Actually 2) is not really a viable solution. Xamarin cannot ask contributors to read hundreds of megabytes of single build logs to investigate.

When we were using old CI server (wrench) it had never occurred because each build steps were split and we had to read only relevant log parts.

**Comment by atsushieno** [comment]
These are the PRs / related issues, blocked by this issue: https://github.com/xamarin/xamarin-android/pull/1489 https://github.com/xamarin/xamarin-android/pull/1790 https://github.com/xamarin/xamarin-android/issues/1738

**Comment by jpobst** [comment]
Jenkins is no longer used, so I think this issue is obsolete.
