### ISSUE TITLE
Duplicate resource.designer.cs files used for intellisense and search results

### ISSUE THREAD

**Issue by justintoth** [xamarin/xamarin-android#1794]
### Steps to Reproduce

1. Open our Android project and notice how every Resource usage (e.g. Resource.Id.ambient_pager) has a squiggly line, and when hovered over says "Ambiguity between 'Resource.Id.ambient_pager' and 'Resource.Id.ambient_pager'.)
2. Execute a search in the project for "ambient_pager".
3. Notice how the search results contain two declarations of ambient_pager in two separate resource.designer.cs files, the correct one being in android-application/Resources and an incorrect one in android-application/obj/Debug-Dev/designtime.
4. Notice also how all of the resources in the designtime version are set to a value of 0.
5. Try deleting the offending designtime version and rebuild, and it will be regenerated so you can't get rid of it.

### Expected Behavior

It shouldn't include the designtime resource.designer.cs in the project for intellisense or search results purposes, as it's causing duplicate resources to be generated.

### Actual Behavior

It's generating a duplicate resource.designer.cs, very annoying.

### Version Information

=== Visual Studio Community 2017 for Mac ===

Version 7.5 (build 1254)
Installation UUID: 62cf1ad2-0db0-41e1-ac78-aeb509d79f60
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /android/sdk
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.4 (14160)
Build 9F1027a

=== Xamarin.Mac ===

Version: 4.4.1.176 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.10.1.177 (Visual Studio Community)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400

=== Build Information ===

Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

**Comment by justintoth** [comment]
<img width="768" alt="screen shot 2018-06-08 at 10 43 33 am" src="https://user-images.githubusercontent.com/1443831/41164683-bf152afc-6b09-11e8-8648-2adf0a50e7f6.png">
<img width="858" alt="screen shot 2018-06-08 at 10 45 52 am" src="https://user-images.githubusercontent.com/1443831/41164684-bf3044ea-6b09-11e8-89c1-9e71c8632029.png">

**Comment by JonDouglas** [comment]
Thanks for your report! This looks like a duplicate of #1670 which we have fixed in https://github.com/xamarin/xamarin-android/pull/1779

For the time being, you can disable the managed resource parser via the following in a .csproj:

```
<AndroidUseManagedDesignTimeResourceGenerator>False</AndroidUseManagedDesignTimeResourceGenerator>
```

If this resolves your issue, please feel free to confirm or close this issue. Thanks again for your report!

**Comment by justintoth** [comment]
Thanks, that worked!
