### ISSUE TITLE
minimum version is 6.0 and target 8.0 still can't compile my code.

### ISSUE THREAD

**Issue by jassmith** [xamarin/xamarin-android#1800]
_From @anirugu on May 31, 2018 15:2_

I am using code from this repos 
https://github.com/xamarin/xamarin-forms-samples
![image](https://user-images.githubusercontent.com/2105258/40789992-5eef042a-6511-11e8-8b66-d198bf4da481.png)

when I compile I see this error, 

![image](https://user-images.githubusercontent.com/2105258/40790110-aff84552-6511-11e8-9d9b-ccbba3892b60.png)

What is going wrong in my code,  it was lowest when I clone so I set it to 6.0 if something is wrong with that lower version, Please check and let me know if it's a bug or I am missing something here.

_Copied from original issue: xamarin/Xamarin.Forms#2886_

**Comment by jonathanpeppers** [comment]
@anirugu can you give some more detail? I had some issues with the project myself, but they were different issues...

I tried this project: https://github.com/xamarin/xamarin-forms-samples/blob/866ab519f50a546a43261ac706d77f31efbd8132/Navigation/TabbedPageWithNavigationPage/Droid/TabbedPageWithNavigationPage.Droid.csproj

I did have to check this box under `Right Click Solution | Configuration Manager`:

![image](https://user-images.githubusercontent.com/840039/41357770-7e98df32-6eec-11e8-9123-9b9d63d8062e.png)

Then something was messed up in `Resources\values\styles.xml`, I just pasted over the styles from a default project:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<resources>

  <style name="MainTheme" parent="MainTheme.Base">
  </style>
  <!-- Base theme applied no matter what API -->
  <style name="MainTheme.Base" parent="Theme.AppCompat.Light.DarkActionBar">
    <!--If you are using revision 22.1 please use just windowNoTitle. Without android:-->
    <item name="windowNoTitle">true</item>
    <!--We will be using the toolbar so no need to show ActionBar-->
    <item name="windowActionBar">false</item>
    <!-- Set theme colors from http://www.google.com/design/spec/style/color.html#color-color-palette -->
    <!-- colorPrimary is used for the default action bar background -->
    <item name="colorPrimary">#2196F3</item>
    <!-- colorPrimaryDark is used for the status bar -->
    <item name="colorPrimaryDark">#1976D2</item>
    <!-- colorAccent is used as the default value for colorControlActivated
         which is used to tint widgets -->
    <item name="colorAccent">#FF4081</item>
    <!-- You can also set colorControlNormal, colorControlActivated
         colorControlHighlight and colorSwitchThumbNormal. -->
    <item name="windowActionModeOverlay">true</item>

    <item name="android:datePickerDialogTheme">@style/AppCompatDialogStyle</item>
  </style>

  <style name="AppCompatDialogStyle" parent="Theme.AppCompat.Light.Dialog">
    <item name="colorAccent">#FF4081</item>
  </style>
</resources>
```

If that works for you, maybe I just need to send a PR to this samples repository to clean these issues up?

**Comment by anirugu** [comment]
I got the project from github and trying to debug to my Android 8.0 Honor 9 lite, the minimum was set to 5.0 and it was not working so I changed it to 6.0 (thinking it will work from 6.0) but it doesn't work after setting 6.0 too

I update the nuget package and compiled, it's working on emulator but not on live player.

My device is 8.0 and I minimum to 6.0 so I think something for live player is going wrong, please check it with live player. it's not working there.

I will test same code again with that project and let you know what is going on. Give me sometime.

**Comment by jonathanpeppers** [comment]
@anirugu unfortunately the Live Player can't support everything that works in the emulator or debugging normally on the device.

Is it possible this project is hitting one of the limitations? https://docs.microsoft.com/en-us/xamarin/tools/live-player/limitations?tabs=android

**Comment by anirugu** [comment]
It's working now.

in case of hitting any limitation if that's how it's work then it's confusing, it must be report the real issue, the version number can't be a issue ( I check everything that time, even in my screenshot I set ito min 6.0 and compile and target 8.0)

**Comment by jonathanpeppers** [comment]
Ok @anirugu I think the real issue here is there is some mistake in the `styles.xml` file.

I'll follow up with a PR to update this sample, thanks!
