### ISSUE TITLE
 Question: Startup time on Xamarin.Android

### ISSUE THREAD

**Issue by yunusefendi52** [xamarin/xamarin-android#1802]
A while ago I read about startup time on Xamarin.Android, link to the blog is http://tirania.org/blog/archive/2018/May-18.html (yap, it's Miguel de Icaza's blog), in the blog it says that to remove any dynamic code to integrate with Java Runtime, I don't know much about that but I found this https://github.com/xamarin/xamarin-android/projects/1, is that project related to the blog I mentioned earlier?
Note that I already ask about startup time in X.F (https://github.com/xamarin/Xamarin.Forms/issues/2903).

Thanks..

**Comment by jpobst** [comment]
I think this has mainly been completed in the last few years as part of the effort to speed up XA start times:
https://devblogs.microsoft.com/dotnet/performance-improvements-in-dotnet-maui

Although it says MAUI, many improvements happened in the XA stack and affect all XA applications.
