### ISSUE TITLE
unsupported fstat syscall: Crashes on Samsung S8 running Android 8.0

### ISSUE THREAD

**Issue by kurtcz** [xamarin/xamarin-android#1803]
Google Play Console reports many crashes of my app running on Samsung S8 / Android 8.0 - this issue only started happening after 30th May 2018. I cannot reproduce the issue myself as I do not have the said phone. I wonder what has debugger to do with it as noone is trying to debug the application - the crash comes from my users - and the app has been compiled in release mode. Or perhaps the problem is calling ___dl_syscall+28_ ... ?

#### Call stack:
```
00 pc 000000000005beac /system/bin/linker (__dl_syscall+28)
01 pc 00000000000190ab /system/bin/linker (__dl__ZL24debuggerd_signal_handleriP7siginfoPv+642)
02 pc 0000000000130370 /data/app/com.tnemec.mariasek.android-03Z6ZpuZ_a9QKQrb9Lo5kg==/lib/arm/libmonosgen-2.0.so
```

### Steps to Reproduce

1. Checkout https://github.com/kurtcz/mariasek.git
2. Build solution in RELEASE mode
3. Deploy Mariasek.AndroidClient to Samsung S8 with Android 8.0 Oreo

### Expected Behavior
Application runs normally

### Actual Behavior
Application crashes

### Version Information
Visual Studio Enterprise 2017 for Mac
Version 7.5.2 (build 40)
Installation UUID: 70909173-5545-4391-be84-b9907f1a55e1
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 8.3.3.2 (Visual Studio Enterprise)
Android SDK: /Users/kurt/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3 (API level 10)
		4.2 (API level 17)
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Apple Developer Tools
Xcode 9.3.1 (14154.1)
Build 9E501

Xamarin.Mac
Version: 4.4.1.193 (Visual Studio Enterprise)

Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Enterprise)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 705020040
Git revision: cfe2fc0566bc4db990242959de40505a13f58352
Build date: 2018-05-30 11:24:18-04
Xamarin addins: 3ac7413ef51a88e06367313c27aec8f7292752a6
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.5

**Comment by kurtcz** [comment]
Can the below note at https://developer.android.com/about/versions/oreo/android-8.0-changes explain the behaviour?
```
Android 8.0 (API level 26) applies a Secure Computing (SECCOMP) filter to all apps. The list of allowed syscalls is restricted to those exposed through bionic. Although there are several other syscalls provided for backwards compatibility, we recommend against their use. 
```

**Comment by atsushieno** [comment]
It is an interesting insight. I could build and run a simple Xamarin.Forms app built with Release configuration and run it on Pixel 2 (running Android 8.1), so there is something between my simple case and your complicated MonoGame apps (which I have no idea how it makes use of native code, @dellis1972 might have some ideas).

It is also likely that is it Galaxy-8.0 specific. We need someone in the team who can try it.

(I'm using xamarin-android from master branch so there is slight chance that it could be an issue with previous versions. But I'm not aware of such changes in xamarin-android and deps.)

**Comment by atsushieno** [comment]
And any System.* API could also trigger unsupported syscalls internally and it's hitting in your app while not in my simple case. Maybe we'll have to ask someone in the runtime team to audit that.

**Comment by dellis1972** [comment]
I can't think of anything in MonoGame that would cause this. We don't do anything special other than call OpenGL/AL.  Hopefully QA has an S8..

**Comment by kurtcz** [comment]
It could indeed by any System.* call - either under the hood, or perhaps invoked directly by me.
In my code I call `new FileInfo()` in several places - can this be responsible for the `fstat` call perhaps? There was no try/catch block around these. Also I do numerous calls to `File.Exists()`

**Comment by pjcollins** [comment]
I managed to track down a Samsung Galaxy S8 (SM-G950F) running Android 8.0.0, however I did not have any luck reproducing this from VS 15.7.3 (XA 8.3.3.2) on Windows. I built and deployed the app in release mode twice, and spent a few minutes on each deployment attempt trying to play around with what I presume to be various game modes, by tapping various buttons, cards, etc.

@kurtcz do you have any more information from the play store on what kind of actions cause the crash? Perhaps I can try a more specific set of reproduction steps?

**Comment by kurtcz** [comment]
Sadly I don't have more than the call stack. Is there a way to track the memory address `0x130370` to an actual function inside the call?

Another thought - `Mariasek.cs` calls `CanLoadGame()` upon resume which calls FileInfo.Length - possible culprit?

To reproduce this:
1. try to start a new game (Nová hra) in the main menu, tap a few cards or buttons.
2. press the home button to minimize the app (should create a file on disk `Mariasek/_temp.hra`). 
3. Kill the app and then try to restart it - this should attempt to load the _temp.hra saved game - if the problem was around calling the FileInfo.Length then perhaps we will be able to reproduce the error.

**Comment by atsushieno** [comment]
Those people have different ideas on the error message. https://gitter.im/xamarin/xamarin-android?at=5b279d8ef3af564911d64989

**Comment by jmgueirard** [comment]
We were experiencing a lot of crashes on Galaxy S8, and we managed to resolve the issue by adding arm64-v8a in our supported abis. 

Also for testing, we used the [Samsung remote test lab](https://developer.samsung.com/remotetestlab/galaxy/rtlDeviceList.action).

**Comment by Springham** [comment]
Added arm64-v8a as suggested and it's resolved our problem on the Samsung S8

**Comment by jonathanantoine** [comment]
Thanks a lot @jmgueirard, I had this issue since a few weeks and I was struggling to fix it. All good now!

**Comment by DavyHubrecht** [comment]
Having the same issue. Any workaround without enabling 64-bit? Because we have some native libraries that only support 32-bit.
