### ISSUE TITLE
Secondary builds after touching .cs files in an app and library project are now slower in 15.8

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1814]
Separating the latest comment on #1246 out into a new issue.

### Steps to Reproduce
[reproduction from previous bug](https://bugzilla.xamarin.com/attachment.cgi?id=24686)
1. Download and deploy the attached project (`msbuild /t:Install Bug15162.csproj`) in debug mode.
2. Deploy the project again in debug mode (`msbuild /t:Install Bug15162.csproj`) without making any changes.
3. Touch `Bug15162\Activities\LibraryActivity.cs`
4. Touch `Lib15162\GoogleServiceActivity.cs`
5. Deploy the project a third time (`msbuild /t:Install Bug15162.csproj`) 

### Expected Behavior
15.7 (XA 8.3.3.2)
INITIAL TIME: 155.28
UNCHANGED TIME: 6.4
TRIVIAL CHANGE TIME: 10.43
TRIVIAL CHANGE OUTPUT: http://xqa.blob.core.windows.net/gist/log-29e472898c404b7899347db3491ebb45.txt

### Actual Behavior
15.8 (XA 8.4.0.1)
INITIAL TIME: 151.64
UNCHANGED TIME: 6.1
TRIVIAL CHANGE TIME: 28.08
TRIVIAL CHANGE OUTPUT: http://xqa.blob.core.windows.net/gist/log-027bfa60c7394c00a19e9c7323e5de45.txt

### Version Information
15.8 (XA 8.4.0.1)

> VS bug [#633425](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/633425)

**Comment by jonathanpeppers** [comment]
It might be an issue specific to this project, as I tried this one: https://github.com/xamarin/xamarin-android/tree/master/tests/Xamarin.Forms-Performance-Integration

And it's skipping the target when I edit CS files (in the library or the app):
```
 Skipping target "_UpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
```

**Comment by dellis1972** [comment]
Testing on ` 8.3.99.12` it works fine.. which is weird.

Is this only on Windows?

**Comment by dellis1972** [comment]
Happens on MacOS too.

**Comment by dellis1972** [comment]
What is interesting is the `obj/Debug/libraryprojectimports.cache` is updated.. but we are using `SaveIfChanged` so what is changing.. in theory nothing should change.

**Comment by dellis1972** [comment]
```
 diff -u old.cache Bug15162/obj/Debug/libraryprojectimports.cache
--- old.cache	2018-06-14 11:12:10.000000000 +0100
+++ Bug15162/obj/Debug/libraryprojectimports.cache	2018-06-14 11:12:28.000000000 +0100
@@ -1,8 +1,6 @@
 ﻿<?xml version="1.0" encoding="utf-8"?>
 <Paths>
   <Jars>
-    <Jar>obj/Debug/lp/0/jl/formsviewgroup.jar</Jar>
-    <Jar>obj/Debug/lp/7/jl/support-annotations.jar</Jar>
     <Jar>/Users/dean/Downloads/Bug15162-1/Bug15162/obj/Debug/lp/0/jl/formsviewgroup.jar</Jar>
     <Jar>/Users/dean/Downloads/Bug15162-1/Bug15162/obj/Debug/lp/10/jl/bin/classes.jar</Jar>
     <Jar>/Users/dean/Downloads/Bug15162-1/Bug15162/obj/Debug/lp/11/jl/bin/classes.jar</Jar>
```

Very weird. Looks like we have a bug in `ResolveLibraryProjectImports` where we are writing the relative path on some builds but the full path on others.

**Comment by dellis1972** [comment]
doesn't alway happen though.

**Comment by dellis1972** [comment]
and 

```
diff -u old.cache Bug15162/obj/Debug/libraryimports.cache 
--- old.cache	2018-06-14 11:29:41.000000000 +0100
+++ Bug15162/obj/Debug/libraryimports.cache	2018-06-14 11:30:42.000000000 +0100
@@ -3,27 +3,40 @@
   <ManifestDocuments>
     <ManifestDocument>obj/Debug/lp/10/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/11/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/11/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/12/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/13/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/14/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/14/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/15/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/15/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/16/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/16/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/17/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/17/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/18/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/18/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/19/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/20/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/20/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/21/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/27/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/27/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/28/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/29/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/29/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/30/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/30/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/31/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/32/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/33/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/33/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/34/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/35/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/35/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/36/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/37/jl/AndroidManifest.xml</ManifestDocument>
+    <ManifestDocument>obj/Debug/lp/37/jl/manifest/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/38/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/6/jl/AndroidManifest.xml</ManifestDocument>
     <ManifestDocument>obj/Debug/lp/8/jl/AndroidManifest.xml</ManifestDocument>
```

**Comment by dellis1972** [comment]
PR #1818 is up

**Comment by dellis1972** [comment]
We still have a problem with `ConvertResourcesCases` taking over 5 seconds to complete on the sample. This is during the `_GenerateJavaStubs` target call. Now it is expected that `_GenerateJavaStubs` is called because the library and main project were updated. 

That said we do need to make `ConvertResourcesCases` more efficient since it is taking up a ton of build time. I think we need to spit `ConvertResourcesCases` into two parts. One for fixing up the casing of view elements, the other for fixing up JCW's with the md5 hashed versions. We are also using XDocument for most of the work and looping through the elements multiple times which is inefficient. We should switch to using a stream based system like `XmlReader` or `XNavigator` to fix up these files.. and maybe `async` it too...
