### ISSUE TITLE
Allow storing native libs uncompressed in the .apk

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1822]
Android Things [appears to require that native libraries be stored uncompressed within the `.apk`](https://gitter.im/xamarin/xamarin-android?at=5b22a616c277fb705dce70bb).

![native libraries must be uncompressed](https://files.gitter.im/xamarin/xamarin-android/I4QI/image.png)

We should support that.

**Comment by jonpryor** [comment]
Related: https://github.com/flutter/flutter/issues/17173

**Comment by dellis1972** [comment]
In progress via #1827
