### ISSUE TITLE
monodroid_typemap_java_to_managed is failing

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1830]
When recently profiling Xamarin.Android application startup, we observed lots of string allocations were being performed as part of a `Object.GetObject()` call:

1. [`Object.GetObject()`](https://github.com/xamarin/xamarin-android/blob/bb8183c8c16667b18ba9197e78294b17a0af532c/src/Mono.Android/Java.Lang/Object.cs#L441-L468) >
2. [`TypeManager.CreateInstance()`](https://github.com/xamarin/xamarin-android/blob/bb8183c8c16667b18ba9197e78294b17a0af532c/src/Mono.Android/Java.Interop/TypeManager.cs#L235-L294) >
3. [`TypeManager.GetJavaToManagedType()`](https://github.com/xamarin/xamarin-android/blob/bb8183c8c16667b18ba9197e78294b17a0af532c/src/Mono.Android/Java.Interop/TypeManager.cs#L206-L228) >
4. [`JavaNativeTypeManager.ToCliType `](https://github.com/xamarin/java.interop/blob/8ad8e1205a29b22f4b353fa3f760e5f9959712a7/src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs#L117-L126)
5. ...

The problem is that (4) *should not have happened*; the only reason it happens is because the `monodroid_typemap_java_to_managed()` call is returning NULL, forcing us to hit a fallback path (slow! allocates many strings!):

https://github.com/xamarin/xamarin-android/blob/bb8183c8c16667b18ba9197e78294b17a0af532c/src/Mono.Android/Java.Interop/TypeManager.cs#L208-L210

We need to determine why `monodroid_typemap_java_to_managed()` is failing.

> VS bug [#635222](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635222)

**Comment by radekdoulik** [comment]
There are some Java types, which lack mappings. Not many though.

Testing with `xamarin-forms-samples/XamlSamples` app in Release configuration.

Mappings J->M:   20    OK 11    **missed 8**

Missed types:
```
android/app/ContextImpl
android/support/v4/app/BackStackRecord
android/support/v4/app/FragmentManagerImpl
android/view/IWindow$Stub
android/view/ViewRootImpl$W
com/android/internal/os/RuntimeInit$KillApplicationHandler
com/android/internal/policy/PhoneLayoutInflater
com/android/internal/policy/PhoneWindow
```

Looks like some of these are not bound, like `FragmentManagerImpl` or `BackStackRecord`. Some are not even in any *jar* like `PhoneWindow` and `PhoneLayoutInflater`.

```
iMac:Release rodo$ find .|grep jar$|while read jar; do jar tf $jar; done|grep FragmentManagerImpl
android/support/v4/app/FragmentManagerImpl$StartEnterTransitionListener.class
android/support/v4/app/FragmentManagerImpl$OpGenerator.class
android/support/v4/app/FragmentManagerImpl$FragmentTag.class
android/support/v4/app/FragmentManagerImpl$1.class
android/support/v4/app/FragmentManagerImpl$AnimateOnHWLayerIfNeededListener$1.class
android/support/v4/app/FragmentManagerImpl$2.class
android/support/v4/app/FragmentManagerImpl$AnimateOnHWLayerIfNeededListener.class
android/support/v4/app/FragmentManagerImpl$PopBackStackState.class
android/support/v4/app/FragmentManagerImpl.class
```
