### ISSUE TITLE
Xamarin Android BulletSpan Radius missing

### ISSUE THREAD

**Issue by ravikanasagra1** [xamarin/xamarin-android#1840]
I wanted to set radius for BulletSpan to make bullet larger then its default appearance. Android documentation says to user Radius to increase to make bullet larger.

Link: https://developer.android.com/reference/android/text/style/BulletSpan but same is not available in Xamarin Android BulletSpan.

### Expected Behavior
Current BulletSpan class does not have constructor on override as mentioned in above link to pass radius.

### Actual Behavior
Please add this constructor - 

`public BulletSpan (int gapWidth, int color, **int bulletRadius**) `

**Comment by atsushieno** [comment]
The constructor is "added in API level 28".

We will be shipping newer version with Android P support (it's already merged in master). It may still take a while to get it as a "stable" API though.
