### ISSUE TITLE
When two EditText are being used EditText unfocused gets the focus when one is in focus and the other one is in unfocussable state.

### ISSUE THREAD

**Issue by RabhiaBehamK** [xamarin/xamarin-android#1841]
[EditTextSample.zip](https://github.com/xamarin/xamarin-android/files/2111964/EditTextSample.zip)
### Steps to Reproduce

I have used the two EditText in Xamarin.Android project. One is Enabled true and other one is Enabled false. If I will not set the InputType and focus the first EditText the Next symbol was shown on the keypad. If I have pressed Next symbol, nothing happened. But I have set the InputType and focus the first EditText the Next symbol was shown on the Keypad. If I have pressed the Next symbol the focus gone into the disabled EditText. I have attached the simple sample. Please check and let me know the details.

### Expected Behavior
It should not get the focus when it is unfocussable.

### Actual Behavior
It is getting the focus when it is unfocussable.

**Comment by atsushieno** [comment]
We don't control any native behavior. If any Android framework behavior is not expected there is nothing we can do.

**Comment by jonathanpeppers** [comment]
Hi @RabhiaBehamK, @atsushieno is right. Xamarin.Android is just Android, and so you're going to see the same behavior with Java/Android Studio.

Perhaps you should try making a quick Java sample to verify, or post a general "How do I do this on Android?" question on StackOverflow.

Closing for now (sorry!), feel free to reopen if you find more information that shows a bug in Xamarin.Android.
