### ISSUE TITLE
Cannot build projects with latest mono 2018-04

### ISSUE THREAD

**Issue by garuma** [xamarin/xamarin-android#1845]
Either a normal build or invoking `msbuild /restore` will error-out with the following:

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(654,2): error MSB3644: The reference assemblies for framework "MonoAndroid,Version=v1.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

This issue is reproducible with build from https://github.com/mono/mono/commit/07c8f25fe536dbb7e244f965aa3f9a871f41e953  but not with earlier build https://github.com/mono/mono/commit/33a9dca4932ab793ff4a3c644e3a332f0e04af14 which could suggest https://github.com/mono/mono/commit/543b6872febade4b06429269eb40eeba0ad16a5a is the culprit

**Comment by kdubau** [comment]
@radical any updates here? This is blocking a lot of testing.

**Comment by GouriKumari** [comment]
nuget restore of a solution is failing with the same error and this blocks the building of iOS projects  in solution.

nuget restore "/Users/xamarinqa/agent/_work/r26/a/xamarin-forms-book-samples/Chapter14/AbsoluteDemo/AbsoluteDemo.sln"
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(654,2): error MSB3644: The reference assemblies for framework "MonoAndroid,Version=v1.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/xamarinqa/agent/_work/r26/a/xamarin-forms-book-samples/Chapter14/AbsoluteDemo/AbsoluteDemo/AbsoluteDemo.Droid/AbsoluteDemo.Droid.csproj]
