### ISSUE TITLE
Issues with Binding to jar file

### ISSUE THREAD

**Issue by wescur88** [xamarin/xamarin-android#1856]
### Steps to Reproduce

1. Create Android  Binding Project
2. Add minewBeaconAdmin.jar to the Jars folder as an EmbeddedJar
3. Set Target Framework to Android Api 21(Android 5.0 Lollipop)
4. Android Class Parser selection produces the same results
5. First compilation causes errors, edit generated files then build again(not rebuild)
   -change 'public override unsafe bool IsInAlphabet (sbyte p0)' to                                                
    'protected override unsafe bool IsInAlphabet (sbyte p0)' in Org.Apache.Commons.Csts.Binary.Base32
   - add 'IIterable IPhonemeExpr.Phonemes { get; }' to PhonemeList in 
    'Org.Apache.Commons.Csts.Language.BM.Rule'
6. Add binding to Android project, I am actually using a Dependency Service to access this library in 
   Xamarin Forms.
7. SDK guide http://docs.beaconyun.com/BeaconAdmin/Android_BeaconAdmin_Software_Development_Kit_Guide_en/
8. Hardware Smart Minew i4 iBeacon  
www.minewtech.cn/product/60456179997-220649015/Smart_Minew_i4_iBeacon_nRF51822_chipet_ble_4_0_beacon_for_IOS_Android.html

[MinewBeaconAdminSDK(Android)20170801 (2).zip](https://github.com/xamarin/xamarin-android/files/2116373/MinewBeaconAdminSDK.Android.20170801.2.zip)

[MinewBeaconAdminAndroidBinding.zip](https://github.com/xamarin/xamarin-android/files/2116377/MinewBeaconAdminAndroidBinding.zip)

### Expected Behavior
The expected behavior is to scan for beacons and connect to a beacon.

### Actual Behavior
When trying to connect to the beacon, "Java.Lang.NullPointerException: Attempt to invoke virtual method 'void com.minew.beaconset.ConnectService.connect(com.minew.beaconset.MinewBeacon)' on a null object reference"

sdk implementation:
```java
public void connect() {
        this.mConnectService = MinewBeaconManager.getInstance(this.mContext).getConnectService();
        this.mConnectService.connect(this.mBeacon);
        minewBeaconConnections.put(this.mBeacon.getMacAddress(), this);
        this.state = ConnectionState.BeaconStatus_Connecting;
    }
```

binding implementation:
```csharp
[Register ("connect", "()V", "GetConnectHandler")]
		public virtual unsafe void Connect ()
		{
			if (id_connect == IntPtr.Zero)
				id_connect = JNIEnv.GetMethodID (class_ref, "connect", "()V");
			try {

				if (((object) this).GetType () == ThresholdType)
					JNIEnv.CallVoidMethod (((global::Java.Lang.Object) this).Handle, id_connect);
				else
					JNIEnv.CallNonvirtualVoidMethod (((global::Java.Lang.Object) this).Handle, ThresholdClass, JNIEnv.GetMethodID (ThresholdClass, "connect", "()V"));
			} finally {
			}
		}
```

### Version Information

Microsoft Visual Studio Professional 2017 
Version 15.6.6
VisualStudio.15.Release/15.6.6+27428.2037
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA413
Microsoft Visual C++ 2017

Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA413
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10402.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.6.18072.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

EclipseAndroidImporter   1.0
Import Android projects from Eclipse.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.6.18072.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.6.18072.2
Provides templates and integration for the Django web framework.

Python - IronPython support   15.6.18072.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.6.18072.2
Profiling support for Python projects.

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

Telerik ASP.NET AJAX VSExtensions   2017.3.1017.0
Progress® Telerik® UI for ASP.NET AJAX Visual Studio extensions

Telerik ASP.NET Core VSExtensions   2017.3.1121.0
Progress® Telerik® UI for ASP.NET Core Visual Studio extensions

Telerik ASP.NET MVC VSExtensions   2017.3.1121.0
Progress® Telerik® UI for ASP.NET MVC Visual Studio extensions

Telerik WinForms VSExtensions   2018.1.215.2
Progress® Telerik® UI for WinForms Visual Studio extensions

Telerik WPF VSExtensions   2018.1.215.2
Progress® Telerik® UI for WPF Visual Studio extensions

Telerik Xamarin VSExtensions   2018.1.322.3
Progress® Telerik® UI for Xamarin Visual Studio extensions

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27428.2015
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.8
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Apache Cordova   15.123.7102.2
Visual Studio Tools for Apache Cordova

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Unity   3.6.0.5
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonathanpeppers** [comment]
Hi @wescur88,

I think your problem could be partly caused by what you are doing in step No. 5:

> First compilation causes errors, edit generated files then build again(not rebuild)
-change 'public override unsafe bool IsInAlphabet (sbyte p0)' to
'protected override unsafe bool IsInAlphabet (sbyte p0)' in Org.Apache.Commons.Csts.Binary.Base32
add 'IIterable IPhonemeExpr.Phonemes { get; }' to PhonemeList in
'Org.Apache.Commons.Csts.Language.BM.Rule'

This isn't the right way to handle fixups in binding projects--you should be using XPath expressions in `Metadata.xml`.

Jon Douglas has a good guide on how to get started: https://gist.github.com/JonDouglas/dda6d8ace7d071b0e8cb

Also checkout the Xamarin documentation here: https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/

Can you post your C# code that is failing after looking into using `Metadata.xml` instead?

**Comment by wescur88** [comment]
@jonathanpeppers the code that is failing is posted above. It is the under the binding implementation section. I will look into using Metadata.xml

**Comment by jonathanpeppers** [comment]
@wescur88 sorry what I meant was: update your sample project above _after_ you get `Metadata.xml` working.

If something is still happening, we'll need an updated project, thanks!

**Comment by wescur88** [comment]
I added these to the Metadata.xml

 <attr path="/api/package[@name='org.apache.commons.csts.binary']/class[@name='Base32']/method[@name='isInAlphabet' and count(parameter)=1 and parameter[1][@type='byte']]" name="visibility">protected</attr>
  <attr path="/api/package[@name='org.apache.commons.csts.language.bm']/class[@name='Rule.PhonemeList']/method[@name='getPhonemes' and count(parameter)=0]"  name="visibility">public</attr>
  <attr path="/api/package[@name='org.apache.commons.csts.language.bm']/class[@name='Rule.PhonemeList']/field[@name='Phonemes']"  name="visibility">private</attr>

The getPhonemes translates to Phonemes readonly property, but it returns global::System.Collections.Generic.IList<global::Org.Apache.Commons.Csts.Language.BM.Rule.Phoneme> instead of what the IPhonemeExpr requires which is an IIterable. Is there a way to force a return type in the Metadata.xml?

**Comment by jonathanpeppers** [comment]
The Xamarin documentation has an example of this: https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/troubleshooting-bindings#problem-class-does-not-implement-interface-method

**Comment by wescur88** [comment]
[MinewBeaconAdminAndroidBinding.zip](https://github.com/xamarin/xamarin-android/files/2141530/MinewBeaconAdminAndroidBinding.zip)

**Comment by jonathanpeppers** [comment]
So I think you need `return` here instead of `managedReturn`:
```xml
<attr
    path="/api/package[@name='org.apache.commons.csts.language.bm']/class[@name='Rule.PhonemeList']/method[@name='getPhonemes' and count(parameter)=0]"
    name="return">Java.Lang.IIterable</attr>
```

Your project built for me locally after changing this.

I'm going to mark this issue closed for now, as we are getting off-topic. It seems we are now in the area of implementing a binding, and there isn't actually a bug here for us to fix in Xamarin.Android.

Feel free to reopen if you get something that demonstrates a bug, thanks!

**Comment by wescur88** [comment]
Unhandled Exception:

Java.Lang.NullPointerException: Attempt to invoke virtual method 'void com.minew.beaconset.ConnectService.connect(com.minew.beaconset.MinewBeacon)' on a null object reference occurred

This still occurs performing the "Actual Beahvior" versus the "Expected Beahavior" with 

// Metadata.xml XPath method reference: path="/api/package[@name='com.minew.beaconset']/class[@name='MinewBeaconConnection']/method[@name='connect' and count(parameter)=0]"
		[Register ("connect", "()V", "GetConnectHandler")]
		public virtual unsafe void Connect ()
		{
			if (id_connect == IntPtr.Zero)
				id_connect = JNIEnv.GetMethodID (class_ref, "connect", "()V");
			try {

				if (((object) this).GetType () == ThresholdType)
					JNIEnv.CallVoidMethod (((global::Java.Lang.Object) this).Handle, id_connect);
				else
					JNIEnv.CallNonvirtualVoidMethod (((global::Java.Lang.Object) this).Handle, ThresholdClass, JNIEnv.GetMethodID (ThresholdClass, "connect", "()V"));
			} finally {
			}
		}

The jar library implements method:

public void connect() {
        this.mConnectService = MinewBeaconManager.getInstance(this.mContext).getConnectService();
        this.mConnectService.connect(this.mBeacon);
        minewBeaconConnections.put(this.mBeacon.getMacAddress(), this);
        this.state = ConnectionState.BeaconStatus_Connecting;
    }

jar yields expected behavior inside of Android Studio project

I will include the Xamarin.Android implementation that I use
[iBeaconManager.zip](https://github.com/xamarin/xamarin-android/files/2142887/iBeaconManager.zip)

**Comment by jonathanpeppers** [comment]
@wescur88 can you post a sample solution that we can use to reproduce the problem?

Can you make a `File | New Xamarin.Android Project` and just call this `iBeaconManager` class as you have designed it (including the binding project). As it is, I don't know how this class is _intended_ to be used or how we can see the issue in action...

**Comment by wescur88** [comment]
I will upload a sample project. You will need the Minew i4 iBeacon to reproduce error. https://minew.en.alibaba.com/product/60266048498-220649015/Minew_Ibeacon_Module_Bluetooth_4_0_BLE_Support_Near_field_Positioning_Sensor_Wireless_Acquisition.html?spm=a2700.8304367.prewdfa4cf.23.66f2717eZ0GizO

**Comment by wescur88** [comment]
Here is a link to the example project:
https://drive.google.com/open?id=16z6fN9PktqgappM9zrqXGAabyoSlpsK7

**Comment by wescur88** [comment]
@jonathanpeppers, were you able to reproduce the issue?
