### ISSUE TITLE
Incorrect CurrentCulture when phone is Hebrew and Android returns iw

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-android#1866]
CurrentCulture is incorreclty set to Invariant when the phone is set to language Hebrew (Android returns iw as ISO2)

From https://developer.android.com/reference/java/util/Locale, android returns only the old ISO2 codes for he/yi/id (old: iw, ji, ni).
When this is the case, Xamarin Android sets CurrentCulture to Invariant instead of the correct culture.

### Steps to Reproduce

1.  Create a xamarin android app
2. In the first OnCreate, call   ```Console.WriteLine($"culture={CultureInfo.CurrentCulture.Name} iso3={Locale.Default.ISO3Language}");```
3. Deploy on an android device (like Huawei P6 Lite) with language set on Hebrew and run

### Expected Behavior

The console should display the correct culture name. 

### Actual Behavior

The console displays nothing. And debugging indicates that the culture is InvariantCulture.

### Version Information

VS Windows 15.7.4

### Log File

06-21 08:46:25.309  7436  7436 I mono-stdout: culture= iso3=heb

**Comment by softlion** [comment]
Note that some Android versions seems to return the correct ISO2 code (the new one).

**Comment by jonathanpeppers** [comment]
@softlion I think the offending code might be: https://github.com/xamarin/xamarin-android/blob/ff28d572f2820b11490d0ef6c81c1d5e59e04886/src/Xamarin.Android.Build.Tasks/Resources/MonoPackageManager.java#L35-L64

So `language` for my device would be `en-US` and that get's passed into native code and to mono.

What happens on your device if you try this code:
```csharp
Console.WriteLine($"culture={CultureInfo.CurrentCulture.Name} lang={Locale.Default.Language} country={Locale.Default.Language}");
```

**Comment by jonathanpeppers** [comment]
Whoops, had a typo ^^ really looking to see what `Locale.Default.Country` is.

**Comment by atsushieno** [comment]
It is not supported even in desktop mono (and we are subset of it):

```
$ csharp -e "new System.Globalization.CultureInfo(\"hw\");"
System.Globalization.CultureNotFoundException: Culture name hw is not supported.
Parameter name: name
  at System.Globalization.CultureInfo..ctor (System.String name, System.Boolean useUserOverride, System.Boolean read_only) [0x00073] in <76e035f64456453283582b960f5f795e>:0 
  at System.Globalization.CultureInfo..ctor (System.String name, System.Boolean useUserOverride) [0x00000] in <76e035f64456453283582b960f5f795e>:0 
  at System.Globalization.CultureInfo..ctor (System.String name) [0x00000] in <76e035f64456453283582b960f5f795e>:0 
  at <InteractiveExpressionClass>.Host (System.Object& $retval) [0x00000] in <39cce476fa73435698717396f7d8c981>:0 
  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object& result, System.Boolean& result_set) [0x00038] in <21e28acc1d3c4407a760bb361463a867>:0 
  at Mono.CSharpShell.Evaluate (System.String input) [0x00000] in <c544e4c477474cb9b9454cafd2f57bdd>:0 
```

We will have to update mono locale data (mono/tools/locale-builder https://github.com/mono/mono/tree/master/tools/locale-builder).

**Comment by softlion** [comment]
The fact is, you should not support "hw" as it is an obsolete ISO code :)

There should only be a mapping between what android returns (ie: the OLD iso code "hw") and the new one ("he").

"he" is supported correctly.

**Comment by softlion** [comment]
@atsushieno it is not "hw", it is "iw"

**Comment by jonathanpeppers** [comment]
@softlion so we don't really want to add code such as:
```java
String language = locale.getLanguage();
switch (language) {
  case "iw":
    language = "he";
    break;
  case "ji":
    language = "yi";
    break;
  case "ni":
    language = "id";
    break;
}
```
We don't want to maintain this list...

Do you know of an alternate API that will work here?

**Comment by softlion** [comment]
no :)

**Comment by jonathanpeppers** [comment]
Here is an API we should try: https://developer.android.com/reference/java/util/Locale#getISO3Language()

**Comment by BioTurboNick** [comment]
Is there any workaround for this issue, especially when working from Xamarin Forms?

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
