### ISSUE TITLE
Support default interface methods

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1883]
It's been known that C# 8.0 will support default interface methods (DIM) and we will have to wait for 8.0. Turned out that there is already a preview version built within mono sdks, named as `csc-dim`.

We should make use of it and implement preview support for DIMs that will make Java bindings easier.

So far I observed they exist in xamarin-android built tree as:

```
/sources/xamarin-android$ find . -name csc-dim*
./external/mono/scripts/csc-dim.in
./external/mono/sdks/builds/android-armeabi-v7a-debug/scripts/csc-dim
./external/mono/sdks/builds/android-x86-debug/scripts/csc-dim
./external/mono/sdks/builds/android-host-Linux-debug/scripts/csc-dim

/sources/xamarin-android$ cat ./external/mono/sdks/builds/android-host-Linux-debug/scripts/csc-dim
#!/bin/sh
exec /sources/xamarin-android/external/mono/sdks/out/android-host-Linux-debug/bin/mono --gc-params=nursery-size=64m $MONO_OPTIONS /sources/xamarin-android/external/mono/sdks/out/android-host-Linux-debug/lib/mono/4.5/dim/csc.exe "$@"
```

**Comment by atsushieno** [comment]
Marek Safar said we should use csc-dim from system mono instead (after I noticed there is actually no `/sources/xamarin-android/external/mono/sdks/out/android-host-Linux-debug/lib/mono/4.5/dim/csc.exe`). What we should do is probably an extension NuGet package that provides these "dim" assemblies and override `CscToolPath` MSBuild property. So far `/p:CscToolExe=/path/to/my/lib/mono/4.5/dim` made it to work.

**Comment by jonpryor** [comment]
Existing on-desktop-JVM Java.Interop unit tests: https://github.com/xamarin/java.interop/tree/master/src/Java.Interop/Tests  
https://github.com/xamarin/java.interop/blob/master/src/Java.Interop/Tests/Java.Interop/JavaObjectTest.cs

These build atop a `JavaVMFixture`, which creates a desktop JVM: https://github.com/xamarin/java.interop/blob/master/tests/Java.Interop-Tests/Java.Interop/JavaVMFixture.cs  
https://github.com/xamarin/java.interop/blob/master/tests/TestJVM/TestJVM.cs

It should be straightforward to add a new `generator` unit test fixture which uses `TestJVM`/etc. to create an on-desktop JVM and run tests using `generator`-emitted code.

**Comment by jpobst** [comment]
Added in https://github.com/xamarin/xamarin-android/pull/3533.
