### ISSUE TITLE
Large libraries in binding causing dx error with too large of main dex file

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-android#1888]
### Steps to Reproduce

We've encountered a case where a pretty large .jar file in a Xamarin.Android binding project is causing the app project consuming it to hit a dx error:

```
com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:548)
    	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
    	at com.android.dx.command.dexer.Main.runDx(Main.java:289)
    	at com.android.dx.command.dexer.Main.main(Main.java:247)
    	at com.android.dx.command.Main.main(Main.java:94)
```

Now, on the Android Studio side, this can be mitigated by using the dex options:
```
dexOptions {
    preDexLibraries = true
    jumboMode = true
    keepRuntimeAnnotatedClasses false
}
```

In Xamarin, we can specify _some_ of these options:
```
<DxExtraArguments>--force-jumbo </DxExtraArguments>
```

However, there appears to be no way to do the equivalent of `keepRuntimeAnnotatedClasses false`.

Upon further investigation, it seems that `com.android.multidex.MainDexListBuilder` which is what we invoke from google's build-tools to generate the main dex list keep file, does not offer any ability to *not* keep runtime annotated classes, and these classes are added to the main dex keep list file no matter what.  So, gradle appears to generate this list some other way, or at least have the ability to remove these cases from the list before invoking dx.

I also looked to see if there was an opportunity to wire up a custom msbuild task to _intercept_ the `multidex.keep` file we generate and make changes to it, before we pass it to `dx.jar`, but unfortunately those operations happen within the same msbuild task so that doesn't appear to be possible.

One possible solution that comes to mind is to introduce some sort of `MainDexListRemove` msbuild property in which we could specify a file containing classes that should be removed from the `multidex.keep` file, that the Xamarin.Android build task would take into consideration after the file is created, and make changes to, before it's passed to dx.  This could mean the nuget package for the binding could include such a `multidex.remove` file in the .nupkg, with a targets file that sets the msbuild property so that apps consuming the binding would hopefully compile.

Thoughts?

**Comment by jonathanpeppers** [comment]
Just a question, since you have to set `DxExtraArguments` for this library to work already...

Will you likely have custom targets for this library?

I'm wondering if the `multidex.keep` lines should be exposed as an `<ItemGroup />` and you could add a target to remove them. We would also have to split this build task into two steps and provide a way to "do something" in the middle.

**Comment by Redth** [comment]
I think that's certainly a possibility here, and what I originally thought I might be able to accomplish, but as you noted there's no way to "do something" in the middle currently.  

However, considering there's much else one would do to a `multidex.keep` file besides adding and/or removing items from it, and if that's the case, it would certainly be more 'user friendly' to be able to pass files into a couple of item groups: `<MultidexKeepFile Include="blah.keep" />` and `<MultidexNoKeepFile Include="blah.nokeep" />`, even if they came from a nuget's .targets file, instead of having to write a custom msbuild task to intercept things.

**Comment by atsushieno** [comment]
I'm seeing these lines from `build-tools/28.0.0/mainDexClasses`:

```
disableKeepAnnotated=

while true; do
if expr "x$1" : 'x--output' >/dev/null; then
    exec 1>$2
    shift 2
elif expr "x$1" : 'x--disable-annotation-resolution-workaround' >/dev/null; then
    disableKeepAnnotated=$1
    shift 1
elif expr "x$1" : "x--aapt-rules" >/dev/null; then
    extrarules=$2
    shift 2
else
    break
fi
done
```

Maybe this can be used?

**Comment by jonpryor** [comment]
@atsushieno: We no longer use `build-tools/*/mainDexClasses`, as it didn't work reliably on Windows; see 6829b7d1becee2d979516bc0ac4513eac29ee865.  As such, your suggestion won't work. :-(

**Comment by dellis1972** [comment]
@jonpryor it would since it passes the `disableKeepAnnotated` value to the .jar via

`java -cp "$jarpath" com.android.multidex.MainDexListBuilder ${disableKeepAnnotated} "${tmpOut}" ${@} ||  exit 11`

**Comment by dellis1972** [comment]
so I guess we can use `--disable-annotation-resolution-workaround` ?

**Comment by atsushieno** [comment]
yep, that's my point :-)

**Comment by dellis1972** [comment]
we can add an `ExtraArgs` property to `CreateMultiDexMainDexClassList` which should allow end users to take care of additional arguments they need
