### ISSUE TITLE
Missing Activity Attributes such as android:enableVrMode are missing.

### ISSUE THREAD

**Issue by rawnsley** [xamarin/xamarin-android#1891]
This was flagged [in the old bug tracker](https://bugzilla.xamarin.com/show_bug.cgi?id=58958), but hasn't made it to the new one. 

android:showForAllUsers has been added since the bug was originally raised, but android:enableVrMode has not. To be fair it's not listed in the [main documentation for <activity>](https://developer.android.com/guide/topics/manifest/activity-element), but it is a [valid and necessary activity property](https://developers.google.com/vr/reference/vr-manifest).

**Comment by JonDouglas** [comment]
Just to include the relevant information on this issue where Xamarin.Android is potentially missing attributes for(Not a complete list):

- [autoRemoveFromRecents](https://developer.android.com/guide/topics/manifest/activity-element#autoremrecents)
- [banner](https://developer.android.com/guide/topics/manifest/activity-element#banner)
- [colorMode](https://developer.android.com/guide/topics/manifest/activity-element#colormode)
- description(NOT FOUND IN DOCS, ONLY SOURCE)
- [enableVrMode](https://developers.google.com/vr/reference/vr-manifest)
- finishOnCloseSystemDiaglogs(NOT FOUND IN DOCS, ONLY SOURCE)
- lockTaskMode(NOT FOUND IN DOCS, ONLY SOURCE)
- logo(NOT FOUND IN DOCS, ONLY SOURCE)
- [maxAspectRatio](https://developer.android.com/guide/topics/manifest/activity-element#maxaspectratio)
- [maxRecents](https://developer.android.com/guide/topics/manifest/activity-element#maxrecents)
- [persistableMode](https://developer.android.com/guide/topics/manifest/activity-element#persistableMode)
- recreateOnConfigChanges(NOT FOUND IN DOCS, ONLY SOURCE)
- [relinquishTaskIdentity](https://developer.android.com/guide/topics/manifest/activity-element#relinquish)
- resumeWhilePausing(NOT FOUND IN DOCS, ONLY SOURCE)
- rotationAnimation(NOT FOUND IN DOCS, ONLY SOURCE)
- [showForAllUsers](https://developer.android.com/guide/topics/manifest/activity-element#showForAllUsers)
- showOnLockScreen(NOT FOUND IN DOCS, ONLY SOURCE)
- [singleUser](https://source.android.com/devices/tech/admin/multiuser-apps)
- [splitName](https://developer.android.com/reference/android/content/pm/ComponentInfo#splitName)
- visibleToInstantApps(NOT FOUND IN DOCS, ONLY SOURCE)

![activity attributes](https://user-images.githubusercontent.com/1288848/41999484-dbb7f796-7a1a-11e8-986f-34b67cba58f0.png)
![activity attributes2](https://user-images.githubusercontent.com/1288848/41999485-dbd52adc-7a1a-11e8-926f-be6a1210f2d4.png)
