### ISSUE TITLE
Firebase Cloud Firestore error

### ISSUE THREAD

**Issue by amitairos** [xamarin/xamarin-android#1911]
I'm trying out Firestore with Xamarin.Android.
However, after putting this:

` var db = FirebaseFirestore.Instance;`
It throws an error:

`FirebaseOptions.getProjectId() cannot be null`

I have a Google Services JSON with the right build settings, and it has a project id. What is the problem?

**Comment by jonathanpeppers** [comment]
This issue was moved to xamarin/GooglePlayServicesComponents#121
