### ISSUE TITLE
Need to support side-loaded typemap files

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1917]
The `typemap.jm` and `typemap.mj` files are produced as part of the packaging process by [`TypeNameMapGenerator`](https://github.com/xamarin/java.interop/blob/d1cce1907815df1f01501cc3a2b500bdda3afffa/src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs) and the [`<GenerateJavaStubs/>` task](https://github.com/xamarin/xamarin-android/blob/5004d0ff724039737399032192a7f7640feb505a/src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs#L294-L302).

In order to help improve app performance (Issues #1443, #1829, #1830, #1831) we would like to *require* the presence and use of the `typemap` files, removing support for the Reflection-based fallback path, along with obsoleting [`Java.Interop.TypeManager.RegisterType(string, Type)`](https://github.com/xamarin/xamarin-android/blob/5004d0ff724039737399032192a7f7640feb505a/src/Mono.Android/Java.Interop/TypeManager.cs#L295-L311) and [`Java.Interop.TypeManager.RegisterPackage()` and `TypeManager.RegisterPackages()`](https://github.com/xamarin/xamarin-android/blob/5004d0ff724039737399032192a7f7640feb505a/src/Mono.Android/Java.Interop/TypeManager.cs#L313-L345).

However, in order to fully use `typemap` files, we need to support them in Fast Deployment scenarios.  The problem is that the `typemap` files are currently stored as per-`.apk` data.  As such, if a library assembly changes in a manner which requires updating the typemap files, the `App.apk` must be rebuilt and redeployed, if only to transfer the updated `typemap` files.

We need to update `src/monodroid` so that it will look for the `typemap` files in the `.__override__` directories in addition to the `.apk` files.  We can then generate `typemap` files as per-Assembly data and side-load them along with the corresponding assemblies, ensuring that when a new Assembly is deployed to the device we also deploy updated `typemap` files.

*As a suggestion*, we could name the per-assembly files as `typemap-$(AssemblyBaseName).{jm,mj}`, e.g. `typemap-Mono.Android.jm` and `typemap-Mono.Android.mj`.

**Comment by dellis1972** [comment]
The first part of this is done, the side loading support is in. We now need to look at generating type maps on a per assembly basis.

**Comment by grendello** [comment]
The second part, typemap generation and runtime support, is implemented in https://github.com/xamarin/xamarin-android/pull/3992
