### ISSUE TITLE
 Proguard fails when you use SDK >23 and Google SDK

### ISSUE THREAD

**Issue by jonathanantoine** [xamarin/xamarin-android#1918]
### Steps to Reproduce

When activating Proguard using an Android SDK > and Google Play SDK (Admob for instance) build fails because it does not find org.apache.http classes (logs below). 

[ReproProguardApp.zip](https://github.com/xamarin/xamarin-android/files/2163105/ReproProguardApp.zip)

### Expected Behavior
The project build

### Version Information

Visual Studio Community 2017 for Mac
Version 7.5.3 (build 7)
Installation UUID: 37cc8c40-d076-4974-8bf8-344f707f4364
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/jonathanantoine/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Apple Developer Tools
Xcode 9.4.1 (14161)
Build 9F2000

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

Enabled user installed addins
LiveXAML 1.3.31
NuGet Package Management Extensions 0.13

### Log File
Target _CompileToDalvikWithDx:
    /usr/bin/java -jar /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/proguard/lib/proguard.jar -include '/Users/jonathanantoine/Library/Developer/Xamarin/android-sdk-macosx//tools/proguard/proguard-android.txt' -include 'obj/Release/proguard/proguard_xamarin.cfg' -include 'obj/Release/proguard/proguard_project_references.cfg' -include 'obj/Release/proguard/proguard_project_primary.cfg' -include '/Users/jonathanantoine/Downloads/ReproProguardApp/packages/Xamarin.Android.Arch.Lifecycle.Runtime.1.0.3.1/build/MonoAndroid80/../../proguard/proguard.txt' -include '/Users/jonathanantoine/Downloads/ReproProguardApp/packages/Xamarin.Android.Support.Core.UI.27.0.2.1/build/MonoAndroid81/../../proguard/proguard.txt' -include '/Users/jonathanantoine/Downloads/ReproProguardApp/packages/Xamarin.Android.Support.Media.Compat.27.0.2.1/build/MonoAndroid81/../../proguard/proguard.txt' -include 'obj/Release/XbdMerge/proguard/dc663e480.txt' -include 'obj/Release/XbdMerge/proguard/e843ef2a0.txt' -injars "'obj/Release/android/bin/classes/../classes.zip'(!META-INF/MANIFEST.MF):'/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v8.1/mono.android.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/1/jl/arch-core-common.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/10/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/11/jl/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/12/jl/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/2/jl/arch-lifecycle-common.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/3/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/5/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/6/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/7/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/8/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/9/jl/bin/classes.jar'(!META-INF/MANIFEST.MF)" -libraryjars '/Users/jonathanantoine/Library/Developer/Xamarin/android-sdk-macosx/platforms/android-27/android.jar' -outjars obj/Release/proguard/__proguard_output__.jar -optimizations !code/allocation/variable 
    PROGUARD : warning : com.google.android.gms.internal.zzal: can't find superclass or interface org.apache.http.client.methods.HttpEntityEnclosingRequestBase
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.Header
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.Header
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.StatusLine
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.impl.cookie.DateUtils
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.impl.cookie.DateUtils
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.Header
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.Header
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.StatusLine
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.HttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.Header
    PROGUARD : warning : com.google.android.gms.internal.zzad: can't find referenced class org.apache.http.Header
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.HttpClient
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpDelete
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpGet
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpHead
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpOptions
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpPost
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpPut
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpRequestBase
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpTrace
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpUriRequest
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.entity.ByteArrayEntity
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced method 'void addHeader(java.lang.String,java.lang.String)' in program class com.google.android.gms.internal.zzal
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpDelete
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpGet
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpHead
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpOptions
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpPost
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpPost
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpPut
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpPut
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpTrace
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.entity.ByteArrayEntity
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.HttpClient
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpUriRequest
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpUriRequest
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.HttpClient
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.HttpClient
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpUriRequest
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpUriRequest
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
    PROGUARD : warning : com.google.android.gms.internal.zzak: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
    PROGUARD : warning : com.google.android.gms.internal.zzal: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
    PROGUARD : warning : com.google.android.gms.internal.zzal: can't find referenced method 'void setURI(java.net.URI)' in program class com.google.android.gms.internal.zzal
    PROGUARD : warning : com.google.android.gms.internal.zzal: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
    PROGUARD : warning : com.google.android.gms.internal.zzam: can't find referenced class org.apache.http.impl.cookie.DateParseException
    PROGUARD : warning : com.google.android.gms.internal.zzam: can't find referenced class org.apache.http.impl.cookie.DateUtils
    PROGUARD : warning : com.google.android.gms.internal.zzam: can't find referenced class org.apache.http.impl.cookie.DateUtils
    PROGUARD : warning : com.google.android.gms.internal.zzan: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzan: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.ProtocolVersion
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.StatusLine
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.entity.BasicHttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.message.BasicHeader
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.message.BasicHttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.message.BasicStatusLine
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.ProtocolVersion
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.entity.BasicHttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.entity.BasicHttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.entity.BasicHttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.entity.BasicHttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.entity.BasicHttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.message.BasicHeader
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.message.BasicHttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.message.BasicHttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.message.BasicHttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.message.BasicStatusLine
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.StatusLine
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.HttpResponse
    PROGUARD : warning : com.google.android.gms.internal.zzao: can't find referenced class org.apache.http.HttpEntity
    PROGUARD : warning : com.google.android.gms.internal.zzas: can't find referenced class android.net.http.AndroidHttpClient
    PROGUARD : warning : com.google.android.gms.internal.zzas: can't find referenced class android.net.http.AndroidHttpClient
    PROGUARD : warning : there were 84 unresolved references to classes or interfaces.
             You may need to add missing library jars or update their versions.
             If your code works fine without the missing classes, you can suppress
             the warnings with '-dontwarn' options.
             (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
    PROGUARD : warning : there were 2 unresolved references to program class members.
             Your input classes appear to be inconsistent.
             You may need to recompile the code.
             (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
    java.io.IOException: Please correct the above warnings first.
    	at proguard.Initializer.execute(Unknown Source)
    	at proguard.ProGuard.initialize(Unknown Source)
    	at proguard.ProGuard.execute(Unknown Source)
    	at proguard.ProGuard.main(Unknown Source)
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2198,3): error MSB6006: "java" exited with code 1.
Done building target "_CompileToDalvikWithDx" in project "ReproProguardApp.csproj" -- FAILED.

Done building project "ReproProguardApp.csproj" -- FAILED.

Build FAILED.

**Comment by jonathanantoine** [comment]
Hello again and thank you. The issue is still here with the latest version of Google Play Services so I don't think this can be closed.

**Comment by JonDouglas** [comment]
@jonathanantoine Can you please add a reproduction using the latest versions across the board? Thanks! I'll go ahead and reopen the issue for the time being to investigate.

**Comment by jonathanantoine** [comment]
@JonDouglas I updated the logs and the reproduction project in the original comment. Thanks for investigating !

**Comment by Redth** [comment]
It looks like for some reason the custom target in GooglePlayServices.Basement's .targets is not properly resolving the path to your Android SDK, so in turn the extra apache http .jar is not considered in the proguard call.  This looks like a bug on our end.

In any case you can work around it today by adding something like this to your .csproj:

```
<ItemGroup>
    <AndroidExternalJavaLibrary Include="/Users/you/Library/Developer/Xamarin/android-sdk-macosx/platforms/android-27/optional/org.apache.http.legacy.jar" />
  </ItemGroup>
```

**Comment by Redth** [comment]
@jonathanantoine you could just add a proguard config file that ignores warnings for org.apache.http.**:

```
-dontwarn org.apache.http.**
```

**Comment by jonathanantoine** [comment]
ok, thanks I will take a look. In all case, I notice that the drop of "size of my APK" was barely noticeable :(

Regards.

**Comment by eman1986** [comment]
adding

`<uses-library android:name="org.apache.http.legacy" android:required="false" />`

to AndroidManfest.xml is the only thing that gets rid of that message for me.

**Comment by andrelundin** [comment]
Having same issue here. Works fine in debug. Can't build in release.

Tried adding proguard.cfg with -dontwarn org.apache.http.**

Also adding <uses-library android:name="org.apache.http.legacy" android:required="false" /> to Android manifest.

None of them worked.

Can't add 

<ItemGroup>
    <AndroidExternalJavaLibrary Include="/Users/you/Library/Developer/Xamarin/android-sdk-macosx/platforms/android-27/optional/org.apache.http.legacy.jar" />
  </ItemGroup>

As it is later built and released by Azure DevOps pipeline.

**Comment by Redth** [comment]
Try updating to a newer version of Google Play Services basement? 

This is the target which includes it now in recent versions:
https://github.com/xamarin/GooglePlayServicesComponents/blob/master/source/com.google.android.gms/play-services-basement/merge.targets#L98-L105

**Comment by Lordinaire** [comment]
@andrelundin Adding ```-dontwarn org.apache.http.**``` works great in my case, even with an Azure DevOps pipeline.

Hi @jonathanantoine 🤜🏻
