### ISSUE TITLE
Migrate to Android NDK r17 and drop "armeabi"

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1921]
If we use android-ndk-r17 series, xamarin-android tests do not build anymore:

```
    Android NDK: The armeabi ABI is no longer supported. Use armeabi-v7a.    
```

There is no reason to keep supporting armeabi which **Google does not support**.

Sadly "armeabi" specification in our codebase is quite everywhere. We should take time to eliminate everything.

**Comment by atsushieno** [comment]
https://github.com/xamarin/xamarin-android/pull/1995

**Comment by jonpryor** [comment]
`armeabi` support was removed in 9abbfc44dc86450769a3c4ef8d415d442d5de37c.

Support for NDK r17 and r18 was skipped, and support (requirement) for NDK r19 was added in 7bb4f0e77d9f659fed6006f9b9ab6e4a1cf62ada.
