### ISSUE TITLE
App gets installed but error on launching in Google Pixel 2, Moto G devices

### ISSUE THREAD

**Issue by virtualbankingapp** [xamarin/xamarin-android#1922]
Hi Xamarin Team,

We have made app with Xamarin. Our app is working in many devices except few such as Google Pixel 2, Moto G Latest Version and we don't have Nexus phones to test.
App store link for the app https://play.google.com/store/apps/details?id=com.wealth.centrum

App gets installed but whenever the user tries to launch screen gets attached error. Unable to launch app. Please provide help or suggestion so that this issue is resolved in such kinds of devices.

If any dependency need to be installed or need to set the specific framework please specify

Screenshot and manifest file details below at the bottom of the post 

### Expected Behavior
App should work in all android devices

### Actual Behavior
App not working in Google Pixel 2 , Moto G devices

### Version Information

Microsoft Visual Studio Premium 2013
Version 12.0.30501.00 Update 2
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Premium

LightSwitch for Visual Studio 2013   06191-004-0456033-02615
Microsoft LightSwitch for Visual Studio 2013

Team Explorer for Visual Studio 2013   06191-004-0456033-02615
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06191-004-0456033-02615
Microsoft Visual Basic 2013

Visual C# 2013   06191-004-0456033-02615
Microsoft Visual C# 2013

Windows Phone SDK 8.0 - ENU   06191-004-0456033-02615
Windows Phone SDK 8.0 - ENU

.NET Reflector Visual Studio Extension   9.0.1.374
Integrates .NET Reflector into Visual Studio to allow you to seamlessly debug into third-party code and assemblies, even if you don't have the source code for them.

ASP.NET and Web Tools   2013.2.50425

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.1.20409.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.1
Provides common services for use by Azure Mobile Services and Windows Azure Tools.

Debugging Tools for Windows   6.3.9600.17029
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.

Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 

NuGet Package Manager   2.8.50313.46
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   12.0.30919.1
Microsoft SQL Server Data Tools

StyleCop   4.7.48.0
Provides source code style and consistency tools. See http://www.stylecop.codeplex.com/ for more details.

Windows Azure Mobile Services Tools   1.1
Windows Azure Mobile Services Tools

Windows Driver Kit   6.3.9600.17246
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Xamarin   4.0.4.4 (a9c7826)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.4.0 (ee215fc)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.6.2.2 (be25da5)
Visual Studio extension to enable development for Xamarin.iOS.

### Log File
Log in debug mode output window
Couldn't connect to logcat, GetProcessId returned: 0

Manifest file start(removed < & </ characters)
package="com.wealth.centrum" android:installLocation="auto" android:versionCode="2" android:versionName="1.0"
	uses-sdk android:minSdkVersion="15" 
	application android:label="Centrum Wealth" android:icon="@drawable/Icon"
	uses-permission android:name="android.permission.INTERNET" 
	uses-permission android:name="android.permission.WAKE_LOCK" 
	uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" 
	activity android:name="com.example.ExitActivity" android:theme="@android:style/Theme.NoDisplay" android:autoRemoveFromRecents="true" 

manifest end

![a1](https://user-images.githubusercontent.com/40823938/42269757-a3c9afbe-7f9c-11e8-8e31-e6317348517c.png)

**Comment by jonathanpeppers** [comment]
Hi @virtualbankingapp,

I have a Google Pixel 2 and your app from Google Play worked for me: I made it to a login screen.

Can you attach the [ADB log](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=vswin) of a device that is not working? It should have an error message or _something_ we can go on.

**Comment by virtualbankingapp** [comment]
Thanks for checking the apps in your devices. Our problem's root cause is identified "The splash image size is the problem". We are fixing the same.
