### ISSUE TITLE
Design-time Resource.Designer.cs breaks Intellisense for Resources/xml/* files

### ISSUE THREAD

**Issue by lukepothier** [xamarin/xamarin-android#1928]
### Steps to Reproduce

1. Download attached [App.zip](https://github.com/xamarin/xamarin-android/files/2167502/App.zip)
2. Build App.csproj

### Expected Behavior

The build succeeds, the error list is clear, and there are no Intellisense issues.

### Actual Behavior

The build does succeed, but there's an Intellisense error on line 26 in `MainActivity.cs`. The static Resource ID for `test.xml` is missing, despite it being in a valid `/Resources` folder with the correct build action. The `Resource.Designer.cs` file in `/Resources` contains the expected generated class:

	public partial class Xml
	{
			
		// aapt resource value: 0x7f070000
		public const int test = 2131165184;
			
		static Xml()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
			
		private Xml()
		{
		}
	}

whereas it is absent from the design-time `Resource.Designer.cs` in `obj/Debug/designtime`.

![image](https://user-images.githubusercontent.com/7534682/42337118-015ad4b6-8086-11e8-8620-f1217c64762c.png)

![image](https://user-images.githubusercontent.com/7534682/42337125-07d16102-8086-11e8-93fd-03389be40d1a.png)

### Version Information

Microsoft Visual Studio Enterprise 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonathanpeppers** [comment]
@dellis1972 could this also #1914 ?

**Comment by dellis1972** [comment]
This is fixed via [1]. Specifically [2]. The original version of the Managed Parser which is used for design time builds was missing some things (like 'xml' and `dimen`). This should be fixed in the d15-8 preview channel.


[1] https://github.com/xamarin/xamarin-android/commit/3395dbcbb54d60ec2867398f34a96ef8831fa8f5
[2] https://github.com/xamarin/xamarin-android/commit/3395dbcbb54d60ec2867398f34a96ef8831fa8f5#diff-59ae4b660fb37cb01b7d310a733ea531R228
