### ISSUE TITLE
DeleteBinObj issue with Resources

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#1933]
### Steps to Reproduce

1. Somehow when testing/building [Xamarin.Forms.ControlGallery.Android](https://github.com/xamarin/Xamarin.Forms/tree/42c07d1ae5aa56eb574b7d169499f1a9af7ec080/Xamarin.Forms.ControlGallery.Android)
2. I randomly get an `APT0000` error
3. `Rebuild` fixes it

I am not exactly sure what step I did to _cause_ this, the error I get is:

```
"C:\Users\myuser\Desktop\Git\Xamarin.Forms\Xamarin.Forms.ControlGallery.Android\Xamarin.Forms.ControlGallery.Android.csproj" (default target) (1) ->
(_UpdateAndroidResgen target) ->
  Resources\layout\NativeAndroidCell.axml(3): error APT0000: No resource found that matches the given name (at 'background' with value '@drawable/CustomSelector'). [C:\Users\myuser\Desktop\Git\Xamarin.Forms\Xamarin.Forms.ControlGallery.Android\Xamarin
.Forms.ControlGallery.Android.csproj]
  Resources\layout\NativeAndroidListViewCell.axml(3): error APT0000: No resource found that matches the given name (at 'background' with value '@drawable/CustomSelector2'). [C:\Users\myuser\Desktop\Git\Xamarin.Forms\Xamarin.Forms.ControlGallery.Androi
d\Xamarin.Forms.ControlGallery.Android.csproj]

    7 Warning(s)
    2 Error(s)
```

It could be related to opening the solution in VS for Windows?

In `obj\Debug\res` I see both `customselector.xml` and `customselector2.xml`.

### Expected Behavior

I should not have to `Rebuild` here, this seems to be a DeleteBinObj issue.

### Actual Behavior

I have to `Rebuild` for the project to build.

### Version Information

I was using xamarin-android/master as of: 3558fd2a5dadf7b6a9eb9750f33196e593359312

### Log File

I zipped up the project, `obj`, `bin`, and `msbuild.binlog`: https://www.dropbox.com/s/6l5ak1mlqybw9k5/Xamarin.Forms.ControlGallery.Android.zip?dl=0

_NOTE: Github had a 10MB limit_

**Comment by jonathanpeppers** [comment]
@dellis1972 I noticed the branch I'm working on doesn't have https://github.com/xamarin/xamarin-android/pull/1914

Could that be the cause?

**Comment by dellis1972** [comment]
Its probable. Best thing to do is to check the various .cache files in the intermediate dir. If they are missing the Resource paths for the `lp` directories then #1914 may well be the fix.

**Comment by jonathanpeppers** [comment]
`libraryprojectimports.cache` looks fine...

One thing that is _weird_ is I have an `obj\Debug` folder with stuff in it and `obj\Debug\MonoAndroid81`. When I'm getting the error, it's using the `MonoAndroid81` directory, which should not have been bothered by the IDE at all--it was on 15.7.4.
