### ISSUE TITLE
What is the registry location for the android sdk manager in VS2017 15.7.4 and later installed on Windows OS machine?

### ISSUE THREAD

**Issue by vadivel1234** [xamarin/xamarin-android#1935]
Hi, 

As described in the below StackOverflow link, we used the below mentioned "Android SDK registry location" to find the Android SDK installed location on Windows OS machine in our application for a long time. 

**StackOverflow:**
1.  https://stackoverflow.com/questions/51100309/registry-key-file-is-not-found-for-android-sdk-tools-in-vs2017-15-8-preview-1-1
2.  https://stackoverflow.com/questions/51191349/how-to-find-android-sdkmanager-installed-path-in-windows-os-with-visual-studio-2

**Android SDK registry location:** HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Android SDK Tools

From Visual Studio 2017 15.7.4 and later, we could not see the above stated "Android SDK registry location". Instead, we could see the below registry entry in some machines but not in German OS.

HKEY_CURRENT_USER\Software\Xamarin\VisualStudio\15.0_b8627b83\Android 

In some machines, we could find the registry entry here. 

HKEY_USERS\S-1-5-21-1415224841-4160497810-138773753-3121\Software\Xamarin\VisualStudio\15.0_b8627b83\Android

Due to this, our application throwing exception and we could not use our application anymore.

Also, we found that there were some changes in SDK installations along with Visual Studio 2017 15.7 versions as mentioned in below link. Is this affect the Android SDK installed location in the registry?
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#install2
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#xamarin-sdkmanagement

Could you please let us know how to find android SDK installed location from the registry entry which should be common for all language Windows OS machines?

**Comment by jonathanpeppers** [comment]
Hi @vadivel1234 I would recommend using the `AndroidSdkInfo` class we have in this repository: https://github.com/xamarin/xamarin-android-tools

We use it in Xamarin.Android itself to locate the Android SDK.

For an example on how to use it, see: https://github.com/xamarin/xamarin-android/blob/7c38f601f8667749686bd464d3df649a1273fa3e/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/KeyToolTests.cs#L27

You can pass `null` for any of the paths and it will attempt to find them.

Closing this for now, as this doesn't really seem to be an issue with Xamarin.Android. If you find a problem with `xamarin-android-tools`, file an issue there, thanks!

**Comment by vadivel1234** [comment]
Hi @jonathanpeppers ,

I never mentioned that this is an issue with Xamarin.Android. Am seeking helpline to find the Android SDK tools installed location (installed with VS 2017 15.7.4 and later) from the registry entry in console application (C#)
