### ISSUE TITLE
HttpClient has very large response time on Xamarin Android

### ISSUE THREAD

**Issue by ravikanasagra1** [xamarin/xamarin-android#1952]
### Steps to Reproduce

I have followed the article https://docs.microsoft.com/en-gb/xamarin/android/app-fundamentals/http-stack?tabs=macos to make Xamarin Android application support TLS 1.2

When I call rest service, It takes 10+ seconds from Xamarin Android while 2 seconds from Xamarin IOS project.

Both project uses same PCL HttpClient code to call same service.

**Code:**
```
HttpClient client = new HttpClient();
HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, restQuery);
response = await client.SendAsync(request);
string result = await response.Content.ReadAsStringAsync();
```

### Expected Behavior
HttpClient Get call should not take such long time.

### Actual Behavior
Line response = await client.SendAsync(request); takes considerable amount of time to execute as mentioned above.

### Version Information
Visual Studio For Mac - version - 7.5.2
Xamarin Android - version - 8.3.3.2
Target Android Framework  - 8.1
Device tested - Samsung Galaxy J7 Duo - Android 8.0
                        -  Nexus 5X - Android - Android 8.0

**Comment by jpobst** [comment]
This is likely obsolete as we have not had any recent reports on currently supported versions.
