### ISSUE TITLE
This is a suggestion about xamarin for visual studio

### ISSUE THREAD

**Issue by kamikyo** [xamarin/xamarin-android#1953]
Forgive me for submitting this as an issue to here.Because I don't know where the issue about xamarin for visual studio should be mentioned.

When I wrote these words, I was editing the Android UI using android studio (thanks for [Xamaridea](https://github.com/EgorBo/Xamaridea)).

I think many people in the community have the same feelings as me ([the same scene](https://forums.xamarin.com/discussion/39325/using-android-studio-for-axml-editing)).

Xamarin for visual studio has too many problems:
The xml schemas are old and axml intellisense is terrible;
The resource.desinger.cs update is slow;
Axml is severely stuck when it is saved, and sometimes it can even cause visual studio to crash;

These problems have reduced my development efficiency by half. I need to spend a lot of time waiting for visual studio (actually xamarin for visual studio).

I like xamarin, I like visual studio. So, even with android studio for development I have been restraining my impulse to use java for development.

Why can't xamarin get better?

If the development experience on visual studio can achieve the same development experience as android studio, I think that will be an epic enhancement for xamarin.android.

My development environment:
Windows 10
Visual studio 2017 15.7.5
Xamarin.visualstudio 4.10

**Comment by JonDouglas** [comment]
@kamikyo Thank you for your honest feedback, we really appreciate it.

We have recently revamped various areas in our android designer in the current 15.8 Preview. [**Have you had a chance to try it recently?**](https://visualstudio.microsoft.com/vs/preview/)

Here are a couple blogs outlining this work:

https://blogs.msdn.microsoft.com/visualstudio/2018/05/31/visual-studio-2017-version-15-8-preview-2/

https://blog.xamarin.com/future-xamarin-android-designer/

Regarding your concerns:

- The xml schemas are old and axml intellisense is terrible;

**Please try our 15.8 Preview 4 release and let us know if this experience has been improved!** Also any feedback you have regarding this experience as we want to continuously improve in this area.

- The resource.desinger.cs update is slow;

**Can you elaborate further? For example, can you walk me through a workflow and your observations on this?**

- Axml is severely stuck when it is saved, and sometimes it can even cause visual studio to crash;

**What happens when it's stuck? Can you no longer edit the file? Walk me through your last case that you had this happen to you so I can understand further.**

I look forward to hearing back!

**Comment by kamikyo** [comment]
@JonDouglas I am very excited to get your reply so quickly.

If, as you said, 15.8 Preview 4 improves development efficiency, I will try to find opportunities to use it.

Next I will describe how to reproduce the problems I mentioned before.

**The resource.desinger.cs update is slow**

Create an id resource in the layout, such as @+id/kamikyo, ctrl+s. Then use it in the activity right away, like this: Resource.Id.kamikyo. Next I will get an error: kamikyo is undefined. 

There are three different situations:

- > `public const int kamikyo=XXXXXX` is not in Resources\Resource.Designer.cs,but it exists in \obj\Debug\designtime\Resource.Designer.cs.

- > Contrary to the above, `public const int kamikyo=XXXXXX` is in Resources\Resource.Designer.cs, but \obj\Debug\designtime\Resource.Designer.cs does not exist.

- > There is no `public const kamikyo=XXXXXX` in both files.

I use any of the following actions to close this problem：

- > Repeat the rebuild project until there is no such error

- > Restart visual studio and rebuild the solution

- > Remove Resources\Resource.Designer.cs, [ctrl+s], then add it back to the project, rebuild projuect. This is the way I use the most, because it is relatively fast.

**Axml is severely stuck when it is saved, and sometimes it can even cause visual studio to crash**

1.This usually happens when visual studio uses more memory. 

_> How to make visual studio take up more memory, use **mono debugging for visual studio** several times. Because visual studio often reminds me to disable it to reduce the number of crashes._

2.Edit your axml file, then use [ctrl+s once], as mentioned above, this will not update Resource.designer.cs, and sometimes it will not save the axml file successfully (_you close it, then open it right away, you will find that your save is a failure_).So I am used to using [ctrl+s] several times in a row.

3.At this time, visual studio will prompt "waiting...", it takes about 5 seconds to recover. From now on, the same thing happens when you save any axml file multiple times.

Now you can understand what I mean by reducing the development efficiency by half.

The picture below is the hardware information of my computer：
![image](https://user-images.githubusercontent.com/7645337/42598423-bc247e20-858e-11e8-8651-b9c3e1b6f0aa.png)

I use visual studio for c/c++, asp.net/asp.net core, windows form/WPF, etc. on this computer. The development is very smooth and rapid.

Only developing xamarin disappoints me (not disappointing with xamarin technology, I really like xamarin).

In my country, visual studio is called "the strongest IDE in the universe." But in the android development, it really lost to android studio.

**Finally let me say it again: I like c#, I like xamarin.**

**Comment by softlion** [comment]
Please develop an "edit with Android Studio" action like you've done in VS Mac for xcode. I prefer to use Android Studio it's much much faster. And for now i uses the "Open in IDEA/Android Studio" visual studio extension.

**Comment by JonDouglas** [comment]
@kamikyo I've taken your feedback and put it on our backlog. Thank you so much for bringing this scenario to our attention. We will work to improve the new resource id experience to ensure you can work seamlessly between the android designer and code.

**Comment by JonDouglas** [comment]
@softlion Please feel free to create a new issue for this feature request. You can follow our guidelines here: https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#feature-requests

**Comment by JonDouglas** [comment]
@kamikyo For the scenario where your AXML is stuck when saved, can you let us know if you are using a property in your .csproj such as:

```
<AndroidUseManagedDesignTimeResourceGenerator>false</AndroidUseManagedDesignTimeResourceGenerator>
```

This opts your project out of the managed design parser which will use `aapt` instead which might explain the large hangs on saving. I have also included this on our backlog to improve this scenario.

**Comment by kamikyo** [comment]
@JonDouglas Thank you very much for your help, I will try this.
