### ISSUE TITLE
Design-Time Resource.designer.cs can get out of date

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#1956]
### Steps to Reproduce

1. File | New Project
2. Build
3. Change the default namespace on the project, update `MainActivity.cs` to use it
4. Build
5. I get Intellisense errors because `obj\Debug\designtime\Resource.designer.cs` does *not* have the new namespace!

I tried reproducing it with a test, but this passes:
```csharp
[Test]
public void DesignTimeResourceDesignerChangeNamespace ()
{
	const string namespaceA = "NamespaceA", namespaceB = "NamespaceB";
	var proj = new XamarinAndroidApplicationProject {
		RootNamespace = namespaceA
	};
	using (var b = CreateApkBuilder (Path.Combine ("temp", TestName))) {
		b.Target = "Compile";
		Assert.IsTrue (b.Build (proj, parameters: new [] { "DesignTimeBuild=True" }), "first DTB should have succeeded.");

		var designTimeResourceDesigner = b.Output.GetIntermediaryPath (Path.Combine ("designtime", "Resource.designer.cs"));
		FileAssert.Exists (designTimeResourceDesigner, "We should have a Design-Time Resource.designer.cs!");
		var contents = File.ReadAllText (designTimeResourceDesigner);
		StringAssert.Contains ($"[assembly: global::Android.Runtime.ResourceDesignerAttribute(\"{namespaceA}.Resource\", IsApplication=true)]", contents);
		StringAssert.Contains ($"namespace {namespaceA}", contents);

		//change the namespace
		proj.RootNamespace = namespaceB;
		proj.MainActivity = proj.DefaultMainActivity.Replace ("${ROOT_NAMESPACE}", namespaceB).Replace ("${PROJECT_NAME}", proj.ProjectName);
		proj.Touch ("MainActivity.cs");

		//Now a regular build
		b.Target = "Build";
		Assert.IsTrue (b.Build (proj), "first *regular* build should have succeeded.");
		var resourceDesigner = Path.Combine (Root, b.ProjectDirectory, "Resources", "Resource.designer.cs");
		FileAssert.Exists (resourceDesigner, "We should have a Resources/Resource.designer.cs!");
		contents = File.ReadAllText (resourceDesigner);
		StringAssert.Contains ($"[assembly: global::Android.Runtime.ResourceDesignerAttribute(\"{namespaceB}.Resource\", IsApplication=true)]", contents);
		StringAssert.Contains ($"namespace {namespaceB}", contents);

		//Back to DTB
		b.Target = "Compile";
		Assert.IsTrue (b.Build (proj, parameters: new [] { "DesignTimeBuild=True" }), "second DTB should have succeeded.");

		FileAssert.Exists (designTimeResourceDesigner, "We should have a Design-Time Resource.designer.cs!");
		contents = File.ReadAllText (designTimeResourceDesigner);
		StringAssert.Contains ($"[assembly: global::Android.Runtime.ResourceDesignerAttribute(\"{namespaceB}.Resource\", IsApplication=true)]", contents);
		StringAssert.Contains ($"namespace {namespaceB}", contents);
	}
}
```

So here is what I *think* is happening, but I'm not really sure:
* After step 4, a DTB doesn't occur, because a full build occurred?
* Should we overwrite the contents of `obj\Debug\designtime\Resource.designer.cs` when `Resources\Resource.designer.cs` is updated?

@dellis1972 thoughts?

### Expected Behavior

I shouldn't get Intellisense errors when changing namespace on a project.

### Actual Behavior

I get Intellisense errors when changing namespace on a project.

### Version Information

I used VS 2017 15.7.4 on Windows to reproduce this

**Comment by jonathanpeppers** [comment]
Looks like there is an issue in XamarinVS: http://work.devdiv.io/646514

Only question is if Xamarin.Android SDK needs to:

>Should we overwrite the contents of obj\Debug\designtime\Resource.designer.cs when Resources\Resource.designer.cs is updated?

**Comment by dellis1972** [comment]
Hmm. Not sure. This DTB stuff is a pain :(

I'm beginning to wonder if we should just use the managed parser to generate the designer and the id's for the resources. Then force `aapt` to use the id's we generate. That way we can just use the same designer file for DTB and normal builds

**Comment by jonpryor** [comment]
> Then force `aapt` to use the id's we generate.

How on earth do we do that?

If we *can* do that, it certainly sounds interesting...

**Comment by jonathanpeppers** [comment]
Since we already are leaving `$(IntermediateOutputPath)designtime` directory around during a `Clean` because it broke things, I suspect a regular build could also break things if it updated `designtime\Resource.designer.cs`.

See: https://github.com/xamarin/xamarin-android/commit/34a377456872b957b3e3a573075f88b7d4a7e1b8

I think the real fix here is the IDE needs to trigger a DTB on the property options page, and we shouldn't do anything here. Closing this for now.

The idea of using `--stable-ids` is a good one if it works. Maybe this should be an `Aapt2`-only feature, so it is hidden behind a feature flag?
