### ISSUE TITLE
xamarin.android.support.transition 27.0.2.1 fails to update through nuget

### ISSUE THREAD

**Issue by AndieH68** [xamarin/xamarin-android#1977]
### Steps to Reproduce

1. In visual studio , select Manage NugetPackages
2. Select Xamarin.Android.Support.Transation and click Update
3. Package fails to install  with NU3008: The package integrity check failed

Package Manager output
========== Start==========
Restoring packages for C:\Hydrop Mobile\Release\COMPASSFlushing\COMPASSFlushing\COMPASSFlushing.Android\COMPASSFlushing.Android.csproj...
  GET https://api.nuget.org/v3-flatcontainer/xamarin.android.support.transition/index.json
  OK https://api.nuget.org/v3-flatcontainer/xamarin.android.support.transition/index.json 1971ms
  GET https://api.nuget.org/v3-flatcontainer/xamarin.android.support.transition/27.0.2.1/xamarin.android.support.transition.27.0.2.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/xamarin.android.support.transition/27.0.2.1/xamarin.android.support.transition.27.0.2.1.nupkg 394ms
Installing Xamarin.Android.Support.Transition 27.0.2.1.
Signature Hash Algorithm: SHA256
NU3008: The package integrity check failed.
Signature type: Author
Timestamp: 12/06/2018 01:27:08

Verifying timestamp with timestamping service certificate: 
Subject Name: CN=Symantec SHA256 TimeStamping Signer - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
SHA1 hash: 625AEC3AE4EDA1D169C4EE909E85B3BBC61076D3
SHA256 hash: CF7AC17AD047ECD5FDC36822031B12D4EF078B6F2B4C5E6BA41F8FF2CF4BAD67
Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
Valid from: 02/01/2017 00:00:00 to 02/04/2028 00:59:59

Verifying signature with author certificate: 
Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
SHA1 hash: F404000FB11E61F446529981C7059A76C061631E
SHA256 hash: 3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE
Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Valid from: 26/02/2018 00:00:00 to 27/01/2021 12:00:00

Package restore failed. Rolling back package changes for 'COMPASSFlushing.Android'.
Time Elapsed: 00:00:11.2129517
========== Finished ==========

**Comment by jpobst** [comment]
This is likely obsolete as we have not had any recent reports on currently supported versions.
