### ISSUE TITLE
[AAPT2] Aapt2 does not handle values passed to `AndroidResgenExtraArgs`

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1985]
### Steps to Reproduce

1. Build app-acquaint with aapt2 enabled. This app sets the following property: `<AndroidResgenExtraArgs>--no-crunch </AndroidResgenExtraArgs>`

https://github.com/xamarinhq/app-acquaint

### Expected Behavior
I am not entirely sure if this _should_ be supported or not, however if this is an option only supported by `aapt` then perhaps we can try to improve the error message a bit (currently it prints the _entire_ usage messaging for aapt2.

### Actual Behavior

```
error APT0000: unknown option '--no-crunch'. "unknown option '--no-crunch'.". [/Users/xamarinqa/agent/_work/r1/a/app-acquaint/App/Acquaint.XForms/Acquaint.XForms.Droid/Acquaint.XForms.Droid.csproj]
```

### Version Information
XA version: 9.0.0.17 (HEAD/dfb09269d)

### Log File
http://xqa.blob.core.windows.net/gist/log-4ecc7c0748a842568aacb6df43bb7cab.txt

**Comment by dellis1972** [comment]
Aapt2 has completely different arguments, aapt ones are not supported. I
would say that is a totally valid error. But we should try to improve the
messaging.

**Comment by dellis1972** [comment]
PR up https://github.com/xamarin/xamarin-android/pull/2020.
