### ISSUE TITLE
XA0106 warnings in Xamarin.Forms/Android project

### ISSUE THREAD

**Issue by deakjahn** [xamarin/xamarin-android#1988]
### Steps to Reproduce

1. VS can be full of "Skipping .... Please check that your Nuget Package versions are compatible" warnings. This is supposed to be a XA0106 warning but it has no code, so it can't even be disabled in the project properties.
2. The project compiles without any problems but the hundreds of warnings make an awful lot of unwanted noise.

I know it might come with specific Nuget Packages installed but there is no way to identify which. Disabling them should work, though.

### Expected Behavior

A way to disable them.

### Version Information

XF: 3.1.0.583944 (I know there is a newer one but it breaks important things so can't be installed. Anyway, this has no bearing on this particular issue).
XA support libraries: 27.0.2.1

**Comment by ArrowCase** [comment]
Please fix these warnings so they can be suppressed.

**Comment by brendanzagaeski** [comment]
Thanks for this report, and apologies this issue didn't get a reply sooner!

By chance, these XA0106 warnings came up again in the context of the current Visual Studio 2019 version 16.2 Preview version, so I was looking into the story a bit more today. In short, I learned that there is already a way to suppress the warnings, but it isn't too well documented. To suppress the warnings, you can either:

  * Include `XA0106` in the `$(MSBuildWarningsAsMessages)` property in your
    *.csproj* file:

    ```xml
    <PropertyGroup>
        <MSBuildWarningsAsMessages>XA0106</MSBuildWarningsAsMessages>
    </PropertyGroup>
    ```

  * Or add the `-warnasmessage:XA0106` command line switch to the MSBuild invocation. This approach might be useful if you only need to suppress the warnings for command line builds on an automated build server, for example.

## Additional background info

One of the tricky things about the `$(MSBuildWarningsAsMessages)` property and `-warnasmessage` command line switch is that that they were only added to MSBuild within the last few years (first the [switch](https://github.com/microsoft/msbuild/commit/4287837b1b447905625593a926d60ab5e756e71d), and then [property](https://github.com/microsoft/msbuild/commit/01f99150e087634fd563af6fe557e0e8421ed6a5)). They also aren't yet mentioned in the MSBuild documentation on docs.microsoft.com, and there isn't currently a way to edit `$(MSBuildWarningsAsMessages)` in the Visual Studio property pages UI.

Another reason these settings are tricky is that they are *different* from the `$(NoWarn)` MSBuild property. `$(NoWarn)` is an older property that corresponds to the [**Build > Errors and warnings > Suppress warnings**](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings?view=vs-2019#suppress-specific-warnings-for-visual-c-or-f) setting in the Visual Studio property pages UI for C# projects. It is not used by the MSBuild logger directly. Instead, it gets passed into the C# compiler and NuGet restoration utility, allowing them to suppress warnings internally, before MSBuild sees them. Xamarin.Android could take a similar approach with the `$(NoWarn)` property to suppress warnings internally before MSBuild sees them, but it doesn't do that at the moment, and the `$(MSBuildWarningsAsMessages)` property now provides another solution.

One more potentially confusing detail to be aware of is that MSBuild offers [2 different names](https://github.com/microsoft/msbuild/blob/v16.0.461.62831/src/MSBuild/CommandLineSwitches.cs#L265) for the `-warnasmessage` command line switch. The second name is `-nowarn`, which *sounds* like it would match up with the older `$(NoWarn)` property, but they are actually *unrelated*. In fact, I just submitted <https://github.com/xamarin/xamarin-android/pull/3251> to correct a few places in the xamarin-android warning message docs where the Xamarin.Android team, myself included, got fooled by the naming and incorrectly mentioned `$(NoWarn)` when we should have mentioned `$(MSBuildWarningsAsMessages)` instead.
