### ISSUE TITLE
Application crash on startup - condition new_val < (1 << ABORT_PROT_BLOCK_BITS) not met

### ISSUE THREAD

**Issue by jamesmcroft** [xamarin/xamarin-android#1989]
This bug has been copied across from Bugzilla as a quick search isn't showing up any results here. The bug itself had been confirmed but hasn't been updated since October 2017.

As a quick overview, there appears to be an issue with getting passed application startup if Xamarin.Android app has a Resource.designer.cs file which is around 12MB in size. We confirmed this on Friday (7/20/2018) with one of our companies enterprise applications reaching this limit after adding new layouts. Temporarily, we have followed the advice of commenters in the original Bugzilla report to optimize the app's resources by removing unused ones and renaming some to be shorter which has given us about 2MB back but we will inevitably reach the limit again. 

Based on my native Android experience, I don't think this is a limitation of Android itself and is an issue with Mono / Xamarin

The original details from the bug can be found below. 

## condition new_val < (1 << ABORT_PROT_BLOCK_BITS) not met

_Submitted by a community member on 2017-06-09 13:56 UTC_

I just upgraded to Xamarin.Android 7.3.1.2 and my app is crashing on startup with the following error:

Assertion at /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mono/metadata/threads.c:266, condition 'new\_val \< (1 \<\< ABORT\_PROT\_BLOCK\_BITS)' not met

This was deployed to a device running Android 7.1.1

* * *

_Reference: <https://bugzilla.xamarin.com/show_bug.cgi?id=57320>_

**Comment by JonDouglas** [comment]
We believe this issue was resolved in Xamarin.Android 9.0 which contains Mono 5.12. Mono 5.12 does not seem to demonstrate this behavior. Please feel free to open up a new issue if you run into another problem! Thank you for the report!
