### ISSUE TITLE
Xamarin.Android Configuration

### ISSUE THREAD

**Issue by Fergroening** [xamarin/xamarin-android#1996]
Hi Everyone 

I have a Issue with my Xamarin, I'm New in this type of project, 

I create a new blank project, and open AXML to edit, my editor open in red and shows the following Photo 

Can you Help me 

Sorry form myu bad english 

![image](https://user-images.githubusercontent.com/41643166/43160143-9bf994b6-8f41-11e8-83da-3c52d749fd99.png)

> VS bug [#653462](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/653462)

**Comment by garuma** [comment]
Hey @Fergroening, can you share your logs (Help > Xamarin > Zip Logs) after reproducing the problem?

A common reason for those type of issues are either a build problem or potentially NuGet packages that haven't been restored properly (especially with the default templates)

**Comment by jpobst** [comment]
This issue is unlikely to be reproducible any longer.
