### ISSUE TITLE
Could not locate Java 6 or 7 SDK

### ISSUE THREAD

**Issue by Nemra1** [xamarin/xamarin-android#1999]
FRIST time fo used xamarin android and when i click bulid isee this msg
![2018-07-25_051450](https://user-images.githubusercontent.com/22897987/43203617-9cfb975a-8fd3-11e8-8b02-19e84b8dd82a.png)
and my sdks locations
![2018-07-25_051450](https://user-images.githubusercontent.com/22897987/43203643-a785094a-8fd3-11e8-869e-e97f11385cea.png)
any help?

**Comment by atsushieno** [comment]
Did you attach a wrong image for the first screenshot?

**Comment by JonDouglas** [comment]
@Nemra1 Android currently supports JDK 1.8 at the highest. JDK 10 will put you in an unsupported scenario. You can either download Oracle JDK 1.8 online and use that path, or try our [Preview of OpenJDK](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk)
