### ISSUE TITLE
Obfuscated library binding errors for class names with multiple (>2) lower case characters

### ISSUE THREAD

**Issue by awattar** [xamarin/xamarin-android#2003]
### Steps to Reproduce

1. Bind obfuscated AAR/JAR with random multiple (>2) lower case characters class names.

For example jfh, hdjdh, etc.

### Expected Behavior

According to documentation: [https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/troubleshooting-bindings/](url) 

> Classes that have characteristics of obfuscation – Characteristics of obfuscated classes include:
> 
> The class name includes a $, i.e. a$.class
> The class name is entirely compromised of lower case characters, i.e. a.class

all of the above should be treated as obfuscated by Binding Generator but it works only for classes with one or two lower case letter names or only starting with a, b ... aa, ab.

### Actual Behavior

It seems that only one or two letter lower case names are treated as obfuscated by default i.e. a, b, aa, bb.

Binding Generator should automatically mark all lower case classes as obfuscated no matter how long their names are.

### Version Information

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.5.4 (build 3)
Installation UUID: fc295dbb-ea60-45ea-a7bd-051b091fe655
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Enterprise)
Android SDK: /Users/mwesolowski/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Enterprise)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705040003
Git revision: 6ae731889c896d6733efb8ff5117f5bf5b17b509
Build date: 2018-07-19 13:07:45-04
Xamarin addins: 417fed09624e1e1f76ab0a11e8b97ffd8bbf91e1
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5

**Comment by JonDouglas** [comment]
Hi @awattar 

For us to investigate this issue further, can you please add a reproduction project demonstrating the issue? For more information on what other items we look for in a bug report, see the following wiki article on [Bug Reports](https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#bug-reports).

Thanks for filing an issue! We look forward to hearing back from you.

**Comment by atsushieno** [comment]
It is actually the expected behavior. Technically there is no way to determine whether a class is an "obfuscated" one or not. We shouldn't be too false negative. You can manually apply "obfuscated" attribute, setting "true" to wherever you want to apply e.g.

`<attr path="/api/*/method[string-length(@name) <= 3]" name="obfuscated">true</attr>`.

**Comment by atsushieno** [comment]
Basically our tooling works based on common sense. Our premise is that libraries with more than 676 classes are not very nice to support.

We don't special case '$' and no plan to add possibly-breaking change.

You can explicitly mark some methods whose name are of only 3-letters-or-less by another metadata fixup: `<attr path="(path/to/method)" name="obfuscated">false</attr>` after my previous example metadata fixup above, or use XPath `not(contains(@name, 'A')) and not (contains (@name, 'B')) and ...` to 'Z' (I don't like this though).

**Comment by awattar** [comment]
@atsushieno That makes sense.

Could you do one more thing for me?

The first fixup contains '<' that throws error during build - &lt; doesn't help also - is there another way to write this?

**Comment by atsushieno** [comment]
oops, sorry, it should be `&lt;= 3` instead of `<= 3` !

**Comment by awattar** [comment]
Thanks.

**Comment by awattar** [comment]
@atsushieno Will this rule work for nested classes? It seems to work only for top ancestor and reports several warnings like:

> warning BG8604: top ancestor mpmwe not found for nested type Com.XXX.YYY.Mpmwe.Tqsed.

**Comment by atsushieno** [comment]
Of course it won't work because `string-length` XPath function is checking only string length. The use of XPath 1.0 is really standard compliant and you could construct your own XPath expression to filter what you want.

**Comment by awattar** [comment]
Thanks for the quick answer! I've already written our expression but it seems I was wrong about how it works with nested ones.

**Comment by awattar** [comment]
Basically, the main difficulty here was that nested classes are not always being generated as nested in api.xml after top ancestor is marked as obfuscated but they are generated on the same level with name like “anc.chil” where anc in ancestor name and chil is child name. Writing rule that will handle all children of top ancestor obfuscated class is rather difficult in this circumstances. Fortunately, we were able to overcome this by writing tulle that should catch all names equal or longer 3, starting with lower-name character and containing dot.
