### ISSUE TITLE
Xamarin Android Linux build job failing for past two and a half months

### ISSUE THREAD

**Issue by NatElkins** [xamarin/xamarin-android#2009]
### Steps to Reproduce

Navigate to https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/ .  See failed builds.

### Expected Behavior

Builds succeed.

### Actual Behavior

Build hasn't succeeded for a long time.

### Version Information

N/A

### Log File

https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/1151/consoleFull

**Comment by NatElkins** [comment]
If someone could point me in the general direction of what's wrong I'll try taking a crack at this.

**Comment by mungojam** [comment]
Seems like the builds had been working, but are now failing again. The last successful one is from 4 months ago:

https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/lastSuccessfulBuild/Azure

**Comment by mrk-han** [comment]
Bump, it has now been 6 months since the last passing build. 

All of the new and proposed pipelines from https://github.com/xamarin/xamarin-android/pull/2838 are failing

**Comment by eman1986** [comment]
still failing, I can use version 9 but I'd really like to use 10 to match my windows machine
