### ISSUE TITLE
IntelliSense has an error when ItemGroup link AndroidResource

### ISSUE THREAD

**Issue by AigioL** [xamarin/xamarin-android#2011]
### Steps to Reproduce

1. Edit the .csproj file
2. Add xml node
```
<ItemGroup>
  <AndroidResource Include="..\..\android_studio_project\app\src\main\res\layout\activity_main.xml">
    <Link>Resources\layout\activity_main.xml</Link>
  </AndroidResource>
<ItemGroup>
```
3. [project.zip](https://github.com/xamarin/xamarin-android/files/2238466/project.zip)

### Expected Behavior
![expected_behavior](https://user-images.githubusercontent.com/24450093/43362418-3ae61738-931c-11e8-82bd-51a2379eac4d.png)

### Actual Behavior
![actual_behavior](https://user-images.githubusercontent.com/24450093/43362424-4b164c0e-931c-11e8-8e53-671083fa9988.png)

### Version Information

Visual Studio 15.7.5
Xamarin   4.10.10.2 (35a01d8dc)
Xamarin Designer   4.12.1 (f3257e429)
Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)

Visual Studio 15.8.0 Preview 5.0
Xamarin   4.11.0.731 (d15-8@1b61b3b4e)
Xamarin Designer   4.14.218 (79f535bdd)
Xamarin Templates   1.1.104 (12ebed1)
Xamarin.Android SDK   9.0.0.17 (HEAD/dfb09269d)

**Comment by jpobst** [comment]
This issue likely occurs in the Android Designer, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
