### ISSUE TITLE
Localized satellite packages are not included in build output when using PackageReference

### ISSUE THREAD

**Issue by jassmith** [xamarin/xamarin-android#2012]
_From @domyd on July 24, 2018 10:50_

### Description

[Localized satellite packages](https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages#localized-satellite-packages) do not seem to work in a Xamarin app when using the PackageReference restore method. 

Likely related: https://github.com/Humanizr/Humanizer/issues/380

### Steps to Reproduce

Repro project: [SatelliteAssemblyApp.zip](https://github.com/xamarin/Xamarin.Forms/files/2223193/SatelliteAssemblyApp.zip). It's a git project with two additional branches: (*Note: the referenced test nuget packages are included in `/localpackages` and restoring them should just work*)

- Branch `works-single-package` references one single NuGet package (`SatelliteAssemblyTest.1.0.0`) that includes the main assembly and one localized resource DLL.
- Branch `doesnt-work-multiple-packages` references two NuGet packages: `SatelliteAssemblyTest.1.0.1` (which only has the main assembly) and `SatelliteAssemblyTest.de.1.0.1` (which only contains the localized resource DLL).

1) Build solution in Release mode
2) Archive Android project to get an APK

### Expected Behavior
The localized resource DLLs are included in the APK in both cases (`/assemblies/de/SatelliteAssemblyTest.resources.dll` exists within the APK). On a device with German culture, the label on the main page should say "Deutsch" in both cases.

Expected APK: [works-single-package.zip](https://github.com/xamarin/Xamarin.Forms/files/2223194/works-single-package.zip)

### Actual Behavior
The localized resources are missing in the case of split nuget packages (`/assemblies/de` doesn't exist within the APK). On a device with German culture, the label on the main page says "English".

Actual APK: [doesnt-work-multiple-packages.zip](https://github.com/xamarin/Xamarin.Forms/files/2223195/doesnt-work-multiple-packages.zip)

### Basic Information

- Version with issue: 3.0.0.561731
- Last known good version: not tested
- IDE: VS 2017 (v15.7.5)
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 27.0.2
- Nuget Packages: none, except the test package(s)

_Copied from original issue: xamarin/Xamarin.Forms#3386_

**Comment by cassionandi** [comment]
Any workarounds on this?

**Comment by xalikoutis** [comment]
Hi Guys any progress on this?

**Comment by jemunk** [comment]
This is still an issue! Any progress? Any workarounds?

**Comment by smoogipoo** [comment]
Any updates or workarounds for this issue?

**Comment by onovotny** [comment]
Ping? We're still getting reports of this: 

https://twitter.com/lastexitcode/status/1175392618022408192

**Comment by xalikoutis** [comment]
moved to flutter

**Comment by ChaseFlorell** [comment]
Can we open a sister issue on the iOS side of things? Where would it go?

**Comment by souchprod** [comment]
No idea for a solution ? That's really problematic

**Comment by cemrich** [comment]
This issue prevents [Humanizer](https://github.com/Humanizr/Humanizer) from being used in localized Xamarin projects (see https://github.com/Humanizr/Humanizer/issues/799). This is especially problematic, as Humanizer is described as compatible to Xamarin and this issue does only starts to appear when non english translation are added later on in the development process.

**Comment by cemrich** [comment]
Thank you very much for looking into this!

> It appears that this is going to "just work" in .NET 6.

Does this mean this issue will not be resolved until .NET 6 is ready to use?

**Comment by jonathanpeppers** [comment]
@cemrich I'm unsure about setting `$(NuGetRuntimeIdentifier)` and `$(RuntimeIdentifiers)` in "legacy" MSBuild projects to workaround NuGet. It doesn't feel quite right...

I will need to do more research.

**Comment by cemrich** [comment]
I worked around this issue by referencing the Humanizer dlls directly from my head projects and the shared project. I placed the dlls inside a separate project directory with following structure:

```
Humanizer.dll
de/Humanizer.resources.dll
```
I have not yet tested this solution for more than one localization package.

**Comment by tranb3r** [comment]
So, is it going to be fixed or not ?

**Comment by jonathanpeppers** [comment]
This issue is from 2018, I would follow the new one for updates on this: https://github.com/dotnet/maui/issues/4470
