### ISSUE TITLE
Getting SIGABRT 6 in Android when running http calls in parallel

### ISSUE THREAD

**Issue by jassmith** [xamarin/xamarin-android#2013]
_From @tsequeira-vhs on July 27, 2018 14:32_

### Description
We have a Xamarin.Forms app which is crashing with '**signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr -------- java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x3ce2**'

We are running multiple calls to web services with HttpClient in parallel using Task.WhenAll()

The crash is random and due to this we are unable to identify the root cause.

### Steps to Reproduce
1. Login (first time)
2. Set pin code (first time)
3. Enter pin code (from second time)
4. Launches a page with blue header
5. If no crash, kill the app and repeat steps from 3.

Note: To make the crash more frequent enable gref logging using the following ADB command: '**adb shell setprop debug.mono.log gref**'

### Expected Behavior
The app should not crash

### Actual Behavior
App crashes with '**java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x3ce2**'

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017 Enterprise
- Platform Target Frameworks:
  - Android: 8.1 
- Android Support Library Version: API 27
- Affected Devices: Tested on Pixel 2 and Samsung S8

### Logs
[ReportLog-1.txt](https://github.com/xamarin/Xamarin.Forms/files/2236090/ReportLog-1.txt)
[ReportLog-2.txt](https://github.com/xamarin/Xamarin.Forms/files/2236091/ReportLog-2.txt)

_Copied from original issue: xamarin/Xamarin.Forms#3421_

**Comment by jassmith** [comment]
_From @tsequeira-vhs on July 27, 2018 14:43_

We have attached stripped down version of the code. 
[EngageDummy.zip](https://github.com/xamarin/Xamarin.Forms/files/2236134/EngageDummy.zip)

**Comment by elacca** [comment]
We are having the same issue when sending parallel async http calls:

05-06 12:40:24.845 W/zygote  (11296): JNI WARNING: DeleteGlobalRef(0x5fe2) failed to find entry
05-06 12:40:24.845 E/zygote  (11296): JNI ERROR (app bug): accessed deleted Global 0x5fe2
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x5fe2
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504] "Thread-147" prio=10 tid=37 Runnable
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x131c13b8 self=0xde741800
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   | sysTid=12928 nice=-10 cgrp=default sched=0/0 handle=0xbcfae970
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   | state=R schedstat=( 0 0 0 ) utm=79 stm=41 core=5 HZ=100
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   | stack=0xbceb0000-0xbceb2000 stackSize=1022KB
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   | held mutexes= "mutator lock"(shared held)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #00 pc 002c5dcf  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+130)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #01 pc 00358023  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+202)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #02 pc 00354507  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+34)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #03 pc 002308ad  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+736)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #04 pc 00230d17  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #05 pc 0035bf2d  /system/lib/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+292)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #06 pc 000d1d05  /system/lib/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+64)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #07 pc 000d1315  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+220)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #08 pc 000d0b69  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+600)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #09 pc 000d36d3  /system/lib/libart.so (_ZN3art8CheckJNI9DeleteRefEPKcP7_JNIEnvP8_jobjectNS_15IndirectRefKindE+450)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   native: #10 pc 000108f8   (???)
05-06 12:40:24.929 F/zygote  (11296): java_vm_ext.cc:504]   (no managed stack frames)

**Comment by elacca** [comment]
I had the same issue. At my case the problem was coming from the SecureStorage, which I was accessing async to get a Token from it, before each HTTP request. After eliminating this part, the parallel HTTP calls are working flawlessly.
