### ISSUE TITLE
*Profiled* `jnimarshal-gen`

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#2021]
Add feature to generate marshal methods just for given subset of types. (similar to `-t` option) This way we can, for example, speedup just the types used  during the startup or during most common run of the application.

That would reduce the size, while still speeding up the parts we need.

**Comment by grendello** [comment]
`jnimarshalmethods-gen` was superseded by marshal methods (commit 8bc7a3e84f95e70fe12790ac31ecd97957771cb2 and others)
