### ISSUE TITLE
Aapt2 & AndroidResgenExtraArgs compatibility

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#2029]
Context: https://xamarinhq.slack.com/archives/C03CEGRUW/p1533163680000177
Context: https://github.com/xamarin/xamarin-android/pull/2020#issuecomment-409719046

As the [Xamarin.Android.Support.Vector.Drawable](https://www.nuget.org/packages/Xamarin.Android.Support.Vector.Drawable/27.0.2.1) NuGet package overrides `$(AndroidResgenExtraArgs)` and won't override the related `aapt2` properties -- because they don't yet exist in any usable form -- there is a concern that any existing projects which use the Xamarin.Android.Support.Vector.Drawable package *and* enable aapt2 may suffer a build failure.

Possible (hackish?) workaround: update the `<Aapt2Link/>` (`<Aapt2Compile/>`?) target so that it *also* accepts `$(AndroidResgenExtraArgs)`, and does something like:

```csharp
if (AndroidResgenExtraArgs.Contains ("--no-version-vectors"))
    ExtraArgs += " --no-version-vectors";
```

**Comment by dellis1972** [comment]
Or better

```
<PropertyGroup>
   <AndroidAap2LinkExtraArgs Condition=" '$(_AndroidUseAapt2)' == 'True' And $(AndroidResgenExtraArgs.Contains('--no-version-vectors')) And !($(AndroidAap2LinkExtraArgs.Contains('--no-version-vectors'))) ">--no-version-vectors</AndroidAap2LinkExtraArgs>
</PropertyGroup>
```

**Comment by dellis1972** [comment]
PR up https://github.com/xamarin/xamarin-android/pull/2032
