### ISSUE TITLE
Encountering 'error MSB4044: The "InstallPackageAssemblies" task was not given a value for the required parameter "TargetFrameworkVersion"' against d15-9

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2039]
I'm hitting an issue with `InstallPackageAssemblies` on both Mac and Windows during certain in IDE and from command line installation attempts.

### Steps to Reproduce

1. Download or clone https://github.com/xamarin/monodroid-samples/tree/master/android5.0/Cheesesquare
2. nuget.exe restore monodroid-samples\android5.0\Cheesesquare\Cheesesquare.sln
3. msbuild /t:Install monodroid-samples\android5.0\Cheesesquare\Cheesesquare.csproj

### Expected Behavior
Installation succeeds

### Actual Behavior
Installation fails with 
>   C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.Debugging.targets(479,2): error MSB4044: The "InstallPackageAssemblies" task was not given a value for the required parameter "TargetFrameworkVersion".

### Version Information
Xamarin.Android SDK   9.1.0.5 (HEAD/ed37b5cd7)
https://gist.github.com/pjcollins/7c21e5597eaf15824b49d407538a20df

### Log File
https://gist.githubusercontent.com/pjcollins/a26d0fde1c7c6338bbea7ff955974d1d/raw/c8dcd43cee65e0962948283fc6dcff2bc595ad0a/gistfile1.txt

> VS bug [#659689](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/659689)

**Comment by jonpryor** [comment]
Should be fixed in https://github.com/xamarin/monodroid/commit/cb575e4b5f6a6639a77c032fc3ce95e7cb2dcf42
