### ISSUE TITLE
RecyclerView SpanSizeLookup performance issues with a large data set

### ISSUE THREAD

**Issue by Petiephant** [xamarin/xamarin-android#2044]
### Background

[Xamarin Forum Thread](https://forums.xamarin.com/discussion/129533/recyclerview-spansizelookup-horrible-performance-with-a-large-data-set)

### Steps to Reproduce

1. Build and Run - [XamarinCode.zip](https://github.com/xamarin/xamarin-android/files/2267711/XamarinCode.zip) (basic example, please read the comments in the code)
2. Start scrolling through the list
3. Notice the slowness/stuttering/jank

### Expected Behavior

You are able to comfortably scroll smoothly up and down the whole list.

The native java version seems to run fine on my device (Nexus 5, v6.0.1) - [JavaCode.zip](https://github.com/xamarin/xamarin-android/files/2267712/JavaCode.zip)
See here - [JavaScreenRecord.mp4](https://drive.google.com/file/d/1snrFNOSs5qavor-jz4SewKki1wrxvj2D/view?usp=sharing)

### Actual Behavior

Slowness/stuttering/jank when scrolling through the list. This is with a basic SpanSizeLookup that returns 1 (my custom implementation is obviously different). However, even using the default GridLayoutManager.DefaultSpanSizeLookup, things run nice and fast/smooth, but with a basic custom version, things are super slow.

See here - [XamarinScreenRecord.mp4](https://drive.google.com/file/d/1FvWZIOdrUu_TZM07dEhLudBjCfe2xFzD/view?usp=sharing)

Profiling this shows it's because of getSpanSize. It's seem to be called (unnecessarily?) thousands upon thousands of times whenever you scroll the list.

![xamarinprofiler](https://user-images.githubusercontent.com/42078613/43796674-d3a41076-9a7c-11e8-9983-ebb7fdaee220.png)

### Version Information

[VisualStudio.txt](https://github.com/xamarin/xamarin-android/files/2267770/VisualStudio.txt)

**Comment by Petiephant** [comment]
Any chance this could get looked at please? This is a big issue in certain parts of my app, especially for those with a slower CPU. Thanks.

**Comment by MagneticLlama** [comment]
The problem is you're not also overriding GetSpanIndex. The DefaultSpanSizeLookup is essentially this

```C#
public class DefaultSpanSizeLookup : GridLayoutManager.SpanSizeLookup
{
   public int GetSpanSize(int position) 
   {
      return 1;
   }

   public int GetSpanIndex(int position, int spanCount) 
   {
      return position % spanCount;
   }
}
```

If you override GetSpanIndex with the same value, you'll get the same performance as if you used DefaultSpanSizeLookup.
