### ISSUE TITLE
[AAPT2] Encountering build errors due to missing Resource.* fields which aren't actually missing when aapt2 is enabled

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2047]
I've got a handful of projects which are failing during CoreCompile due to Resource related errors when enabling aapt2. These errors appear to be falsely reported however, and don't occur when using aapt. There is also perhaps some relation with the issue described in #1983.

### Steps to Reproduce

1. Build [ApiDemo](https://github.com/xamarin/monodroid-samples/tree/master/ApiDemo) and/or any of the other 4 projects shown in the "Actual Behavior" section with aapt2 enabled.

### Expected Behavior
These projects should build successfully with aapt2 enabled.

### Actual Behavior
http://xqa.blob.core.windows.net/gist/report-3c94cd9125164b8c89c5b1dafc5fab60.txt

```
  Activities/LoggingActivity.cs(122,46): error CS0117: 'Resource.Id' does not contain a definition for 'scrollview' [/Users/xamarinqa/myagent/_work/r5/a/monodroid-samples/android-n/MultiWindowPlayground/MultiWindowPlayground/MultiWindowPlayground.csproj]
```

http://xqa.blob.core.windows.net/gist/report-1e247c7717ac496891b088764c29eddc.txt
```
  View/ContentBrowserActivity.cs(155,41): error CS0117: 'Resource.Id' does not contain a definition for 'seekbar' [/Users/xamarinqa/myagent/_work/r5/a/monodroid-samples/ApiDemo/ApiDemo.csproj]
  View/ContentBrowserNavActivity.cs(158,41): error CS0117: 'Resource.Id' does not contain a definition for 'seekbar' [/Users/xamarinqa/myagent/_work/r5/a/monodroid-samples/ApiDemo/ApiDemo.csproj]
```
http://xqa.blob.core.windows.net/gist/report-85670af60ea046d48d66409f4442f0ee.txt

```
  MainActivity.cs(24,44): error CS0117: 'Resource.Layout' does not contain a definition for 'Main' [/Users/xamarinqa/myagent/_work/r5/a/monodroid-samples/Firebase/FCMNotifications/FCMNotifications/FCMNotifications.csproj]
  MainActivity.cs(25,58): error CS0117: 'Resource.Id' does not contain a definition for 'msgText' [/Users/xamarinqa/myagent/_work/r5/a/monodroid-samples/Firebase/FCMNotifications/FCMNotifications/FCMNotifications.csproj]
  MainActivity.cs(42,67): error CS0117: 'Resource.Id' does not contain a definition for 'logTokenButton' [/Users/xamarinqa/myagent/_work/r5/a/monodroid-samples/Firebase/FCMNotifications/FCMNotifications/FCMNotifications.csproj]
  MainActivity.cs(44,68): error CS0117: 'Resource.Id' does not contain a definition for 'subscribeButton' [/Users/xamarinqa/myagent/_work/r5/a/monodroid-samples/Firebase/FCMNotifications/FCMNotifications/FCMNotifications.csproj]
  MyFirebaseMessagingService.cs(41,71): error CS0117: 'Resource.Drawable' does not contain a definition for 'ic_stat_ic_notification' [/Users/xamarinqa/myagent/_work/r5/a/monodroid-samples/Firebase/FCMNotifications/FCMNotifications/FCMNotifications.csproj]
```

http://xqa.blob.core.windows.net/gist/report-827877f595704e708224b2a8802d0c53.txt

```
  MainActivity.cs(60,58): error CS0117: 'Resource.Id' does not contain a definition for 'alt' [/Users/xamarinqa/myagent/_work/r5/a/mobile-samples/BackgroundLocationDemo/location.Android/Location.Droid.csproj]
```

http://xqa.blob.core.windows.net/gist/report-aee90b21f9e440108a605cd8dac73567.txt
```
  MainActivity.cs(15,49): error CS0117: 'Resource.Layout' does not contain a definition for 'Tabbar' [/Users/xamarinqa/myagent/_work/r5/a/xamarin-forms-samples/WebServices/TodoAzurePush/Droid/TodoAzure.Droid.csproj]
  MainActivity.cs(16,47): error CS0117: 'Resource.Layout' does not contain a definition for 'Toolbar' [/Users/xamarinqa/myagent/_work/r5/a/xamarin-forms-samples/WebServices/TodoAzurePush/Droid/TodoAzure.Droid.csproj]
  Services/FirebaseNotificationService.cs(36,49): error CS0117: 'Resource.Drawable' does not contain a definition for 'ic_stat_ic_notification' [/Users/xamarinqa/myagent/_work/r5/a/xamarin-forms-samples/WebServices/TodoAzurePush/Droid/TodoAzure.Droid.csproj]
```

### Version Information
xamarin-android/d15-9

> VS bug [#660872](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/660872)

**Comment by dellis1972** [comment]
So looking at the `ApiDemo` issue.. we have this problem

`Resources/layout/animation_seeking.xml` has a item with id = `android:id="@+id/seekBar"`
`Resources/layout/content_browser.xml` has id = `android:id="@+id/seekbar"`
`Resources/layout/content_browser_nav.xml` has id = `android:id="@+id/seekbar"`

the old system ended up with both `seekbar` AND `seekBar` in the resource designer. 

This is confirmed by looking  at the `R.txt` which has

```
int id seekBar 0x7f08018e
int id seekbar 0x7f08018f
```

Our `ManagedResourceParser` does NOT allow for items with different casing [1]. As a result the first item it comes across will win. Which means the code using the other casing will fail. 
I will try to make the `Parser` case sensitive and see what that breaks.

[1] https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs#L324

**Comment by dellis1972** [comment]
PR #2058 is up

**Comment by pjcollins** [comment]
@dellis1972 sorry for the late update here but it appears that this issue is still occurring for the following two projects when using `monodroid/d15-9/818caf678/Xamarin.Android.Sdk.9.1.0.32.vsix`

* https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoAzurePush/Droid 
     * http://xqa.blob.core.windows.net/gist/report-4ccea7990490456e978beb75c63f563c.txt

---
* https://github.com/xamarin/monodroid-samples/tree/master/Firebase/FCMNotifications
    * http://xqa.blob.core.windows.net/gist/report-a6a75b0228ef407191ae9d26907fcfa3.txt

**Comment by dellis1972** [comment]
@pjcollins hmm. Just tested this on master and the TodoAzurePush sample works.... :/

**Comment by pjcollins** [comment]
@dellis1972 I just tested this locally against monodroid/master/6b8f18a24 (9.1.199.5) and am still able to reproduce the errors in the two samples mentioned above, although I am on Windows. Did you manage to try the Firebase sample as well?

[Binary and diagnostic logs](https://github.com/xamarin/xamarin-android/files/2470502/logs.zip)

**Comment by dellis1972** [comment]
@pjcollins the problem is https://github.com/xamarin/xamarin-android/commit/960f32c5d70d6a47b41856a70472255a426abf76 

We are too late for a d15-9 cp now are we not?

**Comment by dellis1972** [comment]
So the problem is the google play stuff is causing the main `compiled.flata` archive to NOT be created. As a result it will be missing a ton of resources. The commit 960f32c fixes all of that.

**Comment by pjcollins** [comment]
@dellis1972 oh ok thanks, it looks like this one was CP'd to d15-9 (https://github.com/xamarin/xamarin-android/commit/9102a474c2e10141b2e9708e42596420a02f45d6)  so I'll have to wait for a new build. Marking as resolved for now.

**Comment by pjcollins** [comment]
This is resolved on both windows and macos in D15-9 Preview 4 👍

**Comment by pfedotovsky** [comment]
When this fix will be released?
