### ISSUE TITLE
Need to review our mechanism for ensuring API compatibility

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#2068]
I'm starting to doubt the reliability of our API compatibility infrastructure which uses `mono-api-info.exe`, `mono-api-html.exe`, and the xamarin-android-api-compatibility repo.

What do the mono and corefx repo's do to ensure API compatibility?

Should we do what they do?

**Comment by jpobst** [comment]
This has been replaced with `ApiCompat` from the `dotnet` repo.

https://github.com/xamarin/xamarin-android/pull/3884
