### ISSUE TITLE
XamarinShellPackage package did not load correctly after updating VS to 15.8 or 15.8.1 from 15.7

### ISSUE THREAD

**Issue by allenliu1030** [xamarin/xamarin-android#2085]
This is Allen from APGC Xamarin support team. I am filing this issue for my customer and I finished remote session with him, the issue does exist and not only one customer is having the issue.

My customer's Windows version is Windows 8.1 with version 6.3. And the issue happened after updating VS2017 from 15.7 to 15.8.

The symptom is that the Xamarin components are totally broken, we cannot load the settings from Tools => Options => Xamarin. And each time we click on it, we will get something as below:

"XamarinShellPackage" package did not load correctly. Find the detail information from: "C:\Users\xxx\AppData\Roaming\Microsoft\VisualStudio\15.0_xxxx\ActivityLog.xml".

Please find me for the ActivityLog.xml file if needed. However, customer has tried repair VS, clean install VS.
Also, I did lots of research, I helped to try disable all the VS extensions, clear the ComponentModelCache, none of the things works for this case.

I found some information from the ActivityLog.xml file as below:

```XML
<entry>
<record>543</record>
<time>2018/08/18 23:03:56.718</time>
<type>Error</type>
<source>VisualStudio</source>
<description>LegacySitePackage failed for package [XamarinShellPackage]Source: &apos;Microsoft.VisualStudio.Composition&apos; Description: Expected 1 export(s) with contract name &quot;Clide.IDevEnv&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name &quot;Clide.IDevEnv&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A; at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)&#x000D;&#x000A; at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)&#x000D;&#x000A; at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)&#x000D;&#x000A; at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)&#x000D;&#x000A; at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()&#x000D;&#x000A; at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()&#x000D;&#x000A; at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()&#x000D;&#x000A; at Clide.DevEnv.Get(IServiceProvider serviceProvider) in D:\a\1\s\src\Clide.Interfaces\DevEnv.cs:line 12&#x000D;&#x000A; at Xamarin.VisualStudio.TastyPackage.Initialize() in E:\A_work\53\s\src\Core\VisualStudio\FlavorProject\TastyPackage.cs:line 116&#x000D;&#x000A; at Xamarin.VisualStudio.Shell.XamarinShellPackage.Initialize() in E:\A_work\53\s\src\Core\VisualStudio.Shell\XamarinShellPackage.cs:line 67&#x000D;&#x000A; at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
<guid>{2D510815-1C4E-4210-BD82-3D9D2C56C140}</guid>
<hr>80131500</hr>
<errorinfo></errorinfo>
</entry>
```

Please let me know whether you guys need anymore information from customer, I can also engage customer in here to follow up.

Please help to resolve the issue asap because this is critical for my customer. This issue totally blocked his development progress.

Thanks.
Allen

**Comment by JonDouglas** [comment]
This is a Xamarin for Visual Studio issue and has already been reported here:

https://developercommunity.visualstudio.com/content/problem/312602/after-updating-vs-2017-to-1580-error-when-opening.html

Thus I am closing this issue as it does not pertain to the Xamarin.Android SDK.
