### ISSUE TITLE
Try/Catch not working as expected on initial load of activity

### ISSUE THREAD

**Issue by JRE-6783** [xamarin/xamarin-android#2086]
### Steps to Reproduce

If you successfully load/create an activity, any subsequent unhandled exception is confined only to that activity – you get a stopped working dialog, but the previous activity(s) remain functional. However if you put an unhandled exception in the create method of an activity, and handle the exception form the calling activity (from the StartActivity method, not only does it crash the called activity, but it crashes the calling activity. In the example, trying to load activity three, should remain on activity 2, as activity 2 is handling the load of activity 3 with a try/catch, however it returns to activity 1. The ‘crash’ button is just there to confirm the normal operation of an unhandled operation from a fully loaded activity.

Moreover, the app should crash when the exception is unhandled (when the message 'unfortunately, appname has stopped' has displayed), however it does not.  It just 'crashes' the activity.  Any activity not affected by the unhandled activity (notwithstanding the above issue) remains alive.  This can cause its own set of unexpected behaviors.

[ActiviyCrashTest.zip](https://github.com/xamarin/xamarin-android/files/2306882/ActiviyCrashTest.zip)

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
