### ISSUE TITLE
GeneratedOutputPath is wrong when using the new csproj format in an Android Binding

### ISSUE THREAD

**Issue by benventive** [xamarin/xamarin-android#2090]
### Steps to Reproduce

1. Open the provided solution
2. Build
3. Observe the resulting DLL with a tool like ILSpy

[TestBinding.zip](https://github.com/xamarin/xamarin-android/files/2307964/TestBinding.zip)

### Expected Behavior
The DLL contains all the generated code
### Actual Behavior
The DLL only contains a ZIP (I assume that this is the AAR)
### Version Information
Microsoft Visual Studio Professional 2017 Preview
Version 15.9.0 Preview 1.0
VisualStudio.15.Preview/15.9.0-pre.1.0+28016.0
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Professional

Xamarin   4.12.1.40 (d15-9@5718a2094)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   9.1.0.12 (HEAD/f8e8e5ca4)
Xamarin.Android Reference Assemblies and MSBuild support.

### More
Adding `<GeneratedOutputPath>obj\$(Configuration)\$(TargetFramework)\generated\</GeneratedOutputPath>` to the project's PropertyGroup fixes the issue

**Comment by jonathanpeppers** [comment]
Hmm, I can't imagine this working currently:
```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>monoandroid80</TargetFramework>
		<TargetFrameworkVersion>v8.0</TargetFrameworkVersion>
		<OutputPath>bin/$(Configuration)/$(TargetFramework)</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<LibraryProjectZip Include="Jars/intercom-sdk-base-4.1.9.aar" />
	</ItemGroup>

	<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.Bindings.targets" />
</Project>
```

SDK-style projects are on the roadmap, so I'll leave this open, thanks!

**Comment by benventive** [comment]
@jonathanpeppers It does work! We use it in one of our Xamarin Bindings. We also managed to make cross-targeting work.
Here's the project : https://github.com/nventive/Binding.Intercom
And the build if you're interested : https://uno-platform.visualstudio.com/Uno%20Platform/Uno%20Platform%20Team/_build/results?buildId=537

**Comment by jpobst** [comment]
SDK style project files are now officially supported via .NET 6 Android.  Marking this as complete.
