### ISSUE TITLE
the Release apk file can't be installed

### ISSUE THREAD

**Issue by suihanhbr** [xamarin/xamarin-android#2104]
### Steps to Reproduce

1. rebuild project
2. archive for publishing
3. sign and distribute
4. install the apk

### Expected Behavior

install normally

### Actual Behavior

install failed , message : the apk file is broken.

### Version Information

=== Visual Studio Professional 2017 for Mac ===

Version 7.6.1 (build 9)
Installation UUID: 4e60959a-758f-48ce-ae6d-26e15276ea83
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.6.0.13 (Visual Studio Professional)
Hash: 373c313a
Branch: 
Build date: 2018-07-24 23:47:12-0400

=== Xamarin.iOS ===

Version: 11.14.0.13 (Visual Studio Professional)
Hash: 373c313a
Branch: HEAD
Build date: 2018-07-24 23:47:12-0400

=== Xamarin.Android ===

Version: 9.0.0.19 (Visual Studio Professional)
Android SDK: /Users/huangboru/myfile/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 28.0.2

Java SDK: /usr
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706010009
Git revision: 1916291c332d942d45f3d8a952cc315f7864abef
Build date: 2018-08-22 19:19:11+00
Build branch: release-7.6
Xamarin extensions: 53cd52a227bb91315389d4860f821fa4c3b396b3

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Internet of Things (IoT) development (Preview) 7.5.3

**Comment by suihanhbr** [comment]
And sometimes VS For Mac broken when I was built on release mode.

**Comment by GalaxiaGuy** [comment]
Could this be related to this issue:
https://stackoverflow.com/questions/51679077/error-signing-and-uploading-apk-on-xamarin-android-9-and-visual-studio-for-mac-b

**Comment by lexboss93** [comment]
Confirm, same issue.

**Comment by JonDouglas** [comment]
We believe this issue is related to https://developercommunity.visualstudio.com/content/problem/317799/major-error-76-build-2190-creates-invalid-apk-for.html

Our Visual Studio for Mac team is currently investigating this issue.

**Comment by jpobst** [comment]
The related DevCom issue is marked as fixed, so we'll assume this is fixed since there are no more recent reports.
