### ISSUE TITLE
Xamarin build stuck at --auto-add-overlay

### ISSUE THREAD

**Issue by manivannan184** [xamarin/xamarin-android#2114]
### Steps to Reproduce

1. Xamarin Android project
2. Run MsBuild to build the solution and generate apk

### Expected Behavior

Build should be successful. Apk should be generated.

### Actual Behavior

(Sometimes) Build is getting hang/stuck at following build ouput

Executing package --non-constant-id -f -m -M C:\solution-path\project-path\obj\Debug\lp\29\jl\res\..\manifest\AndroidManifest.xml -J obj\\Debug\android\src -S C:\solution-path\HMI\HMI_App\obj\\Debug\res -S C:\solution-path\project-path\obj\Debug\lp\2\jl\res -S C:\solution-path\project-path\obj\Debug\lp\17\jl\res -S C:\solution-path\project-path\obj\Debug\lp\20\jl\res -S C:\solution-path\project-path\obj\Debug\lp\22\jl\res -S C:\solution-path\project-path\obj\Debug\lp\23\jl\res -S C:\solution-path\project-path\obj\Debug\lp\25\jl\res -S C:\solution-path\project-path\obj\Debug\lp\26\jl\res -S C:\solution-path\project-path\obj\Debug\lp\27\jl\res -S C:\solution-path\project-path\obj\Debug\lp\29\jl\res -S C:\solution-path\project-path\obj\Debug\lp\30\jl\res -I "C:\Program Files (x86)\Android\android-sdk\platforms\android-27\android.jar" --auto-add-overlay (TaskId:3372)

### Version Information

Visual studio Enterprise Edition 15.8.1
Java 8 (x64)
Android SDK - Android 27

### Log File

Provided above

**Comment by jonathanpeppers** [comment]
@manivannan184 can you attach a [diagnostic build log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

Alternatively, you can use [this extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) and record a binary build log. Whichever you prefer.

**Comment by jonathanpeppers** [comment]
@manivannan184 we haven't heard back on this for a while.

Closing for now, feel free to reopen if you can get us the requested info, thanks!
