### ISSUE TITLE
Debugger keeps jumping back to Breakpoint

### ISSUE THREAD

**Issue by tedlindstrom01** [xamarin/xamarin-android#2115]
### Steps to Reproduce

1. Create a new Project: Android App (Xamarin)
2. Select Navigation Drawer App
3. Set a breakpoint on Line 32
4. Debug the application on device or emulator
5. Once the debugger breaks, scroll down to the bottom and hover the mouse over some of the variables in the OnNavigationItemSelected method.

Notice how the debugger jumps back up to the top where the breakpoint is hit.

### Expected Behavior

Debugger should not jump back to the breakpoint while navigating.

### Actual Behavior

Debugger is jumping back to the breakpoint

### Version Information

Visual Studio 15.8.2

**Comment by jonathanpeppers** [comment]
Hi @tedlindstrom01,

Unfortunately Xamarin.Android itself doesn't have anything to do with how the UI is acting in Visual Studio.

I think you need to file this issue for Visual Studio itself using [instructions here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017).

Closing this for now, but feel free to be submitting issues here that are related to Xamarin.Android, thanks!
