### ISSUE TITLE
Reference self-developed .NET library to Xamarin.Android got archiving issue

### ISSUE THREAD

**Issue by allenliu1030** [xamarin/xamarin-android#2135]
This is Allen from APGC Xamarin support team. I got one customer built one .NET library by themselves, previously they are always directly referencing the project as the DLL to Xamarin.Android project. It works previously about half month ago when archiving the project to APK file, but it suddenly does not work and shows the below error message once customer clicked into the Archive for Publish:

![image](https://user-images.githubusercontent.com/36911474/44973443-2e7e1880-af8f-11e8-887f-09df0f7a7254.png)

If we double clicked on this error, it will get into below configuration part:

![image](https://user-images.githubusercontent.com/36911474/44973471-4190e880-af8f-11e8-9fcc-58c11738d750.png)

Currently I found one workaround is that we unload the .NET library project and reference the dll file from the bin\release folder directly.

But customer still wants to know why this is happening and what's the difference between these 2 approaches.

Please let me know if there is anything that we can check or logs to capture that can help to analyze the issue.

Thanks,

Allen Liu

**Comment by jonathanpeppers** [comment]
> built one .NET library by themselves, previously they are always directly referencing the project

@allenliu1030 is this a .NET library project? That isn't something that is supported.

Xamarin.Android apps should only reference:
- NetStandard libs, PCLs, shared projects
- Xamarin.Android library projects

**Comment by allenliu1030** [comment]
@jonathanpeppers 

Hi Jonathan, according to customer, yes, that should be a .NET library, but I can have a confirmation tomorrow.

However, even it's a .NET library, we successfully archive to publish the app by just referencing it to Xamarin.Android project, just not with the library project. Why this will happen?

**Comment by jonathanpeppers** [comment]
If it's a .NET library project, it's lucky it worked _at all_.

That is not something that has ever been supported with Xamarin.Android.

**Comment by allenliu1030** [comment]
@jonathanpeppers 

Then it's really strange. Let me confirm with customer first. But I do not think customer will accept it's lucky... Anyway, let's see how is the information from customer.

Thanks,

Allen

**Comment by allenliu1030** [comment]
@jonathanpeppers 

I got information from customer, he's using the .NET library only. So, any possible reason why a .NET library can be used in Xamarin.Android project?

Allen

**Comment by jonathanpeppers** [comment]
@allenliu1030 that has never been supported in the history of Xamarin, I believe...

Xamarin (iOS/Android/Mac) has the following options for sharing code: https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/code-sharing

I would recommend porting the library to NetStandard 2.0 if they are wanting to use the latest/greatest.

If they are using APIs that won't work in NetStandard, they could also look into using a shared project or Xamarin.Android library project.

**Comment by jonathanpeppers** [comment]
@allenliu1030 closing this, as referencing a plain .NET library from Xamarin.Android is not supported... Sorry!

Feel free to reopen if you see something different here, thanks!
