### ISSUE TITLE
Using Makefile Project (Android) doesn't copy the libs to the main project

### ISSUE THREAD

**Issue by bneumann** [xamarin/xamarin-android#2136]
### Steps to Reproduce

1. Use standard hello world sample Xamarin Android project
2. Use standard Hello Jni from Android samples
3. Create new Makefile Project (Android)
4. Copy hello-jnc.c and Makefiles to project
5. Add NDK Project Path to nmake call (This should be default by the way!)

I prepared a demo here:
[bugReport.zip](https://github.com/xamarin/xamarin-android/files/2346521/bugReport.zip)

### Expected Behavior
1. Build should also build the MakeFile Project
2. The libs should be added to the ouput directory of the Main project

### Actual Behavior
1. Needs to be triggered manually
2. The libs are in a subfolder which is cool but there is no automated way to tell VS that these libs belong to my build. Even copying them manually does not work, they are NOT included in the APK

### Version Information

Microsoft Visual Studio Community 2017 
Version 15.8.2
VisualStudio.15.Release/15.8.2+28010.2016
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA296
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.8.05077.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.11.8-pre (009db7d)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61808.07020
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.8.20801.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27924.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: c55dd2c3d618eb93a8d16e503947342b1fa93556.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   3.8.0.6
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.28010.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.756 (d15-8@b66ff7180)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.14.221 (a73ca07f7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.116 (9619170)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

### Log File

```
D/Mono    (10182): DllImport error loading library '/system/lib/libMakeFileProject.so': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86//system/lib/libMakeFileProject.so" not found'.

D/Mono    (10182): DllImport error loading library 'libMakeFileProject': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86/libMakeFileProject" not found'.

D/Mono    (10182): DllImport error loading library 'libMakeFileProject.so': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86/libMakeFileProject.so" not found'.

D/Mono    (10182): DllImport error loading library 'MakeFileProject': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86/MakeFileProject" not found'.

D/Mono    (10182): DllImport error loading library '/data/data/com.xamarin.helloworld/files/.__override__/libMakeFileProject': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86//data/data/com.xamarin.helloworld/files/.__override__/libMakeFileProject" not found'.

D/Mono    (10182): DllImport error loading library '/data/data/com.xamarin.helloworld/files/.__override__/libMakeFileProject.so': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86//data/data/com.xamarin.helloworld/files/.__override__/libMakeFileProject.so" not found'.

D/Mono    (10182): DllImport error loading library '/system/lib/libMakeFileProject': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86//system/lib/libMakeFileProject" not found'.

D/Mono    (10182): DllImport error loading library '/system/lib/libMakeFileProject.so': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86//system/lib/libMakeFileProject.so" not found'.

D/Mono    (10182): DllImport error loading library 'libMakeFileProject': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86/libMakeFileProject" not found'.

D/Mono    (10182): DllImport error loading library 'libMakeFileProject.so': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86/libMakeFileProject.so" not found'.

D/Mono    (10182): DllImport error loading library 'libMakeFileProject': 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86/libMakeFileProject" not found'.

W/Mono    (10182): DllImport unable to load library 'dlopen failed: library "/data/app/com.xamarin.helloworld-1/lib/x86/libMakeFileProject" not found'.
```

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
