### ISSUE TITLE
Desugar Task should provide deps / --classpath_entry(s)

### ISSUE THREAD

**Issue by erikpowa** [xamarin/xamarin-android#2143]
### Steps to Reproduce

1.  Build an app project with some _binding library_

### Expected Behavior

desugar_deploy.jar desugaring _.jar_ with dependencies without exception

### Actual Behavior

**Desugar** entirely skips the _--classpath_entry_  dependencies for _.jar_ (or it's by design? please no) when desugar_deploy.jar  gets called, causing failures just like:

`1>  Exception in thread "main" java.lang.TypeNotPresentException: Type okhttp3.Interceptor not present`

### Version Information

xa sdk 9.1.0.19

### Fast repro + good scenario
[xabug.zip](https://github.com/xamarin/xamarin-android/files/2351211/xabug.zip)

**Comment by JonDouglas** [comment]
`desugar_deploy.jar` is deprecated as it was a standalone desugar tool that was integrated into the d8/r8 pipeline, and thus our initial support for desugar does not handle this scenario. We will need to ensure we are accounting for this within our `r8` and `d8` proposal.

https://github.com/xamarin/xamarin-android/issues/2040

Our source for the desguar task can be found here:

https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Tasks/Desugar.cs

At first glance, it looks like we would need to add this `--classpath_entry` switch and append the respective .jar file name foreach item. @jonathanpeppers can chime in further on this.

**Comment by erikpowa** [comment]
I just patched the IL in [here](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Tasks/Desugar.cs#L88).
![smy24w1](https://user-images.githubusercontent.com/1832264/45114040-3800af80-b14c-11e8-8761-c69f7c4ec878.png)
tested (with multidex) and it's working
```
commandLineBuilder.AppendSwitch("--classpath_entry ");
commandLineBuilder.AppendFileNameIfNotNull(text);
```
Won't PR it then if it's deprecated

**Comment by JonDouglas** [comment]
@erikpowa To be more specific, the `desguar.jar` is going to be deprecated in favor of the `desugar` step being included in the new dex compiler (d8). I don't believe the new dex compiler has an option to provide this argument. I'd defer to @jonathanpeppers whether he thinks it's worth to PR or not.

**Comment by jonathanpeppers** [comment]
@erikpowa feel free to send a PR!

I'm trying to follow what you're changing here, but not seeing exactly. There isn't a variable named `text` in our `Desugar` MSBuild task.

Are we missing jar files as `--input`? https://github.com/xamarin/xamarin-android/blob/f6c3288dd5a7f82c178ef30ad25c11d475f1daf4/src/Xamarin.Android.Build.Tasks/Tasks/Desugar.cs#L85-L92

Or do we need to specify `--classpath_entry` for each jar file in addition to `--input`?

**Comment by erikpowa** [comment]
@jonathanpeppers sorry, I modified the `Xamarin.Android.Build.Tasks.dll` with dnSpy, I was lazy to clone/edit/build/push from source, and yes, my repro shows the current standalone desugar fails if there are certain jars that needs it's dependencies as classpath_entry, othwerwise it fails if not passed as argument. (such as [twitter-core](http://jcenter.bintray.com/com/twitter/sdk/android/twitter-core/3.3.0/))

The hackish way looks like this (just make every --input --classpath_entry aswell):
```
foreach (var jar in InputJars) { 
 	var output = Path.Combine (OutputDirectory, BitConverter.ToString (md5.ComputeHash (Encoding.UTF8.GetBytes (jar))) + Path.GetFileName (jar)); 
 	outputs.Add (output); 
 	cmd.AppendSwitch ("--classpath_entry"); 
 	cmd.AppendFileNameIfNotNull (jar); 
 	cmd.AppendSwitch ("--input "); 
 	cmd.AppendFileNameIfNotNull (jar); 
 	cmd.AppendSwitch ("--output "); 
 	cmd.AppendFileNameIfNotNull (output); 
 } 
```

**Comment by gmoney494** [comment]
@erikpowa  another way to get past this error without modifiying the dll?

**Comment by erikpowa** [comment]
@gmoney494 don't think so, you can build it XA manually tho, but it's only working >=7.0, something is  messing around under api 24

**Comment by erikpowa** [comment]
@gmoney494 or you can make a custom desugar task on jar files that runs before `Desugar` task and try addig [this](https://github.com/xamarin/xamarin-android/pull/2158#issuecomment-420450419) aswell (but it's untested)
