### ISSUE TITLE
First run of Xamarin Forms Android Control Gallery throws error on inflating class Toolbar

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-android#2177]
VS for MAC
Build Version: 7.6.3 (build 1)

### Steps to Reproduce
1. git clone https://github.com/xamarin/Xamarin.Forms.git
2. open Xamarin.Forms.SLN
3. set Xamarin.Forms.ControlGallery.Android as startup project
4. run and deploy project

At this point I get a crash when the tool bar tries to inflate

Rebuild Xamarin.Forms.ControlGallery.Android
run and deploy project again

Now it runs fine

I'm unable to verify on Alpha because currently XF can't be built on Alpha because a different bug
https://github.com/mono/mono/issues/10352

### Expected Behavior

Project should run and deploy first time without requiring  a rebuild

### Actual Behavior
Requires a rebuild

### Version Information

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.4 (build 22)
Installation UUID: 72a6cb22-788b-4376-9a6e-84deacf6730b
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 11.14.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/shane/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706040022
Git revision: c20766ac3664b80b4098ec4181abcc73ea3a4a2c
Build date: 2018-09-07 17:05:17+00
Build branch: release-7.6
Xamarin extensions: 9c227549870ec221f51f5dfb1f05da688ee71911

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

EditorConfig 1.2

**Comment by jonpryor** [comment]
Could this be due to VS Mac invoking MSBuild targets *concurrently*, e.g. executing the **Build** and **UpdateAndroidResources** targets from *different* processes at the *~same* time?  This is a known issue in VS Mac.

**Comment by jonathanpeppers** [comment]
Yes, my current guess is [this VS for Mac issue](http://work.devdiv.io/661455) is the cause...

Running command line it works for me:
```
git clean -dxf
nuget restore Xamarin.Forms.sln
msbuild Xamarin.Forms.sln
msbuild Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj /t:Install,_Run
```

In VS for Mac, I wasn't able to get it to even build... I was getting build errors from `ResolveLibraryProjectImports`, I presume because it was fighting the concurrent `UpdateAndroidResources` build.

**Comment by jpobst** [comment]
This is likely obsolete as we have not had any recent reports on currently supported versions.
