### ISSUE TITLE
Issue in using JNI to call activity from android AAR file

### ISSUE THREAD

**Issue by tajinder95** [xamarin/xamarin-android#2179]
Hi I am facing using AAR file in xamarin android project . I have added android AAR file in my xamarin android and set its build type to "AndroidAarLibrary" .Following is c# code used in xamarin to call activity that is defined in AAR file.

```csharp
var clsName = Java.Lang.Class.ForName("com.dsphotoeditor.sdk.activity.DsPhotoEditorActivity");
var innt = new Intent(this, clsName);
innt.SetData(inputImageUri); //Set image uri
innt.PutExtra("ds_photo_editor_api_key", "26c479d17c220131bec7b6e29e070ad89f3e6cf4");
innt.PutExtra("ds_photo_editor_output_directory", "ds_photo_editor_sample");
StartActivityForResult(innt, DS_PHOTO_EDITOR_REQUEST_CODE);
```

Now corresponding activity is called successfully and UI showing image editor property. But when clicking filter options in UI then it throw error and application gets closed with follwing error message:

```
CheckJNI: method to register "rsnScriptReduce" not in the given class. This is slow, consider changing your RegisterNatives calls.
Failed to register native method android.support.v8.renderscript.RenderScript.rsnScriptReduce(JJI[JJ[I)V in /data/app/mono.samples.jnitest-1/base.apk
 ----- class 'Landroid/support/v8/renderscript/RenderScript;' cl=0x32c07070 -----
```

I think some classes not included while apk generation or not accessible. Please let me know if I am doing anything or if anyone have used this approach before.
This is google drive link to corresponding xamarin project https://drive.google.com/open?id=13r5FPLhbf75ERBqJI858kubmVARitZ74

Link of full log file of xamarin output : https://drive.google.com/open?id=1doDkuUR7P25TfBfGz_QHn3m_TsGQ3MNo

Note:I am want to use photo-editor AAR library from https://www.dsphotoeditor.com

**Comment by jonpryor** [comment]
@Redth: Thoughts?

What appears to be happening is that the renderscript native library is attempting to register a JNI method which doesn't exist.  For example, [`JNI_OnLoad()` *within* `librsjni.so`](https://android.googlesource.com/platform/frameworks/support/+/62a63e5/v8/renderscript/jni/android_renderscript_RenderScript.cpp#2433) calls [`JNIEnv::RegisterNatives()`](https://android.googlesource.com/platform/frameworks/support/+/62a63e5/v8/renderscript/jni/android_renderscript_RenderScript.cpp#2454), specifying the registration information for [`RenderScript.rsnScriptReduce(JJIJJ[I)V`](https://android.googlesource.com/platform/frameworks/support/+/62a63e5/v8/renderscript/jni/android_renderscript_RenderScript.cpp#2383).  (No idea if that commit is the "right" commit; that's just what came up when searching for ["android.support.v8.renderscript source rsnScriptReduce"](
https://www.google.com/search?q=android.support.v8.renderscript+source+rsnScriptReduce).)

This is largely outside of our control: We don't build `librsjni.so`, nor do we distribute it, nor do I see `librsjni.so` within `Xamarin.Android.Support.v8.RenderScript.dll`.  (For that matter, I don't see *any* embedded resources within `Xamarin.Android.Support.v8.RenderScript.dll`, so where is the corresponding `.jar` file coming from?

My theory is that the `librsjni.so` and renderscript `.jar` file which are being used by your application are "out of sync," inconsistent with each other, such that `librsjni.so` is attempting to register methods which *do not exist* within the `.jar` file.  This causes the crash:

```
09-12 04:47:36.024 E/art     (27428): Failed to register native method android.support.v8.renderscript.RenderScript.rsnScriptReduce(JJI[JJ[I)V in /data/app/mono.samples.jnitest-1/base.apk
...
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Landroid/support/v8/renderscript/RenderScript;.rsnScriptReduce(JJI[JJ[I)V"
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1072)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.String) (Runtime.java:987)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1562)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at android.support.v8.renderscript.RenderScript android.support.v8.renderscript.RenderScript.internalCreate(android.content.Context, int, android.support.v8.renderscript.RenderScript$ContextType, int) (RenderScript.java:1399)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at android.support.v8.renderscript.RenderScript android.support.v8.renderscript.RenderScript.create(android.content.Context, android.support.v8.renderscript.RenderScript$ContextType) (RenderScript.java:1516)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at java.lang.Object com.dsphotoeditor.sdk.b.a$b.doInBackground(java.lang.Object[]) ((null):-1)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at java.lang.Object android.os.AsyncTask$2.call() (AsyncTask.java:305)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at void android.os.AsyncTask$SerialExecutor$1.run() (AsyncTask.java:243)
09-12 04:47:37.217 F/art     (27428): art/runtime/runtime.cc:427]   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
```

What I don't currently understand is *how* `librsjni.so` and the renderscript `.jar` could be out of sync, and/or what mechanisms exist to ensure that they *are* in sync.

**Comment by jonpryor** [comment]
@Redth refreshed my memory on how things work -- thanks! -- pointing out that Xamarin.Android determines the `.so` and `.jar` files to use by using the assembly-level custom attributes within `Xamarin.Android.Support.v8.RenderScript.dll`, a'la

```csharp
[assembly: JavaLibraryReferenceAttribute ("android-N/renderscript/lib/renderscript-v8.jar", SourceUrl = "http://dl-ssl.google.com/android/repository/build-tools_r24-macosx.zip", Version = "24", PackageName = "Xamarin.Android.Support.v8")]
[assembly: NativeLibraryReference ("android-N/renderscript/lib/packaged/armeabi-v7a/librsjni.so", SourceUrl = "http://dl-ssl.google.com/android/repository/build-tools_r24-macosx.zip", Version = "24", PackageName = "Xamarin.Android.Support.v8")]
```

So I go off and download http://dl-ssl.google.com/android/repository/build-tools_r24-macosx.zip and see if it's self consistent:

```bash
$ curl -o build-tools_r24-macosx.zip 'http://dl-ssl.google.com/android/repository/build-tools_r24-macosx.zip'
$ mkdir build-tools_r24-macosx
$ cd build-tools_r24-macosx
$ unzip ../build-tools_r24-macosx.zip
```

What's the Java method signature for `rsnScriptReduce()`?

```bash
$ javap -classpath android-N/renderscript/lib/renderscript-v8.jar  -private -s -c android.support.v8.renderscript.RenderScript |  grep -1 rsnScriptReduce

  native void rsnScriptReduce(long, long, int, long, long, int[]);
    descriptor: (JJIJJ[I)V
...
```

What about the native lib?

```bash
$ strings android-N/renderscript/lib/packaged/x86/librsjni.so  | grep -1 rsnScriptReduce
...
rsnScriptReduce
(JJIJJ[I)V
...
```

Thus, they're consistent: `(JJIJJ[I)V` == `(JJIJJ[I)V`.

...then I re-read the original description:

```
Failed to register native method android.support.v8.renderscript.RenderScript.rsnScriptReduce(JJI[JJ[I)V in /data/app/mono.samples.jnitest-1/base.apk
```

One of these is not like the other: `(JJIJJ[I)V` != `(JJI[JJ[I)V`.

:-(

Doubly odd is that `(JJI[JJ[I)V` *does* exist in `renderscript-v8.jar`, but for *`rsnScriptReduceNew()`*.

@tajinder95: What hardware device and Android OS version are you running this on?

My current guess is that:

 1. `/system/lib/librsjni.so` exists, and
 2. (1) is being used *in preference to* any `librsjni.so` distributed within your `.apk`.

*If* that's the case, there's not a good workaround.  (Upgrade Android?)

That "if" needs to be verified.

**Comment by tajinder95** [comment]
Hi Jonathan Pryor,
Thank for analysis my issue soo deeply. I am using Visual studio 2017 and debugging in device having android 7.1 API (25) .In visual studio build options are "Compile using Android 8.1(Latest)"

For your information same AAR files perfectly in Android sample code. you can find this sample code on link https://drive.google.com/open?id=1PY39GUsisOaaNNQBIhDWg1y6pfLxzpDr .I am not sure why issues comes while using it in xamarin ,As AAR file already contain all native libraries in it .

Although AAR file have native library included ,I still added them into xamarin project also(I have attached screenshot,how I added native library)
![nativeandriod](https://user-images.githubusercontent.com/14553299/45417063-ed78b900-b69e-11e8-8a84-33c75957c291.PNG)
![nativevs](https://user-images.githubusercontent.com/14553299/45417064-ed78b900-b69e-11e8-9b8b-ed699cffc61d.PNG)

**Comment by tajinder95** [comment]
Is there any way I can direly register the concerned native function(android.support.v8.renderscript.RenderScript.rsnScriptReduce(JJI[JJ[I)V)  in c# by using JNI.

**Comment by jonpryor** [comment]
> Is there any way I can directly register the concerned native function(android.support.v8.renderscript.RenderScript.rsnScriptReduce(JJI[JJ[I)V) in c# by using JNI.

Can you?  Yes.

Should you?  No.

Native method registration is done *an entire class at a time*.  You can't "just" register one native method (unless the Java class only declares one native method), you have to register *all* the native methods for that class.

We don't know -- *can't* know? -- what *other* methods are on this type, so if you *did* register *just* that method and one of the other `native` methods was then invoked, you'd get an `Error` thrown at runtime.

It's not a good idea. :-(

@tajinder95: Could you please tell me if your target device contains the file `/system/lib/librsjni.so`?  If it does, could you please run the command:

    adb pull /system/lib/librsjni.so

then attach `librsjni.so` to this issue?

**Comment by jonathanpeppers** [comment]
@tajinder95 closing for now, since we haven't heard from you in a while. Feel free to comment/reopen if you can give more info. Thanks!
