### ISSUE TITLE
Constructor bindings not generated if default constructor is protected

### ISSUE THREAD

**Issue by BenBtg** [xamarin/xamarin-android#2181]
### Steps to Reproduce

1. Download and build the java iot hub device client
https://github.com/Azure/azure-iot-sdk-java/tree/master/device

2. Create an Android binding library and copy the device client jar to bind

### Expected Behavior
Bindings generated include all public constructors

### Actual Behavior
Not contructors created.

Current workaround I have found was to delete the protected default contructor in the deviceclient class which seem to be causing the issue.

### Version Information

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.4 (build 22)
Installation UUID: 1c546fd2-40c4-4184-b556-7e45d5f7749c
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
	1.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
	1.0.0-preview2-003121
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 11.14.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/benbtg/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.1 (API level 22)
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706040022
Git revision: c20766ac3664b80b4098ec4181abcc73ea3a4a2c
Build date: 2018-09-07 17:05:17+00
Build branch: release-7.6
Xamarin extensions: 9c227549870ec221f51f5dfb1f05da688ee71911

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 3.05.19
Internet of Things (IoT) development (Preview) 7.5

**Comment by BenBtg** [comment]
@JonDouglas  
I've pushed the following library which demonstrates the issue.
https://github.com/BenBtg/azure-iot-sdk-java-binding
Note the DeviceClient class defined in iot-device-client-1.14.0.jar has a number of public contructors e.g.  public DeviceClient(String connString, IotHubClientProtocol protocol). 
But because it also has a protected default contructor none of the public ones are generated in the binding.

**Comment by jpobst** [comment]
This has been fixed in VS 2019 16.2+ by this commit:
https://github.com/xamarin/java.interop/commit/a2c0fb2076cb59501b6257c9ba205279162c2632
