### ISSUE TITLE
[build] `msbuild /t:Prepare Xamarin.Android.sln` hits ""ResolveAndroidTooling" task failed unexpectedly." with Visual Studio 2017 version 15.9 Preview if `$(AndroidToolchainDirectory)` doesn't already exist

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#2195]
This is a new error that happens when running `msbuild /t:Prepare Xamarin.Android.sln` using Visual Studio 2017 version 15.9 Preview or higher (any version that includes https://github.com/xamarin/xamarin-android/commit/d73442ec4c661633023b88c9d058e0f2f2455aa4).

The error doesn't happen when building with Visual Studio 2017 version 15.8 because in that version `GetMaxInstalledApiLevel()` was directly part of a single large `ResolveSdkTask` where `$(AndroidSdkPath)` was [set to `MonoAndroidHelper.AndroidSdk.AndroidSdkPath`](https://github.com/xamarin/xamarin-android/blob/9e4ec787991039b9ad0d2ee43235348af739f753/src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs#L83) (C:\\Program Files (x86)\\Android\\android-sdk in my test environment). Although `ResolveSdkTask` itself still uses `MonoAndroidHelper.AndroidSdk.AndroidSdkPath` in Visual Studio 2017 version 15.9 Preview, the new `ResolveAndroidTooling` task does *not* currently use `MonoAndroidHelper`, so `$(AndroidSdkPath)` stays set to `$(AndroidToolchainDirectory)` (C:\\src\\android-toolchain in my test environment). When [`GetMaxInstalledApiLevel()` calls `Directory.EnumerateDirectories()`](https://github.com/xamarin/xamarin-android/blob/9e4ec787991039b9ad0d2ee43235348af739f753/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs#L330) on the Android SDK in the program files directory, it works because that directory exists, but when it tries to enumerate C:\\src\\android-toolchain, it hits an error because that directory does not yet exist. (The next step of the build just after the NuGet packages are restored is [to set up that directory](https://github.com/xamarin/xamarin-android/blob/9e4ec787991039b9ad0d2ee43235348af739f753/build-tools/scripts/PrepareWindows.targets#L19-L24).)

### Possible Fix

One possible way to resolve this issue is to have `ResolveAndroidTooling` use `MonoAndroidHelper.AndroidSdk.AndroidSdkPath`:

```patch
diff --git a/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs b/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
index a6b76204..9161bb99 100644
--- a/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
+++ b/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
@@ -77,6 +77,9 @@ namespace Xamarin.Android.Tasks
 
 		public override bool Execute ()
 		{
+			AndroidNdkPath = MonoAndroidHelper.AndroidSdk.AndroidNdkPath;
+			AndroidSdkPath = MonoAndroidHelper.AndroidSdk.AndroidSdkPath;
+
 			string toolsZipAlignPath = Path.Combine (AndroidSdkPath, "tools", ZipAlign);
 			bool findZipAlign = (string.IsNullOrEmpty (ZipAlignPath) || !Directory.Exists (ZipAlignPath)) && !File.Exists (toolsZipAlignPath);
 
```

I tested this locally, and it worked as desired for this scenario. I believe this should be OK for end-user Xamarin.Android app builds too because it's just going back to how these paths were determined at this step in Visual Studio 2017 version 15.8.

#### Other possibles approaches

I initially tried moving [`<MSBuild Projects="$(MSBuildThisFileDirectory)..\android-toolchain\android-toolchain.csproj" />`](https://github.com/xamarin/xamarin-android/blob/9e4ec787991039b9ad0d2ee43235348af739f753/build-tools/scripts/PrepareWindows.targets#L24) to happen *before* the NuGet restore commands, but that was unsuccessful due to missing dependencies. It might be possible to adjust android-toolchain.csproj and the other preparation steps so that android-toolchain.csproj can build before any `NuGet.exe restore` step (or more precisely, before any `NuGet.exe restore` on a project that imports Xamarin.Android.Common.targets), but I haven't experimented with that.

### Steps to Reproduce

1. Install Visual Studio 2017 version 15.9 Preview 2 or higher with the **Mobile development with .NET** workload. Also select the following **Individual components**:

    - .NET Framework 4 targeting pack
    - .NET Framework 4.5 targeting pack
    - .NET Framework 4.5.1 targeting pack
    - .NET Framework 4.5.2 targeting pack
    - .NET Framework 4.6 targeting pack
    - .NET Framework 4.6.1 targeting pack
    - .NET Framework 4.6.2 targeting pack

2. `git clone https://github.com/xamarin/xamarin-android.git`

3. Ensure that you do not yet have an android-toolchain directory from a previous `msbuild /t:Prepare Xamarin.Android.sln`. (Or rename the existing directory out of the way.)

4. `msbuild Xamarin.Android.sln /t:Prepare`

    If Visual Studio version 15.8 is *also* installed, then NuGet will default to using the MSBuild and Xamarin.Android.Common.targets file from that version, and the `/t:Prepare` target will *succeed*. In that case you can invoke NuGet directly instead, passing in the path to MSBuild from the Visual Studio preview version:

    `.\.nuget\NuGet.exe restore .\Xamarin.Android-Tests.sln -MSBuildPath "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin"`

### Expected Behavior

The NuGet restore step succeeds.

### Actual Behavior

The NuGet restore step fails for Xamarin.Android-Tests.sln at the point where `_SetLatestTargetFrameworkVersion` calls the new `ResolveAndroidTooling` task.

```
"C:\Users\Windows User\AppData\Local\Temp\NuGetScratch\uj5oucwn.yyt.nugetinputs.targets" (GenerateRestoreGraphFile target) (1) ->
"C:\src\xamarin-android\src\Mono.Android\Test\Mono.Android-Tests.csproj
" (_GenerateProjectRestoreGraph target) (2:5) ->
(_SetLatestTargetFrameworkVersion target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(712,2): error MSB4018: The 
"ResolveAndroidTooling" task failed unexpectedly. [C:\src\xamarin-android\src\Mono.Android\Test\Mono.Android-Tests.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(712,2): error MSB4018: 
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\src\android-toolchain\sdk\platforms'. 
[C:\src\xamarin-android\src\Mono.Android\Test\Mono.Android-Tests.csproj]
```

**Comment by jonathanpeppers** [comment]
So I guess I haven't run into this, because I don't set `$(AndroidToolchainDirectory)`, I generally leave all the options default/blank (don't even use `Configuration.Override.props`).

Basically you could boil it down to:
- You want a custom `$(AndroidToolchainDirectory)`, let's say your username has a space or you want it at `C:\android`, etc.
- `$(AndroidToolchainDirectory)` has not been created yet
- `nuget.exe restore Xamarin.Android.sln` errors out, because it's going to call MSBuild and the `_SetLatestTargetFrameworkVersion ` target

I'm not sure what the best fix is here...

If you took your example:
```csharp
AndroidSdkPath = MonoAndroidHelper.AndroidSdk.AndroidSdkPath;
```

I'm guessing this works because it goes and finds _some_ Android SDK somewhere, could you have one from the VS install? I also wouldn't want to do this, as it's going to go "find" an SDK instead of the one supplied by the setting in the IDE in customer apps.

Your other idea about reordering stuff seems a bit safer, but we might have a chicken-and-egg scenario. 

We had to work around something like this for NuGet when we introduced `TargetFrameworkVersion=v9.0` and system Xamarin.Android didn't have it yet: https://github.com/xamarin/xamarin-android/commit/41a4cbcfe520a14fcd80b145ba944e8cd709cd53

I would rather get rid of 41a4cbcfe5 in favor of something less hacky, maybe could fix this scenario at the same time? Need to think about it.

**Comment by brendanzagaeski** [comment]
> You want a custom $(AndroidToolchainDirectory), let's say your username has a space or you want it at C:\android, etc.

I realized overnight that this condition isn't necessary, and so there is in fact a way to hit the issue in end-user app builds too: <https://github.com/xamarin/xamarin-android/issues/2200>.

I'm assuming that since `$(AndroidUseLatestPlatformSdk)` still has an effect in Visual Studio 2017 version 15.9 Preview 2, it's probably safest to apply the  *Possible Fix* patch, at least for the Visual Studio 2017 version 15.9 release. But if the goal is actually to disable `$(AndroidUseLatestPlatformSdk)` entirely (even when explicitly set in a command line build) by the time of the first version 15.9 non-preview release, then this might not be necessary.

**Comment by jonpryor** [comment]
`$(AndroidUseLatestPlatformSdk)`=True needs to continue to be supported on Visual Studio for Mac until after the next major release.  Visual Studio (Windows) 15.8 will actively remove this property from `.csproj` files.

**Comment by jonathanpeppers** [comment]
We believe this fixes it: https://github.com/xamarin/xamarin-android/pull/2204

@brendanzagaeski feel free to reopen if you find something new here.
