### ISSUE TITLE
Visualizer Class returns faulty fft data

### ISSUE THREAD

**Issue by BennyKirschner** [xamarin/xamarin-android#2208]
### Steps to Reproduce

1. Create an Android.Media.Audiofx.Visualizer object
2. Use .getFfs(byte[]) to overwrite an array with current fft data, while playing music on the device
3. The array will be filled with unusable data (mostly 0s and 255s), not the expected behavior of byte data between 0 and 255, making this method completely unusable

### Expected Behavior

byte[] should be filled with current fft spectrum going from 0 - 255 for each element

### Actual Behavior

byte[] mostly consists of 0s and 255s after requesting data, which makes this method unusabe

**Comment by atsushieno** [comment]
There are two possibilities I can think of (without any reproducible code):

- Expectation mismatch: Xamarin.Android doesn't inject Android API behavior. Whatever you get is actually what Android API performs and returns.
- Having said that, array marshaling before and after invoking Android API is somewhat special; Any array contents will be copied over an intermediate Java object array before invocation, and copied back to the original array after operation. Your code possibly does not expect that. Using JavaArray is the best route to avoid that kind of extra marshaling.

**Comment by BennyKirschner** [comment]
I'll try working with the JavaArray and give some feedback afterwards, it would be great if someone could try to recreate this issue however. I could provide a sampleproject if needed.

**Comment by BennyKirschner** [comment]
![capture](https://user-images.githubusercontent.com/15686206/45956092-fd36bc80-c011-11e8-834a-1fd7fbbc7f1d.PNG)

This is how getfft gets called, I haven't tried it with JavaArray yet, but I'll do so later today. Here's how the current fft array looks anyway.

**Comment by grendello** [comment]
While @atsushieno might be right in that it won't be reproducible, I'd like to request a sample/repro project regardles, @BennyKirschner. Would you mind zipping it up and attaching here? Thanks!

**Comment by BennyKirschner** [comment]
Since I can't upload anything >10 MB I'll post a dropbox link instead:
https://www.dropbox.com/s/d78kuhhkzpxfbqr/BadFft.zip?dl=0
Start the app once to accept permsissions, then close it. Uncomment line 41 in MainActivity and start again.
You should see that a foreground service started. You can close the app, start YouTube or anything else that plays audio. Then go to MainLoop and set a breakpoint in line 49. That's it, now check currAudioData[].

**Comment by BennyKirschner** [comment]
After some more testing/research I realized that I just didn't use the method correctly and that it works as it should, can be closed.

**Comment by jonathanpeppers** [comment]
@BennyKirschner feel free to reopen if you get more info and think it is a bug, thanks!
