### ISSUE TITLE
WebRequest timeout

### ISSUE THREAD

**Issue by rgroenewoudt** [xamarin/xamarin-android#2209]
Timeout while using WebResponse many times.

System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () [0x000ba] in <b78695579ed9422b8bc80218eeda782c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.GetResponse () [0x00013] in <b78695579ed9422b8bc80218eeda782c>:0 

### Steps to Reproduce
```
while (true)
                    {
                        System.Diagnostics.Debug.WriteLine("google.nl start");
                        var client = (HttpWebRequest) WebRequest.Create("http://google.nl");
                        client.Timeout = (int) TimeSpan.FromSeconds(10).TotalMilliseconds;
                        client.GetResponse();
                        System.Diagnostics.Debug.WriteLine("google.nl end");
                    }
```
No issues when response is disposed or WebRequest is aborted.

### Version Information
Visual Studio 15.8.5. Same issue with 15.7.6.

**Comment by rgroenewoudt** [comment]
When calling asmx webservice, the implementation of SoapClientProtocol does not dispose of the response (only the stream) resulting in the same timeout.

**Comment by grendello** [comment]
[test.zip](https://github.com/xamarin/xamarin-android/files/2411660/test.zip)

This issue is not specific to Xamarin.Android, I was able to reproduce it on desktop and therefore the issue will be moved to the Mono repository.

**Comment by grendello** [comment]
This issue was moved to mono/mono#10774
