### ISSUE TITLE
Fastdev no longer works for certain projects on second unchanged deployment attempt

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2216]
A legacy amalgamation of test cases used in a fastdev test scenario is no longer working as expected. This application is now being fully re-installed on a second unchanged installation attempt. I'm seeing this on both macOS and Windows. I've attached a similar repro using an XA template with a handful of play services / support NuGets, a wearable 1.0 project, and Android class project references.

### Steps to Reproduce

1. Download the attached project: [App32.zip](https://github.com/xamarin/xamarin-android/files/2413092/App32.zip)
2. Restore NuGet packages.
3. `msbuild /t:Install App32\App32\App32.csproj`
4. `msbuild /t:Install App32\App32\App32.csproj`

### Expected Behavior
A sequential unchanged installation attempt should re-deploy almost immediately.

### Actual Behavior
The `BuildApk` and `InstallPackageAssemblies` tasks execute in full, when `BuildApk` should be skipped entirely. The previous version of the apk is uninstalled and replaced with the newly built version. This is a regression as compared to d15-9 preview and d15-8 stable releases.

### Version Information
Xamarin.Android SDK   9.1.99.26 (HEAD/225afd531)

### Log File
https://gist.githubusercontent.com/pjcollins/51cc04a093dd06727f2247a70ad68d67/raw/cb6b0c6ff827ffb7b1669e25ae8f5ac2511efcda/gistfile1.txt
http://xqa.blob.core.windows.net/gist/report-735652c843e94f199972da9a9e76cc73.txt

> VS bug [#690758](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/690758)

**Comment by jonathanpeppers** [comment]
I think this might be fixed by: https://github.com/xamarin/xamarin-android/pull/2236

This has a custom view `activity_main.axml`:
```
<android.support.v4.widget.DrawerLayout
```

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '15.9' that is not in the list of supported values

**Comment by pjcollins** [comment]
@jonathanpeppers and perhaps @dellis1972 I'm now seeing this against d15-9, it appears to have been introduced somewhere between deeb6d10a14902b04628d7cd903a745502200516 and 34c442a5cd42d04980acdaf5caee7cc4899efbbd (monodroid/d15-9/818caf67 and monodroid/d15-9/99eb396b).

I'm updating the milestone here to d15-9 as we appear to have regressed in the latest 15.9 Preview 4 RC (as compared to 15.9 Preview 3).

**Comment by pjcollins** [comment]
I am going to resolve this issue as I am no longer able to reproduce against monodroid/master/6b8f18a, and a new issue has been opened in ADO to track the resolution of https://github.com/xamarin/xamarin-android/issues/2216#issuecomment-428731234 for d15-9.
