### ISSUE TITLE
Some X.A targets do not respect Inputs/Outputs timestamp invariant

### ISSUE THREAD

**Issue by garuma** [xamarin/xamarin-android#2247]
I'm debugging an incremental compilation for a project of ours and I have identified at least 3 spots where X.A targets are using `CopyIfChanged` or a variant-thereof and thus breaking inputs/outputs invariant.

What I mean by this is that you have plenty of scenarios where some target `Inputs` are newer than `Outputs` causing the target to run **yet** those updated Inputs will end up generating the same Outputs **content**. Because of the logic of `CopyIfChanged`, this mean that **no actual change** is committed to Outputs and thus when the target finishes executing you have broken the invariant that `Outputs` always have to be newer that your `Inputs`.

Three places where I have seen this (there might be more):

- `_CopyIntermediateAssemblies` (Outputs are also wrong for this one, they lack the satellites copy)
- `_GeneratePackageManagerJava`
- `_ResolveLibraryProjectImports`

**Comment by jonathanpeppers** [comment]
@garuma if these targets are running all the time, and taking > 0ms, we should look into this.

The immediate idea that comes to mind is to use a "stamp" file:
```xml
<Target Name="_ResolveLibraryProjectImports" Inputs="..." Outputs="$(IntermediateOutputPath)libraryprojectimports.stamp">
  <!--Whatever the target does-->
  <Touch Files="$(IntermediateOutputPath)libraryprojectimports.stamp" AlwaysCreate="True" />
  <ItemGroup>
    <FileWrites Include="$(IntermediateOutputPath)libraryprojectimports.stamp" />
  </ItemGroup>
</Target
```
We would also need to verify the inputs are correct.

@garuma is there an easy way I can reproduce this? or can you attach binlogs?

**Comment by jonathanpeppers** [comment]
@garuma I can reproduce this issue for `_CopyIntermediateAssemblies` with the following test:
```csharp
[Test]
public void CopyIntermediateAssemblies ()
{
	var target = "_CopyIntermediateAssemblies";
	var proj = new XamarinFormsAndroidApplicationProject ();
	using (var b = CreateApkBuilder (Path.Combine ("temp", TestName))) {
		Assert.IsTrue (b.Build (proj), "first build should succeed");
		Assert.IsFalse (b.Output.IsTargetSkipped (target), $"`{target}` should *not* be skipped!");

		var assembly = Path.Combine (Root, b.ProjectDirectory, proj.IntermediateOutputPath, proj.ProjectName + ".dll");
		FileAssert.Exists (assembly);
		File.SetLastWriteTimeUtc (assembly, DateTime.UtcNow);
		File.SetLastAccessTimeUtc (assembly, DateTime.UtcNow);

		Assert.IsTrue (b.Build (proj, doNotCleanupOnUpdate: true, saveProject: false), "second build should succeed");
		Assert.IsTrue (b.Output.IsTargetSkipped (target), $"`{target}` should be skipped on second build!");
	}
}
```

This is going to certainly impact incremental build times... I will probably investigate each target separately and create a PR for each.

**Comment by garuma** [comment]
For reference, we also logged an enhancement in MSBuild itself to potentially surface those type of issues more easily: https://github.com/Microsoft/msbuild/issues/3817
