### ISSUE TITLE
Using the IntermediateOutputPath in Xamarin.Android application and deleting the obj directory near the project source breaks the build.

### ISSUE THREAD

**Issue by ezverev** [xamarin/xamarin-android#2259]
### Steps to Reproduce

1. Create a Xamarin.Android app,
2. Apply the IntermediateOutputPath tweak i.e. append something like this into the .csproj file:

```
  <PropertyGroup>
    <IntermediateOutputPath>C:\Temp\project1</IntermediateOutputPath>
  </PropertyGroup>
```

3. Delete the now-old obj directory which should exist near the .csproj file. Rebuild the app project.

### Expected Behavior
The project should build without a problem.

### Actual Behavior
------ Rebuild All started: Project: PGPolyglotRussian3.Droid, Configuration: Release Any CPU ------
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets(39,3): error MSB3371: The file "obj\project.assets.json.stamp" cannot be created. Could not find a part of the path '<csproj directory>\obj\project.assets.json.stamp'.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

### Version Information

[VS_version_info.txt](https://github.com/xamarin/xamarin-android/files/2441394/VS_version_info.txt)

### Log File

[adb_logcat.txt](https://github.com/xamarin/xamarin-android/files/2441395/adb_logcat.txt)

**Comment by ezverev** [comment]
Here is the repo: [Problem1.zip](https://github.com/xamarin/xamarin-android/files/2441622/Problem1.zip)

**Comment by ezverev** [comment]
In order to make the project build you will have to manually create the **obj** forlder near the project file and create an empty **project.assets.json.stamp** file inside.

**Comment by ezverev** [comment]
Seems to only reproduce with projects with the old **packages.config** style of NuGet referencing.

**Comment by dellis1972** [comment]
This is because the Nuget system uses the `BaseIntermediateOutputPath` property to decide where to put the files (I think). You can try setting that property instead, this should then filter down to the `IntermediateOutputPath`.

**Comment by dellis1972** [comment]
Given that this is NuGet related there isn't much we can do from the Xamarin.Android side.  I would raise the issue on the [NuGet](https://github.com/NuGet/NuGet.Client) this is where the NuGet client code lives. The maintainers there will probably be able to fix or offer some more detailed advice.

**Comment by ezverev** [comment]
Hmm, how does the **project.assets.json.stamp** belong to the NuGet client? It is the Xamarin.Common.targets that is failing, no?

**Comment by ezverev** [comment]
Ok, thanks, I've created the issue there https://github.com/NuGet/Home/issues/7362
