### ISSUE TITLE
Problem with using updated FSharp.Core 

### ISSUE THREAD

**Issue by Dersei** [xamarin/xamarin-android#2270]
### Steps to Reproduce

1. Open new F# Blank App (Android) project
2. Update FSharp.Core nuget to any version higher than 4.0.0.1

### Expected Behavior

Everything should work like at the beginning.

### Actual Behavior

The project cannot be built because of three errors: 

> Error	FS1108	The type 'BigInteger' is required here and is unavailable. You must add a reference to assembly 'System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

> Error	FS0039	The type 'int' is not defined. Maybe you want one of the following:
>    Int16
>    Int32
>    Int64
>    IntPtr
>    Intent	

and

> Error	FS0039	The field, constructor or member 'Add' is not defined.	

First one is connected with whole project and appears only after trying to build.
The second one appears with every `: int` like in `let mutable count:int = 1`. 
The third one is connected with lines:
```FSharp
        button.Click.Add (fun args -> 
            button.Text <- sprintf "%d clicks!" count
            count <- count + 1
        )
```

The second one appears also after defining other variables with aliases as types' names (e.g. float, string)
```FSharp
let test : float = 1.0
let test : string = "test"
```

All problems disappear after adding System.Numerics to project's dependencies.

### Version Information

> Visual Studio 15.8.6

**Comment by jonathanpeppers** [comment]
@nosami can you give some insight here? It is as-if F# > 4.0.0.1 is using `BigInteger` for `int`??? I also see that the newer FSharp.Core is using `netstandard1.6` now, while 4.0.0.1 is PCL.

I can do File | New F# project and just update all the NuGet packages to latest to see this.

**Comment by jonathanpeppers** [comment]
@Dersei it seems that the templates for Visual Studio on Windows are lagging behind VS for Mac slightly.

This is known and being worked on (in a private xamarin repo). I would follow this issue for updates: https://github.com/mono/monodevelop/issues/6253

Closing this for now, as I don't think it is actually an issue with Xamarin.Android, but perhaps F# + Mono. Thanks for the report!
