### ISSUE TITLE
Deploy to multiple devices from visual studio

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [xamarin/xamarin-android#2278]
It is highly unproductive / infeasible during the dev-cycle to use xamarin test cloud as a way to check ui changes across multiple screen sizes. It would be great and a huge time saver if you could select multiple deployment targets when building an app / debugging an app (maybe with ability to select the primary one for actual stepping through the code etc.).

**Comment by mahendranv** [comment]
@jonathanpeppers Is there a direct link to User Voice for this request?

I would like to vote.

**Comment by jonathanpeppers** [comment]
@mahendranv I think this is it: https://developercommunity.visualstudio.com/idea/358520/builddeploy-to-multiple-android-devices-xamarin.html
