### ISSUE TITLE
Concurrent SGen results in a crash

### ISSUE THREAD

**Issue by sdebruyn** [xamarin/xamarin-android#2313]
### Steps to Reproduce

I can reproduce this in our app, but I can't create a repro with a sample project.
This project is under a strict NDA that doesn't allow me to share it. However, I've asked them if they could make an exception.

This is the relevant part of my build settings:

```
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.props" Condition="Exists('..\..\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{18645BB0-965F-4956-AED3-75CE37549EBB}</ProjectGuid>
    <ProjectTypeGuids>{EFBA0AD7-5A72-4C68-AF49-83D382785DCF};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <OutputType>Library</OutputType>
    <TargetFrameworkVersion>v8.1</TargetFrameworkVersion>
    <AndroidApplication>True</AndroidApplication>
    <AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>
    <AndroidResgenClass>Resource</AndroidResgenClass>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
    <MonoAndroidResourcePrefix>Resources</MonoAndroidResourcePrefix>
    <MonoAndroidAssetsPrefix>Assets</MonoAndroidAssetsPrefix>
    <AndroidUseLatestPlatformSdk>false</AndroidUseLatestPlatformSdk>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
    <AndroidTlsProvider>btls</AndroidTlsProvider>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Integration|AnyCPU' ">
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <BundleAssemblies>true</BundleAssemblies>
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
    <Optimize>true</Optimize>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <EnableProguard>true</EnableProguard>
    <DefineConstants>INTEGRATION</DefineConstants>
    <AndroidSupportedAbis>armeabi-v7a</AndroidSupportedAbis>
  </PropertyGroup>
```

#### The project structure:

- solution

- - shared "core" project - .NET Standard 2.0
- - shared "Droid" project

- - - target app 1 "core" project - .NET Standard 2.0
- - - target app 1 "Droid" project

- - - target app 2 "core" project - .NET Standard 2.0
- - - target app 2 "Droid" project

### Expected Behavior

Nothing.

### Actual Behavior

![image](https://user-images.githubusercontent.com/963413/47083778-f61a5d00-d211-11e8-8671-d3e0707d70e9.png)

### Version Information

Actual build is made using this machine: https://github.com/bitrise-io/bitrise.io/blob/650c40e60b1a0e6d5e247dd0827bda8d4bcad11f/system_reports/osx-vs4mac-stable.log

### Log File

See screenshot above.

Right before that log, I also get the following:

![image](https://user-images.githubusercontent.com/963413/47084729-bb65f400-d214-11e8-9aea-c2cbe315e6d5.png)

**Comment by grendello** [comment]
@SamuelDebruyn the `SIGABRT` crash should be accompanied by a managed and native stack trace in the device's log, would you mind pasting the trace from logcat here? It contains vital information needed to diagnose the issue. It will be most likely found in logcat above the `Fatal signal 6...` line. Thanks!
