### ISSUE TITLE
FEATURE_IRIS and FEATURE_FACE not available (Android 9)

### ISSUE THREAD

**Issue by justintoth** [xamarin/xamarin-android#2347]
### Steps to Reproduce

1. Switch to the Beta channel and download/install all updates.
2. Update your Android SDK to include the Android 9.0 SDK.
3. Switch your Android project to target Android 9.0.
4. Try typing "Android.Content.PM.PackageManager.FeatureIris" or "Android.Content.PM.PackageManager.FeatureFace". Notice how PackageManager.FeatureIris and PackageManager.FeatureFace don't exist, so we can't check if these features are available on the device.

### Expected Behavior

These fields should be available so that we can start leveraging the new BiometricPrompt class (e.g. facial recognition within our Android apps) and stop using the FingerprintManager class.

### Actual Behavior

The fields aren't available.

### Version Information

=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.7 Preview (7.7 build 1738)
Installation UUID: 62cf1ad2-0db0-41e1-ac78-aeb509d79f60
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000201

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.201 (2018-06/32d1539629f) (64-bit)
	Package version: 516000201

=== NuGet ===

Version: 4.7.0.5148

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 5.2.1.9 (Visual Studio Community)
Hash: 62840955
Branch: 
Build date: 2018-10-09 19:53:55-0400

=== Xamarin.iOS ===

Version: 12.2.1.9 (Visual Studio Community)
Hash: 62840955
Branch: d15-9
Build date: 2018-10-09 19:53:55-0400

=== Xamarin.Android ===

Version: 9.1.0.38 (Visual Studio Community)
Android SDK: /android/sdk
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Java SDK: /Users/justintoth/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: dd6b1cc3

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707001738
Git revision: 7dc7716c1cf2bdfb1baafd728a09ef805643c15d
Build date: 2018-10-23 14:31:07+00
Build branch: release-7.7
Xamarin extensions: c114276813ea8f259a34bc54b015d7bf711d402b

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Internet of Things (IoT) development (Preview) 7.5.3

**Comment by JonDouglas** [comment]
@justintoth I cannot find these items documented anywhere. Do you have any links to the official documentation of these two items?

I'm also not seeing any note about these items in the `PackageManager` or `BiometricPrompt` class using Android Studio / Android Documentation either.

https://developer.android.com/reference/android/content/pm/PackageManager
https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt

**Comment by justintoth** [comment]
@JonDouglas My mistake, that's what I get for looking at sample code instead of the documentation! You're right that it doesn't look like these constants are available. I'll close this issue, but it does make me wonder how we're supposed to properly test for these capabilities....

**Comment by mrezekial** [comment]
https://developer.android.com/reference/android/content/pm/PackageManager#FEATURE_FACE

Well it's there now.
