### ISSUE TITLE
`AndroidAarLibrary` is not resolving resources properly

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-android#2354]
### Steps to Reproduce

1. Download repro
[App24.zip](https://github.com/xamarin/xamarin-android/files/2527627/App24.zip)
2. Restore packages
3. Try to build project
4. You can try the `28.0.0-preview5` version of the packages to experience a build where the bindings use `LibraryProjectZip` instead of `AndroidAarLibrary` and the build works correctly.

### Expected Behavior

Compiles cleanly.

### Actual Behavior

Errors: ` No resource identifier found for attribute 'layout_behavior' in package...`  

It looks like something isn't working quite right with `AndroidAarLibrary` item types.  This works fine if I continue to embed the .aar as a `LibraryProjectZip` in the .dll.

**Comment by dellis1972** [comment]
Yay,an Issue with a full repo :D

**Comment by dellis1972** [comment]
@Redth can we close this issue ? I believe its down to MSbuild not resolving the library .target files.

**Comment by Redth** [comment]
Yep
