### ISSUE TITLE
$(AndroidUseAapt2) runs ConvertResourcesCases a lot

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#2356]
### Steps to Reproduce

1. Enable `$(AndroidUseAapt2)` in a Xamarin.Forms project
2. You will see `ConvertResourcesCases` run ~9 times

See https://github.com/xamarin/xamarin-android/pull/2348, where I saw this firsthand. I think if we fixed this, `$(AndroidUseAapt2)` could possibly be enabled by default?

### Expected Behavior

With `$(AndroidUseAapt2)`, `ConvertResourcesCases` should take approximately the same amount of time as a build _without_ `$(AndroidUseAapt2)`.

### Actual Behavior

`$(AndroidUseAapt2)` runs `ConvertResourcesCases` a bit too much.

### Version Information

Reports of this in the 15.9 preview, and I have reproduced on master.

### Log File

[ConvertResourcesCases3.zip](https://github.com/xamarin/xamarin-android/files/2530629/ConvertResourcesCases3.zip)

**Comment by dellis1972** [comment]
When `Aapt2` is enabled we have to generate a `flata` archive for each library resource (i.e everything in the `lp` directory. As part of that process we are calling `ConvertResourcesCases` to ensure that the library resources are fixed up BEFORE we put them in the `flata`. This happens on the very first build of the app, and unless a `Clean` is called will be a one off. `aapt2` will then use those `flata` files in the `link` process later in the build. 

Now we could make use of the new logic to Skip `ConvertResourcesCases` for those known libraries which we know do not need processing so help speed things up.

**Comment by jonathanpeppers** [comment]
What I'm seeing from [these logs](https://github.com/xamarin/xamarin-android/files/2530629/ConvertResourcesCases3.zip), if I just pick one of the files `ConvertResourcesCases` is processing, this log shows up 9 times during the initial build:
```
  Processing: C:\Users\myuser\Desktop\Git\xamarin-android\tests\Xamarin.Forms-Performance-Integration\Droid\obj\Debug\90\lp\22\jl\res\values\values.xml   10/30/2018 4:28:18 PM > 1/1/0001 12:00:00 AM
```

So it would be ok for `ConvertResourcesCases` to run 9 times, if it wasn't running on the same files. But looking at `ConvertResourcesCases`, it seems like it's meant to run on all of them in one shot...

I'm wondering if `ConvertResourcesCases` could be moved to a new target and use `DependsOnTargets`? Then it could probably be setup to run once during the build? I will test and see if this breaks anything.

**Comment by dellis1972** [comment]
Ah right, yes. That is probably it. `Aapt2` will need to run for each `lp` but the conversion should only run either across the whole lot or only for the `res` dir for that `lp`.
