### ISSUE TITLE
StatusBarVisibility enum is not marked with Flags attribute

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/xamarin-android#2372]
I'm doing a bitwise operation in a custom Xamarin Forms renderer to toggle a visibility flag on and off.

// off
`activity.Window.DecorView.SystemUiVisibility &= ~(StatusBarVisibility)SystemUiFlags.LightStatusBar;`

// on
`activity.Window.DecorView.SystemUiVisibility = (StatusBarVisibility)SystemUiFlags.LightStatusBar;`

Resharper issues a warning that says the bitwise operation is being done on an enum that doesn't have a [Flags] attribute. Is it possible for you to add this to `StatusBarVisibility`?

**Comment by dellis1972** [comment]
The PR #2526 could not be merged since in introduced a breaking change to our api. We should try to fix this for d16-1 and provide an overload so that older applications can still function as they do now.
