### ISSUE TITLE
Link away old *Handler methods when using the new marshal methods

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#2375]
We do not want to preserve these old marshal methods in the linked assemblies as they should not be used anymore.

That will reduce the assembly size and thus might improve the performance a bit too.

Originally I thought we might need to add a property to preserve them when needed. The handler methods are private though, so we don't need that.

**Comment by grendello** [comment]
Revision 8bc7a3e84f95e70fe12790ac31ecd97957771cb2 does that as part of the marshal methods implementation.
