### ISSUE TITLE
Deployment for debugging on emulators with android 4 fails because of wrong pm option

### ISSUE THREAD

**Issue by babakRz63ai** [xamarin/xamarin-android#2391]
### Steps to Reproduce

1. Create a new android application project
2. Set target SDK version to 28  
3. Set Minimum SDK version to 15
4. Create and start an emulator with android 4.0 or 4.1 (API 15 or 16)
5. Build and try to start the application in the Debug mode

### Expected Behavior
Application get installed and start running

### Actual Behavior
An error dialog appears telling there was deployment errors. content of the output window is in the logfile.

### Version Information
Microsoft Visual Studio Community 2017 Preview
Version 15.9.0 Preview 4.0
VisualStudio.15.Preview/15.9.0-pre.4.0+28219.56
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Community

C# Tools   2.10.0-beta2-63410-10+45b371170fd8f9f3e9c14ea2a71d17db9469f8b7
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   4.13.11-pre (400cfb1)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   2.10.0-beta2-63410-10+45b371170fd8f9f3e9c14ea2a71d17db9469f8b7
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 5e9c7caea813f8aa3277e8cc843f784488a7da6f.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.60 (d15-9@cd24721c9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.21 (3b929fe22)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.124 (a4f6b98)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.0.37 (HEAD/3e731613f)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.9 (6284095)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		ADB0000:  Deployment failed
Mono.AndroidTools.InstallFailedException: Unexpected install output: Error: Unknown option: -d
usage: pm list packages [-f] [-d] [-e] [-s] [-e] [-u] [FILTER]
       pm list permission-groups
       pm list permissions [-g] [-f] [-d] [-u] [GROUP]
       pm list instrumentation [-f] [TARGET-PACKAGE]
       pm list features
       pm list libraries
       pm path PACKAGE
       pm install [-l] [-r] [-t] [-i INSTALLER_PACKAGE_NAME] [-s] [-f] PATH
       pm uninstall [-k] PACKAGE
       pm clear PACKAGE
       pm enable PACKAGE_OR_COMPONENT
       pm disable PACKAGE_OR_COMPONENT
       pm disable-user PACKAGE_OR_COMPONENT
       pm set-install-location [0/auto] [1/internal] [2/external]
       pm get-install-location
       pm createUser USER_NAME
       pm removeUser USER_ID

pm list packages: prints all packages, optionally only
  those whose package name contains the text in FILTER.  Options:
    -f: see their associated file.
    -d: filter to only show disbled packages.
    -e: filter to only show enabled packages.
    -s: filter to only show system packages.
    -3: filter to only show third party packages.
    -u: also include uninstalled packages.

pm list permission-groups: prints all known permission groups.

pm list permissions: prints all known permissions, optionally only
  those in GROUP.  Options:
    -g: organize by group.
    -f: print all information.
    -s: short summary.
    -d: only list dangerous permissions.
    -u: list only the permissions users will see.

pm list instrumentation: use to list all test packages; optionally
  supply <TARGET-PACKAGE> to list the test packages for a particular
  application.  Options:
    -f: list the .apk file for the test package.

pm list features: prints all features of the system.

pm path: print the path to the .apk of the given PACKAGE.

pm install: installs a package to the system.  Options:
    -l: install the package with FORWARD_LOCK.
    -r: reinstall an exisiting app, keeping its data.
    -t: allow test .apks to be installed.
    -i: specify the installer package name.
    -s: install package on sdcard.
    -f: install package on internal flash.

pm uninstall: removes a package from the system. Options:
    -k: keep the data and cache directories around after package removal.

pm clear: deletes all data associated with a package.

pm enable, disable, disable-user: these commands change the enabled state
  of a given package or component (written as "package/class").

pm get-install-location: returns the current install location.
    0 [auto]: Let system decide the best location
    1 [internal]: Install on internal device storage
    2 [external]: Install on external media

pm set-install-location: changes the default install location.
  NOTE: this is only intended for debugging; using this can cause
  applications to break and other undersireable behavior.
    0 [auto]: Let system decide the best location
    1 [internal]: Install on internal device storage
    2 [external]: Install on external media

   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\21\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 345
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\21\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 753
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()		 	0	
```

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '15.9' that is not in the list of supported values

**Comment by dellis1972** [comment]
This looks like this is the line causing the problem 

https://github.com/xamarin/androidtools/blob/6757427b1e4c0f710f044ffb06686d91de247bb6/Mono.AndroidTools/Internal/AdbShellCommand.cs#L104

and 

https://github.com/xamarin/androidtools/blob/728dab579da21ff30a0afd087ec35b9f737d52a1/Xamarin.AndroidTools/Devices/AndroidDeviceExtensions.cs#L184

**Comment by dellis1972** [comment]
the version of `pm` on the device does not support the `-d` option on the `install` command. Does it work on a newer device?

**Comment by dellis1972** [comment]
what version of `adb` do you have installed?

**Comment by dellis1972** [comment]
My version 

```
Android Debug Bridge version 1.0.40
Version 4797878
```

supports the `-d`

**Comment by brendanzagaeski** [comment]
For cross-referencing, @JonDouglas took a first look at reproducing this and was able to reproduce the reported behavior on an API 16 emulator:

> I can reproduce against API 16, it takes almost 10 minutes to hang before spitting out the ADB0010/ADB0000 regarding the unknown -d option

**Comment by dellis1972** [comment]
Potential fix up at https://github.com/xamarin/androidtools/pull/158

**Comment by matteozoni** [comment]
I have installed today VS 15.9.1 and I have the same issue

**Comment by matteozoni** [comment]
@dellis1972 thank you very much for the information

**Comment by Courahee** [comment]
I have a similar issue and I think it is because I upgraded to VS2017 15.9.1. Before the upgrade my app was running fine on a Symbol MC3200 (Android v4.1 - Jellybean). After the upgrade I get this error when trying to deploy to the barcode scanner:

Severity	Code	Description	Project	File	Line	Suppression State
Error		ADB0000:  Deployment failed
Mono.AndroidTools.InstallFailedException: Unexpected install output: Error: Unknown option: -d
at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\36\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 345
at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\36\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 753
at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
