### ISSUE TITLE
Application crashes on emulators with android 4.0 or 4.1 (API 15 and 16) and architecture X86

### ISSUE THREAD

**Issue by babakRz63ai** [xamarin/xamarin-android#2393]
### Steps to Reproduce

1. Create a new Hello World application
2. Set target SDK version to android 9
3. Set minimum SDK version to android 4.0 or API 15
4. Disable 'Use shared runtime' option in Android options
5. Build and deploy the application on an emulator with API 15 or 16 and X86 architecture 

### Expected Behavior
Application should run normally

### Actual Behavior
The app crashes and the 'Unfortunately, some app stopped' appears.

### Version Information
Microsoft Visual Studio Community 2017 Preview
Version 15.9.0 Preview 4.0
VisualStudio.15.Preview/15.9.0-pre.4.0+28219.56
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Community

C# Tools   2.10.0-beta2-63410-10+45b371170fd8f9f3e9c14ea2a71d17db9469f8b7
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   4.13.11-pre (400cfb1)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   2.10.0-beta2-63410-10+45b371170fd8f9f3e9c14ea2a71d17db9469f8b7
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 5e9c7caea813f8aa3277e8cc843f784488a7da6f.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.60 (d15-9@cd24721c9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.21 (3b929fe22)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.124 (a4f6b98)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.0.37 (HEAD/3e731613f)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.9 (6284095)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

```
I/ActivityManager( 1390): Process App1TestXmr.App1TestXmr (pid 2685) has died.

W/InputMethodManagerService( 1390): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@af1c3e90 attribute=null

I/LocationManagerService( 1390): request passive (pid 1390) 0 0

W/DownloadManager( 1887): Aborting request for download 1: while trying to execute request: org.apache.http.conn.ConnectTimeoutException: Connect to /2a00:1450:4010:c0a::65:443 timed out

W/DownloadManager( 1887): Aborting request for download 2: while trying to execute request: org.apache.http.conn.ConnectTimeoutException: Connect to /2a00:1450:4010:c0a::65:443 timed out

I/ActivityManager( 1390): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=App1TestXmr.App1TestXmr/md576f79108e0732f785a03de2985ca5c27.MainActivity u=0} from pid 2223

W/WindowManager( 1390): Failure taking screenshot for (246x410) to layer 21005

D/dalvikvm( 2721): Not late-enabling CheckJNI (already on)

I/ActivityManager( 1390): Start proc App1TestXmr.App1TestXmr for activity App1TestXmr.App1TestXmr/md576f79108e0732f785a03de2985ca5c27.MainActivity: pid=2721 uid=10048 gids={3003, 1028}

D/EGL_emulation( 2223): eglMakeCurrent: 0xb78f3e08: ver 2 0

D/gralloc_ranchu( 1141): gralloc_alloc: Creating ashmem region of size 1536000

E/Trace   ( 2721): error opening trace file: Permission denied (13)

I/ActivityThread( 2721): Pub App1TestXmr.App1TestXmr.mono.MonoRuntimeProvider.__mono_init__: mono.MonoRuntimeProvider

D/AndroidRuntime( 2721): Shutting down VM

W/dalvikvm( 2721): threadid=1: thread exiting with uncaught exception (group=0xae5ef228)

E/AndroidRuntime( 2721): FATAL EXCEPTION: main

E/AndroidRuntime( 2721): java.lang.UnsatisfiedLinkError: Couldn't load monodroid: findLibrary returned null

E/AndroidRuntime( 2721): 	at java.lang.Runtime.loadLibrary(Runtime.java:365)

E/AndroidRuntime( 2721): 	at java.lang.System.loadLibrary(System.java:535)

E/AndroidRuntime( 2721): 	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:34)

E/AndroidRuntime( 2721): 	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:22)

E/AndroidRuntime( 2721): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4560)

E/AndroidRuntime( 2721): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)

E/AndroidRuntime( 2721): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)

E/AndroidRuntime( 2721): 	at android.app.ActivityThread.access$1300(ActivityThread.java:130)

E/AndroidRuntime( 2721): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)

E/AndroidRuntime( 2721): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/AndroidRuntime( 2721): 	at android.os.Looper.loop(Looper.java:137)

E/AndroidRuntime( 2721): 	at android.app.ActivityThread.main(ActivityThread.java:4745)

E/AndroidRuntime( 2721): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime( 2721): 	at java.lang.reflect.Method.invoke(Method.java:511)

E/AndroidRuntime( 2721): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)

E/AndroidRuntime( 2721): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)

E/AndroidRuntime( 2721): 	at dalvik.system.NativeStart.main(Native Method)

E/jdwp    ( 2721): Failed writing handshake bytes: Broken pipe (-1 of 14)

D/dalvikvm( 2721): Debugger has detached; object registry had 0 entries

W/ActivityManager( 1390):   Force finishing activity App1TestXmr.App1TestXmr/md576f79108e0732f785a03de2985ca5c27.MainActivity

W/WindowManager( 1390): Failure taking screenshot for (246x410) to layer 21010

D/gralloc_ranchu( 1141): gralloc_alloc: Creating ashmem region of size 368640

W/ActivityManager( 1390): Activity pause timeout for ActivityRecord{af2306b8 App1TestXmr.App1TestXmr/md576f79108e0732f785a03de2985ca5c27.MainActivity}

D/EGL_emulation( 2223): eglMakeCurrent: 0xb78f3e08: ver 2 0

D/gralloc_ranchu( 1141): gralloc_alloc: Creating ashmem region of size 368640

D/gralloc_ranchu( 1141): gralloc_alloc: Creating ashmem region of size 368640

I/Process ( 2721): Sending signal. PID: 2721 SIG: 9

I/ActivityManager( 1390): Process App1TestXmr.App1TestXmr (pid 2721) has died.

W/InputMethodManagerService( 1390): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@af168780 attribute=null
```

**Comment by brendanzagaeski** [comment]
Thanks for the report! This error arises on older Android OS versions when attempting to launch a Xamarin.Android application APK that does not contain a *monodroid* native library that matches the target architecture of the emulator or device.

To resolve the issue, navigate to **Project properties > Android Options > Advanced \[button\]** in your project and add **x86** to the list of **Supported architectures**.

Cross-reference: https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#release-apps-fail-to-launch-on-device

More recent Android OS versions block installation of the APK in this case with a nicer error message from `pm install`:

> ADB0010: Failure \[INSTALL\_FAILED\_NO\_MATCHING\_ABIS: Failed to extract native libraries, res=-113\]

I'll mark this item for consideration as a possible future enhancement for the Xamarin tools to check the architecture of the target device themselves so that they can give a nicer error on older ABI levels. Perhaps both a deploy-time check and a run-time check can be added.

**Comment by babakRz63ai** [comment]
Thanks, and sorry I didn't checked the list of supported ABI's.

**Comment by jpobst** [comment]
The minimum supported API for Xamarin.Android is now API-19, so this issue is no longer relevant.
