### ISSUE TITLE
Cookie Container not working on Xamarin.Android

### ISSUE THREAD

**Issue by darkdoctor** [xamarin/xamarin-android#2395]
We just made a library as Data Access Object for our Web Service using .NET 4.5 Framework.
That library will be used for different platforms, like Winform, Console app, Asp.net, and XAMARIN ANDROID.

We have a problem with the COOKIE CONTAINER when our Xamarin app on Android uses the library, the cookie container does not send the cookies to the server, but when we test with Console App, it works pretty fine.

**Comment by brendanzagaeski** [comment]
Thanks for the report! For us to investigate this further, if you could attach a zipped up sample project that demonstrates the issue, that would be perfect. Thanks in advance!

**Comment by brendanzagaeski** [comment]
Ah, thanks! That's a helpful additional piece of information. Xamarin.Android is not designed to have binary compatibility with assemblies compiled against the desktop .NET and Mono profiles. It is compatible with assemblies compiled against the Xamarin.Android profile or the .NET Standard specification. So libraries that are used in a Xamarin.Android app need to be built against one of those options to work as expected. 

For a little additional background info about the compatible profiles see: https://docs.microsoft.com/xamarin/cross-platform/internals/available-assemblies

I'll tentatively close this issue accordingly, but feel free to reply back if I've misunderstood the scenario. Thanks!
