### ISSUE TITLE
Page styleclass css async

### ISSUE THREAD

**Issue by xamarinhalit** [xamarin/xamarin-android#2399]
### Steps to Reproduce

1.  onappering binding page then method used with Task async then cannot load style.css  
2. 
3. 

### Expected Behavior
OnApparing() -> in Page-> BindingContext

**Comment by grendello** [comment]
@xamarinhalit Would you mind creating and attaching a simple application which demonstrates the issue you're seeing? Alas, with the currently available information we won't be able to investigate the issue, thanks!

**Comment by jonathanpeppers** [comment]
@xamarinhalit closing for now as we haven't heard from you for a while.

Reading what information you have here (names of Xamarin.Forms types/methods), I would consider posting an issue in Xamarin.Forms: https://github.com/xamarin/Xamarin.Forms/issues

Feel free to comment/reopen if you can give more info, thanks!
