### ISSUE TITLE
Remove the use of EmbeddedNativeLibrary from Mono.Posix and Mono.Data.Sqlite

### ISSUE THREAD

**Issue by dellis1972** [xamarin/xamarin-android#2407]
We currently embed the required native libraries for Mono.Data.Sqlite and Mono.Posix into the assembly as an EmbeddedResource (`__AndroidNativeLibraries__.zip`). This is then extracted as part of the build process into the apk. This is the only actual change we have from the vanilla versions of both of these assemblies. 

We should update our build system to special case these two assemblies and just copy over/include the required native libraries from the installed Xamarin.Android system. The required files are

`libsqlite3_xamarin.so`
`libMonoPosixHelper.so`

both of which should end up in the `lib` directory of the Xamarin.Android MSBuild install directory. Currently only `libMonoPosixHelper.so` does.

**Comment by Redth** [comment]
Could we also add a different item group name to be able to specify these not inside the .DLL similar to how we now have `AndroidAarLibarary`?

**Comment by dellis1972** [comment]
You should be able to use `NativeLibrary` for that already (I think)
