### ISSUE TITLE
[spec] Enable Embedded DSO Support via android:extractNativeLibs="false"

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#2415]
## Problem

Currently, in order to activate the embedded DSO support, one has to perform the following actions manually:

1. Add the `android:extractNativeLibs="false"` attribute to the `<application>`
element in the `Properties/AndroidManifest.xml` file.

2. Add the following property to the project file:
```xml
<AndroidStoreUncompressedFileExtensions>.so</AndroidStoreUncompressedFileExtensions>
```
3. Add an android environment file to the project with a line which says:
```
__XA_DSO_IN_APK=1
```

## Proposal

The presence of `android:extractNativeLibs="false"` in `AndroidManifest.xml` should setup all the extra "stuff" so developers don't have to manually do it.

`android:extractNativeLibs="false"` would automatically do the following:

1. `.so` will be appended to `$(AndroidStoreUncompressedFileExtensions)`. Both the `<Aapt/>` and `<BuildApk/>` MSBuild tasks use this property.

3. A new generated file in `$(IntermediateOutputPath)` will add `__XA_DSO_IN_APK=1` as an `@(AndroidEnvironment)` build item.

> VS bug [#758653](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/758653)

**Comment by jonathanpeppers** [comment]
Questions I had:
- Should the property be `AndroidEnableEmbeddedDSOs`, or should it be named after "Android Things"?
- How soon should we implement this? Do we have an easy way to figure out how many devs are currently doing this manually?

**Comment by grendello** [comment]
> Questions I had:
> 
>     * Should the property be `AndroidEnableEmbeddedDSOs`, or should it be named after "Android Things"?

No, it's not limited to Android Things. Additionally, it's not optional for Android Things, so any project targetting that platform will always set the property unconditionally.

**Comment by jonathanpeppers** [comment]
Ok, so this feature is new, no one is using it.

Right now it's so hard to use... it's not ideal.

**Comment by JonDouglas** [comment]
> * Should the property be AndroidEnableEmbeddedDSOs, or should it be named after "Android Things"?

This is used in other types of Android projects meeting the Marshmallow+ guidelines and where setting that manifest attribute will force one to store uncompressed libraries in the APK or else fail at install time. Android Things has a requirement to follow this when uploading an APK to the Android Things Console.

I would say that the first naming makes most sense given the use of `EmbeddedDSOs` throughout the properties, tasks, etc.

> * How soon should we implement this? Do we have an easy way to figure out how many devs are currently doing this manually?

We do not have a great metric here other than two noisy GitHub issues(https://github.com/xamarin/xamarin-android/issues/1906, https://github.com/xamarin/xamarin-android/issues/1819) as it's new and requires 3 flags to opt-into. We do want to unblock the workload of Android Things publishing and using `android:extractNativeLibs="false"` in Android Projects to reduce APK size.

**Comment by jonathanpeppers** [comment]
@JonDouglas @grendello 

@dellis1972 mentioned the possibility of just using `android:extractNativeLibs="false"` in the manifest to enable this behavior. Then we wouldn't need a new MSBuild property. Changing the manifest would automatically add `.so` to `$(AndroidStoreUncompressedFileExtensions)` and  set `__XA_DSO_IN_APK=1`.

Does that option seem better/worse?

**Comment by dellis1972** [comment]
from a user perspective, hitting a checkbox on the manifest editor and having our system do the right thing I think is better.

**Comment by JonDouglas** [comment]
@jonathanpeppers @dellis1972 I think that would be the best option as we would not have to worry about maintaining another MSBuild property and surfacing it through the IDEs. 

👍

**Comment by jonathanpeppers** [comment]
I'll redo the spec above before I start on this. Sounds good.
