### ISSUE TITLE
There can be (too) many jnimarshalmethod-gen warnings in the build output

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#2419]
I think the problem is that we now compare the `$(_AndroidJniMarshalMethodsFlag)` flag file against the relevant assemblies, which is fine. We then go to generate marshal methods in them and that's not fine as some of them might not have changed. And that means a lot of warnings.

* Fix: generate the marshal methods only in changed or new assemblies

* Proposal: another thing is that we might only generate limited number of similar warnings in `jnimarshalmethod-gen.exe` and then only report  number of those at the end. That might be overriden by  verbose `-v` option

**Comment by grendello** [comment]
`jnimarshalmethod-gen.exe` was superseded by marshal methods (8bc7a3e84f95e70fe12790ac31ecd97957771cb2 and others)
