### ISSUE TITLE
Update AndroidSdkBuildToolsVersion 

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#2433]
For sanity/consistency, [`$(AndroidSdkBuildToolsVersion)`](https://github.com/xamarin/xamarin-android/blob/c38c58e9c5634819845350e9e687186c0808a781/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets), `$(AndroidSdkPlatformToolsVersion)`, and `$(AndroidSdkToolsVersion)` should be updated to be consistent with the latest supported `$(TargetFrameworkVersion)`.  As we now support v9.0 (API-28), these properties should be updated to use the 28 versions of these packages, e.g. build-tools 28.0.3:

https://developer.android.com/studio/releases/build-tools

Addtionally, we should update the [`HowToAddNewApiLevel.md`](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/HowToAddNewApiLevel.md) docs should be updated to mention that these properties should be updated when a new API level is added.

**Comment by awattar** [comment]
In which Xamarin.Android version it will land?
