### ISSUE TITLE
Add support for dedup of native AOT'ed code

### ISSUE THREAD

**Issue by alexanderkyte** [xamarin/xamarin-android#2434]
Mono added support for deduplication of AOT'ed code a while back. It leads to a noticeable reduction in binary size. It's currently being used with WebAssembly and it's being integrated into xamarin-macios

It requires minor changes to the build integration to work.

It works by making two passes
1) In the first pass, all code that can't be duplicated is emitted.
2) In the second pass, all of the potentially duplicated code, for all of the input assemblies, is placed in a single aot module that acts as a "container" or "dummy" assembly for them. 

The iOS integration of it is here: https://github.com/xamarin/xamarin-macios/pull/3783 . This should provide a concrete example of how to add this support. 

1) Create another assembly during the build that's empty (we'll call it DummyName.dll)
2) Create phase 1 above by aoting with `--aot=dedup-skip`
3) Create phase 2 by aoting with a single mono invocation and all assemblies passed (including the dummy), and `--aot=dedup-include=DummyName.dll`
4) Make sure DummyName.dll is bundled/registered/loaded before main is run.

The rest should be handled by the loading machinery. We mark the DummyName.dll.so as a special aot module and do all of the fixes to code finding once it's loaded.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
