### ISSUE TITLE
Breakpoints not being hit on debug

### ISSUE THREAD

**Issue by michaelkolovrat** [xamarin/xamarin-android#2438]
Hello,
I have an issue with breakpoints not being hit in debug mode. Tried unchecking the 'Build with MSBuild instead of xbuild' box in my VS Preferences but then I get a following error:

**src/packages/Xamarin.GooglePlayServices.Basement.60.1142.1/build/MonoAndroid80/Xamarin.GooglePlayServices.Basement.targets (SetupGoogleServicesJson target) ->

: error : Error initializing task ConvertToAbsolutePath: Not registered task ConvertToAbsolutePath.**

After removing the entire package from the csproj file (Import Project/Condition snippet), another error is triggered:

**/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets (_ResolveAssemblies target) ->

: error : Could not load file or assembly 'NuGet.Common, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

at Xamarin.Android.Tasks.ResolveAssemblies.b__44_0 () [0x0000e] in <96027da06dd5411688a31011072e256f>:0 
at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2886 
at System.Threading.Tasks.Task.Execute () [0x00010] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2509**

Any idea as to how to resolve this?

Thanks!

### Version Information

=== Visual Studio Community 2017 for Mac ===

Version 7.5.4 (build 3)
Installation UUID: b66baa90-5b21-4648-9e17-18bcecd3a526
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Version: 2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/mkolovrat/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.0 (13247)
Build 9A235

=== Xamarin.Mac ===

Version: 3.8.1.0 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705040003
Git revision: 6ae731889c896d6733efb8ff5117f5bf5b17b509
Build date: 2018-07-19 13:07:45-04
Xamarin addins: 417fed09624e1e1f76ab0a11e8b97ffd8bbf91e1
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Mon Nov 13 21:56:25 PST 2017
    root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

**Comment by grendello** [comment]
@michaelkolovrat debugging support is not related to how you build the application (as long as the build includes the debugging symbols, of course) so your change to not use MSBuild will not make a difference in this regard. The errors you're seeing after disabling MSBuild stem from the fact that Xamarin.Android apps must absolutely be built with MSBuild these days, the older Mono implementation of it, xbuild, is no longer supported and doesn't work. Unfortunately, none of the information you provided can help us in identifying the debugger problem. In order to attempt to identify the issues you're having we'd require at least the following information:

  * Your deployment target (emulator, device)
  * IDE logs while *starting and running* the debug session, any error messages you might spot in the UI as well
  * `adb logcat` output for debugging session startup and duration

Thanks!

**Comment by michaelkolovrat** [comment]
The emulator is a custom AVD (Platform 6.0, API level 23, Nexus 4 device, Google APIs Intel Atom x86_64). The device is an LG K8, Android 7.1.2

Breakpoints don't get hit regardless of whether I build the project on emulator or device. Even tried reverting to Mono 4.8.1, removing "." from the project filename (filename.UI.Android > filenameUIAndroid) and refactoring the entire project, physically deleting bin and obj folders before building the project, everything to no avail... 


Attached are the app outputs for both emulator and device, as well as adb logcats for both:

[logcat-device.txt](https://github.com/xamarin/xamarin-android/files/2600127/logcat-device.txt)
[appoutput-device.docx](https://github.com/xamarin/xamarin-android/files/2600145/appoutput-device.docx)
[logcat-emulator.txt](https://github.com/xamarin/xamarin-android/files/2600147/logcat-emulator.txt)
[appoutput-emulator.docx](https://github.com/xamarin/xamarin-android/files/2600150/appoutput-emulator.docx)

**Comment by michaelkolovrat** [comment]
Initially I had it on Full.
Then I tried switching it to Portable, Symbols only, Embedded and None, as per your instructions. No luck...
Also I've defined both TRACE and DEBUG symbols.

Starting to think it may have to do with where exactly in the project am I setting the breakpoints to hit.. It's a fonts class (Fonts.cs). Basically, I'm trying to stop the project on an Init method in the class, to read off of a font variable and see if the correct font has been loaded.
Is it even possible to hit a breakpoint on a fonts class?

**Comment by jonathanpeppers** [comment]
@michaelkolovrat could you make a quick sample project using your `Fonts` class?

Any luck using the latest stable VS for Mac?

**Comment by jonathanpeppers** [comment]
@michaelkolovrat closing for now, as we haven't heard back in a while.

Feel free to comment/reopen if you can get us an update. Thanks!

**Comment by BehnamAbdy** [comment]
in my case it was ridiculous, in the emulator the network data was off, turning it on solved the problem
