### ISSUE TITLE
Mono.Android-Tests and Xamarin.Forms-Performance-Integration should build against system instalation

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#2442]
The https://github.com/xamarin/xamarin-android/pull/2153 added dependency on `_CreateJavaInteropDllConfigs` target, which only works inside the XA build.

I should make the target conditional, so that these tests are still possible to build outside of XA source tree.

**Comment by pjcollins** [comment]
This was also discussed in https://github.com/xamarin/xamarin-android/issues/2683.

Should be resolved in:
https://github.com/xamarin/xamarin-android/pull/3042
and
https://github.com/xamarin/xamarin-android/pull/3235
