### ISSUE TITLE
VS2017 xamarin android project cannot be created unless run as administrator

### ISSUE THREAD

**Issue by MasoudShah** [xamarin/xamarin-android#2446]
After updating visual studio to version 15.9.1, xamarin android project cannot be created and the project folder is empty. Visual studio shows the error "object reference not set to an instance of an object" at the moment the project is going to be created, and after that nothing gets created. This error can be avoided only by running visual studio in run as administrator mode.

**Comment by MasoudShah** [comment]
Hi @joj! This is the link of the report:
[https://developercommunity.visualstudio.com/content/problem/392571/vs2017-xamarin-android-project-cannot-be-created-u.html](url)

**Comment by joj** [comment]
@MasoudShah I closed it duplicate to get votes on the other issue, but still super useful (I get logs from yours too). Meaning, don't think I ignored or didn't need your issue. It really helps. I'll close this one too now and concentrate on the developer community issue.

**Comment by MasoudShah** [comment]
Thanks for consideration. I hope it gets solved in the next update.
