### ISSUE TITLE
VS2017 can not build xamarin android project if it has BuildNativeLibs target

### ISSUE THREAD

**Issue by amagaev** [xamarin/xamarin-android#2451]
I have a project which has additional pre-build step for building native android library by using ndk-build.

I want to add a dependency on "AndroidPrepareForBuild" target to check that all sdk paths have been resolved correctly before ndk-build call.

`
  <Target Name="BuildNativeLibs" DependsOnTargets="AndroidPrepareForBuild" Inputs="jni\Android.mk;jni\Application.mk" Outputs="@(AndroidNativeLibrary)">
    <Exec Command="$(AndroidNdkDirectory)\ndk-build -C jni" />
  </Target>
`

But after that VS can not build my project with some errors with resources:

`
1>NdkExample\NdkExample\obj\Debug\81\android\manifest\AndroidManifest.xml(7): error APT0000: No resource found that matches the given name (at 'icon' with value '@mipmap/ic_launcher').
1>NdkExample\NdkExample\obj\Debug\81\android\manifest\AndroidManifest.xml(7): error APT0000: No resource found that matches the given name (at 'label' with value '@string/app_name').
1>NdkExample\NdkExample\obj\Debug\81\android\manifest\AndroidManifest.xml(7): error APT0000: No resource found that matches the given name (at 'roundIcon' with value '@mipmap/ic_launcher_round').
1>NdkExample\NdkExample\obj\Debug\81\android\manifest\AndroidManifest.xml(7): error APT0000: No resource found that matches the given name (at 'theme' with value '@style/AppTheme').
1>NdkExample\NdkExample\obj\Debug\81\android\manifest\AndroidManifest.xml(8): error APT0000: No resource found that matches the given name (at 'label' with value '@string/app_name').
1>NdkExample\NdkExample\obj\Debug\81\android\manifest\AndroidManifest.xml(8): error APT0000: No resource found that matches the given name (at 'theme' with value '@style/AppTheme.NoActionBar').
`

Seems like I have some conflict with some another target which used for preparing resources.

NdkExample.zip attached.

### Note

This error can be avoided if move BuildNativeLibs target to separated Android binding project and use EmbeddedNativeLibrary instead of AndroidNativeLibrary

[NdkExample.zip](https://github.com/xamarin/xamarin-android/files/2603403/NdkExample.zip)

**Comment by dellis1972** [comment]
Can you provide the build output for the sample? (incase we cannot repo). Best way to do that these days is to add a `/bl` to a command line build and upload the resulting `msbuild.binlog`.

**Comment by dellis1972** [comment]
Btw I just tried to repo and I cannot repo on MacOS.  The `APT0000` are usually down to a failure to restore Nuget package resources. Can you let us know which version of Xamarin.Android you are using and maybe upgrade to the latest (or latest preview) and see if that helps.

**Comment by amagaev** [comment]
This issue is reproduced only on windows.

[msbuild_binlog.zip](https://github.com/xamarin/xamarin-android/files/2617118/msbuild_binlog.zip)


**Visual Studio Info**

Microsoft Visual Studio Enterprise 2017 
Version 15.9.2
VisualStudio.15.Release/15.9.2+28307.108

Xamarin   4.12.3.72 (d15-9@7b34d2bf1)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   9.1.0.38 (HEAD/61d16aa23)
Xamarin.Android Reference Assemblies and MSBuild support.

**Comment by grendello** [comment]
Considering [this comment](https://github.com/xamarin/xamarin-android/issues/2451#issuecomment-460680502), I'm closing this issue. Please reopen if the problem persists.
