### ISSUE TITLE
`AndroidSdkBuildToolsVersion` is not exported in binding projects

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-android#2452]
Looks like the msbuild property `AndroidSdkBuildToolsVersion` is not being exported in binding projects.

Here's a binlog with an example of it:

[binlog.zip](https://github.com/xamarin/xamarin-android/files/2605457/binlog.zip)

**Comment by awattar** [comment]
Was this ever landed in VS17 stable channel?

**Comment by jonathanpeppers** [comment]
@awattar this should be in the VS 2019 previews.

A workaround, is you could just add this value in your csproj:
```xml
<AndroidSdkBuildToolsVersion>27.0.3</AndroidSdkBuildToolsVersion>
```
Depends on the error you are getting these are the values I changed: https://github.com/xamarin/xamarin-android/pull/2465/files#diff-dd33717a50863f225641c5b08ddbd2f9R15

**Comment by awattar** [comment]
@jonathanpeppers thanks for the confirmation. Will after the fix VerifyVersionsTask be able to use correct and most suitable AndroidSdkBuildToolsVersion find in ResolveAndroidTooling or I'll need still give him a hint from the workaround?
