### ISSUE TITLE
VS 2017 15.9.2 axml code broken

### ISSUE THREAD

**Issue by felipecds** [xamarin/xamarin-android#2455]
### Steps to Reproduce

1. Open a pre-created file
2. Try to add a new property for any element (android:id for example)

### Expected Behavior
The editor continue working and I can type the value for property
### Actual Behavior
VS crashes without any sign of log file and reopens sometimes
### Version Information
15.9.2

> VS bug [#735280](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735280)

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '16.0' that is not in the list of supported values

**Comment by garuma** [comment]
Hey @felipecds, could you either use the "Send Feedback > Report a problem" action in Visual Studio so that I can get more information or alternatively manually do "Help > Xamarin > Zip logs (last 7 days)" and attach the result on this issue? Thanks!

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '16.1' that is not in the list of supported values
