### ISSUE TITLE
[mono-runtimes] System.Threading.Tasks.Extensions.dll facade assembly is not yet present on the `d15-9` branch

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#2466]
### Steps to Reproduce

1. Download one of the latest candidate builds for the `d15-9` branch from https://jenkins.xamarin.com/view/Xamarin.Android/job/xamarin-android-builds-d15-9/33/PublishUrls/. Either the .vsix or the .pkg will work.
2. Examine the package contents.

### Expected Behavior

Now that https://github.com/xamarin/xamarin-android/commit/0ea0725c2e9ca86b665ed49dfef0e0146251f7f9 has been committed to the `d15-9` branch to complete the implementation of the types forwarded by the *System.Threading.Tasks.Extensions.dll* facade assembly, it would be best to have the *System.Threading.Tasks.Extensions.dll* facade assembly itself also included in the installer package.

### Actual Behavior

The installer packages (*Xamarin.Android.Sdk.9.1.3.0.vsix* and *xamarin.android-9.1.3-0.pkg*) do not yet contain the *System.Threading.Tasks.Extensions.dll* facade assembly.

I believe that the particular part of https://github.com/xamarin/xamarin-android/pull/2450 that adds the *System.Threading.Tasks.Extensions.dll* facade assembly should be backported to the `d15-9` branch at this time to complete https://github.com/xamarin/xamarin-android/commit/0ea0725c2e9ca86b665ed49dfef0e0146251f7f9.

**Comment by jonpryor** [comment]
The current opinion is that we'll ship the `System.Threading.Tasks.Extensions.dll` façade assembly with d16-0, as we aren't fully comfortable with knowing what things may break by introducing it.

The façade assembly is already in d16-0, as of bf2b59ce6ea13640668dd6385ef287938d2628d7.

**Comment by xperiandri** [comment]
But I have the same issue with VS 2019 Preview 3.0
What does it mean?

**Comment by brendanzagaeski** [comment]
@xperiandri, out of curiosity I took a try at reproducing the issue as described in <https://github.com/xamarin/Xamarin.Forms/issues/5325> with Visual Studio 2019 Preview 3. I was able to build the APK successfully in both the Debug and Release configurations. Hopefully the issue is resolved for you too with the latest Visual Studio 2019 RC.3 release. If not, if you might be able to attach a test case that demonstrates the problem on a [new issue](https://github.com/xamarin/xamarin-android/issues/new), that would be perfect. Thanks!

**Comment by xperiandri** [comment]
Not at all
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "System.Runtime" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>parse error FS3053: error : The type provider constructor has thrown an exception: [error CS1703: An assembly with the same identity 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' has already been imported. Try removing one of the duplicate references.]
1>FSC: warning FS3005: Referenced assembly 'C:\Users\Andrii\Dev\XperiAndri\Conference\packages\Xamarin.Android.FSharp.ResourceProvider.1.0.0.28\lib\monoandroid81\Xamarin.Android.FSharp.ResourceProvider.Runtime.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found
1>		No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2160,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
1>System.IO.FileNotFoundException: Could not load assembly 'Conference.Mobile.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
1>File name: 'Conference.Mobile.Android.dll'
1>   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
1>   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
1>   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
1>   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
1>   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "Conference.Mobile.Android.fsproj" -- FAILED.
```

**Comment by xperiandri** [comment]
@brendanzagaeski can we have a call on Skype for Business to discuss further steps?

**Comment by brendanzagaeski** [comment]
Learning more on a call sounds good, if we can find a time that'll work across the different time zones. Feel free to start a one to one conversation with me on Gitter, for example using a `/query @brendanzagaeski` command from within the [Xamarin.Android Gitter channel](https://gitter.im/xamarin/xamarin-android), or just mention me with `@brendanzagaeski` right in the Xamarin.Android Gitter channel, and we can coordinate on a time.

**Comment by xperiandri** [comment]
@brendanzagaeski thanks for explanation and workaround assumption.
Adding `<Reference Include="mscorlib"/>` to Android project fixes the issue perfectly!
