### ISSUE TITLE
Storage Permission control is available in blank app

### ISSUE THREAD

**Issue by madrvojt** [xamarin/xamarin-android#2468]
### Steps to Reproduce

// Xamarin Android Part
1. Create Blank Xamarin.Android app (Latest and Greatest - min. ver. 5 , target and compile ver. 9)
2. Open App Permissions - Settings - App & Notification - "AppName" - Permission
3. There is include Storage permission

![screenshot_20181129-151819](https://user-images.githubusercontent.com/11706829/49227759-2d238700-f3ea-11e8-88d3-218dc06bc4d1.png)

![screenshot_20181129-150138](https://user-images.githubusercontent.com/11706829/49227215-d8334100-f3e8-11e8-9428-03f7c6febb53.png)

// Android Studio Part
4. Save workflow in Native Android App (Via Android Studio) no permission available.

![screenshot_20181129-150315](https://user-images.githubusercontent.com/11706829/49227223-de292200-f3e8-11e8-992e-55146713c919.png)

Maybe this problem related with this permissions in Xamarin.Android Core.

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

### Expected Behavior

Remove storage permission dependency. 

### Version Information

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.7 (build 1868)
Installation UUID: 7568db7e-1d71-4be6-a694-1fccde0b2998
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.7.0.5148

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.2
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Version: 2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.1.0.38 (Visual Studio Enterprise)
Android SDK: /Users/madrvojt/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.1 (API level 22)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Java SDK: /Users/madrvojt/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: 06ceaea1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.11 (Visual Studio Enterprise)
Hash: 5ef73d34
Branch: 
Build date: 2018-11-21 00:03:25-0500

=== Xamarin.iOS ===

Version: 12.2.1.11 (Visual Studio Enterprise)
Hash: 5ef73d34
Branch: d15-9
Build date: 2018-11-21 00:03:24-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707001868
Git revision: 8bcdfa96d67c8c88dc45728cc968a2f84b55322f
Build date: 2018-11-22 12:19:29+00
Build branch: release-7.7
Xamarin extensions: d66dbedcda237cd9b546abfecfeecafba6f8e3cb

=== Operating System ===

Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.31
MFractor 3.6.6
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.14
Team Foundation Version Control for TFS and Azure DevOps 0.4.3.3

**Comment by JonDouglas** [comment]
The difference here is due to the default setting of `Use Fast Deployment (debug mode only)`, which requires a storage permission to utilize the file system for fast deployment. Please note that this is only for `Debug` configurations and upon disabling this setting or using a `Release` configuration, no storage permission would be used unless set by the `AndroidManifest.xml` or at runtime.

Because of this, I would consider this to be by design rather than a bug. I'll defer to @jonpryor and @dellis1972 whether a storage permission is still required with our recent revamped fast deployment.

**Comment by madrvojt** [comment]
@JonDouglas Thanks for detailed answer! I dont have problem, if this permission will be added only in Fast Deployment (Debug Mode).

Maybe it will be nice added this information to the docs, because READ_EXTERNAL_STORAGE is dangerous permission in Android perspective and i think this is specific behavior for this mode.

**Comment by madrvojt** [comment]
@dellis1972 No, manifest in the template is without any permissions. It's ok.

**Comment by jonathanpeppers** [comment]
@madrvojt feel free to comment if you have further questions, thanks!
