### ISSUE TITLE
Deployment is failing intermittently during InstallPackageAssemblies

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2489]
I'm seeing deployment fail pretty consistently on a first deployment attempt, and I'm seemingly only able to work around it by cleaning and re-deploying. This appears to be a regression in relatively recent d16.0  builds.

### Steps to Reproduce

1. Create a new Android project and try to deploy it to device.
2. You may need to clean and redeploy, or otherwise work from an "incremental" state in order to reproduce, however as mentioned I am seeing this pretty consistently on "Clean" deployment attempts.

### Expected Behavior
Deployment attempts succeed every time.

### Actual Behavior
Deployment intermittently fails with
```MSB4018: The "InstallPackageAssemblies" task failed unexpectedly.
System.MissingMethodException: Method not found: 'Void Xamarin.AndroidTools.AndroidDeploySession.set_FastDevTypemapsProvider(System.Func`1<System.Collections.Generic.IEnumerable`1<System.String>>)'.
   at Xamarin.Android.Tasks.InstallPackageAssemblies.RunTask()
   at Xamarin.Android.Tasks.InstallPackageAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Version Information
Xamarin.Android SDK   9.1.199.38 (HEAD/00f9c37c) installed on top of VS2017 15.9
Mono: mono/mono/2018-08@23f2024af80
    Java.Interop: xamarin/java.interop/master@6dd6f16
    LibZipSharp: grendello/LibZipSharp/master@d695149
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    MXE: xamarin/mxe/xamarin@b9cbb535
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.25.2@4ea4c69
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0-p2@9e78d6e

### Log File
https://gist.githubusercontent.com/pjcollins/9a0737e48f1ccbee5a898583860ab839/raw/ec98364a9f77b8bdcca88891d057016e234aeb93/gistfile1.txt

**Comment by pjcollins** [comment]
I haven't yet managed to reproduce this with a recent xamarin-android master installed on top of A VS2019 preview. This very well may be an incompatibility that is not worth fixing. 

I'm going to leave the issue open for now in case it pops up again, but this can probably be resolved in a "WONT FIX" capacity shortly.

**Comment by pjcollins** [comment]
Closing based on https://github.com/xamarin/xamarin-android/issues/2489#issuecomment-445014349

**Comment by erikpowa** [comment]
Here is a simple repro:

Open one XA Project twice with Visual Studio, then you get 
```
2>System.MissingMethodException: Method not found: 'Void Xamarin.AndroidTools.AndroidDeploySession.set_FastDevTypemapsProvider(System.Func`1<System.Collections.Generic.IEnumerable`1<System.String>>)'.
2>   at Xamarin.Android.Tasks.InstallPackageAssemblies.RunTask()
2>   at Xamarin.Android.Tasks.InstallPackageAssemblies.Execute()
2>   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>Done building project "PerformanceTest.csproj" -- FAILED.
2>Build FAILED.
```
Won't be able to debug until `Target Android version` changes.

_VS Community 15.9.5_
_SDK 9.2.99.3_

**Comment by GreenKn1ght** [comment]
Preview is not licensed to build production apps. Is there any other solution?

**Comment by pjcollins** [comment]
@GreenKn1ght on that same note, we likely wouldn't _recommend_ using pre-release versions of Xamarin.Android to produce release quality production apps either. Is there a specific bug fix in a more recent Xamarin.Android version that you need access to in order to ship an update? My advice would be to continue to use VS 2017 for production until the initial stable VS 2019 release is available, if you can.
