### ISSUE TITLE
Encountering new ClassNotFoundException when attempting to inflate certain layouts

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2501]
I'm now encountering a startup crash when running a handful of projects on device. This error is not reproducible on 15.9 or earlier dev16 previews.

### Steps to Reproduce

1. Download and run the following project:
https://github.com/xamarin/monodroid-samples/tree/master/android-o/EmojiCompat

### Expected Behavior
Layout XML files which specify a fully qualified class name to a layout in a .cs file should inflate successfully.

### Actual Behavior
```
12-07 10:27:07.762 16463 16463 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class EmojiCompatSample.CustomTextView
12-07 10:27:07.762 16463 16463 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class EmojiCompatSample.CustomTextView
12-07 10:27:07.762 16463 16463 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "EmojiCompatSample.CustomTextView" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xamarin.EmojiCompat-e5BLLTVnZZzpdFtPjSKlXA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xamarin.EmojiCompat-e5BLLTVnZZzpdFtPjSKlXA==/lib/arm64, /system/fake-libs64, /data/app/com.xamarin.EmojiCompat-e5BLLTVnZZzpdFtPjSKlXA==/base.apk!/lib/arm64-v8a, /system/lib64]]
12-07 10:27:07.762 16463 16463 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
```

### Version Information
Microsoft Visual Studio Enterprise 2019 [28406.54.d16.0]
Xamarin.Android SDK   9.1.199.32 (HEAD/2e6d2a8d)
    Mono: mono/mono/2018-06@b63e5378e38
    Java.Interop: xamarin/java.interop/master@24e7725
    LibZipSharp: grendello/LibZipSharp/master@de1712c
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    MXE: xamarin/mxe/xamarin@b9cbb535
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.25.2@4ea4c69
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0-p2@9e78d6e

### Log File
logcat: 
https://gist.github.com/pjcollins/06f2177156609585b506f406522f5a8c

build: 
https://gist.githubusercontent.com/pjcollins/770ac072099e9eb70b69b52b92387ac8/raw/dbcc8af3d28660dd716f062138f97186e8335780/gistfile1.txt

**Comment by jonathanpeppers** [comment]
So the problem is when I inspect the APK, `activity_main.xml` has this:
```xml
        <EmojiCompatSample.CustomTextView
            android:id="@+id/emoji_custom_text_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textSize="@dimen/text_size" />
```

But `obj\Debug\81\res\layout\activity_main.xml` has:
```xml
<md54fb1b2c61707abc84bfcfdade5ee07b7.CustomTextView android:id="@+id/emoji_custom_text_view" android:layout_width="match_parent" android:layout_height="wrap_content" android:textSize="@dimen/text_size" />
```

Something must be going wrong at build time?

**Comment by jonathanpeppers** [comment]
Ok, `_GenerateJavaStubs` and `ConvertCustomView` ran *after* `_UpdateAndroidResgen` and `Aapt2Link`.

So `packaged_resources` was generated *before* the custom views were fixed up.

If I add `/p:AndroidUseAapt2=False`, the problem goes away... I'm comparing the ordering of targets with/without aapt2 to see what we should do here.

**Comment by jonathanpeppers** [comment]
We have a circular dependency problem with aapt2...
1. `<Aapt2Compile/>` creates `*.flata`, needs `<ConvertCustomView/>` to have run
2. `<GenerateJavaStubs/>` creates `acw-map.txt`
3. `<ConvertCustomView/>` needs `acw-map.txt` to work

If I try calling no. 3 earlier, `acw-map.txt` doesn't exist yet...

So it seems like custom views aren't getting fixed up at all when aapt2 is enabled...

**Comment by dellis1972** [comment]
PR I question is still stabilising. We probably won't get this for d16-0 now since its closed to CP's and aapt2 is not longer the default.. So I will re-target this for d16-1, so we can hopefully enabled aapt2 as default again.
