### ISSUE TITLE
Crash "Not a valid calendar for the given culture" with Thai locale

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/xamarin-android#2511]
### Steps to Reproduce

1. Set the device language to Thai.
2. Use the following code snippet:
```
var timeSpan = TimeSpan.FromMinutes(65);
timeSpan.ToString(@"h\:mm\:ss")
```
3. Runtime crash with `System.ArgumentOutOfRangeException`.

### Expected Behavior
The method should complete successfully.

### Actual Behavior
Throws `System.ArgumentOutOfRangeException: Not a valid calendar for the given culture.`

### Workaround
Prevent linker from stripping out the reference by including it in the code.
```
_ = new System.Globalization.ThaiBuddhistCalendar();
```

### Version Information

- Microsoft Visual Studio Professional 2017 v15.9.3
VisualStudio.15.Release/15.9.3+28307.145
Microsoft .NET Framework
Version 4.7.03062

- Xamarin 4.12.3.73 (d15-9@20b35b881)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

- Xamarin Designer   4.16.5 (6b9f32067)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

- Xamarin Templates   1.1.127 (e975299)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

- Xamarin.Android SDK   9.1.0.38 (HEAD/61d16aa23)
Xamarin.Android Reference Assemblies and MSBuild support.

- Xamarin.iOS and Xamarin.Mac SDK   12.2.1.11 (5ef73d3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Related
Previously reported:

- https://github.com/onovotny/MetroLog/issues/110
- https://bugzilla.xamarin.com/show_bug.cgi?id=31228
- https://bugzilla.xamarin.com/show_bug.cgi?id=59077

**Comment by shnaz** [comment]
Have same problem with arabic. Fixed it by using your workaround @velocitysystems. Thanks!

**Comment by AhmedKhattab95** [comment]
@shnaz  what was the workaround ?

**Comment by shnaz** [comment]
@AhmedKhattab95 Just call this method early in your MainActivity.OnCreate: 

```
		private void PreventLinkerFromStrippingCommonLocalizationReferences()
		{
			var gregorianCalendar = new System.Globalization.GregorianCalendar();
			var persianCalendar = new System.Globalization.PersianCalendar();
			var arabivAlQuraCalendar = new System.Globalization.UmAlQuraCalendar();
		}
```

**Comment by BurkusCat** [comment]
In case it helps anyone in the future here is a larger method with [all calendars](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.calendar?view=net-5.0#remarks) based on the existing workarounds:
``` csharp
        private void PreventLinkerFromStrippingCommonLocalizationReferences()
        {
            _ = new System.Globalization.ChineseLunisolarCalendar();
            _ = new System.Globalization.GregorianCalendar();
            _ = new System.Globalization.HebrewCalendar();
            _ = new System.Globalization.HijriCalendar();
            _ = new System.Globalization.JapaneseCalendar();
            _ = new System.Globalization.JapaneseLunisolarCalendar();
            _ = new System.Globalization.JulianCalendar();
            _ = new System.Globalization.KoreanCalendar();
            _ = new System.Globalization.KoreanLunisolarCalendar();
            _ = new System.Globalization.PersianCalendar();
            _ = new System.Globalization.TaiwanCalendar();
            _ = new System.Globalization.TaiwanLunisolarCalendar();
            _ = new System.Globalization.ThaiBuddhistCalendar();
            _ = new System.Globalization.UmAlQuraCalendar();
        }
```

**Comment by BurkusCat** [comment]
@Lelelo1 I had included it in my platform specific projects. But you could try it in the Forms project and see if it prevents the crashes.

**Comment by Lelelo1** [comment]
@BurkusCat 
Ok. Thanks! I rather not want to risk more users to crash so I will place them in specific projects as well

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
