### ISSUE TITLE
Tabbed Forms App deploys but fails to start on Samsung SM-G930U (API 23)

### ISSUE THREAD

**Issue by manish** [xamarin/xamarin-android#2512]
### Steps to Reproduce

1. Create a Forms Tabbed App project
2. Select the device as `Samsung SM-G930U (API 23)`
3. Set breakpoint in Android project, MainActivity.cs:22
4. In Debug config, hit Run which runs the project in Debug mode

### Expected Behavior

The app should be deployed to the device, start up and breakpoint should be hit

### Actual Behavior

The app is deployed on the device, but the breakpoint is not hit and VS for Mac goes back to Editor mode

### Version Information

```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.8 Preview (7.8 build 1379)
Installation UUID: c6f583b8-4b21-4c5b-a3df-6aa8a3185d07
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.0.0.0 ( / b40230c0)

	Package version: 516000226

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.226 (2018-06/ad3edd34840) (64-bit)
	Package version: 516000226

=== NuGet ===

Version: 4.7.0.5148

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.0
	2.1.2
	2.1.0-preview1-26216-03
	2.0.9
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.2.100/Sdks
SDK Versions:
	2.2.100
	2.1.302
	2.1.300-preview1-008174
	2.1.202
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 10

=== Xamarin.Android ===

Version: 9.1.4.2 (Visual Studio Enterprise)
Android SDK: /Users/xamarinqa/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 27.0.2

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/xamarinqa/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.10
1.8.0-10
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.8.1.0
Hash: 06ceaea1

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.iOS ===

Version: 12.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

=== Build Information ===

Release ID: 708001379
Git revision: ceb4d12b17330cbb106216964c2055f020119dfe
Build date: 2018-12-05 20:58:31+00
Build branch: release-7.8
Xamarin extensions: a5665f1bf5ba9b485406e2b9beafadba31e405bf

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Wed Oct 10 23:06:14 PDT 2018
    root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64


```

### Log File

* [Adb LogCat Output](http://xqa.blob.core.windows.net/gist/Samsung%20SM-G930U.log.181207223559-a5021ef0f84d4f47ba202e3a0f24ff10.txt)

* [Screencast - have a look at `2:10` mark](http://xqa.blob.core.windows.net/video/macOsScreenRecord.mp4-1349a5d4e69744a0adad089e81315762.mp4)

[Deploying to Device output](http://xqa.blob.core.windows.net/gist/DeployingToDeviceOutput-75e05c9ed9e845a8890891da53410b3f.txt)

* [Application Output](http://xqa.blob.core.windows.net/gist/ApplicationOutput-67b9e5d183e64a40994e47d67a15123d.txt)

```
Forwarding debugger port 8879
Detecting existing process
> am start -n "org.xamarin.formsandroidiosmobilebackend/md51668c1b92954fc4677ad41c78327f502.MainActivity"
> Starting: Intent { cmp=org.xamarin.formsandroidiosmobilebackend/md51668c1b92954fc4677ad41c78327f502.MainActivity VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} }
```

**Comment by pjcollins** [comment]
@manish  I was unable to reproduce this using the [VS Mac stable channel](https://gist.github.com/pjcollins/bffa58a96999a683e6bde5a2c74b2b6a), nor was I able to reproduce with a 7.8 Preview. I was able to debug a tabbed forms app on anNexus 5 (6.0, API 23) and a Pixel 2 (9.0, API 28). Do you think it could be specific to the Samsung device you're using?

Looking at logcat, it seems like the fast deploy codepath failed somewhere along the way:
```
06-14 13:32:11.891 20664 20664 F monodroid: No assemblies found in '/data/user/0/org.xamarin.formsandroidiosmobilebackend/files/.__override__' or '/storage/emulated/0/Android/data/org.xamarin.formsandroidiosmobilebackend/files/.__override__'. Assuming this is part of Fast Deployment. Exiting...
```
Looking at the deployment log, it seems that this app had already been installed in _some_ form:
```
Removing previous version of application
Copying application to device...
10% ... 640kb of 6203kb copied
...
```
That leads me to believe that the reproduction may not be quite as straightforward as suggested in the initial report. Could you help us narrow down the steps that lead to this failure? What actions are you performing before this debug attempt fails?

**Comment by jpobst** [comment]
Our team is unable to investigate this issue further without the requested information.

Hopefully you found a resolution!  If not, please update to the latest version of the product and if the problem still occurs, reply with the requested information and reopen this issue.
