### ISSUE TITLE
Can not add reference "Xamarin.Android.Crashlytics" successfully.

### ISSUE THREAD

**Issue by Carl-Wen** [xamarin/xamarin-android#2516]
### Steps to Reproduce

1. Create a simple project.
2. Try to add reference "Xamarin.Android.Crashlytics".
3. Build and it will failed with a message: Can not resolve reference: `Xamarin.Android.Fabric`, referenced by `Xamarin.Android.Crashlytics`. Please add a NuGet package or assembly reference for `Xamarin.Android.Fabric`, or remove the reference to `Xamarin.Android.Crashlytics`.

[App1.zip](https://github.com/xamarin/xamarin-android/files/2666301/App1.zip)

### Expected Behavior
Build successfully.

### Actual Behavior
Build failed.

**Comment by jpobst** [comment]
This package has been deprecated (https://www.nuget.org/packages/Xamarin.Android.Crashlytics), so this issue is obsolete.
