### ISSUE TITLE
jnimarshalmethod-gen.exe crashes mono on linux

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#2517]
Looks like jnimarshalmethod-gen.exe triggers crash in mono on linux.

Context: https://github.com/xamarin/xamarin-android/pull/2515/files/#r240511508

The crash itself: https://gist.github.com/grendello/82a889e18667a7e730ca90686fb21dac

**Comment by jonpryor** [comment]
I wonder if this is related to trying to write to an assembly which was already loaded, and thus this will be "fixed" by https://github.com/xamarin/java.interop/pull/408.

**Comment by radekdoulik** [comment]
On Windows I was getting unhandled exception, so it is probably different issue. Should be easy to test. @grendello, could you try to use master Java.Interop and add `/p:AndroidGenerateJniMarshalMethodsAdditionalArguments="-o directory-path"` to msbuild when building the XF test?

**Comment by grendello** [comment]
`jnimarshalmethod-gen.exe` was superseded by marshal methods (8bc7a3e84f95e70fe12790ac31ecd97957771cb2 and others)
