### ISSUE TITLE
com.android.layoutlib.bridge.impl.rendersessionImpl$PostInflatException - Xamarin.Android

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/xamarin-android#2523]
I have _Xamarin.Android_ project. I am implementing `android.support.v4.app.FragmentTabHost ` with `TabWidget`  while loading the xaml UI on previewer I am getting above exception. 

This is my code

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.app.FragmentTabHost xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/stabhost"
    android:layout_width="match_parent"
	android:background="@color/grey"
    android:layout_height="match_parent">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <TabWidget
            android:id="@+id/stabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_weight="0"
            android:background="#00e5ff" />
        <FrameLayout
            android:id="@+id/srealtabcontent"
            android:layout_width="match_parent"
            android:layout_weight="1"
            android:layout_height="0dp" />
    </LinearLayout>
</android.support.v4.app.FragmentTabHost>
```

This is the detailed exception

Indirect rendering enabled
Creating LibraryClassLoader in shadow copy path C:\Users\arvind.ch\AppData\Local\Temp\AndroidDesignerJars5330633775603632343
Setting id 1 on newly created ClassLoader

Trying to load class android.support.v4.app.FragmentTabHost

> Failed to process message Load
> mono.android.DesignerException: com.android.layoutlib.bridge.impl.RenderSessionImpl$PostInflateException
> 	at mono.android.DesignerException.fromThrowable(DesignerException.java:54)
> 	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:235)
> 	at mono.android.DesignerSession.load(DesignerSession.java:314)
> 	at mono.android.DesignerSession.processMessage(DesignerSession.java:675)
> 	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
> 	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: com.android.layoutlib.bridge.impl.RenderSessionImpl$PostInflateException: TabHost requires a TabWidget with id "android:id/tabs".
> 
> 	at com.android.layoutlib.bridge.impl.RenderSessionImpl.setupTabHost(RenderSessionImpl.java:802)
> 	at com.android.layoutlib.bridge.impl.RenderSessionImpl.postInflateProcess(RenderSessionImpl.java:616)
> 	at com.android.layoutlib.bridge.impl.RenderSessionImpl.postInflateProcess(RenderSessionImpl.java:692)
> 	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:337)
> 	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
> 	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:270)
> 	at mono.android.DesignerSession.load(DesignerSession.java:307)
> 	... 4 more
> 

### Steps to Reproduce

1. Create Xamarin.Android project.
2. Use code above for layou & switch to previewer window.
3. 

### Expected Behavior
UI should show the in previewer.

### Actual Behavior
Getting exception on previewer & blank fragment after execution.
### Version Information

Microsoft Visual Studio Enterprise 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info
VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.779 (d15-8@ff915e800)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.12 (d7ff6f39c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.118 (4217ee9)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.1.0.15 (cbfb047)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

2. Paste below this comment block.
-->

### Log File

![tabexption](https://user-images.githubusercontent.com/19743421/49871519-7b01ab80-fe3c-11e8-8636-130e95998aad.png)

> VS bug [#749981](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/749981)

**Comment by garuma** [comment]
We don't expose it well but the problem is in the exception. To use TabHost you need to provide a TabWidget and a FrameLayout to the control with the right IDs setup.

This valid version works (notice the ids I used):

``` xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.app.FragmentTabHost xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/stabhost"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <TabWidget
            android:id="@android:id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_weight="0"
            android:background="#00e5ff" />
        <FrameLayout
            android:id="@android:id/tabcontent"
            android:layout_width="match_parent"
            android:layout_weight="1"
            android:layout_height="0dp" />
    </LinearLayout>
</android.support.v4.app.FragmentTabHost>
```
