### ISSUE TITLE
Layout Bindings type fixed up on BottomAppBar & custom view

### ISSUE THREAD

**Issue by Nyconing** [xamarin/xamarin-android#2528]
### Steps to Reproduce

1. Using BottomAppBar in layout
2. Enable Layout bindings
3. Boom, build failed.

In the generated bindings:
```
// Declared in: Resources\layout\genericactivity.xml:(9:6)
// Type fixed up from 'android.support.design.bottomappbar.BottomAppBar' to 'Android.Support.Design.Bottomappbar.BottomAppBar'. Element defined in Resources\layout\genericactivity.xml:(9:6)
```
Generated type are wrong, it should be:
`Android.Support.Design.BottomAppBar.BottomAppBar`

My Environment:
Windows10 Pro 1803
VS 16.0.0 preview1.1
Xamarin.Android 9.1.101.6

**Comment by Nyconing** [comment]
So far, I can only fix it manually every rebuild. 
In `obj\[configuration]\90\generated\Binding.[layout].g.cs`
Please note that you need to fix it on **every configurations**.

**Comment by Nyconing** [comment]
New problem on Layout Binding. Layout Binding pointed to wrong class which is unavailable when using custom view.

Reproduce:

1. using custom view `[Register("com.x.x.views.RoundCardView")] public class RoundCardView:CardView{}`
2. enable Layout Binding
3. Re-build
4. Boom!! build failed

Compile time error:
> Error CS0234 The type or namespace name 'X' does not exist in the namespace 'Com.X' (are you missing an assembly reference?)

**Comment by Nyconing** [comment]
Can we actually config the fixed up type? I think this is the viable way rather than smart to detect correct type.

**Comment by aimore** [comment]
@Nyconing could you provide the sample?

**Comment by VaslD** [comment]
You can specify the fix for generated type in layout XML. Still a PITA to do this for every layout element but beats fixing every rebuild.

```xml
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:xamarin="http://schemas.xamarin.com/android/xamarin/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="@dimen/small_margin">

    <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/list_reloader"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        xamarin:managedType="AndroidX.SwipeRefreshLayout.Widget.SwipeRefreshLayout">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/list_recycler"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            xamarin:managedType="AndroidX.RecyclerView.Widget.RecyclerView"/>

    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>

    ...

</FrameLayout>
```

Note the `xmlns:xamarin` declaration and `xamarin:managedType` attribute to correct the generated Xamarin type.

**Comment by jpobst** [comment]
Hopefully this is gone now that Android Support Libraries are out of the picture.
