### ISSUE TITLE
App showing all screens white color

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/xamarin-android#2530]
I have Xamarin.Android app which is almost 3 years old & in production. Many clients using it. But since yesterday I notice that **all child screens are showing white color** when I click on any menu. I have nearly 20 menu's to navigate. Out of 20 menu's sometimes random one is working, than subsequently all app started working. If I close app and open it than again all screen showing white color.

How can I solve this issue. I am kind of frustrate.

This is how I am switching fragments

```
var spTab = new StudentProfileTabFragment();
var fragmentTx = ca.Activity.SupportFragmentManager.BeginTransaction();
fragmentTx.Hide(ca);
fragmentTx.Replace(Resource.Id.crealtabcontent, spTab, "sptf");
fragmentTx.Commit();
```
This is Layout where fragment pushing

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
	android:background="@color/green"
    android:layout_weight="1">
    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:orientation="vertical">
        <FrameLayout
            android:id="@+id/crealtabcontent"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/background_light"
            android:layout_weight="1" />
        <android.support.v4.app.FragmentTabHost
            android:id="@+id/tabhost"
            android:layout_height="wrap_content"
            android:layout_width="fill_parent"
            android:layout_alignParentBottom="true"
            android:background="#00e5ff" />
    </LinearLayout>
</LinearLayout>
```

Here am attaching gif file. In this, in starting all screens are showing while color, If one is working than all starts working. When I close app & open again than nothing working. I am able to click on white screens. If I blindly click on change password than this screen showing up but in few cases  child screens are opening but not showing.

**I am unable to give you steps** because I have many steps are there in my application. How can I solve this issue.
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
Alll screens/fragments should show UI.

### Actual Behavior
Screens are showing while screens. 
### Version Information

Microsoft Visual Studio Enterprise 2017
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

C# Tools 2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

NuGet Package Manager 4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension 1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension 1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension 1.0
ResourcePackage Visual Studio Extension Detailed Info
VisualStudio.Mac 1.0
Mac Extension for Visual Studio

Xamarin 4.11.0.779 (d15-8@ff915e800)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer 4.15.12 (d7ff6f39c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates 1.1.118 (4217ee9)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK 9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK 12.1.0.15 (cbfb047)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

App gif while using it (length 60 sec.). Looking forward to hearing from you.

![apprecording2](https://user-images.githubusercontent.com/19743421/49941899-ce8dfb00-ff09-11e8-9935-7501a4e024be.gif)

**Comment by brendanzagaeski** [comment]
Thanks for the report! My first suspicion is that this might be related to the various interactions between fragment lifecycle and activity lifecycle. For example, one tricky thing that can happen is that the managed (C#) wrapper object for an activity [can stay alive after Android has destroyed the underlying Java `Activity` object](https://docs.microsoft.com/xamarin/android/deploy-test/performance?context=xamarin/cross-platform#remove-event-handlers-in-activities). This can mean that the managed wrapper for the `FragmentManager` also stays alive and no longer references a valid Java `FragmentManager`. In a case that I looked at a few years ago, this meant that event handlers that had been subscribed in the original managed activity started producing unexpected results after the underlying Java activity was destroyed and recreated. (["A configuration change (such as a change in screen orientation, language, input devices, etc) will cause your current activity to be destroyed"](https://developer.android.com/reference/android/app/Activity)).

There are a couple possible ways forward for further investigation of your issue. A good next question to attempt to answer would be where exactly is the first place that the values in the program are incorrect? For example, when your views are rendered as empty, what are the states of the managed C# object and Java object representing the view? Do both contain the expected instance values for the current view? Are both owned by a valid `FragmentManager` and `Activity`?

If you find more details about where things are going wrong and have new questions, you can reply back on this issue. Or if by chance you would be able to zip up and share a self-contained project that demonstrates the issue, I or someone else on the team could try some local investigation to help track down where the values are getting lost. If you can reduce the example to something small enough that you would be comfortable attaching it directly on this issue, that would be perfect. Or if you can share a larger sample that you must keep private, one option would be to use a private **One to One Conversation** on Gitter, for example by using a `/query @username` command from within the [Xamarin.Android Gitter channel](https://gitter.im/xamarin/xamarin-android) to open a private chat with me or another team member to share it. Another option would be to submit an issue from within Visual Studio via [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017). That will allow you to attach files privately, and after you submit the initial report, you can optionally reply to it with private comments on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thanks in advance!

**Comment by arvindrajachourasiya** [comment]
@brendanzagaeski - This issue has been solved yesterday after wasting 3 days of time by removing one `if` condition(Doubt I have is why the same code was working before) but I am unable to figure it out how that has been solved by removing some piece code? Still if you need to venture into issue I will try to give to zip repository. Moreover I am not able to submit issue on VS developer community due to [this issue](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1445). Thank you for your reply.

**Comment by brendanzagaeski** [comment]
Glad to hear you got things working! If you get a chance to share the project, that could be useful, but no worries if not. The investigation can also pick back up if any other users encounter the issue in the future.

**Comment by brendanzagaeski** [comment]
Thanks again for this report. I'll close the issue for now to tidy up the list of open issues. If any user comes across a similar problem in the future, please do open a new issue for further investigation. Thanks!
