### ISSUE TITLE
Popupwindow update issue in S8(API 26)

### ISSUE THREAD

**Issue by RathanakumarSekar** [xamarin/xamarin-android#2543]
### Detail

I am facing popup window update issue in Samsung S8 device. In my sample editText is placed on the bottom of the screen and popup window appear at top of that editText. But, popup window does not appear in the correct position when editText is in a focused state(Samsung S8 API 26 only). For all other devices, it works as expected.

### Code

```
EditText editText; 
        PopupWindow popupWindow;
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            LinearLayout linearLayout = new LinearLayout(this){Orientation=Orientation.Vertical};

            editText = new EditText(this) { Text = "TestEditText" };
            editText.TextChanged+= EditText_TextChanged;
            RelativeLayout relativeLayout = new RelativeLayout(this);
            relativeLayout.LayoutParameters = new Android.Views.ViewGroup.LayoutParams(Android.Views.ViewGroup.LayoutParams.WrapContent, Android.Views.ViewGroup.LayoutParams.WrapContent);
            relativeLayout.AddView(editText);
            RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(1000, 150);
            layoutParams.SetMargins(0, 1400, 0, 0);
            editText.LayoutParameters = layoutParams;
            linearLayout.AddView(relativeLayout);

            popupWindow = new PopupWindow(this);
            LinearLayout linearLayoutnew = new LinearLayout(this);
            linearLayoutnew.AddView(new TextView(this) { Text = "Testing Popup window behavioor with S8 devices" });
            linearLayoutnew.AddView(new Button(this) { Text = "TestButton" });
            linearLayoutnew.LayoutParameters = new Android.Views.ViewGroup.LayoutParams(300, 200);
            popupWindow.Height = 200;
            popupWindow.ContentView = linearLayoutnew;
            SetContentView(linearLayout);
        }

        void EditText_TextChanged(object sender, Android.Text.TextChangedEventArgs e)
        {
            popupWindow.ShowAsDropDown(editText, 0, -(editText.Height + popupWindow.Height));
        }
```

### Steps to Reproduce
1) Focus EditText (only S8 API 26)
2)change Text
3)Popup not appear above editText

### Expected Behavior

Popup window should appear top of the EditText control.

### Actual Behavior

Popup window appear at wrong position. 

### Version Information

Xamarin.Android
Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/labuser/Library/Android/sdk
	Supported Android versions:
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Also, I already raised the same query on Xamarin forum:

https://forums.xamarin.com/discussion/141802/popupwindow-update-issue-in-s8-api-26#latest

**Comment by jonathanpeppers** [comment]
Hi @RathanakumarSekar, I think you are experiencing the "wonders" of working with Android!

With the APIs you are using here, Xamarin.Android is passing these calls directly to Android (Java). If you are seeing behavior on one device, then it is likely a problem with the Android implementation _on that device_. I'm not sure how it is an issue with Xamarin.Android?

Feel free to comment/reopen if you think there is an issue with Xamarin.Android here. Perhaps try posting your question on [stackoverflow](http://stackoverflow.com)? Closing for now thanks!
