### ISSUE TITLE
HttpClient does not respect Timeout

### ISSUE THREAD

**Issue by csuzw** [xamarin/xamarin-android#2544]
I believe this is the same/similar to this issue for Xamarin.iOS: https://github.com/xamarin/xamarin-macios/issues/5190 .  There is a hint in the original issue linked in that IOS issue that using the AndroidClientHandler and setting the ReadTimeout/ConnectTimeout is a workaround but I get the an exception about encoding 'identity' not being supported if I do this.

### Steps to Reproduce

1. Create a HttpClient and set Timeout to a value greater than 100s ( the default value).
2. Send a request that takes longer than 100s but less than the Timeout set.

### Expected Behavior

The request to return successfully

### Actual Behavior

The request times out after 100s.

### Version Information

Microsoft Visual Studio Enterprise 2017  (2)
Version 15.9.4
VisualStudio.15.Release/15.9.4+28307.222
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA999
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.11009.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.9.02046.0
Azure Functions and Web Jobs Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

HgSccPackage   2.0.5
Mercurial source code control package

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2018.2.1   Build 182.0.20180829.63240
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61810.11040
Microsoft SQL Server Data Tools

Telerik WPF VSExtensions   2018.4.1121.1
Progress® Telerik® UI for WPF Visual Studio extensions

Telerik Xamarin VSExtensions   2018.4.1121.1
Progress® Telerik® UI for Xamarin Visual Studio extensions

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.208
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.77 (d15-9@e3f40b477)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.4.2 (HEAD/8255f42fc)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonathanpeppers** [comment]
Hi @csuzw,

You mentioned you are _not_ using the `AndroidClientHandler`, which options do you have for your HTTP settings here under `Project Options | Android Options | Advanced`?

![image](https://user-images.githubusercontent.com/840039/50094465-e0f18880-01d8-11e9-8390-ced478d54751.png)

`Default` HttpClient implementation is the same as `Managed` (as of this post).

**Comment by csuzw** [comment]
I have Default, Managed and Android.  It is currently set to Default (if I try to set it to Android I get the exception about encoding 'identity').

When the HttpClient is being constructed it is using the default constructor so I believe it uses whatever the default is (which seems to be HttpClientHandler).

**Comment by jonathanpeppers** [comment]
@grendello after the holiday, is it worth testing timeouts with this service? https://httpstat.us/ They have an option to declare a timeout.

It might be that all we can do is forward this issue to the Mono team?

@csuzw it might also help us if you can send a quick code example of what  you are doing, thanks!

**Comment by csuzw** [comment]
Here's a really quick example calling httpstat.us: https://www.dropbox.com/s/rukqqp2yyji5ug9/HttpClientTimeoutApp.zip?dl=0 .  HttpClient has timeout set to 200s.  The call to httpstat.us has timeout set to 110s.  When you click the test button it should timeout after 100s (at least it does for me!).

**Comment by grendello** [comment]
This issue is a problem in the Mono BCL, which `HttpClient` is part of and should be moved to the Mono org.

**Comment by grendello** [comment]
This issue was moved to mono/mono#12577
