### ISSUE TITLE
Visual Studio 2017: "Autos" debug window doesn't work

### ISSUE THREAD

**Issue by mfeingol** [xamarin/xamarin-android#2568]
### Steps to Reproduce

1. Debug an Android app
2. Set a break point
3. Observe the Locals window works fine, but the Autos window doesn't.

![image](https://user-images.githubusercontent.com/218865/50378615-3b308600-05eb-11e9-9725-a7b3475d2b79.png)

### Expected Behavior

Autos should work the same as other debug environments in VS.

### Actual Behavior

Autos is always empty

### Version Information

Visual Studio 2017 15.9.4

**Comment by JonDouglas** [comment]
We believe this issue has been resolved in another product. Please install the latest version of Visual Studio 2017 15.9 and let us know via [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2017)  if it's still an issue.

**Comment by mfeingol** [comment]
The issue has not been resolved as of VS 15.9.7. Please see the attached screenshot.

I reported a VS problem, but you might not want to close this issue out until it's actually fixed.

![capture](https://user-images.githubusercontent.com/218865/53675521-0294d480-3c4c-11e9-925f-09d49f86b91d.JPG)

**Comment by mfeingol** [comment]
https://developercommunity.visualstudio.com/content/problem/475178/xamarin-android-autos-debugger-window-doesnt-work.html

**Comment by mfeingol** [comment]
This is still an issue in Visual Studio 2019 RTM.
