### ISSUE TITLE
Encountering linker failure on macOS on partial build after changing the project TargetFrameworkVersion

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2584]
I'm not sure if this particular scenario represents a "valid" bug per-say, but the behavior described below has started occurring somewhere between d15-9 and d16-0. This incremental build failure also only occurs when linking on macOS, and is not reproducible on Windows. Perhaps this is related to the difference in target framework versions of the app and library projects used in this repro (app currently targets v4.4 while the lib is targeting v8.1).

### Steps to Reproduce

1. Clone https://github.com/xamarin/monodroid-samples/tree/master/BatchStepSensor
2. `msbuild /t:SignAndroidPackage /p:Configuration=Release BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj`
3. `msbuild /t:SignAndroidPackage /p:Configuration=Release BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj`
4. `msbuild /t:SignAndroidPackage /p:TargetFrameworkVersion=v9.0 /p:Configuration=Release BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj`

### Expected Behavior
My third build attempt (which includes a property change) will succeed.

Alternatively, perhaps in this case the app framework version < lib framework version warning[0] just needs to be respected.
[0] warning XA0105: The $(TargetFrameworkVersion) for CommonSampleLibrary (v8.1) is greater than the $(TargetFrameworkVersion) for your project (v4.4). You need to increase the $(TargetFrameworkVersion) for your project.

### Actual Behavior
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2176,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly. [/Users/peter/source/monodroid-samples/BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2176,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'System.Void BatchStepSensor.BatchStepSensorFragment::OnSaveInstanceState(Android.OS.Bundle)' in assembly: 'BatchStepSensor.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.OS.BaseBundle::PutInt(System.String,System.Int32) [/Users/peter/source/monodroid-samples/BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2176,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod (Mono.Cecil.MethodReference reference) [0x00013] in <f427ee17a10d415c9af2d0abe8ab4b20>:0  [/Users/peter/source/monodroid-samples/BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2176,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkMethod (Mono.Cecil.MethodReference reference) [0x0004a] in <f427ee17a10d415c9af2d0abe8ab4b20>:0  [/Users/peter/source/monodroid-samples/BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2176,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkInstruction (Mono.Cecil.Cil.Instruction instruction) [0x00040] in <f427ee17a10d415c9af2d0abe8ab4b20>:0  [/Users/peter/source/monodroid-samples/BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2176,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkMethodBody (Mono.Cecil.Cil.MethodBody body) [0x00098] in <f427ee17a10d415c9af2d0abe8ab4b20>:0  [/Users/peter/source/monodroid-samples/BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2176,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x00162] in <f427ee17a10d415c9af2d0abe8ab4b20>:0  [/Users/peter/source/monodroid-samples/BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2176,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x0001b] in <f427ee17a10d415c9af2d0abe8ab4b20>:0  [/Users/peter/source/monodroid-samples/BatchStepSensor/BatchStepSensor/BatchStepSensor.csproj]
```

### Version Information
Visual Studio Enterprise 2017 for Mac
Version 7.7.2 (build 21)
Installation UUID: 57d9d5c5-f091-4a0a-af36-7330b1af94d2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)
	Package version: 518000225

Mono Framework MDK
Runtime:
	Mono 5.18.0.225 (2018-08/bac9fc1f889) (64-bit)
	Package version: 518000225

XA Version: 9.1.103.6 (Visual Studio Enterprise)

### Log File
https://gist.githubusercontent.com/pjcollins/e915663f696828abaac25e66a1fa49ca/raw/1e48937f1543223975176ec676adc46fddc8dfc1/gistfile1.txt

**Comment by dellis1972** [comment]
This looks like we are not invalidating the linker cache when the build.props changes.. 
We should investigate this and fix for d16-1

**Comment by jonathanpeppers** [comment]
I could repro this on Windows when setting `/p:AppendTargetFrameworkToIntermediateOutputPath=False`, see: https://github.com/xamarin/xamarin-android/blob/c2ff29f246994c6a26656e28261cea2728328bc1/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.DefaultOutputPaths.targets#L13

So there is something wrong when bumping TFV's, we should fix this and test for it since it affects Mac users.

**Comment by brendanzagaeski** [comment]
Fix included in Xamarin.Android 10.0.0.40.

Fix included on Windows in Visual Studio 2019 version 16.3 Preview 3. To try the preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 3. To try the preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
