### ISSUE TITLE
MVVMCross: Unable to load view from one android project to another project on same solution

### ISSUE THREAD

**Issue by parmendrahsc** [xamarin/xamarin-android#2615]
### Steps to Reproduce

1.  Create one Android project with first Activity and view model
2.  Create another project with second Activity and view model
3.  Navigate from first VM to second VM
4. Second Activity having two fragment 1 and fragment 2 and each have separate VM.
5. When navigating on second view load first fragment. 

### Expected Behavior
Second activity should loaded with fragment 1

### Actual Behavior

Getting exception on navigating to second activity "unable to locate view for viewmodel"

### Version Information

Microsoft Visual Studio Professional 2017 
Version 15.9.4
VisualStudio.15.Release/15.9.4+28307.222
Microsoft .NET Framework
Version 4.7.03056
 4.12.3.77 (d15-9@e3f40b477)
Xamarin Designer   4.16.13 (45a16efd4)
Xamarin Templates   1.1.128 (6f5ebb2)
Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by parmendrahsc** [comment]
Any Update ??

**Comment by parmendrahsc** [comment]
I want MvvmCross with two core libraries

**Comment by Strifex** [comment]
You may want to try Mvvmcross's github page - I don't think this is the correct place for this question.  https://github.com/MvvmCross/MvvmCross  Also, I suggest you create a sample project and link it when you open an issue on the mvvmcross git page.

**Comment by dellis1972** [comment]
Can you provide an example project showing the issue please?

**Comment by parmendrahsc** [comment]
@dellis1972 
Create a 1 Core lib project CoreLib1 and two Android project, MVVMAndroid and Android2
MvvmAndroid have three pages page1 page2 page3
Android2 have one page page4
Navigate to 1->2->3->4
Actual Behavior: Activity 4 showing only white screen.

Attached Sample: https://drive.google.com/file/d/1H0zD9_0z-MNRv5taNo3k2MyNBHBImHag/view?usp=drive_web

Version: 6.2 Platform: iphone: iOS Android

**Comment by jonathanpeppers** [comment]
@parmendrahsc your sample project doesn't appear to be complete, I'm getting lots of errors about MvvmCross types being missing:
```
CS0246	The type or namespace name 'MvxViewModel' could not be found (are you missing a using directive or an assembly reference?)	CoreLib1	C:\src\AndroidMvvm\CoreLib1\ViewModels\BaseViewModel.cs
```

I think @Strifex is right, and you should file something on MvvmCross's Github?

Closing for now, but feel free to reopen if you can get your sample to build. A full [Android device log](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows) showing the crash would help as well.
