### ISSUE TITLE
Problem with Java interface binding

### ISSUE THREAD

**Issue by manuelelucchi** [xamarin/xamarin-android#2616]
Hi, i'm binding the Nordicsemi DFU Library (https://github.com/NordicSemiconductor/Android-DFU-Library/) and there's this strange compilation error. This happens when i link the binding to the final app but not when i do the same to a test app. The error is thrown by 2 interfaces that i don't directly use but some of the classes i uses do. I already set the content to EmbeddedJar (i saw that set it to InputJar could cause a similar problem) and now i have no more ideas. Would anyone help me?

Regards, 
Manuele

![image](https://user-images.githubusercontent.com/17146198/51123224-f5e32b00-181b-11e9-874b-475587e8fc1b.png)

**Comment by dellis1972** [comment]
@manuelelucchi any chance you can provide a sample project with the problem and/or diagnostic build output? It is a bit difficult to diagnose the issue from a screen shot.

**Comment by jonathanpeppers** [comment]
@manuelelucchi closing, since we haven't heard from you in a while.

Feel free to comment/reopen if you can send us an example of your binding project, thanks!
