### ISSUE TITLE
`AndroidClientHandler` incorrectly deals with redirect + gzip

### ISSUE THREAD

**Issue by ElteHupkes** [xamarin/xamarin-android#2619]
### Steps to Reproduce
I've created a simple repro project:
[HttpCrashApp.zip](https://github.com/xamarin/xamarin-android/files/2759817/HttpCrashApp.zip)

1. Create a blank Xamarin.Android project using the `AndroidClientHandler`
2. Somewhere in the project, do something like this:
```
var client = new System.Net.Http.HttpClient(new AndroidClientHandler());
var result = await client.GetAsync("https://acc-portal.srxp.com/static/countries.json");
var contentString = await result.Content.ReadAsStringAsync();
Console.Out.WriteLine(contentString);
```
3. Check what that file [actually looks like in your browser](https://acc-portal.srxp.com/static/countries.json).

The supplied URL redirects to a different file on CloudFront, which is sent to the client using gzip encoding (with the appropriate headers).

### Expected Behavior
The logged result should be the readable JSON we see in the browser. This is working as expected using, for instance, ModernHttpClient's NativeMessageHandler.

### Actual Behavior
The contents are some binary scramble, likely the gzipped version of the file.

### Version Information

Visual Studio Community 2017 for Mac
Version 7.7.2 (build 21)
Installation UUID: ccf6f6c1-ad58-4aa7-849b-9a9ced210760
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

Mono Framework MDK
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

NuGet
Version: 4.8.0.5385

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.2
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

Xamarin.iOS
Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

Xamarin.Android
Version: 9.1.4.2 (Visual Studio Community)
Android SDK: /Users/elte/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.2

Java SDK: /Users/elte/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 7.7.1.0
Hash: 06ceaea1

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 707020021
Git revision: f1fea53df9eb0bb5890a9563c0d7ea7b03922144
Build date: 2018-12-14 18:37:35+00
Build branch: release-7.7
Xamarin extensions: 9c5cea335e6a9ce4ccfde31c4aa06c25a3576085

Operating System
Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

### Log File
Not relevant.

**Comment by dellis1972** [comment]
The WebBrowser makes the following request. 

```
Summary
URL: https://d31ptko4hx9sw5.cloudfront.net/acc/static/countries.json
Status: 200
Source: Network
Address: 143.204.178.122:443

Request
:method: GET
:scheme: https
:authority: d31ptko4hx9sw5.cloudfront.net
:path: /acc/static/countries.json
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: keep-alive
Host: d31ptko4hx9sw5.cloudfront.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15
Accept-Language: en-gb
DNT: 1
Accept-Encoding: br, gzip, deflate
```

Note that `Accept-Encoding` is `gzip`. The response is indeed `gzipped`

```
Response
:status: 200
Content-Type: application/json; charset=utf-8
Age: 108
Via: 1.1 b029ee882e6b0b302c9c841990ea3e04.cloudfront.net (CloudFront)
Content-Encoding: gzip
Expires: Tue, 01 Jan 2030 00:00:00 GMT
Cache-Control: max-age=63072000, public
Date: Mon, 21 Jan 2019 09:03:36 GMT
Content-Length: 2776
Accept-Ranges: bytes
ETag: "f9d44a491b153f7e308e70c9a1db3216"
Last-Modified: Fri, 18 Jan 2019 11:56:08 GMT
x-amz-cf-id: XxBRDrcICa1rnWclT-c-eZxkcgIB3XFYCDialrZqMFrwfLU7HUCV_Q==
x-cache: Hit from cloudfront
x-amz-server-side-encryption: AES256
Server: AmazonS3
```

The `AndroidClientHanders` has a `AutomaticDecompression` which will set the  `Accept-Encoding:` header.
By default however the `AndroidClientHandler` does not set these [headers](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.automaticdecompression?view=netframework-4.7.2), they default to `None`. So you need to use the following code

```
var client = new System.Net.Http.HttpClient(new AndroidClientHandler () {
    AutomaticDecompression = System.Net.DecompressionMethods.GZip | System.Net.DecompressionMethods.Deflate,
});
```

**Comment by ElteHupkes** [comment]
@dellis1972 Thanks for that information! Because it "just worked" in other situations (the rest of our API is also gzipped, though perhaps conditionally) I just assumed it was a bug in the client handler. I don't think I would've figured this out otherwise..
