### ISSUE TITLE
AOT breaks mapping of classes containing Enum properties with AutoMapper

### ISSUE THREAD

**Issue by AlexandraMash** [xamarin/xamarin-android#2625]
### Problem summary

We are using **AutoMapper** to map some DTO’s to models in our Xamarin.Android app. Everything is working fine. The problem occurs when we are enabling **AOT** for Android build. If we are mapping some classes that contain a property of **Enum** type, obtained value is reset to default one for this property. It works correctly without AOT enabled.

### Steps to Reproduce

[AotSample.zip](https://github.com/xamarin/xamarin-android/files/2769842/AotSample.zip)

1. Open Sample project (AotSample.zip)
2. Select AotStaging configuration and run the project on Android device
3. Push 'Convert' button to map a DTO object with MinimalLevel = level1 to a model object

### Expected Behavior

The result string shall contain correct mapped value _MinimalLevel = level1_

### Actual Behavior

The result string contains incorrect value _MinimalLevel = level0_ (default one)

**Note:** If you select Staging configuration in sample project and run the app - mapping result will be correct

### Devices on which we tested

Google Pixel 2 XL (9.0)
Nexus 5X (7.1.1)

### Sample project setup

**Xamarin Android** application (AotSample.Droid) with a **.NET Standard 2.0 Library** referenced (AotSample.Core)
using NuGet package **AutoMapper 8.0.0**
Target Android version is 8.0 (**Api level 26**)

### Sample project description:

We have prepared a sample to demonstrate the issue. The project has two custom configurations: **Staging** and **AotStaging** - they are similar except for AOT setting which is disabled in the first one and is enabled in the second.

There is ResponseDTO class which has one bool property and one _LevelDTO_ property (which is a custom enum). _LevelDTO_ has 3 values: _Level0(default), Level1, Level2_.

```
public class ResponseDTO
{
    public bool IsSuccess { get; set; }
    public LevelDTO MinimalLevel { get; set; }
}
```
```
public enum LevelDTO
{
   [EnumMember(Value = "level0")]
    Level0 = 0,

   [EnumMember(Value = "level1")]
    Level1 = 1,

   [EnumMember(Value = "level2")]
    Level2 = 2
}
```

And there two corresponding model classes _ResponseModel_ and _LevelModel_.

AutoMapper is set up with two maps (_MappingProfiles.cs_):

```
CreateMap<ResponseDTO, ResponseModel>();
CreateMap<LevelDTO, LevelModel>();
```

In our _MainActivity_ with its _ViewModel_ by button tap we are **converting a ResponseDTO with MinimalLevel = LevelDTO.Level1 to a ResponseModel** with

`Mapper.Map<ResponseModel>(responseDTO);`

And we are displaying the result.

Result **without AOT** enabled (Staging configuration):

_MinimalLevel = level1_ - **correct**

Result **with AOT** enabled (AotStaging configuration):

_MinimalLevel = level0_ - this is an **error**

By the way mapping from LevelDTO to LevelModel directly seems to work correctly. 

### Note

Currently we have a problem with deploying the project to a device - sometimes it will not deploy in custom configurations because it tries to find referenced AotSample.Core dll in bin/Debug folder instead of bin/Staging for instance. Though it builds to the correct output paths. Have no idea how to fix it for now.

### Version Information

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.7.2 (build 21)
Installation UUID: b7b1e350-00e0-47f1-a47e-2db9ff5fe3da
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.1.4.2 (Visual Studio Enterprise)
Android SDK: /Users/amashenkova/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.2

Java SDK: /Users/amashenkova/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: 06ceaea1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.iOS ===

Version: 12.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707020021
Git revision: f1fea53df9eb0bb5890a9563c0d7ea7b03922144
Build date: 2018-12-14 18:37:35+00
Build branch: release-7.7
Xamarin extensions: 9c5cea335e6a9ce4ccfde31c4aa06c25a3576085

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Fri Nov  2 20:43:16 PDT 2018
    root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

**Comment by dellis1972** [comment]
I suspect this is not an AOT issue as such, but a linker issue. Its possible the linker is removing the types that are not being used. I have managed to repo the issue, I think it needs someone with a bit more knowledge about AOT and the Linker to investigate. @radekdoulik any ideas?

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
