### ISSUE TITLE
[VS 2019] issues building Xamarin.Android and running tests

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#2627]
### Steps to Reproduce

If using VS 2019, there are a few problems building Xamarin.Android itself (and running tests).

* It seems anything referencing `MSBuild` assemblies now needs `$(TargetFrameworkVersion)` 4.7.2. We should look into making a `$(DefaultTargetFrameworkVersion)` property in `Configuration.props` at the same time.
* `xabuild.exe` doesn't work as-is
* `Xamarin.Android.Build.Tests` won't pass as-is

### Expected Behavior

We should be able to develop Xamarin.Android with VS 2019.

### Actual Behavior

You get build errors and/or test errors with VS 2019.

### Other concerns

We have a bit of code looking for `MSBuild.exe`.

This isn't quite right, so we should *also* invest in making that better by either:
- Use [MSBuild.Locator](https://www.nuget.org/packages/Microsoft.Build.Locator/) _if licensing permits_
- Use [vswhere](https://github.com/Microsoft/vswhere)

> VS bug [#770851](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770851)

**Comment by kzu** [comment]
Maybe I should just close #2633?
