### ISSUE TITLE
Environment.TickCount only has a 10ms resolution

### ISSUE THREAD

**Issue by RowanHarris** [xamarin/xamarin-android#2641]
### Steps to Reproduce

1. Insert the following code into any project and run it
            for (var i = 0; i < 50; i++)
            {
                Log.Info("TickCount", "tic " + Environment.TickCount);
                Thread.Sleep(1);
            }
2. Check the output and notice that the time only has 10ms resolution

### Expected Behavior
the Environment.TickCount should increment in ms not just 10ms increments

### Actual Behavior
The sleep for 1ms is working however the Environment.TickCount is reporting the same time after the sleep as before the sleep, the resolution is 10ms. 
I think the solution to this old bug that I posted https://bugzilla.xamarin.com/show_bug.cgi?id=58413 caused this problem. Before that bug was fixed it used to have 1ms resolution. However now it only has 10ms resolution.

### Version Information

Microsoft Visual Studio Community 2017 
Version 15.9.5
VisualStudio.15.Release/15.9.5+28307.280
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA125
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JavaScript Language Service   2.0
JavaScript Language Service

JetBrains ReSharper Ultimate 2018.3.1   Build 183.0.20181225.200351
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.28107.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9.28218
Visual C++ for Linux Development

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Unity   3.9.0.3
Visual Studio Tools for Unity

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VisualSVN   6.2.2
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at https://www.visualsvn.com
Copyright © 2018 VisualSVN Software Ltd. All rights reserved.

Xamarin   4.12.3.78 (d15-9@a9bbf702f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.5.0 (HEAD/4b951a3e7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
### Log File

01-21 13:25:02.720: I/TickCount(3897): tic 381608
01-21 13:25:02.720: I/TickCount(3897): tic 381608
01-21 13:25:02.720: I/TickCount(3897): tic 381608
01-21 13:25:02.720: I/TickCount(3897): tic 381608
01-21 13:25:02.720: I/TickCount(3897): tic 381608
01-21 13:25:02.720: I/TickCount(3897): tic 381608
01-21 13:25:02.720: I/TickCount(3897): tic 381608
01-21 13:25:02.720: I/TickCount(3897): tic 381608
01-21 13:25:02.730: I/TickCount(3897): tic 381618
01-21 13:25:02.730: I/TickCount(3897): tic 381618
01-21 13:25:02.730: I/TickCount(3897): tic 381618
01-21 13:25:02.730: I/TickCount(3897): tic 381618
01-21 13:25:02.730: I/TickCount(3897): tic 381618
01-21 13:25:02.730: I/TickCount(3897): tic 381618
01-21 13:25:02.730: I/TickCount(3897): tic 381618
01-21 13:25:02.730: I/TickCount(3897): tic 381618
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.740: I/TickCount(3897): tic 381628
01-21 13:25:02.750: I/TickCount(3897): tic 381638
01-21 13:25:02.750: I/TickCount(3897): tic 381638
01-21 13:25:02.750: I/TickCount(3897): tic 381638
01-21 13:25:02.750: I/TickCount(3897): tic 381638
01-21 13:25:02.750: I/TickCount(3897): tic 381638
01-21 13:25:02.750: I/TickCount(3897): tic 381638
01-21 13:25:02.750: I/TickCount(3897): tic 381638
01-21 13:25:02.760: I/TickCount(3897): tic 381648
01-21 13:25:02.760: I/TickCount(3897): tic 381648
01-21 13:25:02.760: I/TickCount(3897): tic 381648
01-21 13:25:02.760: I/TickCount(3897): tic 381648
01-21 13:25:02.760: I/TickCount(3897): tic 381648
01-21 13:25:02.760: I/TickCount(3897): tic 381648
01-21 13:25:02.760: I/TickCount(3897): tic 381648
01-21 13:25:02.760: I/TickCount(3897): tic 381648
01-21 13:25:02.770: I/TickCount(3897): tic 381658
01-21 13:25:02.770: I/TickCount(3897): tic 381658
01-21 13:25:02.770: I/TickCount(3897): tic 381658
01-21 13:25:02.770: I/TickCount(3897): tic 381658
01-21 13:25:02.770: I/TickCount(3897): tic 381658
01-21 13:25:02.770: I/TickCount(3897): tic 381658

**Comment by jonathanpeppers** [comment]
Hi @RowanHarris this is actually true: https://docs.microsoft.com/en-us/dotnet/api/system.environment.tickcount?view=netframework-4.7.2

> The value of this property is derived from the system timer and is stored as a 32-bit signed integer. Note that, because it is derived from the system timer, the resolution of the TickCount property is limited to the resolution of the system timer, which is typically in the range of 10 to 16 milliseconds.

If you are trying to get precise timing information, try the [Stopwatch](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch?view=netframework-4.7.2) class.

Closing this as "by-design". Sorry! Feel free to comment more about what you are trying to do, I may have suggestions, thanks!
