### ISSUE TITLE
Unable to find package Rx-Core

### ISSUE THREAD

**Issue by justintoth** [xamarin/xamarin-android#2645]
### Steps to Reproduce

1. Open a Xamarin Android app.
2. Expand the packages section, and note that updates are available for System.Reactive and System.Reactive.Linq.
3. Try to update the packages.

### Expected Behavior

The packages will update.

### Actual Behavior

The packages don't update.

> Unable to find package 'Rx-Core'. Existing packages must be restored before performing an install or update.

### Version Information

=== Visual Studio Community 2017 for Mac ===

Version 7.7.3 (build 43)
Installation UUID: 94f26f0a-434b-4c18-a29a-d9750ccc8a4a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.2
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Version: 2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.1.5.1 (Visual Studio Community)
Android SDK: /android/sdk
	Supported Android versions:
		5.0 (API level 21)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 27.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/justintoth/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: 06ceaea1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 12.2.1.13 (Visual Studio Community)
Hash: a4332c90
Branch: d15-9
Build date: 2019-01-11 13:08:09-0500

=== Build Information ===

Release ID: 707030043
Git revision: 5896ab2acba037c62271742e9e56b900c96c1d8f
Build date: 2019-01-15 21:18:33+00
Build branch: release-7.7
Xamarin extensions: e5b43ba963b7b407aa5b9f2c59018c32a709e6ab

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by jonathanpeppers** [comment]
@justintoth can you attach a sample project we can see the problem?

I suspect there is an issue with NuGet or VS Mac's NuGet integration, and it's not anything to do with Xamarin.Android?

**Comment by justintoth** [comment]
[rpr-mobile-test.zip](https://github.com/xamarin/xamarin-android/files/2796728/rpr-mobile-test.zip)

@jonathanpeppers  Sample project attached... I deleted the packages folder so minimize the download size, so you'll obviously have to do a package restore first before trying to update.

**Comment by justintoth** [comment]
Very helpful actually, thanks! It looks like Rx-Core was removed from nuget: [https://www.nuget.org/packages/rx-core/2.2.5](https://www.nuget.org/packages/rx-core/2.2.5). The funny thing is, this isn't a package we added, it was a dependency for some other more common package, but looks like it's no longer required now.
