### ISSUE TITLE
Add support for HttpClient.PatchAsync()

### ISSUE THREAD

**Issue by terrajobst** [xamarin/xamarin-android#2650]
_From @jacobmohl on January 23, 2019 14:50_

It would make sense to support the HTTP Verb PATCH in HttpClient. Which for now is only supported in .Net Core 2.1 and forward with HttpClient.PatchAsync().

_Copied from original issue: dotnet/standard#1056_

**Comment by terrajobst** [comment]
Sorry, selected the wrong issue to be moved :-(

**Comment by jacobmohl** [comment]
Even rockstars make mistakes @terrajobst :-)
