### ISSUE TITLE
Android project options which require the NDK are no longer working in VS2019 previews

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2652]
### Steps to Reproduce

1. Install the latest VS2019 preview.
2. Ensure you have a recent NDK version installed at $(AndroidSdk)/ndk-bundle.
3. Attempt to build an Android project with AOT enabled.

### Expected Behavior
The NDK path is resolved correctly.

### Actual Behavior
Projects which require the NDK fail to build.

### Version Information
https://gist.github.com/pjcollins/28034d1b01aa5e7893f007f2d3d846cc

### Log File
https://gist.githubusercontent.com/pjcollins/fb3748890b3c2f8cbb4cbd13f39237e6/raw/31eff9a5ecb0ae543572291242fa44f9fe140138/gistfile1.txt

> VS bug [#778535](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/778535)

**Comment by dellis1972** [comment]
PR was merged into d16-0 branch. We need to test to make sure this change fixed the issue.
