### ISSUE TITLE
Build regression with MyDriving on master

### ISSUE THREAD

**Issue by garuma** [xamarin/xamarin-android#2657]
### Steps to Reproduce

1. Run "Restore;Build" target on MyDriving Android sample app (https://github.com/Azure-Samples/MyDriving/tree/master/src/MobileApps/MyDriving/MyDriving.Android)

### Actual Behavior

See attached binlog.

[MyDriving-Android_Restore-Build_123.zip](https://github.com/xamarin/xamarin-android/files/2799615/MyDriving-Android_Restore-Build_123.zip)

### Version Information

Commercial monodroid master 2d8ca9e55ebe74513df8072b0096f372cf0dd890

Last known working build: monodroid d16-0-p2 9a258c4311ab578e2812ae1482b3f553482ccee3

**Comment by jonathanpeppers** [comment]
After looking at this briefly, I'm thinking this NuGet package is causing it:
```
<Import Project="..\..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets" Condition="Exists('..\..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets')" />
```
We need to have a project like this in our test suite, will look into it.

**Comment by jonathanpeppers** [comment]
@dellis1972 maybe you can help figure out what is going on.

This is weird, but I basically did:
```
# it is packages.config
nuget restore C:\src\MyDriving\src\MobileApps\MyDriving.sln
# build
.\bin\Debug\bin\xabuild C:\src\MyDriving\src\MobileApps\MyDriving\MyDriving.Android\MyDriving.Android.csproj /bl
```
Which errors with:
```
"C:\src\MyDriving\src\MobileApps\MyDriving\MyDriving.Android\MyDriving.Android.csproj" (default target) (1) ->
(_CompileResources target) ->
  Resources\values\styles.xml(8): error APT0000: invalid parent reference 'style/Widget.AppCompat.ActionBar.Solid'. [C:\src\MyDriving\src\MobileApps\MyDriving\MyDriving.Android\MyDriving.Android.csproj]
  Resources\values\styles.xml(14): error APT0000: invalid parent reference 'style/Widget.AppCompat.Light.ActionBar.Solid'. [C:\src\MyDriving\src\MobileApps\MyDriving\MyDriving.Android\MyDriving.Android.csproj]
```
But if I pass `/p:AndroidUseAapt2=False` it works.

Here are binlogs with `aapt2.binlog` and `aapt.binlog`: [logs.zip](https://github.com/xamarin/xamarin-android/files/2805314/logs.zip)

**Comment by dellis1972** [comment]
```
Executing compile -o obj\Debug\90\flata\compiled.flata --dir C:\src\MyDriving\src\MobileApps\MyDriving\MyDriving.Android\obj\Debug\90\res
```

This is the line which errors. So it looks like the resources in this dir are referencing a resource from anther directory :/  so it seems we need to pass a bunch of directories to the `compile`. What is really odd is this has NOT come up before. So not sure why its not working now.

**Comment by jonathanpeppers** [comment]
Yeah this app doesn't have any changes since Oct 2017, so it's got to be something that changed in Xamarin.Android: https://github.com/Azure-Samples/MyDriving/commit/2d3cc0f2d99c5d883f1f90f9cfc26f53f3b127bf

Master also has `AndroidUseAapt2` by default, so it makes sense why d16-0 is working OK here.

**Comment by dellis1972** [comment]
@garuma is this still an issue?

**Comment by garuma** [comment]
I think we got to the bottom of this one. Closing.
