### ISSUE TITLE
D8-R8 build fails with  java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/xamarin-android#2669]
i have added d8 and r8 in my android configuration and disabled MultipleDex as shown below and used my existing proguard file which i use with multipledex+proguardenabled=true settings. it returns error as below. I have created an empty project and copied same settings and proguard file. Problem can be reproduced with attached sample. please find the attached simply and build release.

```
   <AndroidEnableMultipleDex>false</AndroidEnableMultipleDex>
    <AndroidExplicitCrunch>true</AndroidExplicitCrunch>
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidLinkTool>r8</AndroidLinkTool>
```

**Error:**
```
8>(_CompileToDalvikWithD8 target) -> 
8>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets(81,5): error : java.lang.StringIndexOutOfBoundsException: String index out of range :  4735
8>
```

[App1.zip](https://github.com/xamarin/xamarin-android/files/2810654/App1.zip)

**Comment by EmilAlipiev** [comment]
I played around a bit and problem was with my proguard. by doing try and fail for each proguard configuration i found that i had this line below and it was causing r8 to fail while proguard doesnt fail.  

`-optimizations !field/removal/writeonly,!field/marking/private,!class/merging/*,!code/allocation/variable`

**Comment by jonathanpeppers** [comment]
I tried your rule, and it's breaking for me the exact same way, even if I just specify one rule: `-optimizations !field/removal/writeonly`.

Unfortunately I can't find documentation showing r8 doesn't support `-optimizations`, best is: https://www.guardsquare.com/en/blog/proguard-and-r8

I think all we can do is file this on r8's issue tracker: https://issuetracker.google.com/issues?q=componentid:326788

Closing as I don't think there is anything we can do in Xamarin.Android?
