### ISSUE TITLE
AndroidEnableDesugar=true doesn't work

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/xamarin-android#2676]
### Steps to Reproduce
i use configuration as below

```
 <AndroidEnableMultipleDex>false</AndroidEnableMultipleDex>
    <AndroidExplicitCrunch>true</AndroidExplicitCrunch>
<AndroidEnableDesugar>True</AndroidEnableDesugar>
   <EnableProguard>true</EnableProguard>
```
 
### Actual Behavior
it returns error as java exited with code 1
### Version Information
xamarin version:3.4

please find attached repro. simply rebuild it in release mode.
[App1.zip](https://github.com/xamarin/xamarin-android/files/2817478/App1.zip)

**Comment by jonathanpeppers** [comment]
@EmilAlipiev this project is using our old "desugar" support. It is old and has some problems. I believe it came from the old jack/jill feature from Android Studio.

A better solution going forward is to just use `<AndroidDexTool>d8</AndroidDexTool>` (available as of 2019 Preview 2) and you can just omit `<AndroidEnableDesugar>True</AndroidEnableDesugar>` from your project.

**Comment by jonathanpeppers** [comment]
Using VS 2019 Preview 3, I was able to build the attached project.

I think the problem you were hitting was fixed by: https://github.com/xamarin/xamarin-android/pull/2158

Let me know if you think otherwise!
