### ISSUE TITLE
[Reminder] Add support for new AOT modes

### ISSUE THREAD

**Issue by grendello** [xamarin/xamarin-android#2677]
Mono is[ adding new AOT modes](https://github.com/mono/mono/pull/12516). This is a reminder to us to add support for them once Mono support is in the branch we use.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.
