### ISSUE TITLE
 Firebase.Firestore.FieldValue does not contain a definition for ArrayUnion

### ISSUE THREAD

**Issue by sdiaz-qkt** [xamarin/xamarin-android#2689]
Hello. I'm currently working with Firestore in iOS and Android using Xamarin. I'm trying to add a value to an existing array in firestore. In iOS I had no problems using FieldValue.FromArrayUnion(obj). However in Android I'm having a hard time since this method does not exist.  I believe this should be consider a bug, specially since I still has no clue on how to add a value to my array in Xamarin.Android.

**Comment by jonathanpeppers** [comment]
This issue was moved to xamarin/GooglePlayServicesComponents#177
