### ISSUE TITLE
Validate minSdkVersion

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#2692]
Context: https://github.com/xamarin/xamarin-android/issues/2690
Context: Commit 590e53c56f025a69b8d955b2dfdbc41df923173a

### Steps to Reproduce

1. Create a new project.
2. Open `Properties\AndroidManifest.xml`
3. Set the `//uses-sdk/@android:minSdkVersion` and `//uses-sdk/@android:targetSdkVersion` properties to 8.

### Expected Behavior

A warning or error *should* be issued, stating that this configuration is not supported, because the resulting `.apk` file will reference the [`ApplicationInfo.nativeLibraryDir` field](https://developer.android.com/reference/android/content/pm/ApplicationInfo#nativeLibraryDir), which was added in API-9, and thus may prevent `classes.dex` from being loaded.

### Actual Behavior

As of commit 590e53c56f025a69b8d955b2dfdbc41df923173a, the project builds.  No warning or error about `minSdkVersion` is issued.

A warning about `targetSdkVersion` *is* issued:

    warning XA4211: AndroidManifest.xml //uses-sdk/@android:targetSdkVersion '8' is less than $(TargetFrameworkVersion) ''. Using API-28 for ACW compilation

**Comment by jonathanpeppers** [comment]
Looks like the warning could be added here: https://github.com/xamarin/xamarin-android/blob/590e53c56f025a69b8d955b2dfdbc41df923173a/src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs

It already has the manifest opened.

**Comment by pjcollins** [comment]
@jonpryor @jonathanpeppers it looks like I am a bit late here but I thought that we had discussed that an error would be best in this scenario, as we know targets lower than < 9 won't work?
