### ISSUE TITLE
Xamarin.Android in Visual Studio 2019 Preview cannot find the Android NDK at the standard install location from the Visual Studio Installer

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#2694]
This is the first of a few follow-up bugs related to:

  * https://github.com/xamarin/xamarin-android/issues/2652
  * https://github.com/xamarin/xamarin-android/issues/2673
  * https://developercommunity.visualstudio.com/content/problem/439101/visual-studio2019-ndk-location-path-is-missing-in.html

These problems stem from two changes in Visual Studio 2019 Preview:

 1. The Visual Studio Tools for Xamarin no longer set the `AndroidNdkDirectory` property of the `HKCU\SOFTWARE\Xamarin\VisualStudio\*\Android` registry key. The motivation behind that change is that the Android SDK Manager can now be used to fetch the NDK instead of the Visual Studio Installer, and in that case the path of the NDK will be *within* the Android SDK directory and won't need its own registry entry. One tricky remaining question is to decide how and when to help users install the NDK via the Android SDK Manager rather than via the Visual Studio Installer.
 2. The Visual Studio Installer no longer shows the Android NDK as an optional component associated with the **Mobile development with .NET** workload. But the Android NDK is still available under **Individual components** and as part of the **Mobile development with C++** workload. I will plan to file a follow-up item in Developer Community related to this. There are some pros and cons to consider, but maybe the **Mobile development with .NET** workload can rely on the **Auto Install Android SDKs** feature for on-demand installation of Android NDK.

### Steps to Reproduce

 1. Install Visual Studio Enterprise 2019 Preview with the **Mobile Development with .NET** workload and the one **Optional** component offered for that workload: **Android SDK setup (API level 27)**. For the purposes of this scenario, it doesn't matter if Visual Studio 2017 is also installed or not.
 2. Create a new **Android App (Xamarin) > Single View App**.
 3. In the project options, enable **Android Options > Bundle assemblies into native code** or **Android Options > AOT Compilation (Experimental)** for the Release configuration.
 4. Attempt to archive the project via **Build > Archive**, or attempt to create a signed APK on the command-line:
    ```cmd
    msbuild -t:SignAndroidPackage -p:Configuration=Release AndroidApp1.sln
    ```
 5. Go back to the Visual Studio Installer. Under **Individual components**, select and install **SDKs, libraries, and frameworks > Android NDK (R16B)**.
 6. Try step 4 again.

### Expected Behavior

The build should at least be able to find the Android NDK from the new location created at step 5. It might also be desirable for the build to be able to find Android NDK versions installed by Visual Studio 2017 version 15.9.6 or earlier.

### Actual Behavior

Both step 4 and step 6 fail.

If **AOT Compilation (Experimental)** is enabled, the error is:

```txt
error XA5101: Missing Android NDK toolchains directory '\toolchains'. Please install the Android NDK.
```

If **Bundle assemblies into native code** is enabled, the error is:

```txt
(_BuildApkEmbed target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2758,3): error : Could not find a part of the path 'C:\platforms'.
```

(A separate problem is that **Bundle assemblies into native code** should produce the same error message as **AOT Compilation** rather than the confusing message about "C:\\platforms". I will plan to file a follow-up issue for that problem.)

### Rough sketch of a possible fix

[external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs](https://github.com/xamarin/xamarin-android-tools/blob/master/src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs) already includes a list of hardcoded fallback search paths, but it turns out the entries for Visual Studio 2017 are outdated. The install prefixes for the *AndroidNDK_\*.swixproj* components in the Visual Studio Installer were changed from `[CommonApplicationData]` to `[SharedInstallDir]` in February 2018. (Visual Studio 2019 Preview also uses `[SharedInstallDir]` for the NDKs.) For the common case where `[SharedInstallDir]` is `C:\`, the following patch would suffice. If anyone knows a good way to get the actual `[SharedInstallDir]`, that would be even better.

```diff
diff --git a/src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs b/src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
index f05a5b6..8ac5687 100644
--- a/src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
+++ b/src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
@@ -208,12 +208,14 @@ namespace Xamarin.Android.Tools
 			// Check some hardcoded paths for good measure
 			var xamarin_private = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.LocalApplicationData), "Xamarin", "MonoAndroid");
 			var vs_default = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.CommonApplicationData), "Microsoft", "AndroidNDK");
-			var vs_default32bit = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.CommonApplicationData), "Microsoft", "AndroidNDK32");
-			var vs_2017_default = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.CommonApplicationData), "Microsoft", "AndroidNDK64");
+			var vs_2017_old_default32bit = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.CommonApplicationData), "Microsoft", "AndroidNDK32");
+			var vs_2017_old_default = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.CommonApplicationData), "Microsoft", "AndroidNDK64");
+			var vs_2017_default32bit = Path.Combine (@"C:\", "Microsoft", "AndroidNDK32");
+			var vs_2017_default = Path.Combine (@"C:\", "Microsoft", "AndroidNDK64");
 			var android_default = Path.Combine (OS.ProgramFilesX86, "Android");
 			var cdrive_default = @"C:\";
 
-			foreach (var basePath in new string [] {xamarin_private, android_default, vs_default, vs_default32bit, vs_2017_default, cdrive_default})
+			foreach (var basePath in new string [] {xamarin_private, android_default, vs_default, vs_2017_old_default32bit, vs_2017_old_default, vs_2017_default32bit, vs_2017_default, cdrive_default})
 				if (Directory.Exists (basePath))
 					foreach (var dir in Directory.GetDirectories (basePath, "android-ndk-r*"))
 						if (ValidateAndroidNdkLocation (dir))
```

VS bug [#786244](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/786244)

**Comment by brendanzagaeski** [comment]
Correction: The current install prefix for the Android NDK in the Visual Studio Installer is `[SharedInstallDrive]`, not `[SharedInstallDir]`. The `[SharedInstallDir]` contains space characters, and the Android NDK commands don't work as expected when invoked from a path that contains spaces.

**Comment by brendanzagaeski** [comment]
> ... two changes in Visual Studio 2019 Preview:
> ...
> 2\. The Visual Studio Installer no longer shows the Android NDK as an optional component associated with the **Mobile development with .NET** workload.

Correction: This change was introduced in Visual Studio 2017 version 15.6. In that version, the Android NDK is no longer installed for the **Mobile development with .NET** workload. In contrast, in Visual Studio 2017 version 15.5.7, the **Mobile development with .NET** workload *did* show the **Android NDK (R13B)** optional component and had it selected by default. Users who originally installed Visual Studio 2017 using version 15.5.7 or earlier would not have had to think about their Android NDK installations for quite a while.

**Comment by brendanzagaeski** [comment]
I have added some telemetry analysis about this scenario in the [corresponding non-public work item](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/786244).

**Comment by brendanzagaeski** [comment]
The current tentative plan is to continue to monitor this issue in Visual Studio 2019, and adjust the behavior if necessary depending on user feedback. I will accordingly adjust the milestone to "d16-1" for now.

**Comment by mfkl** [comment]
Have a consistent repro [here](https://github.com/videolan/libvlcsharp/pull/124), if you're interested.

**Comment by albilaga** [comment]
I also have this issue on VS4Mac with version 8.9.6

**Comment by albilaga** [comment]
Oh looks like it is working. I need to install NDK from Android SDK Manager from Visual Studio instead from Rider or Android Studio. Even the location is the same :S
