### ISSUE TITLE
[DevCom][DTB] AXML Layout takes a long time

### ISSUE THREAD

**Issue by grendello** [xamarin/xamarin-android#2702]
Developer Community issue: https://developercommunity.visualstudio.com/content/problem/334566/axml-layout-118080318720057.html

Original post:

```
Problem in Layout edition for Android devices. When saving XML , aplication takes so long that even freeze for a few seconds
```

**Comment by dellis1972** [comment]
I think this is related to the `_UpdateGeneratedFiles` target. This is triggered when a user saves a Resource file. This will trigger a design time resource build for the application. Now depending on settings this may well call `aapt` which (on a big project) is know to take some time.  That said on later versions of Xamarin.Android we moved all the design time resource building to use a Managed Resource Parser. Which should be significantly quicker than `aapt`. 

We could do with the IDE diagnostic logs on this one to try to figure out what is taking all the time.

**Comment by dellis1972** [comment]
Looks like the customer was on an older version of VS. This is related to this issue https://devdiv.visualstudio.com/DevDiv/_workitems/edit/649008 which was closed. So I am going to close this Issue. 

Please reopen if someone manages to repo this issue.
