### ISSUE TITLE
[unit-tests] Better ignore network failures

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#2734]
Consider: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1515/testReport/(root)/AndroidClientHandlerTests/Mono_Android_Tests__Xamarin_Android_NetTests_AndroidClientHandlerTests_Sanity_Tls_1_2_Url_WithMonoClientHandlerFails___Release_Aot/

This is a failing unit test:

>     SHOULD NOT BE REACHED: BTLS is present, TLS 1.2 should work. Network error? System.AggregateException: One or more errors occurred. (An error occurred while sending the request) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
>      at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <fc03879c3a9b4b62b04a8caa2c7661df>:0 
>      at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <fc03879c3a9b4b62b04a8caa2c7661df>:0 

The assertion happens at: https://github.com/xamarin/xamarin-android/blob/23c30056a8a11b1bf80a2b7bb7d64b44b4351545/src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs#L252

The apparent problem is that `RunIgnoringNetworkIssues()` is only checking for a `WebException`, but -- as seen above -- we instead have an `AggregateException` -> `HttpRequestException` -> `WebException`, and this intermediate `HttpRequestException` trips up our "ignore connection failures" logic:

https://github.com/xamarin/xamarin-android/blob/23c30056a8a11b1bf80a2b7bb7d64b44b4351545/src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs#L160-L170

We should fix `RunIgnoringNetworkIssues()` to support this new nested exception structure.

**Comment by grendello** [comment]
This is a red herring. The assertion is reached because connection to https://tls-test.internalx.com times out and the `SocketException` exception is thrown before we have any chance to set `supportTls1_2 = true`. In other words, there's nothing to fix in the test (except for using a different host...)
