### ISSUE TITLE
[Xamarin.Android.Build.Tasks] build error JavaSourceJar xxxx.stamp not exist

### ISSUE THREAD

**Issue by daddycoding** [xamarin/xamarin-android#2745]
### Steps to Reproduce

1. I tried to create a binding library from  [glide](https://github.com/bumptech/glide/releases/tag/v3.7.0)
download glide-3.7.0-javadoc.jar  glide-3.7.0.jar   and set action build to JavaDocJar
2. build binding library
3. 

### Expected Behavior
build success and binding library has  original Java parameter
### Actual Behavior
build error xxxx.stamp not exist 
### Log File
Xamarin.Android.Bindings.targets   
`<Touch Files="@(JavaDocJar->'$(IntermediateOutputPath)javadocs\%(FileName).stamp')" /> `
maybe miss the attribute  AlwaysCreate="True"

**Comment by Daddoon** [comment]
This bug is still present on Visual Studio 2019 Preview 4.
I'm unable to create the JavaDoc, expect if i set AlwaysCreate="True" on the Xamarin.Android.Bindings.targets.

As it's from Visual Studio installation, it's not ideal at all.
