### ISSUE TITLE
Could not AOT assembly when using Automated build

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/xamarin-android#2751]
I am building a **Xamarin.Android** in release mode using an automated build using **Azure DevOps**

I have AOT turned on with LLVM turned on (I know previously AOT was "Experimental" but I think its now production ready)

I can build my project locally but when using MSBuild I get the following errors:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: System.Data.DataSetExtensions.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: Xamarin.Forms.GoogleMaps.Android.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: CarouselView.FormsPlugin.Android.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: Syncfusion.Core.XForms.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: Plugin.Messaging.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: Syncfusion.DocIORenderer.Portable.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: SQLitePCLRaw.provider.e_sqlite3.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: Syncfusion.DataSource.Portable.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: Microsoft.AppCenter.Analytics.Android.Bindings.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: Plugin.CurrentActivity.dll C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: SQLite-net.dll

The crux of this error is:

> Could not AOT the assembly: AssemblyX.dll

I have tried building on a hosted VM too and I get the same error.

I'm not sure whether this is a Visual studio bug, or a Xamarin android bug or a library bug.

I have also attached my log file
[Build Log.txt](https://github.com/xamarin/xamarin-android/files/2884625/Build.Log.txt)

I'm also not sure whether this issue is linked https://github.com/xamarin/xamarin-android/issues/2290
 because this issue is closed as fixed but I'm using the latest Visual studio

**Comment by jonathanpeppers** [comment]
The log has various errors about AOT, version of VS is `VisualStudio/15.9.7+28307.423`.

I did notice: `Build target ABI: arm64-v8a;armeabi;armeabi-v7a;x86;x86_64`

@JKennedy24 does the problem go away if you remove `armeabi`? We removed support for this in VS 2019.

**Comment by JKennedy24** [comment]
@jonathanpeppers I just checked my project and for the `AppStore` build configuration neither `armeabi` nor `x86_x64` is selected

![image](https://user-images.githubusercontent.com/9284438/53402420-a0b54000-39a9-11e9-8673-f944f6db783a.png)

**Comment by jonathanpeppers** [comment]
@JKennedy24 ok thanks, that is not the problem, then. That message from the log is something else.

**Comment by JKennedy24** [comment]
@jonathanpeppers are there any other logs that would make the error more obvious? I'm about 80% sure this was caused by a Visual Studio update

**Comment by jonathanpeppers** [comment]
@JKennedy24 I think we need either a diagnostic log (or a [binlog](http://msbuildlog.com/)).

We need to see the log message produced here: https://github.com/xamarin/xamarin-android/blob/558901f27ca2bc3f039edf31990487d144c67e98/src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs#L489-L492

Could you re-run this buid, and either specify `/v:diag`, or `/bl`? (you would have to archive the `msbuild.binlog` file as an artifact)

**Comment by JKennedy24** [comment]
I have managed to generate the bin log and attached it to this issue

Hope that helps
[Log.zip](https://github.com/xamarin/xamarin-android/files/2906538/Log.zip)

**Comment by jonathanpeppers** [comment]
@JKennedy24 thanks this helps alot, I think the actual problem is:
```
[aot-compiler stderr] Cannot open assembly 'C:\agent\_work\2\s\F\FS\FieldStrikeMove.Droid\obj\AppStore\90\android\assets\System.Data.DataSetExtensions.dll': File does not contain a valid CIL image.
```
Can you upload a copy of this assembly?

Also does it work if you uncheck the LLVM option?

![image](https://user-images.githubusercontent.com/840039/53442329-abce9700-39ce-11e9-909c-40624f79cccc.png)

**Comment by JKennedy24** [comment]
@jonathanpeppers Thanks for looking into that for me.

I have grabbed the dll you requested. It actually just comes straight from[ here](https://www.nuget.org/packages/System.Data.DataSetExtensions/4.5.0) and is installed to a .net standard 2.0 lib.

[System.Data.DataSetExtensions.zip](https://github.com/xamarin/xamarin-android/files/2909498/System.Data.DataSetExtensions.zip)

I have just tested without LLVM enabled and it still didnt work

**Comment by jonathanpeppers** [comment]
Actually @JKennedy24 the linker does process this assembly:
```
LinkAssemblies
...
Output action:     Save assembly: System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```
We are wondering if a bug is happening here with the linker. Did you upload the one from your `obj\AppStore\90\android\assets\` directory?

Do you know which NuGet package you are using that is bringing this in? I am trying to figure from your log, but the `obj\project.assets.json` looks like would be what shows the dependency tree. Could you paste that here?

If it is a specific NuGet causing it, I could create a small repro project.

**Comment by JKennedy24** [comment]
Hi Jonathan,

The System,Data.DataSetExtensions lib was grabbed from the 
`obj\AppStore\90\android\assets\` directory.

I am using [this nuget ](https://www.nuget.org/packages/System.Data.DataSetExtensions/4.5.0) Version 4.5.0 installed to a .Net standard 2.0 project.

I have uplodaed the project.assets.json file 
[project.assets.zip](https://github.com/xamarin/xamarin-android/files/2914076/project.assets.zip)

Let me know if you need anything else

**Comment by JKennedy24** [comment]
as some extra info. I refactored out that library and it built fine, so it is definitely that library. I don't know where this bug should be reported, whether its a Xamarin.Android problem or a Microsoft problem, I'll leave it open to investigate

**Comment by jonathanpeppers** [comment]
So the dependency looks like:
```
"FieldStrikeMove.Core/1.0.0": {
  "type": "project",
  "framework": ".NETStandard,Version=v2.0",
  "dependencies": {
    ...
    "System.Data.DataSetExtensions": "4.5.0",
    ...
  },
```
Is `FieldStrikeMove.Core` your own NuGet package? (might just be another project in your solution)

If we tried to create a small repro project for this, am I right in thinking it would need:
* NetStandard library
* Xamarin.Android head application
* NetStandard library uses System.Data.DataSetExtensions directly?

Are you able to create a simple project showing this issue? Thanks!

**Comment by JKennedy24** [comment]
You are correct. `FieldStrike.Core` is my own project.

You are also correct that the repo would be 

- NetStandard library
- Xamarin.Android head application
- NetStandard library uses System.Data.DataSetExtensions directly?

I'm pretty busy at the moment so probably wont be able to get time to create a repo, sorry

**Comment by jonathanpeppers** [comment]
@JKennedy24 unfortunately a simple repro works fine: https://github.com/jonathanpeppers/AotRepro

AOT succeeded: 
```
[aot-compiler stdout] JIT time: 205 ms, Generation time: 201 ms, Assembly+Link time: 2487 ms.
```

Maybe you can suggest more NuGet packages to add? Thanks!

**Comment by dktechindia** [comment]
I am getting this issue with Visual Studio Community 2019 (Version 16.1.5) and MacOS Catalina (Version 10.15 Beta (19A501i)

Any workaround for this?

**Comment by jonathanpeppers** [comment]
@dktechindia macOS Catalina dropped support for 32-bit executables. The AOT compilers that target 32-bit devices are 32-bit. This is being worked on, you can follow progress here: https://github.com/mono/mono/issues/15333
