### ISSUE TITLE
[mono-2018-10] No longer able to load certain 64bit system libraries

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2780]
I'm encountering a new crash on startup when running certain projects on 64bit devices that appears to only occur against builds from https://github.com/xamarin/xamarin-android/tree/mono-2018-10.

### Steps to Reproduce

1. Download and run https://github.com/xamarin/xamarin-forms-samples/tree/master/SkiaSharpForms/MandelAnima on a 64bit device. If deploying in Release mode, ensure `arm64-v8a` is enabled as a supported ABI.

This results in the following crash:
http://xqa.blob.core.windows.net/gist/report-37f88bd9516342a0b03dfc95c16ddb3d.txt

#### Secondary steps to Reproduce
1. Download and run https://github.com/xamarin/xamarin-forms-samples/tree/master/FormsGallery on a 64bit device. If deploying in Release mode, ensure `arm64-v8a` is enabled as a supported ABI.
2. Click on the "OpenGLView" page.

This results in the following crash:
http://xqa.blob.core.windows.net/gist/report-01671efd2d8044afbb975c331373b6a5.txt

### Version Information
Mono version: 5.20.0.228 (5849bb2f221)  (2019-02-26 21:33:32 -05:00)
XA version: 9.2.99.36 (HEAD/82e2d017)

**Comment by grendello** [comment]
This is a Mono bug, [PR opened](https://github.com/mono/mono/pull/13281) with a fix
