### ISSUE TITLE
Uploading a large media file with AndroidClientHandler throws an out of memory exception when 'Transfer-Encoding: chunked' header is set

### ISSUE THREAD

**Issue by jamesmcroft** [xamarin/xamarin-android#2805]
### Steps to Reproduce

On a low-end device with ~1 or 2 GB of RAM.

1. Upload a 500MB file to a server using HttpClient and the custom AndroidHttpClientHandler with Transfer-Encoding: chunked set in the header of the request.
2. Sometimes a OutOfMemoryError exception will be thrown explaining that there wasn't enough resource to allocate which then crashes the app.

#### Code example
```csharp
Stream fileStream = await storageFile.OpenReadAsync();
MediaUploadContent streamContent = new MediaUploadContent(fileStream); // A custom StreamContent for reporting upload progress.
streamContent.Progress += this.OnUploadProgress;

form.Add(streamContent, "File", this._mediaEntry.Name);

HttpRequestMessage request =
    new HttpRequestMessage { RequestUri = fullUri, Method = HttpMethod.Post, Content = form };

request.Headers.TransferEncodingChunked = true;

this.SetCustomHeadersAsync(request); // Sets any additional headers required by the system
if (!string.IsNullOrWhiteSpace(this.json))
{
    request.Headers.Add("Metadata", this.json);
}

try
{
    HttpResponseMessage response = cts != null
        ? await httpClient.SendAsync(
            request,
            HttpCompletionOption.ResponseHeadersRead,
            cts.Token)
        : await httpClient.SendAsync(
            request,
            HttpCompletionOption.ResponseHeadersRead);

    CheckForCustomError(response);

    response.EnsureSuccessStatusCode();
}
finally
{
    this.CompleteMediaResponse(); // Calls back to the relevant listeners to finalize media upload.
}
```

When I looked into implementing chunking in Android network requests, I started poking around in the AndroidClientHandler and noticed that the configuration for chunking is in there but doesn't appear to be configured correctly as the out of memory exception should not have occurred with the chunking size set at [line 990](https://github.com/xamarin/xamarin-android/blob/9bd0650519635091fb6da754cdb3ae068dd5aeb0/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L990) using the default (0).

Potentially a side issue, but I also noted that there isn't a way currently with this handler or as part of the request to set a custom chunking size.

### Expected Behavior

- When uploading a file with chunking, it should not throw an out of memory exception.

### Actual Behavior

- The file should upload chunked, and support a custom chunking size

### Version Information

Microsoft Visual Studio Enterprise 2017 
Version 15.9.8
VisualStudio.15.Release/15.9.8+28307.481
Microsoft .NET Framework
Version 4.8.03749

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA427
Microsoft Visual C++ 2017

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.7000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.9.02046.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.7000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.8.0.6968
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2018.3.3   Build 183.0.20190208.91313
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure HDInsight Azure Node   2.3.7000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.7000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.4
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.7000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.28224.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61902.21100
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   3.9.0.3
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.28307.421
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.12.3.80 (d15-9@914127c74)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.15 (d60abd1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by pjcollins** [comment]
@jamesmcroft sorry for the late response, but are you still encountering this issue? Is it still present in the most recent VS 2019 release?

**Comment by jamesmcroft** [comment]
@pjcollins we are currently still in the process of accessing the impact of moving to Visual Studio 2019 internally which will require us to update and modify our build system.

However, I'll install it locally and test the latest Xamarin.Android component to see if changes have resolved the issue.

**Comment by jonpryor** [comment]
Our team is unable to investigate this issue further without the requested information. Please update to the latest version of the product and if the problem still occurs, reply with the requested information.
