### ISSUE TITLE
Button.PerformHapticFeedback doesn't work well on Wear OS

### ISSUE THREAD

**Issue by yelinzh** [xamarin/xamarin-android#2833]
### Steps to Reproduce
Button.PerformHapticFeedback works well on mobile device but not on Wear OS.

```
    Button btn = FindViewById<Button>(Resource.Id.btn);
    btn.LongClick += delegate{
          btn.PerformHapticFeedback(FeedbackConstants.KeyboardTap);
    };
```
### Expected Behavior
The PerformHapticFeedback method will be called when I press the button.
### Actual Behavior
The haptic feedback happens only on the first long press and not subseqent others.
### Version Information
IDE : VS 2017 15.9.9
Version : 28.0.0.1
Platform Target:
&nbsp; &nbsp; &nbsp; &nbsp; Android Mobile
&nbsp; &nbsp; &nbsp; &nbsp; Wear OS

**Comment by pjcollins** [comment]
I think you'll want to use a different delegate, this appears to be working for me:
```csharp
button.HapticFeedbackEnabled = true;
button.LongClick += (b, args) =>
{
	((Button)b).PerformHapticFeedback(FeedbackConstants.KeyboardTap);
	args.Handled = false;
};
```

Or you could create your own listener which inherits from `View.IOnLongClickListener`.

**Comment by yelinzh** [comment]
Did you deploy the code on Wear OS?

**Comment by pjcollins** [comment]
I tested that snippet on a Huawei Watch 2. As shown above, I think you need to inform the event handler that the long press event wasn't fully handled on the first long press to continue to trigger haptic feedback, though I couldn't find any proper documentation about this after a bit of searching.
