### ISSUE TITLE
Retrieve the image stored in an imageview

### ISSUE THREAD

**Issue by lemontreexf123** [xamarin/xamarin-android#2834]
### Steps to Reproduce

1. Retrieve an image as a byte array stored in a database
2. Convert it to a bitmap and display it in an Imageview
3.  At some point the image is changed and I need to store it back in the database

### Expected Behavior
There is a easier way to save or store the image.
### Actual Behavior
Cannot directly get the image from imagview to save or store it. 
Have to write complex code to realize it:
```
BitmapDrawable bitmapDrawable = ((BitmapDrawable) imageView.Drawable);
    Bitmap bitmap;
    if(bitmapDrawable==null){
        imageView.BuildDrawingCache();
        bitmap = imageView.GetDrawingCache();
        imageView.BuildDrawingCache(false);
    }else
    {
        bitmap = bitmapDrawable .Bitmap;
    }

byte[] bitmapData;
   using (var stream = new MemoryStream())
   { 
  bitmap.Compress(Bitmap.CompressFormat.Png, 0, stream);
    bitmapData = stream.ToArray();
   }



```

**Comment by pjcollins** [comment]
Adding to the 16.1 milestone for further investigation.

**Comment by pjcollins** [comment]
I think you may be running into an Android limitation of sorts, though I am not _entirely_ sure what you're trying to accomplish. Perhaps this answer would work as a better solution - https://stackoverflow.com/a/10600736?

I would avoid using `imageView.BuildDrawingCache` and `imageView.GetDrawingCache` as they have been deprecated in API 28.
