### ISSUE TITLE
'Resource' does not exist in the current context throughout the project

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/xamarin-android#2850]
I am getting above error across the project where ever I am using word `Resource` to get the Ids of controls.

> 1>------ Rebuild All started: Project: SISAPP.PCL, Configuration: Debug Any CPU ------
> 1>  Restoring NuGet packages...
> 1>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
> 1>  Feeds used:
> 1>    C:\Users\raja\.nuget\packages\
> 1>    https://api.nuget.org/v3/index.json
> 1>  
> 1>  All packages listed in D:\raja\SIS\SIS_Product\SIS-Global-Dev\Bombat\SISAPP.PCL\packages.config are already installed.
> 1>D:\raja\SIS\SIS_Product\SIS-Global-Dev\Bombat\SISAPP.PCL\DAL\AttendanceDAL.cs(671,22,671,31): warning CS0168: The variable 'isSuccess' is declared but never used
> 1>D:\raja\SIS\SIS_Product\SIS-Global-Dev\Bombat\SISAPP.PCL\DAL\AttendanceDAL.cs(714,27,714,43): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
> 1>D:\raja\SIS\SIS_Product\SIS-Global-Dev\Bombat\SISAPP.PCL\DAL\AttendanceDAL.cs(784,30,784,32): warning CS0168: The variable 'ex' is declared but never used
> 1>D:\raja\SIS\SIS_Product\SIS-Global-Dev\Bombat\SISAPP.PCL\BusinessEntity\Student.cs(10,24,10,29): warning CS0169: The field 'Student.title' is never used
> 1>  SISAPP.PCL -> D:\raja\SIS\SIS_Product\SIS-Global-Dev\Bombat\SISAPP.PCL\bin\Debug\SISAPP.PCL.dll
> 2>------ Rebuild All started: Project: SISAPP.Droid, Configuration: Debug Any CPU ------
> 2>  Restoring NuGet packages...
> 2>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
> 2>  Feeds used:
> 2>    C:\Users\raja\.nuget\packages\
> 2>    https://api.nuget.org/v3/index.json
> 2>  
> 2>  All packages listed in D:\raja\SIS\SIS_Product\SIS-Global-Dev\Bombat\SISAPP\packages.config are already installed.
> 2>D:\raja\SIS\SIS_Product\SIS-Global-Dev\Bombat\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : All projects referencing SISAPP.PCL.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
> \Common\AlarmReceiver.cs(14,34,14,58): warning CS0618: 'WakefulBroadcastReceiver' is obsolete: 'This class is obsoleted in this android platform'
> \Common\CustomProgressBarAsyncTask.cs(12,16,12,30): warning CS0618: 'ProgressDialog' is obsolete: 'This class is obsoleted in this android platform'
> \Staff_Activity.cs(48,9,48,23): warning CS0618: 'ProgressDialog' is obsolete: 'This class is obsoleted in this android platform'
> \Common\Utilities.cs(105,23,105,37): warning CS0618: 'ProgressDialog' is obsolete: 'This class is obsoleted in this android platform'
> \Common\Utilities.cs(35,23,35,37): warning CS0618: 'ProgressDialog' is obsolete: 'This class is obsoleted in this android platform'
> \MainActivity.cs(42,9,42,23): warning CS0618: 'ProgressDialog' is obsolete: 'This class is obsoleted in this android platform'
> \Common\Fragments\AttendanceFilterFragment.cs(28,41,28,51): warning CS0649: Field 'StaffStudentAttendanceFilterFragment.periodName' is never assigned to, and will always have its default value null
\Common\Fragments\DairyTabFragment.cs(209,48,209,56): error CS0103: The name 'Resource' does not exist in the current context
\Common\Fragments\DairyTabFragment.cs(233,48,233,56): error CS0103: The name 'Resource' does not exist in the current context
\Common\Fragments\DairyTabFragment.cs(265,56,265,64): error CS0103: The name 'Resource' does not exist in the current context
\Common\Fragments\DairyTabFragment.cs(322,52,322,60): error CS0103: The name 'Resource' does not exist in the current context
\Common\Fragments\DairyTabFragment.cs(360,52,360,60): error CS0103: The name 'Resource' does not exist in the current context
\Common\Fragments\DashBoardFragment.cs(302,61,302,69): error CS0103: The name 'Resource' does not exist in the current context
\Common\Fragments\DashBoardFragment.cs(315,62,315,70): error CS0103: The name 'Resource' does not exist in the current context
\Common\Fragments\DashBoardFragment.cs(316,51,316,59): error CS0103: The name 'Resource' does not exist in the current context
\Common\Fragments\DashBoardFragment.cs(318,50,318,58): error CS0103: The name 'Resource' does not exist in the current context
.
.
.
.
.

> \Common\Fragments\StaffHomeworkFilterFragment.cs(21,14,21,17): warning CS0169: The field 'StaffHomeworkFilterFragment.abc' is never used
> \Common\StaffHomeworkReviewAdapter.cs(12,35,12,48): warning CS0067: The event 'StaffHomeworkReviewAdapter.OnCheckChange' is never used
> \Common\Fragments\GuardianDetailsFragment.cs(21,24,21,40): warning CS0169: The field 'GuardianDetailsFragment._isStaffGuardian' is never used
> **========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========**

### Steps to Reproduce

1. Can't give steps
2. 
3. 

### Expected Behavior
Should work
### Actual Behavior
Not working
### Version Information
Microsoft Visual Studio Enterprise 2017 
Version 15.9.6
VisualStudio.15.Release/15.9.6+28307.344
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA519
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2017   00369-60000-00001-AA519
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.11009.1
Application Insights Tools for Visual Studio

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61901.03220
Microsoft SQL Server Data Tools

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.208
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.79 (d15-9@260fa6a34)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.5.0 (HEAD/4b951a3e7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

[Log.txt](https://github.com/xamarin/xamarin-android/files/2984256/Log.txt)

**Comment by JonDouglas** [comment]
It sounds like your `Resource.designer.cs` file did not re-generate or is not included in your project. Can you please double check that it exists and includes respective IDs inside it? To further assist, please read through this wiki regarding the details we will need to help!

https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#bug-reports

**Comment by arvindrajachourasiya** [comment]
Yes. You are correct that was the issue. After including resource file now everything working. Thank you
