### ISSUE TITLE
Custom notification does not open the activity on second click

### ISSUE THREAD

**Issue by yelinzh** [xamarin/xamarin-android#2854]
### Steps to Reproduce

Custom notification does not open the activity on second click.
```
Intent intent = new Intent(this, typeof(DrawRect)).AddFlags(ActivityFlags.ClearTop | ActivityFlags.SingleTop);

PendingIntent pendingIntent = PendingIntent.GetActivity(this, 0, intent, PendingIntentFlags.OneShot);

int notificationId = 233;

var notify = new NotificationCompat.Builder(this, "Local Notification")
                    .SetSmallIcon(Resource.Mipmap.icon)
                    .SetContentIntent(pendingIntent)
                    .SetDefaults(0)
                    .SetOngoing(true)
                    .SetStyle(new NotificationCompat.DecoratedCustomViewStyle());

NotificationManagerCompat notificationCompat = NotificationManagerCompat.From(this);
Notification notification = notify.Build();
notification.Flags |= NotificationFlags.OnlyAlertOnce;
notificationCompat.Notify(notificationId, notification);
```

### Expected Behavior
Open an activity when clicking the notification.
### Actual Behavior
Notification does not open activity on second click
### Version Information
xamarin         27.0.2.1
VisualStudio  15.9.9

**Comment by brendanzagaeski** [comment]
Thanks for the report! If I understand the desired behavior correctly, then replacing `PendingIntentFlags.OneShot` with `0` might be what you're looking for. That will allow the `PendingIntent` to fire again if for example the user taps the notification to open the `DrawRect` activity, then taps the back button to return to the original activity, and then taps the notification *again*.

I'll also a sample Xamarin app and corresponding Android Studio Java app that demonstrate the same behavior for opening a new activity when `PendingIntentFlags.OneShot` is included in the call to `PendingIntent.GetActivity()`:

* [NotificationActivityXamarin.zip](https://github.com/xamarin/xamarin-android/files/2994838/NotificationActivityXamarin.zip)
* [NotificationActivityJava.zip](https://github.com/xamarin/xamarin-android/files/2994835/NotificationActivityJava.zip)

I will tentatively close this issue as answered based on this information. If I've misunderstood the problem, please do reply back to attach a test case that demonstrates the correct problem. Thanks in advance!
