### ISSUE TITLE
Annotate attribute members with resource completion hint

### ISSUE THREAD

**Issue by kzu** [xamarin/xamarin-android#2862]
As part of an exploration on how to improve the productivity of our code editing experience, we investigated improved code completion powered by Roslyn that could make it easier to use the myriad attributes where strings are intended to point to resource identifiers for various scenarios (i.e. `ActivityAttribute`)

The intended user experience would look like the following:

![CompletionFromResource](https://user-images.githubusercontent.com/169707/54777844-f9b37500-4bf1-11e9-8e52-63982b8b362f.gif)

In order to make the completion smart about what the various string values mean, I propose annotating the attribute properties with the existing `[System.ComponentModel.Category("CATEGORY")]` attribute that the IDE can then use to filter the offered values. To drive the above completion for the [Activity.Label](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs#L56) property, for example, we would annotate it with:

```
[Category("@string")]
public string Label {get; set;}
```

Any other attributes that point to any of the generated resource identifiers in `Resource.designer.cs` are potential candidates for being annotated this way too.

The associated user story on the IDE side is at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/724024

**Comment by dellis1972** [comment]
Would we be able to apply multiple Attributes for properties which can get source from multiple places ?
For example
```
[Category("@drawable")]
[Category("@mipmap")]
public string Icon {get; set;}
```

**Comment by kzu** [comment]
well, I think in that case you should just use `[Category("@drawable;@mipmap")]`.

**Comment by jonpryor** [comment]
Behold, docs! [`CategoryAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.categoryattribute?view=netframework-4.7.2)

From which we can see that [`AttributeUsageAttribute.AllowMultiple`](https://docs.microsoft.com/en-us/dotnet/api/system.attributeusageattribute.allowmultiple?view=netframework-4.7.2) is *not* set, which means it should have the default value of `false`, i.e. *no*, it cannot be specified multiple times.

We'll need to use @kzu's idea of using a `;`-separated list of types.

**Comment by kzu** [comment]
PR sent :)
