### ISSUE TITLE
KeyStorePurpose enum is not marked with Flags attribute

### ISSUE THREAD

**Issue by radioactiveman** [xamarin/xamarin-android#2864]
### Steps to Reproduce
Do a bitwise operation with the enum `Android.Security.Keystore.KeyStorePurpose`.

Sample code:
```c#
var builder = new KeyGenParameterSpec.Builder(alias, KeyStorePurpose.Encrypt | KeyStorePurpose.Decrypt);
```
### Expected Behavior
No warning by ReSharper

### Actual Behavior
ReSharper shows the following warning:
"Bitwise operation on enum which is not marked by `[Flags]` attribute"

### Version Information
Xamarin 4.12.3.80 (d15-9@914127c74)
Xamarin.Android SDK 9.1.7.0 (HEAD/ba9da7a76)
ReSharper 2018.3.4

> VS bug [#826972](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/826972)

**Comment by AdmiralSnyder** [comment]
This is a problem for Android.Views.Accessibility, too.

seems some mechanism is needed to flag enums as [Flags] in [the mapping file](https://github.com/xamarin/xamarin-android/blob/f9a7cfc0da2f51b2c3006550fad2e25fbd23be5a/build-tools/enumification-helpers/enum-conversion-mappings.xml)
