### ISSUE TITLE
Updated all Nuget References to use `PackageReference`

### ISSUE THREAD

**Issue by dellis1972** [xamarin/xamarin-android#2872]
We currently have allot of duplicated nuget references in `package.config` files. This makes is a pain to upgrade them all. We should split out the references into specific `*.props` files e.g `NUnitNugetReference.props` which will include `PackageReference` entries. Then have the relevant projects just include those. This way we can upgrade in one single place.

**Comment by jonathanpeppers** [comment]
Removal of `packages.config` happened in: https://github.com/xamarin/xamarin-android/pull/4537

We have a couple sets of files that contain `@(PackageReference)` now:

* https://github.com/xamarin/xamarin-android/blob/master/build-tools/scripts/MSBuildReferences.projitems
* https://github.com/xamarin/xamarin-android/blob/master/build-tools/scripts/NUnitReferences.projitems

There may be more common `@(PackageReference)` we can move, but I think we can close this for now?
