### ISSUE TITLE
F# records are broken when building with Link SDK and User Assemblies in Debug mode

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [xamarin/xamarin-android#2873]
### Steps to Reproduce

1.  Define an F# record type
2. Set the Linking option to SDK and User Assemblies
3. Try to create an instance of the record

If you try this sample out you can see it happening. Click the FAB. 

When set to Link SDK Assemblies Only or None, you will see the record printed in the debug console.

When set to link User Assemblies, it will throw an exception.

I have tried adding the standard Preserve attribute but it hasn't helped.
I also saw errors in my production app that suggested union case constructors were being removed.

Remember to clean / rebuild between runs.

[Test.zip](https://github.com/xamarin/xamarin-android/files/3014145/Test.zip)

### Expected Behavior

The record should be constructed normally.

### Actual Behavior

The record crashes the application when trying to access its values.

**Comment by RyanBuzzInteractive** [comment]
@dsyme  I hope you don't mind me tagging you - have you seen this happen before? I can't imagine that I am the first to come across it!

**Comment by jonathanpeppers** [comment]
@RyanBuzzInteractive it looks like the `FSharpLib.fsproj` project is missing in this zip file you attached?

Can you also post the full error message you are getting? The full [Android Device log](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows) would be even better, thanks!

**Comment by RyanBuzzInteractive** [comment]
Hi Jonathan,

Sorry! You are quite right, I had accidentally added the sub project at the same level as the sln folder, I have updated the project link in my original comment.

I just get a null ref exception in the app, I really don't think the logs will be necessary but if you do need them poke me again and I will export them for you.

It looks like the linker is removing the record constructors (and as I mentioned before, in my production app it did also complain about unions so I think it might be a wider issue across F# types)

**Comment by jonathanpeppers** [comment]
@RyanBuzzInteractive things worked when I used the full linker in `Release` mode:
```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>True</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>False</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>True</AndroidUseSharedRuntime>
    <AndroidLinkMode>None</AndroidLinkMode>
    <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>True</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
  </PropertyGroup>
```
Does this `Release` configuration work for you?

Do you need the linker in `Debug` mode here? It is going to add time to your development loop, I wouldn't use it when debugging.

**Comment by RyanBuzzInteractive** [comment]
Ah, well there you go - I didn't realise that using the linker in debug mode would work any differently to release mode, I can confirm I have no problems with that, I hadn't tried it.

Obviously I wouldn't routinely link my debug builds, as you say that would take forever. The thing is if you deploy a release build and there was a problem with the linking which causes a crash then you have no debug log to look at.

I had tended in the past to run a linked build in debug mode to quickly catch any obvious errors, and then do a release build once I got it working. Do you have any tips on how I might connect the debugger to a linked build, or why it was breaking in Debug mode?

Thanks for taking the time to look at it for me.

**Comment by jonathanpeppers** [comment]
There might be a bug when enabling the linker in Debug mode?

Probably worth looking into at some point, I just don't see how the line number are going to match up, etc. Breakpoints likely won't work quite right, so is it a useful scenario?

**Comment by RyanBuzzInteractive** [comment]
Yeah, I mean if you don't set up your 'linker please include' file to reference things like CheckedChanged or Clicked on UI elements then as soon as you use that thing you get an exception. You don't want to be finding that out in production hey.

**Comment by RyanBuzzInteractive** [comment]
Obviously you can test the release build but when it crashes you are left a little in the dark.

**Comment by jonathanpeppers** [comment]
@RyanBuzzInteractive closing for now, as it looks like you solved your issue here, thanks!
