### ISSUE TITLE
NumberPicker shows 0 when empty string is added as an option to SetDisplayValues

### ISSUE THREAD

**Issue by KarthikRajaAKR** [xamarin/xamarin-android#2874]
I have used NnumberPicker to show picker window. I added display values with a string list, which consists of one empty string and two string values. I wanted that the empty string value should shown as empty option but it showing as 0. 

### Steps to Reproduce

1. Run the attached Sample_Android sample 
2. Click the button
3. Note that 0 is in picker list

![image](https://user-images.githubusercontent.com/41435300/54975639-bd9b5e00-4fbd-11e9-8e35-6adf09f0f160.png)

[Sample_Android.zip](https://github.com/xamarin/xamarin-android/files/3006763/Sample_Android.zip)

### Expected Behavior
Empty value should be shown in picker for empty string 
### Actual Behavior
0 is showing inside picker view for empty string

### Version Information
Xamarin.Android.Support.Design : 27.0.2.1

**Comment by jonathanpeppers** [comment]
@KarthikRajaAKR I don't think this is a problem with Xamarin.Android? We just expose the Android APIs directly to C#. So I think you're just seeing behavior Android has. 

Or is this a problem with the support libraries? Issues for those can be posted [here](https://github.com/xamarin/AndroidSupportComponents/issues).

Suggestion though, can you just use a whitespace? `" "` as the text?

Closing for now, let me know if you think there is a Xamarin.Android bug here, thanks!
