### ISSUE TITLE
PanGestureRecognizer Completed Event does not fire

### ISSUE THREAD

**Issue by painavin** [xamarin/xamarin-android#2884]
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:PanGestureBug"
             x:Class="PanGestureBug.MainPage">

    <StackLayout>
        <ListView x:Name="myList" RowHeight="100">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <Label
                            Text="{Binding}">
                            <Label.GestureRecognizers>
                                <PanGestureRecognizer PanUpdated="PanGestureRecognizer_PanUpdated"/>
                            </Label.GestureRecognizers>
                        </Label>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </StackLayout>

</ContentPage>

**Code Behind**

using System.Collections.Generic;
using System.ComponentModel;
using Xamarin.Forms;

namespace PanGestureBug
{
    [DesignTimeVisible(true)]
    public partial class MainPage : ContentPage
    {
        List<string> items = new List<string>();
        public MainPage()
        {
            InitializeComponent();
            for (int i = 0; i < 3; i++)
            {
                items.Add("item " + i.ToString());
            }
            myList.ItemsSource = items;
        }
        private void PanGestureRecognizer_PanUpdated(object sender, PanUpdatedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine(e.StatusType);
        }
    }
}

### Expected Behavior
When you pan on the items, the PanUpdated should get called with completed/cancelled. 

### Actual Behavior
The completed/cancelled is not called consistently.

### Version Information
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 4.4
VisualStudio.16.Preview/16.0.0-pre.4.4+28721.148
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA984
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.0.20307.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.0.12307.51536
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.0.12307.51536
Azure App Service Tools v3.0.0

C# Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.0.300 (573eda3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10306.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 809f41207b74a1356208f11b8fa3a15233734050.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.0.0.513 (d16-0@aebc6bdb5)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.17.4.413 (remotes/origin/d16-0@db42fb8b0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.1.43 (fe3ade5)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

**Comment by painavin** [comment]
I think the bug is in GestureManager.cs

public class TapAndPanGestureDetector : GestureDetector
{
	public override bool OnTouchEvent(MotionEvent ev)
	{
		if (base.OnTouchEvent(ev))
			return true;

		if (ev.Action == MotionEventActions.Up)
			_listener.EndScrolling();

		return false;
	}
...
}
The above function should say

public override bool OnTouchEvent(MotionEvent ev)
{
         if (base.OnTouchEvent(ev))
			return true;

		if (ev.Action == MotionEventActions.Up || **ev.Action == MotionEventAction.Cancel** )
			_listener.EndScrolling();

		return false;
	}

**Comment by dellis1972** [comment]
This looks like a Xamarin.Forms issue rather than a Xamarin.Android specific issue. I'll see if I can move it to the appropriate repo.

**Comment by samhouts** [comment]
Thanks! I'll reopen https://github.com/xamarin/Xamarin.Forms/issues/1495. You can go ahead and close this issue.

**Comment by dellis1972** [comment]
This issue will be tracked on xamarin/Xamarin.Forms#1495. Thanks for the bug report.
