### ISSUE TITLE
Analyze non-XF apps with startup aot profile

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#2885]
Find out, if and how many additional methods are compiled with current startup profile in XA template app.

Context: https://github.com/xamarin/xamarin-android/pull/2877

See how many methods are added from both profiles.

**Comment by radekdoulik** [comment]
I have looked at XA template app. Compared 2 scenarios, with the default startup aot profile and with recorded startup profile.

Sizes of apk with aot profiles:

Without AOT profile
```
-rw-r--r--  1 rodo  staff   6.8M Apr  4 12:40 com.xamarin.xatemplateaot-Signed.apk
```
Recorded profile
```
-rw-r--r--  1 rodo  staff   7.9M Apr  4 12:38 com.xamarin.xatemplateaot-Signed.apk
```
Default profile
```
-rw-r--r--  1 rodo  staff   8.2M Apr  4 12:24 com.xamarin.xatemplateaot-Signed.apk
```
So with recorded profile we can get about 300k smaller apk.

Methods count:

Recorded profile
```
  [aot-compiler stdout] Added 147 methods from profile.
  [aot-compiler stdout] Added 154 methods from profile.
  [aot-compiler stdout] Added 455 methods from profile.
  [aot-compiler stdout] Added 2 methods from profile.
  [aot-compiler stdout] Added 5 methods from profile.
  Total: 763 methods
```

Default profile
```
  [aot-compiler stdout] Added 1015 methods from profile.
  [aot-compiler stdout] Added 251 methods from profile.
  [aot-compiler stdout] Added 7 methods from profile.
  [aot-compiler stdout] Added 3 methods from profile.
  [aot-compiler stdout] Added 261 methods from profile.
  Total: 1537
```

So with default profile, which was recorded with our XF test, there is still a lot of methods AOT'ed, which are not used during the startup. It is to consider, whether to use different default startup AOT profile for non-XF apps or wait and let that for the user to record own profiles, when it is available in IDEs.

I think it would be quite easy to switch non-XF and XF startup profiles, so I think it is worth to implement.

Profile information:

Recorded profile
```
mono --debug bin/Debug/aotprofile-tool.exe -s -d ~/git/xa/profile.aot
Modules:
	769F6DA9-D358-41F6-AAE0-15185488EDE0 mscorlib
	DB6641F2-ED44-48BA-BE32-AB097AF0DF88 Mono.Android
	5F0D8413-F33D-426F-B8D4-D918BB296011 System
	CBAC57F8-48B6-461E-B09A-3476B026C874 Java.Interop
	C8ACDD43-D1E3-4AA6-B954-E18E8C39972F System.Core
	EAB815AF-3864-4431-9EAD-D926BD93AE68 xatemplateaot
Summary:
	Modules:          6
	Types:          210
	Methods:        873
```

Default profile
```
mono --debug bin/Debug/aotprofile-tool.exe -s -d ~/git/xa/src/Xamarin.Android.Build.Tasks/startup.aotprofile
Modules:
	41C38B0A-2032-45CE-8638-0299CED65330 mscorlib
	0326DF03-2158-4F7A-9A2B-B7A9419F021D Mono.Android
	8FB63BB4-1195-4173-A9ED-0EC341B07C32 System
	74C06E06-C1C7-4A4C-B64E-EAC7DBB08BBC Java.Interop
	11E2319F-6A26-461C-9C46-C972248BEE4B System.Core
	7999CC4B-D566-4ECA-8A72-469344172CA3 Xamarin.Forms.Platform.Android
	C5089213-328B-451D-BA87-D6585C120780 Xamarin.Forms.Performance.Integration.Droid
	D754F8AE-503C-41C8-B16F-647FC662507A Xamarin.Android.Support.v7.AppCompat
	929ECB6D-1171-4C66-8470-DD32AC608969 Xamarin.Android.Support.Fragment
	F841E23B-59A8-4AE2-9A84-D2FC1D891B4A Xamarin.Forms.Core
	945CCBF8-C2DB-468B-B3BD-D7ACA37B69AD Xamarin.Forms.Performance.Integration
	AF20FA19-F07E-4BD4-B5ED-104706EA660E Xamarin.Forms.Xaml
	629C84F8-0988-42EF-8BC5-872173A0A71F FormsViewGroup
	60398815-8E62-487E-A553-781F56A0849D Xamarin.Android.Support.Design
	F0C550D7-665A-40B5-A307-8E9B49976D87 Xamarin.Android.Support.Core.UI
	23A34485-DE75-440E-BA9D-E235F664E990 Xamarin.Android.Support.Compat
Summary:
	Modules:         16
	Types:          907
	Methods:      4,230
```

**Comment by jonpryor** [comment]
Re-reading the [`aotprofile-tool` output](https://github.com/xamarin/xamarin-android/issues/2885#issuecomment-479848420) shows *a* reason we may want *some* form of `.aotprofile` editing:

Both `startup.aotprofile` and `startup-xf.aotprofile` include assemblies that (arguably) shouldn't be included: `startup.aotprofile` mentions the `xatemplateaot` module, which is the module for that particular app; other end-user apps won't have that module.

Likewise, `startup-xf.aotprofile` has a module for `Xamarin.Forms.Performance.Integration`, which is the main assembly for our unit test; other end-user apps won't have that module, either.

In theory that shouldn't matter, in that if the AOT compilers  never encounter those modules, nothing will be emitted.

However, it is a source of "noise": when we ship `aotprofile-tool`, people will view the output, and they'll see these "inexplicable" modules.  Removing them will prevent this potential confusion.

**Comment by radekdoulik** [comment]
Yup, I noticed that too. For now I consider it low priority as the impact is really small and the methods would not be AOTed, until someone used the same types and methods API.

I have opened a new issue for it https://github.com/xamarin/xamarin-android/issues/2971. It contains information on how many types/methods are involved

**Comment by radekdoulik** [comment]
It is great we now have a reason for write support :-)

I started collecting these here https://github.com/xamarin/xamarin-android/issues/2972
