### ISSUE TITLE
AndroidX Skip Items Support

### ISSUE THREAD

**Issue by dellis1972** [xamarin/xamarin-android#2895]
For AndroidX support we need to be able to skip over processing of some of the older support libraries if they are referenced. For example we should NOT extract any resources, or generate any java code for those libraries. 

So this to work we need to be able to define which assemblies to skip processing on. Commits 02c07ed6 and 5f27d0ca put in the framework to allow us to skip items based on metadata.
We already have `SkipAndroidResourceProcessing` in place and need to add the following extra items.

- SkipJavaStubsGeneration
- SkipResourceExtraction
- SkipPackaging

These new items will allow us to skip over processing of certain assemblies when they are not needed.

**Comment by mattleibow** [comment]
@dellis1972 right now, there are no new assemblies, so the same assemblies that we skip for resource processing, we need to skip for the extraction.

However, this should not be on by default for the extraction. People can still make apps that _just_ use Support, so we can't skip it. We only want to skip these assemblies if the user has opted into using AndroidX.

**Comment by dellis1972** [comment]
implemented and merged (and cp'd tp d16-2 21561c3b11a0b7763e8bf2ed9f718e6a8f2446ce)
