### ISSUE TITLE
NetworkCredential ignored using AndroidClientHandler resulting in 401 (Unauthorized) 

### ISSUE THREAD

**Issue by jNery** [xamarin/xamarin-android#2902]
NetworkCredential ignored using AndroidClientHandler resulting in 401 (Unauthorized) 

### Steps to Reproduce

1. Set NetworkCredential to valid username/password
Notice that `HttpClientHandler` works just fine but 401 (Unauthorized) using `AndroidClientHandler`
```CSharp
EventHandler clickedHandler = async (a, b) =>
{
    var dialog = new Android.App.AlertDialog.Builder(this);
    try
    {
        if (a == button)
        {
            var client = new System.Net.Http.HttpClient(new HttpClientHandler() { Credentials = new System.Net.NetworkCredential("guest", "guest") });
            var response = await client.GetAsync(new Uri("https://jigsaw.w3.org/HTTP/Basic/"));
            dialog.SetTitle(response.StatusCode.ToString());
            dialog.SetMessage(await response.Content.ReadAsStringAsync());
        }
        else if (a == button1)
        {
            var client = new System.Net.Http.HttpClient(new AndroidClientHandler() { Credentials = new System.Net.NetworkCredential("guest", "guest") });
            var response = await client.GetAsync(new Uri("https://jigsaw.w3.org/HTTP/Basic/"));
            dialog.SetTitle(response.StatusCode.ToString());
            dialog.SetMessage(await response.Content.ReadAsStringAsync());
        }
    }
    catch (Exception error)
    {
        Exception ex = error;
        if (ex is AggregateException)
        {
            ex = ((AggregateException)ex).GetBaseException();
        }
        dialog.SetTitle(ex.GetType().Name);
        dialog.SetMessage(ex.Message);
    }
    RunOnUiThread(() => dialog.Show());
};
button.Click += clickedHandler;
button1.Click += clickedHandler;
```

### Expected Behavior
Server should respond with `HttpStatusCode.OK` 
### Actual Behavior
Server should respond with `HttpStatusCode.Unauthorized` 
### Version Information

Microsoft Visual Studio Enterprise 2017 
Version 15.9.9
VisualStudio.15.Release/15.9.9+28307.518
Microsoft .NET Framework
Version 4.7.03190

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.80 (d15-9@914127c74)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.15 (d60abd1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by grendello** [comment]
@jNery Hi, thanks for reporting! Yes, the code you included won't work and there's, unfortunately, a reason behind it that we cannot fix. It's described in [detail here](https://github.com/xamarin/xamarin-android/blob/0fb11af000390d045be1493a5bd2eafbcb6b5e3f/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L41-L49) and the gist is that the underlying native Android HTTP client `AndroidClientHandler` uses does not support per-request credential store - it uses one, global credential handler (unlike .NET) which makes this kind of code in your post not to work as expected. However, if you implement something similar to the code below, it works as expected (error checks, better loop termination condition checks etc are omitted for brevity - the code works for your sample request):

```csharp
var client = new System.Net.Http.HttpClient (clientHandler);
HttpResponseMessage response;
do {
   response = await client.GetAsync(new Uri("https://jigsaw.w3.org/HTTP/Basic/"));
   if (!clientHandler.RequestNeedsAuthorization || response.StatusCode == HttpStatusCode.OK)
      break;
   clientHandler.PreAuthenticationData = clientHandler.RequestedAuthentication [0];
} while (true);
System.Console.WriteLine ($"Status code: {response.StatusCode}");
System.Console.WriteLine ($"Response: {await response.Content.ReadAsStringAsync()}");
```
