### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION: com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded

### ISSUE THREAD

**Issue by hadigityat** [xamarin/xamarin-android#2919]
### Steps to Reproduce

1. Change target framework level to 28 (Android 9.0)
2. Build (Multidex enabled)
3. 

### Expected Behavior

build runs without errors

### Actual Behavior

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error MSB6006: "java" exited with code 2. (MSB6006)

### Version Information

Visual Studio Community 2019 for Mac
Version 8.0 (build 3001)
Installation UUID: e54e9990-6782-4238-a6cd-797dff2cf7f1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

Mono Framework MDK
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

NuGet
Version: 4.8.2.5835

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

Xamarin.iOS
Version: 12.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

Xamarin.Android
Version: 9.2.0.5 (Visual Studio Community)
Android SDK: /Users/Can/Downloads/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 29.0.0 rc1

Build Information: 
Mono: mono/mono/2018-08-rc@5ad371dab1b
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

Microsoft Mobile OpenJDK
Java SDK: /Users/Can/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-03-27 18:41:02 UTC

Xamarin Designer
Version: 4.17.4.414
Hash: 55b8d07ef
Branch: remotes/origin/d16-0
Build date: 2019-03-22 21:44:12 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 800003001
Git revision: 16b11d379aeff65cd1e81d3616c267ad4251ad36
Build date: 2019-03-28 13:14:24+00
Build branch: master
Xamarin extensions: efad41c7f410d8e6d43361236e0e778cf6f9b4a5

Operating System
Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

### Log File

    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:548)
    	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
    	at com.android.dx.command.dexer.Main.runDx(Main.java:289)
    	at com.android.dx.command.dexer.Main.main(Main.java:247)
    	at com.android.dx.command.Main.main(Main.java:94)

**Comment by hadigityat** [comment]
Fixed by workaround--> add the following lines to csproj property group

<DxExtraArguments>--dex --no-strict --force-jumbo</DxExtraArguments>
<AndroidMultiDexClassListExtraArgs>--disable-annotation-resolution workaround</AndroidMultiDexClassListExtraArgs>

**Comment by jonathanpeppers** [comment]
Hi @hadigityat can you post a [diagnostic build log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

We need to see why your app needs these settings, thanks!

**Comment by hadigityat** [comment]
The reason why it needs the workaround is explained here(I am using a large dll bindings file):

https://github.com/xamarin/xamarin-android/issues/1888

Seems like there was a fix added, but not sure if it helped in my case. Let me know if you still need build logs.

**Comment by jonathanpeppers** [comment]
@hadigityat if you use VS 2019, you can try the `<AndroidDexTool>d8</AndroidDexTool>` option. Although there are more fixes for d8 that aren't in 2019 yet... you may hit a different issue.

I think what you are doing is the best route, and we should see how d8 can handle the problem moving forward. Google is already using d8 by default in Android Studio.

**Comment by hadigityat** [comment]
I tried d8 but it failed, went back to original workaround and now that doesn't work anymore also:

    Invalid option --disable-annotation-resolution
    Usage:
    
    Short version: Don't use this.
    
    Slightly longer version: This tool is used by mainDexClasses script to build
    the main dex list.
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2699,3): error MSB6006: "java" exited with code 1.

**Comment by jonathanpeppers** [comment]
I think we may actually need a sample project to look into this. Is there a NuGet package of the binding you are using? Or would you be able to upload a sample?

**Comment by hadigityat** [comment]
I fixed the d8 error of missing libraries and it works now. I think using d8 is the long term solution for this anyways. 

I can't expose the binding project because it is not an open source code.

 Thanks for your prompt response. Closing this as it is fixed with d8.

**Comment by merckxite** [comment]
Just for posterity @hadigityat, your original solution does work with an extra hyphen in the arg:

```
<DxExtraArguments>--dex --no-strict --force-jumbo</DxExtraArguments>
<AndroidMultiDexClassListExtraArgs>--disable-annotation-resolution-workaround</AndroidMultiDexClassListExtraArgs>
```

I agree that D8 is the way to go in future but for now you saved me a big headache, thanks!

**Comment by matt2003** [comment]
Hi All that saved me too for adding AndHUD to my project tried everything so far including r8 (didnt work) on VS mac 2017 and this allows me to compile both debug and release versions.

Thank you!

**Comment by jonathanpeppers** [comment]
@matt2003 is this the project you're referring to? https://github.com/CNCoderX/AndHub

I could just try enabling d8 + r8, and see what you're seeing?

**Comment by matt2003** [comment]
Hi Jonathan,
I did manage to get it working with that workaround above it was actually AndHUD 
https://github.com/Redth/AndHUD

**Comment by matt2003** [comment]
D8 / R8 is not working I think with VS2017 for mac I get this as output
I am not sure why it is looking to proguard in debug mode, but at least it compiles I will try to install 2019 side by side and see if I can take advantage of the r8/ d8 and see if it compiles there.

Target "_CompileToDalvikWithD8" in file "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.D8.targets":
  Building target "_CompileToDalvikWithD8" completely.
  Output file "obj/Debug/stamp/_CompileToDalvik.stamp" does not exist.
  Task "Error" skipped, due to false condition; ( !Exists('$(AndroidR8JarPath)') ) was evaluated as ( !Exists('/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/r8.jar') ).
  Task "Delete"
  Done executing task "Delete".
  Task "MakeDir"
    Creating directory "obj/Debug/proguard".
  Done executing task "MakeDir".
  Task "Proguard" skipped, due to false condition; ( '$(AndroidLinkTool)' == 'proguard' And '$(_ProguardProjectConfiguration)' != '' ) was evaluated as ( 'r8' == 'proguard' And '' != '' ).
  Task "CreateItem" skipped, due to false condition; ( '$(AndroidLinkTool)' == 'proguard' And '$(_ProguardProjectConfiguration)' != '' ) was evaluated as ( 'r8' == 'proguard' And '' != '' ).
  Using "R8" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Build.Tasks.dll".
  Task "R8"
      processing ClassesZip, JavaLibrariesToEmbed...
    /Users/matt/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/java -Xmx1G -classpath /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/r8.jar com.android.tools.r8.SwissArmyKnife --debug --min-api 24 --output obj/Debug/android/bin --lib /Users/matt/Library/Developer/Xamarin/android-sdk-macosx/platforms/android-28/android.jar obj/Debug/android/bin/classes.zip /Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v9.0/mono.android.jar /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/android-support-multidex.jar obj/Debug/lp/1/jl/bin/classes.jar obj/Debug/lp/12/jl/android.arch.core.common.jar obj/Debug/lp/13/jl/bin/classes.jar obj/Debug/lp/14/jl/android.arch.lifecycle.common.jar obj/Debug/lp/15/jl/bin/classes.jar obj/Debug/lp/16/jl/bin/classes.jar obj/Debug/lp/17/jl/bin/classes.jar obj/Debug/lp/18/jl/bin/classes.jar obj/Debug/lp/19/jl/bin/classes.jar obj/Debug/lp/20/jl/bin/classes.jar obj/Debug/lp/21/jl/bin/classes.jar obj/Debug/lp/22/jl/com.android.support.collections.jar obj/Debug/lp/23/jl/bin/classes.jar obj/Debug/lp/24/jl/bin/classes.jar obj/Debug/lp/25/jl/bin/classes.jar obj/Debug/lp/26/jl/bin/classes.jar obj/Debug/lp/27/jl/bin/classes.jar obj/Debug/lp/28/jl/bin/classes.jar obj/Debug/lp/29/jl/bin/classes.jar obj/Debug/lp/30/jl/bin/classes.jar obj/Debug/lp/31/jl/bin/classes.jar obj/Debug/lp/32/jl/bin/classes.jar obj/Debug/lp/33/jl/bin/classes.jar obj/Debug/lp/34/jl/bin/classes.jar obj/Debug/lp/35/jl/bin/classes.jar obj/Debug/lp/36/jl/bin/classes.jar obj/Debug/lp/37/jl/bin/classes.jar obj/Debug/lp/38/jl/bin/classes.jar obj/Debug/lp/39/jl/bin/classes.jar obj/Debug/lp/40/jl/bin/classes.jar obj/Debug/lp/41/jl/bin/classes.jar obj/Debug/lp/42/jl/bin/classes.jar obj/Debug/lp/43/jl/bin/classes.jar obj/Debug/lp/44/jl/bin/classes.jar obj/Debug/lp/45/jl/bin/classes.jar obj/Debug/lp/46/jl/bin/classes.jar obj/Debug/lp/47/jl/bin/classes.jar obj/Debug/lp/48/jl/bin/classes.jar obj/Debug/lp/49/jl/bin/classes.jar obj/Debug/lp/50/jl/bin/classes.jar obj/Debug/lp/51/jl/bin/classes.jar obj/Debug/lp/52/jl/bin/classes.jar obj/Debug/lp/53/jl/bin/classes.jar obj/Debug/lp/54/jl/bin/classes.jar obj/Debug/lp/55/jl/bin/classes.jar obj/Debug/lp/56/jl/bin/classes.jar obj/Debug/lp/57/jl/classes.jar obj/Debug/lp/58/jl/classes.jar obj/Debug/lp/59/jl/classes.jar obj/Debug/lp/60/jl/classes.jar obj/Debug/lp/61/jl/classes.jar --main-dex-list /var/folders/y0/hg2t5cn90g567hs3k0lnzw_h0000gn/T/tmp355d6dc4.tmp --main-dex-rules /Users/matt/Library/Developer/Xamarin/android-sdk-macosx/build-tools/27.0.3/mainDexClasses.rules --main-dex-list-output obj/Debug/multidex.keep --pg-conf /Users/matt/Library/Developer/Xamarin/android-sdk-macosx//tools/proguard/proguard-android.txt --pg-conf obj/Debug/proguard/proguard_xamarin.cfg --pg-conf obj/Debug/proguard/proguard_project_primary.cfg --pg-conf proguard.cfg --pg-conf obj/Debug/XbdMerge/proguard/dc663e480.txt 
    Error in proguard.cfg:
      Expected char '-' at proguard.cfg:1:1
    ?-libraryjars /Users/matt/Library/Developer/Xamarin/android-sdk-macosx/platforms/android-28/optional/
    ^
    Compilation failed
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.D8.targets(81,5): error MSB6006: "java" exited with code 1.

**Comment by matt2003** [comment]
I did manage to compile now with vs 2019 for mac using in both debug and release mode     
with and without proguard and without multidex  only multipledex 
<AndroidEnableDesugar>true</AndroidEnableDesugar>
    <AndroidDexTool>d8</AndroidDexTool>

Though r8 cant be found on the path it believes it to be.
Its actual location is
/Library/Frameworks/Xamarin.Android.framework/Versions/9.2.0-5/lib/xamarin.android/xbuild/Xamarin/Android/r8.jar
It believes it to be here
!Exists('/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/r8.jar'

It is compiling which is great I also had to fix the BOM issue in the proguard.cfg

Thanks,
Matt
