### ISSUE TITLE
Using VS's linked files on resources causes IDE errors but build succeeds

### ISSUE THREAD

**Issue by alaatm** [xamarin/xamarin-android#2938]
I have a couple of Apps that are almost identical with very minimal differences. Each app has its own package name.

Basically, what I do is have most files (source files, resources, etc...) in one app and use linked files (VS Add Existing -> Add As Link) to add them to the second app and use partial classes, compilation symbols, etc.. for the differences. Both projects are set to use the same namespace so that the generated `Resource` class can be referenced by both.

Basically, everything is working fine except for one annoying thing, the errors tab is filled with `'Resource.AAA' does not contain a definition for 'BBB'`. These errors are shown for the app that uses the linked files. Note that these errors are **NOT** actual errors because both projects build and run with no issues.

As my project gets larger, the error list is also getting larger (currently at 69 errors) which makes it a bit more time consuming to find "**real**" errors.

I have linked a repo for a very simple repro. In it, I am linking MainActivity.cs and the layout resource files in App2.

The result is this:

![image](https://user-images.githubusercontent.com/2095803/55676816-3ca96400-58e5-11e9-9bf5-a7af9bfd0f10.png)

![image](https://user-images.githubusercontent.com/2095803/55676914-a37b4d00-58e6-11e9-8122-2935b12dfda5.png)

Is there anything I could do to make these go away?!

### Steps to Reproduce
Please see https://github.com/alaatm/LinkedFiles
After building succeeds, try opening `MainActivity.cs` under App2.

### Expected Behavior
No errors shown.

### Actual Behavior
Errors shown.

### Version Information
VS2019 GA

**Comment by radekdoulik** [comment]
@joj, could you please take a look at it or reassign to someone in VS team?

**Comment by joj** [comment]
I need to confirm, but I think this is already fixed on an upcoming release. I'll update in a little while.

**Comment by joj** [comment]
It isn't. You can get rid of those errors by switching the dropdown from Build+Intellisense to Build Only, but there will still be squiggles for the intellisense errors in the linked file. I'll look into it.

**Comment by jpobst** [comment]
If this is still an issue:

This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
