### ISSUE TITLE
ResolveSdks should also look for ANDROID_SDK_ROOT

### ISSUE THREAD

**Issue by savornicesei** [xamarin/xamarin-android#2979]
### Steps to Reproduce
Consider a build server configuration on a Windows 10 machine:
1. Have only Visual Studio 2017 Build Tools installed, including Mobile build tools
2. Install AndroidSDK from zip file 
3. Set ANDROID_SDK_ROOT as described [here](https://developer.android.com/studio/command-line/variables#android_sdk_root)
4. Build an android xamarin project using MsBuild

### Expected Behavior
The project should be succesfully build

### Actual Behavior
Build fails with C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(703,2): error XA5300: The Android SDK Directory could not be found. Please set via /p:AndroidSdkDirectory. 

The workaround is to set the Android SDK Tools registry key
```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Android SDK Tools]
"Path"="C:\\Program Files (x86)\\Android\\android-sdk"
"StartMenuGroup"="Android SDK Tools"
```

By looking into the AndroidSdkWindows class I saw that it only checks the registry for specific keys and then checks for some hardcoded paths. Why not checking the ANDROID_SDK_ROOT?

Thanks,
Simo

**Comment by jonathanpeppers** [comment]
@savornicesei can you just use `AndroidSdkDirectory`? Xamarin.Android fully embraces MSBuild so you can use this two ways:

    msbuild foo.android.csproj /p:AndroidSdkDirectory=C:\android-sdk

Or via an `AndroidSdkDirectory` environment variable set to your desired value. All MSBuild properties can be set via environment variables.

**Comment by savornicesei** [comment]
Hi @jonathanpeppers 
I've passed it along but it didn't seemed to be picked up. I will have to prepare some test to look at it more closely.
Still I expected .NET env. (MSBuild) to pick up the ANDROID_SDK_ROOT, as it checks the Android SDK Tools registry key that seems to be set by the Android SDK installer. 
I actually expected ANDROID_SDK_ROOT to take precedence over any other reg key.

Best,
Simo

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) of your build? Or if it is just as easy for you, an [MSBuild binary log](https://github.com/Microsoft/msbuild/wiki/Binary-Log) would be even better.

> Still I expected .NET env. (MSBuild) to pick up the ANDROID_SDK_ROOT, as it checks the Android SDK Tools registry key that seems to be set by the Android SDK installer.
I actually expected ANDROID_SDK_ROOT to take precedence over any other reg key.

I think this part is a feature request you should submit on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com), so other people in the community can vote on it. Pull requests are also welcome! 😄

**Comment by jonathanpeppers** [comment]
Closing for now, let us know if you have a log and we can see why `/p:AndroidSdkDirectory isn't working for you. Thanks!
