### ISSUE TITLE
Control on "one APK per abi" version codes

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-android#2995]
I deployed a unified APK to google play store using appcenter, which put as version code the unix timestamp. It's: 1555015740

Now i want to build one APK per abi. But the format  of the generated version codes is Txxxxxx where T is between 1 and 4 and xxxxxx is the version code from the android manifest. Ex:
400005
200005

So google play refuses to replace the abi 1555015740 with this one, which makes sense.
Xamarin tooling prevents the use of a number with more than 6 digits for multiple APKs.

So i'm not able to switch to multiple APKs anymore in google play store.
Is there a way to control this pattern Txxxxxx so it can fix my scenario ?

**Comment by dellis1972** [comment]
@softlion The version Code you are getting is the default one we calculate when using split apks. However you can control what version code is used. There is a detailed blog post on the subject
 https://devblogs.microsoft.com/xamarin/advanced-android-versioncode/

You need to override the default `$(AndroidVersionCodePattern)` property in your csproj and make sure you get a number that is higher than `1555015740`.  Have a read of the blog post it should help you solve your issue. 

I'll close this issue for now, but feel free to open it again if you have trouble.

**Comment by dellis1972** [comment]
We also have documentation of the `$(AndroidVersionCodePattern)`  in https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/BuildProcess.md

**Comment by softlion** [comment]
Will try as soon as armv7 is working again
