### ISSUE TITLE
Xamarin Android -New Cerated tabbed App run crash after adding control to axml

### ISSUE THREAD

**Issue by john-heaven** [xamarin/xamarin-android#2996]
### Description

I used **VS2017** to create a new `XamarinAndroid ` application. I chose the **TabbedApp** option during the new build. After the project is created, I added a control to the `activity_main.axml`, such as `ImageView`,and then crashed when I run the program.
>Unhandled Exception:Android.Views.InflateException

### Steps to Reproduce

1. New Create a Xamarin Android Tabbed App.
**New Project -> Visual C# -> Android -> Android App(Xamarin) -> Tabbed App(Android version 5.0).**
2. Add a control(`ImageView`) to `activity_main.axml`
![image](https://user-images.githubusercontent.com/7145819/56274397-37dc7f80-6131-11e9-9d7a-f66df832ddd7.png)

3. Click Run button in VS to run this app.

### Expected Behavior
Crash happens in VS.
![image](https://user-images.githubusercontent.com/7145819/56274448-4fb40380-6131-11e9-9d94-eec61df18710.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:MIcrosoft Visual Studio Community 2017 Version 15.9.11
- Platform Target Frameworks: 
  - Android: 
minSdkVersion:21
targetSdkVersion: 27
- Affected Devices: simulator:8.1 (Oreo) - API 27

### Reproduction Link
https://www.dropbox.com/s/9wfhgpmf489or21/App6.rar?dl=0

### Solution Now:
After edit axml file,need to clean project, then build it again can work.
https://stackoverflow.com/questions/55692576/why-i-cant-add-an-imageview-in-the-tabbed-page/55705339#55705339

**Comment by GintasS** [comment]
https://stackoverflow.com/questions/55692576/why-i-cant-add-an-imageview-in-the-tabbed-page/55705339?noredirect=1#comment98117294_55705339

**Comment by jonathanpeppers** [comment]
@john-heaven does a `Rebuild` fix the problem?

It could be related to: https://github.com/xamarin/xamarin-android/pull/2199

This fix is only in VS 2019.

**Comment by john-heaven** [comment]
@jonathanpeppers  Hi, I find it be solved in VS2019. VS2019 is cool IDE. 👍

**Comment by jonathanpeppers** [comment]
@john-heaven thanks!

If anyone else has an issue similar to this with 2019, open a new issue, thanks!
