### ISSUE TITLE
Runtime calls endSession() without first calling beginSession()

### ISSUE THREAD

**Issue by codecore** [xamarin/xamarin-android#3005]
### Steps to Reproduce
1.  Run Xamarin.UITest in AppCenter. Not restricted to a specific device, or OS version. Observed on Google Pixel 2, Moto G6, Huawei Nexus 6P, and others.
java.lang.IllegalStateException: Attempted to endSession() without preceding matching call to beginSession().

[AndroidAppCenterStackTrace.txt](https://github.com/xamarin/xamarin-android/files/3096364/AndroidAppCenterStackTrace.txt)

### Expected Behavior
   Test run flawlessly
### Actual Behavior
  App is unloaded, screenshot is the android 'desktop'. Logfile contains a stacktrace.
### Version Information
Huewei Nexus 6P Android 8.1.0
### Log File
https://github.com/xamarin/xamarin-android/files/3096364/AndroidAppCenterStackTrace.txt

**Comment by jonathanpeppers** [comment]
Can you post a full [adb log](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log) (when run locally)? Or the full log App Center gives you?

I suspect the the problem could be with Xamarin.UITest here, and this isn't anything to do with Xamarin.Android. We can check, though!

**Comment by codecore** [comment]
[Device_Logs.txt](https://github.com/xamarin/xamarin-android/files/3122673/Device_Logs.txt)
[Test_Logs.txt](https://github.com/xamarin/xamarin-android/files/3122674/Test_Logs.txt)

**Comment by jonathanpeppers** [comment]
This looks like something UITest is doing to me:
```
I/System.out(10904): command: {"command":"hide_soft_keyboard"}
I/InstrumentationBackend(10904): Got command:'Command:'Line:null,hide_soft_keyboard', arguments:'null'
I/PhenotypeExpConfig( 1015): refreshConfiguration() : Force = false : UpdateAvailable = false : Age = 9 minutes : MaxAge = 720 minutes
I/System.out(10904): result:{"bonusInformation":[],"message":"","success":true}
I/AndroidIME( 1015): LatinIme.onDeactivate()
I/System.out(10904): URI: /map
I/System.out(10904): params: {json={"query":"* marked:'editFirstName' TextInputEditText","operation":{"method_name":"query","arguments":[]}}
I/System.out(10904): }
E/Tiresias( 1015): endSession: Error executing future.
E/Tiresias( 1015): java.lang.IllegalStateException: Attempted to endSession() without preceding matching call to beginSession().
E/Tiresias( 1015): 	at ghg.i(PG:223)
E/Tiresias( 1015): 	at ghg.c(PG:220)
E/Tiresias( 1015): 	at com.google.android.apps.inputmethod.libs.latin5.LatinIme.c(PG:858)
E/Tiresias( 1015): 	at cyl.F(PG:109)
E/Tiresias( 1015): 	at cyl.A(PG:101)
E/Tiresias( 1015): 	at cyp.g(PG:143)
E/Tiresias( 1015): 	at cyp.b(PG:137)
E/Tiresias( 1015): 	at cwk.a(PG:659)
E/Tiresias( 1015): 	at com.android.inputmethod.latin.LatinIME.a(PG:219)
E/Tiresias( 1015): 	at cwk.onFinishInputView(PG:640)
E/Tiresias( 1015): 	at android.inputmethodservice.InputMethodService.finishViews(InputMethodService.java:1703)
E/Tiresias( 1015): 	at android.inputmethodservice.InputMethodService.hideWindow(InputMethodService.java:1718)
E/Tiresias( 1015): 	at android.inputmethodservice.InputMethodService.doHideWindow(InputMethodService.java:1714)
E/Tiresias( 1015): 	at android.inputmethodservice.InputMethodService.-wrap2(Unknown Source:0)
E/Tiresias( 1015): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInput(InputMethodService.java:457)
E/Tiresias( 1015): 	at cxe.hideSoftInput(PG:6)
E/Tiresias( 1015): 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:199)
E/Tiresias( 1015): 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
E/Tiresias( 1015): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/Tiresias( 1015): 	at android.os.Looper.loop(Looper.java:164)
E/Tiresias( 1015): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/Tiresias( 1015): 	at java.lang.reflect.Method.invoke(Native Method)
E/Tiresias( 1015): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/Tiresias( 1015): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
I/zygote64(10904): Explicit concurrent copying GC freed 30521(1330KB) AllocSpace objects, 12(240KB) LOS objects, 49% free, 4MB/9MB, paused 93us total 41.103ms
```
I'm not seeing a problem with Xamarin.Android here?

Can you file a bug here? https://developercommunity.visualstudio.com/ This is the only place I see to file bugs for Xamarin.UITest.

Closing for now, let me know if there is a Xamarin.Android problem here. Thanks!

**Comment by codecore** [comment]
https://developercommunity.visualstudio.com/content/problem/549106/xamarin-uitest-runtime-calls-endsession-without-fi.html
