### ISSUE TITLE
AddSubtitleSource crashes app to launcher on Android with VideoView

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/xamarin-android#3008]
### Description
using AddSubtitleSource using any type of .NET stream (which is all that's allowed now) crashes the app to the desktop.

### Steps to Reproduce

1. Create a video view with a video.
2. Get a stream of the text of the text/vtt file. (memorystream, httpstream, doesn't matter they all have the same issue)
2. Use AddSubtitleSource like this videoView.AddSubtitleSource(stream, MediaFormat.CreateSubtitleFormat("text/vtt", caption.LanguageCode?.ToUpper() ?? "EN"));
3.  Run your code and observe as your app crashes to the launcher

### Expected Behavior
Should add the subtitles to the options for the video player.

### Actual Behavior
Crash to launcher

### Basic Information

- Version with issue: 3.6.0.293080
- Last known good version: N/A
- IDE: VS.NET 2019 Windows
- Platform Target Frameworks: 
  - Android: 8.1 Oreo, Min 6.0 marshmallow
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices: Pixel 2XL Emulator.

**Comment by pjcollins** [comment]
I'm not sure that there is an issue with Xamarin.Android being described here. I think you may need to rework your `VideoView` usage in `VideoPlayerRenderer.cs` The following stripped down snippet does not throw for me (though subtitles aren't displaying in this trivial demo, but I'm not too familiar with these APIs).

```csharp
using Android.App;
using Android.OS;
using Android.Widget;
using System.Net.Http;
using System.Threading.Tasks;
using Android.Media;

namespace App1
{
	[Activity(Label = "@string/app_name", MainLauncher = true)]
	public class MainActivity : Activity
	{
		protected override void OnCreate(Bundle savedInstanceState)
		{
			base.OnCreate(savedInstanceState);

			var view = GetVideoSourceAsync().GetAwaiter().GetResult();

			var controller = new MediaController(this);
			controller.SetAnchorView(view);
			view.SetMediaController(controller);

			SetContentView(view);
			view.Start();
		}

		async Task<VideoView> GetVideoSourceAsync()
		{
			var videoView = new VideoView(this);
			videoView.SetVideoURI(Android.Net.Uri.Parse("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"));

			using (var client = new HttpClient())
			{
				var stream = await client.GetStreamAsync("https://html5multimedia.com/code/ch8/elephants-dream-subtitles-en.vtt").ConfigureAwait(false);
				videoView.AddSubtitleSource(stream, MediaFormat.CreateSubtitleFormat("text/vtt", "EN"));
			}

			return videoView;
		}
	}
}
```

**Comment by KevinAnass** [comment]
> I'm not sure that there is an issue with Xamarin.Android being described here. I think you may need to rework your `VideoView` usage in `VideoPlayerRenderer.cs` The following stripped down snippet does not throw for me (though subtitles aren't displaying in this trivial demo, but I'm not too familiar with these APIs).
> 
> ```cs
> using Android.App;
> using Android.OS;
> using Android.Widget;
> using System.Net.Http;
> using System.Threading.Tasks;
> using Android.Media;
> 
> namespace App1
> {
> 	[Activity(Label = "@string/app_name", MainLauncher = true)]
> 	public class MainActivity : Activity
> 	{
> 		protected override void OnCreate(Bundle savedInstanceState)
> 		{
> 			base.OnCreate(savedInstanceState);
> 
> 			var view = GetVideoSourceAsync().GetAwaiter().GetResult();
> 
> 			var controller = new MediaController(this);
> 			controller.SetAnchorView(view);
> 			view.SetMediaController(controller);
> 
> 			SetContentView(view);
> 			view.Start();
> 		}
> 
> 		async Task<VideoView> GetVideoSourceAsync()
> 		{
> 			var videoView = new VideoView(this);
> 			videoView.SetVideoURI(Android.Net.Uri.Parse("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"));
> 
> 			using (var client = new HttpClient())
> 			{
> 				var stream = await client.GetStreamAsync("https://html5multimedia.com/code/ch8/elephants-dream-subtitles-en.vtt").ConfigureAwait(false);
> 				videoView.AddSubtitleSource(stream, MediaFormat.CreateSubtitleFormat("text/vtt", "EN"));
> 			}
> 
> 			return videoView;
> 		}
> 	}
> }
> ```

i try this code and the subtitle not showing in the video sir

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.
