### ISSUE TITLE
InputFilter placing buffer into dest

### ISSUE THREAD

**Issue by nodoid** [xamarin/xamarin-android#3034]
### Steps to Reproduce

1. Compile the demo below. Type ASDFGhjkl
2. ASDFG shows in the edit text
3. Press delete. You will need to press delete 5 times before G is delete.

https://github.com/nodoid/edittext_error

### Expected Behavior
If ASDFG is being passed in dest, pressing delete once should remove G
### Actual Behavior
Delete needs to be pressed however many times after the last uppercase character there is an "illegal" entry
### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.0.4 (build 0)
Installation UUID: 933163e9-dca5-472b-b2ed-29d7aab111ab
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.3
	2.1.9
	2.1.8
	2.1.6
	2.1.2
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.500
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.147 (Visual Studio Community)
Hash: a5f2633f
Branch: d16-1
Build date: 2019-04-10 09:42:20-0400

=== Xamarin.iOS ===

Version: 12.10.0.147 (Visual Studio Community)
Hash: a5f2633f
Branch: d16-1
Build date: 2019-04-10 09:42:19-0400

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== Xamarin.Android ===

Version: 9.3.0.14 (Visual Studio Community)
Android SDK: /Users/pfj/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08@bf4e8d2ae19
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/pfj/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800040000
Git revision: 09831ae7eef8ea58cdfad2e923c65a5bf70d27fd
Build date: 2019-04-15 23:04:13+00
Build branch: master
Xamarin extensions: 5efedb990d786142d3b54351c01ce867af7b7680

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.Forms HotReload extension 1.1.0
Team Foundation Version Control for TFS and Azure DevOps 0.4.4.5

**Comment by pjcollins** [comment]
I don't believe this is a Xamarin.Android issue, I believe it is an issue in your `IInputFilter` implementation. Perhaps the [Android.Text.InputFilterAllCaps](https://developer.xamarin.com/api/type/Android.Text.InputFilterAllCaps/) input filter will meet your needs?
