### ISSUE TITLE
Is xamarin app compiled to binary code or JVM byte-code?

### ISSUE THREAD

**Issue by ygc369** [xamarin/xamarin-android#3036]
I hope that Xamarin app on Android platform could be compiled to binary code which could be executed by CPU directly, in order to get best performance.

**Comment by radekdoulik** [comment]
By default the Xamarin.Android application is compiled into CIL, which is translated to native code during runtime by JIT.

It is possible to use [AOT](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/?tabs=macos#aot) to precompile assemblies to native code during build time.
