### ISSUE TITLE
"FileNotFoundException: Could not load assembly 'System.Runtime..." during LinkAssemblies for projects that depend indirectly on System.Runtime.CompilerServices

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#3045]
Motivating Developer Community item: <https://developercommunity.visualstudio.com/content/problem/551186/android-build-failed-on-linker-systemruntime-e>

That report is based on the project in <https://github.com/jamesmontemagno/AllExtensions-DI-IoC>

This is a change in behavior between xamarin-android-9.2.3.0 and xamarin-android.9.3.0.14.  I noticed a difference in the output of the `<ResolveAssemblies/>` task between those two versions, so I tested the commits between those versions that modified `ResolveAssemblies.cs` and found that this problem started with the switch to System.Reflection.Metadata in [xamarin-android/master@c22475d7](https://github.com/xamarin/xamarin-android/commit/c22475d79f699c84ae86c67c4c09d56d09cbd56f). I'm not sure yet if this is revealing a different problem that was in the build process for longer or if the new behavior of `ResolveAssemblies` is slightly incorrect.

### Steps to Reproduce

Attempt to build the [attached test case](https://github.com/xamarin/xamarin-android/files/3130236/ResolveAssembliesSystemRuntime.zip) in the Debug configuration.  This is just an empty Xamarin.Android project with the Microsoft.Extensions.Http NuGet package added.

### Expected Behavior, as seen with [xamarin-android/master@974cf7d](https://github.com/xamarin/xamarin-android/commit/974cf7ddb105f5d9ed2aedab9f8cd6d1991307eb)

The project builds without error.  The build logs show that the `<ResolveAssemblies/>` task adds System.Runtime for System.Runtime.CompilerServices:

```
Adding assembly reference for System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, recursively... (TaskId:173)
  Adding assembly reference for System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, recursively... (TaskId:173)
Adding assembly reference for System.Xml, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, recursively... (TaskId:173)
```

### Actual Behavior in Visual Studio 2019 version 16.1 Preview 2 and [xamarin-android/master@c22475d7](https://github.com/xamarin/xamarin-android/commit/c22475d79f699c84ae86c67c4c09d56d09cbd56f)

The `<LinkAssemblies/>` task fails because it fails to locate the System.Runtime assembly:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2146,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2146,5): error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
```

The build log shows that `<ResolveAssemblies/>` task does *not* add System.Runtime for System.Runtime.CompilerServices:

```
Adding assembly reference for System.Runtime.CompilerServices.Unsafe, recursively... (TaskId:173)
Adding assembly reference for System.Xml, recursively... (TaskId:173)
```

### Log File

[buildlogs.zip](https://github.com/xamarin/xamarin-android/files/3130241/buildlogs.zip)

> VS bug [#859946](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/859946)

**Comment by jonathanpeppers** [comment]
@brendanzagaeski was the test case working for you with xamarin-android/master (or 16.2)? It worked for me.

I'm afraid that it might be mono-2019-02 that is fixing the problem here...

**Comment by BrennanConroy** [comment]
We're hitting this issue while trying to test SignalR bits against Xamarin. Is there a temporary workaround for this locally so we can continue with testing?

**Comment by brendanzagaeski** [comment]
> was the test case working for you with latest xamarin-android/master (or 16.2)?

Innnteresting. I hadn't tried with `master` or `d16-2` yet. I'll try that now to help confirm that I get the same improved behavior on those versions. At first glance, it looks like it is indeed being fixed a different way in `master` because the line about adding System.Runtime in your log file from `master` is now its own "top-level" line instead of being indented under System.Runtime.CompilerServices.Unsafe:

```
    Adding assembly reference for System.Runtime.CompilerServices.Unsafe, recursively... (TaskId:211)
    Adding assembly reference for System.Runtime, recursively... (TaskId:211)
    Adding assembly reference for System.Xml, recursively... (TaskId:211)
```

**Comment by brendanzagaeski** [comment]
> Is there a temporary workaround for this

One quick-and-dirty idea that let me stop the error in local experiments (partly just to help me double-check the role of the `<ResolveAssemblies/>` task) was to add an explicit `@(FilteredAssemblies)` item for the  *System.Runtime.dll* facade assembly in the *.csproj* file:

```xml
<ItemGroup>
    <FilteredAssemblies Include="C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.dll" />
</ItemGroup>
```

As a caution, until the investigation is complete for this issue, I'd be hesitant to say this is necessarily a _correct_ fix, but I suspect it would be OK to use for temporary testing purposes.

**Comment by jonathanpeppers** [comment]
I think master is working, because it's just "lucky", here is a comparison: https://www.diffchecker.com/4lcQRLiN

I have a local build of 16.1, and it seems that `<ResolveAssemblies/>` sees `netstandard` as a reference of `System.Runtime.CompilerServices.Unsafe` when it should be seeing `System.Runtime`. Somehow it is looking at the reference assembly instead of the real assembly.
