### ISSUE TITLE
Xamarin Android Webview does not recognize download links after Chrome 69+ update on Android devices.

### ISSUE THREAD

**Issue by keyur-apa** [xamarin/xamarin-android#3061]
### Steps to Reproduce

1. Create a Webview on Xamarin App with a page which consist a link to a file (pdf for example.)
2. Make sure is Chrome is up-to-date (69+ version) on android device your app is running.
3. Try to click on the file link on that webview, it will do nothing.
4. Now if you uninstall all updates on chrome & go back to 69 or older version of chrome and repeat step-3, it should work.

**Comment by jonathanpeppers** [comment]
@keyur-apa Xamarin.Android just presents Android APIs to C# as-is. I'm not sure there would be a bug in Xamarin.Android here? It seems more like a general bug in Android.

Can you attach one of the following?
* A simple repro project -- using the `WebView` and URL you see the problem with?
* The [android device log](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log) (adb log) of when the problem occurs. Are there any errors logged?

Anything you can send would help, thanks!

**Comment by jonathanpeppers** [comment]
Let us know if you can send more info, thanks.
