### ISSUE TITLE
Auto focus is not working in Xamarin.Android with talk back enabled

### ISSUE THREAD

**Issue by Balasubramanian93** [xamarin/xamarin-android#3076]
### Steps to Reproduce

Reproducing Sample : Attached in this thread.

1. Enable accessibility feature in android device.
2. Deploy and run the application. 
3. We had set the AutoFocus property of the Button with text Mango to focus that button once the application is launched. But the first button added in the view got focus.

### Expected Behavior

Button with the text Mango should be focused.

### Actual Behavior

Button with the text Apple should be focused

### Version Information

[spanishSample.zip](https://github.com/xamarin/xamarin-android/files/3152261/spanishSample.zip)
All Xamarin.Android version

Area: Accessibility, Autofocus

**Comment by pjcollins** [comment]
I think you may be able to achieve this with the following snippet, though I haven't tested it:
```csharp
var button = FindViewById<Button>(Resource.Id.button2);
button.SendAccessibilityEvent(Android.Views.Accessibility.EventTypes.ViewFocused);
```
Or perhaps try to use the `android:accessibilityTraversalBefore` property in your layout file?

**Comment by jonathanpeppers** [comment]
@Balasubramanian93 let us know if peter's idea worked for you, thanks.
