### ISSUE TITLE
Apk per ABI fails with TargetFrameworkVersion v7.1 and lower when Aapt2 is enabled

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#3083]
### Steps to Reproduce

1. ``` msbuild /t:SignAndroidPackage *.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v7.1 /p:AndroidCreatePackagePerAbi=True /p:AndroidUseAapt2=True```

This could be considered a regression in d16-2 as `Aapt2` resource processing is now enabled by default.

### Actual Behavior
I've noticied a difference in `Aapt2Link` task behavior when comparing good and bad builds (both attached below). For some reason ABI specific manifest files don't appear to be processed by `Aapt2Link` when targeting a lower API level, and the ABI specific resource files are never created:

```
error MSB4018: The "BuildApk" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: Could not find file 'obj\Release\71\android\bin\packaged_resources-armeabi-v7a'
```

### Version Information
XA D16-2 9.4.0.4 (HEAD/cc0e8b8d5)

### Log File
[good-bad-binlogs.zip](https://github.com/xamarin/xamarin-android/files/3158319/good-bad-binlogs.zip)

**Comment by dellis1972** [comment]
@pjcollins I repo'd this locally :) looks like we might have broken something.

**Comment by dellis1972** [comment]
ok I found the problem. Aapt2 is writing warnings to StdError so this line

```
return proc.ExitCode == 0 && !output.Any (x => x.StdError);
```

is causing us to think the call to aapt2 failed. But we are only getting warnings

```
/Users/dean/Documents/Sandbox/Xamarin/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2533,3): warning APT0000: W/ResourceType(31967): For resource 0x0101053d, entry index(1341) is beyond type entryCount(1329) [/Users/dean/Projects/BlankAndroid/BlankAndroid.csproj]
/Users/dean/Documents/Sandbox/Xamarin/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2533,3): warning APT0000: W/ResourceType(31967): For resource 0x0101053e, entry index(1342) is beyond type entryCount(1329) [/Users/dean/Projects/BlankAndroid/BlankAndroid.csproj]
/Users/dean/Documents/Sandbox/Xamarin/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2533,3): warning APT0000: W/ResourceType(31967): For resource 0x0101053b, entry index(1339) is beyond type entryCount(1329) [/Users/dean/Projects/BlankAndroid/BlankAndroid.csproj]
/Users/dean/Documents/Sandbox/Xamarin/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2533,3): warning APT0000: W/ResourceType(31967): For resource 0x0101053c, entry index(1340) is beyond type entryCount(1329) [/Users/dean/Projects/BlankAndroid/BlankAndroid.csproj]
```

**Comment by pjcollins** [comment]
Moving to d16-3 as aapt2 has been disabled by default again in d16-2.

**Comment by EmilAlipiev** [comment]
it is still the case using Vs4Mac 2019 8.3preview.

**Comment by brendanzagaeski** [comment]
A new preview version has now been published that includes a fix for this item.

Fix included in Xamarin.Android 10.0.0.40.

Fix included on Windows in Visual Studio 2019 version 16.3 Preview 3. To try the preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 3. To try the preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
