### ISSUE TITLE
SmtpClient.Send System.Net.Mail.SmtpException: Message could not be sent

### ISSUE THREAD

**Issue by sanchobear** [xamarin/xamarin-android#3089]
### Description
Sending email from Android Emulator using SmtpClient fails with System.Net.Mail.SmtpException Connection refused.
Using identical code in ConsoleApp succeeds.

### Steps to Reproduce

1. VS2019(16.0.3)
2. Xamarin.Forms(3.6.0.344457)
3. Android Emulator Android_Accelerated_x86_Oreo API 27
4. Replace gmail account data and password with valid data
```
var mail = new MailMessage
{
	From = new MailAddress("account@googlemail.com", "developer"),
	Subject = "Test smtp",
	Body = $"<p>Smpt test message</p><br>",
	IsBodyHtml = true
};
mail.To.Add("user@othermail.com");
var smtpClient = new SmtpClient
{
	Port = 587,
	Host = "smtp.gmail.com",
	EnableSsl = true,
	UseDefaultCredentials = false,
	Credentials = new System.Net.NetworkCredential("account@googlemail.com", "***password***")
};
smtpClient.Send(mail);
```
### Expected Behavior
Email received
### Actual Behavior
System.Net.Mail.SmtpException Connection refused at smtpClient.Send
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019(16.0.3)
- Platform Target Frameworks: 
  - Android: Oreo 8.1 API 27  
- Android Support Library Version: 
- Nuget Packages:
  - Xamarin.Essentials1.1.0
  - Xamarin.Forms 3.6.0.344457
- Affected Devices:
  - Android Emulator Android_Accelerated_x86_Oreo API 27

### Reproduction Link
[SmtpTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3162818/SmtpTest.zip)

**Comment by brendanzagaeski** [comment]
Thanks for the report! The current implementation of `SmtpClient` in the Xamarin.Android profile of Mono is considered obsolete:

```csharp
[Obsolete ("SmtpClient and its network of types are poorly designed, we strongly recommend you use https://github.com/jstedfast/MailKit and https://github.com/jstedfast/MimeKit instead")]
```

(<https://github.com/mono/mono/blob/2018-08-rc/mcs/class/System/System.Net.Mail/SmtpClient.cs#L62>)

So in general the recommendation if encountering issues with the current of `SmtpClient` would be to move to [MailKit](https://dotnetfoundation.org/projects?searchquery=MailKit&type=project) instead. (Farther the in the future, the Obsolete status of `SmtpClient` for the Xamarin.Android profile might change as the [.NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/) story evolves.)

In case it might also be useful to know, I tried a quick copy-paste of the example code into a test app, updated the password to use an app password for a Gmail account that has 2-factor authentication enabled, and built it using the latest Visual Studio 2019 version 16.1 release. That app was successfully able to send an email.  So if you cannot move to MailKit at this time, then it's possible that updating to the Visual Studio 2019 version 16.1 release might also help with the issue you are seeing.
