### ISSUE TITLE
EditText text is not aligned to the center properly while changing the layout of the View.

### ISSUE THREAD

**Issue by ashokkumar96** [xamarin/xamarin-android#3093]
### Steps to Reproduce

1. Run the attached sample.
2. Click the "Change Layout " button.
3. Text is not aligned to the center of the layout.

### Expected Behavior
Text should be aligned to center of the View, as the layout changes.

### Actual Behavior
Text is not aligned to center of the View, as the layout changes.

### Version Information
MicroSoft visual studio Version 15.9.4
Xamarin Android sdk 9.1.4.2

Reproduced in android device with version 7.1

[App13.zip](https://github.com/xamarin/xamarin-android/files/3178309/App13.zip)

**Comment by grendello** [comment]
Hi @ashokkumar96! Looking at the code, there's nothing specific to Xamarin.Android that would cause the behavior. This is all Android. Having said that, adding the following line to `Button_Click` before the call to `textview.Layout` makes the sample work:

```csharp
textview.Gravity = GravityFlags.Center;
```
