### ISSUE TITLE
Can't build app with DirectBootAware on VS 2019

### ISSUE THREAD

**Issue by rihadavid** [xamarin/xamarin-android#3098]
### Steps to Reproduce

1. Add `DirectBootAware = true` to activity declaration
2. Build the project
3. It fails with:
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018: The "GetAddOnPlatformLibraries" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018: System.Xml.XmlException: 'android:directBootAware' is a duplicate attribute name. Line 172, position 142.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.AttributeDuplCheck()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.ParseAttributes()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.ParseElement()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.ParseElementContent()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.Read()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Tasks.GetAddOnPlatformLibraries.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Version Information

Microsoft Visual Studio Community 2019
Version 16.0.4
VisualStudio.16.Release/16.0.4+28803.452
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Community

Azure App Service Tools v3.0.0   16.0.12313.64372
Azure App Service Tools v3.0.0

C# Tools   3.0.0-beta4-19218-01+18b0cfb66884840b40491fa0896a8854d68b3959
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.0.300 (573eda3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.0.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.0.0-beta4-19218-01+18b0cfb66884840b40491fa0896a8854d68b3959
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 809f41207b74a1356208f11b8fa3a15233734050.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.0.0.521 (d16-0@7b060b3b9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.17.4.419 (remotes/origin/d16-0@c5f131be7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.1.47 (31f664d)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.2.3.0 (HEAD/9f6426ab2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08-rc@5ac37ccd385
    Java.Interop: xamarin/java.interop/d16-0@c987483
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    MXE: xamarin/mxe/xamarin@b9cbb535
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.26.0@325e91a
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

Xamarin.iOS and Xamarin.Mac SDK   12.8.0.2 (f2248ae)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonathanpeppers** [comment]
@rihadavid thanks for the report, it does look like we didn't add a test for this feature in: https://github.com/xamarin/xamarin-android/commit/7c9dea81e5a4abdbe910e227493be95d89456017

However, if I try:
```csharp
[Test]
public void DirectBootAware ()
{
	var proj = new XamarinAndroidApplicationProject ();
	proj.MainActivity = proj.DefaultMainActivity.Replace ("[Activity (", "[Activity (DirectBootAware = true, ");
	using (var b = CreateApkBuilder (Path.Combine ("temp", TestName))) {
		Assert.IsTrue (b.Build (proj), "Build should have succeeded.");
	}
}
```

But this looks like it is working fine. Is your project doing anything besides `[Activity (DirectBootAware = true]`? Does it happen with a small sample project?

If you could send a [diagnostic build log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) that would also help. Thanks!

**Comment by rihadavid** [comment]
Turns out I forgot to remove [the workaround](https://github.com/xamarin/xamarin-android/issues/2081#issuecomment-453979427) from my csproj. Sorry, closing.
