### ISSUE TITLE
CIL strip for profiled AOT

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#3109]
Find out whether it would make sense to add possibility to strip CIL from assemblies for methods contained in the profile. So that would be pretty much Profiled Hybrid AOT.

It would reduce the apk size.

Not sure how much is Hybrid AOT used now though, as it is not available in IDE (IIRC).

**Comment by nexxuno** [comment]
Hybrid AOT is used by many people judging by the bug reports so this would be great too.

**Comment by jonpryor** [comment]
I believe that "CIL strip" was "more broadly" implemented in 82a409278062bd8f5a5bf59d77dd2e66853017a8, and can remove methods even when "normal" (non-Hybrid) Profiled AOT is used, but requires setting the `$(AndroidStripILAfterAOT)` MSBuild property to true.
