### ISSUE TITLE
Thrown an exception while enabling "AndroidUseAapt2" in application.

### ISSUE THREAD

**Issue by Iyyappanmani** [xamarin/xamarin-android#3123]
### Steps to Reproduce

 We have created the sample to reproduce the issue.
In our sample, we have created the one custom control that contains the layout from axml and it has been inflated in our library project.

In our application project, we have only added that custom control into the view and we are facing the below error at the time of enabling the AndroidUseAapt2 in our application.

### Expected Behavior

It should run without any exception.

### Actual Behavior

It has thrown the runtime exception as shown below.

### Basic Information

- Visual Studio Version: Both 2017 and 2019
- Platform Target Frameworks: 
  - Android: Xamarin.Android.SDK version 9.1.7.0
- Android Support Library Version: 28.0.0.1

### Screenshots

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/31088253/58323322-43624b00-7e41-11e9-9962-aec891e61f9f.png)

Error log: Unhandled Exception:

Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class InflatedLibrary.CodeBehindClass occurred

### Sample
[Sample](http://www.syncfusion.com/downloads/support/directtrac/general/ze/INFLAT~11896928298)

**Comment by dellis1972** [comment]
Thanks for the bug report and the example, I have tested this on our latest internal preview (XA SDK 9.4.x) and I am able to reproduce this issue. I'll start taking a look to see what is happening.

**Comment by dellis1972** [comment]
Looks like the `_ConvertCustomViews` task is being skipped it thinks the resources are up to date.

**Comment by HemalathaMarikuma-syncfusion** [comment]
Hi @jonpryor  - we have faced this same issue even disable the aapt2. Is anyone faced this in before

**Comment by jonathanpeppers** [comment]
@HemalathaMarikuma-syncfusion this issue is a bit old, can you file a new one including build logs?

One thing to note is that enabling Android App Bundles forces aapt2 to be enabled. Just and idea, but maybe that is happening?
