### ISSUE TITLE
VS axml designed doesn't support comment-out shortcut

### ISSUE THREAD

**Issue by dotMorten** [xamarin/xamarin-android#3129]
### Steps to Reproduce

1. Open an AXML file
2. Select a piece of XML
3. Use the shortcut "CTRL+E,C" or "CTRL+K,C" to comment out a piece of XML.

The two above shortcuts are common for (un)commenting code, xml etc in the various text editors but is missing from AXML.

### Expected Behavior
The selected text gets commented out like it does in the XAML editor with `<!--   -->`

### Actual Behavior
Nothing happens

### Version Information
VS 15.9.11

It appears the comment/uncomment options aren't even there. Here's a Edit menu when a XAML file is open:

![image](https://user-images.githubusercontent.com/1378165/58360975-8112a400-7e40-11e9-8563-320e43db7bda.png)

And when an AXML file is open:
![image](https://user-images.githubusercontent.com/1378165/58360988-8d96fc80-7e40-11e9-8a9d-80fbd9b8cfe7.png)

**Comment by jpobst** [comment]
If this is still an issue:

This issue likely occurs in the Android Designer, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
