### ISSUE TITLE
Android VS Archive Manager feedback

### ISSUE THREAD

**Issue by mfeingol** [xamarin/xamarin-android#3137]
I wasn't sure where to write this, so please feel free to redirect me to an appropriate location.

I have the following feedback on your Android Archive Manager which, otherwise, is a wonderful tool:

1. When the AndroidCreatePackagePerAbi option is selected, the Google Play distribution wizard will upload the APK for each ABI, and will also attempt to upload the full APK. I don't _think_ the latter is necessary, and it will fail if the full APK is larger than 100MB. It should be optional to upload it or not.

2. The Google Play distribution wizard offers the default Google Play tracks (Alpha, Beta, etc), but does not discover and list any custom tracks created by the user. In my case, I'm using a custom closed release track (not Alpha, but similar) and it doesn't show up on the list.

3. In recent VS releases (e.g. 16.1.1) I'm seeing duplicate entries in the archive list. The repro is as easy as creating a new archive, closing VS, then going to archives. Each entry will be listed twice.

Thanks!

**Comment by JonDouglas** [comment]
@mfeingol Thank you so much for your feedback. I'm sadly going to have to ask for you to create a `Suggestion` in Visual Studio, as this pertains to multiple products and not just one. Also we want to keep your feedback in a central place so others can upvote these ideas as we continuously improve the product.

https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019

For the few issues that seem like bugs, can you file issues for them? (i.e. 1 and 3)

https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
