### ISSUE TITLE
MonoBtlsObject.CheckThrow ()

### ISSUE THREAD

**Issue by Vikashkumar117** [xamarin/xamarin-android#3139]
I am getting the error and i guess the issue is from the Mono.Android dll. Here is the log

02-17 12:26:59.082 21372 21436 E AppCenterCrashes: Unhandled Exception from source=AppDomain

02-17 12:26:59.082 21372 21436 E AppCenterCrashes: System.NullReferenceException: Object reference not set to an instance of an object.

02-17 12:26:59.082 21372 21436 E AppCenterCrashes:   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1[TResult].GetAwaiter () [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

02-17 12:26:59.082 21372 21436 E AppCenterCrashes:   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0xd4876f98 + 0x00033> in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

02-17 12:26:59.272 21372 21397 E mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsObject.CheckThrow () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsObject.get_Handle () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsX509VerifyParam.get_Handle () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsX509VerifyParam.get_CanModify () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsX509VerifyParam.WantToModify () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0xd4876f98 + 0x00033> in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

02-17 12:26:59.292  3007  3860 D libEGL  : eglTerminate EGLDisplay = 0x7f7653ee78

02-17 12:26:59.292  3007  3860 D libEGL  : eglTerminate EGLDisplay = 0x7f7653ee78

02-17 12:26:59.292 21372 21436 E mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.

02-17 12:26:59.292 21372 21436 E mono-rt :   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1[TResult].GetAwaiter () [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

02-17 12:26:59.292 21372 21436 E mono-rt :   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0xd4876f98 + 0x00033> in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

Please help me as soon as possible.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
