### ISSUE TITLE
VS2019: aapt2 throws pixel missing upper left corner error

### ISSUE THREAD

**Issue by ianvink** [xamarin/xamarin-android#3141]
I opened our XF 3.6 solution in VS2019 Release, set the "Use incremental Android packaging system (aapt2)", deleted the bin/obj folders. See screenshot

Build fails with :

```
Error		top-left corner pixel must be either opaque white or transparent.	

Max.Droid	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1400
```	

### Steps to Reproduce

1.  Open in VS 2019
2.  Enable aapt2
3.  Build

### Expected Behavior
Compiles
### Actual Behavior
Doesn't compile, may cause Brexit issues too (unconfirmed) 
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - Android:  VS 2019 Release

### Screenshots
 
![2019-04-02 10_56_22-Window](https://user-images.githubusercontent.com/112916/55424855-fc896080-5535-11e9-8338-4b686842e60d.png)

**Comment by JonDouglas** [comment]
@dellis1972 @jonathanpeppers ^

@ianvink Is it possible for you to minimalize the test case with a smaller set of resources you believe are causing this aapt2 failure? That way we don't have to worry about confidential code. Especially if your verbose build log contains the resource type that aapt2 is failing on. I believe you might be able to also run the aapt2 command line from the build log with the `-v` tag too.

**Comment by dellis1972** [comment]
Please note that `aapt2` has more strict requirements than `aapt`. Some things that were warnings are now errors. I suspect this is one of them. In this case I suspect you have a 9 patch image which has some issue with its background which the new resource compiler does not like. 

Something like (this)[https://stackoverflow.com/questions/55013848/top-left-corner-pixel-must-be-either-opaque-white-or-transparent] might help solve the issue.

**Comment by jonathanpeppers** [comment]
@ianvink can you make a quick sample project with the image that causes the issue?

This might also be related to #3083.

**Comment by jonathanpeppers** [comment]
@ianvink let us know if you can send more info, closing for now, thanks!
