### ISSUE TITLE
Constantly have to delete or edit emulator to test code

### ISSUE THREAD

**Issue by cloudxsky** [xamarin/xamarin-android#3165]
### Steps to Reproduce

1. Test code on Windows 10 emulator with Hyper-V enabled 
2. Exit out of emulator (pressing x on the emulator)
3. Change code (if you don't you won't get an error but it will say that the application doesn't exist at the file location it's looking for)
4. Make sure build is successful and it's not a Resouce.Designer.cs issue
5. Run the emulator again
6. App won't run
7. Edit the emulator and you'll see this 
![image](https://user-images.githubusercontent.com/33331184/58831190-5a572900-8609-11e9-98f5-e3f1b19f8d84.png)

### Expected Behavior
can run the emulator multiple times or after changes and it will work

### Actual Behavior
Run the emulator first time and it's fine. Run the emulator a second time and it doesn't work. 

### Version Information
Visual studio community 2019 (installed 6/3/2019)
Android 9.0 (pie) API level 28 
Windows 10 Pro version 1809

Note: also tried to report this through Visual studio's "Send Feedback" but I click on it and it doesn't work.

**Comment by JonDouglas** [comment]
The primary issue you're seeing is an issue with Google's Android Emulator. Please make sure to report a bug there.

https://developer.android.com/studio/report-bugs#emulator-bugs

You might be running into this issue: https://issuetracker.google.com/issues/126622740
