### ISSUE TITLE
Each change to the proguard.cfg file requires manual delete of the obj folder

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-android#3189]
When updating only the proguard.cfg file between 2 compilation/deployment, the tooset does not reexecute the proguard/r8 step.

### Steps to Reproduce

1. build and run an app using android support libs with an incomplete proguard.cfg file and R8 on
2. it fails with a missing method exception (optimized away)
3. update the proguard file to add a rule to fix it
4. build and deploy/run (without debugging) => no change

If you delete the obj folder, build and deploy/run it will still crash but won"t crash anymore for the target of the rule you just added.

### Version Information

VS2019 16.1.2

**Comment by jonathanpeppers** [comment]
@softlion I'm not actually seeing this behavior with proguard or r8.

I added this test case:
```csharp
[Test]
public void UpdateProguardRule ([Values ("proguard", "r8")] string linkTool)
{
	var target = linkTool == "proguard" ? "_CompileToDalvikWithDx" : "_CompileToDalvikWithD8";
	var encoding = new UTF8Encoding (encoderShouldEmitUTF8Identifier: false); // Java doesn't like BOMs
	var proj = new XamarinAndroidApplicationProject {
		IsRelease = true,
		LinkTool = linkTool,
	};
	proj.OtherBuildItems.Add (new BuildItem (AndroidBuildActions.AndroidJavaSource, "Foo.java") {
		TextContent = () => "public class Foo { }",
		Encoding = encoding
	});
	string proguardRules = "";
	proj.OtherBuildItems.Add (new BuildItem ("ProguardConfiguration", "proguard.cfg") {
		TextContent = () => proguardRules,
		Encoding = encoding
	});
	using (var b = CreateApkBuilder (Path.Combine ("temp", TestName))) {
		Assert.IsTrue (b.Build (proj), "first build should have succeeded.");
		Assert.IsFalse (b.Output.IsTargetSkipped (target), $"`{target}` should not be skipped!");

		proguardRules = "-keep class Foo";
		proj.Touch ("proguard.cfg");

		Assert.IsTrue (b.Build (proj), "second build should have succeeded.");
		Assert.IsFalse (b.Output.IsTargetSkipped (target), $"`{target}` should not be skipped!");

		var className = "LFoo;";
		var dexFile = b.Output.GetIntermediaryPath (Path.Combine ("android", "bin", "classes.dex"));
		FileAssert.Exists (dexFile);
		Assert.IsTrue (DexUtils.ContainsClass (className, dexFile, b.AndroidSdkDirectory), $"`{dexFile}` should include `{className}`!");
	}
}
```
But it seems to be working, and I see:
```
Building target "_CompileToDalvikWithD8" completely.
Input file "proguard.cfg" is newer than output file "obj\Release\stamp\_CompileToDalvik.stamp".
```
Can you attach a [diagnostic build log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) or a [binary log](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md) and I can investigate further?

**Comment by jonathanpeppers** [comment]
let us know if you can send more info, closing for now, thanks!
