### ISSUE TITLE
Xamarin and SignalR can not resolve references

### ISSUE THREAD

**Issue by urodolf** [xamarin/xamarin-android#3191]
We have a problem since installing the latest version of Visual Studio and the latest Xamarin SDK with the projects that reference the SignalR.
We could compile our projects with previous versions of Visual Studio. 
Now we can only compile the projects in build machines with the following characteristics:
MSBuild 16.0.461.62831
BuildTools 2019 16.0.28729.10
Xamarin SDK 9.2.0.5
And in our develop computers we can not compile with the following characteristics:
MSBuild 16.1.76.45076
Xamarin SDK 9.3.0.22

### Steps to Reproduce

1. Create a new App following the step in 
https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart
2. Compile and execute and all is right.
3. Add nuget to Microsoft.AspNetCore.SignalR.Client v=1.1.0
4. In PhoneTraslator.cs add using to Microsoft.AspNetCore.SignalR.Client.
5. Add This line to use a component:
  HubConnectionBuilder conncetionBuilder = new HubConnectionBuilder();
6. Compile and get errors:
   Can not resolve reference to 'System.IO.Pipelines' ...
   Can not resolve reference to 'System.Runtime.CompilerServices.Unsafe' ...

Any idea what the problem might be?

**Comment by germandb** [comment]
I have the same issue, my xamarin project stop working after update Visual Studio, maybe @anurse can have a look at this.

**Comment by anurse** [comment]
Missing references like this tend to indicate problems with the versions of these packages embedded within Xamarin. Would probably be helpful to have some Xamarin folks look at this, though we're happy to help investigate where we can.

**Comment by jonathanpeppers** [comment]
@urodolf I tried your steps with Visual Studio 2019 16.1.3, and they are working for me.

I think there are some recent changes in Mono that fix this issue.

Try and let us know!

**Comment by urodolf** [comment]
We update or Visual Studio version and all nugets, but the result is the same.

I attach captures and a zip with a sample project.
![Running](https://user-images.githubusercontent.com/50919329/59852231-b42c5280-936e-11e9-9232-7b5fd3120ebe.PNG)
![Break](https://user-images.githubusercontent.com/50919329/59852232-b4c4e900-936e-11e9-9f4e-a2516c04f02c.PNG)
[AndroidApp1.zip](https://github.com/xamarin/xamarin-android/files/3310562/AndroidApp1.zip)

**Comment by jonathanpeppers** [comment]
@urodolf your sample project works for me; I just opened it and hit the Play button. Could you have automatic NuGet restore turned off? It just seems like something with NuGet is happening here.

Or... could you need a Visual Studio repair? 😟

**Comment by urodolf** [comment]
Thanks for your answer, I will review and repair all Visual Studio settings.
