### ISSUE TITLE
MONO_THREADS_SUSPEND correct usage and documentation?

### ISSUE THREAD

**Issue by dsaf** [xamarin/xamarin-android#3239]
### Steps to Reproduce

1. Observe frame rate drops despite tweaking MONO_GC_PARAMS various ways.
2. Read about MONO_THREADS_SUSPEND=hybrid and try using it - Android Xamarin app crashes on start.
3. Try googling and find exactly zero information.

### Expected Behavior
MONO_THREADS_SUSPEND=hybrid makes GC work unnoticeably in background.

### Actual Behavior
It just crashes on start and there is no documentation.

### Version Information

Microsoft Visual Studio Community 2019
Version 16.1.3
VisualStudio.16.Release/16.1.3+29009.5
...

Xamarin   16.1.0.543 (d16-1@34a619991)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.22 (HEAD/8e7764fdf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3cb36842fc4
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

Xamarin.iOS and Xamarin.Mac SDK   12.10.0.153 (750a879)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Related
https://github.com/mono/mono/issues/9712

**Comment by lambdageek** [comment]
Hybrid suspend is not supported yet for Xamarin.Android

**Comment by dsaf** [comment]
@lambdageek could you please point me to the roadmap and/or detailed documentation?

**Comment by lambdageek** [comment]
Hybrid suspend is the default on desktop Mono (OSX and Linux on AMD64) in 6.0.  Work on arm64  on Linux is ongoing in Mono.  Once it stabilizes, we will make it the default on Linux/arm64.  Some time after that, Xamarin.Android may begin to use it.  I don't have a more detailed roadmap than that. Sorry.

**Comment by dsaf** [comment]
@lambdageek thank you for the answer!
