### ISSUE TITLE
New "warning XA0106: Skipping MobileAppMasterDetail.Droid.Resource.Id.fixed" message when building a Xamarin.Forms project set to use AAPT in Visual Studio 2019 version 16.2 Preview

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#3250]
This issue is related to <https://github.com/xamarin/xamarin-android/pull/3243>, but I'm filing a separate issue because this particular scenario behaves as a *regression* in Visual Studio 2019 version 16.2 Preview (Xamarin.Android 9.4). That makes it is a slightly different consideration than the longer-standing concern addressed by <https://github.com/xamarin/xamarin-android/pull/3243> (that XA0106 warnings aren't always actionable by an application developer).  Another difference is that this case explicitly uses AAPT rather than AAPT2.  If I switch the project to use AAPT2 in Visual Studio 2019 version 16.1, then I can get the same warnings shown in <https://github.com/xamarin/xamarin-android/pull/3243>, so I'm less concerned about those warnings because the behavior hasn't changed for them between the releases.

### Steps to Reproduce

 1. Create a new **Mobile App (Xamarin.Forms) > Master-Detail** project in Visual Studio 2019 version 16.1.  Or download the attached example project.

 2. For the closest comparability across Visual Studio releases, explicitly disable AAPT2 by adding the following element to the Android app *.csproj* file:
    
    ```xml
    <PropertyGroup>
        <AndroidUseAapt2>false</AndroidUseAapt2>
    </PropertyGroup>
    ```

 3. Build the project in the Debug configuration in Visual Studio 2019 version 16.2 Preview 2 or higher.  For example, on the command line, run:

     ```cmd
     msbuild -restore MobileAppMasterDetail.sln
     ```
Example project: [MobileAppMasterDetail.zip](https://github.com/xamarin/xamarin-android/files/3303500/MobileAppMasterDetail.zip)

### Expected Behavior as seen in Visual Studio 2019 version 16.1

The build does not emit any warnings about Android resources.

### Actual Behavior with Visual Studio 2019 version 16.2 Preview

The build emits a warning about `Resource.Id.fixed`:

```
warning XA0106: Skipping MobileAppMasterDetail.Droid.Resource.Id.fixed. Please check that your Nuget Package versions are compatible.
```

It appears the cause of the warning might be that *Resources\\Resource.designer.cs* is missing a line that it had when the project was built with Visual Studio 2019 version 16.1:

```diff
diff --git "a/MobileAppMasterDetail.Android\\Resources\\Resource.designer.16.1.cs" "b/MobileAppMasterDetail.Android\\Resources\\Resource.designer.cs"
index 970f385..2805b6c 100644
--- "a/MobileAppMasterDetail.Android\\Resources\\Resource.designer.16.1.cs"
+++ "b/MobileAppMasterDetail.Android\\Resources\\Resource.designer.cs"
@@ -1257,7 +1257,6 @@ namespace MobileAppMasterDetail.Droid
                        global::Xamarin.Forms.Platform.Android.Resource.Id.fill_horizontal = global::MobileAppMasterDetail.Droid.Resource.Id.fill_horizontal;
                        global::Xamarin.Forms.Platform.Android.Resource.Id.fill_vertical = global::MobileAppMasterDetail.Droid.Resource.Id.fill_vertical;
                        global::Xamarin.Forms.Platform.Android.Resource.Id.filled = global::MobileAppMasterDetail.Droid.Resource.Id.filled;
-                       global::Xamarin.Forms.Platform.Android.Resource.Id.@fixed = global::MobileAppMasterDetail.Droid.Resource.Id.@fixed;
                        global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_appbar = global::MobileAppMasterDetail.Droid.Resource.Id.flyoutcontent_appbar;
                        global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_recycler = global::MobileAppMasterDetail.Droid.Resource.Id.flyoutcontent_recycler;
                        global::Xamarin.Forms.Platform.Android.Resource.Id.forever = global::MobileAppMasterDetail.Droid.Resource.Id.forever;
```

(Side note: The attached build log also shows a warning about "One or more errors occurred" during the `<GetPrimaryCpuAbi/>` task. That's unrelated. It also occurs and Visual Studio 2019 version 16.1. It is ignorable in the context of this issue.)

### Version Information

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.2.0 Preview 4.0 [29017.117.d16.2stg]
VisualStudio.16.IntPreview/16.2.0-pre.4.0+29017.117.d16.2stg
Microsoft .NET Framework
Version 4.7.03190

Xamarin.Android SDK   9.4.0.34 (d16-2/7cce305)

Android SDK Build-Tools 28.0.3

### Log File

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-android/files/3303510/msbuild.binlog.zip)

**Comment by brendanzagaeski** [comment]
I should perhaps mention that there's a chance this warning might be appearing because the resource ID generation is in some way more correct in the new version. That is, maybe it's correct for the `global::Xamarin.Forms.Platform.Android.Resource.Id.@fixed` ID not to 
 be included in the *Resource.designer.cs* file?

On the other hand, maybe something unexpected is happening in the new version, perhaps due to the `@` character in the field name?

**Comment by dellis1972** [comment]
The `@` is required because `fixed` is a reserved word in C#, so that will not be what is causing the issue. 

The actual cause of the warning is that the Xamarin.Forms Resource.designer.cs has a field which is referencing a resource with an id of `fixed`. The App however is NOT referencing that at all. As a result aapt has NOT generated an ID for it. The App Resource.designer.cs therefore does not have that field. So if we did include the following line

```
global::Xamarin.Forms.Platform.Android.Resource.Id.@fixed = global::MobileAppMasterDetail.Droid.Resource.Id.@fixed;
```

It would result with a compiler error. This was why this code was put in place. The normal reason for this is the "Library" package was built against an older version of the Support Libraries/Platform, the newer version which the app is referencing does NOT have this `fixed` id. The only way to remove these errors is to make sure that app and library are built against the same versions of the Support Libraries/Platform. This is impractical because we have a C# binding layer (in this case XF) which is being shipped as a nuget.

I'm not sure if this is a regression as such. Because we have probably bumped our Max API from 27 to 28 (or higher) and its probable that the version of XF being used was built against 27.
