### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 9103

### ISSUE THREAD

**Issue by funklet** [xamarin/xamarin-android#3252]
Hello,
I have opened my previously working VS 2017 project in VS 2019 16.1.3.
This project is available in the play store and installed on 100+ devices and has worked fine until now.
When in release mode it crashes on opening with
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 9103
[logcat.txt](https://droid.networklimited.co.uk/logcat.txt)
I am currently unable to use VS2019 for Xamarin Android work because of this.

Looking forward to some help!

**Comment by lvenchi** [comment]
i had a similar problem in #3178. What i suggest you is to check all the bindings in xaml files and ensure that they are of the same type of the variables.

**Comment by funklet** [comment]
Thank you for your comment. 
This is not a Xamarin-forms project though and there are no bindings of that nature. 
This crash happens immediately the app is launched. The splash screen shows and then the app crashes.
The logcat is from the Google Pre-Launch report.

**Comment by pjcollins** [comment]
Thanks for the report. Would you be able to provide us with a reproduction case by any chance? You could share it privately over email if needed. Unfortunately we'll need some more information in order to help diagnose the crash you're encountering.

**Comment by jonathanpeppers** [comment]
let us know if you can send more info, closing for now, thanks!
