### ISSUE TITLE
Link assemblies causes app crashes if you have an EditText in VS2019 Preview 2

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-android#3263]
### Steps to Reproduce

1. Add an EditText
2. Choose TextChanged. (Example:  `txtSearch.TextChanged += TxtSearch_TextChanged;`)
3. Choose Linking with either "Sdk Assemblies Only" or "Sdk and User Assemblies".
4. Execute the program.

### Expected Behavior

Be able to execute the TextChanged on Linking with either "Sdk Assemblies Only" or "Sdk and User Assemblies".

### Actual Behavior

App crashes because it cannot load ITextWatcherInvoker.

### Version Information

Windows 10, May Update.
Visual Studio 2019 Preview 2.

### Log File

> System.TypeLoadException: 'Could not load type 'Android.Text.ITextWatcherInvoker' from assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.'

![Annotation 2019-06-20 003519](https://user-images.githubusercontent.com/1666156/59806029-54449600-92f3-11e9-9df5-b3c453facd90.png)

**P.S.**

It's working in Visual Studio for Mac.

> VS bug [#947890](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/947890)

**Comment by pjcollins** [comment]
Thanks for the report! I assume you're referring to VS 2019 16.2 Preview 2? Could you paste the information displayed in `Help`  -> `About Microsoft Visual Studio`? I was unable to reproduce this with the upcoming VS 2019 16.2 Preview 3 release, though my repro may not have been sufficient. Could you also attach a solution file that demonstrates this crash?

**Comment by FANMixco** [comment]
> Thanks for the report! I assume you're referring to VS 2019 16.2 Preview 2? Could you paste the information displayed in `Help` -> `About Microsoft Visual Studio`? I was unable to reproduce this with the upcoming VS 2019 16.2 Preview 3 release, though my repro may not have been sufficient. Could you also attach a solution file that demonstrates this crash?

Yes, it's in the Preview 2 of VS 2019 for Windows only, I could try maybe sharing a OneDrive link because the solution is somehow huge more than a 100Mb.

**Comment by gmck** [comment]
I have exactly the same error however I'm using 16.2.0 Preview 3. I'm going to try an reproduce in a test project

**Comment by pjcollins** [comment]
I've got a repro in https://github.com/xamarin/monodroid-samples/blob/master/android5.0/Topeka/Topeka/Fragments/SignInFragment.cs#L90, just build and deploy the app in release mode and it'll crash on startup.

**Comment by FANMixco** [comment]
> I've got a repro in https://github.com/xamarin/monodroid-samples/blob/master/android5.0/Topeka/Topeka/Fragments/SignInFragment.cs#L90, just build and deploy the app in release mode and it'll crash on startup.

The Issue expanded to the latest version of Visual Studio for Mac.

**Comment by FANMixco** [comment]
Hi @radekdoulik , do we have any news in which release is going to be a fix about this issue? Preview 5? Or Later? Thanks.

**Comment by radekdoulik** [comment]
Don't know about the release version yet. I can reproduce the issue locally and I am looking into it.

**Comment by FANMixco** [comment]
> Don't know about the release version yet. I can reproduce the issue locally and I am looking into it.

I have a similar issue with CoordinatorLayouts, should I share the request here too?

**Comment by jonpryor** [comment]
@FANMixco asked:

> I have a similar issue with CoordinatorLayouts, should I share the request here too?

Please do.  Is it an `TypeLoadException` with the same `ITextWatcherInvoker` type, or is it a different exception or missing type?

Are you able to use any of the *recent* d16-3 or master builds to see if that fixes things for you?

  * https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/JenkinsBuildArtifacts.md
  * https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/lastSuccessfulBuild/Azure/

Thanks,
 - Jon

**Comment by FANMixco** [comment]
> @FANMixco asked:
> 
> > I have a similar issue with CoordinatorLayouts, should I share the request here too?
> 
> Please do. Is it an `TypeLoadException` with the same `ITextWatcherInvoker` type, or is it a different exception or missing type?
> 
> Are you able to use any of the _recent_ d16-3 or master builds to see if that fixes things for you?
> 
> * https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/JenkinsBuildArtifacts.md
> * https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/lastSuccessfulBuild/Azure/
> 
> Thanks,
> 
> * Jon

I'm going to check during the week, also, here is the new bug:

[](https://github.com/xamarin/xamarin-android/issues/3376)

**Comment by pjcollins** [comment]
The `Topeka` repro mentioned above is now working for me with the latest `d16-3` build. 

I was unable to reproduce the issue mentioned in #3376 in both 16.1 and 16.3 just by quickly modifying a new template, so I think we'll want to follow up on that issue separately. If you could attach logcat output and/or a project which reproduces the crash to the new issue you've filed that would be very helpful!

**Comment by FANMixco** [comment]
> The `Topeka` repro mentioned above is now working for me with the latest `d16-3` build.
> 
> I was unable to reproduce the issue mentioned in #3376 in both 16.1 and 16.3 just by quickly modifying a new template, so I think we'll want to follow up on that issue separately. If you could attach logcat output and/or a project which reproduces the crash to the new issue you've filed that would be very helpful!

Hi, here it is:

https://drive.google.com/open?id=1uBO5Xs2F83WZJA_pGxc5oYHN5PuJ6XSg

Also, I have another project where in Debug and Release behaves differently it misses one back button and if you use the compress it crashes when you run it. All those things didn't happen in the first stable version of VS2019.

**Comment by brendanzagaeski** [comment]
**Workaround notes for "System.TypeLoadException: 'Could not load type 'Android.Text.ITextWatcherInvoker' from assembly 'Mono.Android"**

In case any other users come across this issue when using Xamarin.Android 9.4, a possible workaround is to use a [custom linker configuration](https://docs.microsoft.com/xamarin/cross-platform/deploy-test/linker) to preserve the missing types.  To do that, add a new *linker.xml* file to the project, set the **Build Action** to **LinkDescription**, and add the XML lines to preserve the missing types.  For example, for the `ITextWatcherInvoker` error, add the following lines to the file:

```xml
<linker>
  <assembly fullname="Xamarin.Android">
    <type fullname="Android.Text.ITextWatcherInvoker" preserve="all" />
  </assembly>
</linker>
```

(Note: This workaround is for the symptom described at the [beginning of this issue](https://github.com/xamarin/xamarin-android/issues/3263#issue-458255384).)

**Comment by MichaelBourkeCF** [comment]
> **Workaround notes for "System.TypeLoadException: 'Could not load type 'Android.Text.ITextWatcherInvoker' from assembly 'Mono.Android"**
> 
> In case any other users come across this issue when using Xamarin.Android 9.4, a possible workaround is to use a [custom linker configuration](https://docs.microsoft.com/xamarin/cross-platform/deploy-test/linker) to preserve the missing types. To do that, add a new _linker.xml_ file to the project, set the **Build Action** to **LinkDescription**, and add the XML lines to preserve the missing types. For example, for the `ITextWatcherInvoker` error, add the following lines to the file:
> 
> ```
> <linker>
>   <assembly fullname="Xamarin.Android">
>     <type fullname="Android.Text.ITextWatcherInvoker" preserve="all" />
>   </assembly>
> </linker>
> ```
> 
> (Note: This workaround is for the symptom described at the [beginning of this issue](https://github.com/xamarin/xamarin-android/issues/3263#issue-458255384).)

Hi, this should be "Mono.Android" rather than "Xamarin.Android" in the xml file.  It won't compile otherwise.

**Comment by brendanzagaeski** [comment]
Correcting my previous comment. Thanks MichaelBourkeCF!

**Workaround notes for "System.TypeLoadException: 'Could not load type 'Android.Text.ITextWatcherInvoker' from assembly 'Mono.Android"**

In case any other users come across this issue when using Xamarin.Android 9.4, a possible workaround is to use a [custom linker configuration](https://docs.microsoft.com/xamarin/cross-platform/deploy-test/linker) to preserve the missing types.  To do that, add a new *linker.xml* file to the project, set the **Build Action** to **LinkDescription**, and add the XML lines to preserve the missing types.  For example, for the `ITextWatcherInvoker` error, add the following lines to the file:

```xml
<linker>
  <assembly fullname="Mono.Android">
    <type fullname="Android.Text.ITextWatcherInvoker" preserve="all" />
  </assembly>
</linker>
```

(Note: This workaround is for the symptom described at the [beginning of this issue](https://github.com/xamarin/xamarin-android/issues/3263#issue-458255384).)

**Comment by ushenkodmitry** [comment]
I have the same error in Visual Studio Community 2019 16.2.0.

**Comment by lexboss93** [comment]
I have rolled back to xamarin.android 9.2.3-0 to bypass this issue. 9.2.3-0 is the most stable version from recent ones imho.
Rolling back is easy. If you already have an old version on your system just change the "Current" symlink. If don't, then just [download](https://download.visualstudio.microsoft.com/download/pr/70ad99db-5313-4c32-9b0e-9c5b37a995c9/e505e4500a1a89d947906fecad034031/xamarin.android-9.2.3-0.pkg) it first.

**Comment by brendanzagaeski** [comment]
**Windows fix published**. The new Xamarin.Android SDK version 9.4.1.0 that includes a fix for this issue has now been published as part of Visual Studio 2019 version 16.2.1. [Check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/> to get the fix.

**macOS fix published**. The new Xamarin.Android SDK version 9.4.1.0 that includes a fix for this issue has now been released in the Stable updater channel in Visual Studio for Mac. [Check for the latest updates](https://docs.microsoft.com/visualstudio/mac/update) or install the most recent release from <https://visualstudio.microsoft.com/downloads/> to get the fix.

**Comment by subsembly** [comment]
Thanks for the fix. However, it seems that now there is no linking done at all. My build now produces a much larger APK output, regardless of whether I select link SDK or link None. Is this the expected behaviour?

**Comment by ushenkodmitry** [comment]
Size of my apk has increased from 26mb to 31mb after the update.

**Comment by FANMixco** [comment]
> **Windows fix published**. The new Xamarin.Android SDK version 9.4.1.0 that includes a fix for this issue has now been published as part of Visual Studio 2019 version 16.2.1. [Check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from https://visualstudio.microsoft.com/downloads/ to get the fix.
> 
> **macOS fix published**. The new Xamarin.Android SDK version 9.4.1.0 that includes a fix for this issue has now been released in the Stable updater channel in Visual Studio for Mac. [Check for the latest updates](https://docs.microsoft.com/visualstudio/mac/update) or install the most recent release from https://visualstudio.microsoft.com/downloads/ to get the fix.

Hi @brendanzagaeski any idea about the previous issues? Because it seems the issue is a new one then.

**Comment by brendanzagaeski** [comment]
Thanks for the heads-up! I looked through the open issues, noticed a similar report in <https://github.com/xamarin/xamarin-android/issues/3454>, and was able to confirm the problematic linker behavior using a new blank app project as suggested in that issue.

The size increase problem can now be tracked in that issue: <https://github.com/xamarin/xamarin-android/issues/3454>.

I'll keep an eye on that issue to make sure the status stays updated to reflect the investigation and release.

**Comment by EmilAlipiev** [comment]
Sorry but i don't understand why are you publishing some fix for this issue if there is a solution using a custom configuration file. there is now bigger issue effecting the larger community (basically all xamarin users).
