### ISSUE TITLE
Android deployment has become significantly slower in the latest release

### ISSUE THREAD

**Issue by UlrichBodentien** [xamarin/xamarin-android#3265]
In the newest version of Xamarin.Android and VSForMac, I'm experiencing that building and deploying an Android app suddenly was way slower prior to updating.

### Steps to Reproduce

1. Build and deploy a "large" code base to a device with Xamarin.Android. 
2. Building and deploying takes a long time. Around 4-5 minutes.

### Expected Behavior
Building and deploying should be fast
### Actual Behavior
Building and deploying takes around ~4-5 minutes.
### Version Information

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.1 (build 2742)
Installation UUID: 8ef27988-08ca-4212-b69b-d7d18cce0cea
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
	2.1.8
	2.1.6
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
	2.1.504
	2.1.500
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.153 (Visual Studio Enterprise)
Hash: 750a8798
Branch: d16-1-artifacts
Build date: 2019-04-30 15:17:54-0400

=== Xamarin.iOS ===

Version: 12.10.0.153 (Visual Studio Enterprise)
Hash: 750a8798
Branch: d16-1-artifacts
Build date: 2019-04-30 15:17:54-0400

=== Xamarin.Android ===

Version: 9.3.0.22 (Visual Studio Enterprise)
Commit: HEAD/8e7764fdf
Android SDK: /Users/Ulrich/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08@3cb36842fc4
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/Ulrich/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Designer ===

Version: 16.1.0.464
Hash: 66bb7b43f
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-07 07:10:32 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801002742
Git revision: ed27233de1b33083ea2234bc66a3b7824b99bbc7
Build date: 2019-06-12 10:18:51+00
Build branch: release-8.1
Xamarin extensions: 98dc4d7de2257c9b7342dee023910e16d02f8e65

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

**Comment by Ahrentlov** [comment]
Bump.

**Comment by pjcollins** [comment]
@UlrichBodentien thanks for the report, we have recently seen a few signals of potential slowdowns in certain areas in this release as well. Would you be able to switch over to the VS Mac preview channel and compare performance there? We believe that some of these slowdowns have been addressed there.

**Comment by jonathanpeppers** [comment]
@UlrichBodentien It would be helpful if you could record an [MSBuild binary log](https://github.com/Microsoft/msbuild/wiki/Binary-Log) with timing information.

If you could record a "clean" build+deploy:
```
$ git clean -dxf
$ msbuild foo.android.csproj /t:Install /restore /bl:first.binlog
```

Then make a one-line C# code change, and get a second log:
```
$ msbuild foo.android.csproj /t:Install /bl:second.binlog
```

`foo.android` should be the Android head project; zip up and attach the two `.binlog` files.

**Comment by UlrichBodentien** [comment]
Thanks for your replies. 
I tried to build the project with msbuild. The result is that the project builds and deploys very fast, within 1,5 minutes. So this seems to be something related to when building from Visual Studio for Mac

**Comment by jonathanpeppers** [comment]
Hmm, ok. @UlrichBodentien you can get the diagnostic build logs in VS for Mac: https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output

There should be text that the bottom that shows a simplified form of the timing information. Can you post those along with what you get command-line and we can compare? Thanks!

**Comment by jonathanpeppers** [comment]
let us know if you can send more info, closing for now, thanks!

**Comment by xacte-richard** [comment]
Hello,

@jonathanpeppers I actually have the same problem in my visual studio 2019. Buil and debug Android project take around 4-5 min after adding only one line. I try tl install preview 3 and i have the same problem. The problem also exist in visual studio 2017.

Thanks for your help, if you need more information let me know and i will sent it to you.

**Comment by jonathanpeppers** [comment]
@xacte-richard can you file a new issue with [diagnostic build logs](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? It will provide timing breakdown at the end of the file.

Time two scenarios:
* A "clean" build, where you ran Clean before or did something like `git clean -dxf`.
* A build where you changed one line of C# code or XAML.

That would help us look into it, thanks!

**Comment by Jhultink** [comment]
I downgraded to Xamarin.Android [9.2.3](http://dl.xamarin.com/MonoforAndroid/Mac/xamarin.android-9.2.3-0.pkg) and that fixed the slow deploy issue
