### ISSUE TITLE
R8 compiler fails if custom proguard config edited in VS 2019

### ISSUE THREAD

**Issue by ndastur** [xamarin/xamarin-android#3272]
### Steps to Reproduce

1. Open custom proguard config file in VS 2019 editor
2. Edit file and save
3. R8 will fail with error on compile due to a BOM character being added to the beginning of the file.

### Expected Behavior
r8 Compiles

### Actual Behavior
r8 Fails to compile

### Version Information

Visual Studio 2019 for Mac 8.1.1

**Comment by JonDouglas** [comment]
This is a bug I believe on Visual Studio's side. Have you by chance reported an issue about the file adding a BOM mark?

**Comment by ndastur** [comment]
I haven't. I thought probably best to report here as MS are very unlikely to modify their editor to not put BOM marks in. It seems to be an MS thing for their editors on the whole :(
I think the likely fix to do some sort of file conversion step before proguard processing?

**Comment by JonDouglas** [comment]
I think that is something we might be able to consider here. We'll see if it's possible today to improve the proguard and r8 story.

/cc @dellis1972 @jonathanpeppers

**Comment by ndastur** [comment]
Thank you. Happy to report on MS side too as I find it really annoying files are modified with hidden characters like that. But there does not seem to be the same bug reporting facility for VS

**Comment by JonDouglas** [comment]
@ndastur I would highly recommend reporting through the `Help -> Report a Problem` tool inside Visual Studio. It will most likely get routed to the VS team, but it always helps to add more reports so they know it's an issue for certain tools like Proguard and R8.

**Comment by ndastur** [comment]
Done

**Comment by sgjesse** [comment]
Opened http://issuetracker.google.com/135898791 on R8.

**Comment by sgjesse** [comment]
I have landed a fix for R8. Please let me know where Xamarin pulls its release version from, so I can merge the fix to the proper release channel.

**Comment by jonathanpeppers** [comment]
> I haven't. I thought probably best to report here as MS are very unlikely to modify their editor to not put BOM marks in. It seems to be an MS thing for their editors on the whole :(

@ndastur @JonDouglas A workaround for developers in Visual Studio is to use a `.editorconfig` file:
```.editorconfig
[*]
charset = utf-8
```
This removes the BOM from all files saved in Visual Studio, which you could restrict to `*.cfg` files if needed.

The issue with BOMs has been around a while; it happens with proguard, too. We have to workaround it in our tests: https://github.com/xamarin/xamarin-android/blob/53393e134647f69eff33a51dc4029d08931de513/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs#L3392-L3396

> I have landed a fix for R8. Please let me know where Xamarin pulls its release version from, so I can merge the fix to the proper release channel.

@sgjesse we get r8 from Maven: https://mvnrepository.com/artifact/com.android.tools/r8

Master has latest stable, which would be going out in our next release: https://github.com/xamarin/xamarin-android/blob/53393e134647f69eff33a51dc4029d08931de513/src/r8/build.gradle#L13

It will be easy update if there is an update for r8 on Maven.
