### ISSUE TITLE
Build exception (The "GenerateJavaStubs" task failed unexpectedly) when using NetworkSecurityConfig ApplicationAttribute

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#3276]
### Steps to Reproduce

1. Create new xamarin android application
2. Add [Application] attribute and set NetworkSecurityConfig value (@xml/network_security_config)
3. Build project

### Expected Behavior

Should allow user to specify path to the networkSecurityConfig

### Actual Behavior

Build fails (The "GenerateJavaStubs" task failed unexpectedly)

### Version Information

Visual studio 2019 16.1.3 (stable)

### Log File

Xamarin.Android.Common.targets(2342,3): error MSB4018: The "GenerateJavaStubs" task failed unexpectedly.
Xamarin.Android.Common.targets(2342,3): error MSB4018: System.ArgumentNullException: Value cannot be null.
Xamarin.Android.Common.targets(2342,3): error MSB4018: Parameter name: fullName
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Mono.Cecil.AssemblyNameReference.Parse(String fullName)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Manifest.ManifestDocumentElement.ResolveType(String type, ICustomAttributeProvider provider, IAssemblyResolver resolver)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Manifest.ManifestDocumentElement1.<>c.<.cctor>b__25_12(Object value, ICustomAttributeProvider p, IAssemblyResolver r, Int32 v)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Manifest.ManifestDocumentElement1.ToAttributeValue(String name, T value, ICustomAttributeProvider provider, IAssemblyResolver resolver, Int32 targetSdkVersion)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Manifest.ManifestDocumentElement1.ToAttribute(String name, T value, String packageName, ICustomAttributeProvider provider, IAssemblyResolver resolver, Int32 targetSdkVersion)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Manifest.ManifestDocumentElement1.<>c__DisplayClass8_0.<ToElement>b__1(String e)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Manifest.ManifestDocumentElement1.ToElement(T value, ICollection1 specified, String packageName, ICustomAttributeProvider provider, IAssemblyResolver resolver, Int32 targetSdkVersion)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Android.App.ApplicationAttribute.ToElement(IAssemblyResolver resolver, String packageName)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(XElement manifest, String applicationClass, List1 subclasses, List1 selectedWhitelistAssemblies)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Tasks.ManifestDocument.Merge(List1 subclasses, List1 selectedWhitelistAssemblies, String applicationClass, Boolean embed, String bundledWearApplicationName, IEnumerable1 mergedManifestDocuments)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
Xamarin.Android.Common.targets(2342,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by brendanzagaeski** [comment]
A new preview version has now been published that includes a fix for this item.

Fix included in Xamarin.Android 10.0.0.40.

Fix included on Windows in Visual Studio 2019 version 16.3 Preview 3. To try the preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 3. To try the preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
