### ISSUE TITLE
Profiled AOT without NDK

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#3299]
Right now we need Android NDK for profiled AOT. The reason is the AOT compiler uses these 3 tools from NDK: as, ld and strip.

We are already shipping as, Android SDK contains ld.

The plan is to ship ld and strip as well. Meanwhile we will try to use ld from SDK and not use strip.

**Comment by radekdoulik** [comment]
I have checked the size difference between using strip and not using it.

The difference in AOT compiled assemblies size is relatively big.
```
du -sh tests/Xamarin.Forms-Performance-Integration/Droid/obj-strip/Release/aot/
 18M	tests/Xamarin.Forms-Performance-Integration/Droid/obj-strip/Release/aot/
du -sh tests/Xamarin.Forms-Performance-Integration/Droid/obj/Release/aot/
 22M	tests/Xamarin.Forms-Performance-Integration/Droid/obj/Release/aot/
```
The difference is caused by special symbols, which are not striped.

The difference in size of resulting apk is relatively small (approx. 0.5mB):
```
ls -l aot-nostrip/
-rw-r--r--  1 rodo  staff  24532404 Jun 26 12:47 Xamarin.Forms_Performance_Integration-Signed.apk
ls -l aot-strip/
-rw-r--r--  1 rodo  staff  23995828 Jun 26 12:39 Xamarin.Forms_Performance_Integration-Signed.apk
```

**Comment by Mikilll94** [comment]
So, will it be possible to use profiled AOT without Android NDK?

**Comment by radekdoulik** [comment]
Yes. It should be implemented by https://github.com/xamarin/xamarin-android/pull/3317
