### ISSUE TITLE
[Bug] Unable to write on SD card

### ISSUE THREAD

**Issue by gitChef30** [xamarin/xamarin-android#3307]
### Description
If you try to write or simply move a file stored on SD card a `System.UnauthorizedAccessException: Access to the path is denied.` is thrown.

**I don't get exceptions:**

**- reading/writing files on the phone storage;**
**- reading files on the SD card.**

Permssions are present in the `AndroidManifest.xml` file
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
and they are given during runtime.

### Steps to Reproduce

1.  Run the attached test app.
2. Pick a file stored on SD in a physical device. The app just renames the file adding a simple string (".mp3").
3. Right after the `System.IO.File.Move(path, newpath);` statement in the ViewModel.cs file, the app throws a System.UnauthorizedAccessException.

### Expected Behavior
The file on the SD should be renamed/moved.
### Actual Behavior
A System.UnauthorizedAccessException is thrown.
### Basic Information

- Version with issue: 4.0.0.497661
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
Android: Android 9.0 (Pie)
- Affected Devices: Devices with SD card

### Reproduction Link

https://github.com/gitChef30/UnauthorizedExceptionXamarinForms

**Comment by dellis1972** [comment]
Manifest Permissions have been deprecated on never versions of Android (from Marshmallow onwards).

You probably need to reference the `Xamarih.Plugin.FilePicker` to your android project. It already has code to deal with the runtime permissions https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/src/Plugin.FilePicker/Android/FilePickerActivity.android.cs#L52. 
If you don't reference that Nuget in the Android project, you will only get the .net standard version which will not do the right thing under Android and request the permissions.

Failing that you need to explicitly request permissions at runtime. See the following blog post which will walk you through how to implement this https://devblogs.microsoft.com/xamarin/requesting-runtime-permissions-in-android-marshmallow/

I'm going to close this issue. But if none of the above works, please reopen the issue.

**Comment by gitChef30** [comment]
@dellis1972 Hi thanks for your time! 

I added the `Xamarin.Plugin.FilePicker` package to the Android project and requested permissions at runtime, but i got the same result.

**Comment by dellis1972** [comment]
@gitChef30 sorry to head that. I would have hoped that would work. 

In that case I suggest you take a look at https://devblogs.microsoft.com/xamarin/requesting-runtime-permissions-in-android-marshmallow/ and manually implement the request for permissions. 
Or perhaps raise an issue on the FilePicker repo?

**Comment by gitChef30** [comment]
@dellis1972 I don't know why I get this exception only with files stored on SD. I have no problems reading/writing files on phone storage

**Comment by dellis1972** [comment]
This might be related https://stackoverflow.com/questions/43066117/android-m-write-to-sd-card-permission-denied. It looks like sd-card needs some special code.
