### ISSUE TITLE
Missing AudioRouting interface for AudioRecord, etc, preventing solution to problem

### ISSUE THREAD

**Issue by gkarabin** [xamarin/xamarin-android#3313]
### Steps to Reproduce

In API level 24, Android changed the java [AudioRecord](https://developer.android.com/reference/android/media/AudioRecord) class to extend [AudioRouting](https://developer.android.com/reference/android/media/AudioRouting).  This is backwards compatible on the Java side, but not for the C# binding.

I noticed that [someone made notes on the problem](https://github.com/xamarin/xamarin-android/commit/576fb9814662f796cb5b0d466a7629b68c908fa9#diff-14048fd4cb6595cd0ad8cf1b41175ef5) in the Xamarin.Android repo.

As a result, if you look at the docs for Xamarin.Android's [AudioRecord](https://docs.microsoft.com/en-us/dotnet/api/android.media.audiorecord?view=xamarin-android-sdk-9) it does not implement the new interface from AudioRouting. A developer cannot access the new SDK level 24 methods:
- [addOnRoutingChangedListener](https://developer.android.com/reference/android/media/AudioRouting.html#addOnRoutingChangedListener(android.media.AudioRouting.OnRoutingChangedListener,%2520android.os.Handler))
- [removeOnRoutingChangedListener ](https://developer.android.com/reference/android/media/AudioRouting.html#removeOnRoutingChangedListener(android.media.AudioRouting.OnRoutingChangedListener))

I'm trying to resolve a customer issue, and want to provide them a solution based on non-obsolete APIs, on the belief/hope that more Android audio routing bugs are likely to be fixed on newer SDK levels.

### Expected Behavior

I can access the new SDK 24 AudioRouting APIS.

### Actual Behavior

I can't access the new SDK 24 AudioRouting APIS.

### Version Information

Visual Studio Enterprise 2019 for Mac
Version 8.1.3 (build 19)
Installation UUID: 77317fbd-d6e3-451c-b93f-33774ca9e0cf
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

Mono Framework MDK
Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

NuGet
Version: 5.0.2.5988

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.4
	2.1.9
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK Versions:
	2.2.203
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.2.1 (14490.122)
Build 10E1001

Xamarin.Mac
Version: 5.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

Xamarin.iOS
Version: 12.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

Xamarin Designer
Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

Xamarin.Android
Version: 9.3.0.23 (Visual Studio Enterprise)
Commit: HEAD/d0b48056f
Android SDK: /Users/georgekarabin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

Microsoft Mobile OpenJDK
Java SDK: /Users/georgekarabin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 801030019
Git revision: 2d04b0145da8aa946d2cc9898fe2a59484e4f3f4
Build date: 2019-06-26 15:34:25+00
Build branch: release-8.1
Xamarin extensions: de240bddd6d1f96bfb1e7d11ce7ac5398956fe1d

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

Enabled user installed extensions
NuGet Package Explorer 0.3.2
NuGet Package Management Extensions 0.19

### Log File

This problem is not device-specific.  I can give you a device log, but the problem appears before you compile code...

**Comment by gkarabin** [comment]
I tweaked the description.  The text originally read:

> As a result, if you look at the docs for Xamarin.Android's **_AudioRouting_** it does not implement the new interface from **_AudioRouting_**.


It should read:

> As a result, if you look at the docs for Xamarin.Android's **_AudioRecord_** it does not implement the new interface from **_AudioRouting_**.

**Comment by gugavaro** [comment]
https://github.com/xamarin/xamarin-android/pull/3415

**Comment by gkarabin** [comment]
Thanks all!

**Comment by brendanzagaeski** [comment]
A new Preview version has now been published that includes a fix for this item. Thank you for this report!

Fix included in Xamarin.Android 10.0.0.40.

Fix included on Windows in Visual Studio 2019 version 16.3 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
