### ISSUE TITLE
windowLightNavigationBar color delay

### ISSUE THREAD

**Issue by rickdijk** [xamarin/xamarin-android#3319]
### Steps to Reproduce

1. Create a values-v28 folder

2. Add the styles.xml:
```
      <item name="android:navigationBarColor">@android:color/white</item>
      <item name="android:windowDrawsSystemBarBackgrounds">true</item>
      <item name="android:windowLightNavigationBar">true</item>
```

3. Run the app, it works fine. Now put the app to the background and then bring it back again.

### Expected Behavior
Immediately when bringing back the app on screen, the LightNavigationBar should be visible

### Actual Behavior
Run the app, it works fine. Now when putting the app to the background and then bring it back again, the buttons in the navigationBar will be white for a second, before turning dark and visible again.

### Version Information

8.1.3 (build 19)

**Comment by jonathanpeppers** [comment]
@rickdijk I suspect this is nothing to do with Xamarin.Android, and just happens with Android in-general.

Especially if you are just changing Android xml, Xamarin.Android doesn't even come into play here? Does the problem happen with a Java app in Android Studio?

Closing for now, but let me know if you find something else here, thanks!
