### ISSUE TITLE
WebRequest.DefaultWebProxy non null on simulator

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-android#3332]
### Steps to Reproduce

1. Create a new httpclienthandler as below
2. Create a new httprequest using this client handler
3. Call any https url using this httprequest

```
        protected class HttpClientWithProxyHandler : AndroidClientHandler 
        {
            public HttpClientWithProxyHandler(bool autoFollowRedirects = true)
            {
                CookieContainer = new CookieContainer();
                UseCookies = true;
                UseDefaultCredentials = false;
                AllowAutoRedirect = autoFollowRedirects;
                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;

                //Try to get proxy to work
                var proxy = WebRequest.DefaultWebProxy;
                if(proxy != null)
                {
                    Proxy = proxy;
                    UseProxy = true;
                }

                ConnectTimeout = TimeSpan.FromSeconds(8);
            }
        }
```

### Expected Behavior
Succeeds, as "before" (ie: in previous xamarin android versions)

### Actual Behavior
Always fails with "connection reset" exception

### Version Information
[vsversion.txt](https://github.com/xamarin/xamarin-android/files/3365517/vsversion.txt)

### More infos
Debugging shows that DefaultWebProxy is non null, even if no proxy is configured on Android.
Testing on Android simulator API 25 (android 7.1.1) / 64bits.

**Comment by brendanzagaeski** [comment]
Thanks for the report! I was able to reproduce the change in behavior between versions.

It looks like the behavior of `WebRequest.DefaultWebProxy` itself has stayed the same across the different versions, but https://github.com/xamarin/xamarin-android/commit/bf0704496ac5cd5df5c82822048fe07ac6923971 changed the behavior of `AndroidClientHandler`. It added support to use proxies with `AndroidClientHandler`.

Test case: [AndroidClientHandlerDefaultProxy.zip](https://github.com/xamarin/xamarin-android/files/3370788/AndroidClientHandlerDefaultProxy.zip)

### Behavior with Xamarin.Android SDK version 9.4.0.50 (xamarin-android/d16-2@c308421)

  * The HTTPS request fails after approximately 100 seconds with the `System.OperationCanceledException`.
  * `WebRequest.DefaultWebProxy` is a `Android.Runtime.AndroidEnvironment._Proxy`

### Behavior with Xamarin.Android SDK version 9.2.3.0 (monodroid@9f6426a)

  * The HTTPS request fails after approximately 100 seconds with the `System.OperationCanceledException`.
  * `WebRequest.DefaultWebProxy` is a `Android.Runtime.AndroidEnvironment._Proxy`

### Behavior with Xamarin.Android SDK [xamarin-android-freestyle/1256 Jenkins build](https://jenkins.xamarin.com/view/Xamarin.Android/job/xamarin-android-freestyle/1256/) (xamarin-android/master@bf07044)

  * The HTTPS request fails after approximately 100 seconds with:

    ```
    System.OperationCanceledException: The operation was canceled.
      at System.Threading.CancellationToken.ThrowOperationCanceledException () [0x00015] in <58604b4522f748968296166e317b04b4>:0 
      at System.Threading.CancellationToken.ThrowIfCancellationRequested () [0x00008] in <58604b4522f748968296166e317b04b4>:0 
      at Xamarin.Android.Net.AndroidClientHandler+<>c__DisplayClass44_0.<ConnectAsync>b__0 () [0x0004f] in <788a34f7a7b84486905dfde786529d42>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <58604b4522f748968296166e317b04b4>:0 
      at System.Threading.Tasks.Task.Execute () [0x00000] in <58604b4522f748968296166e317b04b4>:0 
    --- End of stack trace from previous location where exception was thrown ---

      at Xamarin.Android.Net.AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState) [0x0012e] in <788a34f7a7b84486905dfde786529d42>:0 
      at Xamarin.Android.Net.AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x002be] in <788a34f7a7b84486905dfde786529d42>:0 
      at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <faf48d3665ec41a489ef407cec7499b0>:0 
      at AndroidApp1.MainActivity.FabOnClick (System.Object sender, System.EventArgs eventArgs) [0x00081] in C:\Temp Files\AndroidApp1\AndroidApp1\MainActivity.cs:53 
    ```

  * `WebRequest.DefaultWebProxy` is a `Android.Runtime.AndroidEnvironment._Proxy`

### Behavior with Xamarin.Android SDK [xamarin-android-freestyle/1255 Jenkins build](https://jenkins.xamarin.com/view/Xamarin.Android/job/xamarin-android-freestyle/1256/) (xamarin-android/master@6a48423)

  * The HTTPS request completes successfully.
  * `WebRequest.DefaultWebProxy` is a `Android.Runtime.AndroidEnvironment._Proxy`

### Behavior with Xamarin.Android SDK version 9.1.8.0 (monodroid@9bf5bd5)

  * The HTTPS request completes successfully.
  * `WebRequest.DefaultWebProxy` is a `Android.Runtime.AndroidEnvironment._Proxy`

**Comment by softlion** [comment]
Well, something is strange here: the AndroidClientHandler's proxy was working fine using my original code. So why a PR was needed ?

**Comment by grendello** [comment]
@softlion the change was required because managed proxy settings were not reflected on the native client - and thus the proxy didn't work as expected. @brendanzagaeski `WebRequest.DefaultWebProxy` will never be null, I think. However, what the commit you indicated changed is a check whether the proxy is configured/enabled for the [specific URL](https://github.com/xamarin/xamarin-android/blob/08e0ccb4a52886859c3290a20f2680d39a773478/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L304). If `Proxy.GetProxy` returns `null`, we configure the request to not use the proxy at all. The error you got above is a timeout - which may be because the proxy wasn't configured for the URL you specified and the request is direct.

Frankly, I don't see any bug here, despite the fact that the orignal code from @softlion worked and now it fails. I know it looks like a bug from your point of view, @softlion, but the fix in the [indicated commit](https://github.com/xamarin/xamarin-android/commit/bf0704496ac5cd5df5c82822048fe07ac6923971) is also a correct change. Our behavior "before" wasn't correct, it is correct now, but it might have broken your code which relied on the broken behavior of ours. This twisted logic would mean that there's no bug here. Or maybe I just don't understand the issue (which is entirely possible).

**Comment by softlion** [comment]
>  because managed proxy settings were not reflected on the native client 
You are right, they were not reflected. Thus my "fix" :)

**Comment by grendello** [comment]
@softlion I think the mystery lies in what  `WebRequest.DefaultWebProxy` really is. I'll have to investigate what gets returned.

**Comment by softlion** [comment]
> Btw you are right that removing my "fix" does fix the problem. But i don't see why leaving my "fix" creates a new problem!

Well no, on device the proxy set on the wifi is ignored if this code is removed.  
So it's not working as expected at all.

**Comment by softlion** [comment]
Hi all,
i undig this one.

We are in 2020 and the default HttpClient behavior is still incorrect.
I see it at all my customer's places.

The default behavior of HttpClient MUST respect the system proxy setup on the mobile phone's connection by default.

We are in 2020 and it's still ignoring it by default. Just tested on Android.

**Comment by Safeer-Ahmad** [comment]
Hi @softlion I'm facing a similar issue https://github.com/xamarin/xamarin-android/issues/6795
Do we have any workaround to this? My client has proxy setup using PAC file but looks like all my requests are going direct and not using proxy.

**Comment by softlion** [comment]
Yes you have to set a proxy object. Create your own and bypass local addresses.

**Comment by Safeer-Ahmad** [comment]
My proxy info is coming from a PAC file so can't really specify the address. I thought the below code should read global web proxy??

var handler = new HttpClientHandler();
handler.Proxy = WebRequest.GetSystemWebProxy();
handler.UseProxy = true;
httpClient = new HttpClient(handler)
{
BaseAddress = new Uri("")
};

**Comment by softlion** [comment]
It should. Is it not working ? The try WebRequest.DefaultWebProxy instead of WebRequest.GetSystemWebProxy()

**Comment by Safeer-Ahmad** [comment]
It worked, thanks.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
