### ISSUE TITLE
[Bug] Problem enabling Use Fast Development

### ISSUE THREAD

**Issue by AlenToma** [xamarin/xamarin-android#3335]
### Description
cant emulate my android project when enabling `Use Fast Development`.

### Steps to Reproduce

1. Enable `Use Fast Development`
2. Rebuild
3. Run on my samsung s9 edge

### Expected Behavior
the app should start on the mobile
### Actual Behavior
the app start and then shutdown directly without any errors.
as for visual studio, the emulator stop
### Basic Information

- Version with issue: 4.1.0.555618
- Last known good version: hmm dont remember really, i think 4.0.0.425677
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: samsung s9 edge

**Comment by brendanzagaeski** [comment]
Thanks for the report! It looks like the team will need some additional information to investigate what's happening with fast deployment in your project. As a starting place, if you could collect and attach back the diagnostic MSBuild output and the `adb logcat` log, that would be perfect:

1. Set **Tools > Options > Project and Solutions \[section\] > Build and Run \[subsection\] > MSBuild project build output verbosity** to **Diagnostic**.
2. Open **Tools > Android > Android Adb Command Prompt**.
3. Run the following command to clear the log on the device:

    ```cmd
    adb logcat -c
    ```
4. Build and deploy the app to the device in the problematic configuration where it exists during launch.
5. Run the following command in the **Android Adb Command Prompt** to collect the log from the device:

    ```
    adb logcat -d > "%USERPROFILE%\Desktop\adblogcat.txt"
    ```
6. Open the **View > Output** window, and set **Show output from** to **Build Order**.
7. Make sure the **Output** window is selected, and then choose **File > Save Output As** to save the contents to a text file. Or copy and paste the build output into a text file.
8. Attach back the *adblogcat.txt* file from step 4 and the saved diagnostic build output file from step 6.

Thanks in advance!

**Comment by AlenToma** [comment]
Sorry. I hade some problem and the project `Android.csproj` got corrupted, before i could extract the logg you requested. I created a new `Android.csproj` file and the problem disappeared. 

dont know if you should close this issue or not ?

**Comment by brendanzagaeski** [comment]
Thanks for the update, and glad to hear you've got it working at the moment! I will close this issue for now, but feel free to comment back on this issue or create a [new issue](https://github.com/xamarin/xamarin-android/issues/new) if a similar problem surfaces again in the future.
