### ISSUE TITLE
In projects configured to use AAPT2, invalid Android resource elements added after an initial successful design-time build do not produce errors during subsequent incremental builds

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#3336]
### Steps to reproduce

1. Create a new **Android App (Xamarin) > Single View App** project.
2. Add a new XML file `Resources\values\ids.xml` that has an intentionally invalid element:
    ```xml
    <?xml version="1.0" encoding="utf-8" ?>
    <resources>
      <item/>
    </resources>
    ```
3. **Build > Build Solution**. If this build fails with no error due to <https://github.com/xamarin/xamarin-android/issues/2427>, then repeat the build again. If the build succeeds, then you can stop at this step. If the build instead fails correctly with the expected `APT0000` error, then complete the additional steps 4–7 to see the problem.
4. Exclude `ids.xml` from the solution by highlighting the file in the Solution Explorer and then selecting **Project > Exclude From Project**.
5. **Build > Build Solution**. (Note: This build might fail with no error on the first attempt due to <https://github.com/xamarin/xamarin-android/issues/2427>. If so, repeat the build again until it succeeds.)
6. Re-include `ids.xml` into the project.
7. **Build > Build Solution**. (Again, repeat the build if needed to work around <https://github.com/xamarin/xamarin-android/issues/2427>.)

If it's more convenient, you can also use command line builds to reproduce the issue:

<details>

1. After creating the project and adding the `ids.xml` file, delete the `.vs` directory, the `obj` and `bin` directories, and the `Resources\Resource.designer.cs` file. Then build the project on the command line:
    
    ```cmd
    msbuild -restore .\AndroidApp1.sln
    ```

2. Edit the `.csproj` file in a text editor to remove the `<AndroidResource Include="Resources\values\ids.xml" />` item.
3. Build the solution again.
4. Edit the `.csproj` file to add back the `ids.xml` item.
5. Build the solution again.

</details>

### Expected behavior

The build should fail at both step 3 and step 7 with the following error:

```
1>C:\Temp\AndroidApp1\AndroidApp1\Resources\values\ids.xml(2): error APT0000: <item> must have a 'type' attribute.
1>C:\Temp\AndroidApp1\AndroidApp1\Resources\values\ids.xml : error APT0000: file failed to compile.
```

Rebuilding the solution with **Build > Rebuild Solution** after either step 3 or step 7 produces this correct result.

Setting `$(AndroidUseAapt2)` to `false` also leads to the correct result.

### Actual behavior

The build succeeds.

Out of curiosity, I tried a quick experiment where I set `$(AndroidUseManagedDesignTimeResourceGenerator)` to `false` and repeated the steps. That did *not* change this particular behavior.

### Version information

Xamarin.Android SDK   9.4.0.34 (d16-2/7cce305)

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.2.0 Preview 4.0 \[29027.242.d16.2stg\]
VisualStudio.16.IntPreview/16.2.0-pre.4.0+29027.242.d16.2stg
Microsoft .NET Framework
Version 4.8.03752

### Log file

[MSBuildBinlogs.zip](https://github.com/xamarin/xamarin-android/files/3371176/MSBuildBinlogs.zip)

**Comment by jonathanpeppers** [comment]
Ugh, I could only repro this in a test with 3 steps...

```csharp
[Test]
public void InvalidAndroidResource ([Values (true, false)] bool useAapt2)
{
	var invalidXml = new AndroidItem.AndroidResource (@"Resources\values\ids.xml") {
		TextContent = () => "<?xml version=\"1.0\" encoding=\"utf-8\" ?><resources><item/></resources>"
	};

	var proj = new XamarinAndroidApplicationProject ();
	proj.SetProperty ("AndroidUseAapt2", useAapt2.ToString ());
	using (var b = CreateApkBuilder (Path.Combine ("temp", TestName))) {
		b.ThrowOnBuildFailure = false;

		proj.OtherBuildItems.Add (invalidXml);
		Assert.IsFalse (b.Build (proj), "Build should *not* have succeeded.");

		proj.OtherBuildItems.Remove (invalidXml);
		Assert.IsTrue (b.Build (proj), "Build should have succeeded.");

		proj.OtherBuildItems.Add (invalidXml);
		Assert.IsFalse (b.Build (proj), "Build should *not* have succeeded.");
	}
}
```
aapt1 works, and I had to specifically do things in this order to see the problem...

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
