### ISSUE TITLE
CookieManager RemoveAllCookie() not working

### ISSUE THREAD

**Issue by robiharid** [xamarin/xamarin-android#3338]
_###_ Steps to Reproduce

1. CookieManager.Instance.RemoveAllCookie();
2.  CookieManager.Instance.hasCookies() is false;
3.  No cookies are removed from the browser 

Using MSAL.

`CookieManager.Instance.RemoveAllCookies(null);
            CookieManager.Instance.RemoveAllCookie();
            CookieManager.Instance.RemoveSessionCookie();
            CookieManager.Instance.Flush();`
### Expected Behavior
Cookies removed from browser and user has to revalidate credentials
### Actual Behavior
Credentials are cached and the user does not have to reenter the password.

**Comment by robiharid** [comment]
Fixed.

Switching from Chrome Custom Tabs to Embedded (WebView?) allows you to manage cookies through CookieManager.

```App.UiParent = new UIParent(Xamarin.Forms.Forms.Context as Activity, true);```

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#choosing-between-embedded-web-browser-or-system-browser-on-xamarinandroid

**Comment by gugavaro** [comment]
@robiharid both removeAllCookie removeAllCookies are abstract, so would be interesting to know what is the type you are using so we could know if there is a proper implementation of it on the class.
CookieManager.Instance.GetType() would give us that.
I see you found a workaround.
I will close the bug for now but please re-open if you think it needs further investigation.

thanks!
