### ISSUE TITLE
Automatic main dex list is not supported when compiling for Android O and later (--min-api 26)

### ISSUE THREAD

**Issue by jrahma** [xamarin/xamarin-android#3345]
Hi,

I have added:

`<AndroidDexTool>d8</AndroidDexTool>
`
to my project file PropertyGroup and now I am getting this error:

> Automatic main dex list is not supported when compiling for Android O and later (--min-api 26)

but my Minimum Version is 8.1 (API 27)

my Target Version is 9.0 (API 28)

and this is my AndroidManifest.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="100" android:versionName="1.0" package="com.jafaria.app" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="27" android:targetSdkVersion="28" />
	<application android:label="الأوقاف الجعفرية" android:icon="@drawable/icon" android:supportsRtl="true" android:largeHeap="true">
		<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_notification" />
    <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id" />
    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="com.jafaria.app" />
			</intent-filter>
		</receiver>
	</application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
	<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.MEDIA_CONTENT_CONTROL" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
</manifest>

```

Kindly help...

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jrahma** [comment]
Guys, any workaround for this?

**Comment by jonathanpeppers** [comment]
@jrahma I am curious how you are hitting this, what version of Xamarin.Android are you using? Are you using a different r8.jar than the one we ship?

I hit this error when I updated r8, and had to make changes in Xamarin.Android: https://github.com/xamarin/xamarin-android/pull/3121

This change will be in Visual Studio 2019 16.3, which is not released yet.

**Comment by jrahma** [comment]
I am getting this when adding:

<AndroidDexTool>d8</AndroidDexTool> 

manually or via Android-Properties then change the Dex Compiler to d8

**This is my info:**

> Microsoft Visual Studio Community 2019
> Version 16.1.6
> VisualStudio.16.Release/16.1.6+29102.190
> Microsoft .NET Framework
> Version 4.8.03752
> 
> Installed Version: Community
> 
> Visual C++ 2019   00435-60000-00000-AA233
> Microsoft Visual C++ 2019
> 
> ADL Tools Service Provider   1.0
> This package contains services used by Data Lake tools
> 
> Application Insights Tools for Visual Studio Package   9.1.00429.1
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2019   16.1.429.50124
> ASP.NET and Web Tools 2019
> 
> ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   16.1.429.50124
> Azure App Service Tools v3.0.0
> 
> Azure Data Lake Node   1.0
> This package contains the Data Lake integration nodes for Server Explorer.
> 
> Azure Data Lake Tools for Visual Studio   2.3.9000.0
> Microsoft Azure Data Lake Tools for Visual Studio
> 
> Azure Functions and Web Jobs Tools   16.1.429.50124
> Azure Functions and Web Jobs Tools
> 
> Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
> Microsoft Azure Stream Analytics Tools for Visual Studio
> 
> C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Extensibility Message Bus   1.1.77 (master@24013d5)
> Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
> 
> Fabric.DiagnosticEvents   1.0
> Fabric Diagnostic Events
> 
> IntelliCode Extension   1.0
> IntelliCode Visual Studio Extension Detailed Info
> 
> Microsoft Azure HDInsight Azure Node   2.3.9000.0
> HDInsight Node under Azure Node
> 
> Microsoft Azure Hive Query Language Service   2.3.9000.0
> Language service for Hive query
> 
> Microsoft Azure Service Fabric Tools for Visual Studio   2.5
> Microsoft Azure Service Fabric Tools for Visual Studio
> 
> Microsoft Azure Stream Analytics Language Service   2.3.9000.0
> Language service for Azure Stream Analytics
> 
> Microsoft Azure Stream Analytics Node   1.0
> Azure Stream Analytics Node under Azure Node
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2
> 
> Microsoft Continuous Delivery Tools for Visual Studio   0.4
> Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft Library Manager   1.0
> Install client-side libraries easily to any web project
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards   1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio Tools for Containers   1.1
> Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> Mono Debugging for Visual Studio   16.1.1 (2473f22)
> Support for debugging Mono processes with Visual Studio.
> 
> Node.js Tools   1.5.10424.1 Commit Hash:c3ce0ae0b29c0b3a755ffc12f8a685fe7ddd3600
> Adds support for developing and debugging Node.js apps in Visual Studio
> 
> NuGet Package Manager   5.1.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> ResourcePackage Extension   1.0
> ResourcePackage Visual Studio Extension Detailed Info
> 
> ResourcePackage Extension   1.0
> ResourcePackage Visual Studio Extension Detailed Info
> 
> SQL Server Data Tools   16.0.61904.23160
> Microsoft SQL Server Data Tools
> 
> Syncfusion ASP.NET Core (Essential JS 1) Project Templates   17.1.0.38
> Provides project templates for creating an ASP.NET Core Web Application using Syncfusion Essential JS 1 components.
> 
> Syncfusion Reference Manager   17.1.0.38
> A useful add-in for adding and migrating Syncfusion Assembly References for Windows Forms, WPF, and Silverlight projects.
> 
> Syncfusion UWP Project Templates   17.1.0.38
> Project to create an Universal Windows Application using Syncfusion Products.
> 
> Syncfusion Web Conversion and Migration   17.1.0.38
> Converts and migrates a web project into a Syncfusion web project.
> 
> Syncfusion.WindowsForms.Package   17.1.0.38
> Provides Item/Project Templates to add Syncfusion Windows Forms Item/Project along with corresponding configurations.
> 
> SyncfusionMenu Extension   1.0
> SyncfusionMenu Visual Studio Extension Detailed Info
> 
> SyncfusionXamarinMenu Extension   1.0
> SyncfusionXamarinMenu Visual Studio Extension Detailed Info
> 
> ToolWindowHostedEditor   1.0
> Hosting json editor into a tool window
> 
> TypeScript Tools   16.0.10506.2004
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
> Microsoft Visual F# Tools 10.4 for F# 4.6
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Tools for Containers   1.0
> Visual Studio Tools for Containers
> 
> Visual Studio Tools for Kubernetes   1.0
> Visual Studio Tools for Kubernetes
> 
> VisualStudio.Mac   1.0
> Mac Extension for Visual Studio
> 
> Xamarin   16.1.0.545 (d16-1@db7c858e8)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
> Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
> 
> Xamarin Templates   16.2.112 (4db4af4)
> Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
> 
> Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
> Xamarin.Android Reference Assemblies and MSBuild support.
>     Mono: mono/mono/2018-08@3a07bd426d3
>     Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
>     LibZipSharp: grendello/LibZipSharp/d16-1@44de300
>     LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
>     ProGuard: xamarin/proguard/master@905836d
>     SQLite: xamarin/sqlite/3.27.1@8212a2d
>     Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26
> 
> 
> Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
> 
>

**Comment by jrahma** [comment]
I also get the same error if I set to r8

![Android](https://user-images.githubusercontent.com/6236241/61224829-581bda80-a730-11e9-8f61-94691ea6fab5.png)

**Comment by jonathanpeppers** [comment]
@jrahma if you change your `minSdkVersion` in your `AndroidManifest.xml` to `25` does the problem go away?

**Comment by jrahma** [comment]
Changing to 25 throws:

> Compilation can't be completed because some library classes are missing.

**Comment by jonathanpeppers** [comment]
So this doesn't have the info we need:

**Comment by jonathanpeppers** [comment]
Can you post diagnostic build logs? https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output

This should actually say which library is missing if you have the full log:

> Compilation can't be completed because some library classes are missing.

**Comment by jrahma** [comment]
@jonathanpeppers attached are two logs:

1. BuildLog_code_shrinker_r8
2. BuildLog_dex_compiler_d8

[BuildLog.zip](https://github.com/xamarin/xamarin-android/files/3393259/BuildLog.zip)

**Comment by jonathanpeppers** [comment]
It mentions:
```
R8 : warning : Missing class: org.apache.http.client.methods.HttpEntityEnclosingRequestBase
```
Did you include this in your manifest?
```xml
  <uses-library android:name="org.apache.http.legacy" android:required="false" />
</application>
```
This is required if you depend on a Java library using these APIs that were deprecated in Android Oreo.

There are more details about this here: https://github.com/xamarin/xamarin-android/commit/b08240ee50e941cb326688cc0dcf5969ebfe5473

**Comment by jrahma** [comment]
(No), I don't have the org.apache.http.legacy

How will I know which API is this which is deprecated?

I am just using the normal packages in my app as you can see in the attached.



[Jafaria.Android.zip](https://github.com/xamarin/xamarin-android/files/3394396/Jafaria.Android.zip)

**Comment by jonathanpeppers** [comment]
It looks like your project uses Google Play Services (aka Google Maps), which uses these org.apache.http.* APIs.

Details at the bottom of the docs here: https://developers.google.com/maps/documentation/android-sdk/config

**Comment by jrahma** [comment]
Yes @jonathanpeppers 

1. I am able to enable the d8 now in my Android project and able to build using Debug and Deploy to my connected device.
2. I am not NOT able to enable r8
3. I am not able to build using Release and it throws error:

> java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)V

although my android:minSdkVersion="28"

**Comment by jonathanpeppers** [comment]
So the error you are getting with r8:
```
error : java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)V
```
This means you cannot use ExoPlayer unless your `minSdkVersion` is 24 or greater.

@jrahma some other advice here:

* If you are using a `Code Shrinker`, either ProGuard or r8, then don't use multi-dex.
* Code Shrinker is for Release builds only -- they slow down your build, but produce a smaller APK.
* You may need to add some ProGuard rules yourself to use ProGuard or r8, I don't see any in this build log yet? Jon Douglas has a good post explaining ProGuard rules here (it was written before we had r8 support, but still valid): https://www.jon-douglas.com/2016/11/22/xamarin-android-proguard/
* Debug builds should use multi-dex if your app doesn't build without it. You would get an error that says "java exited with code N", the build log will say "too many fields" or "too many methods".

I am going to write a blog post on this subject, but my talk at Xamarin Dev Summit might also be helpful: https://youtu.be/YJ8TiRCsLl4?t=5939

**Comment by jrahma** [comment]
> So the error you are getting with r8:
> 
> ```
> error : java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)V
> ```
> 
> This means you cannot use ExoPlayer unless your `minSdkVersion` is 24 or greater.
> 

but my minSdkVersion is already 28 which is greater than 24

**Comment by jonathanpeppers** [comment]
When I read this log again, it isn't even using r8? The error message is coming from dx.jar?

**Comment by jrahma** [comment]
Yes I removed the r8 because of the error so i'll keep it with multi-dex

**the above error is coming when building using Release with d8**

**Comment by jrahma** [comment]
1. I am able to build the app using Release... It was missing the d8 in the Release. Thank you
2. The r8 is not working in Release. I am able to build the app but getting the following error during Archiving:

> The preprocessor token 'rootnamespace' has been given more than one value. Choosing 'Jafaria.Droid' as the value.
> The preprocessor token 'assemblyname' has been given more than one value. Choosing 'Jafaria.Android' as the value.
> The preprocessor token 'fullpath' has been given more than one value. Choosing 'C:\Users\jrahm\Source\Repos\Jafaria\Jafaria\Jafaria.Android' as the value.
> The preprocessor token 'outputfilename' has been given more than one value. Choosing 'Jafaria.Android.dll' as the value.
> The preprocessor token 'filename' has been given more than one value. Choosing 'Jafaria.Android.csproj' as the value.
> Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> MSB4094: "obj\Release\90\Jafaria.Android.dll;obj\Release\90\Jafaria.Android.dll" is an invalid value for the "OutputAssembly" parameter of the "Csc" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem".
> Done building project "Jafaria.Android.csproj" -- FAILED.
> 
> 
>

**Comment by jonathanpeppers** [comment]
Do you have the full build log of the latest error?

It looks like there is somehow a typo in your `.csproj` file?

**Comment by jrahma** [comment]
I am not editing the csproj manually.. All I am doing is selecting the r8 from the Android property in my project.

Attached is the build log

[BuildLog-2.zip](https://github.com/xamarin/xamarin-android/files/3399050/BuildLog-2.zip)

**Comment by jonathanpeppers** [comment]
These logs are successful:
```
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.47
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by jrahma** [comment]
My problem is solved now. I just deleted all unnecessary spaces in the csproj file and deleted bin and ob then restarted Visual Studio and it's now fine for both d8 and r8

Thank you so much @jonathanpeppers
