### ISSUE TITLE
[Designer] Designer crashed when inflating the layout.

### ISSUE THREAD

**Issue by SanthiyaArulsamy** [xamarin/xamarin-android#3349]
I am getting the below exception when trying to drag and drop the custom library.

android.runtime.JavaProxyThrowable: System.NotSupportedException: Could not activate JNI Handle

### Version Information

It works in VS 2017 and the exception from VS 2019.

**Comment by jpobst** [comment]
If this is still an issue:

This issue likely occurs in the Android Designer, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
