### ISSUE TITLE
Disabling multi-dex throws "java.exe" exited with code 2

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/xamarin-android#3351]
In the recent Developer Summit, it was recommended that we turn off multi-dex. When I do that, I'm getting `"java.exe" exited with code 2`. This is all for a Xamarin.Forms project with version 4. I observed that using d8 & r8 while multi-dex is turned off fixes the problem. I'm building on Windows.

@jonathanpeppers 

- Just to clarify, should d8 & r8 be turned on in debug and release or just one environment? 
- Also, I saw that a brand new XF project does not explicitly specify d8 & r8 but disabling multi-dex works. So it looks like I lack some config somewhere. My project was created a year ago.

**Comment by jonathanpeppers** [comment]
You have to be using the preview 16.2 on Windows or 8.2 on Mac to get that improvement.

If you can post the full error message, hopefully it says “too many fields”.  That is what we fixed.

It is still possible that you could have so many java libraries in your app that you still need it.

**Comment by adrianknight89** [comment]
Where is the full message output? I don't see any other information in the `Error List` window. I'm on 16.1.5. As I said before, creating a new XF project defaults to no multi-dex and I can compile it fine.

**Comment by jonathanpeppers** [comment]
You won't be able to see the improvement we made with 16.1, this PR is only in 16.2: https://github.com/xamarin/xamarin-android/pull/2896

The build log should say something like this:
```
trouble writing output: Too many field references: 78376; max is 65536.
You may try using --multi-dex option.
References by package:
     3 android.accounts
    30 android.app
     1 android.content
    37 android.content.pm
    10 android.content.res
     3 android.database
    46 android.graphics
     1 android.graphics.drawable
     2 android.media
     1 android.media.browse
     2 android.net
    25 android.os
     3 android.print
     1 android.provider
     8 android.runtime
     1 android.support.annotation
  2656 android.support.compat
  2656 android.support.coreui
  2656 android.support.coreutils
  2760 android.support.customtabs
  2656 android.support.design
   107 android.support.design.internal
   700 android.support.design.widget
  2656 android.support.fragment
  2815 android.support.graphics.drawable
  2656 android.support.graphics.drawable.animated
  2656 android.support.mediacompat
  2835 android.support.transition
  2656 android.support.v4
    13 android.support.v4.accessibilityservice
    17 android.support.v4.animation
   885 android.support.v4.app
   114 android.support.v4.content
     1 android.support.v4.content.pm
     1 android.support.v4.content.res
    11 android.support.v4.graphics
    41 android.support.v4.graphics.drawable
     4 android.support.v4.hardware.display
    12 android.support.v4.hardware.fingerprint
    10 android.support.v4.internal.view
   388 android.support.v4.media
   379 android.support.v4.media.session
    10 android.support.v4.net
    19 android.support.v4.os
    63 android.support.v4.print
    10 android.support.v4.provider
    55 android.support.v4.text
     6 android.support.v4.text.util
   118 android.support.v4.util
   434 android.support.v4.view
   138 android.support.v4.view.accessibility
     8 android.support.v4.view.animation
   495 android.support.v4.widget
   605 android.support.v7.app
  2656 android.support.v7.appcompat
  2656 android.support.v7.cardview
...
```
You might need to increase the MSBuild output verbosity: https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output

But I think it still prints this information on Normal -- let me know if it's not doing that for you.

**Comment by adrianknight89** [comment]
Changing verbosity did the trick:

```
C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -Dfile.encoding=UTF8 -Xmx1G -jar "C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\\lib\dx.jar" --dex --no-strict --input-list=C:\Users\xyz\AppData\Local\Temp\tmp9C5.tmp --output obj\Debug\90\android\bin  (TaskId:365)
2>   (TaskId:365)
2>  trouble writing output: Too many field references to fit in one dex file: 80614; max is 65536. (TaskId:365)
2>  You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large. (TaskId:365)
```
