### ISSUE TITLE
Device Orientation from Android Options

### ISSUE THREAD

**Issue by gugavaro** [xamarin/xamarin-android#3384]
_From @jrahma on Tue, 23 Jul 2019 20:53:13 GMT_

Hi,

Please provide Device Orientation from the Android Options screen just like the Xamarin iOS so developer will select the supported orientation instead of writing it in the MainActivity

Thanks,
Jassim

_Copied from original issue xamarin/XamarinVS#10761_

> VS bug [#952105](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/952105), VS bug [#952345](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/952345)

**Comment by jpobst** [comment]
This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
