### ISSUE TITLE
Unable to get provider com.google.firebase.provider.FirebaseInitProvider

### ISSUE THREAD

**Issue by jrahma** [xamarin/xamarin-android#3391]
Hi,

Why I started getting this error since I updated to Visual Studio 16.2?

I am not getting anything logged in AppCenter but attached is what I got from Google Play Console for different devices

Thanks,
[Jassim](https://www.softnames.com
[google log.zip](https://github.com/xamarin/xamarin-android/files/3433710/google.log.zip)
)

**Comment by jonathanpeppers** [comment]
@jrahma can you give more detail? Which error message should we be looking at here?

**Comment by jrahma** [comment]
Please see the attached from Android Device Monitor and you can see the same error

My app crashes immediately when apk from Release mode but works perfectly when using Debug mode 

I opened [this case](https://github.com/xamarin/xamarin-android/issues/3413) too so maybe you can merge both


[log.txt](https://github.com/xamarin/xamarin-android/files/3448294/log.txt)

**Comment by jonathanpeppers** [comment]
Do you need a [proguard rule](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows#customizing-proguard) for this type?
```
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path
```

**Comment by jrahma** [comment]
I am not using proguard, do I need to use it?

![AndroidSetup](https://user-images.githubusercontent.com/6236241/62155735-b7760f00-b31a-11e9-83f3-769a3f608bc5.png)

**Comment by jonathanpeppers** [comment]
`Code Shrinker = r8` uses proguard rules, stripping Java code, r8 is _mostly_ backwards compatible with proguard.

**Comment by jrahma** [comment]
@jonathanpeppers do I need to add all the below from [Microsoft](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows#customizing-proguard) website including this line? 

`-keep class com.google.firebase.provider.FirebaseInitProvider`


From [Microsoft](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows#customizing-proguard):

```
# This is Xamarin-specific (and enhanced) configuration.

-dontobfuscate

-keep class com.google.firebase.provider.FirebaseInitProvider
-keep class mono.MonoRuntimeProvider { *; <init>(...); }
-keep class mono.MonoPackageManager { *; <init>(...); }
-keep class mono.MonoPackageManager_Resources { *; <init>(...); }
-keep class mono.android.** { *; <init>(...); }
-keep class mono.java.** { *; <init>(...); }
-keep class mono.javax.** { *; <init>(...); }
-keep class opentk.platform.android.AndroidGameView { *; <init>(...); }
-keep class opentk.GameViewBase { *; <init>(...); }
-keep class opentk_1_0.platform.android.AndroidGameView { *; <init>(...); }
-keep class opentk_1_0.GameViewBase { *; <init>(...); }

-keep class android.runtime.** { <init>(***); }
-keep class assembly_mono_android.android.runtime.** { <init>(***); }
# hash for android.runtime and assembly_mono_android.android.runtime.
-keep class md52ce486a14f4bcd95899665e9d932190b.** { *; <init>(...); }
-keepclassmembers class md52ce486a14f4bcd95899665e9d932190b.** { *; <init>(...); }

# Android's template misses fluent setters...
-keepclassmembers class * extends android.view.View {
   *** set*(***);
}

# also misses those inflated custom layout stuff from xml...
-keepclassmembers class * extends android.view.View {
   <init>(android.content.Context,android.util.AttributeSet);
   <init>(android.content.Context,android.util.AttributeSet,int);
}

```

**Comment by jonathanpeppers** [comment]
I usually only put rules in my apps when I a hit a crash, so I would start with:

```
-keep class com.google.firebase.provider.FirebaseInitProvider
```
Here is a good blog post to learn about proguard rules: https://www.jon-douglas.com/2016/11/22/xamarin-android-proguard/

If you don't want to go through this, you can probably set `Code Shrinker` to `None` for now.

**Comment by jrahma** [comment]
I had to get rid of the r8 just to get it up and running which is sad decision but at least it's working now

Thanks @jonathanpeppers

**Comment by Adlorem** [comment]
I kept r8 to keep low size of my production app and included this line in my proguard.cfg. Worked for me.

-keep class com.google.firebase.provider.FirebaseInitProvider

**Comment by jonathanpeppers** [comment]
Yes @Adlorem that sounds right, my guess here is that more proguard rules were needed.

@jrahma I think we can actually close this, as I don't think there was a problem in Xamarin.Android here, let me know, thanks!

**Comment by l3ender** [comment]
Related: https://forums.xamarin.com/discussion/176104/.
