### ISSUE TITLE
Link assemblies works, but compression doesn't

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-android#3399]
### Steps to Reproduce

1. Uncompressed this project: https://drive.google.com/open?id=1ka2iNlzrD57aD_3K8Yt7hzfyPlCQNOj0
2. Choose any compression **r8** or **proguard** (_there's already r8 chosen_).
3. Run the application.

### Expected Behavior

To run.

### Actual Behavior
Crashes.

I get this error:

<img width="499" alt="Screen Shot 2019-07-29 at 19 45 37" src="https://user-images.githubusercontent.com/1666156/62069838-778b2b00-b239-11e9-9d3d-982b744a61a7.png">

Configuration:

<img width="730" alt="Screen Shot 2019-07-29 at 19 47 49" src="https://user-images.githubusercontent.com/1666156/62069956-c3d66b00-b239-11e9-9b8d-6da5246b0640.png">

<img width="960" alt="Screen Shot 2019-07-29 at 19 41 32" src="https://user-images.githubusercontent.com/1666156/62069965-c8028880-b239-11e9-889c-9a468264d358.png">

**If you choose no compression then it works properly.**

### Version Information

> Visual Studio Community 2019 for Mac
> Version 8.2 (build 1105)
> Installation UUID: fbf7c291-8ea2-41dd-916a-6882576d42d1
> 	GTK+ 2.24.23 (Raleigh theme)
> 	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)
> 
> 	Package version: 600000311
> 
> Mono Framework MDK
> Runtime:
> 	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
> 	Package version: 600000311
> 
> NuGet
> Version: 5.1.0.6013
> 
> .NET Core
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	2.1.12
> 	2.1.11
> 	2.1.9
> 	2.1.8
> 	2.1.7
> 	2.1.6
> 	2.1.2
> 	2.1.1
> 	2.0.5
> 	2.0.0
> 	1.1.2
> 	1.0.5
> SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
> SDK Versions:
> 	2.1.701
> 	2.1.700
> 	2.1.505
> 	2.1.504
> 	2.1.503
> 	2.1.500
> 	2.1.302
> 	2.1.301
> 	2.1.4
> 	2.0.0
> 	1.0.4
> MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks
> 
> Xamarin.Profiler
> Version: 1.6.11
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> Updater
> Version: 11
> 
> Xamarin.Android
> Version: 9.4.0.51 (Visual Studio Community)
> Commit: xamarin-android/d16-2/9fa7775
> Android SDK: /Users/fanmixco/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		8.1 (API level 27)
> 
> SDK Tools Version: 26.1.1
> SDK Platform Tools Version: 29.0.1
> SDK Build Tools Version: 27.0.3
> 
> Build Information: 
> Mono: mono/mono/2019-02@e6f5369c2d2
> Java.Interop: xamarin/java.interop/d16-2@d64ada5
> LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
> LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
> ProGuard: xamarin/proguard/master@905836d
> SQLite: xamarin/sqlite/3.27.1@8212a2d
> Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969
> 
> Microsoft Mobile OpenJDK
> Java SDK: /Users/fanmixco/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
> 1.8.0-25
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> Android Device Manager
> Version: 1.2.0.58
> Hash: d03e3ea
> Branch: remotes/origin/d16-2~1
> Build date: 2019-07-16 17:37:14 UTC
> 
> Xamarin Designer
> Version: 16.2.0.354
> Hash: 5f80a14f8
> Branch: remotes/origin/d16-2
> Build date: 2019-07-11 17:28:26 UTC
> 
> Apple Developer Tools
> Xcode 10.3 (14492.2)
> Build 10G8
> 
> Xamarin.Mac
> Version: 5.14.0.110 (Visual Studio Community)
> Hash: a8bcecce
> Branch: d16-2
> Build date: 2019-06-28 07:31:43-0400
> 
> Xamarin.iOS
> Version: 12.14.0.110 (Visual Studio Community)
> Hash: a8bcecce
> Branch: d16-2
> Build date: 2019-06-28 07:31:42-0400
> 
> Xamarin Inspector
> Version: 1.4.3
> Hash: db27525
> Branch: 1.4-release
> Build date: Mon, 09 Jul 2018 21:20:18 GMT
> Client compatibility: 1
> 
> Build Information
> Release ID: 802001105
> Git revision: a187f6852ae62ba52b944b47e53702957edfcf7b
> Build date: 2019-07-22 18:20:10+00
> Build branch: release-8.2
> Xamarin extensions: 34bd2378d8d707df25989727c23ce68d9a232a67
> 
> Operating System
> Mac OS X 10.14.5
> Darwin 18.6.0 Darwin Kernel Version 18.6.0
>     Thu Apr 25 23:16:27 PDT 2019
>     root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by EmilAlipiev** [comment]
I think that you should post this question on xamarin forums. It is your project specific error. In general compression works fine. If you believe that it doesnt you should attach log information you receive. Also please try to attach projects in zip format directly instead of providing gdrive url

**Comment by FANMixco** [comment]
> I think that you should post this question on xamarin forums. It is your project specific error. In general compression works fine. If you believe that it doesnt you should attach log information you receive. Also please try to attach projects in zip format directly instead of providing gdrive url

No one has complained before from the Xamarin Team about the GDrive URLs, also, I didn't know I can drop files here. Second, the Forum is very vague and hardly ever I get any answer to my problems since I have raised many. Also, this is an issue. How am I going to know the error if the app only crashes when I do what I said and run it? It just crashes, if I deactivate the compression it works.

**Comment by EmilAlipiev** [comment]
in the forum there are xamarin certified developers and xamarin employees they check topics regularly (i do myself also) but if you post like you posted here, nobody will reply you. 
- You should give information, what you have done.
- What error you get.
- Provide minimal logs from your ouput window of VS.
 if you dont have time to post proper information, sorry but people also dont have time. 
Your issue is a kind of beginner issue in its own category, you should go through the documentation and ask question or problems in the forum.
here should be addressed only bug reports and feature requests. Otherwise there are real bugs there preventing our work and business schedule, among 366 open issues, they will be delayed.
Regarding your problem, I dont see any [proguard.cfg](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows) in your project. without this file, compression wont work. I didnt download your project because its 150 mb size, you should clean your bin, obj folders for each project and nuget folder as well before you post it.

**Comment by FANMixco** [comment]
> in the forum there are xamarin certified developers and xamarin employees they check topics regularly (i do myself also) but if you post like you posted here, nobody will reply you.
> 
> * You should give information, what you have done.
> * What error you get.
> * Provide minimal logs from your ouput window of VS.
>   if you dont have time to post proper information, sorry but people also dont have time.
>   Your issue is a kind of beginner issue in its own category, you should go through the documentation and ask question or problems in the forum.
>   here should be addressed only bug reports and feature requests. Otherwise there are real bugs there preventing our work and business schedule, among 366 open issues, they will be delayed.
>   Regarding your problem, I dont see any [proguard.cfg](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows) in your project. without this file, compression wont work. I didnt download your project because its 150 mb size, you should clean your bin, obj folders for each project and nuget folder as well before you post it.

Well, let's start by something, I'm not new here and I know about reporting bugs as getting support if you could answer my Xamarin.Android questions in the forum, it would be awesome since I've been waiting for someone who could give me some light, I asked the same questions in StackOverflow too, but if you could support me, you would do me a great favor.

- https://forums.xamarin.com/discussion/161495/how-to-turn-on-notification-mediastyle-in-text-to-speech-in-android#latest

- https://forums.xamarin.com/discussion/160818/errors-while-binding-library#latest

- https://forums.xamarin.com/discussion/158762/link-assemblies-causes-some-sections-of-my-apps-to-crash#latest

I have reported the questions and they are even accepted by Microsoft as a bugs, let's consider this one:

https://github.com/xamarin/xamarin-android/issues/3263

Therefore, I know how to differentiate between a Bug and a possible mistake from my side. Now, the second point, the project is huge and yes it's 150MB and it's not connected to NuGets, Bins or Objs. There are no bins and objs folders if you see it carefully, I know very well that I need to delete them frequently since they cause several issues.

Next, I know what is proguard since I have enabled it and disabled it many times and this is the first time that the compiler is crashing, how do I know it that's a bug? Because I have built 3 editions of this project with VS2015, VS2017 and VS2019 and only in the latest iteration with VS2019, I have had multiple bugs that I have reported in VS support, Xamarin GitHub and here.

**Comment by EmilAlipiev** [comment]
because in your previous bug report, you have more details and valid point that something was working. no i didnt look detailed into your sample project because many of us will ignore 150mb of project. thats why Xamarin team always says minimal repro! 
You arent giving any details of what is crashing. what error you get. how should we know? you may add a google library or facebook nuget since your last try and when you enable proguard, it will strip off many functions and classes, variables. so you bump into a crash. Without proper proguard config, you can never get proguard or d8/r8 working.

**Comment by FANMixco** [comment]
> because in your previous bug report, you have more details and valid point that something was working. no i didnt look detailed into your sample project because many of us will ignore 150mb of project. thats why Xamarin team always says minimal repro!
> You arent giving any details of what is crashing. what error you get. how should we know? you may add a google library or facebook nuget since your last try and when you enable proguard, it will strip off many functions and classes, variables. so you bump into a crash. Without proper proguard config, you can never get proguard or d8/r8 working.

I added the rest of details including a new project, but it still crashes in the configuration that I said.

**Comment by pjcollins** [comment]
@FANMixco I think you'll need to add a custom proguard config file to your app to ensure certain types required at start up are present in the main dex file. For more information, please see these docs:

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows#customizing-proguard

These proguard config files should still be used when r8 is enabled.

**Comment by FANMixco** [comment]
> @FANMixco I think you'll need to add a custom proguard config file to your app to ensure certain types required at start up are present in the main dex file. For more information, please see these docs:
> 
> https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows#customizing-proguard
> 
> These proguard config files should still be used when r8 is enabled.

It crashes.

<img width="1126" alt="Screen Shot 2019-07-30 at 21 07 05" src="https://user-images.githubusercontent.com/1666156/62158206-3b29fe80-b30f-11e9-9f5f-3db23dca2566.png">

<img width="705" alt="Screen Shot 2019-07-30 at 21 09 02" src="https://user-images.githubusercontent.com/1666156/62158223-42510c80-b30f-11e9-8ac1-1de1c2a9e298.png">

<img width="1261" alt="Screen Shot 2019-07-30 at 21 15 11" src="https://user-images.githubusercontent.com/1666156/62158227-4715c080-b30f-11e9-94c0-e37168d8068f.png">

**Comment by pjcollins** [comment]
The first screenshot looks like a build error, not a runtime crash? It's hard to tell what's going wrong just from these few screen shots. I don't think the `Preserve` attribute should be needed in this case.

**Comment by FANMixco** [comment]
> The first screenshot looks like a build error, not a runtime crash? It's hard to tell what's going wrong just from these few screen shots. I don't think the `Preserve` attribute should be needed in this case.

The last of the preserve can be ignored, however, the error yes, it's not runtime, but the Java heap looks irrelevant and if remove the proguard file then it creates the APK, but it doesn't work.

**Comment by FANMixco** [comment]
Hi @jonathanpeppers, considering that it has been 3 years since it was opened. I'm going to close it.
