### ISSUE TITLE
(IAnimatable) crashing apps

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-android#3400]
### Steps to Reproduce

1. Uncompress this project: https://drive.google.com/open?id=1aKU5ovgk2iwzwUWtQgbUZQSh6POkfvp5
2. Run.
3. Tap on the Search Bar.

### Expected Behavior

To run and work properly the animation.

![a0IwbXvxBY](https://user-images.githubusercontent.com/1666156/62101579-2eb58f80-b296-11e9-9eb8-714df62f1bfc.gif)

If you configure the App as **Code Shrinker: None**, **Linker Behavior: Don't link** and **Debug**, then it works as expected.

**Configuration that works:**

<img width="735" alt="Screen Shot 2019-07-30 at 06 51 31" src="https://user-images.githubusercontent.com/1666156/62101670-7f2ced00-b296-11e9-87b3-73970633ad1a.png">

<img width="736" alt="Screen Shot 2019-07-30 at 06 51 39" src="https://user-images.githubusercontent.com/1666156/62101676-82c07400-b296-11e9-8f41-080ecdcdf0bb.png">

### Actual Behavior

Crashes if you tap on the Search Bar with the configuration **Linker Behavior: Link all assemblies** and choose **Release**. _If you use Debug with Linker Behavior: Link all assemblies or Link SDK assemblies it works._

<img width="907" alt="Screen Shot 2019-07-29 at 20 07 47" src="https://user-images.githubusercontent.com/1666156/62071346-9c34d200-b23c-11e9-83f7-f8efb810a520.png">

And then you get these errors:

<img width="500" alt="Screen Shot 2019-07-29 at 19 59 47" src="https://user-images.githubusercontent.com/1666156/62070953-cfc32c80-b23b-11e9-87dd-228abd8f9be2.png">

<img width="626" alt="Screen Shot 2019-07-29 at 20 00 02" src="https://user-images.githubusercontent.com/1666156/62070962-d2be1d00-b23b-11e9-89a7-e4d37d9a9e95.png">

The library is this one:

[tk.supernovaic.MaterialSearchBar-crashing.zip](https://github.com/xamarin/xamarin-android/files/3443667/tk.supernovaic.MaterialSearchBar-crashing.zip)

And the repository (**_this one has a try catch in the line 592 to avoid the crash, but prevents the animation_**):

https://github.com/FANMixco/Xamarin-SearchBar

### Version Information

> Visual Studio Community 2019 for Mac
> Version 8.2 (build 1105)
> Installation UUID: ca4ace63-e90f-4a21-9d13-77d4006606fd
> 	GTK+ 2.24.23 (Raleigh theme)
> 	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)
> 
> 	Package version: 600000311
> 
> Mono Framework MDK
> Runtime:
> 	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
> 	Package version: 600000311
> 
> NuGet
> Version: 5.1.0.6013
> 
> .NET Core
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	2.1.12
> 	2.1.11
> 	2.1.9
> 	2.1.8
> 	2.1.7
> 	2.1.6
> 	2.1.2
> 	2.1.1
> 	2.0.5
> 	2.0.0
> 	1.1.2
> 	1.0.5
> SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
> SDK Versions:
> 	2.1.701
> 	2.1.700
> 	2.1.505
> 	2.1.504
> 	2.1.503
> 	2.1.500
> 	2.1.302
> 	2.1.301
> 	2.1.4
> 	2.0.0
> 	1.0.4
> MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks
> 
> Xamarin.Profiler
> Version: 1.6.11
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> Updater
> Version: 11
> 
> Xamarin.Android
> Version: 9.4.0.51 (Visual Studio Community)
> Commit: xamarin-android/d16-2/9fa7775
> Android SDK: /Users/fanmixco/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		8.1 (API level 27)
> 
> SDK Tools Version: 26.1.1
> SDK Platform Tools Version: 29.0.1
> SDK Build Tools Version: 27.0.3
> 
> Build Information: 
> Mono: mono/mono/2019-02@e6f5369c2d2
> Java.Interop: xamarin/java.interop/d16-2@d64ada5
> LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
> LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
> ProGuard: xamarin/proguard/master@905836d
> SQLite: xamarin/sqlite/3.27.1@8212a2d
> Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969
> 
> Microsoft Mobile OpenJDK
> Java SDK: /Users/fanmixco/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
> 1.8.0-25
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> Android Device Manager
> Version: 1.2.0.58
> Hash: d03e3ea
> Branch: remotes/origin/d16-2~1
> Build date: 2019-07-16 17:37:14 UTC
> 
> Xamarin Designer
> Version: 16.2.0.354
> Hash: 5f80a14f8
> Branch: remotes/origin/d16-2
> Build date: 2019-07-11 17:28:26 UTC
> 
> Apple Developer Tools
> Xcode 10.3 (14492.2)
> Build 10G8
> 
> Xamarin.Mac
> Version: 5.14.0.110 (Visual Studio Community)
> Hash: a8bcecce
> Branch: d16-2
> Build date: 2019-06-28 07:31:43-0400
> 
> Xamarin.iOS
> Version: 12.14.0.110 (Visual Studio Community)
> Hash: a8bcecce
> Branch: d16-2
> Build date: 2019-06-28 07:31:42-0400
> 
> Xamarin Inspector
> Version: 1.4.3
> Hash: db27525
> Branch: 1.4-release
> Build date: Mon, 09 Jul 2018 21:20:18 GMT
> Client compatibility: 1
> 
> Build Information
> Release ID: 802001105
> Git revision: a187f6852ae62ba52b944b47e53702957edfcf7b
> Build date: 2019-07-22 18:20:10+00
> Build branch: release-8.2
> Xamarin extensions: 34bd2378d8d707df25989727c23ce68d9a232a67
> 
> Operating System
> Mac OS X 10.14.5
> Darwin 18.6.0 Darwin Kernel Version 18.6.0
>     Thu Apr 25 23:16:27 PDT 2019
>     root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by EmilAlipiev** [comment]
Why dont you do it all yourself and attach a reproducible sample? So you can get faster help.

**Comment by FANMixco** [comment]
> Why dont you do it all yourself and attach a reproducible sample? So you can get faster help.

This one I can add it as soon as I'm back I didn't want to forget the issue.

**Comment by FANMixco** [comment]
> Why dont you do it all yourself and attach a reproducible sample? So you can get faster help.

I added both projects, I hope now everything is clear.

**Comment by pjcollins** [comment]
@FANMixco if you're encountering a linker issue when only `Link all assemblies` is enabled, you may want to try adding the `[Android.Runtime.Preserve]` attribute to the types which are being linked out. Alternatively, a custom linker configuration may be required. Please see the following docs for more information on working with the linker:

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker
https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker

I'm going to close this issue for now with the info provided, please report back if you're unable to get things working with some combination of the linker related changes mentioned above

**Comment by FANMixco** [comment]
> @FANMixco if you're encountering a linker issue when only `Link all assemblies` is enabled, you may want to try adding the `[Android.Runtime.Preserve]` attribute to the types which are being linked out. Alternatively, a custom linker configuration may be required. Please see the following docs for more information on working with the linker:
> 
> https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker
> https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker
> 
> I'm going to close this issue for now with the info provided, please report back if you're unable to get things working with some combination of the linker related changes mentioned above

How is possible that in my other project works? Because this is odd that in one works and the other one not.

**Comment by FANMixco** [comment]
> @FANMixco if you're encountering a linker issue when only `Link all assemblies` is enabled, you may want to try adding the `[Android.Runtime.Preserve]` attribute to the types which are being linked out. Alternatively, a custom linker configuration may be required. Please see the following docs for more information on working with the linker:
> 
> https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker
> https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker
> 
> I'm going to close this issue for now with the info provided, please report back if you're unable to get things working with some combination of the linker related changes mentioned above

It doesn't work:

<img width="697" alt="Screen Shot 2019-07-30 at 21 27 09" src="https://user-images.githubusercontent.com/1666156/62158938-e6878300-b310-11e9-875a-f860ad7a45f6.png">

<img width="732" alt="Screen Shot 2019-07-30 at 21 27 20" src="https://user-images.githubusercontent.com/1666156/62158944-eab3a080-b310-11e9-9bc2-072441c3a82c.png">

<img width="729" alt="Screen Shot 2019-07-30 at 21 27 28" src="https://user-images.githubusercontent.com/1666156/62158950-ee472780-b310-11e9-88bb-4460596fbc6b.png">

It still **crashes** in **Release**.

**Comment by pjcollins** [comment]
Are you sure you are preserving the right types? If you're using a library that's being partially linked away you may need to use a custom linker configuration as suggested.

**Comment by FANMixco** [comment]
> Are you sure you are preserving the right types? If you're using a library that's being partially linked away you may need to use a custom linker configuration as suggested.

Yes, this is where the libraries are loaded the main page.

**Comment by FANMixco** [comment]
> @FANMixco if you're encountering a linker issue when only `Link all assemblies` is enabled, you may want to try adding the `[Android.Runtime.Preserve]` attribute to the types which are being linked out. Alternatively, a custom linker configuration may be required. Please see the following docs for more information on working with the linker:
> 
> https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker
> https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker
> 
> I'm going to close this issue for now with the info provided, please report back if you're unable to get things working with some combination of the linker related changes mentioned above

The problem that I see that this is not connected directly to my project, but to the NuGet Library:

https://www.nuget.org/packages/Xamarin-MaterialSearchBar/

Which I know because I built it and I have the source code I know where the issue is:

```csharp
if (NavIconShown)
{
	NavIcon.SetImageResource(Resource.Drawable.ic_menu_animated);
}
else
{
	NavIcon.SetImageResource(Resource.Drawable.ic_back_animated);
}
var mDrawable = NavIcon.Drawable;
((IAnimatable)mDrawable).Start();
NavIconShown = !NavIconShown;
```

And I have two projects where I use this library, but only in this one is crashing when I do the Linking because in this specific line is not being recognized: `((IAnimatable)mDrawable).Start();`, where should I add your suggestion in the library? Or where exactly since in both cases is in the main screen, but only here is not working as expected. Thanks.

**Comment by FANMixco** [comment]
> [Android.Runtime.Preserve]

I added to the library and I get the same issue:

<img width="801" alt="Screen Shot 2019-08-02 at 21 15 47" src="https://user-images.githubusercontent.com/1666156/62393591-e4206580-b56a-11e9-88a1-d60a2da5c046.png">
