### ISSUE TITLE
"TypeLoadException: Could not resolve type with token ..." when AOT enabled on release Build

### ISSUE THREAD

**Issue by beavis88** [xamarin/xamarin-android#3434]
### Steps to Reproduce

1. Release build with AOT
2. Start app
3. Crash

### Expected Behavior

Not crash

### Actual Behavior

Crash

### Version Information

VS2019 16.2.0

[crash.log](https://github.com/xamarin/xamarin-android/files/3459976/crash.log)

**Comment by brendanzagaeski** [comment]
Thanks for the report! If you might be able to share a project that demonstrates this behavior, that would be excellent. If you can't share an example publicly but could share a project privately, a few options are:

  * Upload the project to a temporary private GitHub repository, and add me (brendanzagaeski) as a collaborator.
  * Or use **Help > Send Feedback > Report a Problem** from within Visual Studio to create an item on [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Those allow private attachments. Then you can link to the Developer Community item here. After that I'll close the Developer Community item to point to this GitHub issue, and we can continue the discussion here.
  * Or send a one to one message to me on Gitter, for example using a `/query @brendanzagaeski` command from within the [Xamarin.Android Gitter channel](https://gitter.im/xamarin/xamarin-android), and we can coordinate on another way to send the project non-publicly.

**Comment by jonathanpeppers** [comment]
@beavis88 closing for now, let us know if you can send more info, thanks!
