### ISSUE TITLE
WIP [spec] improvements to the Android settings UI

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#3438]
### Windows

![image](https://user-images.githubusercontent.com/840039/62378463-7d6b5f80-b50a-11e9-889e-f73c1068e445.png)

![image](https://user-images.githubusercontent.com/840039/62378482-852b0400-b50a-11e9-9bd7-0b14ec88b557.png)

## Changes

There are three types of changes we should make here to improve these screens:

1. Remove the setting from the UI. The templates & Xamarin.Android set the defaults appropriately. Users can opt in/out by modifying the csproj manually.

2. Move the setting to Advanced, because it should not be used often.

3. Move the setting to Advanced, but also make the value default. Users would only need to "opt out" if something went wrong.

### No. 1 - settings to remove

* `Use the concurrent garbage collector` - remove and default to `true`.
* Advanced
  * `Java Max Heap Size` - we increased the default to 1G already, developers probably don't need to modify anymore
  * `Additional Java Options` - edit `.csproj` if you want to change this
  * `Additional monodroid arguments` - edit `.csproj` if you want to change this

### No. 2 - settings to move to advanced.

* `Bundle assemblies into native code` - not widely used, in my opinion
* `Generate one package (.apk) per selected ABI` - we probably don't want developers enabling this in Debug mode, advanced users can enable it.
* `Enable Multi-Dex` - since https://github.com/xamarin/xamarin-android/pull/2912, less apps should need Multi-Dex going forward.
* `Code Shrinker` - we don't want users enabling this in Debug builds. Advanced users can find it in `Advanced`
* `Leave the following resources extensions uncompressed` - not widely used, in my opinion
* `Additional Supported Encodings`

### No. 3 - setting moved to advanced, and we make it default

* `Use incremental Android packaging system (aapt2)` - default to `true`, developers can opt out
* `Dex Compiler` - default to `d8` - developers can opt out

### AOT

I think we could do _something_ to simplify our AOT settings. I would like to make `Startup Tracing` very easy for developers to select -- and put the rest on `Advanced`. I am not certain what that should be yet, though.

### r8

Android Studio is using r8 by default, but they have the advantage of knowing all Java code that gets called by the application. We cannot do this without changes to the linker to emit all required proguard rules for Java methods that C# code would be calling. I don't think we can make r8 default until we have that support in Xamarin.Android. The result would be that most simple apps would not need any proguard rules at all. proguard rules would only be needed for edge cases.

We also don't want to pay the build time cost for Debug builds? Research would be needed to see if Android Studio is really running r8 in full, since it will be slower than d8 by itself. We also would be running additional linker steps for Debug builds (right now it's only 1), this will make our usage of r8 inherently slower than Android Studio.

**Comment by MihaMarkic** [comment]
I'm all for No. 3, agree with No.1 and No.2.
Is concurrent garbage collector rock solid and does it have advantages?

**Comment by JonDouglas** [comment]
Concurrent GC is rock solid and has advantages. It is on by default in templates, but not in SDK AFAIK.

https://www.mono-project.com/news/2017/05/17/concurrent-gc-news/

@MihaMarkic

**Comment by MihaMarkic** [comment]
Switching my projects to concurrent GC, thanks.

**Comment by jpobst** [comment]
These have been overhauled for .NET 6+, probably don't need this issue anymore.
