### ISSUE TITLE
Xamarin Android AppCompatCheckBox error when link sdk with target 9.0 API 28 running on 6.0 API 23

### ISSUE THREAD

**Issue by Nick1611** [xamarin/xamarin-android#3448]
### Steps to Reproduce
Hi,

I have an app targeted 8.1 API 27. After targeted to 9.0, I found the CheckBox has a strange behavior:

1. On the first click, the box is not checked but the value “checked” has changed
2. From the second click on, the check mark and “checked” value are toggled accordingly

It can be re-produced with a new Xamarin project – Android App. In content_main.axml, replace content with:

```
<TextView
    android:id="@+id/textView1" 
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_centerInParent="true"
    android:text="Hello World!" />

<CheckBox
    android:text="CheckBox"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:id="@+id/checkBox1" />
```

In MainActivity.OnCreate, add code to check result

```
        TextView tv = FindViewById<TextView>(Resource.Id.textView1);
        CheckBox cb = FindViewById<CheckBox>(Resource.Id.checkBox1);
        cb.Click += (o, e) =>
        {
            if (cb.Checked)
            {
                tv.Text = "checked";
            }
            else
            {
                tv.Text = "not checked";
            }
        };
```

Furthermore, when create checkbox in code (in appcomp activity):
- Using AppCompatCheckBox class will have the same error as in xml
- Using CheckBox class has no error

I tried skip linking classes CheckBox and AppCompatCheckBox using linker configuration file. It does not work (maybe I did it wrong). Then I tried skip linking the whole assemblies of "Xamarin.Android.Support.v7.AppCompat" and "Mono.Android" using linker properties. It does not work too.

After discussed in [stackoverflow](https://stackoverflow.com/questions/57361741/xamarin-android-appcompatcheckbox-error-when-link-sdk-with-target-9-0-api-28-run) it is found out to be a proguard issue. The workaround is to keep class in proguard config file with line:
-keep class android.support.graphics.** { *; }

Please find the attached file for the test project.

### Expected Behavior
check mark and "changed" value are in sync

### Actual Behavior
the check mark is not in sync with the value “checked” since the first click

### Version Information
This error happens only in the combination of

1. release build with linking SDK assembly (debug mode no problem)
2. proguard enabled
3. target 9.0 API 28 (target 8.1 no problem)
4. running on 6.0 API 23 (both Genymotion emulator and real device have problem. Tested on 4.4, 7.0, 9.0 no problem)

### Log File

[checkbox.zip](https://github.com/xamarin/xamarin-android/files/3472767/checkbox.zip)

**Comment by yaliashkevich** [comment]
Can be related to https://github.com/xamarin/AndroidSupportComponents/issues/219

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.
