### ISSUE TITLE
Improve Aapt2 and Explicit Crunch(XA0110) Warning Message Text

### ISSUE THREAD

**Issue by JonDouglas** [xamarin/xamarin-android#3450]
![image](https://user-images.githubusercontent.com/1288848/62552439-df89d480-b82a-11e9-85b3-a20e7e99b652.png)

Warning: https://github.com/xamarin/xamarin-android/blob/5e840abaf59747beeb2c3fa8ba01b97521ee283b/Documentation/guides/messages/xa0110.md

Context: https://twitter.com/MRumpler/status/1158666557440122880

Current warning:

```
warning XA0110: Disabling true as it is not supprted by 'aapt2'. If you wish to use true please set True to false.
```

Current Code:

https://github.com/xamarin/xamarin-android/blob/ecc016a2157e2a048dfd08f57e5ce4952aae3127/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L887-L890

Instead of the actual value, we should be using the property name which seems to be displaying the value here. We should probably escape that somehow?

**Comment by jpobst** [comment]
Fixed in https://github.com/xamarin/xamarin-android/pull/4016.
