### ISSUE TITLE
Support creating unsigned App Bundles

### ISSUE THREAD

**Issue by bryansmi** [xamarin/xamarin-android#3459]
Xamarin.Android 9.4 brought App Bundle (`.aab`) support to Xamarin. 

It appears according to this issue thread: https://github.com/xamarin/xamarin-android/issues/2727 and the documentation: https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.4#initial-support-for-android-app-bundle-publishing-format that App Bundles are produced via the `SignAndroidPackage` MSBuild target.

Unfortunately, this means that a completely unsigned `.aab` is unable to be produced via the Xamarin.Android SDK, since producing the `.aab` is tied to the signing process. This breaks with the flows offered by Google's `bundletool` (https://developer.android.com/studio/command-line/bundletool) which produces unsigned `.aab` artifacts, allowing `jarsigner` to handle the signing.

We'd like to be able to produce unsigned `.aab` artifacts via MSBuild. 

Thanks!

**Comment by jonathanpeppers** [comment]
We have an unsigned copy of the App Bundle in `obj\$(Configuration\android\bin\`. If you could use an [MSBuild logger](https://docs.microsoft.com/en-us/visualstudio/msbuild/build-loggers?view=vs-2019), you could even read the MSBuild properties to get these locations during a build:

https://github.com/xamarin/xamarin-android/blob/f9e2edec0dee291d94cdbd920f88576744d73a8a/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L747

https://github.com/xamarin/xamarin-android/blob/f9e2edec0dee291d94cdbd920f88576744d73a8a/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L745

That would better future-proof things so we would be less likely to break you.

@bryansmi let me know if we need to do anything here, thanks.

**Comment by bryansmi** [comment]
Awesome, thanks for the info. We're going to take a look into this. Assuming this solves the issue for us, I'll close the issue :)

Thanks Jon!

**Comment by bryansmi** [comment]
Hey Jon - it looks like this will work for us. Thanks for your help - closing the issue :)

**Comment by jonathanpeppers** [comment]
@bryansmi we are working on IDE integration for App Bundles -- the Google Play publishing UIs.

We are considering moving `$(_AppBundleIntermediate)` to be the `bin` directory like you were expecting.

Will this be a problem for you yet?

**Comment by bryansmi** [comment]
@jonathanpeppers Thanks for the heads up! So long as it's still in `obj` as well, we'll be fine. We'll probably track using `bin` as a work-item once your change is public, and update to that after some time.
