### ISSUE TITLE
Invalid Archive Folder, No APK files

### ISSUE THREAD

**Issue by jrahma** [xamarin/xamarin-android#3493]
Hi,

I am suddenly getting:

Failed to create App archive
Invalid Archive Folder, No APK files

My Build gives no error

This happens after the last Visual Studio update only.

Here is the Build log..

[Build13092019.txt](https://github.com/xamarin/xamarin-android/files/3498050/Build13092019.txt)

How to fix this please?

Thanks,
[Jassim](https://www.zeera.online)

**Comment by jrahma** [comment]
Can anyone help pleazzzze...

**Comment by sustinel** [comment]
+1 same issue here !

**Comment by wagenheimer** [comment]
I restarted my PC and then I was able to build.

**Comment by jrahma** [comment]
I restarted many times but still having the same problem

**Comment by sustinel** [comment]
> I restarted my PC and then I was able to build.

not working for me

**Comment by jrahma** [comment]
I tried removing:

`<AndroidPackageFormat>aab</AndroidPackageFormat>`

and it works for the archive but then Google Play throws this error when uploading the apk file:

**You uploaded an APK that is not zip aligned. You will need to run a zip align tool on your APK and upload it again.**

**Comment by joj** [comment]
We're not supporting aab yet from VS, so that's why you're getting the no APK error. On the zip alignment issue, build log should have something there.

**Comment by jonathanpeppers** [comment]
@joj the publishing UI in the IDE re-signs and zip aligns. Is there a log he can get that shows what happened there?

**Comment by TarekJihad** [comment]
You need to building the app using aab

1. Add this to MyApp.Android.csproj
<AndroidPackageFormat>aab</AndroidPackageFormat>

2. Start the: Developer Command Prompt for VS 

3. Run the following command
msbuild /t:SignAndroidPackage /p:Configuration=Release MyApp.Android.csproj

Ensure you setup a KeyStore correclty in the android project properties

**Comment by brendanzagaeski** [comment]
Internal cross-referencing link for the Microsoft team:

> VS bug [<span>#</span>965698](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/965698)

**Comment by jpobst** [comment]
Tracked and fixed here: https://developercommunity.visualstudio.com/t/xamarin-forms-android-apk-failure/669333.
