### ISSUE TITLE
Build fails with resource errors

### ISSUE THREAD

**Issue by rihadavid** [xamarin/xamarin-android#3494]
### Steps to Reproduce

1. Create the sample single view android project
2. Clean the project
3. Build the project
4. Open content_main.axml and change anything in the file - for example, change "Hello world!" to "Hello Xamarin!" in the TextView
5. Save all files
6. Edit the file again
7. Build without saving
8. The build fails with those errors and any ruther attempts to build fail again. You need to clean and rebuild.
```
1>  C:\Users\David\source\repos\App15\App15\Resources\values\styles.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
1>  C:\Users\David\source\repos\App15\App15\Resources\values\styles.xml(2): error APT0000: No resource found that matches the given name: attr 'colorAccent'.
1>  C:\Users\David\source\repos\App15\App15\Resources\values\styles.xml(2): error APT0000: No resource found that matches the given name: attr 'colorPrimary'.
1>  C:\Users\David\source\repos\App15\App15\Resources\values\styles.xml(2): error APT0000: No resource found that matches the given name: attr 'colorPrimaryDark'.
1>  C:\Users\David\source\repos\App15\App15\Resources\values\styles.xml(2): error APT0000: No resource found that matches the given name: attr 'windowActionBar'.
1>  C:\Users\David\source\repos\App15\App15\Resources\values\styles.xml(2): error APT0000: No resource found that matches the given name: attr 'windowNoTitle'.
1>  C:\Users\David\source\repos\App15\App15\Resources\values\styles.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'ThemeOverlay.AppCompat.Dark.ActionBar'.
1>  C:\Users\David\source\repos\App15\App15\Resources\values\styles.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'ThemeOverlay.AppCompat.Light'.
```

Seems similar to #2427 

### Version Information

Microsoft Visual Studio Community 2019
Version 16.2.1
VisualStudio.16.Release/16.2.1+29201.188
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Community

Azure App Service Tools v3.0.0   16.2.290.48383
Azure App Service Tools v3.0.0

C# Tools   3.2.0-beta4-19359-03+15b43b33901c88f68ef43f8314b5a2457716780d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.2.0-beta4-19359-03+15b43b33901c88f68ef43f8314b5a2457716780d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.91 (d16-2@2983aebeb)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.0 (d16-2/ebd65c9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

Diagnostic log 
[log2.txt](https://github.com/xamarin/xamarin-android/files/3498291/log2.txt)

**Comment by jonathanpeppers** [comment]
So I think the issue occurs if you introduce an error in the layout: just invalid XML or something. After that point it seems a `Rebuild` is required to get things working again.

We have fixed a few things in 16.3 in this area, so I will test with the latest build.

**Comment by rihadavid** [comment]
No, I am editing just the "Hello world!" string, not creating any code issues.

**Comment by jonathanpeppers** [comment]
Creating an XML syntax error is one issue. But it also looks like we might have multiple MSBuild targets running at once, so what @rihadavid is seeing is just happening randomly.

I think I finally reproduced the issue when doing:

1. Change a layout with the designer split view open (always use valid XML)
1. Randomly Ctlr+S or Ctrl+B quickly
1. Repeat

@garuma or @kzu should this be happening?

![image](https://user-images.githubusercontent.com/840039/62969119-2ef37600-bdd2-11e9-960a-cade0ac6f042.png)

When I look at these two binlogs, `UpdateGeneratedFiles` is running at the same time as `Build`: 
[logs.zip](https://github.com/xamarin/xamarin-android/files/3498437/logs.zip)

I don't know if there is another MSBuild target the designer is running here, could `SetupDependenciesForDesigner` also be running?

**Comment by rihadavid** [comment]
In my project, I am encountering this quite often, not only using the steps described above. I'd say that I get into this every 2nd or 3rd build, when I work with the Android designer. I think it's happening more often if I have two designer windows opened at the same time, but I'm not sure. 

And it's not just resource errors, in my project it says it can't find references etc., it seems to be quite random. Also, I've discovered that when I just keep hitting the build, sometimes it eventually builds, but then the app throws some runtime exception, like some inflated layout is null while it shouldn't be.

It just makes the overall designing/building experience messed up and it seems that the symptomps are different for every project, so you might get some other seemingly unrelated reports from other users that will be based on this issue 🤔 Hope it will be fixed soon 🙏

**Comment by brendanzagaeski** [comment]
A new Preview version has now been published that includes a fix for this item.

Fix included in Xamarin.Android 10.0.0.40.

Fix included on Windows in Visual Studio 2019 version 16.3 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by rsgrey** [comment]
Hello!
The problem is actual!
Xamarin.Android SDK 10.0.0.43
Visual Studio 2019 version 16.3.1

**Comment by brendanzagaeski** [comment]
@rsgrey, note that errors like this can also occur if the Xamarin.Android.Support NuGet packages have not yet been restored successfully into a project. If you are stuck on similar errors, then when you get a chance, you can report a [new issue](https://github.com/xamarin/xamarin-android/issues/new), if possible attaching either a zipped up example project that demonstrates the problem or the [diagnostic MSBuild output](https://docs.microsoft.com/visualstudio/ide/how-to-view-save-and-configure-build-log-files?view=vs-2019#to-change-the-amount-of-information-included-in-the-build-log) from your project, and the team can take a look. Thanks in advance!

**Comment by rsgrey** [comment]
[log.txt](https://github.com/xamarin/xamarin-android/files/3663743/log.txt)


> @rsgrey, note that errors like this can also occur if the Xamarin.Android.Support NuGet packages have not yet been restored successfully into a project. If you are stuck on similar errors, then when you get a chance, you can report a [new issue](https://github.com/xamarin/xamarin-android/issues/new), if possible attaching either a zipped up example project that demonstrates the problem or the [diagnostic MSBuild output](https://docs.microsoft.com/visualstudio/ide/how-to-view-save-and-configure-build-log-files?view=vs-2019#to-change-the-amount-of-information-included-in-the-build-log) from your project, and the team can take a look. Thanks in advance!

Hello.
I attached a log file
