### ISSUE TITLE
v1.0/RedistList/FrameworkList.xml does not yet include Java.Interop, Xamarin.Android.NUnitLite, or System.EnterpriseServices

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#3507]
Context: https://developercommunity.visualstudio.com/content/problem/678458/javainterop-issue.html 
Context: https://github.com/xamarin/xamarin-android/commit/d0b3daf16c9b6c668a56de701fd6c40632475284

I'm not sure if this exclusion might be intentional for Java.Interop and System.EnterpriseServices.

Java.Interop is automatically referenced by Xamarin.Android projects, so users don't need to reference that explicitly. (And it's also fine to remove that reference from existing projects, such as <https://github.com/xamarin/monodroid-samples/blob/master/android-n/CommitContentSample/SampleApp/SampleApp.csproj>.)

System.EnterpriseServices does not contain any types, so I suspect users wouldn't need to reference that either.

On the other hand, Xamarin.Android.NUnitLite does contain useful types, and it is not automatically referenced by Xamarin.Android projects.

### Steps to reproduce

 1. Create a Xamarin.Android project that includes the following `<ItemGroup/>`:

    ```xml
    <ItemGroup>
      <Reference Include="Java.Interop" />
      <Reference Include="Xamarin.Android.NUnitLite" />
      <Reference Include="System.EnterpriseServices" />
    </ItemGroup>
    ```

 2. Open the project in Visual Studio for Mac.

### Expected behavior

Visual Studio for Mac displays the three assemblies as successfully resolved. This was the behavior for Xamarin.Android 9.1 and earlier.

### Actual behavior

Visual Studio for Mac shows the assemblies as not resolved, with an error message similar to "Assembly not found for framework Xamarin.Android v9.0 Support".

But the assemblies are available in */Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/* , and the build process finds them successfully.

### Preliminary investigation

These 3 assemblies are not yet included in the newly populated */Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/RedistList/FrameworkList.xml* from <https://github.com/xamarin/xamarin-android/commit/d0b3daf16c9b6c668a56de701fd6c40632475284>.

These are the only 3 assemblies that are missing from the **Edit References** window compared to what's available when *FrameworkList.xml* is empty.

(It is perhaps also interesting to note that Visual Studio for Mac happily resolves OpenTK-1.0 and Mono.Android.Export even though those assemblies are not included in any *FrameworkList.xml* file. I suspect the important difference is that those assemblies are part of the *v4.4* target framework version rather than the *v1.0* target framework version. The *FrameworkList.xml* file for *v4.4* is empty.)

### Version information

Xamarin.Android SDK version 10.0.0.4 (d16-3@a1f7825)

**Comment by brendanzagaeski** [comment]
In case another team member might get to this before me, I started working on this some time ago, but part way through I learned that it would require outputting *FrameworkList.xml* twice: first during xaprepare, and then again later via the `<CreateFrameworkList/>` task. I haven't yet had a chance to revisit it to set that all up.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
