### ISSUE TITLE
App crash when distributed in app bundle format

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-android#3530]
### Steps to Reproduce

1. Activate app bundle build (on app center)
2. Distribute the app to google play beta channel through app center
3. Install the beta app from the play store on the device and run

### Expected Behavior
Works

### Actual Behavior
Crashes immediatly

### Version Information
From appcenter build:
Xamarin Android 9.4
Mono 6.0

### Log File
[crash-appbundle.txt](https://github.com/xamarin/xamarin-android/files/3523860/crash-appbundle.txt)

**Comment by RadoslawKubas** [comment]
I have exactly same problem

**Comment by jonathanpeppers** [comment]
> From appcenter build: Xamarin Android 9.4

@softlion this fix is only in Xamarin.Android 10.0.0.4 and higher: https://github.com/xamarin/xamarin-android/commit/feb9ea2a53034b73d5bd62ed3caea4e8f658d1e5

Are you able to use a the VS 2019 16.3 preview?

In the meantime, I have submitted a couple App Bundles to Google Play this morning that I built with xamarin-android/master. When they are approved, I will find out if something is still wrong here, thanks!

**Comment by RadoslawKubas** [comment]
Small update, in case it helps. I'm publishing and building using Microsoft App Center and I noticed that it crashes on non Android 9 devices only if install location is different than "Internal Only". With "Internal Only" it works fine.

**Comment by jonathanpeppers** [comment]
We had a report that the latest 16.3/8.3 preview works: https://github.com/xamarin/xamarin-android/issues/3298#issuecomment-528375639

This was using Xamarin.Android 10.x, but they didn't specify which version.

**Comment by softlion** [comment]
It's fixed

**Comment by iamlawrencev** [comment]
@softlion fixed on the latest preview?

**Comment by softlion** [comment]
No, fixed in stable release.

**Comment by jemunk** [comment]
This just happened to us. Distributed an app this Wednesday, to the Play Store beta channel. After install app crashed immediately on start. Splash screen is shown very shortly before crash.

**Comment by jonathanpeppers** [comment]
@jemunk can you file a new issue with your `adb logcat` output? Verify you are using at least Xamarin.Android 10.x

**Comment by jemunk** [comment]
So maybe it is because I am not using Xamarin.Android 10, I will try that, Could be nice if the build process on AppCenter broke and gave me a warning about that, Also Android 10 is not available in Visual Studios "Android SDK's and Tools" unless I select the "Google (Unsupported)" repository.
