### ISSUE TITLE
[Linux] empty apk after increasing TargetFrameworkVersion from v8.1 to v9.0

### ISSUE THREAD

**Issue by Des-Nerger** [xamarin/xamarin-android#3559]
With an app I'm working on, in the csproj file I've increased TargetFrameworkVersion from v8.1 to v9.0. After that, the `$ xabuild AndroidApp/AndroidApp.csproj /p:Configuration=Release /t:SignAndroidPackage` build command now produces an unworkable apk with no errors in the process. In fact, the apk archive is almost empty, having no `lib` and `assemblies` directories; there's only res, resources.arsc, META-INF and AndroidManifest.xml. Can anyone help me? What could be the cause of this? I've attached the diag log of the build process.
[9.0_diag.log](https://github.com/xamarin/xamarin-android/files/3554437/9.0_diag.log)

**Comment by jonathanpeppers** [comment]
I believe this is the issue I fixed here: https://github.com/xamarin/xamarin-android/pull/3405 Which should be coming in the next VS for Mac 8.3 preview.

If you `Rebuild` is the problem solved?

**Comment by Des-Nerger** [comment]
Right now I use xamarin.android-oss-v10.0.99.75 and have built the project using `$ xabuild AndroidApp/AndroidApp.csproj /p:Configuration=Release /t:Clean,SignAndroidPackage`, but the apk is still less than 1MB in size.

**Comment by jonathanpeppers** [comment]
If you look at your log, `<BuildApk/>` is logging some of the files it puts in the APK:
```
  Adding native library: /media/c/Documnts/src/xamarin.android-oss/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib/armeabi-v7a/libmono-android.release.so (APK path: lib/armeabi-v7a/libmonodroid.so) (TaskId:413)
  Adding native library: /media/c/Documnts/src/xamarin.android-oss/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib/armeabi-v7a/libmonosgen-2.0.so (APK path: lib/armeabi-v7a/libmonosgen-2.0.so) (TaskId:413)
  Adding native library: /media/c/Documnts/src/xamarin.android-oss/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib/armeabi-v7a/libmono-btls-shared.so (APK path: lib/armeabi-v7a/libmono-btls-shared.so) (TaskId:413)
  Adding native library: /media/c/Documnts/src/xamarin.android-oss/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib/x86/libmono-android.release.so (APK path: lib/x86/libmonodroid.so) (TaskId:413)
  Adding native library: /media/c/Documnts/src/xamarin.android-oss/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib/x86/libmonosgen-2.0.so (APK path: lib/x86/libmonosgen-2.0.so) (TaskId:413)
  Adding native library: /media/c/Documnts/src/xamarin.android-oss/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib/x86/libmono-btls-shared.so (APK path: lib/x86/libmono-btls-shared.so) (TaskId:413)
  	Adding /media/c/Documnts/src/xamarin.android-oss/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib/armeabi-v7a/libmono-native.so (TaskId:413)
  	Adding /media/c/Documnts/src/xamarin.android-oss/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib/x86/libmono-native.so (TaskId:413)
```
Each of these files seems like they would already be larger than 1MB by themselves. This is running on Linux, correct?

Can you post the output of:
```
zipinfo your.apk
```
I suspect the native library, `libzip` is not working for some reason. We ship a copy of `libzip.dll` and `libzip.dylib` for Windows & Mac, but I have no idea what it does on Linux.

**Comment by Des-Nerger** [comment]
Both the original apk and its signed version are less than 1MB.
Here's output of `$ zipinfo AndroidApp/bin/Release/ru.tysa.app-Signed.apk`: 
[Signed_zipinfo.txt](https://github.com/xamarin/xamarin-android/files/3558917/Signed_zipinfo.txt)

> This is running on Linux, correct?
Yes, I'm on Linux.
> We ship a copy of libzip.dll and libzip.dylib for Windows & Mac, but I have no idea what it does on Linux.
Currently, I've just symlinked `libzip.so` to refer to the version shipped in my Linux distribution. But I can test if the version shipped in `xamarin.android-oss` makes any difference.

**Comment by jonathanpeppers** [comment]
Your build log has files that were reported added, but they are not in here...

@grendello any ideas on what might be happening with libzip on Linux?

**Comment by grendello** [comment]
@Des-Nerger which distro and what version of it are you running?

**Comment by Des-Nerger** [comment]
I tried to use `libzip.so` shipped in xamarin.android-oss, and now everything works as expected. My issue is resolved. Thanks.

@grendello I was using libzip built from https://packages.ubuntu.com/xenial/libzip4
