### ISSUE TITLE
 DatePicker.IOnDateChangedListener.OnDateChanged(...) doesn't works on Android 5.0, but works on 5.1 and higher

### ISSUE THREAD

**Issue by shults-s** [xamarin/xamarin-android#3586]
### Steps to Reproduce
1. Create your own implementation of DatePicker.IOnDateChangedListener interface;
2. Implement method OnDateChanged(DatePicker view, Int32 year, Int32 month, Int32 day);
3. Try changing the date in the date picker.

Code sample:
https://github.com/shults-s/SmtuSchedule/blob/a632b5beb60261ba6a6b80d13ee57c96b0a21044/SmtuSchedule.Android/Views/CustomDatePickerDialog.cs#L17

### Expected Behavior
On all supported Android versions (5.0 ... 9.0) when changing the date, the method of changing the date must works (DatePicker.IOnDateChangedListener.OnDateChanged(...)).

### Actual Behavior
On Android 5.1+ everything works fine!
But on Android 5.0 (it doesn't matter, an emulator or a real device) this method doesn't called!

The same problem was previously, but exactly the opposite:
https://xamarin.github.io/bugzilla-archives/41/41929/bug.html

I created my version of the DatePickerDialog to get rid of the buttons OK/Cancel, so a solution with an "unfocused event" is not suitable.

### Version Information
Xamarin.Android.Support.Design 28.0.0.1
Xamarin.Android.Support.v7.Preference 28.0.0.1
Xamarin.Android.Support.v14.Preference 28.0.0.1
Xamarin.Android.Support.v7.AppCompat 28.0.0.1

**Comment by jonathanpeppers** [comment]
If you search the web for this issue, it seems to point to an issue in Android 5.0:
* https://stackoverflow.com/questions/26589338/ondatechanged-method-does-not-seem-to-work/27404483
* https://stackoverflow.com/questions/31609777/ondatechanged-is-not-called-in-date-picker-android-lollipop

I would try one of the workaround they suggest (even though they are Java examples). I'm afraid there isn't much Xamarin.Android can do here--this seems to be a behavior of the Android OS.

Closing for now, sorry!
