### ISSUE TITLE
Does proguard work only for configuration with linker enabled?

### ISSUE THREAD

**Issue by awattar** [xamarin/xamarin-android#3587]
It seems that proguard step does not run for don't link linker behaviour setting. Is that OK?

**Comment by dellis1972** [comment]
There doesn't appear to be anything stopping proguard running of the linker is not enabled. Do you have a sample diagnostic build log we can take a look at?

In the mean time we will investigate.

**Comment by jonathanpeppers** [comment]
Actually, you need the linker enabled to use proguard: https://github.com/xamarin/xamarin-android/blob/89ddff91805e971cba8bc4bd43dfd92d24f93134/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L2069-L2073

The linker is what auto-generates many of the proguard rules for your app, such as any class that extends `Java.Lang.Object`.

I believe the current behavior will turn off proguard or r8 if you don't have the `<AndroidLinkMode>` set to `SdkOnly` or `Full`.

**Comment by awattar** [comment]
Thanks for the confirmation.

**Comment by jonathanpeppers** [comment]
I think that answer's the question? Thanks.

For more details about these settings you might read further at: https://devblogs.microsoft.com/xamarin/optimize-xamarin-android-builds/

There is even a video at the bottom that might interest you.
