### ISSUE TITLE
Consider using the APEX format to replace the shared runtime

### ISSUE THREAD

**Issue by grendello** [xamarin/xamarin-android#3591]
Android Q supports a new file format, [called APEX](https://android.googlesource.com/platform/system/apex/+/refs/heads/master/docs/README.md), to be used for components that need to be available early in the boot process of Android or are low-level/native components used by other applications. This appears to fit perfectly the purpose of shared runtime as it supports these file types:

  * Native shared libs
  * Native executables
  * JAR files
  * Data files
  * Config files

**Comment by jpobst** [comment]
Since we no longer have a shared runtime, I say "PROBLEM SOLVED"!
