### ISSUE TITLE
 Android App Bundle - does not automatically compress .WAV files

### ISSUE THREAD

**Issue by jgold6** [xamarin/xamarin-android#3598]
### Steps to Reproduce

1. Open the attached test project.
2. Run the app to device or simulator (tested with API 28 simulator)

[TestAABWav.zip](https://github.com/xamarin/xamarin-android/files/3585401/TestAABWav.zip)

### Expected Behavior
App will run and an audio file of a drum beat will play.

### Actual Behavior
App crashes with exception: `[MonoDroid] Java.IO.IOException: This file can not be opened as a file descriptor; it is probably compressed`

### Notes/Workaround
Add `.wav;` to the **Uncompressed Resources extensions** field in the Android Build project properties (VSforMac) or to the **Leave the following resource extensions uncompressed** field in the Android Options page (VS 2019 windows), then the file descriptor can successfully be opened and the WAV file played. 

During some research, supposedly the following file types are supposed to be uncompressed by default as per [this article](https://ponystyle.com/blog/2010/03/26/dealing-with-asset-compression-in-android-apps/):
/* these formats are already compressed, or don't compress well */
static const char* kNoCompressExt[] = {
    ".jpg", ".jpeg", ".png", ".gif",
    ".wav", ".mp2", ".mp3", ".ogg", ".aac",
    ".mpg", ".mpeg", ".mid", ".midi", ".smf", ".jet",
    ".rtttl", ".imy", ".xmf", ".mp4", ".m4a",
    ".m4v", ".3gp", ".3gpp", ".3g2", ".3gpp2",
    ".amr", ".awb", ".wma", ".wmv"
};

This would seem to be true when building an APK but not when building an AAB. 

### Version Information

<details>
<summary>
=== Visual Studio Enterprise 2019 for Mac ===
</summary>

Version 8.2.5 (build 5)
Installation UUID: f86726f2-bd5d-4610-867e-44e82f306ca2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0-preview8-28405-07
	2.1.12
	2.1.11
	2.1.10
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
	1.0.0
SDK: /usr/local/share/dotnet/sdk/3.0.100-preview8-013656/Sdks
SDK Versions:
	3.0.100-preview8-013656
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.1
	1.0.0-preview2-003121
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/jongoldberger/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/jongoldberger/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Enterprise)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Enterprise)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Build Information ===

Release ID: 802050005
Git revision: 94d90d630b6c7876d1d5298730d14ec97bbde3f9
Build date: 2019-08-22 21:31:34+00
Build branch: release-8.2
Xamarin extensions: 1cf04a6621fb6629226ea0285028954d6196e93f

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
</details>

### Log File

<details>
<summary>--------- beginning of system</summary>

09-06 09:15:50.987  6850  6850 I MonoDroid: UNHANDLED EXCEPTION:
09-06 09:15:51.009  6850  6850 I MonoDroid: Java.IO.IOException: This file can not be opened as a file descriptor; it is probably compressed
09-06 09:15:51.009  6850  6850 I MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <967504c0aa5b45129bda6e140020d470>:0 
09-06 09:15:51.009  6850  6850 I MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <967504c0aa5b45129bda6e140020d470>:0 
09-06 09:15:51.009  6850  6850 I MonoDroid:   at Android.Content.Res.AssetManager.OpenFd (System.String fileName) [0x00029] in <8954513db8fa4da9baef1ad29193e3fe>:0 
09-06 09:15:51.009  6850  6850 I MonoDroid:   at TestAABWav.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00049] in <7c870de229f449a3a6044e514f3f91af>:0 
09-06 09:15:51.009  6850  6850 I MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <8954513db8fa4da9baef1ad29193e3fe>:0 
09-06 09:15:51.009  6850  6850 I MonoDroid:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
09-06 09:15:51.009  6850  6850 I MonoDroid:   --- End of managed Java.IO.IOException stack trace ---
09-06 09:15:51.009  6850  6850 I MonoDroid: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.content.res.AssetManager.openFd(AssetManager.java:768)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at md51e54f3129abc6c7d41e0d6b934f5874d.MainActivity.n_onCreate(Native Method)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at md51e54f3129abc6c7d41e0d6b934f5874d.MainActivity.onCreate(MainActivity.java:32)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.Activity.performCreate(Activity.java:7136)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.Activity.performCreate(Activity.java:7127)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.os.Looper.loop(Looper.java:193)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-06 09:15:51.009  6850  6850 I MonoDroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-06 09:15:51.009  6850  6850 I MonoDroid: 
09-06 09:15:51.010  6850  6850 D AndroidRuntime: Shutting down VM
09-06 09:15:51.010  6850  6850 E AndroidRuntime: FATAL EXCEPTION: main
09-06 09:15:51.010  6850  6850 E AndroidRuntime: Process: com.onobytes.testaabwav, PID: 6850
09-06 09:15:51.010  6850  6850 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.onobytes.testaabwav/md51e54f3129abc6c7d41e0d6b934f5874d.MainActivity}: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.content.res.AssetManager.openFd(AssetManager.java:768)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at md51e54f3129abc6c7d41e0d6b934f5874d.MainActivity.n_onCreate(Native Method)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at md51e54f3129abc6c7d41e0d6b934f5874d.MainActivity.onCreate(MainActivity.java:32)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7136)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7127)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
09-06 09:15:51.010  6850  6850 E AndroidRuntime: 	... 11 more
09-06 09:15:51.013  1889  3646 W ActivityManager:   Force finishing activity com.onobytes.testaabwav/md51e54f3129abc6c7d41e0d6b934f5874d.MainActivity
</details>

I do not seem to have permission to add a label.

**Comment by jonathanpeppers** [comment]
@jgold6 is the actual ask here, to leave these extensions uncompressed by default?

https://github.com/aosp-mirror/platform_frameworks_base/blob/036ea39d96babb6c8a20464319903aea130e1a5f/tools/aapt/Package.cpp#L30-L37

We could do this if `$(AndroidUncompressedExtensions)` is completely blank, but if the dev specifies any it would be overwritten?

**Comment by jonathanpeppers** [comment]
The list is in two spots, one for aapt, then here is aapt2: https://github.com/aosp-mirror/platform_frameworks_base/blob/e80b45506501815061b079dcb10bf87443bd385d/tools/aapt2/cmd/Link.cpp#L2339-L2343

**Comment by jgold6** [comment]
> @jgold6 is the actual ask here, to leave these extensions uncompressed by default?

the actual ask is that a project that has a .wav file (or other file type that should remain uncompressed) does not cause an exception at runtime when loading a file descriptor when the app was built as an AAB.

**Comment by jgold6** [comment]
Also I tried AAPT and AAPT2 and both had the same issue.

**Comment by jonathanpeppers** [comment]
Ok, here is why: https://github.com/google/bundletool/blob/5ac94cb61e949f135c50f6ce52bbb5f00e8e959f/src/main/java/com/android/tools/build/bundletool/io/ApkSerializerHelper.java#L323-L330

It doesn't look like `bundletool` compresses these file extensions by default if you specify `BundleConfig.json` -- I guess we have to include them in the list in Xamarin.Android?

We have to use `BundleConfig.json` to specify other files, such as .NET assemblies and `typemap.jm` / `typemap.mj`: https://github.com/xamarin/xamarin-android/blob/e27f818267e07d03383293253a4a6547d41a1ba4/src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs#L31-L35

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.0.99.100.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published for macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.0.1.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
