### ISSUE TITLE
Android build and debug very slow since last update

### ISSUE THREAD

**Issue by xacte-richard** [xamarin/xamarin-android#3612]
### Steps to Reproduce
In my project, each time i do a modification build and deploy take around 4-5 minutes to start my app on my device or emulator.

### Expected Behavior
Like ever before, i expect to be able to debut in a few second. Like i did since a lot of years.

### Actual Behavior
Take around 4-5 minutes to start my app on my device or emulator.

### Version Information
Microsoft Visual Studio Community 2019
Version 16.2.4
VisualStudio.16.Release/16.2.4+29230.47
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ASP.NET and Web Tools 2019   16.2.292.25104
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.292.25104
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.2.292.25104
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.2.292.25104
Azure Functions and Web Jobs Tools

C# Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20626.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.95 (d16-2@37df81894)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.1 (d16-2/cec9eb4)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File
[CleanBuild.zip](https://github.com/xamarin/xamarin-android/files/3596109/CleanBuild.zip)

**Comment by jonathanpeppers** [comment]
Hi @xacte-richard these don't actually look like diagnostic MSBuild logs...

You should get timing info at the bottom that looks like this:
```
       99 ms  ResolveLibraryProjectImports               2 calls
      100 ms  WriteLinesToFile                          14 calls
      104 ms  AppendCustomMetadataToItemGroup            2 calls
      127 ms  FindUnderPath                             10 calls
      131 ms  RemoveDuplicates                           4 calls
      156 ms  CreateItem                                29 calls
      223 ms  ResolveAssemblyReference                   3 calls
      229 ms  Aapt2Compile                               3 calls
      244 ms  Hash                                       3 calls
      249 ms  LinkAssembliesNoShrink                     1 calls
      447 ms  Csc                                        2 calls
      540 ms  Aapt2Link                                  2 calls
      542 ms  ValidateJavaVersion                        2 calls
      549 ms  CallTarget                                 5 calls
      599 ms  Javac                                      1 calls
     1126 ms  D8                                         1 calls
     1152 ms  GenerateJavaStubs                          1 calls
     5061 ms  MSBuild                                    5 calls

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:12.83
```

Did you change the two MSBuild verbosity settings?

![image](https://user-images.githubusercontent.com/840039/64632512-d0b0b780-d3be-11e9-848c-214cf4bc3ec9.png)

Thanks!

**Comment by xacte-richard** [comment]
Hello Jonathan,

Yes i set the two verbosity.

I found this in the file

**Comment by jonathanpeppers** [comment]
Ok it looks like the Install (Deploy) at the end is missing this information. I’ll take a further look, thanks.

**Comment by jonathanpeppers** [comment]
### Build

Even on your one-line change build, `javac` and `dx` are both running, which shouldn't be happening??? These are some of the slowest parts of the Android build.

The example I see is:
```
Building target "_CompileJava" completely.
Input file "obj\Debug\90\android\src\mono\MonoPackageManager_Resources.java" is newer than output file "obj\Debug\90\_javac.stamp".
```
If you delete this file does the problem go away? It seems we might be missing it in this list: https://github.com/xamarin/xamarin-android/blob/cec9eb4f778ff2935fec2c4cab2aeb0f9666b41a/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1914-L1932

### Install (Deploy)

So if the build takes:
```
2>Time Elapsed 00:01:00.40
```

That means your install/deploy is taking the other 4 minutes? Since it looks like the diagnostic logging isn't working (I saw this, too), can you try installing this extension: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools

You can get a "binlog" such as I recorded here: 

![image](https://user-images.githubusercontent.com/840039/64643587-4d02c500-d3d6-11e9-8a7b-047730b4367d.png)

**Comment by xacte-richard** [comment]
Hello @jonathanpeppers 

Here is the log, delete the file not seem to do anything for the build.
[Android_Debug_AnyCPU_Build_2019-09-10T15_49_42.2501314-04_00.zip](https://github.com/xamarin/xamarin-android/files/3597492/Android_Debug_AnyCPU_Build_2019-09-10T15_49_42.2501314-04_00.zip)

**Comment by jonathanpeppers** [comment]
So it looks like `Install` is running these two slow steps _again_. Looking into this...

**Comment by xacte-richard** [comment]
@jonathanpeppers, i saw in the new log that link assemblies take a lot of time, so i changer my linking properties to none (was to sdk assemblies only).

Now it takes only 20 sec to build and deploy after a small change.

What is the impact of this change ? Can we have other problem ?

Thanks

**Comment by jonathanpeppers** [comment]
For a `Debug` build, you should have it on `None`. That is something I'll look into -- that could be the exact issue.

For some details on what is for `Debug` vs `Release`, there is a good article on that here: https://devblogs.microsoft.com/xamarin/optimize-xamarin-android-builds/
