### ISSUE TITLE
AOT compilation now fails when invoking strip on Windows

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#3619]
### Steps to Reproduce

AOT compilation has recently broken on Windows. I _believe_ this is fallout from some recent changes to no longer attempt to use shortened paths for tools in https://github.com/xamarin/xamarin-android/pull/2062. It looks like we've got an extra path escape attempt when invoking `strip`:
```
""C:\Program Files (x86)\Microsoft Visual Studio\2019\Stable\MSBuild\Xamarin\Android\ndk\arm-linux-androideabi-"strip"
```
```
  [aot-compiler stdout] AOTID 3581E20D-4E87-BD23-634B-437CDBBB6296
  [aot-compiler stdout] Compiled: 3/3
  [aot-compiler stdout] Executing the native assembler: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Stable\MSBuild\Xamarin\Android\ndk\arm-linux-
  androideabi-as"   -mfpu=vfp3 -o obj\Release\90\aot\armeabi-v7a\Xamarin.Android.Arch.Core.Common.dll\temp.s.o obj\Release\90\aot\armeabi-v7a\Xamarin.Andr
  oid.Arch.Core.Common.dll\temp.s
  [aot-compiler stdout] Executing the native linker: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Stable\MSBuild\Xamarin\Android\ndk\arm-linux-and
  roideabi-ld"  -shared -o obj\Release\90\aot\armeabi-v7a\libaot-Xamarin.Android.Arch.Core.Common.dll.so.tmp  obj\Release\90\aot\armeabi-v7a\Xamarin.Andro
  id.Arch.Core.Common.dll\temp.s.o
  [aot-compiler stdout] Stripping the binary: ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Stable\MSBuild\Xamarin\Android\ndk\arm-linux-androidea
  bi-"strip" --strip-symbol=\$a --strip-symbol=\$d obj\Release\90\aot\armeabi-v7a\libaot-Xamarin.Android.Arch.Core.Common.dll.so.tmp
  [aot-compiler stderr] '""C:\Program' is not recognized as an internal or external command,
  [aot-compiler stderr] operable program or batch file.
  [aot-compiler stderr] AOT of image C:\Users\peter\source\repos\App9\App9\App9.Android\obj\Release\90\android\assets\Xamarin.Android.Support.CoordinaterL
  ayout.dll failed.
```

### Version Information
d16-4

### Log File
[binlog.zip](https://github.com/xamarin/xamarin-android/files/3602685/binlog.zip)

**Comment by jonathanpeppers** [comment]
Hmm, it’s weird the tests we have are passing on Windows...

**Comment by dellis1972** [comment]
I be the CI system paths for the ndk don't have a space in the path 🤦‍♂

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.1.0.1.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

(The fix is not relevant for macOS.)
