### ISSUE TITLE
Visual Studio for Mac - Stop Debugging after manually killing process

### ISSUE THREAD

**Issue by tuyen-vuduc** [xamarin/xamarin-android#3633]
My VSfM was hang and the whole MacOS is slowed down days ago then I tried to kill several processes manually through Activity app. After that day, I couldn't debug on my Samsung S7 anymore, but I could still debug on Emulator or debug on that device with Android Studio.

I even reinstalled Visual Studio entirely, but the issue still exists.

### Expected Behavior
Start debugging on real device (Samsung S7)

### Actual Behavior
Not start debugging

### Version Information
Visual Studio for Mac v8.2.6 build 26

### Log File
```
at MonoDevelop.Debugger.Soft.MonoDroid.ConnectingAndroidDebuggerSession.LaunchAndConnectWithCommand (System.Threading.CancellationToken cancelToken) [0x00080] in /Users/vsts/agent/2.155.1/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.Debugger.Soft.MonoDroid/ConnectingAndroidDebuggerSession.cs:50 
INFO [2019-09-14 07:22:53Z]: ANDROID: Found Xamarin.Android 9.4.1.0
INFO [2019-09-14 07:22:54Z]: Mapped Pango font description 'Menlo 12' to NSFont '"Menlo-Regular 12.00 pt. P [] (0x7fc63156ebd0) fobj=0x7fc63e9c6a20, spc=7.22"'
ERROR [2019-09-14 07:24:13Z]: Failed to launch android application
Mono.AndroidTools.AdbException
  at Mono.AndroidTools.Util.AggregateAsyncResult.CheckError (System.Threading.CancellationToken token) [0x0002a] in /Users/vsts/agent/2.155.1/work/1/s/MonoDevelop.MonoDroid/external/androidtools/Mono.AndroidTools/Util/AggregateAsyncResult.cs:72 
  at Mono.AndroidTools.Adb.AdbClient.EndWriteCommandWithStatus (System.IAsyncResult asyncResult) [0x00007] in /Users/vsts/agent/2.155.1/work/1/s/MonoDevelop.MonoDroid/external/androidtools/Mono.AndroidTools/Adb/AdbClient.cs:328 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 
--- End of stack trace from previous location where exception was thrown ---

  at MonoDevelop.Debugger.Soft.MonoDroid.ConnectingAndroidDebuggerSession.LaunchAndConnectWithCommand (System.Threading.CancellationToken cancelToken) [0x00080] in /Users/vsts/agent/2.155.1/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.Debugger.Soft.MonoDroid/ConnectingAndroidDebuggerSession.cs:50 
```

**Comment by tuyen-vuduc** [comment]
=== Visual Studio Community 2019 for Mac ===

Version 8.2.6 (build 26)
Installation UUID: 9752f4d9-ab56-4123-b1df-b72324a9c97a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000334

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.334 (2019-02/6256b82d62f) (64-bit)
	Package version: 600000334

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.2.6
SDK: /usr/local/share/dotnet/sdk/2.2.401/Sdks
SDK Version: 2.2.401
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/tuyen/Library/Android/sdk
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.3
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/tuyen/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802060026
Git revision: a4ea4d00345f4d98a95bd2322b1d04935eb553e1
Build date: 2019-09-05 18:24:25+00
Build branch: release-8.2
Xamarin extensions: 366997b587d63360705507e281ae75025762cadf

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by gugavaro** [comment]
@tuyen-vuduc can you please collect and provide here the add logical?

**Comment by brendanzagaeski** [comment]
I was just skimming through this issue by chance, and I think "add logical" in the previous comment was an accidental autocorrect for "adb logcat" 😄 

For tuyen-vuduc, when you get a chance, you can complete the following steps to collect that log and attach it back:

 1. Open **Tools > SDK Command Prompt** in Visual Studio for Mac.

 2. Run the following command in the command prompt to clear the log on the device:

    ```sh
    adb logcat -c
    ```

 3. Follow the steps you used before to attempt to start debugging the app on your device again.

 4. After the debugging attempt fails, run the following command to collect the log from the device:

    ```sh
    adb logcat -d > "$HOME/Desktop/adblogcat.txt"
    ```

 5. Attach back the *adblogcat.txt* file from your desktop. You can optionally compress it in a *.zip* archive before attaching it.

Thanks!

**Comment by tuyen-vuduc** [comment]
Hi,

I am closing this issue since the latest stable version works fine now.

Thank you all.
