### ISSUE TITLE
16.3.0 Prev3.0 IDE changes doesn't always respect changes edited manually in csproj

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#3634]
### Steps to Reproduce
edit csproj - change AotAssemblies to true. Save and reload. Open Properties of project to check something else etc. Close manually edit again and AotAssemblies is now false.

### Expected Behavior
Respect changes either way.

First noticed in Prev 2.0, then thought it had been fixed, but obviously not so.

> VS bug [#1012553](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012553)

**Comment by dellis1972** [comment]
I suspect this is an issue in the IDE. Is this on VSforMac or Visual Studio on windows?

**Comment by gmck** [comment]
Visual Studio on windows

**Comment by gmck** [comment]
Suggestion - Since this is still open I'm editing the csprog all the time and that Hot Reload message is really getting old. Can it just be got rid of. The suggestion is not even appropriate to a new user. How about just on the start page

**Comment by dellis1972** [comment]
We will have to get one of the IDE team to take a look at this. @JonDouglas  any idea where we need to re-direct this issue? I seem to remember you mentioned the csproj editing on the call yesterday?

**Comment by jpobst** [comment]
If this is still an issue:

This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
