### ISSUE TITLE
R8 warnings - another one

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#3663]
R8 : warning : The rule `-keep public class * extends androidx.versionedparcelable.VersionedParcelable {
<init>(); (TaskId:200)
}` uses extends but actually matches implements. (TaskId:200)

**Comment by jonathanpeppers** [comment]
@gmck can you attach a [diagnostic msbuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

Did this start happening after adding AndroidX to your existing app?

**Comment by gmck** [comment]
Jonathan, it was not an existing app, but a new test app just to try out AndroidX, so I was importing code e.g. the base framework from my main app and converting to AndroidX as I imported.  It has similar R8 warnings as I've reported earlier. It was started with 16.3.0 P 4.0 and is now 16.4.0 P1.0. This new R8 warning was/is in both builds. I have the following in my proguard.cfg

-printconfiguration config_obdnowpro.txt
-printseeds seeds.txt
-printusage usage.txt

So I can see androidx.versionedparcelable.VersionedParcelable in the config file above.

[BuildLogNavXApp.zip](https://github.com/xamarin/xamarin-android/files/3649761/BuildLogNavXApp.zip)

The apk is running fine at this point.

**Comment by tranb3r** [comment]
Same warning in my app after migrating to androidx.
It looks like the new version of androix versionedparcelable (1.1.0) fixes the issue:
https://stackoverflow.com/questions/57601897/android-studio-3-5-warning-the-rule-keep-public-class-extends-androidx-vers
Could you please provide the binding updates?

**Comment by tranb3r** [comment]
The warning actually comes from the proguard configuration in xamarin.android.support.versionedparcelable 28.0.0.3.
It's probably harmless though and will disappear when we get rid of support libs.

**Comment by xamarindevelopervietnam** [comment]
in my case, it's come from migrating old app to new app support AndroidX @jonathanpeppers

**Comment by ederbond** [comment]
After upgrading to AndroidX using the VS 2019 Migration tool I started to see this same warning when compiling in release with D8 and R8 Enabled. The build succeed but and the app is deployed to the device but it crashes really faster during the startup. The app doesn't even have time to send the crash report to AppCenter. If I build in release with D8 enabled and R8 DISABLED the app works just fine. 
Another important info: The app builds and runs just fine with both D8 and R8 enabled before migrating to AndroidX. 
Can you give us any advice about a possible fix or work around @jonathanpeppers ?

**Comment by jonathanpeppers** [comment]
@ederbond you should file a new issue for your crash on startup, this one is about build warnings.

Include [adb logcat](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log) output and we should be able to help, thanks!

**Comment by ederbond** [comment]
Just opened this @jonathanpeppers https://github.com/xamarin/xamarin-android/issues/4908
