### ISSUE TITLE
cross-x86_64.exe is detected as a trojan virus.

### ISSUE THREAD

**Issue by hanseul1795** [xamarin/xamarin-android#3668]
### Steps to Reproduce

1. build the game with Xamarin android 10.0.0.40
2. cross-x86_64.exe is detected as a trojan virus
3. build fails

### Expected Behavior
Build without problem
### Actual Behavior
Build fails
### Version Information
Xamarin Android 10.0.0.40

I'm trying to build the app with Xamarin Android 10.0.0.40 and it fails because cross-x86_64.exe is detected as a virus.

What is the use of this file and is it okay to delete the file ?
![detection](https://user-images.githubusercontent.com/32581977/65452672-af64b800-de0f-11e9-891d-aa0072df88a4.png)

**Comment by grendello** [comment]
@hanseul1795 This a Mono runtime compiled as a cross-compiler for use in applications taking advantage of the AOT feature. It's most decidedly not a virus or a trojan. If you don't use AOT targetting x86, yes, you can remove the file. But perhaps first try reinstalling the Xamarin.Android update you are using? It seems to be a red herring, but perhaps the executable was infected in transit somehow?

@marek-safar is there a procedure for cases like this?

**Comment by marek-safar** [comment]
Did you try to notify the antivirus/scanner contact about their misdetection? I don't think we can do much from our position.

**Comment by Murazaki** [comment]
Other builds ([10.0.99.114](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d16-4/6/Azure/)) are also detected as infected by multiple antivirus databases.

**Comment by hanseul1795** [comment]
@marek-safar VIPRE has updated their definition and Xamarin Android is not considered as a treat anymore. I believe McAfee, Bitdefender and some other databases still consider the Xamarin Android as a treat.
