### ISSUE TITLE
Use the Linker to selectively wrap Java exceptions in the BCL ones

### ISSUE THREAD

**Issue by grendello** [xamarin/xamarin-android#3678]
Context: https://github.com/xamarin/xamarin-android/issues/3646

[This comment](https://github.com/xamarin/xamarin-android/issues/3646#issuecomment-534743754) on the above issue introduces the idea to use the Mono Linker to rewrite `try/catch` statements so that they capture Java exceptions. This is a good idea albeit a bit too broad IMO. What if we instead introduced two assembly and method level custom attributes to indicate that the decorated assembly/methods should have its `try/catch` blocks capturing Java exceptions rewritten to wrap them in a BCL exception? A mapping of known exceptions could be maintained in the linker code (e.g. `Java.IO.Exception` would be wrapped in `System.IO.Exception`) and a way to specify mappings in the application (most likely via the already existing Linker customization XML file) would be provided so that exceptions we're not aware of can be wrapped as well.

Perhaps it would be a good idea to also provide a global switch so that, if the developer so chooses, the entire app would be given the above treatment without having to use custom attributes.

**Comment by jpobst** [comment]
Pretty sure this has been implemented as [`$(AndroidBoundExceptionType)`](https://github.com/xamarin/xamarin-android/blob/main/Documentation/docs-mobile/building-apps/build-properties.md#androidboundexceptiontype).
