### ISSUE TITLE
Environment variables and files for package signing passwords failing for files when using Android App Bundle Bundle publishing format. 16.4.0 P1.0

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#3700]
Using the following
```
<AndroidKeyStore>true</AndroidKeyStore>
<AndroidSigningKeyStore>F:\glmkeystore\glm.keystore</AndroidSigningKeyStore>
<AndroidSigningKeyAlias>whateverkeyalias</AndroidSigningKeyAlias>
<AndroidSigningStorePass>file:F:\glmkeystore\KeyStorePassword.txt</AndroidSigningStorePass>
<AndroidSigningKeyPass>file:F:\glmkeystore\KeyPassword.txt</AndroidSigningKeyPass>
```

Buildlog output
Task "BuildApkSet"
Task Parameter:ToolPath=C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin
Task Parameter:JavaMaximumHeapSize=1G
Task Parameter:JarPath=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\bundletool.jar
Task Parameter:AdbToolPath=C:\Program Files (x86)\Android\android-sdk\platform-tools\
Task Parameter:Aapt2ToolPath=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android
Task Parameter:AppBundle=obj\Release\90\android\bin\com.glmsoftware.obdnowpro.aab
Task Parameter:Output=obj\Release\90\android\bin\com.glmsoftware.obdnowpro.apks
Task Parameter:KeyStore=F:\glmkeystore\glm.keystore
Task Parameter:KeyAlias= whateverkeyalias
Task Parameter:KeyPass=file:F:\glmkeystore\KeyPassword.txt
Task Parameter:StorePass=file:F:\glmkeystore\KeyStorePassword.txt
C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -Xmx1G -jar "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\bundletool.jar" build-apks --connected-device --bundle obj\Release\90\android\bin\com.glmsoftware.obdnowpro.aab --output obj\Release\90\android\bin\com.glmsoftware.obdnowpro.apks --mode default --adb "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" --aapt2 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\aapt2.exe" --ks F:\glmkeystore\glm.keystore --ks-key-alias whateverkeyalias --key-pass pass:file:F:\glmkeystore\KeyPassword.txt --ks-pass pass:file:F:\glmkeystore\KeyStorePassword.txt 
Incorrect keystore password.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Incorrect keystore password.
	at com.android.tools.build.bundletool.model.SigningConfiguration.extractFromKeystore(SigningConfiguration.java:116)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:432)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:392)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
The command exited with code 1.

I’ve broken it down to make it more readable and compared it to the output from my  Xamarin.Android Bundletool.

BuildLogOut
C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -Xmx1G -jar "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\bundletool.jar" 
build-apks 
--connected-device 
--bundle obj\Release\90\android\bin\com.glmsoftware.obdnowpro.aab 
--output obj\Release\90\android\bin\com.glmsoftware.obdnowpro.apks 
--mode default 
--adb "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" 
--aapt2 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\aapt2.exe" 
--ks F:\glmkeystore\glm.keystore 
--ks-key-alias whateverkeyalias 
--key-pass pass:file:F:\glmkeystore\KeyPassword.txt 
--ks-pass pass:file:F:\glmkeystore\KeyStorePassword.txt

Bundletool Utility for Xamarin.Android - ProcessStartInfo.Arguments

-Xmx1G -jar "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\bundletool.jar" 
build-apks 
--bundle=D:\ProjectsVS2019Preview\OBDNowPro\bin\Release\com.glmsoftware.obdnowpro-Signed.aab 
--output=D:\APKS\com.glmsoftware.obdnowpro-Signed.apks 
--mode=default
--adb="C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" 
--aapt2="C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\aapt2.exe" 
--ks=F:\glmkeystore\glm.keystore 
--ks-key-alias= whateverkeyalias 
--key-pass=file:F:\glmkeystore\KeyPassword.txt 
--ks-pass=file:F:\glmkeystore\KeyStorePassword.txt 
--overwrite

This above works fine.

The only difference I notice is that I’m using “=” and the build isn’t. I’m using --override and the build is using --connected-device, but that shouldn't make any difference. I got the “=” from the google docs, but the rest of it I relied on the Xamarin docs. I now don’t think the “=” actually matters, because the build doesn’t use them anywhere. However, if you use file or pass don’t you have to prefix with file or pass. In the build, I’m using file, but the build is prefixing it with pass, which I presume is why it is failing.

I sent a copy of the Bundle Tool to Brendan Z a few days ago if you want to check.

Could I also suggest the same treatment for the Key Alias, so it also isn't exposed?

**Comment by brendanzagaeski** [comment]
Thanks for the report!

* * *

*Additional notes for the Microsoft team*

Steps followed to confirm:

 1. Create a new Android single view project.

 2. Enable the Android App Bundle Bundle publishing format for the Release configuration, for example by adding the following lines to the *.csproj* file:

    ```xml
     <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
         <AndroidPackageFormat>aab</AndroidPackageFormat>
     </PropertyGroup>
    ```

 3. Set the **Keystore Password** and **Alias Password** settings in the **Android Package Signing** section of the Visual Studio project property pages to use the new *file:* format, and ensure **Sign the .APK file using the following keystore details.** is enabled.

 4. Attempt to build and deploy the app to a device or emulator in the Release configuration.

**Comment by dellis1972** [comment]
looks like we are not processing the `file:` type arguments for BundleTool.

**Comment by dellis1972** [comment]
PR is up https://github.com/xamarin/xamarin-android/pull/3703

**Comment by dellis1972** [comment]
Note `bundletool` does NOT support `env:` only `pass:` and `file:`.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.1.0.1.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
