### ISSUE TITLE
Latest update with VS2019 ServerCertificateValidationCallback doesn't work

### ISSUE THREAD

**Issue by greektreat** [xamarin/xamarin-android#3705]
Getting this error in Xamarin.Android development
The SSL connection could not be established, see inner exception.
went down the rabit hole to find the inner exception
"Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED\n  at /Users/builder/jenkins/workspace/archive-mono/2019-06/android/release/external/boringssl/ssl/handshake_client.c:1132"
"  at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00048] in <2b1467cde5f6428d89ddadc0df922c3d>:0 \n  at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in <2b1467cde5f6428d89ddadc0df922c3d>:0 \n  at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)\n  at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <2b1467cde5f6428d89ddadc0df922c3d>:0 \n  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in <2b1467cde5f6428d89ddadc0df922c3d>:0 "

internally all traffic is proxied, to access any api I added this to bypass it in dev
 public static class AppSecurityManager{ System.Net.ServicePointManager.ServerCertificateValidationCallback +=
            (sender, cert, chain, sslPolicyErrors) =>{return true;}}  it was working like a charm. after i updated Vs2019 16.3.1   Xamarin.Android SDK 10.0.0.43  it no longer works
 it doesn't even call this function so if I set the breakpoint it doesn't hit. above is the error i see in the output

**Comment by jpobst** [comment]
This is a change in Xamarin.Android 10.0 to match .Net `HttpClient' behavior.  There is now a different event that is raised you will need to handle.

See this comment for an example:
https://github.com/xamarin/xamarin-android/issues/3682#issuecomment-535834783

We are working on updating our Release Notes to call this out.
