### ISSUE TITLE
The archiving process has failed. Please see the Errors section for more details. [Android]

### ISSUE THREAD

**Issue by moniquealtero** [xamarin/xamarin-android#3714]
### Steps to Reproduce

1.  Create a new blank project with Xamarin Forms
2. Change to release mode
3. Build it
4. Archive Android project

Message: The archiving process has failed. Please see the Errors section for more details.

**Console output:** 

- Build

`========== Build: 3 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========`

- Xamarin:
```
Archiving App Bundle 'Unio.App.Forms.Droid'...
Creating archive directory 'Unio.App.Forms.Droid'...
Creating directory 'C:\Users\User\AppData\Local\Xamarin\Mono for Android\Archives\2019-10-01\Unio.App.Forms.Droid 10-01-19 10.28 AM.apkarchive'...
Deleting files '*.apk'...
Signing 'Unio.App.Forms.Droid'...
Cannot create the archive file because the packaging process failed.
Failed to create App archive 'Unio.App.Forms.Droid'.
```

## My **VS log file** can be downloaded [here](https://1drv.ms/u/s!AoZ3OsMZFDwW0ytVN-c2iDYR4Li7?e=vvNCiy)

I was using VS 2017 and everything works fine but after installing VS 2019 it is not working.

Thanks.

**Comment by brendanzagaeski** [comment]
Thanks for submitting this issue!

One common scenario where the **Xamarin** logs will show *Cannot create the archive file* after the *Signing 'Unio.App.Forms.Droid'...* message is if one of the signing properties has a typo in it. To check for that possibility or other potential problems, you can gather the diagnostic MSBuild output for the packaging and signing steps:

***Option 1**: Deploy the project to an emulator or device.*

 1. Set **Tools > Options > Build and Run > MSBuild project build output verbosity** to **Diagnostic**.

 2. Set the solution to the same configuration used for the failing *Build > Archive* command (for example, **Release | Any CPU**).

 3. Attach an Android device or emulator, and Attempt to build and deploy the project via **Debug > Start Debugging**.

 4. Once the deployment fails, check the **Error List** window for errors. For example, if the keystore information is blank, the **Error List** will include the following error:

    ```txt
    MSB4044: The "AndroidApkSigner" task was not given a value for the required parameter "KeyStore".
    ```
 
 5. If those errors still leave questions about how to resolve the issue, open the **View > Output** window, and set **Show output from** to **Build**.

 6. Make sure the **Output** window is selected, and then choose **File > Save Output As** to save the contents to a text file. Or copy and paste the build output into a text file.

 7. Attach back the saved log file, optionally compressed into a *.zip* archive. If needed, remove any sensitive names from the log file before attaching it, or let me know if you'll need a different way to send it.

***Option 2**: Run the packaging and signing steps from the command line to capture the build output.*

 1. Open **Tools > Command Line > Developer Command Prompt**.

 2. Run the following `MSBuild` command to build the solution:

    ```cmd
    MSBuild -restore -flp:v=diag;logfile=MSBuild.log -t:SignAndroidPackage -p:Configuration=Release
    ```

 3. Check the error messages from the `MSBuild` command.

 4. If those errors still leave questions about how to resolve the issue, attach back the saved *MSBuild.log* file from the solution directory, optionally compressed into a *.zip* archive. If needed, remove any sensitive names from the log file before attaching it, or let me know if you'll need a different way to send it.

Thanks in advance!

On a side note, in case it might be on interest, I've submitted a [suggestion](https://developercommunity.visualstudio.com/idea/737488/add-a-way-to-get-the-diagnostic-msbuild-output-fro.html) about making these MSBuild logs for **Build > Archive** easier to access in the future.

**Comment by moniquealtero** [comment]
Hi, thank you for quiick answer!

I fixed it! It wasn't showing up the error but after this process I noticed that was a keystore issue.

**Comment by moniquealtero** [comment]
> 
> 
> @moniquealtero Hi Monique, I'm having the same issue. Could you please give more details on the problem and how you solved it?
> Thanks in advance!

Sure! My problem was that I migrated my VS 2017 to 2019 and my project was loading an old keystore location. So I desabled automatic android keystore signature and build my project then I added the key (manually) to deploy my app.

**Comment by epomeranz** [comment]
Thanks :)

**Comment by moniquealtero** [comment]
> 
> 
> Thanks :)

Did It work?

**Comment by albrecht-jun-zhang** [comment]
Deleting bin and obj folders works for me

**Comment by EmilAlipiev** [comment]
yes somehow VS switches to keystore location when you have a new VS installation. I had the same issue after switching to new pc.

**Comment by LeonSweden** [comment]
This not so enlightening message do also appears  when VS have locked ... something.
Resolved by restarting VS.
Btw.. first I tried MSBUILD cmd in cmd dev - did not help.

**Comment by hanumansitaram** [comment]
MS Build worked here. It seems to be a bug in VS...

**Comment by Shaikh-Ayesha** [comment]
Disable the option "**sign the .APK file using the following keystore details.**"

you will get this option

right click on **android** project select **properties** goto **Android Package Signing**.
