### ISSUE TITLE
Can't build Xamarin.Android project in VS 2019 with SignAndroidPackage as default MSBuild target

### ISSUE THREAD

**Issue by LDan1117** [xamarin/xamarin-android#3715]
### Steps to Reproduce

1. Create a new Xamarin Android project in Visual Studio 2019 (v16.3.1 with Xamarin.Android.SDK 10.0.0.43 and Xamarin 16.0.3.274)
2. Build in Release|AnyCPU. The build is successful.
3. Edit the .csproj file and change the "DefaultTargets" to "SignAndroidPackage" instead of "Build".
4. Build in Release|AnyCPU. The build fails with the following error:
```
The "LinkAssemblies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'SignAndroidPackageErrorSample, Version=0.0.0.0, Culture=neutral, PublicKeyToken='.
Perhaps it doesn't exist in the Mono for Android profile?
File name: 'SignAndroidPackageErrorSample.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Expected Behavior
The build must not fail. An .apk file must be created and signed.

### Actual Behavior
The build fails.

### Version Information

> Microsoft Visual Studio Enterprise 2019
> Version 16.3.1
> VisualStudio.16.Release/16.3.1+29324.140
> Microsoft .NET Framework
> Version 4.8.03761
> 
> Installed Version: Enterprise
> 
> Visual C++ 2019   00435-60000-00000-AA987
> Microsoft Visual C++ 2019
> 
> C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Mono Debugging for Visual Studio   16.3.7 (9d260c5)
> Support for debugging Mono processes with Visual Studio.
> 
> NuGet Package Manager   5.3.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> Snapshot Debugging Extension   1.0
> Snapshot Debugging Visual Studio Extension Detailed Info
> 
> VisualStudio.Mac   1.0
> Mac Extension for Visual Studio
> 
> Xamarin   16.3.0.274 (d16-3@06531f8)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin Designer   16.3.0.230 (remotes/origin/d16-3-xcode11@bbe518670)
> Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
> 
> Xamarin Templates   16.3.565 (27e9746)
> Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
> 
> Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
> Xamarin.Android Reference Assemblies and MSBuild support.
>     Mono: mono/mono/2019-06@7af64d1ebe9
>     Java.Interop: xamarin/java.interop/d16-3@5836f58
>     LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
>     LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
>     ProGuard: xamarin/proguard/master@905836d
>     SQLite: xamarin/sqlite/3.27.1@8212a2d
>     Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333
> 
> Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File
The sample project, screenshots, and logs are attached.
![new android project](https://user-images.githubusercontent.com/15735136/65971928-ae680200-e471-11e9-8594-a21b7a993a7d.png)
![xamarin versions](https://user-images.githubusercontent.com/15735136/65971929-ae680200-e471-11e9-8339-c9aad589a58f.png)
![default target](https://user-images.githubusercontent.com/15735136/65971930-ae680200-e471-11e9-813f-a5f25d21dfde.png)
[SignAndroidPackageError.log](https://github.com/xamarin/xamarin-android/files/3676904/SignAndroidPackageError.log)
[SignAndroidPackageErrorSample.zip](https://github.com/xamarin/xamarin-android/files/3676899/SignAndroidPackageErrorSample.zip)

**Comment by LDan1117** [comment]
I've also noticed that the build is successful in VS 2017 (MSBuild 15) and Visual Studio for Mac (8.3.1 build 18). Thus the matter is probably with MSBuild 16.

**Comment by dellis1972** [comment]
We made some changes too SignAndroidPackage to speed up build times. It not longer depends on `Build` when building from inside the IDE. As a result `Build` is probably not being called now. 

The IDE will call the `Default` target (normally build) and has internal state so it knows when it really needs to build again. When hitting the `Run` button in the IDE our tooling therefore only calls `SignAndroidPackage` and then `Install`. Since we know already if the `Build` was up to date there was no need for `SignAndroidPackage` to depend on it. 

You can try changing `DefaultTargets` to `Build;SignAndroidPackage` if that is what you really need. 
But be warned, this might break some of the build improvements we have been making and will probably slow down your build/deploy/debug times.

I don't think this is a bug since our system is working as designer. So I will close this for now, feel free to re-open the issue if the above workaround does not work.

**Comment by LDan1117** [comment]
Thank you, @dellis1972 !

I've added the Build target and this helped to get rid of the error. Though I'm wondering why I didn't witness the error on Mac?
Considering the changes were made to SignAndroidPackage target it must have appeared in VS for Mac as well, mustn't it?.

**Comment by dellis1972** [comment]
VSforMac has a different internal build process to that of VS on Windows. So they don't always behave in the same way. Allot of this depends on the `BuildingInsideVisualStudio` MSBuild flag, which VS on Windows sets to `true`, I suspect VSforMac is not setting that property at all. That means it will default to the command line behaviour which is to do a Build as part of the SignAndroidPackage call. 

Skipping the `Build` dependency when hitting F5 in VS for Windows can save you a number of seconds on your dev loop when debugging. It takes time for MSBuild to figure out everything is up to date, even if you haven't made any changes.
