### ISSUE TITLE
OpenTK-1.0 crash on Android 10 Xamarin.Android project

### ISSUE THREAD

**Issue by tcoxMonkeyCoder** [xamarin/xamarin-android#3717]
### Steps to Reproduce

1. Add OpenTK-1.0 to a Xamarin.Android project
2. Add a class that inherits from AndroidGameView
3. Override the OnResize method and call GL.GenRenderbuffers(1, out uint x);
4. Add your view to a layout file
5. Run the app on a device with Android Q

Here is a sample project: 
[thisisatest.zip](https://github.com/xamarin/xamarin-android/files/3677432/thisisatest.zip)

### Expected Behavior
No crash
### Actual Behavior
Crash, and can't seem to catch any exception
### Version Information

Visual Studio Community 2019 for Mac
Version 8.3.1 (build 18)
Installation UUID: b58e92e7-ee15-485b-abf3-5163a0a7195d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

Mono Framework MDK
Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
	2.1.302
	2.1.4
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11
	2.1.2
	2.0.5
	2.0.3

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Updater
Version: 11

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

Xamarin Designer
Version: 16.3.0.244
Hash: e15b2ee97
Branch: remotes/origin/d16-3
Build date: 2019-09-25 00:03:16 UTC

Xamarin.Android
Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/i56527/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Microsoft Mobile OpenJDK
Java SDK: /Users/i56527/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

Android Device Manager
Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 803010018
Git revision: 272ab73f00ab2b13ec97dc8b31d02980cf66d47f
Build date: 2019-09-27 19:26:51+00
Build branch: release-8.3
Xamarin extensions: 451b00e65052c11c16b79e6d31a24c4cf0d1b794

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### Log File

10-01 10:07:07.458 30999 30999 D Mono    : DllImport searching in: '__Internal' ('(null)').
10-01 10:07:07.458 30999 30999 D Mono    : Searching for 'java_interop_jnienv_get_int_array_region'.
10-01 10:07:07.458 30999 30999 D Mono    : Probing 'java_interop_jnienv_get_int_array_region'.
10-01 10:07:07.458 30999 30999 D Mono    : Found as 'java_interop_jnienv_get_int_array_region'.
10-01 10:07:07.530 30999 30999 D Mono    : DllImport attempting to load: '/system/lib64/libc.so'.
10-01 10:07:07.531 30999 30999 D Mono    : DllImport loaded library '/system/lib64/libc.so'.
10-01 10:07:07.531 30999 30999 D Mono    : DllImport searching in: '/system/lib64/libc.so' ('/system/lib64/libc.so').
10-01 10:07:07.531 30999 30999 D Mono    : Searching for 'uname'.
10-01 10:07:07.531 30999 30999 D Mono    : Probing 'uname'.
10-01 10:07:07.531 30999 30999 D Mono    : Found as 'uname'.
10-01 10:07:07.533 30999 30999 D Mono    : DllImport attempting to load: 'libEGL.dll'.
10-01 10:07:07.535 30999 30999 D Mono    : DllImport error loading library './libEGL.dll': 'dlopen failed: library "./libEGL.dll" not found'.
10-01 10:07:07.536 30999 30999 D Mono    : DllImport error loading library './libEGL.dll.so': 'dlopen failed: library "./libEGL.dll.so" not found'.
10-01 10:07:07.536 30999 30999 D Mono    : DllImport error loading library './libEGL.dll.so': 'dlopen failed: library "./libEGL.dll.so" not found'.
10-01 10:07:07.536 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libEGL.dll': '(null)'.
10-01 10:07:07.536 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libEGL.dll.so': '(null)'.
10-01 10:07:07.536 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libEGL.dll.so': '(null)'.
10-01 10:07:07.537 30999 30999 D Mono    : DllImport error loading library 'libEGL.dll': 'dlopen failed: library "libEGL.dll" not found'.
10-01 10:07:07.538 30999 30999 D Mono    : DllImport error loading library 'libEGL.dll.so': 'dlopen failed: library "libEGL.dll.so" not found'.
10-01 10:07:07.539 30999 30999 D Mono    : DllImport error loading library 'libEGL.dll.so': 'dlopen failed: library "libEGL.dll.so" not found'.
10-01 10:07:07.539 30999 30999 D Mono    : DllImport error loading library 'libEGL.dll': 'dlopen failed: library "libEGL.dll" not found'.
10-01 10:07:07.540 30999 30999 D Mono    : DllImport error loading library './libEGL': 'dlopen failed: library "./libEGL" not found'.
10-01 10:07:07.540 30999 30999 D Mono    : DllImport error loading library './libEGL.so': 'dlopen failed: library "./libEGL.so" not found'.
10-01 10:07:07.540 30999 30999 D Mono    : DllImport error loading library './libEGL.so': 'dlopen failed: library "./libEGL.so" not found'.
10-01 10:07:07.540 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libEGL': '(null)'.
10-01 10:07:07.541 30999 30999 D Mono    : DllImport loaded library '/system/lib64/libEGL.so'.
10-01 10:07:07.541 30999 30999 D Mono    : DllImport searching in: 'libEGL.dll' ('/system/lib64/libEGL.so').
10-01 10:07:07.541 30999 30999 D Mono    : Searching for 'eglGetCurrentContext'.
10-01 10:07:07.541 30999 30999 D Mono    : Probing 'eglGetCurrentContext'.
10-01 10:07:07.541 30999 30999 D Mono    : Found as 'eglGetCurrentContext'.
10-01 10:07:07.553 30999 30999 D Mono    : DllImport searching in: '__Internal' ('(null)').
10-01 10:07:07.553 30999 30999 D Mono    : Searching for 'java_interop_jnienv_new_string'.
10-01 10:07:07.553 30999 30999 D Mono    : Probing 'java_interop_jnienv_new_string'.
10-01 10:07:07.553 30999 30999 D Mono    : Found as 'java_interop_jnienv_new_string'.
10-01 10:07:07.554 30999 30999 D Mono    : DllImport searching in: '__Internal' ('(null)').
10-01 10:07:07.554 30999 30999 D Mono    : Searching for 'java_interop_jnienv_new_object_array'.
10-01 10:07:07.554 30999 30999 D Mono    : Probing 'java_interop_jnienv_new_object_array'.
10-01 10:07:07.554 30999 30999 D Mono    : Found as 'java_interop_jnienv_new_object_array'.
10-01 10:07:07.555 30999 30999 D Mono    : DllImport searching in: '__Internal' ('(null)').
10-01 10:07:07.555 30999 30999 D Mono    : Searching for 'java_interop_jnienv_set_object_array_element'.
10-01 10:07:07.555 30999 30999 D Mono    : Probing 'java_interop_jnienv_set_object_array_element'.
10-01 10:07:07.555 30999 30999 D Mono    : Found as 'java_interop_jnienv_set_object_array_element'.
10-01 10:07:07.576 30999 30999 D Mono    : DllImport searching in: '__Internal' ('(null)').
10-01 10:07:07.576 30999 30999 D Mono    : Searching for 'java_interop_jnienv_get_field_id'.
10-01 10:07:07.577 30999 30999 D Mono    : Probing 'java_interop_jnienv_get_field_id'.
10-01 10:07:07.577 30999 30999 D Mono    : Found as 'java_interop_jnienv_get_field_id'.
10-01 10:07:07.577 30999 30999 D Mono    : DllImport searching in: '__Internal' ('(null)').
10-01 10:07:07.577 30999 30999 D Mono    : Searching for 'java_interop_jnienv_get_int_field'.
10-01 10:07:07.577 30999 30999 D Mono    : Probing 'java_interop_jnienv_get_int_field'.
10-01 10:07:07.577 30999 30999 D Mono    : Found as 'java_interop_jnienv_get_int_field'.
10-01 10:07:07.644 30999 30999 D Mono    : DllImport attempting to load: 'libGLESv1_CM.dll'.
10-01 10:07:07.647 30999 30999 D Mono    : DllImport error loading library './libGLESv1_CM.dll': 'dlopen failed: library "./libGLESv1_CM.dll" not found'.
10-01 10:07:07.648 30999 30999 D Mono    : DllImport error loading library './libGLESv1_CM.dll.so': 'dlopen failed: library "./libGLESv1_CM.dll.so" not found'.
10-01 10:07:07.648 30999 30999 D Mono    : DllImport error loading library './libGLESv1_CM.dll.so': 'dlopen failed: library "./libGLESv1_CM.dll.so" not found'.
10-01 10:07:07.648 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libGLESv1_CM.dll': '(null)'.
10-01 10:07:07.648 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libGLESv1_CM.dll.so': '(null)'.
10-01 10:07:07.648 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libGLESv1_CM.dll.so': '(null)'.
10-01 10:07:07.649 30999 30999 D Mono    : DllImport error loading library 'libGLESv1_CM.dll': 'dlopen failed: library "libGLESv1_CM.dll" not found'.
10-01 10:07:07.649 30999 30999 D Mono    : DllImport error loading library 'libGLESv1_CM.dll.so': 'dlopen failed: library "libGLESv1_CM.dll.so" not found'.
10-01 10:07:07.650 30999 30999 D Mono    : DllImport error loading library 'libGLESv1_CM.dll.so': 'dlopen failed: library "libGLESv1_CM.dll.so" not found'.
10-01 10:07:07.651 30999 30999 D Mono    : DllImport error loading library 'libGLESv1_CM.dll': 'dlopen failed: library "libGLESv1_CM.dll" not found'.
10-01 10:07:07.651 30999 30999 D Mono    : DllImport error loading library './libGLESv1_CM': 'dlopen failed: library "./libGLESv1_CM" not found'.
10-01 10:07:07.651 30999 30999 D Mono    : DllImport error loading library './libGLESv1_CM.so': 'dlopen failed: library "./libGLESv1_CM.so" not found'.
10-01 10:07:07.652 30999 30999 D Mono    : DllImport error loading library './libGLESv1_CM.so': 'dlopen failed: library "./libGLESv1_CM.so" not found'.
10-01 10:07:07.652 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libGLESv1_CM': '(null)'.
10-01 10:07:07.652 30999 30999 D Mono    : DllImport loaded library '/system/lib64/libGLESv1_CM.so'.
10-01 10:07:07.652 30999 30999 D Mono    : DllImport searching in: 'libGLESv1_CM.dll' ('/system/lib64/libGLESv1_CM.so').
10-01 10:07:07.652 30999 30999 D Mono    : Searching for 'glViewport'.
10-01 10:07:07.653 30999 30999 D Mono    : DllImport searching in: 'libGLESv1_CM.dll' ('/system/lib64/libGLESv1_CM.so').
10-01 10:07:07.653 30999 30999 D Mono    : Searching for 'glScissor'.
10-01 10:07:07.655 30999 30999 D Mono    : DllImport attempting to load: 'libGLESv2.dll'.
10-01 10:07:07.655 30999 30999 D Mono    : DllImport error loading library './libGLESv2.dll': 'dlopen failed: library "./libGLESv2.dll" not found'.
10-01 10:07:07.656 30999 30999 D Mono    : DllImport error loading library './libGLESv2.dll.so': 'dlopen failed: library "./libGLESv2.dll.so" not found'.
10-01 10:07:07.656 30999 30999 D Mono    : DllImport error loading library './libGLESv2.dll.so': 'dlopen failed: library "./libGLESv2.dll.so" not found'.
10-01 10:07:07.656 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libGLESv2.dll': '(null)'.
10-01 10:07:07.656 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libGLESv2.dll.so': '(null)'.
10-01 10:07:07.656 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libGLESv2.dll.so': '(null)'.
10-01 10:07:07.657 30999 30999 D Mono    : DllImport error loading library 'libGLESv2.dll': 'dlopen failed: library "libGLESv2.dll" not found'.
10-01 10:07:07.657 30999 30999 D Mono    : DllImport error loading library 'libGLESv2.dll.so': 'dlopen failed: library "libGLESv2.dll.so" not found'.
10-01 10:07:07.658 30999 30999 D Mono    : DllImport error loading library 'libGLESv2.dll.so': 'dlopen failed: library "libGLESv2.dll.so" not found'.
10-01 10:07:07.658 30999 30999 D Mono    : DllImport error loading library 'libGLESv2.dll': 'dlopen failed: library "libGLESv2.dll" not found'.
10-01 10:07:07.659 30999 30999 D Mono    : DllImport error loading library './libGLESv2': 'dlopen failed: library "./libGLESv2" not found'.
10-01 10:07:07.659 30999 30999 D Mono    : DllImport error loading library './libGLESv2.so': 'dlopen failed: library "./libGLESv2.so" not found'.
10-01 10:07:07.660 30999 30999 D Mono    : DllImport error loading library './libGLESv2.so': 'dlopen failed: library "./libGLESv2.so" not found'.
10-01 10:07:07.660 30999 30999 D Mono    : DllImport error loading library '/system/lib64/libGLESv2': '(null)'.
10-01 10:07:07.660 30999 30999 D Mono    : DllImport loaded library '/system/lib64/libGLESv2.so'.
10-01 10:07:07.660 30999 30999 D Mono    : DllImport searching in: 'libGLESv2.dll' ('/system/lib64/libGLESv2.so').
10-01 10:07:07.660 30999 30999 D Mono    : Searching for 'glGenRenderbuffers'.
10-01 10:07:07.661 30999 30999 E mono-rt : /proc/self/maps:
10-01 10:07:07.661 30999 30999 E mono-rt : 12c00000-12fc0000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
10-01 10:07:07.661 30999 30999 E mono-rt : 12fc0000-13300000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
10-01 10:07:07.661 30999 30999 E mono-rt : 13300000-140c0000 ---p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
10-01 10:07:07.661 30999 30999 E mono-rt : 140c0000-14100000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
10-01 10:07:07.661 30999 30999 E mono-rt : 14100000-141c0000 ---p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
10-01 10:07:07.661 30999 30999 E mono-rt : 141c0000-14240000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
10-01 10:07:07.661 30999 30999 E mono-rt : 14240000-164c0000 ---p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
10-01 10:07:07.661 30999 30999 E mono-rt : 164c0000-2ac00000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
10-01 10:07:07.661 30999 30999 E mono-rt : 701b0000-70437000 rw-p 00000000 fd:03 1344                               /system/framework/arm64/boot.art
10-01 10:07:07.661 30999 30999 E mono-rt : 70437000-70526000 rw-p 00000000 fd:03 1323                               /system/framework/arm64/boot-core-libart.art
10-01 10:07:07.661 30999 30999 E mono-rt : 70526000-7055c000 rw-p 00000000 fd:03 1335                               /system/framework/arm64/boot-okhttp.art
10-01 10:07:07.661 30999 30999 E mono-rt : 7055c000-7059d000 rw-p 00000000 fd:03 1320                               /system/framework/arm64/boot-bouncycastle.art
10-01 10:07:07.661 30999 30999 E mono-rt : 7059d000-705ad000 rw-p 00000000 fd:03 1317                               /system/framework/arm64/boot-apache-xml.art
10-01 10:07:07.661 30999 30999 E mono-rt : 705ad000-70e69000 rw-p 00000000 fd:03 1329                               /system/framework/arm64/boot-framework.art
10-01 10:07:07.661 30999 30999 E mono-rt : 70e69000-70e9c000 rw-p 00000000 fd:03 1326                               /system/framework/arm64/boot-ext.art
10-01 10:07:07.661 30999 30999 E mono-rt : 70e9c000-70f93000 rw-p 00000000 fd:03 1338                               /system/framework/arm64/boot-telephony-common.art
10-01 10:07:07.661 30999 30999 E mono-rt : 70f93000-70fa1000 rw-p 00000000 fd:03 1341                               /system/framework/arm64/boot-voip-common.art
10-01 10:07:07.661 30999 30999 E mono-rt : 70fa1000-70fb6000 rw-p 00000000 fd:03 1332                               /system/framework/arm64/boot-ims-common.art
10-01 10:07:07.661 30999 30999 E mono-rt : 70fb6000-70fb9000 rw-p 00000000 fd:03 1314                               /system/framework/arm64/boot-android.test.base.art
10-01 10:07:07.661 30999 30999 E mono-rt : 70fb9000-71072000 r--p 00000000 fd:03 1345                               /system/framework/arm64/boot.oat
10-01 10:07:07.661 30999 30999 E mono-rt : 71072000-71307000 r-xp 000b9000 fd:03 1345                               /system/framework/arm64/boot.oat
10-01 10:07:07.661 30999 30999 E mono-rt : 71307000-71308000 rw-p 00000000 00:00 0                                  [anon:.bss]
10-01 10:07:07.661 30999 30999 E mono-rt : 71308000-7130a000 r--s 00000000 fd:03 1358                               /system/framework/boot.vdex
10-01 10:07:07.661 30999 30999 E mono-rt : 7130a000-7130b000 r--p 0034e000 fd:03 1345                               /system/framework/arm64/boot.oat
10-01 10:07:07.661 30999 30999 E mono-rt : 7130b000-7130c000 rw-p 0034f000 fd:03 1345                               /system/framework/arm64/boot.oat
10-01 10:07:07.661 30999 30999 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 30999 (are.thisisatest), pid 30999 (are.thisisatest)
10-01 10:07:07.706 31038 31038 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
10-01 10:07:07.707  1071  1071 I /system/bin/tombstoned: received crash request for pid 30999
10-01 10:07:07.708 31038 31038 I crash_dump64: performing dump of process 30999 (target tid = 30999)
10-01 10:07:07.713 31038 31038 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-01 10:07:07.713 31038 31038 F DEBUG   : Build fingerprint: 'google/blueline/blueline:10/QP1A.190711.020.C3/5869620:user/release-keys'
10-01 10:07:07.713 31038 31038 F DEBUG   : Revision: 'MP1.0'
10-01 10:07:07.713 31038 31038 F DEBUG   : ABI: 'arm64'
10-01 10:07:07.717 31038 31038 F DEBUG   : Timestamp: 2019-10-01 10:07:07-0600
10-01 10:07:07.717 31038 31038 F DEBUG   : pid: 30999, tid: 30999, name: are.thisisatest  >>> com.xactware.thisisatest <<<
10-01 10:07:07.717 31038 31038 F DEBUG   : uid: 10281
10-01 10:07:07.717 31038 31038 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
10-01 10:07:07.717 31038 31038 F DEBUG   : Cause: null pointer dereference
10-01 10:07:07.717 31038 31038 F DEBUG   :     x0  0000000000000001  x1  0000007fd4555770  x2  0000007199d1b500  x3  0000000000000438
10-01 10:07:07.717 31038 31038 F DEBUG   :     x4  0000000000000710  x5  00000070fee8e998  x6  0000000000000710  x7  0000400000004000
10-01 10:07:07.717 31038 31038 F DEBUG   :     x8  00000000ffffffff  x9  0000000000000001  x10 0000000000000001  x11 0000000000000002
10-01 10:07:07.717 31038 31038 F DEBUG   :     x12 0000000000000001  x13 00000070a74d0cac  x14 0000000000000001  x15 00000070fee02770
10-01 10:07:07.717 31038 31038 F DEBUG   :     x16 0000000000000000  x17 000000719a6cd8c0  x18 0000000000000008  x19 00000070ad42e458
10-01 10:07:07.717 31038 31038 F DEBUG   :     x20 00000070ad42d268  x21 000000719ca06000  x22 000000719cb79810  x23 0000000000000000
10-01 10:07:07.717 31038 31038 F DEBUG   :     x24 0000007fd4555770  x25 000000719cbbb020  x26 0000007fd4555770  x27 0000000000000005
10-01 10:07:07.717 31038 31038 F DEBUG   :     x28 0000007fd45559e0  x29 0000007fd4555620
10-01 10:07:07.717 31038 31038 F DEBUG   :     sp  0000007fd4555620  lr  00000070a74d19ac  pc  0000000000000000
10-01 10:07:07.780 31038 31038 F DEBUG   : 
10-01 10:07:07.780 31038 31038 F DEBUG   : backtrace:
10-01 10:07:07.780 31038 31038 F DEBUG   :       #00 pc 0000000000000000  <unknown>
10-01 10:07:07.780 31038 31038 F DEBUG   :       #01 pc 000000000000d9a8  <anonymous:70a74c4000>
10-01 10:07:07.945  1071  1071 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_07
10-01 10:07:07.946  1521 31042 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
10-01 10:07:07.946  1521 31041 W ActivityTaskManager:   Force finishing activity com.xactware.thisisatest/md5c660686a969ebdf5deb0a112c213c3fb.MainActivity
10-01 10:07:07.954  1521  1561 I BootReceiver: Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
10-01 10:07:07.955  1521  1561 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x2
10-01 10:07:07.955  1521  1554 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-01 10:07:07.955  1521  1554 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-01 10:07:07.967  1521  2205 W InputDispatcher: channel 'b879958 com.xactware.thisisatest/md5c660686a969ebdf5deb0a112c213c3fb.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-01 10:07:07.967  1521  2205 E InputDispatcher: channel 'b879958 com.xactware.thisisatest/md5c660686a969ebdf5deb0a112c213c3fb.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-01 10:07:07.967  1521  6418 E InputDispatcher: Window handle Window{b879958 u0 com.xactware.thisisatest/md5c660686a969ebdf5deb0a112c213c3fb.MainActivity} has no registered input channel
10-01 10:07:07.969  1521  4502 I WindowManager: WIN DEATH: Window{b879958 u0 com.xactware.thisisatest/md5c660686a969ebdf5deb0a112c213c3fb.MainActivity}
10-01 10:07:07.969   966   966 I Zygote  : Process 30999 exited due to signal 11 (Segmentation fault)
10-01 10:07:07.969  1521  4502 W InputDispatcher: Attempted to unregister already unregistered input channel 'b879958 com.xactware.thisisatest/md5c660686a969ebdf5deb0a112c213c3fb.MainActivity (server)'
10-01 10:07:07.974  1521  3380 I ActivityManager: Process com.xactware.thisisatest (pid 30999) has died: vis+99 TOP 
10-01 10:07:07.975  1521  1556 I libprocessgroup: Successfully killed process cgroup uid 10281 pid 30999 in 0ms
10-01 10:07:07.992  1521  1548 W ActivityManager: setHasOverlayUi called on unknown pid: 30999
10-01 10:07:07.995  1521  1554 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-01 10:07:07.995  1521  1554 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-01 10:07:07.999 21021 21021 I Finsky  : [2] otn.onTrimMemory(1): Memory trim requested to level 40
10-01 10:07:08.022 16525 16525 I WallpaperService: engine resumed
10-01 10:07:08.029 30273 30273 W Glide   : Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
10-01 10:07:08.042   995   995 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
10-01 10:07:08.042  2759  2793 I MicroDetectionState: Keep running DSP hotword
10-01 10:07:08.047  2022  2053 I AiAiReflection: Filtering unlaunchable event /deleted_app/1
10-01 10:07:08.049  2022  2053 I AiAiReflection: Filtering unlaunchable event /deleted_app/0
10-01 10:07:08.081  1521  1542 I DropBoxManagerService: add tag=platform_stats_bookmark isTagEnabled=true flags=0x2
10-01 10:07:08.084  1521  1554 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-01 10:07:08.084  1521  1554 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-01 10:07:08.143  1521  7576 I ActivityManager: Force stopping com.xactware.thisisatest appid=10281 user=0: from pid 31055
10-01 10:07:08.149  3635  3635 D CarrierSvcBindHelper: No carrier app for: 0
10-01 10:07:08.153  4491  4491 D RegisteredNfcFServicesCache: Service unchanged, not updating
10-01 10:07:08.165 20440 20440 I AppLifecycleTracker: App foreground state unchanged: inForeground ? false
10-01 10:07:08.165 20440 20440 I AppLifecycleTracker: App foreground state unchanged: inForeground ? false
10-01 10:07:08.166 23566 23566 I AppLifecycleTracker: App foreground state unchanged: inForeground ? false
10-01 10:07:08.169 20440 20440 I AppLifecycleTracker: App foreground state unchanged: inForeground ? false
10-01 10:07:08.169 20440 20440 I chatty  : uid=10086(com.google.android.youtube) identical 2 lines
10-01 10:07:08.169 20440 20440 I AppLifecycleTracker: App foreground state unchanged: inForeground ? false
10-01 10:07:08.179 17608 17644 I cr_BindingManager: onTrimMemory: level=80, size=0
10-01 10:07:08.250  2847  2847 I AppBase : onTrimMemory(): 5
10-01 10:07:08.305  2847  2847 I GoogleInputMethodService: onTrimMemory(): 5
10-01 10:07:08.448  1521  1548 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{c674e0c u0 com.xactware.thisisatest/md5c660686a969ebdf5deb0a112c213c3fb.MainActivity t-1 f}
10-01 10:07:09.458  1172  1172 W adbd    : timeout expired while flushing socket, closing
10-01 10:07:10.780  3308  3753 D PowerUI : can't show warning due to - plugged: true status unknown: false
10-01 10:07:10.782  1009 20191 I QC2Comp : [avcD_926] Stats: Works: Q(625)/Done(625)| Work-Rate: Q(0.0/s Avg=0.1/s) Done(0.000/s Avg=0.084/s)| Stream: 10000.00fps 133.4Mbps| Pending(0) i/p-done(0)
10-01 10:07:10.782  1009 20044 I QC2Comp : [avcD_925] Stats: Works: Q(59)/Done(59)| Work-Rate: Q(0.0/s Avg=0.0/s) Done(0.000/s Avg=0.008/s)| Stream: 10000.00fps 219.4Mbps| Pending(0) i/p-done(0)
10-01 10:07:10.782  1009 20005 I QC2Comp : [avcD_924] Stats: Works: Q(384)/Done(384)| Work-Rate: Q(0.0/s Avg=0.1/s) Done(0.000/s Avg=0.051/s)| Stream: 10000.00fps 54.4Mbps| Pending(0) i/p-done(0)
10-01 10:07:12.824 19188 19188 I GsaVoiceInteractionSrv: #checkDspStatus
10-01 10:07:12.824 19188 19188 I GsaVoiceInteractionSrv: DSP available

**Comment by dellis1972** [comment]
OpenTK defaults to OpenGLES1. The `GL.GenRenderbuffers` call is not available on that API. You need to set to OpenGL ES 2 or above. 

You need to override the `CreateFrameBuffer` method and set your target OpenGL ES version like so.


```
protected override void CreateFrameBuffer ()
{
    this.ContextRenderingApi = OpenTK.Graphics.GLVersion.ES2;
    base.CreateFrameBuffer ();
}
```

**Comment by tcoxMonkeyCoder** [comment]
@dellis1972 Thank you!
