### ISSUE TITLE
EntityFrameworkCore 3 throws TypeLoadException

### ISSUE THREAD

**Issue by mduchev** [xamarin/xamarin-android#3723]
### Steps to Reproduce

1. Run the app
2. Click on the button
3. When the button is clicked, we are creating a new entity of type Address.
4. After the entity is created, we are adding it to Addresses DbSet (here is where the issue occurs)
5. Before we are able to call SaveChangesAsync, the app crashes

Repro project:
[TestEFC3XamarinApp.zip](https://github.com/xamarin/xamarin-android/files/3680202/TestEFC3XamarinApp.zip)

### Expected Behavior
The EF will create and add the entity to the DBSet and then save the changes

### Actual Behavior
The app crashes with this exception:

_System.TypeLoadException
Message=Could not resolve type with token 01000143 from typeref (expected class 'System.Diagnostics.CodeAnalysis.MaybeNullAttribute' in assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')_

### Version Information
Microsoft Visual Studio Enterprise 2019
Version 16.3.2
VisualStudio.16.Release/16.3.2+29326.143
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.283.64955
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.283.64955
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.283.64955
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.283.64955
Azure Functions and Web Jobs Tools

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.274 (d16-3@06531f8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.246 (remotes/origin/d16-3@bd2f86892)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@7af64d1ebe9
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by SpencerConstance** [comment]
I am having the same issue with accessing data with Entity Framework Core. I have tried visual studio 16.3.1 with xamarin.android 10.0.0.43 and .net core 3.0.100, and also tried visual studio 16.4 preview which uses xamarin.android 10.0.99.100 and I still get the same issue. I also tried targeting and minimum android API version set to 10 just to make sure that it wasn't an issue with targeting older android versions.

**Comment by SpencerConstance** [comment]
Also more information might be found at [this Entity Framework Core issue](https://github.com/aspnet/EntityFrameworkCore/issues/18005) where they determined that this is most likely an external issue with Xamarin.Android and .net standard 2.1.

**Comment by shaks786** [comment]
I'm also getting the same issue on Xamarin.iOS so it's not a problem isolated to Android

**Comment by mduchev** [comment]
@shaks786  Can you build & deploy the project on iOS? I can't see to be able to run it. I have created another issue for iOS.
xamarin/xamarin-macios#7153

**Comment by SpencerConstance** [comment]
It looks like this might be an issue related to Mono, and should be fixed on the next service release according to the thread on [this Mono issue.](https://github.com/mono/mono/issues/17064)

**Comment by SpencerConstance** [comment]
That should solve the iOS issue too I believe, if it is the same error as this one.

**Comment by grendello** [comment]
@mduchev @SpencerConstance could you try the following build of Xamarin.Android 16.4 (preview) to see if it fixes this for you? It includes the Mono fix mentioned above by @SpencerConstance. Note that this is an open source build which means you will have no debugging capabilities after installing it and to get the capability back simply install a commercial version again (downloaded from one of the [locations here](https://github.com/xamarin/xamarin-android/#downloads)):

  * [macOS](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d16-4/21/Azure/processDownloadRequest/xamarin-android/xamarin-android/bin/BuildRelease/Xamarin.Android.Sdk-OSS-10.1.0.1_d16-4_ee1dfb6.pkg)
  * [Windows](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d16-4/21/Azure/processDownloadRequest/xamarin-android/xamarin-android/bin/BuildRelease/Xamarin.Android.Sdk-OSS-10.1.0.1_d16-4_ee1dfb6.vsix)

**Comment by mduchev** [comment]
@grendello Yep, just tested it, everything seems to work fine.

**Comment by grendello** [comment]
@mduchev great! I'm going to consider this issue fixed then, to be available in the upcoming 16.4 release, thanks for testing!

Fixed in: [Xamarin.Android/master](https://github.com/xamarin/xamarin-android/commit/53221d00c2fbf718f33dd38370abcfe0e4f8676e)
Fixed in: [Xamarin.Android/16.4](https://github.com/xamarin/xamarin-android/commit/ee1dfb60e06d644ac652edcb33c52f7aca01d0e1)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item. (Note that the fix is not yet included in the current Preview version. I will update this item again when a Preview version is also available that includes the fix.)

Fix included in Xamarin.Android 10.0.3.0

Fix included on Windows in Visual Studio 2019 version 16.3.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3.2. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
