### ISSUE TITLE
Setting $(EnableLLVM) to true adds to the APK size increase of APKs built by Xamarin.Android 10.0.0.43 vs. 9.4.1.1

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#3724]
This is a new item for discussion about size increases related to `$(EnableLLVM)`, previously discussed in <https://github.com/xamarin/xamarin-android/issues/3454>. It seems that `$(EnableLLVM)` might have itself introduced a size increase, adding to the (perhaps expected) increases in size of the managed input assemblies.

*tranb3r commented on Sep 5 <https://github.com/xamarin/xamarin-android/issues/3454#issuecomment-528239560>*

> Apk size:
> - vs 16.3.0 preview 1.0 : 24438 kB
> - vs 16.3.0 preview 3.0 : 26688 kB
> 
> I'm using AOT+LLVM, and the average increase of .so files seems to be around 10.5%.
> But interestingly, the increase of libmonodroid_bundle_app.so (bundle of the dlls) is only about 2.5%.
> So maybe there is another issue specific to aot/llvm ?
> 
> About java bindings, I'm using a lot of nugets, and I have no idea how many of them contain java bindings. But pretty much every single .so file is increasing in size in the apk.

 * * *

*tranb3r commented on Sep 24 <https://github.com/xamarin/xamarin-android/issues/3454#issuecomment-534469494>*

> Here is the correct comparison between 16.3-pre1 and 16.3-pre3:
> ![apksize](https://user-images.githubusercontent.com/12516566/65498359-09bb5280-debc-11e9-8a30-f9773b3ba34b.png)
> 
> As you can see, the size difference for so libs is quite important (+11%), much more than the impact on dlls (+2.5%), which results in apk size increasing by +9%.
> This is why I think there is still an issue that needs to be explained / fixed.
> 
> Or maybe I've made another mistake ? Could you please double check with another app and confirm my results ?

* * *
*tranb3r commented on Sep 25 <https://github.com/xamarin/xamarin-android/issues/3454#issuecomment-535055403>*

> Here is more data from our app (same code compiled with different versions of VS 2019) :
> 
> VS2019 | Xamarin.Android | APK (kB) | lib\arm64-v8a (B) | libmonodroid_bundle.so (B) | classes.dex (B)
> -- | -- | -- | -- | -- | --
> 16.2.0 | 9.4.0.51 | 24679 | 60196936 | 6579296 | 3207436
> 16.2.1 | 9.4.1.0 | 29321 | 76671880 | 7979888 | 3816684
> 16.2.4 | 9.4.1.1 | 24916 | 61047856 | 6656880 | 3208892
> 16.3.0 | 10.0.0.43 | 26687 | 67170624 | 6754992 | 3054440
> 
> Here are our conclusions:
> - the original linker bug was introduced in xamarin.android 9.4.1.0 (shipped with vs 16.2.1 stable), resulting in a huge increase of apk size.
> - the linker bug was then fixed in xamarin.android 9.4.1.1 (shipped with vs 16.2.4 stable), and the apk size was almost back to normal.
> - however, for some unexplained reason, in xamarin.android 10.0.0.43 (shipped with vs 16.3.0 stable), the apk size increases again, mostly because of aot libs (the bundle of dlls also increases but less the aot libs ; and the classes.dex file size decreases).
> 
> Could you please provide an explanation ? This is kind of serious for us.

**Comment by tranb3r** [comment]
@brendanzagaeski Thanks for opening this issue.
Our setup is AOT+LLVM, but I've never assumed the issue is related to LLVM, and we probably have the same issue with AOT only.
We're going to check that and report more data asap.

**Comment by brendanzagaeski** [comment]
*Preliminary investigation notes for the Microsoft team*

### Steps tested

 1. Create a new master–detail Mobile App targeting Android, using the project template in Visual Studio Enterprise 2019 version 16.2.5.

 2. Package the app in the Release configuration with `AotAssemblies`, `EnableLLVM`, and `BundleAssemblies` each set to `true` or `false`:

    `msbuild -restore -p:Configuration=Release -p:AotAssemblies=true -p:EnableLLVM=true -p:BundleAssemblies=true -t:PackageForAndroid`

### Behavior

For comparison, relative size of tranb3r's APK for 10.0.0.43 vs. 9.3.0.23:
1.071

Relative APK sizes for the master-detail Mobile App template:

| Aot | LLVM | Bundle | 10.0.0.43 vs. 9.4.1.1 | 9.4.1.1 vs. 9.3.0.23 |
| --- | ---- | ------ | --------------------: | -------------------: |
| ✅  | ✅   | ✅     |                 1.085 |                0.984 |
| ✅  | ✅   | 🚫     |                 1.077 |                0.986 |
| ✅  | 🚫   | ✅     |                 1.020 |                1.039 |
| ✅  | 🚫   | 🚫     |                 1.019 |                1.035 |
| 🚫  | 🚫   | ✅     |                 1.053 |                0.981 |
| 🚫  | 🚫   | 🚫     |                 1.043 |                0.985 |

<details>
<summary>Additional data: Raw APK sizes</summary>

| Aot | LLVM | Bundle | APK size (kB) 10.0.0.43 | APK size (kB) 9.4.1.1 | APK size (kB) 9.3.0.23 | 
| --- | ---- | ------ | ----------------------: | --------------------: | ---------------------: | 
| ✅  | ✅   | ✅     |                  33,902 |                31,235 |                 31,734 | 
| ✅  | ✅   | 🚫     |                  37,229 |                34,554 |                 35,050 | 
| ✅  | 🚫   | ✅     |                  34,557 |                33,873 |                 32,602 | 
| ✅  | 🚫   | 🚫     |                  37,883 |                37,191 |                 35,918 | 
| 🚫  | 🚫   | ✅     |                  14,640 |                13,903 |                 14,167 | 
| 🚫  | 🚫   | 🚫     |                  17,967 |                17,222 |                 17,482 | 

</details>

From 9.3.0.23 to 9.4.1.1, sizes shrunk by about 1.6%, except for `AotAssemblies` without `EnableLLVM`, which grew by roughly 3.5%.

From 9.4.1.1 to 10.0.0.43, sizes grew by about 4.5% with no AOT, about 2% with `AotAssemblies`, and about 8% with `AotAssemblies` and `EnableLLVM`.

### Additional version information

Android NDK r19

**Comment by tranb3r** [comment]
@brendanzagaeski It could be worth looking at the break down per cpu architecture.

**Comment by radekdoulik** [comment]
@vargaz do you know about any issue in mono regarding AOT/llvm sizes recently? between the XA versions 9.4.1.1 and 10.0.0.43 there was a bump of mono from 2019-06 to 2019-08 branch.

**Comment by tranb3r** [comment]
More data from our app (10.0.0.43 vs 9.4.1.1):

AOT | LLVM | APK | lib\arm64-v8a
-- | -- | -- | --
✅ | ✅ | +7.1% | +10.0%
✅ | 🚫 | +1.4% | +2.6%
🚫 | 🚫 | +1.3% | +5.4%

So indeed the increase is bigger when using LLVM.

Note: we're using NDK 20.

**Comment by tranb3r** [comment]
@brendanzagaeski @vargaz Any progress?

**Comment by Akademiksdc** [comment]
@brendanzagaeski @vargaz what is the status on this ticket?

**Comment by tranb3r** [comment]
@brendanzagaeski @vargaz @radekdoulik 
Come on guys, we need answers !!!

**Comment by Akademiksdc** [comment]
@radekdoulik @vargaz @brendanzagaeski 

Could you please provide some updates, how it's going on?

**Comment by brendanzagaeski** [comment]
Apologies that there hasn't been much movement here. I'll ask a couple other folks about this issue to see if there's any news available about the plans for investigation.

**Comment by brendanzagaeski** [comment]
*Notes for the Microsoft team*

Out of curiosity, I tried adding `-Os` or `-Oz` to `llvmopts` (e.g., `-p:AndroidAotAdditionalArguments=llvmopts="-Oz"`) to see if those had any effect on final APK size. At least in my quick tests, those options only decreased the APK size by a couple of kilobytes.

**Comment by tranb3r** [comment]
We've been waiting for a fix for several months now. How come nobody is able to identify the commit responsible for this regression and fix it ?!?
Considering the number of open issues we're following and that do not show any progress at all, we're really starting to lose faith in xamarin.
cc @migueldeicaza

**Comment by lewurm** [comment]
The Mono runtime upgraded to a newer LLVM version (from 3.6 to 6.x), so there are significant changes in terms of how code is generated. While apparently the code size has changed, there should also be another implication: Better execution time.

In general, if your main concern is APK size, you shouldn't use AOT at all (with or without LLVM). AOT+LLVM is ought to be for users doing computational intensive tasks in their app, otherwise it isn't really needed.

**Comment by tranb3r** [comment]
@lewurm Thank you for the explanation. 
Like most mobile app developers, our concern is finding the best tradeoff between startup time and app size.
So, could you please make sure that this kind of upgrade (and the expected impact) is mentionned in the release notes of visual studio and xamarin.android ?

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
