### ISSUE TITLE
android.support.design.widget.TabLayout tabs are not visible

### ISSUE THREAD

**Issue by SavikPavel** [xamarin/xamarin-android#3741]
Hello Xamarin team,

We have a problem with TabLayout. With the latest Xamarin.Android updates tabs are no longer visible (the first tab content is visible, but there is no way to switch to any other tab). We've created a sample project and attached it below. 

Google Pixel 2XL with Android 9 installed was used for testing.

Note, that this only started after the latest Xamarin.Android update, it worked as expected before.

### Steps to Reproduce

1. Create ViewPager with TabLayout inside.
2. Create several Fragments and save them in the FragmentPagerAdapter
3. Open the app

[TabsTest.zip](https://github.com/xamarin/xamarin-android/files/3690058/TabsTest.zip)

### Expected Behavior
The first tab content is visible and there is a way to switch to the other tabs.
### Actual Behavior
The first tab content is visible BUT there is NO way to switch to the other tabs.
### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.3.1 (build 18)
Installation UUID: 8aceef2e-ed99-4d1c-a0b1-42f53ffef5d7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.2.300
	2.2.101
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.2.5
	2.2.0
	2.1.13
	2.1.9
	2.1.2
	2.1.1

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.244
Hash: e15b2ee97
Branch: remotes/origin/d16-3
Build date: 2019-09-25 00:03:16 UTC

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/pavelsavik/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/pavelsavik/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803010018
Git revision: 272ab73f00ab2b13ec97dc8b31d02980cf66d47f
Build date: 2019-09-27 19:26:51+00
Build branch: release-8.3
Xamarin extensions: 451b00e65052c11c16b79e6d31a24c4cf0d1b794

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by SavikPavel** [comment]
Same problem after the latest updates:

Visual Studio 8.3.2 (build 32)
Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
Xamarin.Android 10.0.3.0 (Visual Studio Community)

**Comment by radekdoulik** [comment]
@garuma not sure whether that belongs to the designer or XA team?

**Comment by SavikPavel** [comment]
Any news on this? Have you been able to reproduce the issue?

**Comment by SavikPavel** [comment]
@radekdoulik, @garuma, any news about when would this be fixed? 
It's really blocking us. We need to downgrade a Xamarin.Android version to make a release, that's really annoying.

**Comment by SavikPavel** [comment]
If anyone is still interested (which I doubt), the issue is still there with the latest updates:
Visual Studio 8.3.7 (build 1)
Xamarin.Android 10.0.6.2 (Visual Studio Community)

**Comment by rakul1064** [comment]
Hi, I'm also facing same problem. 
android.support.design.widget are not working as expected on VS Mac 8.3.11.
Anyone having solution for this?

**Comment by SavikPavel** [comment]
@rakul1064,  I do have a "workaround", but I'm not really sure if it will be applicable to you. We do not need swipes in our app, so I just removed ViewPager and used FrameLayout as a content container instead. Then, when the tab is selected in the TabLayout, I'm just replacing the Fragment in the FrameLayout manually.

**Comment by jpobst** [comment]
The Android Support libraries have been deprecated and are no longer supported.  Hopefully AndroidX supports this scenario better.
