### ISSUE TITLE
Handler JNI Null Pointer Exception

### ISSUE THREAD

**Issue by llzz19851985** [xamarin/xamarin-android#3755]
### Steps to Reproduce

Because some reason,I need modal dialog like WPF,So I Use reflect to loop ui thread:
![JNI_loop](https://user-images.githubusercontent.com/1481403/66467699-70915c00-eab7-11e9-8387-d3a2a2af5834.jpg)

when cancel the dialog,it crash  directory,exception message as follow:
![JNI_CRASH](https://user-images.githubusercontent.com/1481403/66467293-cfa2a100-eab6-11e9-9f41-c54a0ac48d66.jpg)

please help ! thanks

**Comment by radekdoulik** [comment]
I am not sure what is your reasoning here to use JNIEnv directly. Couldn't you use our binding of Looper class? https://docs.microsoft.com/en-us/dotnet/api/android.os.looper?view=xamarin-android-sdk-9

**Comment by llzz19851985** [comment]
use looper directory here is the same error,is there a way to show a dialog with sync result?
the reason why I need modal dialog is my current project is shared most logic with a wpf project,and in logical level there are hundreds of methods depends on the modal dialog result,I found use looper.loop() in java is ok and no exception,but in xamarin android ,it throw null pointer exception.

**Comment by jonathanpeppers** [comment]
@llzz19851985 can you attach a small sample project that reproduces the issue?

**Comment by jonathanpeppers** [comment]
Closing for now, let us know if you can send a sample project, thanks!
