### ISSUE TITLE
Native crash (SIGABRT): assertion at mini-arm64.c:883, condition `ji' not met

### ISSUE THREAD

**Issue by knocte** [xamarin/xamarin-android#3777]
### Steps to Reproduce

1. I have deployed the following app to the Android AppStore: https://github.com/knocte/geewallet/tree/frontend
2. I installed in several phones.
3. I launch the app in all phones.

### Expected Behavior

It should launch on all phones equally.

### Actual Behavior

I have detected that in a single phone, mono runtime seems to be exploding with a native crash. (Other phones are not affected.)

### Version Information

```
Visual Studio Community 2019 for Mac
Version 8.3.2 (build 32)
Installation UUID: 8f58d412-39f9-4748-a7e7-823e702ef3f4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

Mono Framework MDK
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11
	2.1.9

Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 10.0.3.0 (Visual Studio Community)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/knocte/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Microsoft Mobile OpenJDK
Java SDK: /Users/knocte/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

Android Device Manager
Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

Xamarin Designer
Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

Apple Developer Tools
Xcode 11.0 (14936)
Build 11A420a

Xamarin.Mac
Version: 6.2.0.47 (Visual Studio Community)
Hash: c2cbd3480
Branch: d16-3
Build date: 2019-09-30 22:37:32-0400

Xamarin.iOS
Version: 13.2.0.47 (Visual Studio Community)
Hash: c2cbd3480
Branch: d16-3
Build date: 2019-09-30 22:37:32-0400

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 803020032
Git revision: cac56af22091d80a4c339532595ed90228d87eb0
Build date: 2019-10-04 06:43:01+00
Build branch: release-8.3
Xamarin extensions: 2fc34e1d5c594f52abf0e0e9e14f4945adec6c7f

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

### Log File

I have screenshots of the crash:
![monodroid-bug-screenshot](https://user-images.githubusercontent.com/331303/66696495-b6883300-ecf6-11e9-9929-78cfbce5d657.jpeg)

**Comment by knocte** [comment]
It seems github doesn't let me upload the .apk file to this issue, so if anyone wants it, I'll send it via email.

**Comment by knocte** [comment]
> doesn't let me upload...

I've uploaded the 2 APKs (original and derived) here: https://github.com/knocte/geewallet/blob/bugreport/monodroid-sigabrt/geewallet.v144-apks.zip

**Comment by lewurm** [comment]
In terms of symptoms it looks very much like https://github.com/mono/mono/issues/14080
Depending on the hardware the symptoms occurred due to two different bugs: 
* https://github.com/mono/mono/commit/06e63b345f0be60008597784d1cc8b3251bf60fa
* https://github.com/mono/mono/commit/b2739b5196250a467ce0c315b3fc93065267bfee

Both fixes have been backported to `2019-08`. @grendello are there any Xamarin.Android builds with the mono branch that @knocte could try?

**Comment by jonpryor** [comment]
The forthcoming Xamarin.Android 10.1 in Visual Studio 16.4 Preview 2 should have those fixes.

**Comment by grendello** [comment]
The download URLs can be found here: https://github.com/xamarin/xamarin-android/#downloads

**Comment by knocte** [comment]
Sorry but I prefer to stay in the stable channel, due to the fear of going to the Preview channel and breaking my environment in a way I can't go back (except for formatting my OS). I only have one dev env so...

Anyway, I have to say that after releasing version 146 of my app (notice that I reproduced the bug with v144) I no longer can reproduce the bug. I did very minimal changes so I doubt it is related at all with anything I did. I'll install again v144 manually today in the phone where I reproduced it, to see if the bug is still there.

**Comment by knocte** [comment]
> I no longer can reproduce the bug

I take that back, I could reproduce the bug many times with a particular phone (Sony Xperia).

> Sorry but I prefer to stay in the stable channel

Thankfully, Visual Studio for Windows has received the 16.4 update in the stable channel, and I released a new apk with this new version, which seems to fix the problem.

Any idea when is 16.4 coming to Visual Studio for Mac? IMO these releases should trigger in both Windows and Mac, otherwise for teams that use different OSs for working in the same app, they end up using different versions of Mono and these discrepancies may bring many headaches and problems.

**Comment by brendanzagaeski** [comment]
Many thanks for verifying the candidate fix for this issue on Windows! Now that a corresponding Release version is also available on macOS, I'll add the version info details and close this issue.

* * *

*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
