### ISSUE TITLE
Measure profiled AOT performance with larger app

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#3793]
Lets use larger XF app to compare various scenarios and their performance.

**Comment by radekdoulik** [comment]
App: https://github.com/microsoft/SmartHotel360
Device: Pixel 2 XL
OS: Android 10

Results (average of 10 runs per configuration)

|                               | Release | Release/AOT | Release/Profiled AOT | Release/Custom Profiled AOT |
|-------------------|---------|--------------|----------------------|-------------------------------|
| Activity displayed | 4863ms | 2086ms | 3655ms | 1900ms |
| Last timing message | 6971ms | 4018ms | 5733ms | 3868ms |

**Comment by JonDouglas** [comment]
@bellissimo Custom profiled AOT refers to being able to use your own "custom profile" which can be recorded and used for you application. This differs from Profiled AOT as Profiled AOT is a default profile based on your project type (Xamarin.Forms vs. Xamarin.Android).
