### ISSUE TITLE
Android App Bundle: disable types of configuration APKs

### ISSUE THREAD

**Issue by uwe-neuronation** [xamarin/xamarin-android#3813]
It seems to be not possible to configure the Android App Bundle.

Native Android has an option to **enableSplit** in the build.gradle. Thats missing on Xamarin.

```
android {
    // When building Android App Bundles, the splits block is ignored.
    splits {...}

    // Instead, use the bundle block to control which types of configuration APKs
    // you want your app bundle to support.
    bundle {
        language {
            // Specifies that the app bundle should not support
            // configuration APKs for language resources. These
            // resources are instead packaged with each base and
            // dynamic feature APK.
            enableSplit = false
        }
        density {
            // This property is set to true by default.
            enableSplit = true
        }
        abi {
            // This property is set to true by default.
            enableSplit = true
        }
    }
}
```

https://developer.android.com/studio/projects/dynamic-delivery/configure-base#disable_config_apks

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published on Windows that includes new functionality for this item. The functionality is not yet included in a Release version. I will update this item again when a Release version is available that includes the functionality.

The change is not yet available on macOS. I will update this item again when a Preview version with the change is available on macOS.

New functionality included in Xamarin.Android 10.2.100.7

New functionality included on Windows in Visual Studio 2019 version 16.6 Preview 1. To try the Preview version that includes the change, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

New functionality not yet available on macOS.

* * *

The new functionality allows a [*BundleConfig.json*](https://developer.android.com/studio/build/building-cmdline#bundleconfig) file to be specified for the Xamarin.Android project by using the `AndroidBundleConfigurationFile` MSBuild property:

```xml
<PropertyGroup>
  <AndroidBundleConfigurationFile>BundleConfig.json</AndroidBundleConfigurationFile>
</PropertyGroup>
```

See the [release notes](https://github.com/xamarin/xamarin-android/releases/tag/v10.2.100.7#support-for-android-app-bundle-configuration-files-1021007) for additional information.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published on macOS that includes new functionality for this item. The functionality is not yet included in a Release version. I will update this item again when a Release version is available that includes the functionality.

New functionality included in Xamarin.Android 10.3.0.33.

New functionality included on macOS in Visual Studio 2019 for Mac version 8.6 Preview 1. To try the Preview version that includes the change, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(New functionality also included on Windows in Visual Studio 2019 version 16.6 Preview 1 and higher. To try the Preview version that includes the change, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).)

* * *

The new functionality allows a [*BundleConfig.json*](https://developer.android.com/studio/build/building-cmdline#bundleconfig) file to be specified for the Xamarin.Android project by using the `AndroidBundleConfigurationFile` MSBuild property:

```xml
<PropertyGroup>
  <AndroidBundleConfigurationFile>BundleConfig.json</AndroidBundleConfigurationFile>
</PropertyGroup>
```

See the [release notes](https://github.com/xamarin/xamarin-android/releases/tag/v10.2.100.7#support-for-android-app-bundle-configuration-files-1021007) for additional information.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes new functionality for this item.

New functionality included in Xamarin.Android 10.3.1.0.

New functionality included on Windows in Visual Studio 2019 version 16.6. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

New functionality included on macOS in Visual Studio 2019 for Mac version 8.6. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

* * *

The new functionality allows a [*BundleConfig.json*](https://developer.android.com/studio/build/building-cmdline#bundleconfig) file to be specified for the Xamarin.Android project by using the `AndroidBundleConfigurationFile` MSBuild property:

```xml
<PropertyGroup>
  <AndroidBundleConfigurationFile>BundleConfig.json</AndroidBundleConfigurationFile>
</PropertyGroup>
```

See the [release notes](https://docs.microsoft.com/xamarin/android/release-notes/10/10.3#support-for-android-app-bundle-configuration-files) for additional information.

**Comment by SymboLinker** [comment]
Just a note for others trying to implement this:

I tried implementing this with a BundleConfig.json content:
```
android {
    bundle {
        language {
            enableSplit = false
        }
    }
}
```

but then the packaging **failed**. The error message was:

"Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: a. Path '', line 0, position 0."

Packaging **succeeded** with the following content:

```
{
  "optimizations": {
    "splitsConfig": {
      "splitDimension": [{
        "value": "LANGUAGE",
        "negate": true
      }]
    }
  }
}
```

**Comment by jonathanpeppers** [comment]
This isn't valid JSON:
```
android {
    bundle {
        language {
            enableSplit = false
        }
    }
}
```
It looks like groovy? Maybe a gradle script?

Use valid JSON as described here: https://developer.android.com/studio/build/building-cmdline#bundleconfig
