### ISSUE TITLE
Xamarin.Android - how to add override keyword when binding method

### ISSUE THREAD

**Issue by jpiechowiak** [xamarin/xamarin-android#3825]
### Steps to Reproduce
Hi,
I try to bind aar library to Xamarin and I'm receiving following error:
'TaggingSender' does not implement inherited abstract member 'AsyncTask.DoInBackground(params Object[])'
and in obj directory I've something like this:
```csharp
// Metadata.xml XPath method reference: path="/api/package[@name='com.adition.android.sdk.tagging']/class[@name='TaggingSender']/method[@name='doInBackground' and count(parameter)=1 and parameter[1][@type='java.lang.Void...']]"
[Register ("doInBackground", "([Ljava/lang/Void;)Ljava/lang/Boolean;", "GetDoInBackground_arrayLjava_lang_Void_Handler")]
protected virtual unsafe global::Java.Lang.Boolean DoInBackground (params global::Java.Lang.Void[] voids)
{
    //
}
```

After this I tried to modify metadata.xml with following lines:
```xml
<attr path="/api/package[@name='com.adition.android.sdk.tagging']/class[@name='TaggingSender']/method[@name='doInBackground' and count(parameter)=1 and parameter[1][@type='java.lang.Void...']]/parameter[1]" name="managedType">params Java.Lang.Object[]</attr>
<attr path="/api/package[@name='com.adition.android.sdk.tagging']/class[@name='TaggingSender']/method[@name='doInBackground' and count(parameter)=1 and parameter[1][@type='java.lang.Void...']]" name="managedReturn">Java.Lang.Object</attr>
```

Now method signature is fixed, but override keyword is missing.. How to add override keyword, or resolve this situation in other way?
```csharp
// Metadata.xml XPath method reference: path="/api/package[@name='com.adition.android.sdk.tagging']/class[@name='TaggingSender']/method[@name='doInBackground' and count(parameter)=1 and parameter[1][@type='java.lang.Void...']]"
[Register ("doInBackground", "([Ljava/lang/Void;)Ljava/lang/Boolean;", "GetDoInBackground_arrayLjava_lang_Void_Handler")]
protected virtual unsafe global::Java.Lang.Object DoInBackground (params global::Java.Lang.Object[] voids)
{
    // 
}
```

### Version Information
Visual Studio 16.3.1
Xamarin.Android.Sdk 10.0.0.43

**Comment by jpobst** [comment]
Does removing the `params` fix it?

**Comment by jpiechowiak** [comment]
Yes, it does. Fortunately I didn't need this in interface.
Thank you.

**Comment by lucafabbri** [comment]
Hi, the solution is not clear. How can be params removed?

**Comment by jpiechowiak** [comment]
@lucafabbri You can remove something from public interfaces (if you won't be calling this code from .Net). This things are still available in library internally.

**Comment by lucafabbri** [comment]
Thx for the prompt reply, I'm sorry but I'm quite new with Binding. Could you point out some documentation where understand how to remove? I have the same issue as above (DoInBackground) and it is not necessary to call it from C#

**Comment by jpiechowiak** [comment]
Here is the section on microsoft docs: https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/

Here you can find particular article about metadata.xml
https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/customizing-bindings/java-bindings-metadata

And here is for instance sample metadata.xml from one of Facebook libraries binded by Microsoft: 
https://github.com/xamarin/FacebookComponents/blob/master/Facebook.Android/source/facebook-core/transforms/Metadata.xml

**Comment by donatellijl** [comment]
@jpiechowiak Hi, can you post the xml you used to remove the params? I have this exact problem. I edited the metadata to change the param and return type to Java.Lang.Object and removed the virtual keyword by setting "final" to false. 

I also tried removing the node as a whole, but still got the error that it doesn't implement the abstract member.

My Metadata.xml so far:
<attr path="/api/package[@name='com.xrite.targetextraction']/class[@name='ImageSaveAsyncTask']/method[@name='doInBackground' and count(parameter)=1 and parameter[1][@type='java.lang.Void...']]" name="final">true</attr>
    <attr path="/api/package[@name='com.xrite.targetextraction']/class[@name='ImageSaveAsyncTask']/method[@name='doInBackground' and count(parameter)=1 and parameter[1][@type='java.lang.Void...']]/parameter[1]" name="managedType">params Java.Lang.Object[]</attr>
    <attr path="/api/package[@name='com.xrite.targetextraction']/class[@name='ImageSaveAsyncTask']/method[@name='doInBackground' and count(parameter)=1 and parameter[1][@type='java.lang.Void...']]" name="managedReturn">Java.Lang.Object</attr>

**Comment by jpiechowiak** [comment]
@donatellijl 
Unfortunately I don't have access to this code anymore. 
But in general, if this method doesn't compile and you don't need this, then you might consider to remove it - just like in this article: https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/customizing-bindings/java-bindings-metadata
