### ISSUE TITLE
[Bug] Visual Studio 2019 Create new configuration from "Release" does not archive

### ISSUE THREAD

**Issue by acaliaro** [xamarin/xamarin-android#3835]
### Description
I have an XF project. I would like to create a new "Configuration" starting from Release. I create one "ReleaseTest" copying from "Release". I switch from "Release" to "ReleaseTest" and try to "Archive" my Android project but it fails with a message like **Please ensure that you are using a release configuration and that "Use Shared Mono Runtime" option unchecked.** (It's in italian so I does not if it's correct).

### Steps to Reproduce

1. Create a new Configuration starting from "Release"
2.  Archive the Android project
3. 

### Expected Behavior
It should create an archive...

### Actual Behavior
The archive is not created and I have a **Please ensure that you are using a release configuration and that "Use Shared Mono Runtime" option unchecked.** error

### Basic Information

- Version with issue:
- Last known good version: unknown
- IDE: Visual Studio 2019 16.3.5
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by IngweLand** [comment]
Just to add to that issue. It looks like Archiving fails in general, if current selected configuration is not "Release". Same way, I created new configuration, double-checked that all properties in both configurations are same, still, archiving does not work for new configuration.

**Comment by pjcollins** [comment]
Is this only failing when using a project configuration named something other than `Release`? It's possible that we're actually looking for the string `Release` in the configuration when attempting to archive. Could you paste the content of the full `PropertyGroup` for this configuration? Specifically, does it include the following?
```xml
<AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
```

**Comment by pjcollins** [comment]
Does disabling these debug options allow archiving to work for you in this custom configuration?

**Comment by acaliaro** [comment]
Yes

**Comment by pjcollins** [comment]
I'm glad that the workaround is working at least.

@joj is this something we have some control over? It looks like [our targets](https://github.com/xamarin/xamarin-android/blob/bbd034fc9e7e3f2911a1de54fc1519a6727cfa15/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L210) control fastdev behavior by checking the `Optimize` property (if neither of the two relevant properties are set explicitly). `Optimize` is set to true when creating a new Configuration from the Release configuration. It seems like the IDE may be doing some different evaluation when determining if newly created project configurations should have fast deployment enabled?

**Comment by joj** [comment]
We don't control the new configurations at all, and also I'm not sure we actually know where that new configuration was a copy of. OTOH, a copy should have the Optimize set. Can you (@acaliaro or @pjcollins) add a suggestion in developer community so we can track it and see if there's anything we can do about it? Thanks!

**Comment by jpobst** [comment]
The shared runtime was removed in Xamarin.Android 11.2, so I think we can close this.
https://github.com/xamarin/xamarin-android/releases#rewritten-fast-deployment-system-11199168
