### ISSUE TITLE
Build Problem On XF Apps and Google Ads

### ISSUE THREAD

**Issue by slink99** [xamarin/xamarin-android#3836]
### Description
Unexpected Element found in - AndroidManifest.xml
### Steps to Reproduce

1. Create New XF Android project
2. Add MarcTron Admob from NuGet
3. Build Android Project

### Expected Behavior
Correct build, no issues
### Actual Behavior
`<activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent" />` is placed before the `<application>` tag, causing the "unexpected element" error

### Basic Information

- Version with issue: VS 16.3.6 XF 16.3.0.246
- Last known good version: VS 16.1.3
- IDE:
- Platform Target Frameworks: 
  - Android: 9.0  
- Nuget Packages: MarcTron.Admob 1.4.4
- Affected Devices:

### Reproduction Link

https://stackoverflow.com/questions/58467582/visual-studio-2019-xamarin-forms-google-ads-build-problem

**Comment by pjcollins** [comment]
@slink99 is this happening in the generated manifest in `obj/Debug/android/AndroidManifest.xml`? I just attempted this and my manifest file does have these entries imported correctly:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.testmanifestbuild">
  ...
  <application android:label="TestManifestBuild.Android" android:name="android.app.Application" android:allowBackup="true" android:icon="@mipmap/icon" android:debuggable="true">
    <activity android:configChanges="orientation|screenSize" android:icon="@mipmap/icon" android:label="TestManifestBuild" android:theme="@style/MainTheme" android:name="md51fe0e94f9a726ab53c236daae721f9d1.MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    ...
    <!-- Include the AdActivity and InAppPurchaseActivity configChanges and themes. -->
    <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:exported="false" android:theme="@android:style/Theme.Translucent" />
    <provider android:name="com.google.android.gms.ads.MobileAdsInitProvider" android:authorities="com.companyname.testmanifestbuild.mobileadsinitprovider" android:exported="false" android:initOrder="100" />
  </application>
  <uses-permission android:name="android.permission.WAKE_LOCK" />
</manifest>
```

Could you attach a [binary build log](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#save-a-binary-log) for a failing build? Also, would you be able to attach a project which reproduces this error?

**Comment by slink99** [comment]
The three projects I have this happening in are my apps, so I can't release that. Yes, it happens in the androidmanifest.xml also, as shown below.
```

<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="28" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.CALL_PHONE" />
  <uses-permission android:name="android.permission.LOCATION_HARDWARE" />
  <supports-screens android:largeScreens="true" android:xlargeScreens="true" />
  <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent" />
  <application android:label="NYWineryHopper.Android" android:icon="@drawable/icon" android:name="android.support.multidex.MultiDexApplication" android:allowBackup="true" android:debuggable="true">
It has the two you are showing in the same place along with the incorrect acticity. I am guessing it is possible that this is caused by another of the NuGet packages, although not sure which one it may be. I also have:
NetStandard.Library 2.0.3
Newtonsoft.Json 12.0.2
Plugin.CurrentActivity 2.1.0.4
Plugin.Permissions 3.0.0.12
Refractored.MvvmHelpers 1.3.0
sqlite-net-pcl 1.6.292
Xamarin.Android.Support.Design 28.0.0.3
Xamarin.Android.Support.v4 28.0.0.3
Xamarin.Android.Support.v7.AppCompat 28.0.0.3
Xamarin.Android.Support.v7.CardView 28.0.0.3
Xamarin.Android.Support.v7.MediaRouter 28.0.0.3
Xamarin.Essentials 1.3.1
Xamarin.Forms 4.3.0.908675
Xamarin.Google.iOS.MobileAds 7.47.0 (only iOS project)
Xamarin.GooglePlayServices.Ads.Lite 71.1720.1 (only Android project)

In the working apps, I didn't have Ads.Lite but the absence or presence doesn't seem to make a difference with this problem.
```

**Comment by pjcollins** [comment]
I tried this again today with the latest 16.3.10 version of VS 2019 and was still unable to reproduce with a new Xamarin Forms app after adding the NuGet packages listed above. I also tried to modify a project with a custom application class as it looks like your app is doing the same, but my AndroidManifest was constructed correctly with that project as well.

If you're unable to upload a repro, would you be able to provide the [binary build log](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#save-a-binary-log) for a build which produces this broken manifest? We'll need some more information to try to investigate further.

**Comment by jonathanpeppers** [comment]
@slink99 let us know if you can send a build log or a sample and we can take another look, thanks!
