### ISSUE TITLE
Remove MD5 use in d16-5

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#3844]
Commit 88a1d6cd88e68bda208a6eb05d99d802c7800d2e changed the default Java package name algorithm from md5 to CRC64, controllable via the `$(AndroidPackageNamingPolicy)` MSBuild property.

We need to *entirely* remove support for md5 for d16-5.

**Comment by jpobst** [comment]
I think this has been long completed.  We removed all usage to comply with MS Security policy and have automated scans on our builds to ensure no MD5 usage sneaks back in.
