### ISSUE TITLE
Check for to-be-removed APIs

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#3845]
We know that in the .NET 5 timeframe, certain APIs such as `System.AppDomain.CreateDomain()` will no longer work.

We should updat the `<LinkAssemblies/>` task/etc. to check for these to-be-altered APIs and start warning about them, so that the community has time to migrate away from them before .NET 5 ships.

**Comment by radekdoulik** [comment]
Implemented by https://github.com/xamarin/xamarin-android/pull/3974
