### ISSUE TITLE
Building Xamarin Android on Windows fails on PrepareExternal

### ISSUE THREAD

**Issue by kant2002** [xamarin/xamarin-android#3847]
### Steps to Reproduce

1. `git clone `
2. `msbuild Xamarin.Android.sln /t:PrepareExternal`

### Expected Behavior

Build without errors.

### Actual Behavior

```
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  Preparing external GIT dependencies
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

    * Reading external dependencies from .external
      * xamarin/monodroid (7f40abfa6f55a801619973af0cb875bf5a58c0c9)
      * mono/mono (8946e49a974ea8b75fe5b8b7e93ffd4571521a85)

  Updating external repositories
    * monodroid
      -> cloning from xamarin/monodroid
  stderr | Cloning into 'monodroid'...
  Working... 00:00:00.2506666
  stderr | remote: Repository not found.
  stderr | fatal: repository 'https://github.com:/xamarin/monodroid/' not found
  Elapsed: 00:00:02.1529601
```

**Comment by eman1986** [comment]
this is also an issue with the linux build, this step fails every time when it tries to clone that repo

**Comment by grendello** [comment]
@kant2002 @eman1986 you can safely ignore this target, it is meant for internal commercial builds. Running `make prepare` on Linux/macOS or `msbuild /t:Prepare` on Windows is sufficient to get a local build. With that, @jonpryor suggested that we rename the target to `PrepareInternal` which may make sense as the name might be misleading.

**Comment by kant2002** [comment]
Thanks. That make sense now. What was misleading for me is that step was outlined optional, but there no indication what was step for building commercial version. I can reason that it would not work, but at the same time it would be interesting exercise to me to look into that target. 

So if you put a word on that, that will also help. Even if target is internal I may incorrectly deduce that this target is internal to xamarin-Android project, not internal to Microsoft
