### ISSUE TITLE
How to bind an Android Library which is build using Data Binding

### ISSUE THREAD

**Issue by basheerkohli** [xamarin/xamarin-android#3853]
### Steps to Reproduce

1. Create Android Library with data binding enabled using android studio. 
2. Now try to create DLL for the android library using visual studio.
3. Build process is success. But you won't find classes relating to the Data Binding.
4. In the Build logs you will find a warning 
[ noClassDefFoundError: Landroidx/databinding/DataBinderMapperImpl ]

**Comment by moljac** [comment]
@basheerkohli 
Databinding in Android (Android.Studio) relies on gradle plugin[s] what would map to MSBuild Tasks, Targets and of course Custom Tasks. This is a lot and needs resources (analysis, design and coding-implementation)

Thus we did not bind Databinding group (and artifacts). 

We redirect people to use Xamarin (XAML) databindings infrastructure. I know this is Xamarin.Android not Xamarin.Forms.

If you want we can discuss it. If you are willing to do some research (what gradle plugins do) and analysis it may turn out that effort is not too big. 

But, NO PROMISES from our side

**Comment by basheerkohli** [comment]
Hard to take that from you. But again thank you for your quick response @moljac .  I have generated an SDK in native with data binding enabled.  What you have said is correct as data binding relies on Gradle plugin[s] & has no issues while consuming the SDK from React Native, Ionic frameworks. But unfortunately, in this case, I have to think of the alternative  of replacing Data binding with old school view reference objects.  Thank you for the quick response. Cheers.

**Comment by paulzotov829** [comment]
Hi Did you fix it?

**Comment by moljac** [comment]
@paulzotov829 

He did not fix it. We do not support that (yet).

**Comment by 4brunu** [comment]
Any news or plans on supporting DataBinding or ViewBinding?

**Comment by moljac** [comment]
No. Not at the moment.

**Comment by moljac** [comment]
WIP

https://github.com/xamarin/AndroidX/pull/244

**Comment by 4brunu** [comment]
I'm leaving here this extra information in case it helps anyone.
Now that https://www.nuget.org/packages/Xamarin.AndroidX.DataBinding.ViewBinding/ is already published on NuGet, I was able to bind an Android library the uses View Binding.

In the begining I was havving the following error
```
Error CS0738: 'ActivityTimeBinding' does not implement interface member 'IViewBinding.Root'. 
'ActivityTimeBinding.Root' cannot implement 'IViewBinding.Root' because it does not have the matching return type of 'View'. (CS0738)
```

The solution I used was to remove the generated ViewBinding source from the public API by putting this in `Metadata.xml` and it worked.

```
    <remove-node path="/api/package[@name='com.example.mylibrary.databinding']" /> 
```

@moljac thanks for your help 🙂

**Comment by jeanraymonddaher** [comment]
Thank you for sharing @4brunu , it fixed my issue !

**Comment by nielsdelporte** [comment]
We're also seeing the `[ noClassDefFoundError: Landroidx/databinding/DataBinderMapperImpl ]` error when adding the following nuget packages to our main project. Adding the same packages to the bindings project for our native library did not make a difference.

```
<package id="Xamarin.AndroidX.DataBinding.DataBindingAdapters" version="4.1.2.1" targetFramework="monoandroid10.0" />
<package id="Xamarin.AndroidX.DataBinding.DataBindingCommon" version="4.1.2.1" targetFramework="monoandroid10.0" />
<package id="Xamarin.AndroidX.DataBinding.DataBindingRuntime" version="4.1.2.1" targetFramework="monoandroid10.0" />
<package id="Xamarin.AndroidX.DataBinding.ViewBinding" version="4.1.2.1" targetFramework="monoandroid10.0" />
```

Removing the `DataBinderMapperImpl` from the library in Metadata.xml doesn't yield any results either. 
```
    <remove-node path="/api/package[@name='com.example.databinding']" /> 
    <remove-node path="/api/package[@name='com.example']/class[@name='BR']" />
    <remove-node path="/api/package[@name='com.example']/class[@name='DataBinderMapperImpl']" />

```

Is there any update regarding this issue, @moljac ?

**Comment by 4brunu** [comment]
The problem is that the library that you are trying to use, uses DataBinding, which is not supported in Xamarin binding, AFAIK, only ViewBinding is supported.

**Comment by nielsdelporte** [comment]
Thanks, @4brunu! We dropped DataBinding and will only use ViewBinding for now, which is a big step forward already.
We only needed one NuGet binding in our main project and no Metadata.xml entries.

```
<package id="Xamarin.AndroidX.DataBinding.ViewBinding" version="4.1.2.1" targetFramework="monoandroid10.0" />
```

Is Data Binding being worked on, since this ticket has requested support for Data Binding and closed?
