### ISSUE TITLE
NoClassDefFoundError androidx/lifecycle/LifecycleOwner

### ISSUE THREAD

**Issue by basheerkohli** [xamarin/xamarin-android#3858]
### Steps to Reproduce

1. Create an Android SDK  in Android studio with AndroidX dependency.
2. Now try to create Binding library using the Visual studio .
3. Build the solution it will leads to build time issue saying noClassDefFoundError androidx/appcompat/AppCompatActivity.
4. Now add the  Xamarin.AndroidX.AppCompat Nugget Package.
5.Now again rebuild the solution , build process terminated with issue noClassDefFoundError
androidx/lifecycle/LifecycleOwner

**Comment by jpobst** [comment]
It looks like the Components team is aware of this issue and is investigating.  I'm going to close this issue in favor of their existing issue:

https://github.com/xamarin/AndroidSupportComponents/issues/223
