### ISSUE TITLE
Expose isLocationEnabled in Xamarin.Android.

### ISSUE THREAD

**Issue by KthProg** [xamarin/xamarin-android#3864]
isLocationEnabled was added in API 28, but has not yet been exposed.

https://developer.android.com/reference/android/location/LocationManager.html#isLocationEnabled()

**Comment by jpobst** [comment]
It's not in our documentation for some reason, but I do see it bound in `Mono.Android.dll`.

https://docs.microsoft.com/en-us/dotnet/api/android.locations.locationmanager

![image](https://user-images.githubusercontent.com/179295/67983320-6fed7080-fbf2-11e9-9407-b27732545b44.png)

If you don't see it, make sure you are targeting v9.0+.

**Comment by KthProg** [comment]
Aha! Our portable project that contains all our utility stuff was still targeting Android 8. Thanks!
