### ISSUE TITLE
IsLocationEnabled crashes on phones with API < 28.

### ISSUE THREAD

**Issue by KthProg** [xamarin/xamarin-android#3870]
### Steps to Reproduce

1. Call LocationManager.IsLocationEnabled on a device with API < 28

### Expected Behavior

Falls back to the API level-specific method, in this case, `Settings.Secure.GetInt(CrossCurrentActivity.Current.AppContext.ContentResolver, Settings.Secure.LocationMode) > 0`

### Actual Behavior

Crashes saying the method can't be found at the Java level.

### Version Information

Visual Studio 16.4 Preview 2
Targeting API 28 (Android 8, Oreo)

### Log File

None

**Comment by jpobst** [comment]
Unfortunately we simply wrap the Android libraries that Google provides, we rarely make attempts to change them.  In this case you will need to check the version of Android your app is running on and use fallbacks as necessary, just as if your app is written in Java.

https://developer.android.com/training/basics/supporting-devices/platforms#version-codes

**Comment by KthProg** [comment]
Ah, my bad. Based on some other APIs working I assumed Xamarin did something to make them compatible, but those APIs weren't as new as I thought.
