### ISSUE TITLE
Visual Studio 2019 Preview - Could not the file Mono.Android.Export

### ISSUE THREAD

**Issue by kanadaj** [xamarin/xamarin-android#3871]
### Steps to Reproduce

1. Build and deploy Xamarin.Forms .NET Core based Android project with VS 2019 Preview
2. Run the app
3. Open any page with a custom renderer to call ExportRenderer
4. Error: `System.IO.FileNotFoundException
  Message=Could not load the file 'Mono.Android.Export'.`

Note: Using the non-preview version of VS 2019 the project runs normally, so maybe it's cache related (does 2019 have a separate cache from 2019 preview?) or a problem with the preview tooling?

### Version Information

Microsoft Visual Studio Professional 2019 Preview
Version 16.4.0 Preview 2.0
VisualStudio.16.Preview/16.4.0-pre.2.0+29411.138
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

ASP.NET and Web Tools 2019   16.4.284.46185
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.4.284.46185
For additional information, visit https://www.asp.net/

AssemblyInfo Wizard   1.0
AssemblyInfo Wizard

Azure App Service Tools v3.0.0   16.4.284.46185
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.4.284.46185
Azure Functions and Web Jobs Tools

C# Tools   3.4.0-beta2-19504-06+154af84a603094b52bd08b3366c4448f7481af52
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.2.2   Build 192.0.20190828.114715
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20905.5

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.87+gbb515bf382
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.5.21 (2604ba1)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61910.04130
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10926.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.4.0-beta2-19504-06+154af84a603094b52bd08b3366c4448f7481af52
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19504.1+e3676d75d501a2df6789ad0f5ebc310bc2cee6b5
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.269 (d16-4@9202c30)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.289 (remotes/origin/d16-4@e3c99110c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.15 (51cdaa7)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.0.1 (d16-4/ee1dfb6)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5281037
    Java.Interop: xamarin/java.interop/d16-4@35b08ba
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.8.1.1 (2e360ee)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jpobst** [comment]
This is a bug that should be resolved in the upcoming 16.4 Preview 3.  

There is a workaround listed in this issue, or you can disable the shared runtime:
https://github.com/xamarin/xamarin-android/issues/3758
