### ISSUE TITLE
Android Bundle crashes as it can't find MP3 resource

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-android#3893]
### Steps to Reproduce

1. The app must execute this line of code to crash:
`var mediaPlayer = MediaPlayer.Create(this, Resource.Raw.beep)`
where 'beep' is MP3 file included in the project
2. The app must be distributed as AAB package

### Expected Behavior
This should work as APK file works without the problem
### Actual Behavior
The app crashes with the log:

> FATAL EXCEPTION: main
> Process: com.ls.sc, PID: 32322
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ls.sc/md5139d64b87f002fcb4c62ce68af5c3848.PActivity}: java.io.FileNotFoundException: beep.mp3
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
> 	at android.app.ActivityThread.access$1200(ActivityThread.java:152)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:135)
> 	at android.app.ActivityThread.main(ActivityThread.java:5538)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at java.lang.reflect.Method.invoke(Method.java:372)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
> Caused by: java.io.FileNotFoundException: beep.mp3
> 	at android.content.res.AssetManager.openAssetFd(Native Method)
> 	at android.content.res.AssetManager.openFd(AssetManager.java:329)
> 	at md5139d64b87f002fcb4c62ce69af5c3848.PActivity.n_onCreate(Native Method)
> 	at md5139d64b87f002fcb4c62ce69af5c3848.PActivity.onCreate()
> 	at android.app.Activity.performCreate(Activity.java:6013)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
> 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:184)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)

### Log File

Microsoft Visual Studio Community 2019
Version 16.3.8
VisualStudio.16.Release/16.3.8+29503.13
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA588
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.286.43615
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.286.43615
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.286.43615
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.286.43615
Azure Functions and Web Jobs Tools

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (master@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.278 (d16-3@40034cd)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.256 (remotes/origin/d16-3@8a223bfd7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.6.2 (d16-3/c407838)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@476d72b9e32
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Xamarin.iOS and Xamarin.Mac SDK   13.6.0.12 (e3c2b40)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonathanpeppers** [comment]
This should be fixed by: https://github.com/xamarin/xamarin-android/pull/3604

This change should already have shipped in the 16.4 preview release. Is the issue fixed there?

Alternatively, as a workaround you can set `mp3` files to be uncompressed manually with this setting:

![image](https://user-images.githubusercontent.com/840039/68609488-033c6680-047b-11ea-95c9-98c1ee66ef75.png)

**Comment by ivanicin** [comment]
I can confirm that setting that '.mp3' fixes the problem. Right now I am using the AppCenter for builds, so I can't test the previews.

**Comment by jonathanpeppers** [comment]
You actually _can_ test the previews on App Center!

https://github.com/jonathanpeppers/boots#app-center
