### ISSUE TITLE
Xamarin.Android application crashes when resuming

### ISSUE THREAD

**Issue by shults-s** [xamarin/xamarin-android#3894]
### Introduction
The ```MainActivity``` of the application hosts a ```ViewPager``` containing fragments of the type ```ScheduleFragment``` inherited from ```Fragment```. The ```ViewPager``` has an adapter that inherits from ```FragmentStatePagerAdapter```.

### Steps to Reproduce
1. In Android "Developer options" sets "Background process limit" to "At most 1 process".
2. Launch application and then send it to the background.
3. Launch one or more other applications (Chrome, YouTube, etc.), and then resume the application we launched earlier [it may be necessary to do this several times].

### Expected Behavior
The ```MainActivity``` (with ```ViewPager``` fragments) recreates and application continues to work.

### Actual Behavior
Application crashes with the exception: ```System.NullReferenceException``` at ```SmtuSchedule.Android.Views.ScheduleFragment.OnCreateView(...)```.

(A detailed log see below)

This problem is reproduced on all devices on which I tested the application: starting from Android 5.1 and ending with Android 9.0. Users say that in vivo (without setting the "Background process limit" parameter), the problem usually occurs when the application is in the background for a long time.
This is most likely an issue with the Activity and attached Fragment being destroyed and recreated. I tried to call ```base.OnCreateView (...)``` in the ```ScheduleFragment.OnCreateView (...)``` method, but that did not help.

Source code of ```ScheduleFragment``` [purely for example, to use this application after installation, it must be configured in a special way]:
https://github.com/shults-s/SmtuSchedule/blob/development/SmtuSchedule.Android/Views/ScheduleFragment.cs#L25

I googled that the same problem recently occurred with Xamarin.Forms in Visual Studio 2017, but I am using Xamarin.Android with Visual Studio 2019.

Same issue: https://stackoverflow.com/questions/46401047/xamarin-android-app-crashes-when-resuming

### Version Information
* Microsoft Visual Studio Community 2019 16.3.8
* Xamarin 16.3.0.278 (d16-3@40034cd)
* Xamarin.Android SDK 10.0.6.2 (d16-3/c407838)
* Mono: mono/mono/2019-06@476d72b9e32
* Java.Interop: xamarin/java.interop/d16-3@5836f58
* Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

### Log File
```
[09.11.2019 22:28:01.181] System.NullReferenceException.
Message: Object reference not set to an instance of an object
StackTrace:
  at SmtuSchedule.Android.Views.ScheduleFragment.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) <0x7f61709828 + 0x0006c> in <60fbf9fcf4b84799a79aecb8d0c49d62>:0 
  at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) <0x7f6198569c + 0x000a7> in <e04735c0f86744b49a810beec1c56079>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.18(intptr,intptr,intptr,intptr,intptr)
```

**Comment by jonathanpeppers** [comment]
@shults-s can you add logging to figure out which object reference is actually `null`?

When I look at the code: https://github.com/shults-s/SmtuSchedule/blob/ee30b08e2900bad7a11cf1fd1fd53e4466ec0ca2/SmtuSchedule.Android/Views/ScheduleFragment.cs#L25

There are all kinds of things in here that might be `null` and not related to a problem with Xamarin.Android.

Let us know, thanks!

**Comment by shults-s** [comment]
@jonathanpeppers Yes, I will definitely try to exclude all other things that may be related to the possibility of a System.NullReferenceException. I will write when I get the result. Sorry for premature concern.

**Comment by shults-s** [comment]
@jonathanpeppers Excuse me. The error is indeed in my code, not in Xamarin.Android.

I was confused that Android.Support.V4.App.Fragment is present in the stack trace, I did not immediately understand that this is caused by dynamic polymorphism.

Those who faced this problem and found this issue should read the article ["Don't Store Data in the Application Object"](http://www.developerphil.com/dont-store-data-in-the-application-object/).
