### ISSUE TITLE
[Bug] Attribute "android:XXXXX" has already been defined

### ISSUE THREAD

**Issue by MickLesk** [xamarin/xamarin-android#3896]
### Description
I have updated my project to Xamarin Forms 4.3.0.851321-pre3. When I wanted to build the Android version of my app, I got the error that several attributes are already defined.  I looked at the generated "values.xml" and there e.g. "android:translationX" is present several times. 

Values.xml --> https://www.protectedtext.com/gjfrjzrj (Password: 1234) 

I have already deleted the obj and am folder deleted and recreated. The error appears every time. If I install the project back to the previous version then everything works correctly again.

### Steps to Reproduce

1.  Build my App (Android) - Mind.-Lvl: Android 6.0 - Max.-Lvl: Android 9.0
2. Get Error while Building:
>Android\obj\Debug\90\lp\24\jl\res\values\values.xml(319): error APT0000: Attribute "android:alpha" has already been defined
>Android\obj\Debug\90\lp\24\jl\res\values\values.xml(322): error APT0000: Attribute "android:translationX" has already been defined
>Android\obj\Debug\90\lp\24\jl\res\values\values.xml(322): error APT0000: Attribute "android:translationY" has already been defined
>Android\obj\Debug\90\lp\24\jl\res\values\values.xml(322): error APT0000: Attribute "android:translationZ" has already been defined

### Expected Behavior
- App to be built normally

### Actual Behavior
- App crashes during build attempt

### Basic Information

- Version with issue: 4.3.0.851321-pre3
- Last known good version: 4.2.0.848062
- IDE: Visual Studio 2019 Professional
- Platform Target Frameworks: 
  - iOS:  No Check with iOS
  - Android: SDK: 28.0.3 / Android 9 Device (S9+)
  - UWP:  No Check with UWP
- Android Support Library Version: 28.0.0.3
- Nuget Packages: Forms (pre3) 
- Affected Devices: Samsung Galaxy S9+ Duos

### Screenshots
https://i.imgur.com/w0us0gH.png - Errorlist

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

and perhaps the `obj\Debug\90\lp\24\jl\res\values\values.xml` file it is complaining about? Thanks!

**Comment by MickLesk** [comment]
Hey,

this is the Error:
https://i.imgur.com/yJ0UgmJ.png

The File who you need, dont exist. 
I come to the path \obj\Debug\90\lp\24\jl but i dont have \res


How can i fix this error?
I can fix the error, when i create a new "Debug" Config in Visual Studio with the same Settings from the old. Then it works.
Look: https://i.imgur.com/D5WfNOa.png

**Comment by jonathanpeppers** [comment]
Can you attach the build log? Thanks! See: https://github.com/xamarin/xamarin-android/issues/3896#issuecomment-553095333

**Comment by MickLesk** [comment]
Hey,

i upload the complete lp-Folder as .zip.
You can check it out here:
**Mega - zip-File:** 
https://mega.nz/#!D8RDyaZL!oOf3oDaJgWHKBrpYipc656gj0ZiWZKqzEtjI6VjjSqs
**Virustotal:**
https://www.virustotal.com/gui/file/48ad57585e31ad50ebba9249ed17ec4f4c11cffc96736a531cff744a34319ee3/detection

**Comment by hanwj** [comment]
Hey,
I also have this problem when I build a android project.
I solved this problem by updating gradle plugin and gradle version.

**gradle-plugin: 3.0.1 -> 3.5.3
gradle : 4.4 -> 5.4.1**

hope this can help you!

**Comment by rogihee** [comment]
I solved this by switching to the D8 DEX compiler instead of DX

**Comment by vchelaru** [comment]
Why was this issue closed? I am currently having the same problem. I don't know what gradle is, and I am already using D8 for the **Dex compiler** .

**Comment by FirasAbdennadher** [comment]
try to change the android package format to bunndle , then remove the use fast deployment and linking to none , and change your path location for archives.
