### ISSUE TITLE
PdfRenderer of Android does not render some fonts present in the PDF document in Android API 23 (Android 6.0) 

### ISSUE THREAD

**Issue by ashokkumar96** [xamarin/xamarin-android#3914]
Attached PDF document cannot render the text properly

We have used Android.Graphics.Pdf.PdfRenderer Class to render pages from PDF document. It does not render some text present in the PDF document and it seems to be a break in native PdfRenderer API with the Android API 23 (Android 6.0) - Marshmallow as we do not face same issue in Android API 21 (Android 5.0) – Lollipop.

Can someone please help us to resolve this problem and render the PDF documents properly using PdfRenderer API with the Android API 23 (Android 6.0) - Marshmallow?

Please find the PDF document for your reference in the attachment
[SimplePdfRenderer (1).zip](https://github.com/xamarin/xamarin-android/files/3846741/SimplePdfRenderer.1.zip)
[S2005686010.pdf](https://github.com/xamarin/xamarin-android/files/3846742/S2005686010.pdf)

**Comment by jpobst** [comment]
Xamarin just provides access to the native Android APIs to C#, so it is doubtful there is anything that we can do.  This appears to be an issue with the Android API itself.  There is a bug filed with Android that custom fonts are not supported on different versions of Android: https://github.com/android/graphics-samples/issues/16.

You can try filing a bug with them, but I suspect Google will not be making fixes to Android 6.0 at this point.  Your best options are probably:
- Rework your PDF to not contain unsupported fonts
- Try to find a 3rd party PDF rendering library for Android
- Use a different display format like JPG or PNG
