### ISSUE TITLE
Visual Studio for Mac won't open deployed app and attach debugger on real device

### ISSUE THREAD

**Issue by akamud** [xamarin/xamarin-android#3916]
### Steps to Reproduce

1. Click on play (debug) in Debug mode for a real device

### Expected Behavior
App deploys and opens, debugger then attaches to it.

### Actual Behavior
App deploys but never opens and VS doesn't show any error.

Some extra information:
* The app runs fine if I manually click on it
* We didn't spot any error in "Application Output", logcat or "Deploy to Device", even on Diagnostic verbosity logs
* It launches and debugs on Android Emulator
* Linker is on "SDK Assemblies only"
* The ABIs we tried are x86 and armeabi-v7a

Please let us know if we can provide or collect any more information. Unfortunately this only happens in our client app so we can't share it, we also couldn't create a repro app.

### Version Information

```
=== Visual Studio Professional 2019 for Mac ===
 
Version 8.2.4 (build 17)
Installation UUID: 2f98437b-2ff6-4648-b286-8e7569563f5f
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)
 
    Package version: 600000327
 
=== Mono Framework MDK ===
 
Runtime:
    Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
    Package version: 600000327
 
=== NuGet ===
 
Version: 5.1.0.6013
 
=== .NET Core ===
 
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    3.0.0
    2.2.7
    2.1.13
    2.1.12
SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
    3.0.100
    2.2.402
    2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks
 
=== Xamarin.Profiler ===
 
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
 
=== Updater ===
 
Version: 11
 
=== Apple Developer Tools ===
 
Xcode 10.3 (14492.2)
Build 10G8
 
=== Xamarin.Android ===
 
Version: 9.4.1.0 (Visual Studio Professional)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/fernandookuma/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        8.1 (API level 27)
 
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.3
SDK Build Tools Version: 28.0.3
 
Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969
 
=== Microsoft Mobile OpenJDK ===
 
Java SDK: /Users/fernandookuma/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
 
=== Android Device Manager ===
 
Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC
 
=== Xamarin Inspector ===
 
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1
 
=== Xamarin.Mac ===
 
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.
 
=== Xamarin.iOS ===
 
Version: 12.14.0.114 (Visual Studio Professional)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400
 
=== Xamarin Designer ===
 
Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC
 
=== Build Information ===
 
Release ID: 802040017
Git revision: 9b155edbf23e9fe8b477b3236a342164fabf5f6b
Build date: 2019-08-16 00:21:01+00
Build branch: release-8.2
Xamarin extensions: 9f2598b5f2371ba2903988c2cd87a9759d0255f2
 
=== Operating System ===
 
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 
=== Enabled user installed extensions ===
 
.NET Core support for Mono.Debugging 8.0.5
Xamarin Hot Reload 1.0.0.2925850
Vim 0.65.11.81
```

### Log Files

[adb log.txt.zip](https://github.com/xamarin/xamarin-android/files/3848863/adb.log.txt.zip)
[vslogs.txt.zip](https://github.com/xamarin/xamarin-android/files/3848833/vslogs.txt.zip)

**Comment by joj** [comment]
Deploy is not supposed to run the application, it just installs it. Run runs it. Unless I'm misunderstanding what the action here is?

**Comment by akamud** [comment]
I updated the issue description to be more clear. 
I mean the play button used to debug. And just to be clear, that same project deploys and debugs fine on a Windows machine and on another Mac. To me it is clear that there is some problem with the tools/sdk installed on this specific mac, but the logs don’t show anything useful for us to diagnose what the problem is.

**Comment by joj** [comment]
That makes sense. Do you have any errors in logcat? The output pad should also show _something_ in it. The Mac that works, is it working with the same device? Some devices are more problematic than others.

**Comment by akamud** [comment]
It is the same device. I attached the logcat log file in the original issue, we didn't spot anything that could be helpful.

**Comment by akamud** [comment]
We changed the name of the app in the logcat for "myapp" if you want to search for it.

**Comment by joj** [comment]
The only thing I see with myapp is force stop, which is part of the deploy process and completely normal. I'm seeing some Network errors (below) that could prevent debugging but you're right on the log not showing anything that's too weird. Can you get the Debug output? It should be on the Application Output. Errors:
11-14 18:40:58.519  4855  5195 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=288, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]\
11-14 18:40:58.521  4855  5195 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=289, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]\

**Comment by akamud** [comment]
This happens in my co-work's machine, I'll try to get this today. But from what I remember, there was nothing wrong there either.

**Comment by akamud** [comment]
We just tried it and the only thing that gets printed on the Application Output is this:

```
Forwarding debugger port 8826
```

**Comment by joj** [comment]
That's essentially what I expected. I'll try to get someone here who knows more about the debugger in mac to help.

**Comment by joj** [comment]
If you try to start a Release build (that is, without debugging), does that work?

**Comment by akamud** [comment]
In release the same behavior is seen: everything builds and deploys fine, but the app won't open automatically.

**Comment by Nk54** [comment]
Hello, I got the same problem here... In release mode, the app gets deployed on the iPhone. In debug mode, it's deployed but not launched and attached. Any solution that works ?

**Comment by jpobst** [comment]
I think this is likely fixed, but if not:

This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
