### ISSUE TITLE
xamarin android error APT0000: duplicate value for resource '' with config ''

### ISSUE THREAD

**Issue by cidsv** [xamarin/xamarin-android#3921]
I'm using Xamarin Android with Visual Studio. My two projects has built without errors until update visual studio and xamarin.

### Steps to Reproduce

1. Build [TestApp.zip](https://github.com/xamarin/xamarin-android/files/3854394/TestApp.zip)

### Actual Behavior
Build  errors
1>C:\Users\ccc\source\repos\TestApp\TestApp\Resources\values\attrs.xml(2): error APT0000: duplicate value for resource 'styleable/custom_button' with config ''.
1>C:\Users\ccc\source\repos\TestApp\TestApp\Resources\values\attrs.xml(2): error APT0000: resource previously defined here.
### Version Information
Microsoft Visual Studio Enterprise 2019
Version 16.3.9
VisualStudio.16.Release/16.3.9+29509.3
Microsoft .NET Framework
Version 4.7.03190

Xamarin   16.3.0.278 (d16-3@40034cd)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.256 (remotes/origin/d16-3@8a223bfd7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.6.2 (d16-3/c407838)

Xamarin.iOS and Xamarin.Mac SDK   13.6.0.12 (e3c2b40)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by dellis1972** [comment]
Rather than 

```
  <declare-styleable name="custom_button">
    <attr name="id_expandable_layout" format="reference"/>
  </declare-styleable>
<declare-styleable name="custom_button">
    <attr name="ascbackground" format="reference"/>
  </declare-styleable>
```

you should just be doing

```
  <declare-styleable name="custom_button">
    <attr name="id_expandable_layout" format="reference"/>
    <attr name="ascbackground" format="reference"/>
  </declare-styleable>
```
I made this change and the application complied without any issues. 

If the issue is that this used to work with `aapt` then this is expected. `aapt2` made a number of things that used to be warnings in `aapt`, errors. We are using `aapt2` going forward , so it might be best to update the xml as above.
