### ISSUE TITLE
Can not Export CREATOR Field for IParcelable instance

### ISSUE THREAD

**Issue by MP91** [xamarin/xamarin-android#3923]
When trying to use Parcelable on latest Visual Studio for Mac (16-3) the Creatot gets not exported.

The corresponding code:
```csharp
        [ExportField("CREATOR")]
        public static AudioControlStateCreator InitializeCreator()
        {
            Log.Error("AudioControlStateCreator.InitializeCreator");
            return new AudioControlStateCreator();
        }
```
and the generated code:

```csharp
	data.EnforceInterface (descriptor);
	global::Com.Mercedesbenzaccessories.Constants.Settings.AudioControlState arg0 = default (global::Com.Mercedesbenzaccessories.Constants.Settings.AudioControlState);
	arg0 = data.ReadInt () != 0 ? (global::Com.Mercedesbenzaccessories.Constants.Settings.AudioControlState) global::Android.OS.Bundle.Creator.CreateFromParcel (data) : null;
	this.OnAudioControlChanged (arg0);
	reply.WriteNoException ();
	return true;
}
```

I used Mono.Android.Export and already tried everything I found on the internet

**Comment by radekdoulik** [comment]
Please could you attach a sample app to reproduce the issue?

**Comment by MP91** [comment]
Hi, sorry for the late response. Somehow I didn't get a notification and made a workaround for the problem....

Nevertheless it is the same problem like in this bug:
#1149 (https://github.com/xamarin/xamarin-android/issues/1149)

Hope that helps.

**Comment by jpobst** [comment]
This seems to have been fixed in https://github.com/xamarin/xamarin-android/issues/1149.
