### ISSUE TITLE
Do not add AOT'ed assemblies with 0 methods added

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#3932]
When using the profiled AOT, the aot compiler creates the `.so` libraries even for assemblies with 0 methods emitted. Avoiding these should result in a bit smaller apk size (yay) and possibly also better performance as we will not be loading these.

We should either fix aot compiler to not do it or AOT only assemblies in profiles. Another possibility might be to check the verbose output to see how many methods were added.

I will try to first fix it in mono as I think it doesn't make sense to create these.

**Comment by claudioredi** [comment]
@radekdoulik : We're having a problem on Android <= 4.3 where the amount of generated .so files is greater than 128 and this causes the app to not start. I found this mono log

**D/Mono: DllImport error loading library 'libmono-native.so': 'Cannot load library: soinfo_alloc(linker.cpp:287): too many libraries when loading "libmono-native.so"'.**

As far I understand, this indicates that we're generating more .so files than Android can handle. I wonder if once you fix this problem I get a more reasonable amount of libraries. (I currently have around 140 libaot-xxxx libraries)

**Comment by radekdoulik** [comment]
Yes, if many of those doesn't contain any methods then this should help. It is usually the case with the profiled AOT.

**Comment by FoggyFinder** [comment]
any news?
