### ISSUE TITLE
migrate Jenkins plots to Azure

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#3939]
We will need to migrate the [plots](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/plot/) from Jenkins to devops.

I started looking into that and it looks like the [Azure Time series insights](https://azure.microsoft.com/en-us/services/time-series-insights/) might be a way to go.

Hopefully we will be able to upload the data to it through http(s) and use its nice charts. Like in this [demo](https://insights.timeseries.azure.com/preview/demo).

**Comment by jpobst** [comment]
This was completed: https://github.com/xamarin/xamarin-android/pull/4549.
