### ISSUE TITLE
Socket.ConnectAsync() task is never completed

### ISSUE THREAD

**Issue by zawodskoj** [xamarin/xamarin-android#3944]
### Steps to Reproduce

1. Download project from https://github.com/zawodskoj/WtfSockets
2. Replace hostname and port at MainActivity.cs, line 28
` var (host, port) = ("192.168.108.101", 11883);`
3. Run app with normal network connection
4. Press both buttons and see "Ok"
5. Turn off network
6. Press both buttons

Sync version will fail (ReceiveTimeout/SendTimeout)
In async version, Task will not be completed and WhenAny will return Task.Delay

### Expected Behavior
- ConnectAsync task completed with exception

### Actual Behavior
- ConnectAsync task will never be completed

### Version Information

Microsoft Visual Studio Community 2019
Версия 16.3.10
VisualStudio.16.Release/16.3.10+29519.87

Xamarin   16.3.0.281 (d16-3@859f726)

Xamarin.Android SDK   10.0.6.2 (d16-3/c407838)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@476d72b9e32
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Xamarin.iOS and Xamarin.Mac SDK   13.6.0.12 (e3c2b40)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jpobst** [comment]
This looks like the same as https://github.com/mono/mono/issues/17407.  Can you try the most recent 16.4 Preview and see if the issue goes away?  Alternatively there is a different usage pattern listed in that issue that should work on 16.3.

https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

**Comment by zawodskoj** [comment]
I tried latest 16.4 Preview - problem is still there

VisualStudio.16.Preview/16.4.0-pre.6.0+29519.161
Xamarin   16.4.000.305 (d16-4@a9ec5d9)
Xamarin.Android SDK   10.1.0.30 (d16-4/5e2fd06)

**Comment by zawodskoj** [comment]
I just removed all of VS instances and reinstalled preview - and now it works

**Comment by jpobst** [comment]
Great! Glad you got it working!
