### ISSUE TITLE
AndroidClientHandler doesn't forward cookies on redirect

### ISSUE THREAD

**Issue by aliriomendes** [xamarin/xamarin-android#3954]
### Steps to Reproduce

1. Execute this code:
```
var client = new HttpClient(new AndroidClientHandler());
var res = await client.GetAsync("https://oaa365.sharepoint.com/:x:/s/Development/ESKK8ZI2L2NEvKCM-4rN6rcB3a2i3245l_7uw3mERhNcVw?e=GExumW&download=1");
```
I pulled in the code(AndroidClientHandler) to debug:
```
if (disposeRet)
{
    ret.Dispose();
    ret = null;
}
else
{
    CopyHeaders(httpConnection, ret);
    ParseCookies(ret, connectionUri);
}
```
If I change the code to the one bellow the redirect and file download works perfectly
```
CopyHeaders(httpConnection, ret);
ParseCookies(ret, connectionUri);
if (disposeRet)
{
    ret.Dispose();
    ret = null;
}
```

### Expected Behavior
The cookies are set on redirect and the file is downloaded correctly
### Actual Behavior
The cookies are not set on redirect and, after a series of redirect, we end up downloading the login html page.
### Version Information

Visual Studio Community 2019 for Mac
Version 8.3.10 (build 2)

Mono Framework MDK
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

NuGet
Version: 5.3.0.6192

Xamarin.Android
Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/aliriomendes/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 28.0.3

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Operating System
Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
    root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

**Comment by aliriomendes** [comment]
In my specific case Sharepoint redirect to a new url together with a FedAuth cookie. On iOS and UWP I'm using NSUrlSessionHandler and WinHttpHandler  respectively, this workflow works fine.

**Comment by erlendl** [comment]
I experience the exact same issue and agree with @aliriomendes solution. With NSUrlSessionHandler, the cookies are forwarded upon a 302 Redirect. The behaviour should be identical for AndroidClientHandler.
@grendello / @pjcollins is there any plans to implement the suggested fix soon?

**Comment by dominik-weber** [comment]
@grendello @pjcollins The repro above still yields the same result, also when using `AndroidMessageHandler`. Are there plans to fix this?

As we need Sharepoint links to work, this issue prevents us from switching to AndroidClientHandler / AndroidMessageHandler and we have to still rely on HttpClientHandler, which brings its own problems dealing with ssl certificate validation. A fix would be highly appreciated!

**Comment by dominik-weber** [comment]
@grendello @pjcollins as the solution proposed by @aliriomendes seems rather straight forward, I have created a PR here: #6987 From my testing I can confirm this solves the redirection issue for SharePoint links.

Please let me know if you need further details to process the PR.

**Comment by grendello** [comment]
> @grendello @pjcollins as the solution proposed by @aliriomendes seems rather straight forward, I have created a PR here: #6987 From my testing I can confirm this solves the redirection issue for SharePoint links.
> 
> Please let me know if you need further details to process the PR.

Thanks, merged! :)

**Comment by dominik-weber** [comment]
Thanks for the quick review :) do you have an idea when this will be released? I assume it will be shipped together with a Visual Studio update?

**Comment by jonathanpeppers** [comment]
I backported this to our .NET 6 release branch. Unless something unexpected happens, it should be in the final .NET 6 Android workload when it ships.
