### ISSUE TITLE
The "GenerateResourceDesigner" task failed unexpectedly with NullReferenceException

### ISSUE THREAD

**Issue by SachinCS1992** [xamarin/xamarin-android#3961]
### Steps to Reproduce

1. Create a Xamarin.Forms project that references a custom .NETStandard library and an SDK extras project
2. Try to build the Xamarin.Forms Android platform project
3. Android build fails with the above error message.

### Expected Behavior
Build XF Android project without errors

### Actual Behavior
XF Android fails to build with the above error

### Version Information
Reproduced on both latest VS for Windows and VS for Windows Preview (16.3.10 and 16.4.0 Preview 6 respectively).

Microsoft Visual Studio Enterprise 2019
Version 16.3.10
VisualStudio.16.Release/16.3.10+29519.87
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA598
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.286.43615
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.286.43615
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.286.43615
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.3.286.43615
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.10.8.8132
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   16.3.0.281 (d16-3@859f726)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.256 (remotes/origin/d16-3@8a223bfd7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.6.2 (d16-3/c407838)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@476d72b9e32
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Xamarin.iOS and Xamarin.Mac SDK   13.6.0.12 (e3c2b40)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by SachinCS1992** [comment]
Probably unrelated, but just for reference the exception from the build log is on the same method as the file changed recently on [this commit](https://github.com/xamarin/xamarin-android/commit/15e942ed1bda263ff4cdddbf1a4d99cdcc10271e#diff-45ffe90851907e18e64026545cf07e2b).

**Comment by grendello** [comment]
@SachinCS1992 can you attach a full, verbose level, build log for the crash you're seeing? If you can, a binary log would be best. You can get the binary log by opening the VS developer prompt, changing the directory to your project's top folder and issuing the following command:

```sh
msbuild /bl
```

This will produce the `msbuild.binlog` to attach here. Thanks!

**Comment by SachinCS1992** [comment]
@grendello I have a binlog file generated but the file type is not supported by Github for attachment! I've sent an email to the address on your profile, let me know if you require any more info.

**Comment by SachinCS1992** [comment]
I have attached a diagnostic build log which might also help.

[Output-Build.txt](https://github.com/xamarin/xamarin-android/files/3891276/Output-Build.txt)

**Comment by SachinCS1992** [comment]
I have attached a diagnostic build log however, which might help everyone.

[Output-Build.txt](https://github.com/xamarin/xamarin-android/files/3891280/Output-Build.txt)

**Comment by grendello** [comment]
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-android/files/3891528/msbuild.binlog.zip)

@SachinCS1992 GitHub is picky regarding file extensions :) I've attached your binlog above, zipped-up. Thanks!

**Comment by jonathanpeppers** [comment]
> 1. Create a Xamarin.Forms project that references a custom .NETStandard library and an SDK extras project

Can you zip and upload this project? [MSBuild.Sdk.Extras](https://github.com/onovotny/MSBuildSdkExtras) specifically causes the issue? The File -> New template definitely works for me.

[This commit](https://github.com/xamarin/xamarin-android/commit/15e942ed1bda263ff4cdddbf1a4d99cdcc10271e#diff-45ffe90851907e18e64026545cf07e2b) won't be the issue, as it probably won't ship for months. It would be in some future VS 2019 16.6 release, maybe?

**Comment by SachinCS1992** [comment]
Having spent some more time digging into this, it seems like there's something wrong with my MsBuild.Sdk.Extras project definition. I have custom layouts defined within Android and is being consumed **from** Resource.Designer.cs by some of the consumer classes. I have attached a sample of my SDK.Extras project definition, which is being used as a package reference from my XF.Android project.

[MsBuildSDKExtras.zip](https://github.com/xamarin/xamarin-android/files/3896264/MsBuildSDKExtras.zip)
