### ISSUE TITLE
"Uncompressed resource extensions" not working properly with aapt2 enabled.

### ISSUE THREAD

**Issue by matheussouza97** [xamarin/xamarin-android#3962]
### Steps to Reproduce

1. Add asset with extension .tflite .
2. Add the extension on "Uncompressed resource extensions".
3. Try open asset.

![Screenshot at Nov 26 08-23-08](https://user-images.githubusercontent.com/14929125/69625754-0b250a80-1026-11ea-9cb5-71c57591e86b.png)

Project sample [sample.zip](https://github.com/xamarin/xamarin-android/files/3891596/sample.zip)

### Expected Behavior

Load the asset.

### Actual Behavior

``This file can not be opened as a file descriptor; it is probably compressed``

### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.3.10 (build 2)
Installation UUID: 51da8e57-bfc7-4bfd-88c8-6241f255f48b
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	3.0.100-preview9-014004
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	3.0.0-preview9-19423-09
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.2 (15526)
Build 11B52

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

=== Xamarin Designer ===

Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

=== Xamarin.Android ===

Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/ASAAS/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@476d72b9e32
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ASAAS/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:22 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:42 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803100002
Git revision: add3a4998a5cb5b081e0404e1fe13acfecb7801d
Build date: 2019-11-20 13:35:15+00
Build branch: release-8.3
Xamarin extensions: 79c69708816813b498283eeda7bcb4d464433a04

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by dellis1972** [comment]
This was fixed in the following commit https://github.com/xamarin/xamarin-android/commit/d20a991f403b7daa0b9be6d05db731b689d68833.

The reason this didn't work for you is because you need to include the period `.` in the file extension.
So `.tflite` rather than just `tflite`. Doing so means the resulting asset will be stored as you can see from the output below. 

```
 unzip -lv obj/Debug/android/bin/packaged_resources | grep assets
 4183312  Stored  4183312   0% 01-01-1980 01:00 1313ae97  assets/detect.tflite
```

**Comment by dellis1972** [comment]
Note this is just the way `aapt2` expects the parameter. I'll look at adding a fix which will prepend the `.` if it's not present.

**Comment by matheussouza97** [comment]
I tried the two ways and didn't work. But is good know it is already fixed.

Thanks.

**Comment by brendanzagaeski** [comment]
In case it might be useful to mention, the release status of the original fix from https://github.com/xamarin/xamarin-android/commit/d20a991f403b7daa0b9be6d05db731b689d68833 can be tracked in the corresponding issue <https://github.com/xamarin/xamarin-android/issues/3675>.

In short, with Visual Studio 2019 version 16.4 (currently in Preview), **Uncompressed resource extensions** will work successfully with AAPT2 as long as the listed file extensions start with `.`.
