### ISSUE TITLE
Warning MSB3277 on Microsoft.CSharp when building

### ISSUE THREAD

**Issue by kvpt** [xamarin/xamarin-android#3980]
### Steps to Reproduce
1.  Build the following project : [WarningCsharpRepro.zip](https://github.com/xamarin/xamarin-android/files/3915909/WarningCsharpRepro.zip)
2.  Msbuild output warning MSB3277

### Expected Behavior
Solution build without warning

### Actual Behavior
Solution build with a warning

### Version Information
Microsoft Visual Studio Enterprise 2019
Version 16.3.10
VisualStudio.16.Release/16.3.10+29519.87
Microsoft .NET Framework
Version 4.8.03752

Xamarin   16.3.0.281 (d16-3@859f726)
Extension Visual Studio permettant de développer pour Xamarin.iOS et Xamarin.Android.

Xamarin Designer   16.3.0.256 (remotes/origin/d16-3@8a223bfd7)
Extension Visual Studio pour activer les outils Xamarin Designer dans Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.6.2 (d16-3/c407838)

**Comment by pjcollins** [comment]
This warning has been discussed in a few places in the past:
![image](https://user-images.githubusercontent.com/2000163/70275717-b9deee80-177c-11ea-82cc-ffea18c67429.png)
https://github.com/xamarin/xamarin-android/issues/1261
https://github.com/microsoft/msbuild/issues/3392

I'm not sure how much can be done at this point, however this is scenario that will hopefully be resolved in future versions of .NET and Xamarin (see https://devblogs.microsoft.com/dotnet/introducing-net-5/).
