### ISSUE TITLE
App fails to start on Android 4.0.3 when built on Xamarin.Android SDK 10

### ISSUE THREAD

**Issue by onetreba** [xamarin/xamarin-android#3990]
### Steps to Reproduce

1. Build and deploy solution
2. Run app
3. App closes after start

https://docs.microsoft.com/ru-ru/samples/xamarin/monodroid-samples/helloworld/ 

### Expected Behavior
Application starts

### Actual Behavior
Application closes

### Version Information

Microsoft Visual Studio Enterprise 2019
Version 16.3.10
VisualStudio.16.Release/16.3.10+29519.87
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA418
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.286.43615
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.286.43615
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.286.43615
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.286.43615
Azure Functions and Web Jobs Tools

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Customize Visual Studio Window Title   4.0
This lightweight extension allows changing the window title of Visual Studio to include a folder tree with a configurable min depth and max depth distance from the solution/project file, and the use of special tags to help with many other possible scenarios (Git, Hg, TFS, SVN...). 
Solution-specific overriding rules are available as well to cover virtually any possible renaming needs. It can also be configured so that the rules apply only when at least two instances of Visual Studio are running with the same window title.
This is particularly useful when branching a solution/project: it becomes possible to easily identify which branch you are working on, in case both would have the same solution/project name.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.2.2   Build 192.0.20190828.114715
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.6.7
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

Xamarin   16.3.0.281 (d16-3@859f726)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.256 (remotes/origin/d16-3@8a223bfd7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.6.2 (d16-3/c407838)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@476d72b9e32
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Xamarin.iOS and Xamarin.Mac SDK   13.6.0.12 (e3c2b40)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

[device_log.txt](https://github.com/xamarin/xamarin-android/files/3921230/device_log.txt)

**Comment by pjcollins** [comment]
Unfortunately this is somewhat expected. The lowest 32-bit version of Android supported by Xamarin.Android is determined by the Android NDK that we build against. Xamarin.Android has been building against NDK r20 for some time, and as a result it supports only API 16 and higher at present:

https://github.com/xamarin/xamarin-android/blob/a3de82a659c1c1f9c656a6fc90dcf6c5d3ab8fb2/build-tools/xaprepare/xaprepare/Application/BuildInfo.cs#L93
https://github.com/mono/mono/blob/2019-08/sdks/versions.mk#L14

Some additional historical context can also be found in https://github.com/xamarin/xamarin-android/issues/2692.


---

This unsupported configuration only produces a warning at build time, as certain configurations did still _run_ on targets lower than API 16 even though they weren't supported. This no longer appears to be the case with d16-4:

```
E/AndroidRuntime( 1640): java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1285]:   118 cannot locate 'posix_memalign'...
E/AndroidRuntime( 1640):
E/AndroidRuntime( 1640):        at java.lang.Runtime.loadLibrary(Runtime.java:370)
E/AndroidRuntime( 1640):        at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime( 1640):        at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:76)
E/AndroidRuntime( 1640):        at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:22)
E/AndroidRuntime( 1640):        at android.app.ActivityThread.installProvider(ActivityThread.java:4237)
E/AndroidRuntime( 1640):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:3992)
E/AndroidRuntime( 1640):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3946)
E/AndroidRuntime( 1640):        at android.app.ActivityThread.access$1300(ActivityThread.java:123)
E/AndroidRuntime( 1640):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1185)
E/AndroidRuntime( 1640):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1640):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1640):        at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime( 1640):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1640):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1640):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime( 1640):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime( 1640):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  189):   Force finishing activity com.xamarin.helloworld/crc6445fe2d522ad713b7.HelloAndroid
```

@jonpryor @jonathanpeppers should we perhaps consider converting this build warning to an error at this time?

**Comment by onetreba** [comment]
@pjcollins Thank's for pointing that! Just a little bit confused, have I missed this fact in release notes (https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.0) ?

**Comment by pjcollins** [comment]
The update to a minimum supported SDK version of 16 occurred in XA 9.3, as mentioned in the release notes here:
https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.3#android-ndk-r19-compatibility

Any projects which declare a minimum version lower than 16 should also be encountering the build warning described below:
https://docs.microsoft.com/en-us/xamarin/android/errors-and-warnings/xa4216
