### ISSUE TITLE
Throws at runtime when calling a Java method that receives an interface implemented in C#

### ISSUE THREAD

**Issue by bruno-garcia** [xamarin/xamarin-android#4007]
### Steps to Reproduce

Repro: https://github.com/bruno-garcia/xamarin-android-java-binding-repro

The repro repo includes a [README](https://github.com/bruno-garcia/xamarin-android-java-binding-repro/blob/master/README.md) which includes details of the problem. Copying it here anyway:

The following Java code is not callable from C#:

```java
public static void doSomething(ConfigureOptions callback) {
        Options o = new Options();
        callback.configure(o);
    }
    public interface ConfigureOptions {
        void configure(Options options);
    }
}
```

It is callable from Java (with 1.8 compat) as:

```java
public static void callDoSomething() {
    doSomething(o -> Log.d(TAG, o.getValue()));
}
```

The C# binding calling out the Java method without parameters works just fine.
Calling the one with while passing the argument, fails:

```csharp
public class DotnetConfigureOptions :
    Java.Lang.Object,
    Com.Brunogarcia.Sample.IConfigureOptions
{
    public void Dispose() { }
    public IntPtr Handle { get; }
    public void Configure(Com.Brunogarcia.Sample.Options options) => 
        Log.Debug("dotnet", options.GetType().Name);
}

Com.Brunogarcia.Sample.CallDoSomething();
// Throws here:
Com.Brunogarcia.Sample.DoSomething(new DotnetConfigureOptions());
```

I'm unsure if I'm doing something wrong. It first came up on a project I'm building, I've created a repro "from scratch" to make sure it'd be small enough to discuss it and debug through.

I'm running it on an emulator with Android 10. x86.
As you can see in the repro, it's using D8 and targets API 29, etc.

IDE:

```
JetBrains Rider 2019.2.3
Build #RD-192.7317.11, built on October 16, 2019
Licensed to Bruno Garcia
Subscription is active until June 14, 2020
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8
Registry: ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.title.product=false, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, ide.mac.allowDarkWindowDecorations=true, ide.borderless.title.project.path=false, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.borderless.title.classpath=false, ide.require.transaction.for.model.changes=false, rider.enable.designer.winForms=false
Non-Bundled Plugins: com.intellij.resharper.HeapAllocationsViewer, com.microsoft.vso.idea, com.wakatime.intellij.plugin, io.protostuff.protostuff-jetbrains-plugin, com.jetbrains.rider.android, org.intellij.plugins.markdown, BashSupport
```

**Comment by jpobst** [comment]
Does it work if you remove the `Handle` and `Dispose` methods?  You might be hiding the ones built into `Java.Lang.Object`:

```
public class DotnetConfigureOptions :
    Java.Lang.Object,
    Com.Brunogarcia.Sample.IConfigureOptions
{
    public void Dispose() { }
    public IntPtr Handle { get; }
}
```

**Comment by bruno-garcia** [comment]
IDE added them automatically, assumed it needed override. Java being virtual by default might have been the reason? Although it would not create overrides in C# by default so maybe an issue in rider.
Will try later and reply. 
Thanks!

**Comment by bruno-garcia** [comment]
I haven't tried your advise on this repro but I did in the code base that made me work on a smaller repro in the first place.

JetBrains rider overrides `public IntPtr Handle { get; }` and `Dispose` but I've removed these overrides and things are working.
