### ISSUE TITLE
Severity Code	Description Project	File	Line	Suppression State Error "mdoc.exe" exited with code 1.	XamarinAdaptiveTableLayout			

### ISSUE THREAD

**Issue by gopalawasthi123** [xamarin/xamarin-android#4013]
### Steps to Reproduce

1. I am trying to create the binding library for the [AdaptiveTableLayout](https://github.com/Cleveroad/AdaptiveTableLayout)
2. I am following the steps that are provided in the [link](https://mobileprogrammerblog.wordpress.com/2017/11/20/java-library-binding-with-javadocs-for-xamarin-android/)
3. Following all the steps gives the error.

### Version Information
Visual Studio 2019 Version 16.3.5
Xamarin.Android SDK 10.0.3.0
Microsoft .NET Framewrokversion 4.8.03752

### Log File
 Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(544,5)

**Comment by jpobst** [comment]
The actual error isn't showing anywhere, can you get a [diagnostic build log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) and attach it?

Additionally, you may want to try leaving out the JavaDoc step(s).  I'm not sure that they do anything useful nowadays.

**Comment by gopalawasthi123** [comment]
@jpobst if I leave out the JavaDoc steps I am able to do the build the project but dll is empty. No classes have been added in the Library

**Comment by gopalawasthi123** [comment]
This is due to Progaurd settings. I turn off the minified to false in the android project and the error is gone. Anyway Thanks!
