### ISSUE TITLE
Different APK size which built in VS 2017 and VS 2019

### ISSUE THREAD

**Issue by VictorKochetkov** [xamarin/xamarin-android#4027]
I faced following issue:
If I build Xamarin.Android project in Visual Studio 2017 (15.9.17) the resulting APK is about **50 MB**. 
If I build this project in Visual Studio 2019 (16.4.0) the resulting APK is about **67 MB**.

![image](https://user-images.githubusercontent.com/11313401/70692750-0a9a9e00-1ccd-11ea-9ccb-9921847a6ed5.png)

**Comment by alexthekid07** [comment]
Do you have startup tracing/AOT enabled? This is new to 2019 if I recall correctly and it bloats your APK a decent amount but improves startup performance. 
https://devblogs.microsoft.com/xamarin/faster-startup-times-with-startup-tracing-on-android/

You could try shaving off additional size in production by building AAB instead of APKs perhaps?

**Comment by VictorKochetkov** [comment]
I have `AOT` enabled, `Start up tracing` is disabled. 

![image](https://user-images.githubusercontent.com/11313401/70860857-01f9d000-1f38-11ea-956e-e427ea37d318.png)

**Comment by jonathanpeppers** [comment]
@VictorKochetkov Mono has slowly been migrating code from .NET Core into Mono, which results in a larger BCL. I believe this is what you are seeing. We have put some APK size testing into place, so we are actively monitoring this going forward.

To be sure, you could post the output of 7-zip of the two APKs:

    "C:\Program Files\7-Zip\7z.exe" l yourapp.apk > filesizes.txt

(or upload the APKs if you are OK with that)

### Other Options

There are several other options you can look into for getting your APK smaller:

* Use a `Code Shrinker` to strip Java code. Note that you will have to add some [proguard rules](https://docs.microsoft.com/xamarin/android/deploy-test/release-prep/proguard#using-proguard) to get this fully working. If you enable this, you should be able to disable multi-dex as well.
* Use `Link All Assemblies`. You might need to add some [linker exclusions](https://docs.microsoft.com/xamarin/android/deploy-test/linker) for this option as well.

You might also check out this blog post: https://devblogs.microsoft.com/xamarin/optimize-xamarin-android-builds

**Comment by radekdoulik** [comment]
Hopefully you found a resolution meanwhile! If not, please try the latest version of the product and if the problem still occurs, reply with the requested information and reopen this issue.

**Comment by radekdoulik** [comment]
> I have AOT enabled, Start up tracing is disabled.

The Startup tracing provides smaller apk compared to AOT without a profile. It tries to provide balance between apk size and startup speed. So depending on the circumstances, it can help you reduce the size of the apk.
