### ISSUE TITLE
Xamarin Android Crash at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

### ISSUE THREAD

**Issue by Panasjuk** [xamarin/xamarin-android#4039]
### Steps to Reproduce

1. No stable steps for reproduce. Just in some cases during start Android app. Mostly on Amazon and Samsung devices with Android ~5.1.1.

### Actual Behavior
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
  at System.Array.InternalArray__get_Item[T] (System.Int32 index) [0x00009] in <620c1bc5d654407197bbe331f96aba96>:0 
  at (wrapper managed-to-managed) System.Threading.Tasks.Task[].System.Collections.Generic.IList`1.get_Item(int)
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x9d27c968 + 0x0003b> in <620c1bc5d654407197bbe331f96aba96>:0

### Version Information

Microsoft Visual Studio Professional 2019
Version 16.1.6
VisualStudio.16.Release/16.1.6+29102.190
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Professional

Visual C++ 2019   00435-30010-59437-AA410
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonathanpeppers** [comment]
@Panasjuk can you reproduce this yourself? Or any cases where you have a more detailed stack trace?

[adb logcat output](https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log#accessing-from-the-command-line) would help us know what is happening here.

**Comment by radekdoulik** [comment]
We are unable to investigate this issue further without the requested information.

Hopefully you found a resolution meanwhile! If not, please try the latest version of the product and if the problem still occurs, reply with the requested information and reopen this issue.

**Comment by 1Cor125** [comment]
I am getting this crash on an Amazon Kindle running Android 5.1.1 building with Xamarin.Android 11.1.0.17. It crashes with a native stack trace but when I do get a limited managed stack trace, it always seems to be related to a call to `ThreadPoolWaitCallback:PerformWaitCallback`. I will have to try and create a repro project for this. Starter apps for Xamarin.Android and Xamarin.Forms do not manifest this crash. It may show up when making extensive use of TPL and/or System.Reactive but until I can put together a repro project I can't say for sure. I am posting this just to call out that this is still an issue.

**Comment by 1Cor125** [comment]
@jonathanpeppers I'm hoping we can reopen this issue. This is blocking us from shipping to the Amazon store because we are getting a persistent crash on the 5th generation Amazon Kindle Fire device running Android 5.1. It crashes soon after startup or, at the latest, when the user starts doing anything meaningful. We have tried running a previous version of our app (built with an older version of Xamarin Android) on this device and we do not see the crash. The actual exception that causes the crash varies. The stack traces are very shallow and but they _always_ involve a call to `System.Threading._ThreadPoolWaitCallback:PerformWaitCallback`
```
Amazon Kindle Fire 5th Generation
Android 5.1
Xamarin.Android 11.2.2.1
```
Here is the debug output:

```
=================================================================
	Native Crash Reporting
=================================================================
Got a SEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

No native Android stacktrace (see debuggerd output).

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x9e54cf68):0x9e54cf58  80 96 
98 00 00 00 00 00 f0 d8 ff ff ff ff ff ff  ................
0x9e54cf68  60 32 f0 b8 00 00 00 00 00 00 00 00 00 00 00 00  `2..............
0x9e54cf78  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x9e54cf88  00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Threading._ThreadPoolWaitCallback:PerformWaitCallback <0x00033>
	  at <Module>:runtime_invoke_bool <0x000bb>
=================================================================04-13 09:47:37.346 F/libc    (20033): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x9e54cf68 in tid 20108 (Thread Pool Wor)
```
Attached is a log file with all the statements emitted at or around the point of the native crash.

[logcat_output.txt](https://github.com/xamarin/xamarin-android/files/6311133/logcat_output.txt)
