### ISSUE TITLE
Wrong HttpClient response content string if response headers contain Content-Length

### ISSUE THREAD

**Issue by AndreyFromGomel** [xamarin/xamarin-android#4040]
### Steps to Reproduce

1. Create HttpClient instance and send GET request to host which returns Content-Length header in response.
2. Get response content as string.
3. Result string will be broken (will contain some hex numbers with chunk sizes or smth like this). 

E.g. I added Content-Length: 50 header to response from  http://www.google.com, and run this code:

```
       public async void CallTest()
        {
            using (var httpClient = new HttpClient())
            {
                var res = await httpClient.GetAsync("http://www.google.com");
                var contentString = await res.Content.ReadAsStringAsync();
            }
        }
```
Expected to receive in contentString:
> <!doctype html><html itemscope="" itemtype="http:/

Got:
> 22\r\n<!doctype html><html itemscope=\"\" \r\n28e\r\nitemt

[NetworkTest.zip](https://github.com/xamarin/xamarin-android/files/3969688/NetworkTest.zip)

### Expected Behavior
Response content string with length from Content-Length header.

### Actual Behavior
Broken content string.

### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.3.11 (build 1)
Installation UUID: 2dd74bf7-d195-44c1-ab8a-bce0ad686ffe
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.0.1
	3.0.0
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.0.5

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.2.1 (15526.1)
Build 11B500

=== Xamarin.Mac ===

Version: 6.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:07-0400

=== Xamarin.iOS ===

Version: 13.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

=== Xamarin Designer ===

Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

=== Xamarin.Android ===

Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/andrewm/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@476d72b9e32
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/andrewm/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:22 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:42 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803110001
Git revision: 6ee6ad2ec46ae5a08a1999ee4c815ac656a35b91
Build date: 2019-12-05 16:09:27+00
Build branch: release-8.3
Xamarin extensions: 56bd70ef2e327f71c615cfc29a47fd50685fadcb

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

On latest stable Xamarin.iOS and Xamarin.Mac everything works as expected, with Xamarin.Android 9.1.4.2 HttpClient also works fine. I tested preview version of Xamarin.Android and problem is still exists.

**Comment by jpobst** [comment]
How are you adding the `Content-Length` header?  Could it be an issue with how you are doing that?  It looks like the request directly from google already provides this header and things seem to work fine:

![image](https://user-images.githubusercontent.com/179295/70940746-9b94b080-2010-11ea-9ede-01dc0fc0aa74.png)

**Comment by AndreyFromGomel** [comment]
I'm using Charles proxy for this.
Original response:
<img width="601" alt="Screen Shot 2019-12-17 at 00 12 46" src="https://user-images.githubusercontent.com/46677631/70943580-41bcd680-2062-11ea-9754-87d717c31148.png">
Modified:
<img width="599" alt="Screen Shot 2019-12-17 at 00 16 04" src="https://user-images.githubusercontent.com/46677631/70943701-86487200-2062-11ea-9957-5fd52178f97b.png">

**Comment by Alexandr-Gurinovich** [comment]
@jpobst  @dellis1972 
`Content-Length` header is absent in @AndreyFromGomel's case as `Transfer-Encoding: chunked` header present. 

We also faced this issue when tried to update to VS2019. Issue does not reproduce on VS2017

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
