### ISSUE TITLE
Support for Android App Bundles on Azure DevOps

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/xamarin-android#4042]
Currently, there is no support for Android App Bundles on Azure DevOps. Are there any plans to add tasks for building Android apps as an .aab on Azure DevOps?

**Comment by brendanzagaeski** [comment]
Thanks for the question! The best place track this request will be on Visual Studio Developer Community under the Azure DevOps section.

In particular, I believe the following item matches what you're looking for, so when you get a chance, you can upvote and follow it to let the team know you're also interested:

https://developercommunity.visualstudio.com/idea/756675/azure-devops-pipeline-publish-android-bundle-to-go.html

Thanks!
