### ISSUE TITLE
Unable to Open Database File (connection wizard while testing Sqlite Database Connection)

### ISSUE THREAD

**Issue by Yadwin** [xamarin/xamarin-android#4049]
![SqliteConn](https://user-images.githubusercontent.com/44522708/71053574-e0d1f300-2174-11ea-90d8-7fe42e46eb31.png)

DataBase Path is Correct

**Comment by jpobst** [comment]
This does not seem to be related to Xamarin Android?

I would suggest submitting an issue from inside Visual Studio:
```
Help -> Send Feedback -> Report a Problem
```

This will allow the issue to get internally routed to the correct team.  (Most parts of Visual Studio are not open source, so those teams are not on GitHub.)

**Comment by jonathanpeppers** [comment]
@Yadwin closing for now, let us know if you see a Xamarin.Android issue here, thanks.
