### ISSUE TITLE
How to install older version of Xamarin.Android in VS Community 2019?

### ISSUE THREAD

**Issue by cncb-gh** [xamarin/xamarin-android#4053]
I need a previous version of Xamarin.Android (10.1 installed and need 9.4).  I have downloaded the appropriate .vsix but when try to install it gives me an error: "This extension is already installed".  If I try to uninstall the extension within VS, it requires me to uninstall all of Xamarin and then the .vsix won't install because Xamarin is missing.  How is this done?  Thanks.

**Comment by brendanzagaeski** [comment]
As a little caution, It's possible that using an older Xamarin.Android SDK version in a newer Visual Studio version might lead to unexpected behaviors. Usually the IDE features are fairly flexible about the Xamarin.Android SDK version, but occasionally certain version combinations might cause some trouble.

I think the particular combination you're trying with Xamarin.Android SDK version 9.4 in Visual Studio 2019 version 16.4 will probably work OK.

On the team, when we want to check something with a custom Xamarin.Android SDK version, we usually swap out the Xamarin.Android SDK files in the Visual Studio installation directly. The steps are:

 1. Move the original directories and files for the Xamarin.Android SDK out of the way. For the default install location of Visual Studio 2019 Community, those paths are:

      * *C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Xamarin\\Android*
      * *C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Xamarin\\Xamarin.Android.Sdk.props*
      * *C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Xamarin\\Xamarin.Android.Sdk.targets*
      * *C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Novell*
      * *C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\ReferenceAssemblies\\Microsoft\\Framework\\MonoAndroid*

    One option is to move these items to a temporary location in the user home directory to make it easy to put them back. Another option is to delete them.

 2. Open the *.vsix* package as a ZIP archive, for example by renaming it to have a *.zip* extension and browsing it in Explorer.

 3. Find the corresponding directories and files from step 1 under the *$MSBuild* and *$ReferenceAssemblies* directories in the *.vsix* archive, and extract them into the appropriate locations in the Visual Studio installation.

This is what the `setup-windows.exe` command in the [open source development build *.zip* archives](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/JenkinsBuildArtifacts.md#oss-xamarinandroidzip-installation) does.

## Other possible approaches

I think it might also be possible to change the version number in the *.vsix* to a higher number and then install it using the normal VSIX Installer process. If I get a chance, I'll plan to check on that approach and write up the steps.

**Comment by cncb-gh** [comment]
Success with the manual approach.  Thank you!
