### ISSUE TITLE
Xamarin.Android application and Appium cannot cooperate, and it ends abnormally.

### ISSUE THREAD

**Issue by gremito** [xamarin/xamarin-android#4069]
## problem

Xamarin.iOS apps can work properly with Appium, but Xamarin.Android apps cannot work with Appium.

We believe that this is a problem on the Xamarin side because native Android apps can be linked with Appium.

## all information

The Xamarin.Android app breaks as follows: 
https://twitter.com/grem_ito/status/1208661064428056576

It will be a Japanese document, but details are summarized.
https://qiita.com/gremito/items/8d321a0cd4823fc18d95

**Comment by jonathanpeppers** [comment]
Since we are not familiar with Appium, could you attach a sample app and a couple instructions on how to run the tests?

You might also consider filing a bug here: https://github.com/appium/appium/issues

**Comment by gremito** [comment]
ok, Create an issue in Appium.
Why did you delete https://github.com/xamarin/appium.old ?

**Comment by jonathanpeppers** [comment]
> Why did you delete https://github.com/xamarin/appium.old ?

I'm not sure who was working on this repo, or managing it, sorry.

**Comment by mykola-mokhnach** [comment]
Hi @jonathanpeppers 

To make the task easier for you I would like shed some light on what is happening there. Appium (at least that particular driver) uses [UiAutomator](https://developer.android.com/training/testing/ui-automator) framework from Google to interact with on-screen elements. UiAutomator uses system accessibility for its purposes. This means that if an application is not visible to Appium then the application does not, most likely, exposes its controls (views) to the system [accessibility](https://developer.android.com/guide/topics/ui/accessibility).

**Comment by jonathanpeppers** [comment]
@gremito it sounds like downgrading Appium solved the issue for your Xamarin app?

https://github.com/appium/appium-desktop/issues/849#issuecomment-579188831

Can we close this?

Xamarin exposes Android APIs to C# as-is, so it should be identical to a Java/Kotlin app as far as UiAutomator is concerned. If you are using Xamarin.Forms it is a slightly different story, but it is also built on top of the standard Android APIs: View/Activity, etc.

**Comment by gremito** [comment]
@jonathanpeppers 
Yes, Downgrading to version 1.10.0 solved this problem. 
I think it's okay to close it.
