### ISSUE TITLE
Android App Bundle + Shared Runtime = 💥

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#4071]
### Steps to Reproduce

1. Set some properties
2. Build
3. Run
4. Observe a __Internal dll not found

[AxTest.zip](https://github.com/xamarin/xamarin-android/files/3997088/AxTest.zip)

### Expected Behavior
No 💥

### Actual Behavior
💥

**Comment by jonathanpeppers** [comment]
The IDE didn't let you set this, did it? Had to edit the `csproj` manually?
```xml
<AndroidUseSharedRuntime>true</AndroidUseSharedRuntime>
<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
```
I wouldn't consider this option valid, but maybe we need to make it give a warning and force `$(EmbedAssembliesIntoApk)` to `False` so things work.

**Comment by mattleibow** [comment]
Oh, sorry. not `EmbedAssembliesIntoApk` but the AAB thing.

**Comment by jonathanpeppers** [comment]
So a smaller repro is to just make a new Blank Android App and enable App Bundles.

![image](https://user-images.githubusercontent.com/840039/71686617-51763380-2d61-11ea-9c6c-96ace1a0fb5e.png)

I do get this build warning:
```
Using Fast Deployment and Android App Bundles at the same time is not recommended. Use Fast Deployment for Debug configurations and Android App Bundles for Release configurations.
```

It is probably worth fixing the issue here at some point. But it is weird when I initially implemented App Bundles this scenario worked... 😞

**Comment by mattleibow** [comment]
Again, I should update the issue. I get a runtime issue about not finding __Internal

**Comment by jeromelaban** [comment]
I wish I had found this issue sooner. Now I see the error message, but the general problem is that android builds don't show the errors until the build is actually finished, hiding that message at the top. 

It would probably be best to fail that scenario completely, as in VS 2019 16.6, this is all I get:

```
05-07 22:08:37.366: A/libc(17857): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x11 in tid 17857 (form.calculator), pid 17857 (form.calculator)
05-07 22:08:37.370: I/chatty(1735): uid=1000(system) HwBinder:1735_1 identical 1 line
05-07 22:08:37.401: D/EGL_emulation(2124): eglMakeCurrent: 0xd641a480: ver 3 0 (tinfo 0xd640f0f0)
05-07 22:08:37.406: W/EmuHWC2(1735): validate: layer 210 CompositionType 1, fallback
05-07 22:08:37.419: D/EGL_emulation(2124): eglMakeCurrent: 0xd641a480: ver 3 0 (tinfo 0xd640f0f0)
05-07 22:08:37.421: I/crash_dump32(17880): obtaining output fd from tombstoned, type: kDebuggerdTombstone
05-07 22:08:37.421: I//system/bin/tombstoned(1819): received crash request for pid 17857
05-07 22:08:37.422: I/crash_dump32(17880): performing dump of process 17857 (target tid = 17857)
05-07 22:08:37.431: A/DEBUG(17880): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-07 22:08:37.431: A/DEBUG(17880): Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.191030.002/5978551:userdebug/dev-keys'
05-07 22:08:37.431: A/DEBUG(17880): Revision: '0'
05-07 22:08:37.431: A/DEBUG(17880): ABI: 'x86'
05-07 22:08:37.431: A/DEBUG(17880): Timestamp: 2020-05-07 22:08:37-0400
05-07 22:08:37.431: A/DEBUG(17880): pid: 17857, tid: 17857, name: form.calculator  >>> uno.platform.calculator <<<
05-07 22:08:37.431: A/DEBUG(17880): uid: 10149
05-07 22:08:37.431: A/DEBUG(17880): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x11
05-07 22:08:37.431: A/DEBUG(17880): Cause: null pointer dereference
05-07 22:08:37.431: A/DEBUG(17880):     eax bef21eb5  ebx d305bd00  ecx befe2b58  edx d305bd00
05-07 22:08:37.431: A/DEBUG(17880):     edi e9831b00  esi 00000012
05-07 22:08:37.431: A/DEBUG(17880):     ebp 00000001  esp ffb75ef0  eip becbaa76
```

I had to go back to VS 16.5 to get this error message instead:

```
System.DllNotFoundException: '__Internal assembly:<unknown assembly> type:<unknown type>'
```

**Comment by jpobst** [comment]
The shared runtime was removed in Xamarin.Android 11.2, so I think we can close this.
https://github.com/xamarin/xamarin-android/releases#rewritten-fast-deployment-system-11199168
