### ISSUE TITLE
Xamarin.Android slow build and deploy after no changes in code

### ISSUE THREAD

**Issue by VictorKochetkov** [xamarin/xamarin-android#4072]
Build and deploy on physical device is VERY slow and takes about ~1 minute after NO changes in code and project.

Visual Studio 2019 (Version 16.4.0)

Below is diagnostic logs (there were multiple logs, don't know why) :

> 2>Target Performance Summary:
............
> 2>       49 ms  _ResolveSatellitePaths                     1 calls
> 2>       58 ms  _ConvertCustomView                         1 calls
> 2>       61 ms  IncrementalClean                           1 calls
> 2>       83 ms  ResolveAssemblyReferences                  1 calls
> 2>      134 ms  _CleanGetCurrentAndPriorFileWrites         1 calls
> 2>      224 ms  _ComputeAndroidResourcePaths               1 calls
> 2>      293 ms  _ResolveAssemblies                         1 calls
> 2>      751 ms  GetCopyToOutputDirectoryItems              4 calls
> 2>      822 ms  _GenerateJavaStubs                         1 calls
> 2>      981 ms  _GetProjectReferenceTargetFrameworkProperties   4 calls
> 2>     1351 ms  _GenerateAndroidResourceDir                1 calls
> 2>     7868 ms  _CreateBaseApkWithAapt                     1 calls
> 2>     7886 ms  _CreateBaseApk                             1 calls
> 2>    13113 ms  _UpdateAndroidResgenAapt                   1 calls
> 2>    13349 ms  _UpdateAndroidResgen                       1 calls

>  2>Task Performance Summary:
...........
> 2>       54 ms  RemoveDuplicates                           2 calls
> 2>       55 ms  ConvertCustomView                          1 calls
> 2>       60 ms  FindUnderPath                              5 calls
> 2>       89 ms  CreateItem                                26 calls
> 2>       90 ms  RemoveUnknownFiles                         1 calls
> 2>      132 ms  ResolveAssemblyReference                   2 calls
> 2>      193 ms  GenerateResourceDesigner                   1 calls
> 2>      228 ms  AndroidComputeResPaths                     2 calls
> 2>      272 ms  ResolveAssemblies                          1 calls
> 2>      818 ms  GenerateJavaStubs                          1 calls
> 2>     1138 ms  CopyIfChanged                              1 calls
> 2>     1759 ms  MSBuild                                    7 calls
> 2>     2881 ms  ConvertResourcesCases                      1 calls
> 2>    18099 ms  Aapt                                       2 calls
> 2>    20984 ms  CallTarget                                 3 calls

It seems that `Aapt` and `CallTarget` are slow.
Any suggestions?

**Comment by dellis1972** [comment]
@VictorKochetkov can you upload/gist the diagnostic log or binlog so we can look at what is triggering those targets? We should be able to figure out which files are being touched/updated and following that why those targets are running.

**Comment by jonathanpeppers** [comment]
@VictorKochetkov we would really like to look into this, but need a build log. 😞 

Closing for now, but we can reopen with more info, thanks!
