### ISSUE TITLE
Xamarin Forms Android debug disconnect if not 2 folder levels under .sln file location

### ISSUE THREAD

**Issue by lhughey** [xamarin/xamarin-android#4080]
### Description
An Android Target in an XF project disconnects from the debugger when starting on an emulator or Android device. This happens when the Android project is not 2 levels under the XF solution file (.sln). The disconnect happens without an error and does not occur on iOS.

More details on this error: https://forums.xamarin.com/discussion/comment/397710#Comment_397710

### Steps to Reproduce

1. Create an XF project with Android and iOS targets
2. Create a solutions folder in a higher folder location than the project file. Move both iOS and Droid project files into the solutions folder and fix links to resolve folder move.

**The ending structure should be:**
/Solutions/Droid.csproj
/Solutions/iOS.csproj
/Mobile/Project.sln
/Mobile/Droid/(droid project files)
/Mobile/iOS/(ios project files)
 
### Expected Behavior
Both iOS and Droid will debug.

### Actual Behavior
Only iOS will debug. Android will disconnect from debugger in VS with no error.

### Basic Information

- Version with issue: I've witnessed this error across multiple versions
- Last known good version: Not sure when this issue began. This test case is an odd one, but one I've seen happen twice in 3 weeks. Once with a client, and another time with a new Xamarin user on the forums. 
- IDE: VS 16.3- 16.4 Windows
- Platform Target Frameworks: latest
  - iOS: N/A
  - Android: 9.1
- Android Support Library Version: N/A
- Nuget Packages:N/A
- Affected Devices: Android emulators/Android phones - All

**Comment by jonathanpeppers** [comment]
@lhughey could you be hitting the [Windows MAX_PATH limitation](https://docs.microsoft.com/windows/win32/fileio/naming-a-file#maximum-path-length-limitation)?

Because we use Java, some of the files on disk become quite long. If you move the solution directory to `C:\` does the problem go away?

If not, can you post a sample project, thanks!

**Comment by lhughey** [comment]
I apologize for the delay. This doesn't seem to be related to the max path limitation in windows. The difference in the folder lengths between the folder that doesn't work and the one that does is 3 characters. Also, the folders are not nested deeply.

FYI: The solutions are located in the following folders:
C:\Source\xxxxxxx\Solutions (doesn't work)
C:\Source\xxxxxxx\Mobile (works)

I tried to recreate this issue with the latest version of XF but was unable to do so.  Hopefully someone else can post a repro because the solution I'm working with cannot be posted.

**Comment by jonathanpeppers** [comment]
@lhughey can you explain more about the "disconnect"? Is the app crashing or does the app launch fine if you tap the icon?

If there is nothing printed in the output window in VS, you might check the [android device log or adb logcat](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log).

**Comment by lhughey** [comment]
@jonathanpeppers I'll dig into this and give you some details. I've not dealt with the solution in a few weeks. I'll have something for you tomorrow. Thx

**Comment by lhughey** [comment]
@jonathanpeppers I cannot currently reproduce this issue on my machine. The last time I tried running the solution at the location where it fails was about 6 weeks ago. I have since moved the solution to a new location.

FYI  I'm currently using:
- VS 16.4.2
Xamarin.Android 10.1.1.0

**Comment by radekdoulik** [comment]
We are unable to investigate this issue further without a way to reproduce.

Feel free to reopen the issue if it happens again and is reproducible.
