### ISSUE TITLE
Re-enable Linux build on Jenkins

### ISSUE THREAD

**Issue by janusw** [xamarin/xamarin-android#4116]
Recently the build of xamarin-android on Linux seems to be working again, at least for certain flavors. While Ubuntu 16.04 currently fails, I was able to perform a successful build on 18.04, generating a tarball `xamarin.android-oss-v10.2.99.129_Linux-x86_64_master_7674dad7-Debug.tar.bz2`.

The Jenkins build on Linux at https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/ seems to be disabled since July 31, 2019, and was failing since Apr 17, 2019, see https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/lastSuccessfulBuild/ (version 9.2.99.172).

It would be great if the build could be enabled again. There are a number of tutorials on the web for using xamarin-android on Linux, all of which refer to the old version mentioned above.

**Comment by lordofffarm** [comment]
Yes, please re-enable

**Comment by mungojam** [comment]
It's broken again, I think because of lack of disk space:

https://dev.azure.com/xamarin/public/_build?definitionId=48&_a=summary&repositoryFilter=35&branchFilter=1795

**Comment by mungojam** [comment]
It seems it has never actually run successfully, unless I am looking in the wrong place:

https://dev.azure.com/xamarin/public/_build?definitionId=48&_a=summary&repositoryFilter=35&branchFilter=1795%2C2099%2C2511&statusFilter=succeeded%2Cwarning

**Comment by brendanzagaeski** [comment]
The "No space left on device" error is being tracked in: https://github.com/xamarin/xamarin-android/issues/4432

**Comment by janusw** [comment]
> It seems it has never actually run successfully, unless I am looking in the wrong place:

If you go to https://dev.azure.com/xamarin/public/_build?definitionId=48&_a=summary and scroll all the way down you'll see two successful builds from end of January. Everything since then has failed or was canceled apparently. (You should remove the filter on branch, then you should see them as well ...)

**Comment by janusw** [comment]
Btw, I just noticed that building on Ubuntu bionic seems to fail again. It was working in early March IIRC. Will open a new issue for that soon ...

**Comment by janusw** [comment]
> Btw, I just noticed that building on Ubuntu bionic seems to fail again. It was working in early March IIRC. Will open a new issue for that soon ...

See #4546.
