### ISSUE TITLE
Can no longer inherit from MockContext on API28

### ISSUE THREAD

**Issue by pellet** [xamarin/xamarin-android#4128]
### Steps to Reproduce

1. Set project to use API 28 instead of 27.
2. Inherit from Android.Test.Mock.MockContext for testing purposes.
3. Try to compile the project.

### Expected Behavior
Project compiles ok.

### Actual Behavior
Binding issues occur due to unsupported java features when inheriting from a java class.

### Version Information
API 28.

Visual Studio Community 2019 for Mac
Version 8.4.1 (build 4)
Installation UUID: 5049d043-10da-4ab1-931f-e1424147a79f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

Mono Framework MDK
Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

Roslyn (Language Service)
3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.0.101
	3.0.100
	2.2.300
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.0.1
	3.0.0
	2.2.5
	2.1.14
	2.1.13

Xamarin.Profiler
Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/ben/Library/Android/sdk
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Microsoft Mobile OpenJDK
Java SDK: /Users/ben/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-08 19:54:56 UTC

Android Device Manager
Version: 16.4.0.28
Hash: 68e9956
Branch: remotes/origin/d16-4
Build date: 2020-01-08 19:55:18 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Xamarin Designer
Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

Apple Developer Tools
Xcode 11.2.1 (15526.1)
Build 11C504

Xamarin.Mac
Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

Xamarin.iOS
Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

Build Information
Release ID: 804010004
Git revision: 5f675128315bd5886b283aa192b334a02bc8a758
Build date: 2020-01-10 13:54:46+00
Build branch: release-8.4
Xamarin extensions: 6e5c119bf1e7b092680c1491be659f152329f74e

Operating System
Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
    root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

### Log File

```
  TestHarness.Droid -> /Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/bin/Debug/TestHarness.dll
  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
  obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java:5: error: package android.test.mock does not exist
  	extends android.test.mock.MockContext
  	                         ^
  obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java:24: error: cannot find symbol
  		if (getClass () == ContextMockBuilder_LooseMockContext.class)
  		    ^
    symbol:   method getClass()
    location: class ContextMockBuilder_LooseMockContext
  Note: Some input files use or override a deprecated API.
  Note: Recompile with -Xlint:deprecation for details.
  Note: Some input files use unchecked or unsafe operations.
  Note: Recompile with -Xlint:unchecked for details.
  2 errors
obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java(5,27): javac error JAVAC0000:  error: package android.test.mock does not exist [/Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/TestHarness.Droid.csproj]
obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java(5,27): javac error JAVAC0000: 	extends android.test.mock.MockContext [/Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/TestHarness.Droid.csproj]
obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java(5,27): javac error JAVAC0000:  [/Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/TestHarness.Droid.csproj]
obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java(24,7): javac error JAVAC0000:  error: cannot find symbol [/Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/TestHarness.Droid.csproj]
obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java(24,7): javac error JAVAC0000: 		if (getClass () == ContextMockBuilder_LooseMockContext.class) [/Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/TestHarness.Droid.csproj]
obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java(24,7): javac error JAVAC0000:   symbol:   method getClass() [/Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/TestHarness.Droid.csproj]
obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java(24,7): javac error JAVAC0000:   location: class ContextMockBuilder_LooseMockContext [/Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/TestHarness.Droid.csproj]
obj/Debug/android/src/crc646b9eac36eb384388/ContextMockBuilder_LooseMockContext.java(24,7): javac error JAVAC0000:  [/Users/ben/dev/SmartCapLifeMobileApp/Src/TestHarness.Droid/TestHarness.Droid.csproj]
```

**Comment by jonpryor** [comment]
This actually “feels like” a “not using an existing `android.jar`” problem.

Could you please provide a repro or the complete diagnostic build log?

Thanks!

**Comment by jonathanpeppers** [comment]
It looks like this class was moved out of `android.jar` in API 28:

![image](https://user-images.githubusercontent.com/840039/74844745-8af40580-52f3-11ea-9089-18a8aaff006b.png)

To compare API 27:

![image](https://user-images.githubusercontent.com/840039/74844791-9c3d1200-52f3-11ea-9b1d-a713871dd54c.png)

I added some support to deal types moving in the commit here: https://github.com/xamarin/xamarin-android/commit/b08240ee50e941cb326688cc0dcf5969ebfe5473

You could try adding this to your `AndroidManifest.xml`:
```xml
	<uses-library
	    android:name="android.test.mock"
	    android:required="false"
	/>
</application>
```

I have not tried an example of using a type in this `android.test.mock.jar`. If you can't get it to work, could you make a small sample to upload here? Thanks!

**Comment by pellet** [comment]
Thanks @jonathanpeppers it's compiling again now and I can use mockcontext as part of my integration tests 😺
