### ISSUE TITLE
'make jenkins' fails on Ubuntu 18.04 (/usr/bin/x86_64-w64-mingw32-ld: cannot find -lmincore) 

### ISSUE THREAD

**Issue by janusw** [xamarin/xamarin-android#4144]
### Steps to Reproduce

1. git clone https://github.com/xamarin/xamarin-android.git
2. cd xamarin-android
4. make jenkins

### Expected Behavior

`make` should run through without errors.

### Actual Behavior

After a while the following error occurs:

```
  /usr/bin/x86_64-w64-mingw32-ld: cannot find -lmincore
collect2 : error : ld returned 1 exit status [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
  ninja: build stopped: subcommand failed.
/home/janus/github/xamarin-android/src/monodroid/monodroid.targets(93,5): error MSB3073: The command "/home/janus/android-toolchain/sdk/cmake/3.10.2.4988404/bin/ninja -v" exited with code 1. [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
Done Building Project "/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj" (default targets) -- FAILED.
```

### Version Information

* xamarin-android version: master as of 2020-01-17 (commit fdc9f621cd2ff7645729a447df5595dc1497d4b4)
* OS: Ubuntu Linux 18.04 (bionic)
* Mono version: 6.4.0.198
* msbuild version: Microsoft (R) Build Engine version 16.3.0-ci for Mono

### Log File

If necessary I can attach the full build log or provide further information.

**Comment by grendello** [comment]
@janusw this, again, is unfortunately something too old - this time mingw. You need a newer one which isn't available in 18.04. However, there's no need for you to build the Windows bits, most probably. To that end, do not use `make jenkins` - it enables everything we have (and takes ages to build). If you need to build XA for several API levels (instead of the default one, which is the latest supported at the build time - currently API29) instead replace your step 3. with:

1. `make prepare all`
2. `make API_LEVEL=XY`

and repeat step 2. for each of the API levels you need.

Once more, I'm afraid we cannot fix the issue as we can't update Ubuntu 18.04 mingw on our end.

**Comment by janusw** [comment]
> @janusw this, again, is unfortunately something too old - this time mingw.

Ok. It seems that `make prepare` has checks for mingw stuff, though (in particular g++-mingw-w64, gcc-mingw-w64 and libz-mingw-w64-dev). Those checks probably should be updated then? Which version is required?

**Comment by grendello** [comment]
Yeah, we should make those optional if Windows cross build isn't enabled. You need mingw 6.

**Comment by janusw** [comment]
> Yeah, we should make those optional if Windows cross build isn't enabled.

Turns out `make prepare` only checks for the mingw compilers, but not for the actual `mingw-w64` packages.

> You need mingw 6.

Ubuntu 18.04 has version 5.0.3.

**Comment by grendello** [comment]
> > Yeah, we should make those optional if Windows cross build isn't enabled.
> 
> Turns out `make prepare` only checks for the mingw compilers, but not for the actual `mingw-w64` packages.

`xaprepare` checks for `g++-mingw-w64` which is a [package](https://packages.ubuntu.com/search?keywords=g%2B%2B-mingw-w64&searchon=names&suite=eoan&section=all)

**Comment by janusw** [comment]
> > Turns out `make prepare` only checks for the mingw compilers, but not for the actual `mingw-w64` packages.
> 
> `xaprepare` checks for `g++-mingw-w64` which is a [package](https://packages.ubuntu.com/search?keywords=g%2B%2B-mingw-w64&searchon=names&suite=eoan&section=all)

Sure it's a package, but it's the compiler for mingw, not the mingw environment itself, right?

When you mentioned above that mingw version 6 is required, I assume you were talking about the environment (mingw-w64*) and not the compiler (g++-mingw-w64), since the latter is present in version 7.3.0 on Ubuntu 18.04, which would actually meet your requirement.

So what I think is missing is a check for the package mingw-w64 in version 6. For g++-mingw-w64 there is already a check, which passes on Ubuntu 18.04. But since the mingw stuff is not needed for a basic build, but only for a full build ('make jenkins'), those checks should somehow be optional.
