### ISSUE TITLE
"Unable to read profile ... The system cannot find the file specified" for adb.exe when attempting to complete profiling with FinishAotProfiling

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#4152]
### Steps to reproduce

 1. Create a new Android Single View App project.

 2. Open **Tools > Command Line > Developer Command Prompt**.

 3. Ensure that a target Android device is attached.

 4. Run the following command in the solution directory:

    ```cmd
    msbuild -t:BuildAndStartAotProfiling
    ```

 5. After the app launches successfully, run the following command:

    ```cmd
    msbuild -t:FinishAotProfiling
    ```
 
### Expected behavior

The `FinishAotProfiling` target completes successfully.

### Actual behavior

The `FinishAotProfiling` target fails:

```
Task "Exec" (TaskId:12)
  Task Parameter:Command="C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\aprofutil"  -s -v -f -p 9999 -o "custom.aprof" (TaskId:12)
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\aprofutil"  -s -v -f -p 9999 -o "custom.aprof" (TaskId:12)
  Calling 'adb forward tcp:9999 tcp:9999'... (TaskId:12)
EXEC : error : aotprofile-tool: Unable to read profile through local port: 9999.
  System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified (TaskId:12)
     at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo) (TaskId:12)
     at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) (TaskId:12)
     at aotprofiletool.MainClass.ReadProfileFromPort(ProfileReader reader) (TaskId:12)
     at aotprofiletool.MainClass.Main(String[] args) (TaskId:12)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Application.targets(62,5): error MSB3075: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\aprofutil"  -s -v -f -p 9999 -o "custom.aprof"" exited with code 5. Please verify that you have sufficient rights to run this command.
Done executing task "Exec" -- FAILED. (TaskId:12)
```

Perhaps of interest, the `adb logcat` output seems to indicate that profiling started successfully on the device:

```
01-20 22:48:31.937  7781  7781 W monodroid: Initializing profiler with options: aot:port=9999,output=/data/user/0/com.companyname.androidsingleviewapp1/files/.__override__/profile.aotprofile
```

The following command also ran successfully when I ran it by hand:

```
adb forward tcp:9999 tcp:9999
```

And `netstat` on the device seems to indicate it is indeed listening on port 9999:

```
C:\>adb shell netstat -n -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN
```

### Version information

  * Visual Studio 2019 version 16.5 Internal Preview
  * Xamarin.Android SDK   10.2.0.84 (d16-5/ac3f71f)
      * Mono: df42020
      * Java.Interop: xamarin/java.interop/d16-5@c0cc770
      * ProGuard: xamarin/proguard/master@905836d
      * SQLite: xamarin/sqlite/3.28.0@46204c4
      * Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Android 9.0 (API level 28) arm64-v8a Google Pixel 3

### Log files

[logs.zip](https://github.com/xamarin/xamarin-android/files/4089629/logs.zip)

**Comment by ysmoradi** [comment]
I'm using vs 16.5 prev 3 and there is an error as followings:
```
Unable to read profile through local port: 9999
```
I'm running with administrator privileges and there is no firewall in the middle )-:

**Comment by brendanzagaeski** [comment]
### Workaround

I was able to work around the *Unable to read profile ... The system cannot find the file specified* error by adding the directory containing `adb.exe` to the `PATH` environment variable in the Developer Command Prompt before running `msbuild -t:FinishAotProfiling`:

```bat
set PATH=%PATH%;"C:\Program Files (x86)\Android\android-sdk\platform-tools"
msbuild -t:FinishAotProfiling
```

### Additional notes

It seems that `msbuild -t:FinishAotProfiling` might not yet do any steps to ensure the path to `adb.exe` is known before `aprofutil` [attempts to start it](https://github.com/mono/mono/blob/2e73a3a25a208ebf11d6556117bed50f8486af0e/mcs/tools/aprofutil/Program.cs#L131).

**Comment by AleksandrAlekseev** [comment]
@brendanzagaeski Thanks for solution for Windows, it works! I tested under Parallels on Windows.

But i have build on Mac and have some error, have any solution?

**Comment by brendanzagaeski** [comment]
## Workaround for macOS

Ah yes, on macOS, the workaround would be similar. For the default install path that Visual Studio for Mac uses for `adb`, the workaround would be:

```sh
PATH="$PATH":"$HOME/Library/Developer/Xamarin/android-sdk-macosx/platform-tools/"
msbuild -t:FinishAotProfiling
```

**Comment by MathieuJack** [comment]
I have the same problem, on MacOS.
Changing the PATH did not work for me. 
I tried : Turning off firewall, and launching command as administrator.

Here is the full output:
Projet "/Users/yadusurf/Documents/KODE/GIT/YDSMobile/Yadusurf.XamarinForms.Android/Yadusurf.XamarinForms.Android.csproj" sur le nœud 1 (FinishAotProfiling cible(s)).
_ResolveSdks:
  Found Java SDK version 1.8.0.
  Found Java SDK version 1.8.0.
FinishAotProfiling:
  "/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Darwin/aprofutil"  -s -v -f -p 9999 -o "custom.aprof"
  Calling 'adb forward tcp:9999 tcp:9999'...
  Reading from '127.0.0.1:9999'...
  Read total 0 bytes...
EXEC : error : aotprofile-tool: Unable to read profile through local port: 9999. [/Users/yadusurf/Documents/KODE/GIT/YDSMobile/Yadusurf.XamarinForms.Android/Yadusurf.XamarinForms.Android.csproj]
  System.IO.IOException: Input file is too small.
    at Mono.Profiler.Aot.ProfileReader.ReadAllData (System.IO.Stream stream) [0x00028] in <606ae1055ec743649dfd540827b20abb>:0 
    at aotprofiletool.MainClass.ReadProfileFromPort (Mono.Profiler.Aot.ProfileReader reader) [0x0012e] in <9387e4304a5e43a0be3ce68086330df9>:0 
    at aotprofiletool.MainClass.Main (System.String[] args) [0x00048] in <9387e4304a5e43a0be3ce68086330df9>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Application.targets(62,5): error MSB3075: La commande ""/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Darwin/aprofutil"  -s -v -f -p 9999 -o "custom.aprof"" s'est arrêtée avec le code 5. Assurez-vous d'avoir les droits suffisants pour exécuter cette commande. [/Users/yadusurf/Documents/KODE/GIT/YDSMobile/Yadusurf.XamarinForms.Android/Yadusurf.XamarinForms.Android.csproj]
Génération du projet "/Users/yadusurf/Documents/KODE/GIT/YDSMobile/Yadusurf.XamarinForms.Android/Yadusurf.XamarinForms.Android.csproj" terminée (FinishAotProfiling cible(s)) -- ÉCHEC.

ÉCHEC de la build.

"/Users/yadusurf/Documents/KODE/GIT/YDSMobile/Yadusurf.XamarinForms.Android/Yadusurf.XamarinForms.Android.csproj" (FinishAotProfiling cible) (1) ->
(FinishAotProfiling cible) -> 
  EXEC : error : aotprofile-tool: Unable to read profile through local port: 9999. [/Users/yadusurf/Documents/KODE/GIT/YDSMobile/Yadusurf.XamarinForms.Android/Yadusurf.XamarinForms.Android.csproj]
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Application.targets(62,5): error MSB3075: La commande ""/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Darwin/aprofutil"  -s -v -f -p 9999 -o "custom.aprof"" s'est arrêtée avec le code 5. Assurez-vous d'avoir les droits suffisants pour exécuter cette commande. [/Users/yadusurf/Documents/KODE/GIT/YDSMobile/Yadusurf.XamarinForms.Android/Yadusurf.XamarinForms.Android.csproj]

    0 Avertissement(s)
    2 Erreur(s)

**Comment by brendanzagaeski** [comment]
@MathieuJack, the error messages from this feature are a little tricky at the moment because they show several of the same lines in the output for a few different problems. In this case, the important lines from what you're seeing are:

> Read total 0 bytes...

and

> System.IO.IOException: Input file is too small.

That's a different complication than this item (#4152). The messages you're seeing can happen if the app is for some reason no longer running on the device when the `FinishAotProfiling` target is invoked or if the app didn't start with the correct settings during the `BuildAndStartAotProfiling` target.

If you get stuck on that issue after retrying the `BuildAndStartAotProfiling` target, the best next step would be to submit a new issue and attach the following info so the team can take a look:

  * The diagnostic MSBuild output from the `BuildAndStartAotProfiling` step
  * The `adb logcat` output from the device during both the `BuildAndStartAotProfiling` step and the `FinishAotProfiling` step

Thanks in advance!

**Comment by softlion** [comment]
Why is it not fixed in VS since January ? Still need to add the PATH trick !
Just fall on it today using latest stable VS2019 Enterprise on Windows.

**Comment by mduchev** [comment]
I am also waiting. 😴

**Comment by jonpryor** [comment]
The complexity here is that `aprofutil` comes [from mono](https://github.com/mono/mono/tree/master/mcs/tools/aprofutil), and `aprofutil` doesn't currently provide a mechanism to specify the path to `adb`.

@radekdoulik: can we add an `aprofutil --adb-path` option, so that `adb` doesn't need to be in `$PATH`?  Alternatively, we could set `Exec.EnvironmentVariables` to override `$PATH` to include `$(AdbToolPath)`.

**Comment by radekdoulik** [comment]
@jonpryor I think I will temporarily fix it by setting up the adb port forwarding in our targets, without leaving that on `aproutil`.

Longterm, I will add an option to `aprofutil` tool.

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.4.0.0.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by trampster** [comment]
I'm having this issue with the same error, except that I have added the adb path, and it is still failing in the same way.

**Comment by trampster** [comment]
This happens if you already have a custom.aprof file, deleting the old one makes it work again.

**Comment by brendanzagaeski** [comment]
Thanks for the additional findings trampster! I attempted to reproduce the problem where `FinishAotProfiling` fails with _System.IO.IOException: Input file is too small_ if the project already contains a _custom.aprof_ file. So far, I have not been able to reproduce that problem. I repeated the [steps to collect a custom profile](https://docs.microsoft.com/xamarin/android/release-notes/10/10.2#custom-profiles-for-enable-startup-tracing) through several iterations of adding the new _custom.aprof_ file to the project, cleaning, and rerunning the `BuildAndStartAotProfiling` and `FinishAotProfiling` targets. Both targets completed successfully across all the repetitions in my tests so far.

If you can consistently reproduce that problem, then if you get a chance to submit a [new issue](https://github.com/xamarin/xamarin-android/issues/new/choose) with the diagnostic MSBuild output and `adb logcat` output from the failing scenario so the team can take a look, that would be excellent, but no worries if not. Thanks!

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item that was [previously published in the Preview versions](https://github.com/xamarin/xamarin-android/issues/4152#issuecomment-648454568).

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by IainS1986** [comment]
Tried out the latest release of Xamarin Android and no longer got this error, but I'm not sure the profile generated is working.

I followed this article https://ryandavis.io/using-custom-aot-profiles-with-xamarin-android/

I'm generating the custom .aprof file fine, turned off AOT and LLVM that I was using before and instead hooked it up to use the custom .aprof, but I'm getting an assertion firing...

'[aot-compiler stdout] Using profile data file '/Users/*******/Dev/******/src/******.Droid/custom.aprof'
    [aot-compiler stdout] * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/mini/aot-compiler.c:12409, condition `res == len' not met
    [aot-compiler stdout]'

Any thoughts on what I'm doing wrong or if this is a common issue?

**Comment by IainS1986** [comment]
Further: If I try to inspect the aprof file using,

    aprofutil -s custom.aprof

Then it errors with

    Unhandled Exception:
    System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
    Parameter name: bytes
      at System.Text.UTF8Encoding.GetCharCount (System.Byte[] bytes, System.Int32 index, System.Int32 count) [0x0003e] in <b62523977edc47f990e8bfd12c39abb8>:0 
      at System.Text.Encoding.GetChars (System.Byte[] bytes, System.Int32 index, System.Int32 count) [0x00000] in <b62523977edc47f990e8bfd12c39abb8>:0 
      at Mono.Profiler.Aot.ProfileReader.ReadString () [0x0000c] in <50d9b186fcd54ebcaeed64a60dc51245>:0 
      at Mono.Profiler.Aot.ProfileReader.ReadAllData (System.IO.Stream stream) [0x0025d] in <50d9b186fcd54ebcaeed64a60dc51245>:0 
      at aotprofiletool.MainClass.Main (System.String[] args) [0x000c5] in <760466f08cbf46d488c659de1f35f29d>:0 
    [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
    Parameter name: bytes
      at System.Text.UTF8Encoding.GetCharCount (System.Byte[] bytes, System.Int32 index, System.Int32 count) [0x0003e] in <b62523977edc47f990e8bfd12c39abb8>:0 
      at System.Text.Encoding.GetChars (System.Byte[] bytes, System.Int32 index, System.Int32 count) [0x00000] in <b62523977edc47f990e8bfd12c39abb8>:0 
      at Mono.Profiler.Aot.ProfileReader.ReadString () [0x0000c] in <50d9b186fcd54ebcaeed64a60dc51245>:0 
      at Mono.Profiler.Aot.ProfileReader.ReadAllData (System.IO.Stream stream) [0x0025d] in <50d9b186fcd54ebcaeed64a60dc51245>:0 
      at aotprofiletool.MainClass.Main (System.String[] args) [0x000c5] in <760466f08cbf46d488c659de1f35f29d>:0 


When the aprof is generated though, no errors are reported and it prints out the follow...

    Read 4096 bytes...
    Read 4096 bytes...
    ...
    Read 761 bytes...
    Read total 1315577 bytes...
    Summary:
        Modules:         49
        Types:        3,073
        Methods:     12,778
    Going to write the profile to 'custom.aprof'

**Comment by brendanzagaeski** [comment]
@IainS1986, thanks for the information. At first look, I suspect those behaviors depend on the particular set of references and methods the app is using, similar to <https://github.com/xamarin/xamarin-android/issues/4602>.

When you get a chance, the best next step would to copy your comments into a new issue for further investigation by the team. Thanks in advance!

**Comment by IainS1986** [comment]
@brendanzagaeski  sorry for the really late reply, I got way laid with other features and didn't see notification from this.

I've retried generating custom profiles and using them but ran into a different issue that I see a ticket is already raid for, left a comment in there you can see above ^

**Comment by trampster** [comment]
Just updated my startup tracing for and can confirm that this is still an issue. 
Visual Studio 2019 Version 16.9.3
Xamarin.Android SDK - 11.2.2.1

**Comment by kurema** [comment]
Note:
If you still have problem with "/p:AndroidAotProfilerPort=12345" option, make sure you use the option both on `msbuild /t:BuildAndStartAotProfiling` and `msbuild /t:FinishAotProfiling`. Either doesn't work.

```
$ msbuild /t:BuildAndStartAotProfiling /p:AndroidAotProfilerPort=12345
$ msbuild /t:FinishAotProfiling xxxxx.csproj /p:AndroidAotProfilerPort=12345
```
