### ISSUE TITLE
building xamarin-android fails on Ubuntu 16.04 (FAILED: CMakeFiles/mono-android.debug.dir/jni/designer-assemblies.cc.o)

### ISSUE THREAD

**Issue by janusw** [xamarin/xamarin-android#4155]
Follow-up to #4100 ...

### Steps to Reproduce

1. git clone https://github.com/xamarin/xamarin-android.git
2. cd xamarin-android
3. make prepare
4. make

### Expected Behavior

`make` should run through without errors.

### Actual Behavior

The build now fails with the following errors:

```
FAILED: CMakeFiles/mono-android.debug.dir/jni/designer-assemblies.cc.o 
  /usr/bin/c++  -DDEBUG=1 -DHAVE_CONFIG_H -DJI_DLL_EXPORT -DMONO_DLL_EXPORT -D_GNU_SOURCE -D_REENTRANT -Dmono_android_debug_EXPORTS -I../../../in -I/home/janus/android-toolchain/jdk/include -I/home/janus/android-toolchain/jdk/include/linux -I../../../../../bin/Debug/include/host-Linux -I../../../../../bin/Debug/include/host-Linux/eglib -I../../../../../bin/Release/include/host-Linux -I../../../../../bin/Release/include/host-Linux/eglib -I../../../../../bin/Debug/include/mono-2.0 -I../../../jni -I../../../../../bin/Debug/include -I../../../../../bin/Debug/include/eglib -I../../../../../bin/Release/include -I../../../../../bin/Release/include/eglib -I/home/janus/github/xamarin-android/external/mono/mono/eglib -I../../../jni/zip -I../../../../../external/Java.Interop/src/java-interop -Iinclude -I../../../include -fno-strict-aliasing -ffunction-sections -funswitch-loops -finline-limit=300 -fvisibility=hidden -fstack-protector-strong -Wa,-noexecstack -fPIC -ggdb3 -fno-omit-frame-pointer -O0 -fno-rtti -fno-exceptions -Wall -Wconversion -Wdeprecated -Werror=format-security -Wformat -Wformat-security -Wsign-compare -Wuninitialized   -g -fPIC   -DLINUX -Dlinux -D__linux__ -std=gnu++1z -MD -MT CMakeFiles/mono-android.debug.dir/jni/designer-assemblies.cc.o -MF CMakeFiles/mono-android.debug.dir/jni/designer-assemblies.cc.o.d -o CMakeFiles/mono-android.debug.dir/jni/designer-assemblies.cc.o -c ../../../jni/designer-assemblies.cc
  In file included from ../../../jni/designer-assemblies.hh:4:0,
                   from ../../../jni/designer-assemblies.cc:1:
../../../jni/jni-wrappers.hh(11,18): error GF2421F32: expected ‘{’ before ‘::’ token [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
   namespace xamarin::android
                    ^
../../../jni/jni-wrappers.hh(11,20): error GC3FDACD2: ‘android’ in namespace ‘::’ does not name a type [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
   namespace xamarin::android
                      ^
  In file included from ../../../jni/designer-assemblies.cc:1:0:
../../../jni/designer-assemblies.hh(11,18): error GF2421F32: expected ‘{’ before ‘::’ token [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
   namespace xamarin::android::internal {
                    ^
../../../jni/designer-assemblies.hh(11,20): error GC3FDACD2: ‘android’ in namespace ‘::’ does not name a type [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
   namespace xamarin::android::internal {
                      ^
  In file included from ../../../jni/basic-utilities.hh:5:0,
                   from ../../../jni/util.hh:39,
                   from ../../../jni/globals.hh:6,
                   from ../../../jni/designer-assemblies.cc:2:
/usr/include/c++/5/cstdint(48,11): error G5F1B7AA2: ‘::int8_t’ has not been declared [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
     using ::int8_t;
             ^
/usr/include/c++/5/cstdint(49,11): error G68AD136A: ‘::int16_t’ has not been declared [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
     using ::int16_t;
             ^
/usr/include/c++/5/cstdint(50,11): error G12CF86E5: ‘::int32_t’ has not been declared [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
     using ::int32_t;
             ^
/usr/include/c++/5/cstdint(51,11): error G4C1D5BCD: ‘::int64_t’ has not been declared [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
     using ::int64_t;
             ^
```

After these errors, several more of the same type follow. Similar errors occur also in other files:

```
  FAILED: CMakeFiles/mono-android.debug.dir/jni/debug-constants.cc.o 
  FAILED: CMakeFiles/mono-android.debug.dir/jni/basic-utilities.cc.o 
  FAILED: CMakeFiles/mono-android.debug.dir/jni/basic-android-system.cc.o 
  FAILED: CMakeFiles/mono-android.debug.dir/jni/debug.cc.o 
  FAILED: CMakeFiles/mono-android.debug.dir/jni/android-system.cc.o 
```

### Version Information

* xamarin-android version: master as of 2020-01-21 (commit 198875ec78e7435e53fd2ade8601ac346b993f00)
* OS: Ubuntu Linux 16.04 (xenial)
* Mono version: 6.4.0.198
* msbuild version: Microsoft (R)-Build-Engine, Version 16.3.0-ci für Mono

### Log File

If necessary I can attach the full build log or provide further information.

**Comment by janusw** [comment]
> ```
>   In file included from ../../../jni/basic-utilities.hh:5:0,
>                    from ../../../jni/util.hh:39,
>                    from ../../../jni/globals.hh:6,
>                    from ../../../jni/designer-assemblies.cc:2:
> /usr/include/c++/5/cstdint(48,11): error G5F1B7AA2: ‘::int8_t’ has not been declared [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
>      using ::int8_t;
>              ^
> ```

This smells a lot like missing C++11 support:
* `std::int8_t` has been introduced in C++11
* Ubuntu 16.04 includes gcc version 5, which by default uses `-std=gnu++03` for C++ code AFAICS
* the problems above do not seem to occur on Ubuntu 18.04 (with gcc 7, which by default uses `-std=g++14`)

In consequence, the easiest fix would supposedly be to use the flag `-std=gnu++11` (or `-std=gnu++14`?) when compiling C++ code.

**Comment by janusw** [comment]
Just noticed that my output snippet above includes the flag `-std=gnu++1z`, which should in principle include C++11 support, of course. However, the gcc 5 manual describes it as 'highly experimental'.

**Comment by janusw** [comment]
Trying the following patch:

```
diff --git a/src/monodroid/CMakeLists.txt b/src/monodroid/CMakeLists.txt
index ff8c821..ab9699a 100644
--- a/src/monodroid/CMakeLists.txt
+++ b/src/monodroid/CMakeLists.txt
@@ -2,7 +2,7 @@ cmake_minimum_required(VERSION 3.6.0)
 
 project(libmonodroid C CXX)
 
-set(CMAKE_CXX_STANDARD 17)
+set(CMAKE_CXX_STANDARD 14)
 set(CMAKE_CXX_STANDARD_REQUIRED ON)
 set(CMAKE_CXX_EXTENSIONS ON)
```

gives me errors like this:

```
  In file included from ../../../jni/embedded-assemblies-zip.cc:7:
../../../jni/embedded-assemblies.hh(10,18): warning G898D995E: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions] [/home/janus/github/xamarin-android/src/monodroid/monodroid.csproj]
  namespace xamarin::android::internal {
                   ^~~~~~~~~~~~~~~~~~~
                    { namespace android { namespace internal
```

Apparently xamarin-android requires C++17, but gcc 5 is simply too old to support this properly.

**Comment by grendello** [comment]
@janusw Yes, indeed. We need C++17, but even for C++11 gcc5 might be a tad too old I'm afraid. You can try to use clang from the distro, but I doubt it would fare any better. However, if you build XA on a machine with newer compiler it should still work on Ubuntu 16.04 as we don't use any STL. I'm sorry but I don't think we can fix the issue :(

**Comment by janusw** [comment]
I worked around it using newer GCC packages from this PPA:
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

With gcc 6.5 one still gets errors, but gcc 7.4 seems to work. One just hast to use `export CXX=g++-7` before starting the xamarin-android build.

In summary, it seems that xamarin-android requires a C++ compiler with proper support for C++17. For gcc, at least version 7 is necessary (haven't tried clang).

Assuming that it's not easy to get rid of the C++17 requirement, the above prerequisites should at least be documented (at https://github.com/xamarin/xamarin-android/blob/master/Documentation/building/unix/dependencies.md?), and possibly checked by `make prepare`.

**Comment by janusw** [comment]
> I'm sorry but I don't think we can fix the issue :(

Understood. But please update the documentation accordingly!

**Comment by grendello** [comment]
@janusw if gcc 7.4 works for you, you can try the following:

1. Edit https://github.com/xamarin/xamarin-android/blob/master/build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Unix.cs#L10 and change the constant to `gcc-7`
2. Edit https://github.com/xamarin/xamarin-android/blob/master/build-tools/xaprepare/xaprepare/OperatingSystems/Unix.cs#L33-L43, accordingly setting the compiler names to `gcc-7` and `g++-7`
3. run `make prepare`

`cmake` **may** fail and if it does, export `CXX=g++-7` and `CC=gcc-7` in your environment before running `make prepare`

I will think of a way to make it easier, but this should get you going for now. Please let me know how it worked for you, thanks!

**Comment by grendello** [comment]
> I worked around it using newer GCC packages from this PPA:
> https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
> 
> With gcc 6.5 one still gets errors, but gcc 7.4 seems to work. One just hast to use `export CXX=g++-7` before starting the xamarin-android build.

Please try the steps described in https://github.com/xamarin/xamarin-android/issues/4155#issuecomment-577389537 which expand on this a little bit but generate a more consistent environment than just exporting the variable.

**Comment by grendello** [comment]
@janusw The above commit should make it easier for you to build XA on 16.04

**Comment by janusw** [comment]
> @janusw The above commit should make it easier for you to build XA on 16.04

Thanks a bunch, @grendello. Works pretty well AFAICT.

For the record: I've been able to build XA on Ubuntu 16.04 with:
* gcc 7 (to be precise: 7.4.0)
* clang 5 (that is: 5.0.0-3)
Earlier versions fail (in particular gcc 6.5.0 and clang 4).

Maybe you could extend the build-dependencies documentation to mention the required compiler versions (gcc 7 and clang 5)?
