### ISSUE TITLE
D8 and R8 build error

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/xamarin-android#4194]
### Steps to Reproduce

1. Create Xamarin.forms project
2. Install third party nuget packages (please check list of nuget in attach screen)

![image](https://user-images.githubusercontent.com/1029026/73430999-5d0b4900-4365-11ea-870a-6cc8e92987ef.png)

3. change the build environment to Release
4. Build application

### Expected Behavior
It should be build and run without any error
### Actual Behavior
Getting error please check detail below : 
`Severity	Code	Description	Project	File	Line	Suppression State
Error		"java.exe" exited with code 1.	KegID.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets	79	
`
### Version Information

Microsoft Visual Studio Professional 2019 Preview
Version 16.5.0 Preview 2.0
VisualStudio.16.Preview/16.5.0-pre.2.0+29721.120
Microsoft .NET Framework
Version 4.8.03752

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.400 (d16-5@4a7a7df)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.391 (remotes/origin/d16-5@2aeef9a0a)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.42 (afa79c5)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.84 (d16-5/ac3f71f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: df42020
    Java.Interop: xamarin/java.interop/d16-5@c0cc770
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.14.1.17 (d308800)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File
Please check android Diagnostic output log 

[AndroidLog.txt](https://github.com/xamarin/xamarin-android/files/4132832/AndroidLog.txt)

**Comment by GalaxiaGuy** [comment]
Do you have a custom proguard file? This seems to be the important part:
```
2>  In proguard.cfg: (TaskId:252)
2>    Ignoring option: -optimizations (TaskId:252)
2>  Error in proguard.cfg at line 36, column 28: (TaskId:252)
2>  Expected char '-' at proguard.cfg:36:28 (TaskId:252)
2>  -optimizations optimization_filter  (TaskId:252)
2>                             ^ (TaskId:252)
```

**Comment by gugavaro** [comment]
@jitendrajadav please provide us with a repro project.

**Comment by jitendrajadav** [comment]
> Do you have a custom proguard file? This seems to be the important part:
> 
> ```
> 2>  In proguard.cfg: (TaskId:252)
> 2>    Ignoring option: -optimizations (TaskId:252)
> 2>  Error in proguard.cfg at line 36, column 28: (TaskId:252)
> 2>  Expected char '-' at proguard.cfg:36:28 (TaskId:252)
> 2>  -optimizations optimization_filter  (TaskId:252)
> 2>                             ^ (TaskId:252)
> ```

Yes I do have a custome proguard.cfg file,
let me check with this

**Comment by jitendrajadav** [comment]
> @jitendrajadav please provide us with a repro project.

Sure will have to make it small demo for it because I have a very huge project will update you

**Comment by jonathanpeppers** [comment]
It seems like you might just need to remove this line: `-optimizations optimization_filter`

R8 doesn't support every option ProGuard has, some info on that here: https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md

**Comment by jitendrajadav** [comment]
Thank you @jonathanpeppers I have updated with above guide but still I am not able to get any luck on it I have updated repository as well please check


Updated Log File
Please check android Diagnostic output log
[AndroidLog.txt](https://github.com/xamarin/xamarin-android/files/4158911/AndroidLog.txt)
[Sample Repository](https://github.com/jitendrajadav/D8-and-R8-build-error.git)

**Comment by jonathanpeppers** [comment]
@jitendrajadav hmm, can you remove all lines like these from your `proguard.cfg`?
```
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes InnerClasses
-optimizations optimization_filter 
```
Some of these are in there multiple times. Your project built for me after removing these.

You shouldn't need to put this in here either way.

Since this is an issue with R8, I don't think there is anything we can do for Xamarin.Android here. Let me know if that works for you, thanks!

**Comment by jitendrajadav** [comment]
Thank you @jonathanpeppers after removing above mention it is working thank you again:)

**Comment by michaldobrodenka** [comment]
For me  "java.exe" exited with code 1. error was about Azure notification hub in Xamarin Android.

I had to put
`[assembly: UsesLibrary("org.apache.http.legacy", false)]`

into AssemblyInfo.cs

**Comment by jonathanpeppers** [comment]
> [assembly: UsesLibrary("org.apache.http.legacy", false)]

@michaldobrodenka (or anyone else) if you find any NuGet packages that need this, let them know, so they can put it _inside_ the NuGet package.

This way it would fix it for everyone using the NuGet package.

**Comment by michaldobrodenka** [comment]
@jonathanpeppers MSFT - Xamarin.Azure.NotificationHubs.Android :)

**Comment by jonathanpeppers** [comment]
@michaldobrodenka you might file an issue her, thanks! https://github.com/xamarin/XamarinComponents/tree/master/XPlat/AzureMessaging

It might be they just need to update the binding.
