### ISSUE TITLE
Hang debugging a Xamarin Android app that uses maps

### ISSUE THREAD

**Issue by mfeingol** [xamarin/xamarin-android#4206]
### Steps to Reproduce

1. Enable all CLR exceptions
2. Run the sample project attached below
3. Hit the `switch` button in the app to change from a tile provider that makes HTTP requests and renders tiles from OSM to one that makes local FS requests that fail.
4. When these requests fail, a System.IO.DirectoryNotFoundException is thrown in the OfflineTileProvider class, which is called back from the Map instance. This somehow triggers the hangs while debugging
5. Hit F5, or disable the exception in Exception settings. Observe that the app hangs.

NB: the repro may not be 100%. If you're not seeing a hang, restart VS, enable all exceptions or disable just System.IO.DirectoryNotFoundException and re-run.

NB: you may need to generate a Google Maps API key and use it in `AndroidManifest.xml` where I left a TODO.

Sample project: https://github.com/mfeingol/repros/tree/master/TileExceptionHang

### Expected Behavior

Xamarin Android apps can be debugged without hanging.

### Actual Behavior

Hangs.

### Version Information

VS 2019 16.4.3 on Windows

### Log File

[log.txt](https://github.com/xamarin/xamarin-android/files/4136169/log.txt)

**Comment by gugavaro** [comment]
@grendello have you seen this before?

**Comment by grendello** [comment]
There's not much to go on with here, but looking at the log we have:

```
01-30 12:43:19.053	android_8_1	Warning	19633	monodroid-debug	Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:29258,server=y,embedding=1
01-30 12:43:19.010	android_8_1	Error	2020	adbd	failed to connect to socket 'tcp:29259': Connection refused
```

And there are no errors reported on our side regarding the debug connection. This makes me think the issue is on the IDE side (or possibly on the Mono's soft debugger side). @joj, mind taking a look and bounce it back if you find it's not the IDE?

**Comment by mfeingol** [comment]
@joj: anything I can do to help figure this one out?

**Comment by jpobst** [comment]
If this is still an issue:

This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
