### ISSUE TITLE
IncompatibleClassChangeError when using r8

### ISSUE THREAD

**Issue by jdluzen** [xamarin/xamarin-android#4238]
[d8ICCE.zip](https://github.com/xamarin/xamarin-android/files/4177141/d8ICCE.zip)
### Steps to Reproduce

1. Use the attached project, there was 1 Nuget package added with 1 line of code added in MainActivity: `AdSize.SIZE320x50.ToString();` (Don't mind the misnamed d8ICCEE.zip)

2. Set release build Code shrinker to `r8` to see `IncompatibleClassChangeError` in Android Device Monitor
3. Set release build Code shrinker to `blank` to have it run normally

### Expected Behavior
App to run normally
### Actual Behavior
App crashes with `IncompatibleClassChangeError` in Android Device Monitor
### Version Information
Microsoft Visual Studio Community 2019
Version 16.4.4
VisualStudio.16.Release/16.4.4+29728.190
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA591
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.4.460.23317
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.4.460.23317
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.4.460.23317
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.4.460.23317
Azure Functions and Web Jobs Tools

C# Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.1.209
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.21016.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.87+gbb515bf382
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.24 (1fafd7e)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.226
2.4.226

PeachPie Visual Studio Extension   0.9.46
PeachPie is the PHP language compiler for .NET & .NET Core. It allows for building, integrating, running and debugging of legacy PHP code bases to .NET platform. PeachPie outputs regular .NET assemblies not relying on the native PHP runtime.

This extension provides project templates and other development tools for the PeachPie platform.

Productivity Power Tools 2017/2019   16.0
Installs the individual extensions of Productivity Power Tools 2017/2019

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61912.09160
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

TypeScript Tools   16.0.11031.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.309 (d16-4@1d551f9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.475 (remotes/origin/d16-4@ac250f5aa)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.3.7 (d16-4/d66aed0)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: fd9f379
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.10.0.17 (5f802ef)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

02-09 11:12:44.836: I/MonoDroid(32140): Java.Lang.IncompatibleClassChangeError: no "Lcom/amazon/device/ads/AdSize;" field "SIZE_320x50" in class "Lcom/amazon/device/ads/AdSize;" or its superclasses
02-09 11:12:44.836: I/MonoDroid(32140):   at Java.Interop.JniEnvironment+StaticFields.GetStaticFieldID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <d8da2a6384fc4ec193de1c9303d2c1f2>:0 
02-09 11:12:44.836: I/MonoDroid(32140):   at Android.Runtime.JNIEnv.GetStaticFieldID (System.IntPtr jclass, System.String name, System.String sig) [0x00007] in <d8fc3e98b5ba4cd99316ae125293dda3>:0 
02-09 11:12:44.836: I/MonoDroid(32140):   at Com.Amazon.Device.Ads.AdSize.get_SIZE320x50 () [0x00016] in <68e506ccbf40496cbe6eaa34c2f0a999>:0 
02-09 11:12:44.836: I/MonoDroid(32140):   at d8ICCE.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00034] in <df3e94cdd17e43d5a9bc522d77b4b5a9>:0 
02-09 11:12:44.836: I/MonoDroid(32140):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <d8fc3e98b5ba4cd99316ae125293dda3>:0 
02-09 11:12:44.836: I/MonoDroid(32140):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
02-09 11:12:44.836: I/MonoDroid(32140):   --- End of managed Java.Lang.IncompatibleClassChangeError stack trace ---
02-09 11:12:44.836: I/MonoDroid(32140): java.lang.NoSuchFieldError: no "Lcom/amazon/device/ads/AdSize;" field "SIZE_320x50" in class "Lcom/amazon/device/ads/AdSize;" or its superclasses
02-09 11:12:44.836: I/MonoDroid(32140): 	at crc6407a13cd339700005.MainActivity.n_onCreate(Native Method)
02-09 11:12:44.836: I/MonoDroid(32140): 	at crc6407a13cd339700005.MainActivity.onCreate(Unknown Source:0)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.Activity.performCreate(Activity.java:7136)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.Activity.performCreate(Activity.java:7127)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.os.Looper.loop(Looper.java:193)
02-09 11:12:44.836: I/MonoDroid(32140): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
02-09 11:12:44.836: I/MonoDroid(32140): 	at java.lang.reflect.Method.invoke(Native Method)
02-09 11:12:44.837: I/MonoDroid(32140): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-09 11:12:44.837: I/MonoDroid(32140): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-09 11:12:44.842: D/AndroidRuntime(32140): Shutting down VM
02-09 11:12:44.842: E/AndroidRuntime(32140): FATAL EXCEPTION: main
02-09 11:12:44.842: E/AndroidRuntime(32140): Process: com.companyname.d8icce, PID: 32140
02-09 11:12:44.842: E/AndroidRuntime(32140): java.lang.NoSuchFieldError: no "Lcom/amazon/device/ads/AdSize;" field "SIZE_320x50" in class "Lcom/amazon/device/ads/AdSize;" or its superclasses
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at crc6407a13cd339700005.MainActivity.n_onCreate(Native Method)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at crc6407a13cd339700005.MainActivity.onCreate(Unknown Source:0)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.Activity.performCreate(Activity.java:7136)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.Activity.performCreate(Activity.java:7127)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.os.Looper.loop(Looper.java:193)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at java.lang.reflect.Method.invoke(Native Method)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-09 11:12:44.842: E/AndroidRuntime(32140): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jonathanpeppers** [comment]
@jdluzen adding the proguard rule fixed the problem for me:
```
-keep class com.amazon.device.ads.AdSize { public *; }
```

NuGet packages can add proguard rules themselves, so `DZen.Amazon.Ads` should do this so devs don't have to add this rule in there project.

An example is how Xamarin.Forms does this: https://github.com/xamarin/Xamarin.Forms/blob/655fa004f60e3cfc3820f9a83e7016c763d3ac42/.nuspec/Xamarin.Forms.targets#L172-L176

I would recommend adding a `build/DZen.Amazon.Ads.targets` file to the NuGet that auto-adds any proguard rules needed.

**Comment by jdluzen** [comment]
Thanks Jonathan, I'll add the proguard rules.
By explicitly using using `AdSize.SIZE320x50` in the code, I had hoped that the linker would also let proguard know that it is being used, as this is the first time I've had trouble with r8. Is this not the case? A cursory search did not reveal anything _linking_ the two linkers.

**Comment by jonathanpeppers** [comment]
@jdluzen the linker only adds proguard rules if you _subclass_ a Java class from C#:

https://github.com/xamarin/xamarin-android/blob/87ee20c59a09ba4314f4226e1c77ee2331c3f09f/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/GenerateProguardConfiguration.cs

That I know of, the managed linker hasn't ever generated rules for when methods are _called_ from C#. That is something we can do at some point, possibly? It might be someone attempted to do it in the past, but it generated too many proguard rules.
