### ISSUE TITLE
"ActivityNotFoundException: Device could not find component named: ..." and "Activity class ... does not exist." on Google Pixel 3, Android 10 in Integrated Regression Tests on Windows

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#4239]
### Version info

First failing test run: https://github.com/xamarin/xamarin-android/commit/1a2beeace214c9873b4538963b20ab79a5c5ed4a ([non-public test run](https://dev.azure.com/devdiv/DevDiv/_releaseProgress?releaseId=562253))

Last successful test run: https://github.com/xamarin/xamarin-android/commit/4e389c40b9bbc85126974830a8be84de872b603a ([non-public test run](https://dev.azure.com/devdiv/DevDiv/_releaseProgress?releaseId=558741))

There were [9 commits](https://github.com/xamarin/xamarin-android/compare/4e389c40b9bbc85126974830a8be84de872b603a...1a2beeace214c9873b4538963b20ab79a5c5ed4a) between these test runs:

```
1a2beeac [ci] Check APK sizes on Azure Pipelines
7acc8578 [Xamarin.Android.Build.Tasks] support for $(AdbTarget)
ae70967e [build] Use the CC and CXX envvars to detect compilers on Unix
4d40b70e Use the Framework MSBuild on Mac/Linux
1dedbcf7 [tests] Convert unit tests to short-form style projects
028737c4 [tests] Update Mono.Android_Tests sizes
47e00d7c [CI] Run integrated regression tests in parallel
129e146c [tests] add Install target test when keystore changes
4a17303d [Xamarin.Android.Build.Tasks] merge two targets to fix AndroidX.Migration
```

#### Tests failing on Windows due to "ActivityNotFoundException: Device could not find component named: ..."

```
SqliteShouldRemapCorrectly("89QX0DNTK",[Config: Debug, ])
OverrideDirectories_ShouldStillBeCreated_WhenLoggingPropsAreSet_ForReleaseBuilds("89QX0DNTK")
XARegressionApp_ShouldRunToCompletion_WithNoExpectedFailures("89QX0DNTK",[Config: Debug, ])
XARegressionApp_ShouldRunToCompletion_WithNoExpectedFailures("89QX0DNTK",[Config: Release, ])
ProfilerLogOptions_ShouldCreateMlpdFiles("89QX0DNTK","log:calls,alloc,heapshot")
ProfilerLogOptions_ShouldCreateMlpdFiles("89QX0DNTK","log:heapshot")
ProfilerLogOptions_ShouldCreateMlpdFiles("89QX0DNTK","log:sample")
ProfilerLogOptions_ShouldCreateMlpdFiles("89QX0DNTK","log:nodefaults,exception,monitor,counter,sample-real")
ProfilerLogOptions_ShouldCreateMlpdFiles("89QX0DNTK","log:nodefaults,exception,monitor,counter,sample")
ProfilerLogOptions_ShouldCreateMlpdFiles("89QX0DNTK","log:nodefaults,gc,nogcalloc,gcroot,gcmove,counter")
ProfilerLogOptions_ShouldCreateMlpdFiles("89QX0DNTK","log:alloc")
ProfilerLogOptions_ShouldCreateMlpdFiles("89QX0DNTK","log:nodefaults,gc,gcalloc,gcroot,gcmove,counter")
```

Each of these tests is passing on the MedfieldA99CC2B2 and 4836544432383098 devices.

#### Tests failing due to "Activity class ... does not exist."

```
EnsureHelloBuildsAndContainsSuccessString("89QX0DNTK",[Config: release_standard, ])
```

This test is passing on the MedfieldA99CC2B2 and 4836544432383098 devices.

#### For comparison, tests *passing* on the 89QX0DNTK (Google Pixel 3, Android 10) device

```
RebuildsShouldBeFastWithFastDeployEnabled("89QX0DNTK")
SqliteShouldRemapCorrectly("89QX0DNTK",[Config: Release, ])
OverrideDirectories_ShouldNotBeCreated_ForReleaseBuilds("89QX0DNTK")
DllConfigFiles_ShouldBeFastDeployed("89QX0DNTK")
```

### Preliminary investigation

The problem does not seem to depend on fast deployment. For example, the `OverrideDirectories_ShouldStillBeCreated_WhenLoggingPropsAreSet_ForReleaseBuilds()` does not use fast deployment.

Given that fast deployment apparently isn't involved, it is perhaps interesting then that the `SqliteShouldRemapCorrectly()` test passes in the Release configuration but not in the Debug configuration.

So far I have not been able to reproduce the problem locally by running the `SqliteShouldRemapCorrectly()` test. I tested the following devices:

  * Google Pixel 3, Android 9
  * system-images;android-29;google_apis_playstore;x86_64 emulator, Android 10

**Comment by jonathanpeppers** [comment]
@brendanzagaeski are the latest builds working now?

https://build.azdo.io/3456746

Commit: https://github.com/xamarin/xamarin-android/commit/8acd915ebad2253cd0389e980f14f0c3f79b30b7

**Comment by brendanzagaeski** [comment]
@jonathanpeppers, these failures are from the longer-running Integrated Regression Test suite rather than the per-commit master builds.

But indeed, it looks like the most recent run of that test suite from just over this weekend was also successful for this particular set of previously failing tests: [non-public test run](https://dev.azure.com/devdiv/DevDiv/_releaseProgress?releaseId=576769).

So it looks like this is all cleaned up!

For reference, the commits between the last failing test run and the new succeeding test run are <https://github.com/xamarin/xamarin-android/compare/1e7bb2d4975a11dfcf0c909264af5154056a9229...2e28f2eaeeeed13d256231828acbf058287b1202>:

```
2e28f2ea [apkdiff] Add apk diff tool 
1273970b [Mono.Android] Allow seeking on InputStreamInvoker via FileChannels 
5945e9a7 Bump to xamarin/Java.Interop/master@3226a4b5 
b954e341 [xaprepare] Delete Mono archive if it's corrupt 
476921a7 [build] Update NDK to r21.0.6113669 
7882f215 [Xamarin.Android.Build.Tasks] further exclude Tests\** 
1e96c795 [Xamarin.Android.Build.Tasks] don't call <ResolveAssemblyReference/> directly 
3757be20 [Xamarin.Android.Build.Tasks] Make APT0002, APT0003, XA0100, & XA4305 localizable 
550423b9 Upgrade Nuget API Packages to 5.4.0 
c0a15f9a Bump to Corretto OpenJDK v8.242.08.1 
ab4b4e61 [Xamarin.Android.Build.Tasks] XA4301 & XA0107 localization 
688b451d [Xamarin.Android.Build.Tasks] CleanBOM could leave behind a temp file 
30cc2769 [check-boot-times] Add check-boot-times 
5f07ff00 [Xamarin.Android.Tools.JavadocImporter] Convert to short-form SDK 
2c247315 [build] Add OSS Azure Pipeline Linux Build 
60b09ee9 Bump to xamarin/monodroid/master@01a4e0a0 
37b868ab [Xamarin.Android.Build.Tools][build] Bump Android tools versions
```
