### ISSUE TITLE
PackageReference condition not applied when build AndroidManifest.xml

### ISSUE THREAD

**Issue by danielmeza** [xamarin/xamarin-android#4261]
### Steps to Reproduce

1. Install in a new project Xamarin.Android.Things nuget 
2. Punt a false condition on the ItemGroup or PackageReference tag
3. Deploy the app to and not Android Things device

### Expected Behavior
The produced AndroidManifest should not include the 
`<uses-library android:name="com.google.android.things" />`
### Actual Behavior
The produced AndroidManifest contains 
`<uses-library android:name="com.google.android.things" />`
and the deployment fail with Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Package couldn't be installed in /data/app/{pacakge-name}: Package com.speedsol.www.printlink requires unavailable shared library com.google.android.things; failing!]

**Comment by jonathanpeppers** [comment]
Can you share a [diagnostic MSBuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) or sample project?

**Comment by moljac** [comment]
@danielmeza 
Please could you share diagnostic MSBuild log?
Otherwise we'll have to close the issue. Thanks

**Comment by grendello** [comment]
Since the requested information hasn't been provided to-date, I'm going to close this issue. Please reopen if the requested information is available.
