### ISSUE TITLE
I'm trying to compile an Android within xamarin.  here is the errors I'm seeing

### ISSUE THREAD

**Issue by steveschofield** [xamarin/xamarin-android#4271]
This is a mobile app written in Xamarin.  Latest version of Xamarin.   I'm new to Xamarin...

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(154,3): error APT2062: failed linking references.

/Users/userX/code/work/example-app/Example.Services.Client.Forms.Droid/obj/Debug/lp/1/jl/res/values/values.xml(0,0): Error APT2260: style attribute 'attr/cardBackgroundColor (aka Example.Services.Client.Forms.Droid:attr/cardBackgroundColor)' not found. (APT2260) 

/Users/userX/code/work/example-app/Example.Services.Client.Forms.Droid/obj/Debug/lp/1/jl/res/values/values.xml(0,0): Error APT2260: style attribute 'attr/cardElevation (aka Example.Services.Client.Forms.Droid:attr/cardElevation)' not found. (APT2260) (Example.Services.Client.Forms.Droid)

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(3,3): Error APT2260: resource style/CardView (aka Example.Services.Client.Forms.Droid:style/CardView) not found. (APT2260) (Example.Services.Client.Forms.Droid)

**Comment by grendello** [comment]
@steveschofield the most likely cause is that the nuget packages weren't properly restored. Start from scratch following these steps:

 * open terminal and go to the top directory of your application
 * run
```shell
rm -rf Example.Services.Client.Forms.Droid/obj Example.Services.Client.Forms.Droid/bin
```
 * run
```sh
msbuild /t:"Restore;SignAndroidPackage"
```

Please let us know if that helped!

**Comment by steveschofield** [comment]
The error still happens.  All of this is happening on a single solution.  We have several projects within the large app.  Looks like they recently updated to newer packages.  this is my first go around where it's an open source type project and support.  This is all kind of new for me. Not sure where to go next.

**Comment by grendello** [comment]
@steveschofield The best route here is to start afresh, with a clean checkout of your app (I assume it's stored in some sort of revision control system) - without build artifacts, without restored packages. Once you have the directory tree cleaned up and ready, please go to the top dir and issue the following commands:

```shell
nuget restore YourSolution.sln
msbuild /bl /t:"Restore;SignAndroidPackage" YourSolution.sln
```
The first command above will restore all the "old style" nugets (configured via `packages.config`) and the second command will restore and build the solution but it will also create a detailed binary log file named `msbuild.binlog` - please attach this file to this issue (if you're not allowed to do it, please mail me the file at my GitHub address). Hope that helps.

**Comment by aiuex79** [comment]
This issue ended up being in the one project folder the "project" file did not update some packages from 28.0.0.1 to 28.0.0.3.  Once we manually updated the file, things were fine.   "Ghost update not happening".   I right clicked on the project > tools > edit file and verify package versions in the "hint location" was the culprit.

**Comment by steveschofield** [comment]
This issue ended up being in the one project folder the "project" file did not update some packages from 28.0.0.1 to 28.0.0.3.  Once we manually updated the file, things were fine.   "Ghost update not happening".   I right clicked on the project > tools > edit file and verify package versions in the "hint location" was the culprit.   Hope this helps someone else.

**Comment by alexshikov** [comment]
The hint from @grendello actually helped me to find a proper solution.

The line `msbuild /t:"Restore;SignAndroidPackage" YourSolution.sln` helped me.

But actually it appeared that the CI was using nuget version 4.3.0, while locally I have 5.6.0.
So updating CI to the nuget 5.6.0 actually solved the problem and we keep using `nuget restore` without `msbuild /t:"Restore"` workaround.

Shutout to @grendello :)
