### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by Borjamao** [xamarin/xamarin-android#4276]
Hi,

Cannot find anything about TLS 1.3 on XF, i'm testing it with an Android 10 (supposed to implement TLS 1.3), but cannot get further than TLS 1.2.

¿Should it be working or implementation in XF is needed?

Regards

**Comment by radekdoulik** [comment]
Could you please attach a small project which reproduces the issue?

**Comment by grendello** [comment]
@Borjamao if you use Xamarin.Android's [AndroidClientHandler](https://github.com/xamarin/xamarin-android/blob/d543a8ac5ed65bcb1cc5d1d65cca1ba3344a62ed/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs) then you're using the underlying platform's stack and you should be set.

**Comment by rapcgutz** [comment]
Any help with this issue, I follow James Montemagno's suggestion and still get the issue. 

The inner exception I get is 

`Javax.Net.Ssl.SSLProtocolException: SSL handshake aborted: ssl=0xcb444f08: Failure in SSL library, usually a protocol error error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:592 0xcb172b48:0x00000001) --- End of managed Javax.Net.Ssl.SSLProtocolException stack trace --- javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xcb444f08: Failure in SSL library, usually a protocol error error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:592 0xcb172b48:0x00000001) at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375) at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224) at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192) at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149) at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127) at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)`



Below is the link for my post in StackOverflow.

[Xamarin.Forms sending HttpClient GET or POST request to API with TLS 1.3](https://stackoverflow.com/questions/63539253/xamarin-forms-sending-httpclient-get-or-post-request-to-api-with-tls-1-3)
