### ISSUE TITLE
Method not being discovered in project that has a reference to a binding project with an aar.  

### ISSUE THREAD

**Issue by steveschofield** [xamarin/xamarin-android#4277]
### Steps to Reproduce

1. Having a binding project hosting a 3rd party aar
2. Another project has reference binding project, when looking in Object Browser a method is not available in project
3. Code for 3rd party hasn't changed in many months.   Updated to latest xamarin.android, xamarin and other package updates.  

Looking how to troubleshoot why a previous build of xamarin, xamarin.android will cause a method to disappear.  Hope that makes sense.

**Comment by radekdoulik** [comment]
Could you please attach a small project which reproduces the issue?

**Comment by steveschofield** [comment]
[Repo-Method-Lost.zip](https://github.com/xamarin/xamarin-android/files/4231184/Repo-Method-Lost.zip)
<img width="282" alt="Screen Shot 2020-02-18 at 7 49 13 AM" src="https://user-images.githubusercontent.com/21150221/74943677-c6113a00-53c2-11ea-95a4-90b34b417ebf.png">
<img width="393" alt="Screen Shot 2020-02-18 at 7 49 47 AM" src="https://user-images.githubusercontent.com/21150221/74943678-c6a9d080-53c2-11ea-9e70-e245bed3de9d.png">

**Comment by steveschofield** [comment]
I installed an older version of xamarin.android (9.4.1) and the method shows up.

**Comment by dellis1972** [comment]
adding @gugavaro as this might be a binding generator issue.

**Comment by steveschofield** [comment]
Thanks for looking at this.   We are planning a new app and would like to have the latest packages including Xamarin. Android included

**Comment by steveschofield** [comment]
I've seen others who have reported binding issues.  Any update would be appreciated.

**Comment by gugavaro** [comment]
@steveschofield are you still having issues? 

I am unable to repro this issue.
I created a binding project and added your aar, then I reference the project form an Android project and I can see the method there.

![image](https://user-images.githubusercontent.com/16258805/78371036-73b46300-7595-11ea-84a8-10a4fd9e3991.png)

![image](https://user-images.githubusercontent.com/16258805/78371112-8464d900-7595-11ea-9b74-58148e2acb6b.png)

**Comment by gugavaro** [comment]
In case you are still getting the error, I suggest you update your environment.

You may be hitting:
https://github.com/xamarin/java.interop/issues/543

I am closing this issue for now, but please re open if you are still having issues.

thanks!

**Comment by steveschofield** [comment]
What version of Xamarin.Android were you running if I can ask?   The issue starts after 10.0.6
