### ISSUE TITLE
[WIP] Duplicating jars from NuGet references

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#4281]
### Steps to Reproduce

I got a binding project for okhttp that references the okio (v1.6) NuGet. I also have an app project that references the okhttp binding, and the okio (v1.13) NuGet. It appears that the sample is pulling in BOTH okio jar files

I noticed this because the v1.6 file is named "okio-1.6.0.jar" and the v1.13 is named just "okio.jar", the files are both in the same `lp` directory

This was working a few months ago on stable - I released some packages on devops. 

I did some looking and I see that for some reason the jar is getting pulled out from the binding project's nuget and being bubbled up somehow. then the app project gets both. weird.

### Log File

[msbuild (3).zip](https://github.com/xamarin/xamarin-android/files/4220575/msbuild.3.zip)

**Comment by antonioseric** [comment]
Is there any update on this issue?

**Comment by galcantara-asapp** [comment]
Hello, is there any update?
