### ISSUE TITLE
XAbuild ignore properties from command line

### ISSUE THREAD

**Issue by kant2002** [xamarin/xamarin-android#4305]
### Steps to Reproduce

I made following steps
- `msbuild Xamarin.Android.sln /t:Prepare /p:HOME=f:\d\build`
- `msbuild Xamarin.Android.sln /p:HOME=f:\d\build`
This create build properly, but install `android-toolchain` to `f:\d\build\android-toolchain\ndk`
Then I try to add property `/p:HOME=f:\d\build` to the xabuild
- `bin\Debug\bin\xabuild.exe Xamarin.Android-Tests.sln /restore /p:Configuration=Debug /bl:bin\TestDebug\msbuild-build-tests.binlog /p:HOME=f:\d\build`

### Expected Behavior

Respect `/p:HOME` when create configuration for MSBuild executed from XABuild

### Actual Behavior

`/p:HOME` ignored and lead to 
```
src\Mono.Android\Test\Mono.Android-Tests.targets(17,5): error : Could not locate Android NDK
```

**Comment by jonpryor** [comment]
Would you be able to attach `msbuild-build-tests.binlog`?

**Comment by kant2002** [comment]
Attached the file.
[msbuild-build-tests.zip](https://github.com/xamarin/xamarin-android/files/4239020/msbuild-build-tests.zip)

**Comment by kant2002** [comment]
@jonpryor do you need something else from me?

**Comment by jonathanpeppers** [comment]
@kant2002 can you just use `/p:AndroidToolchainDirectory` instead?

Setting `HOME` seems like it could have other weird side effects. We don't fully understand what MSBuild is doing in your log. It is like MSBuild might be doing something special for a property with that name.

**Comment by kant2002** [comment]
@jonathanpeppers I will try. But I can tell exactly what happens.
There 2 calls to MSBuild. 

First for resolving targets
https://github.com/xamarin/xamarin-android/blob/d89e3f134192c68418d59e2f08c4e70fecff7c81/tools/xabuild/XABuildPaths.cs#L273-L292

and second the actual call
https://github.com/xamarin/xamarin-android/blob/d89e3f134192c68418d59e2f08c4e70fecff7c81/tools/xabuild/XABuild.cs#L91

Second call properly pickup any property given to command line, but first one, use only predefined properties, and these kind of override which I attempt to make, does not working.

Also binlog was produced by second call, and not first call which may show you the root cause of the issue.

I can provide PR, but given not fully understand the scope, I may miss something important. If in general location of problem is more or less clear, and you get a hint of an issue, I can work on PR which better show you the problem.

**Comment by jonathanpeppers** [comment]
So @kant2002 thanks, I see what is happening.

We don't want to be in the business of parsing the arguments coming in to `xabuild.exe` -- that is why we run `MSBuildApp.Main()`. I don't see how to fix this without writing a command-line argument parser that is compatible with MSBuild...

What you could try is setting a `AndroidToolchainDirectory` or `HOME` environment variable instead of using `/p`. You could also make use of `Configuration.Override.props` and put any customization in there.

Down the line, it looks like we will be able to get rid of `xabuild.exe` for .NET 5. It is a huge hack anyway.

**Comment by kant2002** [comment]
@jonathanpeppers thanks. I would not die for that bug, since I fix bugs which prevent my work. I can live just provide PR with documentation, but if .NET 5 get rid of XABuild I'm more then happy and issue can be closed. Can you hint me on links/issues where this discussion happens, so I can read more about.

**Comment by jonathanpeppers** [comment]
You should use `Configuration.Override.props` for now, I think it will work.

This is the doc we'll be putting information about .NET 5 as we learn more: 

https://github.com/xamarin/xamarin-android/pull/4453/files#diff-067b669391f466a22e74ca7d8d8e0c1f

**Comment by kant2002** [comment]
Thanks. `Configuration.Override.props` is how I solve it. thanks for your help and patience.
