### ISSUE TITLE
Subsequent XABuild do not run

### ISSUE THREAD

**Issue by kant2002** [xamarin/xamarin-android#4306]
### Steps to Reproduce

In non-admin console.

1. bin\Debug\bin\xabuild.exe Xamarin.Android-Tests.sln /restore /p:Configuration=Debug /bl:bin\TestDebug\msbuild-build-tests.binlog /p:HOME=f:\d\build
2. bin\Debug\bin\xabuild.exe Xamarin.Android-Tests.sln /restore /p:Configuration=Debug /bl:bin\TestDebug\msbuild-build-tests.binlog /p:HOME=f:\d\build

### Expected Behavior
Symlinks removed

### Actual Behavior

First run is ok.
On second run

```
Removing old symlink: bin\Debug\lib\xamarin.android\xbuild\Microsoft

Unhandled Exception: System.IO.IOException: The directory is not empty.
...
   at System.IO.Directory.Delete(String path)
   at Xamarin.Android.Build.XABuild.Main() in d:\d\kant\GitHub\xamarin-android\tools\xabuild\XABuild.cs:line 67
```

**Comment by kant2002** [comment]
Ok. I think I miss one important details. 
- GitHub Xamarin location - Phisical drive 2, disk D:
- Visual Studio Location - Phisical drive 1, disk C:
- Android Toolset (generally HOME)  - Phisical drive 2, disk F:

I strongly suspect that this can cause issue like that when symlink point to another physical drive

**Comment by jonathanpeppers** [comment]
@kant2002 do you have "Developer Mode" enabled? https://github.com/xamarin/xamarin-android/blob/f9f5b6cd120484b13df74e94638e07411d8693fa/Documentation/workflow/UsingYourBuild.md#using-your-xamarinandroid-build

I don't know if Windows symlinks work across drives, I have a single 2 TB drive.

**Comment by kant2002** [comment]
Yes. I do have `Developer Mode` enabled. I will do my research on Windows symlinks and Win32 API, I probably will be able to diagnose that issue, just give me some more time. I mention multiple drives, since I vaguely remember that something can be off in that scenario and this *potentially* can be important. If you don't mind, my investigation comes in form of PR.

**Comment by jonathanpeppers** [comment]
@kant2002 you can try the `mklink /D` command to do the same thing we are doing:

https://docs.microsoft.com/windows-server/administration/windows-commands/mklink

Let me know if that works across drives, in general, thanks! You might also try an elevated cmd to see if that works. Developer mode _should_ work without elevation, though.

**Comment by kant2002** [comment]
I have a feling that there slight misunderstanding. I have no problem create symlink, the problem with *removing* existing symlink by XABuild.

But real cause is more then funny. see upcoming PR
