### ISSUE TITLE
Auto generated Resource.designer.cs does not include resources in UpdateIdValues() from indirect dependencies

### ISSUE THREAD

**Issue by rafalkwol** [xamarin/xamarin-android#4334]
### Steps to Reproduce

1. Create a new Xamarin Android project (v10.0).
2. Create a new Xamarin Class Library project (v10.0).
3. Create a new .NET Standard Project and convert to project supporting MonoAndroid references. To do this you need to replace the Project markup element in *.csproj file with `<Project Sdk="MSBuild.Sdk.Extras/2.0.54">` and the TargetFramework markup element in *.csproj with `<TargetFramework>monoandroid10.0</TargetFramework>`.
4. Add a new Layout file to Xamarin Class Library to have it's Id generated in project Resource file.
5. Add reference to Xamarin Class Library in the modified .NET Standard project.
6. Add reference to modified .NET Standard project in Xamarin Android project.
7. Make sure that `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` is set in the Xamarin Android project. Restart Visual Studio if necessary to make sure *.csproj take the new MSBuild property into account.
8. Rebuild Xamarin Android project to regenerated it's Resource.designer.cs file.

### Expected Behavior

Id of the Layout from Xamarin Class Library should be taken into account in UpdateIdValues() method in the Xamarin Android project.

### Actual Behavior

Id of the Layout from Xamarin Class Library is not taken into account in UpdateIdValues() method in the Xamarin Android project. It seems to be related to the project not being directly referenced to the main Xamarin Android project, as if you do the reference directly it works properly. This issue leads to mismatch of Ids between multiple Xamarin Class Libraries if they are not directly referenced to the main Xamarin Android projects. This greatly limits the ability to split application into modules when using dynamic project references based on the Solution Configuration.

### Version Information

Microsoft Visual Studio Professional 2019
Version 16.4.5
VisualStudio.16.Release/16.4.5+29806.167
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

**Comment by grendello** [comment]
@rafalkwol Would you mind attaching a small application which reproduces the issue? If that's not possible, please attach binary logs of the application build (both from a clean state, without the `bin` and `obj` folders as from a rebuild after making a small change that affects the resource ids). You can generate the binary logs by running the following command in your application's root directory from the Visual Studio Developer Prompt window:

```
msbuild /bl
```

This command will produce the `msbuild.binlog` file to attach here. Thanks!

**Comment by rafalkwol** [comment]
@grendello  I'm attaching an example application. You have 4 projects there. Example and Example2 projects are main Android application projects. IntermediateLibrary is a project that has reference to XamarinClassLibrary. Example project has reference to IntermediateLibrary and Example2 project has direct reference to XamarinClassLibrar. If you check Resource.designer.cs files in both Example projects you will see that in the one with direct reference in UpdateIdValues method you have lines like this `global::XamarinClassLibrary.Resource.` (which is correct), but in the other one you have `global::IntermediateLibrary.Resource.` (which is incorrect).

[Example.zip](https://github.com/xamarin/xamarin-android/files/4260600/Example.zip)

**Comment by jonathanpeppers** [comment]
@rafalkwol is the workaround here to just add a reference to the project?

You have projects A -> B -> C, and project A just needs a `<ProjectReference/>` to C?

**Comment by rafalkwol** [comment]
That's what I'm doing right now, but it forces me to reference all the assemblies to the main project which I would like to avoid, as the intermediate project is dynamically changing referenced class libraries depending on solution configuration. This way when I compile the application for specific client build it only packs assemblies necessary for this build.

**Comment by jonathanpeppers** [comment]
> it forces me to reference all the assemblies to the main project which I would like to avoid

After .NET 5, we plan to revisit this. Xamarin.Android and Xamarin.iOS/Mac do not even have the same behavior right now. For example with A -> B -> C, Xamarin.iOS won't include `C.dll` in the iOS app unless A has a reference to C. Xamarin.Android, however, will include `C.dll` in the APK -- but we still have this bug as you pointed out.

We want to standardize with all of .NET. For example, what does a [.NET Core global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) do with this A -> B -> C project dependency scenario? I will need to review the behavior of .NET Core projects to decide what we should do.

**Comment by rafalkwol** [comment]
@jonathanpeppers It's good to hear that there are some plans for this. Honestly Xamarin is the only project type right now in our solution that is not capable of this kind of dynamic behaviour. For web stack we have Blazor, for desktop native we use WinForms on .NET Core and for backend we have ASP.NET Core. It all works really well with dynamic behaviour of the solution where with a simple configuration change applications are built for specific client demands. Only problematic point is Xamarin project which doesn't react to MSBuild changes in real-time and for most of them requires solution restart. I guess for now I will keep the class libraries as static references to the main project and write a simple script to block compilation if someone adds new class library and won't reference it to the main project. Hopefully in the next iteration of .NET something will improve in this part. Anyways thanks for your input as I guess this is how it works at the moment.

PS. Really looking forward to Mobile Blazor Bindings. I think this is the real future for mobile development if it will become production ready and will be combined with Xamarin capabilities. Hope it will become reality.

**Comment by dellis1972** [comment]
I did some investigating and I think this is not an easy problem to solve. 

The compiled `IntermediateLibrary.dll` from `Example` all does not contain any reference to `XamarinClassLibrary.dll`

```
monodis --assemblyref IntermediateLibrary.dll 
AssemblyRef Table
1: Version=2.0.5.0
	Name=mscorlib
	Flags=0x00000000
	Public Key:
0x00000000: 7C EC 85 D7 BE A7 79 8E 
	Zero sized hash value
2: Version=0.0.0.0
	Name=Mono.Android
	Flags=0x00000000
	Public Key:
0x00000000: 84 E0 4F F9 CF B7 90 65 
	Zero sized hash value
3: Version=2.0.5.0
	Name=System
	Flags=0x00000000
	Public Key:
0x00000000: 7C EC 85 D7 BE A7 79 8E 
	Zero sized hash value
```

This means that `ResolveAssemblyReference` will never be able to find this by navigating the references of the assembly. If we add some code in IntermediateLibrary which uses the code in XamarinClassLibrary it works (without adding a reference to the app).
So I think that might actually be the problem. We need to investigate some more.

**Comment by dellis1972** [comment]
One idea is to add a new Attribute to the Resource.designer.cs which specifies which assemblies it gets resources from. This would force the Reference to be added to the final assembly.

**Comment by rafalkwol** [comment]
Closing this as I solved this issue another way.
