### ISSUE TITLE
HttpClient Fails to make request to ip address over cell when using HttpClientHandler 

### ISSUE THREAD

**Issue by Nickjgniklu** [xamarin/xamarin-android#4336]
### Description
When  my android app initializes an HttpClient with an HttpClientHandler get requests cannot be made to ip addresses with the HttpClient. The requests do no respect the clients set timeout and they time out after 2 or 3 minutes with a TasKCanceledException. This behavior occurs over cell only.
### Steps to Reproduce
I have included an example. Simple pushing the button under the URI with the ip address while a phone is connected over a cell connection should trigger the error after about 2-3 minutes. I have only seen this issue on a physical device.
1.  Create an instance of HttpClient with a HttpClientHandler
2. On a physical device disable wifi so that request must be sent over cell
3. Make a requestClient.GetAsync(stringUri)
4. if the URI uses an ip address it will fail after 2 or 3 minutes
[httpTest.zip](https://github.com/xamarin/xamarin-android/files/4262771/httpTest.zip)

### Expected Behavior
HttpClient Should be able able to make requests to a URI with an ip address in it.
### Actual Behavior
Throws
System.Threading.Tasks.TaskCanceledException

Stack Trace
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00180] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:84 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ea] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:371 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:529 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x0003f] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:284 
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:506 
  at httpTest.MainPage.Button_Clicked (System.Object sender, System.EventArgs e) [0x00050] in /Users/njugganaikloo/Projects/httpTest/httpTest/MainPage.xaml.cs:30 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <e98afaf88af5496ea979d99b06e991b9>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e98afaf88af5496ea979d99b06e991b9>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <e98afaf88af5496ea979d99b06e991b9>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.54(intptr,intptr)

## Version Information

Visual Studio Community 2019 for Mac
Version 8.4.7 (build 17)
Installation UUID: dcfd4dec-2c2f-4f28-9ff1-40edf7d8d7d8
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000166

Mono Framework MDK
Runtime:
	Mono 6.6.0.166 (2019-08/d9001b5ae70) (64-bit)
	Package version: 606000166

Roslyn (Language Service)
3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Versions:
	3.1.101
	3.1.100
	3.0.101
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.15
	2.1.14
	2.1.13

Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.3.1 (15715)
Build 11C504

Xamarin.Mac
Version: 6.10.0.21 (Visual Studio Community)
Hash: 02c4b3bdc
Branch: xcode11.3
Build date: 2020-02-18 14:13:31-0500

Xamarin.iOS
Version: 13.10.0.21 (Visual Studio Community)
Hash: 02c4b3bdc
Branch: xcode11.3
Build date: 2020-02-18 14:13:32-0500

Xamarin Designer
Version: 16.4.0.479
Hash: 074544417
Branch: remotes/origin/d16-4
Build date: 2020-01-22 22:50:22 UTC

Xamarin.Android
Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/njugganaikloo/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Microsoft Mobile OpenJDK
Java SDK: /Users/njugganaikloo/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.4.0.10
Hash: 2c49a7d
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:25:52 UTC

Android Device Manager
Version: 16.4.0.32
Hash: 7a5cb8b
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:26:14 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 804070017
Git revision: 35c9b9b9315ec81feec25ebabe131761b304257d
Build date: 2020-02-21 16:06:09+00
Build branch: release-8.4
Xamarin extensions: 35c9b9b9315ec81feec25ebabe131761b304257d

Operating System
Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
  
## Log File

[log.txt](https://github.com/xamarin/xamarin-android/files/4262849/log.txt)

**Comment by grendello** [comment]
@Nickjgniklu Does it work if you use `AndroidClientHandler`? Also, did you try setting the proxy?

**Comment by Nickjgniklu** [comment]
I tried changing the build setting in my android project so that AndroidClientHandler was used but it did not help. I do not know what I should set the proxy to. Should I use GetEmptyWebProxy() ?

**Comment by chaiyasitr** [comment]
I also facing the same issue on Android 10 devices, client.GetAsyn(uri) always timeout exception, the code is running fine on Android8, and 9 devices.

**Comment by Nickjgniklu** [comment]
I tested this today on a device with Android 8 and it works fine for me too. I think it is definitely linked to Android 10.

**Comment by chaiyasitr** [comment]
@Nickjgniklu 
Did you faced this problem when request on WiFi also ? I never try it on cell.
In my case I got failed when request on WiFi to offline host, below is my code.

```
var uri = new Uri("http://192.168.1.1/info");
var client = new HttpClient();
client.MaxResponseContentBufferSize = 256000;
client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
var response = await client.GetAsync(uri);
```

Above code is work fine for Android 8 and 9, but always failed on Android10 API 29.
 I also think that it is definitely linked to Android 10.

**Comment by chaiyasitr** [comment]
@Nickjgniklu
I download your shared code and test on physical devices android10 (google pixel 2), there is no problem with your shared code.  My issue is difference as new issue reported by me #4368 .

**Comment by Nickjgniklu** [comment]
I have continued to test this bug on multiple devices. I have only been able to reproduce this this on a galaxy s9 running android 10. It does not happen on a pixel 3a running android 10 and a couple other devices that have been able to borrow to test on. 

Another strange  thing that I noticed is that if I use this app https://play.google.com/store/apps/details?id=com.egorovandreyrm.pcapremote&hl=en_US to to save a pcap file of my traffic when sending requests of cellular connection the error never occurs.(This makes me think it could be related to the proxy)

I have also found a work around. I am now using dependency injection to create my HttpClient instance manually on both iOS and Android. Creating the client in the following manner seems to avoid this bug.

### Android
```
using System;
using Xamarin.Android.Net;
using System.Net.Http;
using httpTest.Droid;
using System.Net;

[assembly: Xamarin.Forms.Dependency(typeof(HttpClientService))]
namespace httpTest.Droid
{
    public class HttpClientService: IHttpClientService
    {
        public HttpClientService()
        {
            Client= new HttpClient(new AndroidClientHandler() { UseCookies = true, AllowAutoRedirect = false, CookieContainer = Cookies}); ;
        }
        public CookieContainer Cookies { get; set; } = new CookieContainer();

        public HttpClient Client { get; } 
        
    }
}
```
### iOS
```
using System.Net;
using System.Net.Http;
using httpTest.iOS;

[assembly: Xamarin.Forms.Dependency(typeof(HttpClientService))]

namespace httpTest.iOS
{
    public class HttpClientService: IHttpClientService
    {
        public HttpClientService()
        {
            Client= new HttpClient(new HttpClientHandler() { UseCookies = true, AllowAutoRedirect = false, CookieContainer = Cookies}); ;
        }
        public CookieContainer Cookies { get; set; } = new CookieContainer();

        public HttpClient Client { get; }
    }
}
```

### Xamarin Forms Project
```
using System.Net;
using System.Net.Http;

namespace httpTest
{
    public interface IHttpClientService
    {
        public HttpClient Client { get; }
        public CookieContainer Cookies { get; set; }


    }
}
```
### Usage
```
            CookieContainer Cookies;
            HttpClient Client;
            var clientService = DependencyService.Get<IHttpClientService>();
            Cookies = clientService.Cookies;
            Client = clientService.Client;``

**Comment by grendello** [comment]
@Nickjgniklu I'm glad you found a work-around for your issue. The fact that `AndroidClientHandler` works for you indicates that there must be some inner workings in play with the Samsung version of Android 10 (quite possibly proxy setup). I'm not sure there's anything Mono can do to to fix the issue, therefore I'm going to close it - please feel free to reopen if you are able to provide some more detailed information from the Samsung device, thanks!

**Comment by Nickjgniklu** [comment]
I was able to work around the issue by using the fix I described above. Basically you must create your `HttpClient` in your Android project using an `AndroidClientHandler` and use a dependency service if you want to use it in your shared project.

**Comment by pasha-o** [comment]
hi @Nickjgniklu do you have any suggestions for when one has no control over creating the handler? for example, I use MongoDB to connect to the server and the connection  won't work on this particular Samsung S10


            MongoClientSettings settings = MongoClientSettings.FromUrl(new MongoUrl(ConnectionString));
            settings.SslSettings = new SslSettings() { EnabledSslProtocols = SslProtocols.Tls12 };
            _mongoClient = new MongoClient(settings);

**Comment by Nickjgniklu** [comment]
I know there are some build settings that affect this. [Http Stack Info](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=macos) . Might be worth trying that. If that does not work your best bet might be building the library yourself with a constructor that allow you to pass an httpclient in. [This looks like the library you are using]( https://github.com/mongodb/mongo-csharp-driver)
