### ISSUE TITLE
Cannot access a disposed object. Object name: 'Android.Views.ViewStub

### ISSUE THREAD

**Issue by DavidMarquezF** [xamarin/xamarin-android#4341]
I'm not sure if this is the expected behavior, but if a ViewStub is Inflated, and you navigate to another activity and come back, trying to access properties of the ViewStub throws System.ObjectDisposedException. I suppose it may be related with the ViewStub getting removed from the view once it is inflated?

I have to access the Parent property of the viewstub to know if it is inflated (as a workaround I can use a flag for the moment though)

### Steps to Reproduce

1.  Use ViewStub inside an Activity and call its Inflate function
2. Navigate to another activity and go back
3. Try to access a Property of ViewStub

### Expected Behavior

As I commented before I'm not sure if this should be the excpected behaviour, but if it isn't, the ViewStub shouldn't be disposed when changing activities.

### Actual Behavior

ViewStub disposed when navigating to an activity and navigating back after using its Inflate function

### Version Information

Microsoft Visual Studio Enterprise 2019
Version 16.4.4
VisualStudio.16.Release/16.4.4+29728.190
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Xamarin   16.4.000.309 (d16-4@1d551f9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.475 (remotes/origin/d16-4@ac250f5aa)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.3.7 (d16-4/d66aed0)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: fd9f379
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

**Comment by moljac** [comment]
@DavidMarquezF 
Could you provide minimal repro sample please?

**Comment by DavidMarquezF** [comment]
After trying to reproduce it in various ways, I have been unable to reproduce this in a repro sample. This happens consistently every time in my app though

**Comment by VincentDondain** [comment]
Hi @DavidMarquezF, our team is unable to investigate this issue further without the requested repro sample. Given that it only happens with your app it might very well be a project issue (hence the needed repro). I suggest updating to the latest version of the product and see if the problem still occurs.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

**Comment by brendanzagaeski** [comment]
*Cross-referencing note*

In case any other users find this issue first when searching for similar exceptions, one common cause of this kind of exception is <https://github.com/xamarin/xamarin-android/issues/2049>. A fix for that issue is now included in the latest Xamarin.Android SDK Preview version 10.3.0.33. You can follow <https://github.com/xamarin/xamarin-android/issues/2049> for additional updates on the release status of that fix.
