### ISSUE TITLE
Expose Manifest VersionName/Code as MSBuild properties.

### ISSUE THREAD

**Issue by dellis1972** [xamarin/xamarin-android#4348]
Context https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1005105

We should also expose the values for versionCode and versionName from the final manifest as properties for users to use later during archiving or renaming of apks.

**Comment by jpobst** [comment]
This has been added in .NET 6 via `$(ApplicationVersion)` and `$(ApplicationDisplayVersion)` MSBuild properties:
https://github.com/xamarin/xamarin-android/blob/d8fec08e6d7297d43a85d874753208341c002165/Documentation/guides/OneDotNetSingleProject.md#one-net-single-project
