### ISSUE TITLE
.java issues surfacing instead of C# issues

### ISSUE THREAD

**Issue by Xamtastic** [xamarin/xamarin-android#4361]
### Steps to Reproduce

1. Create a .aar with a Java class that does not override an abstract method but should
2. Add it to a Java Binding Library and Build
3. Reference the same library from a Xamarin.Android app but do not reference the class (or any other classes) and build - the error will be thrown.

### Expected Behavior
I expect Java Binding Libraries to fail building when there is an underlying problem in a .java file class.
### Actual Behavior
The Java Binding Library builds without error, yet when it is referenced to a Xamarin.Android app and that is built, an error is thrown that when tapped goes to the .java file, instead of an auto-generated C# file.

In this case the error is:

```
RedactedImplementor.java(8,8): Error JAVAC0000:  error: RedactedImplementor is not abstract and does not override abstract method onNewValue(RedactedValue) in RedactedListener
public class RedactedListenerImplementor
 (JAVAC0000) (MyXamarinAndroidProjectName) javac
```

If there was an underlying problem wit mthe java, this error should have been thrown during the Java Binding Library build, but wasn't, it was thrown when the Xamarin.App project that referenced it was built.

### Version Information

```
Xamarin.Android
Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/anthonyharrison/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Microsoft Mobile OpenJDK
Java SDK: /Users/anthonyharrison/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.4.0.10
Hash: 2c49a7d
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:25:52 UTC

Android Device Manager
Version: 16.4.0.32
Hash: 7a5cb8b
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:26:14 UTC

```

### Log File

No output.

**Comment by jpobst** [comment]
I'm a bit confused by "Create a .aar with a Java class that does not override an abstract method but should", could you provide a sample?

**Comment by Xamtastic** [comment]
The Xamarin.Android Java Binding Library takes .jar and .aar files, and the .aar files, which are zip files, contain compiled java classes.

The following is an example of a class that implements and interface, however you'll notice that the interface has not been implemented. 

The interface itself follows the class.

Class extending interface but not implementing method defined in interface:
```
package part1.part2;
// RedactedListenerImplementor.java
public class RedactedListenerImplementor
	extends java.lang.Object
	implements
		mono.android.IGCUserPeer,
		part1.part2.RedactedListener
{
	public RedactedListenerImplementor()
	{
	}
}
```
Interface:
```
package part1.part2;

public interface RedactedListener {
  void onNewValue(Redacted);
}
```

**Comment by Xamtastic** [comment]
Thanks for your help, I'll close the issue, I overlooked the matter that the java errors were in generated code and not in the original .aar libraries, a simple remove-node solved it. What a week!
