### ISSUE TITLE
VS 16.5.0 Preview 5.0 windowLayoutInDisplayCutoutMode=shortEdges produces distorted layout

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#4377]
Create a standard app using the Navigation Drawer template. By default the template still uses the Support libs, however, the behaviour is unchanged if modified to use the release versions of the Xamarin.AndroidX libs. If you add a values-28 folder and include in styles.xml the following

`<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`

Then simulate a notch e.g. Tall cutout via Developer Options/Drawing/Display cutout
The resultant layout when rotated right to landscape is completely out of wack. The toolbar or app bar doesn’t extend the full width of the screen when in Landscape, the contents of the status bar, also goes full screen. The toolbar pulls up short by the equivalent amount of space of that of the inset allowing for the notch, as though it is applying insets.SystemWindowInsetRight padding to the app bar and the toolbar.

The reverse is true when the device is rotated left. The app bar toolbar now starts at the equivalent distance of insets.SystemWindowInsetLeft padding. Put the device back to Device Default and the layout is normal in both left and right Landscape orientations. What should happen is the relative layout of content_main should be letterboxed in both landscape orientations, e.g. Both short sides. In other words, the statusbar and toolbar are probably close to correct, but the layout of content_main is not letterboxing. I could be wrong, but that is what it looks like to me.

Now swap to Android Studio and use their equivalent template. When I first tried this in AS a couple of weeks ago, I was using AS 3.5.3. That version doesn’t allow you to uncheck “Use androidX” so by default it is using the androidX libs in the code and layouts. It also uses the androidx.navigation:navigation-fragment and androidx.navigation:navigation-ui so the code produced is totally different, but the output of the apk produced is identical to the one produced by the Xamarin template. Run their app and the layout problem is the same.

So, my conclusion is that there must be a bug in the Support libs and since the first versions of the AndroidX libs are meant to be functionally the same as the support libraries the bug comes with them.

I posted my results on StackOverflow in the Android section and got zero responses, so I just got back to what I was doing and forgot about it while I tried to work around it in my app. Eventually, I went back to AS and looked at it again and looking in the Gradle file noticed that the libs required updating. As soon as I updated them, built the app and ran it again, the layout problems just disappeared. 

The following is the relevant section of build.gradle and the changes to versions of the androidx libs that should allow you to reproduce the above and then correct it.

implementation 'androidx.appcompat:appcompat:1.0.2'                                   	1.1.0
implementation 'androidx.legacy:legacy-support-v4:1.0.0'                     
implementation 'com.google.android.material:material:1.0.0'                 	1.1.0
implementation 'androidx.constraintlayout:constraintlayout:1.1.3'   
implementation 'androidx.navigation:navigation-fragment:2.0.0'               2.2.1
implementation 'androidx.navigation:navigation-ui:2.0.0'                     2.2.1
implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'               2.2.0

Since we aren’t even testing the later versions of androidx yet, I suppose this issue will be treated as closed, which would be very frustrating from my point of view.

Can someone give an estimation as to when Xamarin will be releasing the updated versions of the androidx libs to match what the Android guys are using now, as I would assume many of us are having serious problems keeping our apps up to date and functional?

**Comment by gugavaro** [comment]
@moljac have you seen this before?

**Comment by moljac** [comment]
@gmck 
Can you make repro sample please?
This will be moved to AndroidX repo.

And I'm working on updates like crazy. We have issues with external bindings and some tools, but fixing those step by step

**Comment by gmck** [comment]
@moljac  Don't understand why you want a repo, when I've given complete instructions on how to create it for both VS and Android Studio.

**Comment by moljac** [comment]
@gmck 

> Don't understand why you want a repo, when I've given complete instructions on how to create it for both VS and Android Studio.

Economic reasons. If you already did minimal repro sample why not submitting them? Is it really so hard? It takes time to switch context and create 2 repro samples, read the essay (your description) and fix the bug. And if you think that this issue is the only one, then...

> Can someone give an estimation as to when Xamarin will be releasing the updated versions of the androidx libs to match what the Android guys are using now, as I would assume many of us are having serious problems keeping our apps up to date and functional?

I wanted yesterday/today/tomorrow (pick whatever you like), but process and other issues are blocking release. Updates were ready (bindings itself) beginning Feb., but I cannot publish even previews w/o having CI completely green.

Here is the PR and branch with updates:

https://github.com/xamarin/AndroidX/pull/70/files

Quite a lot of users build it themselves and use those packages, so I would suggest you to do so.

**Comment by gmck** [comment]
@moljac Attached is a zip just for you of the Xamarin app. I'll leave it to you to create the AS app, just follow my "essay".

Build it, simulate a notch, run it and rotate to landscape. 

[NavTemplateAppForMel.zip](https://github.com/xamarin/xamarin-android/files/4326333/NavTemplateAppForMel.zip)

**Comment by jpobst** [comment]
Updated versions of the AndroidX packages have been released, so I think this just never got closed.
