### ISSUE TITLE
SIGSEGV with AOT enabled after updating to Entity Framework 3

### ISSUE THREAD

**Issue by mfeingol** [xamarin/xamarin-android#4390]
In a nutshell, my app crashes on startup with a SIGSEGV after upgrading from EF Core 2.2.6 to 3.1.2. The crash occurs on devices (ARM64) and appears to also occur on emulators (x86).

I have found two workarounds for the crash:

1. Downgrade back to EF Core 2.2.6
2. Disable AOT compilation

Things that are not workarounds:
1. Disabling LLVM
2. Disabling startup tracing
3. Disabling R8
4. Disabling the concurrent GC

When the app crashes, the following crash appears in the device log:

```
03-12 14:43:55.459: A/DEBUG(20338): Build fingerprint: 'lge/h1_lra_us/h1:7.0/NRD90U/1733911185dd1:user/release-keys'
03-12 14:43:55.459: A/DEBUG(20338): Revision: '12'
03-12 14:43:55.459: A/DEBUG(20338): ABI: 'arm64'
03-12 14:43:55.460: A/DEBUG(20338): pid: 20219, tid: 20219, name: ckroads.android  >>> com.backroads.android <<<
03-12 14:43:55.460: A/DEBUG(20338): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa0200004e
03-12 14:43:55.460: A/DEBUG(20338):     x0   000000000000000d  x1   0000007fdcbc7c28  x2   000000000000000d  x3   0000007fdcbc7c30
03-12 14:43:55.460: A/DEBUG(20338):     x4   ffffffffffffffff  x5   8080800000000000  x6   0000000000808080  x7   fefeff1f1f64332f
03-12 14:43:55.460: A/DEBUG(20338):     x8   0000000000000000  x9   769d136f83ec1d3c  x10  7f7f7f7fffff7f7f  x11  0101010101010101
03-12 14:43:55.460: A/DEBUG(20338):     x12  0000000000000028  x13  000000008000002f  x14  00000077507280f8  x15  0000007750727d9c
03-12 14:43:55.460: A/DEBUG(20338):     x16  000000774558b590  x17  00000077506ed4c8  x18  0000007fdcbc91a8  x19  0000000000000000
03-12 14:43:55.460: A/DEBUG(20338):     x20  0000000000000000  x21  0000000000000040  x22  0000007745564201  x23  00000077454c4992
03-12 14:43:55.460: A/DEBUG(20338):     x24  00000077454e05e5  x25  000000000000002e  x26  00000077454de670  x27  00000077454c4990
03-12 14:43:55.460: A/DEBUG(20338):     x28  0000000a0200004e  x29  0000007fdcbc80b0  x30  0000007745490814
03-12 14:43:55.460: A/DEBUG(20338):     sp   0000007fdcbc8050  pc   0000007745490824  pstate 0000000080000000
03-12 14:43:55.461: A/DEBUG(20338): backtrace:
03-12 14:43:55.461: A/DEBUG(20338):     #00 pc 0000000000276824  /data/app/com.backroads.android-1/lib/arm64/libmonosgen-2.0.so
03-12 14:43:55.461: A/DEBUG(20338):     #01 pc 0000000000276810  /data/app/com.backroads.android-1/lib/arm64/libmonosgen-2.0.so
```

I'm not sure how to get a better stack backtrace than that.

### Steps to Reproduce

I do not have a simple repro project for this. My app is building with the following settings:

```
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
    <BundleAssemblies>true</BundleAssemblies>
    <AndroidSupportedAbis>armeabi-v7a;arm64-v8a</AndroidSupportedAbis>
    <JavaMaximumHeapSize>1G</JavaMaximumHeapSize>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidEnableMultiDex>false</AndroidEnableMultiDex>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>
    <LangVersion>latest</LangVersion>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
    <AndroidPackageFormat>aab</AndroidPackageFormat>
  </PropertyGroup>
```

### Expected Behavior

A working Android app.

### Actual Behavior

A crashing Android app.

### Version Information

VS 2019 16.4.6

### Log File

Device logs from several build variations:

[Log-crash-disableLLVMandStartupTracing.txt](https://github.com/xamarin/xamarin-android/files/4327072/Log-crash-disableLLVMandStartupTracing.txt)
[Log-crash-startup.txt](https://github.com/xamarin/xamarin-android/files/4327066/Log-crash-startup.txt)
[Log-crash-startup-disableLinking.txt](https://github.com/xamarin/xamarin-android/files/4327067/Log-crash-startup-disableLinking.txt)
[Log-crash-startup-disableLLVM.txt](https://github.com/xamarin/xamarin-android/files/4327069/Log-crash-startup-disableLLVM.txt)
[Log-crash-startup-disableR8.txt](https://github.com/xamarin/xamarin-android/files/4327070/Log-crash-startup-disableR8.txt)
[Log-working-disableAOT.txt](https://github.com/xamarin/xamarin-android/files/4327071/Log-working-disableAOT.txt)

**Comment by mfeingol** [comment]
@radekdoulik: let me know if there's something I can do to help you figure this one out.

**Comment by brendanzagaeski** [comment]
I'll chime in here to suggest a possible way to get a more detailed backtrace. The steps are a bit tricky, but hopefully they'll provide additional interesting clues. (Another option could be to share the project code privately with the Mono team, if that might be possible.)

 1. Get a version of *libmonosgen-2.0.so* that includes debugging symbols. For example, for Visual Studio 2019 version 16.4.6, download [android-debug-Darwin-fd9f379d294e8208a63dd3f63d104057180c9789.7z](https://xamjenkinsartifact.azureedge.net/mono-sdks/android-debug-Darwin-fd9f379d294e8208a63dd3f63d104057180c9789.7z).

 2. Extract the arm64-v8a ABI version of *libmonosgen-2.0.so*:

    ```bat
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Xamarin.VisualStudio\7-Zip\7z.exe" x android-debug-Darwin-fd9f379d294e8208a63dd3f63d104057180c9789.7z android-arm64-v8a-debug\lib\libmonosgen-2.0.so
    ```

 3. Deploy a *debuggable* version of your app that is built with **AOT Compilation** enabled. For example, deploy the app in the Debug configuration, but temporarily alter that configuration to disable **Use Shared Runtime**, enable **AOT Compilation**, and set **Linking** to **Sdk Assemblies Only**.

 4. Attach either GDB or LLDB to your app. The easiest way to do this will depend on whether you have the **C++ Android development tools** workload for Visual Studio installed or have Android Studio installed. See the corresponding sections on the [development tips page](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/DevelopmentTips.md#attaching-gdb-using-visual-studio-on-windows).

 5. For GDB in Visual Studio, you'll need to complete the *If you need symbols* step. For LLDB in Android Studio, you'll need to use the steps to [Manually load the library with symbols](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/DevelopmentTips.md#option-c-manually-load-the-library-with-symbols).

 6. Now reproduce the crash in the app.

 7. When GDB or LLDB breaks on the fatal signal, get the backtrace via `-exec backtrace` in the **Immediate** window in Visual Studio or via `bt` in the LLDB prompt in Android Studio.

If you try these steps and need a different version of the debugging symbols or have other questions, let me know. Thanks a bunch!

**Comment by mfeingol** [comment]
I'll try to find some time to walk through these steps. In the meantime, I'm happy to provide access to the project code privately. Just shoot me an email if you're interested.

**Comment by mfeingol** [comment]
Interestingly enough, I'm no longer able to reproduce this issue using Visual Studio 16.5.2. I'm guessing a newer Xamarin.Android / Mono may have worked around or fixed the problem.

**Comment by brendanzagaeski** [comment]
Nice. Thanks for the updated info, and glad it's working better now!
