### ISSUE TITLE
Resource.designer.cs does not yet support comma-delimited list for library %(Aliases) metadata

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#4409]
Context: https://github.com/xamarin/xamarin-android/issues/3808#issuecomment-599821699

In Visual Studio, I noticed that the description text for **Aliases** in the **Properties** window says:

```
A comma-delimited list of aliases to this reference.
```

I haven't yet found a mention of this in my quick searches of docs.microsoft.com, but it seems this is indeed allowed for the `%(Aliases)` metadata.

### Steps to reproduce

 1. Edit the `AndroidUpdateResourcesTest.CheckProjectReferenceAlias` test to replace:

    ```patch
    -Metadata = { { "Aliases", "Lib1" } },
    +Metadata = { { "Aliases", "Lib1A,Lib1B" } },
    ```

 2. Run the test.

### Expected behavior

The test passes.

It looks like the desired `external alias` lines to generate for _Resource.designer.cs_ would probably be:

```csharp
extern alias Lib1A;
extern alias Lib1B;
```

### Actual behavior

The test fails due to a syntax error in the generated _Resource.designer.cs_:

```csharp
extern alias Lib1A,Lib1B;
```

```text
Resources\Resource.designer.cs(1,20,1,21): error CS1002: ; expected
```

### Version information

xamarin-android/master@aaea55ff99ae033682dc8eef0817ddbe007aa542

**Comment by dellis1972** [comment]
Pr up #4423

**Comment by brendanzagaeski** [comment]
*Release status update*

A Preview version has now been published on Windows that includes the fix for this item. The fix is not yet included in a Release version. This item will be updated again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.3.0.74

Fix included on Windows in Visual Studio 2019 version 16.6 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment]
*Release status update*

A Preview version of Xamarin.Android has now been published on macOS that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.3.0.74.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6 Preview 2. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.3.1.0.

Fix included on Windows in Visual Studio 2019 version 16.6. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
