### ISSUE TITLE
Not enough info when application fails with System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by ivmazurenko** [xamarin/xamarin-android#4411]
We have encountered with confusing exception messages in our log. The exception was reproduced on a client device and it is not reproduced on my machine. There is nothing special in the application logcat, just an error:

```
a326acfb-7119-4500-80a5-bb06fe81a3daSystem.IndexOutOfRangeException: Index was outside the bounds of the array.
  at (wrapper dynamic-method) System.Object.47c(intptr,object[])
  at (wrapper native-to-managed) System.Object.60(intptr,intptr)
```

### Expected Behavior

Exception with some additional info. 

### Actual Behavior

Сonfusing exception. It is not reproducible on device.

### Version Information

Microsoft Visual Studio Community 2019
Version 16.4.3
VisualStudio.16.Release/16.4.3+29709.97
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ASP.NET and Web Tools 2019   16.4.457.38025
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.4.457.38025
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.4.457.38025
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.4.457.38025
Azure Functions and Web Jobs Tools

C# Tools   3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.21016.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.87+gbb515bf382
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.5.24 (1fafd7e)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61912.09160
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.11031.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.308 (d16-4@4755fb3)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.475 (remotes/origin/d16-4@ac250f5aa)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.3.7 (d16-4/d66aed0)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: fd9f379
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.10.0.17 (5f802ef)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
### Log File

Exception from logs, other logging information is looking as usual

```
a326acfb-7119-4500-80a5-bb06fe81a3daSystem.IndexOutOfRangeException: Index was outside the bounds of the array.
  at (wrapper dynamic-method) System.Object.47c(intptr,object[])
  at (wrapper native-to-managed) System.Object.60(intptr,intptr)
```

Android versions :
vivo 1820 8.1.0
SM-G925F 7.0
ALP-L29 9
Redmi Note 4 7.0

Mono android referenced v4.0.30319

**Comment by gugavaro** [comment]
Is that the complete stacktrace?
Did you try to instrument your code?

**Comment by grendello** [comment]
@ivmazurenko we will need to see the full trace (a full logcat output would be best) before we can start diagnosing the issue. The three lines you provided are not enough, alas.

**Comment by ivmazurenko** [comment]
Unfortunatelly, I cant publish our application log, but I checked, there is nothing special  was found before crash, just this error after ordinary logs.

The only thing I need - is additional information, where this error was happen. 
More errors:


```
299537ms|2020-04-07 18:36:15.3545|Error|TID:1:     |Unhandled exception 35d6a048-81cc-405a-818e-8cd1a20ede95System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at (wrapper dynamic-method) System.Object.377c(intptr,object[])
  at (wrapper native-to-managed) System.Object.60(intptr,intptr)
```
284935ms|2020-04-07 22:09:49.2468|Error|TID:1:     |Unhandled exception 4411137f-2d1c-4e2c-8ae9-d1a12405bc9bSystem.IndexOutOfRangeException: Index was outside the bounds of the array.
  at (wrapper dynamic-method) System.Object.74c(intptr,object[])
  at (wrapper native-to-managed) System.Object.60(intptr,intptr)

```
```
570638ms|2020-03-30 23:02:58.5549|Error|TID:1:     |Unhandled exception 9e6e85ad-58c9-4e99-a408-db22984a4026System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at (wrapper dynamic-method) System.Object.280c(intptr,object[])
  at (wrapper native-to-managed) System.Object.62(intptr,intptr)
```

**Comment by moljac** [comment]
@ivmazurenko 

Can you try get more info through android execution environment, please?

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/environment

Otherwise we will not be able to help you and we'll have to close the issue.

**Comment by moljac** [comment]
@ivmazurenko Without more info we will be forced to close the issue. Thanks.

**Comment by moljac** [comment]
@steveisok If you cannot help with this one. I will close it.

**Comment by moljac** [comment]
Closing this one.
