### ISSUE TITLE
Design-time build missing Resource class

### ISSUE THREAD

**Issue by scorpionsweda** [xamarin/xamarin-android#4428]
[Please help look](http://aflam24.cc/2020-03-19_21-35-12.mp4)

**Comment by jonathanpeppers** [comment]
In your video you don't show where the `Resource.designer.cs` class is in the project. Did it get removed from the project?

**Comment by scorpionsweda** [comment]
I did not remove anything

**Comment by jonathanpeppers** [comment]
Sorry, you're going to need to give a little more detail. Does the file show up in `Solution Explorer`?

Can you share a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

**Comment by scorpionsweda** [comment]
![2020-03-20_04-07-42aaaaaaa](https://user-images.githubusercontent.com/62402631/77128488-56de4280-6a61-11ea-86a6-4fb925ad96fb.png)

**Comment by scorpionsweda** [comment]
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin|Information|0|Xamarin - 16.5.000.521-d16-5+b3ea41e
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin.VisualStudio.Android.XamarinAndroidPackage|Warning|0|Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify mustCheckIfSolutionIsReady:True delay:00:00:02
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify canceled => solution is not ready
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing AndroidStarted event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify mustCheckIfSolutionIsReady:True delay:00:00:02
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify canceled => solution is not ready
Xamarin.HotReload|Information|0|1441-07-25 03:47:58.9 Hot Reload IDE Extension Loaded
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AutoSdk|Information|0|androidsdksetup: AutoSdk tries to resolve dependencies: platforms/android-29, build-tools/28.0.3@28.0.3, platform-tools@28.0.0, tools@26.1.1, ndk-bundle@16.1, emulator, build-tools/29.0.2@29.0.2, platforms/android-28
Xamarin.VisualStudio.Android.Setup.AutoSdk|Warning|0|androidsdksetup: AutoSdk cannot resolve dependencies: platform-tools@28.0.0
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error: 
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error: 
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error: 
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing MonoDroidPropertiesChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error: 
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error: 
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing MonoDroidPropertiesChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error: 
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error: 
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing MonoDroidPropertiesChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error:

**Comment by scorpionsweda** [comment]
[codecanyon-y4s02IyR-wowonder-android-messenger-mobile-application-for-wowonder.zip](https://github.com/xamarin/xamarin-android/files/4357540/codecanyon-y4s02IyR-wowonder-android-messenger-mobile-application-for-wowonder.zip)

**Comment by jonathanpeppers** [comment]
I opened your project and no errors for me:

![image](https://user-images.githubusercontent.com/840039/77173981-62942e00-6a8e-11ea-86d7-ac798d4cf4d0.png)

My Visual Studio is:

![image](https://user-images.githubusercontent.com/840039/77174067-7c357580-6a8e-11ea-8deb-abb8a9428fa8.png)

What version do you have? Need to update to latest?

**Comment by scorpionsweda** [comment]
![2020-03-20_18-23-41xxxxxxxxxxx](https://user-images.githubusercontent.com/62402631/77178366-081fbf80-6ad8-11ea-8e0c-fb21cf553973.png)

**Comment by scorpionsweda** [comment]
![77128488-56de4280-6a61-11ea-86a6-4fb925ad96fb](https://user-images.githubusercontent.com/62402631/77194440-a9167680-6ae8-11ea-906b-4acec032d6ed.png)

**Comment by jonathanpeppers** [comment]
Can you change the logging to [diagnostic](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

![image](https://user-images.githubusercontent.com/840039/77196528-8a48bd80-6ab1-11ea-94cc-8012db90c3eb.png)

That will print out a lot more information. Then you can paste the output into a text file, zip, and upload it here.

**Comment by scorpionsweda** [comment]
[مستند نصي جديد (2).txt](https://github.com/xamarin/xamarin-android/files/4361734/2.txt)

**Comment by scorpionsweda** [comment]
Hello, what do you think of entering my computer through
https://remotedesktop.google.com
And if you solve this problem for me, can you set a specific time for me to send you the access code for my computer and to contact you on the email or WhatsApp

**Comment by jonathanpeppers** [comment]
@scorpionsweda if you create a new project, does it work fine?

What language/region is your computer set to? Mine is English/US.

**Comment by scorpionsweda** [comment]
I made a formate for the computer and solved the old problem but I have other problems please enter my computer through anydesk and help me

**Comment by jonathanpeppers** [comment]
@scorpionsweda maybe post what your new problem is and we can help you here?

It's better to do everything here, since other people can read this if they hit the same issues you are.

**Comment by scorpionsweda** [comment]
My problem was not solved

**Comment by jonathanpeppers** [comment]
> I made a formate for the computer and solved the old problem

Sorry, I thought this meant it solved your problem.

> If you create a new project, does it work fine?
> What language/region is your computer set to? Mine is English/US.

I'm wondering if a blank File->New Xamarin.Android Project works? or does the same thing happen?

What language/region is your PC set to? I can try changing mine to see if I hit the same problem.

**Comment by scorpionsweda** [comment]
![IMG_20200325_181249](https://user-images.githubusercontent.com/62402631/77559179-83acb280-6ec4-11ea-8154-302fbf97b69b.jpg)

**Comment by jonathanpeppers** [comment]
What am I looking at here? I don't see the error message.

**Comment by scorpionsweda** [comment]
![15851530193075670702670019279741](https://user-images.githubusercontent.com/62402631/77559429-dbe3b480-6ec4-11ea-88f6-d2a80190638b.jpg)

**Comment by scorpionsweda** [comment]
![15851532941531996808109154739392](https://user-images.githubusercontent.com/62402631/77559982-81972380-6ec5-11ea-95c3-6012e59f8ddd.jpg)

**Comment by jonathanpeppers** [comment]
Can you manually install `Platform-Tools`?

Mine has `29.0.5` installed:

![image](https://user-images.githubusercontent.com/840039/77561072-390f4400-6e8c-11ea-8a8b-b5ffff7b7f37.png)

**Comment by scorpionsweda** [comment]
![15851545499118102939983455321812](https://user-images.githubusercontent.com/62402631/77562221-6c6fc400-6ec8-11ea-9645-c0801060f28c.jpg)

**Comment by scorpionsweda** [comment]
Do you i have microsoft at my as vps_windows available on visual studio

**Comment by jonathanpeppers** [comment]
@scorpionsweda does the project fail to build? Can you post a new build log?

**Comment by scorpionsweda** [comment]
Failed to set, please login to my device

**Comment by scorpionsweda** [comment]
Please please

**Comment by grendello** [comment]
I'm going to close this issue because of the requested additional information not having been provided to-date. Please reopen the issue once the information is available, thanks.
