### ISSUE TITLE
Xamarin.Android-OSS Ubuntu Azure Pipeline failing on System.IO.IOException: No space left on device

### ISSUE THREAD

**Issue by brzooz** [xamarin/xamarin-android#4432]
Hi,

I was looking for latest Xamarin.Android SDK for linux and saw that build is failing because of _System.IO.IOException: No space left on device_. Could someone take a look into this? 

I know that Xamarin.Android for linux is not oficially supported so this is low priority issue. 

Also I'm sad that there is not much interest in linux version. I can't be the first person who saw this? Or am I?

**Comment by knuxbbs** [comment]
I'm interested in that too.

NET 5 should have support to Linux. See what the Flutter guys have done.

**Comment by knuxbbs** [comment]
Maybe this issue is related to https://github.com/dotnet/runtime/issues/33689.

**Comment by brendanzagaeski** [comment]
@pjcollins, let me know if there's anything I can help out with on this. I wonder if the builds are leaving something behind or if maybe the xamarin-android build is just using up all the space for the current VM size.

https://dev.azure.com/xamarin/public/_build?definitionId=48&_a=summary

**Comment by pjcollins** [comment]
Maybe we can try to leverage https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/vmss?view=azure-devops as an alternative to the hosted pool to allow for more disk space. I'll try to look at this soon.

**Comment by stannynuytkens** [comment]
> Maybe we can try to leverage https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/vmss?view=azure-devops as an alternative to the hosted pool to allow for more disk space. I'll try to look at this soon.

Has soon arrived yet? :stuck_out_tongue:

**Comment by stannynuytkens** [comment]
> Hi,
> 
> I was looking for latest Xamarin.Android SDK for linux and saw that build is failing because of _System.IO.IOException: No space left on device_. Could someone take a look into this?
> 
> I know that Xamarin.Android for linux is not oficially supported so this is low priority issue.
> 
> Also I'm sad that there is not much interest in linux version. I can't be the first person who saw this? Or am I?

I'm sad with you... I'll try to build it locally for now..

**Comment by TheForgetTime** [comment]
我在本地编译10.3.0.33版本时也遇到了这个问题
Today, when trying to build 10.3.0.33 version locally, I also encountered this error.

还有一些 git submodules 没有正确检出问题
In addition, there are some git submodules that are not checked out correctly.

幸运的是，在解决了存储空间和git子模块检出问题之后，构建成功。
Fortunately, the build was successful after solving the storage space and git submodule checkout issues.

如果您的位置在中国，则可以通过以下方式下载用于Arch Linux的软件包或通用的tar.gz文件。
If your location is China, you can download a software package built for ArchLinux or a general zip file in the following ways.

虽然只有android 10
Although only android 10

百度云(BaiDu NetDisk) : 
> 链接: https://pan.baidu.com/s/18NY4JSXEQtp1SaZkuWsHdA 提取码: w58v 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by brzooz** [comment]
Actually, I still can't see build working on Azure DevOps.  
@brendanzagaeski @pjcollins Could you confirm if this can really by closed?

**Comment by Akademiksdc** [comment]
@brendanzagaeski do you have any updates, when the pipeline is going to be stable?

**Comment by Akademiksdc** [comment]
@pjcollins @brendanzagaeski  Hi, any ETA when the pipeline will get back to green state?

**Comment by pjcollins** [comment]
I'm trying to get this back to working order as part of https://github.com/xamarin/xamarin-android/pull/4674.

**Comment by pjcollins** [comment]
This should be fixed in https://github.com/xamarin/xamarin-android/commit/063d645c7ae16750f5b44da8d7a2d0589e2cdd14.

**Comment by toverux** [comment]
Awesome!
I'm trying to download the new .deb from this page, but when I click Linux Packages (or any other row), nothing happens. I guess that's a bug on Azure's side?
Is there another location where we could download the artifacts?

![image](https://user-images.githubusercontent.com/1343250/82120895-748e0680-9789-11ea-9be4-fb5643da2970.png)
