### ISSUE TITLE
Accessing Android.Locations.Location's "BearingAccuracyDegrees" leads to throw error Java.Lang.NoSuchMethodError: 'no non-static method "Landroid/location/Location;.getBearingAccuracyDegrees on Android version below "O"

### ISSUE THREAD

**Issue by yousufctec** [xamarin/xamarin-android#4440]
### Steps to Reproduce

1. Access Android.Locations.Location "BearingAccuracyDegrees" obtained by FusedLocationProviderClient on LocationCallback. (Android version 6)
2. Getting an error as below
Java.Lang.NoSuchMethodError: 'no non-static method "Landroid/location/Location;.getBearingAccuracyDegrees

### Expected Behavior
Supposed to return default value or null.

### Actual Behavior
Throwing an error that causes the application to crash.

### Version Information
Android 6 Marshmallow

**Comment by jpobst** [comment]
That method was added to Android in API Level 26 (Oreo): https://developer.android.com/reference/android/location/Location#getBearingAccuracyDegrees().  You will not be able to use it on devices running earlier versions.  

One option is to check what device you are on at runtime as described here: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/android-api-levels?tabs=windows#runtime-checks-for-android-versions.

**Comment by yousufctec** [comment]
I am aware that method was added in Android in API Level 26 (Oreo). But, that shouldn't crash on the unavailable versions right? Or that's how every API works in Xamarin.Android? If not found, will throw error and crash?

**Comment by jpobst** [comment]
Yes, every API in Xamarin.Android (or even regular Java Android) will crash if you attempt to call it on a device where it does not exist.  The performance overhead of probing every single API call to see if it exists first would be significant, which is why I'm not aware of any languages that do it.

**Comment by yousufctec** [comment]
Ok understand, thanks for the information.
