### ISSUE TITLE
UnAuthorized Overlay Error on entering Picture in Picture mode YoutubePlayer View Android?

### ISSUE THREAD

**Issue by gopalawasthi123** [xamarin/xamarin-android#4442]
### Steps to Reproduce

1. Open YouTube Player View in activity.
2. By Clicking backbutton Enter in Picture in Picture mode is called
3. Video plays for 1-2 sec then stop. Again entering in full mode video again plays 

### Expected Behavior
Video should play inline in picture in picture mode.
### Actual Behavior
video Stops playing

### Version Information

Visual Studio version : 16.5.0
Xamarin.Android  SDK: 10.2.0.100

### Log File

DateTime.Now : 3/23/2020 11:23:07 AM
SqlLastTime : 3/23/2020 11:21:34 AM
03-23 16:53:07.193 I/mono-stderr(12778): DateTime.Now : 3/23/2020 11:23:07 AM
03-23 16:53:07.193 I/mono-stderr(12778): SqlLastTime : 3/23/2020 11:21:34 AM
EventApp.HelperClasses.ForegroundChecker03-23 16:53:07.451 I/mono-stdout(12778): EventApp.HelperClasses.ForegroundChecker

03-23 16:53:07.576 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->getObjectVolatile(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
03-23 16:53:07.577 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->putOrderedObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
03-23 16:53:07.577 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->putOrderedLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
03-23 16:53:07.740 W/YouTubeAndroidPlayerAPI(12778): Forcefully created overlay:ajck@cde4e7e helper:Lazy@a05ffdf view:null status: ....... {...}
03-23 16:53:07.751 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
03-23 16:53:07.751 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
03-23 16:53:07.824 E/RecyclerView(12778): No adapter attached; skipping layout
03-23 16:53:07.830 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->getObjectVolatile(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
03-23 16:53:07.831 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->putOrderedObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
03-23 16:53:07.831 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->putOrderedLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
03-23 16:53:07.872 W/event.meetappg(12778): Accessing hidden method Lsun/misc/Unsafe;->getObjectVolatile(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
EventApp.HelperClasses.ForegroundChecker03-23 16:53:07.965 I/mono-stdout(12778): EventApp.HelperClasses.ForegroundChecker

03-23 16:53:10.447 W/YouTubeAndroidPlayerAPI(12778): Video playback stopped because of an unauthorized overlay on top of player. The player view is obstructed by another window.

```<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:id="@+id/linear_youtube_rootlayout"
android:orientation="vertical"
android:background="@color/black"
android:layout_width="match_parent"
android:layout_height="match_parent">

<com.google.android.youtube.player.YouTubePlayerView
    android:id="@+id/youtube_player"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>

private void pictureInPictureMode()
    {
        youtubevideo.SetPlayerStyle(YouTubePlayerPlayerStyle.Chromeless);
        Rational aspectRatio = new Rational(200, 110);
        pictureInPictureParamsBuilder.SetAspectRatio(aspectRatio).Build();
        EnterPictureInPictureMode(pictureInPictureParamsBuilder.Build());

    }

**Comment by jpobst** [comment]
This seems to be a "feature" of `YouTubePlayerView` and nothing specific to Xamarin.Android.  I would try searching that error message on Google and seeing if any of the proposed fixes are relevant to your case.

https://stackoverflow.com/questions/16067783/android-youtubeplayer-with-unauthorized-overlay-on-top-of-player

**Comment by gopalawasthi123** [comment]
I have tried all those solutions . these are not worked for me

**Comment by jpobst** [comment]
I tried for a few hours but was not able to figure out how to do this correctly.  I don't see anyone on the internet who has successfully run `YouTubePlayerView` in PIP mode.  It may not be possible.

I would suggest you get support from Google on if this is possible, and if so, how to accomplish it.

**Comment by gopalawasthi123** [comment]
okay. I think it is against the googe policies. I have now implemented it using iframe. So i am closing this issue for now
