### ISSUE TITLE
AMQP Timeout Exception after migrating from VS 16.4.6 to VS 16.5

### ISSUE THREAD

**Issue by 18-th** [xamarin/xamarin-android#4448]
### Steps to Reproduce
1. Create a default Xamarin.Android project
2. Install any version of Microsoft.Azure.Service bus
3. Create a MessageSender with default settings pointing to the ServiceBus Queue, default transport type is set to AMQP
4. Attempt to send a message
5. Repeat previous steps, but replace the AMQP transport type with AMQP WebSockets
6. Attempt to send the same message

### Expected Behavior
Both messages are sent within a second, no exceptions thrown

### Actual Behavior
AMQP one fails to send a message with a timeout exception after trying to connect for roughly over a minute. AMQP WebSockets one gets delivered with no issues at all.

### Sidenote
The code to send a message has been in production for a bit over a year now, I use the same netstandard 2.0 shared library to send messages from the WPF app and Xamarin.Android app. WPF sends messages correctly. Xamarin app used to send messages perfectly fine too until I upgraded Visual Studio 2019 from version 16.4.6 to 16.5, after which it broke. I have tried to roll back to the version of the code that is currently in production and works but it is broken now as well, so at this point, I am fairly sure it has something to do with either Visual Studio or Xamarin.Android update.

The exception I get is along the lines of:
**Microsoft.Azure.ServiceBus.ServiceBusTimeoutException:** 'The operation did not complete within the allocated time 00:00:13.4100620 for object session5.'

I have tried two different queues, several devices with different Android versions, only WiFi\Data, but the bug is persistent.

### Version Information
Microsoft Visual Studio Community 2019
Version 16.5.0
VisualStudio.16.Release/16.5.0+29911.84
Microsoft .NET Framework
Version 4.8.03752

<details>
Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA442
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   16.5.236.49856
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.5.236.49856
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.5.236.49856
Azure Functions and Web Jobs Tools

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.5.20041.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IncrediBuild Build Acceleration   1.5.0.13
IncrediBuild effectively reduces compilation and development times by up to 90%.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30207.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.25+gdacdb9b7a1
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.512 (7a72495)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.5.20041.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.5.20041.1
Conda support for Python projects.

Python - Django support   16.5.20041.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.5.20041.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.5.20041.1
Profiling support for Python projects.

SQL Server Data Tools   16.0.62003.05170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20104.8+7c4de19faf36647c1ef700e655a52350840c6f03
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   16.5.000.521 (d16-5@b3ea41e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.49 (0904f41)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.14.1.39 (30e8706)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</details>

### Log File

[log.txt](https://github.com/xamarin/xamarin-android/files/4372527/log.txt)

### Repro
There is a SendMessage method bound to two buttons, one of them uses AMQP, the other one - WebSockets. AMQP one fails after about a minute, WebSockets just works. I have, obviously, removed my credentials so you would have to use your own ServiceBus plan, I hope you have one.

[ServiceBusRepro.zip](https://github.com/xamarin/xamarin-android/files/4372557/ServiceBusRepro.zip)

**Comment by grendello** [comment]
@18-th what is the exception? The attached log doesn't contain it. Can you post a full stack trace. Also, please see if you can reproduce the issue from a console/desktop app - timeouts are rarely a problem in the client, most often they happen because the server doesn't respond.

**Comment by 18-th** [comment]
@grendello 
Here is the stack trace.
[StackTrace.txt](https://github.com/xamarin/xamarin-android/files/4383991/StackTrace.txt)

I believe it is a client issue as I currently use this code in production and it works perfectly fine. I can not release the new version just because the old code is broken now.

I have searched the mono website but I am probably missing something, external links on creating projects are mostly 10-15 year old, could please you point me to the way of creating a VS project with NuGet dependencies using Mono? I have created a Netcore 3.1 console app, which I assume uses Mono for compilation, and I can not reproduce the issue.

Thank you in advance for your help

**Comment by grendello** [comment]
@18-th Just create a console app in VS, then copy it to a machine with Mono installed and use `msbuild` to build it as per normal command line steps (same as on Windows). Then run the app from the `bin` subdirectory of the solution. 

Thank you for the stack trace, unfortunately it doesn't have anything that could help. Also, it doesn't contain a single line pointing to anywhere in Xamarin.Android, it **may** be caused by something in the Mono runtime or BCL, but I can't see any evidence of that either - the stack trace almost exclusively contains lines from the `Microsoft.Azure` SDK and the error message suggests a **server** error in my opinion (unless you set a 13.0733440s timeout in your code). It seems as if the request reached the server and whatever backend it uses on the server side timed out accessing some resource.

I'd suggest trying to contact the Azure help service in order to see if it is in fact a server side issue. I don't think there's anything wrong with the code, but I will assign your issue to the Mono team to see if any changes in the runtime between the two XA releases in your upgrade can be responsible for the error.

@steveisok mind, taking a look? Thanks!
