### ISSUE TITLE
AesGcm support is missing

### ISSUE THREAD

**Issue by trampster** [xamarin/xamarin-android#4469]
## Steps to Reproduce

1. Try and construct a AesGcm instance
2. Notice you get a PlatformNotSupportedException

### Current Behaviour
AesGcm is not supported

### Expected Behavior
AesGcm is part of dotnet standard 2.1 which is officially supported, so I would except this to work.

## On which platforms did you notice this
Xamarin.Android

**Version Used**:
Xamarin.Android 10.1.4.0

**Comment by trampster** [comment]
I originally raised this against mono here: https://github.com/mono/mono/issues/19285
I'm not sure which project it should be raised against. Please feel free to delete which ever one is in the wrong place

**Comment by grendello** [comment]
It's a Mono BCL issue, thus closing this report, thanks!
