### ISSUE TITLE
Xamarin Android Binding Library Project fails using Proguard and Linker

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/xamarin-android#4475]
### Steps to Reproduce

I have created a android binding library using Samsung Accessory Sdk jar file. Everything works fine when I use Without linking or Sdk Assemblies only. But using full linking it fails with error MSB6006: "java.exe" exited with code 1. Thats typical proguard error but I couldnt figure out what could be the exact issue although I enabled diagnostic logs and logs doesnt say anything. There SO post like below suggesting Proguard settings for Samsung Accessory Sdk.
I tried all but unfortunately none of them worked for me. It is probably because I used Binding Library and it has some exception. It looks like that no way to keep binding library working using Proguard. Is it a bug?

https://stackoverflow.com/questions/24872517/proguard-issue-with-saagentsamsung-accessory-java-lang-nosuchmethodexception 

[SamsungWearCompanion.zip](https://github.com/xamarin/xamarin-android/files/4396322/SamsungWearCompanion.zip)

### Expected Behavior
It should work with my proguard config rules or at least give me a specific reason why it fails.

### Actual Behavior

returns error as "java.exe" exited with code 1." and no sufficient information in diagnostic logs

### Version Information

<!--
1. Vs 2019 16.4.5

**Comment by jonathanpeppers** [comment]
Building your project, I see a lot more information beyond `java exited with code 1`:

```
  java.io.FileNotFoundException: keepclassmembers class com.samsung.** { * (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileReader.<init>(FileReader.java:72)
        at proguard.FileWordReader.<init>(FileWordReader.java:39)
        at proguard.ConfigurationParser.parseIncludeArgument(ConfigurationParser.java:243)
        at proguard.ConfigurationParser.parse(ConfigurationParser.java:150)
        at proguard.ProGuard.main(ProGuard.java:530)
  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2421,3): error MSB6006: "java.exe" exited with code 1.
```

When I look at the proguard file, there looks like invalid proguard-rule syntax, spaces after `-`:
```
- keepclassmembers class com.samsung.** { *; }
- keep class com.samsung.** { *; }
- dontwarn com.samsung.** 
```

Beyond fixing that, did the solutions they recommended on StackOverflow work for you? 

https://stackoverflow.com/questions/24872517/proguard-issue-with-saagentsamsung-accessory-java-lang-nosuchmethodexception

**Comment by EmilAlipiev** [comment]
Hi @jonathanpeppers 
thanks for the quick reply. I have tried every single of the answer in SO post but error didnt change for me. I assumed that it was because of using Binding library and SO post was actually for Android java. I have seen other posts that people are failing with using Bind Libraries and proguard. thats why i created this issue here.

**Comment by moljac** [comment]
@EmilAlipiev 

I have the same results with your code like @jonathanpeppers.

I see few potential issues in your project config:

```
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{D6A0C922-E365-4E1A-AD61-BA3A9E530B49}</ProjectGuid>
    <ProjectTypeGuids>{EFBA0AD7-5A72-4C68-AF49-83D382785DCF};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <TemplateGuid>{c9e5eea5-ca05-42a1-839b-61506e0a37df}</TemplateGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>WearCompanion.Droid</RootNamespace>
    <AssemblyName>WearCompanion.Android</AssemblyName>
    <AndroidApplication>True</AndroidApplication>
    <AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>
    <AndroidResgenClass>Resource</AndroidResgenClass>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
    <MonoAndroidResourcePrefix>Resources</MonoAndroidResourcePrefix>
    <MonoAndroidAssetsPrefix>Assets</MonoAndroidAssetsPrefix>
    <AndroidUseLatestPlatformSdk>false</AndroidUseLatestPlatformSdk>
    <TargetFrameworkVersion>v10.0</TargetFrameworkVersion>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>3</WarningLevel>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidEnableMultiDex>true</AndroidEnableMultiDex>
    <AndroidDexTool>dx</AndroidDexTool>
    <AndroidEnableSGenConcurrent>false</AndroidEnableSGenConcurrent>
    <EmbedAssembliesIntoApk>false</EmbedAssembliesIntoApk>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidLinkTool>proguard</AndroidLinkTool>
    <BundleAssemblies>true</BundleAssemblies>
  </PropertyGroup>
```

and 

```
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.1.0" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0" />
    <PackageReference Include="Xamarin.AndroidX.CardView" Version="1.0.0" />
    <PackageReference Include="Xamarin.AndroidX.MediaRouter" Version="1.1.0" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.Utils" Version="1.0.0" />
    <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.2.0" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.1" />
    <PackageReference Include="Xamarin.AndroidX.Migration" Version="1.0.1" />
```

So you are using `dx` and `proguard` with AndroidX and that is not recommended.

I removed prougard config lines @jonathanpeppers mentioned too and was able to run the app and made unified use of `d8` and `r8` for both Debug and Release.

It crashes because I don't have connection to Samsung Wear device I assume.

Thanks.

**Comment by radekdoulik** [comment]
Hopefully this has been resolved by the previous suggestions. Please reopen and add more information if it is still happening.
