### ISSUE TITLE
TLS certificate error when xamarin.android project. Works if .NET Core 3.1

### ISSUE THREAD

**Issue by johnjore** [xamarin/xamarin-android#4481]
# Description
I'm using the MQTTnet library to communicate with mosquitto. If not using certificates it works fine in Xamarin. 

Certificates works fine, when compiled as a console application using .NET Core 3.1. 
However, when compiled as xamarin.android it fails to work.

### Steps to Reproduce
1. mosquitto (MQTT) is configured to use TLS1.2 and certificates (tried auto, no difference).
```
listener 8881
cafile /mosquitto/config/certs/root.crt
certfile /mosquitto/config/certs/client.crt
keyfile /mosquitto/config/certs/nopwd.key
require_certificate true
allow_anonymous false
use_identity_as_username false
tls_version tlsv1.2
```

2. This snippet works when compiled as a console app using .NET Core 3.1:
```
const SslProtocols sslProtocolVersion = SslProtocols.Tls12;

string currentPath = Path.Combine(Android.OS.Environment.ExternalStorageDirectory.AbsolutePath, Android.OS.Environment.DirectoryDownloads);
X509Certificate rootCert = X509Certificate.CreateFromSignedFile(Path.Combine(currentPath, rootCertName));
X509Certificate2 certificate = new X509Certificate2(Path.Combine(currentPath, userCertName), CertPrivKey);
UpdateStatusNonUI("Root Cert: '" + rootCert.Subject.ToString() + "'");
UpdateStatusNonUI("User Cert: '" + certificate.Subject.ToString() + "'");
UpdateStatusNonUI(userCertName + " has Private Key: '" + certificate.HasPrivateKey.ToString() + "'");

var TLSParameters = new MqttClientOptionsBuilderTlsParameters {
  UseTls = true,
  IgnoreCertificateChainErrors = false,
  IgnoreCertificateRevocationErrors = false,
  AllowUntrustedCertificates = false,
  SslProtocol = sslProtocolVersion,
  CertificateValidationCallback = (X509Certificate x, X509Chain y, SslPolicyErrors z, IMqttClientOptions o) => {
  return true;
  },
  Certificates = new List<X509Certificate> {
    rootCert,
    certificate
  },
};
UpdateStatusNonUI("TLS Parameters Set");

var options = new MqttClientOptionsBuilder()
  .WithClientId(clientId)
  .WithTcpServer(strMQTTServer, intMQTTPort)
  .WithCredentials(strMQTTUser, strMQTTPassword)
  .WithCleanSession()
  .WithTls(TLSParameters)
  .WithProtocolVersion(mqttProtocolVersion)
  .Build();
  UpdateStatusNonUI("Options Set");

  var mqttClient = new MqttFactory().CreateMqttClient();
  var MqttClientAuthenticateResult = await mqttClient.ConnectAsync(options);
```

3. mosquitto shows no errors if running as a console app using .NET Core 3.1, but reports this when snippet is an xamarin.android project:

> 1585478267: OpenSSL Error[0]: error:140350E5:SSL routines:ACCEPT_SR_CERT:ssl handshake failure

### Expected Behavior
Connect without errors, client or server

### Actual Behavior
While the errors refer to Mono, the error _could_ be within the MQTTnet library.

> Exception: MQTTnet.Exceptions.MqttCommunicationException: Authentication failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.Security.Cryptography.CryptographicException: Caught unhandled exception in `MonoBtlsSslCtx.ProcessHandshake`. ---> System.NullReferenceException: Object reference not set to an instance of an object.
> at Mono.Btls.MonoBtlsSsl.SetPrivateKey (Mono.Btls.MonoBtlsKey key) [0x00006] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsSsl.cs:214 
> at Mono.Btls.MonoBtlsContext.SetPrivateCertificate (Mono.Btls.X509CertificateImplBtls privateCert) [0x00011] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsContext.cs:166 
> at Mono.Btls.MonoBtlsContext.SelectCallback (System.String[] acceptableIssuers) [0x0003a] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsContext.cs:122 
> at Mono.Btls.MonoBtlsSslCtx.NativeSelectCallback (System.IntPtr instance, System.Int32 count, System.IntPtr sizes, System.IntPtr data) [0x00025] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsSslCtx.cs:174 
> --- End of inner exception stack trace ---
> at Mono.Btls.MonoBtlsObject.CheckLastError (System.String callerName) [0x00064] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsObject.cs:120 
> at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00032] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsContext.cs:219 
> at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:715 
> at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
> at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:289 
> at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:223 
> --- End of inner exception stack trace ---
> at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x0025c] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:310 
> at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync (System.Threading.CancellationToken cancellationToken) [0x00296] in <a330a25b6dc144a7be9224b975f9b26f>:0 
> at MQTTnet.Internal.MqttTaskTimeout.WaitAsync (System.Func`2[T,TResult] action, System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken) [0x000c2] in <a330a25b6dc144a7be9224b975f9b26f>:0 
> at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync (System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken) [0x00117] in <a330a25b6dc144a7be9224b975f9b26f>:0 
> --- End of inner exception stack trace ---
> at MQTTnet.Adapter.MqttChannelAdapter.WrapException (System.Exception exception) [0x00067] in <a330a25b6dc144a7be9224b975f9b26f>:0 
> at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync (System
> 

### Version Information
- Version with issue: All?
- Last known good version: None found

- Visual Studio 2019, 16.5.1
- Android: 8.0 (API Level 26)
- Xamarin.Android.SDK 10.2.0.100 (d16-5/988c811)
- Nuget Packages:
-- Microsoft.NETCore.Platforms 5.0.0-preview.1.20120.5 (same issue when using 3.1.0)
-- MQTTnet 3.0.9-rc1 (same issue when using 3.0.8)
-- System.Net.Security 4.3.2
-- NETStandard.Library 2.0.3
- Affected Devices: Samsung SM-A520F/DS (patched to latest and greatest from Samsung. Android version 8.0.0. Samsung Experience Version 9.0.

Cross-posted here: https://github.com/chkr1011/MQTTnet/issues/883

**Comment by baulig** [comment]
Using client certificates for authentication has always been a bit of a use at your own risk thing.  It's never been fully finished or thoroughly tested.

**Comment by johnjore** [comment]
That probably explains why it's not working. As its security related, and working with .NET Core, hope it gets implemented / fixed.

**Comment by rohitvipin** [comment]
Is there any update on this? 
Since AWS SDK does not support MQQT for IoT, it would be useful to use this.

**Comment by KevPantelakis** [comment]
I've come across the same error while trying out MQTTNet with Xamarin Forms.
In the process of testing solutions, I've found a complete random unexpected workaround:

When creating the Certificates list like it's shown in the [Wiki](https://github.com/dotnet/MQTTnet/wiki/Client#tls-using-a-client-certificate) I had the error:
```
[...]
Certificates = new List<X509Certificate>()
{
    caCert,
    clientCert,
}

System.Security.Cryptography.CryptographicException: Caught unhandled exception in MonoBtlsSslCtx.ProcessHandshake. ---> System.NullReferenceException: Object reference not set to an instance of an object.
```
BUT, I have no clue why, giving the clientCert first in the list gave me a successful connection in Xamarin:
 ```
[...]
Certificates = new List<X509Certificate>()
{
    clientCert,
    caCert,
}
```

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
