### ISSUE TITLE
GlGetString  responses empty string.

### ISSUE THREAD

**Issue by CoreNion** [xamarin/xamarin-android#4503]
### Steps to Reproduce

```C#:MainPage.xaml.cs
using System;
using Xamarin.Forms;
#if __ANDROID__
using Android.Opengl;
#endif
namespace testgl
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
#if __ANDROID__
            Name.Text = GLES20.GlGetString(GLES20.GlRenderer);
#endif
        }
    }
}
```

### Expected Behavior
Show GPU Renderer.
### Actual Behavior
Label(Name.Text) is empty.
Other information(e.g. GlExtensions) is same, too. 
### Version Information
=== Visual Studio Community 2019 for Mac ===

Version 8.5.1 (build 42)
Installation UUID: 
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.100
	3.0.101
	3.0.100
	2.2.300
	2.1.700
	2.1.505
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.0
	3.0.1
	3.0.0
	2.2.5
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.11
	2.1.9
	2.1.2
	2.0.5

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.4 (16134)
Build 11E146

=== Xamarin.Mac ===

Version: 6.16.0.11 (Visual Studio Community)
Hash: aa73e4125
Branch: d16-5-xcode11.4
Build date: 2020-03-25 11:04:02-0400

=== Xamarin.iOS ===

Version: 13.16.0.11 (Visual Studio Community)
Hash: aa73e4125
Branch: d16-5-xcode11.4
Build date: 2020-03-25 11:04:03-0400

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

=== Xamarin.Android ===

Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/********/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/********/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-03-28 00:48:52 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5~1
Build date: 2020-03-28 00:49:12 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805010042
Git revision: 926c6e86370a6d68fc930f0600932e0a9192e3da
Build date: 2020-03-30 17:14:37-04
Build branch: release-8.5
Xamarin extensions: 926c6e86370a6d68fc930f0600932e0a9192e3da

=== Operating System ===

Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**Comment by grendello** [comment]
@CoreNion what devices do you run the code on? Does it fail to return the string in all cases? If only some, then can you list device names that fail? The model, Android version, API level. Thanks.

**Comment by CoreNion** [comment]
@grendello at least, my device and emulator(gpu:host) don't show it.
(Pixel 4 XL, API 29 and API 28 Emulator)

**Comment by grendello** [comment]
@CoreNion Xamarin.Android does nothing special with the bindings to the methods you call, it's  straightforward pass-through to Android proper and the value you see is coming from Android, not us. With that - is your OpenGL initialized by the time you call this (and other) methods? If it isn't initialized you won't get any values, please see for instance [this SO topic](https://stackoverflow.com/questions/26614632/static-call-to-glgetstring-returns-null-in-android-5-0), hope that helps!

I'm going to close this issue as I don't believe there's anything Xamarin.Android can do to make the code work, thanks for reporting!
