### ISSUE TITLE
Android.Content.Res.Resources+NotFoundException when aapt:attr used in Android 6.0

### ISSUE THREAD

**Issue by dsenkyr** [xamarin/xamarin-android#4508]
### Steps to Reproduce

1. **TestDrawable.xml** in **Xamarin.Android** project in folder **Resources\drawable** using `aapt:attr`.
```
<?xml version="1.0" encoding="utf-8"?>
<!-- https://blog.stylingandroid.com/vectordrawable-gradients-part1 -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:aapt="http://schemas.android.com/aapt"
        android:width="96dp"
        android:height="96dp"
        android:viewportHeight="100"
        android:viewportWidth="100">
  <path android:pathData="M1,1 H99 V99 H1Z"
        android:strokeWidth="0">
    <aapt:attr name="android:fillColor">
      <gradient android:endColor="#4400FF"
                android:endX="50"
                android:endY="99"
                android:startColor="#1100FF"
                android:startX="50"
                android:startY="1"
                android:type="linear" />
    </aapt:attr>
  </path>
</vector>
```
2. **Debug | Any CPU** directly in a mobile phone (Android 6.0, API 23) or in Android Emulator (Android 6.0, API 23).

### I Tried

Following https://github.com/xamarin/xamarin-android/issues/3314 and https://www.gitmemory.com/issue/xamarin/xamarin-android/3314/508839100,

I add `<AndroidAapt2LinkExtraArgs>--no-version-vectors</AndroidAapt2LinkExtraArgs>` to all three **Property Groups** of **MyProject.Android.csproj**:
```
<PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    …
</PropertyGroup>

<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    …
</PropertyGroup>

<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    …
</PropertyGroup>
```

It does not help. Therefore, I tried set `AndroidUseAapt2` to `false` in all groups. It does not help too.

### Actual Behavior

**Exception:** Android.Content.Res.Resources+NotFoundException: 'File res/drawable/testdrawable.xml from drawable resource ID #0x7f020070'

**Observation:** Camel case in the name of **TestDrawable.xml** is not respected. I also try name the file **testdrawable.xml** but it does not help.

**Note:** When I debug the app in Android Emulator (Android 9.0, API 28), no exception occurs.

### Version Information

Visual Studio: Microsoft Visual Studio Professional 2019, Version 16.5.2
Mobile phone / Android Emulator: Android 6.0, API 23

**Comment by dellis1972** [comment]
Documentation reference for further research on how this `aapt:attr` works https://developer.android.com/guide/topics/resources/complex-xml-resources

**Comment by dellis1972** [comment]
@dsenkyr I did a quick test with the layout you provided with `aapt2` and it compiled without any issues. However I was targeting API 29. When switching back to API 23 I got the following errors from `aapt2`

```
res/drawable/testdrawable.xml:12: error: attribute android:endX not found.
res/drawable/testdrawable.xml:12: error: attribute android:endY not found.
res/drawable/testdrawable.xml:12: error: attribute android:startX not found.
res/drawable/testdrawable.xml:12: error: attribute android:startY not found.
```

It seems the attributes you are trying to use are not available on API 23. I would recommend updating your `targetSdkVersion` and Target Framework to be 29 or above (as per google's recommendation). If you want to be able to run you app on API 23 you can leave you `minSdkVersion` value as API 23. With those settings the app should compile.

These are the values from my Manifest which worked.

```
<uses-sdk minSdkVersion="23" targetSdkVersion="29" />
```

If you are not using `aapt2` in your project that might also account for the problem , I would recommend switching over to it.
