### ISSUE TITLE
Dots in TextView text is not appeared when TextView is remeasured at run time

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [xamarin/xamarin-android#4513]
### Description

Dots at the end of the text when text length exceeds TextView width is not appeared when the TextView is remeasured at runtime. Kindly find the sample below,

**Sample:**  [TestSample.zip](https://github.com/xamarin/xamarin-android/files/4427302/TestSample.zip)

In my sample, i have added TextView in custom FrameLayout and measured it. On initial load dots in the text of TextView is appears perfectly, but when I change the measure of the TextView by clicking the Change Layout button, dots get disappeared. 

### Steps to Reproduce

- Run the sample.
- Click change layout.

### Output Images

**On Initial load**
![screenshot-1585907838583](https://user-images.githubusercontent.com/39787321/78363335-31ad1080-75d9-11ea-882e-a5b3a7debbe6.jpg)

**After Remeasured**
![screenshot-1585918645506](https://user-images.githubusercontent.com/39787321/78363377-44bfe080-75d9-11ea-8ba4-7a7323907c07.jpg)

Could you please check on this and do the need full?

Regards,
Ganeshamoorthy C

**Comment by jpobst** [comment]
Using your sample project, ellipses do not show up before or after I click the button.  It is probably dependent on the device's default font.

If I'm reading your code correctly, you are initially setting the width to `200` and then when you click the button you set the width to `201`.  What is likely happening is this is simply the boundary between when the device thinks it needs to truncate the text and when it decides it has enough space to display the text without truncating it.

That is:
* `200` width - not big enough truncate the text
* `201` width - enough room to show the whole text, so no ellipses

**Comment by Ganeshamoorthy10** [comment]
Hi @jpobst,

Thanks for the response. 

If you are not getting ellipses at the end of the text, you can increase the text size in my TestSample, so that you can able to reproduce the issue.

In my sample you can see the text width "Sampleeeeeeeee", sample with 9 ‘e’ letter, when I change the text width as 201, only 7 ‘e’ letter is displayed. Its not enough width to display the whole text, so it should truncate the text and ellipses should be appeared. 

What I am trying to say is, when I change the TextView width at runtime, ellipses gets disappeared even if the new width is not enough to show the whole text.

**Comment by jpobst** [comment]
If you start with the text width at 201, do you get the ellipses? or does it only display the 7 `e`'s?

Ultimately I don't think there is much that can be done on our side.  We simply provide wrappers to allow the Java Android APIs to be consumed from C#.  This seems like an issue that exists in Android itself and could only be resolved by Google.

**Comment by Ganeshamoorthy10** [comment]
Ellipses appeared with the text width as 201 on initial load.

**Comment by jpobst** [comment]
Unfortunately this sounds like a bug in Android and not Xamarin, and there's not much we can do.  😞
