### ISSUE TITLE
Random failures with _CompileJava: Javac exited with code 1 in Azure Devops Hosted Agents

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#4514]
### Steps to Reproduce

There is no clear repro, aside from building this project on azure devops vs2019 hosted agents. Most of the time, retrying the build will generally make the build pass.

I'm looking for a way to trouble shoot this. Are there parameters to view the actual errors ?

### Expected Behavior

There is no Javac.exe exited with code 1 error.

### Actual Behavior

```
       _CompileJava:
         C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64\bin\javac.exe -J-Dfile.encoding=UTF8 "@C:\Users\VssAdministrator\AppData\Local\Temp\tmp3970.tmp" 
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2459,3): Error MSB6006: "javac.exe" exited with code 1.
    28>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2459,3): error MSB6006: "javac.exe" exited with code 1. [d:\a\1\s\src\SamplesApp\SamplesApp.Droid\SamplesApp.Droid.csproj]
    28>Done Building Project "d:\a\1\s\src\SamplesApp\SamplesApp.Droid\SamplesApp.Droid.csproj" (default targets) -- FAILED.
     2>Done Building Project "d:\a\1\s\src\Uno.UI.sln" (Restore;Build target(s)) -- FAILED.
     1>Done Building Project "d:\a\1\s\Build\Uno.UI.Build.csproj" (default targets) -- FAILED.

```

### Version Information

vs2019 hosted agents, `MSBuild Version 16.4.0`. This happened in vs2017 agents as well.

**Comment by jpobst** [comment]
It may just be a typo on this issue, but it looks like there's not enough spaces in your argument list:
```
C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64\bin\javac.exe -J-Dfile.encoding=UTF8 "@C:\Users\VssAdministrator\AppData\Local\Temp\tmp3970.tmp"
```

The most likely way to troubleshoot this would be to use MSBuild diagnostic verbosity, I think that will add the actual error message `javac` is returning to the log file:
```
msbuild /v:diag Uno.UI.sln
```

**Comment by jeromelaban** [comment]
I'm having a hard time reproducing it, as adding logging seems to make the error go away :) 

As for the log, it's not a typo, that's the actual output, taken from the azure devops UI.

**Comment by jeromelaban** [comment]
This looks like the issues were related to memory pressure. I'm splitting our build in more phases and disabling parallelism.

When upgrading to 16.5, the problem became more apparent as there it seems that hosted machines have less available memory.

Thank for your help!

**Comment by jpobst** [comment]
Cool, glad you figured it out, and thanks for keeping us updated!
