### ISSUE TITLE
Custom Profile with Startup Tracing fails on Visual Studio for Mac

### ISSUE THREAD

**Issue by MathieuJack** [xamarin/xamarin-android#4566]
Create a new Xamrin.Forms project with VS For Mac.
Follow this [step by step tutorial ](https://forums.xamarin.com/discussion/180700/best-way-to-insert-a-native-android-activity-in-a-xamarin-forms-application/p1?new=1) to do profiled startup tracing :

1. In terminal window, move to Android project folder the run msbuild /t:BuildAndStartAotProfiling 
2. Once app is launched, in terminal window, run msbuild /t:FinishAotProfiling

### Repro project
[TestSplash2.zip](https://github.com/xamarin/xamarin-android/files/4488845/TestSplash2.zip)

### Expected Behavior
process finishes succesfully, and a profile file is created

### Actual Behavior
process finished wit an error, and not profile file is created.
Error is : 
EXEC : error : aotprofile-tool: Unable to read profile through local port: 9999. [/Users/yadusurf/Projects/TestSplash2/TestSplash2.Android/TestSplash2.Android.csproj]

### Version Information
=== Visual Studio Community 2019 for Mac ===

Version 8.5.2 (build 13)
Installation UUID: fce74197-4474-4c5e-bfdf-d7e65aabd7e3
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
	3.0.101
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.0.1
	3.0.0
	2.1.16
	2.1.15
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.4.1 (16137)
Build 11E503a

=== Xamarin.Mac ===

Version: 6.16.0.13 (Visual Studio Community)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:18-0400

=== Xamarin.iOS ===

Version: 13.16.0.13 (Visual Studio Community)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:19-0400

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

=== Xamarin.Android ===

Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/yadusurf/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/yadusurf/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-04-02 00:16:12 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5~1
Build date: 2020-04-02 00:16:32 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805020013
Git revision: 90b766333e562018f979de04293c097898dafdf4
Build date: 2020-04-02 10:35:07-04
Build branch: release-8.5
Xamarin extensions: 90b766333e562018f979de04293c097898dafdf4

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

### Log File
Here is terminal window content.
(Note : it is a rtf I had to rename it txt to attach it)
[terminal window content.txt](https://github.com/xamarin/xamarin-android/files/4488864/terminal.window.content.txt)

**Comment by brendanzagaeski** [comment]
Thanks for the report! In the specific Terminal session attached in the first comment, the issue is:

```
  Calling 'adb forward tcp:9999 tcp:9999'...
  The files /Users/yadusurf/Projects/TestSplash2/TestSplash2.Android/adb, /Users/yadusurf/Projects/TestSplash2/TestSplash2.Android/forward, /Users/yadusurf/Projects/TestSplash2/TestSplash2.Android/tcp:9999, and /Users/yadusurf/Projects/TestSplash2/TestSplash2.Android/tcp:9999 do not exist.
EXEC : error : aotprofile-tool: Unable to read profile through local port: 9999.
  System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
    at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00102] in <d6a60aa59c7e453abe17968d3649bb29>:0 
    at System.Diagnostics.Process.Start () [0x00032] in <d6a60aa59c7e453abe17968d3649bb29>:0 
    at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
    at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <d6a60aa59c7e453abe17968d3649bb29>:0 
    at System.Diagnostics.Process.Start (System.String fileName, System.String arguments) [0x00007] in <d6a60aa59c7e453abe17968d3649bb29>:0 
    at aotprofiletool.MainClass.ReadProfileFromPort (Mono.Profiler.Aot.ProfileReader reader) [0x00044] in <9387e4304a5e43a0be3ce68086330df9>:0 
    at aotprofiletool.MainClass.Main (System.String[] args) [0x00048] in <9387e4304a5e43a0be3ce68086330df9>:0 
```

In that case, the issue is that the `adb` command could not be found on the path. For this particular Terminal session, it seems the `PATH` environment variable was not set. In comparison, in your previous comment in <https://github.com/xamarin/xamarin-android/issues/4152#issuecomment-612349918>, it looked like the `PATH` environment variable _was_ set.

## Next steps

 1. Run the following command in the Terminal window to `adb` to `PATH`:

    ```sh
    PATH="$PATH":"$HOME/Library/Developer/Xamarin/android-sdk-macosx/platform-tools/
    ```

 2. Run the following command to clear the log on the device:

    ```sh
    adb logcat -c
    ```

 3. Build and start profiling again with diagnostic logging:
 
    ```sh
    msbuild "/flp:v=diag;logfile=$HOME/Desktop/startprofiling.log" /restore /t:Clean,BuildAndStartAotProfiling
    ```

 4. Finish profiling with diagnostic logging:
    
    ```sh
    msbuild "/flp:v=diag;logfile=$HOME/Desktop/stopprofiling.log" /t:FinishAotProfiling
    ```

 5. Collect the device log by running a command similar to the following:

    ```sh
    adb logcat -d > "$HOME/Desktop/adblogcat.txt"
    ```

 6. Zip up and attach back the three log files from your desktop: *startprofiling.log*, *stopprofiling.log*, *adblogcat.txt*.

Thanks in advance!

**Comment by MathieuJack** [comment]
Dear Brendan, my Path was not well set; I followed your steps and it worked, not only in repro project, but also in my real project. Thank you very much.

**Comment by brendanzagaeski** [comment]
Excellent. Glad to hear it's working now!

**Comment by MathieuJack** [comment]
I could not complete startup tracing with profile successfully, I have another problem at deployment. It occurs with my "main" application which is much bigger that repro app posted before.

the deployment log shows several times this error : 
    [aot-compiler stdout] * Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mono/mini/aot-compiler.c:12437

Then at the end : 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: Newtonsoft.Json.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: SkiaSharp.Views.Forms.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: SkiaSharp.Views.Android.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: SkiaSharp.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: Yadusurf.XamarinForms.Android.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: Xamarin.Android.Arch.Core.Common.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: Rg.Plugins.Popup.Droid.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: System.Xml.Linq.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: Java.Interop.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: Mono.Android.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: mscorlib.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: Xamarin.Android.Arch.Core.Runtime.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: Ninject.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: MR.Gestures.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: FormsViewGroup.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2703,3): error XA3001: Could not AOT the assembly: System.Numerics.dll
    0 Warning(s)
    16 Error(s)

More detailled log and custom profile file attached.
[Logs and custom profile.zip](https://github.com/xamarin/xamarin-android/files/4496294/Logs.and.custom.profile.zip)

Should I create a new issue, or is it OK to continue this issue?

**Comment by brendanzagaeski** [comment]
Thanks for the additional info. That looks interesting. It appears that either (a) the recording step wrote an invalid value into the custom profile or (b) the compilation step read a value incorrectly from the profile.

The failing assertion happens while parsing the custom profile: https://github.com/mono/mono/blob/c0c5c78e2bdbdbf7a70ae10b0a698708f1f2edbe/mono/mini/aot-compiler.c#L12437

I think the best next step would indeed be to copy your last comment into a new issue for further investigation by the team. The _custom.aprof_ file and build logs might be enough information for the initial investigation, but if you get a chance, one other detail that might be useful to include would be which ABIs the app is targeting. One way to capture that info, along with various other build parameters that might be useful clues, would be to set the build verbosity to diagnostic under **Visual Studio > Preferences > Build > Log verbosity**, and then repeat the Build and Deployment steps.

Thanks in advance!

**Comment by MathieuJack** [comment]
OK, donc!
I have created issue 4602 and attached diagnostics logs.
Thank you!
