### ISSUE TITLE
Can't call Java desugared static interface methods in android libraries before API-24

### ISSUE THREAD

**Issue by Dolfik1** [xamarin/xamarin-android#4574]
### Steps to Reproduce

1. Generate bindings to any library with static interface method
2. Set Minimum Android version to API Level 23 or lower
3. Call static interface method

[WebRtcTest.zip](https://github.com/xamarin/xamarin-android/files/4492298/WebRtcTest.zip)

### Expected Behavior
Method called successfully

### Actual Behavior
Java.Lang.NoSuchMethodError: 'no static method "Lorg/webrtc/EglBase;.create()Lorg/webrtc/EglBase;"'

### Other
There are fix for Gradle: https://github.com/react-native-webrtc/react-native-webrtc/issues/720#issuecomment-554299138

### Version Information
Microsoft Visual Studio Community 2019
Version 16.5.2
VisualStudio.16.Release/16.5.2+29926.136
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.5.236.49856
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.5.236.49856
Azure Functions and Web Jobs Tools

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30207.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.25+gdacdb9b7a1
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.5.514 (c4f36a9)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62003.05170
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Example of hosting the editor embedded into a tool window.

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20104.8+7c4de19faf36647c1ef700e655a52350840c6f03
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.528 (d16-5@2b54082)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.49 (0904f41)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.16.0.11 (aa73e41)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonpryor** [comment]
The problem is caused by ["desugaring"](https://developer.android.com/studio/write/java8-support), which "moves things around."  In particular, if you run `dexdump classes.dex` on the `classes.dex` contained within the `.apk`, the *only* `create` method with a "type" of `()Lorg/webrtc/EglBase;` is declared in `Lorg/webrtc/EglBase$-CC;`:

```
$ $HOME/android-toolchain/sdk/build-tools/29.0.2/dexdump classes.dex
…
Class #1481            -
  Class descriptor  : 'Lorg/webrtc/EglBase$-CC;'
  Access flags      : 0x1011 (PUBLIC FINAL SYNTHETIC)
  Superclass        : 'Ljava/lang/Object;'
  Interfaces        -
  Static fields     -
  Instance fields   -
  Direct methods    -
    …
    #1              : (in Lorg/webrtc/EglBase$-CC;)
      name          : 'create'
      type          : '()Lorg/webrtc/EglBase;'
      access        : 0x0009 (PUBLIC STATIC)
      code          -
      registers     : 2
      ins           : 0
      outs          : 2
      insns size    : 8 16-bit code units
      catches       : (none)
      positions     : 
        0x0000 line=170
      locals        : 
```

`EglBase$-CC` is *not* a class present within the original `classes.jar`.  Equally important, our code is looking for the `create` method on `org/webrtc/EglBase`, *not* `org/webrtc/EglBase$-CC;`, and while `org/webrtc/EglBase` exists in `classes.dex`, it does not contain the static `create` method.

This is why the `Java.Lang.NoSuchMethodError` is thrown.

Disabling desugar allow the app to run, but requires -- as you note in step (2) -- that the Minimum Android version to API Level be 24 or higher.  *26* in this case, actually, to avoid a different build error:

```
D8 : error : Invoke-customs are only supported starting with Android O (--min-api 26)
```

---

I'm not entirely sure how to address this on our end.  We could skip binding static interface methods/etc. unless building against `Mono.Android.dll` v7.0, which would avoid the `NoSuchMethodException`… by removing the method entirely.  (This isn't a "fix.")  I'm also not sure it would actually *work*, because *all* `Mono.Android.dll`s have an assembly version of 0.0.0.0, so we'd have to "somehow" ensure that the v7.0 bit makes it into the NuGet package?  (*I* don't understand how that process works.)

The only other fix I can think of is to IL-rewrite the binding assembly to replace appropriate instances of `Lorg/webrtc/EglBase;` with `Lorg/webrtc/EglBase$-CC;`, which could be done but could be "brittle".

**Comment by Dolfik1** [comment]
@jonpryor is it possible fix that via transforms without IL rewriting?

I tried to use this code, but it doesn't worked for me:
```
<add-node path="/api/package[@name='org.webrtc']">
  <interface abstract="true" deprecated="not deprecated" final="false" name="EglBaseCustom" static="false" visibility="public" jni-signature="Lorg/webrtc/EglBase;">
    <method abstract="false" deprecated="not deprecated" final="false" name="create" jni-signature="()Lorg/webrtc/EglBase$-CC;" 
		  bridge="false" native="false" return="org.webrtc.EglBase" jni-return="Lorg/webrtc/EglBase;" static="true" synchronized="false" synthetic="false" visibility="public">
    </method>
  </interface>
</add-node>```

**Comment by Dolfik1** [comment]
I found workaround for this issue:
```csharp
namespace Org.Webrtc
{
	[Register("org/webrtc/EglBase$-CC", DoNotGenerateAcw = true)]
	public abstract class EglBaseStatic : Java.Lang.Object
	{
		internal EglBaseStatic()
		{
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='org.webrtc']/interface[@name='EglBase']/method[@name='create' and count(parameter)=0]"
		[Register("create", "()Lorg/webrtc/EglBase;", "")]
		public static unsafe global::Org.Webrtc.IEglBase Create()
		{
			const string __id = "create.()Lorg/webrtc/EglBase;";
			try
			{
				var __rm = _members.StaticMethods.InvokeObjectMethod(__id, null);
				return global::Java.Lang.Object.GetObject<global::Org.Webrtc.IEglBase>(__rm.Handle, JniHandleOwnership.TransferLocalRef);
			}
			finally
			{
			}
		}

		static readonly JniPeerMembers _members = new XAPeerMembers("org/webrtc/EglBase$-CC", typeof(EglBaseStatic));
	}
}
```

But this workaround works only in Debug configuration. I got this exception in Release configuration:
```
Java.Lang.IncompatibleClassChangeError: no static method "Lorg/webrtc/EglBase$-CC;.create()Lorg/webrtc/EglBase;"
      at Java.Interop.JniEnvironment+StaticMethods.GetStaticMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <3f76ba23ba894c92a0082c32427fb8a5>:0 
      at Java.Interop.JniType.GetStaticMethod (System.String name, System.String signature) [0x0000c] in <3f76ba23ba894c92a0082c32427fb8a5>:0 
      at Java.Interop.JniPeerMembers+JniStaticMethods.GetMethodInfo (System.String encodedMember) [0x00036] in <3f76ba23ba894c92a0082c32427fb8a5>:0 
      at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00000] in <3f76ba23ba894c92a0082c32427fb8a5>:0 
      at Org.Webrtc.EglBaseStatic.Create () [0x0000a] in <e9145eeab3c54ba095bbc83c7d9b5f7a>:0 
```

@jonpryor what do you think about this?

**Comment by jpobst** [comment]
We believe desugar remapping is now fully supported in `net8.0-android` and beyond.

https://github.com/xamarin/java.interop/pull/1077
