### ISSUE TITLE
Make it easy to update apkdesc files used for regression testing

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#4576]
In https://github.com/xamarin/xamarin-android/pull/4545 we switched from old `.xml` files with size information to more descriptive `.apkdesc` files generated by `apkdiff` tool.

Let make the PR's actual `.apkdesc` files be part of test results build artifacts, with the names containing the test configuration and flavor.

**Comment by jonpryor** [comment]
A related feature: could the contents of the `.apkdesc` file be *sorted*?  I had to update some the files as part of PR #4569, and found that the order of entires in git completely differed from what it generated locally:

```diff
diff --git a/tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc b/tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc
index 2f10db2a..aab1a92a 100644
--- a/tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc
+++ b/tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc
@@ -3049,173 +3049,170 @@
     "lib/x86/libmono-native.so": {
       "Size": 788196
     },
-    "lib/armeabi-v7a/libaot-Xamarin.Android.Support.AsyncLayoutInflater.dll.so": {
-      "Size": 8668
-    },
-    "lib/armeabi-v7a/libaot-Java.Interop.dll.so": {
-      "Size": 878844
-    },
-    "lib/armeabi-v7a/libaot-Xamarin.Android.Arch.Core.Runtime.dll.so": {
-      "Size": 8640
-    },
-    "lib/armeabi-v7a/libaot-System.dll.so": {
-      "Size": 3969392
-    },
     "lib/armeabi-v7a/libaot-Xamarin.Forms.Performance.Integration.Droid.dll.so": {
       "Size": 179420
     },
-    "lib/armeabi-v7a/libaot-System.Net.Http.dll.so": {
-      "Size": 1198956
+    "lib/armeabi-v7a/libaot-FormsViewGroup.dll.so": {
+      "Size": 58348
     },
-    "lib/armeabi-v7a/libaot-Xamarin.Android.Support.Annotations.dll.so": {
-      "Size": 9128
+    "lib/armeabi-v7a/libaot-Xamarin.Android.Arch.Lifecycle.Runtime.dll.so": {
+      "Size": 8660
     },
-    "lib/armeabi-v7a/libaot-Xamarin.Android.Support.Core.UI.dll.so": {
-      "Size": 70112
+    "lib/armeabi-v7a/libaot-Newtonsoft.Json.dll.so": {
+      "Size": 3390944
     },
```

It's not that the entries had been removed, it's that they had been *reordered*.  This adds noise, and complicates review.  (And results in me manually reordering elements to make for a smaller diff.)

**Comment by jonpryor** [comment]
Another oddity I'm encountering:


```
$ bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/apkdiff tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc ~/Downloads/Xamarin.Forms_Performance_Integration-Profiled-Aot-Signed.apkdesc 
…
  +     255,792 classes.dex
```

I don't understand where this `255,792` is coming from.  `$HOME/Downloads/Xamarin.Forms_Performance_Integration-Profiled-Aot-Signed.apkdesc` has:

```json
    "classes.dex": {
      "Size": 2200624
    },
```

While the original shows 1944832.  255792 appears to have no relation to either of those?

**Comment by radekdoulik** [comment]
> While the original shows 1944832. 255792 appears to have no relation to either of those?

It shows the difference - note the plus sign. The size increased by 255,792 bytes. (2,200,624 - 1,944,832 = 255,792)

**Comment by radekdoulik** [comment]
> It's not that the entries had been removed, it's that they had been reordered. This adds noise, and complicates review. (And results in me manually reordering elements to make for a smaller diff.)

Great idea, I will look into this.

**Comment by radekdoulik** [comment]
Implemented by https://github.com/xamarin/xamarin-android/pull/4591 and improved with https://github.com/xamarin/xamarin-android/pull/4613
