### ISSUE TITLE
VS 16.6.0 Prev 4.0 - System bars reappear on rotation of ImmersiveSticky fragments - Android 10 devices only

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#4611]
My production app (Android 9 and support libs) does not have this problem. The same two ViewPager fragments can be rotated as many times as you like, and the system bars never reappear running any version of Android (21-29)

The replacement app I’m working on is a prototype version using AndroidX libs compiled using Android 10. The prototype app uses a BottomNavigationView (production app uses a different technique) on a particular fragment that allows two other full-screen fragments to be viewed. 

The same app rotates without the reappearance of the system bars on any device running less than Android 10. The Android 10 devices I’ve tested with are a Pixel3a and a Samsung 20. The behaviour is identical on both those devices.

My app connects via Bluetooth so using an emulator is not normally possible. I temporarily removed the Bluetooth dependence and tried with an emulator. The emulator doesn’t emulate a real device as when both fragments are rotated to landscape, the gauges in the fragment instead of being orientated N/S are E/W, so it is not possible to test using an emulator. It would appear that the emulator may not be able to support reading an alias when reading a layout file.

For example: 
```
<item
name="gauges2" type="layout">@layout/gauges2_wide
 </item>
```
Because the emulator was of no practical use, it can’t reproduce the problem and doesn’t rotate properly, I didn’t bother investigating with the emulator further. **Please don’t bother with an emulator, it must be an Android 10 device**

The project uploaded contains a Word readme file re instructions of use and all the possible solutions I’ve attempted to eliminate the reappearance of the system bars.

The uploaded project was also responsible for issues #4415 and #4471 which I believe are now fixed. It is also responsible for Issue #4317 which is not fixed as this project demonstrates if you open any layout file.

[OBDNowProto.zip](https://github.com/xamarin/xamarin-android/files/4527780/OBDNowProto.zip)

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.
