### ISSUE TITLE
A couple of monodroid-samples binding projects no longer build against d16-6

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#4617]
### Steps to Reproduce

1. Build the following projects against d16-6
* https://github.com/xamarin/monodroid-samples/tree/master/android5.0/GoogleIO2014Master
```
msbuild /restore android5.0/GoogleIO2014Master/GoogleIO2014Master/GoogleIO2014Master.csproj
```
* https://github.com/xamarin/monodroid-samples/tree/master/OsmDroidBindingExample

```
msbuild /restore OsmDroidBindingExample/OSMDroidTest/OSMDroidTest.csproj
```

These projects previously built against d16-5 and earlier, and are no longer building with d16-6.

[GoogleIO2014 CI failure](
https://dev.azure.com/devdiv/DevDiv/_releaseProgress?releaseId=654124&_a=release-environment-extension&environmentId=3567428&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&runId=12813208&resultId=100067&paneView=debug)

[OsmDroidBindingExample CI failure](https://dev.azure.com/devdiv/DevDiv/_releaseProgress?releaseId=654124&_a=release-environment-extension&environmentId=3567428&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&runId=12813208&resultId=100244&paneView=debug)

**Comment by pjcollins** [comment]
We fixed this on the [monodroid-samples side](https://github.com/xamarin/monodroid-samples/commit/eb0e85d2d675322ec7173eb676f6dbf5af93ab02), but we may want to make a note of this behavior in 16.6 release notes?

**Comment by jpobst** [comment]
Here's the note I suggested @brendanzagaeski add:

Note: 

Previously nested private classes were bound by default. This has been changed so
the `private` modifier is respected. However bindings projects may have been
relying on this behavior. If a nested private class needs to be exposed, 
use metadata to mark is as visible:

```
<attr path="/api/package[@name='com.example']/class[@name='MyClass.NestedClass']" name="visibility">public</attr>
```

**Comment by brendanzagaeski** [comment]
Thanks for the heads-up on this! Here's what I have staged for this for publication in the next update of the Xamarin.Android 10.3 release notes. I took some creative license, so let me know if I messed up anything about the intended meaning.

````
### Bindings projects now exclude private nested types

Previously, Xamarin.Android bindings projects generated public bindings for all
nested Java types, even when the types had private or package-private
visibility.  Bindings projects now respect private visibilities on nested types
and no longer generate bindings for those types.

> ![NOTE]
> This change in behavior can result in new C# compiler errors for bindings
> projects, such as:
>
> ```
> error CS0426: The type name 'AttribOp' does not exist in the type 'CSSParser'
> error CS0115: 'MapControllerOld.HalfCosinusalDeceleratingAnimationRunner.JniPeerMembers': no suitable method found to override
> ```
>
> To restore any needed missing types, adjust the visibilities by adding rules
> like the following to the _Transforms\Metadata.xml_ file:
>
> ```xml
> <attr path="/api/package[@name='com.caverock.androidsvg']/class[@name='CSSParser.AttribOp']" name="visibility">public</attr>
> <attr path="/api/package[@name='org.osmdroid.views']/class[@name='MapControllerOld.CosinusalBasedAnimationRunner']" name="visibility">public</attr>
> ```
````

I'll plan to close this issue once the release notes update that includes that info is published.

**Comment by brendanzagaeski** [comment]
This section is now published in the release notes: <https://docs.microsoft.com/xamarin/android/release-notes/10/10.3#bindings-projects-exclusion-of-private-nested-types>

I will accordingly close this item as a documented change. Thanks again!
