### ISSUE TITLE
CopyGeneratedJavaResourceClasses and Xamarin.Android (Mac 8.5 & 8.6)

### ISSUE THREAD

**Issue by vixez** [xamarin/xamarin-android#4628]
### Steps to Reproduce

1. Try to run a Xamarin Android application on a device (on Mac or Windows)
2. Build succeeds
3. Deployment fails

This is the case both on stable and preview channel (as of today 28/04/2020).
Xamarin iOS works.

### Expected Behavior
The application deploys and runs

### Actual Behavior
Error at the end of deployment:
`The "CopyGeneratedJavaResourceClasses" task was not given a value for the required parameter "SourceTopDirectory"`

### Version Information

=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.6 Preview (8.6 build 4243)
Installation UUID: 31096e3f-b37d-4f41-b798-bd631bf3feac
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
	Package version: 610000101

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.101 (2019-12/6f0bf73005d) (64-bit)
	Package version: 610000101

=== Roslyn (Language Service) ===

3.6.0-3.20209.3+34fad56309fc96f2af1171df6ea012cbf991c27d

=== NuGet ===

Version: 5.5.0.6473

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.0
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.3.0.74 (Visual Studio Community)
Commit: xamarin-android/d16-6/964ac42
Android SDK: /Users/glennruyschaert/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/glennruyschaert/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.46
Hash: f6bfa7b
Branch: remotes/origin/dev/joe/d16-6~2
Build date: 2020-04-09 20:14:24 UTC

=== Android Device Manager ===

Version: 16.6.0.75
Hash: 4509c53
Branch: remotes/origin/d16-6~6
Build date: 2020-04-09 20:14:50 UTC

=== Xamarin Designer ===

Version: 16.6.0.320
Hash: dcc2cd183
Branch: remotes/origin/d16-6
Build date: 2020-04-10 18:49:40 UTC

=== Apple Developer Tools ===

Xcode 11.4 (16134)
Build 11E146

=== Xamarin.Mac ===

Version: 6.18.1.31 (Visual Studio Community)
Hash: b3eedfed9
Branch: d16-6
Build date: 2020-04-09 10:22:36-0400

=== Xamarin.iOS ===

Version: 13.18.1.31 (Visual Studio Community)
Hash: b3eedfed9
Branch: d16-6
Build date: 2020-04-09 10:22:36-0400

=== Build Information ===

Release ID: 806004243
Git revision: dda82db2458288a91a58f44d24abe41cf0d25bb6
Build date: 2020-04-14 16:13:25-04
Build branch: release-8.6
Xamarin extensions: dda82db2458288a91a58f44d24abe41cf0d25bb6

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

### Log File

http://glennruysschaert.com/devlogs/logs/XamarinAndroidDeploymentCopyGeneratedJavaResourceClasses.txt

**Comment by dellis1972** [comment]
Looks like the problem here is the `_PrepareUpdateAndroidResgen` target is skipped. Which means the temp directory is not created and the value for `ResgenTemporaryDirectory` is then empty. 

It is however odd that `_PrepareUpdateAndroidResgen` is skipped but `_UpdateAndroidResgen` is NOT since they both have exactly the same inputs. That means something else is modifying a file which is then causing `_UpdateAndroidResgen` to run when it shouldn't.

**Comment by dellis1972** [comment]
In this case its the following

```
Input file "obj/Debug/res/values/goog_svcs_json.xml" is newer than output file "obj/Debug/R.cs.flag".
```

and that is caused by 
```
Target "ProcessGoogleServicesJson" in file "/Users/glennruyschaert/Code/Energylab_Yoga_001/YogaMetEvi/packages/Xamarin.GooglePlayServices.Basement.42.1001.0/build/MonoAndroid70/Xamarin.GooglePlayServices.Basement.targets":
  Using "ProcessGoogleServicesJson" task from assembly "/Users/glennruyschaert/Code/Energylab_Yoga_001/YogaMetEvi/packages/Xamarin.GooglePlayServices.Basement.42.1001.0/build/MonoAndroid70/Xamarin.GooglePlayServices.Tasks.dll".
  Task "ProcessGoogleServicesJson"
    Started ProcessGoogleServicesJson...
    Android Package Name: be.bazookas.mobile.yogametevy
    Writing Resource File: obj/Debug/res/values/goog_svcs_json.xml
    Wrote Resource File: obj/Debug/res/values/goog_svcs_json.xml
    Finished ProcessGoogleServicesJson...
  Done executing task "ProcessGoogleServicesJson".
Done building target "ProcessGoogleServicesJson" in project "YogaMetEvi.Droid.csproj".
```

Which comes from the `Xamarin.GooglePlayServices.Basement.42.1001.0` nuget package.

Which is a very very old version of that package. The latest version is `71.1620.0`. That package was updated to include Inputs/Outputs to that target which will stop it running if the file is up to date.

I would recommend you upgrade your nuget packages to the latest versions, that should fix this issue.

**Comment by vixez** [comment]
@dellis1972 You were right, this is quite an old project that needed a minor update. Updating the NuGet packages solved it.
