### ISSUE TITLE
HttpClient does not use /etc/hosts file for DNS lookup

### ISSUE THREAD

**Issue by zd-dalibor** [xamarin/xamarin-android#4639]
In my android emulator I change the hosts file (`/etc/hosts`, `/etc/system/hosts`, `/system/etc/hosts`) and add this.

```
10.0.2.2 my.app.test
```

When I start chrome browser in emulator and enter `http://my.app.test:8080` I get page loaded from my local machine web server.

But when I try the same thing in my code in xamarin application with `HttpClient.SendAsync()` I get this error:

```
Unable to resolve host "my.app.test": No address associated with hostname
```

**Comment by brendanzagaeski** [comment]
Thanks for the report. I was unable to reproduce this behavior with Visual Studio 2019 version 16.5 (Xamarin.Android SDK version 10.2.0.100).

Steps tested: 

 1. Launch an Android 7.1 Nougat (API level 25) Google APIs x86 emulator (system-images;android-25;google_apis;x86) with a command similar to:

    ```
    emulator -avd Google_API_25_x86 -writable-system
    ```

 2. Push a hosts file with an entry for `my.app.test`:

    ```
    adb root
    adb remount
    adb push hosts /system/etc/hosts
    ```

 3. Run a test app that uses `HttpClient.SendAsync()` to send a request to `my.app.test`.

Observed behavior:

The `HttpClient.SendAsync()` method successfully sends the HTTP request to the endpoint.

## Next questions

- What emulator are you using?
- Which version of Visual Studio and Xamarin.Android SDK are you using?

**Comment by zd-dalibor** [comment]
@brendanzagaeski I am using emulator with Android 9.0 (API 28) x86 and Xamarin Android SDK 10.2.0.100.

Maybe I miss something. Do I need some special privileges for resolving domain names from hosts file. My app currently has INTERNET & ACCESS_NETWORK_STATE permission granted.

**Comment by zd-dalibor** [comment]
I found what is the problem **line endings** in host file. It is CLRF and should be LF.

**Comment by brendanzagaeski** [comment]
Nice find! Happy to hear you got it working!
