### ISSUE TITLE
[.NET 6] Binding projects should default enable C# 8 features

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#4657]
`Mono.Android.dll` enables some (currently experimental) features which require C#8:

https://github.com/xamarin/xamarin-android/blob/7dab4ee432dcd1e51c52dfe579023fccaf09c471/src/Mono.Android/Mono.Android.targets#L118-L119

Specifically:

  * `--lang-features=nullable-reference-types`: Nullable reference types
  * `--lang-features=default-interface-methods`: Bind Java interface default methods as C# interface default members
  * `--lang-features=nested-interface-types,`: C# interfaces can contain nested types.
  * `--lang-features=interface-constants`: C# interfaces can contain constants.

One of those also binds Java interface static methods as C#8 interface static methods.

We should enable *all* of these by default in .NET 6 projects.

**Comment by jpobst** [comment]
Default is good, but note that some of these create API breaking changes which would hit users migrating their existing bindings to .NET 5.  Each feature will need a `true`/`false` property to disable it, and will need to be documented in a migration guide.
