### ISSUE TITLE
Seems SynchronizationContext.SetSynchronizationContext is not set.

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#4666]
Looking the code, there is a property to get the context:
https://github.com/xamarin/xamarin-android/blob/d471b4a4308310afb8fa3fa1047003a7caedd57f/src/Mono.Android/Android.App/Application.cs#L29

But not set like iOS: 
https://github.com/xamarin/xamarin-macios/blob/45eb105da42d508bee63305f6c4f8703978e638d/src/UIKit/UIApplication.cs#L55

**Comment by jonpryor** [comment]
Fixed by https://github.com/xamarin/xamarin-android/pull/5243
