### ISSUE TITLE
Buttons stop responding if there is some heavy process

### ISSUE THREAD

**Issue by FoggyFinder** [xamarin/xamarin-android#4667]
### Steps to Reproduce

MCVE:

xml:

```xml
    <LinearLayout
        android:orientation="vertical"
        android:id="@+id/linearLayout1"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
```

ui:

```cs
class SomeView : LinearLayout
{
    private int _count;

    private readonly Timer timer;
    private readonly Random random = new Random();

    public const double Interval = 300.0;

    public SomeView(Context context) : base(context)
    {
        var txtView = new TextView(context);
        var btn = new Button(context) { Text = _count.ToString() };
        btn.Click += (_, __) =>
        {
            _count++;
            btn.Text = _count.ToString();
        };
        timer = new Timer(Interval);
        timer.Elapsed += (_, __) => txtView.Text = random.Next().ToString();
        timer.Start();
        var sl = new LinearLayout(context)
        {
            Orientation = Orientation.Vertical
        };
        sl.AddView(txtView);
        sl.AddView(btn);

        AddView(sl);
    }
}
```

usage:

```csharp
var linearLayout1 = FindViewById<LinearLayout>(Resource.Id.linearLayout1);
int count = 12;
for (int i = 0; i < count; i++)
{
    linearLayout1.AddView(new SomeView(ApplicationContext));
}
```

Test project is attached:
[AndoirdMCVE.zip](https://github.com/xamarin/xamarin-android/files/4606147/AndoirdMCVE.zip)

To reproduce one has simply click on different buttons.

Issue isn't totally stable: sometimes it works just fine for relatively long time sometimes it's occurs almost immediately after start. So it might required to re-run app couple of times to see this issue quickly.

### Expected Behavior

Buttons work fine.

### Actual Behavior

Button changes state to "pressed" on click but no action is performed. Refreshing of pages (or something like that) doesn't help.

![_result](https://user-images.githubusercontent.com/16510738/81507000-ce627c80-9302-11ea-9779-3c5e1df9bcf6.png)

### Version Information

```
Microsoft Visual Studio Community 2019
VisualStudio.16.Release/16.5.4+30011.22

Xamarin   16.5.000.533 (d16-5@9152e1b)
Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Xamarin Templates   16.5.49 (0904f41)
Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b
```

**_Additional info_**:

I can't see anything useful in the logs so I haven't provided it. Though sometimes there are some messages with "anim" and "AsyncOperation" tags. Not sure is it related.

**Comment by grendello** [comment]
Any long-running operation executing on the main/GUI thread of your application will block the UI from updating. This is how Android GUI (and most other non-immediate mode GUIs) work - they have an event message loop running on the main/GUI thread which needs to have a chance to process messages. Those messages may include triggering and performing animations, updating the UI state (looks, text etc). By launching several blocking operations on the same thread as your GUI, you will get either a totally unresponsive UI or, as you observed, an UI which works/blocks sometimes. The latter behavior depends on the nature of the blocking operations. In the sample you provided the 12 buttons start 12 timers which trigger at different times, every 300ms for each of them, each time doing something non-trivial on the main/GUI thread - thus saturating the event message queue without giving it much chance to process the backed-up messages. Your UI code must be limited to actually updating the UI state only, all the heavy operations must be performed on a separate thread if you want the UI to remain responsive.

I hope this explanation helped, I'm going to close the issue as it doesn't describe a bug in `Xamarin.Android`. Thanks!

**Comment by FoggyFinder** [comment]
> The latter behavior depends on the nature of the blocking operations. In the sample you provided the 12 buttons start 12 timers which trigger at different times, every 300ms for each of them, each time doing something non-trivial on the main/GUI thread - thus saturating the event message queue without giving it much chance to process the backed-up messages. 

Well, timers are started immediately and not by a button. You could remove them totally and add just single button that does nothing on click. You will see the same result after a while.

Anyway, the sample is nothing more than a sample. Of course real code wouldn't be like this.
You may notice the described behaviour even when interval is equal to 6000ms (or bigger) and when amount of controls is much smaller. Just not so often.
I.e. it is complicated to provide more or less stable reproducible sample without "abusing" of a system.

Looks like it cuts both ways:

* If I try to provide sample without those timers it might require significant time to reproduce it from your side. And then I suppose the issue will be closed as not enough detail provided (or opposite as not very specific). 

* With current sample it looks like wrong usage of timers, GUI threads etc.

Unsure what else I can do to express this issue better.

My point is: 

while I agree that it indicates that there are some issues inside of an app itself the result still looks wrong. I still think it is a bug somewhere in Xamarin.Android.

**Comment by siriak** [comment]
@grendello are there really any CPU-bound or blocking operations? From what I see, it's just simple `txtView.Text = random.Next().ToString();`. It doesn't look long-running at all.

**Comment by grendello** [comment]
@siriak that appears to be "simple" but if you consider several factors in this misguidedly simple code:  random value retrieval takes some time (depending on the source), then there's conversion of the value to the string (in addition, here is culture-specific = slower), then that string needs to be encoded from UTF16 to UTF8, marshaled to Java (all of this involves memory allocation), including several cross-runtime calls. Then Android takes over - it needs to pass the string to the control, the layout needs to be updated (string length may change, properties of the layout and the control can change too), then that needs to be rendered and displayed (parts of it take part in a separate process) and then we need to go back to the managed land - return from the Java retraces the steps, there's also marshaling involved. Then, consider that the GC may kick in in the meantime and that you have 12 timers firing every 300ms on the same thread. Fast UI updates of this sort should be done in a very careful way and definitely the bulk of the work should be done on a separate thread.

**Comment by charlesroddie** [comment]
I believe this issue is that buttons _stop_ responding if there is a heavy process, not that they are slow to respond. If they became slow to respond it could well not be a bug. But stopping responding because of heavy processes that terminate is a bug.
