### ISSUE TITLE
OnCharacteristicChanged() triggered later!!

### ISSUE THREAD

**Issue by honbaa** [xamarin/xamarin-android#4679]
### Steps to Reproduce

Our project is based on BLE connection. We use a android device to communicate with a BLE printer. Printer will do the right actions like "print data","cut paper" when the application sent bytes to it. The application will receive the "response" bytes from OnCharacteristicChanged() function. The problem is that, application send "print","print","cut" in sequence,  but the OnCharacteristicChanged() will not triggered when the first "print" sent, After the sencod "print" sent, OnCharacteristicChanged() triggered twice!!!!

1. Write values using SetValue()
2. Wait for the OnCharacteristicChanged() triggered to get response from printer.

### Expected Behavior

OnCharacteristicChanged() triggered and application got response ~

### Actual Behavior

OnCharacteristicChanged() not triggered until next SetValue() success. 

### Version Information

Android OS version: Greater than 5.0, android 8.1 repoduced more.

**Comment by radekdoulik** [comment]
This might be similar issue as here https://github.com/xamarin/xamarin-android/issues/1843#issuecomment-398882733? In case it is different issue, please provide a sample project which reproduces the issue.
