### ISSUE TITLE
OnCharacteristicWrite() not triggered even if connection state is connected!!

### ISSUE THREAD

**Issue by honbaa** [xamarin/xamarin-android#4680]
Our project is based on BLE connection. We use a android device to communicate with a BLE printer. Printer will do the right actions like "print data","cut paper" when the application sent bytes to it. The application will use SetValue() method to send data. And In the OnCharacteristicWrite() function, i write a debug log to essure the data has been sent ok. But occasionally, the callback will not be triggered!! I don't know why this happen because the connection state is connected!!

### Steps to Reproduce

1.  Write values using SetValue() , maybe 10 times
2. OnCharacteristicWrite will triggered 10 times
 

### Expected Behavior
OnCharacteristicWrite will triggered 10 times
### Actual Behavior
OnCharacteristicWrite will triggered 8 times, the printer not received the complete data.
### Version Information
Android OS version: Greater than 5.0, android 8.1 repoduced more.

**Comment by radekdoulik** [comment]
This might be similar issue as here https://github.com/xamarin/xamarin-android/issues/1843#issuecomment-398882733? In case it is different issue, please provide a sample project which reproduces the issue.
