### ISSUE TITLE
Replace reflection usage when preparing linker pipeline

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#4709]
Context: https://github.com/xamarin/xamarin-android/pull/4669

We are temporarily using reflection to modify pipeline in `SetupStep`. This should be replaced by using cmd line arguments (`--custom-step`) and relevant msbuild parts or by using Pipeline API.

It is not clear yet whether the Pipeline API would be public. I would like to wait before redoing the temporary solution until later when it will be more clear whether we might need pipeline steps removal/replacement or not.

**Comment by jonathanpeppers** [comment]
I think this was fixed in: https://github.com/xamarin/xamarin-android/pull/5748
