### ISSUE TITLE
HttpRequestException running UITest on Android

### ISSUE THREAD

**Issue by trampster** [xamarin/xamarin-android#4721]
### Steps to Reproduce

1. Make a Xamarin.Forms project with Android
2. Make a UITest project
3. Try to run against attached android device

NOTE: I have the internet permission enabled and the shared mono runtime disabled as described here: https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/preparing-for-upload-android

### Expected Behavior
Tests work

### Actual Behavior
Message: 
    System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ----> System.Net.WebException : The underlying connection was closed: The connection was closed unexpectedly.
  Stack Trace: 
    HttpClient.SendData(String endpoint, String method, HttpContent content, ExceptionPolicy exceptionPolicy, Nullable`1 timeOut)
    HttpClient.Post(String endpoint, String arguments, ExceptionPolicy exceptionPolicy, Nullable`1 timeOut)
    HttpApplicationStarter.Execute(String intentJson)
    AndroidAppLifeCycle.LaunchApp(String appPackageName, ApkFile testServerApkFile, Int32 testServerPort)
    AndroidApp.ctor(IAndroidAppConfiguration appConfiguration, IExecutor executor)
    AndroidAppConfigurator.StartApp(AppDataMode appDataMode)
    AppInitializer.StartApp(Platform platform)
    Tests.BeforeEachTest()
    --WebException
    HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
    HttpClientHandler.GetResponseCallback(IAsyncResult ar)

### Version Information
Microsoft Visual Studio Professional 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.5.514 (c4f36a9)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20181.6+85af456066acd4e76d2bc7821b44a325e46f2fca
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.533 (d16-5@9152e1b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.49 (0904f41)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.16.0.13 (b75deaf)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

Googling this issue show other people are having it and that is unsolved for many:
https://forums.xamarin.com/discussion/80997/system-net-http-httprequestexception-exception-will-running-the-ui-test-on-physical-device

https://stackoverflow.com/questions/40188774/system-net-http-httprequestexception-exception-will-running-th-xamarin-ui-test-o

**Comment by Eltee-Taiwo** [comment]
Why was this closed? Did you ever figure out the cause?

**Comment by GertjanBrouwer** [comment]
This issue still exists
