### ISSUE TITLE
[Flags] attribute missing in Android.Content.PM.ForegroundService enum

### ISSUE THREAD

**Issue by johannes-fetz** [xamarin/xamarin-android#4752]
### Steps to Reproduce

According to Android developer documentation available here:

https://developer.android.com/preview/privacy/foreground-service-types

I can use combine multiple service type:

```
<manifest>
    ...
    <service ...
        android:foregroundServiceType="location|camera|microphone" />
</manifest>
```

### Expected Behavior

I can programmaticaly set ForegroundServiceType in my service:

```
    [Service(ForegroundServiceType = ForegroundService.TypeDataSync |ForegroundService.TypeLocation)] 
    internal class TestService : Service
```

### Actual Behavior

It doesn't work because ForegroundService doesn't have [Flags] attribute although member values clearly suggest that it's a bitfield:

```
namespace Android.Content.PM
{
    public enum ForegroundService
    {
        TypeManifest = -1,
        TypeNone = 0,
        TypeDataSync = 1,
        TypeMediaPlayback = 2,
        TypePhoneCall = 4,
        TypeLocation = 8,
        TypeConnectedDevice = 16,
        TypeMediaProjection = 32
    }
}
```

and **also some values are missing like Camera access**.

### Version Information

Microsoft Visual Studio Professional 2019
Version 16.6.1
VisualStudio.16.Release/16.6.1+30128.74
Microsoft .NET Framework
Version 4.8.03752

Xamarin   16.6.000.1061 (d16-6@8e68aa8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jpobst** [comment]
Can you explain what exactly doesn't work? While it looks like it should have the `[Flags]` attribute I don't think having it would change anything.

**Comment by johannes-fetz** [comment]
I'm sorry, I forget to add logs:

3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004: System.ArgumentException: Unsupported ForegroundServiceType value '9'.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004: Parameter name: value
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Manifest.ManifestDocumentElement`1.ToString(ForegroundService value)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Manifest.ManifestDocumentElement`1.<>c.<.cctor>b__26_7(Object value, ICustomAttributeProvider p, IAssemblyResolver r, Int32 v)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Manifest.ManifestDocumentElement`1.ToAttributeValue(String name, T value, ICustomAttributeProvider provider, IAssemblyResolver resolver, Int32 targetSdkVersion)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Manifest.ManifestDocumentElement`1.ToAttribute(String name, T value, String packageName, ICustomAttributeProvider provider, IAssemblyResolver resolver, Int32 targetSdkVersion)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Manifest.ManifestDocumentElement`1.<>c__DisplayClass8_0.<ToElement>b__1(String e)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Manifest.ManifestDocumentElement`1.ToElement(T value, ICollection`1 specified, String packageName, ICustomAttributeProvider provider, IAssemblyResolver resolver, Int32 targetSdkVersion)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Tasks.ManifestDocument.<GetGenerator>b__69_3(ServiceAttribute x)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Tasks.ManifestDocument.ToElement[TAttribute](TypeDefinition type, String name, Func`2 parser, Func`2 toElement, Action`2 update)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Tasks.ManifestDocument.<GetGenerator>b__69_0(TypeDefinition t, String name, Int32 v)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Tasks.ManifestDocument.Merge(TaskLoggingHelper log, TypeDefinitionCache cache, List`1 subclasses, String applicationClass, Boolean embed, String bundledWearApplicationName, IEnumerable`1 mergedManifestDocuments)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2004,3): error XAGJS7004:    at Xamarin.Android.Tasks.AndroidTask.Execute()

**Comment by johannes-fetz** [comment]
In my case I need both TypeDataSync and TypeLocation

**Comment by jpobst** [comment]
Looks like we need to update [this bit of code](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocumentElement.cs#L369), I'll write up a PR for that.  In the meantime you should be able to manually add the needed `<service>` element to your `AndroidManifest.xml`.

**Comment by johannes-fetz** [comment]
Sure, thank you for your responsiveness :)

**Comment by brendanzagaeski** [comment]
Thanks again for submitting this issue!

_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.4.0.0.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
