### ISSUE TITLE
"Could not compile native assembly file: typemaps.x86.s" after incremental build within Visual Studio

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#4790]
### Steps to reproduce

1. Create a new **Mobile App (Xamarin.Forms) > Master-Detail** project that targets Android.
2. Set the active solution configuration to Release.
3. Build the project via **Build > Build Solution**.
4. Change **Supported architectures** to add **x86** under the **Advanced** button in the **Android Options** section of the Visual Studio project property pages.
5. Build the project again via **Build > Build Solution**.

Note: The project must start with empty _obj_ and _bin_ directories at step 1 to see the problem.

So far I have not found a way to reproduce this in command line builds. Replacing steps 3 and 5 with `msbuild -restore -p:Configuration=Release` results in a successful build at step 5, even if I set the `MSBUILDNOINPROCNODE` environment variable to `1`.

### Workaround

Unload and reload the project in the Solution Explorer after step 4.

### Expected behavior

The project builds successfully at step 5.

### Actual behavior

The build fails at step 5:

```
1>  [i686-linux-android-as.EXE stderr] Assembler messages:
1>  [i686-linux-android-as.EXE stderr] Error: can't open typemaps.x86.s for reading: No such file or directory
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2245,3): error XA3006: Could not compile native assembly file: typemaps.x86.s
```

Indeed, the file _obj\Release\90\android\typemaps.x86.s_ does not exist.

Repeating step 5 does not solve the issue, but unloading and reloading the project or cleaning and building the project does.

Diagnostic MSBuild output for a command line build at step 5 and a build within Visual Studio at step 5: [logs.zip](https://github.com/xamarin/xamarin-android/files/4750134/logs.zip)

### Version information

- Visual Studio 2019 version 16.7 Int Preview
- Xamarin.Android SDK   10.3.99.259 (d16-7/feabf52)
  -  Mono: 075c3f0
  -  Java.Interop: xamarin/java.interop/d16-7@d6024f1
  -  ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
  -  SQLite: xamarin/sqlite/3.31.1@49232bc
  -  Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@23c4fe0

### Log file

Diagnostic MSBuild output for a command line build at step 5 and a build within Visual Studio at step 5: [logs.zip](https://github.com/xamarin/xamarin-android/files/4750134/logs.zip)

**Comment by jonathanpeppers** [comment]
@brendanzagaeski is this only happening in 16.7? 16.6 seems like it works.

I was trying to reproduce this in 16.7, but the `Project Options` dialog won't open for me...

It seems like this just goes forever, maybe it is blocking it?

![image](https://user-images.githubusercontent.com/840039/84205263-5d81c200-aa72-11ea-87bc-f69fd80cbd02.png)

I have:
```
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
```

**Comment by brendanzagaeski** [comment]
Interesting. Yeah, I can reproduce on Visual Studio 2019 version 16.6.1 as well.

I didn't notice it yesterday, but after taking a fresh look at the build logs today, I noticed something that might be a good clue.

In _vs.txt_:

```
Skipping target "_GenerateJavaStubs" because all output files are up-to-date with respect to the input files.
```

Compared to _cmdline.txt_:

```
Building target "_GenerateJavaStubs" completely.
Input file "obj\Release\90\android\assets\FormsViewGroup.dll" is newer than output file "obj\Release\90\stamp\_GenerateJavaStubs.stamp".
```

(Maybe the fact that _FormsViewGroup.dll_ gets updated during command line incremental builds where only `$(AndroidSupportedAbis)` is changed is another interesting issue of its own.)

### Experiment

`_GenerateJavaStubs` currently has:

```xml
<Target Name="_GenerateJavaStubs"
    DependsOnTargets="$(_GenerateJavaStubsDependsOnTargets);$(BeforeGenerateAndroidManifest)"
    Inputs="$(MSBuildAllProjects);@(_ResolvedUserMonoAndroidAssemblies);$(_AndroidManifestAbs);$(_AndroidBuildPropertiesCache)"
    Outputs="$(_AndroidStampDirectory)_GenerateJavaStubs.stamp">
```

I tried overriding the `_CreatePropertiesCache` target with a version where I added the following line to the `<ItemGroup/>`:

```xml
<_PropertyCacheItems Include="AndroidSupportedAbis=$(AndroidSupportedAbis)" />
```

This did indeed get `_GenerateJavaStubs` to run:

```
Target "_GenerateJavaStubs: (TargetId:259)" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\16.6Ent\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets" from project "C:\Temp\MobileAppXamarinForms1\MobileAppXamarinForms1\MobileAppXamarinForms1.Android\MobileAppXamarinForms1.Android.csproj" (target "_GeneratePackageManagerJava" depends on it):
Building target "_GenerateJavaStubs" completely.
Output file "obj\Release\90\stamp\_GenerateJavaStubs.stamp" does not exist.
```

So it did stop the problem, but maybe adding `$(AndroidSupportedAbis)` to the build properties cache is overkill? Maybe it's more interesting that `$(MSBuildAllProjects)` is not providing _MobileAppXamarinForms1.Android.csproj_ in the list of `Inputs` for the skipped `_GenerateJavaStubs` target in _vs.txt_?

**Comment by brendanzagaeski** [comment]
Hmmm. I think the command line build is behaving correctly. _FormsViewGroup.dll_ changes because the managed linker runs. And the managed linker runs because _MobileAppXamarinForms1.Android.dll_ gets updated by `CoreCompile`. In contrast, the `CoreCompile` target is skipped when building in Visual Studio.

_vs.txt_:

```
Target "CoreCompile: (TargetId:120)" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets" from project "C:\Temp\MobileAppXamarinForms1\MobileAppXamarinForms1\MobileAppXamarinForms1.Android\MobileAppXamarinForms1.Android.csproj" (target "Compile" depends on it):
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
```

Compared to _cmdline.txt_:

```
Target "CoreCompile: (TargetId:217)" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets" from project "C:\Temp\MobileAppXamarinForms1\MobileAppXamarinForms1\MobileAppXamarinForms1.Android\MobileAppXamarinForms1.Android.csproj" (target "Compile" depends on it):
Building target "CoreCompile" completely.
Input file "C:\Temp\MobileAppXamarinForms1\MobileAppXamarinForms1\MobileAppXamarinForms1.Android\MobileAppXamarinForms1.Android.csproj" is newer than output file "obj\Release\90\MobileAppXamarinForms1.Android.pdb".
```

This is starting to look like it might be an edge case bug in the IDE. If I change the general C# **Build > Advanced > Check for arithmetic overflow** setting between the two builds instead of **Supported architectures**, I can still get the problem where `CoreCompile` does not run even though the timestamp of _MobileAppXamarinForms1.Android.csproj_ has been updated.

**Comment by brendanzagaeski** [comment]
Another curious result is that it seems I can avoid the issue if I add the following steps at the beginning and complete all the steps quickly:

1a. Create a new **Mobile App (Xamarin.Forms) > Master-Detail** project that targets Android.
1b. Quit Visual Studio.
1c. Delete all the _bin_ and _obj_ directories and the hidden _.vs_ directory.
1d. Reopen the solution.

It's a bit tricky to test, but it seems that in this scenario, if I don't complete the steps quickly and I instead let Visual Studio sit for a few minutes after the first build at step 3, I get the problem.

Maybe this issue won't affect the new project system that Xamarin.Android will be using in .NET 6, so it might be OK to add `$(AndroidSupportedAbis)` to the build properties cache as a workaround for the legacy targets?

**Comment by brendanzagaeski** [comment]
In case anyone might be curious, for the problem with `$(MSBuildAllProjects)`, I investigated a bit more and found that it is not specific to Xamarin projects. It affects .NET Framework console app projects too. I submitted a feedback item for it on Visual Studio Developer Community: <https://developercommunity.visualstudio.com/content/problem/1074509/incremental-builds-within-visual-studio-can-be-inc.html>.

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 4. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
