### ISSUE TITLE
HttpHandler ServerCertificateCustomValidationCallback  fires only once

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-android#4797]
### Steps to Reproduce

1. Xamarin forms application
2. Create an HttpClient
3. Attach an Httpclient handler

### Expected Behavior
I expect the ServerCertificateCustomValidationCallback to fire all the time I make an https call to validate the certificate

### Actual Behavior
it only fires once!.

### Version Information
Xamarin forms 4.6.x
Android  7 - 10

Question?
Is this the correct implementation?
how many times should it fire

I do not think I should be creating an httpclient for each call?

Missing the obvious?
your suggestion and  prompt reply would be greatly appreaciated

```
      private static HttpClient client;

       var handler = new HttpClientHandler
            {
                SslProtocols = SslProtocols.Tls12,
                ServerCertificateCustomValidationCallback = 
                HandlerServerCertificateCustomValidationCallback
            };
            client = new HttpClient(handler);`

      public bool HandlerServerCertificateCustomValidationCallback(
        object sender,  
        X509Certificate certificate, 
        X509Chain chain, 
        SslPolicyErrors sslPolicyErrors)
        {
                Debugger.Break();
         }
```

**Comment by developer9969** [comment]
@jpobst  hi there , Thank you for your reply! I am not calling a different url each time , but for some reasons in my head I thought it would perform validation each time.

The problem is/was  I could not find any documentation about this and all the examples out there use the outdated ServicePointManager.

So the expected behavior is:

1.  Launch the Xamarin app and CustomValidation fires as soon as I make the first call.
2.  Any subsequent call will not fire any validation against the same domain.
3.  Any malicious attempt "man in the middle" would use a different url and therefore trigger the validation 

Is this correct? 

I know is very simplistic but would help me understand what the behavior is.
Hope makes sense

many thanks

**Comment by jpobst** [comment]
Correct, any call to the same domain will use the same certificate, so there is no reason to re-check it.

A MITM attack would generally be done on the same domain.  Imagine you connect to your coffee shop's compromised wifi and navigate to `http://google.com` (not `https`).  The attacker would intercept your request and return its webpage rather than Google's.

With SSL, what (roughly) happen is:
* You retrieve the certificate for `google.com`.
* You verify it is the real certificate by ensuring it is signed by a certificate authority (CA) you trust.
* You use the certificate public key to encrypt a request to `https://google.com`
* Google decrypts your request using the certificate private key and establishes the connection.

If an attacker intercepts your data intended for that domain, they will not have the real certificate's private key and will not be able negotiate a connection with you.

Thus what `HandlerServerCertificateCustomValidationCallback` is doing is determining if you 'trust' the certificate or not.  Generally you would not touch this and it will ensure the cert if from a CA you trust.  However for a self-signed cert this would fail, so you are able to examine the cert yourself and determine if you trust it.

So as long as the certificate doesn't change, there is no reason to determine if you 'trust' it more than once.

**Comment by developer9969** [comment]
Jpobst thank you so much for the explanation. Reading about this and trying to understand what actually needs to be done in the validationcallback and if required to validate a certificate /

Reading what you said

> _Thus what HandlerServerCertificateCustomValidationCallback is doing is determining if you 'trust' the certificate or not. **Generally you would not touch this** and it will ensure the cert if from a CA you trust._

Not sure I understand the above, especially "Generally you would not touch this",  also there is no documentation that I can find on how to validate the certificate.  I have done the following :

`
public bool HandlerServerCertificateCustomValidationCallback(object sender,
		 X509Certificate certificate, 
		 X509Chain chain, 
		 SslPolicyErrors sslPolicyErrors)
		{
			if (certificate == null || chain == null) return false;
			if (sslPolicyErrors != SslPolicyErrors.None) return false;

			var publicKey = "whateverTheKey";
			var keyMatches= string.Compare(publicKey, certificate.GetPublicKeyString(), StringComparison.OrdinalIgnoreCase) == 0;

		   return sslPolicyErrors == SslPolicyErrors.None && keyMatches;
		}`


is the above by and large how you perform certificate validation?

Many thanks again for your help

**Comment by jpobst** [comment]
I guess the first question is "why are you trying to override certificate validation"?  Under normal circumstances you should not touch it and certificate validation will be done automatically.  The code that does this is written by people way more familiar with security than you or I.

**Comment by developer9969** [comment]
> why are you trying to override certificate validation"? 

When looking /learning about how to avoid  "a man in the middle attack" in xamarin , all the documentation I found was about  using ServicePointManager and doing something like i did but now using the new .net core version of it.

If what I am doing is totally redundant or not  good I am open to suggestions and scrap the code or be pointed at documentation.
So how do you trust a certificate in xamarin forms?

again thanks for your quick response

**Comment by jpobst** [comment]
The only reason I can think of for doing custom certificate validation is if you are trying to use a self-signed certificate for internal testing.  If you are using a real public certificate from a Certificate Authority (which you absolutely should be for Production) you do not want to touch this.  It is all handled automatically for you.

**Comment by developer9969** [comment]
that is brilliant news. I definetely do not want to touch it!!. where can I read how it handles all for me. are you saying no comparison of  keys - etc..  where is the magic

**Comment by jpobst** [comment]
Think of it like typing `https://google.com` into a browser.  Google's certificate is downloaded and checked by your browser before it lets you connect to the site.  At no point do you need to look up Google's public key and do the comparison yourself.  All SSL/TLS libraries are the same in that they handle it for you.

I don't really know where to point you to, here is the source of `HttpClient`, but it's likely to be deep elsewhere in that repository, or perhaps even handled by the underlying operating system.

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs

**Comment by developer9969** [comment]
big thank you for your time.
So no need for Certificate pinning as security measure then..
