### ISSUE TITLE
Is there an equivalent method to Android

### ISSUE THREAD

**Issue by qcjxberin** [xamarin/xamarin-android#4803]
buildTypes {
        release {
            minifyEnabled true
            buildConfigField "String", "BUILD_COUNTRY", "\"CHINA\""//国内
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }//debug 默认不开混淆
        debug {
            minifyEnabled false
            buildConfigField "String", "BUILD_COUNTRY", "\"CHINA\""
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

**Comment by moljac** [comment]
Hi @qcjxberin 

This is gradle file and Xamarin.Android uses MsBuild to build projects. We'll need more info - which step/task in gradle are you asking about?

`minifyEnable`?
`buildConfigField `?
anything else?

**Comment by qcjxberin** [comment]
Others are temporarily unnecessary.

**Comment by jpobst** [comment]
This is likely obsolete.
