### ISSUE TITLE
Starting in Xamarin.Android 10.3, "System.MemberAccessException: Cannot create an instance of ... `1[T]" in Debug configuration when using certain APIs that have both generic and non-generic versions

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#4809]
Context: https://github.com/xamarin/xamarin-android/issues/4596
Context: https://github.com/xamarin/xamarin-android/issues/4660

For this particular test case, the issue only occurs when using the shared runtime or when the managed linker is disabled.

### Partial workaround

1. Disable **Use Shared Runtime** under the **Android Options** section of the Visual Studio project property pages for the project.
2. Set the **Linking** setting to **Sdk Assemblies Only**.
3. If deploying to an emulator, click the **Advanced** button and add the appropriate **x86** or **x86_64** item under **Supported architectures**.

### Steps to reproduce

1. Download and unzip the attached test case.
2. Ensure that a hardware device is attached and that `adb` is running.
3. ```
   msbuild -restore -p:Configuration=Debug -t:Install AndroidApp1\AndroidApp1.csproj
   ```
4. Launch the app by tapping the app icon on the target device.

Test case: [ArrayAdapterApp1.zip](https://github.com/xamarin/xamarin-android/files/4767814/ArrayAdapterApp1.zip)

### Expected behavior

When built and deployed with Xamarin.Android 10.2, the application launches successfully and displays _Hello World!_ in the center of the view.

### Actual behavior

When built and deployed with Xamarin.Android 10.3, the application exits during launch:

```
System.MemberAccessException: Cannot create an instance of Android.Widget.ArrayAdapter`1[T] because Type.ContainsGenericParameters is true.
  at System.Reflection.RuntimeConstructorInfo.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in <d772a4bbe86c4dc5b425d8ca91786b91>:0 
  at System.Reflection.RuntimeConstructorInfo.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <d772a4bbe86c4dc5b425d8ca91786b91>:0 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <d772a4bbe86c4dc5b425d8ca91786b91>:0 
  at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x0001b] in <43cddc76fe22432dbdbcea2397b6fcd7>:0 
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <43cddc76fe22432dbdbcea2397b6fcd7>:0 
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x00023] in <43cddc76fe22432dbdbcea2397b6fcd7>:0 
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <43cddc76fe22432dbdbcea2397b6fcd7>:0 
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <43cddc76fe22432dbdbcea2397b6fcd7>:0 
  at Android.Widget.ArrayAdapter.CreateFromResource (Android.Content.Context context, System.Int32 textArrayResId, System.Int32 textViewResId) [0x0006d] in <43cddc76fe22432dbdbcea2397b6fcd7>:0 
  at AndroidApp1.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00031] in <51ce4ed05744482eb8a8079a399a17d2>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <43cddc76fe22432dbdbcea2397b6fcd7>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
```

### Version information

- Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
  - Mono: 165f4b0
  - Java.Interop: xamarin/java.interop/d16-6@2cab35c

The issue also occurs with Visual Studio 2019 version 16.7 Preview 2:

- Xamarin.Android SDK   10.3.99.259 (d16-7/feabf52)
  - Mono: 075c3f0
  - Java.Interop: xamarin/java.interop/d16-7@d6024f1

**Comment by brendanzagaeski** [comment]
I have only been able to reproduce this in the Debug configuration (with the debug _libmonodroid.so_), so it seems the fixes for Release configuration builds (with the release _libmonodroid.so_) are still verified.

**Comment by grendello** [comment]
[log-new-fastdev.txt](https://github.com/xamarin/xamarin-android/files/4791065/log-new-fastdev.txt)
[log-regular-fastdev.txt](https://github.com/xamarin/xamarin-android/files/4791067/log-regular-fastdev.txt)

I can't reproduce the issue with `XA/master` :( Attached you can find logcats from two cold-start (no previous version of the application on device exists, no shared runtime installed) sessions for both the "old" and the "new" (`Dexes`) fastdev deployment models (the former puts typemaps in `libxamarin-app.so` the latter in `*.typemap` files uploaded to the override directory). The app was tested on Pixel 3 XL running Android 10.

**Comment by brendanzagaeski** [comment]
Ah, yep. I can't reproduce either using a locally built `v9.0/Mono.Android.dll` from master, but a workaround is to replace the assembly with the version from CI.

Steps I followed:

1. Open the latest status on <https://github.com/xamarin/xamarin-android/commits/>.

2. Open the Details for the JENKINS-SIGN step.

3. Download the `.vsix`.

4. Extract `v9.0\Mono.Android.dll`:

   ```pwsh
   & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Xamarin.VisualStudio\7-Zip\7z.exe" x -r C:\Temp\Xamarin.Android.Sdk-10.4.100.108.vsix '$ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll'
   ```

5. Copy it into the local build:

   ```pwsh
   Copy-Item '$ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll' C:\Source\xamarin-android\bin\Debug\lib\xamarin.android\xbuild-frameworks\MonoAndroid\v9.0\Mono.Android.dll
   ```

6. Rebuild and redeploy the app:

   ```pwsh
   & ".\bin\Debug\bin\xabuild.exe" -restore "-t:Clean,Install" -p:Configuration=Debug -p:AndroidUseSharedRuntime=false -p:EmbedAssembliesIntoApk=true C:\Temp\ArrayAdapterApp1\AndroidApp1\AndroidApp1.csproj
   ```

   (At least one version of the issue occurs without the shared runtime, so I used that approach for this test.)

**Comment by grendello** [comment]
@brendanzagaeski It appears you don't need to get `Mono.Android.dll` from the vsix to reproduce. What you need is a local *Release* Xamarin.Android build (i.e. a  `make CONFIGURATION=Release` one) and *only* the `v9.0` version of the assembly cause the exception to be thrown (I tested framework versions down to `v7.1`, the sample app fails to build for anything older)

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 4. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
