### ISSUE TITLE
[Bug] Network issue accessing Azure IOT Hub

### ISSUE THREAD

**Issue by hbraasch** [xamarin/xamarin-android#4837]
### Description
The Android project generated using the latest stock Mobile App (Xamarin Forms) template, is unable to read D2C messages posted to an Azure IOT Hub. The IOS and UWP projects created during the same process both works fine.
 
All three apps uses the same shared project, which has a function that tries to reads messages posted by IOT devices to IOT Hub. It uses the latest Azure.Messaging.EventHubs.Consumer library and the Android solution hangs at the call (sample project demonstrating problem is supplied): 

var iterator = consumer.ReadEventsAsync(new ReadEventOptions { MaximumWaitTime = TimeSpan.FromMilliseconds(60000) }).GetAsyncEnumerator();

while (await iterator.MoveNextAsync()) // Android hangs here, others carry on fine and read events

### Steps to Reproduce

A simple sample project is supplied <<https://github.com/hbraasch/IotHubD2CReadTester>>. To recreate, it consists of...

(Step 1) Generate a clean Mobile App (Xamarin Forms) solution inside Visual Studio 2019 (I'm using Microsoft Visual Studio Community 2019 Version 16.6.2)
(Step 2) Update all Nugets, and add nuget <<Azure.Messaging.EventHubs>> to all projects

(Step 3) Add the following code to the shared project App class 

	public App()
	{
		InitializeComponent();

		MainPage = new MainPage();

		Task.Factory.StartNew(async () => {
			var cts = new CancellationTokenSource();
			await ReceiveMessagesFromDeviceAsync(cts.Token);
		});
	}

	public static async Task ReceiveMessagesFromDeviceAsync(CancellationToken cancellationToken)
	{
		string connectionString = "Removed: Get this from your sample IOT Hub endpoint";
		private const string EventHubName = "Removed: Get this from your sample IOT Hub endpoint";

		EventHubConsumerClient consumer = new EventHubConsumerClient(EventHubConsumerClient.DefaultConsumerGroupName, connectionString, EventHubName);

		Debug.WriteLine("Listening for messages on all partitions");

		try
		{

			var iterator = consumer.ReadEventsAsync(new ReadEventOptions { MaximumWaitTime = TimeSpan.FromMilliseconds(60000) }).GetAsyncEnumerator();

			while (await iterator.MoveNextAsync())	// Andoid hangs here
			{
				var partitionEvent = iterator.Current;

				Debug.WriteLine("Message received on partition {0}:", partitionEvent.Partition.PartitionId);

			}
		}

		catch (Exception ex)
		{
			Debug.WriteLine(ex.Message);
		}
	}
In the sample code, please place an applicable IOT 'HubName' and 'ConnectionString' in the relevant constant values

See the sample project supplied for a complete working solution. 'ReceiveMessagesFromDeviceAsync' is a stock version of an IOT Hub D2C read based on a sample from https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample05_ReadEvents.cs, modified to run under C#7 using this example https://github.com/Azure/azure-sdk-for-net/issues/9853

(Step 4) Start some IOT device that publishes telemetry to your IOT hub
(Step 5) Build and run e.g. the UWP app, see that it receives messages
(Step 6) Build and run the Android app, see that it DOES NOT receive any messages

### Expected Behavior
The Android app should receive messages (displayed in the Output screen), similar to the IOS and UWP app
### Actual Behavior
The android app waits forever at the 'while (await iterator.MoveNextAsync())' instruction. There are no error/exceptions displayed in output trace
### Basic Information

- Version with issue:
See sample app supplied
- Last known good version: N/A
- IDE: Visual Studio 2019 (I'm using Microsoft Visual Studio Community 2019 Version 16.6.2)
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 
    Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3 
  - UWP:   
- Android Support Library Version: N/A
- Nuget Packages: Azure.Messaging.EventHubs 5.1.0
- Affected Devices: None

### Screenshots

N/A

### Reproduction Link

See https://github.com/hbraasch/IotHubD2CReadTester

### Workaround

None

**Comment by grendello** [comment]
@hbraasch Can you attach a detailed logcat output of the failure, from the start of the app till some one minute after it hangs? Please issue these commands from command line before starting the app:

```shell
> adb logcat -G 128M
> adb shell setprop debug.mono.log default,assembly,timing=bare
> adb logcat -c
# Start the app here and wait till it hangs + 1 minute
> adb logcat -d > log.txt
```

After that, please attach the resulting `log.txt` file here, thanks!

**Comment by hbraasch** [comment]
[log.txt](https://github.com/xamarin/xamarin-android/files/4816928/log.txt)

Requested log file attached.
Thanks for looking into the problem!
A small thing, when I said "hangs", I meant just waiting indefinitely at the async call...
Regards

**Comment by grendello** [comment]
@hbraasch thank you for the log! Unfortunately, it didn't reveal what I hoped it would as there are no network errors reported by our side. However, I noticed there are a lot of network errors from Android components - would you be able to test your app on a different device or emulator? Currently, I don't see any Xamarin.Android issues here and I'm inclined to ask you to open an issue with Azure SDK since the failure to connect happens in the SDK code. I looked (very) briefly at their code and it might also be an issue with the device configuration - do you use (or perhaps should you use?) any proxy? The connection code also appears to be using SSL for connection, perhaps there are issues validating the certificate? In the log you provided I didn't see any diagnostic messages from the Azure SDK - would you be able to enable them and make them show up in logcat? That would perhaps offer further clues as to the nature of the problem.

**Comment by hbraasch** [comment]
[log.txt](https://github.com/xamarin/xamarin-android/files/4822348/log.txt)

@grendello thanks for the feedback.
This time I attached a log running from a physical phone, a Samsung Note9 running fully updated Android10. Internet connection was with 4G (therefore no proxy involved).

I need to mention that this code worked for me before on Android. I noticed the problem started a  few months ago but temporarily bypassed it using direct method polling. I'm only now addressing the issue.

I also tried it on a different Android emulation (Android 10.0, api 29), exact same problem. So I get the impression my sample project works fine on your side?

I tried to activate logs on Azure but was unfortunately unsuccessful (not really a Azure power user :-(). Do you maybe you have a recipe or a link you can refer me to?

Thanks again for your help.

Regards

**Comment by hbraasch** [comment]
@grendello, were you able to duplicate the problem using my sample project?

**Comment by grendello** [comment]
@hbraasch I'm sorry, but I haven't gotten to implementing your instructions yet. I'll try to do it this week.

**Comment by grendello** [comment]
@hbraasch looking at the 2nd log you provided, I still don't see any clue which would indicate in any way what's going wrong. I don't see any Xamarin.Android (or Mono) errors at all. Could you, please, open a parallel ticket with Azure in order for the Azure IOT team to look at the issue from their side?

**Comment by grendello** [comment]
I created an IOT Hub as well as a simulated Chiller truck device and I do see the messages coming through to my test device using your sample app without any modifications except for the connection bits. Test device was Pixel 3 XL running up-to-date Android 10:

```
07-06 18:13:01.489 20929 20956 I mono-stdout: Listening for messages on all partitions
07-06 18:13:02.715 20929 20964 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:02.716 20929 20964 I mono-stdout: {"temperature":76.6329127819663,"temperature_unit":"F","humidity":73.0725036284758,"humidity_unit":"%","pressure":149.053152368429,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:02.716 20929 20964 I mono-stdout: Application properties (set by device):
07-06 18:13:02.716 20929 20964 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:02.717 20929 20964 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:04:24.9152300Z
07-06 18:13:02.717 20929 20964 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:04:24+00:00
07-06 18:13:02.717 20929 20964 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:02.717 20929 20964 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:02.717 20929 20964 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:02.717 20929 20964 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:02.717 20929 20964 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:02.717 20929 20964 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:04:25
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:02.722 20929 20964 I mono-stdout: 	content-type: application/json
07-06 18:13:02.722 20929 20964 I mono-stdout: 	content-encoding: utf-8
07-06 18:13:02.722 20929 20964 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:02.722 20929 20964 I mono-stdout: {"temperature":74.7978420583754,"temperature_unit":"F","humidity":69.4568439838276,"humidity_unit":"%","pressure":156.416353244063,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:02.722 20929 20964 I mono-stdout: Application properties (set by device):
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:05:25.4113206Z
07-06 18:13:02.722 20929 20964 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:05:25+00:00
07-06 18:13:02.722 20929 20964 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:02.722 20929 20964 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:02.722 20929 20964 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:05:25
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:02.722 20929 20964 I mono-stdout: 	content-type: application/json
07-06 18:13:02.722 20929 20964 I mono-stdout: 	content-encoding: utf-8
07-06 18:13:02.722 20929 20964 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:02.722 20929 20964 I mono-stdout: {"temperature":75.6906121617372,"temperature_unit":"F","humidity":72.6065809736525,"humidity_unit":"%","pressure":147.777231350903,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:02.722 20929 20964 I mono-stdout: Application properties (set by device):
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:06:25.4266749Z
07-06 18:13:02.722 20929 20964 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:06:25+00:00
07-06 18:13:02.722 20929 20964 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:02.722 20929 20964 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:02.722 20929 20964 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:06:25
07-06 18:13:02.722 20929 20964 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:02.722 20929 20964 I mono-stdout: 	content-type: application/json
07-06 18:13:02.723 20929 20964 I mono-stdout: 	content-encoding: utf-8
07-06 18:13:02.723 20929 20964 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:02.723 20929 20964 I mono-stdout: {"temperature":71.6603005656089,"temperature_unit":"F","humidity":66.6811959609302,"humidity_unit":"%","pressure":136.701103854785,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:02.723 20929 20964 I mono-stdout: Application properties (set by device):
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:07:25.4439713Z
07-06 18:13:02.723 20929 20964 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:07:25+00:00
07-06 18:13:02.723 20929 20964 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:02.723 20929 20964 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:02.723 20929 20964 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:07:25
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:02.723 20929 20964 I mono-stdout: 	content-type: application/json
07-06 18:13:02.723 20929 20964 I mono-stdout: 	content-encoding: utf-8
07-06 18:13:02.723 20929 20964 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:02.723 20929 20964 I mono-stdout: {"temperature":76.9682612308386,"temperature_unit":"F","humidity":72.956402201418,"humidity_unit":"%","pressure":152.707158414511,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:02.723 20929 20964 I mono-stdout: Application properties (set by device):
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:08:26.4593793Z
07-06 18:13:02.723 20929 20964 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:08:26+00:00
07-06 18:13:02.723 20929 20964 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:02.723 20929 20964 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:02.723 20929 20964 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:08:26
07-06 18:13:02.723 20929 20964 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:02.723 20929 20964 I mono-stdout: 	content-type: application/json
07-06 18:13:02.723 20929 20964 I mono-stdout: 	content-encoding: utf-8
07-06 18:13:03.237 20929 20957 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:03.237 20929 20957 I mono-stdout: {"temperature":76.1304379673118,"temperature_unit":"F","humidity":70.1791726749759,"humidity_unit":"%","pressure":143.468197173657,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:03.238 20929 20957 I mono-stdout: Application properties (set by device):
07-06 18:13:03.238 20929 20957 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:03.238 20929 20957 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:09:26.4757944Z
07-06 18:13:03.238 20929 20957 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:09:26+00:00
07-06 18:13:03.238 20929 20957 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:03.238 20929 20957 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:03.238 20929 20957 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:03.238 20929 20957 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:03.238 20929 20957 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:03.238 20929 20957 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:03.238 20929 20957 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:09:26
07-06 18:13:03.238 20929 20957 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:03.238 20929 20957 I mono-stdout: 	content-type: application/json
07-06 18:13:03.238 20929 20957 I mono-stdout: 	content-encoding: utf-8
07-06 18:13:03.279 20929 20964 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:03.279 20929 20964 I mono-stdout: {"temperature":71.2549233553023,"temperature_unit":"F","humidity":67.4478110279645,"humidity_unit":"%","pressure":160.483840767054,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:03.279 20929 20964 I mono-stdout: Application properties (set by device):
07-06 18:13:03.279 20929 20964 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:03.280 20929 20964 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:10:26.4913162Z
07-06 18:13:03.280 20929 20964 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:10:26+00:00
07-06 18:13:03.280 20929 20964 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:03.280 20929 20964 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:03.280 20929 20964 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:03.280 20929 20964 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:03.280 20929 20964 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:03.280 20929 20964 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:03.280 20929 20964 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:10:26
07-06 18:13:03.280 20929 20964 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:03.280 20929 20964 I mono-stdout: 	content-type: application/json
07-06 18:13:03.280 20929 20964 I mono-stdout: 	content-encoding: utf-8
07-06 18:13:03.280 20929 20964 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:03.280 20929 20964 I mono-stdout: {"temperature":75.2474758257146,"temperature_unit":"F","humidity":68.5750674885116,"humidity_unit":"%","pressure":148.71076735375,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:03.281 20929 20964 I mono-stdout: Application properties (set by device):
07-06 18:13:03.281 20929 20964 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:03.281 20929 20964 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:11:26.5089663Z
07-06 18:13:03.281 20929 20964 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:11:26+00:00
07-06 18:13:03.281 20929 20964 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:03.281 20929 20964 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:03.281 20929 20964 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:03.281 20929 20964 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:03.281 20929 20964 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:03.281 20929 20964 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:03.281 20929 20964 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:11:26
07-06 18:13:03.281 20929 20964 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:03.281 20929 20964 I mono-stdout: 	content-type: application/json
07-06 18:13:03.281 20929 20964 I mono-stdout: 	content-encoding: utf-8
07-06 18:13:03.282 20929 20964 I mono-stdout: 0: Message received on partition {0}:
07-06 18:13:03.282 20929 20964 I mono-stdout: {"temperature":78.1356127627127,"temperature_unit":"F","humidity":68.495878788175,"humidity_unit":"%","pressure":151.882502481752,"pressure_unit":"psig"}: 	{0}:
07-06 18:13:03.282 20929 20964 I mono-stdout: Application properties (set by device):
07-06 18:13:03.282 20929 20964 I mono-stdout: 	iothub-message-schema: chiller-sensors;v1
07-06 18:13:03.282 20929 20964 I mono-stdout: 	iothub-creation-time-utc: 2020-07-06T16:12:26.5254753Z
07-06 18:13:03.282 20929 20964 I mono-stdout: 	$$CreationTimeUtc: 2020-07-06T16:12:26+00:00
07-06 18:13:03.282 20929 20964 I mono-stdout: 	$$MessageSchema: chiller-sensors;v1
07-06 18:13:03.282 20929 20964 I mono-stdout: 	$$ContentType: JSON
07-06 18:13:03.282 20929 20964 I mono-stdout: System properties (set by IoT Hub):
07-06 18:13:03.282 20929 20964 I mono-stdout: 	iothub-connection-device-id: a92cc90d-6c50-4cd6-a796-3bad82e4be01.chiller-01.1
07-06 18:13:03.282 20929 20964 I mono-stdout: 	iothub-connection-auth-method: {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
07-06 18:13:03.282 20929 20964 I mono-stdout: 	iothub-connection-auth-generation-id: 637296482112237080
07-06 18:13:03.282 20929 20964 I mono-stdout: 	iothub-enqueuedtime: 07/06/2020 16:12:26
07-06 18:13:03.282 20929 20964 I mono-stdout: 	iothub-message-source: Telemetry
07-06 18:13:03.282 20929 20964 I mono-stdout: 	content-type: application/json
07-06 18:13:03.282 20929 20964 I mono-stdout: 	content-encoding: utf-8
```

@hbraasch your report didn't mentione the Xamarin.Android version, so in case you're not using the latest one, please upgrade and rebuild your application from scratch, after deleting all the `bin` and `obj` directories.

**Comment by hbraasch** [comment]
@grendello, thanks for the assistance! Much appreciated.
It now appears the problem lies on my side. I will check it out using your suggestions and more.
Can we please keep it open for a while so I can report back once I've found the solution?
Regards.

**Comment by grendello** [comment]
@hbraasch sure, no problem, we can keep the issue open! :)

**Comment by moljac** [comment]
@hbraasch 
Hi!
Do you need this issue to be opened?
Thanks

**Comment by hbraasch** [comment]
You can close it. Still not working my side but I haven’t had much opportunity to investigate. Regards Sent from Mail for Windows 10 From: moljacSent: Monday, 10 August 2020 8:30 PMTo: xamarin/xamarin-androidCc: Heinrich Braasch; MentionSubject: Re: [xamarin/xamarin-android] [Bug] Network issue accessing Azure IOT Hub (#4837) @hbraaschHi!Do you need this issue to be opened?Thanks—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by moljac** [comment]
@hbraasch Thanks. Reopen it or open a new one if the problem persists, please.

**Comment by hbraasch** [comment]
Fixed. Problem dissappeared after updating  Microsoft.Azure.EventHubs to latest nuget version.  Sounds so obvious now.

**Comment by BucurCosmin** [comment]
Sorry to open this again.
For me it's not working with the same code.
Looks like 
EventHubConsumerClient consumer = new EventHubConsumerClient(EventHubConsumerClient.DefaultConsumerGroupName, connectionString, eventHubName); it's failing since with breakpoints i'm not passing.
Updated Azure.Messaging.EventHubs to v5.2.
target Android Api level 27
