### ISSUE TITLE
"error XA0030: Building with JDK version `11.0.7` is not supported" when attempting to use a JDK 11 version that is a bit too new

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#4853]
### Steps to reproduce

1. Download the current version of the _jbrsdk_ JetBrains Runtime that's available on <https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime>.

   Today, that's <https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-windows-x64/765.64>, OpenJDK version 11.0.7.

2. Extract the files to a directory.

3. Set Xamarin.Android builds to use that JDK 11 directory. For example, open **Tools > Options** in Visual Studio, select the **Xamarin > Android Settings** node, and set **Java Development Kit Location** to that directory.

4. Attempt to build a Xamarin.Android app project.

### Expected behavior

Maybe the build should succeed? That is, maybe the explicit version check for the JDK version number can now use just the major.minor part of the version number instead of the full major.minor.build? It seems like the third place of JDK 11 version numbers (the `Build` number in `System.Version` terminology) changes more frequently than it did for the old 1.8.0 version number scheme of JDK 8.

### Actual behavior

The build fails because the third place of the JDK version number is higher than the current `$(LatestSupportedJavaVersion)`:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(163,5): error XA0030: Building with JDK version `11.0.7` is not supported. Please install JDK version `11.0.4`. See https://aka.ms/xamarin/jdk9-errors
```

### Version information

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 4.0 [30222.8.master]

Xamarin.Android SDK   10.4.0.0 (d16-7/de70286)

**Comment by jonathanpeppers** [comment]
@jonpryor should this be 11.0.99?

https://github.com/xamarin/xamarin-android/blob/88215f93fdcf14fa1a2aebbb499c09c6bdb8fa8c/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in#L10

Or what do we actually do here? It seems like they will bump the minor version all the time.

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 4. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by softlion** [comment]
Same problem with JDJK17

  Xamarin.Android.Legacy.targets(252, 5): [XA0030] Building with JDK version `17.0.1` is not supported. Please install JDK version `11.0`. See https://aka.ms/xamarin/jdk9-errors

**Comment by EmilAlipiev** [comment]
is it today still 17 not supported? we should keep the jdk 11 and is it now advised to use Microsoft Own build Jdk 11?

**Comment by jonathanpeppers** [comment]
@EmilAlipiev the latest Android Studio still uses Java 11:
```
> "C:\Program Files\Android\Android Studio\jre\bin\java.exe" -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
```
We can't really support new JDKs until the underlying Android tooling does.

Is there a problem you're having that needs JDK 17? Can you file an issue with more details?
