### ISSUE TITLE
Couldn't match mono version from Xamarin Android runtime with mono sources

### ISSUE THREAD

**Issue by sergey-rubtsov-05** [xamarin/xamarin-android#4862]
### Steps to Reproduce

1. Build and run Xamarin.Android application with that code:
```
var type = Type.GetType("Mono.Runtime");
var displayName = type?.GetMethod("GetDisplayName");
if (displayName != null)
    var version = (string) displayName.Invoke(null, null);
```
2. Check the content on `version` variable

### Actual Behavior

In my case `version` is `6.12.0 (2020-02/165f4b03417)`. But I couldn't find that version or git commit in [mono repository](https://github.com/mono/mono).

### My Questions

1. Is it the correct way to determinate a version of `mono`?
If it is
2. Why mono version in Xamarin.Android isn't synchronized with `mono` repository versions?
3. Is it possible to find source codes of mono which uses by Xamarin.Android?

### Version Information

Microsoft Visual Studio Community 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA133
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.6.948.25768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.948.25768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.948.25768
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.948.25768
Azure Functions and Web Jobs Tools

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.3.4   Build 193.0.20200226.112949
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1061 (d16-6@8e68aa8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by brendanzagaeski** [comment]
> 1. Is it the correct way to determinate a version of `mono`?

Yes, that's a fine way to determine the Mono version. A few other ways are:

- Use the detailed version information copied from Visual Studio. For example, at the bottom of the version information pasted [above](https://github.com/xamarin/xamarin-android/issues/4862#issue-644548170):

  > Xamarin.Android SDK 10.3.1.4 (d16-6/3a10de9)
  > Xamarin.Android Reference Assemblies and MSBuild support.
  > Mono: 165f4b0

- Or use the release notes:

  https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.3#mono-framework-version-update-to-612

  > Xamarin.Android now uses the [Mono 6.12](https://www.mono-project.com/docs/about-mono/releases/6.12.0/) runtime and class libraries at [Commit 165f4b03](https://github.com/mono/mono/commit/165f4b03417a1e18c8c6db3d93a7a4916d77488a), bringing in about 900 new commits.

  Note that releases such as Xamarin.Android SDK version 10.3.1.4 that do not change the Mono version will not mention the Mono version, so with this approach, it's necessary to look for the most recent previous release that mentions the Mono version.

- Or use the Mono source reference directly from the xamarin-android repository. Right now, the way the xamarin-android repository references Mono is via the _.external_ file in the repository:

  https://github.com/xamarin/xamarin-android/blob/v10.3.1.4/.external

  ```
  xamarin/monodroid:d16-6@70d4ff405ad779a5b03a4137358c6911b8f521a5
  mono/mono:2020-02@165f4b03417a1e18c8c6db3d93a7a4916d77488a
  ```

> 2. Why mono version in Xamarin.Android isn't synchronized with `mono` repository versions?
> 3. Is it possible to find source codes of mono which uses by Xamarin.Android?

> In my case version is 6.12.0 (2020-02/165f4b03417). But I couldn't find that version or git commit in [mono repository](https://github.com/mono/mono).

One way to find the corresponding source in the mono/mono repository is to paste the commit hash at the end of the _commit_ endpoint on GitHub: `https://github.com/mono/mono/commit/165f4b03417`

In some cases, I think it's possible the commit hash returned by `Mono.Runtime.GetDisplayName()` could be ambiguous between two or more commits if it isn't long enough. In those cases, the release notes or _.external_ file can help provide the full length commit hash. (Another approach would be to `grep` the output from `git rev-list` in a local clone of the Mono repository.)

**Comment by sergey-rubtsov-05** [comment]
@brendanzagaeski Thank you very much for the very detailed answer. There is only one additional question, why [mono releases](https://github.com/mono/mono/releases) (the last is 6.10.0.105) don't contain the release which uses by Xamarin.Android (6.12 or 2020-02)?

**Comment by brendanzagaeski** [comment]
I think there are 2 parts to that answer:

1. The Git tags that appear on the mono/mono/releases page align with the Mono Framework MDK packages for desktop operating systems like macOS and Linux, so the tagging process doesn't automatically generate a tag when a Xamarin.Android version is released based on a particular Mono version.

2. The next question you might have is "isn't there already a Mono Framework MDK version 6.12 package available for macOS and Linux?" The answer to that is "yes," so I think it's unintentional that there aren't yet any 6.12 tags. Usually a 6.12 tag would be created as soon as 6.12 package was first available for download for macOS and Linux. But <https://www.mono-project.com/download/> and <https://www.mono-project.com/docs/about-mono/releases/> have not yet been updated to include 6.12. I have reached out to the Mono team to let them know those pages are due for an update, and they let me know they would plan to update them soon.
