### ISSUE TITLE
Device not compatible after reupload in Google Play Store

### ISSUE THREAD

**Issue by Kileon** [xamarin/xamarin-android#4883]
Is there someone has the same issue about Google Playstore?
My team made an app using Xamarin and has successfully uploaded into Google Playstore. That app has been downloaded and used by some people for months. 
My team made minor changes (option button) and **update the app** to Google Playstore.
Surprisingly people who has already downloaded my app didn't find it. When we check the detial. The Google Playstore detect that the Device is suddenly not compatible.

Any idea what's going on?
Thank you

**Comment by brendanzagaeski** [comment]
Apologies for the slow reply on this issue. To start at a high level, I suspect the Google Play team might be able to provide better answers about this question than the Xamarin.Android team. For example, I tried a web search for `Device not compatible after update Google Play Store`, and near the top of the results, I found the following page that looks like a good candidate to address your question: https://support.google.com/googleplay/thread/5241214?hl=en

That said, if that Google Play support topic does not resolve the question, then a next piece of information to collect and attach back on this issue would be the dumps of the _AndroidManifest.xml_ files from the two APKs that you uploaded. Alternatively, if it's easier and if the APK files are already freely downloadable from the Google Play store, feel free to attach the full APK files themselves.

Here are the steps to collect and attach back the dumps of the _AndroidManifest.xml_ files:

1. Open **Tools > Command Line > Developer Command Prompt**.

2. Run a command like the following to dump the _AndroidManifest.xml_ information from the original APK file (from before the "device not compatible" problem appeared):

   ```cmd
   "%VSINSTALLDIR%\MSBuild\Xamarin\Android\aapt2.exe" dump xmltree --file AndroidManifest.xml com.conotoso.androidapp1.apk > "%USERPROFILE%\Desktop\AndroidManifest.Before.xml"
   ```

   Replace `com.conotoso.androidapp1.apk` with the path to the original APK file.

3. Repeat step 2 for the new APK file (from when the "device not compatible" problem started happening):

   ```cmd
   "%VSINSTALLDIR%\MSBuild\Xamarin\Android\aapt2.exe" dump xmltree --file AndroidManifest.xml com.conotoso.androidapp1.apk > "%USERPROFILE%\Desktop\AndroidManifest.After.xml"
   ```
   
   (This time replace `com.conotoso.androidapp1.apk` with the path to the new APK file.)

4. Archive the two _.xml_ files from your Desktop into a _.zip_ file, for example by selecting both files, right clicking, and selecting **Send to > Compressed (zipped) folder**.

5. Attach back the _.zip_ file in a new comment on this issue.

Thanks in advance!

**Comment by brendanzagaeski** [comment]
As a small reminder, if you haven't yet resolved this issue, be sure to reply back with the additional information about the _AndroidManifest.xml_ files within the next 14 days so the team can investigate further. If you have already resolved the issue, no need to reply. I'll plan to close this report after 14 days. Thanks!

**Comment by brendanzagaeski** [comment]
To follow up on my previous comment, I will now close this report. If you have not yet resolved this issue, be sure to reply back with the additional information about the _AndroidManifest.xml_ files when you get a chance, and I will reopen the issue so the team can investigate further. Thank you!
