### ISSUE TITLE
Getting build error in Xamarin.Android project

### ISSUE THREAD

**Issue by xhashimks** [xamarin/xamarin-android#4885]
Mac OS - macOS Catalina 10.15.3
Visual Studio for Mac 8.4.4
Xamarin.Android - 9.4.1.0 

### Steps to Reproduce
1. Simply build the application in release model - Build error

Error:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2931,3): error XA3001: Could not link native shared library: libxamarin-app.so
    3 Warning(s)
    1 Error(s)
Time Elapsed 00:00:01.85
Target _CreateApplicationSharedLibraries:
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2931,3): error XA3001: Could not link native shared library: libxamarin-app.so
Done building target "_CreateApplicationSharedLibraries" in project "Xpo.DriverMobile.LastMile.Android.csproj" -- FAILED.
Done building project "Xpo.DriverMobile.LastMile.Android.csproj" -- FAILED.
Build FAILED.

The error will not be seen if i unselect the armeabi-v7a in supported ABIs and this will build successfully.

I have another setup with the same setup but MacOS lower
Mac OS - macOS Mojave 10.14.4
Visual Studio for Mac 8.4.4
Xamarin.Android - 9.4.1.0 

This will not give me build error even though I select armeabi-v7a in supported ABIs

**Comment by xhashimks** [comment]
@dellis1972 , @jonpryor , @brendanzagaeski

**Comment by xhashimks** [comment]
I got same issue after upgrading Xamarin.Android to 10.2.0

**Comment by dellis1972** [comment]
@xhashimks in order to investigate this further we need a diagnostic build log which contains the error. You can get this log by following the instructions at https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting. Please attach the resulting file(s) to this issue so we can investigate further.

**Comment by xhashimks** [comment]
@dellis1972 Thanks for your reply... i will be attaching this asap..

**Comment by xhashimks** [comment]
[Diagnostic MSBuild Output.docx](https://github.com/xamarin/xamarin-android/files/4857490/Diagnostic.MSBuild.Output.docx)

**Comment by xhashimks** [comment]
[AndroidTools.2020-07-01__16-40-16.log](https://github.com/xamarin/xamarin-android/files/4857563/AndroidTools.2020-07-01__16-40-16.log)

**Comment by dellis1972** [comment]
@xhashimks thanks for the data. I'm sorry to say the Diagnostic log output does not seem to contain the reported build error. It seems that all the projects built successfully in that build. We will need a log which has the reported error so we can investigate the previous lines in the logs to see why that error is happening. 

On a side, a plain txt file should be ok for logs, there is no need to place it in a word document.

**Comment by xhashimks** [comment]
@dellis1972 Build is success. But while trying to deploy the error occurs.

**Comment by xhashimks** [comment]
@dellis1972 Attaching new.. you can see build failed in this... search for keyword Build failed
[build output.docx](https://github.com/xamarin/xamarin-android/files/4857738/build.output.docx)

Sorry for updating doc format again as I am using mac os and right now do not have any txt extension file softwares.

**Comment by grendello** [comment]
@xhashimks unfortunately, all the log contains is the final error message without diagnostic output:

```
  Task "LinkApplicationSharedLibraries"
    [Native Linker] /Applications/android-sdk-macosx/build-tools/28.0.3/aarch64-linux-android-ld --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname libxamarin-app.so -z relro -z noexecstack --enable-new-dtags --eh-frame-hdr -shared --build-id --warn-shared-textrel --fatal-warnings -o obj/Debug/app_shared_libraries/arm64-v8a/libxamarin-app.so --fix-cortex-a53-843419 -m aarch64linux obj/Debug/android/typemap.jm.arm64-v8a.o obj/Debug/android/typemap.mj.arm64-v8a.o obj/Debug/android/environment.arm64-v8a.o
    [Native Linker] /Applications/android-sdk-macosx/build-tools/28.0.3/arm-linux-androideabi-ld --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname libxamarin-app.so -z relro -z noexecstack --enable-new-dtags --eh-frame-hdr -shared --build-id --warn-shared-textrel --fatal-warnings -o obj/Debug/app_shared_libraries/armeabi-v7a/libxamarin-app.so -X -m armelf_linux_eabi obj/Debug/android/typemap.jm.armeabi-v7a.o obj/Debug/android/typemap.mj.armeabi-v7a.o obj/Debug/android/environment.armeabi-v7a.o
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2931,3): error XA3001: Could not link native shared library: libxamarin-app.so
```

Since the error occurs on deployment, please use the following command from terminal while in your project's top directory:

```shell
msbuild /bl /t:Install
```

This will create a file called `msbuild.binlog`, please attach it here. Thanks!

**Comment by xhashimks** [comment]
[msbuild.txt](https://github.com/xamarin/xamarin-android/files/4858579/msbuild.txt)


Cannot attach binlog format here. Hence renamed to txt. Please rename it to binlog

**Comment by grendello** [comment]
@xhashimks your Xamarin.Android version is too old for Catalina. macOS Catalina requires that all the binaries are 64-bit, but your build uses a 32-bit native linker from Android SDK build-tools:

```shell
$ file arm-linux-androideabi-ld 
arm-linux-androideabi-ld: Mach-O executable i386
```
Which won't run:
```shell
$ ./arm-linux-androideabi-ld
bash: ./arm-linux-androideabi-ld: Bad CPU type in executable
```

And that causes the build error. You must update your Xamarin.Android to the [latest version](https://github.com/xamarin/xamarin-android/#current) and remove the old one. After doing that, please remove all `bin` and `obj` directories from your project and rebuild/redeploy it from scratch. The binlog you provided came from Xamarin.Android version 9.4.1.0 which will **not** work correctly on macOS Catalina.

**Comment by xhashimks** [comment]
@grendello - Thanks for the detailed information and really appreciate your support. I will try upgrading Xamarin Android to latest version and will update the details here.

**Comment by xhashimks** [comment]
@grendello Yes. This worked. Upgrading to latest android worked for me.

Thanks a lot.
