### ISSUE TITLE
Multiple errors after upgrading Xamarin.Android to latest version

### ISSUE THREAD

**Issue by xhashimks** [xamarin/xamarin-android#4889]
@dellis1972 , @grendello 

Upgraded Xamarin.Android to latest version getting errors in Xamarin android project. Attached screenshot
<img width="961" alt="Screenshot 2020-07-01 at 10 58 20 PM" src="https://user-images.githubusercontent.com/47141601/86278871-b1597400-bbf6-11ea-9756-0431ee3f6254.png">

**Comment by brendanzagaeski** [comment]
As a first quick idea, those errors typically indicate that NuGet packages have not been restored as expected, so with a little luck the following steps will help:

1. Quit Visual Studio.
2. Remove all of the _bin_ and _obj_ directories from the solution.
3. Reopen the project in Visual Studio and allow the NuGet restore process to complete.

If that does not resolve the issue, then if you can attach the [diagnostic MSBuild output](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting), that would be perfect. Thanks in advance!

**Comment by xhashimks** [comment]
@brendanzagaeski I did all the steps mentioned above and still same :|

**Comment by xhashimks** [comment]
@brendanzagaeski I did clean up like above said. Then restarted the machine. It worked now. Thanks for your assistance. You can please close this case.

Thanks a lot!

**Comment by brendanzagaeski** [comment]
Excellent. Glad to hear it's working now!
