### ISSUE TITLE
NullPointerException in AnimatorSet.start

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/xamarin-android#4892]
This is just based on an AppCenter report, so I can provide limited information. It may be a bug deep in Android but I'm not sure.

A user received a crash in AnimatorSet.start when it attempts to call setAllowRunningAsynchronously.

Line 716, here: https://cs.android.com/android/platform/superproject/+/android-8.0.0_r1:frameworks/base/core/java/android/animation/AnimatorSet.java

(It's an Android 8.0.0 device, Galaxy S7)

Clearly there's a null animation being added as a node in the AnimatorSet. But I'm having trouble tracking down where that might be used. This repository doesn't seem to reference AnimatorSet outside of perhaps exposing it, nor does Xamarin.Forms.

My app does use animations, but all of them are not null.

There was a previous issue where animations in Android could fail if battery saver mode was turned on. But if that's it, Android's library should be checking for null, right?

**Comment by grendello** [comment]
@BioTurboNick we'll need at least a managed stack trace to be able to tell anything. Xamarin.Android doesn't modify Android behaviors in any way, we merely bind/wrap the APIs. Xamarin.Forms is a bit more intrusive, but it's hard to tell what's happening here without the managed trace (or, ideally, a full logcat output of the crash).

**Comment by BioTurboNick** [comment]
It's Android stack frames all the way down
```
ndroid.animation.AnimatorSet.start AnimatorSet.java:716
android.animation.AnimatorSet.start AnimatorSet.java:684
android.widget.Editor$HandleView.restore Editor.java:5277
android.widget.Editor$HandleView.onTouchEvent Editor.java:5096
android.widget.Editor$InsertionHandleView.onTouchEvent Editor.java:5627
android.view.View.dispatchTouchEvent View.java:12540
android.view.ViewGroup.dispatchTransformedTouchEvent ViewGroup.java:3159
android.view.ViewGroup.dispatchTouchEvent ViewGroup.java:2844
android.view.ViewGroup.dispatchTransformedTouchEvent ViewGroup.java:3159
android.view.ViewGroup.dispatchTouchEvent ViewGroup.java:2844
android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent PopupWindow.java:2686
android.view.View.dispatchPointerEvent View.java:12788
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent ViewRootImpl.java:5670
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess ViewRootImpl.java:5465
android.view.ViewRootImpl$InputStage.deliver ViewRootImpl.java:4958
android.view.ViewRootImpl$InputStage.onDeliverToNext ViewRootImpl.java:5011
android.view.ViewRootImpl$InputStage.forward ViewRootImpl.java:4977
android.view.ViewRootImpl$AsyncInputStage.forward ViewRootImpl.java:5114
android.view.ViewRootImpl$InputStage.apply ViewRootImpl.java:4985
android.view.ViewRootImpl$AsyncInputStage.apply ViewRootImpl.java:5171
android.view.ViewRootImpl$InputStage.deliver ViewRootImpl.java:4958
android.view.ViewRootImpl$InputStage.onDeliverToNext ViewRootImpl.java:5011
android.view.ViewRootImpl$InputStage.forward ViewRootImpl.java:4977
android.view.ViewRootImpl$InputStage.apply ViewRootImpl.java:4985
android.view.ViewRootImpl$InputStage.deliver ViewRootImpl.java:4958
android.view.ViewRootImpl.deliverInputEvent ViewRootImpl.java:7736
android.view.ViewRootImpl.doProcessInputEvents ViewRootImpl.java:7676
android.view.ViewRootImpl.enqueueInputEvent ViewRootImpl.java:7637
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent ViewRootImpl.java:7847
android.view.InputEventReceiver.dispatchInputEvent InputEventReceiver.java:197
android.os.MessageQueue.nativePollOnce MessageQueue.java
android.os.MessageQueue.next MessageQueue.java:325
android.os.Looper.loop Looper.java:142
android.app.ActivityThread.main ActivityThread.java:6944
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.Zygote$MethodAndArgsCaller.run Zygote.java:327
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1374
```

**Comment by grendello** [comment]
@BioTurboNick the best advice we can offer now is: make sure you initialize everything on Java side and that there isn't code similar to `new Node(null)` anywhere around your app or in the libraries the app depends on.

**Comment by BioTurboNick** [comment]
Thanks @grendello - My code is 100% Xamarin.Forms and some Xamarin.Android. So if it isn't me or you, I guess it must be Android proper.
