### ISSUE TITLE
Android Fatal Error deserialising byte array to structure

### ISSUE THREAD

**Issue by mattfinch1980** [xamarin/xamarin-android#4903]
Fatal error when running below code in current xamarin release candidate v4.7.0.1080 compiling with Android Pie (9.0). 

public static T DeserialiseToObject<T>(byte[] bytearray, int startIndex = 0) where T : struct
        {
            T str = default(T);
            if (bytearray != null)
            {
                int size = Marshal.SizeOf(str);
                IntPtr ptr = Marshal.AllocHGlobal(size);
                Marshal.Copy(bytearray, startIndex, ptr, size);
                str = (T)Marshal.PtrToStructure(ptr, str.GetType());
                Marshal.FreeHGlobal(ptr);
            }
            return str;
        }

error only occurs on Lenovo Tab2 A10 running 6.0.1 currently, output below.

07-07 09:57:11.764 F/        ( 7645): * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/mini/mini-arm.c:6600, condition `arm_is_imm12 (ss_method_ins->inst_offset)' not met
07-07 09:57:11.764 F/libc    ( 7645): Fatal signal 6 (SIGABRT), code -6 in tid 7786 (Thread Pool Wor)

Cannot find workaround. This did not occur in previous xamarin forms releases but at the moment I cannot find last version that was working.

Any thoughts much appreciated.

Best Regards,

Matt Finch

**Comment by mattfinch1980** [comment]
Is there any update on this issue at all or any further information of possible hardware reasons for specific device failure? We need to make decision on affect of a possible new release of software on currently utilised android devices. 

Any info much appreciated.

Best Regards,

Matt Finch

**Comment by mattfinch1980** [comment]
Would there be an update on this at all?

Best Regards,

Matt Finch

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
