### ISSUE TITLE
Bump macOS native toolchain used.

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#4907]
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1139574

When building on macOS, Xamarin.Android uses Xcode 10.2.1 to build native code, e.g. https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3874736&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=65256bb7-a34c-5353-bc4d-c02ee25dc133

```
InstalledDir: /Applications/Xcode_10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

We should look into using a more recent Xcode version, or see if we can auto provision *and use* a more recent Xcode Command Line Tools version.

**Comment by moljac** [comment]
Who has the access to the bots? To assign it?
