### ISSUE TITLE
App crashing when build with R8 after upgrading to AndroidX

### ISSUE THREAD

**Issue by ederbond** [xamarin/xamarin-android#4908]
### Steps to Reproduce

1. Download the following project https://github.com/ederbond/AndroidX_R8_Crash_At_Startup
2. Build the Android project in release mode with both D8 and R8 enabled.
3.  Run it no your device

### Expected Behavior
You was supposed to se a login page.

### Actual Behavior
The app crashes during startup

### Version Information
Visual Studio 2019 16.6.3
Windows 10 Pro 1909

### Log File

[logcat.txt](https://github.com/xamarin/xamarin-android/files/4899619/logcat.txt)

**Comment by ederbond** [comment]
It seems like R8 was cutting androidx.work.impl.WorkManagerInitializer

adding the line bellow to my proguard.cfg solved the issue:
`-keep class androidx.work.impl.WorkManagerInitializer`

Thanks in advance @jonathanpeppers

**Comment by ederbond** [comment]
@jonathanpeppers should I keep this issue ticket open in order to ask for having this -keep class added to the androdX nuget package that androidx.work.impl.WorkManagerInitializer belongs to?

**Comment by jonathanpeppers** [comment]
@ederbond these are the default proguard rules coming from the `androidx.work.*.aar` file:
```proguard
-keep class * extends androidx.work.Worker
-keep class * extends androidx.work.InputMerger
# Keep all constructors on ListenableWorker, Worker (also marked with @Keep)
-keep public class * extends androidx.work.ListenableWorker {
    public <init>(...);
}
# We need to keep WorkerParameters for the ListenableWorker constructor
-keep class androidx.work.WorkerParameters
```
This feels like Google's bug, it could be they need to add a built-in rule -- or some problem with r8 stripping away too much.

Either case, I don't see anything we can fix here. Let me know if you have another issue here, thanks!
