### ISSUE TITLE
Publishing Android release results in error: apk is not a valid zip archive [403]

### ISSUE THREAD

**Issue by tpitman** [xamarin/xamarin-android#4916]
### Steps to Reproduce

1. Sign and Distribute Application
2. Go through publish wizard
3. Get an error half way through upload process: apk is not a valid zip archive [403]

### Expected Behavior
Error

### Actual Behavior
Successful publish

### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.6.5 (build 23)
Installation UUID: b16cad11-3d99-4430-8916-a0e5ff811f9e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.301/Sdks
SDK Versions:
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.401
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.403
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.0-preview2-1-003177
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.6
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.5
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.0

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/tpitman/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.3
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/tpitman/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:42:50 UTC

=== Android Device Manager ===

Version: 16.6.0.96
Hash: 6e8b80b
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:43:28 UTC

=== Apple Developer Tools ===

Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===

Version: 6.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:04-0400

=== Xamarin.iOS ===

Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Build Information ===

Release ID: 806050023
Git revision: 5289d413b99fddfc20b4ecf3e445ccb822213427
Build date: 2020-06-18 12:08:30-04
Build branch: release-8.6
Xamarin extensions: 5289d413b99fddfc20b4ecf3e445ccb822213427

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### Log File

This does not happen when interacting with a device. It happens when trying to publish an Archive to the google play store.

=== Additional Information ===

Something else that is interesting is I am on version 24 of my releases. When I look in the Archive.xml file in the archive folder it has this line:

` <PackageVersionCode>24</PackageVersionCode>`

If I try to manually create a release on the google play store, it tells me I can't upload this apk because I already have one that is version 19. I verified in the AndroidManifest.xml in Visual Studio and also in the Options for the Android project that they are both set to 24. I have uploaded version 20-23 successfully. I don't know if this version 19 issue is related because 20-23 uploaded fine, but each time I have gotten an error in the VS UI about version 19 an yet they uploaded fine. This could be a separate issue.

What I do know is that I can't publish today at all because of this invalid Archive issue.

I have updated all SDK components and Visual Studio.

**Comment by jonathanpeppers** [comment]
@tpitman if you publish from a command-line build, does it work?

```
msbuild Foo.Android.csproj -p:Configuration=Release -t:SignAndroidPackage -bl
```

If you have different `.keystore` settings you would also need to set these as needed:
https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/BuildProcess.md#signing-properties

```
-p:AndroidKeyStore=true -p:AndroidSigningKeyAlias=foo -p:AndroidSigningKeyPass=password -p:AndroidSigningKeyStore=foo.keystore -p:AndroidSigningStorePass=password
```

If it doesn't work, attach the `msbuild.binlog` file you got from the `-bl` switch, thanks! 

Otherwise, we can get the right people to see what might be happening inside VS for Mac.

**Comment by tpitman** [comment]
I ran that command line and am not exactly sure what it was supposed to do. From your message it made me think it would try to actually publish to google play store, but it doesn't. It just finished at the command line. I am at a loss as to what exactly it did.

However, I did notice something at the very end that jumped out at me. When I was looking at the generated files I mentioned in my original post that the VersionCode was properly set to 24 and yet when I tried to manually upload this file it was saying I already had a version 19 which was published several weeks ago.

Well, in the output from your command line build I noticed this line at the very bottom during signing:

`VersionAndBuild.cs(22,20): warning CS0618: 'PackageInfo.VersionCode' is obsolete: 'deprecated' [/Users/tpitman/Projects/Powerteq/Software/Powerteq/Amped/Amped/Amped/Amped.Android/Amped.Android.csproj]`

Could this be related at all?

Before I upload a build log I would like to know that there will not be any security information contained in it. If there will be can you give me some place I can send it directly to you guys and not have it published here in a public forum?

**Comment by jonathanpeppers** [comment]
You'll find the `*-Signed.apk` file in `bin/Release/`. You can upload this file to Google Play, or simply install it to test by running:

```
adb install bin/Release/com.yourapp-Signed.apk
```
This would install the apk to an attached emulator or device ^^

You can email me via my address on [my Github profile](https://github.com/jonathanpeppers) if you don't want the log public. Thanks!

**Comment by tpitman** [comment]
So here are the results of what I have done.

I went to the google play publish page and created a new release. I then manually dropped the file that the command line build you gave me output onto that page and it uploaded and worked is it should.

Keep in mind that all of my previous releases 1-23 were uploaded directly from Visual Studio using the sign and publish button from the Archives page.

So I deleted that release because I want to make sure it works from Visual Studio.

I then tried to do the Archive process in Visual Studio and it wouldn't even archive.

I then right clicked on the previous archive in the archive list on that archive page in VS and did Reveal in Finder. I then manually deleted the archive folder from today.

I then went back to VS and was then able to create a new archive.

I then did the sign and distribute button and again got the [403] error listed as the title of this issue.

So I manually went out to the finder for that archive folder, found the signed apk just generated and tried to upload that to google play. Google play tells me I already have a version 24 even though I removed it. Turns out I hadn't fully removed it so I created a new build 25.

I tried to sign and distribute 25 and got the same error [403] about the archive being invalid. I then manually created a new release and dragged the signed file created as archive 25. I dragged that file onto the google play release page where you drop the file and it worked fine.

So it appears that the creation of the archive is not the issue. It has something to do with trying to upload it in VS.

I don't think sending you the build log will help because that seems to have created a build that is fine.

This has something to do with uploading the archive file from within VS using the sign and distribute button on the archives page.

What would you like me to do now?

**Comment by jonathanpeppers** [comment]
@joj or @tondat what should we do to get more info about the failed upload?

**Comment by kunyli** [comment]
@tpitman Hello, I’ve looked into this issue, and after some investigation it seems like this could be a known issue from Google’s side (reference here: https://stackoverflow.com/questions/62891892/google-api-error-forbidden-apk-is-not-a-valid-zip-archive-while-upload-apk-to). According to the responses in the post, the issue has been fixed now. Can you try to publish your app again to see if it works now?

If the error is still happening, please verify that there are no other pending releases in the channel you are trying to upload to. In addition, to allow you to provide us more information easily and better track this issue internally, can you please create a feedback ticket via the “Report a Problem” tool in the IDE? (Specific instructions here: https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019)
