### ISSUE TITLE
Error : Program type already present: okio.AsyncTimeout on macOS

### ISSUE THREAD

**Issue by ChristopheBovyn** [xamarin/xamarin-android#4932]
### Steps to Reproduce

1. Update PDFTron.Android.Tools from version 7.0 to last version (7.1.3)

Source code is available here : [AndroidX_PDFtron_Sample-develop.zip](https://github.com/xamarin/xamarin-android/files/4936343/AndroidX_PDFtron_Sample-develop.zip)

This is a sample project which contains libs used on my project.

### Actual Behavior

I'm working on macOS on a project which use PDFTron.Android.Tools in version 6.8.4, I try to update the lib to the last version (7.1.3) but when I do it, I can't build my app and I've got the error "Program type already present: okio.AyncTimeout". However I successfully build & run app with PDFTron.Android.Tools v7.0 .
I get the project on Windows and I'm able to build & run the app.

### Version Information
=== Visual Studio Community 2019 for Mac ===

Version 8.4.8 (build 2)
Installation UUID: babcf8ea-c136-458a-8972-4217abc3c66f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000166

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.166 (2019-08/d9001b5ae70) (64-bit)
	Package version: 606000166

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.102/Sdks
SDK Versions:
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.15
	2.1.14
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3 (15712)
Build 11C29

=== Xamarin.Mac ===

Version: 6.10.0.21 (Visual Studio Community)
Hash: 02c4b3bdc
Branch: xcode11.3
Build date: 2020-02-18 14:13:31-0500

=== Xamarin.iOS ===

Version: 13.10.0.21 (Visual Studio Community)
Hash: 02c4b3bdc
Branch: xcode11.3
Build date: 2020-02-18 14:13:32-0500

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/christophebovyn/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.0 (API level 24)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/christophebovyn/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.10
Hash: 2c49a7d
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:25:52 UTC

=== Android Device Manager ===

Version: 16.4.0.32
Hash: 7a5cb8b
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:26:14 UTC

=== Xamarin Designer ===

Version: 16.4.0.479
Hash: 074544417
Branch: remotes/origin/d16-4
Build date: 2020-01-22 22:50:22 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804080002
Git revision: 4f35aa7e44fb398379e512d0bfd6f8df8d34b5ac
Build date: 2020-02-27 16:16:52+00
Build branch: release-8.4
Xamarin extensions: 4f35aa7e44fb398379e512d0bfd6f8df8d34b5ac

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jan 23 06:52:12 PST 2020
    root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5

**Comment by jpobst** [comment]
This appears like you have 2 copies of Okio in your system: https://github.com/square/okio/issues/368.

I think this is because your packages ultimately reference 2 different bindings of Okio.

One is:
- `PDFTron.Android.Tools` 
  - `Karamunting.Android.Square.Picasso`
  - `Karamunting.Android.Square.OkHttp` 
  - `Karamunting.Android.Square.Okio`

Another one is:
- `ModernHttpClient` 
  - `Square.OkHttp`
  - `Square.OkIO`

Your best option is probably to stop using `ModernHttpClient` and use the newer included handlers which provide the same benefits as `ModernHttpClient`.  You can see that recommendation on their site: https://github.com/anaisbetts/ModernHttpClient.  "This project is not actively maintained. Consider using the handlers Xamarin provides."

Here is the documentation on selecting one of the included http handlers: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=macos.

**Comment by jpobst** [comment]
Hopefully this got you unstuck!  Closing.
