### ISSUE TITLE
AAB doesn't include files in assets subdirectories

### ISSUE THREAD

**Issue by FallenAngel97** [xamarin/xamarin-android#4970]
### Steps to Reproduce

1. Create an application of Xamarin Android
2. Add to Assets folder subfolder
3. Place there file
4. Archive it using context menu from right-clicking the solution

### Expected Behavior
In apks there should be subfolders for assets folder

### Actual Behavior
There is no subfolders in aab, but they exist if I select apk

### Version Information

Microsoft Visual Studio Community 2019
Version 16.6.5
VisualStudio.16.Release/16.6.5+30320.27
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA677
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.6.956.60315
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   16.6.956.60315
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.6.956.60315
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.956.60315
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.956.60315
Azure Functions and Web Jobs Tools

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.30014.67
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1064 (d16-6@b03f31e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.3.2 (ce0cc74)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by FallenAngel97** [comment]
Ok. I have investigated this issue a little bit more. If I make a bundle using command line like so:
https://www.appveyor.com/blog/2016/11/22/create-signed-aligned-xamarin-apk/
It does include my files in base-master_2.apk inside the extracted apks file. So the issue is with GUI option to Archive it. 
Any tips?
Because debug version is also missing these assets files, when deploying to device, if I press "Run" from the Visual Studio

**Comment by jonathanpeppers** [comment]
@FallenAngel97 I think this might be the same issue fixed in: https://github.com/xamarin/xamarin-android/pull/4786

Can you try VS 16.7 Preview and see if it's fixed there? You can install it side-by-side.

**Comment by FallenAngel97** [comment]
Can confirm - this issue cannot be repeated on the 16.7. Thanks, will wait for public release.
Closing this issue

**Comment by jonathanpeppers** [comment]
Fyi, I think it came to the stable channel sometime yesterday: https://docs.microsoft.com/xamarin/android/release-notes/11/11.0

**Comment by brendanzagaeski** [comment]
I'll add the template comment with that release information too to be thorough.

_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
