### ISSUE TITLE
[Bug] App deployment fails 

### ISSUE THREAD

**Issue by hadigityat** [xamarin/xamarin-android#4971]
### Description
Application builds fine, but deployment fails due to corrupt XML file, can't see which file because the logs are truncated with diagnostic level, and unable to locate the full "Deployment to Device" log on disk.

### Steps to Reproduce

1. Build the app, no errors seen (d8/r8 with shared mono runtime)
2. Deploy the app to device (non emulator)
3. Deployment fails due to corrupt xml binary file

### Expected Behavior
App deployment is successful
### Actual Behavior
Deployment finishes with error
### Basic Information
Exception occurred while executing:
    java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/xxx.apk
    	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:338)
    	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:906)
    	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)
    	at android.os.ShellCommand.exec(ShellCommand.java:103)
    	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26004)
    	at android.os.Binder.shellCommand(Binder.java:642)
    	at android.os.Binder.onTransact(Binder.java:540)
    	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3329)
    	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4768)
    	at android.os.Binder.execTransact(Binder.java:739)
    Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/xxx.apk
    	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1679)
    	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1637)
    	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:331)
    	... 9 more
    Caused by: java.io.FileNotFoundException: Corrupt XML binary file
    	at android.content.res.ApkAssets.nativeOpenXml(Native Method)
    	at android.content.res.ApkAssets.openXml(ApkAssets.java:152)
    	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1656)
    	... 11 more
    
      at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess (System.String output, System.String packageName) [0x00173] in /Users/builder/azdo/_work/204/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Internal/AdbOutputParsing.cs:348 
      at Mono.AndroidTools.AndroidDevice+<>c__DisplayClass95_0.<InstallPackage>b__0 (System.Threading.Tasks.Task`1[TResult] t) [0x00016] in /Users/builder/azdo/_work/204/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/AndroidDevice.cs:764 
      at System.Threading.Tasks.ContinuationTaskFromResultTask`1[TAntecedentResult].InnerInvoke () [0x00024] in <d8dc2ce16d10401483868046f78047e7>:0 
      at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-12/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
    --- End of stack trace from previous location where exception was thrown ---

- Version with issue:  VS version 8.6.8
- Last known good version: same version used to work
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  
  - Android: API 28
  - UWP:   
- Android Support Library Version: Support repository version 47.0.0
- Nuget Packages: 
- Affected Devices:

### Reproduction Link

Same issue reported by @VictorKochetkov under this ticket -not the original poster-
https://github.com/xamarin/Xamarin.Forms/issues/10707

Workaround suggested by @jonathanpeppers didn't apply to me as there is no cache file related to Xamarin in  ~/Library/Caches

**Comment by jonathanpeppers** [comment]
@hadigityat are you trying to deploy to an Android 11 device?

It sounds like you had trouble getting a log, can you run this:

    msbuild YourAndroid.csproj -t:Install -bl

This will do deploy the project to the attached device command-line and save an `msbuild.binlog` in the current directory. You can attach that file here. Thanks!

**Comment by hadigityat** [comment]
@jonathanpeppers I opened the msbuild.binlog and it doesn't have the full log it seems, rather more info about the project.
I have changed the extension to zip because I can't attach it here otherwise, just change it back please.
[msbuild.zip](https://github.com/xamarin/xamarin-android/files/4997706/msbuild.zip)

**Comment by jonathanpeppers** [comment]
@hadigityat the log worked! But I messed up, can you change the command to:

    msbuild YourAndroid.csproj -t:Clean,Install -bl

Then I can see what happens during `Build`, too. Thanks!

There is definitely something going on, you might also make these changes in your `.csproj`:
```diff
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
-    <DebugType>full</DebugType>
+    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>3</WarningLevel>
    <AndroidSigningKeyStore></AndroidSigningKeyStore>
<NoWarn>APT0000</NoWarn>
<JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
<AndroidPackageFormat>apk</AndroidPackageFormat>
<AndroidDexTool>d8</AndroidDexTool>
-<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
-<AndroidSupportedAbis>arm64-v8a;armeabi-v7a</AndroidSupportedAbis>
-<AndroidLinkTool>r8</AndroidLinkTool>
  </PropertyGroup>
```

1. `DebugType=portable` is recommended over `full`.
1. `EmbedAssembliesIntoApk=true` is turning off Fast Deployment
1. `AndroidLinkTool` shouldn't be used in a `Debug` build, as it will slow your build down.

**Comment by hadigityat** [comment]
@jonathanpeppers I play around with those options to help resolve the issue, I made the changes to csproj and did a clean build. I usually use the project options to change them, but don't know which option changes the DebugType? Can you help me find that in project options GUI?

Here is the log file:
[msbuild.zip](https://github.com/xamarin/xamarin-android/files/5002692/msbuild.zip)

**Comment by jonathanpeppers** [comment]
I think you are looking for this `Debug information` dropdown:

![Screen Shot 2020-07-30 at 2 23 11 PM](https://user-images.githubusercontent.com/840039/88965437-5f951f80-d270-11ea-89c3-191c27590996.png)

You can also right click and `Edit Project File` to edit the XML yourself. 

As for your actual problem, it seems like there is something strange going on. Are you able to share the broken `.apk` file? You can email me via the address on my [Github profile](https://github.com/jonathanpeppers).

**Comment by hadigityat** [comment]
I was looking into the csproj file, and found a lot of outdated packages and two packages that have different versions. This happens to me frequently where the csproj file is not properly updated when there are changes to the packages. After clearing those, the corrupt binary XML error is gone, however I'm facing the "java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList" immediately after the apk installation. 

This has happened to me before, I remember fixing it by switching to dx/updating proguard/firebase libs but I can no longer do that since third party  works with d8 only.  Adding the multidex.keep file for FirebaseInit didn't help as well as checking/unchecking multidex option, do you have any suggestions? Otherwise we can close this ticket, although I still don't know what exactly caused the corrupt file error because I can't see a non-truncated version of those logs.

**Comment by jonathanpeppers** [comment]
You shouldn't need a `multidex.keep` file anymore.

Do you have any proguard rules setup? In one of your logs you were setting `AndroidLinkTool=r8`, you probably need a rule to prevent it from stripping away something from Firebase.

I found an example where some folks were hitting this: https://github.com/xamarin/xamarin-android/issues/3391#issuecomment-516583110

**Comment by hadigityat** [comment]
I have all the proguard rules setup as mentioned in #3391 (comment), and also removed the r8 line from csproj. Another strange thing about this is that even if I removed that "AndroidLinkTool=r8" it still uses r8 when building. In the project options, there are three options and the first one is to not set it to anything and that results in r8 being used still. 

I removed the line "    <Optimize>true</Optimize>" from csproj, and after that Java.Lang.NoClassDefFoundError Failed resolution of: Lcom/google/firebase/iid/internal/FirebaseInstanceIdInternal;. This may have happened because I had a google-services.json in my project but also in a third party app that's integrated. After removing the google services file, it is working now. Thanks for your help!

**Comment by hadigityat** [comment]
The corrupt file error is still happening intermittently. I am emailing you the apk file.

**Comment by jonathanpeppers** [comment]
@hadigityat thanks send a "good" one and a "bad" one to compare, thanks!

**Comment by jonathanpeppers** [comment]
To update on this, the difference between the corrupt `.apk` file and working one was that the `AndroidManifest.xml` was somehow inside the app uncompressed:

![image](https://user-images.githubusercontent.com/840039/91723081-d586f200-eb60-11ea-90dc-5aaa2b0eecb0.png)

I wasn't able to reproduce this, so I think we need a build log of when it happens to look further, thanks.

**Comment by radekdoulik** [comment]
Our team is unable to investigate this issue further without the requested information - the diagnostic build log. Please update to the latest version of the product and if the problem still occurs, reply with the requested information.
