### ISSUE TITLE
FEATURE_IRIS and FEATURE_FACE not available (Android 9 and above)

### ISSUE THREAD

**Issue by saurabharora23** [xamarin/xamarin-android#4978]
### Steps to Reproduce

1. Switch your Android project to target Android 9.0.
2. Notice that PackageManager.FeatureIris and PackageManager.FeatureFace don't exist, so we can't check if these features are available on the device.

### Expected Behavior
These should be available to leverage BiometricPrompt fully
### Actual Behavior
These features are not present. But they are present in android documentation
Ref : https://developer.android.com/reference/android/content/pm/PackageManager#FEATURE_FACE,
         https://developer.android.com/reference/android/content/pm/PackageManager#FEATURE_IRIS

### Version Information

Visual Studio Community 2019 for Mac
Version 8.6.8 (build 2)
Installation UUID: 6db1332e-1dab-4707-bdc1-03ec4ad06741
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000106

Mono Framework MDK
Runtime:
	Mono 6.10.0.106 (2019-12/77769615db1) (64-bit)
	Package version: 610000106

Xamarin Designer
Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

Roslyn (Language Service)
3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

NuGet
Version: 5.6.0.6591

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.302/Sdks
SDK Versions:
	3.1.302
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.500
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.6
	3.0.0
	2.1.20
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.6
	2.0.5
	2.0.0
	1.1.2
	1.0.5

Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/saurabh/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Microsoft OpenJDK for Mobile
Java SDK: /Users/saurabh/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:42:50 UTC

Android Device Manager
Version: 16.6.0.96
Hash: 6e8b80b
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:43:28 UTC

Apple Developer Tools
Xcode 11.6 (16141)
Build 11E708

Xamarin.Mac
Version: 6.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

Xamarin.iOS
Version: 13.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

Build Information
Release ID: 806080002
Git revision: e999e2934e8c771fdf6494b80361dacef9427565
Build date: 2020-07-24 15:17:52-04
Build branch: release-8.6
Xamarin extensions: e999e2934e8c771fdf6494b80361dacef9427565

Operating System
Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Sun Jul  5 00:43:10 PDT 2020
    root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by jpobst** [comment]
According to the linked documentation, those members were added in API-29, which is Android 10.  You should see them if you target Android 10 or above.

Targeting Android 10:

![image](https://user-images.githubusercontent.com/179295/89556760-7a6b1500-d7d7-11ea-86aa-c33198478a3d.png)

**Comment by saurabharora23** [comment]
Thanks for the response. I am able to locate this now. 
Closing the bug.
Thanks
