### ISSUE TITLE
Ambiguity between 'Resource.Layout.Tabbar(Toolbar) and Resource.Layout.Tabbar(Toolbar)'

### ISSUE THREAD

**Issue by dansiegel** [xamarin/xamarin-android#4981]
## NOTE:

​Originally reported in the Prism repository and transferred to the Prism Templates.

https://github.com/PrismLibrary/Prism.Templates/issues/20

​As discussed with @dellis1972 in the Android Channel of the DotNetEvolution Discord.

> that sounds like two Resource.designer.cs files are being included. We have the normal one, and then a design time one which is used for code completion. I've only ever seen this on a Mac and then only for a design time build, not an actual app build. Its possible the combination of `AndroiduseIntermediateDesignerFile` and `AndroidUseManagedDesignTimeResourceGenerator` are causing a problem. We'd need to see a full diagnostic log for the problem in order to investigate.

Reproduction Link:

​https://github.com/wsigel/PrismError 

As indicated in chat, this is an issue that I am personally not able to replicate the issue as it builds as expected for me.

### Steps to Reproduce

1. Create a project with the Prism Template Pack
2. Build for Android

### Expected Behavior

display 'Welcome to Xamarin Forms and Prism!'

### Actual Behavior

Android.Views.InflationException: 'Binary XML file line PrismLibrary/Prism# 1: Binary XML file line PrismLibrary/Prism# 1: Error inflating class androidx.appcompat.widget.Toolbar' is thrown (see image)

### Version Information

To be provided by @wsigel or @BaseCrusher who have experienced the issue

### Log File

To be provided by @wsigel or @BaseCrusher who have experienced the issue

**Comment by BaseCrusher** [comment]
Some edits to initial post.

### Steps to Reproduce

1. Create a project with the Prism Template Pack
2. Build for Android (After the build is done the Ambiguity error is shown in VS)
3. Change the Android App TargetFramework to Android 9.0
4. Rebuild and launch the App.

### Some Additional Informations
Commenting the lines out that sets the Layouts for Tabbar and Toolbar, the App starts normaly.

Using:
Visual Studio Enterprise, Version 16.6.5
Prism Template Pack, Version 2.2.1
Prism.DryIoc.Forms, Version 7.2.0.1422
Crash appearing with Android 9 (Emulator and real device)
[Crash Log](https://pastebin.com/ZVm4xLcS)

If you need some additional informations let me know.
