### ISSUE TITLE
[Bug] Very slow performance when making calls to ASP.NET (ASMX) web service.

### ISSUE THREAD

**Issue by dmsi-leonidl** [xamarin/xamarin-android#4991]
### Description
After upgrading our Xamarin Forms project from VS 2017 (Xamarin Forms 4.2.0.848062) to VS 2019 (Xamarin Forms 4.6.0.800) during stress and performance testing we noticed significant performance degradation when downloading files from ASP.NET (ASMX) web service. This is happening for Android and iOS but the problem is especially severe for Android.
For Android project we tried to set:
   HTTPClient Implementation build option to Android,
   SSL/TLS Implementation build option to Native TLS 1.2+
but it didn't improve performance by much.

Testing procedure:
Our Xamarin Forms app sequentially downloads 150 files ( each files size is roughly 1 MB) from ASP.NET (ASMX) web service.
The results of our testing:
Android:
App built with VS 2019 (Xamarin Forms 4.6.0.800) is **35-45%** slower then app built with VS 2017 (Xamarin Forms 4.2.0.848062).
iOS:
App built with VS 2019 (Xamarin Forms 4.6.0.800) is **10-20%** slower then app built with VS 2017 (Xamarin Forms 4.2.0.848062).

We tried different IIS Authentication methods (Basic, Digest, Windows) and web service binding protocols (HTTP and HTTPS) but that didn't improve performance.

This is very serious issue for us and it is important to improve performance at least to the level of VS 2017 (Xamarin Forms 4.2.0.848062) build.

Any help or suggestions or workarounds will be greatly appreciated.

Thanks for help,

Leo

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: 4.6.0.800
- Last known good version: 4.2.0.848062
- IDE: Microsoft Visual Studio Enterprise 2019 Version 16.5.4
- Platform Target Frameworks: 
  - iOS:  10.3
  - Android: 10.0 
  - UWP:  18362 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Essentials, SyncFusion, Symbol.XamarinEMDK, SkiaSharp, Rg.Plugins.Popup, ZXing.Net.Mobile.Forms, Microsoft.Data.Sqlite, MathParser.org-mXparser
- Affected Devices: All

### Reproduction Link
https://github.com/xamarin/Xamarin.Forms/files/5044431/TestAsmxService.zip

**Comment by dmsi-leo** [comment]
@PureWeen
We found another serious issue when calling  ASMX web services asynchronously using web service proxy when IIS authentication is set to Digest. If we try to download multiple files (to reproduce this issue number of files should be more than 100) from web service asynchronously we suddenly get 'Unauthorized 401 Error' from the web server.
Here is an example of how we calling web service to download files asynchronously:

                            foreach (string strFile in strFilesArray)
                            {
                                strFile.Trim();
                                oListTask.Add(proxy.DownloadFileAsync(strFile));
                            }

                            Task.WaitAll(oListTask.ToArray());

Also the same issue exists for our XF iOS project. It looks like everything works fine if IIS is set up for Basic or Windows authentication.

I attached modified VS 2017 solution that we provided earlier to demonstrate problems with asynchronous web service calls. Please follow these steps to reproduce the issue:
1. Rebuild TestMobileClient1 project.
2. In IIS manager disable Basic and enable Digest authentication.
3. To reproduce this issue we placed ~150 files into "TestFiles" folder.
4. When running TestMobileClient1 app provide windows account credentials and click"Download Files Async" button.

Thank you.
[TestAsmxService.zip](https://github.com/xamarin/xamarin-android/files/5105795/TestAsmxService.zip)

**Comment by dmsi-leo** [comment]
Hi,

I was wondering if there was any progress made on this issue?

Thanks,
Leo

**Comment by fddion** [comment]
Experiencing same issue on 4.8.0 1821, It takes over 60 secs to load a list of items from .asmx service but the same proxy takes 20ms on a console app.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
