### ISSUE TITLE
ViewTreeObserver on View.cs is nullable

### ISSUE THREAD

**Issue by joshuangfraedom** [xamarin/xamarin-android#5002]
### Steps to Reproduce

1. Look at View.cs 's ViewTreeObserver
2. Compare to [View.java over at googlesource](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/View.java)
3. ViewTreeObserver cannot be null.

### Expected Behavior
I don't get potential null reference warnings when using ViewTreeObserver in Xamarin Android

### Actual Behavior
I get potential null reference warnings

### Version Information

=== Visual Studio Professional 2019 for Mac ===

Version 8.7 (build 2037)
Installation UUID: bd277059-e590-458e-a151-c1b16c194a4e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000089

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.89 (2020-02/e59c1cd70f4) (64-bit)
	Package version: 612000089

=== Roslyn (Language Service) ===

3.7.0-6.20371.12+917b9dfae12e3b6cb266a3c062fb20a1e9d5fb06

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.302/Sdks
SDK Versions:
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.100
	3.0.101
	3.0.100
	3.0.100-preview9-014004
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.0
	3.0.1
	3.0.0
	3.0.0-preview9-19423-09
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Professional)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Professional)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Xamarin.Android ===

Version: 11.0.0.3 (Visual Studio Professional)
Commit: xamarin-android/d16-7/aca845b
Android SDK: /Users/jng/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.1

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jng/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/dev/jmt/d16-7readconfig~2
Build date: 2020-07-23 22:38:02 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-23 22:38:26 UTC

=== Build Information ===

Release ID: 807002037
Git revision: b7706774ff5a1b761a7eb7f2d116d0d2c29ad87c
Build date: 2020-07-31 04:14:15-04
Build branch: release-8.7
Xamarin extensions: b7706774ff5a1b761a7eb7f2d116d0d2c29ad87c

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Sun Jul  5 00:43:10 PDT 2020
    root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

### Log File

N/A

**Comment by jpobst** [comment]
We get our nullable reference attributes by automatically reading them from the compiled Java code.  In this case, Google has not annotated that method as `@NonNull`, so we do not annotate it as `NotNull` either.

If/when Google updates the Android source, our assemblies will get automatically updated as well.

You can try filing a bug with Google to see if they fix it.  I am not sure what their policy is regarding adding these annotations.  (Other than I know 

As a workaround, you can use the null forgiving operator (`!`) to let the compiler know that you know this method does not return `null`:

```
var tree = my_view.ViewTreeObserver!;
```

Hope this helps!
