### ISSUE TITLE
VS Studio 16.8.0 Prev 1.0 - Android Designer

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#5018]
This version of VS is the first version where I have been able to open designer files without getting the error first mentioned in issue 4317 when using 15.5.0 Prev 2.0. I don't recall seeing anything about fixing it in the release notes, so I'm wondering if the problem may have been due to something else, in particular, something re my setup etc not related to the designer.

The designer still has one small problem - it complains about any `android:layout_weight` value with a red squiggly "Must specify unit". Android Studio does not.

> VS bug [#1174551](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1174551)

**Comment by brendanzagaeski** [comment]
_Cross-referencing note for the Xamarin team_

A matching Developer Community item: <https://developercommunity.visualstudio.com/content/problem/1149084/on-android-layout-androidlayout-weight1-appears-as.html>
