### ISSUE TITLE
Is it possible to install an older version of Xamarin.Android?

### ISSUE THREAD

**Issue by xplatform** [xamarin/xamarin-android#5033]
Is it possible to install an older version of Xamarin.Android, and overwrite the Xamarin.Android that comes with Visual Studio?

We ran into a crash as mentioned in https://github.com/xamarin/xamarin-android/issues/4548. Currently we can only use Visual Studio 16.5.5. All VS 16.6.x and 16.7.x would produce the crash. I tried downloading “Xamarin.Android 10.2 (d16-5) for Windows+Visual Studio 2019” from here (https://github.com/xamarin/xamarin-android/blob/master/README.md#downloads), and installing it on my computer, which has VS16.7.2 installed, but it gave me an error.

**Comment by brendanzagaeski** [comment]
On the team, when we want to check something with a custom Xamarin.Android SDK version, we usually swap out the Xamarin.Android SDK files in the Visual Studio installation directly. See https://github.com/xamarin/xamarin-android/issues/4053#issuecomment-567431280 for those steps. I'll tentatively close this as answered by that comment, but if you run into trouble when trying those steps, feel free to reply by here, and I can take a look.

One other thing to mention for completeness, though I suspect it might not be what you're looking for in this case, is that it's possible to install an earlier version of the full Visual Studio product using the installers from <https://docs.microsoft.com/visualstudio/releases/2019/history>. That page also includes BuildTools packages that can be used for build servers.
