### ISSUE TITLE
VS Studio 16.8.0 Prev 1.0 Android Designer - was fixed - now broken again

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#5042]
In issue 5018 I reported that issue 4317 was now fixed. Since then I have been adding a number of new layouts and have just noticed that all my layouts now load with the original error message - so what I thought was fixed is broken again.

All these new layouts have been originally copied from a retired VS 16.6.2 project into new empty layouts using the android studio designer, modified in AS and then copy/pasted into a new created empty layout in VS 16.8.0 P1.0 project and then saved. 

Once one of the layouts gives the error contained in 4317 then all the layouts within the project that was previously opening successfully, load with the same error as in issue 4317.

None of the layouts has any effect at run time, the content of each appears as designed, so the problem is only related to the Xamarin designer.

> VS bug [#1179185](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1179185)

**Comment by mclillill** [comment]
I have problems with VS 16.8.1 and binding generation for this package: https://github.com/mclillill/AndroidPdfViewer
It does not seem to generate the binding für class PDFView. May be related.
