### ISSUE TITLE
Preregister startup JNI types when using jnimarshalmethod-gen

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5047]
Idea: use the AOT startup profile to identify types registered during startup and pre-register them. That should avoid slower registration with magic prefill involved and thus speed-up the application startup.

**Comment by grendello** [comment]
Revision 8bc7a3e84f95e70fe12790ac31ecd97957771cb2 and others mentioned in its commit message took care of it by generating the native symbols which completely removes the need for dynamic registration.
