### ISSUE TITLE
High number of errors in DesignTime builds with Resource.Designer.cs loaded twice with AndroidUseIntermediateDesignerFile

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#5069]
### Steps to Reproduce

1. Create an Xamarin.Android application
1. Add any AndroidX library that exposes android resources
1. Set `<AndroidUseIntermediateDesignerFile>true</AndroidUseIntermediateDesignerFile>`
1. Build once

### Expected Behavior

No design-time errors

### Actual Behavior

Notice that the error list window contains a very large number of errors, and if it's not the case, open the Resource.Designer.cs file manually in the obj folder.

### Workaround

Adding the following at the end of the project file will work around the issue.
```xml
<Project ...>
	 ...
	<Target Name="Issue3897Workaround" 
		Condition=" '$(ManagedDesignTimeBuild)' == 'True' "
		AfterTargets="_RemoveLegacyDesigner">
		<!-- https://github.com/unoplatform/uno/issues/3897 -->
		<ItemGroup>
			<Compile Remove="$(_AndroidResourceDesignerFile)"/>
		</ItemGroup>
	</Target>
</Project>
```

This target removes the `_AndroidResourceDesignerFile` when a design time build runs, to avoid a conflict with: 

https://github.com/xamarin/xamarin-android/blob/307355f8d9bc9fc49f152e67efafd728c0ec0e2f/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L932

Which also includes in `Compile` a design-time only version of `Resource.Designer.cs`

### Version Information

VS 16.7.x

**Comment by dellis1972** [comment]
@jeromelaban I suspect this issue is fixed by the following change https://github.com/xamarin/xamarin-android/commit/99ec9f231bc52b4e9c451b955f2493517afc1fc2#diff-db39bf07b89b50eaab8ab2001546310cR495

I will add a unit test to see if this is the case.

**Comment by dimonovdd** [comment]
@dellis1972 @jeromelaban Did you manage to test this? Is this issue relevant at the moment?

**Comment by jeromelaban** [comment]
After the fix mentioned, I was not able to reproduce this issue. I think it can be closed.
