### ISSUE TITLE
Resources not generating when building from command line after updating to Xamarin.Android 11.0.2.0

### ISSUE THREAD

**Issue by RiccardoBelli** [xamarin/xamarin-android#5074]
Build is failing when executed from command line with msbuild command. Building from IDE works fine.
It seems that the resource designer file is not generated with the former.

In the previous version, Xamarin.Android 10.3, everything worked well.

### Steps to Reproduce

1. Update to Xamarin.Android 11.0.2.0
2. Build your project using the command msbuild from command line 

### Expected Behavior

The build should succeed.

### Actual Behavior

The build fails with an error related to the Resource.design.cs.
In my case is:
`Dialogs/ProgressWheel.cs(34,49): error CS0117: 'Resource.Color' does not contain a definition for 'controlColor'
AndroidDevice.cs(75,113): error CS0117: 'Resource.Color' does not contain a definition for 'controlColor' 
Dialogs/ProgressDialog.cs(45,55): error CS0117: 'Resource.Layout' does not contain a definition for 'loadingProgress_dialog'
DeviceAuth/FingerprintDialog.cs(40,56): error CS0117: 'Resource.Layout' does not contain a definition for 'fingerprint_dialog'
DeviceAuth/FingerprintDialog.cs(41,70): error CS0117: 'Resource.Id' does not contain a definition for 'fingerprint_description
...`
 
### Version Information

Visual Studio Community 2019 for Mac
Version 8.7.4

Xamarin.Android
Version: 11.0.2.0

**Comment by dellis1972** [comment]
What is the command line you are using to run the build? Does it include the `/restore` argument? Which target are you calling?

**Comment by dellis1972** [comment]
Can you try without the `maxcpucount` switch. I'm not sure the parallel build system on Mac is 100% working yet. 
If that doesn't work, can you provide a msbuid.binlog for the failure. You can get that by adding a `/bl` to your command line.

**Comment by RiccardoBelli** [comment]
Wow, it really was `maxcpucount`. I never would have thought that.

We knew `maxcpucount` wasn't supported in the previous version (it gave a warning), but we left it in there in the hope of a future support.
It seems that the last release does take in account this argument but is not working properly, as you said.

Thank you!

**Comment by dellis1972** [comment]
I think we can close this issue since its not really and android issue but an msbuild one.
