### ISSUE TITLE
Crash condition `xref_count == xref_index' not met

### ISSUE THREAD

**Issue by rgroenewoudt** [xamarin/xamarin-android#5078]
I'm currently running into an old crash with the latest VS2019 16.7.2

The old related bug can be found at https://github.com/mono/mono/issues/9314, which reports fixed in 16.6.

### Steps to Reproduce
I have currently not an small application to reproduce.
I can reproduce it in our app on XCover 4 and Blackview 6800 Pro.

AndroidEnableSGenConcurrent is enabled.
Default bridge implementation is used. Nursury size is set to 8M

(No crash when switching to 'new' bridge-implementation)

### Actual Behavior
Crash:
```
6870  7649 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 7649 (Thread-73)
 7652  7652 I crash_dump64: obtaining output fd from tombstoned
 1058   561   561 I /system/bin/tombstoned: received crash request for pid 6870
 7652  7652 I crash_dump64: performing dump of process 6870 (target tid = 7649)
 6870  7649 I libc    : orig_dumpable: 0
 7652  7652 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 7652  7652 F DEBUG   : Build fingerprint: 'Blackview/BV6800Pro/BV6800Pro:8.0.0/O00623/1565925933:user/release-keys'
 7652  7652 F DEBUG   : Revision: '0'
 7652  7652 F DEBUG   : ABI: 'arm64'
 7652  7652 F DEBUG   : pid: 6870, tid: 7649, name: Thread-73  >>> com.sequrix.app <<<
 7652  7652 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
 7652  7652 F DEBUG   : Abort message: '* Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/metadata/sgen-tarjan-bridge.c:1172, condition `xref_count == xref_index' not met, function:processing_build_callback_data, xref_count is 60 but we added 53 xrefs
 7652  7652 F DEBUG   : '
 7652  7652 F DEBUG   :     x0   0000000000000000  x1   0000000000001de1  x2   0000000000000006  x3   0000000000000008
 7652  7652 F DEBUG   :     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000080
 7652  7652 F DEBUG   :     x8   0000000000000083  x9   0d494a0efa1c6e25  x10  0000000000000000  x11  0000000000000001
 7652  7652 F DEBUG   :     x12  0000007690175b00  x13  0000000000000038  x14  ffffffffffffffff  x15  00004675dc4ed6f6
 7652  7652 F DEBUG   :     x16  00000076c22e82f8  x17  00000076c22896cc  x18  0000000000000032  x19  0000000000001ad6
 7652  7652 F DEBUG   :     x20  0000000000001de1  x21  000000767dfff588  x22  00000076a5967880  x23  000000769ef04368
 7652  7652 F DEBUG   :     x24  00000076a596b000  x25  00000076a5967000  x26  0000000000000000  x27  0000000000000003
 7652  7652 F DEBUG   :     x28  00000076a5967000  x29  000000767dffd8c0  x30  00000076c223c780
 7652  7652 F DEBUG   :     sp   000000767dffd880  pc   00000076c22896d4  pstate 0000000060000000
 7652  7652 F DEBUG   :
 7652  7652 F DEBUG   : backtrace:
 7652  7652 F DEBUG   :     #00 pc 000000000006a6d4  /system/lib64/libc.so (tgkill+8)
 7652  7652 F DEBUG   :     #01 pc 000000000001d77c  /system/lib64/libc.so (abort+88)
 7652  7652 F DEBUG   :     #02 pc 000000000028cfb8  /data/app/com.sequrix.app-gLYPUtXimGaHxE60baII9w==/lib/arm64/libmonosgen-2.0.so (monoeg_assert_abort+24)
```

### Version Information
Microsoft Visual Studio Enterprise 2019
Version 16.7.2
VisualStudio.16.Release/16.7.2+30413.136
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA326
Microsoft Visual C++ 2019

.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

C# Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper 2020.2.1   Build 202.0.20200820.125348
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResXManager   1.44.3748.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Analysis Services   15.0.19215.0
Microsoft SQL Server Analysis Services Designer 
Version 15.0.19215.0

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

SQL Server Reporting Services   15.0.19124.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19124.0

SsmsVsIntegration   1.0
Information about my package

Switch Startup Project   4.1.71
Provides a toolbar dropdown box  to switch between startup projects.

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.30309.115
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.440 (d16-7@358f3c6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 (817b6f72a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jiro-san** [comment]
Hello, we had a similar issue also with Xamarin 9 some time ago, and the issue was also reproduced in Xamarin 11.0.2.0 too (issue is not really random, we have a repro step but it involves using our application that is very complex).

Anyway **we do not reproduce this issue with Xamarin 11.1.0.17.**

@rgroenewoudt can you check with latest Xamarin (or at least the 11.1.0.17) if you can reproduce? Maybe it was fixed as a side effect of something (I hope!).

**Comment by rgroenewoudt** [comment]
@jiro-san I cannot reproduce this error on 11.1.0.26 (VS2019 16.8.4)

**Comment by jiro-san** [comment]
@rgroenewoudt great this is good news for us because we can be confident that it has certainly been fixed. Thanks.
