### ISSUE TITLE
Issue with generation binding library for nested and inner classes

### ISSUE THREAD

**Issue by redradist** [xamarin/xamarin-android#5091]
### Steps to Reproduce

1. Get **HERE-sdk.aar** from https://developer.here.com or other *.jar/*.aar with inner or nested Java classes
2. Try to build binding library
3. Got error with message duplicate members

I have created also issue on the forum:
https://forums.xamarin.com/discussion/184666/xamarin-java-binding-library-multiple-already-defined-errors#latest

### Expected Behavior
Should properly generate binding library

### Actual Behavior
Error for inner and nested classes that have base class ... in my case VariantMap<?>

### Version Information
Latest at the current moment: Visual Studio Community 2019 Preview, 16.8.0 Preview 2.1

### Log File

Log messages:

Com.Here.Sdk.Analytics.HEREAnalytics.cs(84, 20): [CS0102] The type 'HEREAnalytics.Options' already contains a definition for 'cb_getMap'
  Com.Here.Sdk.Analytics.HEREAnalytics.cs(86, 20): [CS0111] Type 'HEREAnalytics.Options' already defines a member called 'GetGetMapHandler' with the same parameter types
  Com.Here.Sdk.Analytics.HEREAnalytics.cs(93, 18): [CS0111] Type 'HEREAnalytics.Options' already defines a member called 'n_GetMap' with the same parameter types
  Com.Here.Sdk.Analytics.HEREAnalytics.cs(220, 20): [CS0102] The type 'HEREAnalytics.Properties' already contains a definition for 'cb_getMap'
  Com.Here.Sdk.Analytics.HEREAnalytics.cs(222, 20): [CS0111] Type 'HEREAnalytics.Properties' already defines a member called 'GetGetMapHandler' with the same parameter types
  Com.Here.Sdk.Analytics.HEREAnalytics.cs(229, 18): [CS0111] Type 'HEREAnalytics.Properties' already defines a member called 'n_GetMap' with the same parameter types
  Com.Here.Sdk.Analytics.HEREAnalytics.cs(322, 20): [CS0102] The type 'HEREAnalytics.Traits' already contains a definition for 'cb_getMap'
  Com.Here.Sdk.Analytics.HEREAnalytics.cs(324, 20): [CS0111] Type 'HEREAnalytics.Traits' already defines a member called 'GetGetMapHandler' with the same parameter types
  Com.Here.Sdk.Analytics.HEREAnalytics.cs(331, 18): [CS0111] Type 'HEREAnalytics.Traits' already defines a member called 'n_GetMap' with the same parameter types

**Comment by jpobst** [comment]
Are you able to create a repro project you can attach to this issue? `HERE-sdk.aar` doesn't appear to be publicly available.

**Comment by redradist** [comment]
> 
> 
> Are you able to create a repro project you can attach to this issue? `HERE-sdk.aar` doesn't appear to be publicly available.

@jpobst I have added test wrapper library https://github.com/redradist/TestHereMap.Premium.Android

**Comment by jpobst** [comment]
This doesn't seem to be related to nested/inner classes, I think it's more about our weak Java generics support or C#'s lack of covariant return types.

The decompiled Java is roughly this:
```
class VariantMap<T extends VariantMap> {
  public Map<String, Variant> getMap() {
    return this.variants;
  }
}

public static class Properties extends VariantMap<Properties> {
}
```

However `class-parse` reports that there is an additional `public Map getMap()` method on `Properties`:
```
<class abstract="false" deprecated="not deprecated" extends="java.lang.Object" extends-generic-aware="java.lang.Object" jni-extends="Ljava/lang/Object;" final="false" name="VariantMap" static="false" visibility="" jni-signature="Lcom/here/sdk/analytics/VariantMap;">
  <typeParameters>
    <typeParameter name="T" classBound="com.here.sdk.analytics.VariantMap" jni-classBound="Lcom/here/sdk/analytics/VariantMap;">
      <genericConstraints>
        <genericConstraint type="com.here.sdk.analytics.VariantMap">
        </genericConstraint>
      </genericConstraints>
    </typeParameter>
  </typeParameters>
  <method abstract="false" deprecated="not deprecated" final="false" name="getMap" jni-signature="()Ljava/util/Map;" bridge="false" native="false" return="java.util.Map&lt;java.lang.String, com.here.sdk.analytics.internal.Variant&gt;" jni-return="Ljava/util/Map&lt;Ljava/lang/String;Lcom/here/sdk/analytics/internal/Variant;&gt;;" static="false" synchronized="false" synthetic="false" visibility="public">
  </method>
</class>

<class abstract="false" deprecated="not deprecated" extends="com.here.sdk.analytics.VariantMap" extends-generic-aware="com.here.sdk.analytics.VariantMap&lt;com.here.sdk.analytics.HEREAnalytics.Properties&gt;" jni-extends="Lcom/here/sdk/analytics/VariantMap;" final="false" name="HEREAnalytics.Properties" static="true" visibility="public" jni-signature="Lcom/here/sdk/analytics/HEREAnalytics$Properties;">
  <constructor deprecated="not deprecated" final="false" name="HEREAnalytics.Properties" jni-signature="()V" bridge="false" static="false" type="com.here.sdk.analytics.HEREAnalytics.Properties" synthetic="false" visibility="public">
  </constructor>
  <method abstract="false" deprecated="not deprecated" final="false" name="getMap" jni-signature="()Ljava/util/Map;" bridge="true" native="false" return="java.util.Map" jni-return="Ljava/util/Map;" static="false" synchronized="false" synthetic="true" visibility="public">
  </method>
</class>
```

This method does not have the same return type as its base method:
```
// VariantMap
public Map<String, Variant> getMap() { }

// Properties
public Map getMap() { }
```

Because we don't recognize them as the "same" method (because they have different return types and C# does not support covariant return types), we attempt to generate both methods:
```
[Register ("getMap", "()Ljava/util/Map;", "GetGetMapHandler")]
public virtual unsafe global::System.Collections.Generic.IDictionary<string, global::Com.Here.Sdk.Analytics.Internal.Variant> GetMap ()

public virtual unsafe global::System.Collections.IDictionary Map {
[Register ("getMap", "()Ljava/util/Map;", "GetGetMapHandler")]
get { }
}
```

These methods both have the same Java name, so we end up generating plumbing with the same names (`GetGetMapHandler`), causing the C# compile errors.

There are some additional questions around why we are generating a method from a base class in `Properties`, and why `Properties` inherits `Object` instead of `VariantMap` I still need to explore.

A workaround is to remove the `getMap` method from `Properties` class so that the conflict no longer exists:
```
<remove-node path="/api/package[@name='com.here.sdk.analytics']/class[@name='HEREAnalytics.Properties']/method[@name='getMap']" />
<remove-node path="/api/package[@name='com.here.sdk.analytics']/class[@name='HEREAnalytics.Options']/method[@name='getMap']" />
<remove-node path="/api/package[@name='com.here.sdk.analytics']/class[@name='HEREAnalytics.Traits']/method[@name='getMap']" />
```

or to remove the `getMap` method from the `VariantMap` class:
```
<remove-node path="/api/package[@name='com.here.sdk.analytics']/class[@name='VariantMap']/method[@name='getMap']" />
```

**Comment by redradist** [comment]
> 
> 
> This doesn't seem to be related to nested/inner classes, I think it's more about our weak Java generics support or C#'s lack of covariant return types.
> 
> The decompiled Java is roughly this:
> 
> ```
> class VariantMap<T extends VariantMap> {
>   public Map<String, Variant> getMap() {
>     return this.variants;
>   }
> }
> 
> public static class Properties extends VariantMap<Properties> {
> }
> ```
> 
> However `class-parse` reports that there is an additional `public Map getMap()` method on `Properties`:
> 
> ```
> <class abstract="false" deprecated="not deprecated" extends="java.lang.Object" extends-generic-aware="java.lang.Object" jni-extends="Ljava/lang/Object;" final="false" name="VariantMap" static="false" visibility="" jni-signature="Lcom/here/sdk/analytics/VariantMap;">
>   <typeParameters>
>     <typeParameter name="T" classBound="com.here.sdk.analytics.VariantMap" jni-classBound="Lcom/here/sdk/analytics/VariantMap;">
>       <genericConstraints>
>         <genericConstraint type="com.here.sdk.analytics.VariantMap">
>         </genericConstraint>
>       </genericConstraints>
>     </typeParameter>
>   </typeParameters>
>   <method abstract="false" deprecated="not deprecated" final="false" name="getMap" jni-signature="()Ljava/util/Map;" bridge="false" native="false" return="java.util.Map&lt;java.lang.String, com.here.sdk.analytics.internal.Variant&gt;" jni-return="Ljava/util/Map&lt;Ljava/lang/String;Lcom/here/sdk/analytics/internal/Variant;&gt;;" static="false" synchronized="false" synthetic="false" visibility="public">
>   </method>
> </class>
> 
> <class abstract="false" deprecated="not deprecated" extends="com.here.sdk.analytics.VariantMap" extends-generic-aware="com.here.sdk.analytics.VariantMap&lt;com.here.sdk.analytics.HEREAnalytics.Properties&gt;" jni-extends="Lcom/here/sdk/analytics/VariantMap;" final="false" name="HEREAnalytics.Properties" static="true" visibility="public" jni-signature="Lcom/here/sdk/analytics/HEREAnalytics$Properties;">
>   <constructor deprecated="not deprecated" final="false" name="HEREAnalytics.Properties" jni-signature="()V" bridge="false" static="false" type="com.here.sdk.analytics.HEREAnalytics.Properties" synthetic="false" visibility="public">
>   </constructor>
>   <method abstract="false" deprecated="not deprecated" final="false" name="getMap" jni-signature="()Ljava/util/Map;" bridge="true" native="false" return="java.util.Map" jni-return="Ljava/util/Map;" static="false" synchronized="false" synthetic="true" visibility="public">
>   </method>
> </class>
> ```
> 
> This method does not have the same return type as its base method:
> 
> ```
> // VariantMap
> public Map<String, Variant> getMap() { }
> 
> // Properties
> public Map getMap() { }
> ```
> 
> Because we don't recognize them as the "same" method (because they have different return types and C# does not support covariant return types), we attempt to generate both methods:
> 
> ```
> [Register ("getMap", "()Ljava/util/Map;", "GetGetMapHandler")]
> public virtual unsafe global::System.Collections.Generic.IDictionary<string, global::Com.Here.Sdk.Analytics.Internal.Variant> GetMap ()
> 
> public virtual unsafe global::System.Collections.IDictionary Map {
> [Register ("getMap", "()Ljava/util/Map;", "GetGetMapHandler")]
> get { }
> }
> ```
> 
> These methods both have the same Java name, so we end up generating plumbing with the same names (`GetGetMapHandler`), causing the C# compile errors.
> 
> There are some additional questions around why we are generating a method from a base class in `Properties`, and why `Properties` inherits `Object` instead of `VariantMap` I still need to explore.
> 
> A workaround is to remove the `getMap` method from `Properties` class so that the conflict no longer exists:
> 
> ```
> <remove-node path="/api/package[@name='com.here.sdk.analytics']/class[@name='HEREAnalytics.Properties']/method[@name='getMap']" />
> <remove-node path="/api/package[@name='com.here.sdk.analytics']/class[@name='HEREAnalytics.Options']/method[@name='getMap']" />
> <remove-node path="/api/package[@name='com.here.sdk.analytics']/class[@name='HEREAnalytics.Traits']/method[@name='getMap']" />
> ```
> 
> or to remove the `getMap` method from the `VariantMap` class:
> 
> ```
> <remove-node path="/api/package[@name='com.here.sdk.analytics']/class[@name='VariantMap']/method[@name='getMap']" />
> ```

@jpobst Acctually I do not get where you found this:
```java
// Properties
public Map getMap() { }
```
`Properties` is pretty simple class:
```java
    public static class Properties extends VariantMap<HEREAnalytics.Properties> {
        public Properties() {
        }

        public HEREAnalytics.Properties addHereKind(String var1) {
            this.put("hereKind", var1);
            return this;
        }
    }
```

There is no `getMap()` for `Properties` ?!

Ohhh, I get simple like parser mixed `HEREAnalytics.Properties` with `java.util.Properties` ... now I get ...

Maybe it is missed package handling or something like this ...

**Comment by jpobst** [comment]
While the _source code_ for `Properties` may not show a `getMap()` method, there is one in the _compiled_ Java:
```
> javap -v HEREAnalytics$Properties

Classfile /C:/code/temp/TestHereMap.Premium.Android/Jars/HEREAnalytics$Properties.class
  Last modified Jan 1, 1981; size 871 bytes
  MD5 checksum ccbf934022d68be5df02a97141ef3c99
  Compiled from "HEREAnalytics.java"
public class com.here.sdk.analytics.HEREAnalytics$Properties extends com.here.sdk.analytics.VariantMap<com.here.sdk.analytics.HEREAnalytics$Properties>
  minor version: 0
  major version: 51
  flags: ACC_PUBLIC, ACC_SUPER

<...>

  public java.util.Map getMap();
    descriptor: ()Ljava/util/Map;
    flags: ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #27                 // Method com/here/sdk/analytics/VariantMap.getMap:()Ljava/util/Map;
         4: areturn
      LineNumberTable:
        line 1: 1

<...>
```

**Comment by redradist** [comment]
@jpobst
> 
> 
> While the _source code_ for `Properties` may not show a `getMap()` method, there is one in the _compiled_ Java:
> 
> ```
> > javap -v HEREAnalytics$Properties
> 
> Classfile /C:/code/temp/TestHereMap.Premium.Android/Jars/HEREAnalytics$Properties.class
>   Last modified Jan 1, 1981; size 871 bytes
>   MD5 checksum ccbf934022d68be5df02a97141ef3c99
>   Compiled from "HEREAnalytics.java"
> public class com.here.sdk.analytics.HEREAnalytics$Properties extends com.here.sdk.analytics.VariantMap<com.here.sdk.analytics.HEREAnalytics$Properties>
>   minor version: 0
>   major version: 51
>   flags: ACC_PUBLIC, ACC_SUPER
> 
> <...>
> 
>   public java.util.Map getMap();
>     descriptor: ()Ljava/util/Map;
>     flags: ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
>     Code:
>       stack=1, locals=1, args_size=1
>          0: aload_0
>          1: invokespecial #27                 // Method com/here/sdk/analytics/VariantMap.getMap:()Ljava/util/Map;
>          4: areturn
>       LineNumberTable:
>         line 1: 1
> 
> <...>
> ```

Okay, I got this ;)

Will it be fixed ?

**Comment by jpobst** [comment]
I would definitely suggest using the `metadata` provided to fix this, as even if we fixed it today it would take several months before the fix is in a stable release..

**Comment by redradist** [comment]
@jpobst 
> 
> 
> I would definitely suggest using the `metadata` provided to fix this, as even if we fixed it today it would take several months before the fix is in a stable release..

Okay, I will use `metadata`, but anyway as for me it is an issue on parser side and it should be fixed from my point of view ...

**Comment by jpobst** [comment]
Yep, it is definitely an issue that would ideally be solved by the generator.  Unfortunately, there are tons of issues that would ideally be solved in generator.  Some of them can be fixed.  Some of them can't really be fixed, as Java doesn't provide us enough information to automatically make a "correct" decision.

This is why we have `metadata`.  Both to work around things that haven't been fixed yet, and to work around things that can't be fixed.  😉

**Comment by redradist** [comment]
> 
> 
> Yep, it is definitely an issue that would ideally be solved by the generator. Unfortunately, there are tons of issues that would ideally be solved in generator. Some of them can be fixed. Some of them can't really be fixed, as Java doesn't provide us enough information to automatically make a "correct" decision.
> 
> This is why we have `metadata`. Both to work around things that haven't been fixed yet, and to work around things that can't be fixed. 😉

@jpobst This solution do not help completely, because there other issues with wrapping this library ...
Have you observed other issues ?

**Comment by jpobst** [comment]
Most libraries require additional work to properly bind them.  Here's some resources to help:

https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/customizing-bindings/java-bindings-metadata
https://gist.github.com/JonDouglas/dda6d8ace7d071b0e8cb
