### ISSUE TITLE
CancellationToken's delay ignored in Xamarin.Android while using HttpClient

### ISSUE THREAD

**Issue by evgenyvalavin** [xamarin/xamarin-android#5096]
### Steps to Reproduce

1. Create new project in VS 2019
2. Paste the code down below
```
var httpclient = new HttpClient();
using CancellationTokenSource tokenSource = new CancellationTokenSource(2_000);
try
{
httpclient.GetAsync(“https://google.com:4552”, tokenSource.Token).GetAwaiter().GetResult();
}
catch (Exception e)
{
}
```
3. Run the project

### Expected Behavior
The OperationCanceledException is thrown in 2 secs.

### Actual Behavior
The OperationCanceledException is not thrown in 2 secs.

### Version Information
1. Worked fine in VS 2017.
2. Doesn't work normally since VS 2019.

**Comment by evgenyvalavin** [comment]
Sorry, missed two lines of code.

**Comment by jpobst** [comment]
This appears to be affected by the `HttpClient` setting available in:
* Project Properties
* Android Options
* Advanced
* HttpClient

Based on my testing, `Default` and `Managed` do not cancel after 2 seconds, while `Android` and `Legacy` do cancel after 2 seconds.

Our project templates set `Android`, so this is our current recommended option.  I would suggest trying out that setting if you aren't already using it.

**Comment by evgenyvalavin** [comment]
Thank for the information @jpobst . Looks like the issue was fixed for Android implementation. I've been testing all HTTP Client implementations back in May. None of them worked correctly, event Android implementation.
I also reported about the issue to VS dev community back then: https://developercommunity.visualstudio.com/content/problem/1072347/cancellationtokens-delay-ignored-in-xamarinandroid.html

**Comment by evgenyvalavin** [comment]
Btw, there was no Legacy HttpClient implementation as I remember. I did find any info about it.

**Comment by jpobst** [comment]
Glad that `Android` works for you now.  There was probably some bug fix in the past few months for it.

I tested this with `Managed` in the upcoming .NET 6, and it is fixed there as well.

One of the main benefits of merging Xamarin with .NET is that they will share the base class libraries, so we will have a lot fewer issues where something works on .NET and not Xamarin.

Given that `Android` works today, and `Managed` will work in the future, I'm going to close this issue.  We will likely not spend any effort to fix today's version of `Managed` as it is code that'll be replaced with .NET's version.
