### ISSUE TITLE
Set AlarmManager to repeat given a specific time

### ISSUE THREAD

**Issue by luczha** [xamarin/xamarin-android#5105]
I used **AlarmManager** and **BroadcastReceiver** to repeat to  do something every 10 seconds . I used following code

```
 var intent = new Intent(this, typeof(MyBroadcastReceiver));
var pendingIntent = PendingIntent.GetBroadcast(
                    this, 0, intent, PendingIntentFlags.UpdateCurrent);
var alarmManager = (AlarmManager)GetSystemService(AlarmService);
alarmManager.SetRepeating(AlarmType.RtcWakeup, JavaSystem.CurrentTimeMillis(), 10 * 1000, pendingIntent);
```

```
[BroadcastReceiver]
 public class MyBroadcastReceiver: BroadcastReceiver
 {
        public override void OnReceive(Context context, Intent intent)
        {
            // Do stuff here.
            
           
        }
 }
```
However , the interval time is incorrect (more that 60 seconds) . I test the similar code in Native Android (Java) and it works fine .  If I miss something important in Xamarin or it is an existing issue ?

**Comment by jpobst** [comment]
According to the documentation, you can no longer rely on this method to call your code at exact intervals: https://developer.android.com/reference/android/app/AlarmManager#setRepeating(int,%20long,%20long,%20android.app.PendingIntent).

You can try setting your `Target Android version` to `Android 4.4 (API Level 19 - Kit Kat)` like it suggests to see if that fixes it.  It may be that your Android Java project is set like that and your Xamarin one is not.

You can also try one of the other methods listed in that doc regarding best practices for getting exact timing notifications.

**Comment by jpobst** [comment]
Hopefully this helped you get unstuck!
