### ISSUE TITLE
How to distinguish a static method and instance method with same name while binding .jar?

### ISSUE THREAD

**Issue by wen-carl** [xamarin/xamarin-android#5109]
I am binding jar files for Xamarin.Android, [Xamarin.Android.TPNS](https://github.com/wen-carl/Xamarin.Android.TPNS)
And I meet a problem while binding **xm4tpns1.2.0.3.jar** in project **Xamarin.TPNS.Xiaomi**:
**I want to know how can I  distinguish a static method and instance method with same name?**

![image](https://user-images.githubusercontent.com/24239653/92999307-6e9b0d00-f552-11ea-8a78-e9e2ee8824b8.png)

![image](https://user-images.githubusercontent.com/24239653/92999368-dd786600-f552-11ea-81b8-f2c9b7fe64dc.png)

![image](https://user-images.githubusercontent.com/24239653/92999373-ecf7af00-f552-11ea-83c8-61a0e8b79555.png)

### Steps to Reproduce

1. Just download from [https://github.com/wen-carl/Xamarin.Android.TPNS](https://github.com/wen-carl/Xamarin.Android.TPNS), then build project Xamarin.TPNS.Xiaomi.

**Comment by jpobst** [comment]
There is an additional attribute `static="true"` you can use in the XPath path.  For example, something like this should rename the `static` version:

```
<attr path="/api/package[@name='com.xiaomi.mipush.sdk']/class[@name='PushMessageHandler']/method[@name='a' and count(parameter)=0 and @static='true']" name="managedName">StaticA</attr>
```

**Comment by wen-carl** [comment]
@jpobst Thanks for your reply, I tried to add `@static='true'` but it seems not worked, and I got a new error `error MSB6006: "generator.exe" exited with code -532462766.`

**Comment by jpobst** [comment]
My guess would be the XML is invalid.  You can try running it again with Diagnostic verbosity (Tools -> Options -> Projects and Solution) and then look in the Output log.  That should show the actual exception hit when running `generator.exe`.

**Comment by wen-carl** [comment]
@jpobst I tried and get logs here, I find this: `未经处理的异常:  System.InvalidOperationException: XPath 表达式的计算结果为意外类型 System.Boolean`
[log.txt](https://github.com/xamarin/xamarin-android/files/5226382/log.txt)

**Comment by jpobst** [comment]
The XML I provided works for me, make sure you copied it correctly.

![Screenshot 2020-09-15 114144](https://user-images.githubusercontent.com/179295/93239509-80de9c00-f748-11ea-8142-f9ffcaab78ab.png)

**Comment by wen-carl** [comment]
@jpobst This worked for me:
```xml
<attr path="/api/package[@name='com.xiaomi.mipush.sdk']/class[@static='true' and @name='PushMessageHandler']/method[@name='a' and count(parameter)=0]" name="managedName">StaticA</attr>
```

And I meet a new problem here:
![image](https://user-images.githubusercontent.com/24239653/93239823-e61ca680-f7b5-11ea-9ac9-aaad82c50f2c.png)
![image](https://user-images.githubusercontent.com/24239653/93239867-f3399580-f7b5-11ea-8210-9e28dce30582.png)
![image](https://user-images.githubusercontent.com/24239653/93239918-06e4fc00-f7b6-11ea-95e8-94d31d833152.png)

**Comment by jpobst** [comment]
You have 2 methods that differ only by return type.  I'm not even sure how that's allowed in Java.  🤷 

```
<method abstract="false" deprecated="not deprecated" final="false" name="b" jni-signature="()V" bridge="false" native="false" return="void" jni-return="V" static="true" synchronized="false" synthetic="false" visibility="protected">
</method>
<method abstract="false" deprecated="not deprecated" final="false" name="b" jni-signature="()Z" bridge="false" native="false" return="boolean" jni-return="Z" static="true" synchronized="false" synthetic="false" visibility="public">
</method>
```

You can use the `return` attribute to distinguish them:
```
<attr path="/api/package[@name='com.xiaomi.mipush.sdk']/class[@name='PushMessageHandler']/method[@name='b' and count(parameter)=0 and @return='boolean']" name="managedName">StaticBooleanB</attr>
```

**Comment by wen-carl** [comment]
@jpobst Thank you very much, it worked for me, can you add it here [https://docs.microsoft.com/zh-cn/xamarin/android/platform/binding-java-library/customizing-bindings/](https://docs.microsoft.com/zh-cn/xamarin/android/platform/binding-java-library/customizing-bindings/), I didn't find it in Xamarin official website.
