### ISSUE TITLE
Starting from Xamarin.Android 11 can't build app due to error APT2062: failed linking references

### ISSUE THREAD

**Issue by dimapetrovk** [xamarin/xamarin-android#5110]
### Steps to Reproduce

1. Update VSMac to 8.7 and Xamarin.Android to version 11.

### Version Information

Visual Studio Community 2019 for Mac
Version 8.7.4 (build 38)
Installation UUID: 035faede-4bb0-4d97-bd2b-3b49167df572
  GTK+ 2.24.23 (Raleigh theme)
  Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

  Package version: 612000090

Mono Framework MDK
Runtime:
  Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
  Package version: 612000090

Roslyn (Language Service)
3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878

NuGet
Version: 5.7.0.6702

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
  3.1.401
  3.1.200
  3.1.102
  3.0.101
  3.0.100
  2.1.701
  2.1.505
  2.1.302
  2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
  3.1.7
  3.1.2
  3.0.1
  3.0.0
  2.1.21
  2.1.17
  2.1.16
  2.1.15
  2.1.14
  2.1.13
  2.1.12
  2.1.9
  2.1.2
  2.1.1

Xamarin.Profiler
Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/dranhovskyi/Library/Developer/Xamarin/android-sdk-macosx
  Supported Android versions:
    5.0 (API level 21)
    7.0 (API level 24)
    7.1 (API level 25)
    8.0 (API level 26)
    8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Microsoft OpenJDK for Mobile
Java SDK: /Users/dranhovskyi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-08-19 22:18:28 UTC

Android Device Manager
Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-08-19 22:18:52 UTC

Xamarin Designer
Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

Apple Developer Tools
Xcode 11.4.1 (16137)
Build 11E503a

Xamarin.Mac
Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

Xamarin.iOS
Version: 13.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

Build Information
Release ID: 807040038
Git revision: 7f322926a2e0a5fa0c1e3833215a191883f7514a
Build date: 2020-08-20 10:10:20-04
Build branch: release-8.7
Xamarin extensions: 7f322926a2e0a5fa0c1e3833215a191883f7514a

Operating System
Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

Enabled user installed extensions
XAML Styler 2.0.1
MvvmCross Template pack 2.1.0

### Log Info

/Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(269): error APT2260: resource attr/flow_horizontalSeparator (aka com.patrickconstraction.buildbookmobile:attr/flow_horizontalSeparator) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(269): error APT2260: resource attr/flow_verticalSeparator (aka com.patrickconstraction.buildbookmobile:attr/flow_verticalSeparator) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(270): error APT2260: resource attr/flow_horizontalSeparator (aka com.patrickconstraction.buildbookmobile:attr/flow_horizontalSeparator) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(270): error APT2260: resource attr/flow_verticalSeparator (aka com.patrickconstraction.buildbookmobile:attr/flow_verticalSeparator) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(272): error APT2260: resource attr/flow_horizontalSeparator (aka com.patrickconstraction.buildbookmobile:attr/flow_horizontalSeparator) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(272): error APT2260: resource attr/flow_verticalSeparator (aka com.patrickconstraction.buildbookmobile:attr/flow_verticalSeparator) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(272): error APT2260: resource attr/motionProgress (aka com.patrickconstraction.buildbookmobile:attr/motionProgress) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(275): error APT2260: resource attr/motionProgress (aka com.patrickconstraction.buildbookmobile:attr/motionProgress) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(276): error APT2260: resource attr/motionProgress (aka com.patrickconstraction.buildbookmobile:attr/motionProgress) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(285): error APT2260: resource attr/motionProgress (aka com.patrickconstraction.buildbookmobile:attr/motionProgress) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(285): error APT2260: resource attr/waveDecay (aka com.patrickconstraction.buildbookmobile:attr/waveDecay) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(289): error APT2260: resource attr/motionPathRotate (aka com.patrickconstraction.buildbookmobile:attr/motionPathRotate) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(291): error APT2260: resource attr/motionProgress (aka com.patrickconstraction.buildbookmobile:attr/motionProgress) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(319): error APT2260: resource attr/motionProgress (aka com.patrickconstraction.buildbookmobile:attr/motionProgress) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]
  /Users/runner/work/1/s/Droid/obj/Release/lp/24/jl/res/values/values.xml(336): error APT2260: resource attr/duration (aka com.patrickconstraction.buildbookmobile:attr/duration) not found. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(161,3): error APT2062: failed linking references. [/Users/runner/work/1/s/Droid/BuildBookMobile.Droid.csproj]

**Comment by jpobst** [comment]
This sounds like https://github.com/xamarin/xamarin-android/pull/5107.

Can you try setting it to build 1 project at a time and see if that fixes it?

On VS for Windows, it's
- Tools
- Options
- Projects and Solutions
- Build and Run
- Maximum number of parallel project builds = 1.

I assume VS for Mac has a similar setting.

**Comment by jonathanpeppers** [comment]
I've not seen #5107 occur on Mac, does the problem occur if you build command-line?

    $ msbuild YourApp.Android.csproj -t:SignAndroidPackage -bl

If it fails, can you send us the `msbuild.binlog` file that should be found in the current directory?

That would help us know if #5107 will fix your problem, thanks!

**Comment by dimapetrovk** [comment]
So I found workaround. Since it required android attributes (that it doesn't need)? I just Added these attributes. And later I found other people on github doing it. (https://github.com/vanpra/AndroidBackdrop/blob/59e60e81f96f3da5109af98fc9b090929ee5944a/app/src/main/res/values/attrs.xml)

`<resources xmlns:tools="http://schemas.android.com/tools">
    <attr name="flow_horizontalSeparator" tools:ignore="MissingDefaultResource" />
    <attr name="flow_verticalSeparator" tools:ignore="MissingDefaultResource" />
    <attr name="motionProgress" tools:ignore="MissingDefaultResource" />
    <attr name="waveDecay" tools:ignore="MissingDefaultResource" />
    <attr name="motionPathRotate" tools:ignore="MissingDefaultResource" />
    <attr name="duration" tools:ignore="MissingDefaultResource" />
</resources>`

Hope it will save someone's day (or days like in my case).

**Comment by jonathanpeppers** [comment]
It seems like it is something to do with androidx.constraintlayout?
* https://github.com/android/views-widgets-samples/issues/37#issuecomment-512780651
* https://issuetracker.google.com/issues/136103084

Maybe they removed some of these attributes? I think we can close for now, since it is a general Android problem. Let us know if you find something else, thanks!
