### ISSUE TITLE
Xamarin Android build artifacts version Tag 

### ISSUE THREAD

**Issue by Akademiksdc** [xamarin/xamarin-android#5117]
Is it possible to add a tag, or a branch names at 
https://dev.azure.com/xamarin/public/_build?definitionId=48&_a=summary&repositoryFilter=35 
which will be equal to official Xamarin repo versions (https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.3) 

### Example
https://dev.azure.com/xamarin/public/_build/results?buildId=25988

I see that here I can find branch 16-8, seems it is the version 16. But it isn't clear. 

Maybe it's configured somewhere and you can show it to. me, if no, let's add such information. 
@pjcollins @brendanzagaeski  colleagues, maybe you can help me to figure it out, how can I match the latest stable versions of artifacts with the official versions (which even tagged in this repo)?

**Comment by Akademiksdc** [comment]
@pjcollins  @brendanzagaeski you you have any suggestions?

**Comment by brendanzagaeski** [comment]
One approach is:

 1. Look up the commit hash for a particular Xamarin.Android version on https://github.com/xamarin/xamarin-android/tags. For example, for Xamarin.Android SDK version 11.1.0.3:
    ![image](https://user-images.githubusercontent.com/4934473/93488003-dc896080-f8d3-11ea-8255-68b1db493127.png)
 2. Navigate to the open source build pipeline: https://dev.azure.com/xamarin/public/_build?definitionId=48
 3. Enter the value from step 1 in the **Filter by keywords** field:
    ![image](https://user-images.githubusercontent.com/4934473/93486755-8cf66500-f8d2-11ea-9fc1-d33ed3368dd0.png)

Note that d16-8 is the first release branch that has been configured to build on the open source Azure Pipelines build pipeline, so Xamarin.Android SDK version 11.1 is the first version where this approach will work. Earlier release branches (sucs as d16-7 and d16-6) were not set up to run on Azure Pipelines, so there is a little gap between the last open source builds available from the old open source [Jenkins pipelines](https://jenkins.mono-project.com/view/Xamarin.Android/) and this new Azure Pipelines configuration.

**Comment by Akademiksdc** [comment]
thank you. @brendanzagaeski

**Comment by jpobst** [comment]
If you are simply looking to decode Xamarin product versions (`10.3`) into branch names, there is a table in the repository readme: https://github.com/xamarin/xamarin-android.

ex: `Commercial Xamarin.Android 10.3 (d16-6) for Windows+Visual Studio 2019`

**Comment by jonpryor** [comment]
I'm pretty sure I *don't* understand what is being requested here…

For "internal" reasons, our branch names correspond to the *Visual Studio* release that they will be included in, and *not* the Xamarin.Android version number.  Thus, the [d16-8 branch](https://github.com/xamarin/xamarin-android/commits/d16-8) is used for Xamarin.Android 11.1, as Xamarin.Android 11.1 is shipped with Visual Studio 16.8 (Windows) or Visual Studio for Mac 8.8 (macOS).  (Consistency?  I've *heard* of such a thing…)

As @jpobst pointed out, [`README.md`](https://github.com/xamarin/xamarin-android/blob/5429b43b24e5af83c948e1b9773f1189063fbdba/README.md) mentions *both* the branch name and version number in the **Downloads** > **Current** table.

Additionally, the "Tags" drop-down in Azure DevOps appears to have no relation to GitHub tags or release branches.  I don't know where the current values come from (`uitests`, `nightly`, …); they are best ignored for now.

That said…

> Is it possible to add a tag, or a branch names … which will be equal to official Xamarin repo versions

The xamarin-android repo *does* have tags which are equal to Xamarin.Android versions, e.g.

https://github.com/xamarin/xamarin-android/commits/v11.1.0.3

are the commits (tree) for Xamarin.Android 11.1.0.3, which was shipped as part of [Visual Studio 16.8 Preview 3](https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.1#september-14-2020--xamarinandroid-11103).

Is this not what you're asking for?

> how can I match the latest stable versions of artifacts with the official versions (which even tagged in this repo)?

I'm not entirely sure I understand the question; I *think* you should be able to take the Xamarin.Android version number found in the release notes, e.g. `11.1.0.3`, prefix that version with a `v`, and go to the corresponding tag in this repo.

The [Releases section](https://github.com/xamarin/xamarin-android/releases) should also have the same information.

**Comment by brendanzagaeski** [comment]
To record one other bit of discussion on this topic, a question that came up while chatting about this with the team was whether the tags listed in https://github.com/xamarin/xamarin-android/tags could be added to the builds in the open source build pipeline. Though [there is an API for that](https://docs.microsoft.com/rest/api/azure/devops/build/tags/add%20build%20tag?view=azure-devops-rest-6.0), adding the tags could cause some confusion because the open source builds are slightly different from the commercial builds that are part of Visual Studio. In other words, even though any particular Xamarin.Android commit will produce the same version number for the open source build as the commercial build, the open source build artifacts for Linux aren't technically considered part of the commercial support release. Long story short, for now, the best way to find open source builds that match up as closely as possible with particular commercial versions is to search using the commit hash rather than the version number 🙂
