### ISSUE TITLE
Crashes at runtime with AppBundle containing custom java native libraries

### ISSUE THREAD

**Issue by johnthiriet** [xamarin/xamarin-android#5150]
### Steps to Reproduce

On our project, we use a private Android native SDK that we created the binding for. This SDK references some native jars like jna-5.1.0.jar.

When we build our application as AppBundle and deploy it on a device, the application crashes at runtime with the following anonymised log. The crash happens in the SDK.

When we create a universal apk from the exact same AppBundle and deploy this apk to the device then the application works perfectly.

The application is AOTed and targets ARM devices only but the issue occurs exactly the same way without IOT or with the linker set to None. So it really seems like a Bundle issue.

It seems that somehow creating a device specific apk from the AppBundle removes a necessary dependency of the SDK.

Did you hear about such issue and about possible fixes ?

### Expected Behavior

It runs :)

### Actual Behavior

It crashes :)

### Version Information

Visual Studio Enterprise 2019 for Mac
Version 8.7.7 (build 10)
Installation UUID: 4fa1fa42-f193-4a58-9183-8c66ea5c80a1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

Mono Framework MDK
Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

Roslyn (Language Service)
3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

NuGet
Version: 5.7.0.6702

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.301
	2.1.700
	2.1.202
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.6
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.11
	2.0.9

Xamarin.Profiler
Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.7 (16142)
Build 11E801a

Xamarin.Mac
Version: 6.20.2.2 (Visual Studio Enterprise)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

Xamarin.iOS
Version: 13.20.2.2 (Visual Studio Enterprise)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

Xamarin.Android
Version: 11.0.2.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/john/Library/Android/sdk
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Microsoft OpenJDK for Mobile
Java SDK: /Users/john/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-08-19 22:18:28 UTC

Android Device Manager
Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-08-19 22:18:52 UTC

Xamarin Designer
Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

Build Information
Release ID: 807070010
Git revision: e58142243407a357198d18ee1a37b1e67a702eff
Build date: 2020-09-10 11:48:02-04
Build branch: release-8.7
Xamarin extensions: e58142243407a357198d18ee1a37b1e67a702eff

Operating System
Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
MFractor 4.3.2

### Log File

[myapp] Rejecting re-init on previously-failed class java.lang.Class<util.cc.b>: java.lang.UnsatisfiedLinkError: Unable to load library '0c679': Native library (android-aarch64/lib0c679.so) not found in resource path (.)
[myapp]   at com.sun.jna.NativeLibrary com.sun.jna.NativeLibrary.loadLibrary(java.lang.String, java.util.Map) (:-1)
[myapp]   at com.sun.jna.NativeLibrary com.sun.jna.NativeLibrary.getInstance(java.lang.String, java.util.Map) (:-1)
[myapp]   at void com.sun.jna.Library$Handler.<init>(java.lang.String, java.lang.Class, java.util.Map) (:-1)
[myapp]   at java.lang.Object com.sun.jna.Native.loadLibrary(java.lang.String, java.lang.Class, java.util.Map) (:-1)
[myapp]   at void util.cc.b.<clinit>() (:-1)
[myapp]   at int util.cc.mb.ˏ() (:-1)
[myapp]   at byte[] util.d.a.c(boolean, byte[], com.mysdk.LightArrayList) (:-1)
[myapp]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
[myapp]   at void util.au.mb$10.run() (:-1)
[myapp]   at void java.lang.Thread.run() (Thread.java:919)
[myapp] 
[myapp] Rejecting re-init on previously-failed class java.lang.Class<util.cc.b>: java.lang.UnsatisfiedLinkError: Unable to load library '0c679': Native library (android-aarch64/lib0c679.so) not found in resource path (.)
[myapp]   at com.sun.jna.NativeLibrary com.sun.jna.NativeLibrary.loadLibrary(java.lang.String, java.util.Map) (:-1)
[myapp]   at com.sun.jna.NativeLibrary com.sun.jna.NativeLibrary.getInstance(java.lang.String, java.util.Map) (:-1)
[myapp]   at void com.sun.jna.Library$Handler.<init>(java.lang.String, java.lang.Class, java.util.Map) (:-1)
[myapp]   at java.lang.Object com.sun.jna.Native.loadLibrary(java.lang.String, java.lang.Class, java.util.Map) (:-1)
[myapp]   at java.lang.Object com.sun.jna.Native.loadLibrary(java.lang.String, java.lang.Class) (:-1)
[myapp]   at int util.cc.mb.ˏ() (:-1)
[myapp]   at byte[] util.d.a.c(boolean, byte[], com.mysdk.LightArrayList) (:-1)
[myapp]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
[myapp]   at void util.au.mb$10.run() (:-1)
[myapp]   at void java.lang.Thread.run() (Thread.java:919)
[myapp] 
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.mycompany.myapp, PID: 5797
[AndroidRuntime] util.bh.b: Invalid operation:: Device environment is not suitable for the SDK to continue the operation
[AndroidRuntime] 	at util.au.mb$10$2$1.run(Unknown Source:12)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:883)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:237)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7814)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
[Process] Sending signal. PID: 5797 SIG: 9

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

If you use a zip tool like 7-zip, etc., does the app bundle contain:

    base/lib/arm64-v8a/llib0c679.so

**Comment by johnthiriet** [comment]
Interestingly when I tried on the newest version of the SDK with AppBundles the problem did not occur anymore.
I rolledback to the previous version and the crash happened again. I have never heard of something incompatible with AppBundles on the native level so I am pretty surprised. Is it possible that this issue still has some Xamarin tooling root ?

Anyway I have unzipped the bundle file lib0c679.so is present in both arm64-v8a and armeabi-v7.

As for the build logs I'd rather send them privately. What would be the preferred way to transfer this file ?

**Comment by jonathanpeppers** [comment]
You can email me at the email listed on my [Github profile](https://github.com/jonathanpeppers).

> I tried on the newest version of the SDK with AppBundles the problem did not occur anymore.
I rolledback to the previous version and the crash happened again.

This makes me wonder if the problem is related to `extractNativeLibs`, we had a couple of issues around it:

https://github.com/xamarin/xamarin-android/pull/5021
https://github.com/xamarin/xamarin-android/pull/5001

I think when using an App Bundle, you lose control of the `extractNativeLibs` setting. Maybe you can send the broken app bundle as well?

**Comment by johnthiriet** [comment]
@jonathanpeppers I have sent an email with the details.

**Comment by johnthiriet** [comment]
@jonathanpeppers I did not reproduce it with the latest version of Visual Studio for Mac.
I keep monitoring if the issue arises again or not.

**Comment by jonathanpeppers** [comment]
`bundletool` was updated in Xamarin.Android 11.0:

https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.0#bundletool-version-update-to-0140

Maybe that solved your issue? Let us know if you run into something else, thanks!
