### ISSUE TITLE
Debugging Xamarin.Android.Google.BillingClient  v3

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#5160]
@jonathanpeppers. Jonathon is the debugging trick you wrote about in your blog back in March 2017 still applicable today for debugging this latest version of the BillingClient, i.e. substituting Xamarin's debug.keystore with my Google Play Keystore contents, so that we are using our release passwords, alias etc. in a debug build. Any new gotchas to look out for?

**Comment by jonathanpeppers** [comment]
Are you maybe referring to: `So if the keystore has to match, how in the world can you debug?`

http://jonathanpeppers.com/Blog/securing-google-play-in-app-purchases-for-xamarin-with-azure-functions

Using the commands from the bash example shouldn't really have anything to worry about:
```bash
keytool -changealias -keystore $OUT_KEYSTORE -alias $ALIAS -destalias $OUT_ALIAS -storepass $PASSWORD
keytool -keypasswd -keystore $OUT_KEYSTORE -alias $OUT_ALIAS -new $OUT_PASSWORD -storepass $PASSWORD
keytool -storepasswd -keystore $OUT_KEYSTORE -new $OUT_PASSWORD -storepass $PASSWORD
```
This is creating a new version of your key with different alias & password. I wouldn't share the key with anyone, as they will easily know your password to use it.

I'm also not sure if these commands will work on Google's latest signing key formats or if there is an `apksigner` equivalent.

**Comment by gmck** [comment]
@jonathanpeppers . Thanks for your reply. As you suspected the debug.bat file didn't appear to change anything when using apksigner, as the debug build log shows it still uses the original values. 

However, debugging seems to work ok, which doesn't make much sense, but I'll take it until someone gets around to explaining why. 

It didn't work until the aab had been published by Google Play, so you have to go through the whole publishing process and then wait until Google Play emails that it is live in the Play Store(3 days later...) and then install it on your device via the Google Play link for testers. I just uploaded it as an alpha build and allowed only 1 tester - me. I'm presuming it will only work while your build number still matches the uploaded build number. Anyway, I can now step through QuerySkuDetails and make a purchase. I can see the purchase appear in Order Management on Play Console. I need to recheck my server-side Verification code for InApp as I was using Subs in my previous app and then write the Acknowledgement code because you only get 5 minutes (72 hours real-time) before it's refunded. 

According to what I read https://stackoverflow.com/questions/36113347/is-it-possible-to-debug-locally-google-plays-in-app-billing-in-android-studio it does appear that you can do it with Android Studio. That was last edited in 2019 so I presume they were discussing an earlier version of BillingClient. However, none of that explains why it is working in Visual Studio!!

Appreciate it if you have any further explanation or ideas.

If it works out ok, I'll put it up on GitHub (Android only as I'm not interested in iOS) and others can then take it over to make it work for Forms etc.

Using VS 2019 16.8.0 Prev 3.0

**Comment by jonathanpeppers** [comment]
> the debug build log shows it still uses the original values.

The trick was to recreate `%localappdata%\Xamarin\Mono for Android\debug.keystore` with a Google Play keystore file with its alias changed. The username/password would also need to be the same that Xamarin.Android expects.

It sounds like it's working for you either way. Is there another question here, or you think we can close this?

You might also join the [.NET discord](https://aka.ms/dotnet-discord) and ask further questions in the #android channel.

**Comment by gmck** [comment]
@jonathanpeppers. Caren Chang, a Google engineer, yesterday updated a couple of articles re com.android.billingclient.billing 3.0.0 where she specifically says that once a release build is uploaded to Google Play you can then test using debug builds and debug signatures as long as the package name matches the APK in the Play Store. So I guess that answers all of my questions!!!

She also states that you can add your Google account to the license testing section of your Google Play Developer Account, so that should also make testing easier - no more need of additional Gmail accounts just to test. I haven't tested that part yet with my own G Suite account, so I can't confirm if non-Gmail accounts also work.

Thanks for your help.
