### ISSUE TITLE
Review preserve lists

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5167]
Review the preserve lists for illink/net5.

We should also try to use the new illink related [attributes](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis?view=net-5.0) where possible.

**Comment by radekdoulik** [comment]
Also check whether System.ServiceModel is linker safe.

**Comment by jonathanpeppers** [comment]
I think we did some auditing on our preserve lists.

Closing this, we can track this one instead going forward: https://github.com/xamarin/xamarin-android/issues/5652
