### ISSUE TITLE
An error occurred, but the error response could not be deserialized.

### ISSUE THREAD

**Issue by danypepin1** [xamarin/xamarin-android#5171]
### Steps to Reproduce

In august, i published a beta version of this project on google play without problem, since then i did some change in the code and now i am trying to publish a beta version of this again.
I changed the version number, then i build the project in release mode and everything is fine. 
Then i archive the project, and click distribute.
I fill in the informations, enter the password and click load. 
In the errors section it's written : an error occurred during the loading of 'com.companyname.Calculette.apk': An Error occurred, but the error response could not be deserialized.

What i tried : delete bin and obj then restart and rebuild and do the step above again without success.
I even repaired visual studio without success.

When i go to view archive, the version 5 is still there, but the apk file doesn't work when  used on google play.

Since the error message is not shown it's kinda hard to find the problem, any idea ? Thanks

### Expected Behavior
Distribution process has no error and i have a valid apk file.

### Actual Behavior
In the errors section it's written : an error occurred during the loading of 'com.companyname.Calculette.apk': An Error occurred, but the error response could not be deserialized.
### Version Information

Microsoft Visual Studio Professional 2019
Version 16.4.1
VisualStudio.16.Release/16.4.1+29609.76
Microsoft .NET Framework
Version 4.8.03761

Version installée : Professional

ASP.NET and Web Tools 2019   16.4.457.38025
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.4.457.38025
Pour plus d'informations, visitez https://www.asp.net/

Common Azure Tools   1.10
Fournit des services courants utilisables par Microsoft Azure Mobile Services et Microsoft Azure Tools.

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Extension IntelliCode   1.0
Informations détaillées sur l'extension Visual Studio IntelliCode

Extensions des outils de conteneur Visual Studio (préversion)   1.0
Affichez, gérez et diagnostiquez les conteneurs dans Visual Studio.

Gestionnaire de package NuGet   5.4.0
Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, visitez https://docs.nuget.org/

Microsoft Continuous Delivery Tools pour Visual Studio   0.4
Simplification de la configuration des pipelines Azure DevOps à partir de l'IDE Visual Studio.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.5.23 (1b51e8c)
Support for debugging Mono processes with Visual Studio.

Outils Azure App Service v3.0.0   16.4.457.38025
Outils Azure App Service v3.0.0

Outils C#   3.4.1-beta4-19607-02+52d275c4f82f329a9732b078c7f7fa0e45cd3e84
Composants C# utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Outils de développement Office pour Visual Studio   16.0.29417.02
Outils de développement Microsoft Office pour Visual Studio

Outils TypeScript   16.0.11031.2001
Outils TypeScript pour Microsoft Visual Studio

Outils Visual Basic   3.4.1-beta4-19607-02+52d275c4f82f329a9732b078c7f7fa0e45cd3e84
Composants Visual Basic utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Package hôte de l'adaptateur de débogage de Visual Studio Code   1.0
Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61912.09160
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Visual F# Tools 10.4 pour F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 pour F# 4.6

Visual Studio Tools pour Conteneurs   1.0
Visual Studio Tools pour Conteneurs

Visual Studio Tools pour Docker   1.1
Développez, exécutez et validez vos applications ASP.NET Core dans l'environnement cible. Appuyez sur F5 pour exécuter votre application directement dans un conteneur avec débogage ou sur CTRL+F5 pour modifier et actualiser votre application sans avoir à recréer le conteneur.

VisualStudio.DeviceLog   1.0
Informations sur mon paquet

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
Ce package contient les composants d’intégration Visual Studio nécessaires pour Workflow Manager.

Xamarin   16.4.000.306 (d16-4@564b8d0)
Extension Visual Studio permettant de développer pour Xamarin.iOS et Xamarin.Android.

Xamarin Designer   16.4.0.464 (remotes/origin/d16-4@4abf337c3)
Extension Visual Studio pour activer les outils Xamarin Designer dans Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.1.0 (d16-4/f2c9364)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: bef1e63
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.8.3.0 (0d8fe21)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
### Log File

Mmm i am not sure how i can copy from this terminal, it doesn't let me highlight anything.

**Comment by jpobst** [comment]
I assume this error is showing in Visual Studio?

You might want to try updating to the latest Visual Studio.  Something might have changed in the Play Store or Android SDK that needed an update in Visual Studio.

If that doesn't work, I would suggest submitting a bug report from within Visual Studio using `Help -> Send Feedback -> Report a Problem`.  This will send the relevant logs so the VS team can examine them.  It also allows the bug to be assigned to the VS team.  Since VS isn't open-source, they don't generally track issues on GitHub.

**Comment by jpobst** [comment]
I'm not sure why it wouldn't show up in the installer.  Your version (16.4.1) is about a year old.  Maybe try downloading the latest installer from https://visualstudio.microsoft.com/downloads and see if running that offers you the latest (16.7.5).

**Comment by danypepin1** [comment]
@jpobst Probably some company restriction bs haha.

**Comment by jpobst** [comment]
Hopefully updating fixed your issue, or at least you were able to submit a VS issue for the VS team.  😄 

Gonna close this issue since it can't be routed to the VS team.
