### ISSUE TITLE
Black screen - activity is being destroyed and recreated over and over again in an infinite loop.

### ISSUE THREAD

**Issue by awattar** [xamarin/xamarin-android#5178]
### Steps to Reproduce

1. Create a new Xamarin Android app.
2. Change target to Android 10 or 11.
3. Change Minimum Android version to API 24.
4. Install all necessary packages: (Xamarin.AndroidX.Lifecycle.LiveData, Xamarin.Google.Android.Material).
5. Add following method to your AppCompatActivity:
 
```
protected override void AttachBaseContext(Context @base)
 {
     var config = @base.Resources.Configuration;
     config.UiMode = UiMode.TypeNormal;
     ApplyOverrideConfiguration(config);
     base.AttachBaseContext(@base);
 }
```

6. Run on Android 7 Device or emulator.

### Expected Behavior

App runs fine.

### Actual Behavior

Black screen and out of memory crash after some time.

Workaround: rotate device.

### Version Information

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: b3f7962b-ee00-46ef-882b-6565c183ddf3
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.1.100-preview3-014645
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.1.0-preview3.19553.2
	3.0.0
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.16
	2.1.15
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/mwesolowski/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/mwesolowski/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Apple Developer Tools ===

Xcode 11.7 (16142)
Build 11E801a

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Enterprise)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

### Log File

No log - test app in the attachment.

**Comment by awattar** [comment]
[TestApp.zip](https://github.com/xamarin/xamarin-android/files/5313517/TestApp.zip)

**Comment by moljac** [comment]
@awattar Thanks for the feedback. We will look into the issue.

**Comment by grendello** [comment]
Running it on the Android 7 emulator I see the following exceptions:

```
10-06 09:45:00.258  4449  4449 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
10-06 09:45:00.258  4449  4449 I art     :   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
10-06 09:45:00.258  4449  4449 I art     :   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
10-06 09:45:00.258  4449  4449 I art     :   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
10-06 09:45:00.258  4449  4449 I art     :   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
10-06 09:45:00.258  4449  4449 I art     :   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
10-06 09:45:00.258  4449  4449 I art     :   at void crc640aad9a0ab5a3b676.MainActivity.n_onCreate(android.os.Bundle) (MainActivity.java:-2)
10-06 09:45:00.258  4449  4449 I art     :   at void crc640aad9a0ab5a3b676.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:42)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6662)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
10-06 09:45:00.258  4449  4449 I art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2599)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2707)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1460)
10-06 09:45:00.258  4449  4449 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-06 09:45:00.258  4449  4449 I art     :   at void android.os.Looper.loop() (Looper.java:154)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
10-06 09:45:00.258  4449  4449 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-06 09:45:00.258  4449  4449 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:866)
10-06 09:45:00.258  4449  4449 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:756)
10-06 09:45:00.258  4449  4449 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.test.test.testapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test.test.testapp-1/lib/
x86, /data/app/com.test.test.testapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
10-06 09:45:00.258  4449  4449 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
10-06 09:45:00.258  4449  4449 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
10-06 09:45:00.258  4449  4449 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
10-06 09:45:00.258  4449  4449 I art     :   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
10-06 09:45:00.258  4449  4449 I art     :   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
10-06 09:45:00.258  4449  4449 I art     :   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
10-06 09:45:00.258  4449  4449 I art     :   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
10-06 09:45:00.258  4449  4449 I art     :   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
10-06 09:45:00.258  4449  4449 I art     :   at void crc640aad9a0ab5a3b676.MainActivity.n_onCreate(android.os.Bundle) (MainActivity.java:-2)
10-06 09:45:00.258  4449  4449 I art     :   at void crc640aad9a0ab5a3b676.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:42)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6662)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
10-06 09:45:00.258  4449  4449 I art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2599)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2707)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1460)
10-06 09:45:00.258  4449  4449 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-06 09:45:00.258  4449  4449 I art     :   at void android.os.Looper.loop() (Looper.java:154)
10-06 09:45:00.258  4449  4449 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
10-06 09:45:00.258  4449  4449 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-06 09:45:00.258  4449  4449 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:866)
10-06 09:45:00.258  4449  4449 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:756)
```

```
10-06 09:45:00.335  1693  1716 I WindowManager: Destroying surface Surface(name=Starting com.test.test.testapp) called by com.android.server.wm.WindowStateAnimator.destroySurface:2016 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:882 com.android.server.wm.WindowState.removeLocked:1456 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2484 com.android.server.wm.WindowManagerService.removeWindowLocked:2442 com.android.server.wm.WindowManagerService.removeWindowLocked:2311 com.android.server.wm.WindowManagerService.removeWindow:2306 com.android.server.wm.Session.remove:202 
10-06 09:45:00.336  4449  4449 E AppCompatDelegate: updateForNightMode. Calling applyOverrideConfiguration() failed with an exception. Will fall back to using Resources.updateConfiguration()
10-06 09:45:00.336  4449  4449 E AppCompatDelegate: java.lang.IllegalStateException: Override configuration has already been set
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.view.ContextThemeWrapper.applyOverrideConfiguration(ContextThemeWrapper.java:99)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at androidx.appcompat.app.AppCompatDelegateImpl.updateForNightMode(AppCompatDelegateImpl.java:2281)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at androidx.appcompat.app.AppCompatDelegateImpl.applyDayNight(AppCompatDelegateImpl.java:2170)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at androidx.appcompat.app.AppCompatDelegateImpl.attachBaseContext(AppCompatDelegateImpl.java:334)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:98)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at crc640aad9a0ab5a3b676.MainActivity.n_attachBaseContext(Native Method)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at crc640aad9a0ab5a3b676.MainActivity.attachBaseContext(MainActivity.java:50)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.app.Activity.attach(Activity.java:6598)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2580)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4483)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.app.ActivityThread.-wrap19(ActivityThread.java)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.os.Looper.loop(Looper.java:154)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at android.app.ActivityThread.main(ActivityThread.java:6077)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at java.lang.reflect.Method.invoke(Native Method)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
10-06 09:45:00.336  4449  4449 E AppCompatDelegate:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

The former one is raised only once, the latter is repeated over and over. @moljac can it be some AndroidX compatibility issue? @jonathanpeppers, @dellis1972 the former, can it be d8/dx issue?

**Comment by grendello** [comment]
[log.txt](https://github.com/xamarin/xamarin-android/files/5332142/log.txt)
Generated with Xamarin.Android/master (8bcd1cd3c430eb856818a0255a8ce4f2c3824d9e) on Android API 24 x86 emulator

**Comment by jonathanpeppers** [comment]
I think this is happening because an AndroidX Java type is missing. This project has mixed Android support and AndroidX.

I ported the entire project to AndroidX, and it seems to work fine:

[TestApp.zip](https://github.com/xamarin/xamarin-android/files/5334140/TestApp.zip)

In a future release the Xamarin templates will be on AndroidX, so this will hopefully be easier to figure out going forward.

**Comment by awattar** [comment]
@jonathanpeppers IMHO it is not related to mixed support libraries as our production sample is not using any. The attached sample is minified version to show that it can be reproduced out of the box.

We have tested your ported sample and it crashes the same. Could you double check that it was tested on device/emulator running on API 24?

**Comment by grendello** [comment]
@awattar do you see the `java.lang.IllegalStateException: Override configuration has already been set` message in your **real** application's crash? If your real app doesn't use the support libraries, please attach a sample that's closer to the real app since we might be chasing a bug that doesn't cause your issue here. Ideally, could you post a crash logcat from your app? Before starting the app, please issue:

```shell
adb shell setprop debug.mono.log default,timing=bare,assemblies
```

thanks!

**Comment by jonathanpeppers** [comment]
I missed the required API 24 emulator here. I see it now.

It seems like this is a bug in AndroidX, others are saying a couple of workarounds are:

1. use `Activity` instead of `AppCompatActivity` -- might not be an option
2. downgrade to older AndroidX and/or support libraries...

Neither are really good options.

Some links:

* https://stackoverflow.com/questions/52537638/how-to-resolve-noclassdeffounderror-failed-resolution-of-landroid-view-viewon
* https://stackoverflow.com/questions/60279565/java-lang-noclassdeffounderror-failed-resolution-of-landroid-view-viewonunhan?noredirect=1&lq=1

**Comment by awattar** [comment]
Thanks @jonathanpeppers for the links. We know about that using `Activity` instead of `AppCompatActivity` works but as you have pointed it is not an option for us. Downgrading is also not the best idea due to dependencies and compatibility with the latest features for the newest devices.

Can we escalate AndroidX issues here or is it a bad place?

**Comment by jonathanpeppers** [comment]
@awattar Google would have to fix this, I believe. You can file Android bugs here: 

https://source.android.com/setup/contribute/report-bugs

> we also have tested it the on the as most similar native app as we were able to create but probably there are slight differences between android imports and nuget versions

You can check the versions of Java androidx libraries are used in the Xamarin NuGet packages here:

https://github.com/xamarin/AndroidX/blob/b080d196a463d267071b55d5e07442924a69e800/config.json#L73-L75

If you find out that a certain androidx package needs to be updated, we could look into that.

Or perhaps `com.google.android.material` needs to be updated? I see 1.2.1 available here:

https://mvnrepository.com/artifact/com.google.android.material/material

**Comment by awattar** [comment]
Thanks @jonathanpeppers @grendello for the help and the investigation. Obviously, there is an issue in AppCompatActivity between 1.1.0 and 1.2.0 AndroidX libraries and it seems that it has nothing to do with Xamarin.

After several years working with Xamarin is still not clear to me in which layer of this Xamarin/native cake I need to look first ;)

**Comment by jonathanpeppers** [comment]
Closing for now, let us know if you need something else, thanks.
