### ISSUE TITLE
[xaprepare] Alternative to looking into /etc/os-release to get Debian version

### ISSUE THREAD

**Issue by NPellet** [xamarin/xamarin-android#5192]
### Steps to Reproduce

1. Checkout xamarin in a docker image mono:latest
2. Install dependencies
3. Run make prepare

### Expected Behavior
Command should complete properly

### Actual Behavior
Command fails because in this particular case, the field ID_VERSION in /etc/os-release does not exist.
However, there are altenative approaches to retrieve the debian version (for example, lsb_release -a might be one of them).

### Version Information
Docker mono:latest

**Comment by grendello** [comment]
@NPellet please attach the `/etc/os-release` file as well as the log of the failed `make prepare` session, thanks!

**Comment by jonathanpeppers** [comment]
@NPellet closing for now as we haven't had any activity on this for a while.

We can reopen if you can send more info, thanks!
