### ISSUE TITLE
API docs are out of date

### ISSUE THREAD

**Issue by gaurangnirmal** [xamarin/xamarin-android#5200]
### Steps to Reproduce
1. AppOpsManager.CheckOp and AppOpsManager.CheckOpNoThrow are deprecated.
No documentation found for updated content.

### Expected Behavior
- Updated methods like, 
unsafeCheckOp(java.lang.String, int, java.lang.String).
unsafeCheckOpNoThrow(java.lang.String, int, java.lang.String).

and documentation regarding it, should be available.
Please refer below link for more info,
https://developer.android.com/reference/android/app/AppOpsManager#public-methods

### Actual Behavior
- Deprecated methods like, 
AppOpsManager.CheckOp(java.lang.String, int, java.lang.String).
AppOpsManager.CheckOpNoThrow(java.lang.String, int, java.lang.String).

Found deprecated in latest apis but no updat in documentations or anything regarding it.
Please Refer links for more info.
https://docs.microsoft.com/en-us/dotnet/api/android.app.appopsmanager.checkop?view=xamarin-android-sdk-9
https://docs.microsoft.com/en-us/dotnet/api/android.app.appopsmanager.checkopnothrow?view=xamarin-android-sdk-9

### Version Information
Visual Studio v16.7.4
XF v4.8.0.1364
I am targeting my project to API-29.

**Comment by gaurangnirmal** [comment]
These methods are not accessible from code, too. Giving compilation errors.

**Comment by jpobst** [comment]
Ah, I misunderstood and thought only the documentation was missing.

The methods are missing due to a binding issue.  I have submitted a PR that fixes the methods here: https://github.com/xamarin/xamarin-android/pull/5208.
