### ISSUE TITLE
Review reflection usage in src/Mono.Android.Export/CallbackCode.cs

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5206]
We are preserving many types unconditinally in Mono.Android.xml because of reflection used here.

It should be possible to remove some of the types from the list as illink is smarter about reflection and hopefully also update some of the code to be more linker friendly.

Also use the new dependency attributes when possible.

**Comment by jonpryor** [comment]
Pie-in-the-sky alternative: *if* `jnimarshalmethod-gen` ever becomes A Thing, then we can type-forward `Java.Interop.ExportAttribute, Mono.Android` to `Java.Interop.ExportAttribute, Java.Interop` and have build-time marshal method generation for `[Export]` methods.
