### ISSUE TITLE
(AndroidX) Unable to build "AMM0000" - Xamarin.AndroidX.AppCompat.Resources

### ISSUE THREAD

**Issue by moerabaya** [xamarin/xamarin-android#5222]
<img width="1182" alt="Screen Shot 2020-10-19 at 10 57 19 AM" src="https://user-images.githubusercontent.com/12199727/96422777-2336e700-1201-11eb-85b8-8531d47f4fb6.png">

### Steps to Reproduce

1. Install Xamarin.AndroidX.AppCompat.Resources
2. Build
3. See warnings

### Expected Behavior

No errors

### Actual Behavior

<img width="1182" alt="Screen Shot 2020-10-19 at 11 07 52 AM" src="https://user-images.githubusercontent.com/12199727/96422749-14e8cb00-1201-11eb-852d-e897ca65fc2d.png">

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: 6c568fc0-cf38-440a-8b1a-594e0e92e9ac
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.302
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.100
	2.1.504
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.6
	3.1.2
	3.1.1
	3.1.0
	3.0.0
	2.1.22
	2.1.20
	2.1.17
	2.1.15
	2.1.14
	2.1.13
	2.1.8
	2.1.2

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.0.1 (17220)
Build 12A7300

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/curauser/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		6.0 (API level 23)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/curauser/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Xamarin.iOS ===

Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

```

### Build Logs

[https://gist.github.com/moerabaya/c1cc8fdbb124c17028f82e11adf7595f](https://gist.github.com/moerabaya/c1cc8fdbb124c17028f82e11adf7595f)

### Packages

1-
![1](https://user-images.githubusercontent.com/12199727/96422682-ff73a100-1200-11eb-8e91-f7d3f7135b99.jpg)

2-
![2](https://user-images.githubusercontent.com/12199727/96422692-03072800-1201-11eb-93df-f1fba8be3083.jpg)

3-
![3](https://user-images.githubusercontent.com/12199727/96422695-04385500-1201-11eb-8539-e20e4e14bc14.jpg)

**Comment by dellis1972** [comment]
Are you able to provide the following so we can investigate further.

1. A diagnostic build log (the linked log is only normal verbosity). You can get this easily by building from the terminal
```
msbuild <project> /t:SignAndroidPackage /bl
```

This will output a msbuild.binlong file which you can zip and attach to this ticket. 

2. We also need a copy of the AndroidManifest.xml file from your project Properties folder, but also from the intermediate directory in `obj/Debug/android`. 

There seems to be two issues at play here. One is the missing `Xamarin.AndroidX.AppCompat.Resources`. the other seems to be that you have duplicate entires in the final merged manifest. This usually means that on of the referenced Nuget packages or Projects also contains an AndroidManfiest.xml which is being merged into the final manifest.

Once we have this additional data we can start the investigation. A small repo project which demonstrates the issue would also be helpful.

Thanks in advance.

**Comment by moerabaya** [comment]
Thanks @dellis1972 for following up

Here's the diagnostic build log
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-android/files/5434283/msbuild.binlog.zip)

Also here's AndroidManifest under `obj/Debug/android`
[AndroidManifest.xml.zip](https://github.com/xamarin/xamarin-android/files/5434290/AndroidManifest.xml.zip)

**Comment by dellis1972** [comment]
@moerabaya do you have the AndrodManifest.xml from `obj/Debug` and your `Properties` folder too? 
There are allot of manifests being merged in from libraries too. Just trying to narrow down which one has the issue

**Comment by moerabaya** [comment]
@dellis1972
`obj/Debug`
[AndroidManifest.xml.zip](https://github.com/xamarin/xamarin-android/files/5437392/AndroidManifest.xml.zip)

`Properties`
[AndroidManifest.xml.zip](https://github.com/xamarin/xamarin-android/files/5437396/AndroidManifest.xml.zip)

**Comment by dellis1972** [comment]
@moerabaya  thanks.

So what is happening here is one of your project references or nuget files is also including an AndroidManifest.xml file. 
As per the error messages you can use the manifest merger tooling to fix these issues without having to contact the package owner and get them to update the nuget package. Also double check any projects you are referencing to see if they have an AndroidManifest.xml in them, then check they don't have an application element. I have seen users accidentally create two application projects and have one reference the other when they actually wanted one application project and one library project. 


To fix these errors you can do the following. In your main `AndroidManifest.xml` (in Properties) do the following.

Add the following xml namespace to the `manifest` element `xmlns:tools="http://schemas.android.com/tools"`

Then add the following to the `application` element

`tools:replace="android:icon"`
`tools:replace="android:theme"`

This should get rid of the manifest merger issues.  For more information on how this works see the [docs](https://developer.android.com/studio/build/manifest-merge). 

If you still have the build error about `AppCompat.Resources` after that please upload a log with that in it, since the current logs only report the manifest issues.

This is a simple example of the changes

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" android:versionCode="1" android:versionName="1.0" package="com.foo.boo" >
<application android:name="com.foo.boo" android:label="@string/app_name" android:theme="@style/theme" android:icon="@drawable/icon" tools:replace="android:icon" tools:replace="android:theme" >
</application >
</manifest>
```

**Comment by moerabaya** [comment]
Thank you so much for your help @dellis1972 this solved the issue we're having.
