### ISSUE TITLE
App builds but fails to launch after VS update

### ISSUE THREAD

**Issue by michelinaFolino** [xamarin/xamarin-android#5226]
Hi guys

i have the problem with the following versions, can you help me out?

=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.8 Preview (8.8 build 2811)
Installation UUID: aff68713-0e62-4384-a986-02b402d17a23
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.8.0-4.20503.2+75d31ee941ce4dbbe5752f4ac2d5c0583f388a27

=== NuGet ===

Version: 5.8.0.6783

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.301
	3.1.300
	2.1.810
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.5
	3.1.4
	2.1.22
	2.1.19
	2.1.18

=== .NET Core 2.1 SDK ===

SDK: 2.1.810

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.0.1 (17220)
Build 12A7300

=== Xamarin.Mac ===

Version: 6.22.1.26 (Visual Studio Community)
Hash: 1dc78db1a
Branch: d16-8-xm
Build date: 2020-09-18 17:30:35-0400

=== Xamarin.iOS ===

Version: 14.4.0.9 (Visual Studio Community)
Hash: d85bf7be1
Branch: d16-8
Build date: 2020-09-23 11:06:08-0400

=== Xamarin Designer ===

Version: 16.8.0.491
Hash: 335b65ec3
Branch: remotes/origin/d16-8
Build date: 2020-09-25 22:22:16 UTC

=== Xamarin.Android ===

Version: 11.1.0.15 (Visual Studio Community)
Commit: xamarin-android/d16-8/5e36e6e
Android SDK: /Users/folinomi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/folinomi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.31
Hash: 309321e
Branch: remotes/origin/d16-8
Build date: 2020-09-24 23:02:14 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-09-24 23:02:34 UTC

=== Build Information ===

Release ID: 808002811
Git revision: c2511e043f96618435996078ddfd3e0fb34aa645
Build date: 2020-10-08 13:30:34-04
Build branch: release-8.8
Xamarin extensions: c2511e043f96618435996078ddfd3e0fb34aa645

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

NuGet Package Management Extensions 0.24

_Originally posted by @michelinaFolino in https://github.com/xamarin/xamarin-android/issues/4486#issuecomment-712724755_

Log when the app starts:

[AndroidRuntime] java.lang.RuntimeException: Unable to instantiate application androidx.multidex.MultiDexApplication: java.lang.InstantiationException: java.lang.Class<androidx.multidex.MultiDexApplication> cannot be instantiated
[AndroidRuntime] 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6830)
[AndroidRuntime] 	at android.app.ActivityThread.access$1300(ActivityThread.java:268)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:237)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7814)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
[AndroidRuntime] Caused by: java.lang.InstantiationException: java.lang.Class<androidx.multidex.MultiDexApplication> cannot be instantiated
[AndroidRuntime] 	at java.lang.Class.newInstance(Native Method)
[AndroidRuntime] 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
[AndroidRuntime] 	at androidx.core.app.CoreComponentFactory.instantiateApplication(:52)
[AndroidRuntime] 	at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
[AndroidRuntime] 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
[AndroidRuntime] 	... 9 more

**Comment by dellis1972** [comment]
@michelinaFolino  are you able to provide a diagnostic build log or a small repo project so we can investigate?
You can get a build log by doing the following from a clean build tree.

```
msbuild <project> /t:Install /bl
```

This will output a msbuild.binlog file which you can zip and attach to this issue. 
If you can also provide the `adb logcat` output from when you run the app

```
adb logcat -c 
adb logcat 
```

please provide the full logcat output not just the lines with the error on it as there will probably be important diagnostic information earlier in the log which can help us track down this issue.

Thanks in advance.

**Comment by jonathanpeppers** [comment]
@michelinaFolino we've not heard back in a while. Let us know if you can send more info, and we'll take another look. Thanks!
