### ISSUE TITLE
Android 10 App not installed

### ISSUE THREAD

**Issue by genifycom** [xamarin/xamarin-android#5244]
### Steps to Reproduce

1. Create an android app for Minimum Android Version with Android 10 in Visual Studio 16.7.6
2. Try to install app on Android 10 (Samsung SM-T290 in my case)
3. Result is "App not installed"

If I change the Minimum Android Version to Android 9, the app installs and runs.
Apk signing is identical according to apksigner

I am using .NET Standard 2.1 libraries and as long as I target Android 9 they seem to work just fine.

What else can I debug to determine the difference?

I checked the logcat and I can find no errors.

Build tools installed are 29.0.2 and 30.0.2

**Comment by moljac** [comment]
Hi
Thanks for the feedback. Checking what is going on...

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

Where do you see the error "App not installed"?

**Comment by genifycom** [comment]
So in Debug, the App installs on the device and runs. When I switch to Release, generate the apk, copy it to the device and click on it, the I get the App Not Installed.
[MSBuild.txt](https://github.com/xamarin/xamarin-android/files/5462329/MSBuild.txt)

**Comment by jonathanpeppers** [comment]
How are you you installing the app? Are you using `adb install C:\path\to\your\AndroidApp-Signed.apk`? 

Does it work if you just hit the Play button for the Release build? The IDE should be able to launch the app, just without attaching a debugger.

**Comment by genifycom** [comment]
For the first question, no. I am doing an adb push to /storage/emulated/0/Download and then from the download folder on the device using the devices File Manager to click on the adb and install it this way. I have also tried an app center upgrade which failed and alerted me to the problem originally.

To the second. Yes it runs on the device.

I do have a call to app center at the start although that should not affect the actual install right?

AppCenter.Start("my app id", typeof(Distribute), typeof(Analytics), typeof(Crashes));

**Comment by jonathanpeppers** [comment]
Can you share the broken `.apk` file? It sounds like you have one that works, and one that doesn't? You can email at my [email address listed on Github](https://github.com/jonathanpeppers) if you don't want to share it publicly.

Thanks!

**Comment by jonathanpeppers** [comment]
@genifycom we haven't heard back in a while, let me know if I missed the email. If you can send something else, we'll talk a look. Thanks!
