### ISSUE TITLE
Control.Background.SetColorFilter is Obsolete

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [xamarin/xamarin-android#5246]
Hi
Control.Background.SetColorFilter is Obsolete

What to exchange for?
`Control.Background.SetColorFilter(Android.Graphics.Color.White, PorterDuff.Mode.SrcAtop);`

**Comment by jpobst** [comment]
Per the Android [docs](https://developer.android.com/reference/android/graphics/drawable/Drawable#setColorFilter(int,%20android.graphics.PorterDuff.Mode)), it looks like you should be using `SetColorFilter (ColorFilter)` passing it a `PorterDuffColorFilter` class.
