### ISSUE TITLE
[illink] System.Collections.Concurrent.dll linked away causes test to fail

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#5263]
This test fails for `Release` builds:

https://github.com/xamarin/xamarin-android/blob/7bf2216f36719b2ae8ec92c7768fccf7f1cae57f/tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs#L31-L61

The app crashes on startup with:
```
11-04 14:48:51.847 17530 17530 E mono    : Unhandled Exception:
11-04 14:48:51.847 17530 17530 E mono    : System.TypeLoadException: Could not set up parent class, due to: Could not load type of field 'Java.Interop.JniRuntime:TrackedInstances' (31) due to: Could not load file or assembly 'System.Collections.Concurrent, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:Java.Interop.dll type:JniRuntime member:(null)
11-04 14:48:51.848 17530 17530 E mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not set up parent class, due to: Could not load type of field 'Java.Interop.JniRuntime:TrackedInstances' (31) due to: Could not load file or assembly 'System.Collections.Concurrent, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:Java.Interop.dll type:JniRuntime member:(null)
```

I'm thinking that something in `System.Collections.Concurrent` is being used in Java.Interop through using `ViewTreeObserver.GlobalLayout`, but it was completely linked away.

It might also be a bug in `ILLink`, so we might file upstream if that is the case: https://github.com/mono/linker

Here is the test project zipped up, it might help diagnose:

[Bug29730-True.zip](https://1drv.ms/u/s!Apmn9psh-S8hnWki4fzkfD5Hxksp?e=hvhxh2)

**Comment by jonathanpeppers** [comment]
This test crashes in the exact same way, too:

https://github.com/xamarin/xamarin-android/blob/7bf2216f36719b2ae8ec92c7768fccf7f1cae57f/tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs#L274-L275

So maybe this is a more general problem?

**Comment by radekdoulik** [comment]
Observation from attached test archive:

`ILLink: Output action:     Link assembly: System.Collections.Concurrent, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (TaskId:276)`

The assembly is not removed completely and the `System.Collections.Concurrent.ConcurrentDictionary*2<TKey,TValue>` class is present. So I guess some of the `System.Collections.Concurrent` dependencies is missing?

I will look at it in more detail.

**Comment by radekdoulik** [comment]
One thing I noticed is that the `System.Collections.Concurrent` is placed in the `assemblies/<abi>/` directories. I wonder whether there isn't an issues with assembly loading during runtime?

**Comment by radekdoulik** [comment]
One more observation: the `assemblies/x86` doesn't contain the `System.Collections.Concurrent` assembly, and the emulator most probably uses the `x86` architecture.

**Comment by radekdoulik** [comment]
There is `android.21-x86\linked\System.Collections.Concurrent.dll` in the build tree, looks like it just wasn't added to the apk.

**Comment by jonathanpeppers** [comment]
I think the problem is that the armeabi-v7a and x86 versions of `System.Collections.Concurrent.dll` have identical mvids...

And so this MSBuild task is removing the x86 one...

https://github.com/xamarin/xamarin-android/blob/b864f93df36dc1d8dcf11b5219d37c4c7681baa3/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs#L12-L20

I'll look into it.
