### ISSUE TITLE
NetworkOnMainThreadException when using HttpClient

### ISSUE THREAD

**Issue by divil5000** [xamarin/xamarin-android#5264]
### Steps to Reproduce

1.  Run the code below, which simulates a large download starting, over 100kb being read, then cancelled by the user.

        private async void OnTestButtonClick(object sender, EventArgs e)
        {
			var client = new HttpClient(new Xamarin.Android.Net.AndroidClientHandler());

			var message = new HttpRequestMessage(HttpMethod.Get, "http://data.skydemon.aero/data/terrain/E020N40.DEM.GZ");
			var httpResponse = await client.SendAsync(message, HttpCompletionOption.ResponseHeadersRead);

			// Read just part of the response
			var readStream = await httpResponse.Content.ReadAsStreamAsync();
			int totalBytes = 0;
			var buffer = new byte[65536];
			while (true)
			{
				int bytesRead = await readStream.ReadAsync(buffer, 0, buffer.Length);
				if (bytesRead == 0)
					break;
				else
					totalBytes += bytesRead;
				if (totalBytes >= 100000) // Simulate the user pressing Cancel or similar after some bytes have been read
					break;
			}

			httpResponse.Dispose();
		}

2. You'll observe NetworkOnMainThreadException being thrown on the last line, when we attempt to Dispose of the HttpResponseMessage.

### Expected Behavior

Using proper async/await syntax should not cause any Android network i/o to occur on the main thread.

### Actual Behavior

Network i/o must be occurring on the main thread because NetworkOnMainThreadException is being thrown.

### Version Information

Microsoft Visual Studio Professional 2019
Version 16.7.7
VisualStudio.16.Release/16.7.7+30621.155
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional
<details>
ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.6000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.463 (d16-7@5209782)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Xamarin.iOS and Xamarin.Mac SDK   14.2.0.12 (e0ce49680)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</details>

**Comment by jonathanpeppers** [comment]
Does the problem go away if you use `ConfigureAwait(false)` on the first async method call?
```csharp
var httpResponse = await client.SendAsync(message, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
```
You would likely need to move the code to another method if you need to work with the UI, such as:
```csharp
async void OnTestButtonClick(object sender, EventArgs e)
{
    await MakeWebRequest ();
    // Update the UI
}

async Task MakeWebRequest ()
{
    var httpResponse = await client.SendAsync(message, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
    // everything else
}
```

You might also consider a `using` block instead of calling `Dispose()` manually, as it needs to be in ` try-finally` block otherwise.

**Comment by jpobst** [comment]
Note that using `async`/`await` does not use a background thread by default, it still uses the UI thread, it just tries not to block the UI thread.  You will likely need to add `Task.Run (...)` somewhere to actually move the work to a background thread:

https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run

**Comment by divil5000** [comment]
I will give the ConfigureAwait(false) idea a go when I get back to work. Please note that this code runs without any problem on PC and iOS.

@jpobst There is no suggestion that any of this code should run on a different thread; there's no reason why async http methods should do so. There's something going on here though, behind the scenes, with the Android implementation of HttpClient. Why should Android complain when the Dispose method is called after you've gone a certain way through reading the response stream?

**Comment by divil5000** [comment]
@jonathanpeppers that does seem to make the problem go away. Please could you elaborate on exactly why this is/was happening on Android but no other platforms? My understanding of using async with HttpClient is that a background thread is never used, which makes it confusing why this happens under these very specific circumstances.

**Comment by jonathanpeppers** [comment]
Android is the only platform that has `NetworkOnMainThreadException`, right?

This comes from Android's StrictMode, but I think this is generally a good thing to fix:

https://developer.android.com/reference/android/os/StrictMode

**Comment by jonathanpeppers** [comment]
I think you got things working, but let us know if you have another issue, thanks!

**Comment by divil5000** [comment]
Thank you very much for your help.

That still doesn't really explain what's going on. Why would that exception only be being thrown in these very specific circumstances? I agree that we can resolve the problem by using ConfigureAware(false) but it would be good to know why it's a stable solution.

**Comment by jonathanpeppers** [comment]
Any code after the first `ConfigureAwait(false)` resumes on a background thread, this post might explain further:

https://devblogs.microsoft.com/dotnet/configureawait-faq/

`ConfigureAwait(true)` is the default for mobile/desktop apps -- as you generally want to update the UI. `ConfigureAwait(false)` is generally the default in ASP.NET, because they focus on throughput and don't need to come back to the same thread.

So if you have code like this in the click event handler, the continuation will resume on the UI thread:

```csharp
async void OnTestButtonClick(object sender, EventArgs e)
{
    await MakeWebRequest ();
    // Update the UI, I'm on the UI thread
}
```

`MakeWebRequest()` can use `ConfigureAwait(false)` as needed.

**Comment by divil5000** [comment]
Thank you, that is very helpful.
