### ISSUE TITLE
[illink] Mono.Android.Export.dll is linked away when an [Export] attribute is used

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#5265]
### Steps to Reproduce

1. Building a simple One .NET project in Release configuration fails with the following code snippet inserted:
```c#
[Export]
public void MyButton_OnClick ()
{
}
```

### Log File
```
Xamarin.Android.Common.targets(1391,3): error XA4210: Please add a reference to Mono.Android.Export.dll when using ExportAttribute or ExportFieldAttribute. 
```

Binary log:
[msbuild.zip](https://github.com/xamarin/xamarin-android/files/5495484/msbuild.zip)

**Comment by jonathanpeppers** [comment]
Just a thought, @jonpryor could the `ExportAttribute` move to be _inside_ `Mono.Export.dll` in .NET 6? We could also put a type forwarder in `Mono.Android.dll`.

A hello world app in .NET 6 will have a `@(Reference)` for `Mono.Android` and `Mono.Android.Export` by default, as basically every assembly gets referenced.
