### ISSUE TITLE
[illink] Set TrimMode of support and compatibility assemblies in SdkOnly linker mode

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5271]
Currently the support and compatability assemblies are not linked. In future they will inform illink themselves about linkability.

Meanwhile set the TrimMode for them to link.

This can be removed once NET6 versions of packages containing them will be released.

**Comment by jonathanpeppers** [comment]
Assemblies can do this now:
```
[assembly: AssemblyMetadata ("IsTrimmable", "True")]
```
Such as: https://github.com/xamarin/AndroidX/pull/247/files#diff-b885226e4f4904e7fd5e9962c2b93df8a656026c6312f31c4d25f745804ab5dcR10

I think we can close this now.
