### ISSUE TITLE
System.ComponentModel.TypeConverter usage throws in Release mode

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#5275]
### Steps to Reproduce

1. Add the following snippet to a .NET 6 project:
```csharp
var typeConverter = TypeDescriptor.GetConverter (typeof (Color));
var color = (Color)typeConverter.ConvertFromString ("#FFAAEE");

Android.Util.Log.Debug("#####TAG#####", $"ARGB= {color.A}, {color.R}, {color.G}, {color.B}";);
```

This works as expected with a debug deployment, but fails in release. We may be removing an assembly that is needed?

Exception: https://gist.github.com/pjcollins/6fa260d92679bc53b43945a19b2f5af2

Binlog: [msbuild.zip](https://github.com/xamarin/xamarin-android/files/5502574/msbuild.zip)

**Comment by jonpryor** [comment]
I wonder if this will be fixed by https://github.com/xamarin/xamarin-android/pull/5610, as it adds a `@(PackageReference)` to System.Drawing.Common.

**Comment by jonathanpeppers** [comment]
This test is enabled and passes on `main`:

https://github.com/xamarin/xamarin-android/blob/7e1558c495d43762a76bb4eb40f7ecddf4e880db/tests/Mono.Android-Tests/System.Drawing/TypeConverterTest.cs#L12-L22

![image](https://user-images.githubusercontent.com/840039/127330890-780c318c-d8f6-4f27-8664-f845c139d588.png)

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5028390&view=ms.vss-test-web.build-test-results-tab
