### ISSUE TITLE
Move Resources/Resources.designer.cs to obj

### ISSUE THREAD

**Issue by bramborman** [xamarin/xamarin-android#5290]
I propose the generated `Resources/Resources.designer.cs` file is placed in the `obj` folder by default for new projects/in One .NET world.

As the file is generated, it's the reason of some unnecessary merge conflicts while because of its name it cannot be universally ignored in `.gitignore` as at least RESX resources have generated files with the same name pattern.

**Comment by dellis1972** [comment]
This options is already available via the `AndroidUseIntermediateDesignerFile` property.
Add the following to your csproj.

```
<AndroidUseIntermediateDesignerFile>true</AndroidUseIntermediateDesignerFile>
```

in .net 6 this will be on by default.

**Comment by dellis1972** [comment]
See https://github.com/xamarin/xamarin-android/blob/55faee0fe9e489bc03cc8ac08140169ddac4c5b5/Documentation/guides/OneDotNet.md#changes-to-msbuild-properties for details of changes.
