### ISSUE TITLE
warning XA0107: Ignoring Reference Assembly 

### ISSUE THREAD

**Issue by meee1** [xamarin/xamarin-android#5326]
### Steps to Reproduce

1. create a library (netstandard2) with a nuget ref to Mono.Posix.NETStandard, and used
2. add this library to a xamarin android project
3. try compile it.

11>"C:\Users\michael\Source\Repos\MissionPlanner\ExtLibs\Xamarin\Xamarin.Android\Xamarin.Android.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->
11>(_ResolveAssemblies target) -> 
11>  C:\Users\michael\.nuget\packages\mono.posix.netstandard\5.20.1-preview\ref\netstandard2.0\Mono.Posix.NETStandard.dll : warning XA0107: Ignoring Reference Assembly `C:\Users\michael\.nuget\packages\mono.posix.netstandard\5.20.1-preview\ref\netstandard2.0\Mono.Posix.NETStandard.dll`.
11>
11>
11>"C:\Users\michael\Source\Repos\MissionPlanner\ExtLibs\Xamarin\Xamarin.Android\Xamarin.Android.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->
11>(_ResolveAssemblies target) -> 
11>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(240,5): error XA2002: Can not resolve reference: `Mono.Posix.NETStandard`, referenced by `Xamarin.Android`. Please add a NuGet package or assembly reference for `Mono.Posix.NETStandard`, or remove the reference to `Xamarin.Android`.
11>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(240,5): error XA2002: Can not resolve reference: `Mono.Posix.NETStandard`, referenced by `MissionPlanner.ArduPilot`. Please add a NuGet package or assembly reference for `Mono.Posix.NETStandard`, or remove the reference to `MissionPlanner.ArduPilot`.
11>
11>    16 Warning(s)
11>    2 Error(s)

### Expected Behavior

compile without the clash of the builtin lib and the nuget lib

### Actual Behavior

fails to compile

### Log File

https://github.com/ArduPilot/MissionPlanner/runs/1441680026?check_suite_focus=true

**Comment by jonathanpeppers** [comment]
@meee1 this probably has always been a problem, it didn't break with an update to Xamarin.Android?

It seems like this problem will completely go away in .NET 6: we won't be shipping `Mono.Posix` in the box anymore. For now, as a workaround can you put this code in a Xamarin.Android project instead of a netstandard one? You could probably do a trick with a shared project or just a single linked `.cs` file.
