### ISSUE TITLE
VS 16.9.0 Preview 1.0 Not preserving data cache on device between debug deploys

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#5331]
Changing android:minHeight="?android:attr/listPreferredItemHeightSmall" from listPreferredItemHeight inside an androidx.constraintlayout.widget.ConstraintLayout being the only change made to the build caused the following. Similar to problems I had previously with Issue #4913 but not the same problem.

Clean, Rebuild, Deploy fixes it. 

```
Falling back to full APK install as delta update failed with error: Installer command error: ErrorWrongVersion
Installed Package com.glmsoftware.OBDNowPro
FastDev Tools already installed for the app. 0.0.6


Index was outside the bounds of the array.
   at Xamarin.Android.Tasks.FastDeploy.<DeployFastDevFiles>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.Android.Tasks.FastDeploy.<RunTaskAsync>d__78.MoveNext() in /Users/builder/azdo/_work/453/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 175
Done executing task "FastDeploy" -- FAILED.
Done building target "_Upload" in project "OBDNowPro.csproj" -- FAILED.
Done building project "OBDNowPro.csproj" -- FAILED.
Build FAILED.

```

**Comment by dellis1972** [comment]
@gmck thanks for the bug report. This is a new system so its nice to get some feedback. 

We are going to need the usual diagnostic build output I'm afraid. But with one addition. We need to set this parameter `_FastDeploymentDiagnosticLogging`.

so 

```
msbuild OBDNow.proj /restore /t:Install /v:diag /bl /p: _FastDeploymentDiagnosticLogging=true
```

We need all the output if possible please.

**Comment by gmck** [comment]
@dellis1972 
Sorry about the delay. I diverted to a more pressing problem in that I now can’t deploy a release build to the connected device. I don’t know whether it is a coincidence or not but after correcting the manifest problem, the removal of (re Read/Write External permissions) as mentioned in #5334 now every time I attempt a release build the log at the end reports normally:

```
Build succeeded.
1>Deployment was successful to Google Pixel 3a.
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
```

However, nothing appears on the device. Tried on another device Samsung S20 and exactly the same.

I can get around the problem using my own program I wrote for the Bundle tool, which first creates an apk set and then does an install to the connected device from that apk set. The only difference as compared to the build log is that I didn’t check a checkbox allowing downgrade. 

It is all a bit weird because only the night before all was normal, created the aab and it installed normally on the device and then uploaded the aab to Google Play without any problem and their install to the device(s) goes fine.

Now I’ve got this workaround I’ll get on to getting that log you requested re the debug build.
Attachment of the log of the release build.

[ReleaseBuild271120.zip](https://github.com/xamarin/xamarin-android/files/5604857/ReleaseBuild271120.zip)

**Comment by dellis1972** [comment]
@gmck thanks for the info. I did a quick look at the Release log, unfortunately its not a diagnostic log so we are missing all of the vital information we need to investigate. If you'd rather not use the command line option from my earlier comment, you will need to go into VS 2019 Options->Solutions->Build and Run and up the log verbosity to Diagnostic. With that change the output in the IDE will be diagnostic. That said, zipping up a msbuild.binlog produced by the `/bl` command line option is preferred.

One thing I did see is `_AndroidAllowDeltaInstall ` is true, you might want to try disabling that feature for now. We have had reports of it not being entirely reliable.

**Comment by gmck** [comment]
@dellis1972 
Thanks for your reply. I thought you guys were holidaying!!! No one on discord.
_AndroidAllowDeltaInstall must be the default because I haven't set it anywhere. Can you tell me how to turn it off and I'll do these tests again. You were right I only had diagnostic for output not build log file. I've been running a heap of debugging tests this morning and I can't reproduce the problem. I have used your msbuild command this morning so I'll attach it here. I gather it overwrites each time because there is only one in the folder. Are the contents the same as the output of the command because I did copy/paste each time to a file which I was going to upload. How do we read the binlogs? I do have something called MSBuild Structured Log View.


[msbuild.zip](https://github.com/xamarin/xamarin-android/files/5605280/msbuild.zip)

**Comment by dellis1972** [comment]
MSBuild Structured Log Viewer is the tool to use. There is also a website https://live.msbuildlog.com. It runs locally so no data will be uploaded. The binlog contains all the data a diagnostic log does, it also contains additional data that makes it easier to find issues. 

One think to note is we do need `_FastDeploymentDiagnosticLogging=true` set for any logs you get an issue with. The new fast dev logging is very verbose and is only really needed for when we get issues, so it is off by default. So if you do manage to repo that issue again try to have `_FastDeploymentDiagnosticLogging` set to true (perhaps in your csproj? ) so that we can get the right data. 

From the stack trace it seems that the data from the tool `xamarin.find` is returning unexpected results. The only way to see what it returns is via `_FastDeploymentDiagnosticLogging`.

**Comment by dellis1972** [comment]
@gmck looking at the log you uploaded it looks like that project still has the `xamarin.android.build.fastdev` nuget package installed? You should remove that as in d16.9 Preview 1 we completed the work which makes that package redundant. That said the log your initially posted was from the new system.

**Comment by gmck** [comment]
1. Can you tell me how xamarin.android.build.fastdev nuget package got into the project as I've never heard of it and I can find no reference anywhere to that package. Could it be something to do with when you instructed me to add `<BaseNuGetRuntimeIdentifier>monoandroid</BaseNuGetRuntimeIdentifier>` 
from the previous issue #4913? I've now commented that out but it makes no difference.
 
The command I used to create the MSBuild log was as below, so I don't understand how it didn't give you the info you wanted.

`msbuild OBDNowPro.csproj /restore /t:install /v:diag /bl /p:_FastDeploymentDiagnosticLogging=true`


2. I can see AllowDeltaInstall in the release build output logs, but I still don't know how to turn it off or for that matter how it was turned on in the first place. Can you please advise?

I'm attaching new logs repeating that test Dellis1.zip. the binlog and the output from the build. The output from the build is small, so something isn't working re that p:_FastDeploymentDiagnosticLogging=true.

I'm also attaching another set of logs Dellis2.zip using the Extension for bin logging. These are specifically Release builds, which don't deploy the apk to the device.

[Dellis1.zip](https://github.com/xamarin/xamarin-android/files/5609935/Dellis1.zip)
[Dellis2.zip](https://github.com/xamarin/xamarin-android/files/5609936/Dellis2.zip)

**Comment by gmck** [comment]
@dellis1972. I've added to the top PropertyGroup

```
<_AndroidAllowDeltaInstall>false</_AndroidAllowDeltaInstall>
<_FastDeploymentDiagnosticLogging>true</_FastDeploymentDiagnosticLogging>
```
Both reflected correctly in the log, but it didn't make any difference re - deploying an apk to the device.

Anything else you want me to try? 

Attached logs. Dellis3.zip

[Dellis3.zip](https://github.com/xamarin/xamarin-android/files/5609966/Dellis3.zip)

**Comment by gmck** [comment]
@dellis1972 

Re not deploying to the device. On the Pixel3a and Samsung S20, I found the apks. Viewing all Apps from within Settings it appears as the packagename com.glmsoftware.OBDNowPro with a size of 0B in both cases. Uninstalling and redeploying  doesn't help as it puts it back again.

Uninstalling and then using my Bundle tool app installs the apk correctly with the correct name and it runs normally.

So I guess that proves something is out of wack with the VS Deploy. I hope you have some ideas as to what has gone wrong. Remember it was all fine as far as release builds until I removed the WriteExternalStorage from both my library and the main app project.

In the morning, as a test, I'm going to build it with the backup version of the library and see if that gets the correct deploy behaviour back again.

**Comment by dellis1972** [comment]
@gmck  ok that last set of logs had the right data. 

So I figured out the problem with the 'Release' build and using `aab`. What is happening is `FastDeploy` is still running, when it really shouldn't be I don't think. As a result its uninstalling the app from the device and not re-installing it because there is no apk to install only an aab. We will need to make sure FastDeploy does not run for release builds or when targeting `aab`. that is a bug, I'll look at on Monday. Might not make it into P2 though as our cut off was this week I believe. 

So what we need now is logs for the problems you had when deploying in Debug mode so we can figure out the issue with the crash you first reported.

**Comment by gmck** [comment]
@dellis1972 

Thanks for the explanation. Seems weird when this problem presents now considering I've been using 16.9.0 p1.0 since its release and it was working fine until that change with the permissions.

I didn't have much luck recreating the debug build issue today. I'm including all the logs in the zip. I've left the project settings as they were yesterday, so maybe _AndroidAllowDeltaInstall = false has fixed that problem. Preserve data cache between deploys is checked.

One thing I forgot to mention last night, was that with the release build I did have one successful Deploy to a Samsung tablet Android 7.1.1 whereas the failures Pixel3a and Samsung s20 are both Android 10.

Any other tests you need?

Could you please comment on the xamarin.android.build.fastdev nuget package because I can't find that.

[Dellis4.zip](https://github.com/xamarin/xamarin-android/files/5611307/Dellis4.zip)

**Comment by dellis1972** [comment]
The `xamarin.android.build.fastdev` package was probably me looking at the wrong binlog in my downloads folder. I have a ton of them mostly called `msbuild (x).binlog` so its probably down to that.  So don't worry about it :)

That `DeployBuildOutput.txt` log from the last set of logs is exactly what I need, it has all the data and includes the additional verbose output.  So when you do finally hit this issue again, that should provide some answers. 

Based on the stack trace I still suspect the `xamarin.find` call we make is returning weird data. I will see if I can put in some extra checks to take care of that, but it would be good to see what we get. 

In order to repo xamarin.find will need to return data, so it will probably only occur if the app has already been fast deployed to the device, and is then deployed again with C# changes. I also suspect it will be specific to a particular device. There are some features (like the `adb shell run-as` command) which are required for this new system to work. This may well be disabled or not functional on some devices. This is normally only on API 20 devices and lower, anything api 21 ad higher should work. However some manufacturers may well disable certain features. We do our best to detect this incomparable state and error, but that will probably need more work. Samsung is known for making "tweaks" to android so they might be good devices to test on. 

Thanks for the help in tracking this down. Android has such a large range of devices it is difficult to test on everything, so getting feedback like this on the Previews is really fantastic :)

**Comment by gmck** [comment]
@dellis1972 

I've been trying to reproduce the original debug build problem by flipping the value from listPreferredItemHeight to Small and back again, but can't reproduce it. It deploys quickly and runs fine and the value obviously changes in the line item of the recyclerview each time I run it. I guess your additions made to the project file has prevented it happening.

The xamarin.find is there
[BEGIN] Fast Deploy Application Files
xamarin.find: ./OBDNowPro.dll	836608	1606624470

Attaching another bunch of logs for these debug deploys.

[Dellis5.zip](https://github.com/xamarin/xamarin-android/files/5611696/Dellis5.zip)

**Comment by gmck** [comment]
@dellis1972 
I got the following when deploying a debug build to a Samsung tablet running Android 7.1.1

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		XA0130: Sorry. Fast deployment is only supported on devices running Android 5.0 (API level 21) or higher.
Please disable fast deployment in the Visual Studio project property pages or edit the project file in a text editor and set the 'EmbedAssembliesIntoApk' MSBuild property to 'true'.		 	0	
```
The project settings were the same as you requested over the weekend. I did try EmbedAssembliesIntoApk but it made no difference. Is that just another similar example of what we had already or do you need logs of this one too? Ironically, it was fine doing a release build which did put the apk from the aab on the device, whereas I still have to use my own bundle tool to get the apk onto the other two devices as mentioned previously.

The same settings have been working fine for the Pixel3a and Samsung S20 the last two days for debug builds and I've added quite a bit of code in that time without any problems until I tried to deploy to this tablet.

I'm still not sure if _AndroidAllowDeltaInstall is how you disable fast deployment. Can you please confirm?

**Comment by dellis1972** [comment]
@gmck `EmbedAssembliesIntoApk` is the way you control Fast Deployment. When it is `false` we will fast deploy the assemblies as they will not be in the apk. When it is `true` the assemblies will be in the apk and will be loaded from there. 

`_AndroidAllowDeltaInstall` is an experimental feature which does a `diff` install of the apk if there are changes. We had some issues with it so have disabled it by default for now. That is one of the reasons why I asked you do disable it. 

Regarding the `XA0130` it would be useful to see the full diagnostic deploy output like you provided before. As I mentioned we make use of the `run-as` feature to do fast deployment. Some devices may not support it. Normally that is API 20 and below, but some manufacturers (i.e Samsung) make changes and may well disable that feature. So when you get that error you need to set `EmbedAssembliesIntoApk` to `true` and debug without fast deployment.  If you can provide the diagnostic logs for that error (including the _FastDeploymentDiagnosticLogging = true setting) I can probably tell you what caused you to get that error on that device. 

Just a note one of the reasons we had to completely rewrite this system is that android has now removed support for writing to external storage. Our old system was completely tied to that , and did not work at all on API 30. Hence the rewrite.

**Comment by gmck** [comment]
@dellis1972 
This is frustrating, without changing anything from last night. I deleted the apk from the device, cleaned, deployed and it deployed fine. So I don't think there is any point of sending the logs. Unfortunately, I deleted the previous logs before I started.

I'll try later on today after I've added some more code.

**Comment by gmck** [comment]
@dellis1972 
Tried again this morning on the Samsung tablet after adding more code yesterday. This time I just hit deploy and it deployed without any errors. The two new menu choices executed normally. I doubt I'm ever going to get you the logs you want.

Do you have any suggestions that may trip the deployment error?

**Comment by dellis1972** [comment]
@gmck I don't have any tips I'm afraid. Just normal C# code changes or Resource changes should eventually produce the issue. 
I have put up a PR which should at least catch the crash you first reported, hopefully we can get that into P3. And we disabled the delta install stuff by default too. 

If its not too much trouble you could leave the `_FastDeploymentDiagnosticLogging` setting turned on and just go about your normal routine. As long as it doesn't impact on your deployment times or day to day work. Then just report the data when you have it. We can leave this Issue open.

**Comment by gmck** [comment]
_fastDeploymentDiagnosticLogging is on all the time. Doesn't really impact me in anyway. Just spits out 150k lines each time!!!

**Comment by gmck** [comment]
@dellis1972 
Just updating this. I haven't been able to reproduce the debug build problem since I last commented. Still have the deploy problem re release builds, but my workaround is still working fine.

**Comment by dellis1972** [comment]
@gmck it might be you are hitting an issue we are tracking in our private repo https://github.com/xamarin/monodroid/issues/1150. I have a fix in progress, hopefully it will make it into d19-9 Preview 4.

**Comment by mackayn** [comment]
I can confirm this issue exists in VS2019 16.8.3 and 16.8.4 without or without fast deploy enabled (Xamarin Forms 4.7 & 5.0 apps).

**Comment by dellis1972** [comment]
@mackayn are you able to provide any diagnostic build output of the Install ? So we can investigate what is happening.
See this comment https://github.com/xamarin/xamarin-android/issues/5331#issuecomment-734500996 for help on turning on diagnostic output (the normal output will not contain the data we need).

**Comment by mackayn** [comment]
> @mackayn are you able to provide any diagnostic build output of the Install ? So we can investigate what is happening.
> See this comment [#5331 (comment)](https://github.com/xamarin/xamarin-android/issues/5331#issuecomment-734500996) for help on turning on diagnostic output (the normal output will not contain the data we need).

I need to pass it with my boss 1st that he's happy for the logs and the csproj to be passed on. Device wise, my S8 and another users S20 Samsung both are been use.

**Comment by dellis1972** [comment]
There was a bug on the MS bug system where they changed the `android:installLocation` in the manifest from `auto` to `preferExternal`. This seemed to fix the issue of the data cache not being preserved. It might be worth trying.
