### ISSUE TITLE
VS 2019 16.9.0. Prev 1.0 Removed Read/Write External Storage Permissions - but obj/manifest still generates them

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#5334]
I just download a new version from Google Play. In this build, I had removed the above permissions because I'd decided I didn't need them anymore. I then downloaded to a Pixel3a (Android 10) and made a test purchase and then ran the program. It didn't ask for any permissions. Did the same with a Samsung S20 and it did ask for permission. Checked my manifest again and it was fine. Checked the properties page and they are both unchecked.
Checked both generated obj/manifests and both Debug and Release still have both permissions.

How can I force the generated obj/manifests to drop those permissions? I can't actually remember when I ran any of my apps without those permissions, so I thought all that was required was either uncheck on the Properties page or just delete them from the manifest directly.

Doesn't explain why the Pixel3a didn't ask for them though!!!

**Comment by gmck** [comment]
Found the problem. My main library had both those permissions in assembly.info. I guess they were automatically inserted when it was first created 5 or 6 years ago. It only ever needs updating every two years when the ISO spec changes, so it hasn't had much love lately.

Is that still true today when creating a new library?

Still doesn't explain why the Pixel3a didn't ask for them, but don't think it worthwhile trying to figure that out.

**Comment by dellis1972** [comment]
In API 30 External Storage was changed https://developer.android.com/about/versions/11/privacy/storage. That might explain why there was no prompt. 
We currently still include Internet and WriteExternalStorage in our templates, however the WriteExternalStorage will be removed since the new Fast Deployment system does not need it. But the Internet one will still be required since the Debugger needs it.

**Comment by gmck** [comment]
@dellis1972 
Understand re API 30. My point was that both the Pixel3a and Samsung S20 are both running Android 10, therefore the behaviour of the WriteExternalStorage permission should have been the same on both. Of course, it could have been due to the flaky deploy behaviour I was experiencing at that time.

I agree re Internet for the templates, but I don't think for new lib creation that it should default to WriteExternalStorage. Let the developer decide if it is required.

Another beef. Creating a new app defaults to Android 9 and Support libs. Shouldn't that be changed to at least Android 10 and AndroidX libs? Android Studio defaults to Android 11 and AndroidX libs and themes.xml as compared to styles.xml. We are way behind!!

**Comment by jonathanpeppers** [comment]
> Creating a new app defaults to Android 9 and Support libs. Shouldn't that be changed to at least Android 10 and AndroidX libs?

I think this is will be coming in VS Windows 16.9 and VS Mac 8.9.

There was a bit of delay because of the many changes involving AndroidX, in general.

**Comment by gmck** [comment]
@jonathanpeppers 
Thanks. That is good news
