### ISSUE TITLE
Cannot access network after a 'Network Request API for peer-to-peer connectivity'

### ISSUE THREAD

**Issue by Dolphinsimon** [xamarin/xamarin-android#5335]
### Steps to Reproduce

1. Connect to a device access point by the google's sample:https://developer.android.google.cn/guide/topics/connectivity/wifi-bootstrap
2. connect to device by TCP client
3. Exception 'Network subsystem is down'

### Expected Behavior
the local network based operation will be successful.
### Actual Behavior
cannot connect to device after the connect process.
### Version Information
Android 11 on Xamarin.Android 11.1

**Comment by pjcollins** [comment]
Thanks for your report. Would you be able to attach a project that reproduces this issue? Feel free to exclude whatever local network details you're trying to access as applicable from the reproduction case. This may be a silly question, but have you made sure to include all relevant permissions and a valid minSdkVersion in your AndroidManifest.xml?

```xml
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by grendello** [comment]
And, what is the exception stack trace? Please provide a logcat of the failed session, thanks!

**Comment by Dolphinsimon** [comment]
> Thanks for your report. Would you be able to attach a project that reproduces this issue? Feel free to exclude whatever local network details you're trying to access as applicable from the reproduction case. This may be a silly question, but have you made sure to include all relevant permissions and a valid minSdkVersion in your AndroidManifest.xml?
> 
> ```
> <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
> <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
> <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
> <uses-permission android:name="android.permission.INTERNET" />
> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
> ```

I have shared my testing project here, you can try it. https://1drv.ms/u/s!Ak8xZo_dxVop0ccQKmilLdHcL2xmHA?e=HPSneu

**Comment by Dolphinsimon** [comment]
`	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />
	<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
    <uses-feature android:name="android.hardware.location" android:required="false" />
    <uses-feature android:name="android.hardware.location.gps" android:required="false" />
    <uses-feature android:name="android.hardware.location.network" android:required="false" />`

**Comment by Dolphinsimon** [comment]
> And, what is the exception stack trace? Please provide a logcat of the failed session, thanks!

Network is unreachable
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:127 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/System/System.Net.Sockets/Socket.cs:1214 
  at System.Net.Sockets.TcpClient.EndConnect (System.IAsyncResult asyncResult) [0x00006] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/System/net/System/Net/Sockets/TCPClient.cs:393 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 
--- End of stack trace from previous location where exception was thrown ---

  at MyMvvmCrossApp1.Core.ViewModels.Home.HomeViewModel.ConnectAsync () [0x002f6] in C:\Users\Simon\source\repos\MyMvvmCrossApp1\src\MyMvvmCrossApp1.Core\ViewModels\Home\HomeViewModel.cs:99

**Comment by grendello** [comment]
@Dolphinsimon can you list networks **before** and **after** you connect to the device over TCP/IP? What I think is happening is that your connection to the device with the TCP/IP client reconfigures networks so that no other network than your debug connection is available. The stack trace and error message confirm that this is not an issue inside Xamarin.Android runtime or class libraries - it merely reacts to the condition of the environment. The TCP/IP connection to the device is set up and managed by the IDE via ADB. Please generate and attach the requested network interface listings (you can use code [similar to this](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface?view=net-5.0) to do that)

**Comment by Dolphinsimon** [comment]
We are testing the network list. But the exception above is a different one from what i have reported the'Network Subsystem is down'. I am trying to get the full exception stack form this exception too.
