### ISSUE TITLE
Is SqlClient supported on Xamarin/Xamarin.Android?

### ISSUE THREAD

**Issue by JasonLiu007** [xamarin/xamarin-android#5345]
![image](https://user-images.githubusercontent.com/53427423/100711862-d7c14c80-33ec-11eb-960d-75737f3b114d.png)

**Comment by pjcollins** [comment]
I would recommend taking a look at the `Microsoft.Data.SQLite` NuGet package for Xamarin.Android development:

https://www.nuget.org/packages/Microsoft.Data.SQLite/
https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/?tabs=visual-studio

Hopefully this library will suit your needs. If not, please re-open this issue and provide some more details around what you are trying to accomplish. Thanks!

**Comment by JasonLiu007** [comment]
@pjcollins Thanks lot for your patience reply.I want to connect to SQL Server so I choose the Microsoft.Data.SqlClient or System.Data.SqlClient.
My project information:
![4](https://user-images.githubusercontent.com/53427423/100846311-54216180-34b9-11eb-97e2-eea27fcfe131.png)
![5](https://user-images.githubusercontent.com/53427423/100846326-597eac00-34b9-11eb-9812-e98f7a9f9883.png)
![2](https://user-images.githubusercontent.com/53427423/100846344-5daac980-34b9-11eb-9c21-2bf018145d62.png)
![3](https://user-images.githubusercontent.com/53427423/100846355-60a5ba00-34b9-11eb-85be-bf49f9af8cbf.png)

First I use the System.Data,SqlClient,but if my project inclde SqlDependency class the error is occer.
![1](https://user-images.githubusercontent.com/53427423/100846389-6ac7b880-34b9-11eb-9cb1-53fd0e0673d1.png)
![error1](https://user-images.githubusercontent.com/53427423/100846404-6ef3d600-34b9-11eb-9477-409257ab8097.png)
Then I find the Microsoft.Data.SqlClient on the website.Than I try to use it.But it has other error blew:
![11](https://user-images.githubusercontent.com/53427423/100846430-774c1100-34b9-11eb-8f0c-95503640d0b3.png)
![error2](https://user-images.githubusercontent.com/53427423/100846437-7a470180-34b9-11eb-8072-2d3086a179a9.png)

I use the Nuget Package Manager to added the Microsoft.Data.SqlClient or System.Data.SqlClient.By the way,I need added the Microsoft.Data.SqlClient or System.Data.SqlClient in one project or both the .net standard class and android project.
![werpnuget1](https://user-images.githubusercontent.com/53427423/100846471-87fc8700-34b9-11eb-8857-affbf47294e6.png)
![werpanuget1](https://user-images.githubusercontent.com/53427423/100846478-8af77780-34b9-11eb-8388-7aabe2a1460c.png)
I search in the internet.
[https://github.com/dotnet/SqlClient/wiki/Frequently-Asked-Questions#11-why-do-i-get-a-platformnotsupported-exception-when-my-application-hits-a-sqlclient-method](url)
From this link,find some thing about the error.But I dodn't know how can I fix it.Usually use Nuget Package Manager to added the package.But this pakage is special?

**Comment by pjcollins** [comment]
The following resources may be helpful for you -- if you are hoping to connect to a remote SQL server you should create a REST API that will manage database operations, and call the REST API from the Android application:

https://www.c-sharpcorner.com/forums/how-to-use-ms-sql-server-in-xamarin

**Comment by JasonLiu007** [comment]
Ok.I will try it.Thaks for your support.
