### ISSUE TITLE
Custom Aot Startup Profile - System.NotImplementedException: 62

### ISSUE THREAD

**Issue by IainS1986** [xamarin/xamarin-android#5353]
### Steps to Reproduce

1. Generated custom aprof profile with msbuild /t:BuildAndStartAotProfiling
2. Finish custom aprof profile with msbuild /t:FinishAotProfiling
3. Set project to use Aot Profiling, Default FALSE and add custom profile in with
```
<PropertyGroup>
    <AndroidUseDefaultAotProfile>false</AndroidUseDefaultAotProfile> 
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
</PropertyGroup>
<ItemGroup>  
    <AndroidAotProfile Include="$(MSBuildThisFileDirectory)custom.aprof" />
</ItemGroup>
```
4. Build Release
5. Deployment fails with follow AOT errors...
```
    [aot-compiler stdout] Mono Ahead of Time compiler - compiling assembly /Users/xxxx/Dev/xxxxx/src/xxxxx.Droid/obj/Release/android/assets/shrunk/IxMilia.Dxf.dll
    [aot-compiler stdout] AOTID 2B084D23-9CBA-DE67-EA5E-C356687B7CB7
    [aot-compiler stdout] Using profile data file '/Users/xxxxx/Dev/xxxxx/src/xxxxx.Droid/custom.aprof'
    [aot-compiler stdout] 62
    [aot-compiler stdout] * Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/mini/aot-compiler.c:12558
    [aot-compiler stdout] 
```
6. Approx. 10 of these errors print out for different DLLs...
IxMilia.Dxf.dll
MvvmCross.Plugin.Messenger.dll
Java.Interop.dll
Mono.Android.dll
Microsoft.AppCenter.Analytics.Android.Bindings.dll
DnsClient.dll
Microsoft.AppCenter.dll
Microsoft.AppCenter.Crashes.Android.Bindings.dll
mscorlib.dll
7. Ends with error '/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2099,3): error XA3001: Could not AOT the assembly: IxMilia.Dxf.dll' - but I think thats just the first one it gets an exception on.

### Expected Behaviour

Custom aprof file is built correct, app deploys to device and runs.

### Actual Information

Deployment fails. Aprof file inspection throws exception.

### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.8.3 (build 16)
Installation UUID: 9e9a832c-d8b3-4f0d-9104-454764f27728
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/iainstanford/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/iainstanford/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Build Information ===

Release ID: 808030016
Git revision: cc6375d2fdcc1b42532e551e24ce650eaca1ae45
Build date: 2020-11-25 13:16:20-05
Build branch: release-8.8
Xamarin extensions: cc6375d2fdcc1b42532e551e24ce650eaca1ae45

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

### Log File
[Log.zip](https://github.com/xamarin/xamarin-android/files/5628814/Log.zip)

### Further Information

When I inspect the aprof profile with 'aprofutil -s custom.aprof' I get the following exception.

```
Unhandled Exception:
System.NotImplementedException: 62
  at Mono.Profiler.Aot.ProfileReader.ReadAllData (System.IO.Stream stream) [0x002c6] in <93f9949abfd248dc9a1f76190855f685>:0 
  at aotprofiletool.MainClass.Main (System.String[] args) [0x000c5] in <760466f08cbf46d488c659de1f35f29d>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: 62
  at Mono.Profiler.Aot.ProfileReader.ReadAllData (System.IO.Stream stream) [0x002c6] in <93f9949abfd248dc9a1f76190855f685>:0 
  at aotprofiletool.MainClass.Main (System.String[] args) [0x000c5] in <760466f08cbf46d488c659de1f35f29d>:0 

```

**Comment by IainS1986** [comment]
Can provide my aprof file if that would be helpful?

**Comment by IainS1986** [comment]
Hi, is anyone able to give me any guidance or help on this? I can try and provide more information if needed?

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
