### ISSUE TITLE
Consolidate @(AndroidLibrary) item groups for .NET 6

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#5357]
As discussed a couple things can improve upon fcd7cf8f4200ccae92e333c920613bfec260973b:

1. We should support `@(AndroidLibrary)` in "legacy" Xamarin.Android and document it. It seems like a convenience that would not be to difficult to support.
1. We should "hide" the old item groups in .NET 6 (via `@(AvailableItemName)`) so they don't appear in the dropdown in IDEs.
1. `@(AndroidNativeLibrary)` should remain distinct from `@(AndroidLibrary)` as the `%(Bind)` and `%(Abi)` metadata do not really make sense for both types of libraries.

**Comment by jonpryor** [comment]
"Related" from our discussions earlier today: we need to overhaul the [XA4301](https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/messages/xa4301.md) error message emitted, currently:

> Native library '{0}' will not be bundled because it has an unsupported ABI.

This message is *not actionable*, and thus in the [proposed](https://github.com/xamarin/xamarin-android/pull/5349#discussion_r534345904) workflow:

1. User adds `libexample.so` file to the directory containing `Foo.csproj`
2. User builds `Foo.csproj`
3. Build quickly fails with XA4301, as we can't infer the ABI for `libexample.so`.

We thus need to update XA4301 with an appropriate fix, to either

1. Edit `Foo.csproj` to add `libexample.so` to an `@(AndroidNativeLibrary)` item group, and set `%(Abi)`, or
2. *Move* `libexample.so` into an e.g. `libs/ABI` directory.

**Comment by jonathanpeppers** [comment]
I filed a different issue for the error message: https://github.com/xamarin/xamarin-android/issues/5358
