### ISSUE TITLE
CategoryAttribute is places on several properties in ActivityAttribute

### ISSUE THREAD

**Issue by marek-safar** [xamarin/xamarin-android#5373]
This seems unnecessary at least for netcore builds and based on @jonathanpeppers look it does not seem to work. It'd be better to clean this up not do pull additional unnecessary dependencies.

https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs#L56

**Comment by jonathanpeppers** [comment]
Context:
* https://github.com/xamarin/xamarin-android/commit/d548ec9ca5746e7ef2f4bd5f0ea11bd58b09ae3b
* (nice GIF): https://github.com/xamarin/xamarin-android/issues/2862

I asked the IDE team if anyone knows if it should work or not. Not heard back yet.
