### ISSUE TITLE
Issue template in this repo asks to run invalid 'pdbcopy' command in Windows

### ISSUE THREAD

**Issue by Eilon** [xamarin/xamarin-android#5389]
1. Go to https://github.com/xamarin/xamarin-android/issues/new/choose
1. Select an issue template such as "🛠 Building an Application" or "🏃‍♀️ Running an Application"
1. In the template towards the bottom you see:
   > 1. On macOS and within Visual Studio:
   >     a. Click **Tools** > **SDK Command Prompt**.
   >     b. Within the launched `Terminal.app` window, run:
   > 
   >             adb logcat -d | pbcopy
   > 
   > 2. Paste below this comment block
1. The command `adb logcat -d | pbcopy` fails on Windows because there is no tool `pdbcopy` in the path of the opened command prompt:
   ```
   C:\GitHub\MobileBlazorBindings\samples\HybridApp\HybridApp.Android>adb logcat -d | pbcopy
   'pbcopy' is not recognized as an internal or external command,
   operable program or batch file.
   ```
1. Also, the instructions are slightly off for Windows because the command prompt is accessed via Tools > Android > Android Adb Command Prompt. (Or, if that's the wrong thing, then where should I be?)

![image](https://user-images.githubusercontent.com/202643/101527274-a099f080-3942-11eb-9841-a337a9c88375.png)

As an aside, I'm not sure what piping the output to pdbcopy would do anyway. Is it trying to filter for the string `pdbcopy`? If so, on Windows you'd run `adb logcat -d | findstr pbcopy` (though, at least for me, that doesn't seem to find anything after running any Android emulator stuff).

**Comment by jonathanpeppers** [comment]
I think the instructions for Windows should be:
```
> adb logcat -d | clip
```

**Comment by Eilon** [comment]
Oh that's to get it into the clipboard? I totally didn't guess that. Makes more sense!

**Comment by Eilon** [comment]
I kept reading it as PDB Copy! My brain was in a debugger mindset.

**Comment by Eilon** [comment]
Thank you!
