### ISSUE TITLE
System.Text.Json version 5.0 crashes the application on Android in the release mode

### ISSUE THREAD

**Issue by holecekp** [xamarin/xamarin-android#5393]
### Steps to Reproduce
I am not sure where to report this issue. It seems that it is more likely problem of System.Text.Json package but I did not find a right place to report it.

I have been using System.Text.Json 4.7.2 and it worked well in my application. After updating to the version 5.0 it works only in the debug mode but not in the release mode. Using methods such as JsonSerializer.DeserializeAsync crashes the application. It seems that there is a problem with the linker. After downgrading to 4.7.2, the application works again.

The error message is:
```
E/AndroidRuntime(15479): android.runtime.JavaProxyThrowable: System.MissingMethodException: Constructor on type 
'System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2[[System.Collections.Generic.IEnumerable`1[[MorseCode.
Models.MorseCodeItem, MorseCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=2.0.5.0, 
Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MorseCode.Models.MorseCodeItem, MorseCode, Version=1.0.0.0, 
Culture=neutral, PublicKeyToken=null]]' not found.
```

Once I got also the following error:
```
java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file 
"/data/app/holecek.pavel.MorseCode-5SfrQXGg4mMrjYSFQ87SBw==/base.apk", zip file "/data/app/holecek.pavel.MorseCode-
5SfrQXGg4mMrjYSFQ87SBw==/split_config.en.apk", zip file "/data/app/holecek.pavel.MorseCode-
5SfrQXGg4mMrjYSFQ87SBw==/split_config.x86.apk", zip file "/data/app/holecek.pavel.MorseCode-
5SfrQXGg4mMrjYSFQ87SBw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/holecek.pavel.MorseCode-
5SfrQXGg4mMrjYSFQ87SBw==/lib/x86, /data/app/holecek.pavel.MorseCode-5SfrQXGg4mMrjYSFQ87SBw==/base.apk!/lib/x86, 
/data/app/holecek.pavel.MorseCode-5SfrQXGg4mMrjYSFQ87SBw==/split_config.en.apk!/lib/x86, 
/data/app/holecek.pavel.MorseCode-5SfrQXGg4mMrjYSFQ87SBw==/split_config.x86.apk!/lib/x86, 
/data/app/holecek.pavel.MorseCode-5SfrQXGg4mMrjYSFQ87SBw==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]
```

### Expected Behavior
Application works in the release mode in the same way as with the previous version of the Nuget package.

### Actual Behavior
Application crashes in the release mode.

### Version Information
`Microsoft Visual Studio Community 2019
Version 16.8.2
VisualStudio.16.Release/16.8.2+30717.126
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA088
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.553.28003
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.553.28003
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.553.28003
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.553.28003
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.255 (d16-8@d002176)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.4.1.3 (e30c41de3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.`

**Comment by MagicAndre1981** [comment]
do you use `PackageReference Include` or `packages.config`? I also [had a similar issue with packages.config](https://github.com/dotnet/aspnetcore/issues/22891).

**Comment by holecekp** [comment]
I have added the Nuget package in the Visual Studio dialog and it created a new PackageReference in the csproj file.

**Comment by dajbych** [comment]
I have a similar problem in Xamarin.iOS. The problem is really related to the linker. The constructor is not statically referenced so it is removed (in release builds). The problem is that it is not your type which is missing the _PreserveAttribute_.

**Comment by holecekp** [comment]
The problem still persists also in 6.0.0. Is any solution planned?

**Comment by jpobst** [comment]
The "reflection mode" of `System.Text.Json` is documented as not being linker-safe:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation-modes?pivots=dotnet-6-0

If using Android for .NET 6+, you can try the source generator version.

If not, you will need to mess with Xamarin.Android linker settings to preserve the needed constructors:
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker
