### ISSUE TITLE
[net6] Referencing xamarin.androidx.vectordrawable fails the build

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#5401]
### Steps to Reproduce

Build an android app with net6-android, reference 
```
<PackageReference Include="xamarin.androidx.vectordrawable" Version="1.1.0" />
```

### Expected Behavior

The build succeeds.

### Actual Behavior

```
.nuget\packages\xamarin.androidx.vectordrawable\1.1.0\buildTransitive\monoandroid90\Xamarin.AndroidX.VectorDrawable.targets(22,5): 
error MSB4062: The "Xamarin.AndroidX.VectorDrawable.BuildTasks.VectorDrawableCheckBuildToolsVersionTask" task could not be loaded from the assembly .nuget\packages\xamarin.androidx.vectordrawable\1.1.0\buildTransitive\monoandroid90\Xamarin.AndroidX.VectorDrawable.BuildTasks.dll. 
Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a'. 
The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\s\nv.github\uno\src\Uno.UI.BindingHelper.Android\Uno.UI.BindingHelper.Android.net6.csproj]
```

### Version Information

Windows: dotnet-sdk-6.0.100-alpha.1.20562.2-win-x64.exe
Windows: Microsoft.NET.Workload.Android.11.0.100.255.msi

**Comment by jonathanpeppers** [comment]
Does the latest version work?
```xml
<PackageReference Include="Xamarin.AndroidX.VectorDrawable" Version="1.1.0.5" />
```
I think you need this "fix" which was to remove these tasks completely: https://github.com/xamarin/AndroidX/commit/cbe9f5463ae8147548e7b067ab166326552cb668

**Comment by jeromelaban** [comment]
Yes, the workaround is to add `ExcludeAssets="build"`, but it's best if they're not there ar all :)

**Comment by jonathanpeppers** [comment]
Ok, I think this was fixed in https://github.com/xamarin/AndroidX/pull/103, and we can close for now.

By the time that .NET 6 ships, we should be on some new Xamarin.AndroidX 1.2 or higher with all the dependencies bumped, so it should hopefully not be a problem going forward.
