### ISSUE TITLE
[One .NET] automatic support for legacy packages

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#5408]
Context: https://github.com/xamarin/net6-samples/blob/e0259e3d94f12a9184623905d9e07c1df8567808/HelloForms/Directory.Build.props#L70-L86

The linker will always find missing assemblies the moment that you bring in an assembly that references `mscorlib.dll`. In a Xamarin.Forms 4.8 application in .NET 6, you would need to add:

```xml
  <ItemGroup>
    <PackageReference Include="System.CodeDom"                        Version="5.0.0" />
    <PackageReference Include="System.Diagnostics.EventLog"           Version="5.0.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="5.0.0" />
    <PackageReference Include="System.IO.Ports"                       Version="5.0.0" />
    <PackageReference Include="System.Security.Permissions"           Version="5.0.0" />
    <PackageReference Include="System.Threading.AccessControl"        Version="5.0.0" />
  </ItemGroup>
```

We need some automatic way to bring these in without making the app size for a "hello world" app grow.

**Comment by jonpryor** [comment]
If we do this, we need to check build times & `.apk` sizes.

**Comment by jonathanpeppers** [comment]
So a problem with the current idea here is I had to use a _different_ set of packages for this Maui sample:

https://github.com/dotnet/net6-mobile-samples/blob/d94606e62a380fa791309462be18d8d9c8b0072e/HelloMaui/HelloMaui.csproj#L17-L26

```xml
    <PackageReference Include="System.CodeDom" Version="6.0.0-preview.1.21102.12" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0-preview.1.21102.12" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="6.0.0-preview.1.21102.12" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="6.0.0-preview.1.21102.12" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0-preview.1.21102.12" />
    <PackageReference Include="System.IO.Ports" Version="6.0.0-preview.1.21102.12" />
    <PackageReference Include="System.Threading.AccessControl" Version="6.0.0-preview.1.21102.12" />
```

I suspect the actual set of packages that would be needed for a particular app is unknown until the linker actually runs and can't find something.

Maui is closer to not using any "legacy" Xamarin.Android assemblies, but it is currently bringing in a Xamarin.Google.Guava package that isn't .NET 6.

Maybe the linker error message needs to be improved to say "Try installing System.CodeDom from NuGet.org"? Maybe that is all we can do?
