### ISSUE TITLE
[Bug] Android Library Project drawable doesn't generate reference

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/xamarin-android#5433]
### Steps to Reproduce

1. Create a new Android library project
2. Add any xml file with whatever you want to it in the drawable folder (will get error that it doesn't exist)
3. Create the drawable folder
4. Add the xml file with whatever you want
5. Reference it like this: var drawable = ContextCompat.GetDrawable(Control.Context, Resource.Drawable.border);
6. Rebuild doesn't cause Resource.Drawable.xxx to exist.

### Expected Behavior
Should work normally and generate the Resource.Drawable
### Actual Behavior
Errors on creating the file in drawable because the physical folder doesn't exist but it shows up in VS.net 2019. 
Then doesn't create the resource dictionary entry.

### Version Information
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 2.0
VisualStudio.16.Preview/16.9.0-pre.2.0+30803.129
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA567
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.311.8738
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2057006+e0968ea4b5f5c523cc7efea1d91fec21e0adc648
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.311.8738
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.311.8738
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.311.8738
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-2.20602.2+eb0a7ff1c241695e17b07b096593804fdd5cfcfd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.9.20324.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.31203.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.9.20324.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.9.20324.1
Conda support for Python projects.

Python - Django support   16.9.20324.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.9.20324.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.9.20324.1
Profiling support for Python projects.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62011.24130
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21120.2001
TypeScript Tools for Microsoft Visual Studio

UnoPlatformPackage Extension   1.0
UnoPlatformPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.9.0-2.20602.2+eb0a7ff1c241695e17b07b096593804fdd5cfcfd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.20567.7+c02b2ef997f1dd07993e1f85b017c858bdf82530
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.196 (main@7f5b5b9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.105 (remotes/origin/c2adbf832aee3f27874ac90b17c433d311053b06@c2adbf832)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.41 (0d792de)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.99.218 (master/9bc0003)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: ac59637
    Java.Interop: xamarin/java.interop/master@99897b2
    ProGuard: Guardsquare/proguard/v7.0.0@84e8560
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ab650f5

Xamarin.iOS and Xamarin.Mac SDK   14.9.0.27 (f4c9327fa)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonathanpeppers** [comment]
I tried in VS 16.8. In step no. 2, I selected:

![image](https://user-images.githubusercontent.com/840039/102636732-a483fa80-411a-11eb-9acc-ea880d9acd5f.png)

Then I get this popup after clicking `Add`:

![image](https://user-images.githubusercontent.com/840039/102636661-8c13e000-411a-11eb-8fe4-642159d3bff9.png)

@JohnGalt1717 is this what you're seeing? @joj do we need to make the `drawable` folder actually *exist* in the Xamarin templates?

It only shows up in the IDE because of:

```xml
  <ItemGroup>
    <Folder Include="Resources\drawable\" />
  </ItemGroup>
  ```

**Comment by JohnGalt1717** [comment]
Yup.

And if you add the folder behind that manually and put in an xml file and paste something into it, it won't get compiled into cs.

**Comment by jonathanpeppers** [comment]
It seems like the same thing happens with a `<Folder Include="foo"/'>` in a .NET framework console app. (If the directory doesn't exist)

So the issue is just how the template is setup?

**Comment by JohnGalt1717** [comment]
I don't think so. I can't get any resources in a android library to actually build into the resources to be referenced in code. The folder thing is just the first of 2 issues that pile on.

**Comment by jonathanpeppers** [comment]
@JohnGalt1717 the steps above worked for me, I just manually created the folder:

![image](https://user-images.githubusercontent.com/840039/102658251-d4dc9080-413c-11eb-9e2b-a337f20d5fbe.png)

Can you attach a new project you created that isn't working?

**Comment by JohnGalt1717** [comment]
I got the latest xamarin.forms package and rebuilt and now it's working. Thanks!
