### ISSUE TITLE
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/xamarin-android#5439]
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

**Comment by jpobst** [comment]
Can you point us to the member that is missing?

https://developer.android.com/reference

**Comment by bbhxwl** [comment]
> Can you point us to the member that is missing?
> 
> https://developer.android.com/reference

https://stackoverflow.com/questions/65345277/xamarin-android-binding-events

**Comment by jpobst** [comment]
According to our tooling, it looks like the method is marked as `internal` in Kotlin, thus we do not bind it for C#.
```
Kotlin: Hiding internal setter method com/binbin/sstputil/SSTPUtils - setOnConnectStatusListener
```
Do you have the original Kotlin source code to confirm if the method is indeed `internal`?

**Comment by bbhxwl** [comment]
> According to our tooling, it looks like the method is marked as `internal` in Kotlin, thus we do not bind it for C#.
> 
> ```
> Kotlin: Hiding internal setter method com/binbin/sstputil/SSTPUtils - setOnConnectStatusListener
> ```
> 
> Do you have the original Kotlin source code to confirm if the method is indeed `internal`?
is this one? I have the source code of this project, which my friend sent to me.


![QQ图片20201218192932](https://user-images.githubusercontent.com/26525599/102609986-619c4400-4167-11eb-9138-461002a64c39.png)

**Comment by bbhxwl** [comment]
> According to our tooling, it looks like the method is marked as `internal` in Kotlin, thus we do not bind it for C#.
> 
> ```
> Kotlin: Hiding internal setter method com/binbin/sstputil/SSTPUtils - setOnConnectStatusListener
> ```
> 
> Do you have the original Kotlin source code to confirm if the method is indeed `internal`?

is this one? I have the source code of this project, which my friend sent to me.

**Comment by jpobst** [comment]
Looks like it.  In order for it to be bound, it would need to be `public` instead of `private`.
