### ISSUE TITLE
Exception on create X509Certificate2 from .p12 file

### ISSUE THREAD

**Issue by alexandresanlim** [xamarin/xamarin-android#5440]
### Steps to Reproduce

```csharp
var file = await FileSystem.OpenAppPackageFileAsync("certificado.p12");

  using (StreamReader sr = new StreamReader(file))
  {
      var bytes = sr.CurrentEncoding.GetBytes(sr.ReadToEnd());
      var x509 = new X509Certificate2(bytes, string.Empty);
  }
```

### Expected Behavior
Create a X509Certificate2 from .p12 on project

### Actual Behavior
Exception message: Unable to decode certificate.

StackTrace: at Mono.Btls.X509CertificateImplBtls..ctor (System.Byte[] data, Microsoft.Win32.SafeHandles.SafePasswordHandle password, System.Security.Cryptography.X509Certificates.X509KeyStorageFlags keyStorageFlags) [0x00070] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/System/Mono.Btls/X509CertificateImplBtls.cs:115 

### Version Information

Microsoft Visual Studio Professional 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86

Xamarin   16.8.000.260 (d16-8@fd405a2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

**Comment by jpobst** [comment]
One guess might be that converting the bytes to a string and back using encodings may be changing them.

You could try something like this:
```
var file = await FileSystem.OpenAppPackageFileAsync ("certificado.p12");

using (var ms = new MemoryStream ()) {
	file.CopyTo (ms);
	var bytes = ms.GetBuffer ();
	var x509 = new X509Certificate2 (bytes, string.Empty);
}
```

**Comment by jpobst** [comment]
Closing due to lack of follow-up.  If this is still an issue, please feel free to reopen.
