### ISSUE TITLE
[illink] Check that `SupportedOSPlatform` is removed on net6

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5470]
Our generator is going to decorate API with  `SupportedOSPlatform` attribute.

We should check that the net6 illink is removing these. (note that we don't have net6 illink yet, we are still using net5's one)

**Comment by jonpryor** [comment]
This is *mostly* working:

```bash
cd samples/HelloWorld
~/android-toolchain/dotnet/dotnet build /t:SignAndroidPackage /p:Configuration=Release HelloWorld.DotNet.csproj
cd obj/Release/net6.0-android
for f in `find . -iname \*.dll` ; do echo "## $f" ; monodis --typeref $f | grep -i supportedos ; done
```

Only one assembly contains a reference to `SupportedOSPlatform`: `HelloWorld.DotNet.dll`, the app assembly.  No other assembly references that type.

So *yay*, *most* references are removed.

That said, do we *also* want the *app* assembly to have `SupportedOSPlatformAttribute` removed in Release builds?

We can answer that question after .NET 6.

**Comment by jonathanpeppers** [comment]
I feel like we can close this. In the example here `HelloWorld.DotNet.dll` is the "root" assembly, and I don't believe anything is trimmed away there.

I don't see `SupportedOSPlatform` as contributing much to app size if it is removed from `Mono.Android.dll`, other Java binding assemblies, etc.
