### ISSUE TITLE
VS for MAC debug doesn't respect applicationId/package from AndroidManifest

### ISSUE THREAD

**Issue by yaliashkevich** [xamarin/xamarin-android#5472]
VS doesn't support build variants out of the box, so by default that is not possible to set up different applicationId/package name for different solution configuration to match different app environments (i.e. dev, stage, ...)

To achieve this I define custom  `AppPackageName`/`AppPackageNameSuffix` properties that applied to `package` attribute of generated AndroidManifest file by `_UpdateManifest` msbuild target injected into build process by overriding `BuildDependsOn`, `CleanDependsOn`, `InstallDependsOnTargets`:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <!-- Just declare properties -->
    <PropertyGroup>
        <AppPackageName Condition=" '$(AppPackageName)' == '' "></AppPackageName>
        <AppPackageNameSuffix Condition=" '$(AppPackageNameSuffix)' == '' "></AppPackageNameSuffix>
    </PropertyGroup>
    
    <PropertyGroup>
        <BuildDependsOn>
            _UpdateAppManifest;
            $(BuildDependsOn);
        </BuildDependsOn>
    </PropertyGroup>
    
    <PropertyGroup>
        <CleanDependsOn>
            _UpdateAppManifest;
            $(CleanDependsOn);
        </CleanDependsOn>
    </PropertyGroup>
    
    <PropertyGroup>
        <InstallDependsOnTargets>
            _UpdateAppManifest;
            $(InstallDependsOnTargets);
        </InstallDependsOnTargets>
    </PropertyGroup>
    
    <Target Name="_UpdateAppManifest" Condition="Exists('$(ProjectDir)$(AndroidManifest)')">
        <!-- Copy original manifest for further modifications -->
        <ItemGroup>
            <_SourceManifest Include="$(ProjectDir)$(AndroidManifest)" />
            <_UpdatedManifest Include="$(IntermediateOutputPath)AndroidManifest.Build.xml" />
        </ItemGroup>
        <Copy SourceFiles="@(_SourceManifest)" DestinationFiles="@(_UpdatedManifest)" />

        <!-- Read package name -->
        <XmlPeek Condition=" '$(AppPackageName)' == '' "
            XmlInputPath="%(_UpdatedManifest.FullPath)"
            Query="/manifest/@package">
            <Output TaskParameter="Result" PropertyName="AppPackageName" />
        </XmlPeek>

        <!-- Update package name -->
        <XmlPoke
            Condition=" '$(AppPackageName)' != '' "
            XmlInputPath="%(_UpdatedManifest.FullPath)"
            Query="/manifest/@package"
            Value="$(AppPackageName)$(AppPackageNameSuffix)" />
        
        <!-- replace manifest with updated one -->
        <PropertyGroup>
            <AndroidManifest>$([MSBuild]::MakeRelative($(ProjectDir), %(_UpdatedManifest.FullPath)))</AndroidManifest>
        </PropertyGroup>

    </Target>

</Project>
```

So now I can define package name suffix per solution configuration like this:
```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'DEV|AnyCPU' ">
    <AppPackageNameSuffix>.dev</AppPackageNameSuffix>
</PropertyGroup>

<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'STAGE|AnyCPU' ">
    <AppPackageNameSuffix>.stage</AppPackageNameSuffix>
</PropertyGroup>
```
It works like a charm.
Let's say my `Properties/AndroidManifest.xml` template has package name set to "com.some.app".
I get "com.some.app.**dev**" for DEV configuration and "com.some.app.**stage**" for STAGE configuration.

The only issue I have is VS for Mac still uses unsuffixed package name from `Properties/AndroidManifest.xml` template instead of resulting manifest file to launch app on device during debug session.
I've checked all manifest files in obj/bin and all of them have correct (suffixed) package name.

```
Forwarding debugger port 8867
Detecting existing process
> am start -n "com.some.app/crc640bc7823b8804bed1.SplashActivity"
> Starting: Intent { cmp=com.some.app/crc640bc7823b8804bed1.SplashActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }
Error type 3
Error: Activity class {com.some.app/crc640bc7823b8804bed1.SplashActivity} does not exist.
```

There is no such problem with VS for Windows, VS2019 does use package name from resulting apk.
VS for Mac should do the same and check actual package name.

**Comment by jonathanpeppers** [comment]
Have you tried using `$(AfterGenerateAndroidManifest)` instead?

https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/building-apps/build-process.md#build-extension-points

If it still doesn't work, can you get a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) inside VS for Mac? I assume that command-line builds work fine?

**Comment by dellis1972** [comment]
This is probably the feature you are after https://github.com/xamarin/xamarin-android/pull/5325.
It allows you to define different AndroidManifest.xml files as overlays, so they will be applied on top of the base AndroidManifest.
You could then have a slightly different manifest per build type.

**Comment by yaliashkevich** [comment]
Don't think `$(AfterGenerateAndroidManifest)` would help.

Build itself is ok and produces valid apk with expected package name, and it is successfully deployed to device.

**Comment by jonathanpeppers** [comment]
> The only issue I have is VS for Mac still uses unsuffixed package name from Properties/AndroidManifest.xml template instead of resulting manifest file to launch app on device during debug session.

So VS for Mac is unable to determine the _correct_ package name to launch the app?

It probably just reads the `Properties\AndroidManifest.xml` directly and does not do any MSBuild evaluation...

**Comment by yaliashkevich** [comment]
> This is probably the feature you are after #5325.
> It allows you to define different AndroidManifest.xml files as overlays, so they will be applied on top of the base AndroidManifest.
> You could then have a slightly different manifest per build type.

Yep, looks like this feature will help to achieve the same. Originally my extension was done time ago and it was no problem until I migrated to VS for MAC from Windows.
Anyway I think that changing package name by overlay feature will have same problem with debugger.

**Comment by yaliashkevich** [comment]
> > The only issue I have is VS for Mac still uses unsuffixed package name from Properties/AndroidManifest.xml template instead of resulting manifest file to launch app on device during debug session.
> 
> So VS for Mac is unable to determine the _correct_ package name to launch the app?
> 
> It probably just reads the `Properties\AndroidManifest.xml` directly and does not do any MSBuild evaluation...

Yes, think so.

**Comment by yaliashkevich** [comment]
This is still an issue, even if you use new standard way to set packageName

- [ApplicationId](https://github.com/xamarin/xamarin-android/pull/5458) 
- [AndroidManifestPlaceholders](https://github.com/xamarin/xamarin-android/pull/5953)

VS for Mac keeps using initial value from AndroidManifest template.
Is it any chance it will be resolved?

**Comment by dellis1972** [comment]
This feels like an issue in VS for Mac itself.  It might be easier to raise an issue with the VS for Mac team via the "Help->Report a Probem" menu in VS for Mac. 

We will reach out to the team in the mean time to see if they have any ideas.

**Comment by yaliashkevich** [comment]
> It might be easier to raise an issue with the VS for Mac team via the "Help->Report a Probem" menu in VS for Mac.

Did already, but it was closed as duplicate with reference to this one on github, https://developercommunity.visualstudio.com/t/VS-for-Mac-debug-doesnt-respect-package/1325569

So I using the thread to get sense on status.

**Comment by dellis1972** [comment]
I've asked our Vs for Mac team to look into it or at least point us to where we can look into this ourselves.

**Comment by yaliashkevich** [comment]
Just to refresh here is steps to reproduce and sample project [pi.zip](https://github.com/xamarin/xamarin-android/files/8462959/pi.zip)

1. Create Blank android app from VS template
2. Update csproj file with following settings
`    <GenerateApplicationManifest>True</GenerateApplicationManifest>
    <ApplicationId>com.home.FromMsBuildProperty</ApplicationId>
`
3. Remove packageName attribute from `Properties/AndroidManifest.xml` to enforce using ApplicationId as name
4. Try to debug app in VS for Mac and observe following in Application Output window:
```
> am start -n "pi.pi/crc6454fe7bf4a62968fe.MainActivity"
> Starting: Intent { cmp=pi.pi/crc6454fe7bf4a62968fe.MainActivity }
Error type 3
Error: Activity class {pi.pi/crc6454fe7bf4a62968fe.MainActivity} does not exist.
```

**Comment by dellis1972** [comment]
I just tested our own internal `_Run` MSBuild command, and that works as expected and picks up the right package name from the intermediate manifest. So this is definately an issue with the VS for Mac Extension.

**Comment by jonathanpeppers** [comment]
I think I did here that this was fixed in VS Mac (not on a public PR). Thanks @yaliashkevich, let us know if you run into anything else!
