### ISSUE TITLE
CanvasWatchFaceService.Engine fails to initialize when omitting type name using constructor invocation expression

### ISSUE THREAD

**Issue by Sour-Codes** [xamarin/xamarin-android#5484]
According to [new operator (C# reference) - Constructor invocation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator#constructor-invocation):

> Beginning with C# 9.0, constructor invocation expressions are target-typed. That is, if a target type of an expression is known, you can omit a type name...

### Steps to Reproduce

1. Follow the [Creating a Watch Face](https://docs.microsoft.com/en-us/xamarin/android/wear/platform/creating-a-watchface?tabs=windows) guide up to the [Try it!](https://docs.microsoft.com/en-us/xamarin/android/wear/platform/creating-a-watchface?tabs=windows#try-it) step.
2. Modify the `OnCreateEngine` method from:

        public override WallpaperService.Engine OnCreateEngine()
        {
            return new MyWatchFaceEngine(this);
        }

to

        public override WallpaperService.Engine OnCreateEngine()
        {
            return new(this);
        }
 
3. Run.

### Expected Behavior
`CanvasWatchFaceService.Engine` instance executes.

### Actual Behavior
Application fails when invoking.

**Comment by jpobst** [comment]
I am pretty surprised that even compiles.  Xamarin.Android does not currently support C# 9.0.

My guess is that your modification is changing the code from:
```
return new MyWatchFaceEngine (this);
```
to:
```
return new WallpaperService.Engine (this);
```

That is, the method returns `WallpaperService.Engine`, so that is what the compiler is going to infer you are constructing.  It has no way to know about your custom type.

**Comment by Sour-Codes** [comment]
It compiles.  I always try to update my projects to the latest language features.  Wasn't aware of the incompatibility although the project file did accept `<LangVersion>Preview</LangVersion>`.  Thank you for the update.

**Comment by jpobst** [comment]
I guess things like that which are pure compiler sugar will work.  Things like covariant return types and function pointers which require runtime support will not.
