### ISSUE TITLE
Is `ref return` supported in Xamarin.Android?

### ISSUE THREAD

**Issue by ackava** [xamarin/xamarin-android#5487]
I am getting crash for following code, however this is just a pseudo code, it is part of a large library and to create reproducible step, it will take sometime.

```c#

       struct Node {

               static Node Null = new Node {  nodes = null };

               Node[] nodes;

               static ref Node GetNode(ref Node start, int i ) {
                     if(start.nodes == null)
                            return ref Null;
                     if(start.nodes.Length <= i)
                             return ref Null;
                      return ref start.nodes[i];
               }
       }

```

`Node.GetNode` always fails with "xamarin androiid fatal signal 11 (sigsegv) code 2 (segv_accerr) libc". This is called recursively by some other class.

The code works correctly on .Net core, .Net Framework but fails in Xamarin.Android.

If `ref return` is supported in Xamarin.Android then I will spend time to create reproducible steps, otherwise I will wait for next Xamarin.Android update when this will be supported.

**Comment by dellis1972** [comment]
@ackava I don't think mono supports this feature yet. This will possibly be supported when .net 6 is released. 

@jonpryor any thoughts?

**Comment by ackava** [comment]
@dellis1972 I found the root cause, `ref return` works till certain stack limit, in too many recursive calls, it crashes probably due to tail call optimization or something else.

**Comment by dellis1972** [comment]
@ackava thanks for letting us know. I'll close this issue, but if it turns out its still a problem please reopen.
