### ISSUE TITLE
.csproj file gets formatted differently when you save it with IDE on MAC and on Windows

### ISSUE THREAD

**Issue by rotanov** [xamarin/xamarin-android#5512]
![image](https://user-images.githubusercontent.com/401399/104901211-cd710700-59c8-11eb-90a8-144a137ac279.png)

On Mac when you save with Visual Studio Mac empty XML tags sometime appear in csproj file and are formatted in one line style.
When resaving such project on windows opening and closing tag get splitted on different lines.

Regarding versions: I feel like I've been seeing such behavior for a couple of years, so it's hard to tell which version exactly and under which conditions introduced which empty tags, it's just that they always oneline on Mac.

**Comment by moljac** [comment]
Thanks for the feedback. We will investigate this issue.

**Comment by rotanov** [comment]
Thank you! I'll be ready to provide any additional details if required.

**Comment by jpobst** [comment]
This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
