### ISSUE TITLE
Java libraries are built on Xamarin.Android 11.0 and not on 11.1

### ISSUE THREAD

**Issue by ashokmec342** [xamarin/xamarin-android#5514]
### Steps to Reproduce

1. I added 3rd party Java libraries and its dependencies
2. I have Mac and windows with different version of Xamarin.Android
3. One of java class is missing on windows machine with new version of Xamarin.Android 11.1
4. On my VS Mac with Xamarin.Android version 11.0 i am able to access all the java classes

**Comment by jpobst** [comment]
Are you saying there is a missing java class in Mono.Android.dll?  If so, can you tell me what it is?

Or are you saying you are creating a binding project and it generates different bindings on each version?

If so, I would run a [Rebuild with "Diagnostic" verbosity](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) and search the log for the class that is missing.  Generally there will be some message like "Could not bind class "blah" because ...." which should help determine the cause.

**Comment by ashokmec342** [comment]
I am actually using java binding project, i have added jar files and I am able to communicate with them in Xamarin.Android version 11.0 but on newer version its showing that it cannot find those classes.

**Comment by jpobst** [comment]
Did the Diagnostic log reveal anything?

**Comment by ashokmec342** [comment]
It says Error while processing type '[Class] com.dexcom.bulk.BulkDataManager': Type 'com.dexcom.common.service.BaseManager' was not found. (TaskId:174), which i dont get on my old version of xamarin.android

**Comment by jpobst** [comment]
If you search for `com.dexcom.common.service.BaseManager`, does it tell you if it found an error for that type?

**Comment by ashokmec342** [comment]
I cannot find this class on new version and there is no error mentioned in build log except for Type 'com.dexcom.common.service.BaseManager' was not found.

**Comment by jpobst** [comment]
Can you provide the `.jar` you are trying to bind?

**Comment by ashokmec342** [comment]
It is from our client, I will clarify the legal matters and come to you. Thank you for the help so far :) !!

**Comment by ashokmec342** [comment]
It is from our client, I will clarify the legal matters and come to you. Thank you for the help so far :) !!

**Comment by ashokmec342** [comment]
I received the latest jar files from client, unfortunately I cannot share them but I had bit of progress. In the api.XML and api.parse.XML I am able to find the Bulkdatamanager class, but when I try to access it says, class not found. Here is the extract from api.xml. There is no error or warnings in build diagnostic.

class abstract="false" deprecated="not deprecated" extends="com.dexcom.common.service.BaseManager" extends-generic-aware="com.dexcom.common.service.BaseManager" jni-extends="Lcom/dexcom/common/service/BaseManager;" final="false" name="BulkDataManager" static="false" visibility="public" jni-signature="Lcom/dexcom/bulk/BulkDataManager;">
      <implements name="com.dexcom.bulk.BulkDataSubscriptionService" name-generic-aware="com.dexcom.bulk.BulkDataSubscriptionService" jni-type="Lcom/dexcom/bulk/BulkDataSubscriptionService;">
      </implements>
      <constructor deprecated="not deprecated" final="false" name="BulkDataManager" jni-signature="(Lcom/dexcom/common/service/core/model/ShareConfig;Landroid/content/Context;Z)V" bridge="false" static="false" type="com.dexcom.bulk.BulkDataManager" synthetic="false" visibility="public">
        <parameter name="p0" type="com.dexcom.common.service.core.model.ShareConfig" jni-type="Lcom/dexcom/common/service/core/model/ShareConfig;" not-null="true">
        </parameter>
        <parameter name="p1" type="android.content.Context" jni-type="Landroid/content/Context;" not-null="true">
        </parameter>
        <parameter name="p2" type="boolean" jni-type="Z">
        </parameter>
      </constructor>


Should I add anything in manifest.xml class and if it doesn't work is there any way to add compiled .dll files taken from build of old xamarin.android version and add them in new xamarin.android version? Please help me!

**Comment by ashokmec342** [comment]
class abstract="false" deprecated="not deprecated" extends="com.dexcom.common.service.BaseManager" extends-generic-aware="com.dexcom.common.service.BaseManager" jni-extends="Lcom/dexcom/common/service/BaseManager;" final="false" name="BulkDataManager" static="false" visibility="public" jni-signature="Lcom/dexcom/bulk/BulkDataManager;">
      <implements name="com.dexcom.bulk.BulkDataSubscriptionService" name-generic-aware="com.dexcom.bulk.BulkDataSubscriptionService" jni-type="Lcom/dexcom/bulk/BulkDataSubscriptionService;">
      </implements>
      <constructor deprecated="not deprecated" final="false" name="BulkDataManager" jni-signature="(Lcom/dexcom/common/service/core/model/ShareConfig;Landroid/content/Context;Z)V" bridge="false" static="false" type="com.dexcom.bulk.BulkDataManager" synthetic="false" visibility="public">
        <parameter name="p0" type="com.dexcom.common.service.core.model.ShareConfig" jni-type="Lcom/dexcom/common/service/core/model/ShareConfig;" not-null="true">
        </parameter>
        <parameter name="p1" type="android.content.Context" jni-type="Landroid/content/Context;" not-null="true">
        </parameter>
        <parameter name="p2" type="boolean" jni-type="Z">
        </parameter>
      </constructor>

**Comment by jpobst** [comment]
Note that the issues will not show up as Errors or Warnings in the Build Log, they are just messages. You will need to manually look through the Build Log to see them.  You can try searching for `BulkDataManager` in the log to see if you find anything.

Is `BaseManager` getting bound?  It is the base class for `BulkDataManager` so it would need to be bound in order to bind `BulkDataManager`.

**Comment by ashokmec342** [comment]
[Output-Build_XamarinAndroid_11.1.txt.zip](https://github.com/xamarin/xamarin-android/files/5912557/Output-Build_XamarinAndroid_11.1.txt.zip)
Here is attached text file.

**Comment by ashokmec342** [comment]
The issue is that, I am unable to access the bulkdatamanager in new xamarin.android version project, reason being BaseManager not found. 

In the old xamarin.android version project, I am able to access the class.
public partial class BulkDataManager : global::Com.Dexcom.Common.Service.BaseManager, global::Com.Dexcom.Bulk.IBulkDataSubscriptionService {
Methods
}

**Comment by jpobst** [comment]
So the root issue isn't that `BulkDataManager` is missing, it's that `BaseManager` is missing.  If we can fix that, then `BulkDataManager` should appear.

```
F : \mylife\Ypsomed.mylife.Apps\Dexcom.Libraries\Android\Dexcom.Cloud.Common.Service\Transforms\Metadata.xml(12, 6) warning BG8A01: <add-node path="/api/package[@name='com.dexcom.common.service']/class[@name='BaseManager']"/> matched no nodes.
```

Looks like you should check the `api.xml` files in the `Dexcom.Cloud.Common.Service` project to see if `BaseManager` is in there.  If it's not, you might want to decompile the Java .jar file and see if `BaseManager` is `public`.  If there was any other reason we didn't bind it, I would expect there would be a message about it in the logs.

**Comment by ashokmec342** [comment]
The funny part is I am do not find this BaseManager in api.xml and api.xml.fixed too. I get no error mentioned related to BaseManager on new version. But on old version i found this in api.xml
<class abstract="true" deprecated="not deprecated" extends="java.lang.Object" extends-generic-aware="java.lang.Object" jni-extends="Ljava/lang/Object;" final="false" name="BaseManager" static="false" visibility="public" jni-signature="Lcom/dexcom/common/service/BaseManager;">
      <implements name="com.dexcom.common.service.core.api.UserCredentialsRegister" name-generic-aware="com.dexcom.common.service.core.api.UserCredentialsRegister" jni-type="Lcom/dexcom/common/service/core/api/UserCredentialsRegister;">
      </implements>

I tried something else, I had two files 1 .jar and 1 .aar files, so i seperated them into two different projects and added references, the BaseManager was supposed to be in .aar file, when i went to obj -> generated -> src I found no classes and no classes in api.xml too.

Regarding the F : \mylife\Ypsomed.mylife.Apps\Dexcom.Libraries\Android\Dexcom.Cloud.Common.Service\Transforms\Metadata.xml(12, 6) warning BG8A01: <add-node path="/api/package[@name='com.dexcom.common.service']/class[@name='BaseManager']"/> matched no nodes.

I tried to add missing class in manifest.xml but no success.

**Comment by ashokmec342** [comment]
@jpobst I have a question, in case if this doesnt work out, is there any way to add the compiled .dll from old xamarin.android project to new version in a proper manner, so that i would be able to access the classes from those libraries, as there are some strict deadlines, before which i need to finish this. Thanks in advance :) !!

**Comment by jpobst** [comment]
You can download the older versions here: https://github.com/xamarin/xamarin-android.  However I do not know if VS will let you downgrade them.  You may need to uninstall VS and install and older version of VS.

**Comment by jpobst** [comment]
I don't know that there's much more I can look at since it's not appearing in `api.xml` or any logs.  To investigate any further I either need the `.jar`/`.aar` file that contains `BaseManager` or a sample project that reproduces the same issue.

If the issue is simply you cannot share them publicly, you can email me at `jonathan.pobst at microsoft dot com`.  But I also understand that some things simply cannot be shared at all.

**Comment by jpobst** [comment]
This was resolved offline, 2 issues were found:
- An `.aar` was not set to the Build Action of `LibraryProjectZip`
- An `.aar` was invalid and needed to be fixed.
