### ISSUE TITLE
[illink] Try to not preserve `__TypeRegistrations` classes

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5515]
These should hopefully be not needed anymore as the new typemap should be sufficient.

**Comment by radekdoulik** [comment]
@grendello does typemap handle all the managed to java type lookups? I wonder whether we can remove this part of code as well https://github.com/xamarin/xamarin-android/blob/7db5be8a56779fbcf0dc7f683d2831910b420d31/src/Mono.Android/Java.Interop/TypeManager.cs#L222-L237 Plus all the code related to package registration.

**Comment by grendello** [comment]
@radekdoulik Typemap handles all the types handed to it by the type scanner (from Java.Interop) and what it cannot find is handled in the managed code in a [fallback path](https://github.com/xamarin/xamarin-android/blob/7db5be8a56779fbcf0dc7f683d2831910b420d31/src/Mono.Android/Android.Runtime/JNIEnv.cs#L697-L737). It feels like removing the type registrations should work?

**Comment by radekdoulik** [comment]
Done.

https://github.com/xamarin/xamarin-android/pull/5516
https://github.com/xamarin/xamarin-android/pull/5629
