### ISSUE TITLE
Bind library that uses Java 8+ API desugaring support

### ISSUE THREAD

**Issue by 4brunu** [xamarin/xamarin-android#5523]
Hi,

I'm not sure if here is the right place to ask, but is it possible to bind a native android library (.aar), that uses Java 8+ API desugaring support?

https://developer.android.com/studio/write/java8-support

A library that uses for example `import java.time.*`

This is how the support for Java 8+ API desugaring is enabled in Android Studio.

```
android {
  defaultConfig {
    // Required when setting minSdkVersion to 20 or lower
    multiDexEnabled true
  }

  compileOptions {
    // Flag to enable support for the new language APIs
    coreLibraryDesugaringEnabled true
    // Sets Java compatibility to Java 8
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.1'
}
```

Is there something like this for Xamarin?
Is it possible to bind a native android library (.aar) that was created with this configuration?
Because I couldn't find a nuget package equivalent to `'com.android.tools:desugar_jdk_libs:1.1.1'`.

Thanks

**Comment by pjcollins** [comment]
I think this should "just work" following these instructions: https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-an-aar. I don't believe you need to worry about adding any desugaring support library. Looping in @jonathanpeppers and @jpobst to maybe help provide more context if needed.

**Comment by 4brunu** [comment]
In Android Studio, If I create a library that uses `import java.time.*` with the previous configurations,  and then consume this aar in an app in Android Studio, I also need to add those previous configurations, otherwise, it will crash the app.

**Comment by jonathanpeppers** [comment]
As long as the Xamarin.Android application project is using d8/r8, things should work by default and you don't need to do anything.

More information on this here:

https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/D8andR8.md#what-does-this-process-look-like-with-d8--r8-enabled

If you are wanting to build a NuGet package, you might consider including an MSBuild `.targets` file that requires `<AndroidDexTool>d8</AndroidDexTool>` to be set. It likely won't work to use `dx`.

I would try it in a "hello world" Xamarin.Android project, and let us know how far you get, thanks!

**Comment by 4brunu** [comment]
Hi,

As @jonathanpeppers suggested, I created a "hello world" Xamarin.Android project and did a bind of a `aar` that uses Java 8+ API desugaring, and `import java.time.*`.

I enabled d8/r8, but got the following crash.
```
Java.Lang.NoClassDefFoundError has been thrown
Failed resolution of: Ljava/time/LocalDateTime
```

Then I added the jar `'com.android.tools:desugar_jdk_libs:1.1.1'` to the project, and it worked.

I got the same results with Xamarin and with Android Studio, when bind the `aar` that uses Java 8+ API desugaring, and `import java.time.*`.

So I opened https://github.com/xamarin/AndroidX/issues/245 to fix this issue.

**Comment by 4brunu** [comment]
Here is the code I used in the sample library
```
package com.example.mylibrary

import java.time.LocalDateTime

object Time {
    @JvmStatic
    fun whatTimeIsIt(): String {
        return LocalDateTime.now().toString()
    }
}
```

**Comment by jonathanpeppers** [comment]
Did you get this error at build time? or when running the app?
```
Java.Lang.NoClassDefFoundError has been thrown
Failed resolution of: Ljava/time/LocalDateTime
```
Can you attach the project here if it is a sample?

**Comment by 4brunu** [comment]
It's a runtime error, when running the app on Android API 23 or bellow.
Because `import java.time.*` was only included in Android platform on API 24 and above.

Here is a sample project in attach.

The sample project has the native Android Library in the directory `NativeApplicationWithNativeLib`.
Then you have the directory `MyApp2` that have the Xamaron Android app, and the `MyLib`, which is the bind for the native Android Library in the directory `NativeApplicationWithNativeLib`

The project now works on Android API 23 or bellow as well as API 24 and above.

If you remove the file `SampleJava8/MyApp2/MyLib/Jars/desugar_jdk_libs-1.1.1.jar`, it will only work on API 24 and above.

[SampleJava8.zip](https://github.com/xamarin/xamarin-android/files/5867546/SampleJava8.zip)

**Comment by Da-Kling** [comment]
Hi, 

I got a similar problem. I am using a third-party library which uses JAVA8+ API and got runtime errors running on Android 23.

`Java.Lang.NoSuchMethodError: 'No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/Queue; or its super classes (declaration of 'java.util.Queue' appears in /system/framework/core-libart.jar)'
`

Even including the desugar_jdk_libs-1.1.1.jar as proposed in the example results in the same error.

Any suggestions?

**Comment by 4brunu** [comment]
Since https://github.com/xamarin/XamarinComponents/pull/1180 got merged, I think this can now be closed.
