### ISSUE TITLE
Aliases with whitespaces cause AndroidSignPackage Task to fail

### ISSUE THREAD

**Issue by Vladimir-Mischenchuk** [xamarin/xamarin-android#5553]
https://github.com/xamarin/xamarin-android/blob/15b40af7d62e0e2003d2a009576834a71967dbb2/src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs#L100

Suggested fix:
`cmd.AppendSwitchIfNotNull (" ", KeyAlias);`

**Comment by pjcollins** [comment]
Thanks for the report and suggestion, I've added this to https://github.com/xamarin/xamarin-android/pull/5572. Next time feel free to submit a PR! 😄
