### ISSUE TITLE
Support for UpdateEngine

### ISSUE THREAD

**Issue by michaelstonis** [xamarin/xamarin-android#5561]
It doesn't appear that there is support for the Android.OS.UpdateEngine APIs. Is there any planned support for this or any known limitations that would prevent using these APIs with a Xamarin.Android application?

**Comment by pjcollins** [comment]
Hello, could you help clarify the type(s) you're looking for? I couldn't find anything relevant in the Android.OS docs here:
https://developer.android.com/reference/android/os/package-summary?hl=en

A more general search doesn't appear to yield anything immediately relevant either:
https://developer.android.com/s/results?hl=en&q=UpdateEngine

Would you be able to provide a reference to the APIs you're looking for?

**Comment by michaelstonis** [comment]
Yea, the API we specifically were looking for is here: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/UpdateEngine.java

Here is an example of an application using it: https://github.com/bnblzq/call-update-engine/blob/master/java/com/example/liu/helloworld/MainActivity.java

**Comment by pjcollins** [comment]
I see, after some more searching it seems that this is a private/internal API. Unfortunately I do not believe that Xamarin.Android will attempt to support this at any point in the future.
