### ISSUE TITLE
Crash in LinkAssembliesNoShrink when using AddKeepAlivesStep

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5562]
Context: https://github.com/xamarin/GooglePlayServicesComponents/pull/419#issuecomment-769411572

`AddKeepAlivesStep` uses `Context` to get `System.GC.KeepAlive` method. When called from `LinkAssembliesNoShrink`, the context is not available.

We need to create new class based on `AddKeepAlivesStep` and provide method (or assembly lookup) to the base class, similar to how we do it for `FixAbstractMethodsStep`. This will allow us to avoid using `Context` there.

We should also add test in XA to check this scenario.

**Comment by mehmetavsar** [comment]
Would you suggest any workaround for this?
