### ISSUE TITLE
[Bug] Xamarin.Forms Android Failed to Create App Archive. Copy of the mdbs files failed.

### ISSUE THREAD

**Issue by developersimsek** [xamarin/xamarin-android#5584]
### Description

[severity:I’m unable to use this version]
On Windows 10 I am using Visual Studio Version 16.8.4. I am no longer able to create an android archive. The last output from Xamarin is this:
Creating directory ‘0708d92989054ec99c2cef4f08e9833d’…
Copying msym ‘Xamarin.AndroidX.AppCompat.AppCompatResources.dll’
Cannot create the archive file because the copy of mdbs files failed.

### Steps to Reproduce

1.  An empty project has been created
2.  Release Archive operation was done after all operations were completed.
3. Copying msym ‘Xamarin.AndroidX.AppCompat.AppCompatResources.dll’
Cannot create the archive file because the copy of mdbs files failed.

### Expected Behavior

Successful Apk or abb creation

### Actual Behavior

Creating directory ‘0708d92989054ec99c2cef4f08e9833d’…
Copying msym ‘Xamarin.AndroidX.AppCompat.AppCompatResources.dll’
Cannot create the archive file because the copy of mdbs files failed

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

Microsoft Visual Studio Enterprise 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

DevExpress Reporting Extension   1.0
A Visual Studio extension that invokes the Report Designer editor for report definition REPX files.

DevExpress Reporting Tools Extension   1.0
Extends Visual Studio with tools required for the Report Designer editor.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

DevExtreme.Design   18.1.6
DevExtreme Visual Studio integration package

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VisualSVN   7.3.0
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at https://www.visualsvn.com
Copyright © 2020 VisualSVN Software Ltd. All rights reserved.

Xamarin   16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

### Build Logs

[output.zip](https://github.com/xamarin/Xamarin.Forms/files/5863401/output.zip)

### Screenshots

![1](https://user-images.githubusercontent.com/23637417/105646638-fa825580-5eb1-11eb-88eb-2cc006ed923b.PNG)

**Comment by OpenInformaticaTrading** [comment]
Same issue here!

**Comment by S-Pourali** [comment]
thank you @KazyuraVasiliy .Changing "Archive Location" solved my issue.

**Comment by bodeg** [comment]
thank you @KazyuraVasiliy .Changing "Archive Location" solved my issue.

Maybe the SPACE in the path is the problem??

**Comment by BerndFfm** [comment]
This is an error I very often have in xamarin forms : The path ist too long for windows, only 256 characters are allowed.

So use very short path names where ever you can.

Greetings Bernd

**Comment by joaquin171993** [comment]
Thank you very much, that is the solution to change the path where the apk is saved :)

**Comment by joaquin171993** [comment]
> > The solution in my case was to edit archives location
> > ![image](https://user-images.githubusercontent.com/66713481/106563736-d207f480-655e-11eb-8ae6-8c6578cefc68.png)
> 
> Tested with your solutions, it's working. Thanks for sharing

Thank you very much, that is the solution to change the path where the apk is saved

**Comment by thE-iNviNciblE** [comment]
nice it works.

**Comment by kiflay** [comment]
> > The solution in my case was to edit archives location
> > ![image](https://user-images.githubusercontent.com/66713481/106563736-d207f480-655e-11eb-8ae6-8c6578cefc68.png)
> 
> Tested with your solutions, it's working. Thanks for sharing

This method works for me as well

**Comment by RicardoJosuePerezAltamirano** [comment]
I have same issue.

**Comment by mttm774** [comment]
> > The solution in my case was to edit archives location
> > ![image](https://user-images.githubusercontent.com/66713481/106563736-d207f480-655e-11eb-8ae6-8c6578cefc68.png)
> 
> Tested with your solutions, it's working. Thanks for sharing

Thank you very much, that is the solution to change the path where the apk is saved :)

**Comment by holecekp** [comment]
I was wandering why I archiving works for some of my projects and why it does not for the others. The reason was the length of the project name. Projects that had a slightly longer name exceeded the total length limit for the whole path and archiving failed. A better error message would be really helpful in these cases.

**Comment by Falco20019** [comment]
Has anyone tried if setting `LongPathsEnabled` in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
to `1` solves this? That helps with similar issues on windows (also in other VS cases). Just stumbled over it since a colleague ran into this issue and I was wondering, why it didn't appear for me.

**Comment by jevonie** [comment]
> The solution in my case was to edit archives location ![image](https://user-images.githubusercontent.com/66713481/106563736-d207f480-655e-11eb-8ae6-8c6578cefc68.png)

Thank you! I was looking for a fix after the update on VS

**Comment by zhyy2008z** [comment]
> I was wondering why archiving works for some of my projects and why it fails for the others. The reason was the length of the project name. Projects that had a slightly longer name exceeded the total length limit for the whole path and archiving failed. A better error message would be really helpful in these cases.

I have tried, it didn't work for me, too.

**Comment by zhyy2008z** [comment]
> Has anyone tried if setting `LongPathsEnabled` in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem` to `1` solves this? That helps with similar issues on windows (also in other VS cases). Just stumbled over it since a colleague ran into this issue and I was wondering, why it didn't appear for me.

I have tried, it didn't work for me, too.

**Comment by darm10** [comment]
Starting VS2022 as administrator works for me, looks like an issue with user rights.

**Comment by Falco20019** [comment]
It reappeared for me after the VS2022 update and I ran into it again. As well as two other colleagues... we have quite long file names where we have no influence on them. So shortening is the only option we have.

Would be great if this could be fixed in the future.

**Comment by jpobst** [comment]
This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

If this is still an issue, please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
