### ISSUE TITLE
Unable to access R.java system IO Exception

### ISSUE THREAD

**Issue by Nivedita-Puneet** [xamarin/xamarin-android#5591]
Visual studio 2019 community edition Version 16.5.4
Created a new project and installed Nuget Packages Xamarin.googleservices.Basement v117.1.0 and Xamarin.Googleservices.Base v117.1.0 and android Target framework is Android Q , xamarin forms version is v5.0.0.1931 and Xamarin download build solution version is 0.9
Build the solution am getting following error
Severity Code Description Project File Line Suppression State
Error Unhandled exception: System.IO.IOException: The process cannot access the file 'C:\HelloFirebasePush\HelloFirebasePush\HelloFirebasePush.Android\obj\Debug\100\android\src\com\google\android\gms\common\R.java' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at System.IO.File.Delete(String path)
at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
at Xamarin.Android.Tasks.GenerateLibraryResources.GenerateJava(Library library)
at Xamarin.Android.Tasks.AsyncTaskExtensions.<>c__DisplayClass0_1`1.b__0() HelloFirebasePush.Android

I wanted to upgrade Xamarin firebase push to latest version this upgrade is costing a lot of time. Can someone please help

**Comment by dellis1972** [comment]
Hi @Nivedita-Puneet 

This issue seems very similar to https://github.com/xamarin/xamarin-android/issues/4063. In that case making sure ` Xamarin.Build.Download` was updated to the latest version fixed the issue. 

Also it might be worth trying to upgrade your Visual Studio to 16.8, 16.5 is quite old now and there have been a number of build improvements since then that might help.

**Comment by Nivedita-Puneet** [comment]
Thank you,

I have tried Upgrading the build Xamarin.build.download to latest version, let me try to updgrade the visual studio and add all the packages again and see if this resolves Build error.
