### ISSUE TITLE
No artifacts for Xamarin android Linux 16-8 in azure pipelines

### ISSUE THREAD

**Issue by Akademiksdc** [xamarin/xamarin-android#5613]
Dear colleagues @pjcollins @brendanzagaeski @jonpryor, 
Could you please describe how to re-run the existed build for ex. https://dev.azure.com/xamarin/public/_build/results?buildId=32563&view=results to retrieve the artifacts for proper version of Xamarin Android? 

Or do you have any storage for an artifacts of previous versions for the Xamarin Android? 

What we are doing: we are trying to migrate from Windows to Linux and we want to have the same versions on Windows and Linux at the same time, but it's impossible to find 16-7 or 16-8 artifacts for it.

**Comment by Akademiksdc** [comment]
Could you please provide any info?

**Comment by pjcollins** [comment]
@Akademiksdc Sorry, I don't know why these artifacts disappeared from the old build... I re-ran it and it should hopefully have Linux packages soon: https://dev.azure.com/xamarin/public/_build/results?buildId=35046&view=results. Please note that these artifacts are "unofficial" and do not receive any real testing, so your usage success mileage may vary.
