### ISSUE TITLE
[illink] New feature switch to disable usage of S.C.WriteLine in our Logger

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5622]
We use `WriteLine` method as fallback in our `Android.Runtime.Logger` in case liblog is not present (originally intended for desktop use). https://github.com/xamarin/xamarin-android/blob/39576f237961fb1f0d05a57bb988ed742620c465/src/Mono.Android/Android.Runtime/Logger.cs#L58-L59

It pulls in `AndroidLogPrint` in simple XA apps.

```
--- Raw dependencies: 'AndroidLogPrint' --------------------------------

--- Method:System.Void Interop/Logcat::AndroidLogPrint(Interop/Logcat/LogLevel,System.String,System.String) dependencies ---
Dependency #1
        Method:System.Void Interop/Logcat::AndroidLogPrint(Interop/Logcat/LogLevel,System.String,System.String)
        | Method:System.Void System.LogcatStream::Write(System.ReadOnlySpan`1<System.Byte>) [1 deps]
        | TypeDef:System.LogcatStream:System.Console.dll [3 deps]
        | Method:System.Void System.LogcatStream::.ctor() [1 deps]
        | Method:System.IO.Stream System.ConsolePal::OpenStandardOutput() [1 deps]
        | Method:System.IO.Stream System.Console::OpenStandardOutput() [1 deps]
        | Method:System.IO.TextWriter System.Console::<get_Out>g__EnsureInitialized|25_0() [1 deps]
        | Method:System.IO.TextWriter System.Console::get_Out() [1 deps]
        | Method:System.Void System.Console::WriteLine(System.String,System.Object,System.Object,System.Object) [1 deps]
        | Method:System.Void Android.Runtime.Logger::Log(Android.Runtime.LogLevel,System.String,System.String) [10 deps]
        | TypeDef:Android.Runtime.Logger:Mono.Android.dll [16 deps]
        | Other:C:\Users\rodo\android-toolchain\dotnet\packs\Microsoft.Android.Sdk.win-x64\11.0.200-ci.master.104\targets\..\PreserveLists\Mono.Android.xml

Found 1 matches
```

If we hide that behind feature switch, whole `System.Console.dll` or at least part of it will be linked away for Release apps.

**Comment by marek-safar** [comment]
That code should be just deleted. The Console.WriteLine calls the exact same method https://github.com/dotnet/runtime/blob/master/src/libraries/System.Console/src/System/ConsolePal.Android.cs#L19

**Comment by jonpryor** [comment]
@marek-safar [wrote](https://github.com/xamarin/xamarin-android/issues/5622#issuecomment-782034444)

> That code should be just deleted.

While on .NET 6 the same `__android_log_print()`/etc. function is invoked, they are *not* "the same" in that a *different* `tag` value is used, and having "everything" originate from the `DOTNET` tag isn't helpful or desired.
