### ISSUE TITLE
Max_Path error due to really long file names in obj folder

### ISSUE THREAD

**Issue by BenjaminCharlton** [xamarin/xamarin-android#5624]
### Steps to Reproduce

1. Make a new Xamarin Forms application from the default Visual Studio template.
2. Save in a location with some degree of nesting. Doesn't need to be a crazy amount. Mine was at C:\Users\Administrator\OneDrive\Hobbies\Software\Developments\ProjectNameAboutThisLength. That's about 90 characters long.
3. Build and run the Android application

### Expected Behavior

Should build and run fine. All the other projects in my solution (including the iOS project) are building fine.

### Actual Behavior

I get this build error:

```
Failed to generate Java type for class: Android.Support.V4.View.Accessibility.AccessibilityManagerCompat/IAccessibilityStateChangeListenerImplementor due to MAX_PATH: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\OneDrive\Hobbies\Software\Developments\ProjectNameAboutThisLength\ProjectNameAboutThisLength.Clients.XamarinClient.Android\obj\Debug\90\android\src\mono\android\support\v4\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
   at Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache)	ProjectNameAboutThisLength.Clients.XamarinClient.Android
```

I saw [on this page](https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.2) that all the file names should now be short, minimizing the risk of a MAX_PATH error, and therefore `UseShortFileNames=false` is no longer needed or supported.

But this looks quite long:

`obj\Debug\90\android\src\mono\android\support\v4\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java`

Is that the short naming convention that's expected or is it using the long naming convention for some reason?

### Version Information

Microsoft Visual Studio Community 2019 Version 16.8.5
Using .NET Core 3.1

**Comment by jonathanpeppers** [comment]
For Java code to compile, it needs this directory structure:
```
mono\android\support\v4\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java
```

The type name is 🤦 

    mono.android.support.v4.view.accessibility.AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor

I don't see how we can solve this problem, if we have to call `javac` during the build.

Can you enable long paths via this registry key?

https://docs.microsoft.com/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by BenjaminCharlton** [comment]
Sorry for the delay circling back on this.
Thank you for your recommendation. I have managed to change the registry key value.
Unfortunately I ended up moving all of my code to a location closer to the root of the C:\ drive, and shortening my project name anyway, prior to implementing your suggestion.
So, while I can't be certain if this is the fix or not, it certainly doesn't hurt and everybody with my issue would be wise to do it.

**Comment by BenjaminCharlton** [comment]
I figured that I would close this seeing as you confirmed that the paths generated by my Xamarin project were not unusually long.

**Comment by venkatsunilm** [comment]
> For Java code to compile, it needs this directory structure:
> 
> ```
> mono\android\support\v4\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java
> ```
> 
> The type name is 🤦
> 
> ```
> mono.android.support.v4.view.accessibility.AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor
> ```
> 
> I don't see how we can solve this problem, if we have to call `javac` during the build.
> 
> Can you enable long paths via this registry key?
> 
> https://docs.microsoft.com/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later

Following the above link worked after restarting the Visual Studio, and running the clean command.
