### ISSUE TITLE
How can we use HybridWebView in Xamarin Android?

### ISSUE THREAD

**Issue by genifycom** [xamarin/xamarin-android#5630]
### Steps to Reproduce
I want to call a Xamarin C# function from a page in a WebView without using ShouldIntercept request the same way as the sample in XFWebViewInteropDemo.Android but I cannot find a Xamarin Android only sample.

Why is there no WebViewRenderer on Xamarin.Android?

Type and use WebViewRenderer in Xamarin Android

**Comment by jpobst** [comment]
Xamarin.Android simply exposes the Android APIs as provided by Google.  These APIs do not contain a `WebViewRenderer` so there isn't one in Xamarin.Android.  You might be able to find a Java sample that does want you want using only Android APIs and convert it to Xamarin.Android.

Alternatively you can look at the Android-specific code of Xamarin.Forms and try to mimic what they do without the rest of Xamarin.Forms: https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs.
