### ISSUE TITLE
AndroidUseInterpreter should work in net6

### ISSUE THREAD

**Issue by joj** [xamarin/xamarin-android#5633]
In .net4 AndroidUseInterpreter used to switch the runtime directory with one that includes an "-interpreter" suffix. That would automatically make the runtime use the interpreter. For net6, the runtime includes both versions in the package,
~~and the way to switch interpreter on is to add this environment variable:~~
~~`debug.mono.runtime_args=--interp=-inline`~~

The parameter is at the moment unchanged for net6, meaning that it adds a prefix that doesn't work anymore, and it doesn't do the environment, which is needed. The ask is to switch to that and then make sure interpreter works (that may require some help from mono runtime).

Thanks! 
J

**Comment by jonathanpeppers** [comment]
This would be adding some new logic to:

https://github.com/xamarin/xamarin-android/blob/214dd76d9441c9974775f0b29feec0d5d8d1097f/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1503-L1518

Basically emit some extra `@(AndroidEnvironment)` lines for .NET 6 when `$(AndroidUseInterpreter)` is `true`.

An additional work item would be to standardize on an MSBuild property for both iOS/Android, as `$(MTouchExtraArgs)` is used for enabling the interpreter at the moment.

**Comment by lambdageek** [comment]
I tried `AndroidUseInterpreter` and it "works" in that the runtime tries to start up with interp support, but it breaks because it passes `MONO_AOT_MODE_LAST` which used to work with old mono, but not net6 mono.

I'm working on a PR to update to use `MONO_AOT_MODE_INTERP_ONLY` (on top of #5632)

**Comment by lambdageek** [comment]
One thing we need to figure out for hot reload:  we need to pass `mono_ee_interp_init("-inline")` some time shortly after `mono_jit_set_aot_mode (mode);` when hot reload is enabled.

**Comment by jonathanpeppers** [comment]
@lambdageek do we still need to do something on the MSBuild side when `$(AndroidUseInterpreter)` is `true`?

Do we need `debug.mono.runtime_args=--interp=-inline` anymore?

**Comment by joj** [comment]
Can we make AndroidUseInterpreter opt out (meaning, default to true when debugging)? What do you think? That will enable these new functionalities by default, and allow users to turn it off if it's causing problems.

**Comment by lambdageek** [comment]
There's two orthogonal issues:
1. Is AndroidUseInterpreter usable with net6 now? Yes.
2. Should something more be done to enable hot reload and other experiences in Debug configurations? Also yes, but I don't think it should be controlled by AndroidUseInterpreter or by changing defaults. We talked about having some property that indicates that hot reload is needed. @StephaneDelcroix 

(On the runtime side I will be implementing support for the new DOTNET_MODIFIABLE_ASSEMBLIES environment variable setting dotnet/runtime#47274 which will obviate the need to explicitly turn off inlining with environment variables. But obviously the new env var will need to be set)
