### ISSUE TITLE
Mark all Android runtime pack assemblies as trimmable

### ISSUE THREAD

**Issue by marek-safar** [xamarin/xamarin-android#5638]
All Android assemblies should be marked as [trimmable](https://github.com/mono/linker/blob/main/docs/design/trimmed-assemblies.md#assemblymetadataistrimmable-true) and [code](https://github.com/xamarin/xamarin-android/blob/master/build-tools/create-packs/Microsoft.Android.Sdk.proj#L118) which tries to override the settings should be removed.

This is the preferred way to tell linker to include assemblies in the trimming process in .NET6 P3

**Comment by jonathanpeppers** [comment]
I think we already have this:

https://github.com/xamarin/xamarin-android/blob/72da34928f3ed0abce5e0c0db313fbf54b428b58/build-tools/create-packs/Microsoft.Android.Sdk.proj#L107-L119

We have `IsTrimmable="true"` on the `@(KnownFrameworkReference)`, or do we also need something else? Thanks.

**Comment by marek-safar** [comment]
As explained in the linked design doc

> Instead of using IsTrimmable metadata in the SDK to control trimmable assemblies, we will move to a model where all trimmable SDK assemblies are built with [assembly: AssemblyMetadata("IsTrimmable", "True")].
