### ISSUE TITLE
Compiling .NET 6 projects with Target SDK less than 30

### ISSUE THREAD

**Issue by LanceMcCarthy** [xamarin/xamarin-android#5643]
### Steps to Reproduce

1. Clone the official .NET6  Mobile Samples app and open in VS 2019 Preview (16.9.x) https://github.com/dotnet/net6-mobile-samples
2. Set the Android Target SDK to 29 by editing AndroidManifest.xml
3. Make sure Android project is set as Startup Project, then compile

### Expected Behavior

Project compiles with Target SDK version

### Actual Behavior

Compiler errors out, expecting SDK 30.

This screenshot explains everything, notice the following items:

- The `android:targetSdkVersion` is set to `29`
- The TargetFramework is set to `net6.0-android` (note: I also tried net6.0-android29)

![image](https://user-images.githubusercontent.com/3520532/108551710-4e6c3880-72be-11eb-94b6-9babcbce5731.png)

### Log File

Logcat instructions are not working in this VS2019 preview setup. 

### Version Information

Here are the VS2019 PReview About details:

```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0
VisualStudio.16.Preview/16.9.0-pre.4.0+31004.235
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA292
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.9.677.50750
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.677.50750
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.677.50750
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.9.677.50750
Azure Functions and Web Jobs Tools

C# Tools   3.9.0-4.21104.8+2fc92d84e746c3aab75f0930278ea6675cd5bb5c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40201.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

Telerik Reporting Tools   3.44.11.0
Complete .NET Reporting Solution for Web, Mobile and Desktop Applications. For more information please visit http://www.telerik.com/reporting. 

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-4.21104.8+2fc92d84e746c3aab75f0930278ea6675cd5bb5c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.258 (d16-9@82c3a34)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.309 (remotes/origin/9a5259fb55e54a445c145ab5ea29c04a418deed2@9a5259fb5)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.65 (0020050)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d


Xamarin.iOS and Xamarin.Mac SDK   14.14.1.0 (17845a189)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by jonathanpeppers** [comment]
Xamarin.Android pre-.NET 6 has the behavior where if you have `$(TargetFrameworkVersion)` higher than `targetSdkVersion`, it forces the `targetSdkVersion` to match because you could be using an API-30 API from C#. You could get a `javac` compiler error if it didn't do this.

Since there is only one `Mono.Android.dll` in .NET 6 that is API 30, it's using the same logic and bumping `targetSdkVersion` to 30.

I think it's worth leaving this open to consider what we should do here. Is there a case you specifically want 29? or just that you didn't have API 30 installed? I didn't check the calendar but Google Play is probably *requiring* 30 soon.

**Comment by LanceMcCarthy** [comment]
> Is there a case you specifically want 29? or just that you didn't have API 30 installed? I didn't check the calendar but Google Play is probably _requiring_ 30 soon.

Correct, I didn't have 30 installed because it is only available in the VS 2019 Preview SDK Manager.  I build production software for myself and debug client problems, I try to avoid having preview SDKs installed. The only exception to that is .NET core preview because I can easily avoid problems with a global.json. 

Like you said Google play will require 30, like they just did for 29, but I can't imagine them doing that any time soon. They literally just forced API 29/android 10 minimum. Please let me know if you have a confirmed time frame for forcing 30.

**Comment by jonathanpeppers** [comment]
API 30 required March 2021 for new apps, Nov 2021 for all apps:

https://developer.android.com/distribute/play-policies

The current timeline for .NET 6 is November:

https://github.com/dotnet/core/blob/master/roadmap.md

So we might not need to do anything here? Would make sense for API 30 to be required for .NET 6, with the current plan to support back to API 21.

**Comment by LanceMcCarthy** [comment]
I agree, since we can't publish with .NET6 anyways, there's no need to support API29. 

I can't imagine a valid scenario where a project using .NET6 needs API 29 as the target SDK... you wont be able to publish it anyways.

**Comment by jonathanpeppers** [comment]
Closing this, as I don't think we need to do anything here for .NET 6.

We can reevaluate this if someone comes up a reason for using older `targetSdkVersion`'s like 29.
