### ISSUE TITLE
dotnet cli might be launching app twice in some cases

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#5648]
### Steps to Reproduce

Context: https://discord.com/channels/732297728826277939/732297837953679412/811986634718314518

1. Using [HelloForms](https://github.com/dotnet/net6-mobile-samples/tree/main/HelloForms), remove all but the `net6.0-android` framework
2. Run `dotnet build HelloForms -t:Run -f net6.0-android`

It appears to launch the app twice:

```
$ dotnet build HelloForms -t:Run -f net6.0-android
Microsoft (R) Build Engine version 16.9.0-preview-21103-02+198f3f262 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored net6-samples/HelloForms/HelloForms.csproj (in 553 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  HelloForms -> net6-samples/HelloForms/bin/Debug/net6.0-android/HelloForms.dll
  Performing Streamed Install
  Success
  Starting: Intent { cmp=com.microsoft.net6.helloforms/crc6454ad0c421ff6d919.MainActivity }
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  HelloForms -> net6-samples/HelloForms/bin/Debug/net6.0-android/HelloForms.dll
  Performing Streamed Install
  Success
  Starting: Intent { cmp=com.microsoft.net6.helloforms/crc6454ad0c421ff6d919.MainActivity }

Build succeeded.
```

If you drop the `-f` and just run `dotnet build HelloForms -t:Run`, it works normally.

Investigate what is going on here...

### Version Information

.NET 6.0.100-preview.1.21103.13

**Comment by filipnavara** [comment]
MSBuild forks out for each `TargetFramework` in `TargetFrameworks`. It looks like the Run is execute both in the inner per-TFM loop and the other one. Running with `/bl` should produce a log that would easily confirm or refute the theory.

**Comment by jonathanpeppers** [comment]
Since filing this, I've run this command many times:
```
dotnet build HelloMaui -t:Run -f net6.0-android
```
It definitely doesn't launch the app twice in .NET 6 Preview 4 or higher, closing this.
