### ISSUE TITLE
VS2019 16.9.0 Prev2 - Effect of BundleAssemblies 

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#5657]
Previously in my release build, I had the following

```
<BundleAssemblies>false</BundleAssemblies>
<AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
<AndroidAotAdditionalArguments>no-write-symbols,nodebug</AndroidAotAdditionalArguments>
```
That resulted in an aab with estimated download sizes of between 16.58 Min and 16.92 Max via the bundle tool.

I then changed to the following 

```
<BundleAssemblies>true</BundleAssemblies>
<AotAssemblies>true</AotAssemblies>
<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
<AndroidAotMode>hybrid</AndroidAotMode>
<AndroidAotAdditionalArguments>no-write-symbols,nodebug</AndroidAotAdditionalArguments>
```

That increased the Min to 22.09 and the Max to 24.96 which was not what I was hoping for. I thought that by removing the assemblies folder and its contents there may have been a reduction.

Could someone please advise how this is meant to work or am I just doing it wrong?

**Comment by gmck** [comment]
Just to be complete I've added the following re the sizes on the device from the apks set.

The large aab results in an apk on the device of 57.96MB
and the smaller aab results in an apk of 34.68MB.

Device Pixel 4a

**Comment by jonathanpeppers** [comment]
`$(BundleAssemblies)` is using something from Mono called `mkbundle`, that is an old way of "compressing" managed .NET assemblies inside your Android app.

In Xamarin.Android 11.0 we created a new `$(AndroidEnableAssemblyCompression)` property that is actually on by default for `Release` builds:

https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.0#smaller-app-package-sizes

☝️ this is already on for your app unless you turn it off.

I would not recommend using `$(BundleAssemblies)` anymore, as it won't be available in .NET 6.

Using AOT may complicate the above settings, as all your managed .NET assemblies become `libaot-*.so` files in your Android application. AOT will improve runtime/startup performance at the cost of larger app sizes.

Hope that helps, thanks!

**Comment by gmck** [comment]
@jonathanpeppers . Thanks for the feedback. I reverted to what I had previously <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot> seems to do the job and my cold start times are still sub 1 sec.

Also thanks to the team for the Release notes on 11.2 notes, great to have that page working again.

**Comment by jonathanpeppers** [comment]
Let us know if you need something else, thanks!
