### ISSUE TITLE
Exception rises when change theme (dark or light)

### ISSUE THREAD

**Issue by felipechavez** [xamarin/xamarin-android#5660]
Hi guys, we are having troubles after updating Xamarin.AndroidX nugets. When we change the theme the app crashes. Does anyone have the same problem?

### Steps to Reproduce

1. Open your app
2. Stay in your main page
3. Change theme (dark or light)

### Expected Behavior
Change theme without problem.
### Actual Behavior

This happens after updating a bunch of Xamarin.AndroidX nugets.

![image](https://user-images.githubusercontent.com/34903236/109177741-e2c71700-7766-11eb-9ebd-0f28f6e954c6.png)

This is the actual setup of the package references:

>   
    <PackageReference Include="Xamarin.Android.Arch.Core.Common">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Core.Runtime">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.Common">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.Extensions">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.LiveData">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.LiveData.Core">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.Runtime">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.ViewModel">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Annotations">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Collections">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Compat">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Core.UI">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.CursorAdapter">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Fragment">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Interpolator">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Loader">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Media.Compat">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v4">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v7.RecyclerView">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.VersionedParcelable">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat">
      <Version>1.2.0.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat.AppCompatResources">
      <Version>1.2.0.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat.Resources">
      <Version>1.1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Browser">
      <Version>1.3.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Concurrent.Futures">
      <Version>1.1.0.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Collection">
      <Version>1.1.0.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Concurrent.Futures">
      <Version>1.0.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Core">
      <Version>1.3.2.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4">
      <Version>1.0.0.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Service">
      <Version>2.3.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Media">
      <Version>1.2.1.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.MediaRouter">
      <Version>1.2.2.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Migration">
      <Version>1.0.8</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Paging.Common">
      <Version>2.1.2.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Paging.Runtime">
      <Version>2.1.2.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Palette">
      <Version>1.0.0.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.RecyclerView">
      <Version>1.1.0.8</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Room.Runtime">
      <Version>2.2.6.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.VersionedParcelable">
      <Version>1.1.1.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Work.Runtime">
      <Version>2.5.0.1</Version>
    </PackageReference>

### Version Information

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

### Log File

> 02-25 15:49:45.833 F/.XXX.XXXX(30269): java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodA called with pending exception java.lang.IllegalStateException: Fragment FragmentContainer{95e55ac} (faff2b7b-f999-4002-b5e9-2a05605ffe19) id=0x1} does not have a view
02-25 15:49:45.833 F/.XXX.XXXX(30269): java_vm_ext.cc:570] (Throwable with no stack trace)
02-25 15:49:45.833 F/.XXX.XXXX(30269): java_vm_ext.cc:570] 
02-25 15:49:45.833 F/.XXX.XXXX(30269): java_vm_ext.cc:570]     in call to CallObjectMethodA
02-25 15:49:45.833 F/.XXX.XXXX(30269): java_vm_ext.cc:570]     from void crc643f46942d9dd1fff9.FormsAppCompatActivity.n_onStart()
Thread started: <Thread Pool> 23
02-25 15:49:46.003 F/.XXX.XXXX(30269): thread.cc:2348] No pending exception expected: java.lang.IllegalStateException: Fragment FragmentContainer{95e55ac} (faff2b7b-f999-4002-b5e9-2a05605ffe19) id=0x1} does not have a view
02-25 15:49:46.003 F/.XXX.XXXX(30269): thread.cc:2348] (Throwable with no stack trace)
02-25 15:49:46.003 F/.XXX.XXXX(30269): thread.cc:2348] 
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] Runtime aborting --- recursively, so no thread-specific detail!
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 00 pc 00493b03  /apex/com.android.runtime/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+115)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 01 pc 005651ca  /apex/com.android.runtime/lib/libart.so (art::Runtime::Abort(char const*)+2794)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 02 pc 000249b3  /apex/com.android.runtime/lib/libartbase.so (_ZNSt3__110__function6__funcIPFvPKcENS_9allocatorIS5_EES4_EclEOS3_+35)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 03 pc 0000bac7  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+727)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 04 pc 005b818a  /apex/com.android.runtime/lib/libart.so (art::Thread::AssertNoPendingException() const+1226)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 05 pc 001704fc  /apex/com.android.runtime/lib/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+60)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 06 pc 0015992b  /apex/com.android.runtime/lib/libart.so (art::ClassLinker::DoResolveType(art::dex::TypeIndex, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>)+187)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 07 pc 005e882f  /apex/com.android.runtime/lib/libart.so (_ZN3art8verifier4impl12_GLOBAL__N_114MethodVerifierILb0EE6VerifyEv$09bf97eb2c0d684adb6d215f7005036e+1823)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 08 pc 005ecd78  /apex/com.android.runtime/lib/libart.so (art::verifier::MethodVerifier::FindLocksAtDexPc(art::ArtMethod*, unsigned int, std::__1::vector<art::verifier::MethodVerifier::DexLockInfo, std::__1::allocator<art::verifier::MethodVerifier::DexLockInfo>>*, unsigned int)+872)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 09 pc 00490cb2  /apex/com.android.runtime/lib/libart.so (art::Monitor::VisitLocks(art::StackVisitor*, void (*)(art::ObjPtr<art::mirror::Object>, void*), void*, bool)+818)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 10 pc 00491f89  /apex/com.android.runtime/lib/libart.so (art::MonitorObjectsStackVisitor::VisitFrame()+281)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 11 pc 0058c888  /apex/com.android.runtime/lib/libart.so (_ZN3art12StackVisitor9WalkStackILNS0_16CountTransitionsE0EEEvb+2008)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 12 pc 005b6b8e  /apex/com.android.runtime/lib/libart.so (art::Thread::DumpJavaStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, bool) const+1022)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 13 pc 005b1f79  /apex/com.android.runtime/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+1017)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 14 pc 005acdf1  /apex/com.android.runtime/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+65)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 15 pc 005d2c61  /apex/com.android.runtime/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+929)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 16 pc 005cafc4  /apex/com.android.runtime/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+1556)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 17 pc 005c9dfc  /apex/com.android.runtime/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+2268)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 18 pc 00579680  /apex/com.android.runtime/lib/libart.so (art::AbortState::DumpAllThreads(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, art::Thread*) const+448)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 19 pc 00564ce0  /apex/com.android.runtime/lib/libart.so (art::Runtime::Abort(char const*)+1536)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 20 pc 000249b3  /apex/com.android.runtime/lib/libartbase.so (_ZNSt3__110__function6__funcIPFvPKcENS_9allocatorIS5_EES4_EclEOS3_+35)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 21 pc 0000bac7  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+727)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 22 pc 003e539d  /apex/com.android.runtime/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1725)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 23 pc 003e55a4  /apex/com.android.runtime/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, char*)+116)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 24 pc 003d6b45  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+69)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 25 pc 003d558e  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+1294)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 26 pc 003d4729  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+745)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 27 pc 003d99e8  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CheckCallArgs(art::ScopedObjectAccess&, art::(anonymous namespace)::ScopedCheck&, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, art::InvokeType, art::(anonymous namespace)::VarArgs const*)+200)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 28 pc 003da5b0  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodA(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue const*, art::Primitive::Type, art::InvokeType)+944)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 29 pc 003c4889  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallObjectMethodA(_JNIEnv*, _jobject*, _jmethodID*, jvalue const*)+73)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 30 pc 00004e68  /data/app/com.gazmows.XXX.XXXXn-dvq9aJorgtIuM6SZxOhLQw==/lib/x86/libxa-internal-api.so (java_interop_jnienv_call_object_method_a+56)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 31 pc 0000049f  <anonymous:bea53000> (???)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:630] 
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:638] No pending exception expected: java.lang.IllegalStateException: Fragment FragmentContainer{95e55ac} (faff2b7b-f999-4002-b5e9-2a05605ffe19) id=0x1} does not have a view
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:638] (Throwable with no stack trace)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:638] 
02-25 15:49:46.017 F/libc    (30269): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 30269 (.XXX.XXXXn), pid 30269 (.XXX.XXXXn)
02-25 15:49:46.015 F/.XXX.XXXX(30269): runtime.cc:638] 
**Java.Lang.IllegalStateException:** 'Loading...'

**Comment by stepkillah** [comment]
not sure why it's closed, but it still seems to be an issue https://github.com/xamarin/Xamarin.Forms/issues/13895
