### ISSUE TITLE
please expose missing MicrophoneInfo, getActiveMicrophones () API 28+

### ISSUE THREAD

**Issue by gsgou** [xamarin/xamarin-android#5667]
https://developer.android.google.cn/reference/android/media/MicrophoneInfo

**Comment by jpobst** [comment]
Are you sure your project is targeting Android 9.0+?  Both `MicrophoneInfo` and `AudioRecord.ActiveMicrophones` exist:

![image](https://user-images.githubusercontent.com/179295/109406013-4e61dd80-793b-11eb-9e04-69997f1a3ce2.png)

![image](https://user-images.githubusercontent.com/179295/109406021-5caff980-793b-11eb-8d7a-d97188064258.png)

**Comment by gsgou** [comment]
@jpobst thanks for your hint. My project targets android 11.
The service was in a submodule fork of a lib which was targeting API 27.
You can close the ticket, thanks for pointing me to the right direction ;)
