### ISSUE TITLE
[tests] run Smoke MSBuild Tests is green when the tests are failing

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5674]
Example build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4516468&view=logs&j=cac0e8d3-0ef5-5d2b-b57e-e8fde7204df3&t=d8447b4e-561a-55bf-52c2-03d87ae8f26c

End of the log shows failing tests and `0` exit code. I would expect noz-zero exit code and failed build step.
```
Test Run Summary
  Overall result: Failed
  Test Count: 65, Passed: 63, Failed: 2, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 2, Errors: 0, Invalid: 0
  Start time: 2021-03-02 12:33:22Z
    End time: 2021-03-02 13:13:27Z
    Duration: 2404.467 seconds

Results (nunit3) saved as TestResult-SmokeMSBuildTests-WinBuildTree-Release.xml
##[debug]$LASTEXITCODE: 0
##[debug]Exit code: 0
##[debug]Leaving Invoke-VstsTool.
##[debug]Leaving C:\a\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.180.1\powershell.ps1.
Finishing: run Smoke MSBuild Tests - Windows Build Tree
```

**Comment by radekdoulik** [comment]
The exit code should contain the number of failing tests. https://docs.nunit.org/articles/nunit/running-tests/Console-Runner.html

In the above build it does not. @jonathanpeppers thinks it might be cause by duplicated tests result files between 2 steps, so hopefully #5676 will fix it.

**Comment by jonathanpeppers** [comment]
Oh... are these `set` commands making `nunit3-console.cmd` always exit with 0?

https://github.com/xamarin/xamarin-android/blob/9e6ce03ca2d72f5415a2a1650185ba46113cc3dd/build-tools/scripts/nunit3-console.cmd#L23-L25
