### ISSUE TITLE
Deployed apk could'n find dll method error.

### ISSUE THREAD

**Issue by yunusemreelagoz** [xamarin/xamarin-android#5688]
Hello,

I have a Xamarin project.  I can build and run project without any problem. but when I chose release mode and distrubute apk to device, app is openning but throwing an error that "dll method not found".

**Comment by jpobst** [comment]
This sounds like an issue with the Linker: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker.

Hopefully that will point you in the correct direction.

If not, you will need to provide information for us to help you, like the complete error message / stack trace, and any other logs that are relevant.
