### ISSUE TITLE
[net6] The ABI specific `System.Private.CoreLib.dll` is big

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#5697]
We should probably bring that to runtime team attention or enable split ABI apks as default on net6.

The compressed assembly is now 500k+ and we have one per each ABI in the apk.

**Comment by jonathanpeppers** [comment]
Since, we currently have a general improvement on file size for .NET 6, I'm moving this to a future milestone.

**Comment by jonpryor** [comment]
Closing as "duplicate" of issue #5249: we should enable split ABI `.aab` files.
