### ISSUE TITLE
Investigate and fix MSBuild smoke test issues on Linux

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#5701]
Context: https://github.com/xamarin/xamarin-android/pull/5681#issuecomment-790017891

We should extend the test coverage of our Linux build and smoke test job.

**Comment by jonpryor** [comment]
Fixed by? https://github.com/xamarin/xamarin-android/commit/1b71da0cd3a44861b006ac41c77a24eedf066281

**Comment by pjcollins** [comment]
Commit 1b71da0cd3a44861b006ac41c77a24eedf066281 moved Linux builds to a new 1ES Managed machine pool, but didn't change build/test scope at all. Extending test coverage for Linux should still be looked at eventually if we want to promote the build artifacts being created there.

**Comment by pjcollins** [comment]
The smoke test issues mentioned in #5681 are fixed by #6585, and I will plan to separate out Linux tests into a separate job.
