### ISSUE TITLE
Aapt2ToolPath is not being searched for in android-sdk\build-tools

### ISSUE THREAD

**Issue by jojorne** [xamarin/xamarin-android#5707]
### Steps to Reproduce

1. Just go to "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android" and there you will find an outdated version of the "aapt2.exe";
2. Rename it to "aapt2.ex_" and you will see that when you try to compile a project it doesn't look in "android-sdk\build-tools".

### Expected Behavior

Try to search for "aapt2.exe" in the "android-sdk\build-tools" directory **_first_**!

### Actual Behavior
When you try to compile a project it uses an outdated version of "aapt2.exe" found in "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android".

### Version Information
Visual Studio 16.9.0
AAPT2 version:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-6503028
C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.2>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-6739378

**Comment by jojorne** [comment]
PS: The old version in "MSBuild\Xamarin\Android" is crashing on my pc too. Replacing it with the one in "android-sdk\build-tools" fixs it.

**Comment by dellis1972** [comment]
@jojorne 

There is a reason why we search in our directory by default. We have had issues in the past where versions of `aapt2.exe` were broken in the sdk for the features we are using, or the user had an older version which did not support the features we need. So we decided to ship our own `known` working version. 

If you want to completely override our default behaviour you should be able use the following in the first `PropertyGroup` section of your csproj file

```
<Aapt2ToolPath>$(AndroidSdkPath)build-tools\30.0.2</Aapt2ToolPath>
```

That should override the path. In the mean time we will look at updating the version of `aapt2` we ship. 
It would be interesting to see what crash you are getting from the version we ship.

**Comment by jojorne** [comment]
@dellis1972

When compiling any Android project like MonoGame or Xamarin.Forms, AAPT2 will crash with:
Unhandled exception at 0x012D966D in aapt2.exe: 0xC000001D: Illegal Instruction.
Unhandled exception at 0x0148966D in aapt2.exe: 0xC000001D: Illegal Instruction.
Unhandled exception at 0x0164966D in aapt2.exe: 0xC000001D: Illegal Instruction.
![AAPT2 Crash](https://user-images.githubusercontent.com/18329136/110398031-b908cc80-8051-11eb-813a-e3edc12a2cab.png)

This other error appears in Xamarin Diagnostics pane:
AutoSdk cannot resolve dependencies: platforms/android-30, build-tools/30.0.2@30.0.2, cmdline-tools/2.1@2.1
[Xamarin Diagnostics Pane.log](https://github.com/xamarin/xamarin-android/files/6104859/Xamarin.Diagnostics.Pane.log)

And this last error, which is strange because I do have cmdline-tools installed, appears in Xamarin pane when opening the Android SDK Manager::
Android component "tools" is obsolete, please install "cmdline-tools"
Trying to fallback to "tools"...
File 'C:\Program Files (x86)\Android\android-sdk\cmdline-tools\android.bat' not found for 'Android SDK Core'
File 'C:\Program Files (x86)\Android\android-sdk\cmdline-tools\mksdcard.exe' not found for 'Android SDK Core'
File 'C:\Program Files (x86)\Android\android-sdk\cmdline-tools\emulator.exe' not found for 'Android SDK Core'
[Xamarin Pane.log](https://github.com/xamarin/xamarin-android/files/6104860/Xamarin.Pane.log)

Perhaps all of these errors appears to be a misconfiguration caused by an update?

**Comment by jonathanpeppers** [comment]
Hi @jojorne, we redistribute `aapt2` from maven. Google engineers recommended for us to start doing this.

There is a new "stable" one: https://mvnrepository.com/artifact/com.android.tools.build/aapt2/4.1.2-6503028

Does this one work for you? [aapt2.zip](https://github.com/xamarin/xamarin-android/files/6131146/aapt2.zip)

If not I can try bumping to one of the beta versions that has the suffix `-6739378`.

**Comment by jojorne** [comment]
No, still crashing. The aapt2 version appears to be the same as Visual Studio, but the file size is different.
D:\Documents\Downloads\Compressed>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-6503028

Tho the one from the Android SDK works (android-sdk\build-tools\30.0.2\aapt2.exe). I just don't know if the SDK version is in Maven. I'm wondering, could it be the CPU? I'm on an AMD Phenom II and it does not have support to a few new instructions. Tho, I dont think so since the version on the SDK is higher.

**Comment by jonathanpeppers** [comment]
It appears `aapt2 version` only prints the version after the `-`. I'm not sure exactly what versioning scheme they are going for...

Does this version work: [aapt2.zip](https://github.com/xamarin/xamarin-android/files/6131701/aapt2.zip)

Came from this one: https://mvnrepository.com/artifact/com.android.tools.build/aapt2/4.2.0-beta05-6840111

```
Android Asset Packaging Tool (aapt) 2.19-6840111
```

**Comment by jojorne** [comment]
No, still does not work. I found this on google: It tries to use pshufb (SSSE3) which is not supported by the AMD Phenom II CPU.

Tho all the AAPT2 from the SDK version bellow works:

C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-SOONG BUILD NUMBER PLACEHOLDER

C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.0>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-6520161

C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.1>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-6625208

C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.2>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-6739378

C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.3>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-6966805

C:\Program Files (x86)\Android\android-sdk\build-tools\31.0.0-rc1>aapt2 version
Android Asset Packaging Tool (aapt) 2.19-7145137

**Comment by jonathanpeppers** [comment]
What I would recommend is to set `<Aapt2ToolPath>` in your `.csproj` file to one that works for you. That way you don't have to save over files or anything.

Not much we can do here, can you file a bug with Google?

https://source.android.com/setup/contribute/report-bugs

I'll try to keep Xamarin.Android on the latest stable version they have on Maven. If you find a build from Maven that works, we could also bump to an RC. Sorry, hope that helps!

**Comment by jojorne** [comment]
Hi, I know this is closed but could you send me the alpha09 or alpha10?
https://mvnrepository.com/artifact/com.android.tools.build/aapt2/7.0.0-alpha09-7147631
https://mvnrepository.com/artifact/com.android.tools.build/aapt2/7.0.0-alpha10-7147631
