### ISSUE TITLE
[Bug] TimeoutException randomly occurs when call WCF contract from Android 9 or 10

### ISSUE THREAD

**Issue by nicolabracchini** [xamarin/xamarin-android#5711]
### Description

I've a strange problem in my app. When i call a webmethod from my ws (IIS 10 but always in IIS 7) randomly i receive TimeoutException. The same WS is used in an old VS 2010 application that work correctly without errors. The ws work well also if i call from browser. 
Last error occurred in this line:

_[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
WSGiac.LeggiArticoloInventarioResponse WSGiac.WService.LeggiArticoloInventario(WSGiac.LeggiArticoloInventarioRequest request)
     {
         return base.Channel._LeggiArticoloInventario_(request); // ERROR OCCURRED HERE
     }_

I've already tried to increase the Timeout Value. Unfortunately the problem still happen.
I've tried sniffing the packet sended and received to search something malformed. But everithing is ok. The strange things is that, when the error occurs, the packet is sended / received correctly. So I think that the problem is not the WCF, but the standard connector. 

I've developed the app for android device from Android 8.1. The problem occurs in device with Android 9 and 10
[stackTrace.txt](https://github.com/xamarin/Xamarin.Forms/files/6048815/stackTrace.txt)

### Steps to Reproduce

connect WCF service with Reference Provider
consume in syncronous mode some contract in Android 9 or 10 device

### Expected Behavior

Correct data retrival without TimeoutException

### Basic Information

    Version with issue: 2.0
    Last known good version: Unknown
    Platform Target Frameworks: Android: 9.0 - API 28
    Android Support Library / AndroidX Version:
    NuGet Packages:
    Affected Devices:

### Environment

Microsoft Visual Studio Community 2019 Versione 16.8.6 
FrameWork 4.8.03752
WCF Service on Windows Server with IIS 10.

**Comment by purposebuiltinc** [comment]
Hi there,

Has the issue resolved or you found any solution? I am also having exactly the same issue when calling WCF service on Android 10.

Ata

**Comment by nicolabracchini** [comment]
Hi @purposebuiltinc ,

unfortunately the issue is not resolved. I had to migrate the ws from SOAP to REST and call directly using HttpClient. In this way everithing works fine. 

Nicola

**Comment by purposebuiltinc** [comment]
Hi Nicola,

Thanks for your response.  then I will move to gRPC.

Ata

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
