### ISSUE TITLE
AndroidUseSharedRuntime is still checked for when archiving app

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-android#5719]
As confirmed [here](https://github.com/xamarin/xamarin-android/issues/5716#issuecomment-793923343), the `AndroidUseSharedRuntime` property is now obsolete. Being a minimalist, I removed it from my .csproj files. However this now prevents me to archive my apps.
`AndroidUseSharedRuntime` is also still included in the default VS Xamarin.Android project template

### Steps to Reproduce
- Select Release configuration
- Build -> Archive

### Expected Behavior
App builds + acrhives

### Actual Behavior

![image](https://user-images.githubusercontent.com/2863198/110505070-1a867500-80fe-11eb-86dc-0d266fc211c3.png)

### Version Information
VS 2019 16.9.0 Windows
Xamarin.Android 11.2.0.21

**Comment by jonathanpeppers** [comment]
@tondat could the IDE be doing something here when you go to Build -> Archive?

We don't define or use `$(AndroidUseSharedRuntime)` anymore in Xamarin.Android.

**Comment by dellis1972** [comment]
A work around would be to just define `<AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>` in the Release Configuration for now, util the archive system has been updated.

**Comment by tondat** [comment]
@jonathanpeppers yes, archive is using this property.

**Comment by dellis1972** [comment]
@tondat do you have a devdiv issue to track this problem? Is anyone working on it?

**Comment by tondat** [comment]
@dellis1972 yes, the issue was fixed. Bug 1290727

**Comment by jonathanpeppers** [comment]
I think we can close this, it should be shipping in a future 16.10 preview release.

**Comment by dellis1972** [comment]
For Reference https://github.com/xamarin/XamarinVS/pull/12101
