### ISSUE TITLE
BuildVersionCodes.R != 30

### ISSUE THREAD

**Issue by bnserig** [xamarin/xamarin-android#5723]
### Steps to Reproduce
Android.OS.BuildVersionCodes has a wrong value for R (10000 instead of 30).
Documentation for Android SDK v11 doesn't exists and v9 stops at OMr1 (27) : https://docs.microsoft.com/en-us/dotnet/api/android.os.buildversioncodes?view=xamarin-android-sdk-9.

### Expected Behavior
BuildVersionCodes.R value should be 30
### Actual Behavior
BuildVersionCodes.R value is 10000
### Version Information
<details>
Microsoft Visual Studio Community 2019
Version 16.9.1
VisualStudio.16.Release/16.9.1+31105.61
Microsoft .NET Framework
Version 4.8.04084

Version installée : Community

Visual C++ 2019   00435-60000-00000-AA899
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.688.6828
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.688.6828
Pour plus d'informations, visitez https://www.asp.net/

Assistants Microsoft Visual C++   1.0
Assistants Microsoft Visual C++

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.688.6828
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Common Azure Tools   1.10
Fournit des services courants utilisables par Microsoft Azure Mobile Services et Microsoft Azure Tools.

Cookiecutter   16.9.21026.1
Fournit des outils pour rechercher, instancier et personnaliser des modèles au format cookiecutter.

Débogage d'image mémoire de noyau Linux   1.0.9.31019
Active le débogage des images mémoire de noyau Linux.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Extension IntelliCode   1.0
Informations détaillées sur l'extension Visual Studio IntelliCode

Extensions des outils de conteneur Visual Studio   1.0
Affichez, gérez et diagnostiquez les conteneurs dans Visual Studio.

Fabric.DiagnosticEvents   1.0
Événements de diagnostic Fabric

Gestionnaire de package NuGet   5.9.0
Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, visitez https://docs.nuget.org/

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools pour Visual Studio   16.0
Microsoft Azure Service Fabric Tools pour Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools pour Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools pour Visual Studio   0.4
Simplification de la configuration des pipelines Azure DevOps à partir de l'IDE Visual Studio.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.21130.2 Commit Hash:dacc0e71a5e060cdcab466a301cacea359c1b6da
Ajoute la prise en charge du développement et du débogage d'applications Node.js dans Visual Studio

Outils Azure App Service v3.0.0   16.9.688.6828
Outils Azure App Service v3.0.0

Outils C#   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Composants C# utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Outils TypeScript   16.0.30201.2001
Outils TypeScript pour Microsoft Visual Studio

Outils Visual Basic   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Composants Visual Basic utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Package hôte de l'adaptateur de débogage de Visual Studio Code   1.0
Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio

Package Microsoft Visual Studio VC   1.0
Package Microsoft Visual Studio VC

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.9.21026.1
Fournit IntelliSense, des projets, des modèles, le débogage, des fenêtres interactives et du support pour les développeurs Python.

Python - Prise en charge Django   16.9.21026.1
Fournit des modèles et une intégration pour le framework web Django.

Python - Prise en charge du profilage   16.9.21026.1
Prise en charge du profilage pour les projets Python.

Python - Prise en charge IronPython   16.9.21026.1
Fournit des modèles et une intégration pour les projets basés sur IronPython.

Python - Prise en charge de Conda   16.9.21026.1
Prise en charge de Conda pour les projets Python.

SettingsWindow Extension   1.0
SettingsWindow Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Visual C++ pour le développement sous Linux   1.0.9.31019
Visual C++ pour le développement sous Linux

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Tools pour CMake   1.0
Visual Studio Tools pour CMake

Visual Studio Tools pour Conteneurs   1.0
Visual Studio Tools pour Conteneurs

Visual Studio Tools pour Docker   1.1
Développez, exécutez et validez vos applications ASP.NET Core dans l'environnement cible. Appuyez sur F5 pour exécuter votre application directement dans un conteneur avec débogage ou sur CTRL+F5 pour modifier et actualiser votre application sans avoir à recréer le conteneur.

Visual Studio Tools pour Kubernetes   1.0
Visual Studio Tools pour Kubernetes

VisualStudio.DeviceLog   1.0
Informations sur mon paquet

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.271 (d16-9@863670b)
Extension Visual Studio permettant de développer pour Xamarin.iOS et Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Extension Visual Studio pour activer les outils Xamarin Designer dans Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d

Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</details>

**Comment by jpobst** [comment]
Thanks for the report!  I have a PR going (#5725) that will switch the build code to 30.
