### ISSUE TITLE
Java.Lang.NoSuchMethodError: 'No static method 

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/xamarin-android#5728]
Struggling with a problem trying to resolve a method that I know EXISTS in my Android Binding Library, the static method is 
```csharp
checkNotNullFromProvides(Ljava/lang/Object;)
```

The exception I am getting is:

```csharp
Java.Lang.NoSuchMethodError: 'No static method checkNotNullFromProvides(Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app/com.companyname.test-lfDh6TdL9GaXsZgKrOqYTQ==/base.apk)'
```
Sample project below:

[NoSuchMethodError.zip](https://github.com/xamarin/xamarin-android/files/6118867/NoSuchMethodError.zip)

### Expected Behavior

The Method should be resolvable

### Actual Behavior

Full exception log here:

```csharp
csharp
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.test, PID: 13541
[AndroidRuntime] java.lang.NoSuchMethodError: No static method checkNotNullFromProvides(Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app/com.companyname.test-bdQmKIKx8inKfkzpRSr5Lw==/base.apk)
[AndroidRuntime]  at sqip.internal.HttpModule_MoshiFactory.moshi(HttpModule_MoshiFactory.java:23)
[AndroidRuntime]  at sqip.internal.HttpModule_MoshiFactory.get(HttpModule_MoshiFactory.java:15)
[AndroidRuntime]  at sqip.internal.HttpModule_MoshiFactory.get(HttpModule_MoshiFactory.java:8)
[AndroidRuntime]  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[AndroidRuntime]  at sqip.internal.HttpModule_CreateCardNonceErrorResponseAdapterFactory.get(HttpModule_CreateCardNonceErrorResponseAdapterFactory.java:24)
[AndroidRuntime]  at sqip.internal.HttpModule_CreateCardNonceErrorResponseAdapterFactory.get(HttpModule_CreateCardNonceErrorResponseAdapterFactory.java:11)
[AndroidRuntime]  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[AndroidRuntime]  at sqip.internal.nonce.RealCreateCardNonceRequestHandler_Factory.get(RealCreateCardNonceRequestHandler_Factory.java:44)
[AndroidRuntime]  at sqip.internal.nonce.RealCreateCardNonceRequestHandler_Factory.get(RealCreateCardNonceRequestHandler_Factory.java:12)
[AndroidRuntime]  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[AndroidRuntime]  at sqip.internal.nonce.ActivityControllerModule_CardEntryActivityControllerFactory.get(ActivityControllerModule_CardEntryActivityControllerFactory.java:36)
[AndroidRuntime]  at sqip.internal.nonce.ActivityControllerModule_CardEntryActivityControllerFactory.get(ActivityControllerModule_CardEntryActivityControllerFactory.java:11)
[AndroidRuntime]  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[AndroidRuntime]  at sqip.internal.nonce.DaggerCardEntryActivityComponent.cardEntryActivityController(DaggerCardEntryActivityComponent.java:160)
[AndroidRuntime]  at sqip.internal.BaseCardEntryActivity.onCreate(BaseCardEntryActivity.kt:132)
[AndroidRuntime]  at sqip.internal.CardEntryActivity.onCreate(CardEntryActivity.kt:38)
[AndroidRuntime]  at android.app.Activity.performCreate(Activity.java:7802)
[AndroidRuntime]  at android.app.Activity.performCreate(Activity.java:7791)
[AndroidRuntime]  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
[AndroidRuntime]  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
[AndroidRuntime]  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
[AndroidRuntime]  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[AndroidRuntime]  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[AndroidRuntime]  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[AndroidRuntime]  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
[AndroidRuntime]  at android.os.Handler.dispatchMessage(Handler.java:107)
[AndroidRuntime]  at android.os.Looper.loop(Looper.java:214)
[AndroidRuntime]  at android.app.ActivityThread.main(ActivityThread.java:7356)
[AndroidRuntime]  at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime]  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[AndroidRuntime]  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_call_object_method'.
[Mono] Probing 'java_interop_jnienv_call_object_method'.
[Mono] Found as 'java_interop_jnienv_call_object_method'.
[Mono] DllImport attempting to load: '/system/lib/liblog.so'.
[Mono] DllImport loaded library '/system/lib/liblog.so'.
[Mono] DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
[Mono] Searching for '__android_log_print'.
[Mono] Probing '__android_log_print'.
[Mono] Found as '__android_log_print'.
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NoSuchMethodError: No static method checkNotNullFromProvides(Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app/com.companyname.test-bdQmKIKx8inKfkzpRSr5Lw==/base.apk)
[MonoDroid]   --- End of managed Java.Lang.NoSuchMethodError stack trace ---
[MonoDroid] java.lang.NoSuchMethodError: No static method checkNotNullFromProvides(Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app/com.companyname.test-bdQmKIKx8inKfkzpRSr5Lw==/base.apk)
[MonoDroid]  at sqip.internal.HttpModule_MoshiFactory.moshi(HttpModule_MoshiFactory.java:23)
[MonoDroid]  at sqip.internal.HttpModule_MoshiFactory.get(HttpModule_MoshiFactory.java:15)
[MonoDroid]  at sqip.internal.HttpModule_MoshiFactory.get(HttpModule_MoshiFactory.java:8)
[MonoDroid]  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[MonoDroid]  at sqip.internal.HttpModule_CreateCardNonceErrorResponseAdapterFactory.get(HttpModule_CreateCardNonceErrorResponseAdapterFactory.java:24)
[MonoDroid]  at sqip.internal.HttpModule_CreateCardNonceErrorResponseAdapterFactory.get(HttpModule_CreateCardNonceErrorResponseAdapterFactory.java:11)
[MonoDroid]  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[MonoDroid]  at sqip.internal.nonce.RealCreateCardNonceRequestHandler_Factory.get(RealCreateCardNonceRequestHandler_Factory.java:44)
[MonoDroid]  at sqip.internal.nonce.RealCreateCardNonceRequestHandler_Factory.get(RealCreateCardNonceRequestHandler_Factory.java:12)
[MonoDroid]  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[MonoDroid]  at sqip.internal.nonce.ActivityControllerModule_CardEntryActivityControllerFactory.get(ActivityControllerModule_CardEntryActivityControllerFactory.java:36)
[MonoDroid]  at sqip.internal.nonce.ActivityControllerModule_CardEntryActivityControllerFactory.get(ActivityControllerModule_CardEntryActivityControllerFactory.java:11)
[MonoDroid]  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[MonoDroid]  at sqip.internal.nonce.DaggerCardEntryActivityComponent.cardEntryActivityController(DaggerCardEntryActivityComponent.java:160)
[MonoDroid]  at sqip.internal.BaseCardEntryActivity.onCreate(BaseCardEntryActivity.kt:132)
[MonoDroid]  at sqip.internal.CardEntryActivity.onCreate(CardEntryActivity.kt:38)
[MonoDroid]  at android.app.Activity.performCreate(Activity.java:7802)
[MonoDroid]  at android.app.Activity.performCreate(Activity.java:7791)
[MonoDroid]  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
[MonoDroid]  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
[MonoDroid]  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
[MonoDroid]  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[MonoDroid]  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[MonoDroid]  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[MonoDroid]  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
[MonoDroid]  at android.os.Handler.dispatchMessage(Handler.java:107)
[MonoDroid]  at android.os.Looper.loop(Looper.java:214)
[MonoDroid]  at android.app.ActivityThread.main(ActivityThread.java:7356)
[MonoDroid]  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[MonoDroid]  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[MonoDroid] 
[Process] Sending signal. PID: 13541 SIG: 9
```

Some screenshots below prove the point that the static method does exist:

Here is the generated .dll of the dagger binding library that is being references though the project

![Capture](https://user-images.githubusercontent.com/5468757/110697360-259dea00-8251-11eb-989b-b7b2d656be2d.PNG)

Here is the jar file that is being included in the jar folder for the Binding library... clearly the method exists also in the expected place:

![Capture2](https://user-images.githubusercontent.com/5468757/110697640-82010980-8251-11eb-91fd-441bdc7cede3.PNG)

**Comment by jpobst** [comment]
Your reference to the Dagger jar is:
```
<InputJar Include="Jars\dagger-2.30.1.jar" />
```

This means it will make a C# binding wrapper, but not include the `.jar` in the binding.  Try this to bind the library and include the Java code in the binding:

```
<EmbeddedJar Include="Jars\dagger-2.30.1.jar" />
```

**Comment by LeoJHarris** [comment]
@jpobst  Thanks for the quick reply :) I must have overlooked that, in any event I've updated the jar as EmbeddedJar and done the build again but got following exception:

```csharp
Xamarin.Android.D8.targets(79,5): error MSB6006: "java.exe" exited with code 1.
```

Full exception"

```csharp
1>"C:\Users\TestBinding\TestBinding\Test\Test.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->
1>(_CompileToDalvik target) -> 
1>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets(79,5): error MSB6006: "java.exe" exited with code 1.
1>
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:18.70
========== Build: 0 succeeded, 1 failed, 20 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by LeoJHarris** [comment]
@jpobst I have include the Xamarin.Google.Dagger plugin which Im pretty sure is required otherwise I get other exceptions. I think this might be to do with having the binding library for the dagger jar and the Xamarin.Google.Dagger.

**Comment by jpobst** [comment]
Is there a reason you are binding dagger yourself?  Ideally you would just add a reference to Xamarin.Google.Dagger so you would only have 1 version of dagger.  (Or if you really must bind Dagger yourself, you'll need to use the same version as `Xamarin.Google.Dagger`.)

If there are multiple things referencing *the same version* of a `.jar` then I think the build process will deduplicate them.

**Comment by LeoJHarris** [comment]
@jpobst 
I believe the reason for including both Xamarin.Google.Dagger and also the dagger jar file from the native SDK was that the dagger jar file provides a method `CheckNotNullFromProvides` that is used in the native SDK some where. I looked into the .dll using dotPeek at the Xamarin.Google.Dagger lib and that method was not there. Infact when I remove the reference to the binding library of the dagger jar I get this exception:

```csharp
Java.Lang.NoSuchMethodError: 'No static method checkNotNullFromProvides(Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app/com.companyname.test-HYB0dWfCe0IWG55vN-Gnqg==/base.apk)'
```

Now if I don't include Xamarin.Google.Dagger and use the binding library of the dagger jar then I get following exception but as you mention and others also, ideally I use the .

```csharp
Java.Lang.NoClassDefFoundError: 'Failed resolution of: Ldagger/internal/Factory;'
```

**Comment by LeoJHarris** [comment]
Hi @jpobst I've looked at the source for Xamarin.Google.Dagger and noticed the version is 2.27.0 so I also got the same jar version from maven search. I'm thinking of removing the Xamarin.Google.Dagger nuget and retrieving the 2.27.0 jar and making my binding library from that version and then in the Metadata add new node for a new method which would essentially be this method that is missing:

```csharp
public static <T> T checkNotNullFromProvides(T reference) {
    if (reference == null)
      throw new NullPointerException("Cannot return null from a non-@Nullable @Provides method"); 
    return reference;
  }
```

Either way the native SDK references a version of the dagger lib that has this method so it must be introduced some how. Would this be a valid work around?

**Comment by LeoJHarris** [comment]
@jpobst Is there any work around for this? We have been stuck on this for a days now...

**Comment by jpobst** [comment]
One possible workaround:

Use only your binding, and try to fix it to include `dagger.internal.Factory`.  I am guessing if you rebuild using a [diagnostic log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) you will see some messages about why this type is not getting included.  You might want to look at the [fixes applied](https://github.com/xamarin/XamarinComponents/tree/master/Android/GoogleDagger/source/Dagger) to `Xamarin.Google.Dagger` and see if they help you.

**Comment by LeoJHarris** [comment]
Hi @jpobst those fixes resolved the issue for dagger 👍 thanks! Ive got some other issue exceptions but they all look similar,

```csharp
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0738	'AndroidModule_ApplicationFactory' does not implement interface member 'IProvider.Get()'. 'AndroidModule_ApplicationFactory.Get()' cannot implement 'IProvider.Get()' because it does not have the matching return type of 'Object'.	NounceInternal	C:\Users\LeoJH\Downloads\TestBinding\TestBinding\NounceInternal\obj\Debug\generated\src\Sqip.Internal.AndroidModule_ApplicationFactory.cs	10	Active
```

![Untitled](https://user-images.githubusercontent.com/5468757/110867827-4f780f00-832c-11eb-8d02-f4ad2fc4533e.png)

I tried adding the the class into additions but no luck and the IProvider looks like this with simple Get()

![Capture](https://user-images.githubusercontent.com/5468757/110867921-76cedc00-832c-11eb-8dc1-72cb16aa2398.PNG)

In my additions I try to implement the interface but not sure how to handle this in the get() method, the red line goes away in the AndroidModule_ApplicationFactory however so how can I correctly implement this

![Capture](https://user-images.githubusercontent.com/5468757/110868441-7420b680-832d-11eb-9fa1-d382aec2c832.PNG)

**Comment by LeoJHarris** [comment]
@jpobst also quickly how can I add an addition for a class that is in another namespace? I have class in Sqip.Internal and another class in Sqip.Internal.Event. The additions class takes a single namespace so not sure how I can cover class in other namespace? Can I create another additions class for that namespace?

**Comment by LeoJHarris** [comment]
@jpobst Also trying to resolve visibility for an interface to public `ICreateCardNonceService` the api.xml show visibility="" so obviously its not visible but in the jar it is marked visible:

![Capture](https://user-images.githubusercontent.com/5468757/110880922-46933780-8344-11eb-8d34-287923992e37.PNG)

![Capture](https://user-images.githubusercontent.com/5468757/110881008-76dad600-8344-11eb-99e2-55a4699ec9cb.PNG)

I have added the following to the metadata.xml to make it public but still after building project it still says "The type of namespace name 'ICreateCardNonceService' does not exist..." 

```csharp
<attr path="/api/package[@name='sqip.internal.nonce']/interface[@name='CreateCardNonceService']" name="visibility">public</attr>
```

![Capture](https://user-images.githubusercontent.com/5468757/110880814-1481d580-8344-11eb-9af6-95821fcf19e1.PNG)

I've followed the docs but cannot change the visibility of this interface so how can I resolve it???

**Comment by jpobst** [comment]
When you look at `AndroidModule_ApplicationFactory.cs`, does it contain any method for `Get ()`?  If so, it likely has a covariant return type, which Java supports but C# does not.  If so, you can use the metadata `managedReturn` to change it to match the interface (`Java.Lang.Object`).  Alternatively you can have the version in your Additions call the generated version and return the result.

If it does not contain any `Get ()`, you can review the diagnostic log to try to determine why it is missing.  You can either try to fix that issue with metadata, or you can try to implement it in C# like it is implemented in Java (return the value of the `Application ()` method.

For `CreateCardNonceService`, it looks like this is a Kotlin library, so I suspect the interface is marked as `internal` in Kotlin.  You can verify this in the diagnostic log by finding a message like `Kotlin: Setting internal interface {klass.ThisClass.Name.Value} to package-private`.

I do not know why it isn't applying.  You can check the diagnostic log for a message like "This metadata matched no nodes" to see if the metadata path is incorrect.  Or you can check the diagnostic log for other reasons that the interface is not getting bound.

You can have as many separate `.cs` files as you want in a bindings project.  At the end of the day, it's just a normal C# project that does a few magic things before compiling.  😄

**Comment by LeoJHarris** [comment]
@jpobst Yes I did find a `Kotlin: Setting internal interface..`  in the interface for `CreateCardNonceService`, so this interface cannot be able to be marked public?

Regarding `AndroidModule_ApplicationFactory` there is a `Get()` and just returns `Application` see screen:

![Capture](https://user-images.githubusercontent.com/5468757/111085034-5d22d400-857a-11eb-9220-686e45bc2dbf.PNG)

The binding library has tried to resolve the `Get()` which is returning the `Android.App.Application` but `IProvicer.Get()` should also be implemented?

![Capture](https://user-images.githubusercontent.com/5468757/111085121-cefb1d80-857a-11eb-8844-418dfe843a83.PNG)

**Comment by jpobst** [comment]
Correct, the interface needs `Java.Lang.Object Get ()`, but the class is implementing `Application.Get ()`, so it doesn't count.  You will need to either do the `managedReturn` fix or the Additions fix mentioned above.

You should be able to change the Kotlin internal interface to public using metadata.  I am not sure why that isn't working, did you find any "matched no nodes" messages?

**Comment by LeoJHarris** [comment]
@jpobst I thought maybe I can remove the node with:

```csharp
<remove-node path="/api/package[@name='com.squareup.common.truststore']/class[@name='SquareSSLSocketFactory']" />
```

But then I get a no 'Java.Lang.NoClassDefFoundError:' from my understanding removing a node still allows the class to be called from other jar classes but doesn't allow me to call it in C#. So doesnt that mean I cannot call the class directly from C# which I am not but should still be callable from within my application through the binding projects?

**Comment by LeoJHarris** [comment]
@jpobst I've removed the `SquareSSLSocketFactory` class and issue has been resolved :) 

Just got one final issue to resolve now hopefully:

```csharp
[MonoDroid] Java.Lang.RuntimeException: Unable to start activity ComponentInfo{com.companyname.test/sqip.internal.CardEntryActivity}: android.view.InflateException: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Error inflating class sqip.internal.CreditCardEditor ---> Android.Views.InflateException: Binary XML f03-16 16:44:39.630 I/MonoDroid( 6152): 	at sqip.internal.CardEntryActivity.onCreate(CardEntryActivity.kt:38)
```

**Comment by jpobst** [comment]
I wonder if it's deeper than `sqip_activity_card_entry`.  You error message is cut off, but it mentions:
```
Java.Lang.NoClassDefFoundError: Failed resolution of: Lsqip/internal/R$attr;
```

If you have Android Studio installed, you should be able to drag/drop your `.apk` file onto it and explore the `classes.dex` file to see what classes are actually in your finished `.apk`.

2 potential issues that might keep it out of your apk:
- The jar file in your binding library is set to `InputJar` rather than `EmbeddedJar`.
- Proguard might be removing the Java code.

**Comment by LeoJHarris** [comment]
Hi @jpobst sorry your right some of the exception was cut off here is the whole exception :) Ill look into this further as well based on your comments, anything further in the exception telling what's going on?

```csharp
csharp
[AndroidRuntime] Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lsqip/internal/R$attr;
[AndroidRuntime] Caused by: android.view.InflateExcep03-16 18:49:23.538 E/AndroidRuntime(10815):     at sqip.internal.CreditCardEditor.<init>(CreditCardEditor.kt:108)
[AndroidRuntime]     ... 30 more
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "sqip.internal.R$attr" on path: DexPathList[[zip file "/data/app/com.companyname.test-HJ1094nZPMw0-WXEaMJQGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.test-HJ1094nZPMw0-WXEaMJQGw==/lib/x86, /data/app/com.companyname.test-HJ1094nZPMw0-WXEaMJQGw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
[AndroidRuntim03-16 18:49:23.538 E]     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
[AndroidRuntime]     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[AndroidRuntime]     ... 31 more
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_call_object_method'.
[Mono] Probing 'java_interop_jnienv_call_object_method'.
[Mono] Found as 'java_interop_jnienv_call_object_method'.
**Java.Lang.RuntimeException:** 'Unable to start activity ComponentInfo{com.companyname.test/sqip.internal.CardEntryActivity}: android.view.InflateException: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Error inflating class sqip.internal.CreditCardEditor'
[Mono] DllImport attempting to load: '/system/lib/liblog.so'.
[Mono] DllImport loaded library '/system/lib/liblog.so'.
[Mono] DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
[Mono] Searching for '__android_log_print'.
[Mono] Probing '__android_log_print'.
[Mono] Found as '__android_log_print'.
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.RuntimeException: Unable to start activity ComponentInfo{com.companyname.test/sqip.internal.CardEntryActivity}: android.view.InflateException: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Error inflating class sqip.internal.CreditCardEditor ---> Android.Views.InflateException: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Error inflating class sqip.internal.CreditCardEditor ---> Android.Views.InflateException: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Error inflating class sqip.internal.CreditCardEditor ---> Java.Lang.Reflect.InvocationTargetException: Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. ---> Java.Lang.NoClassDefFoundError: Failed resolution of: Lsqip/internal/R$attr; ---> Java.Lang.ClassNotF
[MonoDroid]    --- End of inner exception stack trace ---
[chatty] uid=10135(com.companyname.test) identical 3 lines
[MonoDroid]    --- End of inner exception stack trace ---
[MonoDroid]   --- End of managed Java.Lang.RuntimeException stack trace ---
[MonoDroid] java.lang.RuntimeException: Unable to start activity ComponentInfo{com.companyname.test/sqip.internal.CardEntryActivity}: android.view.InflateException: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Error inflating class sqip.internal.CreditCardEditor
[MonoDroid]     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
[MonoDroid]     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
[MonoDroid]     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[MonoDroid]     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[MonoDroid]     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[MonoDroid]     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
[MonoDroid]     at android.os.Handler.dispatchMessage(Handler.java:107)
[MonoDroid]     at android.os.Looper.loop(Looper.java:214)
[MonoDroid]     at android.app.ActivityThread.main(ActivityThread.java:7356)
[MonoDroid]     at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid]     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[MonoDroid]     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[MonoDroid] Caused by: android.view.InflateException: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Error inflating class sqip.internal.CreditCardEditor
[MonoDroid] Caused by: android.view.InflateException: Binary XML file line #1 in com.companyname.test:layout/sqip_activity_card_entry: Error inflating class sqip.internal.CreditCardEditor
[MonoDroid] Caused by: java.lang.reflect.InvocationTargetException
[MonoDroid]     at java.lang.reflect.Constructor.newInstance0(Native Method)
[MonoDroid]     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
[MonoDroid]     at android.view.LayoutInflater.createView(LayoutInflater.java:854)
[MonoDroid]     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
[MonoDroid]     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
[MonoDroid]     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
[MonoDroid]     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
[MonoDroid]     at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
[MonoDroid]     at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
[MonoDroid]     at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
[MonoDroid]     at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
[MonoDroid]     at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
[MonoDroid]     at sqip.internal.CardEntryActivity.doSetContentView(CardEntryActivity.kt:52)
[MonoDroid]     at sqip.internal.BaseCardEntryActivity.onCreate(BaseCardEntryActivity.kt:135)
[MonoDroid]     at sqip.internal.CardEntryActivity.onCreate(CardEntryActivity.kt:38)
[MonoDroid]     at android.app.Activity.performCreate(Activity.java:7802)
[MonoDroid]     at android.app.Activity.performCreate(Activity.java:7791)
[MonoDroid]     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
[MonoDroid]     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
[MonoDroid]     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
[MonoDroid]     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[MonoDroid]     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[MonoDroid]     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[MonoDroid]     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
[MonoDroid]     at android.os.Handler.dispatchMessage(Handler.java:107)
[MonoDroid]     at android.os.Looper.loop(Looper.java:214)
[MonoDroid]     at android.app.ActivityThread.main(ActivityThread.java:7356)
[MonoDroid]     at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid]     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[MonoDroid]     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[MonoDroid] Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lsqip/internal/R$attr;
[MonoDroid]     at sqip.internal.CreditCardEditor.<init>(CreditCardEditor.kt:108)
[MonoDroid]     ... 30 more
[MonoDroid] Caused by: java.lang.ClassNotFoundException: Didn't find class "sqip.internal.R$attr" on path: DexPathList[[zip file "/data/app/com.companyname.test-HJ1094nZPMw0-WXEaMJQGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.test-HJ1094nZPMw0-WXEaMJQGw==/lib/x86, /data/app/com.companyname.test-HJ1094nZPMw0-WXEaMJQGw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
[MonoDroid]     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
[MonoDroid]     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[MonoDroid]     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[MonoDroid]     ... 31 more
[MonoDroid] 
[Process] Sending signal. PID: 10815 SIG: 9
```

**Comment by LeoJHarris** [comment]
@jpobst I checked and the code shrinker is not enabled so there shouldn't be any proguard stripping java code. All the jars are EmbeddedJar as well and the aar files are LibraryProjectZip.

![Capture](https://user-images.githubusercontent.com/5468757/111379767-5fb33400-8708-11eb-9e9c-aea3f2766a5c.PNG)

Ill checkout the apk in android studio as you mention

**Comment by LeoJHarris** [comment]
@jpobst Hi did you get a chance to have a look into this for me? I'm nearing the point Ill need to integrate this into our application and really need this resolved. All the help is hugely appreciated 👍

**Comment by jpobst** [comment]
It would appear to have the `Lsqip/internal/R$attr` class that it is saying it cannot find.

![image](https://user-images.githubusercontent.com/179295/112162939-8666e400-8bba-11eb-825a-cc9ff972ed06.png)

Gonna hand this off to the guys who specialize in creating the APK and see if they have any clues.

@jonathanpeppers @dellis1972

**Comment by jonathanpeppers** [comment]
@LeoJHarris can you attach a `Release` .apk file? A `Debug` one we won't be able to install and test, because of the way Fast Deployment works.

Another question:

> @LeoJHarris commented:
> the aar files are LibraryProjectZip.

A limitation is you can only put a single `@(LibraryProjectZip)` file per `.csproj`. Could that be the issue? You have some `.aar` files that will not make it to the app?

**Comment by LeoJHarris** [comment]
@jpobst thanks for passing this on and the help you provided much appreciate 🥇 

> @LeoJHarris can you attach a `Release` .apk file? A `Debug` one we won't be able to install and test, because of the way Fast Deployment works.

See below, can you let me know if this works for you, I did a quick archive without using signing identify to sign the apk however 
[com.companyname.test.zip](https://github.com/xamarin/xamarin-android/files/6192954/com.companyname.test.zip)

You will also find the attached sample project I have been working with below everything is in there to check if need be

> A limitation is you can only put a single `@(LibraryProjectZip)` file per `.csproj`. Could that be the issue? You have some `.aar` files that will not make it to the app?

[TestBinding (2).zip](https://github.com/xamarin/xamarin-android/files/6192886/TestBinding.2.zip)

**Comment by jonathanpeppers** [comment]
@LeoJHarris I was able to build & run your project, after making this change in `InAppPay.csproj` to fix the NuGet restore:

```diff
--<AssemblyName>NounceInternal</AssemblyName>
++<AssemblyName>InAppPayLib</AssemblyName>
```

![image](https://user-images.githubusercontent.com/840039/112327358-5c2d2900-8c83-11eb-8ea4-e2d4f4778648.png)

(my emulator happened to be in Spanish)

I tried both Debug & Release, and it worked. Do I need to do something to cause the crash?

**Comment by LeoJHarris** [comment]
@jonathanpeppers I think that's resolved the problem 🥇 I think I'd been looking at this problem for way to long to spot that issue... I had changed some of the assembly names earlier as there was a previous bug in visual studio where the create binding library project was missing so I copied and pasted other binding library projects and might have forgot to rename the assembly... in any event yay binding works thanks heaps!

**Comment by LeoJHarris** [comment]
@jonathanpeppers @jpobst  I'm going to close this issue now as the binding is working :) thanks guys
