### ISSUE TITLE
Cannot localize app anymore in Xam.Android 11.2 - System.Resources.ResourceManager.GetString ignores the CultureInfo

### ISSUE THREAD

**Issue by inimirpaz** [xamarin/xamarin-android#5735]
### Description

Since updating from Xamarin.Android 11.1 to 11.2, we are not able to display localized strings anymore: they always default to the base language .resx file. (we are using a localization approach similar to this project https://github.com/hot33331/ResxI18N ). So, basically, (see https://github.com/hot33331/ResxI18N/blob/master/ResxI18N/Helpers/TranslateExtension.cs ) no matter what CultureInfo you pass in `var translation = ResMgr.Value.GetString(Text, ci);`, it will always retrieve the default resx string.

More specifically I have found that:
```
VERSION					DEBUG			RELEASE

xamarin.android-11.2.0.21		Working			NOT Working
xamarin.android-11.2.0.0		NOT Working		NOT Working
xamarin.android-11.1.0.26		Working			Working
```
For some reason when deploying the app (both in the simulator and in real devices) in debug mode with 11.2 it does not work, while doing that with 11.2.0.21 it works, yet it still does not work in release mode, and that is critical!

### Version Information

Visual Studio Community 2019 for Mac
Version 8.9.1 (build 34)

<details>

```
Installation UUID: 3047ce14-1f52-4878-b6c4-5b4461104fb0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

Mono Framework MDK
Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

Roslyn (Language Service)
3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

NuGet
Version: 5.8.0.6860

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/6.0.100-preview.1.21103.13/Sdks
SDK Versions:
	6.0.100-preview.1.21103.13
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-preview.1.21102.12
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12

.NET Core 3.1 SDK
SDK: 3.1.407

Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 11.2.0.21 (Visual Studio Community)
Commit: xamarin-android/d16-9/93eab59
Android SDK: /Users/mpazzaglia/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.0
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@d6d86b2
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d

Microsoft OpenJDK for Mobile
Java SDK: /Users/mpazzaglia/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:14:56 UTC

Android Device Manager
Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:15:18 UTC

Xamarin Designer
Version: 16.9.0.316
Hash: bd2705417
Branch: remotes/origin/d16-9
Build date: 2021-02-24 00:16:08 UTC

Apple Developer Tools
Xcode 12.4 (17801)
Build 12D4e

Xamarin.Mac
Version: 7.8.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

Xamarin.iOS
Version: 14.14.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

Build Information
Release ID: 809010034
Git revision: 33bce2b7f3d45d05865cd3282f1c2cdc3a112aa0
Build date: 2021-03-04 11:21:38-05
Build branch: release-8.9
Xamarin extensions: 33bce2b7f3d45d05865cd3282f1c2cdc3a112aa0

Operating System
Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
AddinMaker 1.6.0

```
</details>

### Workaround

Roll back to http://dl.xamarin.com/MonoforAndroid/Mac/xamarin.android-11.1.0.26.pkg

**Comment by jpobst** [comment]
My guess is this is somehow related to files getting packaged incorrectly in the apk.  Assigning as a build issue.

In the meantime, you might want to try running `apkdiff` on a good version versus a bad version and see what the differences are.  Those logs would probably help investigate this issue as well.

Details are here:
https://github.com/radekdoulik/apkdiff

**Comment by jonathanpeppers** [comment]
@inimirpaz does it work differently comparing `Debug` vs `Release` builds?

If the problem is `Debug`-only, does the problem go away if you add `<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>` into your `.csproj` file?

**Comment by inimirpaz** [comment]
> @inimirpaz does it work differently comparing `Debug` vs `Release` builds?
> 
> If the problem is `Debug`-only, does the problem go away if you add `<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>` into your `.csproj` file?

With version 11.2.0.21 (latest stable) if you run in `Debug` everything works as expected, if you run in `Release` it does not work (string defaults to main resx).
With version 11.2.0.0 it does not work as expected in either cases.
With version 11.1.0.26 everything works fine both in `Debug` and in `Release`.

So the problem is not `Debug`-only, it presists in `Release` in both 11.2 versions.

**Comment by inimirpaz** [comment]
> My guess is this is somehow related to files getting packaged incorrectly in the apk. Assigning as a build issue.
> 
> In the meantime, you might want to try running `apkdiff` on a good apk versus a bad apk and see what the differences are. Those logs would probably help investigate this issue as well.
> 
> Details are here:
> https://github.com/radekdoulik/apkdiff
<details>

```
apkdiff notworkingapks/universal.apk workingapks/universal.apk 
Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
  +      15.509 assemblies/mk/TestApp.resources.dll
  +      10.610 assemblies/hu/TestApp.resources.dll
  +      10.607 assemblies/fr/TestApp.resources.dll
  +      10.460 assemblies/pt/TestApp.resources.dll
  +      10.398 assemblies/es/TestApp.resources.dll
  +      10.063 assemblies/it/TestApp.resources.dll
  +       9.862 assemblies/fi/TestApp.resources.dll
  +       9.720 assemblies/nl/TestApp.resources.dll
  +       9.703 assemblies/hr/TestApp.resources.dll
  +       9.689 assemblies/no/TestApp.resources.dll
  +       9.651 assemblies/sr/TestApp.resources.dll
  +       9.573 assemblies/sl/TestApp.resources.dll
  +       9.563 assemblies/cs/TestApp.resources.dll
  +       9.387 assemblies/da/TestApp.resources.dll
  +       4.096 lib/armeabi-v7a/libaot-Microsoft.AppCenter.Android.Bindings.dll.so
  +       4.096 lib/armeabi-v7a/libaot-Xamarin.Forms.Platform.Android.dll.so
  +       4.096 lib/armeabi-v7a/libaot-Xamarin.Google.Android.Material.dll.so
  +       4.096 lib/x86/libaot-Xamarin.Forms.Platform.Android.dll.so
  +       4.096 lib/x86/libaot-Xamarin.GooglePlayServices.Maps.dll.so
  +       4.096 lib/x86_64/libaot-Xamarin.Google.Android.DataTransport.TransportRuntime.dll.so
  +       4.064 classes.dex
    +           3 strings count
    +           1 fields count
    -           2 methods count
    +       4.060 data section size
  +       3.168 lib/arm64-v8a/libaot-Xamarin.GooglePlayServices.Maps.dll.so
  +       3.064 lib/arm64-v8a/libaot-Xamarin.Google.Android.Material.dll.so
  +       2.224 lib/arm64-v8a/libaot-Xamarin.GooglePlayServices.Tasks.dll.so
  +       1.512 lib/arm64-v8a/libaot-FormsViewGroup.dll.so
  +         875 assemblies/System.dll
    +             Type System.ComponentModel.CategoryAttribute
  +         592 lib/arm64-v8a/libaot-Mono.Android.dll.so
  +         568 lib/arm64-v8a/libaot-Xamarin.Forms.Platform.Android.dll.so
  +         280 lib/x86_64/libaot-Mono.Android.dll.so
  +         272 lib/armeabi-v7a/libaot-Mono.Android.dll.so
  +         264 lib/x86/libaot-Mono.Android.dll.so
  +         184 lib/arm64-v8a/libaot-Xamarin.Google.Dagger.dll.so
  +         176 lib/arm64-v8a/libaot-Xamarin.AndroidX.AppCompat.dll.so
  +         128 lib/arm64-v8a/libaot-System.dll.so
  +          64 lib/arm64-v8a/libaot-Xamarin.AndroidX.Fragment.dll.so
  +          56 lib/arm64-v8a/libaot-Xamarin.Forms.Material.dll.so
  +          40 lib/arm64-v8a/libaot-SkiaSharp.Views.Android.dll.so
  +          24 lib/arm64-v8a/libaot-Plugin.Media.dll.so
  +          24 lib/arm64-v8a/libaot-Xamarin.AndroidX.Loader.dll.so
  +          24 lib/arm64-v8a/libaot-Xamarin.AndroidX.RecyclerView.dll.so
  +          16 lib/arm64-v8a/libaot-Xamarin.AndroidX.SavedState.dll.so
  +          16 lib/arm64-v8a/libaot-Xamarin.AndroidX.SwipeRefreshLayout.dll.so
  +          16 lib/arm64-v8a/libaot-Xamarin.AndroidX.VersionedParcelable.dll.so
  +           8 lib/arm64-v8a/libaot-Xamarin.AndroidX.CustomView.dll.so
  +           4 AndroidManifest.xml
  +           2 res/drawable/splash_white.png
  +           1 assemblies/Mono.Security.dll
  +           1 assemblies/Xamarin.AndroidX.Arch.Core.Common.dll
  +           1 assemblies/Xamarin.AndroidX.CustomView.dll
  +           1 assemblies/Xamarin.AndroidX.Legacy.Support.Core.Utils.dll
  -           1 assemblies/TestApp.Android.dll
  -           1 assemblies/System.IO.Compression.FileSystem.dll
  -           1 assemblies/Xamarin.AndroidX.Browser.dll
  -           1 assemblies/Xamarin.AndroidX.SavedState.dll
  -           1 assemblies/Xamarin.Firebase.Components.dll
  -           1 assemblies/Xamarin.Firebase.Iid.dll
  -           3 res/mipmap-mdpi-v4/splash_white.png
  -           3 res/mipmap-xhdpi-v4/splash_white.png
  -           4 lib/x86/libxamarin-app.so
  -          24 lib/arm64-v8a/libaot-Xamarin.AndroidX.Core.dll.so
  -          24 lib/arm64-v8a/libaot-Xamarin.AndroidX.DrawerLayout.dll.so
  -          24 lib/arm64-v8a/libaot-Xamarin.AndroidX.ViewPager.dll.so
  -          24 lib/arm64-v8a/libaot-Xamarin.Google.Android.DataTransport.TransportBackendCct.dll.so
  -          48 lib/armeabi-v7a/libaot-Java.Interop.dll.so
  -          48 lib/x86/libaot-Java.Interop.dll.so
  -          56 lib/x86_64/libaot-Java.Interop.dll.so
  -          67 assemblies/Xamarin.GooglePlayServices.Base.dll
  -          74 assemblies/Xamarin.Android.Tooltips.dll
  -          81 assemblies/Java.Interop.dll
  -         102 assemblies/Microsoft.AppCenter.Crashes.Android.Bindings.dll
  -         111 assemblies/Microsoft.AppCenter.Analytics.Android.Bindings.dll
  -         201 assemblies/Microsoft.AppCenter.Android.Bindings.dll
  -         212 assemblies/Xamarin.GooglePlayServices.Maps.dll
  -         392 lib/arm64-v8a/libaot-Java.Interop.dll.so
  -         492 assemblies/mscorlib.dll
    Type System.String
      -             Method public static string Concat (System.Collections.Generic.IEnumerable`1<!!T>)
    -             Type System.Runtime.InteropServices.DllImportSearchPath
    -             Type System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute
  -         764 lib/x86/libaot-mscorlib.dll.so
  -         772 lib/armeabi-v7a/libaot-mscorlib.dll.so
  -         816 lib/x86_64/libaot-mscorlib.dll.so
  -       1.172 lib/armeabi-v7a/libxamarin-app.so
  -       1.752 lib/arm64-v8a/libxamarin-app.so
  -       4.096 lib/armeabi-v7a/libxa-internal-api.so
  -       4.848 lib/arm64-v8a/libaot-mscorlib.dll.so
  -      15.443 assemblies/Mono.Android.dll
    -             Type System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes
    -             Type System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute
    Type Android.Content.Intent
      +             Field static System.Delegate cb_clone
      +             Method static System.Delegate GetCloneHandler ()
      +             Method static IntPtr n_Clone (IntPtr, IntPtr)
      +             Method public Java.Lang.Object Clone ()
    Type Android.Runtime.AndroidEnvironment
      +             Method static System.Collections.Generic.IEnumerable`1<System.EventHandler`1<Android.Runtime.RaiseThrowableEventArgs>> GetUnhandledExceptionRaiserInvocationList ()
    Type Android.Runtime.AndroidTypeManager
      -             Method System.Collections.Generic.IEnumerable`1<System.Type> <>n__0 (string)
      -             Type <GetTypesForSimpleReference>d__2
      +             Type <>c__DisplayClass11_0
    Type Android.Runtime.ConstructorBuilder
      -             Field static readonly System.Reflection.MethodInfo newobject
      +             Field static System.Reflection.MethodInfo newobject
      +             Method public void .ctor ()
    Type Android.Runtime.JavaObject
      +             Method Java.Lang.Object Clone ()
    Type Java.Text.DecimalFormatSymbols
      +             Field static System.Delegate cb_clone
      +             Method static System.Delegate GetCloneHandler ()
      +             Method static IntPtr n_Clone (IntPtr, IntPtr)
      +             Method public Java.Lang.Object Clone ()
    Type Java.Text._Format
      +             Field static System.Delegate cb_clone
      +             Method static System.Delegate GetCloneHandler ()
      +             Method static IntPtr n_Clone (IntPtr, IntPtr)
      +             Method public Java.Lang.Object Clone ()
    Type Java.Util.ArrayList
      +             Field static System.Delegate cb_clone
      +             Method static System.Delegate GetCloneHandler ()
      +             Method static IntPtr n_Clone (IntPtr, IntPtr)
      +             Method public Java.Lang.Object Clone ()
    Type Java.Util.Date
      +             Field static System.Delegate cb_clone
      +             Method static System.Delegate GetCloneHandler ()
      +             Method static IntPtr n_Clone (IntPtr, IntPtr)
      +             Method public Java.Lang.Object Clone ()
    Type Java.Util.HashMap
      +             Field static System.Delegate cb_clone
      +             Method static System.Delegate GetCloneHandler ()
      +             Method static IntPtr n_Clone (IntPtr, IntPtr)
      +             Method public Java.Lang.Object Clone ()
    Type Java.Lang.Object
      +             Field static System.Delegate cb_clone
      +             Method static System.Delegate GetCloneHandler ()
      +             Method static IntPtr n_Clone (IntPtr, IntPtr)
      +             Method Java.Lang.Object Clone ()
    Type Java.Lang.Enum
      +             Method Java.Lang.Object Clone ()
  -      17.776 lib/armeabi-v7a/libmonodroid.so
  -      19.984 lib/x86/libmonodroid.so
  -      20.488 lib/x86_64/libxamarin-app.so
  -      25.592 lib/arm64-v8a/libmonodroid.so
  -      32.504 lib/x86_64/libmonodroid.so
Summary:
  +           0 Other entries 0,00% (of 2.825.012)
  +     128.885 Assemblies 1,38% (of 9.350.076)
  +       4.064 Dalvik executables 0,07% (of 5.782.776)
  -      93.912 Shared libraries -0,09% (of 100.277.276)
  -      47.104 Uncompressed assemblies -0,22% (of 21.804.232)
  +      98.304 Package size difference 0,20% (of 48.392.832)
```

</details>

**Comment by jonathanpeppers** [comment]
@inimirpaz I'll take a closer look next week. Does it work for a Release build if you turn off AOT?

**Comment by inimirpaz** [comment]
> @inimirpaz I'll take a closer look next week. Does it work for a Release build if you turn off AOT?

I added `<AotAssemblies>False</AotAssemblies>` and removed `<AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>` to the release build configuration, but still no luck.

**Comment by jonathanpeppers** [comment]
I tested this sample app, and Debug & Release builds are working for me:

https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/usingresxlocalization/

Can you do a build command-line, such as:

```
msbuild YourApp.csproj -t:Clean,SignAndroidPackage -p:Configuration=Release -bl
```

This should Clean then build a Release `.apk` file. There will be a `msbuild.binlog` file as a build log, can you share that with us? Thanks!

**Comment by inimirpaz** [comment]
> I tested this sample app, and Debug & Release builds are working for me:
> 
> https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/usingresxlocalization/
> 
> Can you do a build command-line, such as:
> 
> ```
> msbuild YourApp.csproj -t:Clean,SignAndroidPackage -p:Configuration=Release -bl
> ```
> 
> This should Clean then build a Release `.apk` file. There will be a `msbuild.binlog` file as a build log, can you share that with us? Thanks!

I tried building that project and it works for me too... (Debug & Release).

Here are the msbuilds: https://drive.google.com/file/d/1zU-81EktlwN35uPkUfMf8hRgCBEJdKOM/view?usp=sharing

**Comment by jonathanpeppers** [comment]
@inimirpaz if you add this to your `.csproj` does it work around the issue?

```
<AndroidEnableAssemblyCompression>false</AndroidEnableAssemblyCompression>
```

**Comment by inimirpaz** [comment]
> @inimirpaz if you add this to your `.csproj` does it work around the issue?
> 
> ```
> <AndroidEnableAssemblyCompression>false</AndroidEnableAssemblyCompression>
> ```

@jonathanpeppers yes! It works (around).
I've just installed the latest stable update `Version: 11.2.2.1` and the issue persists. (still work-aroundable with AndroidEnableAssemblyCompression to false).
By the way, what does that option do? Bigger filesize? Do you think the issue can be definitely solved in future updates?

**Comment by dellis1972** [comment]
`AndroidEnableAssemblyCompression` when enabled will L4Z compress the assemblies before they are added to the apk. We then decompress them at odd time. So when enabled it will reduce the apk size, start up time impact is minimal because L4Z has a very fast decompressor. Disabling this setting will result in a larger apk.

**Comment by inimirpaz** [comment]
> `AndroidEnableAssemblyCompression` when enabled will L4Z compress the assemblies before they are added to the apk. We then decompress them at odd time. So when enabled it will reduce the apk size, start up time impact is minimal because L4Z has a very fast decompressor. Disabling this setting will result in a larger apk.

Ok, thanks!
@jonathanpeppers do you need anything else to investigate this issue any further?
It is wierd that in a new simple project this issue is not present at all... What could be possibly wrong with my specific solution that results in this behavior?

**Comment by jonathanpeppers** [comment]
@inimirpaz I was having trouble reproducing it, but I'll keep trying.

If you can get it to happen in a small project that you can share, let me know, thanks!

**Comment by inimirpaz** [comment]
> @inimirpaz I was having trouble reproducing it, but I'll keep trying.
> 
> If you can get it to happen in a small project that you can share, let me know, thanks!

I succeeded in isolating the "bug" in the smallest project possible:
https://drive.google.com/file/d/1NdszQ4NSaC6oLjqRp96Aacld1PdhuPhp/view?usp=sharing
Changing the picker value in `Debug`, changes the language displayed. Also when closing and opening the app again it should be displayed in the previously selected language.
In `Release` it completely ignores the picked language.

**Comment by dellis1972** [comment]
@inimirpaz you seem have a custom task at the bottom of your csproj? is that on purpose?

```
<Target Name="_ResolveSatellitePaths" DependsOnTargets="_ResolveAssemblies">
 <ResolveAssemblyReference AllowedAssemblyExtensions="$(AllowedReferenceAssemblyFileExtensions)" AssemblyFiles="@(ResolvedUserAssemblies)" AutoUnify="$(AutoUnifyAssemblyReferences)" FindDependencies="True" FindRelatedFiles="False" FindSatellites="True" SearchPaths="$(AssemblySearchPaths)" TargetFrameworkMoniker="$(TargetFrameworkMoniker)" TargetFrameworkMonikerDisplayName="$(TargetFrameworkMonikerDisplayName)" TargetFrameworkDirectories="$(TargetFrameworkDirectory)">
 <Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths" />
 </ResolveAssemblyReference>
 </Target>
```

This is completely overriding our own internal `_ResolveSatellitePaths` target. So I'm guessing that is why we could not replicate the issue.

**Comment by inimirpaz** [comment]
@dellis1972 
Good point!
Yes it is intentionally there (even though completely forgotten about that)

https://github.com/xamarin/Xamarin.Forms/issues/10821#issuecomment-634231164

I guess I could try to remove that...

**Comment by inimirpaz** [comment]
Yes, removing that task does seem to solve my issue.
I am not closing this issue though, because I don't know if this is symptomatic of something more involved on your end. Feel free to close it otherwise.

**Comment by jonathanpeppers** [comment]
The target above is a workaround for an old bug: https://github.com/xamarin/xamarin-android/issues/4805#issuecomment-642919727

You can remove it now, I think this was the issue, thanks!

**Comment by inimirpaz** [comment]
@jonathanpeppers @dellis1972 thank you!

I am still not convinced by the "working/not working" table here (when that task is in the csproj)
```
VERSION					DEBUG			RELEASE

xamarin.android-11.2.2.1		Working			NOT Working
xamarin.android-11.2.0.21		Working			NOT Working
xamarin.android-11.2.0.0		NOT Working		NOT Working
xamarin.android-11.1.0.26		Working			Working
```
but if this completely normal given that task, then it's ok. Thanks again.

**Comment by jonathanpeppers** [comment]
In Xamarin.Android 11.2, a new `%(DestinationSubPath)` metadata was added to support .NET 6.

If your target replaces ours, and doesn't set this metadata, it would break these assemblies that are in a subfolder.

**Comment by inimirpaz** [comment]
Ok, it makes sense! Thanks!

**Comment by DragonTM** [comment]
We faced the same issue. We removed the mentioned workaround from the csproj file.
But the issue still there. We are using a command line to build the app. It looks like this
`msbuild $AndroidXamarinProjPath -t:UpdateAndroidResources -t:SignAndroidPackage -p:OutputPath=$OutputFolder/ -p:Configuration=Release -p:AndroidKeyStore=true -p:AndroidSigningKeyAlias=Alias -p:AndroidSigningKeyPass=pass -p:AndroidSigningKeyStore=$KeystoreFileNamePath -p:AndroidSigningStorePass=pass `

Could the build script cause the issue?

**Comment by Kapusch** [comment]
Given my current configuration :
- VS For Mac 8.9.6 (build 6)
- Xamarin.Android 11.2.2.1

I have tried from VS to deploy a release of this [public repo](https://github.com/CrossGeeks/MasteringMultilingualSample) on my Android device, and the culture was incorrectly detected (or resx files were striped out ?).

However, as soon as I have tried to deploy via command line, it worked like a charm on my physical device.

Here is the command which has worked for the repo if you want to reproduce the bug :
`msbuild /t:Install`

**Comment by Kapusch** [comment]
Of course it did work because I was not targetting the release configuration...
It still does not work for me, no matter if I build&deploy my app through VS or with following command-line :
`msbuild /t:Install /p:Configuration=Release `

I have investigated into the build logs for DEBUG / RELEASE, but no explicit difference.

However, with the example repository shared by @jonathanpeppers , the culture works fine in Release mode !

I'll try to dive into the .csproj of this repo to get a chance to fix my issue.

**Comment by jonathanpeppers** [comment]
@Kapusch can you file a new issue? If you can reproduce the problem command-line add a `-bl` and attach the `msbuild.binlog` file it creates, thanks!

**Comment by Kapusch** [comment]
Actually, no need to create an issue !
Removing the "custom task" at the end of my .csproj actually worked.

Indeed, the first time I have tried to remove it yesterday, this somehow did not update the project properties... But after having closed/reopened Visual Studio, and deploying again in release mode (without the custom task), this finally worked :)
