### ISSUE TITLE
Android Emulator no longer lunches after upgrading to Windows 20H2 

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-android#5742]
### Steps to Reproduce

1. I have upgraded to the latest version of windows 20H2
2. Launch visual studio 2019 (latest)
3. Launch android app and get   (any suggestions!! I am stuck now)

![image](https://user-images.githubusercontent.com/16970109/111140414-35cc0700-857a-11eb-9ee4-cca6cd546e99.png)

**Comment by jpobst** [comment]
The Android emulator is a component from Google that ships with the Android SDK, so we don't have much expertise there.

Did you try the troubleshooting instructions in the error message?

You might also want to search for your error message and see if there are other troubleshooting tips:

- https://stackoverflow.com/questions/30686324/error-while-running-android-application-could-not-initialize-opengles-emulatio
- https://stackoverflow.com/questions/30877544/emulator-error-could-not-initialize-opengles-emulation-use-gpu-off-to-disa/31769200

**Comment by developer9969** [comment]
@jpobst  thanks for your reply. I will look at various options on my side then.
