### ISSUE TITLE
[Linux]  Xamarin.Android.Aapt2.targets(123, 3): [APT2144] invalid file path .../obj/Debug/res/resource.designer.cs

### ISSUE THREAD

**Issue by brud** [xamarin/xamarin-android#5743]
### Steps to reproduce
1. Build locally xamarin-android on **main** branch
2. `sudo cp -r bin/Debug/lib/xamarin.android/* /usr/lib/mono`
3. `sudo cp -r bin/Debug/bin/* /usr/lib/mono/xamarin-android/bin/`
4. Create xamarin app from template
5. Try to build

### Expected behavior
App builds correctly

### Given behavior
Get an error:
`/usr/lib/mono/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(123,3): Error APT2144 : invalid file path '/home/anton/RiderProjects/App1/App1/App1.Android/obj/Debug/res/resource.designer.cs'.`

File `resource.designer.cs` exists asd path is correct.

### System info
Kubuntu 20.10 (with last updates)
Kernel 5.8.0-45-generic
Intel Core i5-3230M
dotnet 5.0.201
mono 6.12.0.122
msbuild 15.0
Xamarin.Forms 5.0.0.2012

**Comment by dellis1972** [comment]
@brud 

Out of interest do you get the same issue when you build the template app from the terminal using `xabuild` ?
FYI `xabuild` is a tool we have that is part of the Xamarin.Android repo, you can find it in `bin/Debug/bin/xabuild`. 
If you use that you don't need to copy the files into the system locations. 

```
xabuild MyApp.csproj /restore /t:SignAndroidPackage /v:diag
```

**Comment by brud** [comment]
@dellis1972 

Thanks for quick response. I'm trying `xabuild` but get the same error.

**Comment by dellis1972** [comment]
@brud 

can you post the full diagnostic build output please? It should help us track down the issue.

```
xabuild MyApp.csproj /restore /t:SignAndroidPackage /v:diag /bl
```

That should produce a `msbuild.binlog` which you can zip up and attach to this issue.

**Comment by brud** [comment]
@dellis1972 

Sure, both files in archive
[output_and_binlog.zip](https://github.com/xamarin/xamarin-android/files/6144709/output_and_binlog.zip)

**Comment by brud** [comment]
@dellis1972 I just realized that almost all messages are in Russian, but I don't know how to switch it to English

**Comment by dellis1972** [comment]
@brud 

What did you use to generate this project? I ask because it seems the csproj has the `Resources/resource.designer.cs` file in the `AndroidResource` ItemGroup. Which it definitely shouldn't be. Its C# code, aapt2 has no way to knowing what to do with it. 
Generally the `Resources/Resource.designer.cs` file should only be in the `Compile` group. 

Can you post the csproj so we can take a look?

**Comment by dellis1972** [comment]
@brud 

I managed to get the csproj from the binlog.  This is the offending line in the csproj.

<img width="429" alt="Screenshot 2021-03-16 at 09 18 23" src="https://user-images.githubusercontent.com/810617/111284982-9588e780-8638-11eb-9ac0-6bff2ff1543d.png">

If you remove that the project should compile without any issue.

**Comment by dellis1972** [comment]
for reference, anything with the `AndroidResource` Build action will be passed to `aapt2` for resource compilation and packaging. The fact that the Generator and SubType are there suggests an IDE added this line.

**Comment by brud** [comment]
It seems this is my mistake - I was trying to solve this error:
```
App1/App1/App1.Android/App1.Android.csproj" (целевой объект SignAndroidPackage ) (1:7) ->
(Целевой объект CoreCompile) -> 
  CSC : error CS2001: Source file '/home/anton/RiderProjects/App1/App1/App1.Android/Resources/Resource.Designer.cs' could not be found. [/home/anton/RiderProjects/App1/App1/App1.Android/App1.Android.csproj]
```
now I remove this lines:
```
<AndroidResource Include="Resources\resource.designer.cs">
    <SubType>Designer</SubType>
    <Generator>MSBuild:UpdateGeneratedFiles</Generator>
</AndroidResource>
```
and error appears again.

**Comment by dellis1972** [comment]
Looks like there is a mismatch in the casing between the value for `Compile` and the source file on disk. 
The `AndroidResgenFile` is set to `Resource.designer.cs`, but the `Compile` value is set to `Resource.Designer.cs` .
I suspect the file on disk is `Resource.designer.cs`. So the fix would be to update the `Compile` element to match the casing of the file on disk. 

Can I ask what did you use to create the template? It looks like an error in the template that we need to fix for case sensitive systems.

**Comment by brud** [comment]
I use JB Rider which, as I can see, use MS templates.
Thanks for your time :)

I have two more questions:
1. For my project I am using Refit v6 and need msbuild 16.8.0 or newer - I found a way to install 16.8, but didn't understand, how to tell xabuild to use new version (if it possible at all)
2. I have installed macos in docker but did not find the xamarin.ios project that should connect to macos - does it exist?

**Comment by dellis1972** [comment]
Thanks for letting us know, I think we can close this issue now? I've checked out current templates and they all seem to contain the correct casing. So I suspect rider might be installing some older templates maybe..

I'm not 100% about how this stuff works on linux as its currently unsupported. However with regards to msbuild , xabuild should in theory just pick up the default `msbuild` on the system. So if the 16.8 install is the default mono installation then it should just work. 

As far as I know xamarin.ios -> Mac connectivity only works on windows->Mac. I don't think anyone has ever tested it on a Linux box connected to macOS in a docker.

**Comment by brud** [comment]
Ok, not all at once, you can close this.
