### ISSUE TITLE
No Builds for new Xamarin Android in Azure for (commit id: 877f572) 

### ISSUE THREAD

**Issue by Akademiksdc** [xamarin/xamarin-android#5758]
Dear colleagues (@pjcollins and @jpobst), we are looking for the new stable release 11.2.2.1 (d16-9/877f572) for **Ubuntu**, could you please run the build  in Azure pipelines for it? 

_**As well there are no new updates on the main page about latest release, the last TAG-  only Release from November.**_

<img width="886" alt="Screen Shot 2021-03-19 at 11 33 40 AM" src="https://user-images.githubusercontent.com/4567847/111752833-3977ca80-88a7-11eb-9220-073f0a6da630.png">

 _But there are a lot of fresh versions:_ 
 
 <img width="570" alt="Screen Shot 2021-03-19 at 11 34 52 AM" src="https://user-images.githubusercontent.com/4567847/111752844-3c72bb00-88a7-11eb-8eed-5102582e382a.png">

And on the Downloads tabs the last one only Previews ... 

<img width="334" alt="Screen Shot 2021-03-19 at 11 33 31 AM" src="https://user-images.githubusercontent.com/4567847/111752846-3c72bb00-88a7-11eb-95f3-d37f62a4f127.png">

**Comment by Akademiksdc** [comment]
@pjcollins  could you please help?

**Comment by Akademiksdc** [comment]
@pjcollins and @jpobst  please assist there

**Comment by pjcollins** [comment]
@Akademiksdc sorry for the delay, I'll try to look at this this week.

**Comment by pjcollins** [comment]
This build https://dev.azure.com/xamarin/public/_build/results?buildId=37684&view=results should hopefully produce linux artifacts for our latest d16-9 commit.

I still need to look into why our webhooks stopped working here last month.

**Comment by pjcollins** [comment]
We've attempted to fix the webhooks a couple of times, I think they should be working now.
