### ISSUE TITLE
Dll size ballooned

### ISSUE THREAD

**Issue by MardyGit** [xamarin/xamarin-android#5776]
MacOs 10.16.0; Visual Studio 8.9.2 (build 13); Xamarin.Android 11.2.2; targeting Android 11.0 (R). 

I have a core library I share for Android, iOS and MacOs; shared projects inside platform specific projects. No changes have been made since the last build of Feb 5th.  On rebuild, the Android DLL has ballooned in size from 128KB to 13.4MB. The iOS and MacOs dlls are exactly the same size as before. This is true for release and debug builds. I have the latest stable everything.

**Comment by jpobst** [comment]
If the file is the same size for both Debug and Release builds, then it sounds like Linking somehow got disabled.

I would suggest checking the Linker settings to make sure it is set to link your library:
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker

**Comment by MardyGit** [comment]
It's a DLL, I don't get link options. Also the project is unchanged since the last build.

**Comment by jpobst** [comment]
The link settings will be taken from your Android application project.  It will apply those settings to every `.dll` your application uses.

**Comment by MardyGit** [comment]
It's a standalone library project. Shared by several apps. It gets dropped into the app projects manually. I'm refering to the size of the dlls as built in the library project.

**Comment by jpobst** [comment]
I'm not aware of anything that would cause this.  I would suggest comparing the API of the previous small build to the current large build using a decompiler or similar tool to try to determine what is different between the two.

**Comment by MardyGit** [comment]
I'll try that

**Comment by MardyGit** [comment]
I've found the difference. The new dll has __AndroidNativeLibraries__.zip embedded, this is 13.3MB.

**Comment by jpobst** [comment]
Is this expected? Presumably you are using some native libraries and they will need to be included in the application?

**Comment by MardyGit** [comment]
But the only thing that has changed since the last build is Xamarin.Android. No code or package changes at all.

**Comment by jpobst** [comment]
@jonathanpeppers Are you aware of any changes in 16.9 that would cause packaged native library sizes to increase?

**Comment by jonathanpeppers** [comment]
`__AndroidNativeLibraries__.zip` should get removed by the linker. @MardyGit are you seeing these large `.dll` sizes in a Release build of an app?

If your native libraries are that large, I don't see how any version of Xamarin.Android would keep the 13.3MB of native libraries from taking up space. Are you sure the native libraries didn't change? Maybe they aren't stripped and they used to be?

**Comment by MardyGit** [comment]
TBH, I've never checked what's in the dlls before. Not normally my problem. I'll dig around tomorrow. It's late here. Thanks.

**Comment by MardyGit** [comment]
I've checked everything in git, locally and in DevOps. My local repo is unchanged from the last commit on the 13th. That was for a MacOS only feature. The Android and iOS builds I'm comparing the current build too were built against a commit from Feb 5th, on that day. So AFAIK nothing of mine has changed since then, but there have been updates from your end. I'm not planning any changes to this library in the short term, so I can work with you to resolve this.

**Comment by MardyGit** [comment]
I have a problem with the android version of our app which consumes this library. The linker is dropping a reference to a Google Play API method. So I'm not linking this app version ATM. I'm planning to resolve this while the app is in beta.

**Comment by MardyGit** [comment]
The `__AndroidNativeLibraries__.zip` contains 4 versions of libSkiaSharp.so. I'm using SkiaSharp 2.80.2.

![Screenshot 2021-03-26 at 09 04 04](https://user-images.githubusercontent.com/5832127/112608454-3eda9500-8e12-11eb-831a-3beacfd3f83a.png)

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? You are just referencing SkiaSharp's NuGet package, not bundling `libSkiaSharp.so` yourself?

I would recommend using at least `AndroidLinkMode=SdkOnly` for apps going to Google Play. `SdkOnly` should not cause problems for most apps.

**Comment by MardyGit** [comment]
Here's the build log. I'm only referencing SkiaSharp, as I said above I haven't made any changes to the project since the last build on Feb 5th.

[Stenciletto.Core_AndroidBuldLog.txt](https://github.com/xamarin/xamarin-android/files/6212009/Stenciletto.Core_AndroidBuldLog.txt)

**Comment by MardyGit** [comment]
Regarding the link mode, SdkOnly doesn't work. Nor does LinkSkip. I get this...

`no non-static method "Lcom/google/android/gms/internal/games/zzcm;.getCurrentPlayer()Lcom/google/android/gms/tasks/Task;"`


![Screenshot 2021-03-26 at 13 19 55](https://user-images.githubusercontent.com/5832127/112637371-ff25a480-8e35-11eb-930b-5699533a137f.png)

Though I'm probably doing something stupid somewhere.

**Comment by janusw** [comment]
We're seeing the exact same problem in https://github.com/Mapsui/Mapsui/issues/1115. The size of Mapsui's nupkg has increased by roughly 14 MB when switching from Xamarin.Android 11.1.0.26 to 11.2.0.21!

**Comment by jonathanpeppers** [comment]
@janusw is it also `libSkiaSharp.so` that contributes to the file size? Same as here: https://github.com/xamarin/xamarin-android/issues/5776#issuecomment-808055417

**Comment by janusw** [comment]
> @janusw is it also `libSkiaSharp.so` that contributes to the file size? 

Yes, indeed! See https://github.com/Mapsui/Mapsui/issues/1115#issuecomment-821970862

**Comment by janusw** [comment]
This issue is still present with Xamarin.Android 11.3.0.4. Any progress?

**Comment by jonathanpeppers** [comment]
The problem here is in SkiaSharp: https://github.com/mono/SkiaSharp/pull/1895

As a workaround for now, you should be able to put this in your class library's `.csproj` file:

```xml
<ShouldIncludeNativeSkiaSharp>False</ShouldIncludeNativeSkiaSharp>
```
