### ISSUE TITLE
When I asked about jar binding for the first time, I found it very difficult. Don't know how to modify and rename?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/xamarin-android#5782]
<attr path="/api/package[@name='Com.Iflytek.Cloud']/class[@name='SpeechError']/field[@name='p0']" name="name">b_p0</attr>

Isn't it right for me to revise this way?

 
![image](https://user-images.githubusercontent.com/26525599/112568805-0b9e0300-8e1e-11eb-942c-e0dd702e27bf.png)

The type 'EventArgs' already contains the definition of' P0 '

**Comment by bbhxwl** [comment]
`  <attr path="/api/package[@name='Com.Iflytek.Cloud']/class[@name='SpeechError']/field[@name='p0']" name="name">b_p0</attr>
`

**Comment by jpobst** [comment]
The path is case-sensitive, and most Java package names are lower case, should it be `package[@name='com.iflytek.cloud']`?

**Comment by bbhxwl** [comment]
[Android_aitalk_exp1141_605039a7.zip](https://github.com/xamarin/xamarin-android/files/6208952/Android_aitalk_exp1141_605039a7.zip)

**Comment by bbhxwl** [comment]
> The path is case-sensitive, and most Java package names are lower case, should it be `package[@name='com.iflytek.cloud']`?

As if you're right, but my problem at the moment is.

Document a has Com.Iflytek.Cloud .ErrorEventArgs

File B has it, too Com.Iflytek.Cloud .ErrorEventArgs

**Comment by bbhxwl** [comment]
How to modify this requirement?

**Comment by bbhxwl** [comment]
@mattleibow  @jpobst   @joj  @AmrAlSayed0   help me

**Comment by jpobst** [comment]
I wrote a guide to fixing the duplicate `EventArgs` classes here:
https://github.com/xamarin/java.interop/wiki/Duplicate-EventArgs-Classes

**Comment by bbhxwl** [comment]
> I wrote a guide to fixing the duplicate `EventArgs` classes here:
> https://github.com/xamarin/java.interop/wiki/Duplicate-EventArgs-Classes

I tried to copy the CS file, and then manually modify the code information, as if there were many types that didn't exist.
Metadata is too difficult. I gave up. I think it might be easier to modify the CS file? But why are there so many types that I didn't generate? Can you show me my project?

https://github.com/bbhxwl/xfyunOCWR 
`<remove-node  path="/api"/>`

![image](https://user-images.githubusercontent.com/26525599/112664480-fa440d80-8e94-11eb-8950-9653d8d1e145.png)

**Comment by jpobst** [comment]
I highly suggest you use `metadata`, doing it by hand is going to be a ton of work and nearly impossible to do correctly.

My guess is those files are from a build before you removed the entire API.  Delete them and see if they come back when you rebuild.

**Comment by bbhxwl** [comment]
> I highly suggest you use `metadata`, doing it by hand is going to be a ton of work and nearly impossible to do correctly.
> 
> My guess is those files are from a build before you removed the entire API. Delete them and see if they come back when you rebuild.

It seems that there are four repeated EventArgs and 200 errors. I don't seem to understand metadata very well. It's not clear whether to use managedname or name. I can use PayPal to pay you $20, please ask this question? I really need this. Xamarin is rarely used in China. The hardest part is the third-party class library

**Comment by jpobst** [comment]
The guide I linked to gives sample `metadata` showing how to fix this issue.  

You will need to:
- Change the `path` attribute to point to your method.  (If you look at the `OnError` method in the generated `interface` file it will give you the XPath needed to reference that method.)

For example, in `Com.Iflytek.Cloud.ISpeechUnderstanderListener.cs`:
```
// Metadata.xml XPath method reference: path="/api/package[@name='com.iflytek.cloud']/interface[@name='SpeechUnderstanderListener']/method[@name='onError' and count(parameter)=1 and parameter[1][@type='com.iflytek.cloud.SpeechError']]"
[Register ("onError", "(Lcom/iflytek/cloud/SpeechError;)V", "GetOnError_Lcom_iflytek_cloud_SpeechError_Handler:Com.Iflytek.Cloud.ISpeechUnderstanderListenerInvoker, ClassLibrary3")]
void OnError (global::Com.Iflytek.Cloud.SpeechError p0);
```
- Change the XML inner text value (`MyInterfaceErrorEventArgs`) to be the name you want to give your `EventArgs` class.

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/112667769-a63b2800-8e98-11eb-9bba-8985dccfacaa.png)
For example Com.Iflytek.Cloud .ISpeech UnderstanderListener.cs The first error in the file prompts the type 'erroreventargs' already defines a member with the same parameter type named' erroreventargs'

![image](https://user-images.githubusercontent.com/26525599/112668150-1ba6f880-8e99-11eb-95b2-5341a09f6370.png)
copy com.iflytek.cloud
Modify ErrorEventArgs to ErrorEventArgs2 ?



  <attr  path="/api/package[@name='com.iflytek.cloud']/class[@name='ErrorEventArgs'] " name="name">ErrorEventArgs2</attr>

**Comment by bbhxwl** [comment]
> The guide I linked to gives sample `metadata` showing how to fix this issue.
> 
> You will need to:
> 
> * Change the `path` attribute to point to your method.  (If you look at the `OnError` method in the generated `interface` file it will give you the XPath needed to reference that method.)
> 
> For example, in `Com.Iflytek.Cloud.ISpeechUnderstanderListener.cs`:
> 
> ```
> // Metadata.xml XPath method reference: path="/api/package[@name='com.iflytek.cloud']/interface[@name='SpeechUnderstanderListener']/method[@name='onError' and count(parameter)=1 and parameter[1][@type='com.iflytek.cloud.SpeechError']]"
> [Register ("onError", "(Lcom/iflytek/cloud/SpeechError;)V", "GetOnError_Lcom_iflytek_cloud_SpeechError_Handler:Com.Iflytek.Cloud.ISpeechUnderstanderListenerInvoker, ClassLibrary3")]
> void OnError (global::Com.Iflytek.Cloud.SpeechError p0);
> ```
> 
> * Change the XML inner text value (`MyInterfaceErrorEventArgs`) to be the name you want to give your `EventArgs` class.

`  <attr  path="/api/package[@name='com.iflytek.cloud']/class[@name='ErrorEventArgs'] " name="name">ErrorEventArgs2</attr>
`

**Comment by bbhxwl** [comment]
> The guide I linked to gives sample `metadata` showing how to fix this issue.
> 
> You will need to:
> 
> * Change the `path` attribute to point to your method.  (If you look at the `OnError` method in the generated `interface` file it will give you the XPath needed to reference that method.)
> 
> For example, in `Com.Iflytek.Cloud.ISpeechUnderstanderListener.cs`:
> 
> ```
> // Metadata.xml XPath method reference: path="/api/package[@name='com.iflytek.cloud']/interface[@name='SpeechUnderstanderListener']/method[@name='onError' and count(parameter)=1 and parameter[1][@type='com.iflytek.cloud.SpeechError']]"
> [Register ("onError", "(Lcom/iflytek/cloud/SpeechError;)V", "GetOnError_Lcom_iflytek_cloud_SpeechError_Handler:Com.Iflytek.Cloud.ISpeechUnderstanderListenerInvoker, ClassLibrary3")]
> void OnError (global::Com.Iflytek.Cloud.SpeechError p0);
> ```
> 
> * Change the XML inner text value (`MyInterfaceErrorEventArgs`) to be the name you want to give your `EventArgs` class.

Is the brother still there?

**Comment by bbhxwl** [comment]
> The guide I linked to gives sample `metadata` showing how to fix this issue.
> 
> You will need to:
> 
> * Change the `path` attribute to point to your method.  (If you look at the `OnError` method in the generated `interface` file it will give you the XPath needed to reference that method.)
> 
> For example, in `Com.Iflytek.Cloud.ISpeechUnderstanderListener.cs`:
> 
> ```
> // Metadata.xml XPath method reference: path="/api/package[@name='com.iflytek.cloud']/interface[@name='SpeechUnderstanderListener']/method[@name='onError' and count(parameter)=1 and parameter[1][@type='com.iflytek.cloud.SpeechError']]"
> [Register ("onError", "(Lcom/iflytek/cloud/SpeechError;)V", "GetOnError_Lcom_iflytek_cloud_SpeechError_Handler:Com.Iflytek.Cloud.ISpeechUnderstanderListenerInvoker, ClassLibrary3")]
> void OnError (global::Com.Iflytek.Cloud.SpeechError p0);
> ```
> 
> * Change the XML inner text value (`MyInterfaceErrorEventArgs`) to be the name you want to give your `EventArgs` class.

Did you sleep? It's 3 o'clock in the morning. I'm sleeping too. I hope you can help me.

**Comment by bbhxwl** [comment]
> The guide I linked to gives sample `metadata` showing how to fix this issue.
> 
> You will need to:
> 
> * Change the `path` attribute to point to your method.  (If you look at the `OnError` method in the generated `interface` file it will give you the XPath needed to reference that method.)
> 
> For example, in `Com.Iflytek.Cloud.ISpeechUnderstanderListener.cs`:
> 
> ```
> // Metadata.xml XPath method reference: path="/api/package[@name='com.iflytek.cloud']/interface[@name='SpeechUnderstanderListener']/method[@name='onError' and count(parameter)=1 and parameter[1][@type='com.iflytek.cloud.SpeechError']]"
> [Register ("onError", "(Lcom/iflytek/cloud/SpeechError;)V", "GetOnError_Lcom_iflytek_cloud_SpeechError_Handler:Com.Iflytek.Cloud.ISpeechUnderstanderListenerInvoker, ClassLibrary3")]
> void OnError (global::Com.Iflytek.Cloud.SpeechError p0);
> ```
> 
> * Change the XML inner text value (`MyInterfaceErrorEventArgs`) to be the name you want to give your `EventArgs` class.

are you there?

I really need help.

**Comment by jpobst** [comment]
You need to make your XML:
```
<attr path="/api/package[@name='com.iflytek.cloud']/class[@name='ErrorEventArgs'] " name="name">ErrorEventArgs2</attr>
```

Look like the one in the guide:
```
<attr path="/api/package[@name='my.package']/interface[@name='MyInterface']/method[@name='onError']" name="argsType">MyInterfaceErrorEventArgs</attr>
```

So it needs to be:
```
<attr path="/api/package[@name='com.iflytek.cloud']/interface[@name='SpeechUnderstanderListener']/method[@name='onError']" name="argsType">ErrorEventArgs2</attr>
```
