### ISSUE TITLE
How to do  EventBus  in Xamairn.Android?

### ISSUE THREAD

**Issue by wangyankun33** [xamarin/xamarin-android#5783]

**Comment by wangyankun33** [comment]
使用EventBus3.0.0.jar 通过Binding,使用 Subscribe 时，
jar 异常提示:'`Subscriber class xxx.Activity1 and its super classes have no public methods with the @Subscribe annotation.`

Activity1.cs
```
if (!EventBus.Default.IsRegistered(this))
{
    EventBus.Default.Register(this);
}
StartActivity(new Intent(this, typeof(Activity2)));
```
```
[Subscribe(Priority =10)]
public void OnGetMessage(string msg)
{
    Console.WriteLine($"收到信息:{msg}");
} 
```

**Comment by jpobst** [comment]
This is not a library that we maintain or support.  You will need to get support from the maintainer(s) or searching the internet.

**Comment by jpobst** [comment]
One thing to try would be to add `[Export]` to `OnGetMessage` and see if that helps Java to find the method:

https://github.com/xamarin/release-notes-archive/blob/master/release-notes/android/mono_for_android_4/mono_for_android_4.2/index.md#exporting-arbitrary-java-member-for-better-java-integration
