### ISSUE TITLE
Compilation failed      error   Xlint:deprecation 

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/xamarin-android#5784]
I bind the project successfully, but other projects reference DLL, compile error
https://github.com/bbhxwl/xfyunOCWR      binding 

严重性	代码	说明	项目	文件	行	禁止显示状态
错误		閿欒: 绋嬪簭鍖匔om.Iflytek.Cloud涓嶅瓨鍦?
		Com.Iflytek.Cloud.InitListener
娉? 鏌愪簺杈撳叆鏂囦欢浣跨敤鎴栬鐩栦簡宸茶繃鏃剁殑 API銆?
娉? 鏈夊叧璇︾粏淇℃伅, 璇蜂娇鐢?-Xlint:deprecation 閲嶆柊缂栬瘧銆?
娉? 鏌愪簺杈撳叆鏂囦欢浣跨敤浜嗘湭缁忔鏌ユ垨涓嶅畨鍏ㄧ殑鎿嶄綔銆?
娉? 鏈夊叧璇︾粏淇℃伅, 璇蜂娇鐢?-Xlint:unchecked 閲嶆柊缂栬瘧銆?
1 涓敊璇?	InnoADLMedical.Android	D:\project\InnoADLMedical\InnoADLMedical\InnoADLMedical.Android\obj\Debug\110\android\src\mono\com\iflytek\Cloud\InitListenerImplementor.java	8	

![image](https://user-images.githubusercontent.com/26525599/112595827-ede49400-8e45-11eb-8ea4-a2199ced9c01.png)

**Comment by jpobst** [comment]
Can you get an English error message?  I cannot read what that says, and Google translate isn't returning anything useful.

**Comment by realZhangChi** [comment]
@bbhxwl I encountered the same problem, did you solve it?
