### ISSUE TITLE
Interface method missing 

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/xamarin-android#5809]
Hi again sorry to be a pain, having an issue with an interface method that is missing from the the generated binding library. 

The Interface is `CardNonceBackgroundHandler` and the method that is missing is `handleEnteredCardInBackground` which is a critical method that I need access to. I can confirm in the api.xml that the interface appears not to have any methods despite the .aar showing the method. As such I cannot implement the method in my consuming application to get a hold of the `CardDetails` object. Further more the interface looks to be implementing `IJavaObject, IJavaPeerable` but I dont see these in the original .aar file.

![InkedCapture2_LI](https://user-images.githubusercontent.com/5468757/113228931-781f7300-92f2-11eb-8efa-3b62d3445cbc.jpg)

In my Android application its showing methods to be implemented but not the `handleEnteredCardInBackground`

![Untitled](https://user-images.githubusercontent.com/5468757/113229192-e9f7bc80-92f2-11eb-9a48-7fe4f2476037.png)

**Comment by jpobst** [comment]
You will need to Rebuild with a [diagnostic log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) to find the messages indicating why the method was removed.

`IJavaObject` and `IJavaPeerable` are part of the Xamarin infrastructure and will automatically be added to every bound interface.

In order to implement a bound interface in Xamarin, you need to subclass `Java.Lang.Object` and implement the desired interface, like this:

```
public class CustomCardNonceBackgrounHandler : Java.Lang.Object, ICardNonceBackgroundHandler
{ ... }
```

Deriving from `Java.Lang.Object` will correctly implement all of those needed methods.

**Comment by jpobst** [comment]
I am trying to create some better documentation for investigating binding issues, and added a section for missing types and members:
https://github.com/xamarin/java.interop/wiki/Troubleshooting-Android-Bindings-Issues

Even if it doesn't end up containing the specific fix you need, it should at least help you narrow down what the root issue is so I can help with a fix.

**Comment by LeoJHarris** [comment]
@jpobst okay got this sorted, missing a dependency as usual again. The dependency wasn't actually mentioned in the .pom file but from Gradle and I didn't see this earlier although adding `Java.Lang.Object` did correctly implement the other needed methods which was good. That being said I will go through that additional documentation that was added which will be very helpful indeed! 👍 

![Untitled](https://user-images.githubusercontent.com/5468757/113640820-6bbf5f80-96d0-11eb-9c3f-db488d733815.png)

**Comment by ianmichaelbrown** [comment]
> You will need to Rebuild with a [diagnostic log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) to find the messages indicating why the method was removed.
> 
> `IJavaObject` and `IJavaPeerable` are part of the Xamarin infrastructure and will automatically be added to every bound interface.
> 
> In order to implement a bound interface in Xamarin, you need to subclass `Java.Lang.Object` and implement the desired interface, like this:
> 
> ```
> public class CustomCardNonceBackgrounHandler : Java.Lang.Object, ICardNonceBackgroundHandler
> { ... }
> ```
> 
> Deriving from `Java.Lang.Object` will correctly implement all of those needed methods.

Hi, just wanted to add a note here as I have just been having a similar problem and managed to fix it a different way.  I've created a class in Xamarin which implements an interface contained in a Java binding library.  The interface derives from IJavaObject and IJavaPeerable, so my class has to satisfy their implementations.  Deriving my class from Java.Lang.Object did not work, specifically as IJavaPeerable was not implemented; however, deriving from **Java.Lang.Throwable** did solve my problem, as this contains all the required methods.

This took me a while to work out (I'm not a Java or real Android developer!), so I hope the info helps someone else. :-)

**Comment by jpobst** [comment]
> Deriving my class from Java.Lang.Object did not work, specifically as IJavaPeerable was not implemented

This seems fishy, as `Java.Lang.Object` implements `IJavaPeerable`:
https://docs.microsoft.com/en-us/dotnet/api/java.lang.object
