### ISSUE TITLE
The EGL* APIs have deprecation warnings that can't be followed

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#5818]
### Steps to Reproduce

1. Use `Javax.Microedition.Khronos.Egl.EGL10.EglNoContext`
2. Observe warning `'EGL10.EglNoContext' is obsolete: 'Use 'Javax.Microedition.Khronos.Egl.IEGL10.EglNoContext'. This class will be removed in a future release.'`
3. Use `IEGL10`
4. Observe Compiler error `'IEGL10' does not contain a definition for 'EglNoContext'`
This seems to be the various `No*` things like `NoContext`, `NoDisplay`, and `NoSurface`. And also `EglDefaultDisplay`

### Expected Behavior

The new member exists.

### Actual Behavior

New member does not exist.

### Version Information

This is on `net6.0-android` but did not test classic

**Comment by jpobst** [comment]
Filed as https://github.com/xamarin/java.interop/issues/821 for the root cause.

**Comment by jpobst** [comment]
Fixed as a result of:
- https://github.com/xamarin/java.interop/pull/831
- https://github.com/xamarin/xamarin-android/pull/5923
