### ISSUE TITLE
Keyboard doesn't show up when focus EditText

### ISSUE THREAD

**Issue by RubaShanmugamm** [xamarin/xamarin-android#5821]
### Description

The keyboard doesn't show up when focus EditText, the edit text is added inside the PopupWindow content.

### Steps to Reproduce

1. Run the sample on Android [[Sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/EditText_PopupWindow-1230033734)]
2. Focus the EditText.
3. The keyboard doesn't show up.
4. We were not able to interact with the keys.

### Expected Behavior

The EditText is focused only when the user taps the EditText and Keyboard need to show.

### Actual Behavior

The EditText is focused and Keyboard is not showing.

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:  28.0.0.3
- Affected Devices: In All Android device.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by AnandRaj32** [comment]
Hi Team,

Any update on this?

**Comment by thedee** [comment]
How about an update.  I have same type of issue.

**Comment by jeyakasipandi** [comment]
Any update on this?

**Comment by jeyakasipandi** [comment]
Can you please consider this with high priority?

**Comment by RubaShanmugamm** [comment]
Any update?

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.
