### ISSUE TITLE
Can not find the right path of a android library interface

### ISSUE THREAD

**Issue by mcguu** [xamarin/xamarin-android#5823]
I have tried again and again and read many times about the metadata and binding aar but I still can not do it.
please help me.
the normal error I can fix but only one I can not which is mentioned in the `Troubleshooting Bindings`
`Duplicate custom EventArgs types`

1. add the android.aar in the bindingaar.zip to xamarin.android library.
2. there will be an error The Type `MyClass` already contains a definition for `PropertyChange`
3. try to fix it.

### Actual Behavior
not matter what `path` I set and the `managedName` `managedType` or `argsType` I tried again and again but the `PropertyChange` still be two. I can not remove one or re-name one.

I know there is a interface in the `aar` and there are interface of `onPropertyChange` and there will be two methods call the interface
`addOnPropertyChangeListener` and `setOnPropertyChangeListener` but I set the path of the both still can not re-name the `PropertyChange`

**Comment by jpobst** [comment]
Your case is a little different, in that the `event` is getting duplicated, not the `EventArgs` class.  I am trying to create better documentation for common issues, so I wrote a new page for this case:

https://github.com/xamarin/java.interop/wiki/Duplicate-Events

Hope this helps!

**Comment by mcguu** [comment]
Thank you 

but on the `addOnCameraChangeListener ` and `setOnCameraChangeListener ` there are different codes such as `weak_implementor_AddOnCameraChangeListener` and `weak_implementor_SetOnCameraChangeListener`

shouldn't it re-name ?

**Comment by mcguu** [comment]
I find another question that there are two same name method with different parameters 
there will be same name event-handlers

`public EventHandler<XXXEventArgs> OnXXXHandler;`

how to fix it?
@jpobst

**Comment by mcguu** [comment]
there is another error please help me. thank you.

`“AMap.IOnMapScreenShotListenerImplementor”already contains definition of “OnMapScreenShotHandler”`

**Comment by jpobst** [comment]
Wrote up a guide for that error:  
https://github.com/xamarin/java.interop/wiki/Duplicate-Event-Handlers

**Comment by mcguu** [comment]
There is another question thank you @jpobst  you are perfect.

there is an interface which has a method
void PropertyChange(boolean paramBoolean);

`MyClass` extends the interface
but the code is
`public override void PropertyChange(bool p0){}`

it is wrong and how to remove the `override`?

**Comment by jpobst** [comment]
While I am sorry that our existing tools and documentation are not great, this is really helping me to expand my new binding documentation.  😉 

https://github.com/xamarin/java.interop/wiki/Incorrect-override-or-virtual-Method-Modifiers

**Comment by mcguu** [comment]
Thanks a lot @jpobst .to tell the truth I have seeking this for months but can not find the right answer you help me a lot.

you are a perfect man. and can solve the problem so quick and patiently.

**Comment by mcguu** [comment]
sorry to disturb you but here is another bug:

I compile ok and use in in xamarin.android there is an error:
`
错误		閿欒: 鎵句笉鍒扮鍙?
		.setRunLowFrameListener
  绗﹀彿:   绫?setRunLowFrameListener
  浣嶇疆: 绫?AMapNativeGlOverlayLayer
娉? 鏌愪簺杈撳叆鏂囦欢浣跨敤鎴栬鐩栦簡宸茶繃鏃剁殑 API銆?
娉? 鏈夊叧璇︾粏淇℃伅, 璇蜂娇鐢?-Xlint:deprecation 閲嶆柊缂栬瘧銆?
娉? 鏌愪簺杈撳叆鏂囦欢浣跨敤浜嗘湭缁忔鏌ユ垨涓嶅畨鍏ㄧ殑鎿嶄綔銆?
娉? 鏈夊叧璇︾粏淇℃伅, 璇蜂娇鐢?-Xlint:unchecked 閲嶆柊缂栬瘧銆?
1 涓敊璇?
`
it is the `Xlint:unchecked`? or `Xlint:deprecation`?

**Comment by mcguu** [comment]
another bug @jpobst 

how to fix the package name which has a number?

like `com.xxx.my.3MyClass`

the `3MyClass` how to fix to `ThreeMyClass`?

**Comment by jpobst** [comment]
Here you go!

https://github.com/xamarin/java.interop/wiki/Renaming-namespaces-or-types-or-members

**Comment by mcguu** [comment]
@jpobst  thank you but it not work.

I added it but sill with warnnings.
`Could not find base interface 'com.xxx.api.3ss' for type my-type`
`unknown parameter type **com.xxx.api.3ss.do** for member my-member(com.xxx.api.3ss.do)`

the package name is `com.xxx.api.3ss`

**Comment by jpobst** [comment]
That doesn't seem like issues caused by the package name containing a number.  Those messages are trying to resolve things based on the Java name, which isn't affected by the managed name.

I would try out the "missing API" guide, which should help you determine why the base interface (and other missing API) cannot be found:
https://github.com/xamarin/java.interop/wiki/Missing-Types-or-Members

**Comment by mcguu** [comment]
`Invalidating Com.xxxx.MyClass and all its nested types because some of its methods were invalid`

how to fix this?

**Comment by jpobst** [comment]
You will need to find the messages saying which method(s) were invalid and why in order to know what needs to be fixed.

**Comment by mcguu** [comment]
Thank you handsome man @jpobst
