### ISSUE TITLE
android.security.KeyStoreException: Invalid operation handle

### ISSUE THREAD

**Issue by jantanis** [xamarin/xamarin-android#5831]
We're moving from deprecated code to the new version, but encounter this issue on Samsung S10 when using Biometric Prompt.

### Steps to Reproduce

1. Open the attached solution
2. Tap "Sign!"
3. Use fingerprint
4. Watch crash

### Expected Behavior
No crash, like on the Xiaomi Redmi Note 8 Pro

### Actual Behavior
android.security.KeyStoreException: Invalid operation handle
![Uploading Screen Shot 2021-04-12 at 11.20.58.png…]()

### Version Information
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.9.5 (build 4)
Installation UUID: 31d3c531-ce9e-4f2f-ac8e-48a490cdf4b4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Xamarin Designer ===

Version: 16.9.0.323
Hash: 1b4790c08
Branch: remotes/origin/d16-9
Build date: 2021-03-31 05:12:20 UTC

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.201/Sdks
SDK Versions:
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.100
	2.1.810
	2.1.809
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9

=== .NET Core 3.1 SDK ===

SDK: 3.1.407

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Enterprise)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/jan/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.0
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jan/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9~2
Build date: 2021-03-24 08:30:26 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-03-24 08:30:44 UTC

=== Build Information ===

Release ID: 809050004
Git revision: ec53df089052c178e16b778d89782a97e01d7fa2
Build date: 2021-03-31 17:20:20-04
Build branch: release-8.9
Xamarin extensions: ec53df089052c178e16b778d89782a97e01d7fa2

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
MFractor 4.4.8
Straight8's SpecFlow Integration 1.11.3.0
NuGet Package Management Extensions 0.26
AapIdeExtension.Mac 1.1.81

### Log File

[logcat.txt](https://github.com/xamarin/xamarin-android/files/6295497/logcat.txt)

Solution file
[Signing.zip](https://github.com/xamarin/xamarin-android/files/6295504/Signing.zip)

**Comment by grendello** [comment]
Hi @jantanis 

I don't see the exception you mentioned in OP in the attached logcat file, however it has several instances of the following Java exception:

```
04-12 11:15:27.920  1921  1921 D OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
04-12 11:15:27.920  1256  1256 I ADB_SERVICES: service_to_fd shell:ps -A
04-12 11:15:27.928  1921  1921 W KeyStore: KeyStore exception
04-12 11:15:27.928  1921  1921 W KeyStore: android.os.ServiceSpecificException:  (code 7)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.os.Parcel.createException(Parcel.java:1967)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.os.Parcel.readException(Parcel.java:1921)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.os.Parcel.readException(Parcel.java:1871)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.security.KeyStore.get(KeyStore.java:195)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
04-12 11:15:27.928  1921  1921 W KeyStore:      at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
04-12 11:15:27.928  1921  1921 W KeyStore:      at java.security.KeyStore.getEntry(KeyStore.java:1560)
04-12 11:15:27.928  1921  1921 W KeyStore:      at crc64ee486da937c010f4.ButtonRenderer.n_onClick(Native Method)
04-12 11:15:27.928  1921  1921 W KeyStore:      at crc64ee486da937c010f4.ButtonRenderer.onClick(ButtonRenderer.java:104)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.view.View.performClick(View.java:6614)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.view.View.performClickInternal(View.java:6587)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.view.View.access$3100(View.java:787)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.view.View$PerformClick.run(View.java:26122)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.os.Handler.handleCallback(Handler.java:873)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.os.Looper.loop(Looper.java:201)
04-12 11:15:27.928  1921  1921 W KeyStore:      at android.app.ActivityThread.main(ActivityThread.java:6831)
04-12 11:15:27.928  1921  1921 W KeyStore:      at java.lang.reflect.Method.invoke(Native Method)
04-12 11:15:27.928  1921  1921 W KeyStore:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
04-12 11:15:27.928  1921  1921 W KeyStore:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
```

The only Xamarin.Android bit in that stack trace is the `crc64ee486da937c010f4` package which is a Java wrapper for the button clicked in order to initiate signing. The issue appears to exist entirely on Android/Java side. The exception appears to be thrown by the Java keystore service, possibly when trying to obtain the key service handle? As Xamarin.Android merely wraps the API, I unfortunately don't see anything we can do to fix the issue on our side. I would suggest checking the Android SDK documentation to investigate what `code 7` means in the keystore service, perhaps it's a misconfiguration on the application part or something specific to the hardware you're observing the issue on? Unfortunately, I don't have access to Samsung S10 and was unable to reproduce the exception on my test hardware (Pixel 3XL)
