### ISSUE TITLE
.NET 6: `$(AndroidEnablePreloadAssemblies)`=False by default

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#5838]
Context: d13d0f972a4eb663251b2a6b5a934c59a6789db1
Context: b90d3ab717cbfd38b2e6a307b4387d2d6cf04af8
Context: PR #5790
Context: PR #5811
Context? 9e6ce03ca2d72f5415a2a1650185ba46113cc3dd

For .NET 6 we want `$(AndroidEnablePreloadAssemblies)`=False by default, so that all assemblies don't need to be loaded as part of process startup.

This was done in PR #5790 / d13d0f972a4eb663251b2a6b5a934c59a6789db1 , after which point we found a problem (missed during PR review, alas):

 1. .NET 6 +
 2. "Debug" build +
 3. Fast Deployment +
 4. App launch

resulted in a crash (!) in [`DebuggingTest.ClassLibraryMainLauncherRuns()`](https://github.com/xamarin/xamarin-android/blob/bf4f4f42af26cdddb46087deed59aae8424f7942/tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs#L74-L124):

```
android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
    at MyLibrary.MainActivity.OnCreate(Bundle bundle)
    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
    at com.xamarin.classlibrarymainlauncherruns.MainActivity.n_onCreate(Native Method)
    at com.xamarin.classlibrarymainlauncherruns.MainActivity.onCreate(MainActivity.java:29)
```

The cause of the crash is that, *because* not all assemblies are loaded as part of process startup, [`ResourceIdManager.UpdateIdValues()`](https://github.com/xamarin/xamarin-android/blob/bf4f4f42af26cdddb46087deed59aae8424f7942/src/Mono.Android/Android.Runtime/ResourceIdManager.cs#L9-L31) isn't able to update all fields in all `Resource` types to have the values from the *app* `Resource.designer.cs` file.  Consequently, the values may be invalid, thus the `NullReferenceException`.

In order to actually default `$(AndroidEnablePreloadAssemblies)`=False for .NET 6, we need to figure out how to make this work.

Perhaps we can enable `$(AndroidLinkResources)`=True (9e6ce03ca2d72f5415a2a1650185ba46113cc3dd) for all .NET 6 builds?  What would the build-time impacts be?

**Comment by jonpryor** [comment]
I *thought* I had an idea of a workaround: we should add a handler to the [`AppDomain.AssemblyLoad`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyload?view=net-5.0) event, and fixup resource ids on the assembly when it's loaded.

Then while discussing with @dellis1972 we realized that none of this makes any sense: `ResourceIdManager.UpdateIdValues()` calls the generated `Resource.UpdateIdValues()` method, which is e.g.

```csharp
// From the tests/Xamarin.Forms-Performance-Integration build
namespace Xamarin.Forms.Performance.Integration.Droid {
	public partial class Resource {
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Animation.abc_fade_in = global::Xamarin.Forms.Performance.Integration.Droid.Resource.Animation.abc_fade_in;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.abc_fade_out = global::Xamarin.Forms.Performance.Integration.Droid.Resource.Animation.abc_fade_out;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.abc_grow_fade_in_from_bottom = global::Xamarin.Forms.Performance.Integration.Droid.Resource.Animation.abc_grow_fade_in_from_bottom;
			// …
		}
	}
}
```

*How* does this fail?  When `$(AndroidEnablePreloadAssemblies)` is False, "no" assemblies are preloaded, sure.  However, once the above method is invoked, *every referenced assembly **must** be loaded*, simply so that the specified field can be resolved and it's value updated.

Thus, *why* does `MainActivity.OnCreate()` throw a `NullReferenceException`?  *Presumably* it's because [`MainActivity.cs`](https://github.com/xamarin/xamarin-android/blob/af7f7f5da475c5cb8d2d725d77082ba7915bbc7e/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/MainActivity.cs)' `FindViewById<Button>()` invocation is returning null:

https://github.com/xamarin/xamarin-android/blob/af7f7f5da475c5cb8d2d725d77082ba7915bbc7e/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/MainActivity.cs#L26-L30

That still doesn't make sense though; *why* would `button` be null?  (Is that the actual reason for the `NullReferenceException`?)

More investigation required.

**Comment by jonpryor** [comment]
More investigation: https://discord.com/channels/732297728826277939/732297837953679412/836964276438564884

The cause of the issue is that when `$(AndroidEnablePreloadAssemblies)`=False, the "main" assembly isn't loaded by default.  The main assembly is also the assembly which has the `Resource.UpdateIdValues()` method which is responsible for updating all of the other `Resource` values (see snippet in [previous comment](https://github.com/xamarin/xamarin-android/issues/5838#issuecomment-827762418)).

*Because* the main assembly isn't loaded, *no* assembly is found by `ResourceIdManager.UpdateIdValues()`, and thus `Resource.UpdateIdValues()` is *never* invoked, and thus the resource ids for non-main assemblies are never updated to contain the correct values.

Possible solutions:
1. *Always* preload the "main" assembly.  (The "main" assembly is the assembly created by the "App" `.csproj` build.)

    @dellis1972 is looking into this now.

2. Otherwise "change" `ResourceIdManager.UpdateIdValues()` logic so that instead of probing all loaded assemblies for the `Resource.UpdateIdValues()` method to execute, we specify the type to use "elsewhere", e.g. environment variable, `libxamarin-app.so` value, etc.

3. ...?

**Comment by dellis1972** [comment]
Work around https://github.com/xamarin/xamarin-android/pull/5883
