### ISSUE TITLE
[NET6] libxamarin-debug-app-helper.so should not be packaged for Release builds

### ISSUE THREAD

**Issue by grendello** [xamarin/xamarin-android#5855]
`libxamarin-debug-app-helper.so` is a helper DSO used by Debug builds only, however `dotnet build -c Release` for NET6 places it in the apk:

```shell
net6-samples/HelloMaui/bin/Release/net6.0-android $ zipinfo com.microsoft.hellomaui-Signed.apk | grep helper
-rwxr-xr-x  6.3 unx    37104 b- defX 21-Apr-20 16:45 lib/arm64-v8a/libxamarin-debug-app-helper.so
-rwxr-xr-x  6.3 unx    31796 b- defX 21-Apr-20 16:45 lib/x86/libxamarin-debug-app-helper.so
```

The DSO comes from the `microsoft.android.runtime.android-{ARCH}` nuget packages which contains all the native libraries from Xamarin.Android, for both Release and Debug builds.

**Comment by grendello** [comment]
It appears this issue also applies to `Java.Interop.dll` which is placed in Debug build packages, while it should only be present in the Release ones.

**Comment by dellis1972** [comment]
My guess is `libxamarin-debug-app-helper.so` should not even be in the runtime pack. Its probably just being included because its the default behaviour of the new build system to include all native libs from the pack. 

My understanding about Java.Interop was the problem is its a DEBUG build of the assembly in the pack not a RELEASE one? As a result we are hitting asserts that we don't normally hit. That does raise the question on how we are getting a DEBUG release of that dll in the runtime pack...

**Comment by grendello** [comment]
> My guess is `libxamarin-debug-app-helper.so` should not even be in the runtime pack. Its probably just being included because its the default behaviour of the new build system to include all native libs from the pack.
> 

If the same runtime pack is used to build debug apps, we need to have the DSO in there?

> My understanding about Java.Interop was the problem is its a DEBUG build of the assembly in the pack not a RELEASE one? As a result we are hitting asserts that we don't normally hit. That does raise the question on how we are getting a DEBUG release of that dll in the runtime pack...

Yeah, it's supposed to be used only in Debug builds, so I guess there's no non-debug build of it

**Comment by jonathanpeppers** [comment]
I think we can make this task exclude `libxamarin-debug-app-helper.so` based on `$(AndroidIncludeDebugSymbols)`:

https://github.com/xamarin/xamarin-android/blob/5db4d17c0943420262e324b84afabb759916314a/src/Xamarin.Android.Build.Tasks/Tasks/ProcessNativeLibraries.cs#L9-L14

It seems like the `Java.Interop.dll` we are shipping for .NET 6 is somehow a debug build, whoops!
```csharp
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
```

**Comment by jonathanpeppers** [comment]
> It seems like the Java.Interop.dll we are shipping for .NET 6 is somehow a debug build, whoops!

Nevermind the `Java.Interop.dll` I looked at was from a local `Debug` build.
