### ISSUE TITLE
Setting AndroidFastDeploymentType to "Assemblies:Dexes" leads to [MSB3680] The source file "obj/Debug/androidx/jl/classes.dex" does not exist

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/xamarin-android#5863]
### Steps to Reproduce

1. Set `EmbedAssembliesIntoApk` to `false`
2. Set `AndroidFastDeploymentType` to `Assemblies:Dexes`
3. Run `msbuild`

### Expected Behavior

Succeeding build.

### Actual Behavior

Build failing with error:

`Xamarin.Android.Common.Debugging.targets(207, 2): [MSB3680] The source file "obj/Debug/androidx/jl/classes.dex" does not exist.`

### Workaround

When setting `AndroidFastDeploymentType` to `Assemblies`, the build succeeds.

### Version Information

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.9.7 (build 8)
Installation UUID: 6c0fc207-9de0-4094-807a-d55b8a672088
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.202/Sdks
SDK Versions:
	5.0.202
	5.0.201
	3.1.408
	3.1.407
	2.1.814
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.5
	5.0.4
	3.1.14
	3.1.13
	2.1.26

=== .NET Core 3.1 SDK ===

SDK: 3.1.408

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.8.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Enterprise)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/ckapplmueller/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.1
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/ckapplmueller/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9~2
Build date: 2021-03-24 08:30:26 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-03-24 08:30:44 UTC

=== Build Information ===

Release ID: 809070008
Git revision: 8b7ac2442978ec88d09703fafa4e43eb774f0a26
Build date: 2021-04-16 07:38:03-04
Build branch: release-8.9
Xamarin extensions: 8b7ac2442978ec88d09703fafa4e43eb774f0a26

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Color Helper Addin 0.2

### Log File

[buildlog.txt.zip](https://github.com/xamarin/xamarin-android/files/6357054/buildlog.txt.zip)

### Edits

**Edit 1:** Added "Workaround" section.

**Comment by thisisthekap** [comment]
Thank you @dellis1972 for looking into this one and providing this information on [Discord](https://discord.com/channels/732297728826277939/732297837953679412/834741459764379689):

>it looks like the androidx jetifier process is not producing a classes.dex, we'll need to put in some additional checks to make sure the file exists. So for now, there is no work around you will have use normal Fast Dev.

**Comment by thisisthekap** [comment]
@jonpryor Was this one closed in accident?

**Comment by dellis1972** [comment]
@thisisthekap we merged the fix in the  xamarin/monodroid#1197 PR. Unfortunately that is not a public repo. Hopefully the fix will be in 16.10 Preview 2 or 3.

**Comment by thisisthekap** [comment]
@dellis1972 Great to hear! Thank you for the fast fix.
