### ISSUE TITLE
Xaprepare Fails At The Git Section Due To The Line With The Sole Word "Boundary"

### ISSUE THREAD

**Issue by vindicatorr** [xamarin/xamarin-android#5867]
Heads-up... I'm trying to build from scratch using a non-documented way. But I'm pretty certain this issue in particular is unrelated to that fact.

### Steps to Reproduce

1. Build and run xaprepare
2. Get to the `Running: git --no-pager blame -p "Configuration.props"` part

### Expected Behavior
Don't fail?

### Actual Behavior
Fails with `Unhandled exception. System.InvalidOperationException: Unexpected commit header format (wrong number of fields): boundary`

### Log File

Error:
```
...
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Updating Git submodules                                                                                             
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=                                                       

Elapsed: 00:00:01.3709537

Determining basic build information
  * Commit of last version change
    Running: git --no-pager blame -p "Configuration.props" 
Unhandled exception. System.InvalidOperationException: Unexpected commit header format (wrong number of fields): boundary
```

git output (using `$ git blame -p "Configuration.props"`):
```
5db4d17c0943420262e324b84afabb759916314a 1 1 226
author Jonathan Peppers
author-mail <jonathan.peppers@microsoft.com>
author-time 1618956495
author-tz -0500
committer GitHub
committer-mail <noreply@github.com>
committer-time 1618956495
committer-tz -0500
summary [azdo] fix release branch triggers (#5853)
committer-time 1618956495
committer-tz -0500
summary [azdo] fix release branch triggers (#5853)
boundary
filename Configuration.props
        <?xml version="1.0" encoding="utf-8"?>
...
```

./xaprepare/ToolRunners/GitRunner.BlamePorcelainEntry.cs:
```
			void StoreHeader (string line)
			{
				string[] parts = line.Split (FieldSeparator, 2, StringSplitOptions.RemoveEmptyEntries);
				if (parts.Length != 2)
					throw new InvalidOperationException ($"Unexpected commit header format (wrong number of fields): {line}");
```
Note how "boundary" doesn't have a 2nd part to it.

**Comment by grendello** [comment]
@vindicatorr Can you try https://github.com/xamarin/xamarin-android/pull/5869? I can't repro it locally on any machine (not gettting any `boundary` headers at all), but the PR should work for you

**Comment by vindicatorr** [comment]
Almost, but not quite there yet.
You forgot to account for:
```
				if (OtherHeaders == null)
					OtherHeaders = new SortedDictionary <string, string> (StringComparer.Ordinal);
				**OtherHeaders [parts [0]] = parts [1];**
```
I don't know if you just want to "return" after logging or what.

I was looking to see what "boundaries" were about (not really sure how it came into play): https://stackoverflow.com/questions/42437590/what-is-a-git-boundary-commit
I don't know if it came about because I "cloned" the master using "depth".

Looking at git-blame, when I used "--root", "boundary" doesn't show up, but you're probably safer using your adjusted code in case there are any other hidden timebombs(?) like this.

**Comment by grendello** [comment]
`OtherHeaders` is not a problem here, it's not used anyway.

**Comment by vindicatorr** [comment]
Uhhh... it is though? Given that I even tried it myself `Index was outside the bounds of the array.`
I don't see where the function is going to return before, or skip over `OtherHeaders` trying to grab `parts [1]`

**Comment by grendello** [comment]
Missed a line in the original PR. https://github.com/xamarin/xamarin-android/pull/5875 fixes it.

**Comment by vindicatorr** [comment]
Oh, sure, that'll do. Again, I wasn't getting the "why" behind it existing when it isn't being used, but hey it works now, as you'd expect.

**Comment by grendello** [comment]
The "why" is that it's occasionally useful for ad-hoc debugging locally - to see what we catch where. I can always add a logger loop to dump stuff that gets sent its way on CI
