### ISSUE TITLE
Android.Provider.CalendarContract.IEventsColumns should be public (to be able to use constants)

### ISSUE THREAD

**Issue by JeroenBer** [xamarin/xamarin-android#5868]
We are using constants like:

- Android.Provider.CalendarContract.EventsColumns.Title
- Android.Provider.CalendarContract.EventsColumns.EventLocation

After upgrading to Xamarin.Android.SDK 11.2.2.1 (from 10.2.0.100) we get compiler warnings:
" 'CalendarContract.EventsColumns' is obsolete: 'Use the 'Android.Provider.CalendarContract.IEventsColumns' type. This class will be removed in a future release."

So we changed EventsColumns to IEventsColumns. However then we get a compiler error because IEventsColumns is inaccessible. After looking at the source, this is:

```
protected internal interface IEventsColumns
```

I think this should be made public, otherwise we can no longer use these constants.

**Comment by jpobst** [comment]
This is [defined in Java](https://developer.android.com/reference/android/provider/CalendarContract.EventsColumns?hl=en) as:
```
public final class CalendarContract {
  protected static interface EventsColumns {
    public static final String TITLE = "title";
  }
}
```

This gets translated to `protected internal` which cannot be accessed by user assemblies.

I think we should probably use `metadata` to change these "constants interfaces" to `public`.
