### ISSUE TITLE
Crash from `System.Threading._ThreadPoolWaitCallback:PerformWaitCallback`in Android 5.1 on Kindle

### ISSUE THREAD

**Issue by 1Cor125** [xamarin/xamarin-android#5881]
@jonathanpeppers I'm hoping we can reopen this issue. This is blocking us from shipping to the Amazon store because we are getting a persistent crash on the 5th generation Amazon Kindle Fire device running Android 5.1. It crashes soon after startup or, at the latest, when the user starts doing anything meaningful. We have tried running a previous version of our app (built with an older version of Xamarin Android) on this device and we do not see the crash. The actual exception that causes the crash varies. The stack traces are very shallow and but they _always_ involve a call to `System.Threading._ThreadPoolWaitCallback:PerformWaitCallback`
```
Amazon Kindle Fire 5th Generation
Android 5.1
Xamarin.Android 11.2.2.1
```
Here is the debug output:

```
=================================================================
	Native Crash Reporting
=================================================================
Got a SEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

No native Android stacktrace (see debuggerd output).

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x9e54cf68):0x9e54cf58  80 96 
98 00 00 00 00 00 f0 d8 ff ff ff ff ff ff  ................
0x9e54cf68  60 32 f0 b8 00 00 00 00 00 00 00 00 00 00 00 00  `2..............
0x9e54cf78  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x9e54cf88  00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Threading._ThreadPoolWaitCallback:PerformWaitCallback <0x00033>
	  at <Module>:runtime_invoke_bool <0x000bb>
=================================================================04-13 09:47:37.346 F/libc    (20033): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x9e54cf68 in tid 20108 (Thread Pool Wor)
```
Attached is a log file with all the statements emitted at or around the point of the native crash.

[logcat_output.txt](https://github.com/xamarin/xamarin-android/files/6311133/logcat_output.txt)

_Originally posted by @1Cor125 in https://github.com/xamarin/xamarin-android/issues/4039#issuecomment-819531538_

**Comment by jonathanpeppers** [comment]
This looks like an issue the Mono team would have to look at and fix.

Is this happening only when using AOT or LLVM? Can you turn off either one to get it working?

**Comment by velocitysystems** [comment]
@1Cor125 @jonathanpeppers We're also very keen to get a fix for this issue.
