### ISSUE TITLE
Type casting for return type is  not correct. Error CS0234: The type or namespace name 'Lang' does not exist in the namespace 

### ISSUE THREAD

**Issue by akalghatgi** [xamarin/xamarin-android#5894]
### Steps to Reproduce

1. Creating Binding Project 
2. Add koin-core-2.1.0.jar to jar folder and set the Build Action to "EmbeddedJar"
3. Build
4. Throws errors.
 

### Expected Behavior
Should build and should create binding for each class

### Actual Behavior
Throws multiple error and Binding fails

### Version Information

<details>

</details>

**Comment by jpobst** [comment]
Ugh, they have a package called `org.koin.java` which gets translated to the C# namespace `Org.Koin.Java`.  When we try to cast things to `Java.Lang.Object` it is trying to resolve it as `Org.Koin.Java.Lang.Object` which is incorrect.

The easiest fix is to rename that package to something else using metadata, like this:
```
<attr path="/api/package[@name='org.koin.java']" name="managedName">Koin</attr>
```

**Comment by akalghatgi** [comment]
Hi @jpobst,
     Thanks a lot... renaming has the solved the issue for me... :-)

Regards,
Amit
