### ISSUE TITLE
Binding Fails with Generator.exe exited with code 1.

### ISSUE THREAD

**Issue by akalghatgi** [xamarin/xamarin-android#5904]
### Steps to Reproduce

1. Create Binding Project
2. Add material-1.1.0-rc02.aar to jar folder , Build Action as **LibraryProjecttZip**
3. Build, Throws Error : error MSB6006: "generator.exe" exited with code 1.
[AndroidMaterialBinding.zip](https://github.com/xamarin/xamarin-android/files/6420565/AndroidMaterialBinding.zip)

### Expected Behavior
Should builds nd Generate Binding

### Actual Behavior
Throwing Error : error MSB6006: "generator.exe" exited with code 1.

### Version Information

<details>

1. On macOS and within Visual Studio, select Visual Studio > About Visual Studio, then click the Show Details button, then click the Copy Information button.

2. Paste below this comment block.
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.10 Preview (8.10 build 976)
Installation UUID: 835df4f7-0fa3-464a-85ab-ec7f9bbe2581
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000137

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.137 (2020-02/b4a385816ed) (64-bit)
	Package version: 612000137

=== Roslyn (Language Service) ===

3.10.0-2.21169.30+7eb55689fac855d3fd8aeb5641128c61d0f349cc

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.202/Sdks
SDK Versions:
	5.0.202
	5.0.201
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.302
	2.1.811
	2.1.809
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.5
	5.0.4
	5.0.2
	5.0.1
	5.0.0
	5.0.0-rc.2.20475.5
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.6
	2.1.23
	2.1.22
	2.1.21
	2.1.20

=== .NET Core 3.1 SDK ===

SDK: 3.1.408

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.10.0.81
Hash: 713a3996a
Branch: remotes/origin/d16-10-p2
Build date: 2021-04-16 22:35:52 UTC

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.11.2.4 (Visual Studio Community)
Hash: 62151a4df
Branch: d16-10-preview2
Build date: 2021-04-14 08:56:34-0400

=== Xamarin.iOS ===

Version: 14.17.2.4 (Visual Studio Community)
Hash: 62151a4df
Branch: d16-10-preview2
Build date: 2021-04-14 08:56:34-0400

=== Xamarin.Android ===

Version: 11.2.99.192 (Visual Studio Community)
Commit: xamarin-android/main/a9a7190
Android SDK: /Users/akalghatgi@vmware.com/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.2
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: eb4c311
Java.Interop: xamarin/java.interop/main@a3de91e
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.2@afa0437
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@237642c

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/akalghatgi@vmware.com/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.8
Hash: 56a50f7
Branch: remotes/origin/HEAD
Build date: 2021-03-31 18:48:48 UTC

=== Android Device Manager ===

Version: 16.10.0.9
Hash: 1a0a16f
Branch: main
Build date: 2021-03-31 18:49:14 UTC

=== Build Information ===

Release ID: 810000976
Git revision: 82d55cbad7481152e89f2dbab0fb80dc674a04bd
Build date: 2021-04-19 11:57:57-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Fri Mar  5 01:14:14 PST 2021
    root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64

</details>

### Log File
[Log_Exp.zip](https://github.com/xamarin/xamarin-android/files/6420580/Log_Exp.zip)

**Comment by jpobst** [comment]
You should be able to get a better error message with a [diagnostic build log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output).

There is a lot of information about diagnosing binding issues available [here](https://github.com/xamarin/java.interop/wiki/Troubleshooting-Android-Bindings-Issues).

Also, it seems like you're trying to bind Google's Material library.  We already have a binding of that available on NuGet that is probably much easier to use than binding it yourself:
https://www.nuget.org/packages/Xamarin.Google.Android.Material

If you have a reason for binding it yourself, you will probably want to look at our binding project for it to see what kind of modifications you might need to get it build:
https://github.com/xamarin/AndroidX/tree/master/source/com.google.android.material/material

**Comment by akalghatgi** [comment]
Hi @jpobst,
     Yes... I am trying bind Google Material as we are getting a error while building App using our in-house Android SDK Binding. SDK Binding uses Material 1.0.0 but if I have a reference of it in App I get following errors.

```
Resources/drawable/com_mixpanel_android_nocolor_list.xml : warning XA1001: AndroidResgen: Warning while updating resource XML '/Users/akalghatgi@vmware.com/Documents/code/Xamarin/ws1-sdk-xamarin-native-bindings/XamarinAndroidNativeSampleApp/obj/Release/lp/8/jl/res/drawable/com_mixpanel_android_nocolor_list.xml': Length cannot be less than zero.
Resources/drawable/com_mixpanel_android_nocolor_list.xml : warning XA1001: Parameter name: length
/Users/akalghatgi@vmware.com/Documents/code/Xamarin/ws1-sdk-xamarin-native-bindings/XamarinAndroidNativeSampleApp/obj/Release/lp/5/jl/res/values/values.xml(4): error APT2260: resource style/Preference_TextAppearanceMaterialBody2 (aka com.air_watch.peoplesearch:style/Preference_TextAppearanceMaterialBody2) not found.
/Users/akalghatgi@vmware.com/Documents/code/Xamarin/ws1-sdk-xamarin-native-bindings/XamarinAndroidNativeSampleApp/obj/Release/lp/5/jl/res/values-v17/values-v17.xml(2): error APT2260: resource style/Preference_TextAppearanceMaterialBody2 (aka com.air_watch.peoplesearch:style/Preference_TextAppearanceMaterialBody2) not found.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(157,3): error APT2260: resource style/Theme.MaterialComponents.DayNight.Bridge (aka com.air_watch.peoplesearch:style/Theme.MaterialComponents.DayNight.Bridge) not found.
/Users/akalghatgi@vmware.com/Documents/code/Xamarin/ws1-sdk-xamarin-native-bindings/XamarinAndroidNativeSampleApp/obj/Release/lp/15/jl/res/values/values.xml(2): error APT2260: style attribute 'attr/hintTextColor (aka com.air_watch.peoplesearch:attr/hintTextColor)' not found.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(157,3): error APT2062: failed linking references.
```

if I upgrade to higher version I get these error.
```
Resources/drawable/com_mixpanel_android_nocolor_list.xml : warning XA1001: AndroidResgen: Warning while updating resource XML '/Users/akalghatgi@vmware.com/Documents/code/Xamarin/ws1-sdk-xamarin-native-bindings/XamarinAndroidNativeSampleApp/obj/Release/lp/8/jl/res/drawable/com_mixpanel_android_nocolor_list.xml': Length cannot be less than zero.
Resources/drawable/com_mixpanel_android_nocolor_list.xml : warning XA1001: Parameter name: length
/Users/akalghatgi@vmware.com/Documents/code/Xamarin/ws1-sdk-xamarin-native-bindings/XamarinAndroidNativeSampleApp/obj/Release/lp/5/jl/res/values/values.xml(4): error APT2260: resource style/Preference_TextAppearanceMaterialBody2 (aka com.air_watch.peoplesearch:style/Preference_TextAppearanceMaterialBody2) not found.
/Users/akalghatgi@vmware.com/Documents/code/Xamarin/ws1-sdk-xamarin-native-bindings/XamarinAndroidNativeSampleApp/obj/Release/lp/5/jl/res/values-v17/values-v17.xml(2): error APT2260: resource style/Preference_TextAppearanceMaterialBody2 (aka com.air_watch.peoplesearch:style/Preference_TextAppearanceMaterialBody2) not found.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(157,3): error APT2062: failed linking references.
```

So I am not able to build the app with any version available of "Xamarin.Google.Android.Material"

**Comment by akalghatgi** [comment]
Hi @jpobst , Closing this issue as issue was somewhere else... 
Thanks
