### ISSUE TITLE
"java.exe" exited with code 1

### ISSUE THREAD

**Issue by Manojjangir** [xamarin/xamarin-android#5933]
### Steps to Reproduce

1. Severity Code Description Project File Line Suppression State Error "java.exe" exited with code 1. WoWonder C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets 79

### Version Information

 Microsoft Visual Studio Community 2019
Version 16.9.3
VisualStudio.16.Release/16.9.3+31129.286
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA199
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.9.693.2781
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.273 (d16-9@1bba9e0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by Manojjangir** [comment]
I added a new package file named Firebase Analytics and after adding the package I'm getting the error "java.exe" exited with code 1. Can you tell me the solution to solve this error?

**Comment by jpobst** [comment]
You will need to collect a [Diagnostic MSBuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) which should contain the actual error that `java.exe` is reporting.

**Comment by Manojjangir** [comment]
Here I am attaching the output build log file
[Output-Build.txt](https://github.com/xamarin/xamarin-android/files/6494376/Output-Build.txt)

**Comment by jonathanpeppers** [comment]
The error is:
```
1>  Error in obj\Release\110\lp\172\jl\bin\classes.jar:com/google/android/gms/internal/measurement/zze.class:
1>  Type com.google.android.gms.internal.measurement.zze is defined multiple times: obj\Release\110\lp\172\jl\bin\classes.jar:com/google/android/gms/internal/measurement/zze.class, obj\Release\110\lp\174\jl\bin\classes.jar:com/google/android/gms/internal/measurement/zze.class
1>  Compilation failed
```

The same class is coming from:
```
Xamarin.GooglePlayServices.Measurement.Base.dll
Xamarin.GooglePlayServices.Measurement.Impl.dll
```

Can you verify that all of your Google Play Services NuGet packages are on the same version? Something like this could happen if Google moved a Java class from one library to another and your versions are mixed.

You don't actually have diagnostic verbosity turned on in this log, so I can't see the versions of your NuGet packages.

**Comment by Manojjangir** [comment]
can you elaborate how to match the versions, I am new to xamarin and I do not know much about it.

**Comment by Manojjangir** [comment]
I am not able to attach the diagnostic build log file here so I am attaching a link to my drive where file is stored.
https://drive.google.com/file/d/1whKbn6GUew558756QG975rGy2hkNRPO_/view?usp=sharing

**Comment by jonathanpeppers** [comment]
@Manojjangir if you go to NuGet packages screen in Visual Studio, does it show any updates? Is there anything on the `Consolidate` tab it prompts you to fix?

Right away at the top of your build log indicates there are versions that don't match:
```
NU1605: Detected package downgrade: Xamarin.AndroidX.Lifecycle.ViewModel from 2.3.1 to 2.3.0.2-alpha03. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.AndroidX.Activity 1.2.2 -> Xamarin.AndroidX.Lifecycle.ViewModel (>= 2.3.1) 
 WoWonder -> Xamarin.AndroidX.Lifecycle.ViewModel (>= 2.3.0.2-alpha03)
NU1605: Detected package downgrade: Xamarin.AndroidX.Lifecycle.ViewModel from 2.3.1 to 2.3.0.2-alpha03. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.AndroidX.Fragment 1.3.2 -> Xamarin.AndroidX.Lifecycle.ViewModel (>= 2.3.1) 
 WoWonder -> Xamarin.AndroidX.Lifecycle.ViewModel (>= 2.3.0.2-alpha03)
NU1605: Detected package downgrade: Xamarin.AndroidX.Lifecycle.ViewModel from 2.3.1 to 2.3.0.2-alpha03. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.AndroidX.Lifecycle.ViewModelSavedState 2.3.1 -> Xamarin.AndroidX.Lifecycle.ViewModel (>= 2.3.1) 
 WoWonder -> Xamarin.AndroidX.Lifecycle.ViewModel (>= 2.3.0.2-alpha03)
NU1605: Detected package downgrade: Xamarin.GooglePlayServices.Basement from 117.6.0 to 117.5.0. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.Firebase.Analytics 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Api 118.0.3 -> Xamarin.GooglePlayServices.Basement (>= 117.6.0) 
 WoWonder -> Xamarin.GooglePlayServices.Basement (>= 117.5.0)
NU1605: Detected package downgrade: Xamarin.GooglePlayServices.Measurement.Base from 118.0.3 to 118.0.0. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.Firebase.Analytics 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Api 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Base (>= 118.0.3) 
 WoWonder -> Xamarin.GooglePlayServices.Measurement.Base (>= 118.0.0)
NU1605: Detected package downgrade: Xamarin.GooglePlayServices.Measurement.Sdk.Api from 118.0.3 to 118.0.0. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.Firebase.Analytics 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Api 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Sdk.Api (>= 118.0.3) 
 WoWonder -> Xamarin.GooglePlayServices.Measurement.Sdk.Api (>= 118.0.0)
NU1605: Detected package downgrade: Xamarin.Firebase.Measurement.Connector from 118.0.2 to 118.0.1. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.Firebase.Analytics 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Api 118.0.3 -> Xamarin.Firebase.Measurement.Connector (>= 118.0.2) 
 WoWonder -> Xamarin.Firebase.Measurement.Connector (>= 118.0.1)
NU1605: Detected package downgrade: Xamarin.GooglePlayServices.Basement from 117.6.0 to 117.5.0. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.Firebase.Analytics 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Sdk 118.0.3 -> Xamarin.GooglePlayServices.Basement (>= 117.6.0) 
 WoWonder -> Xamarin.GooglePlayServices.Basement (>= 117.5.0)
NU1605: Detected package downgrade: Xamarin.GooglePlayServices.Measurement.Base from 118.0.3 to 118.0.0. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.Firebase.Analytics 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Sdk 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Base (>= 118.0.3) 
 WoWonder -> Xamarin.GooglePlayServices.Measurement.Base (>= 118.0.0)
NU1605: Detected package downgrade: Xamarin.GooglePlayServices.Basement from 117.6.0 to 117.5.0. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.Firebase.Analytics 118.0.3 -> Xamarin.GooglePlayServices.Measurement 118.0.3 -> Xamarin.GooglePlayServices.Basement (>= 117.6.0) 
 WoWonder -> Xamarin.GooglePlayServices.Basement (>= 117.5.0)
NU1605: Detected package downgrade: Xamarin.GooglePlayServices.Measurement.Base from 118.0.3 to 118.0.0. Reference the package directly from the project to select a different version. 
 WoWonder -> Xamarin.Firebase.Analytics 118.0.3 -> Xamarin.GooglePlayServices.Measurement 118.0.3 -> Xamarin.GooglePlayServices.Measurement.Base (>= 118.0.3) 
 WoWonder -> Xamarin.GooglePlayServices.Measurement.Base (>= 118.0.0)
 ```

**Comment by Manojjangir** [comment]
yes there are updates available but when I update those packages, some other errors occurs.
