### ISSUE TITLE
Error XA2002 in Package Reference Xamarin.Android.Legacy.targets(5,5)

### ISSUE THREAD

**Issue by nkolev92** [xamarin/xamarin-android#5946]
https://github.com/nuget/home/issues/10870 by @MaheshBalasubramanian

## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): 

Mono Framework MDK
Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

Roslyn (Language Service)
3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

NuGet
Version: 5.8.0.6860

Product version: 

Worked before? If so, with which NuGet version: N/A

## Repro steps and/or sample project

I have added PDFSharp NuGet Package and while I am building the project, I am getting the below error.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(5,5): Error XA2002.
 Can not resolve reference: `PdfSharp`, referenced by `SevenDashboard`. Please add a NuGet package or assembly reference for `PdfSharp`, or remove the reference to `SevenDashboard`. (XA2002) (SevenDashboard.Android)

**Comment by jonathanpeppers** [comment]
@MaheshBalasubramanian can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? Thanks!
