### ISSUE TITLE
AndroidManifestPlaceholders feature is not documented 

### ISSUE THREAD

**Issue by RwSgxx** [xamarin/xamarin-android#5950]
This is what it does on Android:
[https://developer.android.com/studio/build/manifest-build-variables](https://developer.android.com/studio/build/manifest-build-variables)

It works in Xamarin Android by adding 

```xml
<PropertyGroup> 
<AndroidManifestPlaceholders>PlaceHolderName=PlaceHolderValue'</AndroidManifestPlaceholders> 
</PropertyGroup>
```
to the Xamarin Android csproj
and using it like this in the manifest:
`<application android:label="${PlaceHolderName}"></application>`

This is great for builds that have different properties for each build config. But there is ZERO documentation!

**Comment by dellis1972** [comment]
This feature is documented [here](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties#androidmanifestplaceholders). I admit it could be improved, however the basics are there.

**Comment by RwSgxx** [comment]
Great 👍
