### ISSUE TITLE
LibraryProjectZip build action is not working after migrating binding project to .NET6 

### ISSUE THREAD

**Issue by APopatanasov** [xamarin/xamarin-android#5957]
### Error Message or Issue

I have migrated a mono.android binding project to .NET 6. After the migration the LibraryProjectZip build action set for the .aar file does not work. After decompiling the binary file inside the Resources folder there isn't any "**\_\_AndroidNativeLibraries\_\_.zip"**. I have tried with AndroidLibrary build action as well - the result was the same.

### Version Information

My environment is **MacOS Big Sur 11.3.1** with **dotnet version - 6.0.100-preview.4.21255.9**

### Log File

[binlog.zip](https://github.com/xamarin/xamarin-android/files/6538366/binlog.zip)

### Other Helpful Info

Here is a sample project where the issue can be reproduced - the sample contains aar file as well.
[AndroidBindingNet6.zip](https://github.com/xamarin/xamarin-android/files/6538406/AndroidBindingNet6.zip)
1. Open terminal.
2. Run the following command:
    **dotnet build AndroidBindingNet6.sln -c Release**
3. Decompile the binary and notice how Resources is empty.
<img width="350" alt="Screenshot 2021-05-25 at 12 43 14" src="https://user-images.githubusercontent.com/9336157/119480090-fbd96700-bd59-11eb-8dbf-0e07387cc6f4.png">

**Comment by jonathanpeppers** [comment]
@APopatanasov the resources will be empty, and `__AndroidLibraryProjects__.zip` will not exist in .NET 6.

See: https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md

What should happen is any number of `.aar` or `.jar` files will get copied to your build output next to the `.dll` file.

If you `dotnet pack`, then the `.nupkg` should contain these files automatically.

Is some part of this not working? There could still be an issue here.

**Comment by APopatanasov** [comment]
@jonathanpeppers Thanks for the information. I actually came upon that documentation before I logged the issue, but still I was not sure if this is the intended behavior for .NET 6. The thing that confused me was [this](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-items#libraryprojectzip) part of the documentation where LibraryProjectZip is mentioned to work in NET6.

**Comment by jonathanpeppers** [comment]
@APopatanasov it looks me from your original `.binlog` that `@(LibraryProjectZip)` was indeed working:

```
Task ClassParse
Parameters
    SourceJars = obj/Release/net6.0-android/library_project_jars/Common-Release.aar/classes.jar
    OutputFile = obj/Release/net6.0-android/api.xml.class-parse
...
Copying file from "/Users/apopatan/Projects/AndroidBindingNet6/AndroidBindingNet6/Common-Release.aar" to "/Users/apopatan/Projects/AndroidBindingNet6/AndroidBindingNet6/bin/Release/net6.0-android/Common-Release.aar".
```

What issue were you having exactly?

**Comment by APopatanasov** [comment]
@jonathanpeppers I was expecting that build action to work the same way as in the mono android type of projects. To create an "\_\_AndroidNativeLibraries\_\_.zip" and to include it in the Resources of the dll.

Here is how the dll looks in MonoAndroid:
<img width="352" alt="Screenshot 2021-05-28 at 9 53 28" src="https://user-images.githubusercontent.com/9336157/119942502-958f5700-bf9a-11eb-9837-8535cc48501a.png">

I am fine with the way how it is working now - copying the aar file next to the dll.

**Comment by jonathanpeppers** [comment]
@APopatanasov thanks let us know if you hit an issue with that, is it brand new, thanks!
