### ISSUE TITLE
When press Backspace, the TextChanged event is called thrice and Text is not cleared

### ISSUE THREAD

**Issue by RubaShanmugamm** [xamarin/xamarin-android#5958]
### Steps to Reproduce

Issue Description:

I have added the Text inside the TextChanged based on the particular condition. While press backspace the text is not cleared. Check the sample attached.

**Note: Issue reproduced only a particular device**

1. Run the attached sample in Xamarin.Android. [[Sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample_Android-2122646381)]
2. Focus the EditText and type any character.
3. Then press backspace for deleting the character.

### Expected Behavior
The TextChanged event is called only once.

### Actual Behavior
The TextChanged event is called three times.

### Version Information

<details>

</details>

**Comment by jpobst** [comment]
I'm not sure I understand your issue.

### Scenario 1: Pressing `g`

If I press `g` I get:
```
[0:] TextChanged event calling count:1
```

Then when I press backspace I get:
```
[0:] TextChanged event calling count:2
```

### Scenario 2: Pressing `a`

If I press `a` I get:
```
[0:] TextChanged event calling count:1
[0:] TextChanged event calling count:2
```

One is from changing the text from nothing to `a`, and one is from changing the text from `a` to `India`.

Then when I press backspace I get:
```
[0:] TextChanged event calling count:3
```

Pressing backspace removes the letter in front of the cursor, correctly leaving `Indi`.

Are you seeing something different?

**Comment by jpobst** [comment]
If you are trying to create an AutoComplete text box, there is one built-in that you will probably want to use instead of writing your own: https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/auto-complete.

**Comment by RubaShanmugamm** [comment]
Hi @jpobst 

Thanks for addressing the reported issue. 

Actually, AutoComplete control isn't something I'm looking for. Because I used EditText to construct a custom control and we appended the Text in the TextChanged event, if I remove the text, the TextChanged event will be called three times, and it will not operate properly on my end.

Can you check the [this](https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample_Android-1664170204) sample on **pixel device with Android 9.0(API 28)**?

Replication steps:
1. press "e" - TextChanged event calling. One is from changing the text from nothing to "e", and one is from changing the text from "e" to "EditText".
2. Press backspace - TextChanged event calling three times.

Expected Behaviour: The TextChanged event calling only once.

**Comment by jpobst** [comment]
It looks like this is known behavior with Android's EditText:
https://stackoverflow.com/questions/17535415/textwatcher-events-are-being-fired-multiple-times

The suggestion to make it `textVisiblePassword` seems to work, and only triggers the TextChanged event once.

```
editText.InputType |= InputTypes.TextVariationVisiblePassword;
```
