### ISSUE TITLE
Missing release notes for xamarin android 11.3.0.1 and 11.3.99.31

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#5961]
Visual studio 16.10.0 has just been published.
Could you please make sure release notes for xamarin are published with VS release notes ?
cc @brendanzagaeski #5498
cc @dalexsoto https://github.com/xamarin/xamarin-macios/issues/11684

**Comment by tranb3r** [comment]
Visual Studio 16.11.0-pre3 is out with xamarin-android 11.4.0.5. What's new in this release ? There is no corresponding tag in github !!

**Comment by Tommigun1980** [comment]
@tranb3r You are supposed to fly blind. It's exciting!

**Comment by Tommigun1980** [comment]
Seriously, release notes are an absolute necessity and we shouldn't have to open bug reports for this.
Thank you for a prompt fix.
