### ISSUE TITLE
VS 2019 16.11.0 Preview 1.0 - WindowInsetsController

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#5970]
I upgraded my app yesterday to Android 11 and immediately hit a problem with my ImmersiveFragment class which was using the now deprecated Activity.Window.DecorView.SystemUiVisibility to control SystemUiVisibility. Since it failed on Android 11, I then checked out IWindowInsetsController interface to replace it.

It seems to be missing the following. 

```
public int BEHAVIOR_SHOW_BARS_BY_TOUCH = 0;  		//0x00000000 Deprecated Android 12 S - Use BEHAVIOR_DEFAULT or BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
public int BEHAVIOR_SHOW_BARS_BY_SWIPE = 1;  		//0x00000001 Deprecated Android 12 S - Use BEHAVIOR_DEFAULT instead
        
public int BEHAVIOR_DEFAULT = 1;                       //0x00000001
public int BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE = 2;  //0x00000002

public int APPEARANCE_LIGHT_NAVIGATION_BARS = 16;      //0x00000010
public int APPEARANCE_LIGHT_STATUS_BARS = 8;           //0x00000008 
```
        
Looking at the Android docs it would appear they are in their WindowInsetsController, but not in Xamarin’s IWindowInsetsController.

Adding the following code to my HideSystemUi method fixes my problem and does produce the same result as my previous code.
```
Activity.Window.SetDecorFitsSystemWindows(false);
IWindowInsetsController windowInsetsController = Activity.Window.InsetsController;
windowInsetsController.Hide(WindowInsets.Type.SystemBars());                            
windowInsetsController.SystemBarsBehavior = BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE;
```
and the following code in my ShowSystemUi method also works.

```
Activity.Window.SetDecorFitsSystemWindows(true);
IWindowInsetsController windowInsetsController = Activity.Window.InsetsController;
windowInsetsController.Show(WindowInsets.Type.SystemBars());
```
Substituting WindowInsets.Type.StatusBars() | WindowInsets.Type.NavigationBars() for WindowInsets.Type.SystemBars() works too.

The only problem is you need an if (Build.VERSION.SdkInt >= BuildVersionCodes.R) else test and the old code for whatever the device is running.

The docs indicate that there is an androidx.core.view.WindowInsetsControllerCompat version which would eliminate the Build.Version.SdkInt test. However the available Xamarin.AndroidX.Core version is only at 1.3.2.3, whereas I think the Compat version wasn’t added until their 1.5.0 version. 

As the Android 11 deadline for Google Play is looming is there any chance that more resources could be made available for the AndroidX stuff.

**Comment by dellis1972** [comment]
So is this an AndroidX issue? If so and issue should probably be raised over at https://github.com/xamarin/AndroidX.

It looks like WindowInsetsController is part of API 30 though, so this is probably more a binding issue? @jpobst is that your area?

**Comment by jpobst** [comment]
> Since it failed on Android 11

Why did it fail?  Using a deprecated API should just be a warning, it should continue working for several years.

> It seems to be missing the following...

These constants were made into enums, which is good:

- `Android.Views.WindowInsetsControllerAppearance`
- `Android.Views.WindowInsetsControllerBehavior`

Unfortunately it looks like the methods that use them, like `WindowInsetsController.SystemBarsBehavior` did not get changed to use the enum, which is bad.  Worse, this can't really be fixed now, as fixing it would be a breaking change.

You can use them like this:
```
windowInsetsController.SystemBarsBehavior = (int)WindowInsetsControllerBehavior.ShowBarsBySwipe;
```

> Xamarin.AndroidX.Core 1.5.0

Looks like this version just came out last week.  Fortunately we've dramatically shortened the time it takes us to update AndroidX packages, so it'll probably be published in a week or two.  (Unless it adds something bizarre that require a lot of extra work.)

**Comment by gmck** [comment]
@jpobst 

> Why did it fail? Using a deprecated API should just be a warning, it should continue working for several years.

It didn’t fail on the HideUi, but on the ShowUi. The show didn’t effectively cancel the full screen and therefore the toolbar of the return fragment got pushed to the top of the screen and the status bar and its contents were then placed over the top of it. Not a good look!!. Android 10 and less devices were still ok. I didn’t really spend any time on why it failed, because at the time I thought I’d be able to use the Compat version.

•	Android.Views.WindowInsetsControllerAppearance
•	Android.Views.WindowInsetsControllerBehavior

Thanks for those enums. Not knowing how Xamarin would have named them I searched with the object browser for Swipe but it only came up with Google.Android.Material stuff so I assumed they were all missing. I should have searched for Transient which does come up with Android.Views.WindowInsetsControllerBehavior.ShowTransientBarsBySwipe which was the one I wanted anyway.

The enums have eliminated my fix. Not too much of a hassle to have to cast it when the compiler suggests you need to anyway.

> Worse, this can't really be fixed now, as fixing it would be a breaking change.
Not that it really matters now. I don’t understand that. Why not a breaking change if the change is documented?

Xamarin’s WindowInsetsController Compat version can’t come quick enough.

**Comment by jpobst** [comment]
> Not that it really matters now. I don’t understand that. Why not a breaking change if the change is documented?

If it just required people to change their source code in order to compile we would probably consider it.  

However it's a binary breakage, which means any NuGet package out there that has been compiled against the "broken" version would now crash at runtime.  And any NuGet package that had been updated to the "fixed" version would crash for users who had not upgraded their VS yet.

Breaking the entire ecosystem is too costly, so we just live with the mistake.
