### ISSUE TITLE
Xa-prep-tasks "Unable to parse branch name"

### ISSUE THREAD

**Issue by vindicatorr** [xamarin/xamarin-android#5972]
### Steps to Reproduce

1. $`dotnet msbuild /t:Restore,Build /binaryLogger:"bin/BuildRelease/bootstrap-build.binlog" /fileLogger1 /p:Configuration=Release Xamarin.Android.BootstrapTasks.sln`

### Expected Behavior
Build completes

### Actual Behavior
Parsing external/sqlite branch fails with `build-tools/scripts/XAVersionInfo.targets(31,5): error : Unable to parse branch name from: grafted, HEAD [<pathTo>/build-tools/xa-prep-tasks/xa-prep-tasks.csproj]`

\<pathTo\>/xamarin-android/build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitCommitInfo.cs:61
`if (branchFull.StartsWith ("HEAD, ", StringComparison.Ordinal)) {`
Issue is that sqlite starts with "grafted"

XAVersionInfo.targets:31
```
    <GitCommitInfo
        WorkingDirectory="$(XamarinAndroidSourcePath)\%(_SubmoduleBranchInfo.Identity)"
        XASourceDirectory="$(XamarinAndroidSourcePath)"
        SubmoduleName="%(_SubmoduleBranchInfo.Identity)"
        GitPath="$(GitToolPath)$(GitToolExe)">
      <Output TaskParameter="CommitInfo" PropertyName="%(_SubmoduleBranchInfo.OutputPropertyName)" />
    </GitCommitInfo>
```

Good branch info: proguard
`commit 912d149394fc96072905735649327d4101980832 (HEAD, tag: v7.0.1)`
```
       Task "GitCommitInfo"
         Task Parameter:WorkingDirectory=<pathTo>/xamarin-android/external/proguard
         Task Parameter:XASourceDirectory=<pathTo>/xamarin-android
         Task Parameter:SubmoduleName=external/proguard
         Gathering GIT commit info submodule external/proguard in directory '<pathTo>/xamarin-android/external/proguard'
           Detached HEAD, branch information available
           Branch: v7.0.1
           Commit hash: 912d149
           Repository URL: https://github.com/Guardsquare/proguard.git
           Organization: Guardsquare
           Repository: proguard
         Output Property: _BuildInfo_ProguardCommit=Guardsquare/proguard/v7.0.1%40912d149
       Done executing task "GitCommitInfo".
```
Bad branch info: sqlite
`commit 85460d34e2bbb357e4fb7ec7161decf41f19dffb (grafted, HEAD)`
```
       Task "GitCommitInfo"
         Task Parameter:WorkingDirectory=<pathTo>/xamarin-android/external/sqlite
         Task Parameter:XASourceDirectory=<pathTo>/xamarin-android/
         Task Parameter:SubmoduleName=external/sqlite
         Gathering GIT commit info submodule external/sqlite in directory '<pathTo>/xamarin-android/external/sqlite'
```

### Version Information

<details>

</details>

**Comment by vindicatorr** [comment]
I should add that if I "--unshallow" the sqlite git, then it'll be fine.
I just prefer to use "--depth 1" when I'm manually cloning, instead of having xaprepare get it all itself.

**Comment by jpobst** [comment]
We no longer have a `sqlite` git submodule, so I'm guessing this is no longer an issue.
