### ISSUE TITLE
error APT2263: unexpected element <provider> found in <manifest><queries>

### ISSUE THREAD

**Issue by ololomax** [xamarin/xamarin-android#6003]
### Steps to Reproduce

1. Create blank Android project
2. Open Properties/AndroidManifest.xml with Source Code Editor
3. Add following text before `<application>` tag:

```
<queries>
    <provider android:authorities="test" />
</queries>
```

4. Build project

### Expected Behavior

Project builds successfully

### Actual Behavior

Project build fails with error:
> ../Properties/AndroidManifest.xml : error APT2263: unexpected element `<provider>` found in `<manifest><queries>`.
> ../Properties/AndroidManifest.xml : error APT2263: 
> ../Properties/AndroidManifest.xml : error APT2263: This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.

### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.10 (build 1773)
Installation UUID: e86bbf72-2fb5-4c73-8670-cc0bed94d486
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-3.21251.8+4c32f5e4e9c0828a94fd4d1c9c0994082c85aaf3

=== NuGet ===

Version: 5.9.0.7134

=== Xamarin Designer ===

Version: 16.10.0.117
Hash: 249267d55
Branch: remotes/origin/d16-10
Build date: 2021-05-24 21:27:04 UTC

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.203/Sdks
SDK Versions:
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.101
	5.0.100
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.404
	3.1.403
	3.1.402
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.1
	5.0.0
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.10
	3.1.9
	3.1.8
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

=== .NET Core 3.1 SDK ===

SDK: 3.1.409

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.1 (Visual Studio Community)
Commit: xamarin-android/d16-10/22fc2b3
Android SDK: /Users/maks/Documents/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.2
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/maks/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-05-13 17:01:38 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-05-13 17:01:56 UTC

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Version: 7.14.0.1 (Visual Studio Community)
Hash: fe0e2c518
Branch: d16-10
Build date: 2021-05-19 08:15:55-0400

=== Xamarin.iOS ===

Version: 14.20.0.1 (Visual Studio Community)
Hash: fe0e2c518
Branch: d16-10
Build date: 2021-05-19 08:15:56-0400

=== Build Information ===

Release ID: 810001773
Git revision: 56d63e5691f86f863cfaed823a5a8fe430e1aaa9
Build date: 2021-05-28 11:21:28-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.5.0 Darwin Kernel Version 20.5.0
    Sat May  8 05:10:33 PDT 2021
    root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Log File

> Building whadhr (Debug)
> Build started 06.06.2021 13:05:34.
> __________________________________________________
> Project "/Users/maks/Desktop/whadhr/whadhr/whadhr.csproj" (Build target(s)):
> 
> Target _ResolveAndroidTooling:
>     Found Java SDK version 1.8.0.
>     Found Java SDK version 1.8.0.
> Target _CheckInstantRunCondition:
>     Dex Fast Deployment Enabled: False
> Target _ResolveMonoAndroidSdks:
>     MonoAndroid Tools: /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/
>     Android Platform API level: 30
>     TargetFrameworkVersion: v11.0
>     Android NDK: /Users/maks/Documents/Android/sdk/ndk-bundle/
>     Android SDK: /Users/maks/Documents/Android/sdk/
>     Android SDK Build Tools: /Users/maks/Documents/Android/sdk/build-tools/30.0.2/
>     Java SDK: /Users/maks/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/
>     Application Java class: android.app.Application
> Target _CleanIntermediateIfNeeded:
>   Skipping target "_CleanIntermediateIfNeeded" because all output files are up-to-date with respect to the input files.
> Target _ResolveLibraryProjectImports:
>   Skipping target "_ResolveLibraryProjectImports" because all output files are up-to-date with respect to the input files.
> Target _BuildLibraryImportsCache:
>   Skipping target "_BuildLibraryImportsCache" because all output files are up-to-date with respect to the input files.
> Target _GenerateLayoutBindings:
>   Skipping target "_GenerateLayoutBindings" because it has no outputs.
> Target _ConvertResourcesCases:
>   Skipping target "_ConvertResourcesCases" because all output files are up-to-date with respect to the input files.
> Target _CompileResources:
>   Skipping target "_CompileResources" because all output files are up-to-date with respect to the input files.
> Target _PrepareUpdateAndroidResgen:
>   Skipping target "_PrepareUpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
> Target _UpdateAndroidResgen:
>   Skipping target "_UpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
> Target GenerateTargetFrameworkMonikerAttribute:
>   Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
> Target CoreCompile:
>   Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
> Target _CopyFilesMarkedCopyLocal:
>     Touching "/Users/maks/Desktop/whadhr/whadhr/obj/Debug/whadhr.csproj.CopyComplete".
> Target CopyFilesToOutputDirectory:
>     whadhr -> /Users/maks/Desktop/whadhr/whadhr/bin/Debug/whadhr.dll
> Target _ResolveAssemblies:
>       Adding assembly reference for whadhr, recursively...
>       Adding assembly reference for Java.Interop, recursively...
>       Adding assembly reference for Mono.Android, recursively...
>         Adding assembly reference for System.Net.Http, recursively...
>         Adding assembly reference for System.Drawing.Common, recursively...
>       Adding assembly reference for mscorlib, recursively...
>       Adding assembly reference for System.Core, recursively...
>       Adding assembly reference for System, recursively...
>         Adding assembly reference for Mono.Security, recursively...
>       Adding assembly reference for System.Numerics, recursively...
>       Adding assembly reference for System.Numerics.Vectors, recursively...
>       Adding assembly reference for System.Runtime, recursively...
>         Adding assembly reference for System.ComponentModel.Composition, recursively...
>       Adding assembly reference for System.Xml, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Activity, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Annotation, recursively...
>       Adding assembly reference for Xamarin.AndroidX.AppCompat.AppCompatResources, recursively...
>       Adding assembly reference for Xamarin.AndroidX.AppCompat, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Arch.Core.Common, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Arch.Core.Runtime, recursively...
>       Adding assembly reference for Xamarin.AndroidX.AsyncLayoutInflater, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Browser, recursively...
>       Adding assembly reference for Xamarin.AndroidX.CardView, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Collection, recursively...
>       Adding assembly reference for Xamarin.AndroidX.CoordinatorLayout, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Core, recursively...
>       Adding assembly reference for Xamarin.AndroidX.CursorAdapter, recursively...
>       Adding assembly reference for Xamarin.AndroidX.CustomView, recursively...
>       Adding assembly reference for Xamarin.AndroidX.DocumentFile, recursively...
>       Adding assembly reference for Xamarin.AndroidX.DrawerLayout, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Fragment, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Interpolator, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Legacy.Support.Core.UI, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Legacy.Support.Core.Utils, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Lifecycle.Common, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Lifecycle.LiveData.Core, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Lifecycle.Runtime, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Lifecycle.ViewModel, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Lifecycle.ViewModelSavedState, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Loader, recursively...
>       Adding assembly reference for Xamarin.AndroidX.LocalBroadcastManager, recursively...
>       Adding assembly reference for Xamarin.AndroidX.MultiDex, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Print, recursively...
>       Adding assembly reference for Xamarin.AndroidX.RecyclerView, recursively...
>       Adding assembly reference for Xamarin.AndroidX.SavedState, recursively...
>       Adding assembly reference for Xamarin.AndroidX.SlidingPaneLayout, recursively...
>       Adding assembly reference for Xamarin.AndroidX.SwipeRefreshLayout, recursively...
>       Adding assembly reference for Xamarin.AndroidX.Transition, recursively...
>       Adding assembly reference for Xamarin.AndroidX.VectorDrawable.Animated, recursively...
>       Adding assembly reference for Xamarin.AndroidX.VectorDrawable, recursively...
>       Adding assembly reference for Xamarin.AndroidX.VersionedParcelable, recursively...
>       Adding assembly reference for Xamarin.AndroidX.ViewPager, recursively...
>       Adding assembly reference for Xamarin.Essentials, recursively...
>       Adding assembly reference for Xamarin.Google.Android.Material, recursively...
>       Adding assembly reference for Xamarin.Google.Guava.ListenableFuture, recursively...
> Target _CopyConfigFiles:
>   Skipping target "_CopyConfigFiles" because it has no inputs.
> Target _ConvertPdbFiles:
>   Skipping target "_ConvertPdbFiles" because it has no outputs.
> Target _LinkAssembliesNoShrink:
>   Skipping target "_LinkAssembliesNoShrink" because all output files are up-to-date with respect to the input files.
> Target _GenerateJavaStubs:
>     Touching "obj/Debug/stamp/_GenerateJavaStubs.stamp".
> Target _ManifestMerger:
>     /Users/maks/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/java -cp /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/manifestmerger.jar com.xamarin.manifestmerger.Main obj/Debug/android/manifestmerger.rsp 
> Target _ConvertCustomView:
>   Skipping target "_ConvertCustomView" because all output files are up-to-date with respect to the input files.
> Target _AddStaticResources:
>   Skipping target "_AddStaticResources" because all output files are up-to-date with respect to the input files.
> Target _GeneratePackageManagerJava:
>   Skipping target "_GeneratePackageManagerJava" because all output files are up-to-date with respect to the input files.
> Target _GenerateAndroidAssetsDir:
>   Skipping target "_GenerateAndroidAssetsDir" because it has no outputs.
> Target _CreateBaseApk:
>     Target _CreateBaseApkWithAapt2:
>         /Users/maks/Desktop/whadhr/whadhr/Properties/AndroidManifest.xml : error APT2263: unexpected element `<provider>` found in `<manifest><queries>`.
>         /Users/maks/Desktop/whadhr/whadhr/Properties/AndroidManifest.xml : error APT2263: 
>         /Users/maks/Desktop/whadhr/whadhr/Properties/AndroidManifest.xml : error APT2263: This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.
>     Done building target "_CreateBaseApkWithAapt2" in project "whadhr.csproj" -- FAILED.
> Done building target "_CreateBaseApk" in project "whadhr.csproj" -- FAILED.
> 
> Done building project "whadhr.csproj" -- FAILED.
> 
> Build FAILED.
> 
> /Users/maks/Desktop/whadhr/whadhr/Properties/AndroidManifest.xml : error APT2263: unexpected element `<provider>` found in `<manifest><queries>`.
> /Users/maks/Desktop/whadhr/whadhr/Properties/AndroidManifest.xml : error APT2263: 
> /Users/maks/Desktop/whadhr/whadhr/Properties/AndroidManifest.xml : error APT2263: This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:01.60
> 
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> 
> Build: 1 error, 0 warnings

**Comment by jonathanpeppers** [comment]
It looks like the version of `aapt2` Xamarin.Android ships by default doesn't support this `//queries/provider` value:

https://developer.android.com/guide/topics/manifest/queries-element

Can you ensure you have Build Tools 30.0.3 installed and set this manually in your `.csproj` file?

```xml
<!-- If you're on Windows -->
<Aapt2ToolPath>C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.3\</Aapt2ToolPath>
<!-- If you're on macOS -->
<Aapt2ToolPath>$HOME/Library/Developer/Xamarin/android-sdk-macosx/build-tools/30.0.3/</Aapt2ToolPath>
```

After doing this in a sample app, it worked for me.

In future releases, I think https://github.com/xamarin/xamarin-android/commit/d5ef9982dc7b9efc22f7efb80ed0b58ff0bd7cdb  will solve the problem here.

**Comment by ololomax** [comment]
Thanks for the workaround, it helped.

**Comment by jonathanpeppers** [comment]
Closing this, as we should have https://github.com/xamarin/xamarin-android/commit/d5ef9982dc7b9efc22f7efb80ed0b58ff0bd7cdb in Xamarin.Android 11.4, VS Windows 16.11, and some future version of VS for Mac.

Let use know if you hit another issue here, thanks.
