### ISSUE TITLE
Cannot create AAB release bundle with binding libraries included

### ISSUE THREAD

**Issue by tamasszadvari** [xamarin/xamarin-android#6006]
### Steps to Reproduce

1. Create a Xamarin.Forms project
2. Create Android Binding library project(s)
3.  Reference the binding libraries in the Xamarin.Android project
4. Set the build output to "aab", with Linking set to "Don't link", and without Multi-Dex.
5. Try to Archive for publishing

The compilation works fine, but the the packaging fails.

### Expected Behavior
VS creates an aab file.

### Actual Behavior
Receiving error message:
`[BT : 1.4.0] error : File 'root/resources.arsc' uses reserved file or directory name 'resources.arsc'.`

### Version Information

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10 (build 1773)
Installation UUID: b8b6bb5f-59da-42cd-8f13-122d8dcbf5df
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-3.21251.8+4c32f5e4e9c0828a94fd4d1c9c0994082c85aaf3

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.203/Sdks
SDK Versions:
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.101
	5.0.100
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.1
	5.0.0
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16

=== .NET Core 3.1 SDK ===

SDK: 3.1.409

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.10.0.117
Hash: 249267d55
Branch: remotes/origin/d16-10
Build date: 2021-05-24 21:27:04 UTC

=== Xamarin.Android ===

Version: 11.3.0.1 (Visual Studio Enterprise)
Commit: xamarin-android/d16-10/22fc2b3
Android SDK: /Users/macbookprogrape/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Library/Java/JavaVirtualMachines/jdk-11.0.10.jdk/Contents/Home
2021-01-19
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-05-13 17:01:38 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-05-13 17:01:56 UTC

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.20.0.1 (Visual Studio Enterprise)
Hash: fe0e2c518
Branch: d16-10
Build date: 2021-05-19 08:15:56-0400

=== Build Information ===

Release ID: 810001773
Git revision: 56d63e5691f86f863cfaed823a5a8fe430e1aaa9
Build date: 2021-05-28 11:21:28-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Fri Mar  5 01:14:14 PST 2021
    root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Feature Switch 0.2
NuGet Package Explorer 0.3.1
MFractor 4.4.8
.NET Core support for Mono.Debugging 8.0.5
XAML Styler 2.0.1
StyleCop Support 1.1.0.4
NuGet Package Management Extensions 0.26

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) of the failure? Does it work at the command-line? It seems like you're using the IDE's archive UI.

Thanks!

**Comment by tamasszadvari** [comment]
Thank you for the quick reply! I was gathering information for you in the meanwhile, that's why I'm answering so late, sorry for that.

I've attached the log which you've requested. (Or I hope so that this is what you've asked for.)

The compilation works all the time, "just" the archiving fails. It fails from command-line too. (First it failed in an Azure DevOps pipeline that I've used so far, and because of that failure, I've started trying to archive locally.)

It seems like that this is the JAR file which causes the failure. If I remove this one from the project, the aab is made without any problem: https://search.maven.org/artifact/com.google.android/android/4.0.1.2/jar

[aab_error.txt](https://github.com/xamarin/xamarin-android/files/6610166/aab_error.txt)

**Comment by jonathanpeppers** [comment]
What are you using this com.google.android `.jar` file for? I'm not sure exactly what it is, but it seems like the entire Android API surface? This should be something we get by default when using `android.jar` from the Android SDK.

It includes a `resources.arsc` file that causes this error. Can you just remove this `.jar`?

**Comment by tamasszadvari** [comment]
We've made a binding library for a native SDK for one of our clients, so I'm not completely sure, that what is this library used for. I'll ask this from our client. What do you think, is it safe to remove this  `.jar` file? At first glance, it seemed that the app works fine without that, but the SDK is so complex that I'm not sure if it won't cause any problem in the future.

**Comment by jonathanpeppers** [comment]
That package says:

> A library jar that provides APIs for Applications written for the Google Android Platform.

It seems like it is some kind of "reference package" for Android. I actually think you _shouldn't_ include it in your app, but please comment if it causes an issue.

**Comment by tamasszadvari** [comment]
Thank you for the help! It seems like that removing that library solved the issue, and everything works fine.
