### ISSUE TITLE
[One .NET] select defaults for App Bundles

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#6059]
August 2021, Android App Bundles will be required for new apps on Google Play:

https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

In .NET 6, we should:

1. Release builds with a blank `$(AndroidPackageFormat)` should default to `aab`.
2. Come up with a new property that generates `.apk` files in addition to `.aab`. Enable this by default for release builds.

For no. 2 to work, we should be able to generate the `.aab` as usual, then add a separate step for generating a "fat" `.apk` file for all architectures. This way apps could submit builds to other stores than Google Play, which might not support App Bundles yet.

**Comment by AmrAlSayed0** [comment]
You could make `<AndroidPackageFormat>aab;apk</AndroidPackageFormat>` work? No need for another property.

**Comment by dellis1972** [comment]
> Could you make `<AndroidPackageFormat>aab;apk</AndroidPackageFormat>` work? No need for another property.

If we followed the same convention as .net 6 it would be `AndroidPackageFormats` . I kinda like this idea. But it would mean IDE changes... mind you either way, this will need IDE changes.

**Comment by dellis1972** [comment]
@joj any thoughts on this from the IDE perspective?

**Comment by dellis1972** [comment]
PR #6087 has this in progress. Changing over completely to `AndroidPackageFormats` would have resulted in a rather large PR. Much of our build system is dependent on targeting a single format. 

So we are going to introduce a new property `AndroidAdditionalPackageFormats`. This should have a value of `apk`. 
And when `AndroidPackageFormat` is set to `aab` and `AndroidAdditionalPackageFormats` set to `apk` we will use 
`bundle-tool` to generate a universal `apk` from the `aab` file.
