### ISSUE TITLE
Add Data Binding support

### ISSUE THREAD

**Issue by zenjia** [xamarin/xamarin-android#6070]
Hi, I just came across a great article which implement a Data-Binding Library for Xamarin.Android.(Seems the library hasn't been maintained)
So I just wonder whether it can be integrated into Xamarin.Android sdk.

Really don't like the way of data binding with MvvmCross or MvvmLight. 
If Xamarin.Android(and Xamarin.iOS, if possible) can implement data binding, it would be great!

**Comment by jpobst** [comment]
We won't be implementing data binding at the Xamarin.Android/iOS level.  These projects are simply focused on providing access to the native features provided by their respective platforms.

Xamarin Forms (MAUI) is Microsoft's platform of "ease-of-use" enhancements built on top of the mobile platforms, and it includes robust data-binding support:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/
