### ISSUE TITLE
Add Android default global usings in MSBuild targets

### ISSUE THREAD

**Issue by mhutch** [xamarin/xamarin-android#6075]
Following the pattern in https://github.com/dotnet/sdk/pull/18459, the Android SDK targets should contain default global usings that can be disabled by an MSBuild property.

**Comment by jonpryor** [comment]
As per https://github.com/xamarin/xamarin-android/pull/6118#issuecomment-886863501, I'm starting to wonder if *anything* should be added to `@(Import)` for Android apps.  It feels like anything we add would be likely to introduce type resolution conflicts for MAUI and BCL types.

**Comment by mhutch** [comment]
@jonpryor if there are type conflicts between system types and android types we can make aliasing choices and emit those too.
