### ISSUE TITLE
RSACertificateExtensions.CopyWithPrivateKey() returns cert with HasPrivateKey false and no private key.

### ISSUE THREAD

**Issue by karnamalone** [xamarin/xamarin-android#6077]
### Steps to Reproduce

This only happens with some key combinations but those in the following example always fail.

```C#
string? exampleCertString = "MIIDajCCAlKgAwIBAgIUM25eHTODbqFB9IprXo5X3FAyy7cwDQYJKoZIhvcNAQELBQAwUzEaMBgGA1UECgwRVGFpdCBVbmlmaWVkIFRlYW0xNTAzBgNVBAMMLHBpbG90LnB0dG94LWFwcC1lZnNpbS5tZWR1c2EuY2VyYmVydXMtZGV2LmNvMCAXDTIxMDcwNzAxNDI0OVoYDzIxMjEwNjEzMDE0MjQ5WjBtMQ0wCwYDVQQKDARUYWl0MRAwDgYDVQQLDAdVbmlmaWVkMUowSAYDVQQDDEFlZTJhOGNiYTRhOWI0ZThmOWMyMDEyODUxODBkODg4Mi5wdHRveC5fYXBwLnVuaWZpZWQudGFpdHJhZGlvLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAI1zoscpLdlLJoZque9qj044WbmjmN/gRa7T3qjtqwd77EPrl2CPVOVNs/LWp+xghxPHZ41Wd2wwQd2mNjGPfRisJdiShv+CNr5QPsAIhlSwpX3O3DVgqr3kX00ZbqXLbkFXVUKPzK56lFY4RUgTC2YvgC/JYLq4II3Vxn7e38q25FXoNUbBfxHt4UeubiXz4Z83WSmXEX0QfthBDMIUhD/I+BtQNoTSPXqKCivjPWaZlxV0GwfEIqyfaTi9fiDdGvIkgQ2H4AWE0LiL5xgHYPUvV7O12n7y7KciVWnC/2Hl6ToGYfOANPkawuz2lriN6MtJvcScNT8Cyrx9JIK2pdsCAwEAAaMaMBgwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQADggEBAAp/PsjwdYeASkqxdpB/LQbyjYlXHhSpwdrhSRCTfjFhYcMKfp+M7AbfSXQjlRmB9V6bSpZwi0cthaAxPF4wMR029Mt0w8oSvCDP9LzQSTi+99faa/5TEtF8ZrAx3N4Lo+lBv9N+ySy+jugQV+uKe//+O1RL33c/CfEAQOk7O4LWTgLzKCsYPlWntxyoFKjpWsYyGBmM56Agmar5bCrGo1DplX5fpXuyT9eQuavDQKmnPAXBqrWAexZEh2deiGhpG4Rhrq43Q0cfG1Hk7bJQcZjjsIW/k4GhI8H51DIpVyY32f1Uvt29f1LEWh6pSbZrS4Pw/xoyAQNi8TooVC9zMWg=";
X509Certificate2 signedCert = new X509Certificate2(Convert.FromBase64String(exampleCertString));
RSA privateKey = RSA.Create();
string? exampleCertKeyXml = "<RSAKeyValue><Modulus>jXOixykt2Usmhmq572qPTjhZuaOY3+BFrtPeqO2rB3vsQ+uXYI9U5U2z8tan7GCHE8dnjVZ3bDBB3aY2MY99GKwl2JKG/4I2vlA+wAiGVLClfc7cNWCqveRfTRlupctuQVdVQo/MrnqUVjhFSBMLZi+AL8lgurggjdXGft7fyrbkVeg1RsF/Ee3hR65uJfPhnzdZKZcRfRB+2EEMwhSEP8j4G1A2hNI9eooKK+M9ZpmXFXQbB8QirJ9pOL1+IN0a8iSBDYfgBYTQuIvnGAdg9S9Xs7XafvLspyJVacL/YeXpOgZh84A0+RrC7PaWuI3oy0m9xJw1PwLKvH0kgral2w==</Modulus><Exponent>AQAB</Exponent><P>wAWssMU1RcmmqTQNsWfZKxpRnt7dWBS2IWjkmPQvePDsagN24RnEe5lcYzZ3DLUZFSEGQrrMkHc0EikEC8pDJKdxLOH94W0sAFQOiF0qnqzQZyveYHEh6HuQg6pasZP137A+62/zPOSKr2N4hHllzdBKbW2XmSeA1OitTAG0kZE=</P><Q>vJSbjWn0TFASD31gu9xqw6vWJymq3dPXuZPGV5rfC0nW19r+ZQIdwUUkrNkHboevjY7MiHm+5qZRUog3yLkJW1k00ryEzRf5NbQHxFFXSgyvXBudmHz9n5s1fohbSMbXQP+VfZOgNL6LPDH9qCKXuIYzWkNRJkeICxyMWZHtyqs=</Q><DP>Jqe9yOQaQk9CzqMc8o6uSCAHOE0zD80zkOw1wJi/icAuR3UlFFGEnUEVOR+4vYUjZH5+bSZ/kcF9aP56wwjXlWRjwx5HZn78saA6QLdIoiK13V8WaCG+KrfdMrQzh7X6dCpdsDWcKLD1PjNvCnQJy3HX2cmLEBjEtZeVc0yQlhE=</DP><DQ>jD6srG+m2nYV6GUi4rNaxyhtPHTVeOGKJp5KvG4WAIwqdh+MX8xCGrD0RIOm7kGEgm83lyuLmHcKNanOar2JwuDF0w+WZ/yzPogj2pFvrEdgxsxW2MfjyqYgE3kPAkG2ZcVuBJUcaP1oCR1Yeok3cmiDmlZD7Ib4GuNhUV+gi78=</DQ><InverseQ>kLmAlJdrm9o5h3ZPbTt9n5upUUPXDTBy3/1jMeb75ty58gaY8Sv81R+0w/kV96BQUwQp6XRPsaIQrFhr8lP8lFf/6nqt3Nyz0fUUpvgVkFmHaNgImqLjv5GXR93tq2OwWUQQUeQ3lVQH3y53pLmEFZeFgcecPDY5Qj/QcRH7eBQ=</InverseQ><D>ABps4W3RfHor7WQCc9Zq6TYpibYMK1JabvtzG1Zzusj0SWQFZlaXfH2S7jfhaDiDp1Lh+eg4zUt1DczQgVdzs+cEgwlshxDjd3cqqyjLQjTJBEpP1MN5X/qj1/1GLK68QinyzWRxL69YlIZSJXqzB+wbVSiD8F1rdj/MHc8b7FF8ddhqsJX0u7H0ND9bfL5r0y9soQ/hSPuWFv5YdmIFpI2UyKuh8hLtrvaT65NynNNTj2kj8ozUdygoSn+QT/Lq0+8EiocizrL3/KTyeArtSeZeobk0tXUoISuJuow48rNw9fWulRgEhMrF/D//Ft/t8K+oRkxj2Nd3i7Mam7Rv4Q==</D></RSAKeyValue>";
privateKey.FromXmlString(exampleCertKeyXml);
X509Certificate2 fullCert = signedCert.CopyWithPrivateKey(privateKey);
```

### Expected Behavior
Returns `X509Certificate2` with `HasPrivateKey` true and cert contains private key.

### Actual Behavior
Returns `X509Certificate2` with `HasPrivateKey` false and cert contains no private key.

### Version Information
<details>
Microsoft Visual Studio Professional 2019
Version 16.9.4
VisualStudio.16.Release/16.9.4+31205.134
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.9.693.2781
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.693.2781
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.9.693.2781
Azure Functions and Web Jobs Tools

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40331.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.273 (d16-9@1bba9e0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.318 (remotes/origin/7b35adcdd1b204bbdcb279e0f029d151a20a4bf3@7b35adcdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.72 (426ebf6)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

**Comment by jpobst** [comment]
I filed this upstream with Mono since that's where it's implemented:
mono/mono#21146

I suspect this may already be fixed for .NET 6 Xamarin Android, as it uses the .NET 6 base class libraries instead of the Mono ones.
