### ISSUE TITLE
BluetoothHeadset.ActionAudioStateChanged has incorrect IntelliSense comment

### ISSUE THREAD

**Issue by gkarabin** [xamarin/xamarin-android#6080]
### Steps to Reproduce

1.  Add a reference to [Android.Bluetooth.BluetoothHeadset.ActionAudioStateChanged](https://docs.microsoft.com/en-us/dotnet/api/android.bluetooth.bluetoothheadset.actionaudiostatechanged?view=xamarin-android-sdk-9) to code.
2. Hover over the symbol in Visual Studio and examine the Intellsense tip which reads "Intent used to broadcast the change in the Audio Connection state of the **_A2DP_** profile.".
3. Compare to the text of the [BluetoothHeadset.ACTION_AUDIO_STATE_CHANGED](https://developer.android.com/reference/android/bluetooth/BluetoothHeadset#ACTION_AUDIO_STATE_CHANGED)

### Expected Behavior

The text of the comment in the tooltip matches the comment for [BluetoothHeadset.ACTION_AUDIO_STATE_CHANGED](https://developer.android.com/reference/android/bluetooth/BluetoothHeadset#ACTION_AUDIO_STATE_CHANGED) which reads "Intent used to broadcast the change in the Audio Connection state of the **_HFP_** profile.".

### Actual Behavior

The text of the comment in the tooltip matches the comment for [BluetoothA2dp.ACTION_CONNECTION_STATE_CHANGED](https://developer.android.com/reference/android/bluetooth/BluetoothA2dp#ACTION_CONNECTION_STATE_CHANGED).

The difference between HFP and A2DP is significant and makes it hard to read code that uses the symbols if you don't remember that there is a bug in the docs.  It also makes it harder to discover the correct API to use when perusing the docs on docs.microsoft.com.

### Version Information

<details>

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.5 (build 16)
Installation UUID: d23dfdcd-8711-4e91-a962-2bdb18b0164a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.301/Sdks
SDK Versions:
	5.0.301
	5.0.203
	5.0.202
	5.0.103
	5.0.102
	3.1.410
	3.1.409
	3.1.408
	3.1.406
	3.1.405
	3.0.103
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-preview.1.21102.12
	5.0.7
	5.0.6
	5.0.5
	5.0.3
	5.0.2
	3.1.16
	3.1.15
	3.1.14
	3.1.12
	3.1.11
	3.0.3

=== .NET Core 3.1 SDK ===

SDK: 3.1.410

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5.1 (18212)
Build 12E507

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Enterprise)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Enterprise)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Enterprise)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/georgekarabin/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.1 (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.2
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/georgekarabin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:34 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:52 UTC

=== Build Information ===

Release ID: 810050016
Git revision: d6bd382154950cedf91ffdf19704a7c61888a3b4
Build date: 2021-07-02 06:38:37-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.5.0 Darwin Kernel Version 20.5.0
    Sat May  8 05:10:33 PDT 2021
    root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

</details>

**Comment by jpobst** [comment]
Our Intellisense docs for `Mono.Android.dll` are automatically generated from the comments on the source code Google ships in the Android SDK.  For the current stable release (`android-30`), this is what Google ships:

```
    /**
     * Intent used to broadcast the change in the Audio Connection state of the
     * A2DP profile.
     *
     * <p>This intent will have 3 extras:
     * <ul>
     * <li> {@link #EXTRA_STATE} - The current state of the profile. </li>
     * <li> {@link #EXTRA_PREVIOUS_STATE}- The previous state of the profile. </li>
     * <li> {@link BluetoothDevice#EXTRA_DEVICE} - The remote device. </li>
     * </ul>
     * <p>{@link #EXTRA_STATE} or {@link #EXTRA_PREVIOUS_STATE} can be any of
     * {@link #STATE_AUDIO_CONNECTED}, {@link #STATE_AUDIO_DISCONNECTED},
     *
     * <p>Requires {@link android.Manifest.permission#BLUETOOTH} permission
     * to receive.
     */
    @SdkConstant(SdkConstantType.BROADCAST_INTENT_ACTION)
    public static final String ACTION_AUDIO_STATE_CHANGED =
            "android.bluetooth.headset.profile.action.AUDIO_STATE_CHANGED";
```

It appears that they have fixed this since `android-30` shipped:

`A2DP` -> `HDP` (Jan 29 2021)
https://android.googlesource.com/platform/frameworks/base/+/633ec9f636f492e8307eb49f227a766589ff55c9%5E%21/core/java/android/bluetooth/BluetoothHeadset.java

`HDP` -> `HFP` (Jan 29 2021)
https://android.googlesource.com/platform/frameworks/base/+/1b9358bfe686eabe75936364c67598a6193d0331%5E%21/core/java/android/bluetooth/BluetoothHeadset.java

When `android-31` (Android 12) ships as stable later this year we will begin pulling from its sources, which should contain this change.
