### ISSUE TITLE
Building Android app fails with "_AndroidXJetifyEmbeddedFiles" target missing error.

### ISSUE THREAD

**Issue by zipgenius** [xamarin/xamarin-android#6095]
### Steps to Reproduce

1.  Create a new android project (no matter what are the settings)
2. Try to compile the application.

### Expected Behavior
Compile should complete successfully.

### Actual Behavior
Compiling fails with the following message:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1166,2): error MSB4057: The target "_AndroidXJetifyEmbeddedFiles" does not exist in the project

### Version Information

Microsoft Visual Studio Community 2019
Versione 16.10.3
VisualStudio.16.Release/16.10.3+31424.327
Microsoft .NET Framework
Versione 4.8.04084

Edizione installata: Community

Visual C++ 2019   00435-60000-00000-AA842
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

Estensione IntelliCode   1.0
Informazioni dettagliate sull'estensione IntelliCode di Visual Studio

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Gestione pacchetti NuGet   5.10.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web https://docs.nuget.org/

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Pacchetto di Microsoft Visual Studio VC   1.0
Pacchetto di Microsoft Visual Studio VC

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

Procedure guidate di Microsoft Visual C++   1.0
Procedure guidate di Microsoft Visual C++

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Strumenti C#   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti comuni di Azure   1.10
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.

Strumenti del Servizio app di Azure versione 3.0.0   16.10.526.50910
Strumenti del Servizio app di Azure versione 3.0.0

Strumenti di Visual Basic   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti TypeScript   16.0.30429.2002
Strumenti TypeScript per Microsoft Visual Studio

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

VisualStudio.DeviceLog   1.0
Informazioni sul pacchetto

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.234 (d16-10@ecaf29b)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Estensione di Visual Studio per abilitare gli strumenti di Xamarin Designer in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File
No log file.

**Comment by jonathanpeppers** [comment]
@zipgenius I'm able to create new projects in VS 16.10.3 and build/run them.

Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) of the issue?

You might also try deleting this folder and running NuGet restore again:

    %userprofile%\.nuget\packages\xamarin.androidx.migration

Maybe something was corrupted on the initial restore?

**Comment by zipgenius** [comment]
> @zipgenius I'm able to create new projects in VS 16.10.3 and build/run them.
> 
> Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) of the issue?
> 
> You might also try deleting this folder and running NuGet restore again:
> 
> ```
> %userprofile%\.nuget\packages\xamarin.androidx.migration
> ```
> 
> Maybe something was corrupted on the initial restore?

Let me try again and I will report about it.

**Comment by zipgenius** [comment]
I can confirm: deleting `%userprofile%\.nuget\packages\xamarin.androidx.migration` has solved the issue. Thanks.
