### ISSUE TITLE
Remove Android.Runtime.UncaughtExceptionHandler

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#6099]
Remove the `Android.Runtime.UncaughtExceptionHandler` type: https://github.com/xamarin/xamarin-android/blob/1b71da0cd3a44861b006ac41c77a24eedf066281/src/Mono.Android/Android.Runtime/UncaughtExceptionHandler.cs

This type appears to be dead code, and was obsoleted (and removed!) by 2aff4e7439.  I think it was inadvertently re-introduced by d471b4a4308310afb8fa3fa1047003a7caedd57f.

**Comment by jpobst** [comment]
I think you may have gotten bit by the "GitHub searches for files on random historical branches instead of `main`" "feature"?

This file does not seem to exist on `main`: https://github.com/xamarin/xamarin-android/tree/main/src/Mono.Android/Android.Runtime.

**Comment by jonpryor** [comment]
Nope, this was fixed in: https://github.com/xamarin/xamarin-android/commit/7af33b6128eb80dde9257f567fe3cdeb18e45a59

I forgot to add the `Fixes: #6099` header to that PR.  Doh!
