### ISSUE TITLE
AudioManager SpeakerPhoneOn not working during call

### ISSUE THREAD

**Issue by alex-gigtribe** [xamarin/xamarin-android#6115]
I have built an app that replaces default dialer.

During a call I have UI allowing the user to turn on the speaker phone.  Using the following code on Android 9 devices works perfectly.

AudioManager audioManager = (AudioManager)Android.App.Application.Context.GetSystemService(Context.AudioService);
audioManager.SpeakerphoneOn = true;

On Android 10 devices it no longer works.  
Permission MODIFY_AUDIO_SETTINGS have been granted.

An oddity, if the audioManager.SpeakerphoneOn = true; is set before the call has been accepted then the speakerphone activates, but then cannot be deactivate during the call.

**Comment by jpobst** [comment]
This appears to be a change in the Android platform, developers calling this method directly from Java/Kotlin seem to be experiencing the same behavior:

https://stackoverflow.com/questions/61284015/android-10-audio-settings-permission-denial-setspeakerphoneon

**Comment by alex-gigtribe** [comment]
> This appears to be a change in the Android platform, developers calling this method directly from Java/Kotlin seem to be experiencing the same behavior:
> 
> https://stackoverflow.com/questions/61284015/android-10-audio-settings-permission-denial-setspeakerphoneon

Thank you, this has solved my issue
