### ISSUE TITLE
Android Tooltip not appearing when handling Touch event

### ISSUE THREAD

**Issue by rubiomiguel06** [xamarin/xamarin-android#6136]
[Tooltips](https://developer.android.com/guide/topics/ui/tooltips) do not appear after **LongPress** when handling the `Touch` event of a `Android.Views.View`. Apparently, not setting the `TouchEventArgs.Handled`  to `false` when handling the `MotionEventActions.Down` does not fire the appearance of the Tooltip.

### Steps to Reproduce

1.  Run the attached sample (modified sample from [xamarin / xamarin-forms-samples](https://github.com/xamarin/xamarin-forms-samples))
2. Click the button **BOXVIEW DRAGGING**
3. Drag the boxview around to confirm the touch events are handled.
4. Try to longpress the boxview in order to get the Tooltip.
5. After not getting it, press the button **REMOVE TOUCH** which will remove the `TouchTrackingEffect`
6. Longpress the boxview to confirm the Tooltip appears.

I can confirm that it works as expected when using a Pen pointer (I tried with the S Pen from Samsung)

[tooltip androd.zip](https://github.com/xamarin/xamarin-android/files/6892939/tooltip.androd.zip)

### Expected Behavior
View should handle touch events and also show a tooltip when long pressing the view (if `LongPress` event is not handled).

### Actual Behavior

View is not showing the tooltip after long pressing it.

### Version Information

<details>
Microsoft Visual Studio Community 2019
Version 16.10.3
VisualStudio.16.Release/16.10.3+31424.327
Microsoft .NET Framework
Version 4.8.04084

Xamarin   16.10.000.234 (d16-10@ecaf29b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

</details>

**Comment by jpobst** [comment]
It looks like for all C# events that we create from Java listeners that contain `Handled`, we default the value to `true`:

```csharp
internal sealed partial class IOnTouchListenerImplementor : global::Java.Lang.Object, IOnTouchListener {
	public bool OnTouch (Android.Views.View? v, Android.Views.MotionEvent? e)
	{
		var __h = Handler;
		if (__h == null)
			return false;
		var __e = new TouchEventArgs (true, e); // <-- HERE
		__h (v, __e);
		return __e.Handled;
	}
}

public partial class TouchEventArgs : global::System.EventArgs {
	public TouchEventArgs (bool handled, Android.Views.MotionEvent? e)
	{
		this.handled = handled;
		this.e = e;
	}
}
```

This means these are considered "handled" if you attach an event handler to them.  Perhaps it may have been better to default to "unhandled" and have users explicitly mark the events as handled.  That likely would have been keeping better conventions with .NET.

Unfortunately it's a moot point now, as it has been this way for many years, and changing it would cause existing user code to break.

If you wish to let the system know you did not handle the event in your handler, you will need to explicitly do that:

```csharp
void OnTouch (object sender, Android.Views.View.TouchEventArgs args) {
  ...
  args.Handled = false;
}
```

`generator` source: https://github.com/xamarin/java.interop/blob/main/tools/generator/SourceWriters/InterfaceEventHandlerImplClass.cs#L127

**Comment by rubiomiguel06** [comment]
I see, thanks for your quick reply @jpobst !

Given this scenario, how would you recommend to handle the `TouchEventArgs` and have at the same time the `Tooltip` working?


The following code is the `TapEffect` I've created to handle taps and hover movements on Android, and this is so far how I manage to handle the tooltip appearing as it supposed to. But I don't think it should be like this, since the `TapEffect` should be agnostic of whether there's a tooltip or not, and also this doesn't work for android versions < SDK 26, where [TooltipCompat](https://developer.android.com/reference/androidx/appcompat/widget/TooltipCompat) is necessary, since it only provides a way of `setting` the tooltip and not for `getting` it.

If you'd like a repo just let me know and I prepare one.

Thanks a lot for your help!

```c#
class AndroidTapEffect : PlatformEffect
{
    Android.Views.View _element;

    private bool _attached;

    public static void Initialize() { }

    public AndroidTapEffect()
    {
    }

    protected override void OnAttached()
    {
        if (!_attached)
        {
            _element = Control ?? Container;

            if (_element != null)
            {
                _element.Touch += Control_Touch;
                _element.Hover += Control_Hover;
            }

            _attached = true;
        }
    }

    private void Control_Hover(object sender, Android.Views.View.HoverEventArgs e)
    {
        e.Handled = HandleAction(e.Event);
    }

    private void Control_Touch(object sender, Android.Views.View.TouchEventArgs e)
    {
        e.Handled = HandleAction(e.Event);
    }

    private bool HandleAction(MotionEvent evt)
    {
        bool handled = true;
        ICommand command = null;
        object parameter = null;
        switch (evt.ActionMasked)
        {
            case MotionEventActions.Up:
            case MotionEventActions.PointerUp:
                if ((evt.EventTime - evt.DownTime) < ViewConfiguration.LongPressTimeout)
                {
                    command = TapEffect.GetUpCommand(Element);
                    parameter = TapEffect.GetUpCommandParameter(Element);
                }
                else
                {
                    command = TapEffect.GetCancelledCommand(Element);
                    parameter = TapEffect.GetCancelledCommandParameter(Element);
                }
                // Without this handled = false, the tooltip doesn't disappear when it should, or appears after a normal click (which is not intended)
                handled = false;
                break;
            case MotionEventActions.Down:
            case MotionEventActions.PointerDown:
                command = TapEffect.GetDownCommand(Element);
                parameter = TapEffect.GetDownCommandParameter(Element);

                // This block is necessary to return handled = false ONLY when a tooltip is configured. 
                // If we return handled = false when a tooltip is not configured, then following related touch events will not be handled anymore (so we will not be able to detect MotionEventActions.Up)
                // https://developer.android.com/training/gestures/detector#:~:text=Beware%20of%20creating,as%20described%20above.
                if ((int)Android.OS.Build.VERSION.SdkInt >= 26)
                    if (!string.IsNullOrEmpty(_element.TooltipText))
                        handled = false;
                //
                break;
            case MotionEventActions.HoverEnter:
                command = TapEffect.GetHoverEnterCommand(Element);
                parameter = TapEffect.GetHoverEnterCommandParameter(Element);
                break;
            case MotionEventActions.HoverExit:
                command = TapEffect.GetHoverExitCommand(Element);
                parameter = TapEffect.GetHoverExitCommandParameter(Element);
                break;
            case MotionEventActions.Cancel:
                command = TapEffect.GetCancelledCommand(Element);
                parameter = TapEffect.GetCancelledCommandParameter(Element);
                break;
        }
        command?.Execute(parameter);
        return handled;
    }

    protected override void OnDetached()
    {
        if (_attached)
        {
            if (_element != null)
            {
                _element.Touch -= Control_Touch;
                _element.Hover -= Control_Hover;
            }
            _attached = false;
        }
    }
}
```

**Comment by jpobst** [comment]
I'm afraid I don't have much insight into how to use the Android APIs to achieve your desired effect.  However if you can find a Java example then it should be the same for C#.

In Java, every time the `onTouch` event is handled, the developer must explicitly return `true` or `false` to indicate whether they consumed the event, so how to handle it properly is something other people have surely hit and documented.

 https://developer.android.com/reference/android/view/View.OnTouchListener#onTouch(android.view.View,%20android.view.MotionEvent)

The only difference with C# is we default it to `true` if you do not explicitly change it.
