### ISSUE TITLE
Xamarin Android Linux Build Failed for 16-10

### ISSUE THREAD

**Issue by Akademiksdc** [xamarin/xamarin-android#6141]
Dear @pjcollins  and @jonpryor could you please fix the build 16-10 for the Linux artifacts. 

https://dev.azure.com/xamarin/public/_build/results?buildId=40065&view=logs&s=47748e8d-4396-5896-11b5-4960e3f92372

**Comment by Akademiksdc** [comment]
Any updates??

**Comment by Akademiksdc** [comment]
Dear @pjcollins could you please take a look, we are using linux artifacts for building our applications and we really need it!

**Comment by pjcollins** [comment]
@Akademiksdc can you take a build from our main branch? I recently moved these over to a new build pool and it will take some effort to cherry-pick this to older branches. Would this build be acceptable? https://dev.azure.com/xamarin/public/_build/results?buildId=43659&view=results

**Comment by Akademiksdc** [comment]
@pjcollins kindly ask you to assist me!

**Comment by pjcollins** [comment]
@Akademiksdc hopefully this works well enough for you, it's d16-10 plus a couple of CI related changes: https://dev.azure.com/xamarin/public/_build/results?buildId=44060&view=artifacts&pathAsName=false&type=publishedArtifacts
