### ISSUE TITLE
HttpClient compression and TLS 1.3

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/xamarin-android#6144]
### Steps to Reproduce

1. Create in XF App a HttpClient with Accept-Encoding gzip Header:
```c#
var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));
```
2. Create Request to an api which return json for example
3. Start App on Android Device
4. Use Fiddler or WireShark and monitor traffic

### Expected Behavior
Request should contain "Accept-Encoding: gzip" header

### Actual Behavior
Request contain" "Accept-Encoding: identity" header

The following code works and the header is added:
```c#
var httpClient = new HttpClient(new HttpClientHandler
{
  AutomaticDecompression = DecompressionMethods.GZip,
});
```
But this code only supports TLS 1.2!!! I think because it's not using the native client. Without HttpClientHandler parameter TLS 1.3 is used.

### Version Information

<details>

</details>

**Comment by grendello** [comment]
@AlleSchonWeg if you're using the "legacy" (current) Xamarin.Android, you will need to use the `AndroidClientHandler` with `HttpClient`, as the "legacy" Mono stack doesn't support TLS 1.3. If you're using NET6 previews and the code doesn't work, then it is likely a bug in dotnet/Mono

**Comment by AlleSchonWeg** [comment]
Hi @grendello ,
In my xf 5 Android project I select Android in the httpclient combobox: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows
So it should use AndroidClientHandler as default. This works with TLS 1.3! But then Accept-Encoding gzip header is ignored.

**Comment by grendello** [comment]
@AlleSchonWeg in the code you shown above, you are overriding the setting by specifying your own client handler. Replace `HttpClientHandler` with `AndroidClientHandler` and see if that works with `gzip` (note, however, that mixing TLS and compression is considered insecure)

**Comment by AlleSchonWeg** [comment]
Hi @grendello,
i think i posted to much context infos. So it's a litte bit confusing ;)
The TLS is not the real problem. It works as it should.
What i want is Gzip Compression with HttpClient. This is my setup:

- HttpClient implementation set to Android (AndroidClientHandler)
![Screenshot 2021-07-30 083938](https://user-images.githubusercontent.com/6727366/127611638-a1ec4652-cfa2-42ba-9d85-e1891c09c8fb.jpg)
- In my Xamarin Forms 5 shared project i use this init code:
```c#
HttpClient client = new HttpClient();
client.DefaultRequestHeaders.UserAgent.TryParseAdd("UserAgent");
client.DefaultRequestHeaders.ExpectContinue = false;
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("text/plain"));
client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip")); //Problem here!!
```
When i send a request with the init code above the following http-headers are sent:

> POST https://xxx/ HTTP/1.1
> Content-Type: application/json; charset=utf-8
> User-Agent: UserAgent
> Accept: application/json,text/plain
> **Accept-Encoding: identity**
> Content-Length: 67
> Host: xxx
> Connection: Keep-Alive

As you see the **Accept-Encoding: identity** is sent. But i set **client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));**
Why is Accept-Encoding set to identity and not gzip? 

------ Addition Infos------
The blog from Jonathan Peppers (http://jonathanpeppers.com/Blog/improving-http-performance-in-xamarin-applications) Section "Use GZIP (or deflate) where possible" say that **client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));** is enough to enable compression in xamarin.

**Comment by grendello** [comment]
@AlleSchonWeg This is a bug in Android's Java  client implementation (which is used by Xamarin.Android's `AndroidClientHandler`), take a look at these links:

 * https://github.com/xamarin/xamarin-android/blob/8733e8a943ea25f9519d783e7f955bb72222b961/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.Legacy.cs#L100-L104
 * https://github.com/xamarin/xamarin-android/blob/8733e8a943ea25f9519d783e7f955bb72222b961/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.Legacy.cs#L550-L563
 * https://github.com/xamarin/xamarin-android/blob/8733e8a943ea25f9519d783e7f955bb72222b961/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.Legacy.cs#L847-L856

**Comment by AlleSchonWeg** [comment]
Hmm,
what could be the fix for this issue:
- Make HttpClientHandler public that AutomaticDecompression can be set
- Check if `DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip, deflate"))` is set by user and handle decompression like above (decompress_here)

**Comment by grendello** [comment]
@AlleSchonWeg The compression **does** work with `AndroidClientHandler` if you look at the code - it's merely handled by us and not by the (broken) Java HTTP client

**Comment by AlleSchonWeg** [comment]
> @AlleSchonWeg The compression **does** work with `AndroidClientHandler` if you look at the code - it's merely handled by us and not by the (broken) Java HTTP client

@grendello It's not working, because with `HttpClient client = new HttpClient();` xamarin forms uses `AndroidClientHandler` but `AutomaticDecompression` is set to `DecompressionMethods.None`. And you have no chance to change it, because fields are private.

**Comment by grendello** [comment]
@AlleSchonWeg Please take a look here https://github.com/xamarin/xamarin-android/blob/8733e8a943ea25f9519d783e7f955bb72222b961/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.Legacy.cs#L31-L39

**Comment by AlleSchonWeg** [comment]
> @AlleSchonWeg Please take a look here
> 
> https://github.com/xamarin/xamarin-android/blob/8733e8a943ea25f9519d783e7f955bb72222b961/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.Legacy.cs#L31-L39

Thanks @grendello . I know that.
But in a shared Xamarin Forms Project i can't use `AndroidClientHandler` directly. To get this work, you need a add xamarin.android assembly in the shared project and do something like this:
```C#
HttpClient client;
if (Device.RuntimePlatform == Device.Android){
//Works only on android
var handler = new AndroidClientHandler { 
   UseCookies = true, 
   AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip, 
 };
client = new HttpClient(handler);
} else {
//Works on iOS. But should work with Android too!
client = new HttpClient();
client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip")); 
}
```
This code should work, but has drawbacks:
- Needs reference to xamarin.android assembly in Xamrin Shared Project
- Needs check for Device.RuntimePlatform

But as i wrote above Jonathan Peppers wrote in his blog: http://jonathanpeppers.com/Blog/improving-http-performance-in-xamarin-applications Section "Use GZIP (or deflate) where possible" that setting `client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));` is enough to use decommpression. But it's only enough for iOS not for Android.

**Comment by grendello** [comment]
@AlleSchonWeg you can't really except platforms in cross-platform applications, that's the reality of life (even the "cross platform" Electron browser-in-a-box apps can't do that). iOS and Android use different implementations of the handlers and they will have different bugs and workarounds. For the reasons pointed out before, the AcceptEncoding workaround won't work (and I don't really want to add more workarounds to workarounds...) with the Android handler. Since Xamarin.Forms [supports](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/dependency-injection) dependency [injection](https://www.xamarinhelp.com/xamarin-forms-dependency-injection/), you could use that to provide an instance of `HttpMessageHandler` to pass to `HttpClient` on construction (it could return `null` to indicate that `HttpClient` should be instantiated without passing it a specific message handler, thus using whatever is the platform default)

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
