### ISSUE TITLE
XA0134 - The application does not have the 'android:debuggable' attribute

### ISSUE THREAD

**Issue by LeBuzzy** [xamarin/xamarin-android#6153]
### Steps to Reproduce

1. In debug mode, i deploy my app on my android emulator.
2. Compilation succeeds but deployment fails with error XA0134.

I tried the steps described in the error description but with no luck.

### Expected Behavior

Deployment succeeds and app starts on the device.

### Actual Behavior

Deployment fails and app does not start on the device.
Note that i had a class which derivated from Application and had the following content :

```csharp
using Android.App;
using Android.Runtime;
using Plugin.CurrentActivity;
using System;

namespace <obfuscated>
{
#if DEBUG

    [Application()]
#else
	[Application()]
#endif
    public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
          : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            CrossCurrentActivity.Current.Init(this);
        }
    }
}
```

My manifest does not contain android:debuggable at all (i tried with and without). The project works on my other machine.

### Version Information

Microsoft Visual Studio Community 2019
Version 16.10.4
VisualStudio.16.Release/16.10.4+31515.178
Microsoft .NET Framework
Version 4.8.04161

Version installée : Community

Visual C++ 2019   00435-60000-00000-AA858
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
Pour plus d'informations, visitez https://www.asp.net/

Assistants Microsoft Visual C++   1.0
Assistants Microsoft Visual C++

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Common Azure Tools   1.10
Fournit des services courants utilisables par Microsoft Azure Mobile Services et Microsoft Azure Tools.

Cookiecutter   16.10.21111.19
Fournit des outils pour rechercher, instancier et personnaliser des modèles au format cookiecutter.

Débogage de .NET Core avec WSL 2   1.0
Débogage de .NET Core avec WSL 2

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Extension IntelliCode   1.0
Informations détaillées sur l'extension Visual Studio IntelliCode

Extensions des outils de conteneur Visual Studio   1.0
Affichez, gérez et diagnostiquez les conteneurs dans Visual Studio.

Fabric.DiagnosticEvents   1.0
Événements de diagnostic Fabric

Gestionnaire de package NuGet   5.10.0
Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, visitez https://docs.nuget.org/

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools pour Visual Studio   16.10
Microsoft Azure Service Fabric Tools pour Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools pour Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools pour Visual Studio   0.4
Simplification de la configuration des pipelines Azure DevOps à partir de l'IDE Visual Studio.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.30310.1 Commit Hash:e550dd1b679956810ccace4368dbc7a64443213b
Ajoute la prise en charge du développement et du débogage d'applications Node.js dans Visual Studio

Outils Azure App Service v3.0.0   16.10.526.50910
Outils Azure App Service v3.0.0

Outils C#   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
Composants C# utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Outils TypeScript   16.0.30429.2002
Outils TypeScript pour Microsoft Visual Studio

Outils Visual Basic   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
Composants Visual Basic utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Package hôte de l'adaptateur de débogage de Visual Studio Code   1.0
Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio

Package Microsoft Visual Studio VC   1.0
Package Microsoft Visual Studio VC

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.10.21111.19
Fournit IntelliSense, des projets, des modèles, le débogage, des fenêtres interactives et du support pour les développeurs Python.

Python - Prise en charge Django   16.10.21111.19
Fournit des modèles et une intégration pour le framework web Django.

Python - Prise en charge du profilage   16.10.21111.19
Prise en charge du profilage pour les projets Python.

Python - Prise en charge de Conda   16.10.21111.19
Prise en charge de Conda pour les projets Python.

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Tools pour Conteneurs   1.0
Visual Studio Tools pour Conteneurs

Visual Studio Tools pour Docker   1.2
Développez, exécutez et validez vos applications ASP.NET Core dans l'environnement cible. Appuyez sur F5 pour exécuter votre application directement dans un conteneur avec débogage ou sur CTRL+F5 pour modifier et actualiser votre application sans avoir à recréer le conteneur.

Visual Studio Tools pour Kubernetes   1.0
Visual Studio Tools pour Kubernetes

VisualStudio.DeviceLog   1.0
Informations sur mon paquet

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.234 (d16-10@ecaf29b)
Extension Visual Studio permettant de développer pour Xamarin.iOS et Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Extension Visual Studio pour activer les outils Xamarin Designer dans Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File
<empty>

**Comment by dellis1972** [comment]
What are your settings for `DebugSymbols`, `DebugType`, `EmbedAssembliesIntoApk` and `Optimize` in your csproj for your debug configuration?

**Comment by LeBuzzy** [comment]
`DebugSymbols` : `true`
`DebugType` : `Full`
`EmbedAssembliesIntoApk` : `false`
`Optimize` : `False`

**Comment by dellis1972** [comment]
Hmm, the attribute should be ending up on the Manifest in `obj/Debug/android/AndroidManifest.xml`. 
I wonder if your custom application is causing the issue.

try changing the code to 
```
#if DEBUG
    [Application(Debuggable=true)]
#else
	[Application()]
#endif
```

It might be that the custom application class is overriding our normal build settings and forcing it to be false.

**Comment by dellis1972** [comment]
Another thing to check is that you don't have the app installed under multiple user/guest accounts. That can sometimes cause problems with the fast deployment system.

**Comment by LeBuzzy** [comment]
I tried your code but it also failed with the `XA0134`error.

In fact, i'm trying to run it on a brand new workstation from a Gitlab repo (i also tried with copied files from my previous pc).
I'm using the same account on the two computers. I'm using a brand new instance of an emulator installed yesterday.

Last thing, my current workstation is running on Windows 11, i don't think it can be an issue but..well..just saying.

**Comment by dellis1972** [comment]
ok so time to get some logs.

Can you try the following from a `Developer Command Prompt` and a clean build.

```
msbuild <your.csproj> /restore /t:Install /bl
```

Then zip up the `msbuild.binlog` file and attach it to this issue. 
We can then take a look at the logs and see what is going on. Something it overriding the `debuggable` attribute value (or removing it).

**Comment by dellis1972** [comment]
btw, back out my code change before running the above command please :)

**Comment by LeBuzzy** [comment]
Okay here's the file :
[msbuildlog.zip](https://github.com/xamarin/xamarin-android/files/6907587/msbuildlog.zip)

**Comment by dellis1972** [comment]
Ok, nothing stands out in that build log all the arguments are as expected. 

So the next thing to check is if any of the dependencies have `android:debuggable="false"`. Do a find in files in the following directory `obj\Debug\90\lp` and search for `debuggable`. See if any of the libraries you are using have it set. It's not the first time that has happened, generally libraries should not be setting any `application` attributes in their manifests.
If there is a library which is causing this , then we need to figure out which one it is so we can raise an issue.  But we will cover that if that turns out to be the case.

Also can you zip and post the contents of  `obj\Debug\90\android\AndroidManifest.xml`.
I'm curious to see if the attribute is missing entirely or set to `false`.

**Comment by LeBuzzy** [comment]
[AndroidManifest.zip](https://github.com/xamarin/xamarin-android/files/6907833/AndroidManifest.zip)
I didn't find any "debuggable" in any file.

**Comment by dellis1972** [comment]
Ah, you have two application elements.

```
  <application android:name="androidx.multidex.MultiDexApplication">
```

and 

```
<application android:name="crc64baa1aeef6d56a918.MainApplication" android:allowBackup="true" android:appComponentFactory="androidx.core.app.CoreComponentFactory" android:debuggable="true" android:extractNativeLibs="true" android:icon="@drawable/orcab96" android:label="@string/app_name" android:supportsRtl="true" android:theme="@style/Theme.App.Contrast.Launcher">
```

Not sure how you've managed to get two. It might be because you are trying to use `androidx.multidex.MultiDexApplication` but also have a custom app which does not derive from `androidx.multidex.MultiDexApplication`.

**Comment by LeBuzzy** [comment]
So, i tried something. I removed all of the **application** tag of the manifest. And..well..it's deploying now.
Working manifest : 
[AndroidManifest.zip](https://github.com/xamarin/xamarin-android/files/6907879/AndroidManifest.zip)

**Comment by LeBuzzy** [comment]
Finally, i re-inserted my first **application** and discarded the second. My app is deploying fine now. Thanks for your time.

**Comment by dellis1972** [comment]
No problem :) Glad its working again :D
