### ISSUE TITLE
Android debugger showing variables wrongly (.Net6)

### ISSUE THREAD

**Issue by arivoir** [xamarin/xamarin-android#6161]
Android debugger is showing incorrect values, either by hovering the variables in code or using "Add watch" or "Quick watch"

As it can be seen in the below video, the "fontFamily" variable is showing true, as if it were a boolean variable, and the "typeface" variable is showing a string that has the value of the "fontFamily" variable. Similarly textStyle shows the value of the "a" variable.

![android debugger bug](https://user-images.githubusercontent.com/17496741/127874130-1c8aa1c5-1ab2-4845-b2ec-cf4e83f97f3d.gif)

**Comment by arivoir** [comment]
The parameters of the method look fine, when the code enters in the _GetTypefaceFromAttrs_ method, I can see the parameters correctly. The bug is with the local variables in the method body

**Comment by grendello** [comment]
@arivoir Could you please provide full Xamarin.Android, dotnet and IDE version information? Thanks!

**Comment by arivoir** [comment]
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.11.0 Preview 3.0
VisualStudio.16.Preview/16.11.0-pre.3.0+31507.150
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA363
Microsoft Visual C++ 2019

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   16.11.72.17133
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.72.17133
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.72.17133
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.72.17133
Azure Functions and Web Jobs Tools

C# Tools   3.11.0-3.21351.9+49a655e40d938aa74b1d149b407c30cbb2287d71
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ComponentOne IntelliSpell   4.7.20203.457
ComponentOne IntelliSpell

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62107.02200
Microsoft SQL Server Data Tools

SVG Viewer   1.0.14
Makes it much easier to work with SVG files by showing a live preview in the bottom-right corner of the code window

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-3.21351.9+49a655e40d938aa74b1d149b407c30cbb2287d71
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21322.6+488cc578cafcd261d90d748d8aaa7b8b091232dc
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.169 (d16-11@9499c2a)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.0.5 (d16-11/7776c9f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@48766c0
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@683f375


Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by thaystg** [comment]
Could you paste here the method body that you are seeing the issue? I'm trying to reproduce and could not in a method like this:
```
private void OnButtonClicked(object sender, EventArgs e)
{
	List<int> a = new List<int>() { 1, 2, 3, 4 };
	count++;
	StaticMethod3();
	CounterLabel.Text = $"You clicked {count} times Thays!";
}
```

**Comment by arivoir** [comment]
I can't share my project, but I can tell you it happens everywhere, also the debugger hangs and need to restart visual studio, apart from the fact that the deploy doesn't work fine in the emulator and need to uninstall the application every time it is compiled. It's complicated. I hope next preview comes with something usable.

**Comment by arivoir** [comment]
I see this problem everywhere. Right now I'm seeing it in a synchronous method without parameters.

**Comment by arivoir** [comment]
@thaystg can you run an empty project without issues?

**Comment by thaystg** [comment]
Which type of project are you trying to create? Is a MAUI App?

**Comment by mattleibow** [comment]
This issue I think has maybe mixed 2 issues. 

1. After updating things, I see android gets this error: `The path is not of a legal form.`  
   This happens with plain android apps AND maui apps

2. https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1366070/

**Comment by arivoir** [comment]
@thaystg all these issues are in native Android projects (former Xamarin.Android)

**Comment by arivoir** [comment]
@mattleibow I can confirm I've updated vs previews one after the other and also have Visual Studio 2022 installed.

**Comment by mattleibow** [comment]
OK. The bad debug values are a known issue, but the path dialog is brand new for me. I just got it this week as we are trying to figure it out.

For the bad values, I found that I could help "reset" them by declaring 2 variables. It happens after a jump in the code, like a condition or loop:

```csharp
var view = GetView() // view is correct
if (view != null)
{                    // view is the result of the if
    var v2 = view    // view is still bad
    var v3 = view    // view is now correct again
}
```

For the popup, we don't know yet and it is very strange because the maui repo with 50 project does not have an issue, but a very simple `dotnet new android` does.

I am running the very latest internal vs, and I get it too. So it might be the .NET SDK or workload versions.

What version of .NET do you have? `dotnet --info` and also what is the version in the manifest for android:
C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.android\WorkloadManifest.json

**Comment by arivoir** [comment]
I have net6 preview 7 now, but all these issues were in reported in preview6. I haven't played much with it these days
