### ISSUE TITLE
Kotlin .AAR to Xamarin App - Given component holder class android.support.multidex.MultiDexApplication does not implement interface dagger.hilt.internal.GeneratedComponent

### ISSUE THREAD

**Issue by Engincode** [xamarin/xamarin-android#6163]
Hi, i'm creating Xamarin DLL from "**Kotlin AAR**" or "Kotlin Libraries".

Then AAR to **DLL Converted Successfully.**

There are dagger and hilt libraries (aar/jar) to DLL Converted Successfully.

- dagger-2.37.jar
- hilt-core-2.37.jar
- hilt-android-2.37.aar
- dagger-lint-aar-2.37.aar

**On Xamarin.Android App Side**
- Added Kotliin DLL
- Added Dagger/Hilt Library DLL
- Added from nuget package manager.
- Enabled MultiDexApplication

During testing, create an instance "Kotlin Class (With Converted DLL)", then Xamarin.Android app throws an exception.

Exception Message Java.Lang.IllegalStateException: Given component holder class android.support.multidex.MultiDexApplication does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager.
**![117777-g9f5c](https://user-images.githubusercontent.com/12773298/128022033-e958e8dc-7700-4d35-8653-52a539b6338f.png)** 
**Please help to me.
What it this message?
How to solve?**

**Comment by jpobst** [comment]
Are you using AndroidSupportLibraries or AndroidX?

One of your exceptions references `android.support.multidex.MultiDexApplication`, the other references `androidx.multidex.MultiDexApplication`?  If you are using the automatic AndroidX migration support, you might want to complete the manual AndroidX transition to see if it fixes it (and dramatically speed up your build times!).

Aside from that, it's hard to tell anything without seeing how things are set up.  Can you provide a sample project that demonstrates the error?

**Comment by Engincode** [comment]
Yes AndroidX is used. 
It gives this error via **dagger.hilt.**
What do you think about this subject?
I can share the project.

**Comment by jpobst** [comment]
I think you need to set your application name to `com.greenmile.engine.GMEngineApplication`: 

```
<application android:allowBackup="true"
        android:name="com.greenmile.engine.GMEngineApplication" .....
```

Your `GMEngine.Companion.GetInstance("validator1-eu-test", this)` is expecting an application context (`this`) that implements `dagger.hilt.internal.GeneratedComponentManagerHolder` like `com.greenmile.engine.GMEngineApplication`.

`androidx.multidex.MultiDexApplication` does not implement `dagger.hilt.internal.GeneratedComponentManagerHolder`.

**Comment by Engincode** [comment]
Thank you so much.
You saved my days.
android:name="com.greenmile.engine.GMEngineApplication"
It worked this way.

**So is this solution correct?**
Should the team that created the "Kotlin .aar"' library make any changes?
**Should there be changes on the Kotlin side?**
Same library works in "Java" project without manifest.xml change. 
**Why is that in Xamarin?**

**Comment by Engincode** [comment]
We had to change the android:name of the app to use the library.
This solution has been bad for us.
What should we do?
What do you suggest?

**Comment by jpobst** [comment]
I'm not sure you have much choice.  Your library basically does this:

```java
public GMEngine getEngine (Application application)
{
  var app = (GeneratedComponentManagerHolder)application;
}
```

`com.greenmile.engine.GMEngineApplication` implements `dagger.hilt.internal.GeneratedComponentManagerHolder`:

```java
public abstract class Hilt_GMEngineApplication extends Application implements GeneratedComponentManagerHolder
{
  ...
}
```

but `androidx.multidex.MultiDexApplication` does not:

```java
public class MultiDexApplication extends Application {
  ...
}
```

Thus it is essentially throwing an `InvalidCastException`.

If you want to be able to use an `Application` that does not implement `GeneratedComponentManagerHolder` you will need to change your library to not require that.

**Comment by Engincode** [comment]
Thanks. We are trying..

**Comment by Engincode** [comment]
This was the solution in the Empty Xamarin project.
But this solution didn't work in our company's Xamarin project.

'**Given component holder class crc645c4c9795d8f50a97.SuperTroykaApplication** does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager'

We use customized application class named SuperTroykaApplication.cs.

What is your suggestion?

**Comment by jpobst** [comment]
I think your application class will need to inherit from `GMEngineApplication` or `Hilt_GMEngineApplication`:

```csharp
public class SupraTroykaApplication : GMEngineApplication
{
 ...
}
```

**Comment by Engincode** [comment]
There is no such a class name "**GMEngineApplication**" or "**Hilt_GMEngineApplication**" on Greenmile Library.
What is your suggestion?

**Comment by gui2960** [comment]
Could you explain a little more about:
"If you want to be able to use an Application that does not implement GeneratedComponentManagerHolder you will need to change your library to not require that."?

**Comment by Engincode** [comment]
@jpobst  Please help to me.
I try this 

     [Application(Debuggable = true**, Name = "com.greenmile.engine.GMEngineApplication"**)]
      #else
     [Application(Debuggable = false**, Name = "com.greenmile.engine.GMEngineApplication"**))]
     #endif
     public class SuperTroykaApplication :  Application
     {
     }
 

**There was a compile error.**
**error MSB6006: "java.exe" exited with code 1.**

**Detail**
3>  Error in obj\Debug\90\android\bin\classes.zip:com/greenmile/engine/GMEngineApplication.class:
3>  **Type com.greenmile.engine.GMEngineApplication is defined multiple times**: obj\Debug\90\android\bin\classes.zip:com/greenmile/engine/GMEngineApplication.class, obj\Debug\90\lp\3\jl\bin\classes.jar:com/greenmile/engine/GMEngineApplication.class

Please help to me..

**Comment by Engincode** [comment]
@jpobst We are waiting for a response from you?
I can share the screen with you. 
We can look at the company project online together.
Can we set an online meeting?

**Comment by jpobst** [comment]
My understanding of Hilt is that when you build your Java application (via Gradle), it takes your Application class:

```java
public class GMEngineApplication extends Application { ... }
```

and it dynamically creates and injects itself into a different Application class in the background that gets used:

```java
public final class GMEngineApplication extends Hilt_GMEngineApplication { ... }
public abstract class Hilt_GMEngineApplication extends Application implements GeneratedComponentManagerHolder { ... }
```

The issue is that Xamarin does not use Gradle to build your application, thus Hilt's custom injection code never runs, and it never creates the "hidden" `Application` class from your custom `Application`.

If you must use Hilt, then I think you will need to create an `Application` class in Java that you want to use, compile it to a `.jar`, bind it, and then inherit it from C#.

There should already be `GMEngineApplication` that you can use:

```csharp
public class MyApplication : Com.Greenmile.Engine.GMEngineApplication { ... }
```

Or if you want a custom Application based on `androidx.multidex.MultiDexApplication`, you will need to make it in Java:

```java
public class MyJavaApplication extends androidx.multidex.MultiDexApplication { ... }
```

You will need to reference Hilt in your Java project, and compile it to a `.jar`, then bind it as a Xamarin binding project.

Then you can use it to create your application:

```csharp
public class MyApplication : MyJavaApplication { ... }
```

**Comment by Engincode** [comment]
Thanks for replies.
Com.Greenmile.Engine.GMEngineApplication  doesn't exists Xamarin side.
![test_result_23_08_2021_1](https://user-images.githubusercontent.com/12773298/130475746-959a7d1c-201e-4359-bfc0-d506bdaa7877.png)

**Comment by jpobst** [comment]
We have some pretty good documentation for helping you fix missing binding types:

- https://github.com/xamarin/java.interop/wiki/Troubleshooting-Android-Bindings-Issues
- https://github.com/xamarin/java.interop/wiki/Missing-Types-or-Members

**Comment by Engincode** [comment]
@jpobst  Can you help?
Class is not created.

**Comment by jpobst** [comment]
Where did you get stuck in your investigation?

**Comment by Engincode** [comment]
The Kotlin library is of type .aar.
Embedded Resource: Works with LibraryPorjectZip.
Here, the GMEngineApplication class is not generated.
Your said it can't be generated on the Xamarin side because it uses Hilt.

In this case, those who prepared the Kotlin library should find a solution with java.
