### ISSUE TITLE
Best way to enable Mono logging in .NET 6?

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#6165]
In .NET 6, to get log messages about AOT, I had to make an `@(AndroidEnvironment)` file with:
```
debug.mono.debug=1
debug.mono.log=default,timing=bare,assembly,aot,mono_log_level=debug,mono_log_mask=aot
MONO_LOG_LEVEL=debug
MONO_LOG_MASK=aot
```

@lambdageek had a similar situation, and needed to use this to diagnose an issue with "hot reload":
```
debug.mono.debug=1
debug.mono.log=default,timing=bare,assembly,aot,mono_log_level=debug,mono_log_mask=all
MONO_LOG_LEVEL=debug
MONO_LOG_MASK=all
```

I feel like extra parameters are needed in .NET 6 that weren't needed in legacy?

Is there something we should do to make this easier? Maybe we need to document something at the least?

**Comment by grendello** [comment]
With `mono_log_level=debug,mono_log_mask=all` you don't need

```
MONO_LOG_LEVEL=debug
MONO_LOG_MASK=all
```

As the `debug.mono.log` options set the above environment variables.

`debug.mono.debug` merely causes the `.pdb` or `.mdb` files to be loaded, it doesn't affect logging at all. Doing

```shell
adb shell setprop debug.mono.log mono_log_level=<LEVEL>,mono_log_mask=<MASK>
```
Should be all that's needed. We could add separate properties for `mono_log_*` setting, but that wouldn't change much IMO.

The reason we reduced the default Mono log level in 6e58ce405d00a965f3c206e2d509f5a5343b16f7 is that we had complaints that XA/mono are too noisy. I agree we should document the Xamarin.Android properties, and perhaps we could add a way to enable "verbose" logging by adding a boolean MSBuild property so that the build adds appropriate settings to the environment file (which we always generate anyway)?

**Comment by jonathanpeppers** [comment]
Ok, so I thought there was a difference between legacy and .NET 6, but it's actually just the changes in https://github.com/xamarin/xamarin-android/commit/6e58ce405d00a965f3c206e2d509f5a5343b16f7.

So in theory you could just do:

```
adb shell setprop debug.mono.log mono_log_level=debug,mono_log_mask=all
```

And not have an `@(AndroidEnvironment)` file at all? I'll give this a test sometime.

**Comment by lambdageek** [comment]
@jonathanpeppers I verified that just
```
debug.mono.log=mono_log_level=debug,mono_log_mask=metadata-update
```

is enough for me to see the log messages that I expected.

But there's some problem with dirty builds.

if I had one build where I had the above settings, and then I change it to `mono_log_mask=asm`, for example, and *also* make some code changes in a `.xaml.cs` file, then clean and build (from VS) I _still_ get the messages as if `mono_log_mask=metadata-update` was set.  not the new ones.

**Comment by grendello** [comment]
@lambdageek it might be a build caching issue

Keep in mind that setting the **Android** property (and that's what `debug.mono.log` is) with `adb shell setprop` will override the `@(AndroidEnvironment)` value of the same property (or, rather, the one set with `adb shell setprop` will take precedence) - the properties set in the environment file (everything in that file starting with lower case is treated as a property and everything starting with an upper case is an environment variable) are handled internally by us, we do **not** "forward" them to Android. It's also worth remembering that properties set with `adb shell setprop` are global and they will affect all the applications started on the device.

**Comment by grendello** [comment]
> Ok, so I thought there was a difference between legacy and .NET 6, but it's actually just the changes in [6e58ce4](https://github.com/xamarin/xamarin-android/commit/6e58ce405d00a965f3c206e2d509f5a5343b16f7).
> 
> So in theory you could just do:
> 
> ```
> adb shell setprop debug.mono.log mono_log_level=debug,mono_log_mask=all
> ```
> 
> And not have an `@(AndroidEnvironment)` file at all? I'll give this a test sometime.

Yep, that's all you should need.

**Comment by jonathanpeppers** [comment]
I found that `adb shell setprop` seems to work for this.

However, it overrides the `@(AndroidEnvironment)` file unless I clear it by doing:

```
> adb shell
$ setprop debug.mono.log ""
$ exit
```

With Windows & Powershell, I couldn't figure out if there is a way to run `adb shell setprop debug.mono.log ""` in one step.

Changing the `@(AndroidEnvironment)` file also seemed to work for me, but I had to use command-line due to an IDE issue.

I think I'll just document the commands, and we can close this.

**Comment by grendello** [comment]
> I found that `adb shell setprop` seems to work for this.
> 
> However, it overrides the `@(AndroidEnvironment)` file unless I clear it by doing:

That's correct. The reason is that we **first** read the value of a requested property from the system and only then from the application's environment, on account of the former being more easily manipulated once the app is already installed.

> 
> ```
> > adb shell
> $ setprop debug.mono.log ""
> $ exit
> ```
> 
> With Windows & Powershell, I couldn't figure out if there is a way to run `adb shell setprop debug.mono.log ""` in one step.
> 

Yeah, it's an old problem with `setprop`. You can try this instead:

```shell
$ adb shell setprop debug.mono.log "''"
```

> Changing the `@(AndroidEnvironment)` file also seemed to work for me, but I had to use command-line due to an IDE issue.
> 
> I think I'll just document the commands, and we can close this.

**Comment by jonathanpeppers** [comment]
`adb shell setprop debug.mono.log "''"` works on Windows, too. I updated the doc for this.
