### ISSUE TITLE
Failed resolution of: Lkotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by Engincode** [xamarin/xamarin-android#6172]
I am using Kotlin library in Xamarin.Android project.

The following libraries are included in Xamarin.

  - Xamarin.Kotlin.StdLib.1.5.21
  - Xamarin.Kotlin.StdLib.Common.1.5.21
  - Xamarin.Jetbrains.Annotations.13.0.0.4
 
Target SDK: 10.0
Xamarin.Forms: 5.0.0.2083
 
It still throws the error **"'Failed resolution of: Lkotlin/jvm/internal/Intrinsics;'".**
An empty Xamarin Android project does not have this error.
But there is an error in the Xamarin.Android project that our **company uses**.

Why is there this error even though the latest Kotlin libraries have been added?
**How is it resolved?**

**Comment by Engincode** [comment]
Xamarin.Kotlin.Stdlib.dll from Microsoft was already included.
Additionally, by converting "kotlin-stdlib-1.5.21.jar" to Dll with Xamarin Binding Library and adding it to the project, the error was fixed.
It was a bad solution.
But it worked.
There are now 2 Kotlin.Stdlib libraries in the project.

**Comment by radixdev** [comment]
I have the exact same issue

**Comment by radixdev** [comment]
@Engincode can you elaborate on your solution

**Comment by Engincode** [comment]
I downloaded the kotlin-stdlib-1.5.21.jar file from the link https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.5.21.

I converted it to dll with Xamarin Binding Library.

It got fixed after adding dll to the project.
dll file is attached.

**Comment by radixdev** [comment]
@Engincode Was that kotlin jar added as an `EmbeddedJar`? And if so, how did you get around all of the binding errors?

And thank you so much for responding.

**Comment by radixdev** [comment]
@Engincode nevermind on the above. I actually might have an answer for YOU instead.

See https://github.com/xamarin/xamarin-android/issues/6201

You might need to manually edit your `csproj` and add:

```
  <Import Project="..\packages\Xamarin.Kotlin.StdLib.1.5.21\buildTransitive\monoandroid9.0\Xamarin.Kotlin.StdLib.targets" Condition="Exists('..\packages\Xamarin.Kotlin.StdLib.1.5.21\buildTransitive\monoandroid9.0\Xamarin.Kotlin.StdLib.targets')" />
  <Import Project="..\packages\Xamarin.Kotlin.StdLib.Common.1.5.21\buildTransitive\monoandroid9.0\Xamarin.Kotlin.StdLib.Common.targets" Condition="Exists('..\packages\Xamarin.Kotlin.StdLib.Common.1.5.21\buildTransitive\monoandroid9.0\Xamarin.Kotlin.StdLib.Common.targets')" />
```

**Comment by Engincode** [comment]
@radixdev thanks for shared.
As I see this is a xamarin bug. 
But we are fixed finally.
See you bro.

**Comment by jpobst** [comment]
We think this is because the Kotlin package needs the `.targets` file in the `build` folder when building with `packages.config`.  So another way to fix this would be to migrate to `<PackageReference>` instead of `packages.config`.

https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

We'll look into updating the package(s) to work with `packages.config` by default as well.

**Comment by radixdev** [comment]
@jpobst is that migration not available for Visual Studio for Mac? Everything for it seems to be Windows based only.

**Comment by jpobst** [comment]
The latest Kotlin packages should work with `packages.config` now.

**Comment by hirandesai** [comment]
Even in 2022, migrating to Project Reference fixed for me. It seems, this is dependent on VS version?
