### ISSUE TITLE
How long will VS2019 16.11 get support?

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/xamarin-android#6179]
Now that [VS2019 got the last feature update to version 16.11](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#support-timeframe), how does this impact Xamarin.Android?

> As explained in more detail in our lifecycle and support policy, version 16.11 will be supported with fixes and security updates through April 2029

The [16.11 branch was updated 2 months ago](https://github.com/xamarin/xamarin-android/compare/d16-11...main) and now everything is in main which will go to VS2022. 

Will the 16.11 branch get fixes backported that fix non NET6 related issues?

**Comment by jonpryor** [comment]
The [Xamarin support policy](https://dotnet.microsoft.com/platform/support/policy/xamarin) supersedes the Visual Studio support policy.  While the Xamarin support policy hasn't been updated recently, the "primary thrust" is unchanged:

> Current releases are supported for the following timeframe:
> * Two years after initial release
> * Or until a newer subsequent Current release

Once Visual Studio 17 is stable, the Xamarin.Android shipped as part of Visual Studio 17 will become the "newer subsequent Current release", and Visual Studio 16.11 will no longer be supported.

The only fixes that d16-11 will get, like d16-10 before it, are "critical" fixes.  These are expected to be rare, and will *not* include all fixes on main that are unrelated to net6.

**Comment by MagicAndre1981** [comment]
ok, I see d16-11 got some fixes, this is nice to see. 

Will it also get the `AndroidPackageFormats` support fix to build apk and aab?
