### ISSUE TITLE
I have a new Samsung Galaxy S20 FE that I want to deploy my app on, but I'm getting a Debuggable error

### ISSUE THREAD

**Issue by VizMAP** [xamarin/xamarin-android#6192]
The error is:
Error XA0134: The application does not have the 'android:debuggable' attribute set in the AndroidManifest.xml.
This is required in order for Fast Deployment to work. This is normally enabled by default by the Xamarin.Android build system for Debug builds. Please check that you to not have this attribute set on the 'application' element in your 'AndroidManifest.xml'.
If you have a class that derives from 'Android.App.Application' and are using the '[Application]' make sure the 'Debuggable' property is not set at all as it will override the value for debug builds.

It is not clear how this can be overcome.
I have tried including "android:debuggable" within the application element within the Manifest (which the error says NOT to do, I know). The error persisted.
I have tried including the following in the AssemblyInfo.cs:

     #if DEBUG
     [Application(Debuggable = true)]
     #else
     [Application(Debuggable = false)]
     #endif

The error persisted.
As I mentioned, it is not clear how to fix this and answers to similar questions are years old.

I get exactly the same error using the Android Emulator Pixel 2 Pie 9.0 - API 28 (Android 9.0 - API 28).
I get a slightly different error using my physical Motorola Nexus 6 (Android 7.1 - API 25):
Severity Code Description Project File Line Suppression State
Error XA0137: The 'run-as' command failed with 'run-as: Package 'net.grime.apps.handsfreenotes' is not debuggable
'.
Fast Deployment is not currently supported on this device.
Please file an issue with the exact error message using the 'Help->Send Feedback->Report a Problem' menu item in Visual Studio or 'Help->Report a Problem' in Visual Studio for Mac.
Please set the 'EmbedAssembliesIntoApk' MSBuild property to 'true' to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor. 0

To be clear, I obtained the Galaxy to do physical Android testing because the Nexus 6 was getting old.

VS2019 is running as Debug, not Release.

**Comment by dellis1972** [comment]
This seems related to https://github.com/xamarin/xamarin-android/issues/6153. 
If you are using a custom `Application` derived class check do don't end up with duplicate `application` elements in your final AndroidManifest.xml . See https://github.com/xamarin/xamarin-android/issues/6153#issuecomment-889898514

**Comment by VizMAP** [comment]
@dellis1972 
You are correct in that I had duplicate application elements. I deleted those I had added and the app now deploys to the Galaxy. Thankyou.

**Comment by VizMAP** [comment]
Thankyou. I did add a couple of other application elements. I deleted them
and itnow deploys.

Ciao,
Graeme
GRAEME BROOKE
VizMAP <http://www.vizmap.com.au> ~ Grime <http://www.grime.net>
Batphone: +61 (0)4 1965 9866 ~ Skype Phone: +61 (0)7 3040 2228
------------------------------
