### ISSUE TITLE
SDK Binding projects shouldn't have Resource.designer.cs

### ISSUE THREAD

**Issue by jpobst** [xamarin/xamarin-android#6198]
Using: 6.0.100-preview.7.21379.14

In Legacy binding projects, a `Resource.designer.cs` file is not created and no `Resource` class is added to the assembly.  In .NET 6, `Resource.designer.cs` is created and a `Resource` class is added, even if it's "empty".

I assume this class is not needed as we've never had it before.

This is causing a few issues for AndroidX/GPS:
* The `Resource` class is generated in the default namespace, which is the assembly name, which isn't actually used elsewhere and conflicts with a type name.  eg: `Xamarin.AndroidX.LiveData.Resource` and `Xamarin.AndroidX.LiveData` types.
* The GPS default namespaces are actually invalid, since they are based on the `aar` name, resulting in types like `com.google.android.gms.play-services-basement.Resource`.

While these issues are ultimately fixable, it feels like we don't intend to add the `Resource` class for binding projects.  (Maybe `$(OutputType) = 'Library'`?)

Repro projects:
[Legacy.zip](https://github.com/xamarin/xamarin-android/files/7008165/Legacy.zip)
[NET6.zip](https://github.com/xamarin/xamarin-android/files/7008166/NET6.zip)

Note the projects won't fully build because I didn't do the metadata or dependencies for them, but they get to the `csc` step, which means the `Resource.designer.cs` has been generated already.

**Comment by jonathanpeppers** [comment]
.NET 6 doesn't have binding projects any more, so that seems like it's causing the issue here.

Do we need an MSBuild property force `Resource.designer.cs` to be disabled?

@dellis1972 I was thinking this might check if `@(AndroidResource)` is empty, and skip it:

https://github.com/xamarin/xamarin-android/blob/e811ecb5b7a6288b382a4b393e86db58e7a95e7d/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1217-L1219

But is there some case where a NuGet package, `.jar`, `.aar`, etc. might put values in `Resource.designer.cs`?

**Comment by dellis1972** [comment]
We might need to check both `@(AndroidResource)` and `@(AndroidAarLibrary)` or '@(AndroidLibrary)' where `Bind = true`.

**Comment by jonathanpeppers** [comment]
So in the `NET6.zip` above, the `Resource.designer.cs` has values inside. It has an `.aar` file with resources.

I found I could delete this line:

https://github.com/xamarin/xamarin-android/blob/10335e600d7153c85b4e3ec7a7c1e10b12dba732/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L10

Then also pass `-p:AndroidUseIntermediateDesignerFile=false` to prevent any `Resource.designer.cs` from being created.

Do we still need a new property here, or does this make sense to put in a `.csproj` to stop generating `Resource.designer.cs`?
```xml
<AndroidUseIntermediateDesignerFile>false</AndroidUseIntermediateDesignerFile>
```

Do we also need a `$(AndroidGenerateResourceDesigner)`?
