### ISSUE TITLE
Kotlin NoClassDefFoundError

### ISSUE THREAD

**Issue by radixdev** [xamarin/xamarin-android#6201]
### Error Message or Issue
I'm following https://docs.microsoft.com/en-us/xamarin/android/platform/binding-kotlin-library/walkthrough to the letter and included `Xamarin.Kotlin.StdLib` for my project. The project itself can be found [here](https://github.com/Appboy/appboy-xamarin-bindings/tree/master/appboy-component/src). Whenever I try to run the project, I get the following error.

"Java.Lang.NoClassDefFoundError" for kotlin.collections.sets.

![image](https://user-images.githubusercontent.com/2373546/129982197-992d7e52-bcd3-4768-b040-74547b0a9dbe.png)

### Version Information

<details>

=== Visual Studio Community 2019 for Mac ===

Version 8.10.7 (build 17)
Installation UUID: 1929dbfc-c9c6-4199-8cd6-c44dd86e563f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.400/Sdks
SDK Versions:
	5.0.400
	3.1.412
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.9
	3.1.18

=== .NET Core 3.1 SDK ===

SDK: 3.1.412

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

A valid Xcode installation was not found at the configured location: '/Library/Developer/CommandLineTools'

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/juliancontreras/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/juliancontreras/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:48:52 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:49:10 UTC

=== Build Information ===

Release ID: 810070017
Git revision: 503b9b053dff2e7f136e96b362a629c199f78a42
Build date: 2021-08-05 12:48:29-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Tue Jun 22 19:49:55 PDT 2021
    root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64

</details>

### Log File

diagnostic logs: 

https://gist.github.com/radixdev/ac96fd46fafe84474f16f3524e5e7e7b
### Other Helpful Info

(note that these are only zips due to Github not allowing AAR file uploads)

[android-sdk-ui-15.0.2.zip](https://github.com/xamarin/xamarin-android/files/7010662/android-sdk-ui-15.0.2.zip)
[android-sdk-base-15.0.2.zip](https://github.com/xamarin/xamarin-android/files/7010664/android-sdk-base-15.0.2.zip)

The actual kotlin code that is causing the first crash:
```
package com.braze

import android.app.Activity
import android.app.Application.ActivityLifecycleCallbacks
import android.os.Bundle
import com.braze.BrazeActivityLifecycleCallbackListener
import com.braze.push.NotificationTrampolineActivity
import com.braze.support.BrazeLogger
import com.braze.ui.inappmessage.BrazeInAppMessageManager

/**
 * Can be used to automatically handle Braze lifecycle methods.
 * Optionally, openSession() and closeSession() are called on onActivityStarted and onActivityStopped respectively.
 * The InAppMessageManager methods of registerInAppMessageManager() and unregisterInAppMessageManager() can
 * be optionally called here as well.
 * Note: This callback should not be set in any [.android.app.Activity]. It must be set in the [.android.app.Application] class
 * of your app.
 */
open class BrazeActivityLifecycleCallbackListener @JvmOverloads constructor(private val mSessionHandlingEnabled: Boolean = true,
                                                                            private val mRegisterInAppMessageManager: Boolean = true,
                                                                            inAppMessagingRegistrationBlocklist: Set<Class<*>?>? = emptySet<Class<*>>(),
                                                                            sessionHandlingBlocklist: Set<Class<*>?>? = emptySet<Class<*>>()) : ActivityLifecycleCallbacks {
  private var mInAppMessagingRegistrationBlocklist: Set<Class<*>?>
  private var mSessionHandlingBlocklist: Set<Class<*>?>

  /**
   * Constructor that sets a blocklist for session handling and [BrazeInAppMessageManager] registration while also enabling both features.
   *
   * @param inAppMessagingRegistrationBlocklist A set of [Activity]s for which in-app message
   * registration will not occur. Each class should be retrieved via [Activity.getClass].
   * @param sessionHandlingBlocklist            A set of [Activity]s for which session handling
   * will not occur. Each class should be retrieved via [Activity.getClass].
   */
  constructor(inAppMessagingRegistrationBlocklist: Set<Class<*>?>?, sessionHandlingBlocklist: Set<Class<*>?>?) : this(true, true, inAppMessagingRegistrationBlocklist, sessionHandlingBlocklist) {}

  /**
   * Constructor that only sets a blocklist for [BrazeInAppMessageManager] registration and enables
   * [BrazeInAppMessageManager] registration. Session handling is enabled and has an empty blocklist.
   *
   * @param inAppMessagingRegistrationBlocklist A set of [Activity]s for which in-app message
   * registration will not occur. Each class should be retrieved via [Activity.getClass].
   * If null, an empty set is used instead.
   */
  constructor(inAppMessagingRegistrationBlocklist: Set<Class<*>?>?) : this(true, true, inAppMessagingRegistrationBlocklist, emptySet<Class<*>>()) {}

  @Deprecated("Please use {@link #setInAppMessagingRegistrationBlocklist(Set)}")
  fun setInAppMessagingRegistrationBlacklist(blocklist: Set<Class<*>?>) {
    setInAppMessagingRegistrationBlocklist(blocklist)
  }

  /**
   * Sets the [Activity.getClass] blocklist for which in-app message registration will not occur.
   */
  fun setInAppMessagingRegistrationBlocklist(blocklist: Set<Class<*>?>) {
    BrazeLogger.v(TAG, "setInAppMessagingRegistrationBlocklist called with blocklist: $blocklist")
    mInAppMessagingRegistrationBlocklist = blocklist
  }

  @Deprecated("Please use {@link #setSessionHandlingBlocklist(Set)}")
  fun setSessionHandlingBlacklist(blocklist: Set<Class<*>?>) {
    setSessionHandlingBlocklist(blocklist)
  }

  /**
   * Sets the [Activity.getClass] blocklist for which session handling will not occur.
   */
  fun setSessionHandlingBlocklist(blocklist: Set<Class<*>?>) {
    BrazeLogger.v(TAG, "setSessionHandlingBlocklist called with blocklist: $blocklist")
    mSessionHandlingBlocklist = blocklist
  }

  override fun onActivityStarted(activity: Activity) {
    if (mSessionHandlingEnabled && shouldHandleLifecycleMethodsInActivity(activity, true)) {
      BrazeLogger.v(TAG, "Automatically calling lifecycle method: openSession for class: " + activity.javaClass)
      Braze.getInstance(activity.applicationContext).openSession(activity)
    }
  }

  override fun onActivityStopped(activity: Activity) {
    if (mSessionHandlingEnabled && shouldHandleLifecycleMethodsInActivity(activity, true)) {
      BrazeLogger.v(TAG, "Automatically calling lifecycle method: closeSession for class: " + activity.javaClass)
      Braze.getInstance(activity.applicationContext).closeSession(activity)
    }
  }

  override fun onActivityResumed(activity: Activity) {
    if (mRegisterInAppMessageManager && shouldHandleLifecycleMethodsInActivity(activity, false)) {
      BrazeLogger.v(TAG, "Automatically calling lifecycle method: registerInAppMessageManager for class: " + activity.javaClass)
      BrazeInAppMessageManager.getInstance().registerInAppMessageManager(activity)
    }
  }

  override fun onActivityPaused(activity: Activity) {
    if (mRegisterInAppMessageManager && shouldHandleLifecycleMethodsInActivity(activity, false)) {
      BrazeLogger.v(TAG, "Automatically calling lifecycle method: unregisterInAppMessageManager for class: " + activity.javaClass)
      BrazeInAppMessageManager.getInstance().unregisterInAppMessageManager(activity)
    }
  }

  override fun onActivityCreated(activity: Activity, bundle: Bundle?) {
    if (mRegisterInAppMessageManager && shouldHandleLifecycleMethodsInActivity(activity, false)) {
      BrazeLogger.v(TAG, "Automatically calling lifecycle method: ensureSubscribedToInAppMessageEvents for class: " + activity.javaClass)
      BrazeInAppMessageManager.getInstance().ensureSubscribedToInAppMessageEvents(activity.applicationContext)
    }
  }

  override fun onActivitySaveInstanceState(activity: Activity, bundle: Bundle) {}
  override fun onActivityDestroyed(activity: Activity) {}

  /**
   * Determines if this [Activity] should be ignored for the purposes of session tracking or in-app message registration.
   */
  private fun shouldHandleLifecycleMethodsInActivity(activity: Activity, forSessionHandling: Boolean): Boolean {
    val activityClass: Class<out Activity> = activity.javaClass
    if (activityClass == NotificationTrampolineActivity::class.java) {
      BrazeLogger.v(TAG, "Skipping all automatic registration of notification trampoline activity class")
      // Always ignore
      return false
    }
    return if (forSessionHandling) {
      !mSessionHandlingBlocklist.contains(activityClass)
    } else {
      !mInAppMessagingRegistrationBlocklist.contains(activityClass)
    }
  }

  companion object {
    private val TAG = BrazeLogger.getBrazeLogTag(BrazeActivityLifecycleCallbackListener::class.java)
  }
  /**
   * @param mSessionHandlingEnabled              When true, handles calling openSession and closeSession in onActivityStarted
   * and onActivityStopped respectively.
   * @param mRegisterInAppMessageManager         When true, registers and unregisters the [BrazeInAppMessageManager] in
   * [Application.ActivityLifecycleCallbacks.onActivityResumed]
   * and [Application.ActivityLifecycleCallbacks.onActivityPaused] respectively.
   * @param inAppMessagingRegistrationBlocklist A set of [Activity]s for which in-app message
   * registration will not occur. Each class should be retrieved via [Activity.getClass].
   * If null, an empty set is used instead.
   * @param sessionHandlingBlocklist            A set of [Activity]s for which session handling
   * will not occur. Each class should be retrieved via [Activity.getClass].
   * If null, an empty set is used instead.
   */
  /**
   * A default constructor equivalent to calling BrazeActivityLifecycleCallbackListener(true, true, Collections.<Class>emptySet(), Collections.<Class>emptySet())
  </Class></Class> */
  /**
   * @param sessionHandlingEnabled      When true, handles calling openSession and closeSession in
   * [Application.ActivityLifecycleCallbacks.onActivityStarted] (Activity)}
   * and [Application.ActivityLifecycleCallbacks.onActivityStopped] (Activity)} respectively.
   * @param registerInAppMessageManager When true, registers and unregisters the InAppMessageManager in
   * [Application.ActivityLifecycleCallbacks.onActivityResumed]
   * and [Application.ActivityLifecycleCallbacks.onActivityPaused] respectively.
   */
  init {
    mInAppMessagingRegistrationBlocklist = inAppMessagingRegistrationBlocklist ?: emptySet<Class<*>>()
    mSessionHandlingBlocklist = sessionHandlingBlocklist ?: emptySet<Class<*>>()
    BrazeLogger.v(TAG, "BrazeActivityLifecycleCallbackListener using in-app messaging blocklist: $mInAppMessagingRegistrationBlocklist")
    BrazeLogger.v(TAG, "BrazeActivityLifecycleCallbackListener using session handling blocklist: $mSessionHandlingBlocklist")
  }
}

```

**Comment by jpobst** [comment]
Are you referencing the `Xamarin.Kotlin.StdLib` package in your application?

I don't see any errors in your build log for the bindings, and looking at the `.jar` included in `Xamarin.Kotlin.StdLib` shows that it contains the `SetsKt` type:

![image](https://user-images.githubusercontent.com/179295/129985200-a0de49be-366f-49a3-a1dc-f6cf39d48082.png)

So it looks like the bindings are fine, and it's an issue with the Kotlin code making it into the app.  The two possibilities I can think of are:
- The `Xamarin.Kotlin.StdLib` NuGet is not being referenced by the app.
- Maybe Proguard is removing the Kotlin code? You could investigate Proguard rules to tell it to keep `kotlin*` stuff.

**Comment by radixdev** [comment]
The app itself is definitely referencing the kotlin lib. The two Java binding libraries and the sample app themselves reference the kotlin standard lib in xamarin.

Is proguard running in the debug configuration? These crashes were happening on debug. Where would I include proguard in a xamarin application? 

Thanks for the fast reply!

**Comment by jpobst** [comment]
Here's some info on Proguard: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows

It doesn't look like it should be running in Debug mode.

I would double check your application build log to ensure that the Kotlin stdlib is indeed being put into the apk.

**Comment by radixdev** [comment]
For "ensure that the Kotlin stdlib is indeed being put into the apk." is there anything in particular in looking for?

**Comment by radixdev** [comment]
@jpobst ,

You got me down the right rabbit hole!

I had indeed added the stdlib but I later looked at my `.csproj` to confirm. Every other working dependency had

```
  <Import Project="..\packages\Xamarin.AndroidX.WebKit.1.4.0.2\build\monoandroid90\Xamarin.AndroidX.WebKit.targets" Condition="Exists('..\packages\Xamarin.AndroidX.WebKit.1.4.0.2\build\monoandroid90\Xamarin.AndroidX.WebKit.targets')" />
```

with the exception of the kotlin dependencies. I had to add these manually and it works!

```
  <Import Project="..\packages\Xamarin.Kotlin.StdLib.1.5.21\buildTransitive\monoandroid9.0\Xamarin.Kotlin.StdLib.targets" Condition="Exists('..\packages\Xamarin.Kotlin.StdLib.1.5.21\buildTransitive\monoandroid9.0\Xamarin.Kotlin.StdLib.targets')" />
  <Import Project="..\packages\Xamarin.Kotlin.StdLib.Common.1.5.21\buildTransitive\monoandroid9.0\Xamarin.Kotlin.StdLib.Common.targets" Condition="Exists('..\packages\Xamarin.Kotlin.StdLib.Common.1.5.21\buildTransitive\monoandroid9.0\Xamarin.Kotlin.StdLib.Common.targets')" />
```

![image](https://user-images.githubusercontent.com/2373546/129992502-c7f836db-fd90-4c54-bed5-ffcd3fae9e00.png)

The folder for kotlin is called `buildTransitive` yet all of the other (working automatically) dependencies just had `build`. Maybe this was why Visual Studio wasn't adding them correctly.

**Comment by jpobst** [comment]
We think this is because the Kotlin package needs the `.targets` file in the `build` folder when building with `packages.config`.  So another way to fix this would be to migrate to `<PackageReference>` instead of `packages.config`.

https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

We'll look into updating the package(s) to work with `packages.config` by default as well.
