### ISSUE TITLE
CleverTap Android Bindings Issue: mono.android.runtime.JavaObject cannot be cast to java.util.HashMap

### ISSUE THREAD

**Issue by darshanclevertap** [xamarin/xamarin-android#6203]
### Error Message or Issue
mono.android.runtime.JavaObject cannot be cast to java.util.HashMap

### Version Information

<details>
=== Visual Studio Community 2019 for Mac ===

Version 8.6.2 (build 6)
Installation UUID: d93cfeba-83b1-42f2-a5f9-b6e913fd4a9b
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.300/Sdks
SDK Version: 3.1.300
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.4
	2.1.18

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

A valid Xcode installation was not found at the configured location: '/Applications/Xcode.app'

=== Xamarin.Mac ===

Version: 6.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:04-0400

=== Xamarin.iOS ===

Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2021-08-18 06:33:36 UTC

=== Xamarin.Android ===

Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/darshan/Library/Android/sdk
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home
1.8.0_231
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2021-08-18 06:34:42 UTC

=== Android Device Manager ===

Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2021-08-18 06:34:40 UTC

=== Build Information ===

Release ID: 806020006
Git revision: c742dc3fcbf76855738eef57ce41d65f91acbf27
Build date: 2020-05-28 15:22:51-04
Build branch: release-8.6
Xamarin extensions: c742dc3fcbf76855738eef57ce41d65f91acbf27

=== Operating System ===

Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

</details>

### Other Helpful Info

I could not attach the CleverTap Android SDK AAR file, but [here is a link to it](https://github.com/CleverTap/clevertap-android-sdk/releases/download/core-v4.0.0/clevertap-android-sdk-4.0.0.aar)

The `pushChargedEvent` method after creating the bindings file expects an `IDictionary<string, Java.Lang.Object> chargedDetails` and an `IList<IDictionary<string, Java.Lang.Object>> items`

Providing the items in the correct data type causes the following exception on the Android side

```mono.android.runtime.JavaObject cannot be cast to java.util.HashMap```

The workaround is mentioned in the [documentation](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#javalangclasscastexception-monoandroidruntimejavaobject-cannot-be-cast-to) but only for development done for Xamarin Android apps and not Xamarin Android Bindings.

It also says this will be [fixed in the future over here](https://bugzilla.xamarin.com/54/5401/bug.html)

**Comment by jpobst** [comment]
What does your code that is calling this API look like?  Did you apply the workaround listed in your link?

**Comment by darshanclevertap** [comment]
The Xamarin App uses the `PushChargedEvent` method like this -

```
            //Record Charged
            IDictionary<string, Java.Lang.Object> chargedDetails = new Dictionary<string, Java.Lang.Object>();
            chargedDetails.Add("Total Amount", 400);

            IDictionary<string, Java.Lang.Object> item1 = new Dictionary<string, Java.Lang.Object>();
            //HashMap item1 = new HashMap();
            item1.Add("Product Name", "Harry Potter");
            item1.Add("ProductID", "4756");
            item1.Add("Price", 300);

            IDictionary<string, Java.Lang.Object> item2 = new Dictionary<string, Java.Lang.Object>();
            //HashMap item2 = new HashMap();
            item2.Add("Product Name", "Harry Potter 2");
            item2.Add("ProductID", "4776");
            item2.Add("Price", 100);

            IList<IDictionary<string, Java.Lang.Object>> items = new List<IDictionary<string, Java.Lang.Object>>();
            items.Add(item1);
            items.Add(item2);
    
            cleverTapAPI.PushChargedEvent(chargedDetails,items);
```
Since the workaround is supposed to be made in the CleverTap Bindings DLL file, I don't know how I can implement it?

**Comment by jpobst** [comment]
I'm not sure what you mean that "the workaround is supposed to be made in the CleverTap Bindings DLL file".  You should be able to make the changes to your calling code for it to work.

If you are wanting to make the change in the binding DLL, you can use the `Additions` feature to add any arbitrary C# code to it that you want.  (See the `AboutAdditions.txt` file in the `Additions` folder of your project.)

You could make an additional C# function in the `CleverTapAPI ` class that does the correct marshalling to call the original method:

```csharp
namespace Com.Clevertap.Android.Sdk {
    public partial class CleverTapAPI {
        public void PushChargedEventFixed (IDictionary<string, Java.Lang.Object> chargeDetails, IList<IDictionary<string, Java.Lang.Object>> items)
        {
           // Modify the parameters to be JavaList/JavaDictionary
           ...
           // Pass the new parameters to the existing method
           PushChargedEvent (newChargeDetails, newItems);
        }
    }
}
```

**Comment by darshanclevertap** [comment]
> I'm not sure what you mean that "the workaround is supposed to be made in the CleverTap Bindings DLL file". 

So there is a `pushChargedEvent` method in the AAR file, which gets converted to the `PushChargedEvent` method in the bindings DLL file. 

Now `pushChargedEvent` in the AAR expects an `ArrayList` of `HashMaps`, but when the DLL file is generated from the AAR, the `PushChargedEvent` in C# expects an `IList` of `IDictionary<string, Java.Lang.Object>`.

When I pass an `IList<IDictionary<string, Java.Lang.Object>>` to the `PushChargedEvent` method, on the Android side it doesn't get converted to an `ArrayList` of `HashMaps`. The issue is why doesn't Xamarin handle the conversion of `IList<IDictionary<string, Java.Lang.Object>>` to an `ArrayList` of `HashMaps` directly?

Or after conversion of an AAR to a DLL file, the `PushChargedEvent` method should ideally require `JavaList` of `JavaDictionary` instead of an `IList` of `IDictionary`. Why doesn't Xamarin convert it in this way?

Also regarding your suggestion of writing a new method, see the below comment in the code snippet -

```c#
namespace Com.Clevertap.Android.Sdk {
    public partial class CleverTapAPI {
        public void PushChargedEventFixed (IDictionary<string, Java.Lang.Object> chargeDetails, IList<IDictionary<string, Java.Lang.Object>> items)
        {
           // Modify the parameters to be JavaList/JavaDictionary
           ...
           // Pass the new parameters to the existing method
           PushChargedEvent (newChargeDetails, newItems);
           // This will not work because PushChargedEvent expects newItems to be IList<IDictionary<string, Java.Lang.Object>>
           // and not a JavaList of JavaDictionary on the C# side.
        }
    }
}
```

I hope you get my issue here, please feel free to correct me if I'm wrong at any instance.

**Comment by jpobst** [comment]
`JavaList` implements `IList` ([docs](https://docs.microsoft.com/en-us/dotnet/api/android.runtime.javalist?view=xamarin-android-sdk-9)), and `JavaDictionary<K, V>` implements `IDictionary` ([docs](https://docs.microsoft.com/en-us/dotnet/api/android.runtime.javadictionary-2?view=xamarin-android-sdk-9)), so you can pass them into a method that requires `IList`/`IDictionary`.
