### ISSUE TITLE
Missing release notes for xamarin android 11.4.0.5 in visual studio 16.11.1

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#6226]
Visual studio 16.11.1 was published recently.
Could you please publish release notes for xamarin android 11.4.0.5 ?

Similar issues:
- https://github.com/xamarin/xamarin-android/issues/5961
- https://github.com/xamarin/xamarin-android/issues/5498

**Comment by jonpryor** [comment]
Still missing 11.4.0.5, but we do have 12.0.0.3, *also* released as part of VS 16.11: https://docs.microsoft.com/en-us/xamarin/android/release-notes/12/12.0
