### ISSUE TITLE
The call is ambiguous between the following methods or properties but there is only one property not two with the same name

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-android#6249]
I'm trying to bind this library:

https://github.com/FANMixco/chip-navigation-bar

That is technically this one (I just upgraded the libs in my repo because I was not able to compile it in the latest version of Android Studio and couldn't download the AAR normally):

https://github.com/ismaeldivita/chip-navigation-bar

I'm getting an error about **ambiguous methods** but I cannot find any duplicated event in the repo:

![screencapture-github-ismaeldivita-chip-navigation-bar-search-2021-08-31-16_04_46](https://user-images.githubusercontent.com/1666156/131518532-9bed3cab-3291-4356-81d6-443bbb54b9eb.jpg)

I attached the project and maybe you could give me a hint of what I'm doing wrong. Thanks for your support.

### Error Message or Issue

> The call is ambiguous between the following methods or properties: iChipNavigationBar.SetOnItemSelectedListener(ChipNavigati onBar.lOnitemSelectedListener)' and 'ChipNavigationBar.SetOnitemSelectedListener(IFunctionl)' CS0121) 

### Version Information

> Visual Studio Community 2019 for Mac
> Version 8.10.8 (build 0)
> Installation UUID: 7c243ae0-5088-439b-b16f-28ef4c408829
> 	GTK+ 2.24.23 (Raleigh theme)
> 	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
> 
> 	Package version: 612000140
> 
> Mono Framework MDK
> Runtime:
> 	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
> 	Package version: 612000140
> 
> Roslyn (Language Service)
> 3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
> 
> NuGet
> Version: 5.9.0.7134
> 
> .NET Core SDK
> SDK: /usr/local/share/dotnet/sdk/5.0.400/Sdks
> SDK Versions:
> 	5.0.400
> 	5.0.302
> 	5.0.301
> 	5.0.203
> 	5.0.202
> 	5.0.103
> 	5.0.102
> 	5.0.101
> 	5.0.100
> 	3.1.412
> 	3.1.411
> 	3.1.410
> 	3.1.409
> 	3.1.408
> 	3.1.406
> 	3.1.405
> 	3.1.404
> 	3.1.403
> 	3.1.402
> 	2.1.810
> 	2.1.701
> MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks
> 
> .NET Core Runtime
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	5.0.9
> 	5.0.8
> 	5.0.7
> 	5.0.6
> 	5.0.5
> 	5.0.3
> 	5.0.2
> 	5.0.1
> 	5.0.0
> 	3.1.18
> 	3.1.17
> 	3.1.16
> 	3.1.15
> 	3.1.14
> 	3.1.12
> 	3.1.11
> 	3.1.10
> 	3.1.9
> 	3.1.8
> 	3.1.2
> 	2.1.22
> 
> .NET Core 3.1 SDK
> SDK: 3.1.412
> 
> Xamarin.Profiler
> Version: 1.6.12.29
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> Updater
> Version: 11
> 
> Apple Developer Tools
> Xcode 12.5.1 (18212)
> Build 12E507
> 
> Xamarin.Mac
> Version: 7.14.0.24 (Visual Studio Community)
> Hash: c4b89cddb
> Branch: d16-10
> Build date: 2021-06-15 22:03:00-0400
> 
> Xamarin.iOS
> Version: 14.20.0.24 (Visual Studio Community)
> Hash: c4b89cddb
> Branch: d16-10
> Build date: 2021-06-15 22:03:01-0400
> 
> Xamarin Designer
> Version: 16.10.0.119
> Hash: 36a2d986f
> Branch: remotes/origin/d16-10
> Build date: 2021-06-02 19:41:34 UTC
> 
> Xamarin.Android
> Version: 11.3.0.4 (Visual Studio Community)
> Commit: xamarin-android/d16-10/ae14caf
> Android SDK: /Users/fanmixco/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		None installed
> 
> SDK Tools Version: 26.1.1
> SDK Platform Tools Version: 31.0.3
> SDK Build Tools Version: 30.0.2
> 
> Build Information: 
> Mono: b4a3858
> Java.Interop: xamarin/java.interop/d16-10@f39db25
> ProGuard: Guardsquare/proguard/v7.0.1@912d149
> SQLite: xamarin/sqlite/3.35.4@85460d3
> Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0
> 
> Microsoft OpenJDK for Mobile
> Java SDK: /Users/fanmixco/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
> 1.8.0-25
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> Android SDK Manager
> Version: 16.10.0.13
> Hash: 1b81df5
> Branch: remotes/origin/d16-10
> Build date: 2021-08-12 20:43:52 UTC
> 
> Android Device Manager
> Version: 16.10.0.15
> Hash: 89dcc0b
> Branch: remotes/origin/d16-10
> Build date: 2021-08-12 20:44:10 UTC
> 
> Build Information
> Release ID: 810080000
> Git revision: 0bc91c25997e4c374dc6eb96809c7bf52f6a7c33
> Build date: 2021-08-18 14:50:30-04
> Build branch: release-8.10
> 
> Operating System
> Mac OS X 10.16.0
> Darwin 20.6.0 Darwin Kernel Version 20.6.0
>     Wed Jun 23 00:26:31 PDT 2021
>     root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
> 

### Project:

[Xamarin-ChipNavigationBar.zip](https://github.com/xamarin/xamarin-android/files/7084547/Xamarin-ChipNavigationBar.zip)

**Comment by jpobst** [comment]
Looks like the infrastructure generated is trying to set it the listener to `null` in the event removal, so it can't choose between the 2 overloads:
```csharp
public event EventHandler<global::Com.Ismaeldivita.Chipnavigation.ChipNavigationBar.ItemSelectedEventArgs> ItemSelected {
	add { ... }
	remove {		global::Java.Interop.EventHelper.RemoveEventHandler<global::Com.Ismaeldivita.Chipnavigation.ChipNavigationBar.IOnItemSelectedListener, global::Com.Ismaeldivita.Chipnavigation.ChipNavigationBar.IOnItemSelectedListenerImplementor>(
		ref weak_implementor_SetOnItemSelectedListener,
		global::Com.Ismaeldivita.Chipnavigation.ChipNavigationBar.IOnItemSelectedListenerImplementor.__IsEmpty,
		__v => SetOnItemSelectedListener (null),  // <----
		__h => __h.Handler -= value);
	}
}
```

The best solution is probably to remove the `IFunction1` overload and just keep the `ChipNavigationBar.lOnItemSelectedListener` overload using metadata:

```xml
  <remove-node path="/api/package[@name='com.ismaeldivita.chipnavigation']/class[@name='ChipNavigationBar']/method[@name='setOnItemSelectedListener' and count(parameter)=1 and parameter[1][@type='kotlin.jvm.functions.Function1&lt;? super java.lang.Integer, kotlin.Unit&gt;']]" />
```
