### ISSUE TITLE
Facing RequestLayout() and Performance issue while using virtualization concept in Xamarin.Android

### ISSUE THREAD

**Issue by Muniappan612** [xamarin/xamarin-android#6255]
### Steps to Reproduce

Issue 1: Performance issue 
1. Run the sample 
2. scroll the view to down and up
3. You can see that the green bar in the Graph is high the On layout and OnMeasure is graph line will be a hike
Issue 2: RequestLayout issue in the output window
![Screen Shot 2021-09-01 at 5 40 13 PM](https://user-images.githubusercontent.com/46158936/131669145-d5a1dcc8-450b-45a0-ae77-fce23a26cda2.png)

Inspect performance by using the **Profile GPU Rendering** - https://developer.android.com/topic/performance/rendering/inspect-gpu-rendering

Sample:
[Performance.zip](https://github.com/xamarin/xamarin-android/files/7090868/Performance.zip)

Video: 
[Video.mov.zip](https://github.com/xamarin/xamarin-android/files/7090925/Video.mov.zip)

### Expected Behavior
In this sample, we have rendered the text view based on the virtualization concept. we have updated the scroll panel children while scroll view is scrolled by using the OnScrollChanged event. Because of this, we are facing a performance issue and RequestLayout issue in the output window.
### Actual Behavior
The Graph should be rendered below the green line and the request layout error should not come in the outPut window.

### Version Information

<details>

</details>

**Comment by jpobst** [comment]
Android has libraries to help fix this performance issue.  The concept is called "View Recycling":  https://developer.android.com/guide/topics/ui/layout/recyclerview

We bind this library on NuGet as [Xamarin.AndroidX.RecyclerView](https://www.nuget.org/packages/Xamarin.AndroidX.RecyclerView/).

**Comment by JeyasriVijay** [comment]
As our requirement , we need to add Scroll Viewer as base have to add children's in it , as reported issue replicated in simple sample as shared before , please validate the sample shared , let us know the possible to fix in using ScrollViewer used.

Please check same related issue -  https://github.com/roughike/BottomBar/issues/371

**Comment by jpobst** [comment]
For help with usage of Android APIs, you will probably get better responses on [StackOverflow](https://stackoverflow.com/questions/tagged/android) or the [.NET Android section of Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/dotnet-android.html).

This repository caters more to issues with the Xamarin.Android tooling itself and does not have extensive expertise in how to properly consume Google Android APIs in an application.
