### ISSUE TITLE
VS 16.11.0 Preview 3 Project will not deploy

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#6261]
I suddenly can't deploy and get the following message

```
Build started...
1>Starting deployment to Google Pixel 3a ...
1>Deploying to Google Pixel 3a ...
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

```
I've not had a problem building or deploying in months and none of the code changes I made today could possibly cause deployment problems. I then copied the project to another computer that is running 16.11.2 Prev 1 and it builds and deploys just fine.

 I've noticed a problem on this computer (Dell XPS) when I deploy to a Samsung Galaxy Tab S7. It seems to lose the USB connection randomly, (Windows dinging sound) so I tried another cable.  That is when I first noticed that I couldn't deploy anymore. I then changed back to a Pixel 3a with the previous cable and it started not being able to deploy too, where previously I had been deploying to it all morning.

I did all the usual delete bin/obj folders, reboot the computer etc. It still builds fine, but as soon as you try and deploy what you just built, you immediately get the above very informative message.

I can upgrade the Dell to 16.11.2 Prev 1, but I doubt that will make any difference as I don't think anything changed re xamarin.android from 16.11.0 P3 to 16.11.2 P1. 

Also doesn't make any difference whether I use a debug or release build.

Any suggestions? Is there any way of forcing more log output from the deploy part?

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) with this setting added to your project?

```xml
<_FastDeploymentDiagnosticLogging>true</_FastDeploymentDiagnosticLogging>
```

Does it work fine if you use an emulator?
