### ISSUE TITLE
No Arm32 added to apk for wear os

### ISSUE THREAD

**Issue by DevronB** [xamarin/xamarin-android#6285]
I hope this is the right place?

### Steps to Reproduce
I'm having issues with the APK when built for Wear OS 3.0 as it's missing Arm32 resources. The absence of these is causing the install on wear OS physical hardware to fail with invalid architecture. x86 Emulators and mobile devices (Arm64) are fine.

See screenshot, left if built using net6.0-android and right a Xamarin.Andriod wear project.
![image](https://user-images.githubusercontent.com/27395345/132973085-3c658279-f94a-492d-a7fc-c196a35892d9.png)

`dotnet build -c Release -f net6.0-android`

Is there a way I can specify the RID's to build for? I've tried: `dotnet build -c Release -f net6.0-android -r arm` and it seemed to package arm32 and install ok on the watch. But arm64 was omitted. can I specify multiple?

Is this a bug where the build targets need to be corrected in the workload? I'm a little out of my depth here so any pointers would be appreciated.

Sorry if I've misinterpreted this.
 
### Expected Behavior
When building net6.0-andriod project for release the Arm32 and Arm64 resources should be bundled and x86 excluded, I presume as per Xamarin.Andriod project.

### Actual Behavior
Arm32 resources are omitted.

### Version Information
net6.0-android

**Comment by dellis1972** [comment]
You probably need to add 
```
<RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
```

to your project.  I think it defaults to only `android-arm64;android-x86`

**Comment by DevronB** [comment]
Ok, yes I have tried this and it seems to work ok. I imagine when the Wear project template is ported to net6.0-android this would be set in the template then?

**Comment by DevronB** [comment]
All good, thank you for the links.
