### ISSUE TITLE
Is any way to run dll in android studio java 

### ISSUE THREAD

**Issue by lkhore** [xamarin/xamarin-android#6287]
How we can use dll in android studio or any way to create aar and jar for dll?

**Comment by jpobst** [comment]
If you are asking if you can use a managed (C#) .dll in a native Java/Kotlin app, the answer is probably not.

It's not possible to simply consume a .dll in Java.  You must also embed the Mono runtime to run the .dll, and set up a bridge between the Java runtime and the Mono runtime.

There was a project that did this: https://github.com/mono/Embeddinator-4000, however it hasn't been maintained in quite some time and likely no longer works.

**Comment by lkhore** [comment]
I had found https://github.com/mono/Embeddinator-4000 but didn't work.
So how about **set up a bridge between the Java runtime and the Mono runtime.**.
So can you please give some information?

Do you have any future plans for this?

**Comment by jpobst** [comment]
I doubt there are any future plans for this, as it's not really the focus of Xamarin.  Perhaps @chamons knows more.

**Comment by lkhore** [comment]
**set up a bridge between the Java runtime and the Mono runtime** Please provide the details of.

**Comment by jpobst** [comment]
That is what Embeddinator-4000 does.  It looks like the docs were deleted out of the repo to be placed on docs.microsoft.com, and now no longer exist there either.

You can view the old docs in the PR that removed them: https://github.com/mono/Embeddinator-4000/pull/649/files.

There are no additional details besides what is provided by that project.

**Comment by lkhore** [comment]
Ok, thanks so I am assuming we can't convert DLL to AAR.
