### ISSUE TITLE
Is reverting to ProGuard possible?

### ISSUE THREAD

**Issue by bellissimo** [xamarin/xamarin-android#6294]
The Amazon IAP plugin for Xamarin is quite out of date now, and no longer works with R8. It seems unlikely this will be fixed anytime soon, which is obviously an issue when trying to update an app which utilises IAPs. I have to use D8 due to using the AndroidX libs, however it is no longer possible to use D8 with ProGuard ,since this now generates a compile time error.

`Using ProGuard with the D8 DEX compiler is no longer supported. Please set the code shrinker to 'r8' in the Visual Studio project property pages or edit the project file in a text editor and set the 'AndroidLinkTool' MSBuild property to 'r8'. `

So is it possible to revert to ProGuard at all?

**Comment by jonathanpeppers** [comment]
> The Amazon IAP plugin for Xamarin is quite out of date now, and no longer works with R8.

What is the error? Should we just address that? Sometimes, it is simply a `<uses-library/>` missing in your `AndroidManifest.xml`.

> Using ProGuard with the D8 DEX compiler is no longer supported. Please set the code shrinker to 'r8' in the Visual Studio project property pages or edit the project file in a text editor and set the 'AndroidLinkTool' MSBuild property to 'r8'.

Was this a warning or an error? Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

**Comment by bellissimo** [comment]
It is a build error which stops the build pretty early on. The Amazon problem is essentially the same thing as reported here:

[https://github.com/xamarin/xamarin-android/issues/5466]

I was hoping to see if turning on ProGuard would be an easy workaround.

**Comment by jonathanpeppers** [comment]
I think you can set both of these at once to try ProGuard:
```xml
<AndroidDexTool>dx</AndroidDexTool>
<AndroidLinkTool>proguard</AndroidLinkTool>
```

My memory is coming back to me about:

https://github.com/xamarin/xamarin-android/issues/5466#issuecomment-756449789

The issue is that the Amazon IAP library is swallowing the exception and not logging what Java type is missing. If we could somehow figure that out, I think you just need a proguard rule to prevent r8 from stripping away a specific class -- then it should work fine?

**Comment by bellissimo** [comment]
Ok, so setting both those options seems to revert to ProGuard, though I now get a load of ProGuard warnings regarding the AndroidX libs, which I was kind of expecting. It also exits the build with a Java Code 1 (which may be related).

I think it may be easier, and better in the long run, to try to re-generate the Amazon IAP binding library using the latest jar instead, rather than spending a lot of time getting the old version to work. 

Thanks for your help, and you answered the original query regarding ProGuard so I will close it now.
