### ISSUE TITLE
Failure to build/deploy/run with android:packageName and <ApplicationId>

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#6302]
### Steps to Reproduce

1. Create an Android app with a package name in the manifest and the .csproj
2. Observe the build create an .apk and deploy it using the name in the csproj
3. Observe the deploy fail or runtime exception when the app actually has the package name in the android manifest

ID in Manifest: com.microsoft.maui
ID in Project: com.microsoft.maui.sample

![image](https://user-images.githubusercontent.com/1096616/133549034-ed99587f-78e3-4216-8d80-dd34ca6d9e4d.png)

[com.microsoft.maui.sample-Signed.zip](https://github.com/xamarin/xamarin-android/files/7174904/com.microsoft.maui.sample-Signed.zip)

### Expected Behavior
Deploy and run.

### Actual Behavior
Failure to deploy or broken run.

### Log File
[msbuild.zip](https://github.com/xamarin/xamarin-android/files/7174896/msbuild.zip)

**Comment by dellis1972** [comment]
So I guess the first question is which packageId should take precedence ? csproj or AndroidManifest.xml?

**Comment by jonathanpeppers** [comment]
This seems broken on our end:

![image](https://user-images.githubusercontent.com/840039/133677489-feb7bef7-304a-4731-88a9-623df1274663.png)

I have `package="com.companyname.bar"` in the `AndroidManifest.xml`
