### ISSUE TITLE
App can't launch without internet in debug mode

### ISSUE THREAD

**Issue by themronion** [xamarin/xamarin-android#6330]
### Steps to Reproduce

1. Create an empty project with XF (i am quite sure this issue will be for android native as well). Turn off all internet connections completely on emulator (wifi and celullar data). Launch app and observe debugger and app shutting down.

### Version Information

Latest Visual Studio and Visual Studio for Mac, also happened on previous versions, forgot to report

[log.txt](https://github.com/xamarin/xamarin-android/files/7219012/log.txt)

Log file is attached

**Comment by grendello** [comment]
Hi,

Debugging of managed code on devices requires networking support (IDE talks to the app over sockets forwarded by ADB to the device/emulator), this is by design.
