### ISSUE TITLE
Xamarin.Kotlin.StdLib 1.5.31 will lead app crash

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-android#6333]
### Steps to Reproduce

1. Check out this sample and run it https://github.com/jingliancui/XamarinFormsEasyFloatSample
2. Run it and it will be fine.
3. Then install kt 1.5.31 https://www.nuget.org/packages/Xamarin.Kotlin.StdLib/1.5.31 because EasyFloat depend on kt.
4. Run it and it will crash.

### Expected Behavior
Run it and it will be fine.
### Actual Behavior
Run it and it will crash.
### Version Information
Microsoft Visual Studio Community 2019
Version 16.11.3

**Comment by jpobst** [comment]
What is the crash in the log?

**Comment by jingliancui** [comment]
`Java.Lang.NoClassDefFoundError: 'Failed resolution of: Lkotlin/jvm/internal/Intrinsics;'`

log file:
[fulllog.txt](https://github.com/xamarin/xamarin-android/files/7263939/fulllog.txt)

![crash1](https://user-images.githubusercontent.com/16309962/135561126-24997e48-7b1d-4910-82c6-6a356c9dca8a.png)

**Comment by jpobst** [comment]
Thanks for the log!  Looks like this package is broken.  We are working on getting a fixed version out.

Details and tracking here: https://github.com/xamarin/AndroidX/pull/404.

In the meantime, `1.5.30` should be the newest available package that works correctly.

**Comment by jpobst** [comment]
If you can, please try out `https://www.nuget.org/packages/Xamarin.Kotlin.StdLib/1.5.31.2` and see if it works for you.  Thanks!

**Comment by jingliancui** [comment]
OK Thanks so much!

**Comment by jingliancui** [comment]
I have tested it and it's work.
