### ISSUE TITLE
error defined multiple times building project with net6.0-android, but success with xamarin.android

### ISSUE THREAD

**Issue by yunusefendi52** [xamarin/xamarin-android#6341]
### Steps to Reproduce
I can't create the steps to reproduce, but I am trying to port project to net6.0-android from xamarin.android, all of the dependency is using `Directory.Build.props` and `Directory.Build.targets` and I also have net6.0-android library (also ported).
Building project using xamarin.android is succeded but when trying to port to net6.0-android building with `dotnet` is failing (see in Actual Behavior).
I also uses Xamarin.Forms and not trying to port it to maui yet, i am only trying port to net6.0-android

### Expected Behavior
success

### Actual Behavior
fail with
```
Type androidx.collection.ArrayMap$1 is defined multiple times: /Users/vm/.nuget/packages/xamarin.androidx.collection/1.1.0.8/buildTransitive/net6.0-android30.0/../../jar/androidx.collection.collection.jar:androidx/collection/ArrayMap$1.class, obj/Debug/net6.0-android/lp/122/jl/libs/9CEF1E3534E2CB62.jar:androidx/collection/ArrayMap$1.class (TaskId:541)
                     Compilation failed (TaskId:541)
```
There are actualy 4 libraries affected with above error with different naming pattern
9CEF1E3534E2CB62.jar
178FE9B200CBF81E.jar
322E37C639F43D36.jar
BFFE505C2AEC36C4.jar

### Workaround (but not really)
After seeing the error message I compare the two jars `/jar/androidx.collection.collection.jar` and `9CEF1E3534E2CB62.jar` it seems that these jars has different size, so I manually copy the `/jar/androidx.collection.collection.jar` to obj/Debug/net6.0-android/lp/122/jl/libs/ and rename it to `9CEF1E3534E2CB62.jar` and build again (without clean) and the build is **success** and the app is running though with runtime error which I don't know why but will investigate more

### Version Information
xamarin.android 11.2.2.1
dotnet 6.0.100-rc.1.21463.6

### Log File

**Comment by yunusefendi52** [comment]
I think I can reproduce this, in my project `Directory.Build.props` and `Directory.Build.targets` is not in the same folder, I move those to the root project folder and now I can build the project successfully
[BuildSuccess.zip](https://github.com/xamarin/xamarin-android/files/7242501/BuildSuccess.zip)
[BuildFailed.zip](https://github.com/xamarin/xamarin-android/files/7242500/BuildFailed.zip)
I build above projects using `dotnet build App/TestNet6Android.csproj` in the root project folder

**Comment by jonathanpeppers** [comment]
@yunusefendi52 Xamarin.Forms is not supported on .NET 6. (Sorry can't find a link on this) If it works for your app, that is great, though.

I noticed this comment in the sample:
```xml
        <!-- This is the closest reproduce I can get -->
        <!-- Explicitly add below will make the build successful -->
        <!-- <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.3.0.6" /> -->
```

If this comment is accurate, it sounds like Xamarin.Forms has a dependency on this package and it's not listed as a dependency of Xamarin.Forms. Moving `Directory.Build.targets` around seems unrelated to the Android workload, maybe an issue with MSBuild?

I would just include the line above if that solves the issue, thanks!

**Comment by jonathanpeppers** [comment]
The issue might be one of the `<PackageReference/>` items aligns the dependencies in `MyAndroidLibService.csproj`.

When you moved it, it made sure the same packages are used in both projects.
