### ISSUE TITLE
Better report `java.exe exited with code 1` error messages

### ISSUE THREAD

**Issue by jpobst** [xamarin/xamarin-android#6380]
One of the most common support issues we get is this error:
```
error MSB6006: “java.exe” exited with code 1.
```

This requires directing the user to create a diagnostic MSBuild log to get the real Java error before we can do anything.

It would be nice if we could better parse Java error messages so we could show them directly to the user instead of the `MSB6006`.  Then they could search for that message instead of searching for the generic `MSB6006` which often sends them in the wrong direction since it represents an infinite amount of different cases.  Hopefully this would result in more users able to figure out the issue without needing to contact us.

**Comment by jonpryor** [comment]
This should happen for *all* tools that we invoke.

Would also be handy to "decode" our "encoded" directory names in the `…/lp/…` paths.

**Comment by jpobst** [comment]
Should be fixed via https://github.com/xamarin/xamarin-android/pull/7012.
