### ISSUE TITLE
Missing release notes for xamarin android 12.1.0.4 in visual studio 17.0.0-pre5

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#6386]
Visual studio 17.0.0-pre5 was published recently.
Could you please publish release notes for xamarin android 12.1.0.4 ?

Similar issues:
- #6226
- #5961
- #5498

**Comment by jonpryor** [comment]
Release notes for Xamarin.Android 12.1.0.5 are now live: https://docs.microsoft.com/xamarin/android/release-notes/12/12.1
