### ISSUE TITLE
Make dotnet publish more consistent

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-android#6393]
Goal: Make `dotnet publish` relatively consistent and relatively free of platform specific arguments required...

Consider the following scenario for building in CI:

`dotnet publish -f net6.0-android -c Release -o ./artifacts`

This produces the following output:
 - ./artifacts/com.app.id.aab
 - ./artifacts/com.app.id-Signed.aab

If you just do a `dotnet build -f net6.0-android -c Release` you get in the output path:
- ./com.app.id-Signed.apk
- ./com.app.id.aab
- ./com.app.id-Signed.aab

I think the ideal scenario would be for publish to produce both apk and aab by default, and only output the -Signed variants (perhaps it should also not be named -Signed? not super opinionated on that) to the output path specified.

I would expect the following output:
- ./artifacts/com.app.id.aab (Signed)
- ./artifacts/com.app.id.apk (Signed)

This is a small change but makes a lot of sense for publish scenarios, especially if iOS works roughly the same.

**Comment by Redth** [comment]
I think the default should be to emit both package formats in publish like you do already for a Release configuration build, but yeah the apk is missing from the output.

Also i really do think we don't want both signed and unsigned - I am not sure why you would ever want the _unsigned_ binaries in a publish command....  Again for something like a CI system, this is just more confusing to have both.

**Comment by dellis1972** [comment]
> We don't have a great way to say "don't sign at all".

We do, we have a `PackageForAndroid` target which just does the package build. It does not do the sign or aligning bits.

**Comment by RaspeR87** [comment]
This command `dotnet build -f net6.0-android -c Release` works for me in .NET 6 but only for **.NET MAUI App template** and not for **.NET MAUI Blazor APP template**. 

More about that in this github post: https://github.com/dotnet/maui/issues/3060
