### ISSUE TITLE
Biometrics  -  Identifying multiple users(token based) with fingerprint API

### ISSUE THREAD

**Issue by UdayKumar-BH** [xamarin/xamarin-android#6396]
Fingerprint Multiple User Authentication  - How to get Unique key/id from Finger-Print Authentication API in the app(to map and store server tokens per user in the app ex.. one for user A and one for user B.) 

Our business need is to register/authenticate multiple users to use separate token for each user

Does the API provide support to detect which user, A or B or just logged in(like thumbs up or down)

Is there any way for an app to access the fingerprint data to be able to save it or use across the devices(if we share multiple devices)

### Steps to Reproduce

1. 
2. 
3. 

### Version Information

<details>

</details>

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.
