### ISSUE TITLE
The Android App Bundle was not signed.

### ISSUE THREAD

**Issue by DevronB** [xamarin/xamarin-android#6412]
I'm trying to upload an net6-android app to a test channel for early alpha testing.
Play Store won't sign aab file and returns error: 'The Android App Bundle was not signed' when attempting to upload.

### Steps to Reproduce
- In VS2022 P5 if I create new 'Android Application (Preview)'
- Set configuration to 'Release'
- Build aab Archive
- Attempt to upload to play store testing release using Google provided play store signing.
- After 30sec, Error: 'The Android App Bundle was not signed.'

Also tried, dotnet publish -f net6.0-android -c Release -o ./artifacts

### Expected Behavior
aab bundle uploaded and signed without error.

### Actual Behavior
Error: 'The Android App Bundle was not signed.'

### Version Information
VS2022 Preview 5
net6-android 6.0.100-rc.2.21505.57

**Comment by DevronB** [comment]
ok all sorted. Thanks for the pointers.

Not wanting to hijack this issue, but would you be able to tell what MSBuildProp I would need to set the aab filename?

so, something like this but for the aab,/apk not the assemblies.
<AssemblyName>$(ApplicationId)-$(ApplicationDisplayVersion)</AssemblyName>

I can't find it for looking...

Cheers

**Comment by jonathanpeppers** [comment]
There is not a public property to change the file name:
https://github.com/xamarin/xamarin-android/blob/617500c92d989c87641db7010595f296eeffcfde/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L542-L543

It will just be your `package` name + `-Signed.aab`. Hope that helps, I think we solved the issue here, thanks!
