### ISSUE TITLE
Visual studio 2022 RC3 - There was a conflict between Java.Interop, Version=0.1.0.0 and Version=0.1.2.0

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#6438]
New warning when building a xamarin forms app for android, using visual studio 2022 RC3 (not happening with RC2)

```
There was a conflict between "Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" 
and "Java.Interop, Version=0.1.2.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"
```

What is going on ?
Could this be related to https://github.com/xamarin/java.interop/commit/2d5431f765928e5377288d3284ace3c5d871755a ?
cc @jonpryor 

```
Visual Studio 2022 RC3
Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9
```

**Comment by ryanholden8** [comment]
@jonathanpeppers  This is currently an error on our project, so unfortunately we can't ignore. Am I understanding correctly that the only way to fix this is to update to .NET 6? Our entire team uses VS for Mac so I'm not sure if Xamarin.Android in VS2022 apply to us or not?

**Comment by glennawatson** [comment]
I think the problem needs to be fixed on the ReactiveUI end @ryanholden8 not you as a consumer on the VS for Mac standard version.

**Comment by tranb3r** [comment]
Still not fixed in VS 2022 17.0.0 (xamarin.android 12.1.0.5).
And also not fixed in VS 2022 17.1.0-pre1 (xamarin.android 12.1.99.56).

@jonathanpeppers Could you please explain when this is going to be fixed ?

**Comment by jonathanpeppers** [comment]
@tranb3r the correct version of `Java.Interop.dll` is in Xamarin.Android 12.1.0.5.

Can you share a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) of your latest issue?

The problem is probably that you have some dependency that was built against a "bad" version of `Java.Interop.dll` and it now needs to be rebuilt.

**Comment by tranb3r** [comment]
@jonathanpeppers You're absolutely right.
I've identified the faulty dependency. I've rebuilt it and now the warnings are gone.
Thanks a lot for your help!
