### ISSUE TITLE
Incorrect handling of Daylight Saving Time (DST) (Central Europe) of DateTimeOffset.Now and ToLocalTime

### ISSUE THREAD

**Issue by Fuzzillogic** [xamarin/xamarin-android#6446]
### Steps to Reproduce

In the Central European Timezone the summertime / DST ended on 2021-10-31 03:00.

1. On Android device, disable network time and time zone.
2. Select timezone "Amsterdam/Netherlands".
3. Set time to 2021-10-31 01:59. Verify you're in summertime, i.e. the offset should be GMT +02:00
4. Wait one minute. It will be 02:00 +02:00. Thus, still one hour of summertime to go!
5. In Xamarin, assign `DateTimeOffset.Now` to a variable and inspect.
6. Compare with `DateTimeOffset.UtcNow`.

Possibly related: `DateTimeOffset.ToLocalTime()` yields wrong results.

### Expected Behavior
The correct offset, i.e. +02:00

### Actual Behavior
Wrong offset: +01:00

The current time on device is 02:05 +02:00. (CEST)

Inspecting variables in the debugger:
![image](https://user-images.githubusercontent.com/10601512/139691253-801b1f28-5d3a-4466-81fe-ce49f3ca46ab.png)

Variable `u` is correct: 00:05 +00:00 is equal to 02:05 +02:00. Variable `n` is incorrect, 02:05 +01:00 is one hour in the future!

Converting to local time, using `ToLocalTime()` also yields wrong results: offset is +01 instead of +02, as it is still summer time.

For reference, device time a few minutes after the above test:
![image](https://user-images.githubusercontent.com/10601512/139691504-1ab6ffe8-2c44-4907-8931-6ad2c52535f1.png)

(Network time disabled. Date: 2021-10-31. Time: 02:10. Timezone GMT +02:00 Central European Summer Time)

### Version Information

<details>

Microsoft Visual Studio Enterprise 2019
Version 16.11.5
VisualStudio.16.Release/16.11.5+31729.503
Microsoft .NET Framework
Version 4.8.04084

C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Xamarin   16.11.000.190 (d16-11@2391ed9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.17 (remotes/origin/11e0001f0b17269345e80b58fb3adf1ba4efe2cd@11e0001f0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.0.5 (d16-11/7776c9f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@48766c0
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@683f375

Xamarin.iOS and Xamarin.Mac SDK   15.0.0.8 (0796d78dc)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

**Comment by Fuzzillogic** [comment]
Both desktop and Xamarin.Android seem to agree on TimeZoneInfo,Local:

```
Id	W. Europe Standard Time
DisplayName	(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
StandardName	W. Europe Standard Time
DaylightName	W. Europe Daylight Time
BaseUtcOffset	01:00:00
SupportsDaylightSavingTime	True
```

But regardless the actual TimeZoneInfo used, `Math.Round((DateTimeOffset.UtcNow - DateTimeOffset.Now).TotalMinutes)` should always be 0, correct? On Xamarin.Android, in the above scenario, this results in -60.

**Comment by jpobst** [comment]
It looks like this is covered here: https://github.com/mono/mono/issues/10014.

Test case that does not require changing your Android time:
```
var tz = System.TimeZoneInfo.FindSystemTimeZoneById ("Europe/Amsterdam");

var utc0 = new DateTime (2021, 10, 30, 23, 5, 0);
var utc1 = new DateTime (2021, 10, 31, 0, 5, 0);
var utc2 = new DateTime (2021, 10, 31, 1, 5, 0);
var utc3 = new DateTime (2021, 10, 31, 2, 5, 0);

var local0 = TimeZoneInfo.ConvertTimeFromUtc (utc0, tz);
var local1 = TimeZoneInfo.ConvertTimeFromUtc (utc1, tz);
var local2 = TimeZoneInfo.ConvertTimeFromUtc (utc2, tz);
var local3 = TimeZoneInfo.ConvertTimeFromUtc (utc3, tz);

Console.WriteLine (local0);
Console.WriteLine (local1);
Console.WriteLine (local2);
Console.WriteLine (local3);
```

On Legacy this incorrectly reports:
```
10/30/2021 1:05:00 PM
10/31/2021 2:05:00 AM
10/31/2021 3:05:00 AM
10/31/2021 3:05:00 AM
```

On .NET6 Android this correctly reports:
```
10/30/2021 1:05:00 PM
10/31/2021 2:05:00 AM
10/31/2021 2:05:00 AM
10/31/2021 3:05:00 AM
```

**Comment by jpobst** [comment]
Closing as this is tracked in https://github.com/mono/mono/issues/10014.
