### ISSUE TITLE
Xamarin (Visual Studio) - "Preserve application data" does not preserve application data

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6453]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Visual-Studio---Preserve-appl/1371823)._

---
[severity:I'm unable to use this version]
Repro steps.
1. In VS, under Tools --> Options --> Xamarin --> Android Settings, enable "Preserve Application Data Cache on Device Between Deploys"
2. Install the production version (from Google Play) of your app on your phone
3. Connect your phone to your computer via USB
4. Deploy the Debug version of your app to your phone via Visual Studio

Expected Results
Application data is preserved

Actual Results
All application data is wiped, resulting in me losing dozens of hours of work, and making it nearly impossible to debug certain issues.

Note: Based on [this thread](https://forums.xamarin.com/discussion/4221/debug-as-upgrade-instead-of-new-deployment-to-retain-data), this used to work but broke sometime around late 2018.

---
#### Feedback Bot on 3/16/2021, 08:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/23/2021, 08:23 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 3/23/2021, 08:24 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 3/23/2021, 11:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/23/2021, 03:19 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Dean Ellis [MSFT] on 3/23/2021, 03:38 PM: 

<p>I suspect for this scenario to work there would be some restrictions.</p>
<ol>
<li>The Debug apk will probably need to be signed with the same key as the release one from Google Play.</li>
<li>The version number of the new apk will need to be greater than the one from Google Play.</li>
</ol>
<p>What is probably happening in this case is that <code>adb</code> is deciding that the new apk is incompatible. when it does this<br>
any caches data will be deleted. This is not something we control, since I believe that even if we do pass the -k option  (which we always do)<br>
when we uninstall the package, when we install the new one adb might decide to completely replace it.</p>
<p>So I would suggest you try with the restrictions outlined in 1 and 2. To see if that works.</p>

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
This has not received a response from the reporter, so I think we can close it.
