### ISSUE TITLE
.Net MAUI app crashing phone

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6455]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-MAUI-app-crashing-phone/1521554)._

---
[severity:I'm unable to use this version]
I wanted to try .Net MAUI with VS 2022 preview 3, and tried to run the initial application on my actual phone (Samsung Galaxy S7), the app started without any problem and the hot reload kinda worked.
But as soon as I ended my debug session (and came back on Home), my phone became very very laggy, and "Samsung Home Experience" kept crashing every 4-5 seconds, making my whole display fully reset.

I soon realized that if I was quick enough to reach Settings, the crash would stop for the time I left Home, and started to explore the settings to find a solution.

I decided to go in Applications, find the app that had been installed by Visual Studio and uninstall it, but as soon as the blade with the icon and the name of the app should have been displayed when scrolling through my applications, Settings crashed the same way as Samsung Home Experience did. 

Settings crashes as soon as it should display it.
Samsung Home Screens takes a few seconds, but when it initializes, it loads the icons 1 by 1, and the one from the MAUI app should be the very last one in my phone.
So I am pretty sure the "loading" of the icon makes anything crash on my phone.

The only solution I found (for anyone who'd face the same problem) was to go to applications in settings again, select them all, unselect those I want to keep (until I would reach the "danger zone" that would make my Settings crash) and uninstall all the rest (hence, having the MAUI app selected)
Since my phone is not super recent that would take a while, but once it has finished, my Home stops crashing, only problem remaining is that I lost any app whose name would have made it sorted after the MAUI app.

I made 2 more experiments in order to collect more data 
- I fully reseted developer mode on my phone before trying to do the process all over again, crash came back
- I installed a basic mobile app from Android Studio, no crash, so the problem really is between Visual Studio Preview 3 or .Net MAUI with my specific phone.

Hope that helps, do not hesitate to notify me if this is found and fixed, since I don't have an intel CPU, emulation is not really a solution for me.

---
#### Feedback Bot on 9/5/2021, 08:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Paul Wang [MSFT] on 9/6/2021, 03:35 AM: 

<p>Hi, thanks for your feedback. Do you have this problem on Windows or MAC? And what is the build number?</p>

#### Benoit Hoffman on 9/6/2021, 11:56 PM: 

<p>Hi, sorry for not specifying at least my OS.</p>
<p>My OS is Microsoft Windows 10 Education version 10.0.18362 Build 18362.<br>
The .net preview version I run (info from terminal) is 6.0.100-preview.7.21379.14</p>
<p>and here is the list of intalled products fetched from VS:<br>

```
Microsoft Visual Studio Enterprise 2022 Preview
Version 17.0.0 Preview 3.1
VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2022 00476-70000-00000-AA218
Microsoft Visual C++ 2022

.NET Core Debugging with WSL 1.0
.NET Core Debugging with WSL

ADL Tools Service Provider 1.0
This package contains services used by Data Lake tools

ASA Service Provider 1.0

ASP.NET and Web Tools 2019 17.0.414.6609
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019 17.0.414.6609

Azure App Service Tools v3.0.0 17.0.414.6609
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio 2.6.2000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools 17.0.414.6609
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio 2.6.2000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools 4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools 1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus 1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents 1.0
Fabric Diagnostic Events

Microsoft Azure Hive Query Language Service 2.6.2000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio 17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service 2.6.2000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio 2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager 2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger 1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards 1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers 1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package 1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio 17.0.6 (1ebf2f7)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager 6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit docs.nuget.org

ProjectServicesPackage Extension 1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core) 17.0.0.2138002+9e71a625d64fa38b323fa6ac52154e6b1bde703d
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension 1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools 17.0.62108.04180
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test 1.0
Enables Visual Studio’s testing tools with unit tests written for Boost.Test. The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test 1.0
Enables Visual Studio’s testing tools with unit tests written for Google Test. The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor 1.0
Hosting json editor into a tool window

TypeScript Tools 17.0.0730.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools 4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 17.0.0-beta.21370.1+9b96c1bde17e9af532ae34eacbfc12d1628183d7
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package 1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions 1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode 2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake 1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers 1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog 1.0
Information about my package

VisualStudio.Foo 1.0
Information about my package

VisualStudio.Mac 1.0
Mac Extension for Visual Studio

Xamarin 17.0.0.145 (main@bdc8369)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer 17.0.0.58 (remotes/origin/d17-0@927d548a1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates 17.0.3 (a84fb28)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK 11.4.99.70 (main/7e1558c)
Xamarin.Android Reference Assemblies and MSBuild support.
Mono: c633fe9
Java.Interop: xamarin/java.interop@4fb7c14
ProGuard: Guardsquare/proguard@912d149
SQLite: xamarin/sqlite@a575761
Xamarin.Android Tools: xamarin/xamarin-android-tools@623332d

Xamarin.iOS and Xamarin.Mac SDK 14.99.0.294 (13b1b3c45)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

<hr>
<p>If that helps, when creating my .net MAUI project, I could not find the template in VS although I had everything from doc installed, so I succesfully created it from command line <code>dotnet new maui -n _projectname_</code></p>

#### Feedback Bot on 9/7/2021, 07:08 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 9/8/2021, 11:36 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jonathan Peppers [MSFT] on 9/8/2021, 02:05 PM: 

<p>Can you attach <a target='_blank' href="https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log">adb logcat output</a> when your phone is acting strange? There should be some error message or something showing what is happening. I’m not sure what could cause a problem like this.</p>
<p>Does a Release build of the app have any issues?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Benoit Hoffman on 9/9/2021, 02:02 AM: 

<p>Hi Jonathan, and thanks for looking into that, I really want to try MAUI out 😦</p>
<p>Same problem seems to happen with Release build (so the app works fine, but phone dies)</p>
<p>You may find a 6000 lines log record from my phone in the attached Android_Logs.txt, most of those lines seems to be useless debug messages coming from the app itself (ConnectivityService Tag) and could easily be filtered out but I left them there just in case 😃</p>
<p>The operations I performed was:</p>
<ul>
<li>start the app from VS</li>
<li>go into settings to avoid repetitive crash</li>
<li>stop the debugging from VS</li>
<li>start recording of the logs</li>
<li>go to home and wait for 2-3 crashes to happen</li>
<li>stop recording</li>
</ul>
<p>Really hope it helps,</p>
<p>Cheers!</p>

#### Jonathan Peppers [MSFT] on 9/9/2021, 06:49 AM: 

(private comment, text removed)
#### Benoit Hoffman on 9/9/2021, 08:42 AM: 

(private comment, text removed)
#### Benoit Hoffman on 10/13/2021, 02:33 AM: 

<p>Hi <a target='_blank' href="https://developercommunity2.visualstudio.com/user/4907eedc-8e83-6418-970d-be28acc2b5b2/profile">Jonathan Peppers [MSFT]</a>,</p>
<p>I thought you might be interested to learn that I installed the new version of Visual Studio Preview 5, and the problem is still exactly the same for me 😦.</p>
<p>I can’t believe that it’s common, otherwise you guys would have already figured it out, but I am so sad I still cannot play with MAUI 😦.</p>
<p>Additional note: this test with preview 5 has been made on another computer than the first tests, so the fault is most probably between MAUI and the phone, not the dev environment.</p>
<p>Cheers!</p>

#### Jonathan Peppers [MSFT] on 10/13/2021, 07:06 AM: 

<p>Does the problem occur with a plain .NET 6 Android app? This is <code>dotnet new android</code> or the template that just says <code>Android Application</code>.</p>

#### Benoit Hoffman on 10/13/2021, 09:54 AM: 

<p>I get a weird “the path is not in a legal form” error when building from VS, but the app is nevertheless installed on the phone, works as expected, and no bug like the one described in my ticket is to be seen.</p>
<p>Just to be clear, the “plain Android app” I tried was created with the <code>dotnet new android</code> command, while the .Net MAUI app I tried in VS preview 4 and 5 were created using the MAUI app template from VS directly.</p>

#### Jonathan Peppers [MSFT] on 10/13/2021, 11:03 AM: 

<p>I think the “path is not in a legal form” error is something that happens when you open a <code>.csproj</code> file and didn’t save the <code>.sln</code> file in VS yet. We have an issue somewhere filed about this.</p>
<p>So your original problem only occurs with MAUI and nothing appears to be wrong with plain .NET 6 Android apps?</p>

#### Benoit Hoffman on 10/13/2021, 11:26 AM: 

<p>Exactly, the plain .NET 6 Android app works fine and my phone has 0 problem.</p>
<p>Btw, were you able to get your hands on my Android Logs this time?</p>

#### Benoit Hoffman on 10/13/2021, 11:50 AM: 

<p>Also, I was able to get my hands on another old phone just for trial (Samsung J5 2016), and the app works fine, no bug to be seen.</p>

#### Jonathan Peppers [MSFT] on 10/13/2021, 00:28 PM: 

<p>No, we’re not seeing those logs.</p>
<p>Can you try creating a <a target='_blank' href="https://gist.github.com">gist</a> (or some similar site), and just share the link to it? Thanks!</p>

#### Benoit Hoffman on 10/13/2021, 01:07 PM: 

<p>Sure thing <a target='_blank' href="https://developercommunity2.visualstudio.com/user/4907eedc-8e83-6418-970d-be28acc2b5b2/profile">Jonathan Peppers [MSFT]</a>!</p>
<p>There it is: <a target='_blank' href="https://gist.github.com/Petit-Pas/b64d2c1c92a44cab10174ad53131eebb">https://gist.github.com/Petit-Pas/b64d2c1c92a44cab10174ad53131eebb</a></p>

#### Jonathan Peppers [MSFT] on 10/13/2021, 02:54 PM: 

<p>This part might be interesting:</p>
<pre><code><span class="hljs-number">09</span><span class="hljs-number">-09</span> <span class="hljs-number">10</span>:<span class="hljs-number">49</span>:<span class="hljs-number">31.964</span>	Samsung SM-G935F	Debug	<span class="hljs-number">15252</span>	LauncherActivityInfo	packageName: com.companyname.ZzzMAUIProject, supportTheme: <span class="hljs-literal">false</span>, height: <span class="hljs-number">912</span>, width: <span class="hljs-number">912</span>, density: <span class="hljs-number">640</span>
<span class="hljs-number">09</span><span class="hljs-number">-09</span> <span class="hljs-number">10</span>:<span class="hljs-number">49</span>:<span class="hljs-number">31.964</span>	Samsung SM-G935F	Info	<span class="hljs-number">15252</span>	ApplicationPackageManager	<span class="hljs-keyword">return</span> adaptive icon <span class="hljs-keyword">for</span> <span class="hljs-literal">NULL</span>
<span class="hljs-number">09</span><span class="hljs-number">-09</span> <span class="hljs-number">10</span>:<span class="hljs-number">49</span>:<span class="hljs-number">31.964</span>	Samsung SM-G935F	Debug	<span class="hljs-number">4836</span>	PackageManager	getSelectedMetaData : packageName(com.companyname.ZzzMAUIProject) <span class="hljs-keyword">or</span> Metadata strings {[Ljava.lang.String;@<span class="hljs-number">59b</span>9037}
</code></pre>
<p>What if you delete the fancy Maui icon?</p>
<pre><code class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">MauiIcon</span>
  <span class="hljs-attr">Include</span>=<span class="hljs-string">"Resources\appicon.svg"</span>
  <span class="hljs-attr">ForegroundFile</span>=<span class="hljs-string">"Resources\appiconfg.svg"</span>
  <span class="hljs-attr">Color</span>=<span class="hljs-string">"#512BD4"</span> /&gt;</span>
</code></pre>
<p>Then just copy over the icon from the <code>dotnet new android</code> app?</p>
<p>This line has the icon:</p>
<ul>
<li><a target='_blank' href="https://github.com/xamarin/xamarin-android/blob/fbbdc9f9a80b12fc70fab13f40b02844f75da1c5/src/Microsoft.Android.Templates/android/AndroidManifest.xml#L3">https://github.com/xamarin/xamarin-android/blob/fbbdc9f9a80b12fc70fab13f40b02844f75da1c5/src/Microsoft.Android.Templates/android/AndroidManifest.xml#L3</a></li>
</ul>
<p>And then the <code>mipmap</code> files:</p>
<ul>
<li><a target='_blank' href="https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates/android/Resources">https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates/android/Resources</a></li>
</ul>

#### Benoit Hoffman on 10/14/2021, 00:54 AM: 

<p>Ha! I always said it was probably about the icon being loaded 😄<br>
Here is what I did:</p>
<p>1st, I went to see the so called fancy Maui icon just to make sure we were on the same page, and it could be worth noting that the line referencing an icon in my csproj was &lt;MauiImage&gt; and not &lt;MauiIcon&gt;. So I first tried to just edit this, no change.</p>
<p>Then I looked at the mipmap files (forgive me for any misuse of terms, I am not very familiar with Android dev environment) and realized they were none in my MAUI project under Platforms/Android/Resources/, so I copy pasted every mipmap folder from the Android app to the Platforms/Android/Resources.<br>
Finally I changed the &lt;application&gt; in AndroidManifest (since I guess here is the place I was supposed to “copy over the icon from the <code>dotnet new android</code> app”)</p>
<p>For the record, here is the line that was generated by MAUI template (note that it uses mipmap ressources, even though they had not been generated in my project):<br>
<code>&lt;application android:allowBackup=&quot;true&quot; android:icon=&quot;@mipmap/appicon&quot; android:roundIcon=&quot;@mipmap/appicon_round&quot; android:supportsRtl=&quot;true&quot;&gt;&lt;/application&gt;</code><br>
And here is the line generated by <code>dotnet new android</code> (note that it does add android:label, and the ressources used are differents):<br>
<code>&lt;application android:allowBackup=&quot;true&quot; android:icon=&quot;@mipmap/ic_launcher&quot; android:label=&quot;@string/app_name&quot; android:roundIcon=&quot;@mipmap/ic_launcher_round&quot; android:supportsRtl=&quot;true&quot;&gt;&lt;/application&gt;</code></p>
<p>I then had trouble about the color ic_launcher_background not being defined, so I copy pasted that line only from plain Android to MAUI Platforms/Android/Resources/values/colors.xml.<br>
Same for string/app_name, I copied the file into values/ folder.</p>
<p>After that I was finally able to try to build the app aand <em>drum rolls</em> it works!<br>
My application works as before, but my home screen does not crash anymore, I even dared scrolling in my phone until I could see the icon, and even though it’s now showing xamarin instead of MAUI, no crash to report.</p>
<p>Now the remaining questions are:</p>
<ul>
<li>Was the generation of my project somehow incorrect? Not having mipmap files generated and yet having the &lt;application&gt; referencing them seems odd. Even though the app and icon were working fine on the other, older phone</li>
<li>If, for whatever build magic, it was correct, what triggered the problem with my phone ? (Android 8.0, API 26, I realized I never said it yet)</li>
</ul>
<p>Anyway, thanks for your help <a target='_blank' href="https://developercommunity2.visualstudio.com/user/4907eedc-8e83-6418-970d-be28acc2b5b2/profile">Jonathan Peppers [MSFT]</a>!<br>
I’ll keep refreshing this thread anyway, in case you need more insight from my side to find the source of the problem itself, since I believe you’ll probably want this fixed for the Release Candidate in (hopefully) Q1 2022 😃</p>

---
### Original Solutions
(no solutions)

**Comment by jonathanpeppers** [comment]
This is really a dotnet/maui issue -- as there wasn't an issue with `dotnet new android`.

We can put it on the .NET 6 milestone for now.

**Comment by firecrauter** [comment]
It just happened to me, I was able to fix it by uninstalling the application with adb:
Activate programmer mode on the cell phone.
connect with usb to computer, file transfer mode. (not loading)
install adb on the computer.
open cmd.
"`adb devices`", if one appears, it is already connected and you can use the following commands:
1. `adb shell`
2. run the command "pm list packages" to get the list of package names of all apps present on your device.
3. `pm uninstall -k --user 0 <name of package>`
PS: don't include "package:"
example: `pm uninstall -k --user 0 com.companyname.MauiAppExample`

**Comment by TYMELAPSE** [comment]
Happened to me today. Managed to turn Developer Mode off as soon as it started happening hoping it would fix it. Phone is now too slow so I can't access Settings menu to turn Developer Mode back on without it crashing to home screen again before using. Phone is about as useful as a brick from now on...

**Comment by firecrauter** [comment]
You can save files by usb / file transfer to computer.
And do a factory reset by entering the "recovery mode"

pd: https://developer.android.com/studio/command-line/adb#Enabling

**Comment by jonathanpeppers** [comment]
@TYMELAPSE you should be able to just uninstall the app, as mentioned: https://github.com/xamarin/xamarin-android/issues/6455#issuecomment-994976126

```
adb unininstall com.yourcompany.yourapp
```
You can find the id to put here in `$(ApplicationId)` in your .csproj file.

From what I've seen the problem is related to some dashboards not able to support the newer mipmap-style app icons.

Has anyone been able to reproduce this problem in an emulator? Could you mention what devices and OS versions you have? Thanks!

**Comment by jonathanpeppers** [comment]
@TYMELAPSE a workaround for now would be to compare a `dotnet new android` project, and copy the app icons over -- and put a condition on `MauiIcon`:
```xml
<MauiIcon Condition="'$(TargetFramework)' != 'net6.0-android'" Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#512BD4" />
```

**Comment by firecrauter** [comment]
![Screenshot_20211216-140626](https://user-images.githubusercontent.com/7044466/146417197-a0a48feb-54d1-428c-830f-4bc7111f2c89.png)

Motorola e5

**Comment by mattleibow** [comment]
@Redth  I wonder if this is Samsung not handing adaptive icons, not handling the android vectors or just samsung.

**Comment by mattleibow** [comment]
We were not able to reproduce this with our Samsung running Android 8 and the Samsung Experience 9. However, looking at the stack trace in the log, it appears it is the android vector icon that is causing the issue.

It is very likely that the changes in https://github.com/dotnet/maui/pull/4069 will actually resolve this.

If anyone is able to reproduce this could they give us exact details about the device, such as:
 - Brand/model
 - OS version
 - Vendor "experience" version
 - Any custom launchers
 - Icon files that caused the crash

**Comment by jens-dittmer** [comment]
I just ran into the same issue on two of my older devices.
After deploying a basic MAUI app, both devices got bricked:
- Device 1: Redmi 5 Plus with Android 8.1 (showed only a black screen, even after restarting).
- Device 2: Lenovo TB-8504X with Android 8.1 (App Launcher kept crashing every 5 seconds, even after restarting).

Using ADB to uninstall the app (as proposed above) did work and both devices are working again.

I can confirm that the problem were the MAUI default svg icons - after removing all traces of them from the MAUI project, the app now works on both devices.

**Comment by dustyroberts** [comment]
I get the same issue with the following device:

Brand/model : Huawei P10 lite / WAS-LZ1
OS version :  Android 8.0.0

**Comment by mattleibow** [comment]
Just an FYI that this fix is coming in P13.

There is a new issue here: https://github.com/dotnet/maui/issues/4598

But I think the general consensus is that I cannot repro this at all, but happens for several people on devices and emulators seemiingly related to Android 8.x
