### ISSUE TITLE
Can't debug Xamarin Forms Application in Visual Studio 2022 Preview 6

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6458]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-debug-Xamarin-Forms-Application-in/1560574)._

---
[severity:It's more difficult to complete my work]
Well the good news is that the Xamarin project builds and deploys in Visual Studio 2022 preview 6

However I get the following

error: Failed to load AOT module 'System.Collections.Immutable' while running in aot-only mode: doesn't match assembly.

Which means that the debugger detaches.

---
#### Feedback Bot on 10/21/2021, 07:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jonathanpeppers** [comment]
If Ian Martin, the original poster can comment: "Why are you debugging AOT?"

That is going to be the main question here. It would be pretty poor build times for your development loop.

I'm unsure if debugging an AOT-build is supported.

**Comment by DavidStrachanLexacom** [comment]
I believe this is a duplication of: https://github.com/xamarin/Xamarin.Forms/issues/14871

**Comment by jonathanpeppers** [comment]
I don't see how https://github.com/xamarin/Xamarin.Forms/issues/14871 is related, because it is iOS.

**Comment by DavidStrachanLexacom** [comment]
@jonathanpeppers the original community ticket, was ambiguous and didn't mention android.

**Comment by polotto** [comment]
I found this problem updating my Xamarin Forms to latest stable version (5.0.0.2401)

**Comment by n8water** [comment]
Hello there,

Any updates on this?

I also have a problem with the combination of Visual Studio 20220 Preview 6 and Xamarin Forms debugging.
The execution of the Xamarin Forms code in Debug mode doesn't hit any of the set breakpoints. 
Is there anything special to consider?

**Comment by kunalprakash3891** [comment]
Hello, also asking for an update on this. 

I've moved my Xamarin project across from VS 2019 to VS 2022 and can no longer debug on Android. Breakpoints just do not trigger.
