### ISSUE TITLE
Xamarin.Android.FSharp.ResourceProvider v1.0.1

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6459]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/XamarinAndroidFSharpResourceProvider-/1554530)._

---
Xamarin F# (Android) project does not compile when the project references Xamarin.Android.FSharp.ResourceProvider v1.0.1

Downgrading to v1.0.0.28 version works

Steps to reproduce:
1. Create F# Xamarin project.
2. Update packages
3. Build project

---
#### Feedback Bot on 10/14/2021, 11:30 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jonathanpeppers** [comment]
If the original poster, could share a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) we can take a look, thanks!

**Comment by pjcollins** [comment]
This will be fixed in https://github.com/xamarin/Xamarin.Android.FSharp.ResourceProvider/pull/12, and we will attempt to unlist the v1.0.1 package.
