### ISSUE TITLE
API Level 31 - Wiki page "JDK 11 Warning"

### ISSUE THREAD

**Issue by domedellolio** [xamarin/xamarin-android#6466]
Hi everyone,

I was looking into this article https://github.com/xamarin/xamarin-android/wiki/JDK-11-Warning#set-tfv 
since I'm upgrading to API level 31. 

What I see is that the article contains a possible mistake in the step 3 "Set $(TargetFrameworkVersion) to v12.0.".

Basically, this is true for Visual studio for Mac while for Windows I can only use version 11.0.99 which make me a bit lost, since I need to have different .csproj file in these 2 platforms.

Anyone can help in understanding me, why we have differences here?

CC: @jonpryor

**Comment by jpobst** [comment]
The latest VS2019 doesn't appear to have the `11.0.99` -> `12.0` change yet.  I think it's coming in the next service release.

I think your current options are:
- Stay with API-30 until VS2019 service release comes out
- Use a VS2022 preview build (https://visualstudio.microsoft.com/vs/preview)

**Comment by domedellolio** [comment]
I see the second option is not yet viable as well.
Installing side by side VS 2022 I see it only have up to API 27. That is really strange as well

**Comment by jpobst** [comment]
That does not seem correct, I definitely have 12.0 in VS2022.

![image](https://user-images.githubusercontent.com/179295/140403397-6335896c-82f6-4eb8-aaef-a96d2b002d85.png)

**Comment by domedellolio** [comment]
This is not what I see, wow.
It can be specific of my local configuration since I’m running side by side. Will check tomorrow and update the thread accordingly 

thanks!

**Comment by domedellolio** [comment]
This is how Android SDK utility looks like in VS 2022
![image](https://user-images.githubusercontent.com/11771925/140499186-21a70ebb-8ddd-4aad-aa1e-9334cd08e0b6.png)

This is how Androdi SDK utility looks like in VS 2019
![image](https://user-images.githubusercontent.com/11771925/140499331-af87d357-c445-4245-a465-4119f41040f3.png)

...and finally yes I see Android 12 into property panel
![image](https://user-images.githubusercontent.com/11771925/140499547-5010fbc9-3a2a-4163-9e9d-421d05fce95c.png)


No so sure why, BTW we will wait for final release of VS 2022 and eventually ask them :)

Thanks

**Comment by SvetBonev** [comment]
The workaround is to go to "Tools/Options/Xamarin/Android Settings" and click OK.
Let me know if it helps.

Thanks!

**Comment by jpobst** [comment]
The VS2019 16.11.6 service release was released today, containing Android 12.  🎉

**Comment by inforithmics** [comment]
Android 12 cannot be used in Visual Studio 2019. Opening the Xamarin Android Settings page changes back the used JDK 
From:
C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot
To:
C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot
And therefore an Android Build with 12 Fails (Because Android 12 needs JDK 11).

**Comment by domedellolio** [comment]
Guys, thank you very much. Your suggestions solved my pain.
May I ask also an advise on how to build Android API Level 31 on App Center? Or do you have a contact I may reach?

Thanks again

**Comment by jpobst** [comment]
If you want to build with a different Xamarin.Android from what is provided on AppCenter, I think you can install one of your choosing using `boots`:

https://devblogs.microsoft.com/xamarin/boots-xamarin-ci/#app-center
