### ISSUE TITLE
xamarin-android linux artifacts

### ISSUE THREAD

**Issue by rokups** [xamarin/xamarin-android#6472]
Now that .NET6 is released, maybe it would be a good time to release nightly artifacts of xamarin-android workload for linux, as discussed in https://github.com/dotnet/maui-samples/issues/61?

Thanks

**Comment by fogzot** [comment]
Yes, please. I understand why MS does not want to support *running* MAUI on Linux but making it impossible to *develop* on it is clearly sending the message that Linux is a second class citizen in the dotnet exosystem.

**Comment by redradist** [comment]
@jonpryor Does it mean that now I can develop Android application on Ubuntu without any hack ?
If yes, then is there some example ?

**Comment by Cheesebaron** [comment]
Have you tried: `dotnet workload install android`?

**Comment by rokups** [comment]
Something does not quite work. Looks like some package can not be found.

<details>

```
% sudo dotnet workload install android
[sudo] password for rk: 

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.102

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Installing workload manifest microsoft.net.sdk.maccatalyst version 15.0.101-preview.11.551…
Installing workload manifest microsoft.net.sdk.ios version 15.0.101-preview.11.551…
Installing workload manifest microsoft.net.sdk.macos version 12.0.101-preview.11.551…
Installing workload manifest microsoft.net.sdk.tvos version 15.0.101-preview.11.551…
Installing workload manifest microsoft.net.sdk.android version 31.0.101-preview.11.117…
Installing workload manifest microsoft.net.workload.mono.toolchain version 6.0.3…
Installing workload manifest microsoft.net.sdk.maui version 6.0.101-preview.11.2349…
Installing workload manifest microsoft.net.workload.emscripten version 6.0.2…
Installing pack Microsoft.Android.Sdk version 31.0.101-preview.11.117...
Workload installation failed. Rolling back installed packs...
Installing workload manifest microsoft.net.sdk.maccatalyst version 15.0.101-preview.9.31…
Installation rollback failed: Failed to install manifest microsoft.net.sdk.maccatalyst version 15.0.101-preview.9.31: The transaction has aborted..
Rolling back pack Microsoft.Android.Sdk installation...
Workload installation failed: microsoft.android.sdk.linux::31.0.101-preview.11.117 is not found in NuGet feeds https://api.nuget.org/v3/index.json".
```

</details>

**Comment by SwaLLoweD** [comment]
In my experience, minimum dotnet version 6.0.2 is needed for android workload installs.. And as a side note, on arch-linux, even though the package versions are 6.0.2, the real installed dotnet version is actually 6.0.102 (something is not right with arch packages, don't know about ubuntu).. I had to manually download and install the up-to-date package from dotnet site, and then "dotnet workload install android" command did start working and my android projects did successfully compile.. 

For some reason i do remember i had to install dotnet packages system-wide, for my own use case.. But i don't quite remember why.. Android workload install was working fine before i installed dotnet system-wide.. That, i do remember..

**Comment by redradist** [comment]
@Cheesebaron
> Have you tried: `dotnet workload install android`?

I've tried and it is working !! Android workload for Linux is finally exists !!
I waited for it for years !!

But I've faced with another issue ... When I create project during compilation I have the following error:
```console
Xamarin.Android.Tooling.targets(69, 5): [XA5300] The Android SDK directory could not be found. Check that the Android SDK Manager in Visual Studio shows a valid installation. To use a custom SDK path for a command line build, set the 'AndroidSdkDirectory' MSBuild property to the custom path.
```

Is there a special way of creation of application ??

**Comment by redradist** [comment]
@SwaLLoweD Do you have example of creation application on Linux ?
I was able to install android workload, but unfortunately created application is not compiled !!

**Comment by Cheesebaron** [comment]
@redradist perhaps if you set the environment variable: `ANDROID_SDK_ROOT` to the root of the android sdk folder. Additionally you may also need to set the `JAVA_HOME` variable.

**Comment by SwaLLoweD** [comment]
You do need android sdk installed somewhere.. I install and manage it through android studio on linux.. And then, you do add "AndroidSdkDirectory=/<pathtosdkdir>" environment variable to the dotnet build/run commands... There used to be some xamarin-android way to automatically do that on linux.. By editing and adding a few lines to the .csproj file.. I don't know if that still works.. I just added that environment variable to my ".profile", problem solved..

**Comment by redradist** [comment]
@Cheesebaron @SwaLLoweD Thanks !!
When I added `AndroidSdkDirectory` project was able to compile !! I cannot believe !! I waited for so long ...

Guys, one addition question, how to upload the application on my Android phone using dotnet command line ?
And is there a way to debug a build application for example using VS Code ?

**Comment by SwaLLoweD** [comment]
After connecting adb (manually if necessary), dotnet run command should deploy the apk on the connected device, that should be easy to set up and should work for anything.. 

As for debugging: I can debug a maui application on an android emulator fine with vscode, but it's not that easy to describe the setup, there are guides online though.. You need to build the project with "AndroidAttachDebugger=true" parameter, specify a sdb port through "AndroidSdbHostPort" parameter during the build, and then attach a mono debugger to the specified port basically.. So you need tasks and launch settings configured properly and all the required extensions installed (c#, mono debug) for it to work, which you need to do manually.. If it works with the emulator, it should work with a hardware device, and if it works with maui android app, it should work with xamarin android native i think, they all use the same plumbing after all.. But to be exact, i only tried a maui app on an emulator for debugging purposes, so i'm not certain about the rest..

**Comment by redradist** [comment]
@SwaLLoweD You are right !!
It do not work from `Rider`, but it works from command line with just `dotnet run` !! It is unbelievable ...
Guys how to choose virtual devices using `dotnet` command line ?

**Comment by SwaLLoweD** [comment]
Rider has no support for dotnet 6 xamarin or maui parts yet.. It simply does not work.. The xamarin support rider has is for the older dotnet sdks, and you have to compile xamarin-android from source to make them work.. It does not understand net6-android target or any xamarin or maui target yet and the current eap has no developments on that front either.. So, it seems like it will be quite a while.. Vscode seems like the only option on linux to develop xamarin related things for now.. 

And that parameter you're looking for is probably `/p:_DeviceName=`.. There are again documents online describing its usage.. I rarely need it, so can't speculate on it..

**Comment by MandeepSingh-MS** [comment]
Hello, I want to develop `maui` apps on `ubuntu`.
I installed the required tools but it is not working.



I created a new `dotnet maui` project. Then I installed `maui-android` workload. I opened the project with `vs code` but `OmniSharp` gives following error

`System.DllNotFoundException: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory at SkiaSharp.LibraryLoader.Linux.dlopen(String path, Int32 mode) at SkiaSharp.LibraryLoader.Linux.dlopen(String path, Boolean lazy) in D:\a\1\s\binding\Binding.Shared\LibraryLoader.cs:line 200 at SkiaSharp.LibraryLoader.LoadLibrary(String libraryName) in D:\a\1\s\binding\Binding.Shared\LibraryLoader.cs:line 129 at SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName) in D:\a\1\s\binding\Binding.Shared\LibraryLoader.cs:line 30 at SkiaSharp.SkiaApi.<>c.<.cctor>b__1831_0() in D:\a\1\s\binding\Binding\SkiaApi.cs:line 15 at System.Lazy 1.ViaFactory(LazyThreadSafetyMode mode) --- End of stack trace from previous location ---`


then I tried to build the project with `dotnet build` and it gives the error

`dotnet/packs/Microsoft.Maui.Resizetizer.Sdk/6.0.200- preview.14.5099/targets/Microsoft.Maui.Resizetizer.targets(475,9): error MAUI0000: System.DllNotFoundException: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory`


I set the environment variable `LD_DEBUG=libs` and again run the `dotnet build` then there is the following error
`dotnet/packs/Microsoft.Android.Sdk.Linux/31.0.200-preview.14.106/targets/Microsoft.Android.Sdk.Tooling.targets(32,5): error XA0111: Unsupported version of AAPT2 found at path`

**Comment by pjcollins** [comment]
@MandeepSingh-MS thanks for the details, would you mind opening a new issue to track this? If you could please attach a binary log file (or a full diagnostic build log) for the aapt2 error that would help us better understand what may be going wrong. Thanks!

**Comment by MandeepSingh-MS** [comment]
@pjcollins  Thanks for the reply.  I examined the project and logs and finally found that the problem is with `Microsoft.Maui.Resizetizer.Sdk`.

`Microsoft.Maui.Resizetizer.Sdk` is unable to process `.svg` files that `dotnet maui` used for app logo, splash screen etc.

When I code comment the `<MauiIcon>` , `<MauiSplashScreen>` and `<MauiImage>` in `.csproj` the project build successfully.

**Comment by igorgue** [comment]
> I set the environment variable `LD_DEBUG=libs` and again run the `dotnet build` then there is the following error `dotnet/packs/Microsoft.Android.Sdk.Linux/31.0.200-preview.14.106/targets/Microsoft.Android.Sdk.Tooling.targets(32,5): error XA0111: Unsupported version of AAPT2 found at path`

@MandeepSingh-MS how did you get rid of this problem?

**Comment by MandeepSingh-MS** [comment]
@igorgue  I was targeting only `Android`. 

I code commented the `<MauiIcon>` , `<MauiSplashScreen>` and `<MauiImage>` in `.csproj` file.

Then I created the required `Icons/Images` and moved them to the `Platforms/Android/Resources`.

**Comment by igorgue** [comment]
Yeah thank you! I got it to work too, well kinda, I wish it was smoother and you could use the images...
