### ISSUE TITLE
Content Provider fails to return queries if the underlying app is closed

### ISSUE THREAD

**Issue by KijongHan** [xamarin/xamarin-android#6476]
### Description
In a situation where one app has a content provider (with the underlying content in this case specifically being a sqlite database) and another app tries to access that content while the first app with the content provider is closed, the second app content provider query (or cursor) is null. This doesn't appear to be the case if the first app is running, in this case the content provider query is returning results as expected.

### Steps to Reproduce

1. Setup one app as specified in this example: https://docs.microsoft.com/en-us/xamarin/android/platform/content-providers/custom-contentprovider, in addition to specifying the provider read/write permissions as necessary (and specifying the permission in the manifest file)
2. Setup another app to consume that content provider query, in addition to specifying the necessary use-permissions tags in the manifest file
3. Deploy the first app with the content provider. Close the app
4. Deploy the second app, and run a content provider query as specified in https://docs.microsoft.com/en-us/xamarin/android/platform/content-providers/custom-contentprovider

### Expected Behavior
The content provider query should return results, and the cursor for that content provider should not be null

### Actual Behavior
The cursor is null

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: ?
- Platform Target Frameworks:
  - Android: 11.0
- Affected Devices:
  - Samsung SM-A315G (API 29)

### Reproduction Link

https://github.com/KijongHan/XF-Issue-ContentProvider
- TestPOC is the consumer
- TestPOC2 is the provider

### Workaround

No

**Comment by grendello** [comment]
Hi @KijongHan, does any of the app crash in any way? Do you see any managed exceptions or native crashes in the logs? At this point it doesn't look to me like an issue with the Xamarin.Android **native** runtime.

**Comment by KijongHan** [comment]
Hi there, no there are no crashes that occur

**Comment by KijongHan** [comment]
But as far as I am aware this issue doesn't occur with for example native java/kotlin
