### ISSUE TITLE
Can't debug with VS 2022 17.1.0 Prev 1.0

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#6480]
I can't debug at all. Hangs on the splash screen. A breakpoint in OnCreate of the MainActivity is never hit as I get the following in the debugger. 

```
System.InvalidProgramException
  Message=Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally
```
A release build runs fine, except for what was reported in #6479.

Tried on another machine, and get the same result. Both machines Windows 11

Reverted back to VS 2022 17.0.0 and can debug normally again.

**Comment by lanarchyste** [comment]
I have the same error and behavior with Visual Studio for Mac 8.10.13 (build 11) and Xamarin.Android 12.1.99.75 (version that fixes the build with the exported attribute)

**Comment by tspersian** [comment]
same vs 17.1.0 Preview 1.1 
android 7 (Galaxy A7)

**Comment by steveisok** [comment]
@thaystg can you please take a look at this?

**Comment by thaystg** [comment]
Can you please help me to reproduce it? What kind of project are you creating?

**Comment by gmck** [comment]
@thaystg  _What kind of project are you creating?_

Seems a strange question! What type of answer are you looking for? My own app is a single activity/multi fragment app using the NavigationComponent, although I can't see how that relates to a debugging problem that now hangs on the splash screen of the app and never even gets to the OnCreate of the MainActivity. This wasn't a problem until 17.1.0 Prev 1.0. So it would seem to indicate that something changed between 17.0.0 and 17.1.0 Prev 1.0.  17.1.0 Prev 1.1 also has the same problem.

If the above is not what you are looking for could you please be more specific re the question of the kind of project?

**Comment by thaystg** [comment]
Two questions:
1) If you create a new project from the templates list of VS, you can reproduce the error? What kind of project should I create to reproduce it?
2) If you start the app without debugging, I mean, the app in debug mode but started using this option:
![image](https://user-images.githubusercontent.com/4503299/142520234-92a35217-6b40-426c-b981-f04a281a6576.png)

Thanks a lot.

**Comment by gmck** [comment]
@thaystg. Thanks for your reply. No, I can't reproduce it when I create say a Blank app from the templates.

If I start the app via Start Without Debugging - it just hangs on the splash screen. Hence, that was why I tried to debug it and got the error.  The debugger is telling me it is not my code e.g.

`Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code).`

I really can't remember what template I used when I first created the app, a couple of years ago. 
Whenever I create a new test app, I invariably use the Blank template.  I then remove any reference to Xamarin.Essentials, change the default namespace to "com.companyname.whatever", edit resource.designer.cs to match the namespace for the global attribute and its namespace. Change the project to Android 11 (or whatever ) set the min SDK to say 7.0  Then update Xamarin.AndroidX.AppCompat and Xamarin.Google.Android.Material to the latest versions. Clean and rebuild and check it runs. If it runs ok without errors got on with whatever I need to do for the test app. I'm sure others would do it differently, but that is my minimum setup when starting a new test app. It would be nice if all that could be done automatically, but it is not something you do every day, so you put up with out of date templates. As an example, just look at the template for creating a new fragment. It still uses Android.App.Fragment that was deprecated ages ago. You sure wouldn't want to be a newbie starting with Xamarin.Android!!

If I can debug with 17.0.0, but can't with 17.1.0 P1.0  and now 17.1.0 P1.1, then surely it must be something that changed between VS 2022 release and the first preview.
 
Please advise if you want me to try something else.

**Comment by aarcoraci** [comment]
Same thing is happening to me:
A couple of months ago I created a AppShell app and it was working fine on VS2019 up to date (as for 19 Nov. 2021). I transitioned to VS2022 preview (macos) and I get the same problem.

Ive downloaded .Net 6 for the m1 architecture.

```
[mono] Unhandled Exception:
[mono] System.InvalidProgramException: Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally
[mono] 
[mono] 
[mono]   at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args) [0x000e8] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:173 
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally
[mono-rt] 
[mono-rt] 
[mono-rt]   at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args) [0x000e8] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:173 


```

**Comment by aarcoraci** [comment]
Just to add to the discussion, a colleague using VS2022 17.0.0 (on a Windows 11 machine) is not having this issue. Exactly the same code as me

**Comment by steveisok** [comment]
@grendello it's not clear if this is a runtime / debugger issue yet.  Would the linker be involved in any debug configuration?

**Comment by grendello** [comment]
@steveisok no, linker is off (by default) for Debug builds

**Comment by tspersian** [comment]
i tried many thing to find whats different from my project that i can run one but not another so i compare every thing from Manifest to dependencies even every part of code noting works anyway. so after i disable aapt2 and rebuild it give me errors so i enable it again and enable fast deploy and set debugging information to full (Build -> Advanced...) i can now deploy and debug in android 7 phone again...

 i don't know exactly what happened but its works for me maybe just need simple rebuild? or just needs some love?

**Comment by dellis1972** [comment]
@gmck @tspersian  can you try and disable `AndroidAddKeepAlives` in your csproj?

`<AndroidAddKeepAlives>False</AndroidAddKeepAlives>`

See if that helps.

**Comment by gmck** [comment]
@dellis1972 

Made no difference, still the same error.

**Comment by dellis1972** [comment]
I don't think this is the Android LinkAssembliesNoShrink task. 
@gmck The best bet is to get us a full diagnostic debug build (from clean) so we can see what the LinkAssembiesNoShrink task is doing so we can rule that out. 

To me this is looking like a mono issue since the Mono.SystemDependencyProvider is not something we control from Xamarin.Android.

**Comment by gmck** [comment]
@dellis1972 

Just tried again now that I've converted the app to Android 12 - still the same problem with the debug build. Sorry about the delay.

Attaching the build log as requested.

[testbuild.zip](https://github.com/xamarin/xamarin-android/files/7658377/testbuild.zip)

**Comment by dellis1972** [comment]
Hmm. Looking at the logs `LinkAssembliesNoShrink` did not make any changes to the assemblies at all (which I kinda suspected). So this is beginning to look like a mono issues possibly. 

@steveisok any further ideas on what this might be?

**Comment by sam-skedulo** [comment]
Have this issue in Visual Studio for Mac 2022 17.4729 on Macbook M1 Pro

<details>
<summary>Visual Studio for Mac Build Info</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.0 Preview (17.0 build 4729)
Installation UUID: 67c4fcf4-3360-41d2-b60f-d0c2ad6439f0
	GTK+ 2.24.23

Mono Framework MDK
Runtime:
	Mono 6.12.0 (2020-02/5ce143a1a88) (64-bit)
	Package version: 612000158

Roslyn (Language Service)
4.1.0-1.21511.14+c09d760509f00afadf0fa9b6ee7d0c53b70943ca

NuGet
Version: 6.0.0.262

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.100/Sdks
SDK Version: 6.0.100
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 6.0.0

Xamarin.Profiler
Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 12.1.99.56 (Visual Studio Community)
Commit: xamarin-android/main/43243b4
Android SDK: /Users/sam/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/main@79744f61
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.36.0@a575761
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@a5194e9

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.1.0.14
Hash: 9c65d8a
Branch: remotes/origin/backport-pr-548-to-main~1
Build date: 2021-11-04 15:16:32 UTC

Android Device Manager
Version: 17.1.0.13
Hash: 1de1208
Branch: remotes/origin/anchimna/missingLibCmdtoolsFix~1
Build date: 2021-11-04 15:16:32 UTC

Apple Developer Tools
Xcode 13.1 (19466)
Build 13A1030d

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 15.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:56-0400

Xamarin Designer
Version: 17.1.0.43
Hash: 1841a0e79
Branch: remotes/origin/main
Build date: 2021-11-04 15:16:29 UTC

Build Information
Release ID: 1700004729
Git revision: 39b9401f81b4c2246a15990f370e17e42f6d74d0
Build date: 2021-11-04 11:15:22-04
Build branch: release-17.0

Operating System
Mac OS X 12.0.1
Darwin 21.1.0 Darwin Kernel Version 21.1.0
    Wed Oct 13 17:33:01 PDT 2021
    root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 x86_64

```
</details>

**Comment by steveisok** [comment]
@gmck Do you have XAML Hot Reload on?  If it is on, can you turn it off?

**Comment by steveisok** [comment]
Also, is fast deployment enabled?  @jonathanpeppers @grendello would that potentially cause any interference?

**Comment by dellis1972** [comment]
I can't see how fast dev would cause. `Invalid IL code in` error for that assembly.

**Comment by lambdageek** [comment]
> I can't see how fast dev would cause. `Invalid IL code in` error for that assembly.

If we can repro the issue with fast dev, we can ask OP to pull System.dll from the device using adb and check if it's  corrupted somehow.

If the issue only repros without fastdev then it might be a bug in the assembly loader in Mono or the XA assembly loader hook that helps us to load assemblies from inside APKs.

**Comment by lambdageek** [comment]
One other thing we can try is to set the environment variable `MONO_VERBOSE_METHOD=Mono.SystemDependencyProvider:Initialize` and launch the app with debugging.  Then collect the adb log and see what Mono thinks is inside that method.

If I'm reading https://github.com/xamarin/xamarin-android/blob/main/Documentation/workflow/SystemProperties.md#custom-android-system-properties-used-by-xamarinandroid correctly, something like this should work:

```
adb shell setprop debug.mono.env 'MONO_VERBOSE_METHOD=Mono.SystemDependencyProvider:Initialize'`
```

XA folks: please correct me if that's wrong

**Comment by agneszitte-nventive** [comment]
On my side I don't get the `System.InvalidProgramException Message=Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally` anymore by removing `<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>` in the Android .csproj

**Comment by jonathanpeppers** [comment]
@agneszitte-nventive if turning _on_ Fast Deployment solves your issue (`EmbedAssembliesIntoApk=true` is Fast Dev off, it toggles opposite of the property).

Then I think the issue might be related to: https://github.com/dotnet/runtime/issues/62201

As another workaround, if you want Fast Deployment off (like if you need to Debug on an older device), you could try checking every ABI:

![image](https://user-images.githubusercontent.com/840039/145466462-b1f88431-48af-4e8c-bf54-ebd2ebf34f8d.png)

**Comment by gmck** [comment]
> @gmck Do you have XAML Hot Reload on? If it is on, can you turn it off?

@steveisok My app is Xamarin.Android, I don't think Hot Reload is even available for that project type. I've never even looked to see if it is on or not, as haven't been able to open any of my layout files without an error with the Xamarin.Designer since Feb 2020 so I wouldn't be able to use it anyway. I'm presuming it must be off by default.

**Comment by jonathanpeppers** [comment]
It's this checkbox:

![image](https://user-images.githubusercontent.com/840039/145496190-7c56d4d8-676b-4e88-909d-54b3297daab9.png)

@steveisok is probably thinking about another issue some folks are hitting, where XAML hot reload loads an assembly the same as  your app (but a different version), and this causes a crash.

It might not be your issue at all, if your app is not Xamarin.Forms.

**Comment by gmck** [comment]
@agneszitte-nventive, @jonathanpeppers, @dellis1972, @steveisok, @lambdageek  

After reading the conversation above, it twigged a memory that when I deployed a debug build to an old Samsung Tablet (7.1.1) I had to add <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk> to make it deploy. Unfortunately with the Preview version, I hadn't removed that. Then when 17.1.0 Preview 1.1 was released the project in that folder still had it unchecked and therefore failed.
 
Now, as soon as I've checked fast deployment I can debug with 17.1.0 Preview 1.1. Note @tspersian  was also debugging on an old Samsung too.

I went back to my old tablet to recheck and had to make it true again to deploy a debug version. That now hangs on the splash screen and when you debug it you get the original error. The release build works ok though, and I doubt I'll ever want to debug on something as slow as that thing. 

Do you think we could have a new warning (a reminder) when debugging and fast deployment is left unchecked - just for us old guys with failing memories?

**Comment by aarcoraci** [comment]
Hello,
just wanted to check if anyone has found a fix or workaround for this (Ive tried everything on this discussion). A few days ago my VS2022 got updated but Im still experiencing the problem when I try to debug on an Android phone (a new phone).

```
Visual Studio Community 2022 for Mac Preview
Version 17.0 Preview (17.0 build 5186)
Installation UUID: c81571c2-f2fa-4c93-afd3-7d8081c78b30
	GTK+ 2.24.23
```

Thanks !

**Comment by jonathanpeppers** [comment]
@aarcoraci do the workarounds not work?

1. Enable Fast Deployment
2. (on an old enough device you can't do 1), instead enable all ABIs. [see screenshot](https://github.com/xamarin/xamarin-android/issues/6480#issuecomment-990194681)

**Comment by captainjono** [comment]
> @aarcoraci do the workarounds not work?
> 
>     1. Enable Fast Deployment
> 
>     2. (on an old enough device you can't do 1), instead enable all ABIs. [see screenshot](https://github.com/xamarin/xamarin-android/issues/6480#issuecomment-990194681)

None of these workarounds solve my issue deploying to an older Chromebook device. cant fast deploy, selecting all ABIs already. Please advise.

```
Microsoft Visual Studio Enterprise 2022
Version 17.1.0 Preview 2.0
VisualStudio.17.Preview/17.1.0-pre.2.0+32104.313
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00476-80000-00000-AA788
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2022   00476-80000-00000-AA788
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.1.229.41008
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.1.229.41008
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.1.229.41008
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.1.229.41008
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.1.0-2.21607.5+4e139d3fdfc73247aece2e29d7abcecd0d4f6464
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   6.5.0+76d4669002
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.1.10 (65f98f5)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.31201.1 Commit Hash:3b3b7a244d711249ddd13dba98e08336cde83120
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2160703+95aa380e1d4fd51f7f032aa44e903c892f6bde89
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   17.0.62111.24160
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.1203.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-2.21607.5+4e139d3fdfc73247aece2e29d7abcecd0d4f6464
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21561.4+56d49a0f5a876dbadeaf34af91972c7a10de858b
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput64   2021.3
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

Xamarin   17.1.0.269 (main@be6679a)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.1.0.87 (remotes/origin/main@d50fb5635)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.99.117 (main/c52e6e6)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@7f1a5ab1
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.37.0@88e12a9
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@35c89dd


Xamarin.iOS and Xamarin.Mac SDK   15.3.0.215 (faa966ba2)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by dellis1972** [comment]
Are you able to provide the error you seeing ? Is it the same `Invalid IL code` as reported in the initial report or is it something different?

**Comment by captainjono** [comment]
@dellis1972 

> Acer Chromebook R13 (9.0 - 28)

```
System.InvalidProgramException
  Message=Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally
```

**Comment by dellis1972** [comment]
@captainjono and fast deployment does not work on this Chromebook? Do you know what error you get when trying to use fast deployment? It might be useful to post the sections of your `csproj` which show your project configuration settings so we can take a look.

**Comment by captainjono** [comment]
.csproj

```
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{FA85A68C-28D9-48F4-A232-B038E20E203B}</ProjectGuid>
    <ProjectTypeGuids>{EFBA0AD7-5A72-4C68-AF49-83D382785DCF};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <OutputType>Library</OutputType>
    <RootNamespace>JanisonReplay.Droid</RootNamespace>
    <AssemblyName>JanisonReplay.Droid</AssemblyName>
    <TargetFrameworkVersion>v11.0</TargetFrameworkVersion>
    <AndroidApplication>True</AndroidApplication>
    <AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>
    <AndroidResgenClass>Resource</AndroidResgenClass>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
    <MonoAndroidResourcePrefix>Resources</MonoAndroidResourcePrefix>
    <MonoAndroidAssetsPrefix>Assets</MonoAndroidAssetsPrefix>
    <AndroidTlsProvider>
    </AndroidTlsProvider>
    <AppSettingsDirectory>$(MSBuildThisFileDirectory)</AppSettingsDirectory>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
    <AndroidLinkMode>None</AndroidLinkMode>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ConsolePause>false</ConsolePause>
    <AndroidSupportedAbis>armeabi-v7a;x86;x86_64;arm64-v8a</AndroidSupportedAbis>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidEnableMultiDex>true</AndroidEnableMultiDex>
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <MandroidI18n />
    <AndroidCreatePackagePerAbi>true</AndroidCreatePackagePerAbi>
  </PropertyGroup>
  ```
  
  when i enable fast-deployment
  
  > Severity	Code	Description	Project	File	Line	Suppression State
Error		XA0137: The 'run-as' command failed with 'run-as: setegid(AID_PACKAGE_INFO) failed: Operation not permitted
'.
Fast Deployment is not currently supported on this device.
Please file an issue with the exact error message using the 'Help->Send Feedback->Report a Problem' menu item in Visual Studio
or 'Help->Report a Problem' in Visual Studio for Mac.
Please set the 'EmbedAssembliesIntoApk' MSBuild property to 'true' to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor.		 	0

**Comment by dellis1972** [comment]
@captainjono I'm afraid this error

```
The 'run-as' command failed with 'run-as: setegid(AID_PACKAGE_INFO) failed: Operation not permitted
```

Is comming from the `run-as` tool on the device. Which means fast deployment will not work on that particular device. This is normally because the maker of the device has made changes to the underlying OS.

As for why the `AndroidSupportedAbis` is not working with fast dev off is odd. @jonathanpeppers any ideas on this one?

**Comment by jonathanpeppers** [comment]
I don't understand the error:

```
System.InvalidProgramException
  Message=Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally
```

When I look at the code:

https://github.com/mono/mono/blob/45efaa3b6f9bb6aa5e6e2ef82d08ad849a40a34c/mcs/class/System/Mono/SystemDependencyProvider.cs#L46-L54

It's like the `finally` block generated by `lock` statement is invalid IL???

I think we'll need Mono runtime folks to look into this? @captainjono does your app work on an Android emulator or other device that is *not* a Chromebook?

**Comment by dellis1972** [comment]
Can people try changint the `DebugType` from `Full` to `portable` and see if that helps?

**Comment by dellis1972** [comment]
@captainjono see https://github.com/xamarin/xamarin-android/issues/6480#issuecomment-1020301413

**Comment by dr1rrb** [comment]
@dellis1972 On my side setting `DebugType` to `portable` was not enough, I had also to enable fast deploy and add the `<AndroidUseAssemblyStore>false</AndroidUseAssemblyStore>` to finally be able to debug my project 🎉
