### ISSUE TITLE
Android 12 and KeyStore

### ISSUE THREAD

**Issue by dubstepadii** [xamarin/xamarin-android#6481]
### Steps to Reproduce

Running existing app on Android 12 emulator/device fails on saving key entry in KeyStore

### Expected Behavior
Key entry is saved within KeyStore

### Actual Behavior

>   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <ab8d28d5e9d9431491b8f96d5d4df9d7>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <ab8d28d5e9d9431491b8f96d5d4df9d7>:0 
  at Java.Security.KeyStore.SetKeyEntry (System.String alias, Java.Security.IKey key, System.Char[] password, Java.Security.Cert.Certificate[] chain) [0x00081] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Java.Security.KeyStore.cs:1729 
  at IFBaltics.MobileApplication.Droid.Features.Security.AppCertificate.ImportChain (System.Byte[][] chain) [0x000b0] in C:\Repos\mobile-app-v2\IFBaltics.MobileApplication.Droid\Features\Security\AppCertificate.cs:190 
  --- End of managed Java.Security.GeneralSecurityException stack trace ---
java.security.KeyStoreException: **Can only replace keys with same alias: if-auth != if-auth in the same target domain: 0 != 0**
	at android.security.keystore2.AndroidKeyStoreSpi.assertCanReplace(AndroidKeyStoreSpi.java:589)
	at android.security.keystore2.AndroidKeyStoreSpi.setPrivateKeyEntry(AndroidKeyStoreSpi.java:436)
	at android.security.keystore2.AndroidKeyStoreSpi.engineSetKeyEntry(AndroidKeyStoreSpi.java:268)
	at java.security.KeyStore.setKeyEntry(KeyStore.java:1179)

### Version Information

App sample ->
[KeyStoreAndroid12.zip](https://github.com/xamarin/xamarin-android/files/7525393/KeyStoreAndroid12.zip)

<details>

Microsoft Visual Studio Professional 2022
Version 17.0.0
VisualStudio.17.Release/17.0.0+31903.59
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ASP.NET and Web Tools 2019   17.0.789.48259
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.0.789.48259
Azure App Service Tools v3.0.0

C# Tools   4.0.0-6.21526.21+c7d6f9fab845ffd943216da465022744e7d35f22
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.0-6.21526.21+c7d6f9fab845ffd943216da465022744e7d35f22
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.336 (d17-0@29731f2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.182 (remotes/origin/d17-0@ea204898d)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.17 (9e779b0)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9

Xamarin.iOS and Xamarin.Mac SDK   15.0.0.18 (577ff6329)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

**Comment by jpobst** [comment]
@jonathanpeppers @dellis1972 Does your work with Android's KeyStore give you any insight here?

**Comment by dubstepadii** [comment]
@jonathanpeppers will try to add it.

**Comment by dubstepadii** [comment]
Any updates?

**Comment by dubstepadii** [comment]
After checking logs in PROD in our end to get some statistics how many users are affected by this issue, seems that issue is with Google Pixel devices, as some users using Samsung/Xiaomi  devices with Android 12 did not have it.

**Comment by brunocapu** [comment]
Just found out this is a bug on new keystore2 code. Im not a Java expert, therefore not a masochist, but it looks like a bad string comparison:
https://cs.android.com/android/platform/superproject/+/android-12.0.0_r4:frameworks/base/keystore/java/android/security/keystore2/AndroidKeyStoreSpi.java;l=582;drc=android-12.0.0_r4

They already tracked the issue: https://issuetracker.google.com/issues/197556146
The workaround should be using the same string object from key descriptor as the alias. Did not test yet.
Regards

**Comment by dubstepadii** [comment]
Latest Security update for Google Pixel devices have fixed this issues.
