### ISSUE TITLE
MONO GC log messages are not being printed

### ISSUE THREAD

**Issue by jfichtner** [xamarin/xamarin-android#6483]
These log messages used to be printed, up to some fairly recent (maybe last 6 months) Visual Studio release. I verified that VS version 16.3.10 does print these messages, but my current version 16.10.1 does not.
(See https://stackoverflow.com/questions/69829907/xamarin-android-no-longer-printing-mono-gc-log-messages)

### Steps to Reproduce
1. Create new Xamarin.Android app
2. Call GC.Collect() from within the app
3. Run app and observe logcat output

### Expected Behavior
Log messages similar to the following should be printed to the log when GC.Collect() is called:
`04-11 16:46:22.658 D/Mono    (14892): GC_BRIDGE waiting for bridge processing to finish
04-11 16:46:22.661 D/Mono    (14892): GC_TAR_BRIDGE bridges 424 objects 2303 colors 445 ignored 814 sccs 424 xref 150 cache 0/0 setup 0.16ms tarjan 2.39ms scc-setup 0.20ms gather-xref 0.06ms xref-setup 0.02ms cleanup 0.31ms
04-11 16:46:22.661 D/Mono    (14892): GC_BRIDGE: Complete, was running for 49.28ms
04-11 16:46:22.661 D/Mono    (14892): GC_MAJOR: (LOS overflow) time 27.89ms, stw 29.64ms los size: 2048K in use: 467K
04-11 16:46:22.661 D/Mono    (14892): GC_MAJOR_SWEEP: major size: 3936K in use: 2558K`

### Actual Behavior
No "GC_<XXXXX>" log messages from "D/Mono" appear in the log (only log messages from "ART" are printed)

### Version Information
Visual Studio version 16.10.1

<details>

`Microsoft Visual Studio Professional 2019
Version 16.10.1
VisualStudio.16.Release/16.10.1+31402.337
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper 2021.1.3   Build 211.0.20210525.202743
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2021 JetBrains, Inc.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.230 (d16-10@0e66389)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.1 (d16-10/22fc2b3)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.3 (17fdcf569)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.`

**Comment by jpobst** [comment]
@grendello Is this change expected?  I know we did some rework of message logging in https://github.com/xamarin/xamarin-android/pull/5692.

**Comment by jfichtner** [comment]
> @grendello Is this change expected? I know we did some rework of message logging in #5692.

For what it's worth, I did also try setting the MONO_LOG_LEVEL to gc, as described here: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/environment, which did print some new messages, but did NOT print the expected messages as described above.

**Comment by grendello** [comment]
> @grendello Is this change expected? I know we did some rework of message logging in #5692.

Yes, it is. We were asked to log less by default, #5692 addresses that

**Comment by grendello** [comment]
> > @grendello Is this change expected? I know we did some rework of message logging in #5692.
> 
> For what it's worth, I did also try setting the debug.mono.log to gc, and MONO_LOG_LEVEL to info, as described here: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/environment, which did print some new messages, but did NOT print the expected messages as described above.

Can you try this command:

```shell
$ adb shell setprop debug.mono.log default,mono_log_level=info,mono_log_mask=gc
```

**Comment by jfichtner** [comment]
> > > @grendello Is this change expected? I know we did some rework of message logging in #5692.
> > 
> > 
> > For what it's worth, I did also try setting the debug.mono.log to gc, and MONO_LOG_LEVEL to info, as described here: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/environment, which did print some new messages, but did NOT print the expected messages as described above.
> 
> Can you try this command:
> 
> ```shell
> $ adb shell setprop debug.mono.log default,mono_log_level=info,mono_log_mask=gc
> ```

I apologize for the hiatus, but tried your suggestion today and the setprop command you suggested does bring the messages back!

**Comment by jfichtner** [comment]
@grendello this is an issue that needs fixed in Xamarin.Android, isn't it? Was hiding these messages intentional?

**Comment by grendello** [comment]
@jfichtner yes, it was intentional as people requested that we "spam" logcat less.
