### ISSUE TITLE
Building android pipeline android 12Error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-android#6509]
### Steps to Reproduce

1. Changed my build to use windows-2022
2. Changed the XF TargetFramework to be Android12
3. Run my pipeline on a microsoft hosted agent and I get
4. Error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.

Any suggestions, I have no control over the agent used. Am I missing something.

thanks

**Comment by jpobst** [comment]
You can try running the Java Installer Task before your build to get the correct Java installed and in your $PATH:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops

**Comment by developer9969** [comment]
@jpobst thanks for your reply , still no luck, is this something that I should raise in another forum?
Despite looking like that is installing I still get an error as below

![image](https://user-images.githubusercontent.com/16970109/142719665-9cc3d70f-d20b-4cfe-a87a-17304a22ae0b.png)


```    
- task: JavaToolInstaller@0
          inputs:
            versionSpec: '11'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled
```

**Errors**
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(252,5): 
error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0. 

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(252,5):
 error XA0031: Download the latest JDK at: https://aka.ms/msopenjdk

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(252,5): 
error XA0031: Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11 
```
and below is the result

**Comment by DrTJ** [comment]
In my case, just deleting my older version of JDK fixed the problem...

**Comment by MagicAndre1981** [comment]
@jpobst 

not directly related to this, but VS2019 resets JDK location to 1.8 after restart and I have to pick JDK 11 each time again. Can this be fixed?

**Comment by jpobst** [comment]
That's a VS issue. You can try filing it as feedback inside of Visual Studio so it can be routed to the relevant team, but VS2019 likely will not receive anything more than security fixes going forward.

**Comment by MagicAndre1981** [comment]
> That's a VS issue. You can try filing it as feedback inside of Visual Studio

there is [already an issue about it](https://developercommunity.visualstudio.com/t/Java-development-kit-Location-path-is-no/1609482), but it is ignored as always.

**Comment by MagicAndre1981** [comment]
> That's a VS issue. 

ok, removing JDK 1.8 from PATH environment variable fixes my issue. Now VS2019 uses JDK11 even after a restart.
