### ISSUE TITLE
Who can bind Baidu AI face recognition offline version?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/xamarin-android#6510]
The binding project always prompts that the so file cannot be found, but I set it

http://pan.adl66.com/Baidu_Face_Offline_SDK_Android_7.0.zip 
![image](https://user-images.githubusercontent.com/26525599/142610127-1aec06db-f825-4bb9-9d76-acde0bb3c1d6.png)

**Comment by bbhxwl** [comment]
$20 for help. Is anyone willing to help?

**Comment by jpobst** [comment]
Can you post the full error message you are seeing?

**Comment by xtuzy** [comment]
jar中调用so的例子或许可以参考下
https://github.com/JoesWeek/XamarinSDK/tree/master/UMeng.Android.Shares/Jars

https://github.com/daddycoding/XamarinAndroidBindLibary/tree/master/BaiduPush/src/BaiduPush
