### ISSUE TITLE
Resx files don't work with Android App Bundle in Release Mode

### ISSUE THREAD

**Issue by sayed-alim** [xamarin/xamarin-android#6513]
If use Android App Bundle, then AppResource.de.resx and other don't work, but AppResource.resx work. This happens only in release mode. In debug mode it works fine.

This issue was reported multiple times in last few years.
https://github.com/xamarin/xamarin-android/issues/3596
https://github.com/xamarin/Xamarin.Forms/issues/1595
https://github.com/xamarin/Xamarin.Forms/issues/4479

Tried all the suggested solutions
Add xml to the android .csproj file (_targetassemblies)
add .dll;mp3 not to compress

All the suggested solutions in (#3596,#1596,#4479) were tried without any success.

VS, Xamarin forms, SDK are all the latest.
VS for windows 16.11.7
Xamarin Forms 5.0.0.2244
Android SDK build tools 30.0.2
[MasteringMultilingualSample-master.zip](https://github.com/xamarin/xamarin-android/files/7570590/MasteringMultilingualSample-master.zip)

There are so many earlier comments that says this has been fixed in earlier release, but we continue to face this issue. We already have the app available on Google and Apple store. It currently supports 8 languages and we want to add 4 more languages. 

Sample zip file is attached which reproduce this scenario.

Any help will be highly appreciated.

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) of your build? Thanks!

**Comment by jonathanpeppers** [comment]
I just noticed you attached a sample.

When I remove this target, it works:
```xml
 <Target Name="_ResolveSatellitePaths" DependsOnTargets="_ResolveAssemblies">
    <ResolveAssemblyReference AllowedAssemblyExtensions="$(AllowedReferenceAssemblyFileExtensions)" AssemblyFiles="@(ResolvedUserAssemblies)" AutoUnify="$(AutoUnifyAssemblyReferences)" FindDependencies="True" FindRelatedFiles="False" FindSatellites="True" SearchPaths="$(AssemblySearchPaths)" TargetFrameworkMoniker="$(TargetFrameworkMoniker)" TargetFrameworkMonikerDisplayName="$(TargetFrameworkMonikerDisplayName)" TargetFrameworkDirectories="$(TargetFrameworkDirectory)">
      <Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths" />
    </ResolveAssemblyReference>
  </Target>
```
This seems like an old workaround you wouldn't need anymore.

Does that also work for you?

**Comment by sayed-alim** [comment]
Yes. It does resolved the issue. Thank You. Removing the xml from the android .csproj file fixed the issue.
Thank Jonathan.
