### ISSUE TITLE
[Question] GC Messages disappeared

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/xamarin-android#6516]
Hi,

not sure if this is the correct place, but the GC Messages in my VS output are gone/changed. If i try to debug a XF App, i only get this type of GC infos:

> [rv.mypapp] Explicit concurrent copying GC freed 1731(202KB) AllocSpace objects, 12(1584KB) LOS objects, 49% free, 2504KB/5008KB, paused 231us total 7.274ms
> [rv.mypapp] Explicit concurrent copying GC freed 4579(175KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3562KB/7125KB, paused 234us total 10.651ms

A few weeks ago i get the GC_MINOR and GC_MAJOR Messages like this:

> GC_MINOR: (Nursery full) pause 643.96ms, total 644.45ms, bridge 1292.70ms promoted 0K major 33344K los 108818K

In my app i changed nothing. I only update windows and Visual Studio. I thought something changed in VS 2022 but in VS 2019 there are also no GC_MINOR: (Nursery full) messages. As a nice side effect a reproducible ObjectDisposedException is now gone ;)
Hopefully somebody knows what changed?!

Thank you

**Comment by jpobst** [comment]
I think this change is being discussed here:
https://github.com/xamarin/xamarin-android/issues/6483

**Comment by AlleSchonWeg** [comment]
Perhaps. I have installed Xamarin.Android SDK 12.1.0.5 on VS 2022 and 12.0.0.3 on VS 2019.
I don't know after which version this changes are included.

**Comment by jpobst** [comment]
Seems like the same issue, so let's continue tracking it there.
