### ISSUE TITLE
class-parse has issue if the input jar references some unknown type

### ISSUE THREAD

**Issue by sunnyqeen** [xamarin/xamarin-android#6524]
### Error Message or Issue

We have an interface class that references other types not in the jar.
Use jar2xml way, the library and interface are generated correctly.
But after we target android 12, and use jdk11, jar2xml way is not working any more, VS gives errors.
error:
JARTOXML : error : Could not create the Java Virtual Machine.
JARTOXML : error : A fatal exception has occurred. Program will exit.

Then we switch to class-parse with more issues

We have an interface lib like

```
package test2;
import test1.TestClassA;

public class TestClassB {
  public interface BBB {
	  void DoJob1();
	  void DoJob2(TestClassA.AAA aaa);
  }
}
```

and another reference lib like

```
package test1;

public class TestClassA {
	public class AAA {
		
	}

}

```

Then the in generated C# dll,
Only method DoJob1() is there.
DoJob2 is stripped by using  class-parse.

![image](https://user-images.githubusercontent.com/649698/143452027-1f7fa7ff-69d5-4f32-9b73-6e480861b4ba.png)

(We check it using ilspy)

The example project

[lib2.zip](https://github.com/xamarin/xamarin-android/files/7603229/lib2.zip)

### Version Information
Microsoft Visual Studio Professional 2019
Version 16.11.7
VisualStudio.16.Release/16.11.7+31911.196
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-20313-02959-AA247
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.94.52318
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.11.94.52318
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Linux Core Dump Debugging   1.0.9.31829
Enables debugging of Linux core dumps.

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62111.11070
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.31829.152
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   16.0.31213.239
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.9.31829
Visual C++ for Linux Development

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jpobst** [comment]
We have some pretty good documentation on troubleshooting issues with missing API in binding projects here: https://github.com/xamarin/java.interop/wiki/Troubleshooting-Android-Bindings-Issues.

In particular: https://github.com/xamarin/java.interop/wiki/Missing-Types-or-Members.

**Comment by jonpryor** [comment]
`jar2xml` was deprecated in Xamarin.Android 11.0, and is not included in the .NET SDK for Android: https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.0#bindings-projects-xa4231-warning-for-deprecated-jar2xml-parser

`class-parse` is the only supported binding mechanism.

**Comment by sunnyqeen** [comment]
@jpobst have you checked the sample I provided 
https://github.com/xamarin/xamarin-android/files/7603229/lib2.zip

I already added the reference jar.
But still get the missing method.

**Comment by jonpryor** [comment]
Meanwhile, the `TestClassB.IBBB` interface shouldn't have been emitted *at all*, ***because*** it's lacking the `DoJob2()` method.  The emission of `TestClassB.IBBB` is in fact a bug: https://github.com/xamarin/java.interop/issues/814

We thus get to the problem of *semantics*:

  * `@(ReferenceJar)` isn't properly documented (doh), but is "like" [`@(EmbddedReferenceJar)`](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-items#embeddedreferencejar), just without embedding:
    > does not create a C# binding
  * `@(EmbeddedJar)` *does* create a binding.

`lib1.jar` declares `test1.TestClassA`, but is *only* a reference library, and thus won't be bound.  As it won't be bound, `test2.TestClassB.BBB` is unbindable, as `test1.TestClassA` can't be resolved.

So long as you use `@(ReferenceJar)` for `lib1.jar`, `test2.TestClassB.BBB` cannot be properly bound.  As-is, the bound `Test2.TestClassB.IBBB` interface is only *partially* usable; you can't *implement* the interface:

```csharp
class BadExample : Java.Lang.Object, Test2.TestClassB.IBBB {
    public void DoJob1() {}
}
```

If you attempt to do so, the generated Java Callable Wrapper will fail to build, which means apps referencing this binding will fail to build.

A solution is to just use `@(EmbeddedJar)` for *both* `lib1.jar` *and* `lib2.jar`:

```xml
  <ItemGroup>
    <EmbeddedJar Include="Jars\lib2.jar" />
    <EmbeddedJar Include="Jars\lib1.jar" />
  </ItemGroup>
```

This causes `test1.TestClassA` to be publicly accessible, and thus usable from bindings, and thus allows `Test2.TestClassB.IBBB` to be properly generated:

```csharp
namespace Test2 {
	public partial class TestClassB : global::Java.Lang.Object {
		// Metadata.xml XPath interface reference: path="/api/package[@name='test2']/interface[@name='TestClassB.BBB']"
		[Register ("test2/TestClassB$BBB", "", "Test2.TestClassB/IBBBInvoker")]
		public partial interface IBBB : IJavaObject, IJavaPeerable {
			// Metadata.xml XPath method reference: path="/api/package[@name='test2']/interface[@name='TestClassB.BBB']/method[@name='DoJob1' and count(parameter)=0]"
			[Register ("DoJob1", "()V", "GetDoJob1Handler:Test2.TestClassB/IBBBInvoker, lib2")]
			void DoJob1 ();

			// Metadata.xml XPath method reference: path="/api/package[@name='test2']/interface[@name='TestClassB.BBB']/method[@name='DoJob2' and count(parameter)=1 and parameter[1][@type='test1.TestClassA.AAA']]"
			[Register ("DoJob2", "(Ltest1/TestClassA$AAA;)V", "GetDoJob2_Ltest1_TestClassA_AAA_Handler:Test2.TestClassB/IBBBInvoker, lib2")]
			void DoJob2 (global::Test1.TestClassA.AAA p0);

		}
	}
}
```

---

Thus, the question: why are you using `@(ReferenceJar)` for `lib1.jar`?

**Comment by sunnyqeen** [comment]
The main problems we have is the generating of interface with missing method, then cause the compiling error of building android apk. With old jar2xml the issue is not there, and all the methods are generated.
I prefer generating the default code for unknown class like the old jar2xml doing, in the case the java unknown class could be inside another jar. And if the real class is missing, we will know the problem during compiling or running apk.

**Comment by jonpryor** [comment]
@sunnyqeen [wrote](https://github.com/xamarin/xamarin-android/issues/6524#issuecomment-981999627):

> With old jar2xml the issue is not there, and all the methods are generated.

In point of fact, when `jar2xml` is used, the `test2.TestClassB.BBB` interface is *not* bound:

```
warning BG8503: Invalidating 'Test2.TestClassB.IBBB' and all its nested types because some of its methods were invalid.
```

At least it's not bound for me, when using JDK 1.8.  (See also PR #6531, which should fix JDK-11 support.)

If it's bound for you, I don't understand how that's happening, and would love to see some diagnostic build logs…

> I prefer generating the default code for unknown class like the old jar2xml doing.

I don't understand what "default code" means.

You likewise haven't explained why `lib1.jar` is using the `@(ReferenceJar)` build action, as using `@(EmbeddedJar)` or `@(InputJar)` on `lib1.jar` would have allowed the `test2.TestClassB.BBB` interface to be bound.

**Comment by sunnyqeen** [comment]
@jonpryor this project is an example to show the different about missing java class reference. I do know adding both as EmbeddedJar could solve the problem.

Our real project has only the jar with some missing reference classes, there is no reference jar to add.
I rechecked our project, the interface with missing class reference is not used, so we could just remove that interface class from the jar to solve the problem.

But still, class-parse should remove the interface, but not generate an half binding interface, that cause the apk build failed.

And regarding the default code.
I mean just binding the missing class as a normal java object, without any member functions.
In the case the missing class in just use as an java object.
```
public class A
{
     public MissingClass Create();
     public void Use(MissingClass cls);
}
```

**Comment by jonpryor** [comment]
@sunnyqeen [wrote](https://github.com/xamarin/xamarin-android/issues/6524#issuecomment-982515804)

> But still, class-parse should remove the interface, but not generate an half binding interface, that cause the apk build failed.

Agreed.  We'll need to increase the priority on fixing https://github.com/xamarin/java.interop/issues/814 .

**Comment by jpobst** [comment]
Closing, I think all the outstanding issues here are complete or tracked in https://github.com/xamarin/java.interop/issues/814.
