### ISSUE TITLE
OnDestroy is not called when exiting the app when built against Android 11 or 12, only on devices running Android 12.

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#6525]
Beginning with Android 8 any app using a bound service is required to create a notification to indicate that the app is running in the background. My app has been displaying a notification indicating that since that time.

Now when I build it with Android 11 or 12, when I exit the app, the notification is still displaying, whereas, on any device running between Android 8 and Android 11, the notification always disappears on exiting the app.

After debugging I found that OnDestroy of the MainActivity is never called on an Android 12 device. The code that closed the service and notification etc is contained within an if ( IsFinishing ), but consequently if OnDestroy() is not called, then that code doesn’t execute either.

OnDestroy is being called on a normal rotation, but since IsFinishing is false in that situation, then that code is bypassed anyway.

I’ve googled the problem but don’t get any hits, so I’m asking here if anyone is aware of the problem. I just don’t understand why OnDestroy is not being called, but can’t really think of any reason why it would be Xamarin.Android specific.

Using VS 2022 17.0.0 as I can’t use 17.1.0 Prev 1.1 because of #6480.

**Comment by grendello** [comment]
@jpobst @jonpryor any idea?

**Comment by gmck** [comment]
@grendello, @jonpryor, @jpobst   

I was able to work around the problem for Android 12 devices by adding an OnBackPressedCallback to the top-level Fragment that just calls Activity.Finish() in its HandleBackPressed method. That would seem to indicate that something in OnSupportNavigateUp() may have changed. I'm using Xamarin.AndroidX.Navigation.UI 2.3.5. I notice that there is now a 2.3.5.3 so I'll upgrade it later and see if that is where the change is.

Look forward to your comments.

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

I'm glad you found a workaround.
