### ISSUE TITLE
Run Classic Xamarin.Android Unit Tests against JDK-11 in Nightly Builds

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#6532]
Context: https://github.com/xamarin/xamarin-android/pull/6531#issuecomment-982246117

Run Classic Xamarin.Android Unit Tests against JDK-11 in Nightly Builds.  This would have found the regression in the `<JarToXml/>` task.

**Comment by jpobst** [comment]
With Classic being deprecated, it probably doesn't make sense to invest in this.
