### ISSUE TITLE
The dll of ClassLibrary too big than ios,i found it pack something  from nuget, can i not pack they at debug?

### ISSUE THREAD

**Issue by xtuzy** [xamarin/xamarin-android#6545]
### Android application type

Classic Xamarin.Android (MonoAndroid11.0, MonoAndroid12.0, etc.)

### Affected platform version

VS2022

### Description

When create classlibrary for  xamarin, i found the dll size always big of android than ios, such as install Skiasharp nuget, its .so will pack in __AndroidNativeLibraries__.zip of dll, so dll very big. Have method can let it not pack they in classlibrary when debug? I need use socket send dll to app, so i hope it is small.

### Steps to Reproduce

1.Create classlibrary for xamarin.android
2. Intstall some nuget
3. build

**Comment by xtuzy** [comment]
#5776

**Comment by jpobst** [comment]
Possibly related to https://github.com/xamarin/xamarin-android/issues/5776?

**Comment by xtuzy** [comment]
android library nuget that use skiasharp are big, all have .so file.

**Comment by jonathanpeppers** [comment]
The problem here is in SkiaSharp: https://github.com/mono/SkiaSharp/pull/1895

As a workaround for now, you should be able to put this in your class library's `.csproj` file:

```xml
<ShouldIncludeNativeSkiaSharp>False</ShouldIncludeNativeSkiaSharp>
```
