### ISSUE TITLE
Android designer is not loading 

### ISSUE THREAD

**Issue by sridharsaminathant** [xamarin/xamarin-android#6558]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VSMac 8.10.14(build 17)

### Description

Android designer is not loadin
![Uploading Screenshot 2021-12-09 at 4.07.48 PM.png…]()
g

### Steps to Reproduce

Open android xml layouts in Xamarin.android project

**Comment by jpobst** [comment]
This issue likely occurs in the Android Designer, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
