### ISSUE TITLE
Error "Internal API library is required"

### ISSUE THREAD

**Issue by vukasin89** [xamarin/xamarin-android#6574]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2019

### Description

I am having problem opening my Android app as System app.
App is blank app created in Xamarin.Forms. 
There were no changes in default code.

When I deploy APK as normal(non-system) app it is working normally, main screen appears.
But I get this error:

**Internal API library is required**

_System: Android version is 8.1.0.
Processor: ARMv7 Processor rev 5 (v7l)_

After this when I start the app, white screen opens and that is it.
Logcat is showing this error:
`F monodroid: Internal API library is required`

When I lookup for this error I see that it is in this file as explicit error:
https://github.com/xamarin/xamarin-android/blob/994388d91c2c5d5ff49b393cfe10af4ca4009247/src/monodroid/jni/monodroid-glue.cc#L1238

```
MonodroidRuntime::init_internal_api_dso (void *handle)
{
	if (handle == nullptr) {
		log_fatal (LOG_DEFAULT, "Internal API library is required");
		exit (FATAL_EXIT_MONO_MISSING_SYMBOLS);
	}
	....
}
```

but I am not sure what is missing? What file? Where to put it? How to debug it?
APK is here as attachment in zip
[com.companyname.app.mobile-Signed.zip](https://github.com/xamarin/xamarin-android/files/7722324/com.companyname.app.mobile-Signed.zip)
.

### Steps to Reproduce

I am following rules from this link:
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/install-system-app

So I am having all these .so files uploaded:
adb push 'C:\SoFiles\libmono-btls-shared.so' '/system/lib/'
adb push 'C:\SoFiles\libmono-native.so' '/system/lib/'
adb push 'C:\SoFiles\libmonodroid.so' '/system/lib/'
adb push 'C:\SoFiles\libmonosgen-2.0.so' '/system/lib/'
adb push 'C:\SoFiles\libxa-internal-api.so' '/system/lib/'
adb push 'C:\SoFiles\libxamarin-app.so' '/system/lib/' 
(I have tried without these libraries and error was explicit about mising every of them)

after this I am doing all this code

adb root
adb remount
adb push "c:\SoFiles\com.companyname.app.mobile-Signed.apk" /system/app/
adb shell chmod 644 /system/app/com.companyname.app.mobile-Signed.apk
adb reboot

**Comment by grendello** [comment]
Hi @vukasin89

The APK looks fine, it appears that for some reason the shared library wasn't loaded for **some** reason (might be missing dynamic dependencies, but that would be odd since the library in question depends only on libc, libm and libdl). Unfortunately, I can't say what's wrong with it given the information available. Can you please attach a logcat of the failed session after issuing the commands below:

```cmd
> adb shell setprop debug.mono.log default,assembly
> adb logcat -G 16M
> adb logcat -c
rem Run the app here
> adb logcat -d > logcat.txt
```

Thanks!
