### ISSUE TITLE
debugger breaks on handled WebExceptions

### ISSUE THREAD

**Issue by trampster** [xamarin/xamarin-android#6584]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2019

### Description

When WebExceptions occur, even though the exceptions are handled in a try catch block the debugger still breaks and shows the exception details.

Break when exception type is thrown is not set (as can be seen from the screenshot)

![image](https://user-images.githubusercontent.com/2063633/146692730-6da11b2e-fc1e-4142-bd69-ee34b03ade31.png)

### Steps to Reproduce

1. Use an HttpClient to do a request that will throw a WebException (in my cases due to an ssl issue)
2. Add a try catch block so that the exception will get caught and handled
3. Run in debug mode
-> debugger breaks and shows Exception Unhandled dialog for a handled exception

**Comment by grendello** [comment]
@trampster Thanks for filing the issue, however debugger is a component of Visual Studio and not Xamarin.Android and I'm afraid you will need to file a separate issue with VS (using the Feedback button in the IDE) for the VS team to investigate.
