### ISSUE TITLE
Please update android emulator to version 31.x.x

### ISSUE THREAD

**Issue by rustedwizard** [xamarin/xamarin-android#6590]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022, Windows 11

### Description

Currently, Xamarin comes with Android emulator version 30.x.x and it doesn't work on Windows 11 (Please refer to [this page](https://stackoverflow.com/questions/68373280/android-studio-emulator-is-not-working-on-windows-11-using-whpx) ). It is fixed in version 31.x.x. Can we have version 31.x.x please ?

### Steps to Reproduce

Create any virtual device and start it in Windows 11 environment, Android emulator failed to start.

**Comment by jpobst** [comment]
The current workaround is:
- Open Android SDK Manager (Tools -> Android -> Android SDK Manager)
- Click the little gear in the bottom right and choose Repository -> Full List
- Go to the Tools tab
- There should be an update available for the emulator (currently 31.1.4)

**Comment by jpobst** [comment]
Looks like it is still missing from the "Approved List" in VS2022 17.1 P1, but it is available in the internal 17.1 P3 nightly build.  

Not sure if it will be fixed in P2 or not, as I do not have a build of that.

**Comment by pjcollins** [comment]
We may want to consider updating https://github.com/xamarin/xamarin-android-tools/blob/a5194e93498e7f12225d87e2811415a45f742116/src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.Versions.props#L15 to help guide what Auto SDK management will install. The `emulator` SDK package is no longer included in the VS installer, and I think we only try to install the latest version on project load if that package is missing.

**Comment by pjcollins** [comment]
@tondat does my understanding above sound correct to you? Or will updates/installations of newer VS versions automatically upgrade the `emulator` package if is already installed?

**Comment by tondat** [comment]
Emulator version 31.1.4 is available in VS2022 17.1 P2.

@pjcollins the change in the props for auto-sdk is not required, emulator always install the latest version available in the approved list.

**Comment by pjcollins** [comment]
@tondat ok thanks good to know! I think we can mark this as resolved in 17.1 Preview 2 then.
