### ISSUE TITLE
Is there a Xamarin Android implementation of KeyedAppStatesReporter for app feedback?

### ISSUE THREAD

**Issue by skuskusku** [xamarin/xamarin-android#6592]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

VS2019

### Description

Hello everyone,

I would like to implement app feedback from my xamarin android app to an EMM as described here: https://developer.android.com/work/app-feedback/overview . It all starts with creating an instance of the KeyedAppStatesReporter class, which I don't know where to get from. I have also grepped the Xamarin monodroid-samples-master repo for "KeyedAppStatesReporter" without any success. What do I have to do in order to use KeyedAppStatesReporter in Xamarin.Android? Some magic Nuget package?

### Steps to Reproduce

Try to find an implementation in the Xamarin Android Source Code or Samples

### Did you find any workaround?

No, is there one?

**Comment by jpobst** [comment]
It looks like this is implemented in the `androidx.enterprise.enterprise-feedback` AndroidX package:
https://developer.android.com/reference/androidx/enterprise/feedback/KeyedAppStatesReporter

https://maven.google.com/web/index.html?#androidx.enterprise:enterprise-feedback

Unfortunately this AndroidX package has not been bound.

Available options are:
- Request the package to be bound here: https://github.com/xamarin/AndroidX/issues
- Bind the package yourself

**Comment by skuskusku** [comment]
Thank you, @jpobst. I have requested the package to be bound at the location you suggested. I do not have the slightest idea, how I could bind the package myself. Any pointers?

Again, thanks.

-- 
Stefan Kuhr

**Comment by skuskusku** [comment]
Oh, most probably it is this: https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/

**Comment by jpobst** [comment]
Yep! That's the place to start.
