### ISSUE TITLE
Using the default TrimMode=link breaks FirstChanceException handler support and crashes app

### ISSUE THREAD

**Issue by lauxjpn** [xamarin/xamarin-android#6626]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 6.0.100

### Description

When registering an `AppDomain.CurrentDomain.FirstChanceException` handler, the handler works fine with non-trimmed builds.

With the default `TrimMode=link` option when using `PublishTrimmed=true`, the app crashes at runtime (presumable when the handler gets called for the first time).

I also tried the following, but the crash still happens at runtime:

```
<Target Name="ConfigureTrimming"
        BeforeTargets="PrepareForILLink">
    <ItemGroup>
        <ManagedAssemblyToLink Condition="'%(Filename)' == 'System.Runtime'">
            <IsTrimmable>false</IsTrimmable>
        </ManagedAssemblyToLink>
    </ItemGroup>
</Target>
```

---

I wanted to use a `FirstChanceException` handler to break into the code when an exception because of another trimmed method occurs, so that I could take a look at the call stack and the parameters of a `System.Delegate.CreateDelegate(Type type, Type target, String method)` call, so that I could investigate which target method got trimmed in https://github.com/xamarin/xamarin-android/issues/6612#issuecomment-1006145047.

Unfortunately, since the `TrimMode=link` also trims away the `FirstChanceException` handler support, I can't use it for that purpose.

### Steps to Reproduce

See description.

**Comment by jonathanpeppers** [comment]
This example in a `dotnet new android` app works for me:
```csharp
[Activity(Label = "@string/app_name", MainLauncher = true)]
public class MainActivity : Activity
{
    protected override void OnCreate(Bundle? savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        // Set our view from the "main" layout resource
        SetContentView(Resource.Layout.activity_main);

        AppDomain.CurrentDomain.FirstChanceException += (sender, e) =>
        {
            Console.WriteLine("First change exception!");
        };
    }

    public override void OnBackPressed() => Task.Factory.StartNew(() => throw new Exception("foo"));
}
```

However, if I do this, then `FirstChanceException` doesn't fire:
```csharp
public override void OnBackPressed() => throw new Exception("foo");
```

**Comment by jonathanpeppers** [comment]
I think this behavior is correct for Debug builds ^^

The problem is Release builds (that are trimmed) crash with:
```
04-18 11:47:56.344 31371 31456 E companyname.fo: * Assertion at /__w/1/s/src/mono/mono/metadata/object.c:4179, condition `ctor' not met
```

@steveisok do you have any ideas on which type I should check to see what is linked away?

**Comment by jonathanpeppers** [comment]
@steveisok @akoeplinger here is a smaller example:
```csharp
        AppDomain.CurrentDomain.FirstChanceException += (sender, e) =>
        {
            Console.WriteLine("First chance exception!");
        };

        try
        {
            throw new Exception("foo");
        }
        catch
        {
            Console.WriteLine("Exception handled!");
        }
```
I tested with `adb shell setprop debug.mono.log default,timing,assembly,mono_log_level=debug,mono_log_mask=all`

In a trimmed build (Release), this crashes without much info was to what is wrong:
```
04-19 15:01:49.456 24437 24437 D Mono    : Running class .cctor for System.AppDomain from 'System.Private.CoreLib.dll'
...
04-19 15:02:44.254 24437 24437 E companyname.fo: * Assertion at /__w/1/s/src/mono/mono/metadata/object.c:4179, condition `ctor' not met
```
[adb.txt](https://github.com/xamarin/xamarin-android/files/8516178/adb.txt)

So I was looking at:

https://github.com/dotnet/runtime/blob/6c7ce85e149eaaf4cc452a7008754d5c799db938/src/mono/mono/metadata/object.c#L94

What would preserve the ctor of this type?

![image](https://user-images.githubusercontent.com/840039/164087781-5f6775b5-7862-4a64-8e6d-90dfc076105b.png)

![image](https://user-images.githubusercontent.com/840039/164087856-962e29d3-af73-4d1a-9fe3-2ab8ac27962a.png)

I think ILSpy is showing this type has no ctor.

**Comment by akoeplinger** [comment]
Thanks, I opened https://github.com/dotnet/runtime/pull/68235 to fix this. In the meantime you can workaround the issue by adding this to a [custom linker configuration](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker):

```xml
<type fullname="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
    <method signature="System.Void .ctor(System.Exception)" />
</type>
```
