### ISSUE TITLE
AppCompatDialogFragment not displaying correctly on Android 12 devices

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#6648]
### Android application type

Classic Xamarin.Android (MonoAndroid11.0, MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.0.0

### Description

I have many modal Dialogs in my app, which are all based on AppCompatDialogFragment. Some are more complicated than others and so have their own classes, but they now appear to have a problem in displaying correctly on Android 12 devices only. On any devices lower than Android 12, they display normally as they have done, since Android 10, when I first converted to AndroidX.

I’ve only recently converted my app to Android 12 and the only relevant change I had to make was to include permissions for BluetoothConnect and BluetoothScan because of the new Android 12 permission requirements.   

The simplest one of these dialogs is what I call BasicDialogFragment. An instance of it takes 2 strings, a title and a message. The layout is a ScrollView containing a LinearLayout containing one Textview for the message, which can be of any length.
I’m using a MaterialAlertDialogBuilder and in the OnCreateDialog. 

```
public override Dialog OnCreateDialog(Bundle savedInstanceState)
{
            LayoutInflater inflater = LayoutInflater.From(Activity);
            View view = inflater.Inflate(Resource.Layout.generic_dialog, null);

            TextView textViewExplanation = view.FindViewById<TextView>(Resource.Id.textView_explanation);
            textViewExplanation.Text = Arguments.GetString("Message");

            MaterialAlertDialogBuilder builder = new MaterialAlertDialogBuilder(Activity);
            builder.SetTitle(Arguments.GetString("Title"));
            builder.SetPositiveButton(Android.Resource.String.Ok, (sender, args) => { Dismiss(); });
            builder.SetView(view);
            return builder.Create();
}
```
The problem is the OK button doesn’t always appear, especially on longer multi-paragraph messages. It might appear the first time the Dialog is called, the next time it might only be partially visible (but still clickable) and another time it is not visible, and therefore the dialog can’t be dismissed. Kill and Restart the app and the OK button will then usually not appear.

 I’ve just rechecked, the Android 11 version of the app and it also has the same problem on the Android 12 devices.

I have 3 Pixel devices - 3a (Android12), 4a (still Android11 - doesn’t have the problem) and a Pixel 6.
I was wondering if anyone else has hit this problem with Android 12 devices. My googling doesn’t get any hits.

### Steps to Reproduce

Can create a sample if required

### Did you find any workaround?

Not yet

### Relevant log output

```shell
None
```

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.
