### ISSUE TITLE
Xamarin.Android binding library Java.Lang.NoClassDefFoundError Failed resolution of: Lokio/Buffer

### ISSUE THREAD

**Issue by arnoldlaishram** [xamarin/xamarin-android#6650]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS MAC 8.10.16

TargetFramework - Android 11

### Description

I am trying to create a Xamarin binding library of a native android library which has a dependency on `Square okhttp3`

After adding the packages from Nuget packages, I found out that `Square okhttp3` library has a dependency on `square okio` library so i have also added the `square okio` library. My packages list looks like this.

<img width="300" alt="165658-screenshot-2022-01-17-at-51044-pm" src="https://user-images.githubusercontent.com/19688333/149876844-93c3cfba-faaa-47db-bc7b-8c734fb767f1.png">

Once the binding library is build library.dll is generated, I used the library.dll file as a reference in an android app. After successfully running the app, the internal dependency package, square okio library is not resolved.

This is the error i am getting

<img width="350" alt="165676-screenshot-2022-01-17-at-51552-pm" src="https://user-images.githubusercontent.com/19688333/149877032-769322ed-6bbb-4eb2-b8ae-265900e3c3ca.png">

Is there a way to make this work?

### Steps to Reproduce

1. Download the aar file from here. https://drive.google.com/file/d/1ufpoLkUhAGhitUp3xqJzUaVBD9iXrvUI/view?usp=sharing
2. Create an android binding library by adding the aar file in jars folder.
3. Add `Xamarin Square okhttp3` package from nuget in packages folder.
4. Build the binding library to create the dll file.
5. Once the dll file is created, reference it from an android app.
6. And write this code of line DependencyTest.Execute() inside onCreate of MainActivity.cs file;
7. You should get the error "Failed to resolve Lokio/buffer";

### Did you find any workaround?

A workaround i found to make it work is that, in the app if i add a reference of `square okio` library and run the app, it works.

<img width="376" alt="165711-screenshot-2022-01-17-at-52456-pm" src="https://user-images.githubusercontent.com/19688333/149877069-fc033f20-9d37-4ec7-b2d8-ecbeef0e1715.png">

Since I am trying to release a library to nuget repository and I wouldn't want the client to add another reference other than my library. Is there a way to make this work without adding any reference in the app? It is okay to add the reference in the binding library but not in the app.

**Comment by jpobst** [comment]
Are you using `<PackageReference>`'s or a `packages.config` file?

If using `<PackageReference>`, you should not need to specify transitive dependencies.  If using `packages.config`, you will need to specify all dependencies.

**Comment by ArnoldLaishram** [comment]
Hey @jpobst i am using <PackageReference>. Here's how my library package reference looks like.

<img width="660" alt="Screenshot 2022-01-19 at 9 45 26 AM" src="https://user-images.githubusercontent.com/19688333/150063191-258d6996-83e8-407f-872e-a06801d94bda.png">

All the dependencies are already in the list. It doesn't work though.

**Comment by jpobst** [comment]
Hmm, those aren't our packages.  The OkHttp package published by Microsoft is:
https://www.nuget.org/packages/Square.OkHttp3

If you look at the dependencies of the package you are using, it does not specify any dependencies, so it's not going to pull in Okio automatically:
https://www.nuget.org/packages/XamarinLibrary.Xamarin.Android.Squareup.Okhttp3.OkHttp

**Comment by ArnoldLaishram** [comment]
Thanks for the suggestion but I am still getting the same error with Square.OkHttp3 also

<img width="489" alt="Screenshot 2022-01-19 at 11 58 25 AM" src="https://user-images.githubusercontent.com/19688333/150076305-94a23167-e0dd-484a-a82f-ea82f9fd435d.png">

**Comment by jpobst** [comment]
How are you consuming your binding library in your application?  Reference? ProjectReference? PackageReference?

**Comment by ArnoldLaishram** [comment]
I am consuming the dll file in References.

My library name is `leap_xamarin_android_creator`

<img width="489" alt="Screenshot 2022-01-21 at 10 59 01 AM" src="https://user-images.githubusercontent.com/19688333/150471289-a29c7661-ccdf-4ce1-8e1a-4f7db48c0a0c.png">

**Comment by jpobst** [comment]
If that is just an assembly reference, then I would expect you will need to add references to all of your dependencies.  I do not believe any transitive assemblies will be automatically pulled in.

If that is a project reference, then I would expect transitive assemblies to be pulled in automatically.

@jonathanpeppers Does that sound right?

**Comment by jpobst** [comment]
That library is provided by one of our packages: `Square.OkIO`, which is `<EmbeddedJar>`.  They are consuming that package in the binding library as a transitive reference from another of our packages: `Square.OkHttp3`.

That is, their binding project has:
```
<PackageReference Include="Square.OkHttp3" />`
```

And the `Square.OkHttp3` package has:
```
<PackageReference Include="Square.OkIO" />`
```

The issue is when referencing their binding library in their application, would the referenced NuGet package assemblies (and thus `EmbeddedJar`s get automatically included in their application? (Note their library is not being referenced as a NuGet package.)

I think for an assembly reference the answer is "no", but for a project reference the answer is "yes" ?

**Comment by jonathanpeppers** [comment]
@ArnoldLaishram so if you just add the `<PackageReference/>` to the app, it solves the problem?

There is custom logic in Xamarin.Android to find the closure of all assemblies needed for an app project. I would guess it's not working for this case.

**Comment by ArnoldLaishram** [comment]
> @ArnoldLaishram so if you just add the `<PackageReference/>` to the app, it solves the problem?
> 
> There is custom logic in Xamarin.Android to find the closure of all assemblies needed for an app project. I would guess it's not working for this case.

Thats right @jonathanpeppers. If I add the reference in the app it works. If I add it in the library and reference it from the app it doesn't. 

Like you mentioned, Is there a way to find the closure of all the assemblies needed for an app and make changes?

**Comment by jpobst** [comment]
> Is there a way to find the closure of all the assemblies needed for an app and make changes?

Unfortunately not.  If you are using a reference to a `.dll`, you will have to be responsible for providing references to all of its dependencies.
