### ISSUE TITLE
Android APK/ABB with RESx build in release mode ONLY displays ENGLISH translations

### ISSUE THREAD

**Issue by muellnes** [xamarin/xamarin-android#6668]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

MSBuild 16.10.1.58001, VS 8.10.17.2, Xamarin.Android 12.0.0.3

### Description

# Android APK/ABB with RESx build in release mode ONLY displays ENGLISH translations
When building an Android application using the command line tools for release using the referenced versions translations 
are not shown anymore and only the fallback language - English - is displayed for all RESx translations.
Native translations that are used for push notifications are not affected and always show correctly in the user selected language.

## Test Results regarding different Versions

The following table shows the results of various Android APK builds. Note that English is also the default language.

- ✅ The APK contains all RESx files and is working as expected regarding localisations - so all translated languages are correctly displayed.

- ⛔️ The APK contains  all RESx files, but the RESx files are smaller than in the working build and only English is shown - independent of what language is selected by the user.

| Build type | MSBuild | VisualStudio | Xamarin.Android | Result |
|---|---|---|---|---|
|CLI|16.6.0.52201|8.8.3.16|11.1.0.17|✅|
|IDE|16.8.0.52201|8.8.3.16|11.1.0.17|✅|
|CLI|16.9.0.22901|8.10.13.11|12.0.0.3|⛔️|
|IDE|16.10.1.27501|8.10.13.11|12.0.0.3|✅|
|CLI|16.10.1.58001|8.10.17.2|12.0.0.3|⛔️|
|IDE|16.10.1.27501|8.10.17.2|12.0.0.3|✅|

Version numbers are given regarding the installed packages. The difference in MSBuild versions is due to the internal VisualStudio DLL and the command line tool used for the build from the Mono install - which can be gathered by:

`mono /Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/msbuild.dll --version`

| Type | msbuild |
|---|---|
| CLI  | `/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild` |
| DLL | `/Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/msbuild.dll` |

### Steps to Reproduce

`msbuild ./src/App.Droid/App.Droid.csproj /m:1 /p:Configuration=QA /p:Platform=AnyCPU /p:PackageOutputPath=./artifacts /p:ReferencePath=./packages /p:RestoreNoCache=true /p:RestorePackagesPath=./packages /p:OutputPath=./artifacts/ /t:UpdateAndroidResources /t:SignAndroidPackage /p:AndroidPackageFormat=apk -t:build -restore`

### Did you find any workaround?

The only workaround found would be to use the IDE or and older Install of VS (msbuild 16.6.0.52201, VS 8.8.3.16, Xamarin.Android 11.1.0.17).
This is not suitable for us as our CI is heavily used by our developers and a working console build is necessary for most of our processes

**Comment by WarBorg** [comment]
I can confirm this is an issue

is there a reason why the msbuild from the CLI is different from the one used by visual studio? I mean it could lead to a lot of issues like seen in this case

**Comment by dellis1972** [comment]
@muellnes 

Do you have a sample at all? We have a unit test which does use translations which I'll look at in order to repo this issue. 
However it would be useful to see the settings you are using for your `QA` configuration. For example, the linker settings, if Aot is used or not. 

If you don't have a full sample we can use, please add `/bl` to your command line arguments you posted. This will produce a `msbuild.binlog` file which you can zip and attach to this Issue. We can then see what settings are used and what might be happening.

**Comment by muellnes** [comment]
@dellis1972 

Thanks for the quick response. As requested here the configuration:

`<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'QA|AnyCPU' ">

<Optimize>true</Optimize>

<OutputPath>bin\QA</OutputPath>

<DefineConstants>QA;</DefineConstants>

<ErrorReport>prompt</ErrorReport>

<WarningLevel>4</WarningLevel>

<AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>

<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>

<AndroidManifest>Properties\AndroidManifestQA.xml</AndroidManifest>

<AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>

<AndroidUseDefaultAotProfile>false</AndroidUseDefaultAotProfile>

<AndroidSupportedAbis>armeabi-v7a;arm64-v8a</AndroidSupportedAbis>

<AndroidDexTool>d8</AndroidDexTool>

<AndroidLinkTool>r8</AndroidLinkTool>

</PropertyGroup>`

**Comment by thumm-msg** [comment]
@dellis1972 Here is the `msbuild.binlog` you asked for.

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-android/files/7950639/msbuild.binlog.zip)

**Comment by dellis1972** [comment]
@muellnes @thumm-msg 

I've been trying to repo this issue. I have a basic template Xamarin.Android app to which I added the following

1. Foo.resx

```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
	<resheader name="resmimetype">
		<value>text/microsoft-resx</value>
	</resheader>
	<resheader name="version">
		<value>2.0</value>
	</resheader>
	<resheader name="reader">
		<value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
	</resheader>
	<resheader name="writer">
		<value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
	</resheader>
	<data name="CancelButton"><value>Cancel</value></data>
</root>
```

2. Foo.en.resx
```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
	<resheader name="resmimetype">
		<value>text/microsoft-resx</value>
	</resheader>
	<resheader name="version">
		<value>2.0</value>
	</resheader>
	<resheader name="reader">
		<value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
	</resheader>
	<resheader name="writer">
		<value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
	</resheader>
	<data name="CancelButton"><value>Cancelar</value></data>
</root>
```
3. Foo.Designer.cs
```csharp
using System;
using System.Reflection;

namespace UnnamedProject
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Foo {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Foo() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UnnamedProject.Foo", typeof(Foo).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
    }
}
```

Then I added the following to the csproj

```xml
  <ItemGroup>
    <EmbeddedResource Include="Foo.es.resx">
      <Link>Foo.es.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="Foo.resx">
      <Link>Foo.resx</Link>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Foo.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
</ItemGroup>
```

And finally I updated the default "Button click" code as follows

```csharp
button.Click += delegate {
     button.Text = string.Format ("{0} {1}!", count++, Foo.CancelButton);
};
```

Now when I change the Locale of the device to Español and start the app. I get the correct spanish text.
Changing the Locale AFTER already starting the app does not. But if that doesn't work that might be a runtime issue (@jonpryor thoughts on this? ). 

So am I doing something different from what you are dong?

**Comment by WarBorg** [comment]
@dellis1972 did you compile the app using the msbuild from the CLI? and also did you enable the profiled AOT?

also our translations come from different modules which are nuget packages maybe that has an influence on it as well?

**Comment by dellis1972** [comment]
@WarBorg i always work from the CLI 😄 and profiled AOT has been enabled. 

So the translations `resx` files are compiled in other library projects then pulled in via Nuget? So you have one Nuget Per locale?

**Comment by WarBorg** [comment]
@dellis1972 just checking :D

so we have modules witch have their own translations and they get packaged up as nuggets, all the modules have the same locales but with different translation strings in them

but I will also run on Monday the scenario you did, installing the fresh app and switching the device language before actually starting the app but from what I remember we still got English, but I will check again just to be sure,

the other scenario you mentioned also happens to us as well if we close the app and reopen it we still get the English translation

**Comment by muellnes** [comment]
@dellis1972 You got a lot of hearts for this particular sentences.
I guess @WarBorg knows why ;)  

As described by @WarBorg we have setup with separates all features in different projects containing their own RESX translations. These projects are build, bundled as a nuget and distributed via a binary repository. 

The App project does only contain these modules as nuget references and some logic to stitch them together.

**Comment by muellnes** [comment]
@dellis1972  Thank you for your quick response, we are already setting up a test project that we can provide to you and that you can hopefully use to reproduce the issue and maybe also as a base for your test setup.

**Comment by muellnes** [comment]
@dellis1972 Hi sorry for the long wait. 
While doing the test project we found out a solution/workaround for our issue.
First we already had the following workaround for some previous RESx issues in the Droid.csproj:

` 
<Target Name="_ResolveSatellitePaths" DependsOnTargets="_ResolveAssemblies">
    <ResolveAssemblyReference AllowedAssemblyExtensions="$(AllowedReferenceAssemblyFileExtensions)" AssemblyFiles="@(ResolvedUserAssemblies)" AutoUnify="$(AutoUnifyAssemblyReferences)" FindDependencies="True" FindRelatedFiles="False" FindSatellites="True" SearchPaths="$(AssemblySearchPaths)" TargetFrameworkMoniker="$(TargetFrameworkMoniker)" TargetFrameworkMonikerDisplayName="$(TargetFrameworkMonikerDisplayName)" TargetFrameworkDirectories="$(TargetFrameworkDirectory)">
      <Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths" />
    </ResolveAssemblyReference>
  </Target>
`

That was the first thing we needed to remove, further on the build scripts we use are kind of dynamic for various build pipelines and also the `msbuild` command for the Android build had been customly generated. 
So the other thing we found was that our parameter concatenation which created the following command:

`msbuild droid.csproj /t:Build /t:PackageForAndroid /t:SignAndroidPackage`

did also affect the build artefact, replacing this with the following command

`msbuild droid.csproj //t:Build,PackageForAndroid,SignAndroidPackage`

produced a build artefact with valid RESx localisations.

This changes are currently no applied to the latest versions of our product and I will give you a follow-up, when we are safe and sound using the "fixes" we found.

**Comment by dellis1972** [comment]
@muellnes I don't know if this helps, but `SignAndroidPackage` has build dependencies on both `Build` and `PackageForAndroid`. So you shouldn't really need to provide all three. 

The following should work `msbuild droid.csproj  /t:SignAndroidPackage` and produce the required outputs.

**Comment by dellis1972** [comment]
I tend to use `msbuild droid.csproj /restore  /t:SignAndroidPackage` a my goto command line these days :D
