### ISSUE TITLE
[net6-android] Using `PrivateAssets="all"` on a package reference seems remove the assemblies from the apk

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#6674]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS2022 17.1 Preview 4

### Description

Building with a package reference marked with "`PrivateAssets="all"`" removes the assemblies from the apk.

It's not a blocking issue, as the `PrivateAssets` metadata is not useful in the context of a app's head project, but it can be a failure hard to troubleshoot.

### Steps to Reproduce

Create a net6-android app, add a nuget package reference with `PrivateAssets="all"` and use types from the package's assemblies.

At runtime, the assemblies from the package will fail to load.

### Did you find any workaround?

Removing the `PrivateAssets="all"` from the `PackageReference` is enough.

**Comment by dellis1972** [comment]
Hi @jeromelaban 

Do you have a specific NuGet that you are using which has this issue?
I just tried this with and AndroidX package reference in one of my test projects and that ran without any issues. The assemblies were in the apk.

**Comment by jeromelaban** [comment]
Sure, I added a reference this way:
```xml
<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.0-dev.7" PrivateAssets="all" />
```
You can force an actual reference by using `typeof(Uno.Extensions.LogExtensionPoint).ToString()`.

**Comment by jonathanpeppers** [comment]
@jeromelaban I seem to get this same behavior in a console app:

```
dotnet new console
dotnet add package Newtonsoft.Json
# manually add PrivateAssets="all"
dotnet publish -c Release -r win-x64 --self-contained
```

So I believe this is down to the publishing behavior in the .NET SDK. We're using an item group `@(ResolvedFileToPublish)` from the .NET SDK, that is likely doing this on purpose?

Do you think it's worth us moving this issue dotnet/sdk? I think we basically have to close and copy/paste the info on a new issue.

**Comment by jeromelaban** [comment]
I don't see any problem moving the issue :) You definitely know better than I do!

**Comment by jonathanpeppers** [comment]
Moved to: https://github.com/dotnet/sdk/issues/27211
