### ISSUE TITLE
AOT fails on テスト.dll

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#6685]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

xamarin-android/main

### Description

If I add `proj.AotAssemblies = true;` to this test, it fails:

https://github.com/xamarin/xamarin-android/blob/ce0d212e85f5710ebcfd68533221cead76bda5ec/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs#L123-L134

> C:\src\xamarin-android\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Legacy.targets(692,5): error XA3001: Could not AOT the assembly: テスト.dll [C:\src\xamarin-android\bin\TestDebug\temp\SmokeTestBuildWithSpecialCharactersFalse\テスト\テスト.csproj]

### Steps to Reproduce

1. Create a Xamarin.Android or .NET 6 project named `テスト`
2. Build with `-p:Configuration=Release -p:AotAssemblies=true`

### Did you find any workaround?

Probably rename the assembly?

**Comment by steveisok** [comment]
@jonathanpeppers I think this might be something with the runtime aot task and/or compiler.

**Comment by jonathanpeppers** [comment]
Yeah, it doesn't work in Xamarin.Android either -- so I think it might be the AOT compiler.

**Comment by steveisok** [comment]
ok, I'll move this issue into runtime then.
