### ISSUE TITLE
make prepare fails due to outdated download link

### ISSUE THREAD

**Issue by iamQuiliamQuil** [xamarin/xamarin-android#6705]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

xamarin-android 11.2.1.1 & 11.2.99.192, .NET 6.0.101

### Description

I'm trying to build Xamarin on my machine from the source code. I try to run "make prepare" and I get an error "Error: Failed to obtain JetBrains OpenJDK size. HTTP status code: Forbidden (403)" when it tries "Downloading JetBrains OpenJDK from https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-8u202-linux-x64-b1483.37.tar.gz". If you click on that link it will redirect you to an unrelated page with no downloadable content. 

### Steps to Reproduce

cd /bin
sudo git clone https://github.com/xamarin/xamarin-android.git
cd xamarin-android
sudo git checkout a9a71901b672bd5c5e4fabee8d4eed8e25da7b43
sudo make prepare

### Relevant log output

```shell
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Installing JetBrains OpenJDK 1.8
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

JetBrains JDK 1.8.0.202 r1483.37 will be installed
Downloading JetBrains OpenJDK from https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-8u202-linux-x64-b1483.37.tar.gz
  Error: Failed to obtain JetBrains OpenJDK size. HTTP status code: Forbidden (403)

Step Xamarin.Android.Prepare.Step_InstallJetBrainsOpenJDK8 failed
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_InstallJetBrainsOpenJDK8 failed
  at Xamarin.Android.Prepare.Scenario.Run (Xamarin.Android.Prepare.Context context, Xamarin.Android.Prepare.Log log) [0x001a8] in /bin/xamarin-android/build-tools/xaprepare/xaprepare/Application/Scenario.cs:50 
  at Xamarin.Android.Prepare.Context.Execute () [0x000fc] in /bin/xamarin-android/build-tools/xaprepare/xaprepare/Application/Context.cs:815 
  at Xamarin.Android.Prepare.App.Run (System.String[] args) [0x00861] in /bin/xamarin-android/build-tools/xaprepare/xaprepare/Main.cs:164
```

**Comment by iamQuiliamQuil** [comment]
[error.txt](https://github.com/xamarin/xamarin-android/files/8005981/error.txt)

**Comment by jonathanpeppers** [comment]
@iamQuiliamQuil does the latest commit from `main` work for you? It appears to be working on macOS, maybe @grendello can take a look?

**Comment by grendello** [comment]
We removed the JetBrains URL on April 13 last year in 5984ecb7c2009c7c1d10f743df9137f3b600fa2f, please update your repository to the latest main or a branch that contains that commit. It should work then.
