### ISSUE TITLE
Trouble binding LiTr - class definitions are not coming out as expected

### ISSUE THREAD

**Issue by beeradmoore** [xamarin/xamarin-android#6714]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS for Mac 8.10.17

### Description

I am trying to bind [linkedin/LiTr](https://github.com/linkedin/LiTr). The initial binding appears to work fine but it requires a second binding for the `litr-filters` for the additional classes it brings in. These classes live in the `com.linkedin.android.litr.filter.video.gl` package/namespace.

I think the problem I am having is that both litr and litr-filters have files in the same package/namespace. 

When initially trying to use a single library and using litr-sources.jar I would get the following output while building.

> BINDINGSGENERATOR : warning BG8601: No '<package>' elements found.

I also had tried extracting litr-filters-sources.jar as a zip and importing the files into lit-sources.jar so I could just have the one binding library/nuget but it would still give the BINDINGSGENERATOR warning above.)

I swapped to using litr.aar and that fixed that problem, but becuase using two aars in the same project is not supported so I made two binding libraries. Also because the litr-filters depends on litr my bindings requires litr nuget to be built in order to build the litr-filters binding. The bindings appear to build correctly.

The problem I am experiencing is that binding of (at least) one of the classes does not preserve its inheritance. 

[BitmapOverlayFilter.java
](https://github.com/linkedin/LiTr/blob/main/litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BitmapOverlayFilter.java) from litr-filters has a class definition of 

```
public class BitmapOverlayFilter extends BaseOverlayGlFilter {
```

[BaseOverlayGlFilter.java
](https://github.com/linkedin/LiTr/blob/c241a1bad2c310f936c01e87a22335e9f493568d/litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter.java#L26) is abstract, also from litr-filters, and implements GlFilter.

```
abstract class BaseOverlayGlFilter implements GlFilter {
```

and then [GlFilter](https://github.com/linkedin/LiTr/blob/c241a1bad2c310f936c01e87a22335e9f493568d/litr/src/main/java/com/linkedin/android/litr/filter/GlFilter.java#L16) is an interface, but it is part of litr not litr-filters like the other mentioned files.

```
public interface GlFilter {
```

When I attempt to copy some of their sample code [to use BitmapOverlayFilter](https://github.com/beeradmoore/Xam.Plugin.LinkedIn.LiTr/blob/master/ExampleApp/Utils/TransformationUtil.cs#L69) I will get a compile error that BitmapOverlayFilter can't be cast to IGlFilter.

> Xam.Plugin.LinkedIn.LiTr/ExampleApp/Utils/TransformationUtil.cs(30,30): Error CS0266: Cannot implicitly convert type 'Xam.Plugin.LinkedIn.LiTr.Filter.Video.GL.BitmapOverlayFilter' to 'Xam.Plugin.LinkedIn.LiTr.Filter.IGlFilter'. An explicit conversion exists (are you missing a cast?) (CS0266) (LiTrExample)

If I check the generated class `Xam.Plugin.LinkedIn.LiTr/LiTrFiltersBinding/obj/Release/generated/src/Xam.Plugin.LinkedIn.LiTr.Filter.Video.GL.BitmapOverlayFilter.cs` it does not mention `IGlFilter` or `BaseOverlayGlFilter`

```
namespace Xam.Plugin.LinkedIn.LiTr.Filter.Video.GL {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.linkedin.android.litr.filter.video.gl']/class[@name='BitmapOverlayFilter']"
	[global::Android.Runtime.Register ("com/linkedin/android/litr/filter/video/gl/BitmapOverlayFilter", DoNotGenerateAcw=true)]
	public partial class BitmapOverlayFilter : global::Java.Lang.Object {
```

I find this odd because api.xaml has
```
    <class abstract="false" deprecated="not deprecated" extends="com.linkedin.android.litr.filter.video.gl.BaseOverlayGlFilter" extends-generic-aware="com.linkedin.android.litr.filter.video.gl.BaseOverlayGlFilter" jni-extends="Lcom/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter;" final="false" name="BitmapOverlayFilter" static="false" visibility="public" jni-signature="Lcom/linkedin/android/litr/filter/video/gl/BitmapOverlayFilter;">
```

Should I be expecting the result `BitmapOverlayFilter` in the C# code to be different than above?

Am I doing the correct way of binding this library that ends up being two packages or is there a better way to achieve this?

### Steps to Reproduce

My bindings and repro can be found [here](https://github.com/beeradmoore/xam.plugin.linkedin.litr).
After pulling that repo you will want to execute the following.
```
cd Binding
./FetchJars.sh
./BuildNugetPackage.sh
```
This should produce `Xam.Plugin.LinkedIn.LiTr.1.4.18.nupkg` and `Xam.Plugin.LinkedIn.LiTr.1.4.18.snupkg` in the Binding directory. From there you can
```
cd ../LiTrFiltersBinding
./FetchJars.sh
./BuildNugetPackage.sh
```
and this should additionally make `Xam.Plugin.LinkedIn.LiTr-Filters.1.4.18.nupkg` and `Xam.Plugin.LinkedIn.LiTr-Filters.1.4.18.snupkg` also placed in the initial `Binding` directory.

To get the build error mentioned above you need to open and try build LiTrExample.sln inside the ExampleApp directory. This should restore both of those local nugets. From there you can attempt to build and you should receive the `Cannot implicitly convert type` error mentioned above. Once the app builds I don't expect it to function correctly as it is not finished, but I can't finish it yet because it does not build.

### Did you find any workaround?

Not yet.

### Relevant log output

```shell
I am not sure what log would be relevant. LiTr binding build log using litr-sources.jar, LiTr binding build log using litr.aar, LiTr-Filters binding build log, or LiTrExample Android app build log. I think relevant log messages are mentioned above.

Something not mentioned above is that when I am getting

BINDINGSGENERATOR : warning BG8601: No '<package>' elements found.
```
output I am getting a lot of 
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets(53,5): /somedir/git/Xam.Plugin.LinkedIn.LiTr/Binding/Transforms/Metadata.xml(26,6) warning BG8A04: Metadata.xml element '<attr path="/api/package[@name='com.linkedin.android.litr.transcoder']" />' matched no nodes. [/somedir/git/Xam.Plugin.LinkedIn.LiTr/Binding/Xam.Plugin.LinkedIn.LiTr.csproj]
/somedir/git/Xam.Plugin.LinkedIn.LiTr/Binding/Transforms/Metadata.xml(27,6): warning BG8A04: Metadata.xml element '<attr path="/api/package[@name='com.linkedin.android.litr.utils']" />' matched no nodes. [/somedir/git/Xam.Plugin.LinkedIn.LiTr/Binding/Xam.Plugin.LinkedIn.LiTr.csproj]
```

One for each item in my Metadata.xml. I believe the litr-sources.jar is not being loaded so those warnings are saying that things in my Metadata.xml don't match anything to modify.
```

**Comment by beeradmoore** [comment]
Hey @jpobst . That makes total sense about `-sources.jar` not working. I was under the impression it was building the source.

I put both projects inside the same solution on this [other branch](https://github.com/beeradmoore/xam.plugin.linkedin.litr/tree/reference_project). I was also toying around with some other issues it was giving me such as being unsure if the msbuild command was working correctly, renaming projects to remove - and . on account of msbuild erroring with projects with . in them. I updated the build nuget script to also build XamPluginLinkedInLiTrFilters inside the solution (which I assume builds XamPluginLinkedInLiTr?, I also tried "XamPluginLinkedInLiTr;XamPluginLinkedInLiTrFilters" as the target).

Build output didn't seem to indicate anything was wrong but my releases folder was empty. bin/obj folder look fully populated for the base project, but filters project bin/Release and obj/Release are empty (with the exception of an empty `obj/Release/XamPluginLinkedInLiTrFilters.csproj.FileListAbsolute.txt`)

The nuget package failed with
```
Error NU5019: File not found: 'bin/Release/Xam.Plugin.LinkedIn.LiTr-Filters.dll'.
```
but that filename is wrong in nuspec, and it doens't matter because there is nothing in bin/Release folder anyway.

Full build log of that is here, [msbuild litr with project ref.txt](https://github.com/xamarin/xamarin-android/files/8027894/msbuild.litr.with.project.ref.txt)

Building the same build in VS4Mac under release mode builds the files I'd expect. Here are the debug logs for building the projects, They are in the same solution and referenced correctly but I wanted clear seperate build logs for each project. This is with diagnostics on.

[XamPluginLinkedInLiTr buildlog.txt](https://github.com/xamarin/xamarin-android/files/8028062/XamPluginLinkedInLiTr.buildlog.txt)

**Comment by jpobst** [comment]
Ah, the issue is that `BaseOverlayGlFilter` isn't public:
```java
abstract class BaseOverlayGlFilter implements GlFilter { ... }
```

Java allows public types to inherit from non-public types.  C# does not.  To get around this, the bindings process does what I mentioned before and looks for a base class that is public, and uses that instead.  In this case that is `Java.Lang.Object`.

The "good" news is that Java doesn't actually care about type visibility, so you can use metadata to make the class `public` and then `BitmapOverlayFilter` will be generated correctly:

```xml
<attr path="/api/package[@name='com.linkedin.android.litr.filter.video.gl']/class[@name='BaseOverlayGlFilter']" name="visibility">public</attr>
```

```csharp
public partial class BitmapOverlayFilter : global::Xam.Plugin.LinkedIn.LiTr.Filter.Video.GL.BaseOverlayGlFilter { ... }
```

**Comment by beeradmoore** [comment]
Adding that attr did indeed fix the issue!

I was still having issues with building with my msbuild command line while having both projects in the same solution. I am happy to continue with the second reference the first as NuGet packages through. It seems in the original java project if people wanted to use these filters they'd have to add a second package. I guess in Xamarin land people can just add the second nuget 😂

Now to tidy things up, structure my folders correctly, etc.

Thanks for the help with getting that sorted. Much appreciated.
