### ISSUE TITLE
Xamarin Android Camera 2 - Preview and captured image gets stretched

### ISSUE THREAD

**Issue by DevarajSekar** [xamarin/xamarin-android#6720]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Any version from Android 7.0

### Description

- While taking snaps from Xamarin Android Camera 2 - The preview size and the captured image gets stretched (either vertically or horizontally). 
- This issue/behavior varies from different devices. 
- Even after adjusting the aspect ratio, the issue still persists.

### Steps to Reproduce

- Create a sample using Xamarin android Camera2 or Custom renderer using Xamarin forms application.
- Set size allocation to camera2 preview and the size captured (Default value or any standard values - Device width and height)
- Now, the preview/captured image will be scaled or stretched.

**Sample code snippet** : https://social.msdn.microsoft.com/Forums/en-US/dd78fd71-5543-4377-bce4-4607345c35af/how-could-i-make-camera-full-screen?forum=xamarinandroid 

Issue can be directly reproduced from the documentation sample.

**Stretched image:**
![error_image](https://user-images.githubusercontent.com/42164547/153154760-e5a39e85-b4cc-48c7-946e-55a8bbc4db6a.png)

**Expected Behavior:**

![correct_image](https://user-images.githubusercontent.com/42164547/153154805-a3ad1baf-b29e-48d9-aba5-2004dc1383e5.png)

**Comment by DevarajSekar** [comment]
Hi Team / @xamarin-release-manager ,

Kindly help us to resolve the issue.

Regards,
Devaraj S

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.

**Comment by uiuxexplorer** [comment]
Hi All,

This issue can be handled using scaling factor of Xamarin Android (View / Layouts)

ScaleX / ScaleY

Cheers.
