### ISSUE TITLE
Prebuild events is run second time before Xamarin Android deployment with missing macro variables

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6741]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Prebuild-events-is-run-second-time-befor/1582694)._

---
[severity:I'm unable to use this version]
In the new VS 2022 Current, when a pre-build event is added to a Xamarin project, the command is run once correctly before the build, but also a second time, during the deployment, and this time the macro variables are not evaluated.
This works correctly in VS 2020 – the pre-build event is ran only once, before the build.

Attached is an example project and the full build log.

It has simple pre-build event
! [image.png] (https://aka.ms/dc/image?name=B26ccf155e1c44a89bb0e74b733f5a8f3637723996037620999_20211113-132641-image.png&tid=26ccf155e1c44a89bb0e74b733f5a8f3637723996037620999)

During the build process, the event is correctly run
! [image.png] (https://aka.ms/dc/image?name=Bcb4401cf26b645138ee30efc5e75701e637723996328850592_20211113-132710-image.png&tid=cb4401cf26b645138ee30efc5e75701e637723996328850592)

But during the deployment, the build command is re-run and this time the macros are "*Undefined*"
! [image.png] (https://aka.ms/dc/image?name=B1662d27216404e0f909615df2c6f888e637723996481918130_20211113-132726-image.png&tid=1662d27216404e0f909615df2c6f888e637723996481918130)

---
#### Feedback Bot on 11/14/2021, 11:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/15/2021, 01:22 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sjavashev** [comment]
Just to note that I found a workaround by using a condition on the build event, checking for the incorrect value:
```"Condition=" '$(SolutionDir)' != '*Undefined*' ""

![image](https://user-images.githubusercontent.com/57228456/154043021-84e85fa7-7028-4d09-ae1b-c54cbb4ad34b.png)

**Comment by jpobst** [comment]
@jonathanpeppers Not sure if this is us or VS extension team.

**Comment by jonathanpeppers** [comment]
@sjavashev does the problem happen at the command-line? or only in the IDE?

I think possibly the IDE is running the `Install` target in a second "Deploy" step where `$(SolutionDir)` would be blank.

**Comment by sjavashev** [comment]
> @sjavashev does the problem happen at the command-line? or only in the IDE?
> 
> I think possibly the IDE is running the `Install` target in a second "Deploy" step where `$(SolutionDir)` would be blank.

The problem was related to the deployment part, which I don't know how to run from the command-line, but right know I can't reproduce it even from the IDE!

So it seems to be solved now. Sorry for wasting your time on this!

**Comment by jonathanpeppers** [comment]
@sjavashev let us know if you find something else, thanks!
