### ISSUE TITLE
Conditional ItemGroup for PackageReference not work

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6747]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Conditional-ItemGroup-for-PackageReferen/1417544)._

---
[severity:I'm unable to use this version]
In Android project I use AppCenter.Distribute and GooglePlay simulatenously.
AppCenter Docs says that I need to add to Android project conditional PackageReference entries like below:

```
<ItemGroup Condition=" '$(Configuration)' != 'GooglePlay' ">
    <PackageReference Include="Microsoft.AppCenter.Distribute" Version="3.4.3" />
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)' == 'GooglePlay' ">
    <PackageReference Include="Microsoft.AppCenter.DistributePlay" Version="3.4.3" />
  </ItemGroup>
```
But when I build Release or GooglePlay configurations, Microsoft.AppCenter.DistributePlay package is added to compilation all time.
So something is wrong...

Project attached.

---
#### Feedback Bot on 5/10/2021, 07:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Piotr on 5/11/2021, 00:56 AM: 

<p>I checked few times, when I first build Release configuration all is ok.<br>
Next when I switch to GooglePlay configuration, a DistibutePlay package is added, I see it in Android project References, and in build Logs.<br>
Now, when I switch back to Release configuration, there is no way to remove DistributePlay package. Restore no helps.<br>
I need to remove conditional entry in Android project csproj, cleanup all obj an bin folders and back to project again.<br>
I think something is wrong with configurations and packages.</p>

#### Feedback Bot on 5/12/2021, 09:06 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Jonathan Peppers [MSFT] on 5/13/2021, 06:47 AM: 

<p>Can you attach a <a target='_blank' href="https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output">diagnostic MSBuild log</a> of the issue? Do you see the same problem if you at the build command-line? You can use <code>-p:Configuration=Release</code> or <code>-p:Configuration=GooglePlay</code> to switch configurations.</p>
<p>Thanks!</p>

#### Piotr on 5/18/2021, 07:19 AM: 

(private comment, text removed)
#### Jonathan Peppers [MSFT] on 5/24/2021, 06:29 AM: 

<p>When I look at your 3rd log that is a <code>Release</code> configuration, it has the right <code>PackageReference</code>:</p>
<pre><code><span class="hljs-attr">PackageReference</span>
    <span class="hljs-attr">Microsoft.AppCenter</span>
        <span class="hljs-attr">Version</span> = <span class="hljs-string">3.4.3</span>
    <span class="hljs-attr">Microsoft.AppCenter.Analytics</span>
        <span class="hljs-attr">Version</span> = <span class="hljs-string">3.4.3</span>
    <span class="hljs-attr">Microsoft.AppCenter.Crashes</span>
        <span class="hljs-attr">Version</span> = <span class="hljs-string">3.4.3</span>
    <span class="hljs-attr">Microsoft.AppCenter.Distribute</span>
        <span class="hljs-attr">Version</span> = <span class="hljs-string">3.4.3</span>
    <span class="hljs-attr">Prism.Unity.Forms</span>
        <span class="hljs-attr">Version</span> = <span class="hljs-string">8.0.0.1909</span>
    <span class="hljs-attr">Xamarin.Essentials.Interfaces</span>
        <span class="hljs-attr">Version</span> = <span class="hljs-string">1.5.3.2</span>
    <span class="hljs-attr">Xamarin.Forms</span>
        <span class="hljs-attr">Version</span> = <span class="hljs-string">4.8.0.1364</span>
</code></pre>
<p>Does this issue happen at the command-line?</p>
<p>It doesn’t actually seem related to Xamarin.Android, but something with the IDE and NuGet?</p>

#### Feedback Bot on 6/1/2021, 07:02 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Piotr on 6/1/2021, 11:49 PM: 

(private comment, text removed)
#### Jonathan Peppers [MSFT] on 6/10/2021, 06:10 AM: 

<p>Sorry, it’s been a while, did you try the command-line? I’m trying to understand if this is a Visual Studio issue. This is a general MSBuild feature you’re using, so it doesn’t seem like you should need the workaround with <code>&lt;Choose&gt;</code>/<code>&lt;When&gt;</code> you posted here.</p>

#### Piotr on 6/14/2021, 02:03 AM: 

(private comment, text removed)
#### Jonathan Peppers [MSFT] on 6/14/2021, 06:42 AM: 

(private comment, text removed)
#### Piotr on 6/15/2021, 00:38 AM: 

(private comment, text removed)
#### Piotr on 6/15/2021, 01:54 AM: 

(private comment, text removed)
#### Feedback Bot on 7/13/2021, 07:39 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 9/5/2021, 08:21 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Piotr on 12/7/2021, 08:31 AM: 

<p>I discover Visual Studio not refresh nuget package references after configuration switch from for ex. Release to Debug and GooglePlay, when project use conditional element.</p>

#### Piotr on 12/8/2021, 04:50 AM: 

<p>How about this problem?</p>

#### Piotr on 12/9/2021, 01:31 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
This seems like a VS general issue with supporting `Condition` on `PackageReference`.  If this still occurs it should be refiled in DevCom.
