### ISSUE TITLE
incompatible with attribute textColor error seen when code was migrated to VS2019

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6748]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/incompatible-with-attribute-textColor-er/1396323)._

---
[regression] [worked-in:VS2017 Community.]
Noticing a new error when I attempted to build a solution for the first time in VS 2019.

A whole series of "incompatible with attribute" is being reported when I tried to build for the first time in VS2019 - when the project at least compiled correctly.

! [image.png] (https://aka.ms/dc/image?name=Be38e7f0beb844eb7a09443e0c094b25f637538567564468475_20210412-133915-image.png&tid=e38e7f0beb844eb7a09443e0c094b25f637538567564468475)

---
#### Feedback Bot on 4/12/2021, 07:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/13/2021, 07:10 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 8/2/2021, 00:28 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
This is pretty old, so I'm going to assume it is no longer relevant.  If the issue persists, please comment and I can re-open.
