### ISSUE TITLE
Xamarin android . Net6 build error: generated code Google.GMS 'AppStateBuffer' does not implement inherited abstract member 'DataBuffer.Get(int)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6753]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-android-Net6-build-error:-gener/1639219)._

---
[severity:I'm unable to use this version]
I’m trying to build xamarin android project after converting to “.net6.0-android31.0” but it results in build errors in .net 6.0 generated code:

CS0534	'AppStateBuffer' does not implement inherited abstract member 'DataBuffer.Get(int)'	D:\XX\XX.Droid\obj\Release\net6.0-android31.0\generated\src\Com.Google.Android.Gms.Appstate.AppStateBuffer.cs	10	N/A

CS0534	'AchievementBuffer' does not implement inherited abstract member 'DataBuffer.Get(int)'	D:\XX\XX.Droid\obj\Release\net6.0-android31.0\generated\src\Com.Google.Android.Gms.Games.Achievement.AchievementBuffer.cs	10	N/A

CS0534	'GameBuffer' does not implement inherited abstract member 'DataBuffer.Get(int)'		D:\XX\XX.Droid\obj\Release\net6.0-android31.0\generated\src\Com.Google.Android.Gms.Games.GameBuffer.cs	10	N/A

CS0534	'LeaderboardScoreBuffer' does not implement inherited abstract member 'DataBuffer.Get(int)'		D:\XX\XX.Droid\obj\Release\net6.0-android31.0\generated\src\Com.Google.Android.Gms.Games.Leaderboard.LeaderboardScoreBuffer.cs	10	N/A

CS0534	'ParticipantBuffer' does not implement inherited abstract member 'DataBuffer.Get(int)'		D:\XX\XX.Droid\obj\Release\net6.0-android31.0\generated\src\Com.Google.Android.Gms.Games.Multiplayer.ParticipantBuffer.cs	10	N/A

CS0534	'PlayerBuffer' does not implement inherited abstract member 'DataBuffer.Get(int)'	
D:\XX\XX.Droid\obj\Release\net6.0-android31.0\generated\src\Com.Google.Android.Gms.Games.PlayerBuffer.cs	10	N/A

I'm not sure how to fix the generated code, i've tried different nu package "Xamarin.GooglePlayServices.Maps" versions: 29.0, 42.1021.1, 117.0, and latest 117.0.1.3 all result in same errors.

This is the closest thing i found on this error "https://social.msdn.microsoft.com/Forums/en-US/d54264bb-2a0d-44c2-ac58-e9ba88a76a39/google-maps-v2-and-quotdoes-not-implement-inherited-abstract-memberquot-messages?forum=xamarinandroid" but it says use old versions like "Xamarin.Android 4.6.8" and android sdk "22.0.1" while i'm using latest VS 2022 17.1 preview 2

Any clue how to proceed?

---
#### Feedback Bot on 1/17/2022, 11:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/20/2022, 06:43 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 1/23/2022, 01:38 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
Are you trying to create your own bindings of GooglePlayServices libraries?

We maintain bindings of these on NuGet:
https://www.nuget.org/packages/Xamarin.GooglePlayServices.Games
