### ISSUE TITLE
Cannot find the menu.xml under resources on a Xamarin application

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6754]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Cannot-find-the-menuxml-under-resources/1345959)._

---
[severity:It's more difficult to complete my work]
Steps:
Create a new Android App(Xamarin) or clone the project (https://github.com/marius02/QuizApp)
Add new Item -> Menu.xml from the template
Refere it in the activity_main.xml -> app:menu="@menu/navMenu" (using my example)
Notice the folowing error (Severity	Code	Description	Project	File	Line	Suppression State
Error		resource menu/navMenu (aka com.companyname.quizapp:menu/navMenu) not found.	QuizApp	D:\Git_Repo\QuizApp\QuizApp\Resources\layout\activity_main.xml	2	
) even if the xml file is corectly refer.

---
#### Feedback Bot on 2/22/2021, 05:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/22/2021, 07:19 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
This is very old, so I'm assuming it is no longer relevant.  If the issue persists, comment and I can re-open.
