### ISSUE TITLE
Xamarin.Android BuildVersionCodes.R has an invalid value

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6755]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/XamarinAndroid-BuildVersionCodesR-has-/1300570)._

---
[severity:It's more difficult to complete my work]
Xamarin.Android's `BuildVersionCodes.R` has an invalid value of `10000` instead of `30`: https://developer.android.com/reference/android/os/Build.VERSION_CODES#R

---
#### Feedback Bot on 1/4/2021, 10:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/5/2021, 01:31 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 1/5/2021, 01:32 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
This is often the case when an API level is still in beta or preview, and sometimes does not get updated in a timely manner.

This looks like it has been fixed since this report was filed:

`src/Mono.Android/map.csv`:
```
E,28,android/os/Build$VERSION_CODES.P,28,Android.OS.BuildVersionCodes,P,remove,
E,29,android/os/Build$VERSION_CODES.Q,29,Android.OS.BuildVersionCodes,Q,remove,
E,30,android/os/Build$VERSION_CODES.R,30,Android.OS.BuildVersionCodes,R,remove,
E,31,android/os/Build$VERSION_CODES.S,31,Android.OS.BuildVersionCodes,S,remove,
E,32,android/os/Build$VERSION_CODES.S_V2,32,Android.OS.BuildVersionCodes,SV2,remove,
```
