### ISSUE TITLE
Animation fails in release mode, while debug works fine in Xamarin Android.

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6756]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Animation-fails-in-release-mode-while-d/1236125?preview=true)._

---
[severity:It bothers me. A fix would be nice]
A Morphin Animation in Xamarin.Android release mode fails, while in debug mode is works fine. 

In our xamarin android app (Android 10) we use a morphing animation.
An AnimatedVectorDrawable  is created using latest AndroidX.Core" Version="1.3.0.3, by

using (var wrapper = new ContextThemeWrapper(this.context, styleID))
 {
    var drawable = ResourcesCompat.GetDrawable(this.context.Resources, resourceID, wrapper.Theme);
 }

In debug : drawable is AnimatedVectorDrawable
In release : drawable is DrawableInvoker.

Issue was already detected in previous Android .Support.Library and reported to Xamarin Forum, see
https://forums.xamarin.com/discussion/181176/why-fails-animation-in-release-mode-while-debug-works-fine

After upgrading to AndroidX, it is still present.

---
#### Feedback Bot on 10/28/2020, 11:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Zack Yang [MSFT] on 10/30/2020, 00:19 AM: 

<p>Thanks for your feedback!<br>
Please try to install the sample project via this link: <a target='_blank' href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/simple">https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/simple</a>, then run it in Xamarin.Android release mode and confirm whether it is normal.<br>
If possible, provide us your sample project.<br>
We look forward to hearing from you!</p>

#### Feedback Bot on 10/30/2020, 08:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/9/2020, 03:24 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Jonathan Peppers [MSFT] on 11/10/2020, 07:10 AM: 

<p><a target='_blank' href="https://aka.ms/dc/u?aid=277748">Robert van Dillen</a> can you share the small demo project?</p>
<p>Is the issue only occurring when <code>AndroidLinkMode=Full</code>? If you can’t share the project, can you share a broken <code>.apk</code> file? I can check if there a type the linker removed.</p>
<p>You can use the “private” option when replying and only Microsoft employees can see it.</p>

#### Jonathan Peppers [MSFT] on 11/10/2020, 07:10 AM: 

<p>Let me know if you can share more info, thanks!</p>

#### Robert van Dillen on 11/10/2020, 11:18 AM: 

(private comment, text removed)
#### Feedback Bot on 11/16/2020, 09:58 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 5/26/2021, 06:10 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 7/5/2021, 11:35 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
#### Jonathan Peppers [MSFT] solved on 11/5/2020, 09:27 AM, 0 votes: 

<p>It sounds like you solved your issue, let us know if you need something else, thanks!</p>

#### Robert van Dillen on 11/7/2020, 01:10 PM: 

(private comment, text removed)
#### Jonathan Peppers [MSFT] on 11/9/2020, 08:42 AM: 

<p>Hmm <a target='_blank' href="https://aka.ms/dc/u?aid=277145">rvdillen</a>’s comment is blank now – maybe it got lost when this site migrated to the new version? <a target='_blank' href="https://aka.ms/dc/u?aid=277145">rvdillen</a> is this issue solved for you?</p>
<p><a target='_blank' href="https://aka.ms/dc/u?aid=277748">Robert van Dillen</a> am I correct in understanding the issue only occurs with Android Support and not AndroidX? Google Play requires Android 29 – which means you need to be on AndroidX going forward.</p>
<p><a target='_blank' href="https://developer.android.com/distribute/play-policies">https://developer.android.com/distribute/play-policies</a></p>
<p>Are you able to switch to AndroidX? Thanks!</p>

#### Robert van Dillen on 11/9/2020, 11:09 AM: 

<p><a target='_blank' href="https://aka.ms/dc/u?aid=82859">Jonathan Peppers [MSFT]</a></p>
<p>I added a comment on Saturday, but it’s disappeared.<br>
So I try again today.</p>
<p>No, the issue is NOT solved.</p>
<p>I can demonstrate the issue with 2 lines of code:</p>
<pre><code><span class="hljs-keyword">string</span> type = buttonImage.Drawable.GetType().Name;
Device.SendToast(<span class="hljs-string">$"Drawable is <span class="hljs-subst">{type}</span>"</span>);
</code></pre>
<p>Inspect the 2 attached screenshots one for debug and release build.<br>
See the difference in toast and animation of the lock image.</p>
<p>NB:</p>
<ul>
<li>This app is an Xamarin.Android app (target api 29), NOT Xamarin Forms;</li>
<li>Many animations in the App do work, but not this vector morphing.</li>
<li></li>
</ul>
<p>The issue was already reported in 28 april 2020 using the previous<br>
Android support library. The issue was then easy to reproduce,<br>
so I’ve send a single page demoapp to ‘jezh’ as evidence.<br>
Unforunately there was no response, see<br>
<a target='_blank' href="https://forums.xamarin.com/discussion/181176/why-fails-animation-in-release-mode-while-debug-works-fine">https://forums.xamarin.com/discussion/181176/why-fails-animation-in-release-mode-while-debug-works-fine</a></p>
<p>After upgrading the support library to AndroidX in our business App,<br>
the issue was still there. So I decided to report it again.</p>
<p>Unfortunately I can not reproduce the issue with the small demo project anymore.<br>
When I upgraded the demo project with AndroidX, it works fine in debug and release.<br>
I can not send you the Business App with the Issue.</p>
<p><img src="https://aka.ms/dc/image?name=B77cd61e81eb7469e8e75caace09c4aa4637405453341408189_screenshot-debug.jpg&amp;tid=77cd61e81eb7469e8e75caace09c4aa4637405453341408189" alt="screenshot-debug.jpg"></p>
<p><img src="https://aka.ms/dc/image?name=B5fa792f8502944a2bf4b4ed5919840ce637405456333641934_screenshot-release.jpg&amp;tid=5fa792f8502944a2bf4b4ed5919840ce637405456333641934" alt="screenshot-release.jpg"></p>

**Comment by jpobst** [comment]
This is very old, so I'm assuming it is no longer relevant.
