### ISSUE TITLE
.Net 6 Android - breakpoints not hit on class libraries

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6758]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-6-Android---breakpoints-not-hit-on-/1414059)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.10.0 p2]
Since VSC 16.10.0 p2.1, breakpoints does not hit in class libraries. It does hit on the main startup project. 

Attached solution for reproduction - any breakpoint in TestLibrary.Class1.Foo() will not be hit. On MainActivity or Startup classes, breakpoint will hit but will not step into methods in class library.

---
#### Feedback Bot on 5/5/2021, 08:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/18/2021, 01:39 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 9/5/2021, 08:29 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
There has been a lot of work on .NET 6 Android since this early preview, so I'm going to assume this has been fixed elsewhere.  If not, please comment and I can re-open.
