### ISSUE TITLE
ADB binary is obsolete and has serious performance problems

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6759]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ADB-binary-is-obsolete-and-has-serious-p/1473688)._

---
[severity:It bothers me. A fix would be nice]
When launching an Android emulator for Xamarin a message periodically pops up indicating that the ADB binary is out of date and has serious performance problems.

>The ADB binary found at "C:\Program Files (x86)\Android\android-sdk\platform-
>tools\adb.exe is obsolete and has seriousperformance [sic] problems with the
>Android Emulator. Please update to a newer version to get **significantly** faster
>app/file transfer. [emphasis mine]

---
#### Feedback Bot on 7/13/2021, 07:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/14/2021, 06:23 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 11/1/2021, 01:33 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
@grendello Do you know if we have updated to a newer `adb` that does not emit this warning?

**Comment by grendello** [comment]
Xamarin.Android doesn't control the version of Android SDK (which `adb` is part of) that's installed on the user's machine. The SDK there is (likely) installed by the Visual Studio Installer (or the user themselves). I don't think we can do anything here.

**Comment by jpobst** [comment]
This was filed against VS2019 16.10.  We'll assume this has been updated in newer versions of VS 2022.  If not, it can be re-opened and routed to the VS extension team.
