### ISSUE TITLE
Cannot compile release build using Xamarin.Android

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6761]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-compile-release-build-using-Xamar/1520864)._

---
[severity:I'm unable to use this version]
I can build my project fine in Debug mode, but not in Release mode. I get compile-time errors that I do not understand. After exhaustive googling, I have tried restarting my machine, updating VS, repairing VS, all with the same errors result upon trying to build Release.

Windows 10, VS2019 v16.11.2

Errors:
```Severity	Code	Description	Project	File	Line	Suppression State
Error		at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)	Muffed_Android_Demo			
Error		at System.Reflection.PortableExecutable.PEBuilder.Serialize(BlobBuilder builder)	Muffed_Android_Demo			
Error		at System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeTextSection(SectionLocation location)	Muffed_Android_Demo			
Error		Parameter name: mappedFieldDataStreamRva	Muffed_Android_Demo			
Error		Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName, Nullable`1 requestId)	Muffed_Android_Demo			
Error		at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)	Muffed_Android_Demo			
Error		at System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeSection(String name, SectionLocation location)	Muffed_Android_Demo			
Error		at System.Reflection.Throw.ArgumentOutOfRange(String parameterName)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, ICompilerServerLogger logger, Nullable`1 requestId)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)	Muffed_Android_Demo			
Error		at System.Reflection.PortableExecutable.PEBuilder.SerializeSections()	Muffed_Android_Demo			
Error		at System.Reflection.Metadata.Ecma335.MetadataRootBuilder.Serialize(BlobBuilder builder, Int32 methodBodyStreamRva, Int32 mappedFieldDataStreamRva)	Muffed_Android_Demo			
Error		at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)	Muffed_Android_Demo			
```

---
#### Feedback Bot on 9/2/2021, 11:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/6/2021, 02:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jared Parsons [MSFT] on 9/9/2021, 08:45 AM: 

<p>Thanks for taking the time to file this feedback issue. This looks like the compiler is running into an error during compilation but unfortunately there isn’t enough information here for me to see what is going on.</p>
<p>Can you provide a small sample that reproduces this behavior? If not can you get a binary log of the build or grab a crash dump of the compiler when this occurs?</p>

#### Sam on 9/9/2021, 11:32 AM: 

(private comment, text removed)
#### Jared Parsons [MSFT] on 9/9/2021, 11:42 AM: 

<p>Thanks for uploading that file. It’s actually showing an error further up the stack (Xamarin resolving assemblies). The stack trace there indicates that one of the references it’s looking at isn’t actually a .NET reference. Going to route to them for further investigation.</p>

#### Sam on 9/9/2021, 11:44 AM: 

(private comment, text removed)
#### Feedback Bot on 9/9/2021, 11:44 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Jared Parsons [MSFT] on 9/9/2021, 11:50 AM: 

(private comment, text removed)
#### Sam on 9/9/2021, 00:14 PM: 

(private comment, text removed)
#### Feedback Bot on 11/9/2021, 02:48 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
I'm assuming this is no longer relevant.  If this is still an issue please comment and I can re-open it.
