### ISSUE TITLE
System:NullReferenceException 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6762]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/System:NullReferenceException/1654833)._

---
[severity:I'm unable to use this version]
[Screenshot (115).png] (https://aka.ms/dc/file?name=B464b89c2b23648a69519b6270c5e3ae0637796768046258219_Screenshot_(115).png&tid=464b89c2b23648a69519b6270c5e3ae0637796768046258219)

I can not fix this error.

---
#### joepuhich2 on 2/6/2022, 01:19 PM: 

<p>Is the fix in an update I do not have ???<br>
This error has been here for a year…</p>

#### joepuhich2 on 2/6/2022, 01:23 PM: 

<p>I have tried ??<br>
I have de NULL ed.<br>
I have tried moving the code around.<br>
I can not get this code to work.</p>

#### Feedback Bot on 2/6/2022, 11:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 2/8/2022, 01:41 AM: 

<p>Thanks for your feedback.<br>
We guess where you should set the text property of the EditText control to null. But we’re not sure since we don’t have your demo.</p>
<p>Suggestion:<br>
Change line 293 (in Screenshot (115).png) scankeyinput = e.Text.ToString(); to scankeyinput = e.Text?.ToString();<br>
Then have a try.</p>

#### joepuhich2 on 2/8/2022, 08:27 AM: 

(private comment, text removed)
#### joepuhich2 on 2/8/2022, 08:17 AM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 2/9/2022, 03:17 AM: 

<p>I’m glad to see that you provided the code.<br>
System:NullReferenceException look like cased by your code.<br>
In file MainActivity.cs, replace all “e.Text.” with “e?.Text?.”<br>
For example for line 121:  change textView_1.Text = e.Text.ToString();  to  textView_1.Text = e?.Text?.ToString();</p>

#### joepuhich2 on 2/9/2022, 00:21 PM: 

<p>I migrated my vs2019 to vs2022.<br>
My Resource.designer.cs file is now generating a lot of errors !!!<br>
and I cannot figure a way to clear the errors.</p>
<pre><code>        var button_0 = FindViewById&lt;Button&gt;(Resource.Id.Button0);
        var button_1 = FindViewById&lt;Button&gt;(Resource.Id.Button1);
        var button_2 = FindViewById&lt;Button&gt;(Resource.Id.Button2);
        var button_3 = FindViewById&lt;Button&gt;(Resource.Id.Button3);
        var button_4 = FindViewById&lt;Button&gt;(Resource.Id.Button4);
        var button_5 = FindViewById&lt;Button&gt;(Resource.Id.Button5);
        var button_6 = FindViewById&lt;Button&gt;(Resource.Id.Button6);
        var button_7 = FindViewById&lt;Button&gt;(Resource.Id.Button7);
        var button_8 = FindViewById&lt;Button&gt;(Resource.Id.Button8);
        var button_9 = FindViewById&lt;Button&gt;(Resource.Id.Button9);

        button_0.Click += delegate { OnClickButton0(); };
        button_1.Click += delegate { OnClickButton1(); };
        button_2.Click += delegate { OnClickButton2(); };
        button_3.Click += delegate { OnClickButton3(); };
        button_4.Click += delegate { OnClickButton4(); };
        button_5.Click += delegate { OnClickButton5(); };
        button_6.Click += delegate { OnClickButton6(); };
        button_7.Click += delegate { OnClickButton7(); };
        button_8.Click += delegate { OnClickButton8(); };
        button_9.Click += delegate { OnClickButton9(); };

        var textView_4 = FindViewById&lt;TextView&gt;(Resource.Id.textView4);
        var textView_5 = FindViewById&lt;TextView&gt;(Resource.Id.textView5);
        var textView_6 = FindViewById&lt;TextView&gt;(Resource.Id.textView6);
        var textView_7 = FindViewById&lt;TextView&gt;(Resource.Id.textView7);
        var textView_8 = FindViewById&lt;TextView&gt;(Resource.Id.textView8);
        var textView_9 = FindViewById&lt;TextView&gt;(Resource.Id.textView9);
        var textView_10 = FindViewById&lt;TextView&gt;(Resource.Id.textView10);
        var textView_11 = FindViewById&lt;TextView&gt;(Resource.Id.textView11);
        var textView_12 = FindViewById&lt;TextView&gt;(Resource.Id.textView12);
        var textView_13 = FindViewById&lt;TextView&gt;(Resource.Id.textView13);
        var textView_14 = FindViewById&lt;TextView&gt;(Resource.Id.textView14);
        var textView_15 = FindViewById&lt;TextView&gt;(Resource.Id.textView15);

        var tableRow_1 = FindViewById&lt;TableRow&gt;(Resource.Id.tableRow1);
        var tableRow_2 = FindViewById&lt;TableRow&gt;(Resource.Id.tableRow2);
        var tableRow_3 = FindViewById&lt;TableRow&gt;(Resource.Id.tableRow3);
        var tableRow_4 = FindViewById&lt;TableRow&gt;(Resource.Id.tableRow4);

        var tableLayout_1 = FindViewById&lt;TableLayout&gt;(Resource.Id.tableLayout1);
</code></pre>

#### joepuhich2 on 2/9/2022, 00:30 PM: 

<p>How do you compile activity_main.xml<br>
<a target='_blank' href="https://aka.ms/dc/file?name=B39b06fbe47a448ca8862a1dca2c9f4e3637800353708271898_Screenshot_(122).png&amp;tid=39b06fbe47a448ca8862a1dca2c9f4e3637800353708271898">Screenshot (122).png</a><br>
in vs2022 ???</p>

#### joepuhich2 on 2/9/2022, 04:27 PM: 

<p>In file MainActivity.cs, replace all “e.Text.” with “e?.Text?.”<br>
For example for line 121: change textView_1.Text = e.Text.ToString(); to textView_1.Text = e?.Text?.ToString();</p>
<p>scankeyinput = e?.Text?.ToString();</p>
<p>This code returns a null;<br>
I am trying to return any character that the key pressed is.</p>
<p>Getting closer ???</p>

#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 2/9/2022, 10:10 PM: 

<p>Actually, the problem you described is not reproduced on our machines.<br>
When debugging your project on 16.11.9 ( Installed workload: Mobile development with .NET and .NET desktop development with optional .NET Portable Library targeting pack ), there is an error: MSB6006: “java.exe” exited with code2.<br>
<img src="https://aka.ms/dc/image?name=B40c52a6dde824ee09c5840a98b1f1a4c637800705491686328_Debugging2019.jpg&amp;tid=40c52a6dde824ee09c5840a98b1f1a4c637800705491686328" alt="Debugging2019.jpg"></p>
<p>But debugging your project on 17.0.5 (VS 2022: Installed workload: Mobile development with .NET and .NET desktop development with optional .NET Portable Library targeting pack ), everything works well, and I didn’t change any code, no Exception.<br>
<img src="https://aka.ms/dc/image?name=B17b77fb38956463a82bcbcf941b6f2aa637800705632774333_Debugging2022.jpg&amp;tid=17b77fb38956463a82bcbcf941b6f2aa637800705632774333" alt="Debugging2022.jpg"></p>

#### Feedback Bot on 2/9/2022, 10:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### joepuhich2 on 2/10/2022, 02:48 AM: 

<p>Yes, That is how the program works.<br>
If you bring up the keyboard and input key strokes, data goes into the database.<br>
Then click on button1, The program takes you to the search method.<br>
Then if you press a key, the program goes into a loop in the search method.<br>
Here I will show you !!!</p>
<p>The program goes into search and reads a null every time the key is pressed.<br>
at the code<br>
<a target='_blank' href="https://aka.ms/dc/file?name=B39cabe1f37cf48d3b59e53070c5d7efc637800863770176208_Screenshot_(124).png&amp;tid=39cabe1f37cf48d3b59e53070c5d7efc637800863770176208">Screenshot (124).png</a><br>
scankeyinput = e?.Text?.ToString();<br>
At line 296 in search method.</p>
<p>Notice line 294<br>
private static void EditV2_TextChanged(object sender, Android.Text.TextChangedEventArgs e)<br>
is where TextChanged should give a key pressed response.<br>
I have to call it from line 276 !!!</p>
<pre><code>public static string Read_New_key()
	{
		//			EditV_2.TextChanged += EditV2_TextChanged;
</code></pre>
<p>line 276						EditV2_TextChanged(sender, e);<br>
//			MainActivity.TextBox1_TextChanged(sender, e);<br>
//			MainActivity.EditV2_TextChanged(sender, e);</p>
<p>From what I think<br>
private static void EditV2_TextChanged(object sender, Android.Text.TextChangedEventArgs e)<br>
should give a keypressed without being called from line 276 ???</p>

#### Feedback Bot on 2/10/2022, 06:32 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.
