### ISSUE TITLE
APT2259 linker error when converting app project to library project

### ISSUE THREAD

**Issue by dk-jlew** [xamarin/xamarin-android#6767]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VSMac 8.10.17 (build 2)

### Description

We currently have a large Xam.Forms app which actually builds two different products from a single Xamarin.Android app project.  I am trying to split the project into two (one per product) app projects, which each reference a common "base app" library.  First step was converting the existing app project to a library, by removing the `<AndroidApplication>true</AndroidApplication>` property from the `csproj`.  With no other changes, I can no longer build the project:
```
1>/[...appdir...]/obj/Casino/Debug/AnyCPU/lp/230/jl/res/layout/mtrl_calendar_month_navigation.xml(33): Error APT2259 : 'textEnd' is incompatible with attribute iconGravity (attr) flags [start=1, textStart=2] [weak].
1>/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(157,3): Error APT2061 : failed linking file resources.
```

There seem to be similar problems for people upgrading to Xamarin Forms 5 (I am still on 4.8), but it's unclear what the underlying problem is or how to proceed in this case.  Disabling aapt2 produces a raft of other errors.

### Steps to Reproduce

You'd have to be building our app, I have no way to distill any further without guidance.  binlog attached.

[msbuild.binlog.gz](https://github.com/xamarin/xamarin-android/files/8082321/msbuild.binlog.gz)

### Did you find any workaround?

No.

### Relevant log output

```shell
See attached binlog (in steps to reproduce)
```

**Comment by jonathanpeppers** [comment]
There is some information here: https://stackoverflow.com/questions/63168050/android-resource-linking-failed-android-studio

Are the same versions of packages being used after you moved things around? I've seen something like this and downgrading either Google.Material or AndroidX packages solved it.
