### ISSUE TITLE
App size significantly increased with Xamarin.Android 12.2

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-android#6776]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS17.1 + Xamarin.Android 12.2

### Description

When building my app on VS 17.0.5 and Xamarin.Android 12.1.0.5, my .aab file is ~36 MB large.
With VS17.1 + Xamarin.Android 12.2, the same app now builds to a .aab which is ~39 MB large.
I am using Startup Tracing.

I tried to find Release Notes to see what could have changed causing the 3 MB increase, but wasn't able to find them.
When inspecting the .aab files, it seems like the "libaot-MyApp.dll.so" file went from 238 KB to almost 4 MB. Why?

### Steps to Reproduce

- Build -> Archive (in Release mode)
- Inspect .aab size

**Comment by jonathanpeppers** [comment]
This was an improvement for startup times: https://github.com/xamarin/xamarin-android/pull/6482 We started full AOT-ing the "main" app assembly.

Is the startup time of your app better/worse? I've been using [this script](https://github.com/jonathanpeppers/maui-profiling#faq) to measure this.

You might also be able to record a custom AOT profile for your app, if you want less of your app to be AOT'd.

**Comment by tipa** [comment]
Thanks for the quick response. I used the script you linked and measured both variants using a Samsung A54:

Xamarin.Android 12.1.0.5:
```
Average(ms): 1423.2
Std Err(ms): 4.50875691170958
Std Dev(ms): 14.257941257029
```

Xamarin.Android 12.2:
```
Average(ms): 1304.1
Std Err(ms): 6.93373396278417
Std Dev(ms): 21.9263920120632
```

Installed App size is even 4 MB larger than before.
So there is a slight improvement, but for me it's not worth the 4 MB.
I will look into custom AOT profiles and see if that helps bringing my app size down again.

**Comment by jonathanpeppers** [comment]
@tipa another simple option might be to move some of your app's code to another project

Anything you have that wouldn't be called on startup.

**Comment by tipa** [comment]
I already have most of my code in a Shared Project but I guess that "counts" as the same project as it's in the same dll?
I'd want to avoid having to restructure my whole code and outsource it to yet another project just for the sake of app size optimization.
Is there a way to exclude my app's binary from AOT to get the same behavior as previously?

**Comment by jonathanpeppers** [comment]
How many architectures is the `.aab` file? You might want to be comparing what Google Play says the app is for a specific device & architecture.

**Comment by tipa** [comment]
The aab contains all 4 architectures (armeabi-v7a + arm64-v8a + x86 + x86_64).
Would you expect the app size delta to be lower when comparing in Google Play?
From my experience, the app sizes are pretty comparable when deploying from VS and when downloading from the Store

**Comment by jonathanpeppers** [comment]
When you download from Google Play you get one architecture specific for your device.

They should give a breakdown of file size. If you see your `.aab` go from 36MB to 39MB, then that is actually only .75MB increase if you have 4 architectures inside.

**Comment by tipa** [comment]
When I compared the `libaot-MyApp.dll.so` sizes, I didn't compare the compressed size (which went form 55 KB zu 904 KB) but the uncompressed size (238 KB to almost 4 MB), which is how it will be stored on the phone after the download. And when deploying the app from VS to the phone, the installed app size was also 4 MB larger.

I did the same profiling using your script on my Pixel 5.
Xamarin.Android 12.1.0.5:
```
Average(ms): 1062.8
Std Err(ms): 1.88443920334701
Std Dev(ms): 5.95911999468975
```

Xamarin.Android 12.2:
```
Average(ms): 947.6
Std Err(ms): 6.9716887799474
Std Dev(ms): 22.0464156824742
```

So this is about 10% startup gain for 10% larger installed app size (37 MB or 41 MB). Perhaps this is preferable for most developers, but I lately tried to optimize for app size so this is kind of a set-back.
If there's no switch to get back the old behavior, I will try the manual startup profiles to see if I can get a better tradeoff there.

**Comment by tipa** [comment]
I now profiled my app startup and used a custom profile.
This caused the app size to increase by another 2 MB, but the startup size went down even more.

Xamarin.Android 12.1.0.5 (installed app size 37.31 MB):
```
Average(ms): 1423.2
Std Err(ms): 4.50875691170958
Std Dev(ms): 14.257941257029
```

Xamarin.Android 12.2 (installed app size 41.38 MB):
```
Average(ms): 1304.1
Std Err(ms): 6.93373396278417
Std Dev(ms): 21.9263920120632
```

Xamarin.Android 12.2 (with custom profile, installed app size 43.48 MB):
```
Average(ms): 1048.7
Std Err(ms): 6.29117547751522
Std Dev(ms): 19.8944436687455
```

It looks like more of `libaot-mscorlib.dll.so` was `AOT`'d
Is there a way to cherry-pick/exclude assemblies to AOT?

**Comment by jonathanpeppers** [comment]
I filed: https://github.com/xamarin/xamarin-android/issues/6779 to track this.

**Comment by jonathanpeppers** [comment]
I think the workaround for you could be to not use a "Shared Project" and either use a `netstandard` or Xamarin.Android class library.

I don't know if you have iOS code as well, though.

**Comment by tipa** [comment]
Thanks for tracking this in a new issue.
I have projects for Android, Windows, iOS and macOS. Plus the Shared project already makes 5 projects.
Currently, adding another (or another bunch) of projects to save 1 or 2 MB is not worth it. Thanks for suggesting it thought!

**Comment by jonathanpeppers** [comment]
Well, you could add 1 Xamarin.Android class library that references your shared project.

Then the main app references the class library.

**Comment by dellis1972** [comment]
Another option might be an Sdk style Multi Target project to replace the shared one, using something like [SDkExtras](https://www.nuget.org/packages/MSBuild.Sdk.Extras/) .

**Comment by dellis1972** [comment]
I used to use Shared Projects allot when doing GameDev as it lets you use `#if` blocks for little bits of platform specific code. So I totally understand :D
