### ISSUE TITLE
OS not working for C# Xamarin Android 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6793]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/OS-not-working-for-C-Xamarin-Android/1662320)._

---
[severity:I'm unable to use this version]
I am using C# Xamarin Android.

OS calls for the following are not operating:

1:  ToString();
2:  File read;
3:  File write;
4: TextChanged;
5: MainActivity;

My code works.
The OS code for the above functions do not work !!!!

Is there a way to make these functions work????

---
#### Feedback Bot on 2/13/2022, 10:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/16/2022, 08:15 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### joepuhich2 on 2/21/2022, 09:47 AM: 

<p>These functions are not working.<br>
I need these functions to work or my project is scrap.</p>

---
### Original Solutions
(no solutions)

**Comment by pasha-o** [comment]
this could be related to https://developercommunity.visualstudio.com/t/latest-visual-studio-2022-update-version-171-and-c/1672337?from=email&viewtype=all

**Comment by joepuhich** [comment]
protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            TextView tv = new TextView(this);
            AssetManager assets = this.Assets;

            string content_upload2;
            using (StreamReader sr = new StreamReader(assets.Open("read_asset.txt")))
            {
                content_upload2 = sr.ReadToEnd();
            }

            string content_upload;
            using (StreamReader sr = new StreamReader(assets.Open("upload.txt")))
            {
                content_upload = sr.ReadToEnd();
            }

**Comment by joepuhich** [comment]
The code above does not generate a string content_upload.

**Comment by joepuhich** [comment]
Am I missing a flag to set file to read enable ????

**Comment by joepuhich** [comment]
[upload.txt](https://github.com/xamarin/xamarin-android/files/8672365/upload.txt)

**Comment by joepuhich** [comment]
vs2022 bugs

**Comment by joepuhich** [comment]
Am I missing something to make the OS operate properly or is this the way it is suppose to work?

**Comment by joepuhich** [comment]
Is the third party controlling the OS ???

**Comment by joepuhich** [comment]
HERE IS THE CODE FROM MY PROJECT.
I have been chasing read and write code for 2 years. I can not get it to work.


       protected override void OnCreate(Bundle bundle)
         {
            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            Context context = Android.App.Application.Context;
 
            base.OnCreate(bundle);
            TextView tv = new TextView(this);
            AssetManager assets = this.Assets;
   
            string content_upload;
            using (StreamReader sr = new StreamReader(assets.Open("upload.txt")))
            {
                content_upload = sr.ReadToEnd();
            }

            qq = 0;
            for (leep = 0; leep <= 500; leep++)
            {
                for (lep = 0; lep <= 20; lep++)
                {
                    Tester.garage_array_database[lep, leep] = MainActivity.content_upload[qq].ToString();
                    qq++;
                }
            }

**Comment by joepuhich** [comment]
THIS IS AN ATTEMPT TO READ A FILE ONCE LOADED.
It give an empty also.

			var path = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
			var filename = Path.Combine(path, "download.txt");
			string content = File.ReadAllText(filename);

			qq = 0;
			for (leep = 0; leep <= lotsize; leep++)
			{
				for (lep = 0; lep <= 20; lep++)
				{

					//garage_array_database[lep, leep] = content.ToString();
					Tester.garage_array_database[lep, leep] = content.ToString();
					//garage_array_database[lep,leep] = "M";
					qq++;
				}
			}

			leep = 0;
			for (lep = 0; lep <= 20; lep++)
			{
				//garage_array_database[lep, leep] = headery[lep].ToString();
				Tester.garage_array_database[lep, leep] = headery[lep].ToString();
			}
			//garage_array_database[20, 0] = "\n";
			Tester.garage_array_database[20, 0] = "\n";
			//			file.close(path);

**Comment by joepuhich** [comment]
I have been writing C# xamarin android code for 2 yrs.
I can not get my OS to work properly.
So i think.

**Comment by jonathanpeppers** [comment]
> HERE IS THE CODE FROM MY PROJECT. I have been chasing read and write code for 2 years. I can not get it to work. I can not generate a "read or write" with any kind of code !!!
> 
> It compiles. When it runs I get an empty string in "content_upload". I think I am not accessing the OS correctly.
> 
> ```
>    protected override void OnCreate(Bundle bundle)
>      {
>         Xamarin.Essentials.Platform.Init(this, savedInstanceState);
>         Context context = Android.App.Application.Context;
> 
>         base.OnCreate(bundle);
>         TextView tv = new TextView(this);
>         AssetManager assets = this.Assets;
> 
>         string content_upload;
>         using (StreamReader sr = new StreamReader(assets.Open("upload.txt")))
>         {
>             content_upload = sr.ReadToEnd();
>         }
> 
>         qq = 0;
>         for (leep = 0; leep <= 500; leep++)
>         {
>             for (lep = 0; lep <= 20; lep++)
>             {
>                 Tester.garage_array_database[lep, leep] = MainActivity.content_upload[qq].ToString();
>                 qq++;
>             }
>         }
> ```

For this to work, you would need a file in your project at `Assets\upload.txt` with a build action of `AndroidAsset`. Are you able to `.zip` up the whole project and share it? It sounds like it is a sample/personal projecct.

**Comment by joepuhich** [comment]
[](url
[appTOPDOGcleanbestsync.zip](https://github.com/xamarin/xamarin-android/files/9030126/appTOPDOGcleanbestsync.zip)
)

**Comment by joepuhich** [comment]
[zl1800.XXX-Signed.zip](https://github.com/xamarin/xamarin-android/files/9049489/zl1800.XXX-Signed.zip)

I think this is what you are asking for !!

I upgraded to vs 17.2.4
Android 12
API 31
AndroidX

**Comment by jonathanpeppers** [comment]
Opening the `.apk` in Android Studio, the values are in there correctly:

![image](https://user-images.githubusercontent.com/840039/177416512-8b74f40f-0c8e-4333-9384-75380af5915b.png)

Are you able to load this file in a new project? What if you use a different device/emulator?

**Comment by joepuhich** [comment]
![Screenshot (167)](https://user-images.githubusercontent.com/62358901/177416781-acbc6ea6-efc5-4176-83ea-6fdb4918b06e.png)
![Screenshot (166)](https://user-images.githubusercontent.com/62358901/177416803-0d4babd6-b4cd-459b-b43a-d6765d49306e.png)

**Comment by joepuhich** [comment]
I can get the text files also.
I can not compile the project and then read the txt file into my program.

**Comment by joepuhich** [comment]
![Screenshot (168)](https://user-images.githubusercontent.com/62358901/177418023-2a22ce54-daba-44c9-86a6-c7683ad8cb54.png)

**Comment by joepuhich** [comment]
[appTOPDOGcleanbestsync.zip](https://github.com/xamarin/xamarin-android/files/9049949/appTOPDOGcleanbestsync.zip)

**Comment by joepuhich** [comment]
![Screenshot (169)](https://user-images.githubusercontent.com/62358901/177607509-02c102ea-a81f-4f18-9926-5a849d92566c.png)

**Comment by joepuhich** [comment]
[appTOPDOGcleanbestsync.zip](https://github.com/xamarin/xamarin-android/files/9057384/appTOPDOGcleanbestsync.zip)

**Comment by jonathanpeppers** [comment]
All the samples have worked for me so far. What am I doing wrong?

![image](https://user-images.githubusercontent.com/840039/177625660-cb13b419-3346-4b8b-8d2e-b97c3292ae7a.png)

What is the actual problem here? You get an exception? or can't load the text?

The app launches for me, but I'm not sure what I should be looking for:

![image](https://user-images.githubusercontent.com/840039/177625783-86672637-3751-4b09-8333-09966ed4afc9.png)

You also shouldn't use `<Content/>` on Android, as it isn't supported. Is this related to your issue?
```xml
  <ItemGroup>
    <Content Include="upload.txt" />
  </ItemGroup>
```

**Comment by joepuhich** [comment]
[appTOPDOGcleanbestsync.zip](https://github.com/xamarin/xamarin-android/files/9057601/appTOPDOGcleanbestsync.zip)

**Comment by joepuhich** [comment]
![image](https://user-images.githubusercontent.com/62358901/177876176-3f074ae4-7e87-41ac-8a04-73dde8edbce5.png)

**Comment by jonathanpeppers** [comment]
Ok, so this seems like you needed general C# programming help. We generally only discuss issues specific to Xamarin.Android or the .NET 6+ Android workload. For example, solving an issue would normally result in changing a file in this repo.

If you have other issues like this, I'd recommend posting on a general Q&A site like https://stackoverflow.com. Thanks!
