### ISSUE TITLE
HttpClientHandler not picking up PAC proxy on Android

### ISSUE THREAD

**Issue by Safeer-Ahmad** [xamarin/xamarin-android#6795]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Xamarin.Android 11.2.2.1

### Description

I've specified proxy on android using PAC file and have set HTTP client implementation to AndroidClientHandler and my expectation is when I send an HTTP request using HttpClient in my Forms project, it should be able to pick up the proxy settings and send the request accordingly. However, its not working and trying to hit the url directly than going through proxy.

I've looked at below issue and seems like there has been a fix released to use proxy if present. 

https://github.com/xamarin/xamarin-android/issues/3058[](url)

### Steps to Reproduce

- set proxy using PAC file in android
- set HTTP client implementation to AndroidClientHandler in android project
- send http request in forms project and see proxy is not being used

**Comment by Safeer-Ahmad** [comment]
Any update on this, please?

**Comment by Safeer-Ahmad** [comment]
`
var handler = new HttpClientHandler();
            handler.Proxy = WebRequest.GetSystemWebProxy();
            handler.UseProxy = true;
            httpClient = new HttpClient(handler)
            {
                BaseAddress = new Uri("https://api.agify.io/")
            };`

**Comment by Safeer-Ahmad** [comment]
This is getting frustrating now, it's been over a week, and still no response. Please update me on this issue ASAP as this is a blocker for us atm. Thanks

**Comment by steveisok** [comment]
@Safeer-Ahmad What device(s) are you using and what api level are you targeting?

**Comment by Safeer-Ahmad** [comment]
We are targeting Android 9 (pie) and running it on Samsung mobile and Zebra TC 51

**Comment by Safeer-Ahmad** [comment]
`
HttpClientHandler handler = new HttpClientHandler
                    {
                        UseProxy = true,
                        Proxy = WebRequest.DefaultWebProxy
                    };

                    var client = new HttpClient(handler);
`

This worked for me, thanks all.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
