### ISSUE TITLE
Target runtime doesn't support covariant types in overrides. Type must be 'Filter' to match overridden member ...

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-android#6796]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2022 and VS2019

### Description

I'm trying to bind this lib:
https://github.com/ajithvgiri/search-dialog

But I'm getting this error:

> /Users/fanmixco/Documents/GitHub/xamarin-search-dialog-2/Search-Dialog/obj/Debug/generated/src/Com.Ajithvgiri.Searchdialog.SearchListAdapter.cs(93,93): Error CS8831: 'SearchListAdapter.Filter': Target runtime doesn't support covariant types in overrides. Type must be 'Filter' to match overridden member 'ArrayAdapter.Filter' (CS8831) (Search-Dialog)

From my understanding this is supported in C# 9+:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/covariant-returns

I targeted the latest version.

### Steps to Reproduce

1. Uncompress the attached project.
2. Open the project.
3. Try compiling the lib:
[xamarin-search-dialog-2.zip](https://github.com/xamarin/xamarin-android/files/8142729/xamarin-search-dialog-2.zip)

### Relevant log output

```shell
> /Users/fanmixco/Documents/GitHub/xamarin-search-dialog-2/Search-Dialog/obj/Debug/generated/src/Com.Ajithvgiri.Searchdialog.SearchListAdapter.cs(93,93): Error CS8831: 'SearchListAdapter.Filter': Target runtime doesn't support covariant types in overrides. Type must be 'Filter' to match overridden member 'ArrayAdapter.Filter' (CS8831) (Search-Dialog)
```

**Comment by jpobst** [comment]
Try being explicit with the C# version you want to use:
```
<LangVersion>9.0</LangVersion>
```

I think `latest` refers to the latest ***supported*** version, which probably isn't 9.0 for Xamarin.

https://stackoverflow.com/questions/64786495/is-it-possible-to-use-c-sharp-9-for-xamarin

**Comment by FANMixco** [comment]
Hi @jpobst, I got exactly the same error.

**Comment by jpobst** [comment]
Ah, true.  I guess the normal error message for that is something like:
```
Feature 'blah' is not available in C# 7.3. You must target C# 9 to use this feature.
```

This is different:
```
Target runtime doesn't support covariant types in overrides.
```

This means the C# feature requires runtime support, and it must not be available in the Mono runtime used by "classic" Xamarin.

This is probably only available in `net6.0-android`.

**Comment by FANMixco** [comment]
Hi @jpobst, and how can I upgrade it? Is there any way to retarget the projects?

**Comment by jpobst** [comment]
I don't think there's much documentation for upgrading to .NET 6 Xamarin yet, since it's still in preview.  The easiest way would be to recreate your projects with one of the new templates.

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNet.md

Alternatively, you can fix the binding issue so that it will still be usable on the current Xamarin:

https://github.com/xamarin/java.interop/wiki/Covariant-Return-Types-(Class)
