### ISSUE TITLE
Changing ActionBarSize, leaves an emptyspace in layout below

### ISSUE THREAD

**Issue by dbSoft-SoftwareSolutions** [xamarin/xamarin-android#6802]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Visual Studio 2019 version 16.11.10

### Steps to Reproduce

1. Create a File > New Android App
2. Update packages to latest version
Xamarin.AndroidX.AppCompat version 1.3.1.3:
Xamarin.Essentials 1.7.1:
Xamarin.Google.Android.Materials version 1.4.0.4:
4. Add the following code in styles
 ```
 <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
    <item name="android:textAllCaps">false</item>
    <item name="android:windowFullscreen">true</item>
    <item name="actionBarSize">26.0dip</item>
 </style>
```
5.Run the app and observe the bug
![155687773-59643f37-3bb3-4238-9576-8ad471810023](https://user-images.githubusercontent.com/61802513/156244860-95e1b689-fed6-4102-adf4-b69d4f53e0ab.jpg)

### Did you find any workaround?

Problem not exists if i will use package Xamarin.Google.Android.Materials version 1.0.0.1:

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly.  (Or in this case, Google's Material library.)

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.

**Comment by grendello** [comment]
@moljac unless it's something in the component packaging, I don't think we can do anything here?
