### ISSUE TITLE
Latest Visual Studio 2022 update version 17.1 and Compiling Xamarin forms on Android 12.0 API 31 fails

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6808]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Latest-Visual-Studio-2022-update-version/1672337)._

---
[regression] [worked-in:the stable version prior to 17.1]
updated visual studio to the latest version 17.1 and complied a xamarin forms app targeting Android 12.0 API 31 fails with the following message.

Please note the compile is successful but deployment fails. I tried both an emulator and a physical phone. the emulator is Pixel 2 R11 - API 30

[mkbundle stderr] 
[cc stderr] 'C:\Program' is not recognized as an internal or external command,
[cc stderr] operable program or batch file.
[cc stderr] 
XA5103: NDK C compiler exited with an error. Exit code 0
Done building project "[].Android.csproj" -- FAILED.
Build FAILED.

Xamarin version 17.1.0.309
Xamarin.Android SDK 12.2.0.4

I have also reinstalled the visual studio 2022, with no success and getting the same result.

 I have tested the same solution is still compiled and deployed successfully using Visual Studio 2019 latest version.

---
#### Feedback Bot on 2/21/2022, 09:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### JASON Zhao [MSFT] on 2/23/2022, 01:11 AM: 

<p>Thanks for your feedback.<br>
Could you provide device log for us to investigate it further?<br>
1.Launch the Device Log tool, View &gt; Other Windows &gt; Device Log<br>
2.When the Debug Log tool window is displayed, choose the Android device to monitor<br>
3.Start Device Log tool<br>
4.Reproduce your issue and attach the debug logs</p>

#### Sasan Pasha on 2/24/2022, 02:44 PM: 

<p>I don’t think the log is helpful at all  - but I attached it here.<br>
<a target='_blank' href="https://aka.ms/dc/file?name=B9a43246e350840d8b7ef919bce5b4f02637813394434194281_devicelog.txt&amp;tid=9a43246e350840d8b7ef919bce5b4f02637813394434194281">devicelog.txt</a></p>
<p>XA5103: NDK C compiler exited with an error. Exit code 0<br>
Done building project “[].Android.csproj” – FAILED.<br>
Build FAILED</p>

#### Sasan Pasha on 2/24/2022, 03:20 PM: 

(private comment, text removed)
#### JASON Zhao [MSFT] on 2/24/2022, 06:05 PM: 

<p>Please click Tools=&gt;Options=&gt;Check if the path of Android SDK Location is correct, if possible, you can also change it to the default setting, check if the Visual Studio has the same error.<br>
<img src="https://aka.ms/dc/image?name=B7d3687fe83ac420ea6fdfb0983f28094637813515629138530_20220225-100601-image.png&amp;tid=7d3687fe83ac420ea6fdfb0983f28094637813515629138530" alt="image.png"></p>

#### Sasan Pasha on 2/24/2022, 06:10 PM: 

<p>the path is correct - as i mentioned, compiling builds the solution successfully. deployment fails.</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=Bfddb5f7d59414826960b808212ca2b68637813517877596430_JDK.jpg&amp;tid=fddb5f7d59414826960b808212ca2b68637813517877596430">JDK.jpg</a></p>

#### JASON Zhao [MSFT] on 2/24/2022, 06:37 PM: 

<p>Can you please try the following troubleshooting steps:</p>
<ol>
<li>Launch the emulator from the Android Device Manager (select your virtual device and click Start).</li>
<li>Open a command prompt and go to the folder where adb is installed. If the Android SDK is installed at its default location, adbis located at C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe; if not, modify this path for the location of the Android SDK on your computer.</li>
<li>Type the following command: adb devices</li>
<li>If the emulator is accessible from the Android SDK, the emulator should appear in the list of attached devices. For example:<br>
List of devices attached emulator-5554 device 5. If the emulator does not appear in this list, start the Android SDK Manager, apply all updates, then try launching the emulator again.</li>
</ol>
<p>Does the emulator works in Release mode?If so, can you create a new configuration, you are able to go to the Solutions Configurations dropdown in Visual Studio and select the Configuration Manager. The dropdown is probably currently set to Debug. Create a new configuration from the working Release config if possible.</p>

#### Sasan Pasha on 2/24/2022, 07:16 PM: 

<p>with the new update to VS version 17.1  - I launched the android device manager - the following image is shown to install command line tools  - I click install and it installs something. but in reality, nothing happens.  when I click the device manager, it wants to install the command line tools again.<br>
<a target='_blank' href="https://aka.ms/dc/file?name=B02d1d8a30c9a4b0a85efd4207fcadfea637813545506548972_commandLineTools.jpg&amp;tid=02d1d8a30c9a4b0a85efd4207fcadfea637813545506548972">commandLineTools.jpg</a></p>
<p>keep in mind I already have 2 instances of emulator that are functional on VS 2019. prior to the update to VS 2022 version 17.1, I didn’t have this issue as well.<br>
I did open the adb command and get the list of devices and it shows the correct emulator. image attached<br>
<a target='_blank' href="https://aka.ms/dc/file?name=Baf96039c29c1411c9c3dc98f17334d8d637813548100622995_adb.jpg&amp;tid=af96039c29c1411c9c3dc98f17334d8d637813548100622995">adb.jpg</a></p>
<p>launching the SDK manager has everything updated - image attached<br>
<a target='_blank' href="https://aka.ms/dc/file?name=Bbe1c5e81667b489a8860dc421850be88637813549664722904_sdk-2.jpg&amp;tid=be1c5e81667b489a8860dc421850be88637813549664722904">sdk-2.jpg</a><br>
<a target='_blank' href="https://aka.ms/dc/file?name=Bce40109cc6af46ef8c5a10bd83e885c1637813549809916406_sdk-1.jpg&amp;tid=ce40109cc6af46ef8c5a10bd83e885c1637813549809916406">sdk-1.jpg</a></p>
<p>changing to debug both emulator and physical device - compiles but fails to deploy<br>
changing to release both emulator and physical device - compiles  but fails to deploy</p>
<p>Task Parameter:TempOutputPath=obj\Release\120<br>
Task Parameter:AndroidNdkDirectory=C:\Program Files (x86)\Android\android-sdk<br>
dk\22.1.7171670<br>
Task Parameter:ToolPath=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android<br>
CC=“C:\Program Files (x86)\Android\android-sdk<br>
dk\22.1.7171670\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi16-clang.CMD”<br>
AS=“C:\Program Files (x86)\Android\android-sdk<br>
dk\22.1.7171670\toolchains\llvm\prebuilt\windows-x86_64\bin\arm-linux-androideabi-as.EXE”<br>
[mkbundle] C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\mkbundle.exe --dos2unix=false --nomain --i18n none --bundled-header --mono-api-struct-path “C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\mkbundle-api.h” --style linux -c -o obj\Release\120\bundles\armeabi-v7a\temp.c -oo obj\Release\120\bundles\armeabi-v7a\assemblies.o -z obj\Release\120\android\assets\shrunk\System.Drawing.Common.dll obj\Release\120\android\assets\shrunk\System.ComponentModel.DataAnnotations.dll obj\Release\120\android\assets\shrunk\System.Runtime.Serialization.dll obj\Release\120\android\assets\shrunk\System.Json.dll obj\Release\120\android\assets\shrunk\System.Data.dll obj\Release\120\android\assets\shrunk\System.Threading.Tasks.Extensions.dll obj\Release\120\android\assets\shrunk\Java.Interop.dll obj\Release\120\android\assets\shrunk\Mono.Android.dll obj\Release\120\android\assets\shrunk\mscorlib.dll obj\Release\120\android\assets\shrunk\System.Buffers.dll obj\Release\120\android\assets\shrunk\System.Core.dll obj\Release\120\android\assets\shrunk\System.dll obj\Release\120\android\assets\shrunk\System.Net.Http.dll obj\Release\120\android\assets\shrunk\System.Numerics.dll obj\Release\120\android\assets\shrunk\System.Runtime.CompilerServices.Unsafe.dll obj\Release\120\android\assets\shrunk\System.Xml.dll obj\Release\120\android\assets\shrunk\System.Xml.Linq.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.AppCompat.AppCompatResources.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.AppCompat.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.CardView.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.CoordinatorLayout.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Core.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.CustomView.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.DrawerLayout.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Fragment.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Legacy.Support.Core.UI.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Lifecycle.Common.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Lifecycle.LiveData.Core.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Lifecycle.ViewModel.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Loader.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Media.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.RecyclerView.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.SwipeRefreshLayout.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.VersionedParcelable.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.ViewPager.dll obj\Release\120\android\assets\shrunk\Xamarin.Google.Android.Material.dll obj\Release\120\android\assets\shrunk\System.ServiceModel.Internals.dll obj\Release\120\android\assets\shrunk\System.Text.Encoding.CodePages.dll obj\Release\120\android\assets\shrunk\Microsoft.CSharp.dll obj\Release\120\android\assets\shrunk\Mono.Security.dll obj\Release\120\android\assets\shrunk\SpotLee.Droid.dll obj\Release\120\android\assets\shrunk\AppCenter.Analytics.Metrics.dll obj\Release\120\android\assets\shrunk\BarcodeScanner.XF.dll obj\Release\120\android\assets\shrunk\ColorMinePortable.dll obj\Release\120\android\assets\shrunk\ColorPicker.Android.dll obj\Release\120\android\assets\shrunk\ColorPicker.dll obj\Release\120\android\assets\shrunk\DnsClient.dll obj\Release\120\android\assets\shrunk\Essential.Interfaces.dll obj\Release\120\android\assets\shrunk\ExoPlayer.Core.dll obj\Release\120\android\assets\shrunk\ExoPlayer.Dash.dll obj\Release\120\android\assets\shrunk\ExoPlayer.dll obj\Release\120\android\assets\shrunk\ExoPlayer.Ext.MediaSession.dll obj\Release\120\android\assets\shrunk\ExoPlayer.Hls.dll obj\Release\120\android\assets\shrunk\ExoPlayer.SmoothStreaming.dll obj\Release\120\android\assets\shrunk\ExoPlayer.UI.dll obj\Release\120\android\assets\shrunk\FFImageLoading.dll obj\Release\120\android\assets\shrunk\FFImageLoading.Forms.dll obj\Release\120\android\assets\shrunk\FFImageLoading.Forms.Platform.dll obj\Release\120\android\assets\shrunk\FFImageLoading.Platform.dll obj\Release\120\android\assets\shrunk\FFImageLoading.Svg.Forms.dll obj\Release\120\android\assets\shrunk\FFImageLoading.Svg.Platform.dll obj\Release\120\android\assets\shrunk\FFImageLoading.Transformations.dll obj\Release\120\android\assets\shrunk\FormsViewGroup.dll obj\Release\120\android\assets\shrunk\Infrastructure.dll obj\Release\120\android\assets\shrunk\MediaManager.dll obj\Release\120\android\assets\shrunk\MediaManager.Forms.dll obj\Release\120\android\assets\shrunk\Microsoft.AppCenter.Analytics.Android.Bindings.dll obj\Release\120\android\assets\shrunk\Microsoft.AppCenter.Analytics.dll obj\Release\120\android\assets\shrunk\Microsoft.AppCenter.Android.Bindings.dll obj\Release\120\android\assets\shrunk\Microsoft.AppCenter.Crashes.Android.Bindings.dll obj\Release\120\android\assets\shrunk\Microsoft.AppCenter.Crashes.dll obj\Release\120\android\assets\shrunk\Microsoft.AppCenter.Distribute.Android.Bindings.dll obj\Release\120\android\assets\shrunk\Microsoft.AppCenter.Distribute.dll obj\Release\120\android\assets\shrunk\Microsoft.AppCenter.dll obj\Release\120\android\assets\shrunk\Microsoft.CognitiveServices.Speech.csharp.dll obj\Release\120\android\assets\shrunk\Microsoft.IdentityModel.JsonWebTokens.dll obj\Release\120\android\assets\shrunk\Microsoft.IdentityModel.Logging.dll obj\Release\120\android\assets\shrunk\Microsoft.IdentityModel.Tokens.dll obj\Release\120\android\assets\shrunk\MongoDB.Bson.dll obj\Release\120\android\assets\shrunk\MongoDB.Driver.Core.dll obj\Release\120\android\assets\shrunk\MongoDB.Driver.dll obj\Release\120\android\assets\shrunk\MongoDB.Libmongocrypt.dll obj\Release\120\android\assets\shrunk\Newtonsoft.Json.dll obj\Release\120\android\assets\shrunk\PhoneNumbers.dll obj\Release\120\android\assets\shrunk\Plugin.AudioRecorder.dll obj\Release\120\android\assets\shrunk\Plugin.Beacon.Android.dll obj\Release\120\android\assets\shrunk\Plugin.Beacon.Core.dll obj\Release\120\android\assets\shrunk\Plugin.Permissions.dll obj\Release\120\android\assets\shrunk\Prism.dll obj\Release\120\android\assets\shrunk\Prism.Forms.dll obj\Release\120\android\assets\shrunk\Prism.Plugin.Popups.dll obj\Release\120\android\assets\shrunk\Prism.Unity.Forms.dll obj\Release\120\android\assets\shrunk\Rg.Plugins.Popup.dll obj\Release\120\android\assets\shrunk\SharpCompress.dll obj\Release\120\android\assets\shrunk\SkiaSharp.dll obj\Release\120\android\assets\shrunk\SkiaSharp.Views.Android.dll obj\Release\120\android\assets\shrunk\SkiaSharp.Views.Forms.dll obj\Release\120\android\assets\shrunk\SpotLee.dll obj\Release\120\android\assets\shrunk\Syncfusion.Buttons.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.Buttons.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.Core.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.Core.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.DataSource.Portable.dll obj\Release\120\android\assets\shrunk\Syncfusion.Expander.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.Expander.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.GridCommon.Portable.dll obj\Release\120\android\assets\shrunk\Syncfusion.Licensing.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfAutoComplete.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfAutoComplete.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfBadgeView.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfBadgeView.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfBusyIndicator.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfBusyIndicator.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfBusyIndicator.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfCalendar.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfCalendar.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfCarousel.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfCarousel.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfComboBox.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfComboBox.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfDataForm.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfDataForm.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfImageEditor.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfImageEditor.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfListView.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfListView.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfMaskedEdit.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfMaskedEdit.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfNumericTextBox.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfNumericTextBox.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfNumericTextBox.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfNumericUpDown.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfNumericUpDown.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfPicker.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfPicker.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfPicker.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfPopupLayout.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfPopupLayout.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfProgressBar.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfProgressBar.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfRadialMenu.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfRadialMenu.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfRadialMenu.XForms.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfTabView.XForms.Android.dll obj\Release\120\android\assets\shrunk\Syncfusion.SfTabView.XForms.dll obj\Release\120\android\assets\shrunk\System.Collections.Immutable.dll obj\Release\120\android\assets\shrunk\System.IdentityModel.Tokens.Jwt.dll obj\Release\120\android\assets\shrunk\Twilio.dll obj\Release\120\android\assets\shrunk\Unity.Abstractions.dll obj\Release\120\android\assets\shrunk\Unity.Container.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.Activity.dll obj\Release\120\android\assets\shrunk\Xamarin.AndroidX.SavedState.dll obj\Release\120\android\assets\shrunk\Xamarin.Cognitive.Speech.dll obj\Release\120\android\assets\shrunk\Xamarin.CommunityToolkit.dll obj\Release\120\android\assets\shrunk\Xamarin.Essentials.dll obj\Release\120\android\assets\shrunk\Xamarin.Forms.BetterMaps.dll obj\Release\120\android\assets\shrunk\Xamarin.Forms.Core.dll obj\Release\120\android\assets\shrunk\Xamarin.Forms.Material.dll obj\Release\120\android\assets\shrunk\Xamarin.Forms.PancakeView.dll obj\Release\120\android\assets\shrunk\Xamarin.Forms.Platform.Android.dll obj\Release\120\android\assets\shrunk\Xamarin.Forms.Platform.dll obj\Release\120\android\assets\shrunk\Xamarin.Forms.Xaml.dll obj\Release\120\android\assets\shrunk\Xamarin.Google.Guava.ListenableFuture.dll obj\Release\120\android\assets\shrunk\Xamarin.GooglePlayServices.Base.dll obj\Release\120\android\assets\shrunk\Xamarin.GooglePlayServices.Basement.dll obj\Release\120\android\assets\shrunk\Xamarin.GooglePlayServices.Maps.dll obj\Release\120\android\assets\shrunk\Xamarin.GooglePlayServices.Tasks.dll obj\Release\120\android\assets\shrunk\Xamarin.GooglePlayServices.Vision.Common.dll obj\Release\120\android\assets\shrunk\Xamarin.GooglePlayServices.Vision.dll obj\Release\120\android\assets\shrunk\Xamarin.Jetbrains.Annotations.dll obj\Release\120\android\assets\shrunk\Xamarin.Kotlin.StdLib.Common.dll obj\Release\120\android\assets\shrunk\Xamarin.Kotlin.StdLib.dll<br>
[mkbundle stdout] Generated obj\Release\120\bundles\armeabi-v7a\temp.c<br>
[mkbundle stderr]<br>
[mkbundle stdout]<br>
[CC] “C:\Program Files (x86)\Android\android-sdk<br>
dk\22.1.7171670\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi16-clang.CMD” -c -D__ANDROID_API__=16 -DANDROID -o obj\Release\120\bundles\armeabi-v7a\temp.o -I “C:\Program Files (x86)\Android\android-sdk<br>
dk\22.1.7171670\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi” -I “C:\Program Files (x86)\Android\android-sdk<br>
dk\22.1.7171670\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include” obj\Release\120\bundles\armeabi-v7a\temp.c<br>
[cc stderr] ‘C:\Program’ is not recognized as an internal or external command,<br>
[cc stderr] operable program or batch file.<br>
[cc stdout]<br>
[cc stderr]<br>
XA5103: NDK C compiler exited with an error. Exit code 0<br>
Done executing task “MakeBundleNativeCodeExternal” – FAILED.<br>
Done building target &quot;<em>AndroidAot&quot; in project “[].Android.csproj” – FAILED.<br>
Done building project “[].Android.csproj” – FAILED.<br>
Build FAILED.<br>
1&gt;Deployment failed to pixel_2_r_11_0</em>-_api_30.</p>
<p>this issue is only happening on VS 2022 version 17.1 on android only - iOS is fine.<br>
you ay want to consider consulting with xamarin.android group as well as I also saw similar issues are being reported there, but I guess it’s to do with the latest release of VS.<br>
I also don’t have much time to run more tests for you - perhaps, there should be other ways to get to the root cause here.</p>

#### JASON Zhao [MSFT] on 2/25/2022, 01:39 AM: 

<p>This issue of “‘C:\Program’ is not recognized” related to Android NDK setup seems to be dependent on windows command system calls not liking either a space or bracket in the file path names.<br>
You can try changing the directory in which sdk is located to C:\Android which involved just cut and paste and changing the sdk location setting in the Android studio sdk manager dialog.</p>

#### Sasan Pasha on 2/25/2022, 01:05 PM: 

<p>I can confirm moving the android to <strong>C:\Android\android-sdk</strong> - I was able to deploy it to the emulator successfully. However, changing the path back to the original <strong>C:\Program Files (x86)\Android\android-sdk</strong> - will still fail. Please keep in mind, this wasn’t an issue prior to the update to 17.1, so something must not like the default path.</p>
<p>On top of this issue -  I no longer can create any new emulator through the android device manager, by launching it through tools -&gt; Android -&gt; Android Device Manager , as the program shows an infinite loop of installing the command line tools. this happens regardless of the android-sdk path.<br>
<a target='_blank' href="https://aka.ms/dc/file?name=B6a0b2a44250c4238b145429876781e6b637814197877526538_ADM.jpg&amp;tid=6a0b2a44250c4238b145429876781e6b637814197877526538">ADM.jpg</a></p>

#### Sasan Pasha on 2/28/2022, 10:13 AM: 

<p>hi <a target='_blank' href="https://developercommunity2.visualstudio.com/user/2e43e195-b62c-6bda-97d8-059df7c7395e/profile">JASON Zhao [MSFT]</a><br>
When I moved the android folder to C: drive it starts working. but changing it back to the original location is not working.</p>
<p>does this help you understand why the 17.1 update makes the default location not work properly? also, not sure why thy label of this ticket still says need more info?</p>

#### JASON Zhao [MSFT] on 2/28/2022, 06:56 PM: 

<p>This feedback is being re-triaged as we are moving it to another team that can better help with the issue. Thanks for your patience.</p>

#### Sasan Pasha on 3/1/2022, 10:56 AM: 

<p><a target='_blank' href="https://developercommunity2.visualstudio.com/user/2e43e195-b62c-6bda-97d8-059df7c7395e/profile">JASON Zhao [MSFT]</a><br>
i also want to make sure the following issue is also dealt with: I no longer can create any new emulator through the android device manager, by launching it through tools -&gt; Android -&gt; Android Device Manager, as the program shows an infinite loop of installing the command line tools. this happens regardless of the android-SDK path. The image is attached in the previous comments.</p>

---
### Original Solutions
(no solutions)

**Comment by pasha-o** [comment]
i am the original creator of the issue  - please reach out if you need more info.

**Comment by jonathanpeppers** [comment]
I think this is fixed in main via: https://github.com/xamarin/xamarin-android/commit/5d2bc5eded8442da5baf35ee67bf4f719b8d466f

A workaround is to not use LLVM and Profiled AOT at the same time, so setting `EnableLLVM=false`.

Josué Tille let us know  if you still have a problem when using the workaround, thanks!

**Comment by Enbi-Zhang** [comment]
@jonathanpeppers  on this https://developercommunity.visualstudio.com/t/Unable-to-deploy-or-archive-release-vers/1694213, the customer work on VS17.1.1. still encouter this issue. 
Also I provided the workaround you metioned above to them, but still cannot solve his issue, could you take a look?

**Comment by save2love** [comment]
I am having the same issue today.
Microsoft Visual Studio Enterprise 2022 (64-bit) - 17.1.3
Xamarin - 17.1.0.324
Disable  `Bundle assemblies into native code` was helped me.

**Comment by danielkraut** [comment]
> I think this is fixed in main via: [5d2bc5e](https://github.com/xamarin/xamarin-android/commit/5d2bc5eded8442da5baf35ee67bf4f719b8d466f)
> 
> A workaround is to not use LLVM and Profiled AOT at the same time, so setting `EnableLLVM=false`.
> 
> @pasha-o let us know if you still have a problem when using the workaround, thanks!

I don't think the workaround works, I encountered the issue today with Visual Studio 17.1.4, when I tried to set `<BundleAssemblies>true</BundleAssemblies>` and the build/deployment still failed even with all AOT options switched off.

**Comment by jonathanpeppers** [comment]
@danielkraut can you file a new issue with a diagnostic MSBuild log? The `$(BundleAssemblies)` setting seems like a different issue.

I'd also ask why you're using `$(BundleAssemblies)`, as we deprecated this feature in Xamarin.Android -- removed in .NET 6. We would recommend using assembly compression instead, which is on by default for Release builds.

**Comment by danielkraut** [comment]
@save2love The issue started when I set `$(BundleAssemblies)` to true, it was not happening before. The project was building and deploying just fine until I tried the `$(BundleAssemblies)` option. 

@jonathanpeppers Because I had no idea that `$(BundleAssemblies)` is deprecated. I was tweaking build flags for a first official release of an application, trying AOT and stuff and found on StackOverflow that BundleAssemblies can reduce APK size. Also I was reading [this documentation](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/?tabs=windows#bundle-assemblies-into-native-code) and it does not say that it is deprecated, so maybe the documentation should be updated. Also I found issue #6697 now which seems like a better target for my issue. Do you want the MSBuild log with diagnostics?

**Comment by jonathanpeppers** [comment]
Here is the details about it:

https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.0#smaller-app-package-sizes
