### ISSUE TITLE
Support C#9 top-level statements?

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#6825]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 6

### Description

C# 9 added support for [top-level statements](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements), which are used in the default `dotnet new console` template:

```csharp
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```

Can these be supported at all in .NET SDK for Android?

*An* idea to support them is to probe all assemblies for "entrypoints" (`.entrypoint` IL statement), and if any are found, add an `Application` subclass which invokes all of the entrypoints in an unspecified order.

One would think that C#10 source generators could be used for this, but unfortunately the entrypoint generated via top-level statements is "name-mangled", e.g.

```il
  .custom instance void [System.Runtime]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 ) 
  .method private hidebysig static void  '<Main>$'(string[] args) cil managed
  {
    .entrypoint
    // Code size       12 (0xc)
    .maxstack  8
    IL_0000:  ldstr      "Hello, World!"
    IL_0005:  call       void [System.Console]System.Console::WriteLine(string)
    IL_000a:  nop
    IL_000b:  ret
  } // end of method Program::'<Main>$'
```

### Steps to Reproduce

-

**Comment by jpobst** [comment]
There doesn't seem to be any interest in supporting this. The .NET has also backed off of this a bit and now allows you to turn them off when creating a new project:

![image](https://github.com/xamarin/xamarin-android/assets/179295/065624df-73b7-4a29-84dc-577894e2fddb)
