### ISSUE TITLE
compile error when convert aar to dll

### ISSUE THREAD

**Issue by zhuweihua163** [xamarin/xamarin-android#6834]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2019 win10 64bit

### Description

I want to convert an aar library to dll file。There are some errors during build solution：

![图片](https://user-images.githubusercontent.com/7005876/158566072-ff305a18-4c71-4182-9aa3-cec4de356f0f.png)

I try to edit Metadata.xml file, but it doesn't work. Please tell me how to solve it.
Thanks lot!

### Steps to Reproduce

related code is：

1. com/rscja/deviceapi/interfaces/ConnectionStatusCallback.java

```java
package com.rscja.deviceapi.interfaces;


public interface ConnectionStatusCallback<T> {
    /**
     * @param status 状态(status)
     * @param device 目标设备(device)
     */
    public void getStatus(final ConnectionStatus status, final T device);
    
}
```

2. com/rscja/deviceapi/interfaces/IUHF.java
```java
package com.rscja.deviceapi.interfaces;
public interface IUHF {
    ......
    public void setConnectionStatusCallback(ConnectionStatusCallback<Object> btStatusCallback);
}
```

3. com/rscja/deviceapi/UhfBase.java
```java
package com.rscja.deviceapi;

import com.rscja.deviceapi.interfaces.IUHF;

public abstract class UhfBase implements IUHF {
    ......
}
```

4. com/rscja/deviceapi/RFIDWithUHFUART.java
```java
package com.rscja.deviceapi;

public class RFIDWithUHFUART extends UhfBase implements IUHF{
    ......
    @Override
	public void setConnectionStatusCallback(ConnectionStatusCallback<Object> btStatusCallback) {
		this.btStatusCallback=btStatusCallback;
	}
}
```

5. other class files like above code.

**Comment by jpobst** [comment]
You will need to compare the generated C# code to see what the interfaces look like, and what the implementations look like.

The method signatures for the interface and implementation of `SetConnectionStatusCallback` are not matching, and you will need to use metadata to make them match.
