### ISSUE TITLE
AGP4.1.0 with minification enabled prevents Monodroid from finding assemblies

### ISSUE THREAD

**Issue by stefanoberdoerfer** [xamarin/xamarin-android#6838]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2019 for Mac 8.10.20, Xamarin.Android 12.0.03

### Description

I have rather complex build setup for an android app which basically consists of a native kotlin/java android app fused together with a Xamarin/Mono build in order to include an important C# library directly into the native app.

Everything is working fine except if I enable minification in my `app/build.gradle` via `minifyEnabled true` the app instantly crashes on startup because Monodroid can't find native assemblies that are definitely contained in the apk.
Only if I downgrade the Android Gradle Plugin to version 4.0.1 the crash disappears again.

More info:
 - The proguard.config for the minification consists of:
```
-dontshrink
-dontoptimize
-dontobfuscate
```
 - FastDeployment and code shrinking are both deactivated in Xamarin.Android Project
 - I tried to disable all features mentioned in the release notes of AGP 4.1.0 but had no success

Repro Project: https://github.com/stefanoberdoerfer/KotlinAppWithXamarinDependency/tree/agp_issue 
Forked from: https://github.com/royd/KotlinAppWithXamarinDependency

For me it looks like this function in MonoAndroid somehow can't read the assemblies included in the apk when it was build with AGP 4.1.0 and higher:
https://github.com/xamarin/xamarin-android/blob/169838082a55f8a280d4179ca3a12f852ef6002c/src/monodroid/jni/monodroid-glue.cc#L896

### Steps to Reproduce

1. Clone Repro Project (https://github.com/stefanoberdoerfer/KotlinAppWithXamarinDependency/tree/agp_issue) and checkout `agp_issue` branch
2. Clone companion project (https://github.com/royd/XamarinDependency) so that the root directories of both projects are side by side in the same parent directory
3. Build release apk of "KotlinAppWithXamarinDependency" via commandline `./gradlew assembleRelease` or by opening the project in Android Studio building `release` variant
4. Run the app on a real device or emulator and it crashes on startup

### Did you find any workaround?

Downgrading to AGP 4.0.1 fixes the crash

### Relevant log output

```shell
A/monodroid: No assemblies found in '(null)' or '<unavailable>'. Assuming this is part of Fast Deployment. Exiting...
```

**Comment by jonathanpeppers** [comment]
This message means there are no .NET assemblies in the app:
```
No assemblies found in '/data/user/0/com.roydammarell.kotlinappwithxamarindependency/files/.__override__' or '<unavailable>'. Assuming this is part of Fast Deployment. Exiting...
```

So this means you somehow are building with a Fast Deployment configuration? And those assemblies weren't fast deployed?

Can you check `EmbedAssembliesIntoApk=true`? That disables Fast Deployment.

I would also try to get a `.binlog` of the build + deploy with:

```
msbuild YourAndroidApp.csproj -t:Clean,Install -bl
```
Share the `msbuild.binlog` file with us, and we can take a closer look, thanks!

**Comment by stefanoberdoerfer** [comment]
Thanks for your reply!

I checked that Fast Deployment is disabled in `XamarinDependency.Application.csproj` and got the attached `.binlog` and `.apk` from executing my release build:
```
msbuild XamarinDependency.Application.csproj -t:Clean,Install /property:Configuration=Release
```
[binlog_and_xamarinApk.zip](https://github.com/xamarin/xamarin-android/files/8560882/binlog_and_xamarinApk.zip)

I assume that this build works as intended, because in my setup I am merging the (unpacked) contents of this apk into a native Android project managed in Android Studio ([KotlinAppWithXamarinDependency - build.gradle](https://github.com/stefanoberdoerfer/KotlinAppWithXamarinDependency/blob/master/xamarin/build.gradle)) and everything is working fine until I enable minification in the enclosing project.

For the sake of completeness I also attached the final apk output of this second apk build (with and without `minifyEnabled` + minimal proguard config as described in initial posting).
Both seem to contain all the needed .NET and native assemblies but only the one with minification produces the error.

[merged-kotlin-apks.zip](https://github.com/xamarin/xamarin-android/files/8561165/merged-kotlin-apks.zip)

**Comment by dellis1972** [comment]
We have a tool called `apkdiff` (its on nuget). The same assemblies are in place. But there are some changes to the classes.dex. So I guess its possible one of the Java types we need to load the assemblies has been stripped out.

```
Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
  +           3 assemblies/XamarinDependency.Application.dll
  -           1 assemblies/System.Net.Http.dll
  -           1 assemblies/System.Numerics.dll
  -     120,036 classes.dex
    -         983 strings count
    -           2 types count
    +         273 fields count
    +       2,261 methods count
    -     136,368 data section size
Summary:
  +           0 Other entries 0.00% (of 1,095,098)
  +           1 Assemblies 0.00% (of 1,679,422)
  -     120,036 Dalvik executables -2.27% (of 5,293,068)
  +           0 Shared libraries 0.00% (of 11,383,888)
  +           0 Uncompressed assemblies 0.00% (of 3,718,144)
  +     264,267 Package size difference 2.88% (of 9,164,106)
```

**Comment by stefanoberdoerfer** [comment]
Thanks for the hint.

I was able to find a better workaround for my problem than downgrading AGP.

I didn't find any real differences in the dex files, but while analyzing the contents of both apks in AndroidStudio I noticed that the zip entries for all embedded .NET assemblies within the two apk differed in size.
The .dlls in the apk with enabled minification were around 20% smaller.

After some more hours of digging I found out, that in the Android Gradle Plugin versions 3.6.0 to 4.1.0 they switched to a more performant tool for building apks called [zipflinger](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/zipflinger/).
This tool can be disabled by adding this line to my `gradle.properties`:
```
android.useNewApkCreator=false
```

And with this change my app is working! Even with newer AGP versions like 7.1.2 🎉 

So I think the monodroid loading of assemblies is somehow not compatible with the way `zipflinger` adds the .NET assemblies to the apk.

**Comment by dellis1972** [comment]
Interesting, ok so that is the problem then. The assembies should be added to the apk as 'Stored` not compressed. This is because we do some memory mapping directly into the apk for performance reasons. We don't want to have to extract the assembly from the apk. 

This new tool must be adding everything as `Deflate`

**Comment by dellis1972** [comment]
I think we can close this for now as I does not seem to be an issue with Xamarin.Android itself.
