### ISSUE TITLE
Strip AOT shared libraries when packaging

### ISSUE THREAD

**Issue by grendello** [xamarin/xamarin-android#6840]
https://github.com/xamarin/xamarin-android/pull/6683 introduced LLVM-based toolchain and it appears that the debug data generated during build is much bigger than before.
We should probably strip AOT (and perhaps other) .so libraries on packaging time.

**Comment by grendello** [comment]
Alternatively, we can pass `-S` via the `LdFlags` property of the `AotCompiler` task

**Comment by jonathanpeppers** [comment]
Radek add this at one point:

https://github.com/xamarin/xamarin-android/blob/dccda9898170e7fe979fd7f3e1811061a9b19af7/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets#L212-L227

So AOT `.so` files aren't going through here?

**Comment by grendello** [comment]
It appears it only affects framework libs? I think adding `-s` to `LdFlags` would be faster - we'd save running `strip` X times
