### ISSUE TITLE
AppDomain.CurrentDomain.FirstChanceException didn't get trigger

### ISSUE THREAD

**Issue by dzeping96** [xamarin/xamarin-android#6866]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2019 16.11.10, Xamarin 16.11.000.197, Xamarin.Android SDK 12.0.0.3

### Description

I trying to achieve global exception handler with [AppDomain.CurrentDomain.FirstChanceException](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.firstchanceexception?view=netframework-4.8) I understand that this is not a proper way to handle exception, but I am using this only for a global log purpose, because it will be triggered when all exception happen, even within a try/catch. I still using proper try/catch in every methods. The issue I met is it doesn't occur at all when an exception happened, is anybody know how to solve this, or any workaround? Or any reason why it is not working? Appreciate your helps!

### Steps to Reproduce

I tried in both App.xaml.cs -> OnStart and MainActivity -> OnCreate, add
`AppDomain.CurrentDomain.FirstChanceException += CurrentDomain_FirstChanceException;`

and define a handler
```
private static void CurrentDomain_FirstChanceException(object sender, System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs e)
{
    Console.WriteLine("MyException: " + e.Exception.Message);
}
```

and both doesn't have any effect.

**Comment by jpobst** [comment]
Confirmed.  This appears to be a known bug in Mono, which is tracked here:
https://github.com/mono/mono/issues/21111
