### ISSUE TITLE
Fix build for android NDK r23b

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6899]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Fix-build-for-android-NDK-r23b/10004575)._

---
[severity:It's more difficult to complete my work]
I recently upgraded from r21 to r23 and ran into issues with the built-in props files that prevented the build from working. In the file C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Application Type\Android\3.0\Android.NDK.props around line 22 I needed to remove the check ``and Exists('$(VS_NdkRoot)\toolchains\$(ToolchainName)-$(ToolchainVersion)\prebuilt\windows-x86_64')``. The newer version of the NDK doesn't not contain that folder but otherwise builds just fine without that check.

I am able to work around this by auto-creating that folder during solution generation, but that's not a great solution long-term.

Version info:
Microsoft Visual Studio Community 2022
Version 17.1.2
VisualStudio.17.Release/17.1.2+32319.34
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA534
Microsoft Visual C++ 2022

Azure App Service Tools v3.0.0   17.1.358.51495
Azure App Service Tools v3.0.0

C# Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Visual Basic Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   17.0.32113.165
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

---
#### Feedback Bot on 4/6/2022, 04:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dadude999** [comment]
I see the same issue; this currently blocks usage of modern NDKs. Not related to Xamarin.Android at all, just C++ support.
