### ISSUE TITLE
Root drive glob enumeration in `AutoImport.props` when `MonoAndroidResourcePrefix` is not defined

### ISSUE THREAD

**Issue by KirillOsenkov** [xamarin/xamarin-android#6937]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022

### Description

MSBuild glob evaluation takes a long time and throws first-chance exceptions accessing drive root locations such as `C:\System Volume Information`, etc.

This is because there's no condition here where we should check whether `MonoAndroidResourcePrefix` is empty:
https://github.com/xamarin/xamarin-android/blob/4a958fc8fec73180bc7f9379c95200c68711f477/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props#L29

Compare with this line that correctly checks for whether it's empty:
https://github.com/dotnet/maui/blob/87cc1877ad68e9d13239b85203d0ee6e7f9231dd/src/Workload/Microsoft.Maui.Sdk/Sdk/AutoImport.props#L43

### Steps to Reproduce

This is when building a new project, it's unclear to me how these targets get included because I don't have a binlog yet, we just debugged MSBuild when it happened

**Comment by KirillOsenkov** [comment]
Reported by @miloush

**Comment by jonathanpeppers** [comment]
We set this here by default:
https://github.com/xamarin/xamarin-android/blob/68edc60db5eb735c34c885add84465f6db2ab0bf/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L7

It's probably worth checking if it's empty, though. We don't *ever* want it wildcarding an entire drive.

Is there some custom MSBuild logic that clears this property? It's set when a workload's `Sdk.targets` are imported, then the `AutoImport.props`' item groups would be evaluated right after.

**Comment by KirillOsenkov** [comment]
My understanding is that this happens in a pretty vanilla .NET project, with no Android (knowingly) used at all. It's clearly enumerating the drive, just don't know why the default value wouldn't get picked up.

**Comment by jonathanpeppers** [comment]
@miloush can you share a `.binlog` of this problem?

**Comment by KirillOsenkov** [comment]
it's in your email :)

**Comment by jonathanpeppers** [comment]
`$(EnableDefaultAndroidItems)` isn't in the emailed `.binlog` at all.

How does it even evaluate this item group?

https://github.com/xamarin/xamarin-android/blob/4a958fc8fec73180bc7f9379c95200c68711f477/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props#L29

**Comment by KirillOsenkov** [comment]
Maybe MSBuild evaluates the globs before evaluating the conditions??

**Comment by KirillOsenkov** [comment]
Ugh, let me dig into this some more:
https://source.dot.net/#Microsoft.Build/Definition/ProjectLoadSettings.cs,f3011bd220c9f8b3

**Comment by jonathanpeppers** [comment]
If `DoNotEvaluateElementsWithFalseCondition` is a thing, then it implies they could possibly be evaluated...

If I add a `Condition` on each item like:
```xml
<AndroidResource Include="$(MonoAndroidResourcePrefix)\*\*.xml" Condition=" '$(MonoAndroidResourcePrefix)' != '' " />
```
Would it have the same behavior anyway?

Let me know what you find.

**Comment by KirillOsenkov** [comment]
No, I think there's no bug in Xamarin Android, it's just the tool we used to call into MSBuild to evaluate didn't set this (I think everyone should be setting this). I will confirm soon, and if so, we'll close the bug.

**Comment by KirillOsenkov** [comment]
Confirmed that the bug was on our side. Setting DoNotEvaluateElementsWithFalseCondition fixed it. 

Sorry about the noise! And thanks into looking into this!

**Comment by miloush** [comment]
It does sound like a good idea to check that `MonoAndroidResourcePrefix` is non-empty though, so that the whole drive is not included for whatever reason.

Alternatively, the `MonoAndroidResourcePrefix` could be set in the targets including trailing slash and the individual `<AndroidResource`s could have `*\*.xml` rather than `\*\*.xml` so that it never fallbacks to root.
