### ISSUE TITLE
VS 2022 17.2.0 pre- R8 : Validation error : The generic signature has a different number of interfaces than the class.

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/xamarin-android#6944]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Vs2022 17.2.0 pre3 and pre4.0

### Description

It is really weird problem. When I try to build  X.F project on Android, I am getting an error` "R8 : Validation error : The generic signature has a different number of interfaces than the class." `

Exact same Project with exact same signature .cert files used works just fine using VS2019. I have same SDK, NDK, JDK path defined for both VS versions. What could be the issue here?

### Steps to Reproduce

Difficult to say about Repro steps because I have no clue why this can occur while it works just fine with VS2019

### Did you find any workaround?

Using VS2019 16.11.12  

### Relevant log output

```shell
I can provide the logs as private if possible.
```

PS, it doesnt seem to be a general issue. When I try with another project using same settings but different cert to sign, it works fine.

**Comment by jonathanpeppers** [comment]
This error means that r8 failed trying to compile all Java code to Android DEX format:

    R8 : Validation error : The generic signature has a different number of interfaces than the class.

It's not actually related to signing.

Can you share a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? Maybe just the snippet of the `Task "D8"` or `Task "R8"` would be enough to look into this further.

**Comment by EmilAlipiev** [comment]
Thanks for your quick reply. I have seen that it seems to be related to pspdfkit nuget used in the project and proguard. Possibly some proguard settings should be extended? I guess Linker removed more than supposed to be.

```
 Info in obj\Release\110\androidx\proguard\faca6582-1b42-4117-a181-9d1634192e61.cfg at line 96, column 1: (TaskId:490)
3>  Ignoring option: -optimizations (TaskId:490)
3>  Info in obj\Release\110\lp\7\jl\bin\classes.jar:com/pspdfkit/internal/ia.class: (TaskId:490)
3>  Invalid signature 'Ljava/lang/Object;Ljava/lang/Object<Lcom/pspdfkit/internal/ka;Lcom/pspdfkit/internal/ja;>;' for class com.pspdfkit.internal.ia. (TaskId:490)
3>R8 : Validation error : The generic signature has a different number of interfaces than the class.
3>  Signature is ignored and will not be present in the output. (TaskId:490)
3>  Info in obj\Release\110\lp\7\jl\bin\classes.jar:com/pspdfkit/internal/s4.class: (TaskId:490)
3>  Invalid signature 'Ljava/lang/Object;Ljava/lang/Object<Lcom/pspdfkit/internal/u4;Lcom/pspdfkit/internal/t4;>;Lcom/pspdfkit/internal/o4;' for class com.pspdfkit.internal.s4. (TaskId:490)
3>R8 : Validation error : The generic signature has a different number of interfaces than the class.
```

**Comment by sgjesse** [comment]
It could look as if the `pspdfkit` has been processed by a shrinking tool, which has left some of the [`Signature` attributes](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.7.9) invalid. R8 will normally rewrite `Signature` to match the rewritten program. However, if the `Signature` is invalid on input it will be removed and the warning you see will be emitted. This should not fail compilation, and if the program does not require the generic signature information it should fine to ignore these warnings.

However, the suppliers of the `pspdfkit` library should be notified that their code contains invalid generic signature information.
