### ISSUE TITLE
Paint.Color is attributed with [SupportedOSPlatform("android29.0")] causing warnings in Maui

### ISSUE THREAD

**Issue by buyaa-n** [xamarin/xamarin-android#6962]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Mono.Android.dll 31.0.101-preview.11.117

### Description

Paint.Color setter is annotated with `[SupportedOSPlatform("android29.0")]` 
![image](https://user-images.githubusercontent.com/45579687/165155957-827b1037-4eba-4fe4-b13c-81c01e809c61.png)
which causing false positive warning for each call of the API, from the [PR review comment](https://github.com/dotnet/maui/pull/6237/files/fba9e343bf35928902335de8f4553483e4211399#r857912371) `setColor(int) was added in API 1 and then they added a long overload in API 29`. 

### Steps to Reproduce

1. Open a project where CA1416 is enabled
2. Try set a Color for Paint
```cs
   var paint = new Paint();
   paint.Color = _endColor;
```
3. See CA1416 warning

CC @PureWeen

**Comment by jpobst** [comment]
I am hoping the updated ref pack will get published when the next RC of Maui comes out:
https://github.com/xamarin/xamarin-android/issues/6914

If not, I will raise the issue again so we get it published.  😁

**Comment by buyaa-n** [comment]
@jpobst `SpannableString.Length()` is also annotated with `[SupportedOSPlatform("android29.0")]` and causing warnings. @mattleibow says [This seemed suspicious and I just tested on a 23 emulator and it works.](https://github.com/dotnet/maui/pull/6237#discussion_r859630746). Do I need to create a new issue for this or it is already been reported/handled?

**Comment by jpobst** [comment]
Looks like this commit did not make it in time, so a new pack was not published with RC2: https://github.com/xamarin/xamarin-android/commit/07cde0138eca5cc0ee307ebdb5797e5bc285798b

It should be published with RC3.

I have not seen any issue about `SpannableString` yet.

**Comment by jpobst** [comment]
Investigated `SpannableString` and made fixes here: https://github.com/xamarin/xamarin-android/pull/6976.

**Comment by jpobst** [comment]
This should be fixed now in RC3:

https://www.nuget.org/packages/Microsoft.Android.Ref.31/32.0.300-rc.3.45
