### ISSUE TITLE
Minor type differences after migrating existing binding library to .NET6

### ISSUE THREAD

**Issue by BenBtg** [xamarin/xamarin-android#6967]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.2.0 Preview 5.0

### Description

After migrating an existing library to NET6 I get a few errors due to apparent type changes.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0118	'IOfficeLensProductivity.InterpolationType' is a type but is used like a variable	SeeingAI.Core (net6.0-android)	D:\Dev\Customers\SeeingAI\SeeingAI-Mobile\Core\Platforms\Android\Helpers\OfficeLensHelper.cs	35	Active
Error	CS0572	'InterpolationType': cannot reference a type through an expression; try 'IOfficeLensProductivity.InterpolationType' instead	SeeingAI.Core (net6.0-android)	D:\Dev\Customers\SeeingAI\SeeingAI-Mobile\Core\Platforms\Android\Helpers\OfficeLensHelper.cs	35	Active
Error	CS0103	The name 'OfficeLensProductivityInterpolationType' does not exist in the current context	SeeingAI.Core (net6.0-android)	D:\Dev\Customers\SeeingAI\SeeingAI-Mobile\Core\Platforms\Android\Helpers\OfficeLensHelper.cs	35	Active
Error	CS0103	The name 'OfficeLensProductivityImageType' does not exist in the current context	SeeingAI.Core (net6.0-android)	D:\Dev\Customers\SeeingAI\SeeingAI-Mobile\Core\Platforms\Android\Helpers\OfficeLensHelper.cs	102	Active

### Steps to Reproduce

Clone git@ssh.dev.azure.com:v3/msresearch/SeeingAI/SeeingAI-Mobile
Branch Net6Migration2

### Did you find any workaround?

Update the Client to take the new types.

### Relevant log output

```shell
>D:\Dev\Customers\SeeingAI\SeeingAI-Mobile\Core\Platforms\Android\Helpers\OfficeLensHelper.cs(35,27,35,44): error CS0572: 'InterpolationType': cannot reference a type through an expression; try 'IOfficeLensProductivity.InterpolationType' instead
1>D:\Dev\Customers\SeeingAI\SeeingAI-Mobile\Core\Platforms\Android\Helpers\OfficeLensHelper.cs(35,13,35,44): error CS0118: 'IOfficeLensProductivity.InterpolationType' is a type but is used like a variable
1>D:\Dev\Customers\SeeingAI\SeeingAI-Mobile\Core\Platforms\Android\Helpers\OfficeLensHelper.cs(35,47,35,86): error CS0103: The name 'OfficeLensProductivityInterpolationType' does not exist in the current context
1>D:\Dev\Customers\SeeingAI\SeeingAI-Mobile\Core\Platforms\Android\Helpers\OfficeLensHelper.cs(102,17,102,48): error CS0103: The name 'OfficeLensProductivityImageType' does not exist in the current context
1>D:\Dev\Custom
```

**Comment by jpobst** [comment]
.NET 6 binding projects have a different set of defaults that use more modern code constructs.  However these differences can definitely change the API of existing binding libraries.  There are MSBuild properties that allow you to retain the previous API documented here:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetBindingProjects.md#migration-considerations
