### ISSUE TITLE
Could not compile native assembly file: typemaps.arm64-v8a.s

### ISSUE THREAD

**Issue by L10Messi10** [xamarin/xamarin-android#6974]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022

### Description

Currently transferred my project to another PC and Got this error on my current PC running windows 10 vs 2022 while on the other PC (windows 11) the project runs fine, what could be this error?? been googling all day, and seems that there are no answers on this error yet.

### Steps to Reproduce

1. Create a project on vs 2022 xamarin forms on windows 11
2. Open the project with windows 10
3. run the project

and I got this error:  Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not compile native assembly file: typemaps.arm64-v8a.s	iViewServer.Android			

### Did you find any workaround?

No

### Relevant log output

```shell
2>  [i686-linux-android-as.EXE stderr] Assembler messages:
2>  [i686-linux-android-as.EXE stderr] Error: can't open typemaps.x86.s for reading: Permission denied
2>  [aarch64-linux-android-as.EXE stderr] Assembler messages:
2>  [aarch64-linux-android-as.EXE stderr] Error: can't open typemaps.arm64-v8a.s for reading: Permission denied
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1928,3): error XA3006: Could not compile native assembly file: typemaps.arm64-v8a.s
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by MagicAndre1981** [comment]
> Permission denied

check the permissions of the project folder so that your current account has full read/write permissions. Better way is to commit the code into a repository on the old PC and clone the repository on the new device.

**Comment by L10Messi10** [comment]
> > Permission denied
> 
> check the permissions of the project folder so that your current account has full read/write permissions. Better way is to commit the code into a repository on the old PC and clone the repository on the new device.


Thanks, this method quite worked in a weird way. My project is currently saved on OneDrive and I assume, that this error had to do with Github, as on my old PC there were still uncommitted changes, since I committed those changes, the project works fine again.
