### ISSUE TITLE
Cannot able to show both the horizontal and vertical scrollbars at a time in the Viewport

### ISSUE THREAD

**Issue by Deepak1799** [xamarin/xamarin-android#7006]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.0.1

### Description

I am developing a scroll view that supports both horizontal and vertical scrolling. So I am using two controls - ScrollView (Parent) and HorizontalScrollView (child). But I cannot make both the scrollbars to be visible at anytime in the view port.

If I add HorizontalScrollView as a child to the ScrollView, and the content is larger than the view port, the below behavior happens.
* The vertical scroll bar alone visible in the view port all the time, 
* But the horizontal scrollbar is visible only at the bottom of the content. We need to scroll down to the bottom end to see it.

Simimarly, If I add ScrollView as a child to the HorizontalScrollView, and the content is larger than the view port, the below behavior happens.
* The horizontal scroll bar alone visible in the view port all the time, 
* But the vertical scrollbar is visible only at the right end of the content. We need to scroll horizontally to the right end to see it.

This behavior does not indicate that the content size is large (and need to scroll) in one of the directions at a time. So we need to show both the scrollbars in the view port every time.

### Steps to Reproduce

1. Create a file new Xamarin Android App.
2. Use the below code to create a scrollview to support horizontal and verical scrolling.

```
<ScrollView
    android:fillViewport="true" >
    <HorizontalScrollView
        android:fillViewport="true" >
//<Add your content here: Make sure the size the large than the viewport vertically and horizontally/>
    </HorizontalScrollView>
</ScrollView>
```
3. You can see only the vertical scrollbar is visible in the viewport. But the horizontal scrollbar is not visible in the viewport and will appear only at the bottom end of the content. 

### Did you find any workaround?

No.

### Relevant log output

```shell
NA
```

**Comment by jonathanpeppers** [comment]
@Deepak1799 it appears that your question is "How do I use ScrollView on Android?"

And so this isn't a problem in Xamarin.Android at all? but a question about the usage of an Android API? Xamarin.Android just provides what Android provides as-is. We don't have any logic for `ScrollView` here.

I would recommend asking a question on a Q&A site like StackOverflow. If you do indeed find a bug in Xamarin.Android this is the place for it, thanks!
