### ISSUE TITLE
[Templates] Update .NET 6 templates

### ISSUE THREAD

**Issue by davidortinau** [xamarin/xamarin-android#7041]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

All

### Description

Update app icon and splash screen for all templates to reflect .NET 6 branding - purple and .NET logo.

Remove/replace all Xamarin branding 

### Steps to Reproduce

create a new .NET 6 for Android app and observe the Xamarin logo and branding

**Comment by jonathanpeppers** [comment]
@davidortinau where should we get the images from? MAUI templates use `.svg` files.
