### ISSUE TITLE
Redirecting specific Xamarin.Android issues to Microsoft’s Developer Community is useless

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#7056]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.3.0 Prev 1.1

### Description

@jonathanpeppers, @dellis1972 , @jonpryor , @jpobst 
 
I’ve now been asked here twice to redirect problems raised here in Xamarin.Android to the Developer Community site through the Visual Studio’s Send Feedback/Report a Problem functionality.

From my own experience, and I note others here have reached the same conclusion, in that it simply doesn’t work, the problems reported such as #4317 just aren’t fixed, as the following quote from the Feedback Bot proves.

_I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issue's severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you._

I originally reported #4317 **VS 16.5.0 Preview 2.0 Android Designer** problem on 25 Feb 2020. On 26th October 2021, @jonathanpeppers  eventually closed the issue here with the recommendation that I should report to the developer community as it wasn’t now the Xamarin.Android team responsibility to report these types of issues. 

Reluctantly after reporting the problem close to two years earlier, I eventually did report it on Dec 18th 2021 **Xamarin.Android Designer fails on opening layout files in any Xamarin.Android app, if the project is using a NavigationComponent** and nearly 4 months later on April 02, 2022, received the above useless reply. 

So now over two years later Xamarin.Android is still stuck with that designer problem. I have to ask the question if a developer supplies the Developer Community with a test app, that reliably reproduces the problem, then what else can you do other than to report/complain here. The above proves that the Microsoft Visual Studio team is only going to look at your specific problem if it gets enough votes. My conclusion is, that it didn’t get any votes, so the test app was never even checked. If the bot had a brain, it would know that the steps it is now asking for have already been supplied.

From a developer's point of view producing a report and suppling a test app that undisputably demonstrates the problem is a time-consuming process.  To see that effort going for naught reward can only make one reluctant to ever participate again in such a useless exercise. Fixing bugs based on votes. Interesting concept, what fool came up with that one? I’d guess he isn’t a programmer. 

Android’s NavigationComponent – Single Activity app concept is not exactly new, it has been around for years now and is Google’s recommendation for modern Android development. It is also obvious that Microsoft is aware of it, as the following link in MAUI proves https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs. I’ve no particular interest in MAUI so I assume there is no nav_graph.xml involved.

The second example was only posted 4 days ago #7048 **VS2020 17.3.0 Preview 1.1 Add new item dialog - useless**. This was closed today by @jonathanpeppers  with the same recommendation as previously.

As the above response proves, I would be wasting my time again reporting this glaring problem of not being able to use Add new item in any Xamarin.Android app. 

While I’m venting, I’d like to point out that Xamarin.Android starter templates in Visual Studio 2022 are stuck in a time warp of around 2019. It barely makes it to Android 10, with the only concession to at least support the jetpack AndroidX libraries. Just consider the standard templates that are available to create a new Android app and then compare them to what is available in Android Studio’s starter templates. 

All you can do now with Xamarin’s starter templates is to strip just about everything once you opened the newly created project.

_Prior to this latest release:_ 

The following are changes that you have to make for any new testapp depending on which of the 4 templates is chosen.

1. Edit the default namespace, e.g. com.companyname.AppName. 
2. Edit resource.designer.cs in two places to reflect the new namespace, and the MainActivity’s namespace.
3. Update the Xamarin.AndroidX.AppCompat and Xamarin.Google.Android.Material references to something closer to the latest versions. 
4. Remove Xamarin.Essentials (not required) if writing a Xamarin.Android app. If a user wants it, let them add it or at least make it optional.

If you want to make an app using the NavigationComponent then there is even more work to do. In my opinion, it is about time that these templates are updated to reflect modern Android development. I’m pretty sure that they haven’t been touched since approximately sometime in 2019.

Note there is no provision or creation of a themes.xml  for both the values and values-night folders, so no provision for Light and Dark themes. The colors.xml still uses names such colorPrimaryDark and colorAccent instead of describing the colour e.g. 

`<color name="red_700_dark">#9a0007</color>`
 
and then referring to the color name in the theme.xml as an in the following example: 

`<item name="colorPrimaryVariant">@color/red_700_dark</item>`
 
All the above and more could be automated if the templates and wizard were modernised.

_Version 17.3.0 Prev 1.1_

**As well as no Add New Item Dialog for Android, there are no longer any Android templates period** – heaps of MAUI stuff, but no Android templates. The above problem is now solved, just get rid of all the Android templates. I hope someone on the Visual Studio team didn’t do that deliberately, but you’d never know judging by the stuff up of this release. Obviously, no one was concerned about Android – just gotta get MAUI out there.

**I understand that it is not the team here that is responsible for these releases.  Since the recommended suggestion isn’t a solution worthy of a developer’s time, I’m therefore wondering if you could advise of a more appropriate channel? How about the name and email address of the person who heads up the Visual Studio 2020 side of Xamarin.Android, where I would be at least guaranteed a timely response that these problems can and will be fixed.**  

### Steps to Reproduce

Not applicable

### Relevant log output

```shell
None
```

**Comment by jpobst** [comment]
The only service I know of where Microsoft guarantees a timely response (I think) is a support incident:
https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-tech-support

The official place to give feedback to the Xamarin VS Extension team is Developer Community.  Unfortunately we do not have any control or insight over how other teams triage and prioritize their issues.

I sympathize that you have not received a proper response(s) from DevCom, but this is still not something that our team is involved with.
