### ISSUE TITLE
The debugger isn't "breaking" correctly when there is an exception in VSMac 2022 / VSMac Preview 2022

### ISSUE THREAD

**Issue by xDaijobu** [xamarin/xamarin-android#7085]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VSMac & VSMac Preview

### Description

**net6.0-android ( VSMac & VSMac Preview )**
![image](https://user-images.githubusercontent.com/22674537/173105620-0a60e96e-712a-4b57-ac52-f3f172a3c6b5.png)

**Xamarin.Android ( VS Windows )**
![image](https://user-images.githubusercontent.com/22674537/173105215-1e7682cd-b802-49c9-ac40-d49b252a29c6.png)

**Xamarin.Android ( VSMac & VSMac Preview )**
![image](https://user-images.githubusercontent.com/22674537/173105300-0936da65-20c7-4bca-950a-9cb5ae894f11.png)
<img width="2554" alt="Bc6d36a4fbb6a4e8c9ed825676c86a77c637904472730329015_Screen_Shot_2022-06-10_at_15 35 26" src="https://user-images.githubusercontent.com/22674537/173104725-7870ab03-a830-4eb0-a510-9f599c7ae6ee.png">

source: ‘Mono.Android’
stacktrace:
```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.

at Android.Runtime.JNINativeWrapper._unhandled_exception (System.Exception e) [0x0000e] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x0001d] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:111
at (wrapper native-to-managed) Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(intptr,intptr,intptr)
```

### Steps to Reproduce

1. Create a Xamarin.Forms / Xamarin.Android project.
2. throw new Exception (“Fire!”);
3. run the project with VSMac / VSMac Preview

[test.zip](https://github.com/xamarin/xamarin-android/files/8880392/test.zip)

### Did you find any workaround?

https://discord.com/channels/732297728826277939/738043671575920700/983915567184498739

'Start without debugging'
![image](https://user-images.githubusercontent.com/22674537/173106278-d5373ed4-40b1-4b25-86b4-60ae855d26bb.png)

![image](https://user-images.githubusercontent.com/22674537/173106309-6dc37110-3297-44b2-9fc2-bdea9e7f4a65.png)

**Comment by xDaijobu** [comment]
Xamarin.Android with Visual Studio 2022 (Windows)
![image](https://user-images.githubusercontent.com/22674537/173274020-ff46b953-e0f6-4710-aea5-80000960fe79.png)

Microsoft Visual Studio Community 2022
Version 17.2.3
VisualStudio.17.Release/17.2.3+32526.322
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA178
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.2.392.13739
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.392.13739
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.2.392.13739
Azure Functions and Web Jobs Tools

C# Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.2.20 (482eb2a)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2218101+885a343b00bcab620a90c1550c37dafd730ce984
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

TypeScript Tools   17.0.10418.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22253.3+058e7a7e597a02c129f38742f250a4b212da9ee3
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.2.0.175 (d17-2@e4ffdc0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.2.0.244 (remotes/origin/d17-2@197e1a0b7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.15 (2e3b60e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.3.0.3 (d17-2/bbba5a2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/d17-2@9760f0a9
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac


Xamarin.iOS and Xamarin.Mac SDK   15.10.0.1 (568bdb24e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by xDaijobu** [comment]
**_Workaround_** 
![image](https://user-images.githubusercontent.com/22674537/173276055-44f4efc0-6f73-4549-b2c4-52e4f069f09d.png)



![image](https://user-images.githubusercontent.com/22674537/173276154-9fe2c05b-a0c2-4ace-9a4f-f0a28c6eb232.png)

**Comment by xDaijobu** [comment]
Xamarin.Android 12.3.99.58 (main/64b22fc)
Visual Studio 2022 17.3.0 Preview 1.1

![image](https://user-images.githubusercontent.com/22674537/173278714-024ce991-0280-45ab-b4c2-595819b6e098.png)

**Comment by jpobst** [comment]
@jonathanpeppers I don't know how to assign this one.  If it's not you, please help it find a home!
