### ISSUE TITLE
Regression: Runtime errors with IL stripped assemblies

### ISSUE THREAD

**Issue by jxbrenner** [xamarin/xamarin-android#7088]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Xamarin.Android 12.3

### Description

Mono runtime error, app hangs and crashes. See device log output below.

Sample project attached for reference. MSBuild configured to match what I'm using in VS 2019 for app distribution.
[XamarinAndroidApp.zip](https://github.com/xamarin/xamarin-android/files/8883280/XamarinAndroidApp.zip)

### Steps to Reproduce

1. New Android App (Xamarin) - Blank App
2. Configure MSBuild for static compilation, IL stripping, and target arm64-v8a
3. Build and run

### Did you find any workaround?

Build with Xamarin.Android 12.0.

### Relevant log output

```shell
Time	Device Name	Type	PID	Tag	Message
	Sonimtech XP8800	Info	1785	ActivityManager	Process com.companyname.xamarinandroidapp (pid 14562) has died: fore TOP 
	Sonimtech XP8800	Error	14562	mono-rt	
  at Java.Interop.JniRuntime.GetRegisteredRuntime (System.IntPtr invocationPointer) <0x720f10ff0c + 0x0007c> in <4be0212dda1448dbbb5bcb78bcd13cf4>:0 
  at Java.Interop.JniEnvironmentInfo.set_EnvironmentPointer (System.IntPtr value) <0x720f12534c + 0x0008b> in <4be0212dda1448dbbb5bcb78bcd13cf4>:0 
  at Java.Interop.JniRuntime..ctor (Java.Interop.JniRuntime+CreationOptions options) <0x720f110234 + 0x005b7> in <4be0212dda1448dbbb5bcb78bcd13cf4>:0 
  at Android.Runtime.AndroidRuntime..ctor (System.IntPtr jnienv, System.IntPtr vm, System.Boolean allocNewObjectSupported, System.IntPtr classLoader, System.IntPtr classLoader_loadClass, System.Boolean jniAddNativeMethodRegistrationAttributePresent) <0x720f4c15b0 + 0x0008b> in <97754039425649c180140cd9408a4bd2>:0 
  at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args) [0x000f3] in <97754039425649c180140cd9408a4bd2>:0 
	Sonimtech XP8800	Error	14562	mono-rt	
	Sonimtech XP8800	Error	14562	mono-rt	[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in System.Collections.Generic.Dictionary`2<intptr, Java.Interop.JniRuntime>:TryGetValue (intptr,Java.Interop.JniRuntime&): IL_0000: ret       
```

**Comment by jonathanpeppers** [comment]
This setting is not supported in .NET 6, does it help to remove it?
```xml
<BundleAssemblies>True</BundleAssemblies>
```

Likewise, we don't have support for this "experimental" setting either:
```xml
<AndroidAotMode>Hybrid</AndroidAotMode>
```
Which is what would use `cil-strip`. Can you give some more info on why you'd like to use it? Thanks!

**Comment by jxbrenner** [comment]
@jonathanpeppers hey what gives, now you're making me think! I don't think so. I spent some time comparing the output of stripped assemblies produced when I build with the example project with VS 2019 and VS 2022, and so far I believe cil-strip is still producing the same output for given input (go figure, it's version 0.6.9.0 in both versions of VS). Definitely the case with XamarinAndroidApp and System.Collections.Generic.Dictionary (what I'm getting the runtime error on in the example).

While I was doing that I found that the packages built with VS 2022 keep all the managed assemblies in assemblies/assemblies.blob instead of directly in the assemblies folder (or bundled). That's something different from VS 2019, I'm wondering if there's an easy fix here. Is there a build property I can set to disable the assembly store task?

**Comment by jonathanpeppers** [comment]
Yes, you might try this for your `Release` configuration:
```xml
<AndroidUseAssemblyStore>false</AndroidUseAssemblyStore>
```
And if that solves the issue, there might be a problem with this combination of settings. Let us know, thanks!

**Comment by jxbrenner** [comment]
Unfortunately if there's an easy fix, that's not it, still the same runtime error.

To help you help me I've attached a diff report of the build properties from the MSBuild logs of the example project (VS 2019 on the left, VS 2022 on the right). Does anything jump off the page for you? How about the runtime error? Invalid IL code in the BCL, I mean there shouldn't be any since we stripped it, and why would we need it since it's all statically compiled? As mentioned, mscorlib output from cil-strip appears exactly the same, ex. all methods in the method table have their bodies stripped and are patched NoInlining.

I'm wondering about the differences in the AndroidAotEnableLazyLoad, AndroidAotStripLibraries. These are both false in the VS2019 build, but I can't seem to override them in VS2022 using the project file.

[BuildPropDiffs.zip](https://github.com/xamarin/xamarin-android/files/8896680/BuildPropDiffs.zip)

**Comment by dellis1972** [comment]
@jxbrenner can use us the `monodis` tool (if you have access to mono) to get the contents on the stripped assembly from both VS2019 output and VS2022 output. Then diff that output to see what changed.

**Comment by jxbrenner** [comment]
@dellis1972 I was doing a pretty superficial comparison just looking at some of the tables and method signatures using dnSpy, but I installed mono, dumped the CIL images, and diffed to see what changed. I focused on mscorlib since the runtime error is complaining about invalid IL in the Dictionary type.

For a given input (mscorlib v2.0.5.0), there are definitely differences in the build output of VS 2019 and VS 2022 despite passing the same build parameters. However, these differences are not a function of cil-strip. I compared both the stripped and non-stripped IL and any differences between the two assemblies is unrelated to stripping. I didn't see any obvious differences (to me) between System.Collections.Generic.Dictionary, but I did see quite a few overloads present in the 2019-built assembly that were not present in the 2022 assembly (ex. System.Action, ILGenerator.Emit).

All my Android development has been at a higher level of abstraction, so I'm a bit out of my depth here. My analysis is basically these things are different, shouldn't they be the same? Beyond that I still wonder why my build log shows AndroidAotEnableLazyLoad and AndroidAotStripLibraries as true when I set them false in the project file, and wonder if there is correlation here. Could the symbol stripping and/or lazy loading cause this runtime error on projects where the IL has been stripped? I assume the missing overloads in mscorlib is linker related. Would not being able to override these properties be issues in themselves?

Any thoughts guys? I've attached an archive with the assemblies, IL dumps, and WinMerge project files. I'm willing to try whatever build properties you can think of.

[mscorlib-il-diff.zip](https://github.com/xamarin/xamarin-android/files/8904484/mscorlib-il-diff.zip)

**Comment by dellis1972** [comment]
Regarding `AndroidAotStripLibraries` the actual name of that property is `_ AndroidAotStripLibraries` as its an "internal" property. So be sure you include the underscrore when setting it in your project. 

`AndroidAotEnableLazyLoad` is not an internal property so that one should work...

can you post a snippet from your csproj where you are setting these properties?

@grendello we might need some runtime assistance on this issue. I'm not sure how to go about getting the required diagnsotic data from the runtime to debug this issue.

**Comment by jxbrenner** [comment]
@dellis1972, thanks for the heads up, silly mistake. Here's my project file (appended .txt so I could upload):
[XamarinAndroidApp.csproj.txt](https://github.com/xamarin/xamarin-android/files/8913335/XamarinAndroidApp.csproj.txt)

@grendello here's the device log:
[log.txt](https://github.com/xamarin/xamarin-android/files/8913322/log.txt)

I spent some time trying different versions of VS 2022 and found that I'm able to execute both the blank template app and my app with these build settings when building with VS 17.1.7 (Xamarin.Android 12.2.4). I get this runtime error with VS 17.2.0 and up (>= Xamarin 12.3.0).

The values of_AndroidAotStripLibraries and AndroidAotEnableLazyLoad appear to have no bearing on the issue, since I can build with XA 12.2.4 with these properties either true or false. Also, I still get the runtime error when setting either property true or false when building with XA 12.3.0.

It seems pretty clear Xamarin.Android 12.3 breaks IL stripping. It doesn't matter if I manipulate the targets file to get the CilStrip task to run on just the shared and/or head project assembly, any IL stripping results in an InvalidProgramException for Invalid IL code.

**Comment by gabriel-kozma** [comment]
This issue interests me as well, I use the hybrid aot and have noticed the same thing

**Comment by grendello** [comment]
@lambdageek would you mind looking at this issue? It seems like `mono/mono` JIT generating somehow invalid code for generics? Thanks!

**Comment by gabriel-kozma** [comment]
any updates on this?

**Comment by jxbrenner** [comment]
@grendello @lambdageek 
Any ideas yet as to why the mono JIT is breaking with hybrid AoT in Xamarin.Android 12.3? Isn't the JIT successful in compiling the same code when there is no AoT enabled?

**Comment by lambdageek** [comment]
Hi folks @jxbrenner , @gabriel-kozma, add this to your `.csproj`:

```xml
    <AndroidAotAdditionalArguments>hybrid</AndroidAotAdditionalArguments>
```


@grendello @jonathanpeppers @dellis1972 as far as I can tell, setting `<AndroidAotMode>Hybrid</AndroidAotMode>` doesn't actually pass `--aot=...,hybrid,...` to the mono AOT compiler.

for future reference: I used the following to get extra logging during aot compilation:
```xml
    <AndroidAotAdditionalArguments>log-generics,hybrid</AndroidAotAdditionalArguments>
    <AndroidExtraAotOptions>-v</AndroidExtraAotOptions>
```

which dumps information about added generic instances and also each method that gets compiled.

**Comment by jxbrenner** [comment]
@lambdageek Thank you! I passed that build property and was able to execute my app built with VS 17.3.0 (Xamarin.Android 13.0). I'll just keep that one in my project file from now on and keep and eye on the device log for the Mono AOT mode setting going forward.

With regards to closing the issue, I suppose the regression lives somewhere in the changes to the build tasks in Xamarin.Android 12.3. `<AndroidAotMode>Hybrid</AndroidAotMode>` no longer sets the runtime to hybrid AoT. Is the intent then to make it so it does again, or just leave this as tribal knowledge here in this issue as this is not a documented feature?

**Comment by simon10says** [comment]
@lambdageek , thanks. I'm also able to my app working with your solution.

Can I just double confirm, to get the hybrid aot mode, we just need to add the following?
```xml
<AotAssemblies>true</AotAssemblies>
<AndroidAotAdditionalArguments>hybrid</AndroidAotAdditionalArguments>
```

Do I still need to set `<AndroidAotMode>`?
