### ISSUE TITLE
Debugger not working in cross platform project when running on chrome os (chromebook)

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/xamarin-android#7089]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Xamarin.Android 12.3.0.3

### Description

When debugging a Xamarin.Android project on chrome os using a network connection, breakpoints in the android project are hit properly:

![breakpoint-mainactivity](https://user-images.githubusercontent.com/9071974/173393906-55a8dbdf-6837-43cb-9a3d-90da373e5088.png)

Breakpoints in the cross platform project are ignored:

![breakpoint-app](https://user-images.githubusercontent.com/9071974/173393947-04d8b0a3-2f13-4b67-9fd3-7e6ef2bf4bd4.png)

The sample project was created as a new project using the current wizard of Visual Studio for Mac 2022: https://github.com/thisisthekap/chromebookdebuggerissue

### Steps to Reproduce

See https://github.com/thisisthekap/chromebookdebuggerissue

**Comment by grendello** [comment]
@akoeplinger @lambdageek it might be either the IDE or the runtime side of the soft debugger, can you dispatch it as appropriate? Thanks!

**Comment by akoeplinger** [comment]
@grendello hmm given breakpoints work in the Android project but not in the "cross-plat project" (which is the NS2.0 library with the shared code) I'm not actually sure this is a debugger issue directly since there should be no difference since the actual app is the same. Maybe the .pdb from the NS2.0 library doesn't end up in the app somehow?

**Comment by jpobst** [comment]
Possibly related: https://github.com/xamarin/xamarin-android/issues/7085.

**Comment by thisisthekap** [comment]
@akoeplinger The NS2.0 library ends up in the app for sure, because all the code in there works properly (doing calculations, opening dialogs, ...).

**Comment by thisisthekap** [comment]
@jpobst I do not think this one is a duplicate of #7085, because I see no exception when running the app on chrome os (but i might be easily missing something).

**Comment by lambdageek** [comment]
@thaystg was able to reproduce the issue; she's investigating.

**Comment by thisisthekap** [comment]
@lambdageek @thaystg Are you able to provide an update?

**Comment by thaystg** [comment]
Not a fix yet, but there is a workaround. You can change the `DebugType` of your cross platform project to `embedded`, then the breakpoints will work.

**Comment by thisisthekap** [comment]
@thaystg Awesome! Does this workaround have any potentially harmful implications?
