### ISSUE TITLE
HLS Streaming Webview corrupts cookie headers in native network calls

### ISSUE THREAD

**Issue by dk-jlew** [xamarin/xamarin-android#7095]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VSMac 17.3

### Description

A WebView that renders a  `<video>` element that uses HTTP Live Streaming appears to corrupt the app's native networking stack (`HttpClient/AndroidClientHandler`) and causes duplicate cookie headers to be sent until the app is hard-reset. 

Xamarin.Android repro app
[HLSBugTest.zip](https://github.com/xamarin/xamarin-android/files/8903600/HLSBugTest.zip)

(net6 version) 
[HLSReproNet6.zip](https://github.com/xamarin/xamarin-android/files/8903615/HLSReproNet6.zip)

### Steps to Reproduce

1. Set up the WIFI connection of an Android emulator or device to proxy to Charles Proxy, ProxyMan, or the equivalent.
2. Build, deploy, and run the attached `DroidNative` app (debug mode) on the emulator/device.
3.  You should observe a webview with a streaming video in it (the URL for the page is `https://developer.apple.com/streaming/examples/basic-stream-osx-ios4-3.html`).  Meanwhile there are native requests to `https://www.draftkings.com` going on in the background.
4. Wait for 10-15 seconds, and observe the traffic captured in your proxy.  

- You should see a mix of webview traffic (`developer.apple.com` and related apple sites), and native traffic (`www.draftkings.com`).  
- If you inspect the request headers for the native traffic, you will see that about the 3rd request to `www.draftkings.com`, there are TWO `Cookie` headers, with overlapping cookies, and different values.  Once this starts, every subsequent (native) request will have two cookie headers, and their values will diverge over time.  This is not a legal HTTP/1.1 request.

### Did you find any workaround?

No

**Comment by jpobst** [comment]
To be clear, do you see this on both Classic and .NET 6 version?  They use very different `HttpClient` implementations and I am surprised if they are affected the same way.

**Comment by dk-jlew** [comment]
Hmm, now that you mention it, I'm not sure I did the net6 conversion right, let me check that.

**Comment by dk-jlew** [comment]
Ok, VSMac (17.3 preview) was not allowing me to deploy a project created via `dotnet new android` to either a simulator or my device:
![image](https://user-images.githubusercontent.com/58529643/173694265-5321535f-c512-4af3-8fed-b41d59d2d52b.png)

(Not sure what's incompatible w/ API level 29, I'll try a newer image)
So, I created the project from inside Visual Studio but apparently that was using the Xamarin.Android template.  I'll see if I can get the net6 one working, but while the results of that may be interesting,  our real app is Xamarin.Forms, it will take many months to port to MAUI, so we'd like to figure out how to fix/work around it in XF.

**Comment by jpobst** [comment]
> I'll see if I can get the net6 one working, but while the results of that may be interesting, our real app is Xamarin.Forms

Understood, however if possible, the results would potentially help us narrow down the cause.  😁

**Comment by dk-jlew** [comment]
We have attempted, unsuccessfully so far, to reproduce this behavior in a native (Android Studio/Kotlin) app, however we used higher-level networking stack than what AndroidClientHandler uses, because it would take quite a while to implement at that low of a level.  It's quite possible that this is a WebKit/Android-level bug vs a Xamarin bug, but I have no real evidence either way.  I copied `AndroidClientHandler` (Xamarin version) to my app so I could easily step through that code in the debugger and I didn't spot anything wrong.

**Comment by dk-jlew** [comment]
After some more digging, I now believe this is the nature of the problem:

https://stackoverflow.com/questions/16305486/cookiemanager-for-multiple-threads

For *some reason*,  when you display a webview with this kind of streaming video, someone seems to be installing a default java cookie handler, which then gets used by `AndroidClientHandler's` `URLConnections`, causing any new cookies to be detected/emitted by that mechanism, in addition to .NET's mechanism.

**Comment by dk-jlew** [comment]
Confirmed that in a default Xamarin.Android app:
- Upon startup the value of  (Android's) `CookieHandler.Default` is null
- When you use a webview to navigate to a webpage like https://developer.apple.com/streaming/examples/basic-stream-osx-ios4-3.html (or any webpage with this type of video streaming element), `CookieManager.Default` will be set, and from that point on, `Set-Cookie` response headers will cause both `AndroidClientHandler`'s cookie management and the newly-installed `CookieHandler` to conflict by emitting separate `Cookie` headers on subsequent requests.  This explains all of the bad behavior we have seen:
- Two `Cookie` headers per request
- Corruption persists until app restart

As a workaround, we are calling `CookieHandler.Default = new Java.Net.CookieManager(null, CookiePolicy.AcceptNone)` at app startup, since we do not want any kind of java-managed CookieHandling.  Whatever Android/WebKit code is installing the `CookieHandler` seems to only do it if there is none.  The WebView cookies seem to still work normally after this, and I have so far been unable to track down the AOSP or WebKit code that is setting the `CookieHandler`, but I'm not sure where to look.

**Comment by grendello** [comment]
@dk-jlew I'm afraid there's nothing we can do for you here. `AndroidClientHandler`/`AndroidMessageHandler` don't use neither `CookieManager` nor `CookieHandler` in any form or fashion 
(when `UseCookies` is set, they use the managed [CookieContainer](https://docs.microsoft.com/en-us/dotnet/api/system.net.cookiecontainer?view=net-6.0) since that's what's expected in the managed app), but even though they are affected by the behavior changes of the underlying 
`URLConnection` code, we must not apply workarounds to specific issues not directly related to our code in a framework - we must stay "generic".  

I'd advise bringing the issue up with the `WebView` maintainers to see if they even consider this a bug.  Your workaround appears to be perfectly good, however.

**Comment by dk-jlew** [comment]
I understand there's not much you can change to fix it, however it's not exactly true to say that you don't use `CookieManager` or `CookieHandler`, since (as I found out) the default is implicitly used by anyone using `HttpURLConnection`, which `AndroidClientHandler/MessageHandler` are built on top of.  It might be worth a discussion in your documentation at least, since the effects are pretty severe and hard to track down.
