### ISSUE TITLE
ExtraAddSelfManagedCallsToIncallservice is missing from Xamarin.Android SDK 12

### ISSUE THREAD

**Issue by trampster** [xamarin/xamarin-android#7115]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2019

### Description

The Xamarin docs say that PhoneAccount.ExtraAddSelfManagedCallsToIncallservice exists and is available in Xamarin.Android 12. However it's not there. https://docs.microsoft.com/en-us/dotnet/api/android.telecom.phoneaccount.extraaddselfmanagedcallstoincallservice?view=xamarin-android-sdk-12

This is an API that was added in API 31.

I am targeting API 31, and I have Xamarin.Android SDK 12:

![XamarinAndroid12](https://user-images.githubusercontent.com/2063633/174905913-9eda0eed-93e8-427e-9bac-0019f02d3a6f.png)

I get this error:
CS0117 'PhoneAccount' does not contain a definition for 'ExtraAddSelfManagedCallsToIncallservice'

### Steps to Reproduce

1. Make a Xamarin.Android Project
2. Set target API to 31
3. Make sure you have Xamarin.Android SDK 12 (see Help->About Visual Studio)
4. Try to use PhoneAccount.ExtraAddSlefManagedCallsToIncallService
-> notice that it doesn't compile

### Did you find any workaround?

No

**Comment by trampster** [comment]
I noticed that my Project is using Mono.Android from:
C:\Program Files (x86)\Microsoft Visual studio\2019\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v11.0

I assume this should be v12.0 instead.

I discovered after some digging that there is an option in the Project Properties called "Compile using Android version (Target Framework)" changing this  to Android 12 makes it work.

I found this confusing as this option doesn't indicate it has anything to do with the version of Xamarin.Android used.

**Comment by jonathanpeppers** [comment]
`$(TargetFrameworkVersion)` is the way you select a `Mono.Android.dll` and which C# bindings for the Android APIs it includes. The version of the Xamarin.Android package, might coincide with the latest `$(TargetFrameworkVersion)` you can use in a project. 

This concept predates Microsoft, I believe this design started at Novell (over 10 years ago) with the MonoDroid product.

In .NET 6, you can put `net6.0-android31` or `net6.0-android32` for the same behavior. The designs for this are here:

* https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#os-versions
* https://github.com/dotnet/designs/blob/main/accepted/2021/net6.0-tfms/net6.0-tfms.md
