### ISSUE TITLE
CarConnection API is missing

### ISSUE THREAD

**Issue by trampster** [xamarin/xamarin-android#7120]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022

### Description

Xamarin.Android does not seem to provide a wrapper for https://developer.android.com/reference/androidx/car/app/connection/CarConnection

This API is used for Android Auto

### Steps to Reproduce

1. Try to use CarConnection in a Xamarin.Android project
-> Doesn't compile
2. Look at the Xamarin docs, (not mentioned)

### Did you find any workaround?

No

**Comment by jpobst** [comment]
Looks like this is available in the NuGet package: https://www.nuget.org/packages/Xamarin.AndroidX.Car.App.App.

![image](https://user-images.githubusercontent.com/179295/175160631-1a6dba5b-081f-40d7-bf27-5798fa68aeff.png)
