### ISSUE TITLE
Hostname not verified when sending request

### ISSUE THREAD

**Issue by IgorKravchenko10** [xamarin/xamarin-android#7149]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 17.3.0 Preview 2.0, .net 6.0.400

### Description

We started developing MAUI application and stuck with error trying to send http request. We already have a Xamarin Forms application which successfully works with same API.
We get error `Hostname not verified when sending request`.
This issue described [here](https://docs.microsoft.com/en-us/answers/questions/885827/error-hostname-not-verified-when-sending-request-o.html)
Also reported in [maui](https://github.com/dotnet/maui/issues/8518)
MAUI reproduction (not working) [github](https://github.com/IgorKravchenko10/Maui-web-service-bug) [onedrive](https://1drv.ms/u/s!Aun0lW86yXKJijM3oPvspRfY-8nR?e=xKHhcY) [zip](https://github.com/xamarin/xamarin-android/files/9045283/ServiceTest.zip)
Xamarin Forms (working) [github](https://github.com/IgorKravchenko10/XFWebService) [onedrive](https://1drv.ms/u/s!Aun0lW86yXKJijT30Nexve-y0Q7k?e=OC79QY) [zip](https://github.com/xamarin/xamarin-android/files/9045272/XFServiceTest.zip)

### Steps to Reproduce

1. Create a new MAUI application.
2. Make http request to API with self signed certificate.
3. Get error "Hostname not verified when sending request".

### Did you find any workaround?

No

**Comment by simonrozsival** [comment]
@IgorKravchenko10 There's a mismatch between your server's hostname (`tcu.base2base.com.ua`) and your certificate's CN (`DESKTOP-LK5ITUQ`). You can fix this either by getting a certificate specific for your server (you can get free ones from https://letsencrypt.org/) or by setting up your custom hostname verifier for your AndroidMessageHandler (see https://github.com/dotnet/maui/discussions/8131, https://gist.github.com/Eilon/49e3c5216abfa3eba81e453d45cba2d4). Let me know if this helps you or if you have more questions.

**Comment by simonrozsival** [comment]
I think the difference between the Xamarin Forms and MAUI you're seeing is because the `HttpClientHandler` has different behavior on those two platforms by default (managed impl. in Xamarin Forms and native android handler in MAUI). 

If you want to use the managed implementation in MAUI, where the validation callback behaves as you were used to, you can add `<UseNativeHttpHandler>false</UseNativeHttpHandler>` to your csproj file.

Does this resolve the problem, @IgorKravchenko10?

**Comment by IgorKravchenko10** [comment]
Hi. Thank you for response.
If I use `HttpClientHandler` and <UseNativeHttpHandler>false</UseNativeHttpHandler> I get `Exception of type 'Interop+AndroidCrypto+SslException' was thrown.`
If I use `HttpClientHandler` <UseNativeHttpHandler>true</UseNativeHttpHandler> I get `hostname not verified`.
If I use `Xamarin.Android.Net.AndroidMessageHandler` and <UseNativeHttpHandler>false</UseNativeHttpHandler> I get `hostname not verified`.
If I use `Xamarin.Android.Net.AndroidMessageHandler` and <UseNativeHttpHandler>true</UseNativeHttpHandler> I get `hostname not verified`.

So, adding `<UseNativeHttpHandler>false</UseNativeHttpHandler>` changes nothing (placed in first PropertyGroup node). 
```
<PropertyGroup>
		<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net6.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net6.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>ServiceTest</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseNativeHttpHandler>false</UseNativeHttpHandler>
		<!-- Display name -->
		<ApplicationTitle>ServiceTest</ApplicationTitle>
		<!-- App Identifier -->
		<ApplicationId>com.companyname.servicetest</ApplicationId>
		<ApplicationIdGuid>1A0C5EF4-713E-4C12-B3F1-49E83BDC0D75</ApplicationIdGuid>
		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>		
	</PropertyGroup>
```

In **Xamarin.Forms** I use HttpClientHandler and **it works with both** of managed or android client implementations.

```
protected virtual HttpClientHandler CreateHttpClientHandler()
        {
            var handler = new HttpClientHandler
            {
                ClientCertificateOptions = ClientCertificateOption.Manual,
                ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) => true
            };
            return handler;
        }
```

I have tried [DevHttpsConnectionHelper.cs](https://gist.github.com/Eilon/49e3c5216abfa3eba81e453d45cba2d4#file-devhttpsconnectionhelper-cs) and connection was **successful** using both `<UseNativeHttpHandler>false</UseNativeHttpHandler>` and `<UseNativeHttpHandler>true</UseNativeHttpHandler>`

```
private sealed class CustomHostnameVerifier : Java.Lang.Object, Javax.Net.Ssl.IHostnameVerifier
            {
                public bool Verify(string hostname, Javax.Net.Ssl.ISSLSession session)
                {
                    bool virified = Javax.Net.Ssl.HttpsURLConnection.DefaultHostnameVerifier.Verify(hostname, session)
                        || hostname == "tcu.base2base.com.ua" && session.PeerPrincipal?.Name == "CN=DESKTOP-LK5ITUQ";
                    return virified;
                }
            }
```
But this is painful approach because our api exchange implementation is placed in separate project to use it for other applications. And we don't want to have links on specialized things like Java.Lang.Object, Javax.Net.Ssl.IHostnameVerifier, etc.
My question is why MAUI needs this verification `hostname == "tcu.base2base.com.ua" && session.PeerPrincipal?.Name == "CN=DESKTOP-LK5ITUQ"` when Xamarin.Forms doesn't need this?
Thanks.

**Comment by IgorKravchenko10** [comment]
Is this fix already in .NET 7?
Because I have updated my MAUI project to .NET 7 but still have this issue.
![image](https://user-images.githubusercontent.com/8657879/192045584-8f709cb1-da1d-439a-bd20-473a4068fa42.png)
