### ISSUE TITLE
Make `$(AndroidLinkResources)` able to be the default for MAUI projects

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#7194]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 7

### Description

Context: https://github.com/dotnet/maui/pull/7038

We found some Telerik and/or other vendor libraries would fail due to this code in SkiaSharp:

https://github.com/mono/SkiaSharp/blob/4a687a87b86f127ccc23116ee410dcb5df8fca63/source/SkiaSharp.Views/SkiaSharp.Views.Android/SKCanvasView.cs#L48-L61

So *if* we don't finish #6427 for .NET 7, we could consider:
1. Fix `SKCanvasView` so it doesn't use a `Styleable int[]`.
2. Give an error message at build time if the `AndroidLinkResources` linker step encounters a `int[]`
3. Try turning on `AndroidLinkResources=true` by default for MAUI projects

### Steps to Reproduce

1. Use `SKCanvasView` in a project
2. Build with `-c Release -p:AndroidLinkResources=true`

### Did you find any workaround?

Don't use `$(AndroidLinkResources)`

**Comment by tipa** [comment]
I was hitting the same problem today (not using a 3rd party library) when subclassing a View and using `ObtainStyledAttributes`.
Attached a simple repo project: [AndroidApp2.zip](https://github.com/xamarin/xamarin-android/files/9302722/AndroidApp2.zip)
 
Would appreciate if a fix could be found

**Comment by jonathanpeppers** [comment]
@tipa can you share the error message you got? Probably a crash at runtime?

**Comment by tipa** [comment]
With the demo project attached I first get this exception (only when enabling all exceptions in the VS Exception Settings Window):
`System.BadImageFormatException: 'Could not resolve field token 0x0400000b'
`

When I then click "Continue" in the debugger I get this exception:
`System.NotSupportedException: 'Could not activate JNI Handle 0x7fe1003920 (key_handle 0x73cc609) of Java type 'crc641149b9fe658fbe8e/MyView' as managed type 'AndroidApp2.MyView'.'
`

They are crashes at runtime, yes
