### ISSUE TITLE
Deploy to device fails with apksigner.jar AccessDeniedException

### ISSUE THREAD

**Issue by mgierlasinski** [xamarin/xamarin-android#7202]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.2.6

### Description

I cannot deploy to device because signing with apksigner.jar fails with following exception:

```
Exception in thread "main" java.nio.file.AccessDeniedException: bin\Debug\my.application-Signed.apk
```

(see log for more info)

I have VS 2022 17.2.6 and 17.3 Preview 4 installed. It started to happen in VS17.2 after upgrading VS17.3 from Preview 3 to Preview 4, not sure if this is related. It affects only one project I have, Android app created with File->New can be deployed with no issues. I wasn't able to reproduce in other project, I cannot send the one that is effected.

File my.application-Signed.apk is created on disk but it's not signed, any further attempt to deploy fails with:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		ADB0010: Mono.AndroidTools.InstallFailedException: The package was not properly signed (NO_CERTIFICATES).
   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Internal/AdbOutputParsing.cs:line 345
 ```

### Steps to Reproduce

1. Open solution.
2. Start debugging on device. 

### Did you find any workaround?

Running apksigner.jar from command line with parameters copied from VS output creates valid, signed apk.

### Relevant log output

```shell
C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.3\zipalign.exe -p 4 "obj\Debug\100\android\bin\my.application.apk" "bin\Debug\\my.application-Signed.apk" 
C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe -jar "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\apksigner.jar" sign --ks "C:\Users\username\AppData\Local\Xamarin\Mono for Android\debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 21 --max-sdk-version 29  bin\Debug\my.application-Signed.apk 
Exception in thread "main" java.nio.file.AccessDeniedException: bin\Debug\my.application-Signed.apk
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:384)
at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
at java.base/java.nio.file.Files.move(Files.java:1422)
at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:352)
at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
MSB6006: "java.exe" exited with code 1.
```

**Comment by jonathanpeppers** [comment]
This error sounds like another process has the file open:
```
Exception in thread "main" java.nio.file.AccessDeniedException: bin\Debug\my.application-Signed.apk
```
Have you tried a reboot?

**Comment by mgierlasinski** [comment]
@jonathanpeppers Yes, I have tried to reboot, remove bin/obj, I've downloaded fresh copy of the project from git repo. It seems that apksigner is having trouble to access this file only when launched from VS, running from command line works normal. Maybe this is something related:
```
https://bugs.openjdk.org/browse/JDK-8252883?attachmentOrder=asc
```

**Comment by jonathanpeppers** [comment]
Have you been able to find which process is locking the file?

There is a Sysinternals tool that can figure this out, for example:

https://www.mysysadmintips.com/windows/clients/593-find-what-is-locking-a-file-using-sysinternals-process-explorer

**Comment by mgierlasinski** [comment]
I did more tests and apksigner.jar is failing also in cmd if I run zipalign.exe just before, in a single run like VS does. Normally Sysinternals doesn't show anything but if run it just before zipalign.exe, CynetMS.exe is shown on the list. 

So it looks like this:
- zipalign.exe creates -Signed.apk
- CynetMS.exe wants to check/scan this new file (?)
- apksigner.jar is run in parallel but cannot access -Signed.apk because it's temporary locked by CynetMS

CynetMS was recently installed by our admins but didn't cause any issues so far. I need to take a look on this.

**Comment by jonathanpeppers** [comment]
Antivirus software has caused issues like this in the past. Let us know if that's the culprit, thanks!
