### ISSUE TITLE
Any news for Xamarin + Monodevelop linux ?

### ISSUE THREAD

**Issue by jhay06** [xamarin/xamarin-android#7206]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Ubuntu

### Description

Any news for Xamarin + monodevelop for linux ? 

jetbrains successfully integrated xamarin on their product Rider but currently there's no community edition for the product.

I'm just a hobbyist guy who likes coding so proprietary apps are not for me. 

so im still hoping for monodevelop and xamarin integration

i knew that vs mac was based on monodevelop so i think this is not impossible for linux also .

### Steps to Reproduce

N/a

### Did you find any workaround?

N/A

### Relevant log output

```shell
N/a
```

**Comment by jonpryor** [comment]
There are no plans to bring "Classic" Xamarin.Android to Linux.  You should be able to build the xamarin-android repo on Linux and use [`xabuild`](https://github.com/xamarin/xamarin-android/tree/main/tools/xabuild) to build Classic Xamarin.Android apps (f9d15dd203147382c9bdf6ffdf44fd9a87499992).

We have NuGet packages for Linux for .NET 6 SDK for Android, e.g. [Microsoft.Android.Sdk.Linux](https://www.nuget.org/packages/Microsoft.Android.Sdk.Linux), and the normal workload install command [should](https://discord.com/channels/732297728826277939/732297837953679412/1001888851545039000) [work](https://gist.github.com/grendello/f50b6f69b62fc1d61ab04e0aa0da2427) on .NET 6 on Linux:

```
sudo dotnet workload install android
```

This is not the appropriate forum for IDE questions.  I would suggest upvoting the [**Visual Studio for Linux** item on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-for-Linux/360479?space=8).
