### ISSUE TITLE
Add Fragment.OnCreateAnimation(int32, bool, int32) to the list that saves us from a `System.Reflection.Emit` call

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-android#7212]
### Android application type

.NET 7.0 MAUI
Android for .NET (net7.0-android)

### Affected platform version

.NET 7

### Description

I'm currently generating the AOT Profiles for non shell apps in .NET MAUI

There's one place where it's currently falling back to `System.Reflection.Emit`

https://github.com/dotnet/maui/blob/0062faeba1dd391b1468798cd29299403b9b67f0/src/Core/src/Platform/Android/Navigation/NavigationViewFragment.cs#L88

```bash
2022-07-25 11:25:06.254 14932-14932/? D/monodroid-assembly: Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPIZI_L': IntPtr n_OnCreateAnimation_IZI(IntPtr, IntPtr, Int32, Boolean, Int32)
```

We only need these changes for NET7 

### Steps to Reproduce

If you run the following project [ShellVsNonShell.zip](https://github.com/xamarin/xamarin-android/files/9203635/ShellVsNonShell.zip)

with the following logging enabled then you should see it popup in logcat

```bash
adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
```

You might also see one around `OnPageScrolled` that's ok to ignore. We have a fix in the MAUI repository to remove this code path. 

### Relevant log output

```shell
2022-07-25 11:25:06.254 14932-14932/? D/monodroid-assembly: Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPIZI_L': IntPtr n_OnCreateAnimation_IZI(IntPtr, IntPtr, Int32, Boolean, Int32)
```
```

**Comment by jonpryor** [comment]
@PureWeen: We can't add *all* possible method signatures (there are hundreds in `Mono.Android.dll` alone), so the question is: where do we draw the line?

The current "line" is "used by our default templates", specifically all `android` and `maui` templates.

It sounds like this signature isn't used by the current default templates.  As such, I am inclined to skip this signature.

In .NET 8, this should be moot, as we should be using LLVM Marshal Methods (e1af9587bb98d4c249bbc392ceccc2b53ffff155), which avoids the need for `System.Reflection.Emit` wrappers at runtime.

**Comment by PureWeen** [comment]
@jonpryor  This signature is used on `MAUI` for users that don't use `Shell` for their default experience so it'll be a fairly common scenario for users migrating over from XF to `MAUI`

This is the only addition that would be a nice to have for NET7

**Comment by jonathanpeppers** [comment]
Is there a non-Shell template? Do we have an idea how many opt into this?

**Comment by PureWeen** [comment]
@jonathanpeppers as far as I know we don't have a way to extract data that indicates the type of elements/controls that users use.  

The updates I made last time for our AOT profile represent the two possible page structures that users go with when building a MAUI/XF app https://github.com/dotnet/maui/pull/8941.  This particular method will get invoked for any scenario where a user uses a `NavigatePage`.   I don't completely know the impact of adding this case currently so I'd say

- If I promise to not ask for anymore additions for NET7 and it's easy enough to just add this one then can we? :-) 
- If adding this is going to cause a windfall of issues that results in a lot of extra work in order for us to stay below the APK sizes we want to stay below then we can just ignore since it's irrelevant in NET8. 

My hope for NET8 is that both shell/non shell follow all the same platform paths as well.

**Comment by jonathanpeppers** [comment]
So this is in the AOT profile here:

https://github.com/dotnet/maui/blob/64a5a588a8c4c1413f43bb41ba488214abb96d25/.nuspec/maui.aotprofile.txt#L7107-L7113

Introduced in: https://github.com/dotnet/maui/commit/15df4ed8fc8a8f84b090b1afae08303d847c481f

We should probably just fix this one, and maybe it's the last one for .NET 7? Unless a new one pops up in the templates or .NET Podcast app.
