### ISSUE TITLE
Android Items Template is missing for .Net Android project

### ISSUE THREAD

**Issue by hamiddd1980** [xamarin/xamarin-android#7231]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

Android 6, Android 9

### Description

Currently in **.Net Android** project, the template for Android specific items(files) like _Activity,Layout,Menu_ …is missing from menu : **Resource Folder>Add>New Item**.
These items are available in Xamarin.Android , but are not implemented in new **.Net Android**.
Without Android Items Template in **.Net Android**, it’s so difficult to develop Android Apps in VS.
Request:
Please add Android Files Templates (Like Activity,Layout,…) to .Net Android projects like Xamarin.Android.

### Steps to Reproduce

1-Create a new **.Net Android project**
2-Try to add a new **Android item(file)** like Layout,Activity... to the project by right click on project items.

**Comment by dellis1972** [comment]
Hmm, our template pack for .net 6 does include Activity and Layout Item Templates. Namely android-activity and android-layout (see https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates). 

So I wonder why they do not show up in the IDE. 

@tondat are you aware of any issues with Item Templates not showing up in Visual Studio?

**Comment by hamiddd1980** [comment]
Hi **dellis1972** . is it possible that I add .Net Android templates to Visual Studio manually? (where should I copy those files?)
Thank you.

**Comment by jonathanpeppers** [comment]
You should be able to use `dotnet new android` and then just open the template in Visual Studio.

https://docs.microsoft.com/dotnet/core/tools/dotnet-new

**Comment by dellis1972** [comment]
@jonathanpeppers its the Item Templates they are after, not a new project one. 

I'm not sure how to go about getting those to show up in VS.

**Comment by jonathanpeppers** [comment]
Ah yes, the item template should also work:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNet.md#dotnet-new

So like:

    dotnet new android-activity --name LoginActivity --namespace MyAndroidApp

**Comment by hamiddd1980** [comment]
but I'm looking for .Net Android specific templates(layout,Activity ...) 
![androidmissing](https://user-images.githubusercontent.com/57061231/183955255-05a66183-8f26-41f5-b3e3-aa2587fcd58a.png)
