### ISSUE TITLE
Can Not Debug Xamarin.Android Application on a Real Device With Error Forwarding debugger port

### ISSUE THREAD

**Issue by hamiddd1980** [xamarin/xamarin-android#7232]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Android 9.0

### Description

After updating to **VS Version 17.3.0 Preview 6.0**, it's not possible to **debug Xamarin.Android** (and also MAUI) on a real device: the App is installed on the real device but the debug process doesn't start.
the  following error is reported:
```
Forwarding debugger port 8873
Failed to launch android application
```
it is noticeable that the **Debug works well in Android Emulator in VS**.
also in  Android Studio, **the Debug process starts successfully  with Real Device**. 
(I have uninstalled all of previous Xamarin.Android from my phone)

### Steps to Reproduce

1.create a new Xamarin.Android Project
2.try to start Debugging the App on a real device (phone)

**Comment by grendello** [comment]
@tondat since I don't know how to deal with VS bugs reported here, would you mind moving/copying this issue to wherever VS team wants it to be? Thanks! :)

**Comment by dellis1972** [comment]
The error might not be related to the debugger port. What we will need is the diagnosic log output in order to investigate what might actually be causing the issue. 

See https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting for details on how to turn on diagnstic logging.

**Comment by hamiddd1980** [comment]
Thanks for reply. after trying different things , finally the problem was solved by repairing VS.
