### ISSUE TITLE
BroadcastReceiver with targetSdkVersion="31" causes java.exe exited with code 1

### ISSUE THREAD

**Issue by NebulaSleuth** [xamarin/xamarin-android#7250]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022

### Description

Placing this class in a Xamarin.Android app that targets sdk 31 (Android 12) and compiles with Android 12 causes a build error 
java.exe exited with code 1

```
    [BroadcastReceiver]
    [IntentFilter(new[] { Android.Content.Intent.ActionBatteryChanged })]
    public class MyReceiver : BroadcastReceiver
    {

        public override void OnReceive(Context context, Intent intent)
        {
        }
    }
```
Including example project
[XamApp1.zip](https://github.com/xamarin/xamarin-android/files/9309213/XamApp1.zip)

### Steps to Reproduce

1. Create standard Xamarin.Android app using VS2022
2. Add the Broadcast reciever
3. Make sure your android:targetSdkVersion="31" in AndroidManifest.xml
4. Make sure the Compile Using Android Version: (Target Framework) setting is set to Android 12 (S)
5. Compile Debug->AnyCPU

### Did you find any workaround?

Target Android 11 or below

**Comment by dellis1972** [comment]
@NebulaSleuth In order to get this to compile, I had to use JDK-11. To target API-31 you need to use JDK-11 rather than JDK-8. Check that you have the correct Java Sdk setup in the IDE. It might be picking up the wrong one. 

See as I cannot repo exactly, it would be helpful if you could provide a diagnostic build log of the error you are seeing.

**Comment by NebulaSleuth** [comment]
[buildlog.txt](https://github.com/xamarin/xamarin-android/files/9309584/buildlog.txt)

**Comment by dellis1972** [comment]
`android:exported needs to be explicitly specified for element <receiver#crc6460ea81dbc58b223f.MyReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. `

With android 12 you need to use `[BroadcastReceiver(Exported=true)]` now.

**Comment by NebulaSleuth** [comment]
Doh!!  That was it.  Thanks for the help.  You can close this, hopefully it helps someone in the future.
