### ISSUE TITLE
[illink] Turn on serialization discovery in .NET 7

### ISSUE THREAD

**Issue by sbomer** [xamarin/xamarin-android#7256]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 7 (rc1 SDK)

### Description

https://github.com/dotnet/linker/pull/2929 made serialization heuristics opt-in. To preserve the .NET 6 behavior, the Xamarin SDK should opt in to the old behavior by setting `<_ExtraTrimmerArgs>--enable-serialization-discovery</_ExtraTrimmerArgs>`. This can be done once using an SDK with https://github.com/dotnet/sdk/pull/26993 (which will be part of rc1).

### Steps to Reproduce

n/a

**Comment by jonpryor** [comment]
Fixed via #7255.
