### ISSUE TITLE
System.Text.Json

### ISSUE THREAD

**Issue by finflaex** [xamarin/xamarin-android#7281]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Ubuntu 22.04 / .NET 6.0

### Description

![изображение](https://user-images.githubusercontent.com/13582750/185415709-abe3fb4e-4f06-48ba-96e4-821ab7f7a418.png)

### Steps to Reproduce

git clone https://github.com/xamarin/xamarin-android
cd xamarin-android/
./build.sh Build

### Relevant log output

```shell
"/home/fx/xamarin/test/xamarin-android/tools/xabuild/xabuild.csproj" (целевой объект по умолчанию) (1:7) ->
"/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj" (целевой объект по умолчанию) (2:6) ->
(Целевой объект GenerateBuildDependencyFile) -> 
  /usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: непредвиденная ошибка при выполнении задачи "GenerateDepsFile". [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: File name: 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:   at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile (System.String depsFilePath) [0x00281] in <e31e40ddf21843738daea259b4f6a4ad>:0  [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:   at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore () [0x00007] in <e31e40ddf21843738daea259b4f6a4ad>:0  [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:   at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x0002e] in <e31e40ddf21843738daea259b4f6a4ad>:0  [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:   at Microsoft.NET.Build.Tasks.TaskWithAssemblyResolveHooks.Execute () [0x00016] in <e31e40ddf21843738daea259b4f6a4ad>:0  [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /build/msbuild-16.10.1+xamarinxplat.2021.05.26.14.00/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:578  [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /build/msbuild-16.10.1+xamarinxplat.2021.05.26.14.00/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:807  [/home/fx/xamarin/test/xamarin-android/tools/vswhere/vswhere.csproj]
```

**Comment by finflaex** [comment]
> Did you run `./build.sh Prepare` first?

yes

**Comment by dellis1972** [comment]
do a `git clean -xfd` and then try running `make prepare` manually. 
If that works then try `make`.

**Comment by jonathanpeppers** [comment]
It might be easiest to make `vswhere.csproj` not build at all on Linux, since that is a tool for finding Visual Studio on Windows. If that works for you, can you send a PR for it? Thanks!

**Comment by finflaex** [comment]
> @finflaex: Какой это дистрибутив Linux?
cat /etc/lsb-release && uname -r
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
5.19.1-051901-generic

**Comment by finflaex** [comment]
> Это может быть проще всего сделать `vswhere.csproj`вообще не строить в Linux, так как это инструмент для поиска Visual Studio в Windows. Если это сработает для вас, можете ли вы отправить PR для этого? Спасибо!

can you tell me how to do it right?

**Comment by grendello** [comment]
@finflaex I build XA daily on Debian/sid, it should build just fine on Ubuntu 22.04 as well. However, I noticed that you have a very old version of dotnet6 installed (6.0.108) - why don't you try updating it to the latest version (6.0.400 - this is what I have installed)?

**Comment by finflaex** [comment]
> 

dotnet-sdk-6.0/jammy-updates,now 6.0.108-0ubuntu1~22.04.1 amd64 [установлен]
  dotNET 6.0 Software Development Kit
- this is the latest version in the ubuntu repository

**Comment by grendello** [comment]
@finflaex it might be a good idea to use Microsft repo for this... This is grossly out of date

**Comment by finflaex** [comment]
>  it might be a good idea to use Microsft repo for this... This is grossly out of date

just the other day I left it - this caused a problem - I stopped showing the SDK in the list (dotnet --list-sdks)

**Comment by grendello** [comment]
It appears to work here:

```shell
$ dotnet --list-sdks
5.0.408 [/usr/share/dotnet/sdk]
6.0.400 [/usr/share/dotnet/sdk]
```

Maybe purging all dotnet from your system and reinstalling from the Microsoft repo helps?

**Comment by finflaex** [comment]
> It appears to work here:
> 
> ```shell
> $ dotnet --list-sdks
> 5.0.408 [/usr/share/dotnet/sdk]
> 6.0.400 [/usr/share/dotnet/sdk]
> ```
> 
> Maybe purging all dotnet from your system and reinstalling from the Microsoft repo helps?

wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0
dotnet --list-sdks
... empty

**Comment by grendello** [comment]
@finflaex that's reinstallation without previous purging - remove all the traces of dotnet from the system first (`~/.dotnet`, the `/usr/{share,lib,bin}` locations etc)

**Comment by finflaex** [comment]
> @finflaex that's reinstallation without previous purging - remove all the traces of dotnet from the system first (`~/.dotnet`, the `/usr/{share,lib,bin}` locations etc)

![image](https://user-images.githubusercontent.com/13582750/185447298-47ba244c-dee6-4613-bd2d-d0ac390f9262.png)

what else should I clean ...

**Comment by finflaex** [comment]
it just seems to me that this glitch is due to the fact that these packages have the same name in different repositories and it's easier for me to get rid of the microsoft repository than ubuntu

**Comment by finflaex** [comment]
![image](https://user-images.githubusercontent.com/13582750/185453913-dd98d42a-092d-44ea-85ec-bf9e82e76908.png)

nevertheless, it helped solve my problem, it remains to wait for the ubuntu repository update ...
thank you very much for your help
