### ISSUE TITLE
ByteBuffer.Array is Not Exposed

### ISSUE THREAD

**Issue by hamiddd1980** [xamarin/xamarin-android#7282]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 Version 17.4.0 Preview 1.0

### Description

The `Array()` method is missing from **ByteBuffer** class when using it in `ImageAnalysis.IAnalyzer`

### Steps to Reproduce

1. create a subclass of ImageAnalysis.IAnalyzer
2. implement `public void Analyze(IImageProxy imageProxy)`
```
public void Analyze(IImageProxy imageProxy)
{
       ByteBuffer byteBuffer=plane.Buffer;
       byte[] buffer=byteBuffer.Array();//Not Exists
}
```
4. The `Array()` method is missing from **ByteBuffer** class

**Comment by jpobst** [comment]
There is some explanation and a workaround here:
https://github.com/xamarin/xamarin-android/issues/5347
