### ISSUE TITLE
Task "GenerateLibraryResources" throwing error : Root element is missing

### ISSUE THREAD

**Issue by Kapusch** [xamarin/xamarin-android#7287]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VSMac 17.3.1, .NET 6.0.5 (64-bit), Xamarin.Android 13.0.0.0

### Description

Hello, I am unable to debug and fix the issue I encounter when building [Plugin.Firebase](https://github.com/TobiasBuchholz/Plugin.Firebase) on VSMac.

As the author of the library does not encounter any build issue, I have tried to reinstall its repository, clean my NuGet cache, delete all temp objects, [uninstalled / reinstalled all my dev setup on my Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2022), installed another IDE... but still I'm getting the exact same error when building the project:
```
Task "GenerateLibraryResources"
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error : Root element is missing.
      [...]
      Done executing task "GenerateLibraryResources" -- FAILED.
```
Full diagnostic logs : [msbuild_logs.txt](https://github.com/xamarin/xamarin-android/files/9385620/msbuild_logs.txt)

Could you please help me to understand what is causing the issue ?
Any guidance to fix it is welcome, thanks in advance !

### Steps to Reproduce

1. Download the library: [Plugin.Firebase](https://github.com/TobiasBuchholz/Plugin.Firebase)
2. Build the project: Plugin.Firebase.csproj
3. See the "Root element is missing" error logged in Build Output

### Relevant log output

```shell
Using "GenerateLibraryResources" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Build.Tasks.dll".
      Task "GenerateLibraryResources"
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error : Root element is missing.
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x00027] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlTextReaderImpl.cs:2503 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlTextReaderImpl.cs:2511 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0035d] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlTextReaderImpl.cs:3742 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at System.Xml.XmlTextReaderImpl.Read () [0x0008c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlTextReaderImpl.cs:1168 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at System.Xml.Linq.XDocument.Load (System.Xml.XmlReader reader, System.Xml.Linq.LoadOptions options) [0x00016] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Private.Xml.Linq/src/System/Xml/Linq/XDocument.cs:427 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at System.Xml.Linq.XDocument.Load (System.String uri, System.Xml.Linq.LoadOptions options) [0x0000f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Private.Xml.Linq/src/System/Xml/Linq/XDocument.cs:222 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at System.Xml.Linq.XDocument.Load (System.String uri) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Private.Xml.Linq/src/System/Xml/Linq/XDocument.cs:190 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at Xamarin.Android.Tools.AndroidAppManifest.Load (System.String filename, Xamarin.Android.Tools.AndroidVersions versions) [0x0001c] in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs:86 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1245,2): error :   at Xamarin.Android.Tasks.GenerateLibraryResources.RunTaskAsync () [0x00120] in <7a79b94231674f8abef431c7441b514f>:0 
      Done executing task "GenerateLibraryResources" -- FAILED.
```

**Comment by dellis1972** [comment]
I can't repo locally.

If you are not making use a the Resource.Designer.cs file in the code base (which I don't think you are) you can completely disable the generation of the designer file. By setting the following property in the csproj.

` <AndroidGenerateResourceDesigner>false</AndroidGenerateResourceDesigner>`

This will stop aapt2 and the `GenerateLibraryResources` from even running. I don't think you need it since this plugin does not reference any resources with the exception of `global::Android.Resource.Drawable.SymDefAppIcon` which seems to be coming from the global `Android.Resource` namespace. so that must be in the Mono.Android assembly I guess.

**Comment by Kapusch** [comment]
Hi Dellis, thank you very much for your quick return !

If I understood well, your suggestion would indeed make sense... But I gave a try and `GenerateLibraryResources` is still launched in the build, along with `Aapt2Link`.

I can see you were not able to reproduce issue, which means I'm really the only one blocked with that 😄

**Comment by Kapusch** [comment]
Hi @dellis1972 , I have finally been able to resolve the build issue by updating reference to the `Xamarin.GooglePlayServices.Auth` library from [119.2.0.3](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Auth/119.2.0.3) to [v120.2.0.2](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Auth/120.2.0.2)
