### ISSUE TITLE
Templates need to provide ide.host.json files

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#7315]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 17.4

### Description

Context: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-contentview-xaml/.template.config/ide.host.json

The `.template.config/ide.host.json` file is used by Visual Studio to control where in the File > New > New File and File > New > New Project dialogs a given template is shown.

For example, with [File > New > New Project](https://docs.microsoft.com/en-us/visualstudio/ide/create-new-project?view=vs-2022), you can select **All project types** and set the type to `MAUI`.  After doing so, three projects are shown:

  * ".NET MAUI App":
    * https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/.template.config/ide.host.json
    * https://github.com/dotnet/maui/blob/f2ae851de7c070408c0fc0d85923a6ec075924b7/src/Templates/src/templates/maui-mobile/.template.config/template.json#L8
  * ".NET MAUI Blazor App":
    * https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-blazor/.template.config/ide.host.json
    * https://github.com/dotnet/maui/blob/f2ae851de7c070408c0fc0d85923a6ec075924b7/src/Templates/src/templates/maui-blazor/.template.config/template.json#L8
  * ".NET MAUI Class Library":
    * https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-lib/.template.config/ide.host.json
    * https://github.com/dotnet/maui/blob/f2ae851de7c070408c0fc0d85923a6ec075924b7/src/Templates/src/templates/maui-lib/.template.config/template.json#L8

Similarly, if you have a .NET Maui project, and within the Solution Explorer you right-click the Project > Add > New Item…, in the Add New Item dialog, on the right you can select the node Installed > C# Items > .NET MAUI, which will show on the right e.g.

  * .NET MAUI ContentPage (C#)
    * https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-contentpage-csharp/.template.config/ide.host.json
    * https://github.com/dotnet/maui/blob/f2ae851de7c070408c0fc0d85923a6ec075924b7/src/Templates/src/templates/maui-contentpage-csharp/.template.config/template.json#L8

Update the .NET SDK for Android projects and items to contain a `.template.config/ide.host.json` files so that Visual Studio can appropriately sort & filter these projects and items.

**Comment by jonpryor** [comment]
.NET SDK for Android example:

Within Visual Studio, create a new .NET SDK for Android project (File > New > Project… , "Android Application", …).

Within the Solution Explorer, right-click *Project Name* > Add > New Item….  This displays the **Add New Item** dialog:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/155958/187287895-1fd4c5cd-f023-48d4-9691-7f2e9f93b34c.png">

Notice that there is no "Android" section in the leftmost tree.

Additionally, of the two item templates that we provide -- [android-activity](https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates/android-activity) and [android-layout](https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates/android-layout) -- *neither* are shown within the Add New Item dialog.

Compare to thew **Add New Items** dialog for a MAUI app, which has a ".NET MAUI" section:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/155958/187288685-60db81ef-b0b2-4ac7-b32c-a8d702763e82.png">

`ide.host.json` files are used to populate the the **Add New Items** dialog, controlling:

 1. The name of the leftmost tree-view node, via `itemHierarchyPaths`
 2. Whether or not the item is shown in the right panel, via `appliesTo`.

**Comment by mrward** [comment]
FYI `The .template.config/ide.host.json file is used by Visual Studio to control where in the File > New > New File and File > New > New Project dialogs a given template is shown.` this is only true for the New File dialog.

There is no currently defined mechanism for category mappings in VS Mac for project templates by using the ide.host.json file. Right now VS Mac is using the template classifications as a way to map to categories, and only MAUI is being mapped currently. VS Mac will allow full customisations here for project templates (requires a custom template description provider) where category, name and icons can be overridden. I am planning on adding something here as a starting point - so library projects can be mapped to the right category (instead of going in General).
