### ISSUE TITLE
 Fails build on Microsoft-openjdk@17

### ISSUE THREAD

**Issue by ss-proc** [xamarin/xamarin-android#7338]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

6.0.400

### Description

Building a brand new .NET 6 Xamarin app with Microsoft OpenJDK 17 fails.

I'm using Rider as my IDE and I already have the Microsoft-openjdk@17 (LTS) installed.

```
❯ java --version
openjdk 17.0.4.1 2022-08-12 LTS
OpenJDK Runtime Environment Microsoft-40354 (build 17.0.4.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-40354 (build 17.0.4.1+1-LTS, mixed mode)
```

But when I run a new app, I see this error:

```
  Microsoft.Android.Sdk.Tooling.targets(20, 5): 
[XA0030] Building with JDK version `17.0.4.1` is not supported. 
Please install JDK version `11.0`. See https://aka.ms/xamarin/jdk9-errors
```

Since Microsoft OpenJDK 17 LTS was released over 10 months ago and it is very stable, can you please consider adding support for new .NET 6 apps to be built using Microsoft OpenJDK 17 LTS?

### Steps to Reproduce

1. Install openjdk using https://docs.microsoft.com/en-ca/java/openjdk/install#install-on-macos
2. Install dotnet for macOS https://dotnet.microsoft.com/en-us/download/dotnet/6.0
3. File > New Xamarin APP
4. Build and run

### Did you find any workaround?

Temporary workaround - Install Microsoft OpenJDK 11

**Comment by dellis1972** [comment]
My understanding is that we are dependent on what version of the JDK the android sdk supports. @jonpryor is that correct?

**Comment by jonathanpeppers** [comment]
The latest Android Studio (Dolphin) is still using JDK 11 at this time. We generally can't move faster than Android, as random command-line tooling from the Android SDK tends to break. We shell out to tools like `apksigner`, `bundletool`, etc. that run under Java.

**Comment by jonathanpeppers** [comment]
Yeah, we will probably open a new Java 17 issue in some far away future, lol. Thanks!
