### ISSUE TITLE
`<FastDeploy/>` seems to reinstall `.apk` during incremental deploy

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#7368]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 6

### Description

I found this while looking into https://github.com/xamarin/xamarin-android/issues/7318 (initial deploy), which should be unrelated.

I noticed incremental deploys of a `dotnet new maui` app always seem to print:

```
Installing Package com.companyname.ggg
DEBUG RunShellCommand 0A041FDD400327 pm install -d "/data/local/tmp/com.companyname.ggg-Signed.apk". [142ms]
DEBUG RunShellCommand 0A041FDD400327 rm "/data/local/tmp/com.companyname.ggg-Signed.apk". [1103ms]
```
My code change was a `Console.WriteLine()` statement.

This makes me think it is reinstalling the `.apk` when it shouldn't be?

### Steps to Reproduce

1. Create a MAUI app in VS
2. Deploy
3. Make a small C# change
4. Deploy

### Did you find any workaround?

no

### Relevant log output
[ggg_Debug_AnyCPU_Build_2022-09-12T15_21_38.7064411-05_00.binlog.zip](https://github.com/xamarin/xamarin-android/files/9551646/ggg_Debug_AnyCPU_Build_2022-09-12T15_21_38.7064411-05_00.binlog.zip)

**Comment by dellis1972** [comment]
@jonathanpeppers do you have the build log for the previous build? What I suspect is happening is something in the previous build is triggering the full packaging. The log attached is for the Install target.

that said it does have a hint to the problem.

```
Building target "_GenerateAndroidResourceDir" completely.
                   Input file "C:\src\ggg\ggg.csproj" is newer than output file "obj\Debug\net6.0-android\res.flag".
```

That means the csproj was modified which will trigger a full rebuild of everything. So the question is why is the csproj changing?

**Comment by jonathanpeppers** [comment]
It is now ~4:10PM, but both files seem to be old:
```
> (ls ggg.csproj).LastWriteTime
Monday, September 12, 2022 3:20:51 PM

> (ls .\obj\Debug\net6.0-android\res.flag).LastWriteTime
Monday, September 12, 2022 2:50:29 PM
```
I think they are *both* old, but the `.csproj` file happens be newer than `res.flag`.

**Comment by jonathanpeppers** [comment]
If I delete bin/obj, and try again this message changes:
```
Skipping target "_GenerateAndroidResourceDir" because all output files are up-to-date with respect to the input files.
```
But then it still does this when I only made a C# change:
```
DEBUG RunShellCommand 0A041FDD400327 pm install -d "/data/local/tmp/com.companyname.ggg-Signed.apk". [154ms]
DEBUG RunShellCommand 0A041FDD400327 rm "/data/local/tmp/com.companyname.ggg-Signed.apk". [954ms]
```
