### ISSUE TITLE
Is Xamarin support CarPlay app ?

### ISSUE THREAD

**Issue by XamarinRPMTeam** [xamarin/xamarin-android#7398]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

Xamarin

### Description

Team , This is to ask you about the CarPlay Support in Xamarin . Is Xamarin Support CarPlay? .If yes Could you please get the official documentation on how to do it . We found one and only sample which is music app . Our requirement is to develop a business app which is very much required to do .

### Steps to Reproduce

Team , This is to ask you about the CarPlay Support in Xamarin . Is Xamarin Support CarPlay? .If yes Could you please get the official documentation on how to do it . We found one and only sample which is music app . Our requirement is to develop a business app which is very much required to do .

**Comment by jpobst** [comment]
Are you referring to Apple CarPlay?  If so, I can redirect this to the iOS repository so they can address this.

Or are you referring to Android Auto?
