### ISSUE TITLE
Xamarin.Android app fails to run when built on hosted MacOS 12 in Azure DevOps

### ISSUE THREAD

**Issue by djanders77** [xamarin/xamarin-android#7400]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

11, 12

### Description

We have a Xamarin app that we build and release via Azure DevOps and App Center. Recently, We started getting this error when building the Android app on MacOS-11:

error XA5104: Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path.###

According this this [thread](https://github.com/xamarin/xamarin-android/issues/7233), the best fix was to start using MacOS-12 as the build agent. This technically fixed the problem and the app built successfully,. but when the app is installed on a device it will not run. The app appears to start up, but quits and can be seen running in the background of the device, Attempting to switch to it causes it to immediately close out. Even stranger, the app runs fine when built from our developer’s local machine, which is also running MacOS-12.

I am currently using the Xamarin.Android task to build the app, but I have tried building it with the MSBuild task as well with the same results.

### Steps to Reproduce

1. Use Azure DevOps hosted MacOS-12 agent to build and release Xamanarin.Android app
2. Download the .apk, install app on an Android device, and run the app.

### Did you find any workaround?

Build/sign the app from the developers' machine, then release via App Center

**Comment by jonathanpeppers** [comment]
I think we need a log from `adb logcat` to know where the problem is.

Can you set a system property to enable more logging:

    adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all

Then cause the crash, and save the log via `adb logcat -d > log.txt` and share it here. Thanks!

More details here: https://learn.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log#accessing-from-the-command-line
