### ISSUE TITLE
Missing [Flags] for Android.Nfc.NfcReaderFlags

### ISSUE THREAD

**Issue by rgroenewoudt** [xamarin/xamarin-android#7409]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS2022 17.3.4

### Description

The enum `Android.Nfc.NfcReaderFlags` is missing the `FlagsAttribute`.

When using methods like `Android.Nfc.NfcAdapter.EnableReaderMode()` you will get the warning "Bitwise operation on enum is not marked by [Flags] attribute"
  

### Steps to Reproduce

N/A

**Comment by jpobst** [comment]
Thanks for the report!  Should be backported to .NET 7 and classic XA 13.1.
