### ISSUE TITLE
AppCompatDelegate.SetApplicationLocales() and AppCompatDelegate.GetApplicationLocales() missing

### ISSUE THREAD

**Issue by PaulTaro** [xamarin/xamarin-android#7432]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

MonoAndroid V12

### Description

Android V13 provides new possibilities and API to change the application language. My app must be able to get and set the app language with AppCompatDelegate.GetApplicationLocales and AppCompatDelegate.SetApplicationLocales before base.OnCreate(). Unfortunally, these methods are not provided by MonoAndroid V12.

### Steps to Reproduce

1. Create an app with Android V13.
2. Try the find those members in AppCompatDelegate.

### Did you find any workaround?

Currently, my app is using activity.Resources.UpdateConfiguration(config, null); but this method is deprecated. I must synchronize the app locales stored internal with the app locales stored by Android. This is impossible currently.

**Comment by dellis1972** [comment]
@jpobst I think this one might be in the Mono.Android binding area? Please re-assign if its in the AndroidX Bindings

**Comment by PaulTaro** [comment]
I'am using AndroidX.AppCompat.App.AppCompatActivity.Delegate:
![GetApplicationLocales](https://user-images.githubusercontent.com/49974414/193588404-0cfce115-043e-441c-8878-bd5ada64ca26.png)

**Comment by jpobst** [comment]
It looks like this is in AndroidX, so moving the issue there.
