### ISSUE TITLE
Debug NET 6 Android apps at least 10 x Slower !

### ISSUE THREAD

**Issue by maiad** [xamarin/xamarin-android#7438]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

NET 6, Visual studio 2022

### Description

I converted my xamarin application to NET6 and found that it runs at least ten times slower ! I use SkiaSharp.Views for rendering and after the conversion the application is unusable !

It's possible to test it, just spin up two projects, one in old xamarin and the other in net6. Hang a simple loop on the button:

            Stopwatch sw = new Stopwatch();
            sw.Start();
            int cnt = 0;
            for (int f = 0; f < 100000000; f++)
                cnt++;
            long el = sw.ElapsedMilliseconds;

            label.Caption = $"Elapsed : {el}";

In xamarin on mobile about 120ms, in net6 about 3700ms.... This is for debug mode, in release it is a bit better, but still slow !

I'm afraid C# is not going in quite the right direction.

Translated with www.DeepL.com/Translator (free version)

### Steps to Reproduce

1 Create two projects. Xamatin and NET6 for Android.
2 Add button and label inside both of them with label.
3 Add this code to ONClick:

            Stopwatch sw = new Stopwatch();
            sw.Start();
            int cnt = 0;
            for (int f = 0; f < 100000000; f++)
                cnt++;
            long el = sw.ElapsedMilliseconds;
            label.Caption = $"Elapsed : {el}";

4 View results in debug and release on mobile device.

### Did you find any workaround?

When I tried to find a solution, I only found tons of bugs in visual studio 2022 (Try for example in the Android NET6 project properties to set the application icon in the Android section...)

**Comment by grendello** [comment]
Hi, what was the device you tested the tight loop on?

**Comment by grendello** [comment]
NET6+ apps built in `Debug` mode run with the **interpreter** (they are not JIT-ed), so that hot reload can work. Thus the difference in speed between `Debug` and `Release` in my test above, but as you can see, the `Release` build isn't slow by any means. Could you post numbers you get for old vs. new **Release** builds?

**Comment by jonathanpeppers** [comment]
> I can confirm that our app also is a lot slower when debugging on a physical device. Is there an option to disable hot reload and enable the JIT to get the old debug performance?

@rgroenewoudt yes, you should be able to put `<UseInterpreter>False</UseInterpreter>` in your project file, but this will obviously prevent C# hot reload from working.

**Comment by jonathanpeppers** [comment]
@maiad can you provide your original numbers in a Release build? Or at least turn off interpreter for your measurement, as Xamarin.Android apps would not have an interpreter (no hot reload support).
