### ISSUE TITLE
Interface is not generated in the Bindings Generator output code (.JAR Kotlin)

### ISSUE THREAD

**Issue by Sergtek** [xamarin/xamarin-android#7439]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.3.5

### Description

After updating a .JAR (created by my company) in an Android binding project, I am finding that an interface is no longer generated that in previous versions of the same .JAR if they were generated correctly. The .JAR is using Java and Kotlin and the Android binding project is using Android Class Parser jar2xml (it's a very old project that's why we don't use class-parse and currently we don't plan to update it as till today with jar2xml Everything has been working fine, we also tried to update to class-parse once and many errors were generated, so it is something that has been delayed in time).

Xamarin Bindings Generator output code ("**ScannerManager**" is the interface that is not being generated):
<img width="1112" alt="kotlinIssue2" src="https://user-images.githubusercontent.com/20904914/194268992-badeac82-54e4-40fb-84d0-0889c866e15a.png">

Here is an image with the changes that have occurred in that interface from one version to another:
<img width="1254" alt="kotlinIssue" src="https://user-images.githubusercontent.com/20904914/194264874-8db606c0-3819-4b57-9411-fa58b8b76e48.png">

You can see that only 2 new imports have been added:
```
import kotlin.Unit;
import kotlin.jvm.functions.Function1;
```

And a new method.

To test I have created a variable in MainActivity accessing the IScannerManager interface (which is not being generated with this new .JAR so it will throw an error, but with the old .JAR it was generated):
<img width="1331" alt="kotlinIssue3" src="https://user-images.githubusercontent.com/20904914/194274723-2d390703-bc56-43e0-979e-75a60fcc5652.png">

How could these seemingly trivial changes prevent Xamarin's Bindings Generator output code from generating that interface?

**In the following directory of the GitHub repository I have left the old .JAR that does generate the interface correctly:**
<img width="740" alt="kotlinIssue4" src="https://user-images.githubusercontent.com/20904914/194276915-a50d0e70-a89a-4832-a9d9-9673acfbb75d.png">

P.S. I am aware that jar2xml is deprecated but would appreciate any advice on this.

### Steps to Reproduce

https://github.com/nacompllo/KotlinBindingTest

1 - Clone the repository.
2 - Compile the solution.
3 - In the MainActivity class there is a variable called "test" which is trying to access a namespace of the .JAR but it is failing (however a previous version of the .JAR was accessing it without problem (in the description of the problem I show the differences between both .JAR).

### Relevant log output

1>JARTOXML : warning J2XA006: missing class error was raised while reflecting com.x.lfwkhwsc_sharedmod.interfaces.ScannerManager : kotlin/jvm/functions/Function1

**Comment by jpobst** [comment]
> How could these seemingly trivial changes prevent Xamarin's Bindings Generator output code from generating that interface?

This part is easy, the new method is using `Function1`:
```java
void isHardwareConnected(@NonNull Function1<? super Boolean, Unit> paramFunction1);
```

And your error message says there was an error trying to find the `Function1` type:
```
warning J2XA006: missing class error was raised while reflecting com.x.lfwkhwsc_sharedmod.interfaces.ScannerManager : kotlin/jvm/functions/Function1
```

_Why_ it can't find the type is the tricky part.  `jar2xml` uses Java reflection to access the types, so for some reason Java reflection cannot find the type.  

Unfortunately `jar2xml` was deprecated several years before I started, so I am not familiar with much beyond that.  Here is the code and where that error is coming from: https://github.com/xamarin/jar2xml/blob/4125da65cc69bd0f2b0be13e227676259ef63e03/JavaClass.java#L562-L565

It looks like it should be printing out a stack trace before the warning line (you will likely need to have a [diagnostic build log](https://learn.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)).  Hopefully that will give you a pointer to the issue.
