### ISSUE TITLE
Xamarin.Android project build fails after upgrading to Visual Studio 17.3.5 (from 17.2.5) due to missing .dll in AOT folder and aapt_rules.txt

### ISSUE THREAD

**Issue by vilinet** [xamarin/xamarin-android#7447]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 17.3.5

### Description

Not a single change in our project or CI script, just VS got update to the currently latest one and we experience 2 strange and blocker side-effect during AOT apk build, that can be strangely workaround if we get rid of those packages, but still nothing change on our side at all aside the VS update:

First:
It looks like some .dll is not getting copied/generated into the target folder anymore like Humanizer or PublicHoliday give us this error at the very end of the AOT process when it tries to zip the aot files into a zip:
`"X.Android.csproj" (SignAndroidPackage target) (1) ->
(_BuildApkEmbed target) -> 
  C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3): error XABLD7028: Sy
[MissingDllDuringAOT.zip](https://github.com/xamarin/xamarin-android/files/9745881/MissingDllDuringAOT.zip)
stem.IO.FileNotFoundException: Could not find file 'X.Android\obj\DEV-Release\110\aot\arm64-v8a\libaot-PublicHoliday.dll.so'. [X.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3): error XABLD7028: File name: 'X.Android\obj\DEV-Release\110\aot\arm64-v8a\libaot-PublicHoliday.dll.so' `

Second error that even if we get those things fixed, we get now these errors during the "startup" phase of the build that we have no idea so far why and can't even workaround it:

`MSBUILD : java.exe error JAVA0000: Error in obj\Release\110\aapt_rules.txt at line 289, column 1: [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj] MSBUILD : java.exe error JAVA0000: Expected char '-' at obj\Release\110\aapt_rules.txt:289:1 [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj] MSBUILD : java.exe error JAVA0000: nit>(...); } [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj] MSBUILD : java.exe error JAVA0000: Compilation failed`
  
I hope someone can help why these now happen and some possible workaround to fix these issues

### Steps to Reproduce

I can reproduce the error by trying to build the attached [MissingDllDuringAOT.zip](https://github.com/xamarin/xamarin-android/files/9745893/MissingDllDuringAOT.zip) in Release mode.

### Relevant log output

`Severity    Code    Description    Project    File    Line    Suppression State
Error        XABBA7028: System.IO.FileNotFoundException: Could not find file 'C:\Users\Charlie\Downloads\MissingDllDuringAOT\MissingDllDuringAOT\MissingDllDuringAOT\obj\Release\110\aot\armeabi-v7a\libaot-Humanizer.dll.so'.
File name: 'C:\Users\Charlie\Downloads\MissingDllDuringAOT\MissingDllDuringAOT\MissingDllDuringAOT\obj\Release\110\aot\armeabi-v7a\libaot-Humanizer.dll.so'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Xamarin.Tools.Zip.WindowsPlatformServices.IsDirectory(ZipArchive archive, String path, Boolean& result) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/WindowsPlatformServices.cs:line 47
   at Xamarin.Tools.Zip.PlatformServices.CallServices(Func`2 code) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/PlatformServices.cs:line 166
   at Xamarin.Tools.Zip.PlatformServices.IsDirectory(ZipArchive archive, String path) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/PlatformServices.cs:line 74
   at Xamarin.Tools.Zip.ZipArchive.AddFile(String sourcePath, String archivePath, EntryPermissions permissions, CompressionMethod compressionMethod, Boolean overwriteExisting) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/ZipArchive.cs:line 406
   at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String[] supportedAbis, String apkInputPath, String apkOutputPath, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo, String assemblyStoreApkName)
   at Xamarin.Android.Tasks.BuildApk.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17             0    
_No response_`

**Comment by dellis1972** [comment]
Hi, The second error seems to be related to the `AndroidLinkTool` which you are using in your project. 
I think the recommendation is to use r8 now for the `AndroidLinkTool` for release builds and `d8` for debug. You might need to delete your bin/obj folders to get a clean build on upgrade. The error suggests that the format of the `aapt_rules.txt` file has changed and the old version is now incompatible. This file is auto generated by `aapt2` during the build pocess. 

Can you provide a diagnostic build log which contains the error ?

This can be done on the Visual Studio Developer Command Prompt. You can navigate to your project directory then use
```
msbuild Demo.Android.csproj /restore /p:Configuration=Release /t:SignAndroidPackage /bl
```

This will produce a `msbuild.binlog` file which you can zip up and attach to this issue.

**Comment by vilinet** [comment]
@dellis1972 
I will run it soon with the logging.

Until that, This issue happens in release only anyway and we always build with cleaned/removed bin/obj dirs.

This is the Android.csproj related section:
`    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <AotAssemblies>true</AotAssemblies>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidCreatePackagePerAbi>true</AndroidCreatePackagePerAbi>
    <AndroidKeyStore>true</AndroidKeyStore>
    <AndroidApkSignerAdditionalArguments>--v2-signing-enabled true</AndroidApkSignerAdditionalArguments>`

**Comment by vilinet** [comment]
Regarding the missing AOT-d dlls, i noticed that the 2 libs we have issues with, Humanizer and PublicHoliday, both uses local-dependent nuget packages.
So i wonder if something changed/broke in msbuild that local resolution in msbuild, so AOT ends up not finding that dll for AOt-ing?

**Comment by vilinet** [comment]
I cant really provide the logs as they are kind of private for now, i will try to replicate it with a new project, BUT
I found something strange, i found out why the aapt_rules are failing,
it looks like the aapt_rules.txt file is not getting flushed properly during the generation.
Sometimes the CI has no issue and it just builds that, but most of the time the aapt_rules.txt has some random "garbage" due to some bad stream flushing:

Like here:
![image](https://user-images.githubusercontent.com/13279531/194858658-30b8956c-67bb-4cee-89d3-75c271b04498.png)
Seemingly the comment line and the -keep line got merged somehow into a single line.

**Comment by vilinet** [comment]
I managed to reproduce the AOT dll problem with a sample project that i attached and added to the "Reproduce" section.

**Comment by vilinet** [comment]
Here is the .binlog for the missing dll problem during AOT:

[MissingDllDuringAOT_Release_AnyCPU_Build_2022-10-18T15_22_45.9764268+01_00.zip](https://github.com/xamarin/xamarin-android/files/9811459/MissingDllDuringAOT_Release_AnyCPU_Build_2022-10-18T15_22_45.9764268%2B01_00.zip)

**Comment by vilinet** [comment]
@dellis1972 Hi, could you re-open the ticket please? Sorry for the late .binlog but there it is. Just as an example solution to reproduce the problem.

**Comment by vilinet** [comment]
Also here is a video of the AAPT 2 error with a fresh, clean build: https://easyupload.io/1lwixd

It really looks like the aap rules files is not getting flushed properly during generation and the lines getting scrambled

**Comment by melimion** [comment]
vs 17.4.1 - issue still persists

**Comment by jonathanpeppers** [comment]
I tried the project above, and I'm not hitting an issue with `aapt_rules.txt`, but I get:
```
Xamarin.Android.Common.targets(2084,3): error XABBA7028: System.IO.FileNotFoundException: Could not find file 'C:\Users\jopepper\Downloads\MissingDllDuringAOT\MissingDllDuringAOT\obj\Release\110\aot\armeabi-v7a\libaot-Humanizer.dll.so'.
```

It looks like the core problem is that Mono's AOT compiler is having an issue with Humanizer:

```
[aot-compiler stderr] obj\\Release\\110\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:36178:83: error: expected STT_<TYPE_IN_UPPER_CASE>, '#<type>', '%<type>' or "<type>"
[aot-compiler stderr]         .type Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool,#function
```

It looks like the "B" here is some unicode character:

https://github.com/Humanizr/Humanizer/blob/7f80e03070f9e46cb5bc499567a95e0f54b4bdb5/src/Humanizer/Localisation/NumberToWords/GreekNumberToWordsConverter.cs#L187

GitHub can't even render it here:

https://github.com/Humanizr/Humanizer/blob/7f80e03070f9e46cb5bc499567a95e0f54b4bdb5/src/Humanizer/Localisation/NumberToWords/GreekNumberToWordsConverter.cs#L161

![image](https://user-images.githubusercontent.com/840039/204309152-97f1c4b3-2a53-46ed-a384-a11f0fff1c23.png)

So to look into this further:
1. If you don't use Humanizer, do the issues go away?
2. Does this still happen in .NET 6+?

If the problem happens in .NET 6+, we will have an easier time reporting an issue for the AOT compiler and getting it fixed.

**Comment by melimion** [comment]
@jonathanpeppers , try remove bin and obj folders and then Rebuild project. Not Build or Deploy.
Rebuild reproduces `aapt_rules.txt` issue.

If I use Build, projects builds successfully.
If I use Deploy, your issue with `Humanizer` reproduced.

**Comment by dellis1972** [comment]
@melimion I think this is related to the `AndroidCreatePackagePerAbi` setting. 
can you try turning that off?

I think whats happening is multiple calls to `aapt2 link` are using the same file, and they are tripping over each other.

**Comment by melimion** [comment]
@dellis1972 looks like you're right, 5 rebuilds with `<AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>` succeded

**Comment by dellis1972** [comment]
@melimion ok cool good to know, I'm working on a fix 👍
