### ISSUE TITLE
Missing Manifest.permission.POST_NOTIFICATIONS

### ISSUE THREAD

**Issue by P3PPP** [xamarin/xamarin-android#7455]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.3.5

### Description

There is no C# definition for [Manifest.permission.POST_NOTIFICATIONS](https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS).
(Presumably other values added in API level 33 have the same problem.)

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)

### Steps to Reproduce

enter `Android.Manifest.Permission.Post...`

### Did you find any workaround?

use constant value "android.permission.POST_NOTIFICATIONS"

**Comment by jpobst** [comment]
It looks like it's there:

![image](https://user-images.githubusercontent.com/179295/195203304-a3daf38e-bc5e-47cf-bb99-378ed44a076e.png)

Are you sure you are targeting `MonoAndroid13.0`?

**Comment by P3PPP** [comment]
@jpobst  Sory, TargetFramework in csproj was not Android 13.
(only AndroidManifest...)
