### ISSUE TITLE
GetProperties\GetProperty do not return non-public members (Reflection)

### ISSUE THREAD

**Issue by vyacheslav-volkov** [xamarin/xamarin-android#7469]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

Version 17.3.6

### Description

Reflection api (GetProperties\GetProperty) doesn't work correctly for net6.0-android platform. If you try to get non-public members from any class, it will only return members from that class, ignoring the type hierarchy. 

### Steps to Reproduce

- Create a new Android .NET 6 app.
- Add code:
```   
    public abstract class Alpha
    {
        protected object? AlphaProperty { get; set; }
    }

    public class Beta : Alpha
    {
        protected object? BetaProperty { get; set; }
    }

    [Activity(Label = "@string/app_name", MainLauncher = true)]
    public class MainActivity : Activity
    {
        protected override void OnCreate(Bundle? savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            var propertyInfos = typeof(Beta).GetProperties(BindingFlags.NonPublic | BindingFlags.Instance); //propertyInfos contains only the BetaProperty
            if (propertyInfos.Length != 2)
                throw new InvalidOperationException();
        }
    }
```
- GetProperties returns only the BetaProperty but it should return the BetaProperty and the AlphaProperty.

**Comment by jpobst** [comment]
I think this is being tracked here: https://github.com/dotnet/runtime/issues/76881.

**Comment by vyacheslav-volkov** [comment]
Yes, the same issue, I will close the issue.
