### ISSUE TITLE
ListenerImplementors potentially generating incorrect java code?

### ISSUE THREAD

**Issue by jbowmanp1107** [xamarin/xamarin-android#7493]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.3.6

### Description

I am working on creating an Android binding library using multiple Android Java Library Binding projects.

On Multiple of the bindings projects, everything seems to build as expected, but when I attempt to use these bindings in my .NET Maui project, the build in failing with errors like below, ALWAYS related to a ListenerImplementor.

![image](https://user-images.githubusercontent.com/24641485/197823174-e7dd5385-e3f4-4937-b31a-fe35d846d453.png)
![image](https://user-images.githubusercontent.com/24641485/197823532-11ff3a52-f0a6-4bfb-ae1c-cd8ed46ddcb9.png)

### Steps to Reproduce

1. Create a new .NET Maui Project
2. Add an Android Binding created with the Android Java Binding Project tempalte that consists of at least one Listener
3. Reference the binding somewhere in the MAUI project and use it as would be expected.
4. Attempt to build the project.
5. Observe: Build fails with errors similar to what is shown in the description.

### Did you find any workaround?

No

**Comment by jpobst** [comment]
It looks like the `.jar` or `.aar` package that you are binding is not making it into the application build.

- Are you just using the default includes for your `.jar`/`.aar` in the binding project or are you explicitly adding it?
- If explicitly adding it, it should be `<AndroidLibrary>`.
- When referencing the bindings project from the application project, are you using `<ProjectReference>`?

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetBindingProjects.md#default-file-inclusion

**Comment by jbowmanp1107** [comment]
The .aar are being added as <AndroidLibrary>, and within the MAUI project I am actually just referencing a local .dll, not the project directly. Is there something different that should be done?

![image](https://user-images.githubusercontent.com/24641485/197845548-4fa5f367-6007-4f0c-ae8c-3e147a0cc898.png)

**Comment by jpobst** [comment]
In .NET 6+, the `.jar`/`.aar` is no longer embedded in the resulting `.dll`.  It will be sitting beside the `.dll` in the output folder, like:

```
\Debug
  Venmo.dll
  Venmo.aar
```

If you are using a normal `<Reference>` to the `.dll`, you will need to make sure that whatever folder contains the `.dll` also contains the `.aar`.

**Comment by jbowmanp1107** [comment]
Thank you so much! I created local NuGet packages for all the bindings projects, and that of course brought into .aar files and then I was able to build my MAUI project as expected.

**Comment by jpobst** [comment]
Glad you got it working!

Yeah, `<PackageReference>` and `<ProjectReference>` "just work".  It's only an issue when you are using a `<Reference>` to a loose `.dll` that's been moved around on disk.  😁 

The change was made to speed up the build process, as we no longer have to scan inside each `.dll` for embedded Java packages and extract them.
