### ISSUE TITLE
MAUI fails to hide keyboard in android when text view control closes the input

### ISSUE THREAD

**Issue by liveinvarun** [xamarin/xamarin-android#7510]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS2022 preview

### Description

when keyboard is collapsed the view doesn't refresh and stays the way it is.
The background view is partially shown which is also interactive.

### Steps to Reproduce

open the repo and run the app in page 3

https://user-images.githubusercontent.com/8180770/199124158-47a96917-1633-4939-8d2b-76b5dd64bc72.mov

https://github.com/liveinvarun/MauiRepo/tree/main/TabbedPageIssue

### Did you find any workaround?

No

**Comment by jpobst** [comment]
I think this needs to be filed in https://github.com/dotnet/maui.

Unfortunately GitHub does not support moving issues to repositories in other organizations, so we can't just move it.  😢

**Comment by jpobst** [comment]
Moved to https://github.com/dotnet/maui/issues/11047.
