### ISSUE TITLE
Signing .apk targetting Android 12 using JDK 11 causes IOException: Failed to load "signer #1"

### ISSUE THREAD

**Issue by MDThomsen** [xamarin/xamarin-android#7514]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VSMac 8.10.16, Xamarin.Android 12.0.0.3

### Description

I have been trying to build and sign my app for release targeting Android 12(SDK 31) using VSMac 8.10.16, which doesn't come with JDK-11 which is required when targeting Android 12. I am using a keystore to sign the .apk myself and uploading it to Google Play.

I started off by following the instructions given here: 
[https://github.com/xamarin/xamarin-android/wiki/JDK-11-Warning#install-jdk-11-and-configure-visual-studio-to-use-jdk-11](https://github.com/xamarin/xamarin-android/wiki/JDK-11-Warning#install-jdk-11-and-configure-visual-studio-to-use-jdk-11)

I updated the code to live up to the new requirements in Android 12 specified here: 
[https://developer.android.com/about/versions/12/behavior-changes-12#exported](https://developer.android.com/about/versions/12/behavior-changes-12#exported) 

After this, the app builds just fine in debug mode. 

As part of my CI/CD pipeline I build the app with MSBuild like so: 
`msbuild  myapp.Droid.csproj /p:WarningLevel=0 /p:Configuration=”Release” p:Platform="Android" /t:SignAndroidPackage` 

The `myapp.Droid.csproj` then contains relevant information regarding the keystore.  All of this setup is unchanged from before the migration and has worked fine before. 

The build starts off fine detecting the changes in target framework and JDK version: 
![image](https://user-images.githubusercontent.com/12932687/199261086-fa09694b-1a1a-4db1-91fc-9c53b18e477a.png)

When trying to sign
`/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home/bin/java -jar /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/apksigner.jar sign –ks mykeystore.keystore --ks-pass pass:mypass --ks-key-alias myalias --key-pass pass:mykeypass --min-sdk-version 24 --max-sdk-version 31  pathforsignedapk.apk `

I then get the following exception: 
```

  Failed to load signer "signer #1" 

  java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big. 

  at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:606) 

  at java.base/sun.security.util.DerValue.init(DerValue.java:390) 

  at java.base/sun.security.util.DerValue.<init>(DerValue.java:331) 

  at java.base/sun.security.util.DerValue.<init>(DerValue.java:344) 

  at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1973) 

  at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222) 

  at java.base/java.security.KeyStore.load(KeyStore.java:1479) 

  at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353) 

  at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239) 

  at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181) 

  at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277) 

  at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83) 

 

```

I have searched a lot for this issue, but I’m having a hard time finding posts that relate to this target update to Android 12 (31). However, I found the following SO post: 
[https://stackoverflow.com/questions/42554221/signing-android-app-throws-ioexception-redundant-length-bytes-found](https://stackoverflow.com/questions/42554221/signing-android-app-throws-ioexception-redundant-length-bytes-found) 

It claims that the issue is due to older .keystore files being encoded incorrectly leading to newer JDK versions failing to parse them. Our keystore is actually quite old. It is from 2011.

However this would leave me with a different signature for my app, since I essentially end up with a new keystore file. As I understand, this would lead to issues updating existing apps because of the different signature conflicting with the currently installed app. 

 

Do you guys have an idea of how to handle this? 

### Steps to Reproduce

Steps included in description.

**Comment by jonathanpeppers** [comment]
Can you update to VS Mac 2022?

What happens if you try to use the `apksigner.jar` from the Android SDK?
