### ISSUE TITLE
Bug with Visual Studio 2022 Preview. Cant interact with idle when android emulator is started. MAUI Blazor App

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7516]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bug-with-Visual-Studio-2022-Preview-Can/10178873)._

---
[severity:I'm unable to use this version]
When my programm is built, i can use  my app on emulator, but idle isnt working in that moment. So i cant navigate, edit or stop debugging my programm.

---
#### Feedback Bot on 10/23/2022, 07:09 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
Can you elaborate on the issue, perhaps with screenshots of what you're seeing?

I am unable to understand exactly where the issue is.

Thanks!
