### ISSUE TITLE
Please, help to update to .net 6 sdk project style

### ISSUE THREAD

**Issue by ivmazurenko** [xamarin/xamarin-android#7527]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

vs 2022 17.3.6

### Description

I am trying to update project to .net 6 sdk style and i am struggling with following errors:
```
  'Download' does not implement interface member 'IDownload.Download(URI, File)'
  'AbstractCommandLineConverter' does not implement interface member 'ICommandLineConverter.Convert(ParsedCommandLine, Object)'
```

### Steps to Reproduce

This is my csproj file, like in reccomendations

<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0-android</TargetFramework>
        <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
        <OutputType>Exe</OutputType>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <ApplicationId>com.companyname.AndroidApp3</ApplicationId>
        <ApplicationVersion>1</ApplicationVersion>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <TargetFrameworkVersion>v12.0</TargetFrameworkVersion>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
    // MY DEPENDENCIES, BUISNESS LOGIC, NETSTANDARD2.1, nothing that can add problems
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AppsFlyerXamarinBindingAndroid" Version="6.5.4" />
        <PackageReference Include="Branch-Xamarin-Linking-SDK" Version="7.1.2" />
        <PackageReference Include="Com.Airbnb.Android.Lottie" Version="4.2.2" />
        <PackageReference Include="Microsoft.AppCenter" Version="4.5.3" />
        <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.5.3" />
        <PackageReference Include="Xam.Plugin.Media" Version="5.0.1" />
        <PackageReference Include="Xamarin.AndroidX.SwipeRefreshLayout" Version="1.1.0.9" />
        <PackageReference Include="Xamarin.AndroidX.ConstraintLayout" Version="2.1.4.1" />
        <PackageReference Include="Xamarin.AndroidX.CoordinatorLayout" Version="1.2.0.2" />
        <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.4.0.2" />
        <PackageReference Include="Xamarin.AndroidX.RecyclerView" Version="1.2.1.7" />
        <PackageReference Include="Xamarin.AndroidX.ViewPager2" Version="1.0.0.16" />
        <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
        <PackageReference Include="Xamarin.Facebook.Common.Android" Version="14.1.0" />
        <PackageReference Include="Xamarin.Firebase.Config" Version="121.0.1.3" />
        <PackageReference Include="Xamarin.Firebase.Crashlytics" Version="118.2.1.3" />
        <PackageReference Include="Xamarin.Firebase.Dynamic.Links" Version="120.1.1.3" />
        <PackageReference Include="Xamarin.Firebase.Iid" Version="121.1.0.3" />
        <PackageReference Include="Xamarin.Firebase.Messaging" Version="122.0.0.3" />
        <PackageReference Include="Xamarin.Google.Android.Material" Version="1.6.1.1" />
        <PackageReference Include="Xamarin.GooglePlayServices.Analytics" Version="117.0.1.3" />
        <PackageReference Include="Xamarin.GooglePlayServices.Auth" Version="119.2.0.3" />
        <PackageReference Include="Xamarin.GooglePlayServices.Maps" Version="117.0.1.3" />
        <PackageReference Include="Xamarin.GooglePlayServices.Measurement.Api" Version="119.0.1.3" />
    </ItemGroup>

</Project>

### Did you find any workaround?

No

**Comment by ivmazurenko** [comment]
binlog

**Comment by ivmazurenko** [comment]
[mylog.zip](https://github.com/xamarin/xamarin-android/files/9939924/mylog.zip)

**Comment by jonathanpeppers** [comment]
Fyi @jpobst it looks like the generated binding doesn't compile:

```
obj\Debug\net6.0-android\generated\src\Org.Gradle.Cli.AbstractCommandLineConverter.cs(11,89): error CS0535: 'AbstractCommandLineConverter' does not implement interface member 'ICommandLineConverter.Convert(ParsedCommandLine, Object)' obj\Debug\net6.0-android\generated\src\Org.Gradle.Wrapper.Download.cs(10,60): error CS0535: 'Download' does not implement interface member 'IDownload.Download(URI, File)' 
```
It may be a general binding behavior change moving from Xamarin to .NET 6+.

@ivmazurenko can you attach a `.binlog` of a `Rebuild`, it skipped this part:
```
Skipping target "GenerateBindings" because all output files are up-to-date with respect to the input files.
```

**Comment by jpobst** [comment]
There are some changes to defaults between classic and .NET 6 projects that might be affecting some metadata changes you previously did.  You can try setting them back to their classic values to see if it helps.

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetBindingProjects.md#migration-considerations

**Comment by ivmazurenko** [comment]
[builldlog_of_rebuild.zip](https://github.com/xamarin/xamarin-android/files/9940422/builldlog_of_rebuild.zip)

**Comment by jonathanpeppers** [comment]
Are you actually wanting to create a binding for this???

![image](https://user-images.githubusercontent.com/840039/200029715-1adf5fb8-03db-4513-9763-69d2ce6b6d5b.png)

**Comment by jonathanpeppers** [comment]
Maybe you just need this in your `.csproj`:

```xml
<AndroidLibrary Remove="AndroidStudio\gradle\wrapper\gradle-wrapper.jar" />
```

Or if you want to remove any that ever appear in that folder:
```xml
<AndroidLibrary Remove="AndroidStudio\**\*.jar" />
```

**Comment by ivmazurenko** [comment]
Thanks!
