### ISSUE TITLE
3rd Party library internal invoke native code lead app crash

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-android#7532]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

Version 17.3.6 Windows Version

### Description

.Net6 app Invoke 3rd party lib will lead crash.
Native app didn't crash.

Please take a look at the attachment codes and run them.

### Steps to Reproduce

[JPushMAUI.zip](https://github.com/xamarin/xamarin-android/files/9944038/JPushMAUI.zip)
1.Unzip the ziped file.
2.Using Android Studio run the app that placed on the native folder with debug mode.
3.Using Visual Studio run the app that placed on the SampleApp folder with debug mode.
4.Native app normal run after occur `JPushInterface.init(this);` which wrote on `MainActivity.java`
5.SampleApp crash after occur `CN.Jpush.Android.Api.JPushInterface.Init(this);` which wrote on `MainActivity.cs`

Additions info:
Then we should focus on the logcat window on AS and the output window on VS for
`[jiguang]`
At last the crash are occur from the `*.so` exception because output window will show a message error like: fatal signal.

Take a look at csproj file because it need ManifestPlaceholder, But I've double checked in` obj/Debug/net6.0-android/AndroidManifest.xml`, I think all values are correctly set.

### Did you find any workaround?

Sorry, I've no idea about that.

### Relevant log output

```shell
[JIGUANG-JPush] [JPushInterface] action:init - sdkVersion:4.8.4, buildId:225
[JIGUANG-JPush] [AndroidUtil] action:checkValidManifest
[yname.sampleap] Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (greylist, reflection, allowed)
[yname.sampleap] Accessing hidden field Landroid/app/ActivityThread;->mActivities:Landroid/util/ArrayMap; (greylist, reflection, allowed)
[JIGUANG-JPush] [JPushConstants] found messageReceiverClass :com.companyname.sampleapp.SampleReceiverat com.companyname.sampleapp by getCommonReceiverNames
[JIGUANG-JPush] [AndroidUtil] The fileprovider required for inapp-message is incorrectly configured, please check AndroidManifest.xml
[JIGUANG-JPush] [ActionHelper] doSingleAction: third_init
[libc] Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40 in tid 32024 (jg_fr_pool_thre), pid 31955 (yname.sampleapp)
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager2.dll
Loaded assembly: /data/data/com.companyname.sampleapp/files/.__override__/Xamarin.AndroidX.ViewPager2.dll [External]
[TabLayout] MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.Runtime.dll
Loaded assembly: /data/data/com.companyname.sampleapp/files/.__override__/Xamarin.AndroidX.Lifecycle.Runtime.dll [External]
```

**Comment by grendello** [comment]
@jingliancui could you please provide full logcat output of the crash on your device(s)? To produce the output, please run the following commands from the command prompt:

```bat
adb logcat -G 16M
adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
adb logcat -c
rem start the application on device here and wait for it to crash, then
adb logcat -d > log.txt
```

Please attach the resulting `log.txt` file, thanks!

**Comment by jingliancui** [comment]
[log.txt](https://github.com/xamarin/xamarin-android/files/9953023/log.txt)
Ok,@grendello , I've log them, please have a look. thanks.

**Comment by grendello** [comment]
@jingliancui thanks! I think it might be a runtime issue. The crash stack trace (just the relevant portion):

```
0x10a998
copy_stack_data_internal
/__w/1/s/src/mono/mono/utils/mono-threads-coop.c:191
copy_stack_data
/__w/1/s/src/mono/mono/utils/mono-threads-coop.c:246

0x10a7e0
mono_threads_enter_gc_unsafe_region_unbalanced_with_info
/__w/1/s/src/mono/mono/utils/mono-threads-coop.c:476

0x9abe4
mono_runtime_invoke
/__w/1/s/src/mono/mono/metadata/object.c:2442
```

@lambdageek mind taking a look? Thanks!

**Comment by lambdageek** [comment]
@grendello Looking at the stack trace and the code, it looks like `mono_runtime_invoke` is called from `MonodroidRuntime::Java_mono_android_Runtime_register` on a thread that's not attached to the runtime (`MonoThreadInfo *` is null in `copy_stack_data`).

Why does this code only attach to the runtime in `!defined (NET)` - you still need to attach (using the root domain) even on net6:

https://github.com/xamarin/xamarin-android/blob/acfc1efe047a5ec12bf199418d56b1796d3758dc/src/monodroid/jni/monodroid-glue.cc#L2527

**Comment by grendello** [comment]
@lambdageek good catch! Probably a mistake during separating classic and net6 code back in the day. I'll open a PR. Thanks :)
