### ISSUE TITLE
Signing a release app with the same keystore differs in Visual Studio vs Android Studio

### ISSUE THREAD

**Issue by hadigityat** [xamarin/xamarin-android#7535]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 8.10.20 (build 0)

### Description

Trying to migrate to Android Studio native development of my app, and using the same keystore details as used in Visual Studio, how can the app signature be different ? This means users cannot update the app when development switches from VS to Android Studio.

### Steps to Reproduce

1.) create app, create keystore and sign the app
2.) create the same app in Android Studio, sign the app with gradle using same keystore/pass
3) app signatures are different.

### Did you find any workaround?

No

**Comment by jonathanpeppers** [comment]
I think you'll probably want to file a bug with Google, if you are having trouble using Android Studio:

https://developer.android.com/studio/report-bugs

I don't think we can help much here, as this repo is for issues in Xamarin.Android or the Android workload for .NET 6+.

You might try signing the `.apk` manually as described here:

https://learn.microsoft.com/xamarin/android/deploy-test/signing/manually-signing-the-apk
