### ISSUE TITLE
Xamarin Android projects crash on startup after company rolled out ZScaler Client

### ISSUE THREAD

**Issue by snydesc** [xamarin/xamarin-android#7544]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.3.6

### Description

Recently my company pushed out ZScaler to select machines.  My machine was one one of them and since the push out the Xamarin Android apps built with Visual Studio now crash on startup.

One of 2 things occurs either the app will throw a null reference exception on startup:

```
 System.NullReferenceException: Object reference not set to an instance of an object.
      at Java.Interop.Runtime.GetSurfacedObjects () [0x00000] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/Runtime.cs:14 
      at Android.Runtime.JNIEnv.Exit () [0x00000] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:210 
```

Or the app will throw a signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x64696f72646e41

What is weird is if I do a clean all and rebuild, the app will run will run until I change the code.  I can add 1 line of code in the OnCreate() of the Main Applicaton class, such as adding something stupid like `int h = 0;` the app will then crash with either the nullreference error or a seg fault.  It crashes before OnCreate is even called.

I had a coworker who does not have ZScaler try the same thing on his machine  and his version runs fine (same code base/hardware).
If I provide the built APK to my coworker the application will crash on his device 

This problem will occur on any Xamarin Android Project I have, so it's not project specific.

I also determined that if I change Linking: "Sdk Assemblies Only" to "None" then the problem does not occur.

Zscaler messes with the intermediate certificates, I'm not sure how the linker plays into this, but any ideas of how to resolve this would be appreciated. 

Version Information:
```
Microsoft Visual Studio Enterprise 2022
Version 17.3.6
VisualStudio.17.Release/17.3.6+32929.385
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00476-80000-00000-AA479
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2022   00476-80000-00000-AA479
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2012   17.3.376.3011
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.40629.1 Commit Hash:3f5cc0329815af3ffb948f08857446d206a9af36
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.308 (d17-3@56b9f7e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.217 (remotes/origin/d17-3@b81db1dcc0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6


Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Steps to Reproduce

Create any Xamarin Android Application and have Linking set to "SDK assemblies only"
Run it once.
Change or add any line of code in the Android project
Run it again and it will crash.

### Did you find any workaround?

Set linking to "None"

### Relevant log output

```shell
Build fingerprint: 'Zebra/TC57/TC57:10/10-16-10.00-QG-U120-STD-HEL-04/109:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-11-07 13:30:42-0500
pid: 9910, tid: 9910, name: ar.TestApp  >>> TestApp <<<
uid: 10395
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x64696f72646e41
    x0  0000007e6a632540  x1  2e64696f72646e41  x2  0000000000000008  x3  0000007ddc7ce508
    x4  0000000000000000  x5  0000000000000000  x6  0000007d7dabe280  x7  0000007d7dabe300
    x8  0000007ddc7ceda8  x9  0000000000000001  x10 0000000000004001  x11 0000000000000000
    x12 0000000004be3e30  x13 0000000000000001  x14 0000000000000001  x15 0000000000000000
    x16 0000007ddc82d000  x17 0000007e65fe7a48  x18 0000000000000008  x19 0000007fe1718830
    x20 0000007fe1718a30  x21 0000000000000000  x22 0000000000000000  x23 0000007fe1718b98
    x24 0000007e6a6450e0  x25 0000007fe1718b98  x26 0000007ddc7ce508  x27 0000000000000000
    x28 0000007e6a91f020  x29 0000007fe1718790
    sp  0000007fe1718790  lr  0000007d7c3c5dc4  pc  0000007ddc7cef98

backtrace:
      #00 pc 0000000000007f98  <anonymous:7ddc7c7000>

stack:
         0000007fe1718710  0000007d7c6fe000  /data/app/TestApp-i7Yz5NO_Jgjg8Mv1hWBLNA==/lib/arm64/libmonosgen-2.0.so
         0000007fe1718718  0000007d7c6fe000  /data/app/TestApp-i7Yz5NO_Jgjg8Mv1hWBLNA==/lib/arm64/libmonosgen-2.0.so
         0000007fe1718720  0000007d7c6fe000  /data/app/TestApp-i7Yz5NO_Jgjg8Mv1hWBLNA==/lib/arm64/libmonosgen-2.0.so
         0000007fe1718728  0000007d7da847e0  [anon:libc_malloc]
         0000007fe1718730  0000007d7da847e0  [anon:libc_malloc]
         0000007fe1718738  0000007e6a72ca80  [anon:libc_malloc]
         0000007fe1718740  0000007d7daac3a0  [anon:libc_malloc]
         0000007fe1718748  0000007fe1718a30  [stack]
         0000007fe1718750  0000007fe1718820  [stack]
         0000007fe1718758  0000007d7c3c183c  /data/app/TestApp-i7Yz5NO_Jgjg8Mv1hWBLNA==/lib/arm64/libmonosgen-2.0.so
         0000007fe1718760  0000007de4caded8  [anon:dalvik-LinearAlloc]
         0000007fe1718768  0000007d7c7172d8  [anon:.bss]
         0000007fe1718770  0000007e6a72ca80  [anon:libc_malloc]
         0000007fe1718778  000000000000000c
         0000007fe1718780  0000007dd4165e15  /data/app/TestApp-i7Yz5NO_Jgjg8Mv1hWBLNA==/lib/arm64/libmonodroid.so
         0000007fe1718788  0000000000000006
    #00  0000007fe1718790  0000007fe17189e0  [stack]
         0000007fe1718798  0000007d7c3c5dc4  /data/app/TestApp-i7Yz5NO_Jgjg8Mv1hWBLNA==/lib/arm64/libmonosgen-2.0.so
         0000007fe17187a0  0000007fe1718a30  [stack]
         0000007fe17187a8  0000000000000000
         0000007fe17187b0  0000000000000000
         0000007fe17187b8  0000007fe1718b98  [stack]
         0000007fe17187c0  0000007e6a6450e0  [anon:libc_malloc]
         0000007fe17187c8  0000007d7c6fe000  /data/app/TestApp-i7Yz5NO_Jgjg8Mv1hWBLNA==/lib/arm64/libmonosgen-2.0.so
         0000007fe17187d0  0000007e6a607060  [anon:libc_malloc]
         0000007fe17187d8  0000000000000000
         0000007fe17187e0  0000000000000000
         0000007fe17187e8  0000007d7c6fef28  /data/app/TestApp-i7Yz5NO_Jgjg8Mv1hWBLNA==/lib/arm64/libmonosgen-2.0.so
         0000007fe17187f0  0000007ddc82d000
         0000007fe17187f8  0000007fe1718b98  [stack]
         0000007fe1718800  0000000000000000
         0000007fe1718808  0000007e6a72ca80  [anon:libc_malloc]
```

**Comment by snydesc** [comment]
Here are ADB logs and bugreport
[log.txt](https://github.com/xamarin/xamarin-android/files/9963370/log.txt)
[bugreport-TC57-10-16-10.00-QG-U120-STD-HEL-04-2022-11-08-11-43-33.zip](https://github.com/xamarin/xamarin-android/files/9963371/bugreport-TC57-10-16-10.00-QG-U120-STD-HEL-04-2022-11-08-11-43-33.zip)

**Comment by snydesc** [comment]
[log2.txt](https://github.com/xamarin/xamarin-android/files/9963641/log2.txt)
App crashes at 11-08 12:22:32.559

**Comment by grendello** [comment]
@snydesc would you be able to reproduce the SIGSEGV crash? The logs you provided all show the app exiting cleanly

**Comment by jonpryor** [comment]
@grendello [wrote](https://github.com/xamarin/xamarin-android/issues/7544#issuecomment-1307621115):

> The logs you provided all show the app exiting cleanly

While true, they show the app exiting cleanly with *exit code `1`*, which means it comes from `exit(1)`.  There are a few places where we do this:

  * https://github.com/xamarin/java.interop/blob/7716ae53da79068e079b17dd4961d0c821bb2c34/src/java-interop/java-interop-gc-bridge-mono.cc#L255
    `FATAL_EXIT_CANNOT_FIND_MONO` is 1
  * https://github.com/xamarin/xamarin-android/blob/030cd63c06d95a6b0d0f563fe9b9d537f84cb84b/src/monodroid/jni/strings.hh#L543-L544
  * https://github.com/xamarin/xamarin-android/blob/030cd63c06d95a6b0d0f563fe9b9d537f84cb84b/src/monodroid/jni/strings.hh#L744-L749

The `FATAL_EXIT_CANNOT_FIND_MONO` case is unlikely, as that only happens when `libmonosgen-2.0.so` cannot be found; when that happens, managed code *cannot be executed*, so this seems impossible.

That leaves the other `exit(1)` instances, which similarly *should* be unlikely/impossible.  Furthermore, `log_fatal()` is called before each of these `exit(1)` instances, and neither of the relevant messages are present in the log output.

Very odd. :-(

**Comment by snydesc** [comment]
The crash happens with debug.mono.trace disabled.

JNIEnv.Exit() might be being called because I did launch the application from Visual Studio.  The app crashed produced the null reference exception and then terminated.  If I launched it from the device it would hang on the splash screen and logcat would output the null reference exception and Unknown bits set in runtime_flags: 0x8000 continuously. 

1.  I am downloading 17.4 now and will see if that changes things.
2. [https://help.zscaler.com/z-app/what-zscaler-app](ZScaler).  Unfortunately this stuff just gets pushed to us.  When it was pushed Android Studio prompted me to install a bunch of untrusted intermediate certificates issued by ZScaler (CN: *.google.com, plugins.jetbraines.com, *.azurewebsites.net). [Application Configurations](https://help.zscaler.com/zia/adding-custom-certificate-application-specific-trusted-store?_ga=2.195023917.1296088437.1667198174-1144749249.1616666145&_gl=1*1abkrfd*_ga*MTE0NDc0OTI0OS4xNjE2NjY2MTQ1*_ga_10SPJ4YJL9*MTY2NzIwNjk0NC44MDUuMS4xNjY3MjA3MTExLjEwLjAuMA).   I did install the root ca and configured it forJava and android studio as outlined in the documents above.  Since they are doing a trial run of ZScaler I was able to uninstall it, however I still have the issues with the apps crashing (This issue started the day ZScaler was installed)
3.   This is a Debug build of the application.  It also occurs on any Xamarin Android project.

**Comment by grendello** [comment]
@snydesc the `JNIEnv.Exit()` is never called from any of XA code, only from the managed Android Designer. I suspect it might be a problem with linking in that it, somehow, replaces some call with one to `Exit()`. It's just an unsubstantiated guess, however

**Comment by grendello** [comment]
@snydesc would you mind attaching all the `Mono.Android.dll` copies you can find in your `obj/` folder (while keeping the directory structure)?

**Comment by snydesc** [comment]
[obj.zip](https://github.com/xamarin/xamarin-android/files/9964642/obj.zip)
The problem still occurs with 17.4
I did include java.interop.dll along with any thing that started with mono.android.*  within the zip file.

**Comment by grendello** [comment]
@snydesc thank you for the assemblies! One more request, however :) - can you please zip up and attach all the files in `obj/` named `environment*.ll`?

**Comment by grendello** [comment]
@snydesc thanks!

It appears at least part of the problem lies in the linker.  During the build we record (in the `environment*.ll`) files method tokens for the `JNIEnv.Initialize` and `JNIEnv.RegisterJniNatives` methods. In your application they are:

```
        i32 100673617, ; jnienv_initialize_method_token
        i32 100673616, ; jnienv_registerjninatives_method_token
```

However, after looking at `Mono.Android.dll` metadata, we can see the tokens are off by one:

```
10320: default int32 gettid ()  /* 0x6001428 */  (param: 12148 impl_flags: cil managed preservesig )
10321: default void RegisterJniNatives (native int typeName_ptr, int32 typeName_len, native int jniClass, native int methods_ptr, int32 methods_len)  /* 0x6001428 */  (param: 12148 impl_flags: cil managed )
10322: default void Initialize (valuetype Android.Runtime.JnienvInitializeArgs* args)  /* 0x6001429 */  (param: 12153 impl_flags: cil managed )
10323: default void Exit ()  /* 0x6001429 */  (param: 12154 impl_flags: cil managed 
```

Token we record consists of two parts - token/table identifier and table offset. In the case of method tokens we get the following conversion from the recorded token to the index:

```
# Method name: decimal token -> hexadecimal token -> (token without table id -> decimal offset: method name)
Initialize: 100673617 -> 0x6002851 -> (0x2851 -> 10321: RegisterJniNatives)
RegisterJniNatives: 100673616 -> 0x6002850 -> (0x2850 -> 10320: getid)
```

So when we invoke `JNIEnv.Initialize`, the call actually goes to `JNIEnv.RegisterJniNatives`, passing it garbage as arguments which can cause all kinds of crashes. So, somehow, `Mono.Android.dll` is modified **after** we record the tokens, and the "invalid" version is packaged, eventually causing the runtime crash.

**Comment by snydesc** [comment]
I noticed that adding the following line in the OnCreate of the MainAndroidApplication class after the initial build
`string t = Android.OS.Environment.ExternalStorageState;` will cause the Mono.Android.dll to be regenerated that is different then the initial one generated (This makes sense because the linker would now include this property into the dll).  It seems like environment*.ll is not being regenerated to account for this.

Steps to reproduce:
1.) Build Xamarin Android Project. 
2.) Add  `string t = Android.OS.Environment.ExternalStorageState;`  to OnCreate of the MainAndroidApplication class
3.) Build  Xamarin Android Project (Do not do rebuild, just normal build)
4.) Launch application and it will seg fault.

If you copy the mono.android.dll from between builds you will see they are different.  You can also look at the *.ll files and see that they do not change between builds.

**Comment by grendello** [comment]
@snydesc would you be willing to modify an msbuild targets file that ships with Xamarin.Android to test a potential fix for the environment files generation?
The file is called `Xamarin.Android.Common.targets' and it will be found somewhere below the Visual Studio installation root. In it, please apply the following change:

```diff
 <Target Name="_GenerateJavaStubs"                                                                                                                                                                                                                                          
     DependsOnTargets="$(_GenerateJavaStubsDependsOnTargets);$(BeforeGenerateAndroidManifest)"
-    Inputs="@(_AndroidMSBuildAllProjects);@(_ResolvedUserMonoAndroidAssemblies);$(_AndroidManifestAbs);$(_AndroidBuildPropertiesCache)"
+    Inputs="@(_AndroidMSBuildAllProjects);@(_ResolvedUserMonoAndroidAssemblies);$(_AndroidManifestAbs);$(_AndroidBuildPropertiesCache);@(AndroidEnvironment);@(LibraryEnvironments)"
     Outputs="$(_AndroidStampDirectory)_GenerateJavaStubs.stamp">
```

It should have the effect of regenerating the environment files whenever any source changes.

**Comment by jonathanpeppers** [comment]
An example of the path is:
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets
```

**Comment by snydesc** [comment]
[Xamarin.Android.Common.txt](https://github.com/xamarin/xamarin-android/files/9974043/Xamarin.Android.Common.txt)
That did not seem to fix the problem.

I made sure no instance of VS 2022 were running, updated the file, and then ran my test.  The app will still crash and the dates on the *.ll do not change between builds.

I attached my version of the file (I had to change the extension to txt to get it to upload)

**Comment by snydesc** [comment]
So here is some more useful information.
When my co worker ran his test for me he was running Visual Studio 2022 17.1.4 and he did not exhibit the problem.
I asked him to update to 17.4.0 and when he did, his version started seg faulting.

My version of Visual Studio updated to 17.3.6 around the same time our company pushed ZScaler down to my machine.  I'm now thinking that Zscaler may not be causing the issue, but something is wrong with Visual Studio.

**Comment by grendello** [comment]
@jonathanpeppers @dellis1972 I'm tentatively switching this issue to `Area: App Runtime` because it seems that the failure to regenerate the environment files sits at the center of the issue here.

**Comment by grendello** [comment]
@snydesc we can try one more thing, if you're willing to run a `main` branch build of XA :) If you don't mind testing that out, please download [this VSIX](http://pryorclan.com/tmp/Xamarin.Android.Sdk-13.1.99.43.vsix) archive which was produced by [this build](http://github.com/xamarin/xamarin-android/commit/c54222a853a59fe9a08e723dd7e68525872151ea). Once you update XA, shut down VS and make absolutely sure there are no `MSBuild.exe` processes left behind. Let's see if you can reproduce the issue with that build :)

**Comment by snydesc** [comment]
@grendello that did not work.  I updated to  13.1.99.43 and the problem still occurs.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
