### ISSUE TITLE
First Deploy: Investigate time spent with LZ4

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#7572]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

All

### Description

I profiled the initial `dotnet build -t:Run` of a MAUI app.

There are 21 threads in the `.speedscope` file, but if you look through several of them have time spent LZ4-ing things:

![image](https://user-images.githubusercontent.com/840039/203104265-39f86b44-3ef6-476d-a9f8-785dcecc8771.png)

![image](https://user-images.githubusercontent.com/840039/203104970-821d5a87-dc42-443e-8984-ba2602afe1c4.png)

![image](https://user-images.githubusercontent.com/840039/203105074-974bd611-ae13-4903-8ff8-0c64c2010067.png)

![image](https://user-images.githubusercontent.com/840039/203105180-4361c0be-ba2e-4edf-8e2b-c7985996d769.png)

Questions:
* Did we try in the past, not using LZ4 at all?
* There is a package `K4os.Compression.LZ4.Streams`, can we use this alongside `ArrayPool` or reuse the `byte[]` as we go?

I think we could shorten the time taken here if we made it reuse `byte[]`.

### Steps to Reproduce

```powershell
mkdir mauibuild ; cd mauibuild
dotnet new maui
# Manually edited .csproj to have 1 target framework
dotnet build -bl:build.binlog
$env:DOTNET_CLI_TELEMETRY_OPTOUT=1 # Removes CLI telemetry from trace
dotnet trace collect --format speedscope -- dotnet build "-t:Run" "-m:1" "-bl:run.binlog" --no-restore mauibuild.csproj
```

Any use of `:` needed quotes around it with `dotnet trace`, not sure why.

### Did you find any workaround?

n/a

### Relevant log output

[mauibuild.zip](https://github.com/xamarin/xamarin-android/files/10058207/mauibuild.zip)

(Look at threadpool threads in `.speedscope`)

**Comment by jonathanpeppers** [comment]
I'll try to get this trace on a slow laptop like it did with:

https://github.com/xamarin/xamarin-android/issues/7318#issuecomment-1243933121

**Comment by dellis1972** [comment]
The Lz4 stuff is quite important. It takes a 10 meg Mono.Android.dll and drops it down to 3 meg. 
So it does reduce the amount of data we transmit over the stdin of the fast dev app.

**Comment by jonathanpeppers** [comment]
The .NET 7 one is 30MB, so it might be we are creating that many `byte[]` and the GC is collecting them as it goes.

I'm still working on getting my laptop updated to the latest bits to test it.

**Comment by jonathanpeppers** [comment]
The times are higher, maybe 2x slower, but everything is on this machine:

[foo.zip](https://github.com/xamarin/xamarin-android/files/10060766/foo.zip)

**Comment by dellis1972** [comment]
So we might need to dig into LZ4 and see what its doing. 
The buffers we work on are preallocated here https://github.com/xamarin/monodroid/blob/main/tools/msbuild/Tasks/FastDeploy.cs#L551. They are then passed in by reference. So I wonder if this is the line where all the work is done https://github.com/xamarin/monodroid/blob/main/tools/msbuild/Tasks/FastDeploy.cs#L259.

**Comment by jonathanpeppers** [comment]
We should see about the compression level:

* https://github.com/MiloszKrajewski/K4os.Compression.LZ4/blob/1f3cd16ddba91368af165e9765b0d7e3454684ce/src/K4os.Compression.LZ4/LZ4Codec.cs#L47-L49
* https://github.com/MiloszKrajewski/K4os.Compression.LZ4/blob/1f3cd16ddba91368af165e9765b0d7e3454684ce/src/K4os.Compression.LZ4/LZ4Level.cs#L8-L12

Trace shows the slower one:

![image](https://user-images.githubusercontent.com/840039/203356865-9daf8910-3b59-4abb-8836-6b7701b97c1b.png)

**Comment by jonathanpeppers** [comment]
Let's add an MSBuild property that lets you control the compression level. /cc @dellis1972

**Comment by dellis1972** [comment]
I did some investigation on this and I have some data to share. 

https://gist.github.com/dellis1972/9cbf2f6b12bec73232fab9f89639bc33#file-data-csv-L8

The gist contains the results of a test app. This app compresses all the assemblies for a sample app, but times how
long it takes and how much we save for each compression level. It also tries a number of different buffer sizes.

The results clearly show that for larger buffer sizes L00_FAST is the fastest option for compression speed, but does result is slight larger compressed data. The best compression methods do result in smaller data but come at a cost of longer compression times. This is fairly obvious but at least we have the data to prove it.

**Comment by dellis1972** [comment]
45476 ms  FastDeploy                                 1 calls  L03_HC 4096 buffer
26893 ms  FastDeploy                                 1 calls L00_FAST  65260 Buffer

The second option also has some async compression changes which will compress the data while other parts are deploying it. This allows larger files to be compressed in the background.
