### ISSUE TITLE
Nullable enabled problem

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#7586]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.5.0 Prev 1

### Description

Over the weekend I converted one of my test apps to net7.0-android33.0. I used the new project technique and then just imported everything from the old project via Add Existing Item. I initially disabled nullable and implicitUsings and then enabled nullable after getting the project to build and deploy successfully.

The only warning I couldn't get rid of was the following
```
if (Build.VERSION.SdkInt >= BuildVersionCodes.P)
{
                //#pragma warning disable CA1416 // Validate platform compatibility
                Window!.Attributes!.LayoutInDisplayCutoutMode = LayoutInDisplayCutoutMode.Default;
                //#pragma warning restore CA1416 // Validate platform compatibility
}
```
I could get rid of the pragma by using the [[SupportedOSPlatformAttribute("android28.0")]](url) attribute on the function calling the code. However, I don't understand the necessity for either, when the code is already surrounded by the correct Build.VERSION.SdkInt >= BuildVersionCodes.P condition. Why the warning?

A second problem was trying to do the equivalent of `<RuntimeIdentifiers>android-arm;android-arm64;</RuntimeIdentifiers>` within Application Properties - it doesn't seem possible,

Sample App https://github.com/gmck/NavigationGraph2Net7

### Steps to Reproduce

See sample app

### Did you find any workaround?

No

**Comment by jonathanpeppers** [comment]
The code analyzer that emits `CA1416` has no idea about `Build.VERSION.SdkInt`. It is based on the `OperatingSystem` class:

https://github.com/dotnet/designs/blob/a447d77bb53d189746ccd80c2d814064c2b6c606/accepted/2020/platform-checks/platform-checks.md#platform-guards

So does an `OperatingSystem.IsAndroidVersionAtLeast(28)` check solve the problem here? I would use that anyway, as it won't have to do any interop into Java (should be faster).

**Comment by gmck** [comment]
@jonathanpeppers 
Thanks, Jonathon for the explanation and the source
```
if (OperatingSystem.IsAndroidVersionAtLeast(28)) 
    Window!.Attributes!.LayoutInDisplayCutoutMode = LayoutInDisplayCutoutMode.Default;
```
works fine.

**Comment by dellis1972** [comment]
@gmck can we close this one now?

**Comment by gmck** [comment]
Could you also comment on

A second problem was trying to do the equivalent of <RuntimeIdentifiers>android-arm;android-arm64;</RuntimeIdentifiers> within Application Properties - it doesn't seem possible.

**Comment by jonathanpeppers** [comment]
You should be able to click the project to edit the `.csproj` in the XML editor, and do:
```xml
<RuntimeIdentifiers Condition=" '$(Configuration)' == 'Release' ">android-arm;android-arm64</RuntimeIdentifiers>
```
I would only set these for `Release` mode, as `Debug` mode (Fast Deployment) will already use a single RID that works with the selected device.

If you want to suggest a feature for project options UI (the IDE), you can use:

https://developercommunity.visualstudio.com/

Thanks!

**Comment by gmck** [comment]
@jonathanpeppers 
Could you post links of where to find info like the above, e.g. the condition you added to the RuntimeIdentifiers? Everything, I've read so far refers to net6, I can't find specific stuff on net7
