### ISSUE TITLE
Binary serialization compiles, but throws exception in runtime

### ISSUE THREAD

**Issue by ivmazurenko** [xamarin/xamarin-android#7606]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

dotnet 6.0.403 with android workload. 

### Description

Hello, we are required to update xamarin ios/android application to .net 6. 

But, unfortunately, we have the binary serialization code. And we can not remove it, because we have data that can not be migrated in users devices fastly. 

So, application is successfully compiled, but it throws exception in runtime:

```
 ---> System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
```

As I see here https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md :
```
...
    NET 6 (Nov 2021)
    No new [Serializable] types introduced
    No new calls to BinaryFormatter from any first-party dotnet org code base
    All first-party dotnet org code bases begin migration away from BinaryFormatter
```

I tried to re-enable binary serialization like followiing:
```
 <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  AppContext.SetSwitch("System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization", true);

``` 

, but it throws again.

So, does that mean that it is impossible to enable binary serialization temporarily in .net 6? This is very big problem for us, according to this problem, migration to .net6 can not be acheived in observed time?

### Steps to Reproduce

Build android application in .net6 with binary serialization used
Run it

### Did you find any workaround?

No

### Relevant log output

```shell
nothing special
```

**Comment by jpobst** [comment]
I wonder if this is the issue, as Android/iOS share a lot of BCL code with WASM:
>WASM projects disable BinaryFormatter with no ability to re-enable

I would suggest refiling this issue in https://github.com/dotnet/runtime so the .NET runtime team can answer if this is intended or not.

**Comment by grendello** [comment]
@ivmazurenko this is, indeed, a BCL problem and I hope that @steveisok can answer your questions. However, should it be impossible to get binary serialization working with standard .NET6, you can always take the BinarySerializer sources from either [Mono](https://github.com/mono/mono/) or [.NET](https://github.com/dotnet/runtime/) and implement some migration strategy in-house, so to speak.

**Comment by ivmazurenko** [comment]
@grendello Maybe this issue is already solved with nuget package? Can you recommend nuget to use?

**Comment by grendello** [comment]
@ivmazurenko I'm sorry, I don't know which, if any, nuget could solve it. I stand by my recommendation of you taking the serializer sources from either Mono or .NET as this might be the fastest way for you to solve the issue.

**Comment by steveisok** [comment]
The decision not to support BinaryFormatter was intentional.  We won't support it on platforms new to .NET beyond 5.  Wasm, iOS, and Android fall into that bucket.

@ivmazurenko, I think it's going to be difficult to change our stance, but you are welcome to open an issue in dotnet/runtime for further discussion.
