### ISSUE TITLE
Localization via satellite assemblies doesn't work for android when the app built in debug mode.

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#7622]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @nevse.

---

_From @nevse on Wednesday, February 2, 2022 12:39:22 PM_

### Description

If I run app in debug mode `dotnet build -t:Run -f:net6.0-android` it doesn't show translated message. For `dotnet build -t:Run -f:net6.0-android -c:Release` it does.
Project to reproduce - https://github.com/nevse/Maui-Tests-Localization1
![debugVsRelease](https://user-images.githubusercontent.com/1169410/152153995-2c4d55e6-f1b8-4f0a-ab33-86e8705cfd25.png)

### Steps to Reproduce

1. create app `dotnet new maui -n HumanaizerTests`
2. add references 
```
<ItemGroup>
        <PackageReference Include="Humanizer.Core" Version="2.14.1" />
        <PackageReference Include="Humanizer.Core.de" Version="2.14.1" /> 
</ItemGroup>
```
3. change culture to `de` and use Humanizer to read data localization resources
```
CultureInfo.CurrentCulture = CultureInfo.CurrentUICulture = new CultureInfo("de");

CounterLabel.Text = DateTime.UtcNow.AddHours(-2).Humanize();
```
4. run the app in debug `dotnet build -t:Run -f net6.0-android` and release mode `dotnet build -t:Run -f:net6.0-android -c:Release`

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @shimingsg.

---

_From @shimingsg on Thursday, February 17, 2022 10:10:53 AM_

Verified Repro with Android 11, Repro project
[4470.zip](https://github.com/dotnet/maui/files/8130305/4470.zip)

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @AntonKosenkoDX.

---

_From @AntonKosenkoDX on Thursday, May 19, 2022 5:12:25 AM_

Hello, we are developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) and experienced the same issue. This issue has a Normal priority for us but we don't have a workaround. Thank you for your help.

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @AntonKosenkoDX.

---

_From @AntonKosenkoDX on Monday, June 27, 2022 6:56:54 AM_

@jsuarezruiz Hello! Any update on this issue?

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @msftbot[bot].

---

_From @msftbot[bot] on Tuesday, August 30, 2022 3:11:56 PM_

We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/maui/blob/main/docs/TriageProcess.md).

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @tranb3r.

---

_From @tranb3r on Wednesday, November 9, 2022 7:55:39 AM_

Hello,
Any update ?
In https://github.com/xamarin/xamarin-android/issues/2012, @jonathanpeppers said it should "just work" in .net6.
However, it still does not look like it works on maui, neither with .net6 nor .net7, right ?

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @jonathanpeppers.

---

_From @jonathanpeppers on Thursday, November 10, 2022 4:29:22 PM_

https://github.com/xamarin/xamarin-android/issues/2012 is very old, I wouldn't focus on that.

This is the first I've seen this issue for .NET 6+, I'll try the sample above.

My guess is the Humanizer library is doing something to cause this issue, but I will check.

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @tranb3r.

---

_From @tranb3r on Thursday, November 24, 2022 7:05:59 PM_

Any update on this issue ? Thanks

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @jonathanpeppers.

---

_From @jonathanpeppers on Monday, November 28, 2022 4:46:38 PM_

I think @dellis1972 is going to look into this one.

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#4470**
- Please respond to @dellis1972.

---

_From @dellis1972 on Monday, November 28, 2022 6:18:04 PM_

I've been investigating, the localised assemblies (*.resources.dll) are NOT beiing fast deployed to the device. 
I still need to narrow down the "why" part of this. I'll post updates as I find out more.

**Comment by tranb3r** [comment]
It's not really fun watching you guys close old tickets and open new ones for the same issue.
The same question remains, are you going to fix it ?
The [original issue](https://github.com/xamarin/xamarin-android/issues/2012) is more than 4 year old !!

**Comment by tranb3r** [comment]
@jonpryor 
Could you please add a link to the PR or explain in which version this fix will be fixed?

**Comment by jonathanpeppers** [comment]
It is in a private repo, so you won't be able to see it:

![image](https://user-images.githubusercontent.com/840039/214675228-91b479a1-49c6-44a8-a1e7-3f68bed4ddb8.png)

Currently testing if we can backport at: https://github.com/xamarin/xamarin-android/pull/7741
