### ISSUE TITLE
Xamarin.Forms Android app crashing on splash screen of Android 12

### ISSUE THREAD

**Issue by SikandarZafar** [xamarin/xamarin-android#7634]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Android 12 Devices

### Description

I am currently testing my app with VS 2019. Works fine with android devices lower than android 12 but crashes on devices => android 12. I updated android target framework to Android 12. Application that is being deployed on Android 12 crashes on the splash screen without throwing any errors, exception or activating any debugger in App.xaml.cs, SplashActivity.cs or any other file that supposed to be called. I tried all the possible changes in android manifest, mainActivity and splashActivity but it didn't work. Versions 6.4.0 of MVVMCross.Forms and 4.8.0.1821 of Xamarin.forms are both used in my application. I uploaded the app to the Play Store for internal testing, and while it functions on all devices, Android 12 devices experience splashing crashes. I'm using VS 2019, Android SDK 31 and Android JDK 11. I am getting a similar crash in of one my other app as well. Can you please guide me ? I checked but I did not find anything on this.

### Steps to Reproduce

Updated target version of xamarin android app android 12. Run application and it will crash right after the default blue(Splash) Screen.

### Did you find any workaround?

Not yet

**Comment by jpobst** [comment]
We will need to know what the crash is in order to investigate.  Please see https://learn.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log for directions for retrieving "logcat".
