### ISSUE TITLE
Android - APT2000 build error when maui-blazor

### ISSUE THREAD

**Issue by skoc10** [xamarin/xamarin-android#7639]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 7.0.100

### Description

```C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Aapt2.targets(212,3): error APT2000: The system cannot find the file specified. (2). [D:\ci\Jenkins\workspace\abp-commercial-nightly\volo\abp\templates\app-pro\aspnet-core\src\MyCompanyName.MyProjectName.MauiBlazor\MyCompanyName.MyProjectName.MauiBlazor.csproj::TargetFramework=net7.0-android]```

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/64414348/207810075-46624dfe-402a-440a-a7a3-bc449862a547.png">

I am facing this error when build Maui-Blazor project.
I updated all related SDK but problem continues.
This issue is not related https://github.com/xamarin/xamarin-android/issues/6925.

### Steps to Reproduce

dotnet new maui-blazor
dotnet build

**Comment by dellis1972** [comment]
@skoc10 

As per the other bug can you add the following to your project

```
<AndroidAapt2LinkExtraArgs>$(AndroidAapt2LinkExtraArgs) -v</AndroidAapt2LinkExtraArgs>
```

then build (from clean) on the command line again and post the logs?  We need the binlog file
so you need to run

```
dotnet build MyCompanyName.MyProjectName.MauiBlazor.csproj -bl
```

This will give us more verbose `aapt2` output. It should help narrow down which file is causing the error.

On a side note, the path you have `D:\ci\Jenkins\workspace\abp-commercial-nightly\volo\abp\templates\app-pro\aspnet-core\src\MyCompanyName.MyProjectName.MauiBlazor\MyCompanyName.MyProjectName.MauiBlazor.csproj` might cause some issues on windows. Windows has a max command line length which you might hit when building release builds with aot.

**Comment by skoc10** [comment]
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-android/files/10236795/msbuild.binlog.zip)

**Comment by dellis1972** [comment]
@skoc10 

I'm not seeing anyting obvious in the logs. `aapt2` is raising that error, but its not reporting which file it cannot find. 
I will try to repo here (not luck so far). 

Are you getting this on a maui-blazor template? If so can you zip up the entire project and attach it to this issue please?

**Comment by ebicoglu** [comment]
this problem is related to Windows long path. but the error message that `aapt2` is rasing is not clear.

**Comment by dellis1972** [comment]
It might also be worth looking at some of the suggestions in https://learn.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception and see if they work.

Setting a shorter `BaseIntermediateOutputPath` (and leaving the project where it is) might also help.
You will need to place this in a `Directory.Build.props` file next to your project/solution.

```
<Project>
  <PropertyGroup>
      <BaseIntermediateOutputPath Condition=" '$(OS)' == 'Windows_NT' ">C:\Intermediate\$(ProjectName)</BaseIntermediateOutputPath>
      <BaseIntermediateOutputPath Condition=" '$(OS)' != 'Windows_NT' ">/tmp/Intermediate/$(ProjectName)</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```

**Comment by skoc10** [comment]
> It might also be worth looking at some of the suggestions in https://learn.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception and see if they work.
> 
> Setting a shorter `BaseIntermediateOutputPath` (and leaving the project where it is) might also help. You will need to place this in a `Directory.Build.props` file next to your project/solution.
> 
> ```
> <Project>
>   <PropertyGroup>
>       <BaseIntermediateOutputPath Condition=" '$(OS)' == 'Windows_NT' ">C:\Intermediate\$(ProjectName)</BaseIntermediateOutputPath>
>       <BaseIntermediateOutputPath Condition=" '$(OS)' != 'Windows_NT' ">/tmp/Intermediate/$(ProjectName)</BaseIntermediateOutputPath>
>   </PropertyGroup>
> </Project>
> ```

Thanks. ```Directory.Build.props``` foder worked!
