### ISSUE TITLE
Is there an alternative to Mono.Runtime.RemoveSignalHandlers/InstallSignalHandlers in .NET 6/7?

### ISSUE THREAD

**Issue by akravch** [xamarin/xamarin-android#7640]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

Any .NET 6 and .NET 7.

### Description

We have Xamarin.Android and Xamarin.iOS apps that can catch and report native crashes by installing their own signal handlers like this:

```c#
Mono.Runtime.RemoveSignalHandlers();

try
{
    NativeCrashListener.Initialize();
}
finally
{
    Mono.Runtime.InstallSignalHandlers();
}
```

Migrating from Xamarin to .NET 6 I noticed that the `Mono.Runtime` type is not accessible any more, even though the Mono runtime is still there for Android and iOS, so obviously, you can't remove and install the handlers like this.

Mono [suggests](https://www.mono-project.com/docs/advanced/signals/) the following alternative:

```c#
IntPtr sigbus = Marshal.AllocHGlobal (512);
IntPtr sigsegv = Marshal.AllocHGlobal (512);

// Store Mono's SIGSEGV and SIGBUS handlers
sigaction (Signal.SIGBUS, IntPtr.Zero, sigbus);
sigaction (Signal.SIGSEGV, IntPtr.Zero, sigsegv);

// Enable crash reporting libraries
EnableCrashReporting ();

// Restore Mono SIGSEGV and SIGBUS handlers
sigaction (Signal.SIGBUS, sigbus, IntPtr.Zero);
sigaction (Signal.SIGSEGV, sigsegv, IntPtr.Zero);

Marshal.FreeHGlobal (sigbus);
Marshal.FreeHGlobal (sigsegv);
```

We tried both the way Mono recommends and getting rid of the remove/install code at all on our Xamarin apps to see if it makes a difference. Turns out that it does, and the number of crashes that we get significantly differs in both cases. It is hard to say which way is more correct though, since you can only see the difference on big numbers, but in any case the behavior is not the same.

I would still want to apply something similar to the .NET 6 apps, and I wonder whether there is an alternative API I didn't find. I know that there is some API to work with POSIX signals now in .NET 6, so maybe I'm just missing something.

So is there a way to achieve something like that in .NET 6+ apps or any plans to add a new API to support this?

### Steps to Reproduce

1. Try to use `Mono.Runtime` in a .NET 6 app

__Expected__:
It either works or there is a replacement for it.

__Actual:__
Doesn't work, no replacement.

### Did you find any workaround?

I was unable to find a complete workaround.
One can use what Mono [suggests](https://www.mono-project.com/docs/advanced/signals/) though, but it seems to give different results.

**Comment by jpobst** [comment]
This issue likely occurs in the .NET 6+ Mono runtime or base class libraries (BCL), which lives in the https://github.com/dotnet/runtime repository.  

Unfortunately GitHub does not support moving issues to repositories in a different organization.  Please refile this issue in that repository so that appropriate team can help.

Thanks!
