### ISSUE TITLE
Java.Lang.Class.FromType(typeof(MyClass)) throws Java.Lang.ClassNotFoundException when used with an interface

### ISSUE THREAD

**Issue by alyxal** [xamarin/xamarin-android#7649]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.4.1, Xamarin.Android SDK 13.1.0.1, TargetFrameworkVersion v13.0

### Description

Hello,

I was implementing `Bundle.GetParcelableArrayList(name, class)` as introduced in Android 13 when I found out about this issue.

As this needs a Java.Lang.Class as parameter, i added this lign of code 
`Java.Lang.Class.FromType(typeof(MyClass))`
and didn't have an issue with it.

But when I did the same with one of my interfaces, the app crashs at runtime and gives me the following error 

>[monodroid] JNIEnv.FindClass(Type) caught unexpected exception: Java.Lang.ClassNotFoundException: crc6447265ed
1f179ed47.IMyInterface ---> Java.Lang.ClassNotFoundException: Didn't find class "crc6447265ed1f179ed47.IMyInterface" on path

This is the declaration of my interface
`public interface IMyInterface : IJavaObject`

I've tried with classes, android interfaces, it works fine. The crash only occurs with interface that I've wrote myself.
I've tried device, emulator, Android 7, Android 12 and Android 13, same issue.

Here's a project sample : just launch it and press the floating button to see the crash. [TestFromType.zip](https://github.com/xamarin/xamarin-android/files/10270491/TestFromType.zip)

### Steps to Reproduce

*From the sample project*
1. Build project and launch on any device
2. Press fab button

*From a new Android project*
1. Create an interface (doesn't matter what is defined inside)
2. In your launch activity, add the following code :
`var javaclass = Java.Lang.Class.FromType(typeof(IMyInterface));`
3. Build and launch app

### Did you find any workaround?

Only workaround that I have found is to add a check to typeof(IMyInterface) with the boolean IsInterface like that :

> var type = typeof(IMyInterface);
> if (type.IsInterface) return;

### Relevant log output

```shell
[monodroid] JNIEnv.FindClass(Type) caught unexpected exception: Java.Lang.ClassNotFoundException: crc6447265ed1f179ed47.IMyInterface ---> Java.Lang.ClassNotFoundException: Didn't find class "crc6447265ed1f179ed47.IMyInterface" on path: DexPathList[[zip file "/data/app/~~tsWfh3ZSwjPRW31nBmf7WQ==/com.companyname.testfromtype-x8QWa8KC6ub8F-7sgV6n-g==/base.apk"],nativeLibraryDirectories=[/data/app/~~tsWfh3ZSwjPRW31nBmf7WQ==/com.companyname.testfromtype-x8QWa8KC6ub8F-7sgV6n-g==/lib/arm64, /data/app/~~tsWfh3ZSwjPRW31nBmf7WQ==/com.companyname.testfromtype-x8QWa8KC6ub8F-7sgV6n-g==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
[monodroid]    --- End of inner exception stack trace ---
[monodroid]   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/JniEnvironment.g.cs:12890 
[monodroid]   at Android.Runtime.JNIEnv.FindClass 
**Java.Lang.ClassNotFoundException:** 'crc6447265ed1f179ed47.IMyInterface'
```

**Comment by jpobst** [comment]
The issue is that Java does not know about your C# `IMyInterface` type.  A Java wrapper is never created for it because it never needs to interact with Java.  (That is, no Java code tries to use that interface.)

If you do not have a common Java type to pass to `Bundle.GetParcelableArrayList`, you might just want to try passing `Java.Lang.Object`.
