### ISSUE TITLE
App crasing when first XForms class loadsup - netstandard.dll not found

### ISSUE THREAD

**Issue by cail** [xamarin/xamarin-android#7655]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS/VSMac 2019

### Description

Very strange issue, being visualised by XForms pages fatal failure when load:

```
12-25 12:23:09.797  9905  9905 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
```

Application has complex dependencies, not only Xamarin Forms, but also android native views.

The most interesting fact is that being build in DEBUG mode - it works FINE!
Only RELEASE build fails!

Comparing Debug and Release APK content (and also project/obj/(Debug/Release)/android/assets content)
I see that Debug version includes netstandard (2.0.0.0), but Release version (and APK file) does not have it.

Thats a reason I feel this is a build/dependency generation issue, but not XForms issue.

Any hints?

### Steps to Reproduce

I never tried to repro it with empty project. Have a feeling its a consequence of my project configuration.

### Did you find any workaround?

NO

### Relevant log output

```shell
12-25 12:23:09.797  9905  9905 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
12-25 12:23:09.797  9905  9905 E AndroidRuntime: File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
12-25 12:23:09.797  9905  9905 E AndroidRuntime:   at XXX..ctor () [0x00008] in <641f2548c647481a8e62ae203d0e2565>:0 
12-25 12:23:09.797  9905  9905 E AndroidRuntime:   at XXXX.OnListItemClick (Android.Widget.ListView l, Android.Views.View v, System.Int32 position, System.Int64 id) [0x00161] in <641f2548c647481a8e62ae203d0e2565>:0 
12-25 12:23:09.797  9905  9905 E AndroidRuntime:   at Android.App.ListActivity.n_OnListItemClick_Landroid_widget_ListView_Landroid_view_View_IJ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_l, System.IntPtr native_v, System.Int32 position, System.Int64 id) [0x00017] in <8f9bb5389d2844a39ffbc124af8cc56a>:0 
12-25 12:23:09.797  9905  9905 E AndroidRuntime:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.70(intptr,intptr,intptr,intptr,int,long)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at crc643f94551bd7fc4228.SettingsActivity.n_onListItemClick(Native Method)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at crc643f94551bd7fc4228.SettingsActivity.onListItemClick(SettingsActivity.java:57)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.app.ListActivity$2.onItemClick(ListActivity.java:323)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1187)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3179)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4109)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3867)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:14309)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
12-25 12:23:09.797  9905  9905 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
```

**Comment by cail** [comment]
Version info:
[vsmac-version.txt](https://github.com/xamarin/xamarin-android/files/10299844/vsmac-version.txt)

**Comment by cail** [comment]
[assemblies.manifest.txt](https://github.com/xamarin/xamarin-android/files/10299845/assemblies.manifest.txt)
of the resulting APK file. Contains NO netstandard.dll

**Comment by jonathanpeppers** [comment]
`nestandard.dll` is an assembly that contains all type forwards. The reason this is gone in a release build, is the linker will "link away" this assembly completely putting the real types in their place.

Can you share more information about the assemblies these two types come from in the stack trace?

```
12-25 12:23:09.797  9905  9905 E AndroidRuntime:   at XXX..ctor () [0x00008] in <641f2548c647481a8e62ae203d0e2565>:0 
12-25 12:23:09.797  9905  9905 E AndroidRuntime:   at XXXX.OnListItemClick (Android.Widget.ListView l, Android.Views.View v, System.Int32 position, System.Int64 id) [0x00161] in <641f2548c647481a8e62ae203d0e2565>:0 
```

What `TargetFramework` are they? Is `XXX..ctor ()` coming from a `nestandard1.x` assembly?

Is it possible to share your `.apk` privately?

**Comment by cail** [comment]
> Can you share more information about the assemblies these two types come from in the stack trace?

Thats a main application's assembly. The application is actually executing fine until the moment it tries to activate XForms based Activity.

So XXX..ctor () is just a class derived from ContentPage.

I can share the APK privately, no problem!

**Comment by jonathanpeppers** [comment]
@cail have you already tried setting:

```xml
<PropertyGroup>
  <AndroidLinkSkip>netstandard</AndroidLinkSkip>
</PropertyGroup>
```

https://learn.microsoft.com/en-us/xamarin/android/deploy-test/linker#linkskip

The problem looks like it could be caused by `GalaSoft.MvvmLight` being a portable class library:

![image](https://user-images.githubusercontent.com/840039/212092217-9e58b886-2dbc-4b40-bca7-663079203bb1.png)

Do they have a `nestandard2.0` version of this library? I didn't check if there are other assemblies that are PCLs.

**Comment by cail** [comment]
Hi @jonathanpeppers!

Thanks for the hint, with this linker instruction I see now netstandard is in the list of APK assemblies. And XForm classes are instantiated fine.

I've checked MVVM library - it contains 
`SL5 monoandroid1 net35 net40 net45 portable-net45+wp8+wpa81+netcore45+monoandroid1+xamarin.ios10 uap10.0 windows81 wp8 wp81 wpa81 xamarin.ios10` list of frameworks.
In my android, monoandroid1 is used.

Should then this be considered a temporary workaround?

**Comment by jonathanpeppers** [comment]
For the long term solution, you should eventually migrate to .NET 7. We'd more likely to get a fix there, as there are people actively working on dotnet/linker. It's also possible this problem goes away in .NET 7.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
