### ISSUE TITLE
[.NET 8] perf regression in `<LinkAssembliesNoShrink/>`

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#7684]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 8 / main

### Description

In .NET 7, in an old log I see:

![image](https://user-images.githubusercontent.com/840039/211677412-a672b5fa-7034-4a70-8d3d-8ad3820e6c5c.png)

This was an example of a `.xaml` change in a `dotnet new maui` project.

Now I see:

![image](https://user-images.githubusercontent.com/840039/211677489-b17cc8c3-f4ce-4ce9-8e85-a9b8272813ae.png)

`dotnet trace` shows most of the time is:

![image](https://user-images.githubusercontent.com/840039/211677562-296eed6a-e557-4dc1-880f-08598c8da684.png)

So I think we might need to rework parts of dc3ccf28cdbe9f8c0a705400b83c11a85c81a980, maybe it can skip some things on incremental builds?

Less log messages would also help:

![image](https://user-images.githubusercontent.com/840039/211677697-34f68a48-72da-45a0-aa05-a1e1f7aae0b0.png)

### Steps to Reproduce

1. `dotnet new maui`
2. build
3. change `.xaml`
4. build again

### Did you find any workaround?

Set `$(AndroidUseDesignerAssembly)` to `false`, would skip some of these steps.

### Relevant log output

[msbuild.zip](https://github.com/xamarin/xamarin-android/files/10387362/msbuild.zip)

**Comment by dellis1972** [comment]
This step is converting old Resource.designer.cs code over to the new system. So once Maui has switched over to using the newer system it should be better as it will have less work to do.

**Comment by jonathanpeppers** [comment]
Yeah, we can keep an eye and test again when we have a new MAUI. 

What made me think something else is going on, is this target builds partially:

    Target Name=_LinkAssembliesNoShrink Project=bar.csproj
    Building target "_LinkAssembliesNoShrink" partially, because some output files are out of date with respect to their input files.
    [ResolvedAssemblies: Input=obj\Debug\net8.0-android\android-arm64\bar.dll, Output=obj\Debug\net8.0-android\android-arm64\android\assets\bar.dll] Input file is newer than output file.

So in theory it should only be looking at `bar.dll` in this example?

**Comment by dellis1972** [comment]
It is buiding partially. but the Task in the target is not using any of the "partial" calculated ItemGroups

```
<LinkAssembliesNoShrink
      ResolvedAssemblies="@(_AllResolvedAssemblies)"
      SourceFiles="@(ResolvedAssemblies)"
      DestinationFiles="@(ResolvedAssemblies->'$(MonoAndroidIntermediateAssemblyDir)%(DestinationSubPath)')"
      TargetName="$(TargetName)"
      AddKeepAlives="$(AndroidAddKeepAlives)"
      UseDesignerAssembly="$(AndroidUseDesignerAssembly)"
      Deterministic="$(Deterministic)"
      UsingAndroidNETSdk="$(UsingAndroidNETSdk)"
  />
```

Its using `@(_AllResolvedAssemblies)` , so all the items will be processed.

**Comment by jonathanpeppers** [comment]
Previously `@(_AllResolvedAssemblies)` was only used for search paths on the `DirectoryAssemblyResolver` -- it's possible Mono.Cecil would need to go load other assemblies.

The "partial" part is:

      SourceFiles="@(ResolvedAssemblies)"
      DestinationFiles="@(ResolvedAssemblies->'$(MonoAndroidIntermediateAssemblyDir)%(DestinationSubPath)')"

**Comment by jonathanpeppers** [comment]
If I'm reading the code right, I think this will fix this: https://github.com/xamarin/xamarin-android/pull/7686

But let's see if anything breaks?
