### ISSUE TITLE
Bindings from `$(AndroidJavaSource)` don't work with Intellisense

### ISSUE THREAD

**Issue by jpobst** [xamarin/xamarin-android#7692]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 7, VS 2022 17.4. 17.5 P2

### Description

.NET 7's `$(AndroidJavaSource)` is great for simplifying several binding tasks.  However, while it compiles on a build, the `.cs` files it generates do not get added to the files used by IntelliSense, and thus trying to consume the bindings is difficult because they do not show up in IntelliSense dropdowns and show as errors in the editor.

![image](https://user-images.githubusercontent.com/179295/212108988-f55e0ecf-3bdf-444b-9a84-b10f3b1d9f12.png)

Looking at a design time build, this appears to be because they are never added to `@(Compile)` which is used by `<Csc>`:
![image](https://user-images.githubusercontent.com/179295/212109117-6c0e8751-4a0f-4674-a635-2acfe9fa695a.png)

For comparison, it appears we add `Resources.designer.cs` to `@(Compile)` when `$(ManagedDesignTimeBuild)' == 'True'`.

https://github.com/xamarin/xamarin-android/blob/8c24b8ff0b32e198311b75e3bbce904989504f7c/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1076

### Steps to Reproduce

1) `dotnet new android`
2) Add a `.java` file to the project
3) Attempt to consume the generated binding in the project

Minimal test case:
[AndroidApp2.zip](https://github.com/xamarin/xamarin-android/files/10403218/AndroidApp2.zip)

**Comment by dellis1972** [comment]
My gut says that `AddBindingsToCompile` is not being called during a Design Time Build.

**Comment by dellis1972** [comment]
Yup 

```
Target "AddBindingsToCompile" skipped, due to false condition; ( '$(_AndroidGenerateManagedBindings)' == 'true' ) was evaluated as ( '' == 'true' ).
```

`_AndroidGenerateManagedBindings` is empty, probably because we are not evaluating it. 
I'm not sure we want to do a Java build in the DTB though....
If its done already and the source has been generated the we should include it. But I'm not sure about doing a java compile at that time though.

**Comment by mohachouch** [comment]
Hi, we have the same problem in my company. it makes this feature completely useless. Please fix it

**Comment by jonathanpeppers** [comment]
@mohachouch as a workaround, I think you can just put the `.java` file in a separate class library? Did you try that?

Then Intellisense should be able to use the compiled `.dll` on disk in that case.

**Comment by mohachouch** [comment]
@jonathanpeppers Thanks for tour Quick response. I tried to separate in a library but I had the same problem. I feel like it's more related to the new csproj format. I will try again tomorrow.

**Comment by jonathanpeppers** [comment]
I hit similar issues working on:

https://github.com/jonathanpeppers/spice/blob/main/src/Spice/Platforms/Android/Interop.java

I spent a little time on it, but I didn't see an immediately, easy fix.

**Comment by mohachouch** [comment]
Hi @jonathanpeppers do you reproduce the bug?

**Comment by mohachouch** [comment]
Any news @jonathanpeppers

**Comment by jonathanpeppers** [comment]
Please others upvote, if this impacts you. This helps us know how important it is.

I'm currently working on MAUI issues that have a lot louder feedback. 👀

**Comment by mohachouch** [comment]
Hi @jonathanpeppers,

Any News about this bug ? This bug is present since .net 6, so since 2 years.

Thanks
