### ISSUE TITLE
Updating two test projects to Xamarin.AndroidX.AppCompat Version 1.6.0 causes build failure

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#7699]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.5.0 Prev 2.0

### Description

@jonpryor , @moljac 

I just upgraded two test projects to Xamarin.AndroidX.AppCompat Version 1.6.0, no other changes and both projects fail to build with the following type of errors.

The projects are available at https://github.com/gmck/NavigationGraph7Net7 and https://github.com/gmck/PredictiveBackGesture. Both projects just need to have the AppCompat version updated to 1.6.0 for them to fail to build.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/gmcke/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/gmcke/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/gmcke/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-AU style='tab-interval:36.0pt;word-wrap:break-word'>

<p class=MsoNormal><span style='font-size:8.0pt;line-height:107%;mso-bidi-font-family:
Calibri;mso-bidi-theme-font:minor-latin;color:black'><o:p>&nbsp;</o:p></span></p>

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Warning | XA4214 | The managed type   `Kotlin.IO.Path.IExperimentalPathApi` exists in multiple assemblies:   Xamarin.Kotlin.StdLib, Xamarin.Kotlin.StdLib.Jdk7. Please refactor the   managed type names in these assemblies so that they are not identical. | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Warning | XA4214 | References to the type   `Kotlin.IO.Path.IExperimentalPathApi` will refer to   `Kotlin.IO.Path.IExperimentalPathApi, Xamarin.Kotlin.StdLib`. | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Warning | XA4214 | The managed type   `Kotlin.IO.Path.IFileVisitorBuilder` exists in multiple assemblies:   Xamarin.Kotlin.StdLib, Xamarin.Kotlin.StdLib.Jdk7. Please refactor the   managed type names in these assemblies so that they are not identical. | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Warning | XA4214 | References to the type   `Kotlin.IO.Path.IFileVisitorBuilder` will refer to   `Kotlin.IO.Path.IFileVisitorBuilder, Xamarin.Kotlin.StdLib`. | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Error | XA4215 | The Java type   `kotlin.io.path.ExperimentalPathApi` is generated by more than one managed   type. Please change the [Register] attribute so that the same Java type is   not emitted. | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Error | XA4215 | `kotlin.io.path.ExperimentalPathApi` generated by:   Kotlin.IO.Path.IExperimentalPathApi, Xamarin.Kotlin.StdLib, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Error | XA4215 | `kotlin.io.path.ExperimentalPathApi` generated by:   Kotlin.IO.Path.IExperimentalPathApi, Xamarin.Kotlin.StdLib.Jdk7,   Version=1.0.0.0, Culture=neutral, PublicKeyToken=null | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Error | XA4215 | The Java type   `kotlin.io.path.FileVisitorBuilder` is generated by more than one managed   type. Please change the [Register] attribute so that the same Java type is   not emitted. | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Error | XA4215 | `kotlin.io.path.FileVisitorBuilder` generated by:   Kotlin.IO.Path.IFileVisitorBuilder, Xamarin.Kotlin.StdLib, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  
Error | XA4215 | `kotlin.io.path.FileVisitorBuilder` generated by:   Kotlin.IO.Path.IFileVisitorBuilder, Xamarin.Kotlin.StdLib.Jdk7,   Version=1.0.0.0, Culture=neutral, PublicKeyToken=null | PredictiveBackGesture | C:\Program   Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets | 1476 |  

<p class=MsoNormal><span style='font-size:8.0pt;line-height:107%;mso-bidi-font-family:
Calibri;mso-bidi-theme-font:minor-latin'><o:p>&nbsp;</o:p></span></p>

</body>

</html>

### Steps to Reproduce

See test projects

### Did you find any workaround?

No

**Comment by jpobst** [comment]
Looks like this can be fixed by ensuring the 2 versions of Kotlin match.  Perhaps they moved these types from one package to another in `1.8`, and if they are mismatched, it exists in both.

```xml
<PackageReference Include="Xamarin.Kotlin.StdLib.Jdk8" Version="1.8.0" />
```

**Comment by sk1llsh0t** [comment]
I'm also experiencing these errors as well.

**Comment by moljac** [comment]
will do

**Comment by gmck** [comment]
@sk1llsh0t , @jpobst , @moljac 
I can also confirm your suggestion of adding  `<PackageReference Include="Xamarin.Kotlin.StdLib.Jdk8" Version="1.8.0" />` also allowed both my test apps to build and run correctly.

**Comment by fgiacomelli** [comment]
Same problem for me, these errors:

`Error		The Java type `kotlin.io.path.ExperimentalPathApi` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.		

Error		`kotlin.io.path.ExperimentalPathApi` generated by: Kotlin.IO.Path.IExperimentalPathApi, Xamarin.Kotlin.StdLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null		

Error		The Java type `kotlin.io.path.FileVisitorBuilder` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.		

Error		`kotlin.io.path.FileVisitorBuilder` generated by: Kotlin.IO.Path.IFileVisitorBuilder, Xamarin.Kotlin.StdLib.Jdk7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null		

Error		`kotlin.io.path.ExperimentalPathApi` generated by: Kotlin.IO.Path.IExperimentalPathApi, Xamarin.Kotlin.StdLib.Jdk7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null	`

that appeared when I update Xamarin.AndroidX.AppCompat from 1.5.1.1 to 1.6.0 was solved adding the package as suggested above

**Comment by egorychev10** [comment]
> 

Thank you! That works for me

**Comment by jpobst** [comment]
A full bump to all AndroidX NuGets/dependencies was published Jan 21.  Updating to the latest versions should fix this and remove the need for the additional `<PackageReference>`.
