### ISSUE TITLE
Predictive text not working on Keyboards

### ISSUE THREAD

**Issue by manojSF3414** [xamarin/xamarin-android#7708]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Android 11

### Description

Hi,
I was unable to get text predictions with EditText API using the Samsung keyboard and swift keyboard. there were no issues while using the Gboard.
We have used the input type below

```csharp
EditText.InputType = Android.Text.InputTypes.TextFlagAutoCorrect |
    Android.Text.InputTypes.TextFlagAutoComplete |
    Android.Text.InputTypes.TextFlagMultiLine |
    Android.Text.InputTypes.TextVariationFilter;
```

I have attached a runnable sample with only edit text control in the application
![image](https://user-images.githubusercontent.com/93641357/212807638-87f988e6-9b3b-4006-a1e4-55b97a6c505a.png)
[KeyboardIssueSample.zip](https://github.com/xamarin/xamarin-android/files/10431106/KeyboardIssueSample.zip)

### Steps to Reproduce

1. Open the application [KeyboardIssueSample.zip](https://github.com/xamarin/xamarin-android/files/10431112/KeyboardIssueSample.zip)
2. with the swift keyboard or Samsung keyboard as default try to edit the text using the edit text control
3. No text predictions will occur even after selecting the types Android.Text.InputTypes.TextFlagAutoCorrect | Android.Text.InputTypes.TextFlagAutoComplete

**Comment by jpobst** [comment]
Ultimately, all Xamarin.Android does is provide generated wrappers that allow you to call Google’s Android API. We do not have much expertise in how to use those API’s properly. 

You will likely need to use the Android API documentation and relevant forums to determine how to write code for your desired outcome.
