### ISSUE TITLE
Please, remove implict conversion of Andropid.Graphics.Color to int

### ISSUE THREAD

**Issue by ivmazurenko** [xamarin/xamarin-android#7740]
### Description

We have a thousand of lines of code that mixed following:
- Android colors
- Android color id's (Resource.Color.colorYellow)
- Android material color attributes (Resource.Attribute.colorYellow)
- our domain color struct

And it is easy to and put color to place, where ID is expected. We are making these mistakes often!

**Comment by jpobst** [comment]
Unfortunately removing this would break every other user's code who currently rely on the implicit cast, and thus we cannot make that change.

**Comment by ivmazurenko** [comment]
At the first look, it it not dangerous, because users code just will not compile It is like enable #nullable in project. All possible dangerous places will be rechecked again. 

But okay, I think, you know much more then me. Thanks

**Comment by jpobst** [comment]
Correct, that is the issue.  We do not want users to update to .NET 8 and all of the sudden there are hundreds or thousands of compile errors they have to fix.  Not breaking users code is one of our highest priorities.

This is the exact reason why `#nullable` is something that users must opt into.  It is not enabled by default.
