### ISSUE TITLE
AssemblyLoadContext.LoadFromStream(Stream, Stream) is not implemented

### ISSUE THREAD

**Issue by MaxwellDAssistek** [xamarin/xamarin-android#7763]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022

### Description

Attempting to call [LoadFromStream(Stream, Stream)](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.loadfromstream?view=net-7.0#system-runtime-loader-assemblyloadcontext-loadfromstream(system-io-stream-system-io-stream)) raises a Not Implemented exception.

PR #5940 gave support for most AssemblyLoadContext functions, but it seems LoadFromStream including symbols was missed.

### Steps to Reproduce

1. Call `AssemblyLoadContext.LoadFromStream(Stream, Stream)`

### Did you find any workaround?

A workaround seems to be to write out the dll and pdb data to a temporary file and load it from there using `AssemblyLoadContext.LoadFromAssemblyPath`, or use embedded debug symbols in the loaded DLL (only applicable if you have control over the DLL build).

**Comment by grendello** [comment]
@MaxwellDAssistek could you please attach the full stack trace you get for this exception? Thanks!

**Comment by grendello** [comment]
@MaxwellDAssistek thanks for the trace! From looking at the code, it seems that `Length` is supported only if the backing stream is a `Java.IO.FileInputStream`. I don't think we can fix it, @jonpryor?

**Comment by grendello** [comment]
@MaxwellDAssistek would you be able to provide a full, small, repro application for this issue? Alternatively, if that's not possible, can you tell us what is the type of `resStream` in your code snippet?

**Comment by MaxwellDAssistek** [comment]
@grendello That's actually just this function: https://learn.microsoft.com/en-us/dotnet/api/xamarin.essentials.filesystem.openapppackagefileasync?view=xamarin-essentials-watchos

**Comment by grendello** [comment]
@MaxwellDAssistek yes, but it returns an abstract base class instead of a concrete implementation.  However, it appears that what this method really returns is a [`Java.IO.InputStream`](https://developer.android.com/reference/java/io/InputStream) (via [this](https://developer.android.com/reference/android/content/res/AssetManager#open(java.lang.String))), and that is an abstract class itself, derivatives of which **may** have a member which gives us the stream length.

**Comment by MaxwellDAssistek** [comment]
@grendello Interesting. Perhaps [this](https://developer.android.com/reference/android/content/res/AssetManager#open(java.lang.String,%20int)) overload can be used instead with the proper flags. which would guarantee that a length is available.

**Comment by grendello** [comment]
@MaxwellDAssistek if you give us the type of `resStream` we can special-case it, if it has a way to provide us its length.

**Comment by MaxwellDAssistek** [comment]
@grendello The type of `resStream` is `{Android.Runtime.InputStreamInvoker}` but the type of the BaseStream under that is `{Android.Content.Res.AssetManager.AssetInputStream}`.

**Comment by MaxwellDAssistek** [comment]
@grendello I think there is a way to avoid requiring knowing the length of the stream. It seems that the LoadFromStream boils down to this function that just reads all the contents of the stream into memory: https://github.com/dotnet/runtime/blob/6fecc25b0260b1586305ecefe0cef9a0e22fb66c/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L397 

Surely there's no need to require the length of the stream just to read it in its entirety anyway,

**Comment by grendello** [comment]
@MaxwellDAssistek perhaps, but you'd have to bring it up with the [Dotnet team](https://github.com/dotnet/runtime/), we are just a "downstream" user of .NET BCL.

**Comment by MaxwellDAssistek** [comment]
Got it. I'll open an issue there and link this one to it.
