### ISSUE TITLE
🙋🏽‍♀️ [Survey] GitHub contributor experience

### ISSUE THREAD

**Issue by samhouts** [xamarin/xamarin-android#7783]
### .NET for Android Community! We want to hear from YOU!

We're asking you to let us know how we're doing as maintainers. Fill out the survey in the link below and tell us what you think.

Whether you've been involved for years or you're relatively new, please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8KTX9VT?Source=xamarin/xamarin-android

**Comment by jpobst** [comment]
This survey has now closed, thanks to everyone who participated!
