### ISSUE TITLE
ContentProvider crashes the app when throws cross-process exception

### ISSUE THREAD

**Issue by dzhukovski** [xamarin/xamarin-android#7788]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Xamarin.Android Version 13.1.0.1

### Description

Once the code tries to throw cross-process exception (such as IllegalStateException) it crashes the app. The feature was working in previous versions but started to crash the app. Not sure after which update it happened but in the latest Xamarin.Android versions it stopped working.

### Steps to Reproduce

1. Create new Android App
2. Register content provider

```cs
[ContentProvider(new[] { "UriRoot" }, Exported = true)]
public class SqliteDbContentProvider : ContentProvider
{
    public override ICursor Query(
            Uri uri,
            string[] projection,
            string selection,
            string[] selectionArgs,
            string sortOrder)
        {
            try
            {
                // Sqlite logic throws an exception. for instance I use the query "Select UnknownColumn From UnknownTable"
            }
            catch (System.Exception ex)
            {
                Log.Error(GetType().Name, ex.ToString());
                throw new IllegalStateException(
                    $"Query: {uri}\n" +
                    $"Projection: {projection}\n" +
                    $"Selection: {selection}\n" +
                    $"SelectionArgs: {string.Join(", ", selectionArgs)}\n" +
                    $"SortOrder: {sortOrder}",
                    Throwable.FromException(ex)
                );
            }
        }
}
```

3. Compile and Run the app on the device
4. Create the second Android app
5. Implement ContentResolver to pass the arguments to SqliteDbContentProvider registered in the first app
6. Run the app and call ContentResolver.
7. First app is going to crash and sometimes the second app is going to crash too

Expected result:
- First app should not crash
- The exception should be passed to the second app

**Comment by grendello** [comment]
@dzhukovski could you please record the crash using the steps below and attach the resulting log:

```shell
$ adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
$ adb logcat -G 16M
$ adb logcat -c
# Cause the app crash here and after it crashes, wait a couple of seconds then:
$ adb logcat -d > log.txt
```

**Comment by dzhukovski** [comment]
> @dzhukovski could you please record the crash using the steps below and attach the resulting log:
> 
> ```shell
> $ adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
> $ adb logcat -G 16M
> $ adb logcat -c
> # Cause the app crash here and after it crashes, wait a couple of seconds then:
> $ adb logcat -d > log.txt
> ```

[log.txt.zip](https://github.com/xamarin/xamarin-android/files/10721765/log.txt.zip)

**Comment by grendello** [comment]
@dzhukovski from what I see, it happens during debugging, is that correct? If yes, please try running the app without the debugger attached or in the `Release` mode - does the app work then?

The issue I see in the log is not really a crash, but rather a failure to accept a connection from the debugger because the port specified by the IDE is already in use, which is treated as a fatal error and the application aborts:

```
02-13 14:24:30.584 20716 20716 W monodroid-debug: Accepted stdout connection: -1
02-13 14:24:30.584 20716 20716 F monodroid-debug: Error accepting stdout and stderr (127.0.0.1:8786): Address already in use
```

If the application works without the debugger (it should), please restart the device/emulator you deploy as it's possible that some previous instance of the application didn't exit cleanly while being debugged, and there exists a zombie socket occupying the above port.  Note that the port is specified by the IDE when starting the application, so it might also be helpful to shut down all instances of your IDE and start a new session, which should then select different ports for the debugger to use.

Please let me know if any of the above worked.

**Comment by dzhukovski** [comment]
> @dzhukovski from what I see, it happens during debugging, is that correct? If yes, please try running the app without the debugger attached or in the `Release` mode - does the app work then?
> 
> The issue I see in the log is not really a crash, but rather a failure to accept a connection from the debugger because the port specified by the IDE is already in use, which is treated as a fatal error and the application aborts:
> 
> ```
> 02-13 14:24:30.584 20716 20716 W monodroid-debug: Accepted stdout connection: -1
> 02-13 14:24:30.584 20716 20716 F monodroid-debug: Error accepting stdout and stderr (127.0.0.1:8786): Address already in use
> ```
> 
> If the application works without the debugger (it should), please restart the device/emulator you deploy as it's possible that some previous instance of the application didn't exit cleanly while being debugged, and there exists a zombie socket occupying the above port. Note that the port is specified by the IDE when starting the application, so it might also be helpful to shut down all instances of your IDE and start a new session, which should then select different ports for the debugger to use.
> 
> Please let me know if any of the above worked.
[log.txt.zip](https://github.com/xamarin/xamarin-android/files/10722042/log.txt.zip)
This one is in Release without Debugger

**Comment by dzhukovski** [comment]
> @dzhukovski from what I see, it happens during debugging, is that correct? If yes, please try running the app without the debugger attached or in the `Release` mode - does the app work then?
> 
> The issue I see in the log is not really a crash, but rather a failure to accept a connection from the debugger because the port specified by the IDE is already in use, which is treated as a fatal error and the application aborts:
> 
> ```
> 02-13 14:24:30.584 20716 20716 W monodroid-debug: Accepted stdout connection: -1
> 02-13 14:24:30.584 20716 20716 F monodroid-debug: Error accepting stdout and stderr (127.0.0.1:8786): Address already in use
> ```
> 
> If the application works without the debugger (it should), please restart the device/emulator you deploy as it's possible that some previous instance of the application didn't exit cleanly while being debugged, and there exists a zombie socket occupying the above port. Note that the port is specified by the IDE when starting the application, so it might also be helpful to shut down all instances of your IDE and start a new session, which should then select different ports for the debugger to use.
> 
> Please let me know if any of the above worked.

[log.txt.zip](https://github.com/xamarin/xamarin-android/files/10722384/log.txt.zip)

The next log is for the integration test run only. I started the app and run the test. All apps are in Release mode but it crashes the first app.

**Comment by grendello** [comment]
@dzhukovski `storemobile.appservice-1` is the service app that's crashing, correct?

**Comment by dzhukovski** [comment]
> @dzhukovski `storemobile.appservice-1` is the service app that's crashing, correct?

yes, and I probably found the issue:

```cs
$"SelectionArgs: {string.Join(", ", selectionArgs)}\n"
```

Seems it was working on Xamarin.Android in previous versions but started to throw an Exception (value can not be null). I replaced it with next piece of code and it started to work:

```cs
 errorMessage += selectionArgs != null
                    ? $"SelectionArgs: {string.Join(", ", selectionArgs)}\n"
                    : $"SelectionArgs: No Arguments\n";
```

btw the test still fails in debug mode but working well in Release. 
Sorry for improper ticket, I was confused because we didn't touch this code and it stopped working after Xamarin.Android update. It seems string.Join(", ", null) was null ref tolerate.

**Comment by grendello** [comment]
@dzhukovski glad you found the issue! And there's no need to apologize for opening the ticket :) The issue was there and you had no way to know what it was. Indeed, `String.Join` appears to require that the `IEnumerable` is not `null`, although it can be full of `null` entries.

The debug mode in failure maybe caused by a kind of a race condition in the IDE.  If you use two instances of the IDE to launch both the service and the client apps, first attach to one of them then wait for some time (~10 seconds) and only then launch the 2nd app.
