### ISSUE TITLE
System.Exception: Something went wrong with cert validation

### ISSUE THREAD

**Issue by awesome1128** [xamarin/xamarin-android#7798]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2019

### Description

> I'm was also having the same issue but after some research trials and errors I found out the solution well it's more like a workaround. The root certificate of Let's encrypt is expired so just remove it from the `yourcert-chain.prem`.
> 
> * Open the file in any text editor
> * Locate the last `-----BEGIN CERTIFICATE-----` at the end of the file
> * Delete it from `-----BEGIN CERTIFICATE-----` to `-----END CERTIFICATE-----`
> * Save and reload the nginx

What do you mean by "yourcert-chain.prem"?
I have cert.pem, chain.pem, fullchain.pem and privkey.pem files only. No any file that file extension is .prem
I deleted last `-----BEGIN CERTIFICATE-----` at the end of the file from fullchain.pem file.
Also , I ran certbot renew --force-renewal --preferred-chain "ISRG Root X1" command as well.

Is that correct?

I have xamarin project, but I don't know well xamarin. 
I am using visual studio 2019 and it's configured with remote server, but I keep getting "**System.Exception:** 'Something went wrong with cert validation" error.
I am spending much time to fix this problem, but no idea.

Please let me know your thoughts, thanks!

### Steps to Reproduce

I have xamarin project, but I don't know well xamarin. 
I am using visual studio 2019 and it's configured with remote server, but I keep getting "**System.Exception:** 'Something went wrong with cert validation" error.
I am spending much time to fix this problem, but no idea.

**Comment by jonathanpeppers** [comment]
@awesome1128 can you make a sample project to illustrate the problem here?

Does it work any better in a .NET 7 Android app? We may be able to get a fix (if needed) from Mono or the BCL in that case.

**Comment by awesome1128** [comment]
Hi thanks!
Actually, I have been spending a lot of time on this problem.
Very hard.

**Comment by awesome1128** [comment]
Also, I tried to install SSL certificate to my apache server using acme.
I was able to install SSL successfully, but still getting System.Exception: 'Something went wrong with cert validation" message in xamarin android app(vs 2019) when I build.
Very headache.
Please help me, what's wrong??
Thanks.

**Comment by jonathanpeppers** [comment]
For us to be able to help you, we need a sample app that illustrates your problem. You can either attach a `.zip` of an example project here. Or linking to a public GitHub repository also works.

Thanks!

**Comment by awesome1128** [comment]
> For us to be able to help you, we need a sample app that illustrates your problem. You can either attach a `.zip` of an example project here. Or linking to a public GitHub repository also works.
> 
> Thanks!

Hi @jonathanpeppers , thanks for your kind reply.
My project needs to be private.
Anyway, I will push my code to my github privately, and then can I invite you via email?
If so, can you let me know your email?
Please let me know, thanks!

**Comment by jonathanpeppers** [comment]
@awesome1128 can you just create a small sample project that illustrates the problem? A new app.

There are not any code examples provided on this issue, so I'm not sure what we can do so far.

**Comment by awesome1128** [comment]
Okay, 
![image](https://user-images.githubusercontent.com/56351793/219504448-c0d27450-5f92-460c-861a-43f44fe48381.png)
![image](https://user-images.githubusercontent.com/56351793/219504563-2304f7d7-7943-48ad-8f6f-a276e701c965.png)

- These are in AppSettings.cs file
public static bool TurnTrustFailureOnWebException = true;
public static bool TurnSecurityProtocolType3072On = true;

- And this is Main Application.cs file.
public override void OnCreate()
        {
            try
            {
                base.OnCreate();
                //A great place to initialize Xamarin.Insights and Dependency Services!
                RegisterActivityLifecycleCallbacks(this);
                Instance = this;

                switch (AppSettings.TurnSecurityProtocolType3072On)
                {
[MainApplication.cs.zip](https://github.com/xamarin/xamarin-android/files/10761564/MainApplication.cs.zip)

                    //Bypass Web Errors 
                    //======================================
                    case true:
                        {
                            ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
                            var client = new HttpClient(new AndroidClientHandler());
                            ServicePointManager.Expect100Continue = true;
                            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls13 | SecurityProtocolType.SystemDefault;
                            Console.WriteLine(client);
                            break;
                        }
                }

                switch (AppSettings.TurnTrustFailureOnWebException)
                {
                    case true:
                        {
                            //If you are Getting this error >>> System.Net.WebException: Error: TrustFailure /// then Set it to true
                            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
                            var b = new AesCryptoServiceProvider();
                            Console.WriteLine(b);
                            break;
                        }
                }

                InitializePlayTube.Initialize(AppSettings.TripleDesAppServiceProvider, PackageName, AppSettings.TurnSecurityProtocolType3072On);

                var sqLiteDatabase = new SqLiteDatabase();
                sqLiteDatabase.Connect();
                sqLiteDatabase.Get_data_Login();

                new Handler(Looper.MainLooper).Post(new Runnable(FirstRunExcite)); 
            }
            catch (Exception exception)
            {
                Methods.DisplayReportResultTrack(exception); 
            }
        }

- I think, problem is this part, but not sure. I am not an expert in xamarin
![image](https://user-images.githubusercontent.com/56351793/219505743-0464d7ef-0787-4368-ac73-88b9a73563a0.png)

- I have attached MainApplication.cs file
Thanks.

**Comment by jonathanpeppers** [comment]
Can you share a `.zip` of the entire project? Then we can just open it and hit F5?

Is this problem specific to Android? or do you have the same issue in a plain Console project?

If this is a general C# question, a Q&A site like StackOverflow might be better suited for asking your question.

**Comment by awesome1128** [comment]
While I build an app, there is no issue.
I get an error when starting the splash screen on app.

https://www.loom.com/share/6dcd2d9bb97b4456bb418d1689a2769b

**Comment by jonathanpeppers** [comment]
If you are investigating a problem with `AndroidClientHandler` can you try the same code in a new app?

I don't understand why you can't reproduce it in sample app?

**Comment by awesome1128** [comment]
Because I am not good at Xamarin app development.
I will create a new app with AndroidClientHandler.

But if you have any demo project for a sample, then I can reproduct it as I want.
Thanks.

**Comment by awesome1128** [comment]
> If you are investigating a problem with `AndroidClientHandler` can you try the same code in a new app?
> 
> I don't understand why you can't reproduce it in sample app?

Hi @jonathanpeppers !
Good morning, how are you?

Here is a sample app, so I can get a response from remote server.
// Create a new post  
var values = new Dictionary<string, string>
{
      { "username", "okay@okay.com" },
      { "password", "aaafff" },
      { "server_key", "1312a113c58715637a94437389326a49" }
};
var content = new FormUrlEncodedContent(values);

var client = new HttpClient(new AndroidClientHandler());
var response = await client.PostAsync("https://elsalvador4ktv.com?v=1.0&type=login&platform=phone", content);
var responseString = await response.Content.ReadAsStringAsync();
Console.WriteLine(responseString);

- And I tried to call API with POST request on Postman tool, so I can get a response from remote server.
![image](https://user-images.githubusercontent.com/56351793/219651160-ef24ca9a-c2b5-4c63-8bd7-6b3d25b21879.png)

Please help me.
Thanks.
[App1.zip](https://github.com/xamarin/xamarin-android/files/10766568/App1.zip)

**Comment by awesome1128** [comment]
> If you are investigating a problem with `AndroidClientHandler` can you try the same code in a new app?
> 
> I don't understand why you can't reproduce it in sample app?

Hi @jonathanpeppers !
Good morning, how are you?

Sample code is attached.
I can get a response from remote server.
And I tried to call API with POST request on Postman tool, so I can get a response from remote server.
![image](https://user-images.githubusercontent.com/56351793/219659456-865edb9c-acfa-4e4f-a6f2-5ded3e35583a.png)


But I get an SSL error in my project.
SSL certificate is valid, it's not expired.
[App1.zip](https://github.com/xamarin/xamarin-android/files/10766922/App1.zip)

Please help me, thanks!

**Comment by awesome1128** [comment]
Hi @jonathanpeppers , are you there?

**Comment by awesome1128** [comment]
@jonathanpeppers , how are you?
