### ISSUE TITLE
GCSettings.LatencyMode and GCSettings.LargeObjectHeapCompactionMode not support on andoird

### ISSUE THREAD

**Issue by OnlyIslam** [xamarin/xamarin-android#7801]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

vs2022 

### Description

when i run . i get error android platform not support this 

### Steps to Reproduce

```
GCSettings.LatencyMode = [GCLatencyMode.SustainedLowLatency;](url)
GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
```

**Comment by jpobst** [comment]
It looks like the .NET Runtime team is tracking this here:
https://github.com/dotnet/runtime/issues/73167

I would suggest adding a comment there about `GCSettings.LargeObjectHeapCompactionMode` since it isn't mentioned in that issue.
