### ISSUE TITLE
Updating NuGet packages does not update the app

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#7890]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

All

### Description

I have noticed that when I update nugets in my maui app, the dll updates do not reach the final device.

### Steps to Reproduce

I have a GitHub Action here with a test case script:
 - source: https://github.com/mattleibow/maui-bug-repros/blob/repro-android-not-updating/.github/workflows/dotnet.yml
 - run: https://github.com/mattleibow/maui-bug-repros/actions/runs/4440605792/jobs/7794616600#step:5:153

1. dotnet new maui
2. dotnet build -f net8.0-android /bl:build-1-initial.binlog
3. dotnet add package Newtonsoft.Json --version 13.0.1
4. dotnet build -f net8.0-android /bl:build-1-after-json.binlog
5. dotnet add package Newtonsoft.Json --version 13.0.3
6. dotnet build -f net8.0-android /bl:build-1-after-update.binlog
7. (Get-Item obj\Debug\net8.0-android\android\assets\Newtonsoft.Json.dll).VersionInfo

The output of 7. is still 13.0.1
 

### Did you find any workaround?

Rebuild

### Relevant log output

```shell
https://github.com/mattleibow/maui-bug-repros/actions/runs/4440605792/jobs/7794616600#step:5:153
```

**Comment by jonathanpeppers** [comment]
Oh snap, this test is disabled in .NET 6+:

https://github.com/xamarin/xamarin-android/blob/0e4c29aabb2af023d3ff66f02d42c2b487575d85/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs#L984-L988

It must have been broken because it uses Xamarin.Forms.

So something maybe has been wrong here since .NET 6?

**Comment by dellis1972** [comment]
I'll update that test to make use of say NewtonSoft.Json it probably doesn't need to be Xamrain.Forms
