### ISSUE TITLE
[Marshal Methods] MAUI project infinite loop on startup

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#7893]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

.NET 8 Preview 2

### Description

A customer's app won't get past the splash screen when built in Release mode:

![image](https://user-images.githubusercontent.com/840039/225991427-7cee6656-0327-4855-98b6-2df9e56d2faa.png)

But it appears to work if you set `AndroidEnableMarshalMethods=false`.

### Steps to Reproduce

1. I can share the sample with you privately in Teams
2. Run the app in Release mode. It can be a fresh/clean build, so not an incremental build issue.

### Did you find any workaround?

`AndroidEnableMarshalMethods=false`

### Relevant log output

The log just kind of gets here... And stops?
```shell
03-15 23:25:52.948 14320 14320 D Mono    : AOT: FOUND method Microsoft.Maui.WeakList`1/<>c:<CleanupIfNeeded>b__12_0 (System.WeakReference`1<T>) [0x7b4e6fcfd530 - 0x7b4e6fcfd5f7 0x7b4e6fd39ba3]
```

[log.txt](https://github.com/xamarin/xamarin-android/files/11004696/log.txt)

**Comment by 333fred** [comment]
Thanks for the investigation Jon!

**Comment by daltzctr** [comment]
I've also ran into this issue as well. The above workaround solves it.

**Comment by jpobst** [comment]
We are turning off `AndroidEnableMarshalMethods` for .NET 8.  Bumping to .NET 9 when we will try to fix and finish the feature.

**Comment by jpobst** [comment]
Tracking via https://github.com/xamarin/xamarin-android/issues/8253.
