### ISSUE TITLE
Audit remaining unported Classic test suites

### ISSUE THREAD

**Issue by jpobst** [xamarin/xamarin-android#7906]
We are removing "Classic" Xamarin.Android code from the `main` branch.  "Classic" will continue to be maintained for the remainder of its supported lifetime out of existing branch(es).  (Currently [d17-5](https://github.com/xamarin/xamarin-android/tree/d17-5))

The following test suites do not currently have .NET equivalents.  We need to determine if they should be ported to .NET or if they are no longer relevant and can be removed.

- Xamarin.Android.JcwGen-Tests.csproj
  - https://github.com/xamarin/xamarin-android/pull/7949
- Xamarin.Android.JcwGen-Tests.csproj /p:AndroidFastDeploymentType=Assemblies:Dexes
  - https://github.com/xamarin/xamarin-android/pull/7949
- Xamarin.Android.Locale-Tests.csproj
- Xamarin.Android.Locale-Tests.csproj /p:AotAssemblies=True
- Xamarin.Android.Locale-Tests.csproj /p:AotAssemblies=True /p:AndroidEnableProfiledAot=true
- EmbeddedDSO.csproj
- Xamarin.Forms.Performance.Integration.Droid.csproj
- Xamarin.Forms.Performance.Integration.Droid.csproj /p:AotAssemblies=true
- Xamarin.Forms.Performance.Integration.Droid.csproj /p:AotAssemblies=True /p:AndroidEnableProfiledAot=true
- VSAndroidAppProxy.csproj
- Xamarin.Android.Bcl-Tests.csproj

**Comment by jonpryor** [comment]
@dellis1972: is there a need for `tests/locales`/`Xamarin.Android.Locale-Tests*.csproj`?  We have existing localization tests which appear to run under .NET 7+, e.g. PR #6693, so are these projects duplciative?

**Comment by jonpryor** [comment]
@steveisok: do we want to run the dotnet/runtime BCL tests in a .NET Android environment?  Or is that not a huge concern?

If it is a concern,  what's the "sanest" way to do that?

**Comment by dellis1972** [comment]
> @dellis1972: is there a need for `tests/locales`/`Xamarin.Android.Locale-Tests*.csproj`? We have existing localization tests which appear to run under .NET 7+, e.g. PR #6693, so are these projects duplciative?

Looks like there might be some tests in there we should port to the more comprehensive tests we have in #6693, e.g the Environment tests and the Globalisation checks.

**Comment by jpobst** [comment]
If we aren't running them by now, they must not be important.  ;)

Closing.
