### ISSUE TITLE
March 2023 Pixel 6 Security/Feature Update breaks Predictive Back Gesture 

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#7917]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 2022 17.6.0 Prev 2

### Description

There appears to be a problem created by the March 2023 Pixel 6 Security/Features Upgrade to a Pixel 6. I’d be interested to find out if it applies in all countries and to all Android 13 Pixel devices or if it is restricted to the updates that Australia (and maybe some other countries) receive or does this apply irrespective of your country/carrier.

I’m providing two test apps based on Android Studio’s start template BasicActivity(Material3) an Android and a Net7 version. On my Pixel 6, they both exhibit the same behaviour – there are most times no Predictive Back Gestures when I swipe to exit. Occasionally, either will produce a perfectly normal-looking PBG, but when you attempt to repeat it, you can’t. Sometimes clearing it from memory allows it again, but in my testing never more than once.

I have a couple of Samsung devices running Android 13 and there are no problems with either of them they both produce the PBG every time with each app.

Neither app has an active OnBackPressedCallback, so theoretically they both should show the PBG when exiting.
Obviously, this is not a net7.0-android problem, but I’m very interested to know if it applies to all Pixel devices that have received the March update.

Previously my Pixel 6 displayed the PBG with the following Google apps Calculator, Calendar, Google News, Phone, Google TV and Settings – maybe others, I now can’t remember. The above two apps were also ok, now only Calculator, Calendar, Google TV and Settings do.
 
Does anyone know where this should be reported to Google?

 Tip: To get the best possible PBG animations, create shortcuts for the apps on the Home Screen. Extra animations as compared to when launched from the app drawer if your app doesn’t reside alphabetically in the top part of the app drawer.

To test, make sure to turn on Predictive back animations in Developer Settings on your Android 13 devices.

https://github.com/gmck/BasicActivityM3Net7

https://github.com/gmck/BasicActivityM3

### Steps to Reproduce

See above

### Did you find any workaround?

No

### Relevant log output

```shell
N/A
```

**Comment by jpobst** [comment]
Closing as this does not seem related to .NET for Android.
