### ISSUE TITLE
Firebase push notifications - FATAL UNHANDLED EXCEPTION Make sure to call FirebaseApp.initializeApp(Context) first

### ISSUE THREAD

**Issue by LinMoskovitch** [xamarin/xamarin-android#7918]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

JetBrains Rider 2022.3.3

### Description

When trying to implement a cross-platform push notification application on Xamarin, after following many youtube guides and docs on how to implement it with FCM, the android application crashes on `[ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.notify.notify. Make sure to call FirebaseApp.initializeApp(Context) first.`

I tried almost every suggestion on how to solve this issue that I found on the web but it seems like nothing hasn't worked for me,
I am not sure if those solutions are deprecated or not.

Thank you very much for your help.

### Steps to Reproduce

1. Install NuGet package 3.3.10 (their last stable release is 3.4.35 - but it didn't work either)
2. followed exactly step by step this guide https://www.youtube.com/watch?v=1Ixc_B86mDk&ab_channel=XamarinUIDesigns
Also, Gerald's guides didn't help either :  https://www.youtube.com/watch?v=7w2q2D6mR7g&ab_channel=GeraldVersluis
https://www.youtube.com/watch?v=VI1wgekz5ZM&ab_channel=GeraldVersluis
3.Tried various of android api's - now on API 33 on Pixel 5

App crashes every time.

### Did you find any workaround?

Unfortunately no

### Relevant log output

```shell
03-25 00:06:38.401 D/BoundBrokerSvc( 5397): onUnbind: Intent { act=com.google.android.gms.potokens.service.START dat=chimera-action:com.google.android.gms.potokens.service.START cmp=com.google.android.gms/.chimera.GmsApiService }
03-25 00:06:38.408 D/BoundBrokerSvc( 5397): onBind: Intent { act=com.google.android.gms.potokens.service.START dat=chimera-action:com.google.android.gms.potokens.service.START cmp=com.google.android.gms/.chimera.GmsApiService }
03-25 00:06:38.408 D/BoundBrokerSvc( 5397): Loading bound service for intent: Intent { act=com.google.android.gms.potokens.service.START dat=chimera-action:com.google.android.gms.potokens.service.START cmp=com.google.android.gms/.chimera.GmsApiService }
03-25 00:06:38.408 E/JavaBinder( 8537): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1028)
03-25 00:06:38.408 W/GmsClient( 8537): IGmsServiceBroker.getService failed
03-25 00:06:38.408 W/GmsClient( 8537): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
03-25 00:06:38.408 W/GmsClient( 8537): 	at android.os.BinderProxy.transactNative(Native Method)
03-25 00:06:38.408 W/GmsClient( 8537): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
03-25 00:06:38.408 W/GmsClient( 8537): 	at lvm.A(PG:15)
03-25 00:06:38.408 W/GmsClient( 8537): 	at kuh.run(PG:44)
03-25 00:06:38.408 W/GmsClient( 8537): 	at android.os.Handler.handleCallback(Handler.java:942)
03-25 00:06:38.408 W/GmsClient( 8537): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-25 00:06:38.408 W/GmsClient( 8537): 	at android.os.Looper.loopOnce(Looper.java:201)
03-25 00:06:38.408 W/GmsClient( 8537): 	at android.os.Looper.loop(Looper.java:288)
03-25 00:06:38.408 W/GmsClient( 8537): 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-25 00:06:38.409 E/JavaBinder( 8537): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 400)
03-25 00:06:38.409 W/GmsClient( 8537): IGmsServiceBroker.getService failed
03-25 00:06:38.409 W/GmsClient( 8537): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
03-25 00:06:39.120 W/GmsClient( 8406): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffer
03-25 00:06:40.087 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Arch.Core.Common.dll
03-25 00:06:40.219 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Arch.Core.Runtime.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Arch.Lifecycle.Common.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Arch.Lifecycle.LiveData.Core.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Arch.Lifecycle.LiveData.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Arch.Lifecycle.Runtime.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Arch.Lifecycle.ViewModel.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Annotations.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.AsyncLayoutInflater.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Collections.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Compat.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.CoordinaterLayout.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Core.UI.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Core.Utils.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.CursorAdapter.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.CustomView.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.DocumentFile.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.DrawerLayout.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Fragment.dll
03-25 00:06:40.220 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Interpolator.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Loader.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.LocalBroadcastManager.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Media.Compat.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.Print.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.SlidingPaneLayout.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.SwipeRefreshLayout.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.v4.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.v7.CardView.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.VersionedParcelable.dll
03-25 00:06:40.221 W/monodroid-assembly( 9259): open_from_bundles: failed to load assembly Xamarin.Android.Support.ViewPager.dll
03-25 00:06:40.230 W/monodroid-gc( 9259): GREF GC Threshold: 46080
03-25 00:06:41.337 W/m.notify.notify( 9259): Attempt to remove non-JNI local reference, dumping thread
03-25 00:06:41.926 W/FirebaseApp( 9259): Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
03-25 00:06:41.926 I/FirebaseInitProvider( 9259): FirebaseApp initialization unsuccessful
```

**Comment by OfirMatasas** [comment]
I'm having a similar problem using Visual Studio 2022 for Mac.

When I'm starting my Android application, I get the next error messages:
[FirebaseMessaging] Failed to sync topics. Won't retry sync. java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE [FirebaseMessaging] Topic sync or token retrieval failed on hard failure exceptions: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE. Won't retry the operation.

**Comment by OfirMatasas** [comment]
I'm having the same problem using Visual Studio 2022 for Mac.

**Comment by DekelR** [comment]
I had almost the same issue as the one above...

**Comment by grendello** [comment]
@LinMoskovitch since you can already reproduce the issue, could you please create and attach a simple repro app so that we can reproduce it locally. Thanks!

**Comment by LinMoskovitch** [comment]
Hi, This is the repo https://github.com/OfirMatasas/Notify
You can easily reproduce the error by running/debugging the Notify.Android project.
Thank you for your reference

**Comment by dellis1972** [comment]
I am not able to repo using the app in the link provided. I can run up the app is VSforMac and debug without any issue.
I can confirm this app is using some old packages, so its possible that something in those older packages will no longer work.

**Comment by dellis1972** [comment]
Firebase based apps usually have a google-services.json file (or something similar) which controls the API keys etc. I'm not seeing that in the branch. Was it excluded on purpose?

I would expect to see an item in the csproj like 

```
<ItemGroup>
    <GoogleServicesJson Include="google-services.json" />
</ItemGroup>
```

**Comment by LinMoskovitch** [comment]
> Firebase based apps usually have a google-services.json file (or something similar) which controls the API keys etc. I'm not seeing that in the branch. Was it excluded on purpose?
> 
> I would expect to see an item in the csproj like
> 
> ```
> <ItemGroup>
>     <GoogleServicesJson Include="google-services.json" />
> </ItemGroup>
> ```

It was on purpose to prevent data leaking, can you please try again now? you should see the json now as well as in the .csjproj

**Comment by dellis1972** [comment]
So I added my own google-services.json and at first I got a crash. But it turned out my emulator did not have the google api's installed. So I tried one which did and saw the following in the logs.

```
03-27 12:58:26.313  6612  6612 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
03-27 12:58:26.430  6612  6612 I FirebaseInitProvider: FirebaseApp initialization successful
```

However the app did crash later on with 

```
03-27 12:58:27.207  6612  6612 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.ShellFlyoutTemplatedContentRenderer.LoadView (Xamarin.Forms.Platform.Android.IShellContext shellContext) [0x0006f] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.ShellFlyoutTemplatedContentRenderer..ctor (Xamarin.Forms.Platform.Android.IShellContext shellContext) [0x0000d] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.ShellRenderer.CreateShellFlyoutContentRenderer () [0x00000] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.ShellRenderer.Xamarin.Forms.Platform.Android.IShellContext.CreateShellFlyoutContentRenderer () [0x00000] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.ShellFlyoutRenderer.AttachFlyout (Xamarin.Forms.Platform.Android.IShellContext context, Android.Views.View content) [0x00025] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.ShellFlyoutRenderer.Xamarin.Forms.Platform.Android.IShellFlyoutRenderer.AttachFlyout (Xamarin.Forms.Platform.Android.IShellContext context, Android.Views.View content) [0x00000] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.ShellRenderer.OnElementSet (Xamarin.Forms.Shell shell) [0x0008c] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.ShellRenderer.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x0003d] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0003e] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.AppCompat.Platform.AddChild (Xamarin.Forms.Page page, System.Boolean layout) [0x0000d] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPageInternal (Xamarin.Forms.Page newRoot) [0x00061] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPage (Xamarin.Forms.Page newRoot) [0x000e6] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage (Xamarin.Forms.Page page) [0x0003f] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage () [0x0000c] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication (Xamarin.Forms.Application application) [0x00140] in <bcfa7be6a34b4ba48a6d4c79773cfa11>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Notify.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0007c] in <afbd27fa4d184151b90f604ab8d19aee>:0 
03-27 12:58:27.207  6612  6612 E AndroidRuntime:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <2bd7f7c71d9f48c1979033a1d383463e>:0 
```

**Comment by LinMoskovitch** [comment]
After downgrading the emulator API to API 31 and installing some google services packages from the SDK manager, i get this build error : 

`  Xamarin.GooglePlayServices.Basement.targets(71, 3): [MSB4018] The "ProcessGoogleServicesJson" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.GooglePlayServices.Tasks.ProcessGoogleServicesJson.Execute () [0x0033c] in <d754b368411c4152abad84ee299d9f47>:0 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <6f1ac64b362443459ae7e79676b4c67f>:0 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in <6f1ac64b362443459ae7e79676b4c67f>:0 `
  
  Do you know how to solve this? Can you please share your SDK settings and NuGet package versions? maybe it is related to that

**Comment by dellis1972** [comment]
@LinMoskovitch 

I got that error when I tried to use your google-services.json, there was a warning in the list which said it could not filed the "client_id" or something. So I think the .json file you are using is not the right one or has the wrong format. So I created one for myself on my own google firebase account. 

I didn't make any other changes to your app, just replaced the json file and changed the package id in the AndroidManifest.xml to match my settings package id.

i would go to your firebase console https://console.firebase.google.com/ and try downloading one again.

**Comment by LinMoskovitch** [comment]
@dellis1972 
Hi, after a week of trying to troubleshoot the error Im still stuck on `[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.`

I can't find any solution on the web for this.
Maybe you or someone else here can help me solve this?

**Comment by dellis1972** [comment]
@LinMoskovitch 

For me that Error was because the `google-services.json` did not have the right content. 
It was missing the `client_info` section which the `` processor is expecting. So you should have a section 
like this in your json file. 

```
"client_info": {
        "mobilesdk_app_id": "<foo>",
        "android_client_info": {
          "package_name": "<packagename>"
        }
      },
```

I followed these instructions to get the appropriate json file https://support.google.com/firebase/answer/7015592?hl=en#android&zippy=%2Cin-this-article

**Comment by LinMoskovitch** [comment]
> @LinMoskovitch
> 
> For me that Error was because the `google-services.json` did not have the right content. It was missing the `client_info` section which the `` processor is expecting. So you should have a section like this in your json file.
> 
> ```
> "client_info": {
>         "mobilesdk_app_id": "<foo>",
>         "android_client_info": {
>           "package_name": "<packagename>"
>         }
>       },
> ```
> 
> I followed these instructions to get the appropriate JSON file https://support.google.com/firebase/answer/7015592?hl=en#android&zippy=%2Cin-this-article

I have followed these instructions as well and verified I have the `client_info` section in my `google-services.json`
Still, it doesn't work.
Is there something else I should try?

**Comment by dellis1972** [comment]
@moljac any ideas on this one? Looks like there might be a bug in https://github.com/xamarin/GooglePlayServicesComponents/blob/d72add8573e5b63dda71ac6b31d3dbdea8b36d67/source/com.google.android.gms/play-services-basement/buildtasks/ProcessGoogleServicesJson.cs#L12 somewhere.

**Comment by LinMoskovitch** [comment]
Someone has any idea?

**Comment by dellis1972** [comment]
@LinMoskovitch 

At this point I think the only thing to try is to repo with your json file. 
Did you want to send it to me? (rather than put it in your public repo). Or create a private repo and add it there then give me access.

**Comment by moljac** [comment]
> @moljac any ideas on this one? Looks like there might be a bug in https://github.com/xamarin/GooglePlayServicesComponents/blob/d72add8573e5b63dda71ac6b31d3dbdea8b36d67/source/com.google.android.gms/play-services-basement/buildtasks/ProcessGoogleServicesJson.cs#L12 somewhere.

I have never dived deeper into that area, especially MsBuild custom task. Yes it looks like it fails during deserializing/parsing config file.

**Comment by LinMoskovitch** [comment]
> @LinMoskovitch
> 
> At this point I think the only thing to try is to repo with your json file. Did you want to send it to me? (rather than put it in your public repo). Or create a private repo and add it there then give me access.


I will do that and send you.
