### ISSUE TITLE
Binded services only call OnBind the first time

### ISSUE THREAD

**Issue by danardelean** [xamarin/xamarin-android#7923]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS MAC 17.5.2 (build 14)

### Description

When using a Binded Service the OnBind method is called only for the first connection to the service. The other will not call it. I have verified on Xamarin.Android this was working correctly

### Steps to Reproduce

Clone https://github.com/danardelean/BindedServiceBug

TheService and TheClient application both do BindService on the SampleService.

SampleService will present a Toast each time OnBind is executed. 

I will expect to have 2 toasts but I have only one (the first activity that binds the service is the one that will do the toast). There is no subsequent call to OnBind when the second service binds SampleService

**Comment by jonpryor** [comment]
This is documented behavior; as per [Bound services overview](https://developer.android.com/guide/components/bound-services):

> You can connect multiple clients to a service simultaneously. However, the system caches the `IBinder` service communication channel. In other words, the system calls the service's [`onBind()`](https://developer.android.com/reference/android/app/Service#onBind(android.content.Intent)) method to generate the `IBinder` only when the first client binds. The system then delivers that same `IBinder` to all additional clients that bind to that same service, without calling `onBind()` again.

**Comment by danardelean** [comment]
Thanks
