### ISSUE TITLE
Throw exception when project reference the dll which was not contain the aar file

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-android#7960]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

17.5.4 (build 8)

### Description

Dependent on this project
https://github.com/xamarin/xamarin-android/issues/7959

The maui android project will throw exception.
[ExceptionLog.txt](https://github.com/xamarin/xamarin-android/files/11233156/ExceptionLog.txt)

### Steps to Reproduce

[Archive.zip](https://github.com/xamarin/xamarin-android/files/11233172/Archive.zip)

1.Open the project .sln by used the vs mac.
2.Run the project (Due to it reference the dll which is not contain the aar)
3.Throw exception.

### Did you find any workaround?

no

**Comment by jpobst** [comment]
This was resolved on Discord.  The issue was the same as:
https://github.com/xamarin/xamarin-android/issues/7952#issuecomment-1505411745
