### ISSUE TITLE
"NETSDK1136: The target platform must be set to Windows" when compiling net7.0-android project

### ISSUE THREAD

**Issue by vividos** [xamarin/xamarin-android#7987]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

.NET SDK 7.0.202

### Description

(this description came from the discussion found here: https://github.com/dotnet/maui/discussions/14598)
I'm trying out if compiling Xamarin.Forms apps on Android using net7.0-android work. For that, I created an empty "Android Application" project (not an "Android App (Xamarin)"), and it generates me a nice `net7.0-android` targeted app project.

My next step was to create a "Mobile App (Xamarin.Forms)", which creates me the platform specific project(s) and a `netstandard2.0` project with Forms code in it. I immediately throw away the platform specific projects, as I want to use the `net7.0-android` project for building. I have to copy over some code in `MainActivity.cs` from the non-SDK-style Android project (e.g. deriving from `FormsAppCompatActivity`, calling `Forms.Init()` and loading the Forms app). Everything compiles, links and deploys and I get a basic Forms app using .NET 7. I know that compiling Xamarin.Forms using `net7.0-android` is not officially supported, but for now it seems to work.

I'm adding some more NuGet packages, which most of them not aware of the new .NET 5/6/7 world, since they were created in the Xamarin.Forms era. After some of the NuGet packages are added, the NETSDK1136 error appears, saying I must target `net7.0-windows` as well. From my tests, it seems that `Xamarin.CommunityToolkit` is the bad one.

### Steps to Reproduce

1. Create an Android app project targeting `net7.0-android`
2. Add a `netstandard2.0` project and add Xamarin.Forms to both
3. Adjust MainActivity.cs so that it compiles
4. Add `Xamarin.CommunityToolkit` to the `netstandard2.0` project
5. Compile and see the NETSDK1136 error

### Did you find any workaround?

No

### Relevant log output

```shell
Target _CheckForTransitiveWindowsDesktopDependencies:
  Using "NetSdkError" task from assembly "C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk\targets\..\tools\net472\Microsoft.NET.Build.Tasks.dll".
  Task "NetSdkError"
    C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.Shared.targets(250,5): error NETSDK1136: The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so.
  Done executing task "NetSdkError" -- FAILED.
Done building target "_CheckForTransitiveWindowsDesktopDependencies" in project "Net7AndroidAppTest.csproj" -- FAILED.
```

**Comment by jonathanpeppers** [comment]
Xamarin.Forms is not supported in .NET 6+. The `NETSDK1136` error would be coming from the .NET SDK and not this repo, but maybe you could either share a sample project or [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) and we could help further.

**Comment by vividos** [comment]
I'll prepare a sample repo

**Comment by vividos** [comment]
Here's the sample project, GitHub repository https://github.com/vividos/SampleProjects, subfolder [NetSdk1136Android](https://github.com/vividos/SampleProjects/tree/main/NetSdk1136Android). The first commit adds the Android and Forms Core project, which compiles without errors (but slow), and the second commit adds Xamarin.CommunityToolkit, which triggers the error.

**Comment by jonathanpeppers** [comment]
The project builds for me once I added this to `Net7AndroidTestApp.csproj`:

```xml
<DisableTransitiveFrameworkReferences>true</DisableTransitiveFrameworkReferences>
```

Something in the Xamarin community toolkit is pulling in WinForms/WPF, but I couldn't figure out what exactly is happening.

You're definitely in unsupported territory, so I'd recommend migrating to .NET MAUI when you can.

Hope that helps!
