### ISSUE TITLE
"Legacy" HttpClient implementation build failure

### ISSUE THREAD

**Issue by cncb-gh** [xamarin/xamarin-android#8014]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 v17.5.5

### Description

When trying to build with the "Legacy" HttpClient implementation selected I now get the following error:

error XA1031: The 'AndroidHttpClientHandlerType' property value 'System.Net.Http.MonoWebRequestHandler' must derive from 'System.Net.Http.HttpClientHandler'

This must be due to some recent update since it worked a month ago.  It builds fine when I select "Managed" or "Android" as the HttpClient implementation but my app works well with Legacy and I would rather not re-write it.  Thanks.

### Steps to Reproduce

Select "Legacy" for the Android project HttpClient implementation and you will get a build failure.

**Comment by jonathanpeppers** [comment]
What value are you setting for `AndroidHttpClientHandlerType`?

Reading the change in 311b41e864a0162895d079477cb9398fbec5ca6e. The valid value is `System.Net.Http.HttpMessageHandler, System.Net.Http`?

This doesn't look like a valid `HttpMessageHandler`?

https://github.com/mono/mono/blob/3005442218bc1edbeb309cde746067b8f34ecde7/mcs/class/System.Net.Http/MonoWebRequestHandler.cs#L44

(it looks like some internal class)

**Comment by cncb-gh** [comment]
I am choosing "Legacy" in the drop-down which sets it to:

<AndroidHttpClientHandlerType>System.Net.Http.MonoWebRequestHandler, System.Net.Http</AndroidHttpClientHandlerType>

This has been working for years?  

I just tried manually editing it to System.Net.Http.HttpMessageHandler but get the same build error.

**Comment by cncb-gh** [comment]
OK, I manually set it to System.Net.Http.HttpClientHandler and now it builds fine.  I guess the "Legacy" choice in VS needs to be modified to set it to this. Thanks.

**Comment by cncb-gh** [comment]
Sorry, I still need help with this.  I still need the "Legacy" handler for my app.  Is there a way to use this?

**Comment by jonathanpeppers** [comment]
In .NET 6+, your options are `UseNativeHttpHandler` set to `true` or `false`. The default is `true`, using `AndroidMessageHandler` and `false` uses Mono's handler.

`AndroidHttpClientHandlerType` can also be used, but it does the same thing.

**Comment by JeroenBer** [comment]
I can confirm this is a bug, I have the same problem after recently updating VS and Xamarin Classic. This no longer builds in Xamarin classic and there are purposes when you might need the old Mono Legacy implementation because of old compatibility reasons (e.g. NTLM support).

**Comment by JeroenBer** [comment]
As a workaround I used this in code to force getting the legacy implementation:
https://github.com/EgorBo/NtlmHttpHandler/blob/master/NtlmHttpHandlerFactory.cs

**Comment by cncb-gh** [comment]
> As a workaround I used this in code to force getting the legacy implementation: https://github.com/EgorBo/NtlmHttpHandler/blob/master/NtlmHttpHandlerFactory.cs

Thank you for sharing this.  It works for me.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
