### ISSUE TITLE
Xamarin Android Timezone Conversion doesn't work on Android 14 beta (UpsideDownCake)

### ISSUE THREAD

**Issue by JeroenBer** [xamarin/xamarin-android#8028]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022, 17.5.4, Xamarin.Android SDK 13.2.0.0

### Description

Customers of our product noticed that datetimes were no longer correct when running on Android 14 beta (UpsideDownCake). After investigation it seems that System.TimeZoneInfo functions are no longer working correct on Android 14 beta. E.g. System.TimeZoneInfo.CovertTime, System.TimeZoneInfo.IsInvalidTime, System.TimeZoneInfo.IsAmbiguousTime etc.

I created a test project you can find it here:
https://github.com/JeroenBer/TestTimezoneConversion

NOTE 
The failure only occurs in Classic Xamarin Android (we are using that), not in .NET 7 Android.

### Steps to Reproduce

- Download sourcecode from repo: https://github.com/JeroenBer/TestTimezoneConversion
- Compile in VS2022 and run the project TestTimezoneConversion.Xamarin on a Android 13 device or lower and all tests succeed.
- Run the program on Android 14 beta and some Timezone conversion tests will fail.

### Did you find any workaround?

I created a function to use the Android SDK to do timezone calculations, see TimeZoneConverterAndroidOffset.cs, it's unit tests are succesfull on Android 13 and 14 beta.

**Comment by LBally** [comment]
I am seeing this same issue in Xamarin Forms. Many packages used in the project are also affected by this issue and therefore working around this issue myself allows me to fix it for my own code but doesn't solve anything external and therefore causes the application to fall over elsewhere.
The only way to fix this completely is to move to Maui and .net 7. 

Many applications on the store will therefore be potentially broken by this issue as there isnt any support for apps below .net 7 on Android 14 in terms of time.

Is there any news on if this mono issue will be fixed when the Android 14 release goes live?

**Comment by akoeplinger** [comment]
Fixed by https://github.com/mono/mono/pull/21682 which was included in https://github.com/xamarin/xamarin-android/pull/8216.

**Comment by steveisok** [comment]
> Is there any news on if this mono issue will be fixed when the Android 14 release goes live?

We're working on the release details now. Not sure when, but I expect it to be as quick as possible.

**Comment by jonpryor** [comment]
Visual Studio 17.7 shipped on August 8, 2023, and includes Xamarin.Android 13.2.1.2, which fixes this issue.
