### ISSUE TITLE
Static virtual interface methods not called on the base interface

### ISSUE THREAD

**Issue by vyacheslav-volkov** [xamarin/xamarin-android#8038]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

Version: 13.2.0.0

### Description

Static virtual interface methods not called on the base interface, it works for net7.0.

### Steps to Reproduce

1. Create an android app.
2. Run this code and it will fail with the NotSupportedException:
```
public interface ITestVirtualStaticBase
{
    static virtual string Test() => throw new NotSupportedException();
}

public interface ITestVirtualStatic : ITestVirtualStaticBase
{
    static string ITestVirtualStaticBase.Test() => "Test";
}

[Activity(Label = "@string/app_name", MainLauncher = true)]
public class MainActivity : Activity
{
    public static string Test<T>() where T : ITestVirtualStaticBase => T.Test();

    protected override void OnCreate(Bundle? savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        var test = Test<ITestVirtualStatic>(); //throws NotSupportedException instead of "Test" value
    }
}
```

**Comment by jpobst** [comment]
I think this is an issue in the Mono runtime and will need to be filed in [`dotnet/runtime`](https://github.com/dotnet/runtime).  If I understand correctly, they may already be tracking it for .NET 8:

- https://github.com/dotnet/runtime/issues/49904
- https://github.com/dotnet/runtime/issues/67540
