### ISSUE TITLE
`java.time` package not bound in `Mono.Android`

### ISSUE THREAD

**Issue by xpfr** [xamarin/xamarin-android#8081]
Since https://github.com/xamarin/XamarinComponents/pull/1180 got merged, I think this can now be closed.

_Originally posted by @4brunu in https://github.com/xamarin/xamarin-android/issues/5523#issuecomment-850896737_

Still facing the same issue.

**Comment by xpfr** [comment]
To reproduce:

Create a binding library in net6-android over a .aar having desugaring support (https://developer.android.com/studio/write/java8-support) using:

"Microsoft Visual Studio Community 2022
Version 17.6.2
VisualStudio.17.Release/17.6.2+33723.286
Microsoft .NET Framework
Version 4.8.09032
Gestionnaire de package NuGet   6.6.0
Xamarin   17.6.0.251 (d17-6@318364c)
Xamarin Designer   17.6.6.0 (remotes/origin/d17-6@cb430751d1)
Xamarin Templates   17.6.32 (98c12a2)
Xamarin.Android SDK   13.2.0.6 (d17-5/a200af1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77"

Building the binding library gives below error:
warning BG8605: The Java type 'java.time.LocalDate' could not be found (are you missing a Java reference jar/aar or a Java binding library NuGet?)
Related methods are then removed from the bindings:
The method '[Method] <package>.CalendarDay copy(java.time.LocalDate date, com.kizitonwose.calendar.core.DayPosition position)' was removed because the Java parameter type 'java.time.LocalDate' could not be found.

Tried a few things without success:
- add the package created in this issue : https://github.com/xamarin/XamarinComponents/pull/1180
- add jar file "desugar_jdk_libs-2.0.3.jar" to the project

Thank you for the support

**Comment by jpobst** [comment]
The `java.time` package is not bound, and thus no API that relies on it can be bound:
https://github.com/xamarin/xamarin-android/blob/main/src/Mono.Android/metadata#L1340-L1342

The commit from 6 years ago doesn't say why it wasn't bound.  I guess we could try it and see what the issues are.

**Comment by jpobst** [comment]
I think the only thing you can do is write a new Java API that wraps the existing API without exposing `Instant` or `LocalDateTime`, and then bind that API.

Something like:

```java
public void doThing (string localDateTime)
{
  var dt = LocalDateTime.parse (localDateTime);
  doRealThing (dt);
}
```

**Comment by jpobst** [comment]
There is no way to do it in C#, unless you try to bind it by hand yourself.  (I can't help with that.)

If you are using .NET 7+, you can add a loose `.java` file to your application that wraps the API as a `AndroidJavaSource` file and it will automatically get compiled and bound:

https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-items#androidjavasource

Note that it will not show up in Intellisense which is quite annoying, but it does work when you run your application:
https://github.com/xamarin/xamarin-android/issues/7692
