### ISSUE TITLE
_XARemapMembersFilePath is not being treated as a path in the obj folder

### ISSUE THREAD

**Issue by Archit-Pikle** [xamarin/xamarin-android#8095]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 17.6.0 Preview 7.0

### Description

The xa-internal/xa-remam-members.xml created for each build is not being treated as a path in the `obj` folder but is rather being configured as a relative path.
This is causing the file to be added in git changelog.

The workaround we are using is to explicitly add the file in our .gitignore file.

We think this is happening because `MonoAndroidAssetsDirIntermediate` is defined after defining `_XARemapMembersFilePath` in https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

### Steps to Reproduce

1. Create a .NET App for a github project.
2. Make some changes, build and deploy the app.

Expected: `xa-internal/xa-reamp-members.xml` should not be included in the git changelog.
Actual: `xa-internal/xa-remap-members.xml` is included in the git changelog.

### Did you find any workaround?

The workaround is to explicitly add `xa-internal/xa-remap-members.xml` in the .gitignore file

**Comment by jonathanpeppers** [comment]
Similar question as: https://github.com/xamarin/xamarin-android/issues/8096#issuecomment-1572866401

Does this happen if you remove: https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/9.5.2-beta2

**Comment by Archit-Pikle** [comment]
Yes this too goes away if we remove the https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/9.5.2-beta2 dependency from the project

**Comment by Archit-Pikle** [comment]
I'm still able to repro this issue on a .NET 7 app. However, this is resolved on a .NET 8 app.
Is this by design?

**Comment by jonpryor** [comment]
@Archit-Pikle [asked](https://github.com/xamarin/xamarin-android/issues/8095#issuecomment-1819778666):

> Is this by design?

Largely, yes.  Even when using .NET 8, the .NET 7 support is almost entirely separate from the .NET 8 build system.  (Implementation-wise, the [.NET 8 workload references the .NET 7 workload packages](https://github.com/xamarin/xamarin-android/blob/81001af1e533f186a5766fb968eb5482669eb651/src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json#L8).). Thus, in order for *any* .NET 7 build to get build-system fixes, those fixes need to be applied to the release/7.0.4xx branch, a new .NET 7 build released, and the .NET 8 workload updated to reference the new .NET 7 bits.

Changes present in the .NET 8 workload do not apply to .NET 7 builds, even when multitargeting from a .NET 8 installation.
