### ISSUE TITLE
The value parameter of "Java.Lang.Object operator float" should be nullable

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-android#8115]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), .NET Android (net7.0-android, etc.)

### Affected platform version

All

### Description

In https://github.com/xamarin/xamarin-android/blob/main/src/Mono.Android/Java.Lang/Object.cs
```c#
		public static explicit operator float (Java.Lang.Object value)
		{
			return Convert.ToSingle (value, CultureInfo.InvariantCulture);
		}
```

Should be instead:
```c#
public static explicit operator float? (Java.Lang.Object? value)
```
Or a new operator should be added, that takes an Object?  and results in a float?

An example of where this evolution is useful is when using the camera2 api:

```c#
using var cameraCharacteristics = cameraManager.GetCameraCharacteristics(cameraId);

//This line triggers a warning because the implicit float operator don't have a nullable parameter
var lensInfoMinimumFocusDistance = (float?)cameraCharacteristics.Get(CameraCharacteristics.LensInfoMinimumFocusDistance); 
```

`cameraCharacteristics.Get` returns an Object?.

`Convert.ToSingle(value, ...)` correctly checks for a null value, even if it's not annotated.

### Steps to Reproduce

See above

**Comment by jonpryor** [comment]
…and [I had a thinko](https://github.com/xamarin/xamarin-android/issues/8115#issuecomment-1582996287).

The problem is that this code current compiles, *and* compiles without warnings:

```csharp
```

**Comment by jonpryor** [comment]
…and [I had a thinko](https://github.com/xamarin/xamarin-android/issues/8115#issuecomment-1582996287).

The problem is that the following code fragment current compiles, *and* compiles without warnings:

```csharp
Java.Lang.Object o = 42.0f;           // "boxing"; results in Java.Lang.Float instance
float?           f = (float?) o;      // "unboxing"-esque

Java.Lang.Object o2 = null!;          // …because I can
float?           f2 = (float?) o2;
```

Currently `f` and `f2` will *never* be `null`, because only `explicit operator float` exists.

If we added an `explicit operator float?` overload, that would *change the semantics* of the above code: instead of calling `explicit operator float`, it would instead call `explicit operator float?`.  (It may be a *good and useful* semantic change, but it's *still* a semantic change!  A subtle and non-obvious change at that.)

Because this would be a non-obvious semantic change, I don't think we can consider this at all.

Sorry.

**Comment by softlion** [comment]
> A subtle and non-obvious change at that

I fully agree with you. 
I agree on your remark too, that the current behavior is counter intuitive and can lead to bugs very hard to find.

I thought .net8 was about breaking changes too. Well that's what the ms team is hammering at us, users, when we ask why fixes are not backported to net7 immediately.

So if I come back to my selfish use case, which was my initial issue - I know this ticket's title already tries to find a cause instead of expressing the issue - this is a mistake I made, please excuse me on that one.


So given the highlights in this thread, this code won't work as expected.

```
var lensInfoMinimumFocusDistance = (float?)cameraCharacteristics.Get(CameraCharacteristics.LensInfoMinimumFocusDistance); 
if(lensInfoMinimumFocusDistance  == null)
   return false;
```

Thank you ! I won't have find out there is a bug there until some of my customers crashes my app in production on some fancy device model.
So I should fix it like that:

```
var oLensInfoMinimumFocusDistance = cameraCharacteristics.Get(CameraCharacteristics.LensInfoMinimumFocusDistance); 
if(oLensInfoMinimumFocusDistance is null)
   return false;
var lensInfoMinimumFocusDistance = (float)oLensInfoMinimumFocusDistance;
```
or
```
var lensInfoMinimumFocusDistance = (float)cameraCharacteristics.Get(CameraCharacteristics.LensInfoMinimumFocusDistance)!; 
if(lensInfoMinimumFocusDistance is 0)
   return false;
```

A little more complicated, but ok I understand your point of view: this breaking change may surface bugs that already exist and were worked around. 
I'm not sure I would have take the same decision for .net8 though (for .net7 I fully agree with you).

Anyway this should be documented somewhere, to prevent peers checking for null values there.
What would be the best place to document that ?

**Comment by jpobst** [comment]
> I thought .net8 was about breaking changes too. Well that's what the ms team is hammering at us, users, when we ask why fixes are not backported to net7 immediately.

I'm not sure what team is advocating breaking changes, but the general .NET policy is to not make breaking changes except in very extreme circumstances (generally security vulnerabilities).  Each breaking change must go through paperwork and is thoroughly documented here:

https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0

While we cannot fix it to our ideal scenario (actually supporting `(float?)`), it feels like this is still largely a win for the current situation:

The warning that was surfaced when nullable warnings was turned on caused you to investigate the code and realize that it was not correctly handling the `null` case.  😁
