### ISSUE TITLE
App becomes unresponsive when using plugin.fingerprint on net8-pre5

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#8147]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

net8-pre5 (vs 17.7.0-pre2)

### Description

When using Plugin.Fingerprint in a maui app on android built with net8-pre5, at some point the app becomes unresponsive. UI is totally frozen. You have to manually kill the app.

Here is the [repro](https://github.com/tranb3r/Issues/tree/main/MauiSamplePluginFingerprint).

### Steps to Reproduce

1. Open the attached repro (very similar to maui sample app)
2. Build in Release and launch the app
3. Tap on Authenticate (it should check fingerprint and then navigate to a page full of text).
4. Do that a few times (Authenticate, Navigate to page full of text, Back).
5. At some point, the app becomes unresponsive. UI is totally frozen, you have to kill it.

### Did you find any workaround?

This is on Android. I have not tested iOS.
It only happens in Release. No issue in Debug.
It only happens with net8-pre5. No issue with net7.
It seems to happen only if the page is full of text. No issue (it seems) if there is only one row of labels.

Workaround: AndroidEnableMashalMethods=false

**Comment by jpobst** [comment]
Closing, as this is tracked via: https://github.com/xamarin/xamarin-android/issues/8253.
