### ISSUE TITLE
Archiving apk using .net 7.0+ for android includes wrong platforms

### ISSUE THREAD

**Issue by jfversluis** [xamarin/xamarin-android#8165]
---
**Issue moved from dotnet/maui#15971**
- Please respond to @mosammo.

---

_From @mosammo on Monday, July 3, 2023 9:04:33 AM_

### Description

[severity:I’m unable to use this version]
Archiving apk using .net 7.0 for android with “Target platform” “ARM64” produces large apk that includes assemblies of other platforms “X86” and “x64” which increases apk size considerably.

Expected behavior is to only include assemblies of the selected target platform. For example if we select “ARM32” it should not include other platforms like “ARM64”, “X86” and “x64”.

Latest visual studio 2022 17.6.2

### Steps to Reproduce

simple steps:
1. Create a maui project.
2. Right click the project to select the properties change Target platform to “ARM64” under Build->General
3. Build the project then archive apk.

To check it simply rename the apk as .zip file then open it and check folders “assemblies” and “bin” inside the apk. (please check attached screenshots)

### Link to public reproduction project repository

https://github.com/mosammo/DotNetIssues

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

.net 7 for android

### Did you find any workaround?

no

**Comment by jfversluis** [comment]
---
**Issue moved from dotnet/maui#15971**
- Please respond to @mosammo.

---

_From @mosammo on Monday, July 3, 2023 9:07:22 AM_

Example apk for platform "ARM64" including unselected platforms assemblies
![large apk size due to including wrong platforms](https://github.com/dotnet/maui/assets/137315518/6a850db4-4abf-4082-802e-dc1752d1f7be)

**Comment by jfversluis** [comment]
---
**Issue moved from dotnet/maui#15971**
- Please respond to @jsuarezruiz.

---

_From @jsuarezruiz on Monday, July 3, 2023 2:16:10 PM_

cc @jonathanpeppers

**Comment by jfversluis** [comment]
---
**Issue moved from dotnet/maui#15971**
- Please respond to @msftbot[bot].

---

_From @msftbot[bot] on Monday, July 3, 2023 2:16:17 PM_

We've added this issue to our backlog, and we will work to address it as time and resources allow. If you have any additional information or questions about this issue, please leave a comment. For additional info about issue management, please read our [Triage Process](https://github.com/dotnet/maui/blob/main/docs/TriageProcess.md).

**Comment by jfversluis** [comment]
---
**Issue moved from dotnet/maui#15971**
- Please respond to @jfversluis.

---

_From @jfversluis on Tuesday, July 4, 2023 11:47:02 AM_

The reproduction is not using .NET MAUI at all, while this probably would apply to .NET MAUI too, the core is in .NET for Android. Moving it to the right repo.

**Comment by jonpryor** [comment]
@mosammo: When you say "Archiving apk", are you referring to the Archive Manager within Visual Studio Tools > Archive Manager…?

**Comment by mosammo** [comment]
Archiving apk can be done in multiple ways:
- simplest option: right clicking the android project in "solution explorer" then click "Archive..."
- or use "Build" > "Archive..."
After the apk is created  simply rename the apk as .zip file then open it and check folders “assemblies” and “bin” inside the apk. (please check above screenshots)

**Comment by jonathanpeppers** [comment]
My Project Options page is broken in VS right now (they know about it):

![image](https://github.com/xamarin/xamarin-android/assets/840039/90324377-e3e8-422e-b325-c093973fd441)

So, I can't get a screenshot...

`RuntimeIdentifiers` is what you want to set, but we should double-check the project options page has the option to adjust that value.

So, if you only want 64-bit, you could do:
```xml
<RuntimeIdentifiers>android-arm64;android-x64</RuntimeIdentifiers>
```

**Comment by jpobst** [comment]
Yeah, I don't see anything else that looks like runtime identifiers.

**Comment by mosammo** [comment]
Thank you guys, turns out it is indeed just a visual studio UI issue and setting "RuntimeIdentifiers" manually fixes it
https://github.com/xamarin/xamarin-android/issues/8168#issuecomment-1629443944

**Comment by dellis1972** [comment]
The `PlatformTarget` is not the right property to change to these. You should probably leave that as AnyCPU for Android based projects (and probably all platforms to be honest).

`RuntimeIdentifiers` is the thing you can use to specify which android abi's you want to target.

**Comment by mosammo** [comment]
> The `PlatformTarget` is not the right property to change to these. You should probably leave that as AnyCPU for Android based projects (and probably all platforms to be honest).
> 
> `RuntimeIdentifiers` is the thing you can use to specify which android abi's you want to target.

Yes, it's a visual studio UI bug in project settings: the displayed property "Platform target" has no actual use at all, while the needed property "Runtime Identifiers" is missing from the UI

**Comment by jpobst** [comment]
This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team.

Thanks!
