### ISSUE TITLE
Xamarin Android DateTimeOffset.Now is giving wrong time ( not per System time) in Android 14 beta.

### ISSUE THREAD

**Issue by NehaKumari993185** [xamarin/xamarin-android#8175]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 version 17.5.4, Xamarin.Android SDK 13.2.0.0

### Description

Xamarin Android Timezone Conversion doesn't work on Android 14 Beta.
var **currentDateTime** = DateTimeOffset.Now;
Here currentDateTime is having different time in android 13 and in android 14 Beta.

Below table shows difference in response for same code in android 13 and android 14 Beta
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
</head>
<body>

  | Android 13 | Android 14 Beta
-- | -- | --
var currentDateTime = DateTimeOffset.Now; | 7/10/2023 2:06:00 PM +05:30 | 7/10/2023 8:39:07 AM +00:00
var universalDateTime= DateTimeOffset.Now.ToUniversalTime() | 7/10/2023 8:36:00 AM +00:00 | 7/10/2023 8:39:07 AM +00:00
string tziString = TimeZoneInfo.Local.Id;//Asia/Kolkata | Asia/Kolkata | Asia/Kolkata
var timeZone= string.Concat(tziString, ": ", TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById(tziString)).TimeOfDay) | Asia/Kolkata: 14:06:00.1012680 | Asia/Kolkata: 08:39:07.6905290
Time Picker/label shows time | 2:06:00 PM | 8:39:07 AM
System/Mobile Device Time | 2:06:00 PM | 2:09:07 PM

</body>
</html>

**Date Time Setting of  Android 13:**
![image](https://github.com/xamarin/xamarin-android/assets/139105706/ff3a7c4d-f920-4a27-a99d-bfbb79abfc21)

 **Date Time Setting of Android 14 Beta:**
![image](https://github.com/xamarin/xamarin-android/assets/139105706/e30b176f-520b-4cee-8630-fdeb4616e41b)

### Steps to Reproduce

1. Create a project in Xamarin Android 
2. And add below line in OnCreate Method of Main Activity.
3. var **currentDateTime** = DateTimeOffset.Now;
4. See the currentDateTime  value for android 13 and android 14 beta

### Did you find any workaround?

NO

**Comment by akoeplinger** [comment]
Fixed by https://github.com/mono/mono/pull/21682 which was included in https://github.com/xamarin/xamarin-android/pull/8216.
