### ISSUE TITLE
Adding .aar and .jar dependencies without C# bindings in Android Java Library Binding Project

### ISSUE THREAD

**Issue by bbarc** [xamarin/xamarin-android#8190]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

 Visual Studio Professional 2022 - 17.6.4 on Windows

### Description

I have attached the sample code below:

[FooBazBar.Client2.zip](https://github.com/xamarin/xamarin-android/files/12071362/FooBazBar.Client2.zip)

In this project I have the FooForBinding-release.aar file intended for binding, however it depends on 3 other java/kotlin libraries which must not get C# bindings. I have achieved this by setting the following elements in .csproj and Metadata.xml:

- `<remove-node path="/api/package[starts-with(@name,'com.example.foononbinding')]" />`
- `<AndroidLibrary Update="ReferencedBarK.jar" Bind="false" />`
- `<AndroidLibrary Update="ReferencedBazJ.jar" Bind="false" />`

My other approaches failed.

The existing documentation helped me a bit, but did not cover the whole process. Moreover, I am not sure if that is the intended way of doing it. 

Should there be any other working and documented solution for this type of tasks?

### Steps to Reproduce

1. Just run the attached Android Application without any exceptions being thrown.

### Did you find any workaround?

I am not sure if my solution is a workaround or there should be any better approach.

**Comment by jonathanpeppers** [comment]
It seems like you should be able to do this (and that's it):
```xml
<AndroidLibrary Update="ReferencedBarK.jar" Bind="false" />
<AndroidLibrary Update="ReferencedBazJ.jar" Bind="false" />
```

This would allow the binding generator to "find" the referenced libraries if needed and produce a binding, but you shouldn't have to use `<remove-node/>`.

Was this the doc you found already:

* https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md

**Comment by bbarc** [comment]
I have followed the doc you mentioned, just replacing the **Include** attribute with the **Update** one in `<AndroidLibrary/>` element.

using **Update** generates the following content of Foo.Binding.dll
![image](https://github.com/xamarin/xamarin-android/assets/53823316/09d66914-f505-4c64-9175-1361e7c809a2)

whereas using **Include** gives me additional C# bindings:
![image](https://github.com/xamarin/xamarin-android/assets/53823316/c8993cd7-5bc2-47eb-b457-14da220f7e93)

In both cases Foo.Binding.aar containing renamed  ReferencedBazJ.jar and ReferencedBarK.jar files  is created in FooBazBar.Client/Foo.Binding/bin/Debug/net7.0-android directory. And that is fine.

The problem seems to be with .aar, especially when using `<AndroidLibrary Update="FooNonBinding-release.aar" Bind="false" />`. In this case FooNonBinding-release.aar is not copied to FooBazBar.Client/Foo.Binding/bin/Debug/net7.0-android  and I get the runtime exception in the sample Android application:
![image](https://github.com/xamarin/xamarin-android/assets/53823316/25f1ab41-283f-4741-bf3d-b1a20ec271b6)

In case of using **Include** attribute here, like `<AndroidLibrary Include="FooNonBinding-release.aar" Bind="false" />` and with `<remove-node path="/api/package[starts-with(@name,'com.example.foononbinding')]" /> ` removed from Metadata.xml I get an additional C# bindings in .dll:
![image](https://github.com/xamarin/xamarin-android/assets/53823316/d1aef13e-0ace-4d96-8fb5-df48a5ef8118)

They are not desired. I have the requirement of only Com.Example.Foofrobinding C# bindings being present in .dll and my sample app not throwing any runtime exceptions.

Is there any other way to achieve both goals?

**Comment by jonathanpeppers** [comment]
It's possible the entry:
```xml
<AndroidLibrary Update="FooNonBinding-release.aar" Bind="false" />
```

Maybe this doesn't flow properly between `ProjectReference`, but if your class library was a NuGet package, I suspect it would work fine.

Let me review your project above, and see if this is the case.

**Comment by jonathanpeppers** [comment]
@bbarc the sample above seemed like it worked for me.

The `.aar` files were copied to the output directory:

![image](https://github.com/xamarin/xamarin-android/assets/840039/b5e9859a-82f2-459e-b2ba-0b80a42c17dd)

And then when I review a `.binlog` of the app, I see it using the `.aar` files as well:

![image](https://github.com/xamarin/xamarin-android/assets/840039/93045d89-a015-4aaf-b469-7ffb8a2d1133)

So that brings up two thoughts:

* Does a `Rebuild` solve the issue for you?

* If not, can you build command-line and see if that works? Via `dotnet build`.

* Add `-bl` to your `dotnet build` command, and share the `.binlog` here. (https://aka.ms/binlog)

Thanks!

**Comment by bbarc** [comment]
@jonathanpeppers the .zip file above has been updated.

**Comment by jonathanpeppers** [comment]
I think I see the issue, there is a line like this in our MSBuild targets:
```xml
<!-- .aar files should be copied to $(OutputPath) in .NET 6-->
<None Include="@(LibraryProjectZip)" ... CopyToOutputDirectory="PreserveNewest" Link="%(Filename)%(Extension)" />
```
But this isn't setup for `.aar` files when `Bind="false"`.

I could workaround the problem in `Foo.Binding.csproj` by adding:

```xml
<AndroidLibrary Update="FooNonBinding-release.aar" Bind="false" />
<!-- Workaround issue copying .aar file to output directory -->
<None Include="FooNonBinding-release.aar" CopyToOutputDirectory="PreserveNewest" />
```

Good find! Thanks for reporting.
