### ISSUE TITLE
Xamarin.Forms app crashing on .NET 7: Android trimmer undescriptive crashing and insufficient control on trimming

### ISSUE THREAD

**Issue by mosammo** [xamarin/xamarin-android#8195]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 2022 17.6.2+, .Net for Android 7+

### Description

Enabling "Publish Trimmed" in android projects results in undescriptive crashing that is hard to find the root cause of. 
There are many trimming warnings that it's hard to find the actual problem,
Trimmer should at least allow you to stop trimming all except for selected assemblies so you can narrow down which ones cause the problem but it still trims and cause runtime crashes even after setting the trimmer to not trim any assembly as follows:

`<Target Name="ConfigureTrimming" BeforeTargets="PrepareForILLink">
		<ItemGroup>
			<ManagedAssemblyToLink Condition="true">
				<IsTrimmable>false</IsTrimmable>
			</ManagedAssemblyToLink>
		</ItemGroup>
	</Target>
`

Since `Condition="true"` and `<IsTrimmable>false</IsTrimmable>` should disable trimming on all assemblies then this should generate same output like  `<PublishTrimmed>False</PublishTrimmed>`   that doesn't crash at runtime, so then we can at least enable trimming assemblies one by one to find where the problem is. but in reality it still crashes so something still gets trimmed making us unable to use the trimmer or trace its issues.

Strangely same project is published and trimmed on Xamarin android without problems but after migrating to .net for android trimming always causes the app to crash at runtime. Note this is not just about a specific project but the inability of developers to solve trimming crashes and issues generally.

Expected Behavior:
Descriptive trimming crash errors and at least ability to disable trimming as above so it wouldn't trim anything then we can selectively enable trimming assemblies to find where the problem is.

It would be great if we can also export a list of all assemblies that the trimmer would process with their size so at least we can selectively prioritize trimming larger assemblies first. But the priority is to be able to control the trimming starting from trimming nothing then controlling what gets trimmed exactly one by one. 

### Steps to Reproduce

1. Enable publish trimmed in project settings
2. Build and publish
If the app that works normally without trimming crashes after trimming there's no descriptive errors or ability to selectively enable trimming on only selected assemblies.

### Did you find any workaround?

No

**Comment by jonathanpeppers** [comment]
@mosammo the trimmer is located at:

https://github.com/dotnet/runtime/tree/main/src/tools/illink

Are you wanting the team that works on the trimmer to help with this one? Or is this problem specific to Android?

It seems like you have a lot of "trimmer design" questions, and we might not really know the answers here.

**Comment by jonathanpeppers** [comment]
Maybe you can share a sample app that crashes in Release mode, but works in Debug?

That would help us understand what the problem is.

**Comment by mosammo** [comment]
So far I'm not able to reproduce the crash on a sample project and I can't share the real project that has the trimming issue
The problem is not just this specific project, the problem is developers need the ability to find and fix trimming issues.
At least if we can control trimming assemblies one by one then we can find and exclude the assemblies having problems.
The only way I found so far is using ` <ManagedAssemblyToLink > ` 
if `Condition="true"` and `<IsTrimmable>false</IsTrimmable> ` it should means "all assemblies no trimming" so theoretically It should produce same apk as using `<PublishTrimmed>False</PublishTrimmed> ` then we can add assemblies to trimming one by one and locate the assembly with the problem. but in reality somehow something still getting trimmed causing runtime crash.
So is there something else we can use to make the trimmer only trim the assemblies that we specify?

**Comment by mosammo** [comment]
I tried `TrimmerRootAssembly` which is (exclude specific assembly from trimming) instead of (include specific assembly in trimming) but apk still crashes and the problem with it is we need to manually specify "every single assembly" to first reach a working state before trying to trim specific assemblies and so far I can't reach this working state without runtime crashing despite adding as many assemblies as I can. Is there a way to specify "exclude All assemblies from trimming" first to reach a working state then one by one include specific assemblies in trimming?

**Comment by jonathanpeppers** [comment]
If you think that `TrimmerRootAssembly` partially worked. In your `ConfigureTrimming` target you listed above, you could try something like:

```xml
<ItemGroup>
  <TrimmerRootAssembly Include="%(ManagedAssemblyToLink.FileName)" />
</ItemGroup>
```

Inspecting a `.binlog` of your build (see https://aka.ms/binlog) should help to be sure the values you expect are passed to the `<ILLink/>` MSBuild task.

**Comment by mosammo** [comment]
it seems the fileName variable is not supported with `TrimmerRootAssembly ` as it raises error "ILLink : error IL1032: Root assembly '%(ManagedAssemblyToLink.FileName)' could not be found."
I've installed project tools "[https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022](url) to generate binlog and I'm checking it for any clues.
Is there other possible variable syntax that can be used with `TrimmerRootAssembly`? I can't find any documentation for it

**Comment by jonathanpeppers** [comment]
The MSBuild error means it literally tried to use the string `%(ManagedAssemblyToLink.FileName)`, is the `ManagedAssemblyToLink` item group empty? Usually an error like this means a typo, but not sure in your case.

A `.binlog` would show more info.

**Comment by dellis1972** [comment]
`_ComputeManagedAssemblyToLink` is the target which `ManagedAssemblyToLink`. My guess is at the time `TrimmerRootAssembly` is being set that target has not even run yet.

**Comment by mosammo** [comment]
Yes seems we can't use` ManagedAssemblyToLink` with `TrimmerRootAssembly ` to exclude all files from trimming
I've check the assemblies from binlog and added all of them manually but still the apk is 45 MB and crashes unlike the untrimmed apk which is 78 MB and doesn't crash. So still is trimming and crashing. 
I've attached the binlog with and without trimming in addition to the project file if this may help.
![image](https://github.com/xamarin/xamarin-android/assets/137315518/1f2d19f5-000d-42cd-92ac-0e6c17124925)
[BinLogs.zip](https://github.com/xamarin/xamarin-android/files/12187267/BinLogs.zip)

**Comment by mosammo** [comment]
so far no hope. something is broken in the trimming, is there any change we can use the old Xamarin android trimming instead 😢

**Comment by jonathanpeppers** [comment]
@mosammo are you able to make a sample app that shows the same issue? That would help us troubleshoot this.

**Comment by mosammo** [comment]
Finally seems to be generated on attached sample project. the trimmed apk crashes while it runs in debug normally. seems somehow related to using FormsApplicationActivity!

[AndroidApp23.zip](https://github.com/xamarin/xamarin-android/files/12388181/AndroidApp23.zip)

**Comment by mosammo** [comment]
Also tried debugging with trimming enabled using:
`<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<PublishTrimmed>True</PublishTrimmed>
</PropertyGroup>`
 and it crashes with below error. this is also using latest VS 17.7.0 Preview 6.0
![image](https://github.com/xamarin/xamarin-android/assets/137315518/ea365300-ac6a-41c6-b050-b831fd67d6de)

**Comment by mosammo** [comment]
@jonathanpeppers is the crash reproduced with you on this sample project [AndroidApp23.zip](https://github.com/xamarin/xamarin-android/files/12388181/AndroidApp23.zip) ?

**Comment by jonathanpeppers** [comment]
One thing to note, is Xamarin.Forms isn't officially supported on .NET 6+. We have some integration tests that show Xamarin.Forms apps run -- they *might* work.

I tried to build the project, but I get errors for many `Infragistics.*` packages:
```
error NU1101: Unable to find package Infragistics.Core
error NU1101: Unable to find package Infragistics.Core.Charts
error NU1101: Unable to find package Infragistics.Core.DataGrid
error NU1101: Unable to find package Infragistics.Core.DV
error NU1101: Unable to find package Infragistics.Core.Gauges
error NU1101: Unable to find package Infragistics.XF.Charts
error NU1101: Unable to find package Infragistics.XF.DataGrid
```
Are these internal packages? or is there a way to get them?

**Comment by mosammo** [comment]
it's working perfectly but only without trimming. the crashing happens only when we enable trimming. 
I removed all references to Infragistics packages and can still generate the crash. below project has these packages removed.
 
[AndroidApp24.zip](https://github.com/xamarin/xamarin-android/files/12429258/AndroidApp24.zip)

**Comment by mosammo** [comment]
@jonathanpeppers can you reproduce the crash on [AndroidApp24.zip](https://github.com/xamarin/xamarin-android/files/12429258/AndroidApp24.zip)?

**Comment by mosammo** [comment]
It seems so, the error only appears when we enable trimming while if we disable trimming the app works normally without crashing.
Also the error is not descriptive and doesn't show what resource it was looking for that is incorrectly removed in trimming.

**Comment by jonathanpeppers** [comment]
What is very odd is the value used at runtime appears to be:

from `R.txt`:
```
int attr animationMode 0x7f030038
```
And then in C#:
```
Resource.Attribute.animationMode = 2130903096;
```
But I see the correct value here that does not appear to be used:
![image](https://github.com/xamarin/xamarin-android/assets/840039/3ec9e275-fa31-41bd-a0f9-1b04b4b593c6)

```
// aapt resource value: 0x7F0B0095
public const int Toolbar = 2131427477;

// Then later in UpdateIdValues()
global::Xamarin.Forms.Platform.Android.Resource.Layout.Toolbar = global::AndroidApp2.Resource.Layout.Toolbar;
```

**Comment by jonathanpeppers** [comment]
Things continued to not make sense, and then I noticed:
```
at Nemesis.Droid.MainActivity.OnCreate(Bundle bundle)
```

While the `MainActivity` I've been looking at is `AndroidApp2.MainActivity`!

It appears this package is adding its own `MainActivity` to your app, is that expected?
```xml
<PackageReference Include="Nemesis.Forms" Version="1.0.5" />
```
![image](https://github.com/xamarin/xamarin-android/assets/840039/beae7fdb-1816-4da0-80a9-d879d3679a37)

Setting `PublishTrimmed=false` somehow is just "lucky" (unlucky?) that the order is shuffled and your correct activity is launched instead.

**Comment by mosammo** [comment]
I don't know the implementation details of Nemesis package but is there a way to always force it to use always use the correct MainActivity while enabling trimming?

**Comment by dellis1972** [comment]
So the problem here is that the `Nemesis.Forms` Resource.designer.cs is not being updated with the correct Id values in `UpdateIdValues` anywhere. So its using the random id value it got when it was built. 

The problem is that the Nemesis.Forms library was build with `AndroidApplication` set to `true`. See https://github.com/neemesis/Nemesis.Forms/blob/master/Nemesis/Nemesis.Droid/Nemesis.Droid.csproj#L15

As a result ALL the resource designer fields are `const`. So cannot be changed at runtime.
https://github.com/neemesis/Nemesis.Forms/blob/master/Nemesis/Nemesis.Droid/Resources/Resource.Designer.cs#L2925

I have no idea how this even works in debug mode. I guess you are just getting lucky for some reason. 
The fix is to build Nemesis.Forms without the `AndroidApplication` set to `true` in the csproj and use that.

**Comment by mosammo** [comment]
Thank you! seems this is finally the [root cause](https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties#androidapplication)
`Only one project with <AndroidApplication>True</AndroidApplication> may be present within an Android package. (Unfortunately this requirement isn't verified, _which can result in subtle and bizarre errors regarding Android resources._)`
I will try it and hopefully no the crashing will be finally solved

**Comment by mosammo** [comment]
Removing Nemesis package did solve the resource error and it worked in debug with trimming and fast deployment. 
But when I tried to release apk or debug without fast deployment it crashed without any error. 
To make sure it was not related to any other package I removed all packages except Xamarin Forms and tried to release apk or debug without fast deployment but still crashed without any error.
Here's the same sample project that crashes with trimming in release or debug without fast deployment after removing all other packages except Xamarin Forms.
[AndroidApp27.zip](https://github.com/xamarin/xamarin-android/files/12534996/AndroidApp27.zip)

**Comment by mosammo** [comment]
[dellis1972](https://github.com/dellis1972) [jonathanpeppers](https://github.com/jonathanpeppers) can you reproduce the crash on [AndroidApp27.zip](https://github.com/xamarin/xamarin-android/files/12534996/AndroidApp27.zip)?

**Comment by mosammo** [comment]
any clue why it crashes without error in release with trimming but works in debug with trimming and fast deployment?

**Comment by mosammo** [comment]
[dellis1972](https://github.com/dellis1972) [jonathanpeppers](https://github.com/jonathanpeppers) did you get to reproduce the crash?

**Comment by mosammo** [comment]
hello?

**Comment by alexanderdibenedetto** [comment]
Seeing the same issue as we port our projects from Xamarin Forms -> .NET MAUI for Android. Any update here @jonathanpeppers ?

**Comment by jonathanpeppers** [comment]
@alexanderdibenedetto I would file a new issue for your problem. The latest above is an unknown error, so I don't think anyones knows if it is the same or not: https://github.com/xamarin/xamarin-android/issues/8195#issuecomment-1707871976

     it crashed without any error.

@mosammo can you share the latest error you're getting? An updated `adb logcat` log would help.

We've not prioritized this one as it's attempting to run Xamarin.Forms in .NET 7. Migrating to .NET MAUI is the recommended, supported path forward.

**Comment by mosammo** [comment]
is there a way to not trim the platform specific blob and only trim the main "assemblies.blob"?
if not is there a way the we can replace the "assemblies.blob" of the not trimmed apk with the "assemblies.blob" of the trimmed apk?
as i checked "assemblies.blob" alone is 60 MB and in trimmed apk it's 30 MB so if we can only trim "assemblies.blob" it will be enough for most people having this trimming issue
![image](https://github.com/xamarin/xamarin-android/assets/137315518/02270259-3e15-46a3-b189-421e5e44bb74)

**Comment by jonathanpeppers** [comment]
`assemblies.blob` is an implementation detail, it contains every `.dll` packed into a single file to help startup performance.

The error in the log above is:
```
10-18 18:29:29.943 28287 28287 E         : * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:2714, condition `corlib' not met
```

Are you doing something custom now? The runtime does not appear to be able to load `System.Private.CoreLib.dll` for your architecture.
