### ISSUE TITLE
Kotlin issue when building the application

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-android#8209]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VSMac 17.6.1 (build 452)

### Description

MAUI App build error after add [this nuget package](https://www.nuget.org/packages/XamarinLibrary.Net.Android.Loper7.DateTimePicker/0.6.3#dependencies-body-tab)

[mauibuildlog.txt](https://github.com/xamarin/xamarin-android/files/12135678/mauibuildlog.txt)

[DatePickerSampleApp.zip](https://github.com/xamarin/xamarin-android/files/12135685/DatePickerSampleApp.zip) is the code of Forms and MAUI

Other info:
Xamarin.Forms project is fine to build

### Steps to Reproduce

1.Unzip the zip file
2.open the mauisampleapp using vs for Mac
3.build the sln,
4.errors show

### Did you find any workaround?

no

### Relevant log output

```shell
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): warning XA4214: The managed type `Kotlin.IO.Path.IExperimentalPathApi` exists in multiple assemblies: Xamarin.Kotlin.StdLib, Xamarin.Kotlin.StdLib.Jdk7. Please refactor the managed type names in these assemblies so that they are not identical.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): warning XA4214: References to the type `Kotlin.IO.Path.IExperimentalPathApi` will refer to `Kotlin.IO.Path.IExperimentalPathApi, Xamarin.Kotlin.StdLib`.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): warning XA4214: The managed type `Kotlin.IO.Path.IFileVisitorBuilder` exists in multiple assemblies: Xamarin.Kotlin.StdLib, Xamarin.Kotlin.StdLib.Jdk7. Please refactor the managed type names in these assemblies so that they are not identical.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): warning XA4214: References to the type `Kotlin.IO.Path.IFileVisitorBuilder` will refer to `Kotlin.IO.Path.IFileVisitorBuilder, Xamarin.Kotlin.StdLib`.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): error XA4215: The Java type `kotlin.io.path.ExperimentalPathApi` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): error XA4215:   `kotlin.io.path.ExperimentalPathApi` generated by: Kotlin.IO.Path.IExperimentalPathApi, Xamarin.Kotlin.StdLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): error XA4215:   `kotlin.io.path.ExperimentalPathApi` generated by: Kotlin.IO.Path.IExperimentalPathApi, Xamarin.Kotlin.StdLib.Jdk7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): error XA4215: The Java type `kotlin.io.path.FileVisitorBuilder` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): error XA4215:   `kotlin.io.path.FileVisitorBuilder` generated by: Kotlin.IO.Path.IFileVisitorBuilder, Xamarin.Kotlin.StdLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.targets(1476,3): error XA4215:   `kotlin.io.path.FileVisitorBuilder` generated by: Kotlin.IO.Path.IFileVisitorBuilder, Xamarin.Kotlin.StdLib.Jdk7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    4 Warning(s)
    6 Error(s)
```

**Comment by jonathanpeppers** [comment]
@jpobst @moljac is `kotlin.io.path.ExperimentalPathApi` one of the types that Google moved around recently?

**Comment by jpobst** [comment]
I get a different error locally:

```
(0,1): error JAVA0000: Error in C:\.tools\.nuget\packages\xamarin.androidx.annotation\1.5.0.2\buildTransitive\net6.0-android31.0\..\..\jar\androidx.annotation.annotation.jar:androidx/annotation/AnimRes.class:
Type androidx.annotation.AnimRes is defined multiple times: C:\.tools\.nuget\packages\xamarin.androidx.annotation\1.5.0.2\buildTransitive\net6.0-android31.0\..\..\jar\androidx.annotation.annotation.jar:androidx/annotation/AnimRes.class, obj\Debug\net8.0-android\lp\145\jl\libs\54FB89168AC57954.jar:androidx/annotation/AnimRes.class
...
Directory 'obj\Debug\net8.0-android\lp\145' is from 'DateTimePickerBinding.aar'. [C:\Users\jopobst\Desktop\kotlin-dupe-test\kotlin-dupe-test.csproj]
```

Looking at the `XamarinLibrary.Net.Android.Loper7.DateTimePicker` package, it would appear to include several AndroidX .aar files in it:

![image](https://github.com/xamarin/xamarin-android/assets/179295/5cffe95d-a548-4141-a8de-9d64d3b94b26)

![image](https://github.com/xamarin/xamarin-android/assets/179295/464429bb-acd5-4234-bf18-88aaa763f055)

Likely these were referenced via a `.jar/.aar` instead of a `PackageReference`?

They should not have been included in the `XamarinLibrary.Net.Android.Loper7.DateTimePicker` package.

**Comment by jingliancui** [comment]
I think there may some issue on binding Or application.
Let me share the binding code later.

**Comment by jingliancui** [comment]
[DateTimePickerBinding.zip](https://github.com/xamarin/xamarin-android/files/12240338/DateTimePickerBinding.zip)
@jpobst please take a look.
after using vs Mac to build it, it will generates 2 aars file as the image you send days ago.

**Comment by jingliancui** [comment]
then you will found that I use Xamarin.Legacy.Sdk/0.2.0-alpha4 in the csproj. so I'm not sure if this sdk will impact the result.

**Comment by jpobst** [comment]
It looks like this may be caused by using a very old version of `Xamarin.Google.Android.Material`. Try updating it to a newer version like `1.9.0.2`.

**Comment by jingliancui** [comment]
thanks, will check it later.
In the mean time I have a question, because I reference the dependency base on the native package's reference here: 
https://github.com/loper7/DateTimePicker
 implementation 'com.google.android.material:material:1.1.0
 
if we update the dependency to newer version, is it will possible to occur some issue (for example if we are binding other packages instead of this one.)

**Comment by jpobst** [comment]
There is always a possibility of something breaking when updating anything.  But even if you were using this library in Java, Maven would use a newer version of Material if another library requested it.

It looks like even that library actually uses a newer version than specified in their readme:
https://github.com/loper7/DateTimePicker/blob/4a1c55986c52bdc27ffd05bfa236371509b87c5e/date_time_picker/build.gradle#L35

**Comment by jingliancui** [comment]
Ha good catch, and I agree with you. Thank you, let me update nuget and test later.

**Comment by jingliancui** [comment]
But then another question, why xamarin application can pass the build.

**Comment by moljac** [comment]
> Ha good catch, and I agree with you. Thank you, let me update nuget and test later.

Another suggestion: ask (request from) `loper7/DateTimePicker` author[s] to update their dependencies too.

**Comment by jpobst** [comment]
> But then another question, why xamarin application can pass the build.

My guess would be that an XF build uses all "older" dependencies that work well together, while MAUI itself uses "newer" dependencies that are causing this conflict with an "older" Material.

Also, several things about binding projects changed in the transition to .NET 6+, so it could be a change in there that makes things different now.

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md

**Comment by jingliancui** [comment]
thanks all, just tested, It work well after update nuget version of com.google.android.material:material
