### ISSUE TITLE
.NET7.0: Building Android project with UseMaiEssentials results in build warning

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-android#8225]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

Windows - VS2022 17.5.5

### Description

I have:
- Library project targetting `net7.0` and has `<UseMauiEssentials>true</UseMauiEssentials>` in the csproj
- App project targetting `net7.0-android` and `net7.0-ios` both of which have the same entry in the csproj and reference my library project

Upon building the Android project, the following warning is output:
```
Warning	MSB3243	No way to resolve conflict between "Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" and "Microsoft.Maui.Essentials". Choosing "Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily.	linnapp.Core	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2352	
```

This does not occur when building the iOS project.

### Steps to Reproduce

1 Create library targetting net7.0
2. Create Android project targetting net7.0-android and reference your library
3. Build and observe warning

(Optional - do the same with an iOS project and this warning does not occur)

### Relevant log output

```shell
Included above
```

**Comment by jonathanpeppers** [comment]
Does this happen in a `dotnet new android` project template? or just your project?

Can you share a `.binlog`? https://aka.ms/binlog The error message alone isn't enough to investigate what's happening, thanks!

**Comment by projectgoav** [comment]
Issue was caused by Visual Studio adding an explicit reference to the `Microsoft.Maui` assembly for iOS in the csproj alongside `<UseMauiEssentials>true</UseMauiEssentails>` entry. 

Removing the explicit reference solved this issue.
