### ISSUE TITLE
IntentFilterAttribute is missing PathSuffix and PathAdvancePattern

### ISSUE THREAD

**Issue by Digifais** [xamarin/xamarin-android#8235]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), .NET Android (net7.0-android, etc.)

### Affected platform version

Xamarin.Android 13.2.0.6, .NET 7.0.306

### Description

IntentFilterAttribute is missing PathSuffix and PathAdvancePattern, which were introduced in API 31. Cfr: https://developer.android.com/guide/topics/manifest/data-element#path

### Steps to Reproduce

Add an IntentFilterAttribute to any activity and you see that those two data element attributes are not exposed.

### Did you find any workaround?

You can manually add this to your Android Manifest instead of using an IntentFilterAttribute.

**Comment by jpobst** [comment]
@dellis1972 @jonathanpeppers 

It looks like this is split between `Mono.Android` and `Xamarin.Android.Build.Tasks`, is this something you guys normally handle?

[‎src/Mono.Android/Android.App/IntentFilterAttribute.cs](https://github.com/xamarin/xamarin-android/blob/180dd5205ab270bb74bb853754665db9cb5d65f1/src/Mono.Android/Android.App/IntentFilterAttribute.cs#L9)
[src/Xamarin.Android.Build.Tasks/Mono.Android/IntentFilterAttribute.Partial.cs](https://github.com/xamarin/xamarin-android/blob/180dd5205ab270bb74bb853754665db9cb5d65f1/src/Xamarin.Android.Build.Tasks/Mono.Android/IntentFilterAttribute.Partial.cs#L14)

**Comment by jonathanpeppers** [comment]
I don't think anyone is doing anything for these. The build tasks part is what emits the XML during the build.

How do we make it part of the binding process for new API levels? /cc @jonpryor

**Comment by jpobst** [comment]
It looks like we have this:
https://github.com/xamarin/xamarin-android/tree/main/build-tools/manifest-attribute-codegen

Perhaps I can look at extending it to generate the code we need.

**Comment by jpobst** [comment]
Given the timelines for .NET 8, I think I will forgo writing a tool to do this for now, and manually add these requested attributes using this as a guide: https://github.com/xamarin/xamarin-android/pull/3810

For .NET 9 we should probably look at developing a tool to automatically pull in new attributes and generate the needed code.
