### ISSUE TITLE
Build uses insecure V1 APK signing

### ISSUE THREAD

**Issue by trampster** [xamarin/xamarin-android#8249]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VSMac 

### Description

The place that I work requires our apps to pass a security scan using MobSF https://github.com/MobSF/Mobile-Security-Framework-MobSF

However when we run this scan our app fails with the following High Risk item:

> Application is signed with v1 signature scheme, making it vulnerable to Janus vulnerability on Android 5.0-8.0, if signed
> only with v1 signature scheme. Applications running on Android 5.0-7.0 signed with v1, and v2/v3 scheme is also
> vulnerable.

I can find no setting in the vs4mac project editor to change to V2 signing.

This [stackoverflow answer ](https://stackoverflow.com/questions/67804110/choose-or-change-the-apk-v1-signature-scheme-from-visual-studio-2019) says you can fix this by adding the following to your project file but it doesn't work:

```
<AndroidUseApkSigner>True</AndroidUseApkSigner>
<AndroidApkSignerAdditionalArguments>--v2-signing-enabled true</AndroidApkSignerAdditionalArguments>
```

### Steps to Reproduce

- Publish an APK in release mode
- Run the MobSF scan
-> notice it reports a high risk vulnerability due to using v1 signing.

### Did you find any workaround?

No

**Comment by dellis1972** [comment]
The work around is to use `--v1-signing-enabled false` in the `AndroidApkSignerAdditionalArguments`.

**Comment by jpobst** [comment]
We suspect this is working as intended.  We pass `--min-sdk-version` and `--max-sdk-version` to `apksigner`.

If the `min-sdk` is lower than `24` (for example, the default of `19` or `21`), then the apk should be signed with `v1` (plus later versions).  

API levels before API-24 do not support `v2`, so if the apk isn't signed with `v1` it could not be installed on devices before API-24.

Google's recommendation is to sign with all versions:
https://source.android.com/docs/security/features/apksigning#schemes

The "proper" workaround is probably to set `min-sdk` to `24` or higher.
