### ISSUE TITLE
Developer Options - Don’t Keep Activities in the On position can cause problems when exiting/quitting an app

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#8269]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 2022 17.7.0 Prev 6.0

### Description

For a long time, I’ve had the Developer Options setting Don’t Keep Activities in the On position on the devices I deploy to. I probably first set it that way when producing apps using multiple activities and so it has always been that way.

Since moving to Modern Android Development (MAD), single-activity architecture based on Jetpack APIs, I probably should have changed that setting to Off, since there is only one Activity in that type of app. One of the problems I’ve struggled with using the single-activity architecture is that it is very difficult when exiting your program to have the activity in the state where Activity.IsFinishing is true, for when activity.IsFinishing is true is the ideal time to stop a bound service that was started when the app started. I originally controlled it by having an OnBackPressedCallback in the Start Destination fragment or HomeFragment as Google likes to refer to it. That fragment’s HandleOnBackPressed() simply called Activity.Finish() which then meant in the MainActivity’s OnDestroy IsFinishing would be true and therefore StopService would be called. Without that call, the bound service would be left running when the app exited.

That worked fine until Android 13 introduced the Predictive Back Gesture for exiting the app. To use the PBG requires that there should be no enabled OnBackPressedCallback in the HomeFragment or Start Destination Fragment for the PBG to appear. On top of that Google is warning developers that back navigation will be broken in their apps if they don’t support this feature when it’s enforced in a few months.

So the onBackPressedCallback was removed from the HomeFragment and that then led to the solution of using the Application Class’s Application.IActivityLifecycleCallbacks, and to the code snippet below using OnActivityDestroyed, which again made IsFinishing == true in the OnDestroy of the MainActivity and StopService was again successfully called.

```
public void OnActivityDestroyed(Activity activity)
{
    if (!activity.IsChangingConfigurations)
    {
        activity.Finish();
	Log.Debug(logTag, logTag + " OnActivityDestroyed - Calling Activity.Finish()");
    }
}
```

That was fine and a working solution until the Android 13 March update broke the PBG. It still worked on Samsung devices, but not on any of the Pixel devices. It remained that way until the August update made it work again. I’ve not read any Google claim to it being fixed, but then I never read one either when it broke. 
 
A couple of days ago I was having a problem with some subscription code on a Pixel4a, so I decided to reset the Pixel4a. Once set up again, I set the usual Developers Options so that I could deploy to it and started testing the subscription code again. I then attempted to use the app live and found that when I exited the permanent notification icon on the status which indicates the bound service is running didn’t disappear when quitting the app. So, I debugged the app again and found that the debugger wouldn’t break on the above break point, which explained why the service wasn’t stopped. No other Pixel device was failing at this point, so I started thinking about what was different and then realized I hadn’t set Don’t Keep Activities to On. As soon as I changed it to on it worked as before. Well, that was a working solution for a developer device, but probably not what you want for a normal user, who is most unlikely to have that setting in Developer Options turned on. I’ve now checked all my devices to ensure that Don’t Keep Activities is OFF.

Further debugging on the Pixel4a indicated that OnActivitySaveInstanceState was being hit, so I moved the code to there and then turned OFF Don’t Keep Activities, built a release build and watched the Logat logs as I closed the app. Sure enough, OnActivitySaveInstanceState executed and came up in the log and the service was shut down and the icon disappears.

I still don’t know why OnActivityDestroyed isn’t called when Don’t Keep Activities is OFF. Please note that you also need to have Predictive Back Gesture enabled in Developers Options for the PBG to appear and the August update applied to any Pixel device running Android 13.

To see the output of those logs in Android Studio just set the filter to tag:nav

Link to test app https://github.com/gmck/NavigationGraph8Net7.

### Steps to Reproduce

See test app

### Did you find any workaround?

See test spp

### Relevant log output

```shell
See test app
```

**Comment by gmck** [comment]
After some more experimenting, I have come up with a more straightforward method of stopping the dummy service. In the previous version, we saw from the LogCat logs that we needed to call Activity.Finish() within OnActivitySaveInstanceState of the Application class so that when MainActivty.OnDestroy() was reached IsFinishing would be true so that our dummy StopService method would be called. This was necessary because the OnActivityDestroyed was not being called when the Developer Options -Apps - Don’t keep activities was set to OFF. That being the default state for a regular user, it was necessary to find a way to stop the service when the app was exited.

In this update, we now have an OnSaveInstanceState override of the MainActivity. This is called when the app is exited via a back gesture.

So we can dispense with the OnActivitySaveInstanceState override in the Application class or even the whole class. I've commented out the RegisterActivityLifecycleCallbacks(this) and the UnregisterActivityLifecycleCallbacks(this) in the Application class so those callbacks are no longer executed.

The end result is the Predictive Back Gesture works as before and StopService is called.

Please note that we can still see the following in the LogCat logs, but since they are only warnings I think it is probably safe to ignore them.

Input channel object '60d57a Splash Screen com.companyname.navigationgraph8net7 (client)' was disposed without first being removed with the input manager!

Input channel object '60a1c5d com.companyname.navigationgraph8net7/crc640cebeb752226fc06.MainActivity (client)' was disposed without first being removed with the input manager!

A more extensive explanation is in the README of the updated test app.  https://github.com/gmck/NavigationGraph8Net7.

**Comment by grendello** [comment]
@gmck I'm honestly at loss as to what we can fix there? What you described appears to be happening entirely on the Android side, I don't see anything that we could change in **our** behavior to make the code behave differently.  However, since I'm absolutely not an expert in Android UI/app inner workings, and this issue is certainly not a native Xamarin.Android runtime one, I'll reassign and defer to other team members to make a determination if this is something we can fix or not.

**Comment by gmck** [comment]
@grendello 
Well, I only reported these warnings here because I thought you should be aware of them and secondly so that others who may run across them in their logs are made aware of them too. Since I wrote this, I've not noticed any other strange behaviour - the service is still closing as it should and the Predictive Back Gesture is working normally. Google has closed the PBG issue on their issue tracker as fixed, so I guess those warnings are always going to occur. I recently joined the beta of Android 14 and it now looks like every fragment is going to have a PBG showing the screen underneath it. I just hope they give us a switch to allow users to turn it off because it looks ridiculous. We've all been swiping since Android 10, so why now four years later do they think we need help in navigating backwards? I wonder how many times Android users accidentally exit Gmail each day.
