### ISSUE TITLE
Net7-android binding has ClassNotFoundException when trying to consume

### ISSUE THREAD

**Issue by svaldetero** [xamarin/xamarin-android#8308]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 17.6.3, net7.0-android

### Description

I have a net7.0-android binding project created here: https://github.com/Envoc/envoc-stripe-binding/blob/android-2.19.0/src/StripeTerminal/Envoc.Stripe.Terminal.Android/Envoc.Stripe.Terminal.Android.csproj
With a nuget package here: https://www.nuget.org/packages/Envoc.Stripe.Terminal.Android.

Adding that nuget package and trying to consume the library via the line `Com.Stripe.Stripeterminal.Terminal.IsInitialized;` from a `File -> New Maui Project` app causes the exception `java.lang.ClassNotFoundException: Didn't find class "com.stripe.jvmcore.logging.terminal.log.Log"`

It looks like that class is in `com.stripe_stripeterminal-internal-common.aar` under the `libs` folder.

Android binding troubleshooting says to add a missing jar file, but this is a lib of an included aar. Is this a packaging issue?

### Steps to Reproduce

1. Create new Maui app
2. Add nuget reference to `Envoc.Stripe.Terminal.Android`
3. In the click me button add a call to the nuget like `Com.Stripe.Stripeterminal.Terminal.IsInitialized;`

### Did you find any workaround?

No

**Comment by jpobst** [comment]
This feels more like a packaging issue than a binding issue, so I'm gonna pass it to Peppers/Dean first.

https://nuget.info/packages/Envoc.Stripe.Terminal.Android/2.19.0

**Comment by jonathanpeppers** [comment]
So, these files are not in the `.nupkg`?

https://github.com/Envoc/envoc-stripe-binding/blob/2e479c64309a3cb36e71f2aa9f5d9f6e707171e9/src/StripeTerminal/Envoc.Stripe.Terminal.Android/Envoc.Stripe.Terminal.Android.csproj#L75-L76

![image](https://github.com/xamarin/xamarin-android/assets/840039/39fd1105-cefb-4ab8-9f6c-fcef1c3e5db7)

Do you need to just add `Pack="true"` for these?

`AndroidMavenLibrary` must be implemented in another repo, I'm not familiar with it. It probably doesn't define that for you by default like we do here:

https://github.com/xamarin/xamarin-android/blob/6862b52b37f6f70a6f1f9ba3b38af803461327bb/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets#L65-L68

**Comment by svaldetero** [comment]
I don't think I need those in the public API and they required _so much_ more fixing in the `Metadata.xml`. I'll add the pack=true and see if that fixes it.

`AndroidMavenLibrary` is from [XamPrototype.Android.MavenBinding.Tasks nuget package](https://www.nuget.org/packages/XamPrototype.Android.MavenBinding.Tasks). [Github](https://github.com/jpobst/Prototype.Android.MavenBindings)

**Comment by jonathanpeppers** [comment]
I found the repo now:

https://github.com/jpobst/Prototype.Android.MavenBindings/blob/main/src/Microsoft.Android.MavenBinding.Tasks/XamPrototype.Android.MavenBinding.Tasks.targets

It looks like nothing sets `Pack="true"` for you, but if you set yourself it should get passed along.

**Comment by jpobst** [comment]
Doing a local test with:
```xml
<ItemGroup>
    <AndroidMavenLibrary Include="com.stripe:stripeterminal-internal-models" Version="2.18.1" Bind="False" />
    <AndroidMavenLibrary Include="org.jetbrains.kotlin:kotlin-parcelize-runtime" Version="1.7.20" Bind="False" />
    <AndroidMavenLibrary Include="org.jetbrains.kotlin:kotlin-android-extensions-runtime" Version="1.7.20" />
    <AndroidMavenLibrary Include="com.squareup.wire:wire-runtime" Version="4.4.3" />
</ItemGroup>
```

It would appear that it does pick up the `Pack` and `Bind` defaults for `AndroidLibrary`:

![image](https://github.com/xamarin/xamarin-android/assets/179295/0d258324-0640-4dd3-852a-9c0bf280f0bb)

**Comment by jonathanpeppers** [comment]
@jpobst and they don't make it to the `.nupkg`? Can you share a `.binlog` of `dotnet pack -bl`?

**Comment by jpobst** [comment]
For my test case, the 3 `.jar` files end up in `prototype-bind-test.aar` which is included in the `.nupkg` as expected.  However the `com.stripe_stripeterminal-internal-models.aar` file doesn't appear in the `bin` folder or the `.nupkg`.

![image](https://github.com/xamarin/xamarin-android/assets/179295/b4f17bfa-1cdd-4a51-99bd-8302a6ecb70e)

[msbuild.zip](https://github.com/xamarin/xamarin-android/files/12489239/msbuild.zip)

**Comment by jpobst** [comment]
In fact, it does not work in .NET 8 P6, but it does work in P7, so I suspect it is probably this fix?

https://github.com/xamarin/xamarin-android/pull/8193.

**Comment by jonathanpeppers** [comment]
Yeah, I initially was going to service this fix to .NET 7, but it caused other issues, ended up being two fixes:
* https://github.com/xamarin/xamarin-android/pull/8193
* https://github.com/xamarin/xamarin-android/pull/8196

If we don't find any further issues with these, maybe we could take them both back to .NET 7?

For now as a workaround, you could do something like adding a `<None/>` entry mentioned here: https://github.com/xamarin/xamarin-android/issues/8190#issuecomment-1638856266

And also set `Pack="true" PackagePath="lib/net7.0-android33.0"` to get the file in the right location in the `.nupkg` file.

**Comment by jonathanpeppers** [comment]
For now, I think we can close, as we have the two PRs that should fix this in .NET 8:

* https://github.com/xamarin/xamarin-android/pull/8193
* https://github.com/xamarin/xamarin-android/pull/8196

We'll consider backporting to .NET 7, so anyone upvote or comment if you run into this. It will help us know how important it is to backport these. Thanks!

**Comment by ggbtvs** [comment]
@svaldetero Hi, I wonder if you can help me with creating Stripe Terminal bindings for Xamarin Android (not Maui).  I am having issues and would appreciate any tips / advice on hoe to get it working.  I've created iOS version without any issues.  I'm not as familiar with binding projects for Android though. Thanks in advance, if you can.

**Comment by svaldetero** [comment]
> @svaldetero Hi, I wonder if you can help me with creating Stripe Terminal bindings for Xamarin Android (not Maui). I am having issues and would appreciate any tips / advice on hoe to get it working. I've created iOS version without any issues. I'm not as familiar with binding projects for Android though. Thanks in advance, if you can.

If you need the old framework bindings, I would check out this github: https://github.com/Square-Six/Xamarin.Stripe.Terminal.Android. I referenced it a lot when making mine.
