### ISSUE TITLE
.NET 8 RC1 silently breaks binding library (build successful but no binding generated)

### ISSUE THREAD

**Issue by bruno-garcia** [xamarin/xamarin-android#8340]
### Android application type

.NET Android (net6.0-android)

### Affected platform version

8.0.100-rc.1.23455.8

### Description

While trying to get the [Sentry .NET SDK](https://github.com/getsentry/sentry-dotnet) to build with the .NET 8 SDK, I encountered a problem with the `net6.0-android` binding library that blocks things.

### Steps to Reproduce

Repro: https://github.com/bruno-garcia/repro-dotnet-sdk-8-rc1-bindings-android/tree/main

Build with .NET 7:
* Build successful
* DLL contains C# methods that bind to Java methods

Build with .NET 8:
* Build successful
* DLL is empty

### Did you find any workaround?

No

**Comment by jpobst** [comment]
Resolved on Discord, documenting here for future searchers.

It is expected that .NET 8 SDK cannot compile the out-of-support `net6.0-android` framework:
https://github.com/xamarin/xamarin-android/pull/7900

Attempting to do so produces the following error:
```
error NETSDK1202: The workload 'net6.0-android' is out of support and will not receive security updates in the futur
e. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.
```

This sample project is suppressing the error with:
```
<NoWarn>NETSDK1202</NoWarn>
```

Thus no error is produced, but also the project isn't going to work.
