### ISSUE TITLE
XA3007: Could not link native shared library: libxamarin-app.so 

### ISSUE THREAD

**Issue by rubberydev** [xamarin/xamarin-android#8352]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.7.4

### Description

the project Xamarin.Android was built in Visual Studio 2019 but I  want to run and build it in Visual Studio 2022 to upgrade it to API Level 33(Android 13) but this problem doesn´t permit me continue, help me please! 

<img width="370" alt="Error_build_project" src="https://github.com/xamarin/xamarin-android/assets/15622477/80ac60e4-f9d3-4258-a80e-cf24e24ab544">

Thanks in advance!

### Steps to Reproduce

1. Open the project
2. Change the Target Framework 
3. Run.

**Comment by jonathanpeppers** [comment]
Can you attach an [MSBuild binary log](https://aka.ms/binlog) of the error? Thanks!

**Comment by rubberydev** [comment]
> Can you attach an [MSBuild binary log](https://aka.ms/binlog) of the error? Thanks!

I could compile the project after did clean and run sometimes in Debug Mode, after that Ichanged to release mode to signing .apk with new target framework however got the same issue building the project, finally Ichanged to debug mode again and the error persist, I´m gonna attach 2(Debug and Release Mode) MSBuild binary log such as you told me and with same result both,

help me please!

thanks in advance!

[MSBuildLog_DebugMode.txt](https://github.com/xamarin/xamarin-android/files/12668124/MSBuildLog_DebugMode.txt)
[MSBuildLog_ReleaseMode.txt](https://github.com/xamarin/xamarin-android/files/12668125/MSBuildLog_ReleaseMode.txt)

**Comment by rubberydev** [comment]
> Can you attach an [MSBuild binary log](https://aka.ms/binlog) of the error? Thanks!

Hi @jonathanpeppers , I attach the MSBuildLog

Thanks in advance!
[MSBuildLog_DebugMode.txt](https://github.com/xamarin/xamarin-android/files/12678562/MSBuildLog_DebugMode.txt)

**Comment by jonathanpeppers** [comment]
@rubberydev this is a text-based build log with `Normal` (maybe actually `Minimal`?) verbosity. If you want to send a text-based one, can you use `Diagnostic` verbosity?

https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output

**Comment by rubberydev** [comment]
Hi @jonathanpeppers  thank you for your response! excuse me I didn´t know that, thanks again for guide me...
I attach the MSBuild with verbosity in mode Diagnostic:
[MSBuild.zip](https://github.com/xamarin/xamarin-android/files/12686147/MSBuild.zip)

**Comment by rubberydev** [comment]
Input file "obj\Debug\130\android\typemaps.armeabi-v7a.o" is newer than output file "obj\Debug\130\app_shared_libraries\arm64-v8a\libxamarin-app.so".
I think so this is the problem, I looked something similar in forums about MAUI with architecture arm64-v8a

https://github.com/dotnet/maui/issues/14531

I´m not sure it is related?

**Comment by jonathanpeppers** [comment]
@grendello @dellis1972 do you know if there is a way to get more info out of:
```
[Native Linker] c:\program files\microsoft visual studio\2022\community\MSBuild\Xamarin\Android\binutils\bin\ld.EXE --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname libxamarin-app.so -z relro -z noexecstack --enable-new-dtags --eh-frame-hdr -shared --build-id --warn-shared-textrel --fatal-warnings -X -m armelf_linux_eabi obj\Debug\130\android\typemaps.armeabi-v7a.o obj\Debug\130\android\environment.armeabi-v7a.o obj\Debug\130\android\compressed_assemblies.armeabi-v7a.o obj\Debug\130\android\marshal_methods.armeabi-v7a.o obj\Debug\130\android\jni_remap.armeabi-v7a.o -o obj\Debug\130\app_shared_libraries\armeabi-v7a\libxamarin-app.so
[Native Linker] c:\program files\microsoft visual studio\2022\community\MSBuild\Xamarin\Android\binutils\bin\ld.EXE --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname libxamarin-app.so -z relro -z noexecstack --enable-new-dtags --eh-frame-hdr -shared --build-id --warn-shared-textrel --fatal-warnings -m elf_x86_64 obj\Debug\130\android\typemaps.x86_64.o obj\Debug\130\android\environment.x86_64.o obj\Debug\130\android\compressed_assemblies.x86_64.o obj\Debug\130\android\marshal_methods.x86_64.o obj\Debug\130\android\jni_remap.x86_64.o -o obj\Debug\130\app_shared_libraries\x86_64\libxamarin-app.so
[Native Linker] c:\program files\microsoft visual studio\2022\community\MSBuild\Xamarin\Android\binutils\bin\ld.EXE --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname libxamarin-app.so -z relro -z noexecstack --enable-new-dtags --eh-frame-hdr -shared --build-id --warn-shared-textrel --fatal-warnings --fix-cortex-a53-843419 -m aarch64linux obj\Debug\130\android\typemaps.arm64-v8a.o obj\Debug\130\android\environment.arm64-v8a.o obj\Debug\130\android\compressed_assemblies.arm64-v8a.o obj\Debug\130\android\marshal_methods.arm64-v8a.o obj\Debug\130\android\jni_remap.arm64-v8a.o -o obj\Debug\130\app_shared_libraries\arm64-v8a\libxamarin-app.so
[Native Linker] c:\program files\microsoft visual studio\2022\community\MSBuild\Xamarin\Android\binutils\bin\ld.EXE --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname libxamarin-app.so -z relro -z noexecstack --enable-new-dtags --eh-frame-hdr -shared --build-id --warn-shared-textrel --fatal-warnings -m elf_i386 obj\Debug\130\android\typemaps.x86.o obj\Debug\130\android\environment.x86.o obj\Debug\130\android\compressed_assemblies.x86.o obj\Debug\130\android\marshal_methods.x86.o obj\Debug\130\android\jni_remap.x86.o -o obj\Debug\130\app_shared_libraries\x86\libxamarin-app.so
XA3007: Could not link native shared library: libxamarin-app.so
```

**Comment by grendello** [comment]
@jonathanpeppers depends on which NET7 it is. We've had [this improvement](https://github.com/xamarin/xamarin-android/commit/77584e02a86fcd01fc85fe6870decf36a4690656) since November last year.  Prior to that, the stderr output should be in the verbose log/binlog.  Failing that, one can cut-and-paste the command to developer prompt and see what it says.

**Comment by rubberydev** [comment]
Hi guys, thanks a lot for helping me, I  really don´t know how to find  the log in log/binlog, however I  could launch the command dotnet build XxxxXxxx.Droid.csproj in my command prompt and I got the next output:

thanks! 

[Output_from_prompt.txt](https://github.com/xamarin/xamarin-android/files/12707106/Output_from_prompt.txt)

**Comment by jonathanpeppers** [comment]
For `dotnet build` if you just add an additional `-bl` argument, it will create an `msbuild.binlog` file in the current directory.

**Comment by jonathanpeppers** [comment]
The latest one has a completely different error:
```
EnelPeru.Droid.csproj(4934,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\7.0.401\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\7.0.401\\Xamarin\Android\Xamarin.Android.CSharp.targets" is correct, and that the file exists on disk.
```
Is this a Xamarin.Android project? For that, you would have to use `msbuild` instead of `dotnet build`.

My MSBuild is at `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"` for example.

**Comment by rubberydev** [comment]
> The latest one has a completely different error:
> 
> ```
> EnelPeru.Droid.csproj(4934,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\7.0.401\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\7.0.401\\Xamarin\Android\Xamarin.Android.CSharp.targets" is correct, and that the file exists on disk.
> ```
> 
> Is this a Xamarin.Android project? For that, you would have to use `msbuild` instead of `dotnet build`.
> 
> My MSBuild is at `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"` for example.

@jonathanpeppers with MSBuild.exe got o errors:
<img width="852" alt="image" src="https://github.com/xamarin/xamarin-android/assets/15622477/0fb297f2-b7ed-4994-9aa2-47bbc82dfb96">
however I attach the detailed log:
[MSBuildLogDetail.txt](https://github.com/xamarin/xamarin-android/files/12718026/MSBuildLogDetail.txt)

thanks !

**Comment by jonathanpeppers** [comment]
How can we get a log that contains the error:
```
XA3007: Could not link native shared library: libxamarin-app.so
```

**Comment by rubberydev** [comment]
> How can we get a log that contains the error:
> 
> ```
> XA3007: Could not link native shared library: libxamarin-app.so
> ```

I really dont know because the error disappering when I built project with MSBuild tool, so! my question rigth now is, if I could build the project with MSBuild tool and upgraded to API level 33 without any output error in the process, also Could I sign the .apk from similar CLI tools or something like this existent;In order to follow releasing versions to my app.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
