### ISSUE TITLE
Correct version of Mono.Android.Export.dll?

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#8389]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.8.0 Prev 2.0

### Description

When building my app and attempting to use ILifecycleObserver the build fails with a message **Please add a reference to Mono.Android.Export.dll when using ExportAttribute or ExportFieldAttribute.** I added it via Add Reference and found it in Assemblies\Framework. 

After installation the path to it is C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v4.4\Mono.Android.Export.dll. The build is then successful.

Later on, I was searching via Explorer and found many different versions scattered all over my disc. Most of them are in Net7 and Net8 projects. One is referencing a Net6 project which I find confusing as I don't recall ever checking out a Net6 project. 

Looking at a Net8 Android project I can see Mono.Android.Export seems to be added by default, as I don't remember adding it.

Can someone please confirm that I'm using the correct version for an X.A. Android 13 app? Am I also correct in assuming that it is not necessary to manually add it for Net7 and Net8 projects?

### Steps to Reproduce

N/A

### Did you find any workaround?

N/A

### Relevant log output

```shell
N/A
```

**Comment by dellis1972** [comment]
@jpobst any ides on this one?

**Comment by jpobst** [comment]
> Can someone please confirm that I'm using the correct version for an X.A. Android 13 app?

That one should be correct.  It does not contain any API level specific code, so I think we only ship one that "targets" the lowest API we support, and all newer API levels also use that one.

> Am I also correct in assuming that it is not necessary to manually add it for Net7 and Net8 projects?

I believe this is correct.  In .NET, it is now shipped in our Android targeting pack (https://www.nuget.org/packages/Microsoft.Android.Ref.34) and I assume everything in that pack is automatically referenced by any Android application.
