### ISSUE TITLE
Net7 to net8: Mono error using Release build

### ISSUE THREAD

**Issue by xpfr** [xamarin/xamarin-android#8426]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 17.8.0 Preview 3.0, Xamarin.Android SDK 13.2.2.0, API34

### Description

The app uses a binding library to access classes & methods of a Java component.

In the library, there is the below interface:

```csharp
[Register("com/kizitonwose/calendar/view/Binder", "", "Kizitonwose.Calendar.IBinderInvoker")]
[JavaTypeParameters(new string[] { "Data", "Container extends com.kizitonwose.calendar.view.ViewContainer" })]
public interface IBinder : IJavaObject, IDisposable, IJavaPeerable
{
    [Register("bind", "(Lcom/kizitonwose/calendar/view/ViewContainer;Ljava/lang/Object;)V", "GetBind_Lcom_kizitonwose_calendar_view_ViewContainer_Ljava_lang_Object_Handler:Kizitonwose.Calendar.IBinderInvoker, CalendarView")]
    void Bind(Java.Lang.Object container, Java.Lang.Object? data);
...
}
```

A class of the app implements such interface as below:

```csharp
public void Bind(Java.Lang.Object container, Java.Lang.Object data)
{
            CalendarMonth cm = data as CalendarMonth;
...
}
```

CalendarMonth is a class defined in another binding library:

```csharp
[Register("com/kizitonwose/calendar/core/CalendarMonth", DoNotGenerateAcw = true)]
public sealed class CalendarMonth : Java.Lang.Object, ISerializable, IJavaObject, IDisposable, IJavaPeerable
```

Using the release build, the argument "data" can not be cast to the managed type. It gives null (which leads to the crash).
This works well with the Debug build.
This works well with Release build using net7. This looks like a regression.

When looking at the logs:
Mono can not find the managed type and gives below error:

```
10-15 07:47:26.877 14935 14935 E monodroid-assembly: typemap: unable to load assembly 'CalendarCore' when looking up managed type corresponding to Java type 'com/kizitonwose/calendar/core/CalendarMonth'
```
Code where this message sits is inside monoandroid/jni/embedded-assemblies.cc

```cpp
EmbeddedAssemblies::typemap_java_to_managed (hash_t hash, const MonoString *java_type_name) noexcept
{
 .....
	if (module->image == nullptr) {
		module->image = mono_image_loaded (module->assembly_name);
		if (module->image == nullptr) {
			log_error (LOG_ASSEMBLY, "typemap: unable to load assembly '%s' when looking up managed type corresponding to Java type '%s'", module->assembly_name, to_utf8 (java_type_name).get ());
			return nullptr;
		}
	}
```

### Steps to Reproduce

Create app using TargetFramework = net8.0-android34.0

### Did you find any workaround?

Unfortunately not.

Tried to add a Progguard rule to keep the classes from the library. But this does not seem to be related to a class being removed by r8.

### Relevant log output

```shell
10-15 07:47:26.951 14935 14935 I MonoDroid: android.runtime.JavaProxyThrowable: [System.NullReferenceException]: Object reference not set to an instance of an object
10-15 07:47:26.951 14935 14935 I MonoDroid:     at Kizitonwose.Calendar.MonthHeaderBinder.Bind(Unknown Source:0)
10-15 07:47:26.951 14935 14935 I MonoDroid:     at Kizitonwose.Calendar.IBinderInvoker.n_Bind_Lcom_kizitonwose_calendar_view_ViewContainer_Ljava_lang_Object_(Unknown Source:0)
10-15 07:47:26.951 14935 14935 I MonoDroid:     at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLL_V(Unknown Source:0)
10-15 07:47:26.951 14935 14935 I MonoDroid:     at crc64a13059fa34b8339c.MonthHeaderBinder.n_bind(Native Method)
10-15 07:47:26.951 14935 14935 I MonoDroid:     at crc64a13059fa34b8339c.MonthHeaderBinder.bind(MonthHeaderBinder.java:41)
```

**Comment by xpfr** [comment]
Class generated during the build of the binding library attached.
[Kizitonwose.Calendar.Core.CalendarMonth.cs.txt](https://github.com/xamarin/xamarin-android/files/12908997/Kizitonwose.Calendar.Core.CalendarMonth.cs.txt)

**Comment by grendello** [comment]
@xpfr the native code you indicate is incidental here, it doesn't cause the issue.  The most likely causes are either missing correct cast in this code:

```csharp
CalendarMonth cm = data as CalendarMonth;
```

which should be instead:

```csharp
CalendarMonth cm = data.JavaCast<CalendarMonth> ();
```

Or perhaps `data` is `null` from the start?

Another potential cause is that `CalendarMonth` is being linked away by the managed linker.

Please try the `JavaCast` approach first and let's see if it works.
