### ISSUE TITLE
support  OpenHarmony

### ISSUE THREAD

**Issue by ghd258** [xamarin/xamarin-android#8499]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

support  OpenHarmony

### Description

support  OpenHarmony

### Steps to Reproduce

support  OpenHarmony

### Did you find any workaround?

support  OpenHarmony

### Relevant log output

```shell
support  OpenHarmony
```

**Comment by jonpryor** [comment]
🤔 such an effort may not work for long; consider [Chinese companies recruiting HarmonyOS developers to launch native apps](https://www.huaweicentral.com/chinese-companies-recruiting-harmonyos-developers-to-launch-native-apps/):

> Huawei is moving toward native HarmonyOS applications and the current Android source code may not work with future versions of HarmonyOS.

That doesn't sound encouraging?

Something more specific "from the horses mouth" would be desirable, as opposed to a news article from a 3rd party…

**Comment by jonpryor** [comment]
The [Wikipedia page for [OpenHarmony](https://en.wikipedia.org/wiki/OpenHarmony) also links to [HarmonyOS NEXT is a standalone HUAWEI OS without Android apps](https://www.noypigeeks.com/tech-news/harmonyos-next-without-android-apps/):

> This new OS doesn’t use Android libraries and won’t accept Android APKs.

Assuming these two articles are correct, I do not see any point in supporting OpenHarmony.
