### ISSUE TITLE
App size is too large in Release mode with several native binded libraries

### ISSUE THREAD

**Issue by espritm** [xamarin/xamarin-android#8530]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VSMac 17.6.3 (build 421)

### Description

I am rewritting a native Android and iOS application into a single MAUI application.
This application uses 4 main native libraries, that I have binded successfully.

Those native libraries has many dependancies, sush as com.vonage:webrtc which is a 200MB aar for instance.

For iOS, the final Release ipa is 210Mb, versus 50MB with the one built in native with Swift and xCode.
For Android, the final Release apk is 400MB, versus 90MB with the one build in native with Java and Android Studio.

In Debug, apk size is 49MB... And the limit to publish an app to the Play Store is 200MB.

How can I reduce the size please ? Is it an issue with binded library ?
I really need to go under 200MB, else it is a show stopper :x After months of binding, I cannot believe it.

I've tried to follow those advices https://devblogs.microsoft.com/dotnet/dotnet-7-performance-improvements-in-dotnet-maui

### Steps to Reproduce

Use the following repo to compare build size
https://github.com/espritm/MAUI.Binding_Libraries_App_Size_Perfs

It is a sample MAUI app with a dependency to one of the 4 main library I have binded (ESignature).
Building the app without the dependency gives a 9MB apk.
Building the app with the dependency in Debug gives a 28MB.
Building the app with the dependency in Release gives a 84MB.

### Did you find any workaround?

No, I cannot publish to the store because of the apk size.

**Comment by jpobst** [comment]
Have you actually tried uploading your application to Google Play?

My guess is you are actually creating an `.aab` instead of an `.apk`, since Google Play no longer accepts `.apk` packages.  An `.aab` contains code and files for all architectures instead of just one.  Google then creates an architecture-specific `.apk` for each architecture your application supports.  The `.apk` that Google creates must be under 200 MB, but the `.aab` you upload should be able to be bigger.

For example, with `com.vonage:webrtc`, there are 4 copies of `libwebrtc.a`, each are about ~50 MB:

* `jni/arm64-v8a`
* `jni/armeabi-v7a`
* `jni/x86`
* `jni/x86_64`

All four of them will be in the `.aab`, but only one will be in each architecture-specific `.apk` Google creates.

**Comment by jonathanpeppers** [comment]
Another way to estimate what the size would be on Google Play, is to build for a single architecture with `dotnet build -c Release -r android-arm64 -p:AndroidPackageFormat=apk` and see what the resulting `.apk` is.

> This application uses 4 main native libraries, that I have binded successfully.

Is there also a lot of Java/Kotlin code? One difference in Android Studio is they use r8 by default, while we don't do that yet. You can opt into this by setting `AndroidLinkMode=r8`.

**Comment by espritm** [comment]
Thanks a lot for your responses, and sorry for my late answer. I have had to fix a lot of issues with my AAB to be able to submit it to PlayStore..

I've built the project with the following command line
`dotnet build -c ReleasePROD -r android-arm64 -p:AndroidPackageFormat=apk -f:net7.0-android`

I've switched on the R8 code shrinker and the result apk is now 328MB (400MB without R8 option).


Now I've built the AAB with the following command line 
`dotnet publish -f:net7.0-android -c:Release`

The AAB is now 253MB (264MB without R8 option).

I've tryied to upload this 253MB AAB file to the PlayStore but it told me the app was containing Debugs stuff.

By setting `<DebugSymbols>false<DebugSymbols>`, the AAB was 232MB, and accepted to upload to the PlayStore.

In the PlayStore Console, in the App Bunble Explorer, I open the uploaded aab and navigate to Download tab. 
The size of the Signed Universal Apk is 259MB.
The size of the APK per specific device is also displayed, and it varies between 169 and 172MB. 
So I think it is OK for now I may be able to publish. Thanks !

But still the native Java/Kotlin app is 95MB with the same libraries, and much more source code lines (90k vs 65k with MAUI).
Any other options I should investigate to reduce the size please ?

**Comment by espritm** [comment]
Thanks a lot for your responses, and sorry for my late answer. I have had to fix a lot of issues with my AAB to be able to submit it to PlayStore..

I've built the project with the following command line
`dotnet build -c ReleasePROD -r android-arm64 -p:AndroidPackageFormat=apk -f:net7.0-android`

I've switched on the R8 code shrinker and the result apk is now 328MB (400MB without R8 option).


Now I've built the AAB with the following command line 
`dotnet publish -f:net7.0-android -c:Release`

The AAB is now 253MB (264MB without R8 option).

I've tryied to upload this 253MB AAB file to the PlayStore but it told me the app was containing Debugs stuff.

By setting <DebugSymbols>false<DebugSymbols>, the AAB was 232MB, and accepted to upload to the PlayStore.

In the PlayStore Console, in the App Bunble Explorer, I open the uploaded aab and navigate to Download tab. 
The size of the Signed Universal Apk is 259MB.
The size of the APK per specific device is also displayed, and it varies between 169 and 172MB. 
So I think it is OK for now I may be able to publish. Thanks !

But still the native Java/Kotlin app is 95MB with the same libraries, and much more source code lines (90k vs 65k with MAUI).
Any other options I should investigate to reduce the size please ?

**Comment by jonathanpeppers** [comment]
If you want us to investigate the size of your app, can you share it?

You could also list the contents of the C# vs Java/Kolin app with a tool like 7-zip (`7z l`) or [apkdiff](https://www.nuget.org/packages/apkdiff/).

**Comment by jonathanpeppers** [comment]
Oh you also mentioned your app is a MAUI application. How does the size compare if it is a plain .NET 8 Android app? That is closer to a Java/Kotlin project.

MAUI is not currently trimmable and it contributes to app size quite a bit:

https://github.com/dotnet/maui/issues/18658

**Comment by jonathanpeppers** [comment]
For the second `apkdiff` output, it looks like you are comparing an app bundle for 4 architectures. Did you mean to compare a single-architecture `.apk` instead?

The number of `.so` files and `classes*.dex` files are native and Java code respectively. I don't see how MAUI or .NET Android impacts the size of these files.

Are you able to share the `.apk` files you are comparing?

**Comment by espritm** [comment]
Thank you for your answer and your analyze.
I have created an appcenter repo to provide apks : https://appcenter.ms/users/maxime.esprit-gmail.com/apps/Analyze-apk-size
The 5.4.3.10 is the MAUI application, whereas the 3.5.6.2 is the native Java Kotlin application.
