### ISSUE TITLE
MonoDroid will try to connect the Debugger, but USB-C cable is not attached. This keeps hanging up on the start of our app

### ISSUE THREAD

**Issue by SprengerS** [xamarin/xamarin-android#8540]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.NET SDK 7.0.311, VS Mac 17.6.7

### Description

Sometimes a Debug Build of our App hangs at Startup in the Launchscreen. Clearing via Task Manager is not working. After every startup the app keeps hanging in the launch screen. Only a new deployment via Visual Studio resolves this issue. I found out that monodroid-debug wants to connect the debugger with big timeout. Perhaps this might be the problem. Here is my Logcat screen 
![Bildschirmfoto 2023-11-29 um 11 51 49](https://github.com/xamarin/xamarin-android/assets/44831004/6bcc8586-709a-4e4a-ba2c-95810c9f655a)

I'm using this workloads: 
![image](https://github.com/xamarin/xamarin-android/assets/44831004/be5b2e00-b4a1-4fa8-9bf4-6bbddc991996)

### Steps to Reproduce

1. Deploy a Debug build on your mobile phone
2. Disconnect it from usb-c cable.
3. Try to start it. It can hang in the launch screen or it can start

**Comment by jpobst** [comment]
@grendello @jonathanpeppers Is this the intended behavior?

Once we deploy a Debug version of an app, is it always flagged to look for the debugger?

**Comment by jonathanpeppers** [comment]
I think the problem is `adb shell setprop` isn't cleared until you reboot the device.

@SprengerS what is the result of `adb shell 'getprop | grep mono'` when your app "hangs" at startup? I suspect there is just a leftover debugging setting there.

**Comment by grendello** [comment]
I think @jonathanpeppers is right, it's probably a stale property.

**Comment by SprengerS** [comment]
@jonathanpeppers: when our app hangs the next time I will execute your command in the terminal. It is strange, that this problem occurs since .net7. This problem never occurs with Xamarin Android.

**Comment by SprengerS** [comment]
@jonathanpeppers: now my app hangs again and I have printed out the result of `adb shell 'getprop | grep mono'`: 
```
[debug.mono.extra]: [debug=127.0.0.1:8773:8774,timeout=1701357162,loglevel=0,server=y]
```

Here is the screenshot:
![image](https://github.com/xamarin/xamarin-android/assets/44831004/2df91ed5-6622-487f-bee9-8928ec56b4d3)

**Comment by jonathanpeppers** [comment]
Right, so if `debug.mono.extra` is set, that is the behavior you get.

I believe VS should "unset" it if you close VS, we can file an issue with the IDE if it's not doing that?

**Comment by grendello** [comment]
> Right, so if `debug.mono.extra` is set, that is the behavior you get.
> 
> I believe VS should "unset" it if you close VS, we can file an issue with the IDE if it's not doing that?

I'd say it should clear it when it first connects to the device and, if possible, just after debugging session is terminated in any way.

It's possible that the property was set outside VS, so there should be no assumptions made as to what is its state.

**Comment by jonathanpeppers** [comment]
This is also VS Mac, which we're not going to see a lot of fixes for.

@SprengerS is the behavior better (or different?) in Visual Studio Windows or VS Code?

**Comment by SprengerS** [comment]
I don't use VS for Windows and Android Development. I have used VS Mac and now because of cancelling VS Mac for the future we are using Rider. But with both IDEs this problem is existing.

**Comment by jpobst** [comment]
Sounds like this is an issue in Rider and should be filed with them.

If there is also an issue in VSWin or VSMac, please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue. This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.
