### ISSUE TITLE
AppCompatAlertDialog does not dim background on android 34 emulator

### ISSUE THREAD

**Issue by Alex-Dobrynin** [xamarin/xamarin-android#8544]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.net8 android 34 emulator

### Description

Hi, when I show alert dialog on android 34 emulator .net8 everything behind the dialog is not being dimmed as it worked on android 33.
I'm not sure is it issue with emulator only or also with real device too, because I don't have real device v34.
On android v33 real device and emulator everything works well

### Steps to Reproduce

1. Create class CustomAppCompatDialogFragment
2. inherit from AppCompatDialogFragment
3. Override method OnCreateDialog(Bundle bundle) and create dialog as next: 
```
var builder = new AppCompatAlertDialog.Builder(Activity).SetCancelable(false);
builder.SetMessage("some text");
return builder.Create();
```
4. Show this fragment frag.Show(activity.SupportFragmentManager, "sometag");

### Did you find any workaround?

nope

**Comment by jpobst** [comment]
Ultimately, all .NET Android does is provide generated wrappers that allow you to call Google’s Android API. As these are not our API's, we do not have much expertise in how to use them properly. 

You will likely need to use the Android API documentation and relevant Google forums to determine the intended behavior of this API and whether this is a Android bug or not.

**Comment by Alex-Dobrynin** [comment]
@jpobst this is true, found answer on stackoverflow about this, this is new feature of android (or bug) itself
