### ISSUE TITLE
Error APT2260 after upgrading to .NET 8 from 7

### ISSUE THREAD

**Issue by Iron2213** [xamarin/xamarin-android#8606]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.NET 8, VS2022

### Description

As the title says, after upgrading our Android application to .NET 8 from .NET 7 we're unable to build because of the following errors:

**3>Resources\values\themes.xml(2): error APT2260: resource attr/colorSurface (aka <package name>:attr/colorSurface) not found.**

for multiple resources.

We tried deleting "bin" e "obj" folders, we tried upgrading and not upgrading to API 34 and updating all nuget packages.

This is our ".csproj" file after updating:
```
...
  <PropertyGroup>
	  <TargetFramework>net8.0-android</TargetFramework>
	  <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
	  <OutputType>Exe</OutputType>
	  <Nullable>disable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <UseMauiEssentials>true</UseMauiEssentials>
	  <ApplicationId>[package name]></ApplicationId>
	  <ApplicationVersion>1</ApplicationVersion>
	  <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>
...
```

### Steps to Reproduce

We're unable to reproduce with a new project, yet.

### Relevant log output

[build_log.txt](https://github.com/xamarin/xamarin-android/files/13728636/build_log.txt)

**Comment by jonathanpeppers** [comment]
Can you share a `.binlog` of the error? https://aka.ms/binlog
