### ISSUE TITLE
Time format picks 12 hour clock instead of 24 hour clock if language is English (Denmark)

### ISSUE THREAD

**Issue by xanderh** [xamarin/xamarin-android#8669]
### Android application type

Classic Xamarin.Android (MonoAndroid13.0, etc.)

### Affected platform version

VS 2022 version 17.7.1

### Description

When users select the device language English (Denmark), the time format is inconsistent with native Android time formats. DateTime.ToShortDateString will display the time in 12-hour format, while native Android elements will display it in 24-hour format, and the TimeClock view will pick the 24-hour format. 

The native Android implementation is correct, as Denmark uses 24-hour formats, not 12-hour formats. 

I have not tested against .net7 and .net8 apps yet, but I am expecting that to have the same bug. 

### Steps to Reproduce

1. Select English (Denmark) as the device language
2. Call DateTime.ToShortTimeString on any datetime
3. Output is in 12-hour format, rather than 24-hour format

**Comment by jpobst** [comment]
I would suggest testing this out on .NET 7 or .NET 8 Android.  Culture-aware operations is an area where there are large differences between the `Xamarin.Android` version of Mono and the `dotnet` version of Mono.  

With `Xamarin.Android` almost at EOL, this is unlikely to meet the bar for a servicing patch, however it is something that should be fixed if it is still incorrect in `dotnet`.

**Comment by xanderh** [comment]
I can confirm that it works correctly on .net android, so it's just an issue with xamarin. 
Thank you!

**Comment by jpobst** [comment]
Closing, as issue only happens in Classic Xamarin.Android which is EOL.
