### ISSUE TITLE
`dotnet-trace` speedscope report: the call of one method is divided into different pieces

### ISSUE THREAD

**Issue by JaneySprings** [xamarin/xamarin-android#8696]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.NET 8.0

### Description

Hi! I am analyzing the report received with `dotnet-trace` and noticed a strange behavior (it seems to me): I call one method three times. For the first time, it is divided into many small calls. Moreover, you can see how the calls are slightly shifted (even if you look at the colors):
<img width="1440" alt="Screenshot 2024-02-02 at 22 13 12" src="https://github.com/xamarin/xamarin-android/assets/48021947/e0872f7e-11f0-4ce4-a637-e52bcdcdd2d2">

But the next two calls look right:
<img width="1440" alt="Screenshot 2024-02-02 at 22 16 44" src="https://github.com/xamarin/xamarin-android/assets/48021947/82d1cc74-8455-4b56-849c-24febab53860">

### Steps to Reproduce

I attached a `speedscope.json` for example. Maybe it will helpful.

[com.companyname.agendaviewexample.speedscope.json](https://github.com/xamarin/xamarin-android/files/14143774/com.companyname.agendaviewexample.speedscope.json)

**Comment by jpobst** [comment]
@jonathanpeppers I guess you're our speedscope expert.

**Comment by jonathanpeppers** [comment]
We should probably move the issue here somehow:

* https://github.com/dotnet/diagnostics/issues

I think there are still a couple issues with Mono diagnostics even in .NET 8, for example: 

* https://github.com/dotnet/diagnostics/issues/4477

**Comment by jpobst** [comment]
We can't easily move issues across organizations.

@JaneySprings Would you mind refiling this at https://github.com/dotnet/diagnostics/issues?

**Comment by JaneySprings** [comment]
@jpobst Done!

**Comment by jonathanpeppers** [comment]
Closing in favor of: https://github.com/dotnet/diagnostics/issues/4490

Thanks!
