### ISSUE TITLE
Java source file set build-action "AndoidJavaSource" in project causes compile error

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#8698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Java-source-file-set-build-action-Andoi/10567325)._

---
[regression]
VS2022 Ver.17.8.4 with .net8.0-android34.0 project
Java sources within project those which build-action set to "AndroidJavaSource" causes compile error.

After cleaning the solution or project, the build is successfully, and success to deploy package into device, too.
And .cs files(callable-wrapper files) are generated in /obj/Debug/net8.0-android34.0/generated/src/, but IDE continue to indicate CS0246 error and so on.

After change the source , build is fault with error and files in generated/src are deleted.
We add generated .cs files to the project , IDE's error is disapeared, but build failed with dupulicate definition error.

After all we need to clean→build every time to debug the source.

How can I add Java source code to a project without getting an error?

---
#### Feedback Bot on 1/23/2024, 08:52 PM: 

(private comment, text removed)
#### Dean Ellis [MSFT] on 1/24/2024, 06:05 AM: 

(private comment, text removed)
#### デスクトップPC ユーカリ on 1/24/2024, 07:01 AM: 

(private comment, text removed)
#### デスクトップPC ユーカリ on 1/26/2024, 08:27 AM: 

(private comment, text removed)
#### デスクトップPC ユーカリ on 1/26/2024, 04:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StudioLMZa** [comment]
This is the bug?
Is interoperability between C# and Java impossible at the source code level?

**Comment by dellis1972** [comment]
Do you have a sample which demonstrates the issue?

**Comment by StudioLMZa** [comment]
[AndroidApp2.zip](https://github.com/xamarin/xamarin-android/files/14215479/AndroidApp2.zip)
This is the sample to reproduce the issue.

**Comment by StudioLMZa** [comment]
> Do you have a sample which demonstrates the issue?

This is the sample to reproduce.
[AndroidApp2.zip](https://github.com/xamarin/xamarin-android/files/14215520/AndroidApp2.zip)
![image](https://github.com/xamarin/xamarin-android/assets/159449811/b5f8c31c-0b15-420f-bfe9-00fcab50e4d1)

**Comment by dellis1972** [comment]
@StudioLMZa 

I suspect you are hitting the same issue as https://github.com/xamarin/xamarin-android/issues/8658. 

Can you try adding the following to the first PropertyGroup in your csproj.
```xml
<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
```

See if that helps. Alternatively in Visual Studio goto 

Tools | Options | Projects and Solutions | SDK-Style Projects

and disable the "Up to Date Checks".

**Comment by StudioLMZa** [comment]
When I tried it, a compile error occurred, but I was able to deploy it.
However, this option prevents to detect the change code with "build". After all, I have to "rebuild" and compile all the code every time to deploy.
Is this spec?

**Comment by dellis1972** [comment]
ok, so its Intellisense which is not working.

**Comment by StudioLMZa** [comment]
yes, Intellisense is not working at all, even if *.cs exists in object/.../generated folder or not.
And the generated *.cs files are disappeared when build after rebuild even if DisableFastUpToDateCheck is true or not.

**Comment by dellis1972** [comment]
> yes, Intellisense is not working at all, even if *.cs exists in object/.../generated folder or not. And the generated *.cs files are disappeared when build after rebuild even if DisableFastUpToDateCheck is true or not.

One of our targets is not running during the Intellisense build. I thought we had fixed that.....
It looks like the `Install` target is deleting the .cs files, I'm going to be looking at that next week.

**Comment by StudioLMZa** [comment]
Has there been any progress about this issue?

**Comment by StudioLMZa** [comment]
Thank you for the information.
