### ISSUE TITLE
Crashes on client devices `xamarin::android::internal::MonodroidRuntime::mono_log_handler`

### ISSUE THREAD

**Issue by NerijusN** [xamarin/xamarin-android#8725]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 17.7.6

### Description

Clients experience crashes and google threatens to remove the app as we went over 8%.

Play Google Crash details logs say: `[split_config.arm64_v8a.apk!libmono-android.release.so] xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)`

There are bunch of devices reported but mainly Samsungs and Huaweis. There is no pattern in Android API reported.

Issue is very similar what is reported here: https://github.com/xamarin/xamarin-android/issues/7335
Following what other people did first I tried to re-create the problem so

.csproj contains:
```
<PropertyGroup>
	<EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	<AndroidManagedSymbols>True</AndroidManagedSymbols>
	<AndroidEnableSGenConcurrent>True</AndroidEnableSGenConcurrent>
	<AndroidAotAdditionalArguments>nodebug,no-write-symbols</AndroidAotAdditionalArguments>
	<AndroidUseDefaultAotProfile>False</AndroidUseDefaultAotProfile>
	<AndroidUseAapt2>True</AndroidUseAapt2>
</PropertyGroup>

<PropertyGroup>
	<AndroidEnableProfiledAot>True</AndroidEnableProfiledAot>
	<EnableLLVM>False</EnableLLVM>
	<Optimize>True</Optimize>
	<RunAOTCompilation>True</RunAOTCompilation>
</PropertyGroup>
```

All our other projects are .NetStandat2.0 except one
```
<PropertyGroup>
		<TargetFrameworks>net6.0-windows10.0.18362;net6.0-android;net6.0-ios;netstandard2.0</TargetFrameworks>
</PropertyGroup>
```

Also we build with .NET SDK 7.0.302		

1. How I could find out what piece of my C# code causes the problem?
1. What I should update to get issue solved as #7335 seems to be merged in?

### Steps to Reproduce

Can't reproduce even I run [script profile.ps1](https://github.com/xamarin/xamarin-android/files/9525079/Neuer_Ordner.zip) but crash never reproduced locally ~300 loops total. 

Maybe my phones, google pixel 3a and One Plus8 are too good?

### Did you find any workaround?

No

### Relevant log output

```shell
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 30906 >>> [app.identifier] <<<

backtrace:
  #00  pc 0x0000000000051ce8  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x00000000000474c8  /data/app/~~[obfuscated]==/[app.identifier]-[obfuscated]==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: [obfuscated])
  #02  pc 0x00000000002dac50  /data/app/~~[obfuscated]==/[app.identifier]-[obfuscated]==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: [obfuscated])
  #03  pc 0x00000000002dacd8  /data/app/~~[obfuscated]==/[app.identifier]-[obfuscated]==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: [obfuscated])
  #04  pc 0x0000000000253620  /data/app/~~[obfuscated]==/[app.identifier]-[obfuscated]==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: [obfuscated])
  #05  pc 0x0000000000256d5c  /data/app/~~[obfuscated]==/[app.identifier]-[obfuscated]==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: [obfuscated])
  #06  pc 0x00000000002516f4  /data/app/~~[obfuscated]==/[app.identifier]-[obfuscated]==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: [obfuscated])
  #07  pc 0x00000000002529f8  /data/app/~~[obfuscated]==/[app.identifier]-[obfuscated]==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: [obfuscated])
  #08  pc 0x0000000000265cb4  /data/app/~~[obfuscated]==/[app.identifier]-[obfuscated]==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: [obfuscated])
  #09  pc 0x0000000000004c00
```

**Comment by jpobst** [comment]
It doesn't look like https://github.com/xamarin/xamarin-android/pull/7732 was backported to `net6.0-android`.  You will need to update your app to `net7.0-android` or `net8.0-android` in order to get that fix.

Because .NET Android workloads are separate from .NET, they are based on the `<TargetFramework>` instead of the installed .NET.  So even though you have .NET 7 installed, it downloads the `net6.0-android` workload and uses it.  Thus it does not have any fixes released to `net7.0-android`.

**Comment by jeanplevesque** [comment]
Thank you for the information @jpobst!

1. How can we know exactly which version of the Android workload is being used?
2. Do we need to update only the **startup project** to .NET 7/8 or do we need to also update the **dependencies** (the ones that are currently targeting `net6.0-android`)?

**Comment by jpobst** [comment]
> How can we know exactly which version of the Android workload is being used?

You should also see a message like this in your build log with the version number:

```
MonoAndroid Tools: C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\
```

> Do we need to update only the startup project to .NET 7/8 or do we need to also update the dependencies (the ones that are currently targeting net6.0-android)?

This issue is in the application runtime, so updating the startup project should be enough.
