### ISSUE TITLE
Regarding License info of Microsoft.Android.Ref 31.0.101-preview.9.16

### ISSUE THREAD

**Issue by Harshitha1369** [xamarin/xamarin-android#8779]
### Android application type

Classic Xamarin.Android (MonoAndroid13.0, etc.)

### Affected platform version

Xamarin Android

### Description

I am trying to look license for this component - Microsoft.Android.Ref31.0.101-preview.9.16 of version (31.0.101-preview.9.16) for a project.

NuGet.org shows license info as XamarinStudio License. But in Project website, it redirects to Git repo (https://github.com/xamarin/xamarin-android) which has MIT License for other release branches.

I could not find this branch 31.0.101-preview.9.16 in Git repo unlike other release branches.

Can you please share the license Microsoft.Android.Ref31.0.101-preview.9.16 comes under? is it MIT License or XAMARIN SOFTWARE LICENSE ?

It would be helpful if you can share git repo referring to this release branch - 31.0.101-preview.9.16.

Thanks & Regards,
Harshitha

### Steps to Reproduce

On Microsoft.Android.Ref31.0.101-preview.9.16

**Comment by jpobst** [comment]
@pjcollins @jonathanpeppers It looks like we need to update the license we are shipping in our workload packs:
https://www.nuget.org/packages/Microsoft.Android.Ref.33

**Comment by jonathanpeppers** [comment]
There are definitely files in our MSBuild packs that are under the old Xamarin license. Anything from monodroid or androidtools, for example. We could make the license for the Ref & Runtime packs MIT, though?

I also wonder if the Xamarin license should be updated to something else now.

@jonpryor probably has comments.

**Comment by Harshitha1369** [comment]
Hi, 

Would like to add on here, I am looking basically only for this nuget package alone - **Microsoft.Android.Ref** and specifically this version - **31.0.101-preview.9.16**.

On app review, this version(31.0.101-preview.9.16) is not able to categorise to which license it's under and the git repo of it is not found for this version. So I am blocked until I get the main license file of this version 31.0.101-preview.9.16.

https://www.nuget.org/packages/Microsoft.Android.Ref/31.0.101-preview.9.16
**This is tagged with .Net 6.0**

https://www.nuget.org/packages/Microsoft.Android.Ref/31.0.101-preview.9.16/License.

Though I upgraded all Xamarin packages, this version always comes up in mono.android.jar file. So, I need the license file link of this version(31.0.101-preview.9.16) in order to validate, if License.md file of this version in git has MIT license.

**Comment by jonathanpeppers** [comment]
@Harshitha1369 I have no idea what you're trying to accomplish, but we certainly aren't going to go back and retroactively update _old_ packages with new licenses. We could fix the license going forward in .NET 9, though.

Of course, you can always go build from source yourself and use the artifacts. The MIT-license is meant for this use-case.

That package is from 2021, but perhaps you could try building the repo on the .NET 6 release branch:

* https://github.com/xamarin/xamarin-android/tree/release/6.0.4xx

**Comment by Harshitha1369** [comment]
This package here https://www.nuget.org/packages/Microsoft.Android.Ref/31.0.101-preview.9.16 -

Is this the git repo of released version **31.0.101-preview.9.16** - https://github.com/xamarin/xamarin-android/tree/release/6.0.4xx as mentioned above?

**Comment by jonathanpeppers** [comment]
This is the correct repo, but I have no idea what commit might correspond to 31.0.101-preview.9.16. Check if there is a git sha inside the package? You might also be able to find something in old tags or GitHub releases.

**Comment by jonathanpeppers** [comment]
If you inspect `Mono.Android.dll` inside that package with ILSpy, it has:
```csharp
[assembly: AssemblyInformationalVersion("31.0.101.16; git-rev-head:2c2302a; git-branch:release/6.0.1xx-preview9")]
```

**Comment by Harshitha1369** [comment]
Thanks a lot. It shows here: https://nuget.info/packages/Microsoft.Android.Ref/31.0.101-preview.9.16 inside

Full Name:Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065Strong Name:Yes, version 0.0.0.0AssemblyCompany:Microsoft CorporationAssemblyInformationalVersion:31.0.101.16; git-rev-head:2c2302a; git-branch:release/6.0.1xx-preview9AssemblyMetadata:Key = IsTrimmable, Value = TrueAssemblyProduct:Xamarin.AndroidAssemblyTitle:Mono.Android.dll

So It looks, it's from 6.0.1xx-preview9 branch, is that correct?

**Comment by jonpryor** [comment]
Building off of @jonathanpeppers [comment](https://github.com/xamarin/xamarin-android/issues/8779#issuecomment-1973754923), 31.0.101-preview.9.16 was built from this commit: https://github.com/xamarin/xamarin-android/commit/2c2302a

@Harshitha1369: Yes, it was built from the [release/6.0.1xx-preview9 branch](https://github.com/xamarin/xamarin-android/commits/release/6.0.1xx-preview9).  Also note that this branch is for .NET 6.0 Preview 9; it is not a stable version.  Additionally, .NET 6.0 is no longer supported.

How and why are you using [31.0.101-preview.9.16](https://nuget.info/packages/Microsoft.Android.Ref/31.0.101-preview.9.16)?

**Comment by Harshitha1369** [comment]
The app is using Xamarin and is not migrated to MAUI as the app is only support and no feature enhancement. 

I am not specifically downloading [31.0.101-preview.9.16](https://nuget.info/packages/Microsoft.Android.Ref/31.0.101-preview.9.16) this package but it's coming from bin and obj via mono, though all Xamarin package are upgraded to latest.

**Comment by jonpryor** [comment]
@jonathanpeppers [wrote](https://github.com/xamarin/xamarin-android/issues/8779#issuecomment-1973607024):

> There are definitely files in our MSBuild packs that are under the old Xamarin license. Anything from monodroid or androidtools, for example. We could make the license for the Ref & Runtime packs MIT, though?
> 
> I also wonder if the Xamarin license should be updated to something else now.
> 
> @jonpryor probably has comments.

Boy do I!

Currently, all of our packages contain the same license, and because CI contains commercial repo checkouts, the commercial license is used:

https://github.com/xamarin/xamarin-android/blob/60dbcc9fe482dddc1085c003d3a18209709cbb35/build-tools/create-packs/License.targets#L7

@pjcollins: How hard would it be to instead use different licenses for different NuGet packages?  Presumably we'd want something like:

  * `Microsoft.Android.Templates`: MIT
  * `Microsoft.Android.Ref.*`: MIT (it's only reference assemblies!)
  * `Microsoft.Android.Runtime.*`: MIT
  * `Microsoft.Android.Sdk.*`: MIT for OSS builds, Commercial for CI builds (what we currently do)

If this isn't too difficult, maybe we can do this for .NET 9?

**Comment by pjcollins** [comment]
Should be easy enough to update our packs to contain different license files. For the cases where we want to include MIT or OSS should we just include https://github.com/xamarin/xamarin-android/blob/2bd13c4a00ae78db34663a4b9c7a4c5bfb20c344/LICENSE instead? Do we want to update the product name in that license file to something like ".NET Android SDK"?

**Comment by jonpryor** [comment]
@pjcollins [asked](https://github.com/xamarin/xamarin-android/issues/8779#issuecomment-1973941211):

> For the cases where we want to include MIT (or MIT for OSS) should we just include https://github.com/xamarin/xamarin-android/blob/2bd13c4a00ae78db34663a4b9c7a4c5bfb20c344/LICENSE instead?

Yes, I think that should be fine.

> Do we want to also update the product name in that license file to something like ".NET Android SDK"?

I'm looking for guidance on this, but none of the dotnet repos I looked at have _any_ name listed:

  * https://github.com/dotnet/maui/blob/126f47aaf9d5c01224f54fe1c6bfb1c8299cc2fe/LICENSE.txt
  * https://github.com/dotnet/runtime/blob/5a767f24c2fd90b263b8939de841f4f1eb80037e/LICENSE.TXT
  * https://github.com/dotnet/sdk/blob/45cae3e95a7376e283f8cd5c840dafc48ac3bec2/LICENSE.TXT
  * https://github.com/dotnet/installer/blob/7c393400d236bfb80819e52f2945b9ddf28f2b73/LICENSE

Maybe we should just remove the first two lines, and standardize the 5th (now 3rd) line?

> Copyright (c) .NET Foundation and Contributors
