### ISSUE TITLE
Compilation error 'CS0506' while creating bindings for a Java class that inherits Java.Lang.Thread

### ISSUE THREAD

**Issue by mathidlx** [xamarin/xamarin-android#8843]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 2022, .NET 8.0

### Description

The Stop method in original Java.Lang.Thread class is inheritable. The Mono.Android assembly the Stop method in Java.Lang.Thread is not marked virtual, causing the following compilation error while generating bindings for a java class (let's call it MyExampleThread) that inherits Java.Lang.Thread class. 

Error CS0506: 'MyExampleThread.Stop()': cannot override inherited member 'Thread.Stop()' because it is not marked virtual, abstract, or override (CS0506)

It's understood that the Stop method is deprecated, but we are using a vendor's library which has a class that extends Java.Lang.Thread.

### Steps to Reproduce

This issue is clear just looking at the code for the Java.Lang.Thread class in Mono.Android assembly. It's not marked virtual.

    [Obsolete("deprecated")]
    [Register("stop", "()V", "")]
    public void Stop();

Just to point out as an example, if you look at the start method which is inheritable from Java.Lang.Thread, it's marked as virtual in Java.Lang.Thread class in Mono.Android assembly and it doesn't give the compilation error.

![image](https://github.com/xamarin/xamarin-android/assets/91144477/f4e72af1-deb1-47ea-b100-2457534e60c8)

Note: It's understand that the Stop method is deprecated in Java, but that shouldn't have an effect on overriding the method and give a compilation error.

**Comment by jpobst** [comment]
Interestingly, looking at the [Android documentation](https://developer.android.com/reference/java/lang/Thread#stop()) and even the [Java documentation](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#stop--), `stop ()` is marked as `final`, and thus should not be `virtual` in C#.

```java
public final void stop () { ... }
```

I don't see how the vendor library could have overridden `Stop`.  Is there something else that could be going on here?

**Comment by mathidlx** [comment]
Thanks for link to the documentation. I presumed the Stop method is overridable by looking at the decompiled java code from the vendor library.  The Java compiler shouldn't have allowed this if the subclass was overriding the Stop method (which appears to be the case looking at the method signature). If the method was being overloaded in the subclass, we shouldn't see the compilation error we are seeing with the C# compiler. I will connect with the vendor and see what's going on. This issue can be closed as the Java.Lang.Thread class in Mono.Android is in line with the documentation.
