### ISSUE TITLE
Hybrid Blazor maui default example don't work, errors

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#8851]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hybrid-Blazor-maui-default-example-dont/10594059)._

---
[severity:I'm unable to use this version]
I just used the plain template. Did not changed anything. 
Just run it as windows machine and gives an error "the project needs to be deployed before we can debug. Please enable Deploy". in the configuration manager. 
In the configuration manager Deploy and debug are checked. 

Launch it in android mode it wil start the emulator. Tells met that the device is found at 5554.
Emulator closes and the error tells me that there are deployment errors. (continu? (yes/no)). With no it ends with
Severity	Code	Description	Project	File	Line	Suppression State
Error		XA0129: Error deploying 'files/.__override__/System.Net.Quic.dll'.
Please set the 'EmbedAssembliesIntoApk' MSBuild property to 'true' to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor.	

Actions:
- Multiple time deleted the solution with the error and created a new one with a different name. 
- looked up errors on the internet. But only simulair about line 40 and 35, with diffent problems.

(Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 13, Reason: 'com.companyname.hybrid_blazor_maui_app' schendt pattern-beperking van '[-. A-Za-z0-9]+'.
Het kenmerk 'Name' met de waarde 'com.companyname.hybrid_blazor_maui_app' kan niet worden geparseerd.	Hybrid Blazor Maui App			

- Repair with VS installer. It downloaded and reinstalled VS (vs 2022 -17.9) 

Tried again and run into the same problem.  

Sysinfo:
Windows 11 (with latest update) 
Edge, chrome, firefox installed

Hardware Lenovo Ideapad 5 pro (16") 
Processor	AMD Ryzen 9 5900HX with Radeon Graphics           3.30 GHz
Installed RAM	32.0 GB (27.9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

--------
But the problem is all over the place.
My other notebook (Lenovo Yoga i7) with windows 11 and VS 2022 17.8.3 installed comes with the same problem as told you above. 

Theproblem is only by the template '.net Maui Blazor Hybrid app' 

I hope you can trace the problem and solve it. 
Thank you. 
Dinand

---
#### Feedback Bot on 2/25/2024, 05:58 PM: 

(private comment, text removed)
#### Dean Ellis [MSFT] on 2/28/2024, 01:36 PM: 

(private comment, text removed)
#### Dinand van Hartingsveldt on 2/29/2024, 00:30 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
```
Error DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: 
App manifest validation error: The app manifest must be valid as per schema: 
Line 10, Column 13, Reason: 'com.companyname.hybrid_blazor_maui_app' 
schendt pattern-beperking van '[-. A-Za-z0-9]+'.
```

This one looks like you cannot use the underscore character in your project name.
