### ISSUE TITLE
VS2022 cannot find/use drawable resource in Xamarin.Wear

### ISSUE THREAD

**Issue by zlbcdn** [xamarin/xamarin-android#8865]
### Android application type

Classic Xamarin.Android (MonoAndroid13.0, etc.)

### Affected platform version

VS community2022 , 17.8.5

### Description

I create a Xamarin.Wear solution，i found :1、in the solution, there is a folder "drawable", it seems good,but there is none in the real path , so i create a folder drawable in manually。2、then i add some png to the drawable folder. but can't get the resource. the details blow 
![000](https://github.com/xamarin/xamarin-android/assets/6919400/a887a5cc-da40-4fa2-b7bf-647924d16a4f)
![001](https://github.com/xamarin/xamarin-android/assets/6919400/d4673675-46a0-46b3-9086-32852497fad6)
![002](https://github.com/xamarin/xamarin-android/assets/6919400/0e4334d2-876b-4e0d-838a-cf885a24e19c)

### Steps to Reproduce

1、Create a Xamarin.Wear solution
2、 can find the drawable in the solution，but it don't exist in the real path 
3、 add the drawable folder in manual, and add a png
4、can't get/use the drawable resource

**Comment by zlbcdn** [comment]
holy *, i rename the 000.png to a000.png. it works!!! 
last night,i spend at least 3 hours!!!!! what a waste!!!!

**Comment by dellis1972** [comment]
Android has a requirement thst resource files must start with a character, and cannot contain certain characters. If you looked in your build output there was probably a warning about that file.

**Comment by jonathanpeppers** [comment]
You can't even name a C# field or property `000`. Java and Kotlin are the same, and so you can't name an `AndroidResource` that (they have an `R.java` class).

@zlbcdn if you don't see a warning or error about the file let us know, we should look into that. Otherwise, I think this is solved, thanks!
