### ISSUE TITLE
Cannot add System.Json to an Android .NET 8 project

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-android#8916]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 2022, .NET 8

### Description

I'm trying to add the `System.JSON` to an Android with .NET 8 project that I'm migrating from Xamarin, and only this library is not being recognized:

<img width="1127" alt="image" src="https://github.com/microsoft/dotnet/assets/1666156/9e4cd9d5-8d55-4efe-8615-aede07b929b9">

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>22</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>tk.supernovaic.themayanroute</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Json" Version="4.7.1" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.23" />
    <PackageReference Include="Xamarin.AndroidX.Preference" Version="1.2.1.4" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.10.0.3" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.Utils" Version="1.0.0.23" />
    <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.8.0" />
  </ItemGroup>
```

### Steps to Reproduce

- Create a .NET for Android project.
- Add the `System.Json` lib from the NuGet.
- Try to use it.

<img width="1127" alt="image" src="https://github.com/microsoft/dotnet/assets/1666156/9e4cd9d5-8d55-4efe-8615-aede07b929b9">

### Did you find any workaround?

To use Xamarin.Android only maybe? It used to work there.

**Comment by dellis1972** [comment]
@FANMixco My guess is you really want to be using `System.Text.Json` which is part of the framework. 
System.Json is quite old and probably doesn't work well with .net 8.

**Comment by FANMixco** [comment]
> @FANMixco My guess is you really want to be using `System.Text.Json` which is part of the framework. System.Json is quite old and probably doesn't work well with .net 8.

I was able to fix it with a code like this one:

```csharp
 var jsonDocument = await JsonDocument.ParseAsync(stream);
 var jsonString = jsonDocument.RootElement.ToString();
 var responseJson = JsonSerializer.Deserialize<MyObject>(jsonString);
````
