### ISSUE TITLE
Trimming still seems to break android push notifications on MAUI .net 9 preview 3 

### ISSUE THREAD

**Issue by marleenenjaspertrouwen** [xamarin/xamarin-android#8939]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 2022 17.10.0 preview 7

### Description

The tags might be wrong, I'm a bit confused with all the frameworks.

Point is: @jonathanpeppers suggested to create a new issue here if the issue still persisted on .net 9 preview 3. As far as I'm aware it has been an issue at least since .net 7, but also very likely .net 6.

_Originally posted by @jonathanpeppers in https://github.com/xamarin/xamarin-android/issues/5652#issuecomment-2010266232_        
Also mentioned in https://github.com/dotnet/maui/issues/16014
And at least some people seem to be affected here https://github.com/dotnet/maui/discussions/19900

### Steps to Reproduce

1. Create project in .net 9 preview 3
2. Add firebase push notification support via Xamarin.Firebase.Messaging" Version="123.3.1.1", google-services.json, etc.
3. Create a channel with priority max or high, ask for permission to send notifications
5. Build project in release mode, setting PublishTrimmed to true (and AOT on or off, no difference)
6. Deploy it to Android device
7. Launch application
8. Send notification via Firebase Console with application open, specifying the channel
9. Notification does not arrive

### Did you find any workaround?

Set PublishTrimmed to False or running in debug mode fixes the issue immediately: Then the notification does arrive.

Also one odd thing: When the application is in the background, sending a notification via the Firebase console does pop up. 
(But if it's sent as a Data message instead, the FirebaseMessagingService does not pick it up in foreground nor background. That is also fixed by using non-trimming or debug)

Maybe there's something I completely don't understand about Android notifications in MAUI, but the way I understand it, Debug should behave like Release mode in these cases right? And Non-trimmed vs Trimmed in Release mode too?

### Relevant log output

There is no log output. No unhandled exceptions. Nothing appears to happen when the notification is supposed to arrive.

**Comment by jkommeren** [comment]
Also, there is plenty of evidence people seem to be accepting "turning off trimming" as a "solution". But that's not how it should be right?

At least document what the is wrong. It took me weeks to figure out this workaround. I imagine many people giving up at some point.

https://stackoverflow.com/questions/76045900/net-maui-why-would-push-notifications-not-work-the-same-after-publishing

https://github.com/xamarin/xamarin-android/issues/5652

**Comment by marleenenjaspertrouwen** [comment]
Created under wrong account :D moved it here https://github.com/xamarin/xamarin-android/issues/8940
