### ISSUE TITLE
Incorrect enum ApplicationExitInfoReason

### ISSUE THREAD

**Issue by rgroenewoudt** [xamarin/xamarin-android#9000]
### Android framework version

net8.0-android

### Affected platform version

VS2022 17.10.1

### Description

The enum `Android.App.ApplicationExitInfoReason` contains value `Other` but it has the incorrect numeric value.

Defined with value 10:
```
[IntDefinition("Android.App.ApplicationExitInfo.ReasonOther", JniField = "android/app/ApplicationExitInfo.REASON_OTHER"), SupportedOSPlatform("android30.0")]
Other = 10, // 0x0000000A
```
which is duplicate with:
```
[IntDefinition("Android.App.ApplicationExitInfo.ReasonUserRequested", JniField = "android/app/ApplicationExitInfo.REASON_USER_REQUESTED"), SupportedOSPlatform("android30.0")] 
UserRequested = 10, // 0x0000000A
```

[According to Android documentation it should be value 13](https://developer.android.com/reference/android/app/ApplicationExitInfo#REASON_OTHER)

We noticed this we have a lot of ApplicationExitInfo records with value '13' instead of a pretty enum name.

**Comment by jpobst** [comment]
Wrote a quick script to compare `map.csv` to `api-34.xml` to find all instances where our enum values do not match what is actually in API-34:

```
android/app/ActivityManager$RunningAppProcessInfo.IMPORTANCE_PERCEPTIBLE 230 != 130 [API-10]
android/app/ActivityManager$RunningAppProcessInfo.IMPORTANCE_TOP_SLEEPING 325 != 150 [API-23]
android/app/ApplicationExitInfo.REASON_OTHER 10 != 13 [API-30]
android/content/pm/PermissionInfo.PROTECTION_MASK_FLAGS 65520 != 240 [API-16]
android/net/http/SslError.SSL_MAX_ERROR 6 != 4 [API-10]
android/view/animation/Transformation.TYPE_ALPHA 1 !=  [API-10]
android/view/animation/Transformation.TYPE_BOTH 3 !=  [API-10]
android/view/animation/Transformation.TYPE_IDENTITY 0 !=  [API-10]
android/view/animation/Transformation.TYPE_MATRIX 2 !=  [API-10]
```
